#+AUTHOR: Robin Heinemann
#+TITLE: Theoretische Physik III (Schäfer)

#+INCLUDE: "../header.org" :minlevel 1

#+LATEX_HEADER:	\renewcommand\raggedpart\centering
#+LATEX_HEADER:	\renewcommand\thepart{\Alph{part}}
#+LATEX_HEADER:	\renewcommand\thesection{\thepart.\arabic{section}}
#+LATEX_HEADER:
#+LATEX_HEADER:	\renewcommand*{\partheadstartvskip}{%
#+LATEX_HEADER:	\pagebreak\thispagestyle{empty}\vspace*{\fill}\begin{center}
#+LATEX_HEADER:	}
#+LATEX_HEADER:	\renewcommand*{\partheadmidvskip}{%
#+LATEX_HEADER:	\par\nobreak
#+LATEX_HEADER:	}
#+LATEX_HEADER:	\renewcommand*{\partheadendvskip}{%
#+LATEX_HEADER:	\end{center}\vfill\newpage
#+LATEX_HEADER:	}
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER:	\let\oldpart\part
#+LATEX_HEADER: \renewcommand{\part}{\setcounter{section}{0}\oldpart}
#+LATEX_HEADER: \makeatother
#+LATEX_HEADER:	\setlength{\cftsecnumwidth}{2em}

# Klausurzulassung: 60% der Punkte der Übungsaufgaben
# Klausur 8.2
# Nachklausur 15.2 lol, wird /vielleicht/ noch geändert

# Modalitäten
# -----------
# 60% der Punkte
# 2×vorrechnen
# Aufgaben mit Stern sind Zusatzaufgaben
# paarweise	abgeben
# nur ganze Punkte
# übliches bla bla

# Elektrodynamik
# --------------
# Einleitung
# Inhalt:
# Phänomenologie der Maxwell-Gleichungen
#  Maxwell-Gleichungen, differentielle+integrale Formulierung, Ladungserhaltung, Dynamik in Materie, Potentiale
# Potenzialtheorie
#  Poisson-Gleichung, Punktquellen+Suerposition, Green-Theoreme, Multipol-Entwicklung
# Dynamik des elektromagnetischen Felds
#  elektromagnetische Wellen, Polarisation, Wellengleichung, Energie + Impulstransport, Hertz-Dipol
# Lorentz-Geometrie + spezielle Relativitätstheorie
#  Lorentz-Transformation, relativistische Effekte, Raumzeit-Diagramme, kovariante Formulierung der Elektrodynamik
# relativistische Feldtheorie
#  Axiome der Elektrodynamik, Bianchi-identität, Dualität, Variationsprinzipien
# Bewegung von Ladungen
#  minimale Kopplung, Variation+Bewegungsgleichungen, geometrische Interpretation der Lagrangefunktion

\part{Phänomenologie der Maxwell-Gleichungen}
* elektrisches Feld
  #+begin_export latex
  \catcode`(=12
  \catcode`)=12
  \begin{center}
  \begin{tikzpicture}
  \node[draw, circle, left] (q1) at (0,0) {$q_1$};
  \node[draw, circle, left] (q2) at (2,0) {$q_2$};
  \draw[->] (-1,-2)	-- (q1) node[above left,midway] {$\v r_1$};
  \draw[->] (-1,-2)	-- (q2) node[below,midway] {$\v r_2$};
  \end{tikzpicture}
  \end{center}
  \begin{align*}
  F &= k \frac{q_1 q_2}{\abs{\v r_1 - \v r_2}^2} \\
  k &= \frac{1}{4 π ε_0} \\
  ε_0 &= \SI{8654e-12}{\ampere\second\per\volt\meter} \simeq \frac{1}{4π \num{9e9}}\si{\ampere\second\per\volt\meter}
  \end{align*}
  im SI-System.
  \catcode`(=\active
  \catcode`)=\active
  #+end_export
  \[q \to \frac{q}{\sqrt{4πε_0}} \to k = 1, F = \frac{q_1 q_2}{\abs{\v r_1 - \v r_2}^2}\]
  $q$ wird gemessen in $\sqrt{\si{\erg\centi\meter}} = \SI{1}{\esu}$ "elektrostatic unit".
* elektrische Feldstärke
  \[\v E(\v r) = \frac{\v F(\v r)}{q}\]
  \begin{attention}
  viele Bücher verlangen:
  \[\v E(\v r) = \lim_{Δq \to 0} \frac{Δ\v F}{Δq}\]
  dies ist nicht notwending $\to$ Linearität der Elektrodynamik
  \end{attention}
  analog: Lorentz-Kraft auf bewegte Ladungen $\to$ magnetische Felder
* Maxwell-Gleichungen
  $\to$ axiomatisch für die Elektrodynamik. Verbindung zwischen Ladungsdichte $ρ$, elektrischen Stromdichte $\v j$ und den Feldern $\v E, \v D, \v H$ und $\v B$.
  In einem Inertialsystem nehmen die Maxwell-Gleichungen diese Form an:
  1. $\Div \v E = ∇ · \v E = 4π ρ$ Gesetz von Grauß. \\
	 elektrische Ladungen sind Quellen des elektrischen Feldes
	 \[∫_V \d^3 r \Div \v E \overarrow[=]{Satz von Gauß} ∫_{\partial V} \d \v S \v E = \underarrow[ψ]{el. Fluss} = ∫_v \d^3 r 4 π ρ = 4 π \overarrow[q]{eingschl. Ladung}\]
  2. $\Div \v B = ∇ \v B = 0$ \\
	 \[∫_v \d^3 r \Div \v B = ∫_{\partial V} \d \v S \v B = ϕ = 0\]
  3. $\rot \v E = ∇ × \v E = \underarrow[-]{Lenz.-Regel.} \partial_{ct} \v B$ Faraday-Induktionsgesetz. \\
	 \[\partial_{ct} = \pp{}{(ct)} = \frac{1}{c} \pp{}{t}\]
	 \[∫_S \d \v S · \rot \v E = \underbrace{∫_{\partial S} \d \v r \v E}_{U} = -\dd{}{(ct)} \underbrace{∫_s \d \v S · \v B}_{ϕ}\]
  4. $\rot \v B = ∇ × \v B = \partial_{ct} \v E + \frac{4π}{c} \v j$ \\
	 \[∫_s \d \v S \rot \v B = ∫_{\partial S} \d \v r \v B = \frac{d}{(ct)} \underbrace{∫_S \d \v S \v E}_{ψ} + \frac{4π}{c} \underbrace{∫_S \d \v S \v j}_{I}\]
* Eigenschaften der Maxwell-Gleichungen
  - zwei skalare und zwei vektoriell Gleichungen
  - lineare, partielle Differenzialgleichungen erster Ordnung
  - für vorgegebene	$ρ$ und $\v j$ lassen sich $\v E$ und $\v B$ berechnen
  - *oder* aus einer Feldkonfiguration $\v E$ und $\v B$ lassen sich Ladungen $ρ$ und $\v j$ finden
  - Maxwell-Gleichungen gelten in einem Inertialsystem: erst die Definitonen aus Bezugssystem bestimmt, was $ρ$ und $\v j$ ist, und damit $\v E$ und $\v B$ \\
	darüber hinaus ist mit Wahl des Systems klar, was xvolt ist, und damit $\partial_{ct}$ und $∇$.
  - nur eine Skala enthalten: $c \sim$ Lichtgeschwindigkeit
  - im Vakuum: $ρ = 0, \v j = 0$: $ε = 1 = μ \to \v D = \v E, \v H = \v B$.
  	\begin{align*}
    \Div \v E &= 0 \\
    \Div \v B &= 0 \\
    \rot \v E &= -\partial_{ct} \v B \\
    \rot \v B &= -\partial_{ct} \v E \\
    \end{align*}
    Wenn man $\v E \to \v B, \v B \to -\v E$ vertauscht, dann ändern sich die Gleichungen nicht $\to$ *elektromagnetische Dualität*.
  - seltsame Asymmetrie, es gibt kein $ρ_{\text{mag}}$ oder $\v j_{\text{mag}}$
	\begin{align*}
	\Div \v B &= 4 π ρ_{\text{mag}} = 0 \\
	\rot \v E &= -\partial_{ct} \v B + \underbrace{\frac{4π}{c} \v j_{\text{mag}}}_{= 0}
    \end{align*}
* Erhaltung der elektrischen Ladung
  \begin{align*}
  \rot \v B &= \partial_{ct} \v E + \frac{4π}{c} \v j \\
  \Div\rot \v B &= ε_{ijk} \partial_i \partial_j B_k = 0 = \partial_{ct} \underbrace{\Div \v E}_{=4πρ} + \frac{4π}{c} \Div \v j \\
  &= \frac{4π}{c}(\partial_t ρ + \Div \v j) \\
  ⇒ \partial_t ρ + \Div \v j &= 0 \tag{Kontinuitätsgleichung}
  \intertext{Aus der Kontinuitätsgleichung folgt die Ladungserhaltung}
  ∫_V \d^3 r \partial_t ρ &= \dd{}{t} \underbrace{∫_V \d^3 r ρ}_{q} = -∫_V \d^3 r \Div \v j = -∫_{\partial V} \d \v S · \v j
  \end{align*}
  - Änderung der Ladung in einem Volumen = Fluss der Ladung durch die Oberfläche.
  - Dynamik der Felder ist konsistent zur Bewegung der Ladungen
  - gilt auch in Materie! Ampere-Gesetz und Gauß-Gesetz enthalten falls $ε \neq 1$ die dielektrische Verschiebung $\v D$.
  -	es existiert implizit eine zweite Erhaltungsgleichung für die magnetische Ladungen, die nicht existieren.
	$2(1 + 3)$ Maxwell-Gleichungen für $2·2·3$ Felder!
* Elektrodynamik in Materie
  Wechselwirkungen zwischen dem elektromagnetischen Feld und Materie ist *sehr* kompliziert im Mikroskopischen
  $\to$ in vielen Fällen ist es trotzdem möglich, mit zwei Konstatnen eine einfach *effektive* Beschreibung zu finden.
  - $ε$: Dielektrizitätskonstante $\to \v D = ε \v E$
  -	$μ$: Permeabilitätskonstante $\to \v B = μ \v H$
  Im Vakuum: $ε = 1, μ = 1$, in Materie: $ε \neq 1, μ \neq 1$
  \begin{equation*}
  \begin{aligned}
  \text{im Vakuum} \\
  \Div \v E &= 4πρ \\
  \Div \v B &= 0 \\
  \rot \v E &= - \partial_{pt} \v B \\
  \rot \v B &= \partial_{ct} \v E + \frac{4π}{c} \v j
  \end{aligned}
  \qquad\qquad
  \begin{aligned}
  \text{in Materie} \\
  \Div \v D &= 4πρ \\
  \Div \v B &= 0 \\
  \rot \v E &= - \partial_{pt} \v B \\
  \rot \v H &= \partial_{ct} \v D + \frac{4π}{c} \v j
  \end{aligned}
  \end{equation*}
  (wir brauchen noch zwei Konzepte, Dipolfelder und das elektrische Potenzial um ein Modell für $ε$ aufstellen zu können).
* elektrisches Potenzial $\to$ Elektrostatik
  #+begin_export latex
  \begin{minipage}{.45\linewidth}
  \begin{align*}
  \v E(\v r) &= q_1 \frac{\v r - \v r_1}{\abs{\v r - \v r_1}^3} \\
  \v E(\v r) &= \sum_{i} q_i \frac{\v r - \v r_i}{\abs{\v r - \v r_i}^3} \\
  \end{align*}
  (Definiton: Probeladung ist positiv $\to$ abstoßende Coulomb-Kraft falls $q_1 > 0$.)
  \end{minipage}
  \hfill%
  \catcode`(=12
  \catcode`)=12
  \begin{minipage}{.45\linewidth}
  \begin{center}
  \begin{tikzpicture}
  \node[draw, circle, left] (q1) at (0,0) {$q_1$};
  \node[draw, circle, left] (q2) at (2,0) {$q_2$};
  \draw[->] (-1,-2)	-- (q1) node[above left,midway] {$\v r_1$};
  \draw[->] (-1,-2)	-- (q2) node[above left,midway] {$\v r_2$};
  \draw[->] (-1,-2)	-- (2.5, -.5) node[below,midway] {$\v r$};
  \node[right,every text node part/.style={align=center}] at (2.5, -.5) {Beobachter \\ mit Probeladung};
  \end{tikzpicture}
  \end{center}
  \end{minipage}
  \catcode`(=\active
  \catcode`)=\active
  #+end_export
  Superposition wegen der Linearität der Maxwell-Gleichnug. \\
  Kontinuumslimit: ersetze $q \to ρ$
  \begin{align*}
  \v E(\v r) &= ∫_V \d^3 r' ρ(\v r) \frac{\v r - \v r'}{\abs{\v r - \v r'}^3} = - ∫_V \d^3 r' ρ(\v r) ∇ \frac{1}{\abs{r - r'}} \\
  &= - ∇ \underbrace{∫_V \d^3 r' \frac{ρ(\v r)}{\abs{\v r - \v r'}}}_{=ϕ(\v r)} \\
  \to \Aboxed{\v E(\v r) &= -∇ ϕ(\v r)} \\
  ϕ(\v r) &= ∫_V \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}}
  \end{align*}
  und es gilt automatisch in diesem Fall:
  \[\rot \v E = -\rot ∇ ϕ = 0;\qquad (\rot E)_i = ε_{ijk} \partial_j \partial_k ϕ = 0\]
  Substitution in das Gauß-Gesetz:
  \begin{align*}
  \Div \v E &= 4πρ \\
  \to \Aboxed{\Laplace ϕ &= - 4πρ} \tag{Poisson-Gleichung}
  \end{align*}
  Falls keine Ladungen vorliegen, muss $\Laplace ϕ = 0$ gelten.
  \begin{align*}
  ϕ(\v r) &= \frac{1}{\abs{r - r'}} \\
  \intertext{Für Quelle mit $q = 1$ an der Stelle $\v r' = \v 0$:}
  \Laplaceϕ &= (\partial_x^2 + \partial_y^2 + \partial_z^2)ϕ \underarrow[=]{Kugelkoordinaten, Winkel fallen weg, da sie nicht in $ϕ$ vorkommen} \Laplace \frac{1}{r} = \frac{1}{r} \frac{\partial^2}{\partial r^2}(r \frac{1}{r}) = 0 \\
  \intertext{klar, bei $\v r$ ist die Ladung nicht, sondern bei $\v 0$}
  ∫_V \d^3 r \Laplaceϕ &= ∫_V \d^3 r ∇(∇ϕ) \underarrow[=]{Satz von Gauß} ∫_{\partial V} \d \v S ∇ ϕ \\
  &= ∫ r^2 \d Ω \underbrace{\pp{ϕ}{r}}_{=-\frac{1}{r^2}} = -∫ \d Ω = -4π \\
  \intertext{Zusammenfassung beider Fälle}
  \Laplace \frac{1}{\abs{\v r - \v r'}} &= -4π δ_D(\v r - \v r') \\
  \intertext{analog für Gravitation}
  \Div \v g &= 4π ρ \\
  \Laplace ϕ &= 4πGρ
  \end{align*}
* Dirac-Funktion $δ_D$
  Elektrodynamik ist eine Kontinuumstheorie $\to$ $ρ$ ist eine Ladungsdichte:
  \begin{equation*}
  ∫_V \d^3 r ρ = q\tag{im Volumen $V$}
  \end{equation*}
  $qδ_D(\v r - \v r')$ repräsentiert eine Punktladung $q$ an der Stelle $\v r'$.
  \begin{align*}
  ρ(\v r) &= \sum_{i} q_i δ_D(\v r - \v r_i) \\
  ϕ(\v r) &= ∫ \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}} \\
  \intertext{denn}
  \Laplace ϕ(\v r) &= ∫ \d^3 r' ρ(\v r') \Laplace \frac{1}{\abs{\v r - \v r'}} = ∫ \d^3 r'ρ(\v r') (-4π) δ_D(\v r - \v r') \\
  \Laplace ϕ(\v r) &= -4π σ(\v r) \tag*{Poisson-Gleichung} \\
  \intertext{im diskreten Fall:}
  ϕ(\v r) &= \sum_{i} \frac{q_i}{\abs{\v r - \v r_i}} \\
  \Laplace ϕ(\v r) &= \sum_{i} q_i \Laplace \frac{1}{\abs{\v r - \v r'}} = \sum_{i} q_i (-4π) δ_D(\v r - \v r_i) \\
  &= -4π \sum_{i} q_i σ_D(\v r - \v r') = -4π ρ(\v r)
  \end{align*}
* potenzielle Energie und das elektrostatische Potenzial
  \begin{attention}
  bitte seid super vorsichtig mit Energieinterpretationen von allem, was mit Relativität zutun hat!
  \end{attention}
  Coulomb-Kraft $\v F$:
  \[\v F(\v r) = q \v E(\v r)\]
  Verschiebearbeit $W$:
  \begin{align*}
  W &= ∫_A^B \d \v r · \v F = -q ∫_A^B \d \v r \v E \underarrow[=]{$\v E = - ∇ϕ$} g ∫_A^B \underbrace{\d \v r ∇ ϕ}_{= \pp{}{\v r}ϕ} \\
  \intertext{mit $\d \v r · \pp{}{\v r}ϕ = \d ϕ$ (totales Differenzial)}
  W &= q ∫_A^B \d ϕ = q(ϕ(B) - ϕ(A))
  \end{align*}
  - Potenzialdifferenz entspricht der Verschiebearbeit pro Ladung
  -	Verschiebung muss extrem langsam erfolgen, dass $E \to B$ nicth transformiert (Lorentz!)
* Eigenschaften der \(δ_D\)-Funktion
  \begin{align*}
  \intertext{Normierung}
  ∫ \d^n x δ_D(x) &= 1 \\
  \intertext{Lokalisierung}
  ∫ \d^n x g(x) δ_D(x - y) &= g(y) \\
  ∫_a^b \d x δ_D(x - c) &= \begin{cases} 1 & a \leq c \leq b \\ 0 & \text{sonst} \end{cases} \\
  \intertext{Durch Substitution}
  ∫ \d x δ_D(a x) &= \frac{1}{a} \\
  \intertext{Durch partielle Integration}
  ∫ \d x g(x) δ_D'(x - a) &= g(x) δ_D(x - a) \Big|_{-∞}^{+∞} - ∫ \d x g'(x) δ_D(x - a) \\
  &= 0 - g'(a)
  \end{align*}
* Feldänderung an einer Oberfläche
  Betrachte Oberfläche mit Oberflächenladung $σ$
  \[σ = \lim_{ΔS \to 0} \frac{Δq}{ΔS}\]
  wie wird ein elektrischen Feld durch diese Oberfläche beeinflusst? (vor Oberfläche: $\v E_1$, nach Oberfläche $\v E_2$) \\
  Dazu wählen Zylinder mit den Mantelflächen parallel zur Oberfläche und Volumen $ΔV$ und, dass der elektrische Full durch die Seitenwände sehr klein ist und nicht zum Integral beiträgt.
  \begin{align*}
  ∫_{ΔV} \d^3 r' \Div \v E &\underarrow[=]{Gauß} ∫_{ΔS} \d \v S · \v E = 4π q = 4π \overbrace{∫_{\partial V} \d \v S σ}^{ΔS · σ} = ΔS(E_2^{\perp} - E_1^{\perp}) \\
  ⇒ E_2^{\perp} = E_1^{\perp} + 4πσ
  \end{align*}
  Wenn das Feld tangential zur Oberfläche ist, kann man stattdessen eine Schleife wählen und den Satz von Stokes benutzen:
  \[∫_{\partial} \d \v r \v E \underarrow[τ]{Stokes} ∫_S \d \v S \rot \v E = (E_2^{\parallel} - E_1^{\parallel}) Δr \to E_2^{\parallel} = E_1^{\parallel}\]
  Außerdem: $\v E = -∇ ϕ ⇒ \rot \v E = - \rot ∇ ϕ = 0$.
* Energie einer	statischen Ladungsverteilung
  \begin{attention}
  Energie + Relativitätstheorie: supervorsichtig!
  \end{attention}
  \begin{tabular}{cccl}
  1. & $q_1$ an einer Stelle $\v r_1$ & $\to$ & Potential $ϕ_1 = \frac{q_1}{\abs{\v r - \v r_1}}$ \\
  2. & $q_2$ an einer Stelle $\v r_2$ & $\to$ & $W_2 = q_2 · ϕ_1(\v r_2)$ \\
  3. & $q_3$ an einer Stelle $\v r_3$ & $\to$ & $W_3 = q_3 · (ϕ_1(\v r_2) + ϕ_2(\v r_3))$ \\
  \vdots & & & \\
  n. & $q_n$ an einer Stelle $\v r_n$ & $\to$ & $W_n = q_n · \sum_{i}^{n - 1} ϕ_i(\v r_n)$ \\
  \end{tabular}
  Man erkennt
  \begin{align*}
  W &= \sum_{n}^{N} W_n = \sum_{n}^{N} q_n \sum_{i}^{n - 1} ϕ_i(\v r_n) \\
  W &= \sum_{n}^{N} q_n \sum_{i}^{n - 1} \frac{q_1}{\abs{\v r_1 - \v r_n}} = \underarrow[\frac{1}{2}]{Korrektur der doppelten Zählung} \sum_{n}^{N} \sum_{\substack{i\\i\neq n}}^{N} \frac{q_i q_n}{\abs{\v r_1 - \v r_n}}
  \end{align*}
  Kontinuums-Limes
  \begin{align*}
  \sum_{i} q_i &\to ∫ \d^3 r' ρ(\v r') \\
  W &= \frac{1}{2} ∫\d^3 r ∫ \d^3 r' \frac{ρ(\v r) ρ(\v r')}{\abs{\v r - \v r'}} = \frac{1}{2} ∫ \d^3 r ρ(\v r) \underbrace{∫\d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}}}_{=ϕ(\v r)} \\
  &= \frac{1}{2} ∫ \d^3 r ρ(\v r) ϕ(\v r) \\
  W &\underarrow[=]{Poisson-Gleichung $\Laplace ϕ = - 4π ρ$} -\frac{1}{8π} ∫\d^3 r \Laplace ϕ ϕ = - \frac{1}{8π} ∫\d^3 r^3 ϕ \Laplace ϕ  \\
  \intertext{Es gilt: $ϕ \Laplace ϕ = ϕ ∇·(∇ϕ) = ∇(ϕ ∇ ϕ) - ∇ϕ∇ϕ$}
  W &= -\frac{1}{8π} ∫ \d^3 r ∇(ϕ∇ϕ) + \frac{1}{8π} ∫ \d^3 r (∇ ϕ)^2 \\
  &= -\frac{1}{8π} ∫ \d \v S (ϕ ∇ ϕ) + \frac{1}{8π} ∫ \d^3 r \underbrace{(∇ ϕ)^2}_{\v E = - ∇ ϕ} \\
  \intertext{Satz von Gauß: $∫ \d \v S (ϕ ∇ ϕ) = 0$ für große Volumen, da typischerweise $ϕ \sim 1/r$, $∇ϕ \sim 1/r^2 ⇒ ϕ ∇ ϕ \sim 1/r^3$, aber $\d \v S \sim r^2$} \\
  W &= \frac{1}{8π} ∫\d^3 r E^2
  \end{align*}
  Energiedichte des elektrischen Felds:
  \[ρ_{el} = \frac{\v E^2}{8π}\]
  \begin{attention}
  Selbstenergie für \(\v r' = \v r\)- keine Lösung in der klassischen Elektrodynamik.
  \end{attention}


\part{Potentialtheorie}
Lösungen der Poisson-Gleichung $\Laplace ϕ = - 4πρ$.
3 Probleme
1. Inversion des Differenzialoperators $\to$ Green-Funktion
2. Geometrie der Ladungsverteilung $\to$ Multipolentwicklung
3. Randbedingungen $\to$ Green-Theorie
* Green-Theoreme
  Es gilt für $\v A(\v r) = φ ∇ ψ$
  \begin{align*}
  \Div \v A - \Div(φ ∇ ψ) = ∇φ∇ψ + φ \Laplace ψ
  \intertext{Satz von Gauß:}
  ∫_V \d^3 \Div \v A &= ∫_{\partial V} \d \v S \v A \\
  \intertext{$\v S = \d S \v n, \v n \sim$ Normalenvektor} \\
  ∫_V \d^3 r'(∇' φ ∇' ψ + φ \Laplace' ψ) &= ∫_{\partial V} \d S φ ∇' ψ · \v n = ∫_{\partial V} \d S φ \pp{ψ}{n} \tag*{Erste greensche Identität} \\
  \intertext{$φ \rightleftharpoons ψ$ und Subtraktion der Gleichungen}
  ∫_V \d^3 r'(φ \Laplace' ψ - ψ \Laplace' φ) &= ∫_{\partial U} \d S (φ \pp{ψ}{n} - ψ \pp{ϕ}{n}) \tag*{Zweite greensche Identität}
  \end{align*}
  Wahl der Funktionen
  \begin{align*}
  ψ &= \frac{1}{\abs{\v r - \v r'}} \\
  φ &= ϕ(\v r') \tag*{elektrostatisches Potential} \\
  ⇒ \Laplace' ψ &= \Laplace' \frac{1}{\abs{\v r - \v r'}} = -4π δ_D(\v r - \v r') \\
  \Laplace' φ &= \Laplace ϕ = -4π ρ(\v r')
  -4π ∫_V \d^3 r' ϕ(\v r) δ(\v r - \v r') + 4π ∫_V \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}} \\
  &= ∫_{\partial V} \d S' ϕ(\v r') \pp{}{n'} \frac{1}{\abs{\v r - \v r'}} - \frac{1}{\abs{\v r - \v r'}} \pp{}{n'} ϕ(\v r') \\
  \intertext{Falls $\v r$ innerhalb von $V$ liegt:}
  ∫_V \d^3 r' ϕ(\v r') δ_D(\v r - \v r') &= ϕ(\v r) \\
  ⇒ ϕ(\v r) &= \underbrace{∫_V \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}}}_{\mathclap{\text{Potenzial aus}\atop\text{der Ladungsverteilung}}}  + \frac{1}{4π} ∫_{\partial V} \d S'\Big{\string(}\overbrace{\frac{1}{\abs{\v r - \v r'}} \pp{}{n'}ϕ}^{\mathclap{{{\text{Neumann-}}\atop{\text{Raundbedingungen}}}\atop{\pp{ϕ}{n} \text{ auf } \partial V}}} - \underbrace{ϕ(\v r') \pp{}{n'} \frac{1}{\abs{\v r - \v r'}}}_{\mathclap{{\text{Dirichlet-}\atop\text{Randbedingung}}\atop{ϕ\text{ auf }\partial V}}}\Big{\string)}
  \end{align*}
  $\partial V$ unendlich weit weg:
  \begin{align*}
  \frac{1}{\abs{\v r - \v r'}} \pp{}{n}ϕ &\sim \frac{1}{r^3} \to 0 \\
  ϕ \pp{}{n} \frac{1}{\abs{\v r - \v r'}} &\sim \frac{1}{r^3} \to 0
  \end{align*}
  $⇒$ nur der erste Term bleibt übrig:
  \[ϕ(\v r) = ∫_V \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}}\]
  $ρ(\v r) = 0$ innerhalb von $V$: $ϕ$ bestimmt durch $ϕ$ und $\pp{ϕ}{n}$ auf der Oberfläche $\partial V$.
* Eindeutigkeit des Potenzials
  #+begin_thm latex
  Potenzial $ϕ$ ist eindeutig mit der Vorgabe von Dirichlet *oder* Neumann-Randbedingungen.
  #+end_thm
  #+begin_proof latex
  Annahme für Widerspruchsbeweis: 2 Potenziale $ϕ_1(\v r)$ und $ϕ_2(\v r)$, beide Lösungen der Poisson-Gleichnug:
  \begin{align*}
  \begin{rcases*}
  \Laplace ϕ_1 = -4π ρ \\
  \Laplace ϕ_2 = -4π ρ \\
  \end{rcases*}
  \Laplace\underbrace{(ϕ_1 - ϕ_2)}_{U} &= 0
  \intertext{Randbedingungen:}
  ϕ_1 \big|_{\partial V} &= ϕ_2 \big|_{\partial V} \\
  \pp{ϕ_1}{n} \big|_{\partial V} &= \pp{ϕ_2}{n} \big|_{\partial V} \\
  \end{align*}
  1 Green-Theorem mit $U = ϕ_1 - ϕ_2$ und $φ = ψ = U$
  \begin{align*}
  ∫_V \d^3 r'\string(\underbrace{U \Laplace' U}_{= 0} + (∇' U)^2\string) &= ∫_{\partial V} \d S U \pp{U}{n} \\
  \intertext{wenn $n = 0$ (Dirichlet) oder $\pp{U}{n'}$ (Neumann)}
  ∫_{\partial V} \d S U \pp{U}{n} &= 0 \\
  ⇒ ∫_V \d^3 r'(∇' U)^2 &= 0
  \end{align*}
  $⇒ U$ ist konstant un $V$, $ϕ_1 = ϕ_2 + \const$. Die Potenziale unterscheiden sich nur um eine additive Konstante.
  #+end_proof
* Green-Funktion $\to$ Potenzial einer Punktladung
  Potenzial einer Punktladung:
  \[\Laplace \underbrace{\frac{1}{\abs{\v r - \v r'}}}_{\mathclap{\text{Green-Funktion von } \Laplace}} = -4π δ_D(\v r - \v r')\]
  Verallgemeinerung:
  \begin{align*}
  \Laplace G(\v r, \v r') &= -4π δ_D(\v r - \v r') \\
  \text{mit } G(\v r, \v r') &= \frac{1}{\abs{\v r - \v r'}} + \underbrace{F(\v r, \v r')}_{\Laplace F(\v r, \v r') = 0} \\
  \intertext{$F(\v r, \v r')$ erfüllt die vakuum-Feldgleichngug $\Laplace F = 0\to F$ kann benutzt werden, um Randbedingungen zu erfüllen. "Spiegelladungen", Superpositionsprinzip (Elektrodynamik ist linear)}
  \Laplace G(\v r, \v r') &= \Laplace \frac{1}{\abs{\v r - \v r'}} = -4π δ_D(\v r - \v r') \\
  ⇒ ∫ \d^3 r' \Laplace G(\v r, \v r') ρ(\v r') &= \Laplace ∫ \d^3 r' G(\v r, \v r') ρ(\v r') \\
  &= \Laplace ∫ \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}} \\
  &= \Laplace ϕ = -4π ∫ \d^3 r' δ_D(\v r - \v r') ρ(\v r') \\
  &= -4π ρ(\v r) \\
  ⇒ ϕ &= ∫ \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}} \text{ invertiert } \Laplace ϕ = -4πρ
  \end{align*}
  Konstruktion von Green-Funktionen im Fourier-Raum
  \begin{align*}
  \Laplace ϕ(\v r) &= -4π ρ(\v r) \to \text{Fourier-Transformation (Poisson-Gleichnug ist linear)} \\
  \Laplace ϕ(\v r) &= \Laplace ∫ \d^3 k ϕ(\v k) \exp(i \v k \v r) = ∫ \d^3 k ϕ(\v k) \Laplace \exp(i \v k \v r) \\
  &= ∫ \d^3 k ϕ(\v k) (i \v k)^2 \exp(i \v k \v r) = -4π ∫ \d^3 k ρ(\v k) \exp(i \v k \v r) \\
  ⇒ (i \v k)^2 ϕ(\v k) &= -k^2 ϕ(\v k) = -4π ρ(\v k) \\
  ⇒ ϕ(\v k) &= \frac{4π}{k^2}ρ(\v k)
  \end{align*}
  #+begin_export latex
  \catcode`(=12
  \catcode`)=12
  #+end_export
  \begin{figure}[H]
  \centering
  \begin{tikzpicture}
  \matrix (m) [matrix of math nodes, row sep=4em, column sep=5em, minimum width=3em] {ρ(\v k) & ϕ(\v k) \\ ρ(\v r) & ϕ(\v r)\\};
  \path[-stealth]
  (m-1-1) edge node [above] {$-\frac{1}{k^2}$} (m-1-2)
  (m-1-2) edge node [right] {$\mathcal{F}^{-1}$} (m-2-2)
  (m-2-2) edge node [above] {$\Laplace$} (m-2-1)
  (m-2-1) edge node [left] {$\mathcal{F}$} (m-1-1);
  \end{tikzpicture}
  \end{figure}
  #+begin_export latex
  \catcode`(=\active
  \catcode`)=\active
  #+end_export
  für numerische Berechnungen ist es extrem	vorteilhaft, die Fourier-Methode zu benutzen $\to$ "Fast-Fourier-Transform (FFT)". \\
  Faltung der Ladungsverteilung mit der Green-Funktion $\to$ Multiplikation im Fourier-Raum.
  \[ϕ(\v r) = ∫ \d^3 r' \underarrow[G(\v r, \v r')]{$\displaystyle{\frac{1}{\abs{\v r - \v r'}}}$ für $\Laplace$} ρ(\v r') \to ϕ(\v k) = \underarrow[G(\v k)]{$\displaystyle{-\frac{1}{k^2}}$} ρ(\v k)\]
  Bestimmung von Green-Funktionen aus dem Differenzialoperator.
  \begin{align*}
  \Laplace G(\v r, \v r') &= -4π δ(\v r - \v r') \to \text{ Fourier-Transformation} \\
  \Laplace G(\v r, \v r') &= ∫ \d^3 k G(k) \underbrace{\Laplace \exp(i \v k(\v r - \v r'))}_{\mathclap{= (i \v k)^2 = - k^2 \to G(k) = - \frac{1}{k^2}}} = 4π ∫ \d^3 k \exp(i \v k(\v r - \v r')) \\
  G(\v r, \v r') &= ∫ \d^3 k G(k) \exp(i\v k \v r) ∫ \d^3 k (-\frac{1}{k^2}) \exp(i \v k \v r) \text{ mit } \v r' =	\v 0 \\
  &= ∫ k^2 \d k ∫ \sin θ \d θ ∫ \d φ \frac{1}{k^2} \exp(i k r \cos θ) = 2π ∫ \d k ∫_{-1}^{+1} \d μ \exp(i k r μ) \\
  &= 2π ∫ \d k \sinc(k r) = \frac{2π}{r} ∫ \d y \sinc(y) \\
  &= \frac{1}{r}
  \end{align*}
* Multipolentwicklung
  Idee: Von "weit weg" sieht man nur sphärische Ladungsverteilung. Also zerlege Potenzial in sphärischen Anteil und kleine Korrekturen.
  #+begin_export latex
  \catcode`(=12
  \catcode`)=12
  \begin{center}
  \begin{tikzpicture}
  \wigglecircle{.75}{.25}{20}{0}{0}
  \node at (0,.4) {$ρ(\v r)$};
  \draw[->] (-1,-1) --++(1,1) node[midway,above] {$\v r'$};
  \draw[->] (-1,-1) --++(4,1) node[midway,below] {$\v r$};
  \filldraw (-1,-1) circle (1pt);
  \filldraw (3,0) circle (1pt);
  \draw[domain=15:45,smooth,shift={(-1,-1)}] plot ({.5*cos(\x)},{.5*sin(\x)});
  \node[below right,yshift=3pt] at (-1,-1) {$α$};
  \end{tikzpicture}
  \end{center}
  \catcode`(=\active
  \catcode`)=\active
  #+end_export
  \begin{align*}
  ϕ(\v r) &= ∫ \d^3 r' \frac{ρ(\v r)}{\abs{\v r - \v r'}} \\
  \frac{1}{\abs{\v r - \v r'}} &= \frac{1}{\sqrt{r^2 - 2r r' \cos α + r^2}} \\
  \intertext{mit $μ\cos α$:}
  &= \frac{1}{r} \frac{1}{\sqrt{1 - 2 \frac{r'}{r}μ + (\frac{r'}{r})^2}} \overarrow[=]{Annahme $r > r'$, $\v r$ ist weit weg von der Ladungsverteilung an $\v r'$} \frac{1}{r}(\mathcal{P}_0(μ) + \frac{r'}{r} \mathcal{P}_1(μ) + (\frac{r'}{r})^2 \mathcal{P}_2(μ) + \dots) \\
  &= \sum_{l = 0}^{∞} \frac{r^{l + 1}}{r^{\prime l}} \mathcal{P}_l (μ) \\
  \intertext{$\mathcal{P}_l \sim$ Legendre Polynome, erzeugende Funktion:}
  \frac{1}{\sqrt{1 - 2z x + z^2}} &= \sum_{l} \mathcal{P}_l(x) z^l = \mathcal{P}_0(x) + \mathcal{P}_1(x) z + \mathcal{P}_2(x) z^2 + \dots \\
  \intertext{Durch sukksesives Differenzieren kann man durch auswerten an $z = 0$ die $\mathcal{P}_l$ bestimmen:}
  ⇒ \mathcal{P}_l(μ) &= \frac{1}{2^l l!} \frac{\d^l}{\d μ^l}(μ^2 - 1)^l \tag*{Formel von Rodrigues} \\
  \mathcal{P}_0(μ) &= 1 \\
  \mathcal{P}_1(μ) &= μ \\
  \mathcal{P}_2(μ) &= \frac{1}{2}(3μ^2 - 1) \\
  \mathcal{P}_3(μ) &= \frac{1}{2}(5 μ^5 - 3μ^2) \\
  \intertext{Legendre Polynome sind ein Satz orthogonaler Polynome:}
  ∫_{-1}^{+1} \d μ \mathcal{P}_l(μ) \mathcal{P}_{l'}(μ) &= \frac{2}{2l + 1} δ_{l l'} \\
  \intertext{Additionstheorem: $Y_{lm}$: spärische-harmonische Funktionen}
  \mathcal{P}_l(μ) &= \frac{4π}{2l + 1} \sum_{m = -l}^{l} Y_{lm}(θ, φ) Y_{lm}^{\ast}(θ', φ') \\
  \frac{1}{\abs{\v r- \v r'}} &= \sum_{l} \sum_{m = -l}^{+l} \frac{4π}{2l + 1} \frac{r^{\prime l}}{r^{l + 1}} Y_{lm}(θ,φ) Y^{\ast}_{lm}(θ',φ') \\
  ϕ(\v r) &= ∫\d^3 r' \frac{ρ(\v r)}{\abs{\v r - \v r'}} \\
  ⇒ ϕ(\v r) ∫ \d^3 r' \frac{ρ(\v r)}{\abs{\v r - \v r'}} &= \sum_{l = 0}^{∞} \sum_{m = -l}^{+l} \frac{4π}{2 l + 1} \frac{1}{r^{l + 1}} Y_{lm}(θ, φ) \underbrace{∫ \d^3 r' ρ(\v r ') r^{\prime l} Y^{\ast}_{lm}(θ', φ')}_{q_{lm}} \\
  \intertext{$q_{lm}$: Multipol-Moment}
  \end{align*}
  Beitrag von $q_{lm}$ zu $ϕ$ ist $\propto \frac{1}{r^{l + 1}}$ $⇒$ höhere Multipolmomente haben Beiträge nur auf kleinen Skalen.
  - Monopol: $l = 0 ⇒$ 1 Zahl, $m = 0$
	\[q_{00} = ∫ \d^3 ρ(\v r') r^{\prime 0} Y_{00}(θ',φ') = \frac{1}{\sqrt{4π}} ∫ \d^3 r' ρ(\v r') = \frac{Q}{\sqrt{4π}}\]
  - Dipol $l = 1 ⇒$ 3 Zahlen, $m = -1,0,+1$
  - Oktupol $l = 2 ⇒$ 5 Zahlen, $m = -2,-1,0,+1,+2$
  - Hexadekupol $l = 3 ⇒$ 7 Zahlen, $m = -3,-2,-1,0,+1,+2,+3$
  - \(\)-Multipol $⇒ 2l + 1$ Zahlen, von $-l$ bis $l$
  Hermitizität:
  \[Y_{lm}^{\ast} = (-1)^m Y_{lm}\]
  \begin{align*}
  ⇒ q^{\ast}_{lm} &= ∫ \d^3 r' ρ(\v r') r^{\prime l} Y_{lm}^{\ast}(θ', φ') = (-1)^m ∫ \d^3 r' ρ(\v r') Y_{l,rm}(θ,φ) \\
  q^{\ast}_{lm} &= (-1)^m q_{lm}
  \end{align*}
  Ladungsverteilung $ρ(\v r)$ ist reell $⇒$ nur $l + 1$ unabhängige Momente.
* sphärisch-harmonische Funktionen
  Lineares Funktionensystem auf der Kugel $(θ,φ)$ nach dem alle skalaren Funktionen entwickelt werden können.
  \begin{align*}
  Y_{lm}(θ, φ) &= \sqrt{\frac{2l + 1}{4π}}\sqrt{\frac{(l - m)!}{(l + m)!}} \mathcal{P}_{lm}(\cos θ) e^{i m φ} \\
  Y_{00}(θ, φ) &= \frac{1}{\sqrt{4π}} ⇒ ϕ(\v r) = \frac{Q}{r}, Q = q_{00}, l = m - 0 \\
  Y_{10}(θ, φ) &= \sqrt{\frac{3}{4π}} \cos θ \\
  Y_{11}(θ, φ) &= \sqrt{\frac{3}{8π}} \sin θ e^{i φ} \\
  \intertext{$\mathcal{P}_{lm}(\cos θ)$: assoziierte Legendre Polynome}
  \mathcal{P}_{lm}(μ) &= (-1)^m (1 - μ^2)^{\frac{m}{2}} \frac{\d^m}{\d μ^m} \mathcal{P}_l(μ) \\
  \mathcal{P}_{lm}(μ) &= \frac{(-1)^m}{2^l l!} (1 - μ^2)^{m/2} \frac{\d^{l + m}}{\d μ^{l + m}}(μ^2 - 1)^l \\
  ∫_{-1}^{+1} \d μ \mathcal{P}_{lm}(μ) P_{l'm'}(μ) &= \frac{2}{2l + 1} \frac{(l + m)!}{(l - m)!} δ_{ll'} \\
  \intertext{$⇒$ sphärisch harmonische Funktionen}
  ∫_{0}^{2π} \d φ ∫_{0}^{π} \sin θ \d θ Y_{lm}(θ,φ) Y_{l'm'}^{\ast} (θ,φ) &= δ_{ll'} δ_{mm'} \tag{Orthogonalität} \\
  \sum_{l = 0}^{∞} \sum_{m = -l}^{+l} Y_{lm}(θ,φ) Y^{\ast}_{lm}(θ',φ') &= δ_D(φ - φ')\underbrace{δ_D(\cos θ - \cos θ')}_{= δ_D(θ - θ')} \\
  \mathcal{P}_l(\cos α) &= \frac{4π}{2l + 1} \sum_{m = -l}^{+l} Y_{lm}^{\ast}(θ,φ) Y_{lm}(θ',φ') \\
  \intertext{in karthesischen Koordinaten:}
  q_{10} &= ∫\d^3 r' ρ(\v r) r' Y_{10}(θ', φ') = ∫ \d^3 r' ρ(\v r) r' \frac{3}{4π} \cos θ \\
  q_{11} &= ∫\d^3 r' ρ(\v r) r' Y_{10}(θ', φ') = ∫ \d^3 r' ρ(\v r) r' \frac{3}{8π} \sin θ(\cos φ + i \sin φ) \\
  \intertext{intuitives System, Dipolmoment $\v p = q \v a$}
  ρ(\v r) &= q(δ_D(\v r - \frac{1}{2} \v a) - δ_D(\v r + \frac{1}{2} \v a)) \\
  \v p &= ∫ \d^3 r' ρ(\v r') \v r' = q ∫ \d^3 r'(δ_D(\v r' - \frac{\v a}{2}) - δ_D(\v r' + \frac{\v a}{2}))\v r'= q \v a \tag{Dipolmoment} \\
  q_{10} &= ∫ \d^3 r' δ(\v r) \sqrt{\frac{3}{4π}} r' \cos θ' = \sqrt{\frac{3}{4π}} p_z \\
  q_{11} &= ∫ \d^3 r' δ(\v r) \sqrt{\frac{3}{8π}} r' \sin θ'(\cos φ' + i \sin φ') = \sqrt{\frac{3}{8π}}(p_x + i p_y) \\
  \intertext{Quadrupolmomente ($l = 2$)}
  q_{20} &= ∫ \d^3 r' ρ(\v r') r^{\prime 2} \sqrt{\frac{5}{4π}}(\frac{3}{2} \cos^2 θ' \frac{1}{2}) \\
  q_{21} &= -∫ \d^3 r' ρ(\v r') r^{\prime 2} \sqrt{\frac{15}{8π}} \sin θ \cos θ e^{iφ} \\
  q_{22} &= ∫ \d^3 r' ρ(\v r') r^{\prime 2}	\frac{1}{4} \sqrt{\frac{15}{2π}} \sin^2 θ e^{2iφ}
  \end{align*}
  Monopol:
  #+BEGIN_EXPORT latex
  \catcode`(=12
  \catcode`)=12
  \begin{tikzpicture}
  \node[circle,draw] at (0, 0) {$+$};
  \node at (0, -1.5) {$ϕ \sim \frac{Q}{r}$};
  \end{tikzpicture}
  Dipol
  \begin{tikzpicture}
  \node[circle,draw] at (0, -.5) {$+$};
  \node[circle,draw] at (0, +.5) {$-$};
  \node at (0, -1.5) {$ϕ \sim \frac{Q}{r^2}$};
  \end{tikzpicture}
  Quadropol
  \begin{tikzpicture}
  \node[circle,draw] at (.5, -.5) {$-$};
  \node[circle,draw] at (-.5, .5) {$-$};
  \node[circle,draw] at (-.5, -.5) {$+$};
  \node[circle,draw] at (.5, .5) {$+$};
  \node at (0, -1.5) {$ϕ \sim \frac{Q}{r^3}$};
  \end{tikzpicture}
  Oktopol
  \begin{tikzpicture}
  \node[circle,draw] at (.5, -.5, .5) {$-$};
  \node[circle,draw] at (-.5, .5, .5) {$-$};
  \node[circle,draw] at (-.5, -.5, .5) {$+$};
  \node[circle,draw] at (.5, .5, .5) {$+$};
  \node[circle,draw] at (.5, -.5, -.5) {$+$};
  \node[circle,draw] at (-.5, .5, -.5) {$+$};
  \node[circle,draw] at (-.5, -.5, -.5) {$-$};
  \node[circle,draw] at (.5, .5, -.5) {$-$};
  \node at (0, -1.5) {$ϕ \sim \frac{Q}{r^4}$};
  \end{tikzpicture}
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
#  \begin{align*}
#  \frac{1}{\abs{\v r - \v r'}} &= \frac{1}{\sqrt{r^2 - 2\v r \v r' + \v r^{\prime 2}}} = \frac{1}{r} \frac{1}{\sqrt{1 - 2\frac{r'}{r}μ + (\frac{r'}{r})^2}} \\
#  \intertext{Taylorentwicklung:}
#  &= \frac{1}{r} \sum_{l} (\frac{r'}{r})^l P_l(μ) \\
#  P_l(μ) &= \frac{4π}{2l + 1} \sum_{m = -l}^{+l} Y_{lm}(θ, φ) Y_{lm}(θ', φ')
#  \end{align*}
* Alternativer Zugang zur Multipolentwicklung $\to$ Taylor-Reihe in	kartesischen Koordinaten
  Green-Funktion
  \begin{align*}
  G(\v r') &= \frac{1}{\abs{\v r - \v r'}} \\
  \intertext{Taylorentwicklung bei $\v r' = 0$}
  G(\v r') &= G(\v r ' = \v 0) + \sum_{i} \pp{G}{x'_i}\big|_{\v r' = \v 0} · x_i' + \frac{1}{2!} \sum_{ij} \frac{\partial G}{\partial x_i' \partial x_j'} \big|_{\v r' = \v 0} · x_i' x_j' + \dots \\
  &= \sum_{n} \frac{1}{n!} (\sum_{i} x_i' \pp{}{x_i'})^n G \big|_{\v r' = 0} = \sum_{n} \frac{1}{n!}·(\v r' ∇')^nG \big|_{\v r' = \v 0} \\
  G(\v r') &= \frac{1}{\abs{\v r - \v r'}} = \left[\sum_{i}(x_i - x_i')^2\right]^{-1/2} \\
  G(\v r')\big|_{\v r' = \v 0} &= \frac{1}{r} \\
  \pp{}{x_i'} G(\v r') \big|_{\v r' = \v 0} &= \frac{x_i}{r^3} \\
  \frac{\partial^2}{\partial x_i' \partial x_j'} G(\v r') \big|_{\v r' = 0} &= \frac{3 x_i x_j - r^2 δ_{ij}}{r^5} \\
  ϕ(\v r) &= ∫\d^3 r' ρ(\v r') G(\v r, \v r') \\
  &= ∫ \d^3 r' ρ(\v r') (\frac{1}{r} + \sum_{i} \frac{x_i x_i'}{r^3} + \frac{1}{2} \sum_{ij} \frac{3 x_i x_j - r^2 δ_{ij}}{r^5} x_i' x_j' + \dots) \\
  &= \frac{1}{r} ∫\d^3 r' ρ(\v r') + \sum_{i} \frac{x_i}{r^3} ∫\d^3 r' ρ(\v r') x_i' + \frac{1}{2} \sum_{ij} ∫\d^3 r' ρ(\v r') \frac{3 x_i x_j - r^2 δ_{ij}}{r^5} x_i' x_j' + \dots
  \end{align*}
  \begin{ibox}{Umschreiben des Quadrupolterms}
  Quadrupolterm	$×3$:
  \begin{align*}
  &= \sum_{ij} \frac{3 x_i x_j - r^2 δ_{ij}}{r^5} ∫ \d^3 r' ρ(\v r') 3 x_i' x_j' \underbrace{- r^{\prime 2} δ_{ij} + r^{\prime 2} δ_{ij}}_{= 0} \\
  &= \sum_{ij} \frac{3 x_i x_j - r^2 δ_{ij}}{r^5} (∫ \underbrace{\d^3 r' ρ(\v r')(3x_i' x_j' - r^{\prime 2} δ_{ij})}_{Q_{ij}} + ∫ \d^3 r' ρ(\v r') r^{\prime 2} δ_{ij}) \\
  \intertext{2. Term verschwindet:}
  \sum_{ij} \frac{3 x_i x_j - r^2 δ_{ij}}{r^5} δ_{ij} &= 0 \\
  \circled{1}\quad \sum_{ij} x_i x_j δ_{ij} &= \sum_{i} x_i^2 = r^2 \\
  \circled{2}\quad \sum_{ij} δ_{ij}δ_{ij} &= \sum_{i} δ_{ii} = 3
  \end{align*}
  \end{ibox}
  \[⇒ ϕ(\v r) = \frac{Q}{r} + \frac{\v r \v p}{r^3} + \frac{1}{6} \sum_{ij} Q_{ij} \frac{3x_i x_j - r^2 δ_{ij}}{r^5} + \dots\]
  $Q_{ij} = Q_{ji} ⇒$ symmetrische Matrix $⇒ 6$ Einträge! Aber:	in sphärischen Koordinaten: $q_{-2,-2} q_{2,-1}, q_{2,0}, q_{2,1}, q_{22} ⇒$ 5 Einträge.
  Es gilt: $Q_{ij}$ ist spurfrei:
  \begin{align*}
  \sum_{i} Q_{ij} &= \sum_{i} ∫ \d^3 r' ρ(\v r') (3x_i' x_i' - r^{\prime 2} δ_{ij}) \\
  &= ∫ \d^3 r' ρ(\v r') (3 \sum_{i} x_i^{\prime 2} - r^{\prime 2} \sum_{i} δ_{ii}) = 0
  \end{align*}
* Wechselwirkung einer Ladunsverteilung mit einem externen Feld
  \begin{align*}
  W &= ∫ \d^3 r ρ(\v r) ϕ(\v r) \\
  ϕ(\v r) &= ϕ(\v r = 0) + \sum_{i} x_i \pp{ϕ}{x_i} \big|_{\v r = \v 0} + \frac{1}{2} \sum_{ij} \overarrow[x_i x_j]{Subtraktion von $\Laplace ϕ = 0$, weil die felderzeugende Ladung woanders ist!} \frac{\partial^2 ϕ}{\partial x_i \partial x_j} + \dots \\
  \Laplace ϕ &= \sum_{i} \frac{\partial^2}{\partial x_i^2}ϕ = \sum_{ij} δ_{ij} \frac{\partial^2}{\partial x_i \partial x_j} ϕ \\
  ϕ(\v r) &= ϕ(\v r = 0) + \sum_{i} x_i \pp{ϕ}{x_i} \big|_{\v r = \v 0} + \frac{1}{3!} \sum_{ij}(3x_i x_j - r^2 δ_{ij}) \frac{\partial^2 ϕ}{\partial x_i \partial x_j}\big|_{\v r = 0} + \dots \\
  W &= \underbrace{∫ \d^3 r ρ(r)}_{Q} ϕ(\v r = 0) + \sum_{i} \underbrace{∫ \d^3 r ρ(r) x_i}_{p_i} ·	\pp{ϕ}{x_i}\big|_{\v r = \v 0} + \frac{1}{3!} \sum_{ij} \underbrace{∫\d^3 r ρ(r)(3 x_i x_j - r^2 δ_{ij}) · \frac{\partial^2}{\partial x_i \partial x_j}}_{Q_{ij}} \big|_{\r v = \v 0} + \dots \\
  &= qϕ(\v r = 0) + \v p ∇ ϕ \big|_{\v r = 0} + \sum_{ij} Q_{ij} \frac{\partial^2 ϕ}{\partial x_i \partial x_j} \big|_{\v r = 0} + \dots
  \end{align*}
  $l$ Multipol wechselwirkt mit der \(l\)-fachen Ableitung von $ϕ$.
* Polarisation und Modelle für Dielektrika
  #+BEGIN_EXPORT latex
  \catcode`(=12
  \catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \draw[rotate=-45,black,pattern=north west lines, pattern color=black] (-3,0) ellipse (1 and 1.5) node[above left, xshift=-15pt,yshift=25pt] {Molekül $\v i$};
    \draw[rotate=45,black,pattern=north east lines, pattern color=black] (3,0) ellipse (1 and 1.5) node[above right, xshift=15pt,yshift=25pt] {Molekül $\v j$};
    \filldraw (0,-3) circle (1pt) node[below] {Ursprung};
    \draw[->] (0,-3) -- ++(0,7) node[above] {$P$} node[midway,right] {$\v r$};
    \draw[->] (0,-3) -- ++(2.5,4.5) node[below,midway] {$\v r_j$};
    \draw[->] (0,-3) -- ++(-2.5,4.5) node[below,midway] {$\v r_i$};
    \draw[red,->] (0,-3) ++(2.5,4.5) -- ++(.1,.5) node[right,midway] {$\v r'$};
    \draw[red,->] (0,-3) ++(-2.5,4.5) -- ++(-.1,.5) node[left,midway] {$\v r'$};
    \draw (0,-3) ++(-2.5,4.5) ++(-.1,.5) -- (0,4);
    \draw (0,-3) ++(2.5,4.5) ++(.1,.5) -- (0,4);
    \draw (0,-3) ++(-2.5,4.5) -- (0,4) node[below,midway,xshift=10pt] {$\v r - \v r_i$};
    \draw (0,-3) ++(2.5,4.5) -- (0,4) node[below,midway,xshift=-10pt] {$\v r - \v r_j$};
  \end{tikzpicture}
\end{center}
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
  \begin{align*}
  \intertext{Feld $\v E_j$ an der Stelle $\v r$, hervorgerufen durch Molekül $j$}
  \v E_j(\v r) &= ∫\d^3 r' ρ_j(\v r') \frac{\v r - \v r_j -\v r'}{\abs*{\v r - \v r_j - \v r'}^3} = -∇ ∫\d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r_j - \v r'}} \\
  \intertext{Multipolentwickulng}
  \frac{1}{\abs*{\v r - \v r'_j - \v r'}} &= \frac{1}{\abs{\v r - \v r_j}} + (\v r' ∇_j) \frac{1}{\abs{\v r - \v r_j}} + \frac{1}{2} (\v r' ∇_j)^2 \frac{1}{\abs{\v r - \v r_j}} + \dots \\
  ⇒ \v E_j(\v r) &= -∇(∫ \d^3 r' \frac{ρ_j(\v r')}{\abs{\v r - \v r_j}} + ∫\d^3 r' ρ_j(\v r') \v r' ∇_j \frac{1}{\abs{\v r - \v r_j}} + \dots) \\
  &= -∇(\frac{q_j}{\abs{\v r - \v r_j}} + \v p_j ∇_j \frac{1}{\abs{\v r - \v r_j}} + \dots) \\
  \intertext{Ladungsdichte:}
  ρ(\v r) &= \sum_{j} q_j δ_D(\v r - \v r_j) \\
  \intertext{Polarisationsdichte:}
  \v π(\v r) &= \sum_{j} \v p_j δ_D(\v r - \v r_j) \\
  \intertext{Summation der Felder zum Kontinuums-Limes:}
  \v E(\v r) &= \sum_{j} \v E_j(\v r) = -∇(\sum_{j} \frac{q_j}{\abs{\v r - \v r_j}} + \v p_j ∇_j \frac{1}{\abs{\v r - \v r_j}}) \\
  &= -∇(∫\d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}} + \v π(\v r') ∇' \frac{1}{\abs{\v r - \v r'}}) \\
  \Div \v E &= - \Laplace (∫\d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}} + \v π(\v r) ∇' \frac{1}{\abs{\v r - \v r'}}) \\
  &= -∫ \d^3 r' ρ(\v r') \underbrace{\Laplace \frac{1}{\abs{\v r - \v r'}}}_{\mathclap{-4π δ_D(\v r - \v r')}} + \v π(\v r') \underbrace{∇' \underbrace{\Laplace \frac{1}{\abs{\v r - \v r'}}}_{\mathclap{=-4πδ_D(\v r - \v r')}}}_{\mathclap{ = -∇δ_D(\v r - \v r')}} \\
  \Div \v E &= 4π ∫ \d^3 r' ρ(\v r') δ_D(\v r - \v r') - 4π ∇ ∫ \d^3 r' \v π(\v r') δ_D(\v r - \v r') \\
  \Div \v E &= 4πρ - 4π \Div \v π \\
  \Div \underbrace{(\v E + 4π \v π)}_{\v D} &= 4πρ \\
  \intertext{$\v π$ ist oft abhängig von dem externen Feld (da das externe Feld die Moleküle ausrichtet), dann gilt:}
  \v π &= ϰ \v E, \quad ϰ: \text{ Suszeptibilität} \\
  \v D &= ε \v E, ε = 1 + 4π ϰ
  \end{align*}
\setcounter{part}{23}
\part{orthogonale Funktionensysteme}
* orthogonale Funktionensysteme
  Satz von Funktionen $\{u_1, \dots, u_n(x)\}$. Für komplexe Funktionen definiert
  \[\angl{u_i,u_j} = ∫_A^b \d x u_i(x) u_j^{\ast}(x) = A_i \underarrow[δ_{ij}]{Orthogonalitätsrelation $A_i = 1 ⇒$ orthonormal.}\]
  ein Skalarprodukt.(symmetrisch, bilinear und positiv definit). Norm von $u_i(x):$
  \[∫_a^b \d x u_i(x) u_i^{\ast}(x) = A_i\]
  $⇒$ normalisiere $u_i$:
  \[u_i'(x) = \frac{u(x)}{\sqrt{∫_a^b \d x u_i(x) u_i^{\ast}(x)}}\]
  Bilden die orthonomalen Funktionen eine Basis?
  \begin{align*}
  g(x) &\overset{?}{=} \sum_{i}^{n} g_i u_i(x) \\
  0 &\leq Δn = ∫_a^b \d x \abs{g(x) - \sum_{i}^{n} g_i u_i(x)}^2 \\
  &= ∫_a^b \d x g(x) g^{\ast}(x) - ∫_a^b \d x g(x) \sum_{i} g_i^{\ast} u_i^{\ast}(x) - ∫_a^b \d x \sum_{i} g_i u_i(x) g^{\ast}(x) + ∫_a^b \d x \sum_{ij} g_i u_i(x) g_j^{\ast} u_j^{\ast} \\
  &= ∫_a^b \d x g(x) g^{\ast}(x) - \sum_{i} g_i^{\ast} ∫_a^b \d x g(x) u_i^{\ast}(x) - \sum_{i} g_i ∫_a^b \d x u_i(x) g^{\ast}(x) + \sum_{ij} g_i g_j^{\ast} ∫_a^b \d x u_i(x) u_j^{\ast} \\
  \intertext{Minimierung von $Δn$:}
  \pp{Δ}{g_i} &\overset{!}{=} 0 = g_i^{\ast} - ∫_a^b \d x g^{\ast}(x) u_i(x) \\
  \pp{Δ}{g_i^{\ast}} &= g_i - ∫_a^b \d x g(x) u_i^{\ast}(x) \\
  ⇒ g_i &= ∫_a^b \d x g(x) u_i^{\ast}(x) \\
  \intertext{Minimum:}
  Δ &= ∫_a^b \d x g(x) g^{\ast}(x) - \sum_{i} g_i g_i^{\ast} \\
  \intertext{Konvergenz im quadratischen Mittel}
  \lim_{n \to ∞} Δ_n \big|_{min} &= \lim_{n \to ∞}  ∫_a^b \abs{\sum_{i}^n g_i u_i(x) - g(x)}^2 = 0 \\
  \intertext{Konvergenz gesichert, falls: (Parseval-Reltation/Vollständigkeitsrelation)}
  ∫_a^b \d x g(x) g^{\ast}(x) &= \sum_{i} g_i g_i^{\ast} \\
  \intertext{Bessel-Ungleichnug:}
  ∫_a^b \d x g(x) g^{\ast}(x) &\geq \sum_{i} g_i g_i^{\ast} \\
  \intertext{denn:}
  0 &\leq ∫_a^b \d x \abs{g(x) - \sum_{i}^{n} g_i u_i(x)}^2 \\
  &= ∫_a^b \d x g(x) g^{\ast}(x) - 2 \sum_{i} g_i ∫_a^b \d x g^{\ast}(x) u_i(x) + \sum_{ij} g_i g_j^{\ast} \underbrace{∫_a^b \d x u_i(x) u_i^{\ast}(x)}_{=δ_{ij}} \\
  \intertext{Im Fall $Δn = 0$ für $n \to ∞$:}
  ∫_a^b \d x g(x) g^{\ast}(x) &= \sum_{i}^{n} g_i g_i^{\ast} \\
  \intertext{Was bedeutet das für das Basissystem?}
  \sum_{i} g_i g_i^{\ast} &= \sum_{i} ∫ \d x g(x) u_i^{\ast}(x) ∫ \d x' g^{\ast}(x') u_i(x') \\
  &= ∫_a^b \d x g(x) ∫_a^b \d x' g^{\ast}(x') \underbrace{\sum_{i} u_i^{\ast}(x) u_i(x')}_{δ_D(x - x')} \overset{?}{=} ∫_a^b \d x g(x) g^{\ast}(x) \\
  &= ∫_a^b g(x) ∫_a^b g^{\ast}(x') δ_D(x - x') = ∫_a^b g(x) g^{\ast}(x) \\
  \intertext{dies gilt, wenn: (Anforderung an das Basissystem)}
  \sum_{i} u_i^{\ast}(x) u_i(x') &= δ_D(x - x')
  \end{align*}
  Basissystem muss in der Lage sein, die \(δ_D\)-Funktion darzustellen. \\
  Cauchy-Schwarz-Ungleichung $\sim$ Eindeutigkeit der Linearzerlegung:
  \begin{align*}
  \big{\string(}\sum_{i} a_i b_i\big{\string)}^2 &\leq \sum_{i} a_i^2 \sum_{j} b_j^2 \\
  ⇒ \abs*{\v a \v b}^2 &\leq \v a^2 \v b^2 \\
  \abs*{\v a - λ \v b}^2 &= 0 \quad\text{kann nur } \begin{cases} \text{1 Lösung haben} & \text{falls } \v a \parallel \v b \\ \text{keine Lösung haben} & \text{falls } \v a \not\parallel \v b \end{cases} \\
  &= \v a^2 - 2 λ \v a \v b + λ^2 \v b^2 \\
  ⇒ λ_{\pm} &= 2 \v a \v b \pm \sqrt{4\string(\v a \v b\string)^2 - 4 \v a^2 \v b^2} \\
  \sqrt{4\string(\v a \v b\string)^2 - 4 \v a^2 \v b^2} &\begin{cases} \text{hat eine Lösung} & \text{falls } \string(\v a \v b\string)^2 = \v a^2 \v b^2 \\ \text{hat keine Lösung} & \text{falls } \string(\v a \v b\string)^2 < \v a^2 \v b^2\end{cases} \\
  \intertext{falls $\string(\v a \v b\string)^2 = \v a^2 \v b^2$ ist, sind $\v a \parallel \v b$ und $\v a$ lässt sich durch den Vektor $\v b$ darstellen:}
  \bigg{\string(}∫ \d x g(x) h^{\ast}(x)\bigg{\string)}^2 &\leq ∫_a^b \d x g(x) g^{\ast}(x) ∫_a^b \d x h(x) h^{\ast}(x) \\
  ∫_a^b \d x(g(x) - λ h(x))^2 &= ∫_a^b \d x g(x) g^{\ast}(x) - 2λ ∫_a^b \d x g(x) h^{\ast}(x) + λ^2 ∫_a^b \d x h(x) h^{\ast}(x) \\
  \intertext{dann gleiches Argument}
  \end{align*}
  Mögliche Wahlen von orthonormalen Systemen: \\
  $\Laplace ϕ = \const ϕ$ \\
  Sinus (ungerade) und Konsinus (gerade):
  \begin{align*}
  \frac{1}{π} ∫_{-π}^π \d x \sin(n x) \sin(m x) &= δ_{mn} \\
  \frac{1}{π} ∫_{-π}^π \d x \cos(n x) \cos(m x) &= δ_{mn} \\
  \intertext{$⇒$ orthonormale Funktionen:}
  u_m(x) &= \frac{1}{\sqrt{π}} \sin(m x) \\
  v_m(x) &= \frac{1}{\sqrt{π}} \sin(m x) \\
  \intertext{Man erhält die Fourier-Reihe}
  ⇒ g(x) = \frac{a_0}{2} + \sum_{m = 1} a_m \cos(m x) + b_m \sin(m x) \\
  a_m &= \frac{1}{π} ∫_{-π}^{+π} \d x' g(x') \cos(m x') \\
  b_m &= \frac{1}{π} ∫_{-π}^{+π} \d x' g(x') \sin(m x') \\
  \intertext{Kontinuumslimit}
  ∫_{-∞}^∞ \d x \exp(i k x) \exp(i k' x)^{\ast} &= δ_D(k - k')
  δ_D(x - x') &= \sum_{i} u_i(x) u_i^{\ast}(x') \\
  \text{Wellen } \sum_{n} \cos(n x) \cos(n x') &= δ_D(x - x') \\
  \sum_{n} \exp(i n x) \exp(i n x') &= δ_D(x - x')
  \end{align*}
* Kugelflächenfunktionen (spherical harmonics)
  $\Laplace$ in Kugelkoordinaten (in 3D), Laplace-Gleichung: $\Laplace ϕ = 0$:
  \begin{align*}
  \Laplace ϕ &= \frac{1}{r^2} \pp{}{r}(r^2 \pp{}{r}ϕ) + \frac{1}{r^2 \sin^2 θ} \pp{}{θ}(\sin θ \pp{ϕ}{θ}) + \frac{1}{r^2 \sin^2 θ} \frac{\partial^2}{\partial φ^2} ϕ \\
  \intertext{Separation der Variablen}
  ϕ(r, θ, φ) &= R(r) · Y(θ,φ) \\
  \intertext{Radialteil:}
  \dd{}{r}(r^2 \dd{R}{r}) &= λ R \\
  \intertext{Lösungen:}
  R(r) &= A r^λ + B r^{-(1 + λ)} \\
  \intertext{Winkelteil:}
  \frac{1}{\sin θ} \pp{}{θ} (\sin θ \pp{Y}{θ}) + \frac{1}{\sin^2 θ} \frac{\partial^2}{\partial φ^2} Y &= λ Y \\
  \intertext{Separation:}
  Y(θ,φ) &= P(θ) Q(φ) \\
  \intertext{in \(φ\)-Richtung, harmonische Differentialgleichung:}
  \frac{\d^2 Q}{\d θ^2} &= - m^2 Q \\
  \intertext{in \(θ\)-Richtung}
  λ \sin^2 θ + \frac{\sin θ}{P} \dd{}{θ}(\sin θ \dd{P}{θ}) &= m^2 \\
  \intertext{Wellen in \(φ\)-Richtung, Periodizität $2π$}
  ⇒ Q(φ) &\sim \exp( \pm i m φ)
  \intertext{$λ$ muss gleich $l(l + 1)$ mit $l \geq \abs{m}$ sein, damit Lösungen für $P$ existieren. Substitution $μ = \cos θ \to$ Legendre-Differentialgleichung}
  ⇒ 0 &= (1 - μ^2) \frac{\d^2}{\d μ^2} P_{lm}(μ) - 2 \dd{}{μ} P_{lm}(μ) + (l(l + 1) - \frac{m^2}{1 - μ^2}) P_{lm}(μ) \\
  \intertext{Zusammensetzen der Winkellösung}
  Y_{lm}(θ,φ) &= \sqrt{\frac{2l + 1}{4π}} \sqrt{\frac{(l - m)!}{(l + m)!}} \underbrace{P_{lm} \cos(θ)}_{= P} \underbrace{\exp(-imφ)}_{= Q} \\
  \text{mit } ∫ \d Ω Y_{lm} Y_{l'm'} &= δ_{ll'} δ_{mm'}
  \end{align*}
