#+AUTHOR: Robin Heinemann
#+TITLE: Theoretische Physik III (Schäfer)

#+INCLUDE: "../header.org" :minlevel 1

#+LATEX_HEADER:	\renewcommand\raggedpart\centering
#+LATEX_HEADER:	\renewcommand\thepart{\Alph{part}}
#+LATEX_HEADER:	\renewcommand\thesection{\thepart.\arabic{section}}
#+LATEX_HEADER:
#+LATEX_HEADER:	\renewcommand*{\partheadstartvskip}{%
#+LATEX_HEADER:	\pagebreak\thispagestyle{empty}\vspace*{\fill}\begin{center}
#+LATEX_HEADER:	}
#+LATEX_HEADER:	\renewcommand*{\partheadmidvskip}{%
#+LATEX_HEADER:	\par\nobreak
#+LATEX_HEADER:	}
#+LATEX_HEADER:	\renewcommand*{\partheadendvskip}{%
#+LATEX_HEADER:	\end{center}\vfill\newpage
#+LATEX_HEADER:	}
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER:	\let\oldpart\part
#+LATEX_HEADER: \renewcommand{\part}{\setcounter{section}{0}\oldpart}
#+LATEX_HEADER: \makeatother
#+LATEX_HEADER:	\setlength{\cftsecnumwidth}{2em}

# Klausurzulassung: 60% der Punkte der Übungsaufgaben
# Klausur 8.2
# Nachklausur 15.2 lol, wird /vielleicht/ noch geändert

# Modalitäten
# -----------
# 60% der Punkte
# 2×vorrechnen
# Aufgaben mit Stern sind Zusatzaufgaben
# paarweise	abgeben
# nur ganze Punkte
# übliches bla bla

# Elektrodynamik
# --------------
# Einleitung
# Inhalt:
# Phänomenologie der Maxwell-Gleichungen
#  Maxwell-Gleichungen, differentielle+integrale Formulierung, Ladungserhaltung, Dynamik in Materie, Potentiale
# Potenzialtheorie
#  Poisson-Gleichung, Punktquellen+Suerposition, Green-Theoreme, Multipol-Entwicklung
# Dynamik des elektromagnetischen Felds
#  elektromagnetische Wellen, Polarisation, Wellengleichung, Energie + Impulstransport, Hertz-Dipol
# Lorentz-Geometrie + spezielle Relativitätstheorie
#  Lorentz-Transformation, relativistische Effekte, Raumzeit-Diagramme, kovariante Formulierung der Elektrodynamik
# relativistische Feldtheorie
#  Axiome der Elektrodynamik, Bianchi-identität, Dualität, Variationsprinzipien
# Bewegung von Ladungen
#  minimale Kopplung, Variation+Bewegungsgleichungen, geometrische Interpretation der Lagrangefunktion

\part{Phänomenologie der Maxwell-Gleichungen}
* elektrisches Feld
  #+begin_export latex
  \catcode`(=12
  \catcode`)=12
  \begin{center}
  \begin{tikzpicture}
  \node[draw, circle, left] (q1) at (0,0) {$q_1$};
  \node[draw, circle, left] (q2) at (2,0) {$q_2$};
  \draw[->] (-1,-2)	-- (q1) node[above left,midway] {$\v r_1$};
  \draw[->] (-1,-2)	-- (q2) node[below,midway] {$\v r_2$};
  \end{tikzpicture}
  \end{center}
  \begin{align*}
  F &= k \frac{q_1 q_2}{\abs{\v r_1 - \v r_2}^2} \\
  k &= \frac{1}{4 π ε_0} \\
  ε_0 &= \SI{8654e-12}{\ampere\second\per\volt\meter} \simeq \frac{1}{4π \num{9e9}}\si{\ampere\second\per\volt\meter}
  \end{align*}
  im SI-System.
  \catcode`(=\active
  \catcode`)=\active
  #+end_export
  \[q \to \frac{q}{\sqrt{4πε_0}} \to k = 1, F = \frac{q_1 q_2}{\abs{\v r_1 - \v r_2}^2}\]
  $q$ wird gemessen in $\sqrt{\si{\erg\centi\meter}} = \SI{1}{\esu}$ "elektrostatic unit".
* elektrische Feldstärke
  \[\v E(\v r) = \frac{\v F(\v r)}{q}\]
  \begin{attention}
  viele Bücher verlangen:
  \[\v E(\v r) = \lim_{Δq \to 0} \frac{Δ\v F}{Δq}\]
  dies ist nicht notwending $\to$ Linearität der Elektrodynamik
  \end{attention}
  analog: Lorentz-Kraft auf bewegte Ladungen $\to$ magnetische Felder
* Maxwell-Gleichungen
  $\to$ axiomatisch für die Elektrodynamik. Verbindung zwischen Ladungsdichte $ρ$, elektrischen Stromdichte $\v j$ und den Feldern $\v E, \v D, \v H$ und $\v B$.
  In einem Inertialsystem nehmen die Maxwell-Gleichungen diese Form an:
  1. $\Div \v E = ∇ · \v E = 4π ρ$ Gesetz von Grauß. \\
	 elektrische Ladungen sind Quellen des elektrischen Feldes
	 \[∫_V \d^3 r \Div \v E \overarrow[=]{Satz von Gauß} ∫_{\partial V} \d \v S \v E = \underarrow[ψ]{el. Fluss} = ∫_v \d^3 r 4 π ρ = 4 π \overarrow[q]{eingschl. Ladung}\]
  2. $\Div \v B = ∇ \v B = 0$ \\
	 \[∫_v \d^3 r \Div \v B = ∫_{\partial V} \d \v S \v B = ϕ = 0\]
  3. $\rot \v E = ∇ × \v E = \underarrow[-]{Lenz.-Regel.} \partial_{ct} \v B$ Faraday-Induktionsgesetz. \\
	 \[\partial_{ct} = \pp{}{(ct)} = \frac{1}{c} \pp{}{t}\]
	 \[∫_S \d \v S · \rot \v E = \underbrace{∫_{\partial S} \d \v r \v E}_{U} = -\dd{}{(ct)} \underbrace{∫_s \d \v S · \v B}_{ϕ}\]
  4. $\rot \v B = ∇ × \v B = \partial_{ct} \v E + \frac{4π}{c} \v j$ \\
	 \[∫_s \d \v S \rot \v B = ∫_{\partial S} \d \v r \v B = \frac{d}{(ct)} \underbrace{∫_S \d \v S \v E}_{ψ} + \frac{4π}{c} \underbrace{∫_S \d \v S \v j}_{I}\]
* Eigenschaften der Maxwell-Gleichungen
  - zwei skalare und zwei vektoriell Gleichungen
  - lineare, partielle Differenzialgleichungen erster Ordnung
  - für vorgegebene	$ρ$ und $\v j$ lassen sich $\v E$ und $\v B$ berechnen
  - *oder* aus einer Feldkonfiguration $\v E$ und $\v B$ lassen sich Ladungen $ρ$ und $\v j$ finden
  - Maxwell-Gleichungen gelten in einem Inertialsystem: erst die Definitonen aus Bezugssystem bestimmt, was $ρ$ und $\v j$ ist, und damit $\v E$ und $\v B$ \\
	darüber hinaus ist mit Wahl des Systems klar, was xvolt ist, und damit $\partial_{ct}$ und $∇$.
  - nur eine Skala enthalten: $c \sim$ Lichtgeschwindigkeit
  - im Vakuum: $ρ = 0, \v j = 0$: $ε = 1 = μ \to \v D = \v E, \v H = \v B$.
  	\begin{align*}
    \Div \v E &= 0 \\
    \Div \v B &= 0 \\
    \rot \v E &= -\partial_{ct} \v B \\
    \rot \v B &= -\partial_{ct} \v E \\
    \end{align*}
    Wenn man $\v E \to \v B, \v B \to -\v E$ vertauscht, dann ändern sich die Gleichungen nicht $\to$ *elektromagnetische Dualität*.
  - seltsame Asymmetrie, es gibt kein $ρ_{\text{mag}}$ oder $\v j_{\text{mag}}$
	\begin{align*}
	\Div \v B &= 4 π ρ_{\text{mag}} = 0 \\
	\rot \v E &= -\partial_{ct} \v B + \underbrace{\frac{4π}{c} \v j_{\text{mag}}}_{= 0}
    \end{align*}
* Erhaltung der elektrischen Ladung
  \begin{align*}
  \rot \v B &= \partial_{ct} \v E + \frac{4π}{c} \v j \\
  \Div\rot \v B &= ε_{ijk} \partial_i \partial_j B_k = 0 = \partial_{ct} \underbrace{\Div \v E}_{=4πρ} + \frac{4π}{c} \Div \v j \\
  &= \frac{4π}{c}(\partial_t ρ + \Div \v j) \\
  ⇒ \partial_t ρ + \Div \v j &= 0 \tag{Kontinuitätsgleichung}
  \intertext{Aus der Kontinuitätsgleichung folgt die Ladungserhaltung}
  ∫_V \d^3 r \partial_t ρ &= \dd{}{t} \underbrace{∫_V \d^3 r ρ}_{q} = -∫_V \d^3 r \Div \v j = -∫_{\partial V} \d \v S · \v j
  \end{align*}
  - Änderung der Ladung in einem Volumen = Fluss der Ladung durch die Oberfläche.
  - Dynamik der Felder ist konsistent zur Bewegung der Ladungen
  - gilt auch in Materie! Ampere-Gesetz und Gauß-Gesetz enthalten falls $ε \neq 1$ die dielektrische Verschiebung $\v D$.
  -	es existiert implizit eine zweite Erhaltungsgleichung für die magnetische Ladungen, die nicht existieren.
	$2(1 + 3)$ Maxwell-Gleichungen für $2·2·3$ Felder!
* Elektrodynamik in Materie
  Wechselwirkungen zwischen dem elektromagnetischen Feld und Materie ist *sehr* kompliziert im Mikroskopischen
  $\to$ in vielen Fällen ist es trotzdem möglich, mit zwei Konstatnen eine einfach *effektive* Beschreibung zu finden.
  - $ε$: Dielektrizitätskonstante $\to \v D = ε \v E$
  -	$μ$: Permeabilitätskonstante $\to \v B = μ \v H$
  Im Vakuum: $ε = 1, μ = 1$, in Materie: $ε \neq 1, μ \neq 1$
  \begin{equation*}
  \begin{aligned}
  \text{im Vakuum} \\
  \Div \v E &= 4πρ \\
  \Div \v B &= 0 \\
  \rot \v E &= - \partial_{pt} \v B \\
  \rot \v B &= \partial_{ct} \v E + \frac{4π}{c} \v j
  \end{aligned}
  \qquad\qquad
  \begin{aligned}
  \text{in Materie} \\
  \Div \v D &= 4πρ \\
  \Div \v B &= 0 \\
  \rot \v E &= - \partial_{pt} \v B \\
  \rot \v H &= \partial_{ct} \v D + \frac{4π}{c} \v j
  \end{aligned}
  \end{equation*}
  (wir brauchen noch zwei Konzepte, Dipolfelder und das elektrische Potenzial um ein Modell für $ε$ aufstellen zu können).
* elektrisches Potenzial $\to$ Elektrostatik
  #+begin_export latex
  \begin{minipage}{.45\linewidth}
  \begin{align*}
  \v E(\v r) &= q_1 \frac{\v r - \v r_1}{\abs{\v r - \v r_1}^3} \\
  \v E(\v r) &= \sum_{i} q_i \frac{\v r - \v r_i}{\abs{\v r - \v r_i}^3} \\
  \end{align*}
  (Definiton: Probeladung ist positiv $\to$ abstoßende Coulomb-Kraft falls $q_1 > 0$.)
  \end{minipage}
  \hfill%
  \catcode`(=12
  \catcode`)=12
  \begin{minipage}{.45\linewidth}
  \begin{center}
  \begin{tikzpicture}
  \node[draw, circle, left] (q1) at (0,0) {$q_1$};
  \node[draw, circle, left] (q2) at (2,0) {$q_2$};
  \draw[->] (-1,-2)	-- (q1) node[above left,midway] {$\v r_1$};
  \draw[->] (-1,-2)	-- (q2) node[above left,midway] {$\v r_2$};
  \draw[->] (-1,-2)	-- (2.5, -.5) node[below,midway] {$\v r$};
  \node[right,every text node part/.style={align=center}] at (2.5, -.5) {Beobachter \\ mit Probeladung};
  \end{tikzpicture}
  \end{center}
  \end{minipage}
  \catcode`(=\active
  \catcode`)=\active
  #+end_export
  Superposition wegen der Linearität der Maxwell-Gleichnug. \\
  Kontinuumslimit: ersetze $q \to ρ$
  \begin{align*}
  \v E(\v r) &= ∫_V \d^3 r' ρ(\v r) \frac{\v r - \v r'}{\abs{\v r - \v r'}^3} = - ∫_V \d^3 r' ρ(\v r) ∇ \frac{1}{\abs{r - r'}} \\
  &= - ∇ \underbrace{∫_V \d^3 r' \frac{ρ(\v r)}{\abs{\v r - \v r'}}}_{=ϕ(\v r)} \\
  \to \Aboxed{\v E(\v r) &= -∇ ϕ(\v r)} \\
  ϕ(\v r) &= ∫_V \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}}
  \end{align*}
  und es gilt automatisch in diesem Fall:
  \[\rot \v E = -\rot ∇ ϕ = 0;\qquad (\rot E)_i = ε_{ijk} \partial_j \partial_k ϕ = 0\]
  Substitution in das Gauß-Gesetz:
  \begin{align*}
  \Div \v E &= 4πρ \\
  \to \Aboxed{\Laplace ϕ &= - 4πρ} \tag{Poisson-Gleichung}
  \end{align*}
  Falls keine Ladungen vorliegen, muss $\Laplace ϕ = 0$ gelten.
  \begin{align*}
  ϕ(\v r) &= \frac{1}{\abs{r - r'}} \\
  \intertext{Für Quelle mit $q = 1$ an der Stelle $\v r' = \v 0$:}
  \Laplaceϕ &= (\partial_x^2 + \partial_y^2 + \partial_z^2)ϕ \underarrow[=]{Kugelkoordinaten, Winkel fallen weg, da sie nicht in $ϕ$ vorkommen} \Laplace \frac{1}{r} = \frac{1}{r} \frac{\partial^2}{\partial r^2}(r \frac{1}{r}) = 0 \\
  \intertext{klar, bei $\v r$ ist die Ladung nicht, sondern bei $\v 0$}
  ∫_V \d^3 r \Laplaceϕ &= ∫_V \d^3 r ∇(∇ϕ) \underarrow[=]{Satz von Gauß} ∫_{\partial V} \d \v S ∇ ϕ \\
  &= ∫ r^2 \d Ω \underbrace{\pp{ϕ}{r}}_{=-\frac{1}{r^2}} = -∫ \d Ω = -4π \\
  \intertext{Zusammenfassung beider Fälle}
  \Laplace \frac{1}{\abs{\v r - \v r'}} &= -4π δ_D(\v r - \v r') \\
  \intertext{analog für Gravitation}
  \Div \v g &= 4π ρ \\
  \Laplace ϕ &= 4πGρ
  \end{align*}
* Dirac-Funktion $δ_D$
  Elektrodynamik ist eine Kontinuumstheorie $\to$ $ρ$ ist eine Ladungsdichte:
  \begin{equation*}
  ∫_V \d^3 r ρ = q\tag{im Volumen $V$}
  \end{equation*}
  $qδ_D(\v r - \v r')$ repräsentiert eine Punktladung $q$ an der Stelle $\v r'$.
  \begin{align*}
  ρ(\v r) &= \sum_{i} q_i δ_D(\v r - \v r_i) \\
  ϕ(\v r) &= ∫ \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}} \\
  \intertext{denn}
  \Laplace ϕ(\v r) &= ∫ \d^3 r' ρ(\v r') \Laplace \frac{1}{\abs{\v r - \v r'}} = ∫ \d^3 r'ρ(\v r') (-4π) δ_D(\v r - \v r') \\
  \Laplace ϕ(\v r) &= -4π σ(\v r) \tag*{Poisson-Gleichung} \\
  \intertext{im diskreten Fall:}
  ϕ(\v r) &= \sum_{i} \frac{q_i}{\abs{\v r - \v r_i}} \\
  \Laplace ϕ(\v r) &= \sum_{i} q_i \Laplace \frac{1}{\abs{\v r - \v r'}} = \sum_{i} q_i (-4π) δ_D(\v r - \v r_i) \\
  &= -4π \sum_{i} q_i σ_D(\v r - \v r') = -4π ρ(\v r)
  \end{align*}
* potenzielle Energie und das elektrostatische Potenzial
  \begin{attention}
  bitte seid super vorsichtig mit Energieinterpretationen von allem, was mit Relativität zutun hat!
  \end{attention}
  Coulomb-Kraft $\v F$:
  \[\v F(\v r) = q \v E(\v r)\]
  Verschiebearbeit $W$:
  \begin{align*}
  W &= ∫_A^B \d \v r · \v F = -q ∫_A^B \d \v r \v E \underarrow[=]{$\v E = - ∇ϕ$} g ∫_A^B \underbrace{\d \v r ∇ ϕ}_{= \pp{}{\v r}ϕ} \\
  \intertext{mit $\d \v r · \pp{}{\v r}ϕ = \d ϕ$ (totales Differenzial)}
  W &= q ∫_A^B \d ϕ = q(ϕ(B) - ϕ(A))
  \end{align*}
  - Potenzialdifferenz entspricht der Verschiebearbeit pro Ladung
  -	Verschiebung muss extrem langsam erfolgen, dass $E \to B$ nicth transformiert (Lorentz!)
* Eigenschaften der \(δ_D\)-Funktion
  \begin{align*}
  \intertext{Normierung}
  ∫ \d^n x δ_D(x) &= 1 \\
  \intertext{Lokalisierung}
  ∫ \d^n x g(x) δ_D(x - y) &= g(y) \\
  ∫_a^b \d x δ_D(x - c) &= \begin{cases} 1 & a \leq c \leq b \\ 0 & \text{sonst} \end{cases} \\
  \intertext{Durch Substitution}
  ∫ \d x δ_D(a x) &= \frac{1}{a} \\
  \intertext{Durch partielle Integration}
  ∫ \d x g(x) δ_D'(x - a) &= g(x) δ_D(x - a) \Big|_{-∞}^{+∞} - ∫ \d x g'(x) δ_D(x - a) \\
  &= 0 - g'(a)
  \end{align*}
* Feldänderung an einer Oberfläche
  Betrachte Oberfläche mit Oberflächenladung $σ$
  \[σ = \lim_{ΔS \to 0} \frac{Δq}{ΔS}\]
  wie wird ein elektrischen Feld durch diese Oberfläche beeinflusst? (vor Oberfläche: $\v E_1$, nach Oberfläche $\v E_2$) \\
  Dazu wählen Zylinder mit den Mantelflächen parallel zur Oberfläche und Volumen $ΔV$ und, dass der elektrische Full durch die Seitenwände sehr klein ist und nicht zum Integral beiträgt.
  \begin{align*}
  ∫_{ΔV} \d^3 r' \Div \v E &\underarrow[=]{Gauß} ∫_{ΔS} \d \v S · \v E = 4π q = 4π \overbrace{∫_{\partial V} \d \v S σ}^{ΔS · σ} = ΔS(E_2^{\perp} - E_1^{\perp}) \\
  ⇒ E_2^{\perp} = E_1^{\perp} + 4πσ
  \end{align*}
  Wenn das Feld tangential zur Oberfläche ist, kann man stattdessen eine Schleife wählen und den Satz von Stokes benutzen:
  \[∫_{\partial} \d \v r \v E \underarrow[τ]{Stokes} ∫_S \d \v S \rot \v E = (E_2^{\parallel} - E_1^{\parallel}) Δr \to E_2^{\parallel} = E_1^{\parallel}\]
  Außerdem: $\v E = -∇ ϕ ⇒ \rot \v E = - \rot ∇ ϕ = 0$.
* Energie einer	statischen Ladungsverteilung
  \begin{attention}
  Energie + Relativitätstheorie: supervorsichtig!
  \end{attention}
  \begin{tabular}{cccl}
  1. & $q_1$ an einer Stelle $\v r_1$ & $\to$ & Potential $ϕ_1 = \frac{q_1}{\abs{\v r - \v r_1}}$ \\
  2. & $q_2$ an einer Stelle $\v r_2$ & $\to$ & $W_2 = q_2 · ϕ_1(\v r_2)$ \\
  3. & $q_3$ an einer Stelle $\v r_3$ & $\to$ & $W_3 = q_3 · (ϕ_1(\v r_2) + ϕ_2(\v r_3))$ \\
  \vdots & & & \\
  n. & $q_n$ an einer Stelle $\v r_n$ & $\to$ & $W_n = q_n · \sum_{i}^{n - 1} ϕ_i(\v r_n)$ \\
  \end{tabular}
  Man erkennt
  \begin{align*}
  W &= \sum_{n}^{N} W_n = \sum_{n}^{N} q_n \sum_{i}^{n - 1} ϕ_i(\v r_n) \\
  W &= \sum_{n}^{N} q_n \sum_{i}^{n - 1} \frac{q_1}{\abs{\v r_1 - \v r_n}} = \underarrow[\frac{1}{2}]{Korrektur der doppelten Zählung} \sum_{n}^{N} \sum_{\substack{i\\i\neq n}}^{N} \frac{q_i q_n}{\abs{\v r_1 - \v r_n}}
  \end{align*}
  Kontinuums-Limes
  \begin{align*}
  \sum_{i} q_i &\to ∫ \d^3 r' ρ(\v r') \\
  W &= \frac{1}{2} ∫\d^3 r ∫ \d^3 r' \frac{ρ(\v r) ρ(\v r')}{\abs{\v r - \v r'}} = \frac{1}{2} ∫ \d^3 r ρ(\v r) \underbrace{∫\d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}}}_{=ϕ(\v r)} \\
  &= \frac{1}{2} ∫ \d^3 r ρ(\v r) ϕ(\v r) \\
  W &\underarrow[=]{Poisson-Gleichung $\Laplace ϕ = - 4π ρ$} -\frac{1}{8π} ∫\d^3 r \Laplace ϕ ϕ = - \frac{1}{8π} ∫\d^3 r^3 ϕ \Laplace ϕ  \\
  \intertext{Es gilt: $ϕ \Laplace ϕ = ϕ ∇·(∇ϕ) = ∇(ϕ ∇ ϕ) - ∇ϕ∇ϕ$}
  W &= -\frac{1}{8π} ∫ \d^3 r ∇(ϕ∇ϕ) + \frac{1}{8π} ∫ \d^3 r (∇ ϕ)^2 \\
  &= -\frac{1}{8π} ∫ \d \v S (ϕ ∇ ϕ) + \frac{1}{8π} ∫ \d^3 r \underbrace{(∇ ϕ)^2}_{\v E = - ∇ ϕ} \\
  \intertext{Satz von Gauß: $∫ \d \v S (ϕ ∇ ϕ) = 0$ für große Volumen, da typischerweise $ϕ \sim 1/r$, $∇ϕ \sim 1/r^2 ⇒ ϕ ∇ ϕ \sim 1/r^3$, aber $\d \v S \sim r^2$} \\
  W &= \frac{1}{8π} ∫\d^3 r E^2
  \end{align*}
  Energiedichte des elektrischen Felds:
  \[ρ_{el} = \frac{\v E^2}{8π}\]
  \begin{attention}
  Selbstenergie für \(\v r' = \v r\)- keine Lösung in der klassischen Elektrodynamik.
  \end{attention}


\part{Potentialtheorie}
Lösungen der Poisson-Gleichung $\Laplace ϕ = - 4πρ$.
3 Probleme
1. Inversion des Differenzialoperators $\to$ Green-Funktion
2. Geometrie der Ladungsverteilung $\to$ Multipolentwicklung
3. Randbedingungen $\to$ Green-Theorie
* Green-Theoreme
  Es gilt für $\v A(\v r) = φ ∇ ψ$
  \begin{align*}
  \Div \v A - \Div(φ ∇ ψ) = ∇φ∇ψ + φ \Laplace ψ
  \intertext{Satz von Gauß:}
  ∫_V \d^3 \Div \v A &= ∫_{\partial V} \d \v S \v A \\
  \intertext{$\v S = \d S \v n, \v n \sim$ Normalenvektor} \\
  ∫_V \d^3 r'(∇' φ ∇' ψ + φ \Laplace' ψ) &= ∫_{\partial V} \d S φ ∇' ψ · \v n = ∫_{\partial V} \d S φ \pp{ψ}{n} \tag*{Erste greensche Identität} \\
  \intertext{$φ \rightleftharpoons ψ$ und Subtraktion der Gleichungen}
  ∫_V \d^3 r'(φ \Laplace' ψ - ψ \Laplace' φ) &= ∫_{\partial U} \d S (φ \pp{ψ}{n} - ψ \pp{ϕ}{n}) \tag*{Zweite greensche Identität}
  \end{align*}
  Wahl der Funktionen
  \begin{align*}
  ψ &= \frac{1}{\abs{\v r - \v r'}} \\
  φ &= ϕ(\v r') \tag*{elektrostatisches Potential} \\
  ⇒ \Laplace' ψ &= \Laplace' \frac{1}{\abs{\v r - \v r'}} = -4π δ_D(\v r - \v r') \\
  \Laplace' φ &= \Laplace ϕ = -4π ρ(\v r')
  -4π ∫_V \d^3 r' ϕ(\v r) δ(\v r - \v r') + 4π ∫_V \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}} \\
  &= ∫_{\partial V} \d S' ϕ(\v r') \pp{}{n'} \frac{1}{\abs{\v r - \v r'}} - \frac{1}{\abs{\v r - \v r'}} \pp{}{n'} ϕ(\v r') \\
  \intertext{Falls $\v r$ innerhalb von $V$ liegt:}
  ∫_V \d^3 r' ϕ(\v r') δ_D(\v r - \v r') &= ϕ(\v r) \\
  ⇒ ϕ(\v r) &= \underbrace{∫_V \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}}}_{\mathclap{\text{Potenzial aus}\atop\text{der Ladungsverteilung}}}  + \frac{1}{4π} ∫_{\partial V} \d S'\Big{\string(}\overbrace{\frac{1}{\abs{\v r - \v r'}} \pp{}{n'}ϕ}^{\mathclap{{{\text{Neumann-}}\atop{\text{Raundbedingungen}}}\atop{\pp{ϕ}{n} \text{ auf } \partial V}}} - \underbrace{ϕ(\v r') \pp{}{n'} \frac{1}{\abs{\v r - \v r'}}}_{\mathclap{{\text{Dirichlet-}\atop\text{Randbedingung}}\atop{ϕ\text{ auf }\partial V}}}\Big{\string)}
  \end{align*}
  $\partial V$ unendlich weit weg:
  \begin{align*}
  \frac{1}{\abs{\v r - \v r'}} \pp{}{n}ϕ &\sim \frac{1}{r^3} \to 0 \\
  ϕ \pp{}{n} \frac{1}{\abs{\v r - \v r'}} &\sim \frac{1}{r^3} \to 0
  \end{align*}
  $⇒$ nur der erste Term bleibt übrig:
  \[ϕ(\v r) = ∫_V \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}}\]
  $ρ(\v r) = 0$ innerhalb von $V$: $ϕ$ bestimmt durch $ϕ$ und $\pp{ϕ}{n}$ auf der Oberfläche $\partial V$.
* Eindeutigkeit des Potenzials
  #+begin_thm latex
  Potenzial $ϕ$ ist eindeutig mit der Vorgabe von Dirichlet *oder* Neumann-Randbedingungen.
  #+end_thm
  #+begin_proof latex
  Annahme für Widerspruchsbeweis: 2 Potenziale $ϕ_1(\v r)$ und $ϕ_2(\v r)$, beide Lösungen der Poisson-Gleichnug:
  \begin{align*}
  \begin{rcases*}
  \Laplace ϕ_1 = -4π ρ \\
  \Laplace ϕ_2 = -4π ρ \\
  \end{rcases*}
  \Laplace\underbrace{(ϕ_1 - ϕ_2)}_{U} &= 0
  \intertext{Randbedingungen:}
  ϕ_1 \big|_{\partial V} &= ϕ_2 \big|_{\partial V} \\
  \pp{ϕ_1}{n} \big|_{\partial V} &= \pp{ϕ_2}{n} \big|_{\partial V} \\
  \end{align*}
  1 Green-Theorem mit $U = ϕ_1 - ϕ_2$ und $φ = ψ = U$
  \begin{align*}
  ∫_V \d^3 r'\string(\underbrace{U \Laplace' U}_{= 0} + (∇' U)^2\string) &= ∫_{\partial V} \d S U \pp{U}{n} \\
  \intertext{wenn $n = 0$ (Dirichlet) oder $\pp{U}{n'}$ (Neumann)}
  ∫_{\partial V} \d S U \pp{U}{n} &= 0 \\
  ⇒ ∫_V \d^3 r'(∇' U)^2 &= 0
  \end{align*}
  $⇒ U$ ist konstant un $V$, $ϕ_1 = ϕ_2 + \const$. Die Potenziale unterscheiden sich nur um eine additive Konstante.
  #+end_proof
* Green-Funktion $\to$ Potenzial einer Punktladung
  Potenzial einer Punktladung:
  \[\Laplace \underbrace{\frac{1}{\abs{\v r - \v r'}}}_{\mathclap{\text{Green-Funktion von } \Laplace}} = -4π δ_D(\v r - \v r')\]
  Verallgemeinerung:
  \begin{align*}
  \Laplace G(\v r, \v r') &= -4π δ_D(\v r - \v r') \\
  \text{mit } G(\v r, \v r') &= \frac{1}{\abs{\v r - \v r'}} + \underbrace{F(\v r, \v r')}_{\Laplace F(\v r, \v r') = 0} \\
  \intertext{$F(\v r, \v r')$ erfüllt die vakuum-Feldgleichngug $\Laplace F = 0\to F$ kann benutzt werden, um Randbedingungen zu erfüllen. "Spiegelladungen", Superpositionsprinzip (Elektrodynamik ist linear)}
  \Laplace G(\v r, \v r') &= \Laplace \frac{1}{\abs{\v r - \v r'}} = -4π δ_D(\v r - \v r') \\
  ⇒ ∫ \d^3 r' \Laplace G(\v r, \v r') ρ(\v r') &= \Laplace ∫ \d^3 r' G(\v r, \v r') ρ(\v r') \\
  &= \Laplace ∫ \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}} \\
  &= \Laplace ϕ = -4π ∫ \d^3 r' δ_D(\v r - \v r') ρ(\v r') \\
  &= -4π ρ(\v r) \\
  ⇒ ϕ &= ∫ \d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}} \text{ invertiert } \Laplace ϕ = -4πρ
  \end{align*}
  Konstruktion von Green-Funktionen im Fourier-Raum
  \begin{align*}
  \Laplace ϕ(\v r) &= -4π ρ(\v r) \to \text{Fourier-Transformation (Poisson-Gleichnug ist linear)} \\
  \Laplace ϕ(\v r) &= \Laplace ∫ \d^3 k ϕ(\v k) \exp(i \v k \v r) = ∫ \d^3 k ϕ(\v k) \Laplace \exp(i \v k \v r) \\
  &= ∫ \d^3 k ϕ(\v k) (i \v k)^2 \exp(i \v k \v r) = -4π ∫ \d^3 k ρ(\v k) \exp(i \v k \v r) \\
  ⇒ (i \v k)^2 ϕ(\v k) &= -k^2 ϕ(\v k) = -4π ρ(\v k) \\
  ⇒ ϕ(\v k) &= \frac{4π}{k^2}ρ(\v k)
  \end{align*}
  #+begin_export latex
  \catcode`(=12
  \catcode`)=12
  #+end_export
  \begin{figure}[H]
  \centering
  \begin{tikzpicture}
  \matrix (m) [matrix of math nodes, row sep=4em, column sep=5em, minimum width=3em] {ρ(\v k) & ϕ(\v k) \\ ρ(\v r) & ϕ(\v r)\\};
  \path[-stealth]
  (m-1-1) edge node [above] {$-\frac{1}{k^2}$} (m-1-2)
  (m-1-2) edge node [right] {$\mathcal{F}^{-1}$} (m-2-2)
  (m-2-2) edge node [above] {$\Laplace$} (m-2-1)
  (m-2-1) edge node [left] {$\mathcal{F}$} (m-1-1);
  \end{tikzpicture}
  \end{figure}
  #+begin_export latex
  \catcode`(=\active
  \catcode`)=\active
  #+end_export
  für numerische Berechnungen ist es extrem	vorteilhaft, die Fourier-Methode zu benutzen $\to$ "Fast-Fourier-Transform (FFT)". \\
  Faltung der Ladungsverteilung mit der Green-Funktion $\to$ Multiplikation im Fourier-Raum.
  \[ϕ(\v r) = ∫ \d^3 r' \underarrow[G(\v r, \v r')]{$\displaystyle{\frac{1}{\abs{\v r - \v r'}}}$ für $\Laplace$} ρ(\v r') \to ϕ(\v k) = \underarrow[G(\v k)]{$\displaystyle{-\frac{1}{k^2}}$} ρ(\v k)\]
  Bestimmung von Green-Funktionen aus dem Differenzialoperator.
  \begin{align*}
  \Laplace G(\v r, \v r') &= -4π δ(\v r - \v r') \to \text{ Fourier-Transformation} \\
  \Laplace G(\v r, \v r') &= ∫ \d^3 k G(k) \underbrace{\Laplace \exp(i \v k(\v r - \v r'))}_{\mathclap{= (i \v k)^2 = - k^2 \to G(k) = - \frac{1}{k^2}}} = 4π ∫ \d^3 k \exp(i \v k(\v r - \v r')) \\
  G(\v r, \v r') &= ∫ \d^3 k G(k) \exp(i\v k \v r) ∫ \d^3 k (-\frac{1}{k^2}) \exp(i \v k \v r) \text{ mit } \v r' =	\v 0 \\
  &= ∫ k^2 \d k ∫ \sin θ \d θ ∫ \d φ \frac{1}{k^2} \exp(i k r \cos θ) = 2π ∫ \d k ∫_{-1}^{+1} \d μ \exp(i k r μ) \\
  &= 2π ∫ \d k \sinc(k r) = \frac{2π}{r} ∫ \d y \sinc(y) \\
  &= \frac{1}{r}
  \end{align*}
* Multipolentwicklung
  Idee: Von "weit weg" sieht man nur sphärische Ladungsverteilung. Also zerlege Potenzial in sphärischen Anteil und kleine Korrekturen.
  #+begin_export latex
  \catcode`(=12
  \catcode`)=12
  \begin{center}
  \begin{tikzpicture}
  \wigglecircle{.75}{.25}{20}{0}{0}
  \node at (0,.4) {$ρ(\v r)$};
  \draw[->] (-1,-1) --++(1,1) node[midway,above] {$\v r'$};
  \draw[->] (-1,-1) --++(4,1) node[midway,below] {$\v r$};
  \filldraw (-1,-1) circle (1pt);
  \filldraw (3,0) circle (1pt);
  \draw[domain=15:45,smooth,shift={(-1,-1)}] plot ({.5*cos(\x)},{.5*sin(\x)});
  \node[below right,yshift=3pt] at (-1,-1) {$α$};
  \end{tikzpicture}
  \end{center}
  \catcode`(=\active
  \catcode`)=\active
  #+end_export
  \begin{align*}
  ϕ(\v r) &= ∫ \d^3 r' \frac{ρ(\v r)}{\abs{\v r - \v r'}} \\
  \frac{1}{\abs{\v r - \v r'}} &= \frac{1}{\sqrt{r^2 - 2r r' \cos α + r^2}} \\
  \intertext{mit $μ\cos α$:}
  &= \frac{1}{r} \frac{1}{\sqrt{1 - 2 \frac{r'}{r}μ + (\frac{r'}{r})^2}} \overarrow[=]{Annahme $r > r'$, $\v r$ ist weit weg von der Ladungsverteilung an $\v r'$} \frac{1}{r}(\mathcal{P}_0(μ) + \frac{r'}{r} \mathcal{P}_1(μ) + (\frac{r'}{r})^2 \mathcal{P}_2(μ) + \dots) \\
  &= \sum_{l = 0}^{∞} \frac{r^{l + 1}}{r^{\prime l}} \mathcal{P}_l (μ) \\
  \intertext{$\mathcal{P}_l \sim$ Legendre Polynome, erzeugende Funktion:}
  \frac{1}{\sqrt{1 - 2z x + z^2}} &= \sum_{l} \mathcal{P}_l(x) z^l = \mathcal{P}_0(x) + \mathcal{P}_1(x) z + \mathcal{P}_2(x) z^2 + \dots \\
  \intertext{Durch sukksesives Differenzieren kann man durch auswerten an $z = 0$ die $\mathcal{P}_l$ bestimmen:}
  ⇒ \mathcal{P}_l(μ) &= \frac{1}{2^l l!} \frac{\d^l}{\d μ^l}(μ^2 - 1)^l \tag*{Formel von Rodrigues} \\
  \mathcal{P}_0(μ) &= 1 \\
  \mathcal{P}_1(μ) &= μ \\
  \mathcal{P}_2(μ) &= \frac{1}{2}(3μ^2 - 1) \\
  \mathcal{P}_3(μ) &= \frac{1}{2}(5 μ^5 - 3μ^2) \\
  \intertext{Legendre Polynome sind ein Satz orthogonaler Polynome:}
  ∫_{-1}^{+1} \d μ \mathcal{P}_l(μ) \mathcal{P}_{l'}(μ) &= \frac{2}{2l + 1} δ_{l l'} \\
  \intertext{Additionstheorem: $Y_{lm}$: spärische-harmonische Funktionen}
  \mathcal{P}_l(μ) &= \frac{4π}{2l + 1} \sum_{m = -l}^{l} Y_{lm}(θ, φ) Y_{lm}^{\ast}(θ', φ') \\
  \frac{1}{\abs{\v r- \v r'}} &= \sum_{l} \sum_{m = -l}^{+l} \frac{4π}{2l + 1} \frac{r^{\prime l}}{r^{l + 1}} Y_{lm}(θ,φ) Y^{\ast}_{lm}(θ',φ') \\
  ϕ(\v r) &= ∫\d^3 r' \frac{ρ(\v r)}{\abs{\v r - \v r'}} \\
  ⇒ ϕ(\v r) ∫ \d^3 r' \frac{ρ(\v r)}{\abs{\v r - \v r'}} &= \sum_{l = 0}^{∞} \sum_{m = -l}^{+l} \frac{4π}{2 l + 1} \frac{1}{r^{l + 1}} Y_{lm}(θ, φ) \underbrace{∫ \d^3 r' ρ(\v r ') r^{\prime l} Y^{\ast}_{lm}(θ', φ')}_{q_{lm}} \\
  \intertext{$q_{lm}$: Multipol-Moment}
  \end{align*}
  Beitrag von $q_{lm}$ zu $ϕ$ ist $\propto \frac{1}{r^{l + 1}}$ $⇒$ höhere Multipolmomente haben Beiträge nur auf kleinen Skalen.
  - Monopol: $l = 0 ⇒$ 1 Zahl, $m = 0$
	\[q_{00} = ∫ \d^3 ρ(\v r') r^{\prime 0} Y_{00}(θ',φ') = \frac{1}{\sqrt{4π}} ∫ \d^3 r' ρ(\v r') = \frac{Q}{\sqrt{4π}}\]
  - Dipol $l = 1 ⇒$ 3 Zahlen, $m = -1,0,+1$
  - Oktupol $l = 2 ⇒$ 5 Zahlen, $m = -2,-1,0,+1,+2$
  - Hexadekupol $l = 3 ⇒$ 7 Zahlen, $m = -3,-2,-1,0,+1,+2,+3$
  - \(\)-Multipol $⇒ 2l + 1$ Zahlen, von $-l$ bis $l$
  Hermitizität:
  \[Y_{lm}^{\ast} = (-1)^m Y_{lm}\]
  \begin{align*}
  ⇒ q^{\ast}_{lm} &= ∫ \d^3 r' ρ(\v r') r^{\prime l} Y_{lm}^{\ast}(θ', φ') = (-1)^m ∫ \d^3 r' ρ(\v r') Y_{l,rm}(θ,φ) \\
  q^{\ast}_{lm} &= (-1)^m q_{lm}
  \end{align*}
  Ladungsverteilung $ρ(\v r)$ ist reell $⇒$ nur $l + 1$ unabhängige Momente.
* sphärisch-harmonische Funktionen
  Lineares Funktionensystem auf der Kugel $(θ,φ)$ nach dem alle skalaren Funktionen entwickelt werden können.
  \begin{align*}
  Y_{lm}(θ, φ) &= \sqrt{\frac{2l + 1}{4π}}\sqrt{\frac{(l - m)!}{(l + m)!}} \mathcal{P}_{lm}(\cos θ) e^{i m φ} \\
  Y_{00}(θ, φ) &= \frac{1}{\sqrt{4π}} ⇒ ϕ(\v r) = \frac{Q}{r}, Q = q_{00}, l = m - 0 \\
  Y_{10}(θ, φ) &= \sqrt{\frac{3}{4π}} \cos θ \\
  Y_{11}(θ, φ) &= \sqrt{\frac{3}{8π}} \sin θ e^{i φ} \\
  \intertext{$\mathcal{P}_{lm}(\cos θ)$: assoziierte Legendre Polynome}
  \mathcal{P}_{lm}(μ) &= (-1)^m (1 - μ^2)^{\frac{m}{2}} \frac{\d^m}{\d μ^m} \mathcal{P}_l(μ) \\
  \mathcal{P}_{lm}(μ) &= \frac{(-1)^m}{2^l l!} (1 - μ^2)^{m/2} \frac{\d^{l + m}}{\d μ^{l + m}}(μ^2 - 1)^l \\
  ∫_{-1}^{+1} \d μ \mathcal{P}_{lm}(μ) P_{l'm'}(μ) &= \frac{2}{2l + 1} \frac{(l + m)!}{(l - m)!} δ_{ll'} \\
  \intertext{$⇒$ sphärisch harmonische Funktionen}
  ∫_{0}^{2π} \d φ ∫_{0}^{π} \sin θ \d θ Y_{lm}(θ,φ) Y_{l'm'}^{\ast} (θ,φ) &= δ_{ll'} δ_{mm'} \tag{Orthogonalität} \\
  \sum_{l = 0}^{∞} \sum_{m = -l}^{+l} Y_{lm}(θ,φ) Y^{\ast}_{lm}(θ',φ') &= δ_D(φ - φ')\underbrace{δ_D(\cos θ - \cos θ')}_{= δ_D(θ - θ')} \\
  \mathcal{P}_l(\cos α) &= \frac{4π}{2l + 1} \sum_{m = -l}^{+l} Y_{lm}^{\ast}(θ,φ) Y_{lm}(θ',φ') \\
  \intertext{in karthesischen Koordinaten:}
  q_{10} &= ∫\d^3 r' ρ(\v r) r' Y_{10}(θ', φ') = ∫ \d^3 r' ρ(\v r) r' \frac{3}{4π} \cos θ \\
  q_{11} &= ∫\d^3 r' ρ(\v r) r' Y_{10}(θ', φ') = ∫ \d^3 r' ρ(\v r) r' \frac{3}{8π} \sin θ(\cos φ + i \sin φ) \\
  \intertext{intuitives System, Dipolmoment $\v p = q \v a$}
  ρ(\v r) &= q(δ_D(\v r - \frac{1}{2} \v a) - δ_D(\v r + \frac{1}{2} \v a)) \\
  \v p &= ∫ \d^3 r' ρ(\v r') \v r' = q ∫ \d^3 r'(δ_D(\v r' - \frac{\v a}{2}) - δ_D(\v r' + \frac{\v a}{2}))\v r'= q \v a \tag{Dipolmoment} \\
  q_{10} &= ∫ \d^3 r' δ(\v r) \sqrt{\frac{3}{4π}} r' \cos θ' = \sqrt{\frac{3}{4π}} p_z \\
  q_{11} &= ∫ \d^3 r' δ(\v r) \sqrt{\frac{3}{8π}} r' \sin θ'(\cos φ' + i \sin φ') = \sqrt{\frac{3}{8π}}(p_x + i p_y) \\
  \intertext{Quadrupolmomente ($l = 2$)}
  q_{20} &= ∫ \d^3 r' ρ(\v r') r^{\prime 2} \sqrt{\frac{5}{4π}}(\frac{3}{2} \cos^2 θ' \frac{1}{2}) \\
  q_{21} &= -∫ \d^3 r' ρ(\v r') r^{\prime 2} \sqrt{\frac{15}{8π}} \sin θ \cos θ e^{iφ} \\
  q_{22} &= ∫ \d^3 r' ρ(\v r') r^{\prime 2}	\frac{1}{4} \sqrt{\frac{15}{2π}} \sin^2 θ e^{2iφ}
  \end{align*}
  Monopol:
  #+BEGIN_EXPORT latex
  \catcode`(=12
  \catcode`)=12
  \begin{tikzpicture}
  \node[circle,draw] at (0, 0) {$+$};
  \node at (0, -1.5) {$ϕ \sim \frac{Q}{r}$};
  \end{tikzpicture}
  Dipol
  \begin{tikzpicture}
  \node[circle,draw] at (0, -.5) {$+$};
  \node[circle,draw] at (0, +.5) {$-$};
  \node at (0, -1.5) {$ϕ \sim \frac{Q}{r^2}$};
  \end{tikzpicture}
  Quadropol
  \begin{tikzpicture}
  \node[circle,draw] at (.5, -.5) {$-$};
  \node[circle,draw] at (-.5, .5) {$-$};
  \node[circle,draw] at (-.5, -.5) {$+$};
  \node[circle,draw] at (.5, .5) {$+$};
  \node at (0, -1.5) {$ϕ \sim \frac{Q}{r^3}$};
  \end{tikzpicture}
  Oktopol
  \begin{tikzpicture}
  \node[circle,draw] at (.5, -.5, .5) {$-$};
  \node[circle,draw] at (-.5, .5, .5) {$-$};
  \node[circle,draw] at (-.5, -.5, .5) {$+$};
  \node[circle,draw] at (.5, .5, .5) {$+$};
  \node[circle,draw] at (.5, -.5, -.5) {$+$};
  \node[circle,draw] at (-.5, .5, -.5) {$+$};
  \node[circle,draw] at (-.5, -.5, -.5) {$-$};
  \node[circle,draw] at (.5, .5, -.5) {$-$};
  \node at (0, -1.5) {$ϕ \sim \frac{Q}{r^4}$};
  \end{tikzpicture}
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
#  \begin{align*}
#  \frac{1}{\abs{\v r - \v r'}} &= \frac{1}{\sqrt{r^2 - 2\v r \v r' + \v r^{\prime 2}}} = \frac{1}{r} \frac{1}{\sqrt{1 - 2\frac{r'}{r}μ + (\frac{r'}{r})^2}} \\
#  \intertext{Taylorentwicklung:}
#  &= \frac{1}{r} \sum_{l} (\frac{r'}{r})^l P_l(μ) \\
#  P_l(μ) &= \frac{4π}{2l + 1} \sum_{m = -l}^{+l} Y_{lm}(θ, φ) Y_{lm}(θ', φ')
#  \end{align*}
* Alternativer Zugang zur Multipolentwicklung $\to$ Taylor-Reihe in	kartesischen Koordinaten
  Green-Funktion
  \begin{align*}
  G(\v r') &= \frac{1}{\abs{\v r - \v r'}} \\
  \intertext{Taylorentwicklung bei $\v r' = 0$}
  G(\v r') &= G(\v r ' = \v 0) + \sum_{i} \pp{G}{x'_i}\big|_{\v r' = \v 0} · x_i' + \frac{1}{2!} \sum_{ij} \frac{\partial G}{\partial x_i' \partial x_j'} \big|_{\v r' = \v 0} · x_i' x_j' + \dots \\
  &= \sum_{n} \frac{1}{n!} (\sum_{i} x_i' \pp{}{x_i'})^n G \big|_{\v r' = 0} = \sum_{n} \frac{1}{n!}·(\v r' ∇')^nG \big|_{\v r' = \v 0} \\
  G(\v r') &= \frac{1}{\abs{\v r - \v r'}} = \left[\sum_{i}(x_i - x_i')^2\right]^{-1/2} \\
  G(\v r')\big|_{\v r' = \v 0} &= \frac{1}{r} \\
  \pp{}{x_i'} G(\v r') \big|_{\v r' = \v 0} &= \frac{x_i}{r^3} \\
  \frac{\partial^2}{\partial x_i' \partial x_j'} G(\v r') \big|_{\v r' = 0} &= \frac{3 x_i x_j - r^2 δ_{ij}}{r^5} \\
  ϕ(\v r) &= ∫\d^3 r' ρ(\v r') G(\v r, \v r') \\
  &= ∫ \d^3 r' ρ(\v r') (\frac{1}{r} + \sum_{i} \frac{x_i x_i'}{r^3} + \frac{1}{2} \sum_{ij} \frac{3 x_i x_j - r^2 δ_{ij}}{r^5} x_i' x_j' + \dots) \\
  &= \frac{1}{r} ∫\d^3 r' ρ(\v r') + \sum_{i} \frac{x_i}{r^3} ∫\d^3 r' ρ(\v r') x_i' + \frac{1}{2} \sum_{ij} ∫\d^3 r' ρ(\v r') \frac{3 x_i x_j - r^2 δ_{ij}}{r^5} x_i' x_j' + \dots
  \end{align*}
  \begin{ibox}{Umschreiben des Quadrupolterms}
  Quadrupolterm	$×3$:
  \begin{align*}
  &= \sum_{ij} \frac{3 x_i x_j - r^2 δ_{ij}}{r^5} ∫ \d^3 r' ρ(\v r') 3 x_i' x_j' \underbrace{- r^{\prime 2} δ_{ij} + r^{\prime 2} δ_{ij}}_{= 0} \\
  &= \sum_{ij} \frac{3 x_i x_j - r^2 δ_{ij}}{r^5} (∫ \underbrace{\d^3 r' ρ(\v r')(3x_i' x_j' - r^{\prime 2} δ_{ij})}_{Q_{ij}} + ∫ \d^3 r' ρ(\v r') r^{\prime 2} δ_{ij}) \\
  \intertext{2. Term verschwindet:}
  \sum_{ij} \frac{3 x_i x_j - r^2 δ_{ij}}{r^5} δ_{ij} &= 0 \\
  \circled{1}\quad \sum_{ij} x_i x_j δ_{ij} &= \sum_{i} x_i^2 = r^2 \\
  \circled{2}\quad \sum_{ij} δ_{ij}δ_{ij} &= \sum_{i} δ_{ii} = 3
  \end{align*}
  \end{ibox}
  \[⇒ ϕ(\v r) = \frac{Q}{r} + \frac{\v r \v p}{r^3} + \frac{1}{6} \sum_{ij} Q_{ij} \frac{3x_i x_j - r^2 δ_{ij}}{r^5} + \dots\]
  $Q_{ij} = Q_{ji} ⇒$ symmetrische Matrix $⇒ 6$ Einträge! Aber:	in sphärischen Koordinaten: $q_{-2,-2} q_{2,-1}, q_{2,0}, q_{2,1}, q_{22} ⇒$ 5 Einträge.
  Es gilt: $Q_{ij}$ ist spurfrei:
  \begin{align*}
  \sum_{i} Q_{ij} &= \sum_{i} ∫ \d^3 r' ρ(\v r') (3x_i' x_i' - r^{\prime 2} δ_{ij}) \\
  &= ∫ \d^3 r' ρ(\v r') (3 \sum_{i} x_i^{\prime 2} - r^{\prime 2} \sum_{i} δ_{ii}) = 0
  \end{align*}
* Wechselwirkung einer Ladunsverteilung mit einem externen Feld
  \begin{align*}
  W &= ∫ \d^3 r ρ(\v r) ϕ(\v r) \\
  ϕ(\v r) &= ϕ(\v r = 0) + \sum_{i} x_i \pp{ϕ}{x_i} \big|_{\v r = \v 0} + \frac{1}{2} \sum_{ij} \overarrow[x_i x_j]{Subtraktion von $\Laplace ϕ = 0$, weil die felderzeugende Ladung woanders ist!} \frac{\partial^2 ϕ}{\partial x_i \partial x_j} + \dots \\
  \Laplace ϕ &= \sum_{i} \frac{\partial^2}{\partial x_i^2}ϕ = \sum_{ij} δ_{ij} \frac{\partial^2}{\partial x_i \partial x_j} ϕ \\
  ϕ(\v r) &= ϕ(\v r = 0) + \sum_{i} x_i \pp{ϕ}{x_i} \big|_{\v r = \v 0} + \frac{1}{3!} \sum_{ij}(3x_i x_j - r^2 δ_{ij}) \frac{\partial^2 ϕ}{\partial x_i \partial x_j}\big|_{\v r = 0} + \dots \\
  W &= \underbrace{∫ \d^3 r ρ(r)}_{Q} ϕ(\v r = 0) + \sum_{i} \underbrace{∫ \d^3 r ρ(r) x_i}_{p_i} ·	\pp{ϕ}{x_i}\big|_{\v r = \v 0} + \frac{1}{3!} \sum_{ij} \underbrace{∫\d^3 r ρ(r)(3 x_i x_j - r^2 δ_{ij}) · \frac{\partial^2}{\partial x_i \partial x_j}}_{Q_{ij}} \big|_{\r v = \v 0} + \dots \\
  &= qϕ(\v r = 0) + \v p ∇ ϕ \big|_{\v r = 0} + \sum_{ij} Q_{ij} \frac{\partial^2 ϕ}{\partial x_i \partial x_j} \big|_{\v r = 0} + \dots
  \end{align*}
  $l$ Multipol wechselwirkt mit der \(l\)-fachen Ableitung von $ϕ$.
* Polarisation und Modelle für Dielektrika
  #+BEGIN_EXPORT latex
  \catcode`(=12
  \catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \draw[rotate=-45,black,pattern=north west lines, pattern color=black] (-3,0) ellipse (1 and 1.5) node[above left, xshift=-15pt,yshift=25pt] {Molekül $\v i$};
    \draw[rotate=45,black,pattern=north east lines, pattern color=black] (3,0) ellipse (1 and 1.5) node[above right, xshift=15pt,yshift=25pt] {Molekül $\v j$};
    \filldraw (0,-3) circle (1pt) node[below] {Ursprung};
    \draw[->] (0,-3) -- ++(0,7) node[above] {$P$} node[midway,right] {$\v r$};
    \draw[->] (0,-3) -- ++(2.5,4.5) node[below,midway] {$\v r_j$};
    \draw[->] (0,-3) -- ++(-2.5,4.5) node[below,midway] {$\v r_i$};
    \draw[red,->] (0,-3) ++(2.5,4.5) -- ++(.1,.5) node[right,midway] {$\v r'$};
    \draw[red,->] (0,-3) ++(-2.5,4.5) -- ++(-.1,.5) node[left,midway] {$\v r'$};
    \draw (0,-3) ++(-2.5,4.5) ++(-.1,.5) -- (0,4);
    \draw (0,-3) ++(2.5,4.5) ++(.1,.5) -- (0,4);
    \draw (0,-3) ++(-2.5,4.5) -- (0,4) node[below,midway,xshift=10pt] {$\v r - \v r_i$};
    \draw (0,-3) ++(2.5,4.5) -- (0,4) node[below,midway,xshift=-10pt] {$\v r - \v r_j$};
  \end{tikzpicture}
\end{center}
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
  \begin{align*}
  \intertext{Feld $\v E_j$ an der Stelle $\v r$, hervorgerufen durch Molekül $j$}
  \v E_j(\v r) &= ∫\d^3 r' ρ_j(\v r') \frac{\v r - \v r_j -\v r'}{\abs*{\v r - \v r_j - \v r'}^3} = -∇ ∫\d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r_j - \v r'}} \\
  \intertext{Multipolentwickulng}
  \frac{1}{\abs*{\v r - \v r'_j - \v r'}} &= \frac{1}{\abs{\v r - \v r_j}} + (\v r' ∇_j) \frac{1}{\abs{\v r - \v r_j}} + \frac{1}{2} (\v r' ∇_j)^2 \frac{1}{\abs{\v r - \v r_j}} + \dots \\
  ⇒ \v E_j(\v r) &= -∇(∫ \d^3 r' \frac{ρ_j(\v r')}{\abs{\v r - \v r_j}} + ∫\d^3 r' ρ_j(\v r') \v r' ∇_j \frac{1}{\abs{\v r - \v r_j}} + \dots) \\
  &= -∇(\frac{q_j}{\abs{\v r - \v r_j}} + \v p_j ∇_j \frac{1}{\abs{\v r - \v r_j}} + \dots) \\
  \intertext{Ladungsdichte:}
  ρ(\v r) &= \sum_{j} q_j δ_D(\v r - \v r_j) \\
  \intertext{Polarisationsdichte:}
  \v π(\v r) &= \sum_{j} \v p_j δ_D(\v r - \v r_j) \\
  \intertext{Summation der Felder zum Kontinuums-Limes:}
  \v E(\v r) &= \sum_{j} \v E_j(\v r) = -∇(\sum_{j} \frac{q_j}{\abs{\v r - \v r_j}} + \v p_j ∇_j \frac{1}{\abs{\v r - \v r_j}}) \\
  &= -∇(∫\d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}} + \v π(\v r') ∇' \frac{1}{\abs{\v r - \v r'}}) \\
  \Div \v E &= - \Laplace (∫\d^3 r' \frac{ρ(\v r')}{\abs{\v r - \v r'}} + \v π(\v r) ∇' \frac{1}{\abs{\v r - \v r'}}) \\
  &= -∫ \d^3 r' ρ(\v r') \underbrace{\Laplace \frac{1}{\abs{\v r - \v r'}}}_{\mathclap{-4π δ_D(\v r - \v r')}} + \v π(\v r') \underbrace{∇' \underbrace{\Laplace \frac{1}{\abs{\v r - \v r'}}}_{\mathclap{=-4πδ_D(\v r - \v r')}}}_{\mathclap{ = -∇δ_D(\v r - \v r')}} \\
  \Div \v E &= 4π ∫ \d^3 r' ρ(\v r') δ_D(\v r - \v r') - 4π ∇ ∫ \d^3 r' \v π(\v r') δ_D(\v r - \v r') \\
  \Div \v E &= 4πρ - 4π \Div \v π \\
  \Div \underbrace{(\v E + 4π \v π)}_{\v D} &= 4πρ \\
  \intertext{$\v π$ ist oft abhängig von dem externen Feld (da das externe Feld die Moleküle ausrichtet), dann gilt:}
  \v π &= ϰ \v E, \quad ϰ: \text{ Suszeptibilität} \\
  \v D &= ε \v E, ε = 1 + 4π ϰ
  \end{align*}
\setcounter{part}{23}
\part{orthogonale Funktionensysteme}
* orthogonale Funktionensysteme
  Satz von Funktionen $\{u_1, \dots, u_n(x)\}$. Für komplexe Funktionen definiert
  \[\angl{u_i,u_j} = ∫_A^b \d x u_i(x) u_j^{\ast}(x) = A_i \underarrow[δ_{ij}]{Orthogonalitätsrelation $A_i = 1 ⇒$ orthonormal.}\]
  ein Skalarprodukt.(symmetrisch, bilinear und positiv definit). Norm von $u_i(x):$
  \[∫_a^b \d x u_i(x) u_i^{\ast}(x) = A_i\]
  $⇒$ normalisiere $u_i$:
  \[u_i'(x) = \frac{u(x)}{\sqrt{∫_a^b \d x u_i(x) u_i^{\ast}(x)}}\]
  Bilden die orthonomalen Funktionen eine Basis?
  \begin{align*}
  g(x) &\overset{?}{=} \sum_{i}^{n} g_i u_i(x) \\
  0 &\leq Δn = ∫_a^b \d x \abs{g(x) - \sum_{i}^{n} g_i u_i(x)}^2 \\
  &= ∫_a^b \d x g(x) g^{\ast}(x) - ∫_a^b \d x g(x) \sum_{i} g_i^{\ast} u_i^{\ast}(x) - ∫_a^b \d x \sum_{i} g_i u_i(x) g^{\ast}(x) + ∫_a^b \d x \sum_{ij} g_i u_i(x) g_j^{\ast} u_j^{\ast} \\
  &= ∫_a^b \d x g(x) g^{\ast}(x) - \sum_{i} g_i^{\ast} ∫_a^b \d x g(x) u_i^{\ast}(x) - \sum_{i} g_i ∫_a^b \d x u_i(x) g^{\ast}(x) + \sum_{ij} g_i g_j^{\ast} ∫_a^b \d x u_i(x) u_j^{\ast} \\
  \intertext{Minimierung von $Δn$:}
  \pp{Δ}{g_i} &\overset{!}{=} 0 = g_i^{\ast} - ∫_a^b \d x g^{\ast}(x) u_i(x) \\
  \pp{Δ}{g_i^{\ast}} &= g_i - ∫_a^b \d x g(x) u_i^{\ast}(x) \\
  ⇒ g_i &= ∫_a^b \d x g(x) u_i^{\ast}(x) \\
  \intertext{Minimum:}
  Δ &= ∫_a^b \d x g(x) g^{\ast}(x) - \sum_{i} g_i g_i^{\ast} \\
  \intertext{Konvergenz im quadratischen Mittel}
  \lim_{n \to ∞} Δ_n \big|_{min} &= \lim_{n \to ∞}  ∫_a^b \abs{\sum_{i}^n g_i u_i(x) - g(x)}^2 = 0 \\
  \intertext{Konvergenz gesichert, falls: (Parseval-Reltation/Vollständigkeitsrelation)}
  ∫_a^b \d x g(x) g^{\ast}(x) &= \sum_{i} g_i g_i^{\ast} \\
  \intertext{Bessel-Ungleichnug:}
  ∫_a^b \d x g(x) g^{\ast}(x) &\geq \sum_{i} g_i g_i^{\ast} \\
  \intertext{denn:}
  0 &\leq ∫_a^b \d x \abs{g(x) - \sum_{i}^{n} g_i u_i(x)}^2 \\
  &= ∫_a^b \d x g(x) g^{\ast}(x) - 2 \sum_{i} g_i ∫_a^b \d x g^{\ast}(x) u_i(x) + \sum_{ij} g_i g_j^{\ast} \underbrace{∫_a^b \d x u_i(x) u_i^{\ast}(x)}_{=δ_{ij}} \\
  \intertext{Im Fall $Δn = 0$ für $n \to ∞$:}
  ∫_a^b \d x g(x) g^{\ast}(x) &= \sum_{i}^{n} g_i g_i^{\ast} \\
  \intertext{Was bedeutet das für das Basissystem?}
  \sum_{i} g_i g_i^{\ast} &= \sum_{i} ∫ \d x g(x) u_i^{\ast}(x) ∫ \d x' g^{\ast}(x') u_i(x') \\
  &= ∫_a^b \d x g(x) ∫_a^b \d x' g^{\ast}(x') \underbrace{\sum_{i} u_i^{\ast}(x) u_i(x')}_{δ_D(x - x')} \overset{?}{=} ∫_a^b \d x g(x) g^{\ast}(x) \\
  &= ∫_a^b g(x) ∫_a^b g^{\ast}(x') δ_D(x - x') = ∫_a^b g(x) g^{\ast}(x) \\
  \intertext{dies gilt, wenn: (Anforderung an das Basissystem)}
  \sum_{i} u_i^{\ast}(x) u_i(x') &= δ_D(x - x')
  \end{align*}
  Basissystem muss in der Lage sein, die \(δ_D\)-Funktion darzustellen. \\
  Cauchy-Schwarz-Ungleichung $\sim$ Eindeutigkeit der Linearzerlegung:
  \begin{align*}
  \big{\string(}\sum_{i} a_i b_i\big{\string)}^2 &\leq \sum_{i} a_i^2 \sum_{j} b_j^2 \\
  ⇒ \abs*{\v a \v b}^2 &\leq \v a^2 \v b^2 \\
  \abs*{\v a - λ \v b}^2 &= 0 \quad\text{kann nur } \begin{cases} \text{1 Lösung haben} & \text{falls } \v a \parallel \v b \\ \text{keine Lösung haben} & \text{falls } \v a \not\parallel \v b \end{cases} \\
  &= \v a^2 - 2 λ \v a \v b + λ^2 \v b^2 \\
  ⇒ λ_{\pm} &= 2 \v a \v b \pm \sqrt{4\string(\v a \v b\string)^2 - 4 \v a^2 \v b^2} \\
  \sqrt{4\string(\v a \v b\string)^2 - 4 \v a^2 \v b^2} &\begin{cases} \text{hat eine Lösung} & \text{falls } \string(\v a \v b\string)^2 = \v a^2 \v b^2 \\ \text{hat keine Lösung} & \text{falls } \string(\v a \v b\string)^2 < \v a^2 \v b^2\end{cases} \\
  \intertext{falls $\string(\v a \v b\string)^2 = \v a^2 \v b^2$ ist, sind $\v a \parallel \v b$ und $\v a$ lässt sich durch den Vektor $\v b$ darstellen:}
  \bigg{\string(}∫ \d x g(x) h^{\ast}(x)\bigg{\string)}^2 &\leq ∫_a^b \d x g(x) g^{\ast}(x) ∫_a^b \d x h(x) h^{\ast}(x) \\
  ∫_a^b \d x(g(x) - λ h(x))^2 &= ∫_a^b \d x g(x) g^{\ast}(x) - 2λ ∫_a^b \d x g(x) h^{\ast}(x) + λ^2 ∫_a^b \d x h(x) h^{\ast}(x) \\
  \intertext{dann gleiches Argument}
  \end{align*}
  Mögliche Wahlen von orthonormalen Systemen: \\
  $\Laplace ϕ = \const ϕ$ \\
  Sinus (ungerade) und Konsinus (gerade):
  \begin{align*}
  \frac{1}{π} ∫_{-π}^π \d x \sin(n x) \sin(m x) &= δ_{mn} \\
  \frac{1}{π} ∫_{-π}^π \d x \cos(n x) \cos(m x) &= δ_{mn} \\
  \intertext{$⇒$ orthonormale Funktionen:}
  u_m(x) &= \frac{1}{\sqrt{π}} \sin(m x) \\
  v_m(x) &= \frac{1}{\sqrt{π}} \sin(m x) \\
  \intertext{Man erhält die Fourier-Reihe}
  ⇒ g(x) = \frac{a_0}{2} + \sum_{m = 1} a_m \cos(m x) + b_m \sin(m x) \\
  a_m &= \frac{1}{π} ∫_{-π}^{+π} \d x' g(x') \cos(m x') \\
  b_m &= \frac{1}{π} ∫_{-π}^{+π} \d x' g(x') \sin(m x') \\
  \intertext{Kontinuumslimit}
  ∫_{-∞}^∞ \d x \exp(i k x) \exp(i k' x)^{\ast} &= δ_D(k - k')
  δ_D(x - x') &= \sum_{i} u_i(x) u_i^{\ast}(x') \\
  \text{Wellen } \sum_{n} \cos(n x) \cos(n x') &= δ_D(x - x') \\
  \sum_{n} \exp(i n x) \exp(i n x') &= δ_D(x - x')
  \end{align*}
* Kugelflächenfunktionen (spherical harmonics)
  $\Laplace$ in Kugelkoordinaten (in 3D), Laplace-Gleichung: $\Laplace ϕ = 0$:
  \begin{align*}
  \Laplace ϕ &= \frac{1}{r^2} \pp{}{r}(r^2 \pp{}{r}ϕ) + \frac{1}{r^2 \sin^2 θ} \pp{}{θ}(\sin θ \pp{ϕ}{θ}) + \frac{1}{r^2 \sin^2 θ} \frac{\partial^2}{\partial φ^2} ϕ \\
  \intertext{Separation der Variablen}
  ϕ(r, θ, φ) &= R(r) · Y(θ,φ) \\
  \intertext{Radialteil:}
  \dd{}{r}(r^2 \dd{R}{r}) &= λ R \\
  \intertext{Lösungen:}
  R(r) &= A r^λ + B r^{-(1 + λ)} \\
  \intertext{Winkelteil:}
  \frac{1}{\sin θ} \pp{}{θ} (\sin θ \pp{Y}{θ}) + \frac{1}{\sin^2 θ} \frac{\partial^2}{\partial φ^2} Y &= λ Y \\
  \intertext{Separation:}
  Y(θ,φ) &= P(θ) Q(φ) \\
  \intertext{in \(φ\)-Richtung, harmonische Differentialgleichung:}
  \frac{\d^2 Q}{\d θ^2} &= - m^2 Q \\
  \intertext{in \(θ\)-Richtung}
  λ \sin^2 θ + \frac{\sin θ}{P} \dd{}{θ}(\sin θ \dd{P}{θ}) &= m^2 \\
  \intertext{Wellen in \(φ\)-Richtung, Periodizität $2π$}
  ⇒ Q(φ) &\sim \exp( \pm i m φ)
  \intertext{$λ$ muss gleich $l(l + 1)$ mit $l \geq \abs{m}$ sein, damit Lösungen für $P$ existieren. Substitution $μ = \cos θ \to$ Legendre-Differentialgleichung}
  ⇒ 0 &= (1 - μ^2) \frac{\d^2}{\d μ^2} \underbrace{P_{lm}(μ)}_{\mathclap{\text{assoziirte Legendre Polynome}}} - 2 \dd{}{μ} P_{lm}(μ) + (l(l + 1) - \frac{m^2}{1 - μ^2}) P_{lm}(μ) \\
  \intertext{Zusammensetzen der Winkellösung}
  Y_{lm}(θ,φ) &= \sqrt{\frac{2l + 1}{4π}} \sqrt{\frac{(l - m)!}{(l + m)!}} \underbrace{P_{lm} \cos(θ)}_{= P} \underbrace{\exp(-imφ)}_{= Q} \\
  \text{mit } ∫ \d Ω Y_{lm} Y_{l'm'} &= δ_{ll'} δ_{mm'}
  \end{align*}
\setcounter{part}{1}
\part{Fortsetzung Potentialtheorie}
\setcounter{section}{9}
* Helmholtz-Zerlegung
  $\v X = - ∇ ψ + \rot \v Q \sim$ allgemeine Darstellung eines Vektorfelds $\v X$, mit
  \begin{align*}
  ψ &= \frac{1}{4π} ∫_V \d^3 r' \frac{∇' X(\v r')}{\abs{\v r - \v r'}} - \frac{1}{4π} ∫_{\partial V} \d \v S' \frac{\v X(\v r')}{\abs{\v r - \v r'}} \\
  \v Q &= \frac{1}{4π} ∫_V \d^3 r' \frac{∇' × \v X(\v r')}{\abs{\v r - \v r'}} - \frac{1}{4π} ∫_{\partial V} \d \v S' × \frac{\v X(\v r')}{\abs{\v r - \v r'}} \\
  \intertext{falls $\v X$ schneller als $1/r$ gegen Null strebt:}
  \frac{1}{4π} ∫_{\partial V} \d \v S' × \frac{\v X(\v r')}{\abs{\v r - \v r'}} &\to 0
  \end{align*}
  Greenfunktion von $\Laplace$:
  \begin{align*}
  \Laplace \frac{1}{\abs{\v r - \v r'}} &= - 4π δ_D(\v r - \v r')
  \v X(\v r) &= ∫_V \d^3 r' \v X(\v r') δ_D(\v r - \v r') = \frac{1}{4π} ∫_V \d^3 r' \v X(\v r') \Laplace \frac{1}{\abs{\v r - \v r'}} = - \frac{1}{4π} \Laplace ∫_V \d^3 r' \frac{\v X(\v r')}{\abs{\v r - \v r'}} \\
  \Laplace \v A &= ∇(∇ · \v A) - ∇ × (∇ × \v A) \\
  \to \v X(\v r) &= -\frac{1}{4π} (∇ \Div ∫_V \d^3 r' \frac{\v X(\v r')}{\abs{\v r - \v r'}} + \rot \rot ∫_V \d^3 r' \frac{\v X(\v r')}{\abs{\v r - \v r'}}) \\
  &= - \frac{1}{4π}(∇ ∫_V \d^3 r' \v X(\v r') ∇ \frac{1}{\abs{\v r - \v r'}} + \rot ∫_V \d^3 r' \v X(\v r') × ∇ \frac{1}{\abs{\v r - \v r'}})
  \intertext{Umschreiben von $∇$:}
  ∇ \frac{1}{\abs{\v r - \v r'}} &= \frac{\v r - \v r'}{\abs{\v r - \v r'}^3} = - ∇' \frac{1}{\abs{\v r - \v r'}} \\
  \to \v X(\v r) &= - \frac{1}{4π}(- ∇ ∫_V \d^3 r' \v X(\v r') ∇' \frac{1}{\abs{\v r - \v r'}} - \rot ∫_V \d^3 r' \v X(\v r') × ∇' \frac{1}{\abs{\v r - \v r'}}) \\
  \Div (φ \v X) &= ∇ φ \v X + φ \Div \v X \\
  \rot (φ \v X) &= ∇ φ × \v X + φ \rot \v X = - \v X × ∇ φ + φ \rot \v X \\
  \to \v X(\v r) &= - \frac{1}{4π}\vast{\string(}-∇(- ∫_V \d^3 r' ∇' \frac{\v X(\v r)}{\abs{\v r - \v r'}} - ∫_V \d^3 r' \frac{∇' · \v X(\v r)}{\abs{\v r - \v r'}}) \\
  &\hphantom{{}={}} {+} \rot(∫_V \d^3 r' ∇' × \frac{\v X(\v r')}{\abs{\v r - \v r'}} - ∫_V \d^3 r' \frac{∇' × \v X(\v r')}{\abs{\v r - \v r'}})\vast{\string)} \\
  &= - \frac{1}{4π}\vast{\string(}-∇\Bigg{\string(}- \underbrace{∫_{\partial V} \d \v S' \frac{\v X(\v r')}{\abs{\v r - \v r'}}}_{\to 0} - ∫_V \d^3 r' \frac{∇' · \v X(\v r)}{\abs{\v r - \v r'}}\Bigg{\string)} \\
  &\hphantom{{}={}} {+} \rot\Bigg{\string(}\underbrace{∫_{\partial V} \d \v S' × \frac{\v X(\v r')}{\abs{\v r - \v r'}}}_{\to 0} - ∫_V \d^3 r' \frac{∇' × \v X(\v r')}{\abs{\v r - \v r'}}\Bigg{\string)}\vast{\string)} \\
  \intertext{Die Terme gehen gegen null, weil die Felder in der Elektrodynamik schnell genug abfallen (Fläche $\sim r^2$, Feld $\sim 1/r^2$, mit $1/\abs{\v r - \v r'}$: $\sim 1/r^3$)}
  &= -∇\underbrace{(\frac{1}{4π}  + ∫_V \d^3 r' \frac{∇' · \v X(\v r)}{\abs{\v r - \v r'}} - ∫_{\partial V} \d \v S' \frac{\v X(\v r')}{\abs{\v r - \v r'}})}_{= ψ(\v r)} \\
  \hphantom{{}={}} + \rot \underbrace{(\frac{1}{4π}∫_V \d^3 r' \frac{∇' × \v X(\v r')}{\abs{\v r - \v r'}} - ∫_{\partial V} \d \v S' × \frac{\v X(\v r')}{\abs{\v r - \v r'}})}_{= \v Q(\v r)} \\
  \to \v X &= - ∇ ψ + \rot \v Q \\
  \intertext{Maxwell-Gleichung für eine statische Situation, also $\partial_{ct}(\dots) = 0$}
  \Div \v E &= 4π ρ \\
  \Div \v B &= 0 \\
  \rot \v E &= 0 \\
  \rot \v B &= \frac{4π}{c} \v j \\
  \v E(\v r) &= \frac{1}{4π}\Bigg{\string(}-∇ ∫_V \d^3 r' \frac{\overbrace{\Div' \v E'}^{= 4πρ}}{\abs{\v r - \v r'}} + \rot ∫_V \d^3 r' \frac{\overbrace{\rot' \v E'}^{= 0}}{\abs{\v r -\v r'}}\Bigg{\string)} = - ∇ ∫_V \d^3 r' \frac{ρ(\v r)}{\abs{\v r - \v r'}} = - ∇ ϕ(\v r) \\
  \v B(\v r) &= \frac{1}{4π}\Bigg{\string(}-∇ ∫_V \d^3 r' \frac{\overbrace{\Div' \v B'}^{= 0}}{\abs{\v r - \v r'}} + \rot ∫_V \d^3 r' \frac{\overbrace{\rot' \v B'}^{= \frac{4π}{c} \v j}}{\abs{\v r -\v r'}}\Bigg{\string)} = \rot	\frac{1}{c} ∫ \d^3 r' \frac{\v j(\v r')}{\abs{\v r - \v r'}} = \rot \v A(\v r) \\
  \to \v E &= - ∇ ϕ \\
  \v B &= \rot \v A \\
  \intertext{mit Vektorpotenzial $\v A$:}
  \v A &= \frac{1}{c} ∫ \d^3 r' \frac{\v j(\v r')}{\abs{\v r - \v r'}} \\
  \intertext{und Potenzial $ϕ$:}
  ϕ &= ∫_V \d^3 r' \frac{ρ(\v r)}{\abs{\v r - \v r'}} \\
  \end{align*}
* Biot-Savart-Gesetz
  \begin{align*}
  \v B &= \rot \v A = \frac{1}{c} ∫_V \d^3 r' \v j(\v r') × \frac{\v r - \v r'}{\abs{\v r - \v r'}^3}
  \intertext{und gleichzeitig}
  \Laplace \v A &= -\frac{4π}{c} \v j \\
  \intertext{als Umkehrung, da}
  \rot \v B &= \rot \rot \v A = ∇ \Div \v A - \Laplace \v A = \frac{4π}{c} \v j
  \end{align*}
  Wenn $\Div \v A = 0$, dann komplette Symmetrie zu $ϕ$:
  \begin{align*}
  \Laplace \v A &= - \frac{4π}{c} \v j \\
  \Laplace ϕ &= - 4π ρ \\
  \v A &= \frac{1}{c} ∫ \d^3 r' \frac{\v j'}{\abs{\v r - \v r'}} \\
  ϕ &= ∫ \d^3 r' \frac{ρ'}{\abs{\v r - \v r'}}
  \end{align*}
  $⇒$ Eichtransformation: $\v B$ ändert sich nicht, falls $\v A \to \v A + ∇ χ, χ \sim$ Eichfeld
  \begin{align*}
  \v B &= \rot \v A \to \rot(\v A + ∇ χ) = \rot(\v A + \rot ∇ χ) = \rot \v A = \v B \\
  \intertext{Wahl von $χ$:}
  \Div \v A &\to \Div(\v A + ∇ χ) = \Div \v A + \Laplace χ \overset{!}{=} 0 \\
  \intertext{$⇒$ wähle $\Laplace χ = -\Div \v A$}
  \rot \v B &= \rot \rot \v A = ∇ \Div \v A - \Laplace \v A = ∇ \Div (\v A + ∇ χ) - \Laplace (\v A + ∇ χ) \\
  &= ∇ \Div \v A + ∇ \Div ∇ χ - \Laplace \v A - ∇ \Laplace χ = ∇ \Div \v A - \Laplace \v A \underarrow[=]{$\Laplace ∇ χ = ∇ \Laplace χ$} \rot \v B
  \end{align*}
  Warum ist das möglich? $\Laplace χ = - \Div \v A$ hat eine eindeutige Lösung als Potenzialgleichung, wegen des 1.	Green-Theorems. \\
  Wahl von $\Div \v A =0$: Coulomb-Eichung, physikalische Bedeutung:
  \begin{align*}
  \Div \v A &= \Div \frac{1}{c} ∫ \d^3 r' \frac{\v j}{\abs{\v r - \v r'}} = \frac{1}{c} ∫_V \d^3 r' \v j' ∇ \frac{1}{\abs{\v r - \v r'}} = - \frac{1}{c} ∫_V \d^3 r' \v j' ∇' \frac{1}{\v r - \v r'} \\
  &= \frac{1}{c} ∫_V \d^3 r' \frac{∇' \v j'}{\abs{\v r - \v r'}} = - \frac{1}{c} ∫_V \d^3 r' \frac{\partial_t ρ'}{\abs{\v r - \v r'}} = - \frac{1}{c} \partial_t ∫_V \d^3 r' \frac{ρ'}{\abs{\v r - \v r'}} = - \partial_{ct} ϕ
  \end{align*}
  falls $\Div \v A = 0$ gewählt wird, ist das elektirsche Potenzial	konstant als Folge aus der Kontinuität der Ladung.
  zeitabhängige Maxwell-Gleichungen:
  \begin{align*}
  \Div \v E &= 4π ρ \\
  \Div \v B &= 0 \\
  \rot \v E &= -\partial_{ct} \v B \\
  \rot \v B &= \partial_{ct} \v E + \frac{4π}{c}\v j \\
  \intertext{$\to \v B$ ist ein reines Wirbelfeld, $\v B = \rot \v A \to$ Substitution in die Helmholtz-Zerlegung:}
  \v E &= - ∇ \underbrace{\frac{1}{4π} ∫_V \d^3 r' \frac{\Div' \v E'}{\abs{\v r - \v r'}}}_{= ϕ} + \rot \frac{1}{4π} ∫_V \d^3 r' \frac{\overbrace{\rot' \v E'}^{-\partial_{ct} \v B'}}{\abs{\v r - \v r'}} \\
  \v B &= - ∇ \frac{1}{4π} ∫_V \d^3 r' \frac{\overbrace{\Div' \v B'}^{= 0}}{\abs{\v r - \v r'}} + \rot \frac{1}{4π} ∫_V \d^3 r' \frac{\overbrace{\rot' \v B'}^{\mathclap{= \partial_{ct} \v E' + \frac{4π}{c} \v j'}}}{\abs{\v r - \v r'}} \\
  \intertext{zwei Effekte: $\v E$ und $\v B$ sind gekoppelt und $\v B$ ist immernoch ein reines Wirbelfeld}
  \v B &= \rot \frac{1}{4π} ∫_V \d^3 r' \frac{\rot ' \rot ' \v A}{\abs{\v r - \v r'}} \underarrow[=]{$\rot' \rot' \v A = ∇' \Div' \v A' - \Laplace' \v A' = - \Laplace' \v A'$, mit Coulomb-Eichung} - \rot \frac{1}{4π} ∫_V \d^3 r' \frac{\Laplace' \v A'}{\abs{\v r - \v r'}}	\overarrow[=]{$\Laplace \v A = - \frac{4π}{c} \v j$ in Coulomb-Eichung} \rot \frac{1}{c} ∫_V \d^3 r' \frac{\v j'}{\abs{\v r - \v r'}} = \rot \v A \\
  \intertext{immerhin sind $\v B$ und $\v A$ konsistent zueinander, selbst wenn die Felder zeitabhängig sind.}
  \v E &= - ∇ ϕ + \rot \frac{1}{4π} ∫_V \d^3 r' \frac{\rot' \v E'}{\abs{\v r - \v r'}} = - ∇ ϕ - \rot \frac{1}{4π} ∫_V \d^3 r' \frac{\partial_{ct} \v B}{\abs{\v r - \v r'}} \\
  &= - ∇ ϕ - \frac{\partial_{ct}}{4π} ∫_V \d^3 r' \frac{\rot \v B'}{\abs{\v r - \v r'}} \underarrow[=]{$∫ \d^3 r' \frac{\rot \v B'}{\abs{\v r - \v r'}} = - ∫ \d^3 r' \v B' × ∇ \frac{1}{\abs{\v r - \v r'}} = ∫ \d^3 r' \frac{\rot' \v B'}{\abs{\v r - \v r'}}$} - ∇ ϕ - \frac{\partial_{ct}}{4π} ∫ \d^3 r' \frac{\rot' \v B'}{\abs{\v r - \v r'}} \\
  &= - ∇ ϕ - \frac{\partial_{ct}}{4π} ∫_V \d^3 r' \frac{\rot' \rot' \v A'}{\abs{\v r - \v r'}} \underarrow[=]{$\rot' \rot' \v A = - \Laplace \v a' = \frac{4π}{c} \v j'$} - ∇ ϕ - \partial_{ct} \underbrace{∫_V \d^3 r' \frac{\v j'}{\abs{\v r - \v r'}}}_{= \v A} = - ∇ ϕ - \partial_{ct} \v A \\
  \to \v B &= \rot \v A \\
  \v E &= - ∇ ϕ - \partial_{ct} \v A
  \end{align*}
  Rechnung: in Coulomb-Eichung, aber die Wahl der Eichung beeinflusst die Felder nicht.
* Potenziale und Eichung $\to$ allgemeiner Form
  \begin{gather*}
  \left.
  \begin{matrix}
  \Div \v B = 0 \\
  \rot \v E + \partial_{ct} \v B = 0 \\
  \end{matrix}\right\} \text{homogene Maxwell Gleichungen} \\
  \left.
  \begin{matrix}
  \Div \v E = 4πρ \\
  \rot \v B - \partial_{ct} \v E = \frac{4π}{c} \v j
  \end{matrix}\right\} \text{inhomogene Maxwell Gleichungen} \\
  \intertext{Aus den 2 homogenen Maxwell-Gleichungen:}
  \begin{aligned}
  \Div \v B = 0 &\to \v B = \rot \v A \\
  \rot \v E + \partial_{ct} \v B = 0 &\to \rot(\v E + \partial_{ct} \v A) = 0 \to \v E + \partial_{ct} \v A = - ∇ ϕ \\
  \end{aligned} \\
  \intertext{Aus den 2 inhomogenen Maxwell-Gleichungen:}
  \begin{aligned}
  \Div \v E &= \Div(- ∇ ϕ - \partial_{ct} \v A) = - \Laplace ϕ - \partial_{ct} \Div \v A = 4π ρ \\
  \rot \v B &= \rot \rot \v A = \partial_{ct}(-∇ ϕ - \partial_{ct} \v A) + \frac{4π}{c} \v j \\
  ⇒ \Laplace ϕ + \partial_{ct} \Div \v A &= - 4π ρ \\
  \Laplace \v A - \partial_{ct}^2 \v A &= - \frac{4π}{c} \v j + ∇(\Div \v A + \partial_{ct} ϕ) \\
  \intertext{$⇒$ gekoppelte Gleichungen, Entkopplung durch Eichung!}
  \v B &= \rot \v A \text{ unverändert, falls } \v A \to \v A + ∇ χ \text{, weil } \rot ∇ χ = 0 \\
  \v E &= - ∇ ϕ - \partial_{ct} \v A \text{ impliziert, dass } ϕ \to ϕ - \partial_{ct} χ \\
  \v E &\to - ∇ (ϕ - \partial_{ct} χ) - \partial_{ct}(\v A + ∇ χ) = -∇ϕ - \partial_{ct} \v A = \v E
  \end{aligned}
  \end{gather*}
  Wahl der Eichung zum Entkoppeln der Gleichungen
  \begin{align*}
  \Div \v A + \partial_{ct} ϕ &= 0 \tag{Lorenz-Eichung} \\
  \Laplace ϕ - \partial_{ct}^2 ϕ &= - 4π ρ \\
  \Laplace \v A - \partial_{ct}^2 A &= - \frac{4π}{c} \v j \\
  \end{align*}
* elektromagnetische Wellen
  \begin{align*}
  \Laplace ϕ - \partial_{ct}^2 ϕ &= (∇ - \partial_{ct})(∇ + \partial_{ct})ϕ = - 4π ρ \\
  \Laplace \v A - \partial_{ct}^2 \v A &= (∇ - \partial_{ct})(∇ + \partial_{ct}) \v A = - \frac{4π}{c} \v j
  \end{align*}
  im Vakuum: $ρ = 0, \v j = 0$ \\
  \begin{align*}
  ϕ &= ϕ_0 \exp(\pm i(\v k \v x - ω t)) \\
  \to ∇ ϕ &= \pm i \v k ϕ \\
  \Laplace ϕ &= - \v k^2 \\
  \partial_{ct} ϕ &= \mp i \frac{ω}{c}ϕ \\
  \partial_{ct}^2 ϕ &= - \frac{ω^2}{c^2} ϕ \\
  \Laplace ϕ - \partial_{ct}^2 ϕ &= 0 = (- k^2 + \frac{ω^2}{c^2})ϕ \to ω = \pm ck
  \end{align*}
  analog für
  \[\v A = \v A_0 \exp(\pm i(\v k \v x - ω t))\]
  Phasen- und Gruppengeschwindigkeit:
  \[c_{ph} = \frac{ω}{k} = c = \pp{ω}{k} = c_{gr}\]
  $\to$ identisch, keine Dispersion. \\
  \begin{align*}
  \Laplace ϕ + \partial_{ct} \Div \v A &= -4πρ \\
  \Laplace \v A - \partial_{ct}^2 \v A &= - \frac{4π}{c} \v j + ∇(\Div \v A + \partial_{ct} ϕ) \\
  \intertext{Coulomb-Eichbedingung:}
  \Laplace ϕ &= -4πρ \\
  \Laplace \v A - \partial_{ct}^2 \v A &= - \frac{4π}{c} \v j + ∇ \partial_{ct} ϕ \\
  \end{align*}
  neue Quelle für $\v A$: $\partial_{ct} ∇ ϕ = - \v E$
  \[\Div \v A = \pm i \underbrace{\v k \v A_0}_{= 0} \exp(\pm i(\v k \v x - ω t)) = 0\]
  $\to \v A$ steht (in Coulomb-Eichung)	senkrecht auf der Ausbreitungsrichtung: "transversale Eichung" \\
  $\to ϕ$ wird tatsächlich dann durch die Ladungsverteilung $ρ$ instantan erzeugt.
\part{elektromagnetische Wellen}
* Wellen im Vakuum: $ρ = 0, \vec{j} = 0, ε = μ = 1$
  $\to \Div \v E = 0, \Div \v B = 0, \rot \v E = -\partial_{ct} \v B, \rot \v B = \partial_{ct} \v E$ eine Dualität $\v E \to \v B$ und $\v B \to - \v E$ im Vakuum lässt die Maxwell-Gleichnugen
  invariant.
  \begin{align*}
  \rot \rot \v E &= \underbrace{∇ \Div \v E}_{= 0} - \Laplace \v E = - \partial_{ct} \underbrace{\rot \v B}_{= \partial_{ct}} = - \partial_{ct}^2 \v E \\
  \to \Laplace \v E - \partial_{ct}^2 \v E &= 0 \\
  \text{analog für $\v B$:}\quad \Laplace \v B - \partial_{ct}^2 \v B &= 0 \\
  \intertext{Lösung: mache Ansatz}
  \v E &= \v E_0 \exp(\pm i(\v k \v x - ω t)) \\
  \to \v E &= - k^2 \v E \\
  \partial_{ct}^2 \v E = -(\frac{ω}{c})^2 \v E \\
  \Laplace \v E - \partial_{ct}^2 \v E &= (-k^2 + (\frac{ω}{c})^2) \v E = 0 \to c \abs{k} = \pm ω
  \end{align*}
  Dispersionsfreiheit:
  \begin{align*}
  v_{ph} &= \frac{ω}{k} = c \\
  v_{gr} &= \pp{ω}{k} = c \\
  \to v_{ph} v_{gr} &= c^2
  \end{align*}
  Flächen gleicher Phase:
  \[k x - ω t = k(x - \frac{ω}{k}t) = k(x - ct) = \const \text{ falls } x - ct = \const\]
  elektromagnetische Wellen sind transversal:
  \begin{align*}
  \intertext{aus dem Gauß-Gesetz}
  \Div \v E &= \v k \v E = 0 ⇒ \v k \perp \v E \\
  \intertext{genauso aus der 2. Maxwell-Gleichung}
  \Div \v B &= \v k \v E = 0 ⇒ \v k \perp \v B \\
  \intertext{$\v E$ und \(\v B\)-Felder sind gleichphasig}
  \rot \v E &= \v k × \v E = -\partial_{ct} \v B  ⇒ \v E \perp \v B
  \end{align*}
  $\to \v k, \v B_0$ und $\v E_0$ bilden ein Rechtssystem + $\v E$ und $\v B$ sind gleichphasig.

  Wie schaut das für die Potenziale aus?
  \begin{align*}
  ρ &= 0, \v q = 0 \\
  ϕ &= ϕ_0 \exp(\pm i(\v k \v x - ω t)) \\
  \to (\Laplace - \partial_{ct}^2)ϕ &= (- k^2 + (\frac{ω}{2})^2)ϕ = 0 \quad\text{alles ist völlig analog}
  \end{align*}
* Polarisation
  Superposition von 2 ebenen Wellen *ohne* Phasenverschiebung $\to$ lineare Polarisation:
  \[\left.\begin{matrix} \v E_1 = \v ε_1 \exp(i(\v k \v x - ω t)) \\ \v E_2 = \v ε_2 \exp(i(\v k \v x - ω t))\end{matrix}\right\} \to \v E_1 + \v E_2 = (\v ε_1 + \v ε_2)\exp(i(\v k \v x - ω t))\]
  Superposition von 2 ebenen Wellen *mit* Phasenverschiebung $\to$ zirkulare Polarisation
  \[\left.\begin{matrix} \v E_1 = \v ε_1 \exp(i(\v k \v x - ω t)) \\ \v E_2 = \v ε_2 \exp(i(\v k \v x - ω t - φ_0))\end{matrix}\right\} \to \v E_1 + \v E_2 = (\v ε_1 + i\v ε_2)\exp(i(\v k \v x - ω t))\]
  falls $φ_0 = π/2$: $\exp(i π/2) = i$
* Energietransport durch das elektrische Feld
  \begin{gather*}
  \begin{cases}\rot \v E = - \partial_{ct} \v B \\ \rot \v B = \partial_{ct} \v E + \frac{4π}{c} \v j \end{cases} \\
  \begin{aligned}
  \Div (\v E × \v B) &= \v B \rot \v E - E \rot \v B \\
  \v E \rot \v B &= \v B \rot \v E - \frac{4π}{c} \v j \v E + \v E \partial_{ct} \v E + \v B \partial_{ct} \v B \\
  \underbrace{\frac{c}{4π} \Div(\v E × \v B)}_{\text{Energiefluss}} + \underbrace{\v j \v E}_{\text{Ohm}} &= - \frac{1}{8π} \partial_{t}(\v E^2 + \v B^2) \\
  \intertext{mit}
  W_{el} &= \frac{\v E^2}{8π} = \frac{1}{2} ρ ϕ = \frac{1}{8π}ϕ \Laplace ϕ \\
  W_{mag} &= \frac{\v B^2}{8π}
  \end{aligned} \\
  \to \underbrace{\frac{c}{4π} \Div (\v E × \v B)}_{\text{Energiefluess}} + \overbrace{\v j \v E}^{\mathclap{\text{Ohm-Arbeit}}} = \underbrace{-\partial_{t}(W_{el} + W_{mag})}_{\mathclap{\text{Änderung der Energiedichte}}}
  \end{gather*}
  Poynting-Vektor $\sim$ Energieflussdichte
  \[\v S = \frac{c}{4π} \v E × \v B\]
  ebene Welle: $\v S \parallel \v k, \v k$ steht senkrecht auf $\v E$ und $\v B$ \\
  Ohm-Arbeit $\sim$ Arbeit, die das Feld an der Stromdichte verrichtet: $\v j = σ \v E$ (Ohm-Gesetz mit Leitfähigkeit $σ$)
  \begin{align*}
  ⇒ \v j \v E &= σ \v E^2 \\
  ∫_V \d^3 r \v j \v E &= σ ∫_V \d^3 r \v E^2 = σ E^2 ΔV = σ E^2 A \frac{l^2}{l} = \frac{σ A}{l} (E l)^2 = \frac{U^2}{R}
  \end{align*}
  Erhaltungsgleichung "Poynting-Satz"
  \[\underbrace{∫_{\partial V} \d \v A \v S}_{\mathclap{\text{Energietransport durch $\partial V$}}} = \overbrace{∫_V \d^3 r \v j \v E}^{\mathclap{\text{Ohm-Arbeit in $V$}}} + \underbrace{\dd{}{t} ∫_V \d^3 r (W_{el} + W_{mag})}_{\mathclap{\text{Änderung der Feldenergie in $V$}}}\]
* Implustransport durch das elektromagnetische Feld
  \begin{align*}
  \v F &= q \v e + \frac{1}{c} ∇ × \v B \\
  \intertext{Integriere über kleines Volumen, um die Lorentz-Kraftdichte $\v f$ zu erhalten}
  \to \v f &= ρ \v E + \frac{1}{c} \v j × \v B \\
  ⇒ \v F &= ∫_V \d r^2 \v f = ∫_V \d^3 r (ρ \v E + \frac{1}{c}\v j × \v B) = \dd{}{t} \v p \\
  \to \dd{\v p}{t} &= \frac{1}{4π} ∫_V \d^3 r \Div \v E \v E + \rot \v B × \v B - \partial_{ct} \v E × \v B \\
  \partial_{ct}\v E × \v B &= \partial_{ct} (\v E × \v B) - \v E × \partial_{ct} \v B =	\partial_{ct} (\v E × \v B) - \rot \v E × \v E \\
  \dd{\v p}{t} &= ∫_V \d^3 r(\Div \v E \v E + \Div \v B \v B + \rot \v B × \v B - \v E × \rot \v E - \partial_{ct} (\v E × \v B)) \\
  \to \dd{}{t}(\v p + \frac{1}{c^2} ∫_V \d^3 r \v S) &= \frac{1}{4π} ∫_V \d^3 r(\Div \v E \v E + \Div \v B \v B + \rot \v B × \v B + \rot \v E \v E)
  \end{align*}
  Kann man das Integral auf der rechten Seite auls Divergenz schreiben? \\
  $\to$ ja: Maxwell-Spannungstensor
  \begin{align*}
  \string(\v E \Div \v E\string)_i &= E_i \partial_j E_j \\
  \string(\v E × \rot \v E\string)_i &= ε_{ijk} E_j ε_{klm} \partial_l E_m = ε_{ijk} ε_{klm} E_j \partial_l E_m = (-δ_{il} δ_{jm} + δ_{im} δ_{jl}) E_j \partial_{l} E_m \\
  &= - E_j \partial_i E_j + E_j \partial_j E_i \\
  \to (\Div \v E \v E + \rot \v E × \v E)_i &= E_i \partial_j E_j + E_j \partial_j E_i - E_j \partial_i E_j = \partial_j (E_i E_j) - \frac{1}{2} \partial_i (E_j E_j) = \partial_j (E_i E_j - \frac{1}{2} δ_{ij} E_k E_k) \\
  \to \dd{}{t}(\v p + \frac{1}{c^2} ∫_V \d^3 r \v ρ)_i &= \frac{1}{4π} ∫_V \d^3 r \underarrow[\partial_j]{Divergenz} (E_i E_j + B_i B_j - \frac{1}{2} δ_{ij}(E_k E_k + B_k B_k)) \\
  \intertext{Definiere den Maxwell-Spannungstensor $T_{ij}$:}
  T_{ij} &=	(E_i E_j + B_i B_j - \frac{1}{2} δ_{ij}(E_k E_k + B_k B_k)) \\
  \tr (T_{ij}) &= \sum_{i} T_{ii} = \frac{1}{4π}(\v E^2 + \v B^2 - \frac{3}{2}(\v E^2 \v B^2)) = \frac{\v E^2 + \v B^2}{8π} = - \frac{\v E + \v B}{8π} = -(W_{el} + W_{mag}) \\
  W_{el} + W_{mag} + \tr(T_{ij}) &= 0 = T_{μ}^{μ} \\
  \to \dd{}{t}(p_i + \frac{1}{c^2} ∫ \d^3 r S_i) &= ∫_V \d^3 r \partial_j T_{ij} = ∫_{\partial V} \sum_{j} \d A_j T_{ij} \\
  \end{align*}
  $\d A_j T_{ij}$: Kraft auf ein Oberflächenelement $\d A_j ⇒ T_{ij}$ muss sich wie ein "`Druck"' verhalten $\to$ Analogie zur Fluidmechanik.
* Elektromagnetische Wellen in Materie
  \begin{align*}
  \v D &= ε \v E \\
  \v B &= μ \v H \\
  \v j &= σ \v E \\
  \rot H &= \partial_{ct} \v D + \frac{4π}{c} (\v σ \v E) \\
  \rot \v E &= - μ \partial_{ct} \v H \\
  \Div \v H &= 0 \\
  \Div \v E &= 0 \\
  \to \rot \rot \v H &= ∇ \Div \v H - \Laplace \v H = ε μ \partial_{ct}^2 \v H \\
  \to \rot \rot \v E &= ∇ \Div \v E - \Laplace \v H = ε μ \partial_{ct}^2 \v E \\
  \frac{ε μ}{c^2} \partial_{t}^2 &= \frac{1}{c^{\prime 2}} \partial_{t}^2 \\
  \intertext{man erhält eine effektive Ausbreitungsgeschwindigkeit $c'$:}
  c' &= \frac{c}{\sqrt{ε μ}} \\
  \intertext{definiere Brechungsindex $n$:}
  n &= \frac{c}{c'} = \sqrt{ε μ} \underarrow[\approx]{wenn $μ$ fast immer $\approx$ 1 ist} \sqrt{ε}
  \end{align*}
  man würde erwarten, dass $ε$ und $μ$ frequenzabhängig sind, die molekularen Dipole benögitgen eine gewisse Zeit um
  sich auszurichten: Wasser: $ε \approx 81$, aber $n \simeq 1.3$ für optisches Licht.
  \begin{align*}
  \intertext{für $σ \neq 0, ebene Welle:$}
  \rot \rot \v H &= - \Laplace \v H = ε μ \partial_{ct}^2 \v H + \frac{4π}{c} μ σ \partial_{ct} \v H, \v H = \v H_0 \exp(i(\v k \v x - ω t)) \\
  \rot \rot \v E &= - \Laplace \v E = ε μ \partial_{ct}^2 \v E + \frac{4π}{c} μ σ \partial_{ct} \v E, \v E = \v E_0 \exp(i(\v k \v x - ω t)) \\
  \to \rot \v H &= -i ε \frac{ω}{c} \v E + \frac{4π}{c} σ \v E = -i(ε + \frac{4π σ}{ω}i) \frac{ω}{c} \v E \\
  \intertext{Definiere Permittivität $η$:}
  η :&= ε + \frac{4π σ}{ω}i
  \end{align*}
  Vergleich mit
  \[\rot \v H = - i ε \frac{ω}{c} \v E\]
  ohne Leitfähigkeit. \\
  Dispersion in Materie-Wellen aus den Maxwell-Gleichungen
  \begin{align*}
  \v k × \v H &= - \frac{ω}{c}η \v E \\
  \v k × \v E &= \frac{ω}{c} η \v H	\\
  \v k · \v E &= 0 \\
  \v k · \v B &= 0 \\
  \to \v k × \v k × \v H &= (\v k \v H) \v k - k^2 \v H = - \frac{ω}{c} η \v k × \v E = - (\frac{ω}{c})^2 η \v H \\
  \intertext{man erhält eine komplexe Dispersionsrelation}
  k^2 &= \frac{ω^2}{c^2} η ε(1 + \frac{4π σ}{ω ε}i) \\
  \intertext{allgemeiner Ansatze}
  k &= α + i β \\
  \to k^2 &= α^2 - β^2 + 2 i α β \\
  \to α^2 - β^2 &= μ ε \frac{ω^2}{c^2} \\
  2 α β &= \frac{4π σ}{ω} μ \frac{ω^2}{c^2} \\
  ⇒ α &= \frac{1}{2β}(\frac{4π σ}{ω}μ \frac{ω^2}{c^2}) \\
  \frac{1}{4β^2} (·)^2 - β^2 &= μ ε \frac{ω^2}{c^2} \\
  ⇒ β &= \pm \sqrt{ε μ} \frac{ω}{c} \sqrt{\frac{1}{2}(\sqrt{(\frac{4πσ}{ω ε})^2}) - 1} \\
  ⇒ α &= \pm \sqrt{ε μ} \frac{ω}{c} \sqrt{\frac{1}{2}(\sqrt{(\frac{4πσ}{ω ε})^2}) + 1} \\
  k &= α + i β \to \abs{k} = \sqrt{α^2 - β^2} = \sqrt{εμ} \frac{ω}{c} \sqrt[4]{1 + (\frac{4πσ}{ωε})^2} \\
  φ &= \arctan \frac{β}{α} = \frac{1}{2}(2 \arctan \frac{β}{α}) = \frac{1}{2} \arctan \frac{2 \frac{β}{α}}{1 - \frac{β^2}{α^2}} \\
  &= \dots = \frac{1}{2} \arctan \frac{2α β}{α^2 - β^2} = \frac{1}{2} \arctan(\frac{4πσ}{ωε})
  \intertext{veralgemeinerter Brechungsindex}
  n &= \frac{c}{ω} α + i \frac{c}{ω} β, k = α + i β = \frac{ω}{c}n = \frac{ω}{c}(\Re(n) + i \Im(n)) \\
  \exp(i (\v k \v x - ω t)) &= \exp(i ω (\frac{n x}{c} - t)) \\
  &= \exp(i ω (\Re (n)) \frac{x}{c} - t) \exp(-\frac{ω}{c} \Im(n) x)
  \end{align*}
* Wellengleichungen + retardierte Potentiale: Helmholtz Differentialgleichung
  Verbindung zwischen Potenzialen $ϕ, \v A$ und Quellen $ρ, \v j$
  \begin{align*}
  \string(\Laplace \partial^2_{ct}\string)ϕ &= -4πρ \\
  \string(\Laplace \partial^2_{ct}\string)A &= -\frac{4π}{c}\v q \\
  \intertext{in Lorenzeichung:}
  \Div \v A + \partial_{ct} ϕ &= 0 \\
  \end{align*}
  Definiere neuen Operator: D'Alembert-Operator $\dalem = \Laplace - \partial_{ct}^2 = (∇ + \partial_{ct})(∇ - \partial_{ct})$. \\
  \begin{align*}
  \to \dalem ϕ &= 4πρ \\
  \dalem \v A &= \frac{4π}{c} \v j \\
  \end{align*}
  Änderung in $r, \v j$ pflanzt sich mit Geschwindigkeit $c$ fort $\to$ Potenziale $ϕ, \v A$ können sich im
  Abstand $R$ erst nach $R/c$ ändert. $\to$ zeitabhängige Green-Funktion. \\
  Feldgleichungen haben die Form der Helmholtz-Differentialgleichung:
  \[(\Laplace - \partial_{ct}^2) \underbrace{ψ(\v x, t)}_{\mathclap{\text{Potenzial}}} = - 4π \overbrace{Q(\v x, t)}^{\mathclap{\text{Quelle}}}\]
  Fourier-Entwicklung:
  \begin{align*}
  ψ(\v x, t) &= ∫ \frac{\d ω}{2π} ψ(\v x, ω) e^{-i ω t} \\
  Q(\v x, t) &= ∫ \frac{\d ω}{2π} Q(\v x, ω) e^{-i ω t} \\
  \string(\Laplace - \partial_{ct}^2\string) ψ(\v x, t) &= ∫ \frac{\d ω}{2π} (\Laplace - \partial_{ct}^2) ψ(\v x, ω) e^{- i ω t} \\
  &= ∫ \frac{\d ω}{2π}(\Laplace - (\frac{ω}{c})^2)ψ(\v x, ω) e^{- i ω t} \\
  &= ∫ \frac{\d ω}{2π} (-4π) Q(\v x, ω) e^{- i ω t} \\
  &= - 4π Q(\ x, t) \\
  \intertext{Man erhält die Helmholtz-Differentialgleichnug}
  \to (\Laplace + (\frac{ω}{c})^2) ψ &= - 4π Q(\v x, t) \\
  \end{align*}
  Green-Funktion:
  \[(\Laplace + k^2)G(\v x, \v x') = δ_D(\v x - \v x') δ_D(t - t')\]
  $\sim$ löst Wellengleichung für eine Punktquelle bei $\v x'$ zur Zeit $t'$. \\
  Green-Funktion für die Helmholtz-Differentialgleichung: \\
  keine Randbedingungen: $G(\v x, \v x')$ hängtnur von $r$: $r = \abs{\v x - \v x'}$
  \begin{align*}
  \string(\Laplace + k^2\string) G(\v x, \v x') &= δ_D(\v x - \v x ') = (\Laplace + k^2) G(r) = \frac{1}{r^2} \pp{}{r}(r^2 \pp{G}{r}) + k^2 G = δ_D(r)  \\
  r \neq 0: \frac{\d^2}{\d r^2}(r G) + k^2 (r G) &= 0, \quad\text{denn:} \\
  \frac{1}{r^2} \dd{}{r}(r^2 \dd{G}{r}) &= \frac{1}{r^2}(r^2 \frac{\d^2 G}{\d r^2}) + \frac{2}{r} \dd{G}{r} = \frac{\d G}{\d r^2} + \frac{2}{r} \dd{G}{r} = \frac{1}{r} \frac{\d^2}{\d r^2} (r G) = \frac{1}{r} \dd{}{r}(G + r \dd{G}{r}) \\
  \end{align*}
  Lösung der harmonischen Differenzialgleichnug:
  \begin{gather*}
  r G = a_{+} \exp(i k r) + a_{-} \exp(-i k r) \\
  a_{+} + a_{-} = 1 \to a_{-} = 1 - a_{+}
  \end{gather*}
  für Grenzfall $r \to 0$: $G \sim 1/r$ \\
  \[\to G(r) = G(\abs{\v x - \v x'}) = a_{+} G^{+}(\abs{\v x - \v x'}) + a_{-} G^{-}(\abs{\v x - \v x'})\]
  Falls $r \to 0$:
  \[\frac{1}{r^2} \pp{}{r}( r^2 \pp{G}{r}) + k^2 G = δ_D(r)\]
  Physikalisches Argument: bei kleinen Abständen kann Retardation keine Rolle spielen; die Helmholtz-Differentialgleichung
  muss in Poisson-Differentialgleichung übergehen.
  \begin{align*}
  \lim_{kr \ll 1} G(r) &= -\frac{1}{4π} \frac{1}{r}, \text{ als Lösung von: } \frac{1}{r^2} \pp{}{r}(r^2 \pp{G}{r}) = δ_D(r) \\
  \to G^{+}(\abs{\v x - \v x'}) &= - \frac{1}{4π} \frac{\exp(+ ik \abs{\v x - \v x'})}{\abs{\v x - \v x'}} \\
  \to G^{-}(\abs{\v x - \v x'}) &= - \frac{1}{4π} \frac{\exp(- ik \abs{\v x - \v x'})}{\abs{\v x - \v x'}} \\
  \intertext{volle Green-Funktion inklusive Zeitabhängigkeit:}
  G(\v x, t, \v x', t') &= ∫ \frac{\d ω}{2π} G(\v x, ω, \v x', t') \exp(- i ω t) \\
  \string(\Laplace - \partial_{ct}^2\string) G &= ∫ \frac{\d ω}{2π} (\Laplace + k^2) G \exp(- i ω t) = δ_D(\v x - \v x') ∫ \frac{\d ω}{2π} \exp(- i ω(t - t')) \\
  \to (\Laplace + k^2) G &= δ_D(\v x - \v x') \exp(+ i ω t') \\
  \to G^{\pm}(\v x, t, \v x', t') &= - ∫ \frac{\d ω}{2π} \frac{1}{4π} \frac{1}{\abs{\v x - \v x'}} \exp(- i ω(t - t' \pm \frac{\v x - \v x'}{c})) \\
  &= -\frac{1}{4π} \frac{1}{\abs{\v x - \v x'}} δ_D(t - t' \mp \frac{\abs{\v x - \v x'}}{c}) \\
  ψ^{\pm}(\v x, t') &= -4π ∫ \d t' ∫ \d^3 x' G^{\pm}(\v x, t, \v x', t') Q(\v x', t)
  \end{align*}
  Retardierung:
  \[t = t' + \underarrow[\frac{\abs{\v x - \v x'}}{c}]{zusätzliche Zeit, die das Feld von $\v x$ zu $\v x$ benötigt}\text{ für "`$+$"': } t > t'\]
  #+BEGIN_EXPORT latex
  \catcode`(=12
 \catcode`)=12
 \begin{center}
\begin{tikzpicture}
\draw[->] (-.1,0) -- ++(6.1, 0) node[below] {$x$};
\draw[->] (0,-.1) -- ++(0,6.1) node[left] {$c t$};
\filldraw (4,0) circle (2pt);
\filldraw (0,4) circle (2pt);
\draw (4,0) -- (0,4);
\node[left] at (0,2) {$t - t'$};
\node[below] at (2,0) {$\abs{x - x'}$};
\node[below] at (0,0) {Beobachter};
\node[below] at (4,0) {Ladung};
\draw[dashed] (4,0) -- ++(0,6);
\end{tikzpicture}
\end{center}
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
* Wellenfunktion und retardierte Potenziale: allgemeine	Konstruktion
  Wellengleichung:
  \[(\Laplace - \partial_{ct}^2) ψ = -4π Q(\v x, t)\]
  Green-Funktion für eine Punktquelle an der Stelle $(\v x', t')$
  \begin{align*}
  \string(\Laplace - \partial_{ct}^2\string)G(\v x, t, \v x', t') &= -4π δ_D(\v x - \v x') δ_D(t - t') \\
  \intertext{$G(\v x, t, \v x', t')$ hängt nur von den Koordinatenabständen ab:}
  ρ &= \abs{\v x - \v x'}, \v ρ = \v x - \v x' \\
  τ &= t - t' \\
  \intertext{durch Superposition:}
  ψ(x,t) &=	∫ \d^2 x' ∫ \d t G(\v x, t, \v x', t') Q(\v x', t)
  \end{align*}
  Darstellung von $G$ und $δ$ im Fourier-Raum:
  \begin{align*}
  δ_D(\v x - \v x') δ_D(t - t') &= 4π∫ \frac{\d^3 k}{(2 π)^3} ∫ \frac{\d ω}{2π} \exp(i \v k (\v x - \v x')) \exp(-i ω(t - t')) \\
  G(\v x, t, \v x', t') &= ∫ \frac{\d^3 k}{(2π)^3} ∫ \frac{\d ω}{2π} G(\v k, ω) \exp(i \v k(\v x - \v x')) \exp(- i ω(t - t')) \\
  \intertext{mit $\dalem G = -4π δ_D$}
  \dalem G(\v x, t, \v x', t) &= ∫ \frac{\d^k}{(2π)^3} ∫ \frac{\d ω}{2π} G(\v k, ω) (- k^2 + \frac{ω^2}{c^2}) \exp(i \v k(\v x - \v x')) \exp(-i ω t(t - t')) \overset{!}{=} -4π δ_D \\
  \to G(\v k, ω) &= \frac{1}{4π} \frac{1}{k^2 - (\frac{ω}{c})^2} = \frac{1}{4π}	\frac{c^2}{(c k)^2 + ω^2} \quad\text{nur definiert, falls } c k \neq ω \\
  \to G(\v x, t, \v x', t') &= ∫ \frac{\d^3 k}{(2π^3)} ∫ \frac{\d ω}{2π} \frac{c^2}{(c k - ω)(c k + ω)} \exp(i k(\v x - \v x'))\exp(-i ω(t - t')) \\
  \end{align*}
  \(∫ \d ω\)-Integration hat 2 Pole bei $n = \pm c k \to$ analytische Fortsetzung nach $ℂ$ zum Lösen des $∫ \d ω$ Integrals
  - $G(\v k, z)$ komplex differenzierbar $\sim$ holomorph ($z$: komplexes $ω$)
  - $∮_C \d z G(z) = 0$, falls $G \sim$ holomorph + kein Pol von $C$ umschlossen ist.
  - Pol erster Ordnung an einer Stelle $ξ$:
	\[\lim_{z \to ξ} G(z) (z - ξ) = \Res G(ξ)\]
  - $\displaystyle{∮_C \d z G(z) = 2π i \sum_{n}^{} \Res G(ξ_n)}$ (mit den Polen $ξ_n$ umschlossen von $C$)
  #+BEGIN_EXPORT latex
  \catcode`(=12
  \catcode`)=12
Integration $∫ \d ω$ in der komplexen Ebene
\begin{center}
\begin{tikzpicture}
\draw[->] (-4,0) -- ++(8,0) node[below] {$ℝ$};
\draw[->] (0,-2) -- ++(0,6) node[right] {$iℝ$};
\draw[dashed] (4,0) arc[radius=4cm,start angle=0,end angle=180];
\filldraw (-3,.2) circle (2pt) node[above] {$ω = - c k$};
\filldraw (3,.2) circle(2pt) node[above] {$ω = +c k$};
\draw[->] (-3.5,.2) -- ++(7,0);
\draw[<-] (2.9,2.9) -- ++(.5,.5) node[right,every text node part/.style={align=left}] {Integration kann durch einen\\Halbkreis geschlossen werden.\\Integrand $\sim 1/ω^2$ für große $ω$, Halbkreis $\sim ω$};
\end{tikzpicture}
\end{center}
Integrationsweg für $∫ \d ω \dots$. Möglichkeiten:
\begin{center}
\begin{tikzpicture}
\draw[->] (-3.2,0) -- ++(6.4,0) node[below] {$ℝ$};
\draw[->] (0,-3.2) -- ++(0,6.4) node[right] {$iℝ$};
\draw[-{Latex[length=2mm]}] (3,0) arc[radius=3cm,start angle=0,end angle=45];
\draw[-{Latex[length=2mm]}] (45:3) arc[radius=3cm,start angle=45,end angle=135];
\draw (135:3) arc[radius=3cm,start angle=135,end angle=180];
\draw[-{Latex[length=2mm]}] (-3,0) -- ++(0.5, 0);
\draw[-{Latex[length=2mm]}] (-2.5, 0) -- ++(2.5, 0);
\draw[-{Latex[length=2mm]}] (0,0) -- ++(2.5, 0);
\draw[->] (-2, 0) -- ++(0,.6) node[above,yshift=-6pt] {$×$};
\draw[->] (2, 0) -- ++(0,.6) node[above,yshift=-6pt] {$×$};
\node at (2,-1) {$\neq 0$};
\begin{scope}[shift={(7,0)}]
\draw[->] (-3.2,0) -- ++(6.4,0) node[below] {$ℝ$};
\draw[->] (0,-3.2) -- ++(0,6.4) node[right] {$iℝ$};
\draw[-{Latex[length=2mm]}] (3,0) arc[radius=3cm,start angle=0,end angle=-45];
\draw[-{Latex[length=2mm]}] (-45:3) arc[radius=3cm,start angle=-45,end angle=-135];
\draw (-135:3) arc[radius=3cm,start angle=-135,end angle=-180];
\draw[-{Latex[length=2mm]}] (-3,0) -- ++(0.5, 0);
\draw[-{Latex[length=2mm]}] (-2.5, 0) -- ++(2.5, 0);
\draw[-{Latex[length=2mm]}] (0,0) -- ++(2.5, 0);
\draw[->] (-2, 0) -- ++(0,.6) node[above,yshift=-6pt] {$×$};
\draw[->] (2, 0) -- ++(0,.6) node[above,yshift=-6pt] {$×$};
\node at (2,-1) {$= 0$};
\node at (3, 1.5) {Verschiebung um $-i ε, ε > 0$};
\end{scope}

\begin{scope}[shift={(0,-7)}]
\draw[->] (-3.2,0) -- ++(6.4,0) node[below] {$ℝ$};
\draw[->] (0,-3.2) -- ++(0,6.4) node[right] {$iℝ$};
\draw[-{Latex[length=2mm]}] (3,0) arc[radius=3cm,start angle=0,end angle=45];
\draw[-{Latex[length=2mm]}] (45:3) arc[radius=3cm,start angle=45,end angle=135];
\draw (135:3) arc[radius=3cm,start angle=135,end angle=180];
\draw[-{Latex[length=2mm]}] (-3,0) -- ++(0.5, 0);
\draw[-{Latex[length=2mm]}] (-2.5, 0) -- ++(2.5, 0);
\draw[-{Latex[length=2mm]}] (0,0) -- ++(2.5, 0);
\draw[->] (-2, 0) -- ++(0,-.6) node[below,yshift=+6pt] {$×$};
\draw[->] (2, 0) -- ++(0,-.6) node[below,yshift=+6pt] {$×$};
\node at (2,-1) {$= 0$};
\begin{scope}[shift={(7,0)}]
\draw[->] (-3.2,0) -- ++(6.4,0) node[below] {$ℝ$};
\draw[->] (0,-3.2) -- ++(0,6.4) node[right] {$iℝ$};
\draw[-{Latex[length=2mm]}] (3,0) arc[radius=3cm,start angle=0,end angle=-45];
\draw[-{Latex[length=2mm]}] (-45:3) arc[radius=3cm,start angle=-45,end angle=-135];
\draw (-135:3) arc[radius=3cm,start angle=-135,end angle=-180];
\draw[-{Latex[length=2mm]}] (-3,0) -- ++(0.5, 0);
\draw[-{Latex[length=2mm]}] (-2.5, 0) -- ++(2.5, 0);
\draw[-{Latex[length=2mm]}] (0,0) -- ++(2.5, 0);
\draw[->] (-2, 0) -- ++(0,-.6) node[below,yshift=+6pt] {$×$};
\draw[->] (2, 0) -- ++(0,-.6) node[below,yshift=+6pt] {$×$};
\node at (2,-1) {$\neq 0$};
\node at (3, 1.5) {Verschiebung um $+i ε, ε > 0$};
\end{scope}
\end{scope}
\end{tikzpicture}
\end{center}
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
  1. Integration liefert $= 0$, falls keine Pole umsclossen werden $\to$ würde den Fall $t < t'$ beschreiben $\to$ avancierte Potentiale
  2. Integration liefert $\neq 0$, falls beide Pole umsclossen werden $\to$ würde den Fall $t > t'$ beschreiben $\to$ retardierte Potentiale
  Wert der Integration $\sim$ Summe der Residuen: um Holomorphiegebiet kann die Integrationskontur beliebig verformt werden, das Ergebnis hängt nur von den eingeschlossenen Polen ab.
  Verformung der Integrationskontur:
  #+BEGIN_EXPORT latex
  \catcode`(=12
  \catcode`)=12
 \begin{center}
\begin{tikzpicture}
\draw[->] (-3.2,0) -- ++(6.4,0) node[below] {$ℝ$};
\draw[->] (0,-3.2) -- ++(0,6.4) node[right] {$iℝ$};
\draw[-{Latex[length=2mm]}] (3,0) arc[radius=3cm,start angle=0,end angle=-45];
\draw[-{Latex[length=2mm]}] (-45:3) arc[radius=3cm,start angle=-45,end angle=-135];
\draw (-135:3) arc[radius=3cm,start angle=-135,end angle=-180];
\draw[-{Latex[length=2mm]}] (-3,0) -- ++(0.5, 0);
\draw[-{Latex[length=2mm]}] (-2.5, 0) -- ++(2.5, 0);
\draw[-{Latex[length=2mm]}] (0,0) -- ++(2.5, 0);
\draw[->] (-2, 0) -- ++(0,-.6) node[below,yshift=+6pt] {$×$};
\draw[->] (2, 0) -- ++(0,-.6) node[below,yshift=+6pt] {$×$};
\draw[black!50!white] (-2.7, -.2) -- ++(5.4, 0);
\draw[black!50!white] (2.7,-.2) arc[radius=2.7cm,start angle=0,end angle=-180];
\draw[black!50!white] (-1.76,-.715) arc[radius=0.25cm,start angle=-20,end angle=-340];
\draw[black!50!white] (1.76,-.535) arc[radius=0.25cm,start angle=160,end angle=-160];
\draw[black!50!white] (-1.76,-.715) -- (1.76,-.715);
\draw[black!50!white] (-1.76,-.535) -- (1.76,-.535);
\draw[black!50!white,-{Latex[length=2mm]}] (-1.76,-.535) -- (.125,-.535);
\draw[black!50!white,-{Latex[length=2mm]}] (1.76,-.715) -- (-.125,-.715);
\draw (3, .5) edge[->,out=45, in=135] (5,0.5);
\begin{scope}[shift={(8,0)}]
\draw[->] (-3.2,0) -- ++(6.4,0) node[below] {$ℝ$};
\draw[->] (0,-3.2) -- ++(0,6.4) node[right] {$iℝ$};
\draw[-{Latex[length=2mm]}] (3,0) arc[radius=3cm,start angle=0,end angle=-45];
\draw[-{Latex[length=2mm]}] (-45:3) arc[radius=3cm,start angle=-45,end angle=-135];
\draw (-135:3) arc[radius=3cm,start angle=-135,end angle=-180];
\draw[-{Latex[length=2mm]}] (-3,0) -- ++(0.5, 0);
\draw[-{Latex[length=2mm]}] (-2.5, 0) -- ++(2.5, 0);
\draw[-{Latex[length=2mm]}] (0,0) -- ++(2.5, 0);
\draw[->] (-2, 0) -- ++(0,-.6) node[below,yshift=+6pt] {$×$};
\draw[->] (2, 0) -- ++(0,-.6) node[below,yshift=+6pt] {$×$};
\draw[black!50!white,->] (1.75,-.625) arc[radius=0.25cm,start angle=180,end angle=-180];
\draw[black!50!white,->] (-2.25,-.625) arc[radius=0.25cm,start angle=180,end angle=-180];
\end{scope}
\end{tikzpicture}
\end{center}
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
  \[G(\v x, t, \v x', t') = \frac{c^2}{4π} ∫ \frac{\d^3 k}{(2π)^3} ∫ \frac{\d ω}{2π} \frac{\exp(i \v k ρ + i ω τ)}{(ck)^2 - (ω + i ε)^2}\]
  Anwendung des Residuensatzes:
  \begin{align*}
  c^2 k ^2 - ω^2 - 2 i ε ω + ε^2 &= -(ω^2 + 2 i ε ω - c^2 k^2 - ε^2) = -(ω^2 + 2 i ε ck - c^2 k^2 - ε^2) \\
  &= -(ω + (ck - iε))(ω - (ck -iε)) \\
  ∮_C \d ω \frac{\exp(-iωτ)}{c^2 k^2 - (ω + iε)^2} &= -∮_C \d ω \frac{\exp(-iωτ)}{(ω + (c k - iε))(ω - (c k - iε))}
  \end{align*}
  Dies hat zwei Pole: bei $ω_1 = c k - i ε$ und $ω_2 = - c k - i ε$
  \begin{align*}
  \Res(ω_1) &= c^2 \exp(-iω_1 τ) \lim_{ω \to ω_1} \frac{ω - ck + iε}{c^2 k^2 - (ω + iε)^2} \\
  &= c^2 \exp(-i ω_1 τ) \lim_{ω\to ω_1}  \frac{ω - ck + iε}{(c k + ω + i ε)(ck - ω + iε)} \\
  &= c^2 \exp(- i ω_1 τ) \lim_{ω \to ω_1} \frac{ω - ω_1}{2 ck (ω_1 - ω)} = - \frac{c}{2k} \exp(- i ck τ) \text{ mit $ε \to 0$} \\
  \Res(ω_2) &= \frac{c}{2k} \exp(+ i ck τ) \\
  ∮_C \d ω (\dots) &= -2 π i (\Res(ω_1) + \Res(ω_2)) = -2π(-\frac{c}{2k} \exp(- i c k τ) + \frac{c}{2k} \exp( i c k τ)) = \frac{2π c}{k} \sin(c k τ) \\
  \end{align*}
  Zeitabhängige Green-Funktion
  \[G(\v ρ, τ) = \begin{cases} 0 & t < t' \\ \frac{c}{2π^2} ∫ \frac{\d^3 k}{(2π)^3} \exp(i \v k \v ρ) \frac{\sin(c k τ)}{k} & t > t'\end{cases}\]
  $∫ \d^3 k$: Integration in Kugelkoordinaten;
  \begin{align*}
  \d^3 k &= k^2 \d k \d (\cos θ) \d φ, μ = \cos θ, θ = \angle(\v k, \v ρ), \v k · \v ρ = k ρ \cos θ = k ρ μ, \d φ = 2π \\
  G(\v ρ, τ) &= \frac{c}{π} ∫ k^2 \d k ∫ \d μ \exp(i k ρ μ) \frac{\sin(c k τ)}{k} = \frac{c}{π}∫ k^2 \d k \frac{\sin(c k τ)}{k} ∫_{-1}^{+1} \d μ \exp(i k ρ μ) \\
  &= \frac{2c}{πρ} ∫ \d k \sin(c k τ) \sin(k ρ) \\
  \intertext{Substitution $x = c k \to \d x = c \d k$}
  G(ρ, τ) &= \frac{2}{πρ} ∫ \d x \sin(x τ) \sin(\frac{x}{c} ρ) \\
  &= \frac{1}{πρ} ∫ \d x \cos(τ + \frac{R ρ}{c}) \cos(τ x - \frac{Rρ}{c}) \\
  &= \frac{1}{2πρ} ∫ \d x (\exp(i(τ - \frac{R}{c} ρ)) + \exp(-i(τ - \frac{R}{c}ρ))) \\
  &\hphantom{{}={}}{-} (\exp(i(τ + \frac{R}{c} ρ)) + \exp(-i(τ + \frac{R}{c}ρ))) \\
  &= \frac{1}{ρ} \Big{\string(}δ_D\underarrow[(τ - \frac{ρ}{c})]{$t - t' - \frac{\abs{\v x - \v x'}}{c}$} - δ_D\overarrow[(τ + \frac{ρ}{c})]{$t + t' + \frac{\abs{\v x - \v x'}}{c}$}\Big{\string)} \\
  G(\v x, t, \v x', t') &= \frac{1}{\abs{r - r'}} δ_D(t - t' - \frac{\abs{\v x - \v x'}}{c}) \\
  ψ(\v x, t) &= ∫ \d^3 x' ∫ \d t' \frac{Q(\v x', t')}{\abs{\v x - \v x'}} δ_D(t - t' - \frac{\abs{\v x - \v x'}}{c})
  \end{align*}
  #+BEGIN_EXPORT latex
  \catcode`(=12
  \catcode`)=12
  \begin{center}
  \begin{tikzpicture}
  \draw[->] (-.1,0) -- ++(6.1, 0) node[below] {$ρ$};
  \draw[->] (0,-.1) -- ++(0,6.1) node[left] {$τ$};
  \draw[<->] (4,2) -- (0,4);
  \node[left] at (0,3) {$τ = t - t'$};
  \node[below] at (2,0) {$ρ= \abs{x - x'}$};
  \node[right] at (0,5) {Beobachter};
  \node[right] at (4,5) {Quelle};
  \draw[dashed] (4,0) -- ++(0,6);
  \draw (.1, 2) -- ++(-.2, 0) node[left] {$t'$};
  \draw (.1, 4) ++(-.2, 0) node[left] {$t > t'$};
  \draw[<-] (3.5, 2.25) -- ++(1,.5) node[right] {Retardierung um $\displaystyle{\frac{\abs{\v x - \v x'}}{c}}$};
  \end{tikzpicture}
  \end{center}
  (liefert keinen Beitrag für $t > t'$)
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
\setcounter{part}{24}
\part{Differenziation und Integration komplexer Funktionen}
komplexe Funktionen $z = x + i y \to g(z) = u(x,y) + i v(x, y)$ \\
*Stetigkeit*: $g(z)$ ist stetig in $ξ$, falls für jedes $ε > 0$ ein $δ(ε) > 0$ existiert, sodass aus $\abs{z - ξ} < δ$ folgt $\abs{g(z) - g(ξ)} < ε$. \\
*Differenzierbarkeit*: $g(z)$ ist komplex differenziebar in $ξ$, falls
\[\lim_{z \to ξ} \frac{g(z) - g(ξ)}{z - ξ}\]
existiert und eideutig ist $\equiv$ $\dd{g}{z}\big|_{ξ}$.
Differenziebarkeit von komplexen Funktionen hat viele Aspekte
- komplex differenziebar: $\displaystyle{\dd{g}{z}\big|_ξ}$ existiert und ist eindeutig
- analytisch: Cauchy-Riemann-Differentialgleichungen gelten
- regulär: $\displaystyle{∮_C \d z g(z) = 0}$ für eine geschlossene Kurve $C$
- holomorph: $\displaystyle{∮_C \d z \frac{g(z)}{z - ξ} = g(ξ)}$
* Cauchy-Riemann-Differentialgleichungen
  \begin{align*}
  \dd{g}{z} &= \lim_{Δz \to 0} \frac{g(z + Δ z) - g(z)}{Δz} \text{ muss unabhängig von der Richtung von $Δz$ sein} \\
  \dd{g}{z} &= \lim_{Δz \to 0} \frac{g(z + Δx) - g(z)}{Δx} = \pp{g}{x} \\
  \dd{g}{z} &= \lim_{Δz \to 0} \frac{g(z + iΔy) - g(z)}{iΔy} = \frac{1}{i}\pp{g}{x} \\
  \intertext{mit $g(z) = g(x + iy) = u(x,y) + i v(x,y)$:}
  \pp{g}{x} &= \pp{u}{x} + i \pp{v}{x} = \frac{1}{i} \pp{g}{y} = \frac{1}{i}(\pp{u}{y} + i \pp{v}{y}) = \pp{v}{y} - i \pp{u}{y} \\
  \intertext{Cauchy-Riemann-Differentialgleichungen:}
  \pp{u}{x} &= \pp{v}{y} \\
  \pp{v}{x} &= - \pp{u}{y} \\
  \Big{\string(}\pp{}{x} + i \pp{}{y}\Big{\string)} g &= 0
  \end{align*}
* Linienintegrale
  \begin{align*}
  \intertext{mit Parametrisierung $z(λ)$}
  ∫_C \d z g(z) &= ∫_a^b \d λ g(z(λ)) \dd{z}{λ} \\
  ∫_{-C} \d z g(z) &= ∫_b^a \d λ g(z(λ)) \dd{z}{λ} = - ∫_a^b \d λ g(z(λ)) \dd{z}{λ} = - ∫_C \d z g(z)
  \intertext{geschlossene Kurve: $z(λ = a) = z(λ = b)$. Für analytische Funktionen}
  ∮ \d z g(z) &= ∫_{C_1} \d z g(z) + ∫_{-C_2} \d z g(z) = 0 \\
  \intertext{geschlossene Integrale $= 0 ⇔$ Wegunabhängigkeit $\to$ Cauchy-Theorem}
  ∮ \d z g(z) &= ∮(\d x + i \d y)(u + iv) \\
  &= ∮ (\d x u - \d y v) + i∮(\d x v + \d y u) \\
  \intertext{lustiges Argument: Satz von Stokes}
  \v R &= (u, -v, 0), \v I = (v, u, 0) \quad\text{und}\quad \d \v r = (\d x, \d y, \d z) \\
  ∮_{\partial S} \d z g(z) &= ∮ \d \v r · \v R + i ∮ \d \v r · \v I \\
  \intertext{mit 1. Cauchy-Riemann-Differentialgleichnug:}
  ∮ \d \v r · \v R &= ∫_S \d \v S \rot \v R = - ∫_S \d x \d y (\pp{v}{x} + \pp{u}{y}) = 0 \\
  \intertext{mit 2. Cauchy-Riemann-Differentialgleichnug:}
  ∮ \d \v r · \v I &= ∫_S \d \v S \rot \v R = - ∫_S \d x \d y (\pp{u}{x} - \pp{v}{y}) = 0 \\
  \end{align*}
* Cauchy-Theorem und holomorphe Funktionen
  \[g(z) = \frac{1}{2π} ∮_C \d ξ \frac{g(ξ)}{ξ - z}\]
  Werte von
  \[\frac{g(ξ)}{ξ - z}\]
  auf $C$ ausreichend um $g(z)$ zu bestimmen "holomorph"
  \begin{align*}
  \frac{1}{2πi} ∮_C \d ξ \frac{g(ξ)}{ξ - z} &= \frac{1}{2πi} ∮_C \frac{g(z) + g(ξ) - g(z)}{ξ - z} \\
  &= \frac{1}{2πi} ∮_C \d ξ \frac{g(z)}{ξ - z} + \frac{1}{2πi} ∮_C \d ξ \frac{g(ξ) - g(z)}{ξ - z} \\
  &= \frac{g(z)}{2πi} \underbrace{∮_C \d ξ \frac{1}{ξ - z}}_{1.} + \underbrace{\frac{1}{2πi} ∮_C \d ξ \frac{g(ξ) - g(z)}{ξ - z}}_{2.} \\
  \intertext{1. Integral: $ξ \to ξ - z, \d ξ \to \d(ξ - z)$. Substitution und Integration entlang Einheitskreis} \\
  ∫ \frac{\d ξ}{ξ} &= ∫_0^{2π} \d λ \frac{-\sin λ + i \cos λ}{\cos λ + i \sin λ} = ∫_0^{2π} \d λ \frac{-\sin λ + i \cos λ}{\cos λ + i \sin λ} \frac{\cos λ - i \sin λ}{\cos λ - i \sin λ} \\
  &= ∫_0^{2π} \d λ (- \sin λ \cos λ + \cos λ \sin λ) + i(\sin^2 λ + \cos^2 λ) = 2πi \\
  \intertext{2. Integral}
  \abs{\frac{1}{2πi} ∮_C \d ξ \frac{g(ξ) - g(z)}{ξ - z}} &\leq \frac{1}{2πi} \abs{∮_C \d ξ \frac{\abs{g(ξ) - g(z)}}{ξ - z}} \\
  &\leq \frac{ε}{2πi} \abs{∮_C \frac{\d ξ}{ξ - z}} = \frac{ε}{\abs{2πi}}, \text{ falls $\abs{g(ξ) - g(z)} < ε$ (Stetigkeit)} \\
  \intertext{insgesamt erhält man}
  \frac{1}{2πi} ∮_C \d ξ \frac{g(ξ)}{ξ - z} &= \frac{g(z)}{2πi} 2πi + \frac{ε}{\abs{2πi}} = g(z) \text{ falls $ε$ klein genug gewählt wird}
  \end{align*}
  Verallgemeinerung des Cauchy-Theorems durch Induktion
  \[\frac{\d^n g}{\d z^n} = \frac{n!}{2πi} ∮_C \d ξ \frac{g(ξ)}{(ξ - z)^n}\]
  aus Taylor-Entwicklung
  \[g(z) = g(ξ) + \dd{g}{z}(z - ξ) + \dots\]
* Laurent-Reihen - komplexe Potenzreihen
  #+BEGIN_EXPORT latex
  \catcode`(=12
  \catcode`)=12
\begin{center}
\begin{tikzpicture}
    \begin{scope}[scale = 2, rotate=-45]
        \draw[rounded corners=.1cm] (-.2, 0) arc[radius=2cm, start angle=-84.26, end angle=264.26]
        -- ++(0,.980) arc[radius=1cm, start angle={270 - 11.54}, end angle={-90 + 11.54}] -- cycle;
        \draw[->] (-.2, .2) -- ++(0,.33);
        \draw[->] (-.6, .8) -- ++(0,-.36);
        \draw[->] (1.6, 1.95) -- ++(0,-0.01);
        \draw[->] (-2.4, 2.01) -- ++(0,+0.01);
        \draw[->] (-.37, 3.987) -- ++(+0.01,0);
        \draw[->] (-1.4, 1.95) -- ++(0,-0.01);
        \draw[->] (0.6, 2.01) -- ++(0,+0.01);
        \draw[->] (-.43, 2.958) -- ++(-0.01,0);
        \wigglecircle{.45}{.15}{25}{-.4}{1.93}
        \coordinate (o) at (-.4,1.93);
        \filldraw (o) circle (1pt) node[below right] {$z_0$};
        \draw (o) -- ++(140:1.021) node[above] {$r_1$};
        \draw (o) -- ++(120:2.050) node[pos=.75,right] {$r_2$};
        \draw[dotted] (o) -- ++(60:1.5) coordinate (z);
        \filldraw (z) circle (1pt) node[below right] {$z$};
        \begin{scope}[rotate=8]
        \draw[->] (z) ++ (60:.25) arc[radius=.25cm,start angle=60, end angle=242];
        \draw[->] (z) ++ (60:-.25) arc[radius=.25cm,start angle=240, end angle=422];
        \end{scope}
        \node at ([shift=(160:1.1)] o) {$c_1$};
        \node at ([shift=(110:2.15)] o) {$c_2$};
    \end{scope}
\end{tikzpicture}
\end{center}
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
  \[r_1 < \abs{z - z_0} \equiv r < v_2\]
  \[g(z) = \underbrace{\frac{1}{2πi} ∮_{C_1} \d ξ \frac{g(ξ)}{ξ - z}}_{\mathclap{\text{Cauchy-Theorem: $C_2$ enthält $z$}}\qquad} \overarrow[-]{umgekehrter Umlaufsinn} \underbrace{\frac{1}{2πi} ∮_{C_1} \d ξ \frac{g(ξ)}{ξ - z}}_{\qquad\mathclap{\text{$= 0, C_1$ enthält $z$ nicht, kein Pol}}}\]
  Konstruktion einer Reihe ausgehend von $ξ$ auf $C_1$ (1. Integral):
  \begin{align*}
  \frac{1}{ξ - z} &= \frac{1}{ξ - z_0}\frac{1}{1 - \frac{z - z_0}{ξ - z_0}} \underarrow[=]{geometrische Reihe} \frac{1}{ξ - z_0} \sum_{n} (\frac{z - z_0}{ξ - z_0})^n \\
  q &= \abs{\frac{z - z_0}{ξ - z_0}} = \frac{r}{r_2} < 1 \to \sum_{n} q^n = \frac{1}{1 - q}
  \end{align*}
  Konstruktion einer Reihe ausgehend von $ξ$ auf $C_1$ (2. Integral)
  \begin{align*}
  \frac{1}{ξ - z} &= \frac{1}{z - z_0} \frac{1}{1 - \frac{ξ - z_0}{z - z_0}} = \frac{1}{z - z_0} \sum_{n} (\frac{ξ - z_0}{z - z_0})^n
  \intertext{wieder geometrische Reihe:}
  q &= \abs{\frac{ξ - z_0}{z - z_0}} = \frac{r_1}{r} < 1 \to \sum_{n} q^n = \frac{1}{1 - q} \\
  g(z) &= \frac{1}{2πi} ∮_{C_2} \d ξ g(ξ) \sum_{n} \frac{(z - z_0)^n}{(ξ - z_0)^{n + 1}} - \frac{1}{2πi} ∮_{C_1} \d ξ g(ξ) \sum_{n} \frac{(ξ - z_0)^n}{(z - z_0)^{n - 1}} \\
  &= \sum_{n} (z - z_0)^n \underbrace{\frac{1}{2πi}	∮_{C_2} \d ξ \frac{g(ξ)}{(ξ - z_0)^{n + 1}}}_{= a_{-(n + 1)}} - \sum_{n} (z - z_0)^{-(n + 1)} \underbrace{\frac{1}{2πi} ∮_{C_1} \d ξ g(ξ) (ξ - z_0)^n}_{= a_n} \\
  \to g(z) &= \sum_{n = -∞}^{+∞} a_n (z - z_0)^n \quad\text{Laurent-Reihe}
  \intertext{mit den Koeffizienten}
  a_n &= \frac{1}{2πi} ∮_C \d ξ g(ξ) (ξ - z_0)^{-(n + 1)} \\
  \intertext{falls $n = -1$:}
  a_{-1} &= \frac{1}{2πi} ∮_{C_2} \d ξ g(ξ) = \Res g(z_0) \quad\text{"`Residuum"'}
  \intertext{egal ob Integral über $C_1$ oder $C_2$, beide enthalten Punkte $z_0$}
  \to g(z) &= - \dots - \frac{a_{-n}}{(z - z_0)^n} - \dots - \frac{a_{-1}}{z - z_0} + a_0 + a_1(z - z_0) + \dots + a_n (z - z_0)^n + \dots
  \end{align*}
  falls die Laurent-Reihe bei einem $n$ abbricht, spricht man von einen Pol der Ordnung $n$.
* Residuensatz $\to$ Berechnung von $a_{-1}$
  \begin{align*}
  \intertext{wir nehmen eine Reihe, die bei $n$ abbricht}
  g(z) &= - \frac{a_{-n}}{(z - z_0)^n} - \dots - \frac{a_{-1}}{z - z_0} + a_0 + a_1 (z - z_0) + \dots \\
  g(z) (z - z_0)^n &= - a_n - \dots - a_{-1} (z - z_0)^{n - 1} + a_0 (z - z_0) + \dots \\
  \frac{\d^{n - 1}}{\d z^{n - 1}} (g(z) (z - z_0)^n) &= \underbrace{0 - \dots -}_{\text{alle } = 0} \underbrace{a_{-1} (n - 1)!}_{\text{endlich}} + \underbrace{a_0 (z - z_0)^n (n - 1)!}_{= 0 \text{ falls } z = z_0} + \dots \\
  \to a_{-1} &= \frac{1}{(n - 1)!} \frac{\d^{n - 1}}{\d z^{n - 1}} ((z - z_0)^n g(z))\big|_{z = z_0} \\
  \text{anstatt } a_{-1} &= \frac{1}{2πi} ∮_C \d ξ g(ξ)
  \end{align*}
  Berechnung von Residuen: $g(z) = 1/z$ (Klassiker) an der Stelle $0$:
  \begin{align*}
  ∮_C \d ξ g(ξ) &= ∮_C \frac{\d ξ}{ξ} = i ∫_0^{2π} \d λ \frac{\exp(iλ)}{\exp(iλ)} = 2πi \quad\text{(oder kartesisch)} \\
  a_{-1} &= \frac{1}{(n - 1)!} \frac{\d^{n - 1}}{\d z^{n - 1}}((z - z_0)^n g(z)) \big|_{z = z_0} \\
  \intertext{Potenzen von $z$ zum "`Killen"' der Singularität}
  n = 1: &\frac{1}{0!} \frac{\d^0}{\d z^0}(z \frac{1}{z}) \big|_{z = 0} = 1 \\
  n = 2: &\frac{1}{1!} \frac{\d^1}{\d z^1}\underbrace{(z^2 \frac{1}{z})}_{= z}\big|_{z = 0} = 1 \\
  n = 3: &\frac{1}{2!} \frac{\d^2}{\d z^2}\underbrace{(z^3 \frac{1}{z})}_{= z^2}\big|_{z = 0} = 1\,\checkmark \\
  \end{align*}
* Laplace-Gleichungin 2D
  Komplexe Funktion $g(z) = u(x + i y) + i v(x + i y)$
  \begin{align*}
  \frac{\partial^2 u}{\partial x^2} &\underarrow[=]{Cauchy Riemann 1} \pp{}{x} \pp{v}{y} \overarrow[=]{$\partial_x \partial_y = \partial_y \partial_x$} \pp{}{y} \pp{v}{x} \underarrow[=]{Cauchy Riemann 2} - \frac{\partial^2 u}{\partial y^2} \to \underbrace{(\frac{\partial^2}{\partial x^2} + \frac{\partial^2}{\partial y^2})}_{= \Laplace \text{ in 2D}} u = 0 \\
  \frac{\partial^2 1}{\partial x^2} &\underarrow[=]{Cauchy Riemann 2} \pp{}{x} (-\pp{u}{y}) \overarrow[=]{$\partial_x \partial_y = \partial_y \partial_x$} -\pp{}{y} \pp{u}{x} \underarrow[=]{Cauchy Riemann 2} - \frac{\partial^2 v}{\partial y^2} \to \underbrace{(\frac{\partial^2}{\partial x^2} + \frac{\partial^2}{\partial y^2})}_{= \Laplace \text{ in 2D}} v = 0 \\
  \end{align*}
  Anwendung in Potezialproblemen mit Dirilecht-Randbedingungen: $u = \const = ϕ$. Abbildungen für "komplexe" Geometrie. \\
  $\Laplace ϕ = 0$ ist in 2D invariant unter Abbildungen
  \begin{equation*}
  \begin{matrix}
  z = x + i y \xrightarrow{g} W = u + i v \\
  z = G(w) \xrightarrow{}[G] W = g(z) \\
  \end{matrix} : g(x,y) = G(u(x,y),v(x,y))
  \end{equation*}
  $g$ ist analytisch (Cauchy-Riemann-Differentialgleichungen gelten) und umkehrbar
  \begin{align*}
  \pp{g}{x} &= \pp{u}{x} \pp{G}{u} + \pp{v}{x} \pp{G}{v} \\
  \frac{\partial^2 g}{\partial x^2} &= \pp{}{x}(\pp{u}{x} \pp{G}{u}) + \pp{}{x}(\pp{v}{x} \pp{G}{v}) \\
  &= (\pp{u}{x})^2 \frac{\partial^2 G}{\partial u^2} + \pp{u}{x} \pp{v}{x} \frac{\partial^2 G}{\partial u \partial v} + \frac{\partial^2 u}{\partial x^2} \pp{G}{u} \\
  &\hphantom{{}={}}{+} (\pp{v}{x})^2 \frac{\partial^2 G}{\partial v^2} + \pp{v}{x} \pp{u}{x} \frac{\partial^2 G}{\partial u \partial v} + \frac{\partial^2 v}{\partial x^2} \pp{G}{v} \\
  \pp{g}{y} &= \pp{u}{y} \pp{G}{u} + \pp{v}{y}\pp{G}{v} \\
  \frac{\partial^2 g}{\partial y^2} &= \pp{}{y}(\pp{u}{y} \pp{G}{u}) + \pp{}{y}(\pp{v}{y} \pp{G}{v}) \\
  &= (\pp{v}{x})^2 \frac{\partial^2 G}{\partial u^2} + \pp{v}{y} \pp{u}{y} \frac{\partial^2 G}{\partial u \partial v} + \frac{\partial^2 u}{\partial y^2} \pp{G}{u} \\
  &\hphantom{{}={}}{+} (\pp{v}{y})^2 \frac{\partial^2 G}{\partial v^2} + \pp{u}{y} \pp{v}{y} \frac{\partial^2 G}{\partial u \partial v} + \frac{\partial^2 v}{\partial y^2} \pp{G}{v} \\
  \frac{\partial^2 g}{\partial x^2} + \frac{\partial^2 g}{\partial y^2} &= \frac{\partial^2 G}{\partial u^2}((\pp{u}{x})^2 + (\pp{u}{y})^2) + \frac{\partial^2 G}{\partial v^2}((\pp{v}{x})^2 + (\pp{v}{y})^2) \\
  &\hphantom{{}={}}{+} 2 \frac{\partial^2 G}{\partial u \partial v} \underbrace{\bigg{\string(}\pp{u}{x} \overbrace{\pp{v}{x}}^{= - \partial u / \partial y} + \pp{u}{y} \overbrace{\pp{v}{y}}^{\mathclap{= \partial u/\partial x}}\bigg{\string)}}_{\to 0} \\
  &\hphantom{{}={}}{+} \pp{G}{u}\underbrace{\bigg{\string(}\overbrace{\frac{\partial^2 u}{\partial x^2}}^{\mathclap{= - \frac{\partial^2 v}{\partial x \partial y}}} + \overbrace{\frac{\partial^2 u}{\partial y^2}}^{\mathclap{= - \frac{\partial^2 v}{\partial x \partial y}}}\bigg{\string)}}_{\to 0} + \pp{G}{v}\underbrace{\bigg{\string(}\overbrace{\frac{\partial^2 v}{\partial x^2}}^{\mathclap{= - \frac{\partial^2 u}{\partial x \partial y}}} + \overbrace{\frac{\partial^2 v}{\partial y^2}}^{\mathclap{= - \frac{\partial^2 u}{\partial x \partial y}}}\bigg{\string)}}_{\to 0} \\
  &= ((\pp{u}{x})^2 + (\pp{u}{y})^2)(\frac{\partial^2 G}{\partial u^2} + \frac{\partial^2 G}{\partial v^2})
  \end{align*}
  $\Laplace g = 0 \to \Laplace G = 0$, Laplace-Gleichung wird in dem Koordinaten $z$ und $ω$ gelöst.
\setcounter{part}{2}
\part{Fortsetzung elektromagnetische Wellen}
\setcounter{section}{7}
* Dispersion von Wellen
  Dispersionsrelation von Wellen in einem Medium:
  \[ω(k) = \frac{ck}{u(k)}, k(ω) = \frac{ω}{n(ω) c}\]
  $\to$ Phasengeschwindigkeit: $\displaystyle{v_{ph} = \frac{ω(k)}{k} = \frac{c}{u(k)}}$
  \begin{align*}
  \to \text{ Gruppengeschwindigkeit: } v_{gr} &= \pp{ω}{k} = (\pp{k}{ω})^{-1} = (\pp{}{ω} (\frac{n(ω) ω}{c}))^{-1} \\
  &= (\pp{u}{ω} \frac{ω}{c} + \frac{n(ω)}{c})^{-1} \\
  v_{gr} &= \frac{c}{n(ω) + ω \pp{u}{ω}}
  \end{align*}
  Normale Dispersion:
  \[\dd{u}{ω} > 0 \to \dd{ω}{k} < \frac{ω}{k}\]
  alles in Ordnung, Energiefluss ist langsamer als $c$.
* Liénard-Wiechert-Potential
  retardierte Potenziale von Punktladungen \\
  #+BEGIN_EXPORT latex
  \catcode`(=12
  \catcode`)=12
  \begin{minipage}{.45\textwidth}
  \begin{align*}
  ρ(\v r, t) &= q δ_D(\v r - \v r_0(t)) \\
  \v j(\v r, t) &= q\v v(t) δ_D(\v r - \v r_0(t))
  \end{align*}
  \end{minipage}\hfill
  \begin{minipage}{.45\textwidth}
  \begin{center}
\begin{tikzpicture}
\filldraw (0,0) circle (1pt) coordinate (o);
\filldraw (2,1) circle (1pt) coordinate (l) node[below right] {Ladung};
\draw[->] (o) -- (l) node[midway,below right,yshift=2pt,xshift=-2pt] {$\v r_0(t)$};
\draw[->] (l) -- ++(1.5, .2) node[right] {$\v v(t)$};
\coordinate (b) at (1.5, 3);
\node[above] at (b) {Beobachter};
\draw[->] (o) -- (b) node[midway,above] {$\v r(t)$};
\draw[->] (l) -- ($(l)!.5!(b)$) node[right] {$\v u$};
\draw[dotted] (l) -- (b);
\end{tikzpicture}
\end{center}
  \end{minipage}
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
  \begin{align*}
  ϕ(\v r, t) &= q ∫ \d t' ∫ \d^3 r' \frac{1}{\abs{\v r - \v r'}} δ_D(\v r' - \v r_0) δ_D(t' - t + \frac{\abs{\v r - \v r'}}{c}) \\
  \text{aus } ψ(\v r, t) &= ∫ \d t' ∫ \d^3 r' \frac{Q(\v r', t')}{\abs{\v r - \v r'}} δ_D(t - t' - \frac{\abs{\v r - \v r'}}{c}) \\
  ϕ(\v r, t) &= q ∫ \d t \frac{1}{\abs{\v r - \v r_0(t')}} δ_D \underbrace{(t - t' + \frac{\abs{\v r - \v r_0(t')}}{c})}_{\equiv u} \\
  \dd{u}{t'} &= 1 - \frac{\v u(t') \v v(t')}{c} \text{ mit } \v u(t') = \frac{\v r - \v r_0(t')}{\abs{\v r - \v r_0(t')}}
  \intertext{fixiert $u = 0$ oder $t = t' + \abs{r - r_0}/c$}
  \d t' &= \frac{\d u}{1 - \frac{\v u(u) · \v v(u)}{c}} \\
  ϕ(\v r, t) &= q ∫ \d u \frac{1}{\abs{\v r - \v r_0(u)}} \frac{1}{1 - \frac{\v u(u) · \v v(u)}{c}} δ(u) \text{ Feld einer bewegten Punktladung}
  \end{align*}
  Ausdurck für die retardierten Potenziale
  \begin{align*}
  ϕ(\v r, t) &= q \frac{1}{\abs{\v r - \v r_0(t')}} \frac{1}{1 - \frac{\v u(t') · \v v(t')}{c}}\Big|_{t' = t - \frac{\abs{\v r - \v r_0(t')}}{c}} \\
  \v A(\v r, t) &= q \frac{\v v(t)}{c} \frac{1}{\abs{\v r - \v r_0(t')}} \frac{1}{1 - \frac{\v u(t') · \v v(t')}{c}} \Big|_{t' = t - \frac{\abs{\v r - \v r_0(t')}}{c}}
  \end{align*}
* Hertz-Dipol $\to$ Feld eines zeitabhängigen Dipols
  kleine Umformung der Liénard-Wiechert-Potentiale
  \begin{align*}
  ϕ(\v r, t) &= \frac{q}{\abs{\v r - \v r_0(t')} - \frac{\v r - \v r_0(t')}{\abs{\v r - \v r_0(t')}} \frac{\v v(t')}{c}}\Big|_{t' = t - \frac{\abs{\v r - \v r_0(t')}}{c}} \\
  A(\v r, t) &= \frac{q \frac{\v v(t')}{c}}{\abs{\v r - \v r_0(t')} - \frac{\v r - \v r_0(t')}{\abs{\v r - \v r_0(t')}} \frac{\v v(t')}{c}}\Big|_{\underbrace{t' = t - \frac{\abs{\v r - \v r_0(t')}}{c}}_{\mathclap{\text{Bedingung für die retardierte Zeit implizit gegeben}}}} \\
  \end{align*}
  #+BEGIN_EXPORT latex
  \catcode`(=12
  \catcode`)=12
\begin{center}
\begin{tikzpicture}
\filldraw (0,-1.5) circle (1.5pt) coordinate (n) node[right] {$-$};
\filldraw (0,+1.5) circle (1.5pt) coordinate (p) node[right] {$+$};
\draw[<->] (n) -- ++(0,4) node[right] {$z$};
\draw (-2, 0) -- ++(2,0);
\draw[->] (0,0) -- ++(2,0) node[right] {$x,y$};
\filldraw (25:2) circle (1pt) coordinate (b);
\draw[->] (0,0) -- (b) node[midway,below right,yshift=4pt] {$\v r$} node[right] {Beobachter};
\draw (0,.5) arc[radius=.5cm, start angle=90, end angle=25] node[midway,above] {$θ$};
\draw[->] (-.3, 0) -- ++(0,-1.5) node[left,midway] {$\displaystyle{+\frac{\v r_0}{2}}$};
\draw[->] (-.3, 0) -- ++(0,1.5) node[left,midway] {$\displaystyle{-\frac{\v r_0}{2}}$};
\node[right] at (0,-.75) {$\v p$};
\draw[<-] (0,-1.55) ++ (.2,.2) -- ++(1,.5) node[right] {negative Ladung};
\draw[<-] (0,+1.45) ++ (.2,.2) -- ++(1,.5) node[right] {positive Ladung};
\end{tikzpicture}
\end{center}
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
  \[q \v v(t) = - \frac{q}{2} \dot{\v r_0} + \frac{q}{2}(- \dot{\v r_0}) = - q \dot{\v r_0} = \dot{\v p}\]
  mit Dipolmoment $\v p = - q \dot{\v r_0}$. Kanonische Schwingung mit der Frequenz:
  \[\frac{v}{c} = \frac{2 r_{0,\text{max}}}{Δ t c} = \frac{r_{0,\text{max}} ω}{π c} \to \frac{v}{c} = \frac{2}{λ} r_{0,\text{max}}\]
  #+BEGIN_EXPORT latex
  \begin{minipage}{.45\textwidth}
  \begin{gather*}
  \begin{cases}
  Δ \v r_{-}(t') = \v r - \frac{1}{2} \v r_0(t') \\
  Δ \v r_{+}(t') = \v r + \frac{1}{2} \v r_0(t')
  \end{cases} \\
  \begin{cases}
  Δ \v r_{-}(t') + \v r_{+}(t') = 2 \v r \\
  Δ \v r_{-}(t') - \v r_{+}(t') = -\v r_0 \\
  \end{cases}
  \end{gather*}
  \end{minipage}\hfill
  \begin{minipage}{.5\textwidth}
  \catcode`(=12
  \catcode`)=12
  \begin{center}
\begin{tikzpicture}
\draw[->] (0, 0) -- ++(0,-1) node[left,midway] {$\displaystyle{+\frac{\v r_0}{2}}$};
\draw[->] (0, 0) -- ++(0,1) node[left,midway] {$\displaystyle{-\frac{\v r_0}{2}}$};
\draw[->] (-1,0) -- ++(4,0) node[right] {$x,y$};
\draw[->] (0,-2) -- ++(0,4) node[right] {$z$};
\filldraw (2.5, 1.55) circle (.5pt) coordinate (r) node[right] {$\v r$};
\draw[dashed] (0,0) -- (r);
\draw[dashed] (0,-1) -- (r) node[midway,below right,yshift=5pt] {$Δr_{-}$};
\draw[dashed] (0,1) -- (r) node[midway,above] {$Δ r_{+}$};
\end{tikzpicture}
\end{center}
  \catcode`(=\active
  \catcode`)=\active
\end{minipage}
  #+END_EXPORT
  Substitution in die Ausdrücke für die Liénard-Wiechert-Potentiale
  \begin{align*}
  ϕ(\v r, t) &= \frac{-q}{Δ \v r_{-}(t') - \frac{Δ \v r_{-}(t')}{\abs{Δ \v r_{-}(t')}} \frac{\dot{\v r_0}(t')}{2c}}\Big|_{t' = t - \frac{\abs{Δ \v r_{-}(t')}}{c}} + \frac{-q}{Δ \v r_{+}(t') - \frac{Δ \v r_{+}(t')}{\abs{Δ \v r_{+}(t')}} \frac{\dot{\v r_0}(t')}{2c}}\Big|_{t' = t - \frac{\abs{Δ \v r_{+}(t')}}{c}} \\
  \v A(\v r, t) &= \text{ analoger Ausdruck mit Strom } \pm q \frac{\dot{\v r_0}}{2c} = \v j
  \end{align*}
  - falls der Beobachter *weit* von der Quelle entfernt ist, gilt
    \[Δ \v r_{\pm} = \v r \pm \frac{1}{2} \v r_0 \approx \v r\]
	überall, wo $Δ r_{\pm}$ vorkommt. $\to$ Skala: Dipol $\v r_0$; Abstand $\gg$ Länge des Dipols.
  - langsame Bewegung des Dipols $\frac{v}{c} \ll 1$ (wegen der $\dot{\v r_0}$ im Zähler) $\to$ Skala
	\[λ = \frac{2π}{ω}c \ll r_0\]
	Wellenlänge $\ll$ Länge des Dipols
	\[\v A(\v r, t) = \frac{-q \frac{\dot{\v r_0}(t')}{c}}{\abs{r}} = \frac{\dot{\v p}(t')}{cr}\Big|_{t' = t - \frac{\abs{\v r}}{c}}\]
	weil:
	1. $\abs{Δ \v r_{-}} = \abs{Δ \v r_{+}} \approx r$ und
	2. $\dot{\v r_0}$ im Zähler Terme der Ordnung $(\frac{v}{c})^2$ erzeugt.
  Lorenz-Eichbedingung: $\Div \v A + \partial_{ct} ϕ = 0 \to$
  \begin{align*}
  \partial_{ct} ϕ &= - \Div (\frac{\dot{\v p}(t - \frac{r}{c})}{c r}) \\
  ϕ &= - ∫ \d t \Div (\frac{\dot{\v p}(t - \frac{r}{c})}{r}) = - \Div(\frac{1}{r} ∫ \d t \dot{\v p}(t - \frac{r}{c})) = -\Div (\frac{\v p}{r}) \\
  &= \overbrace{\frac{\dot{\v p} \v r}{cr^2}}^{\propto \frac{1}{r}} + \underbrace{\frac{\v p \v r}{r^3}}^{\propto \frac{}{r^2}} \\
  \v p(t(\v r)), t(r) &= t - \frac{\abs{\v r}}{c} \\
  ∇ \v p &= \pp{t}{r} \pp{\v p}{t} = \frac{1}{c} \frac{\v r}{r} \dot{\v p}
  \end{align*}
  \begin{minipage}{.45\textwidth}
  Nahbereich um den Dipol \\
  $r \ll λ$
  \[ϕ = \frac{\v p · \v r}{r^3}, \quad\frac{\dot{\v p} \v r}{c r^2} \text{ vernachlässigt}\]
  Dipolpotenzial mit $ϕ \sim 1/r^2$ proportional zu $\v p$
  \end{minipage}\hfill
  \begin{minipage}{.45\textwidth}
  Fernbereich um den Dipol \\
  $r \gg λ$
  \[ϕ = \frac{\dot{\v p} \v r}{c r^2}, \quad \frac{\v p \v r}{r^3}\text{ vernachlässigt}\]
  zeitabhängiger Dipol mit $ϕ \sim 1/r$ proportional zu $\dot{\v p}$
  \end{minipage}
  Felder: $\v B = \rot \v A$ und $\v E = - \partial_{ct} \v A - ϕ$. Nach längerer Rechnung erhält man
  \begin{align*}
  \v E &= - \frac{\ddot{\v p}}{c^2 r} - \frac{\dot{\v p}}{cr} + \frac{3(\dot{\v p} · \v r) \v r}{c r^4} + \frac{(\ddot{\v p}) \v r}{c^2 r^3} + \frac{3(\v p \v r) \v r}{r^5} - \frac{\v p}{r^3} \\
  \v B &= \frac{\ddot{\v p} × \v r}{c^2 r^2} + \frac{\dot{\v p} × \v r}{c r^3}
  \end{align*}
  Es existiert kein statischer Anteil in $B$! \\
  Nahbereich (keine Retardierung $\to$ Feld folgt instantan)
  \begin{align*}
  \v E &= \frac{3(\v p \v r)\v r}{r^5} - \frac{\v p}{r^3} \\
  \v B &= \frac{\dot{\v p} × \v r}{c r^3}
  \end{align*}
  Fernbereich (führende Terme in $1/r$):
  \begin{align*}
  \v E &= - \frac{\ddot{\v p}}{cr} + \frac{(\ddot{\v p} · \v r) \v r}{c^2 r^3} = \frac{1}{c^2 r^3} (\ddot{\v p} × \v r) × \v r \quad\text{wegen Grassman-Identität} \\
  \v B &= \frac{\ddot{\v p} × \v r}{c^2 r^2} \\
  \to \v E &= \frac{\v B × \v r}{r}
  \end{align*}
  wechselseitig	orthogonal im Fernbereich. Felder $\sim 1/r \to$ Energiedichte $\sim 1/r^2$ \\
  Poynting-Vektor des Hertz-Dipols $\to$ Energietransport.
  \[\v S = \frac{c}{4π} \v E × \v B = \frac{c}{4π}(\v B × \frac{\v r}{r}) × \v B = \frac{c}{4π}(\v B^2 \frac{\v r}{r} - \frac{\v B \v r}{r} \v B)\]
  Orthogonalität: $\v B \v r = 0$ im Fernbereich
  \[\v S = \frac{c}{4π} \v B^2 \frac{\v r}{r} = \frac{c}{4π} \frac{(\ddot{\v p} × \v r)^2}{c^4 r^4} \frac{\v r}{r} = \frac{\abs{\ddot{\v p}}^2}{4π c^3 r^2} \sin^2 θ\]
  Nahbereich: Orthogonalität nicht gegeben: \\
  #+BEGIN_EXPORT latex
  \begin{minipage}{.45\textwidth}
  \begin{align*}
  \v S &= \frac{c}{4π}(\frac{3(\v p \v r) \v r}{r^5} - \frac{\v p}{r^3}) × (\frac{\dot{\v p} × \v r}{c r^3}) \\
  &= \frac{1}{4π r^8}(3(\v p · \v r) \v r - r^2 \v p) × (\dot{\v p} × \v r) \\
  &= \frac{1}{4π r^8}\string(3(\v p · \v r) \v r (r^2 \dot{\v p} - (\v r \dot{\v p}) \v r) \\
  &\hphantom{{}={}}{-} r^2 ((\v r · \v p)\dot{\v p} - (\v p · \dot{\v p}) \v r)\string) \\
  &= \frac{1}{4π r^8} (2(\v p · \v r) r^2 \dot{\v p} \mp p \dot p r^2(3 \cos θ + 1) \v r)
  \end{align*}
  \end{minipage}\hfill
  \begin{minipage}{.45\textwidth}
  \begin{center}
  \catcode`(=12
  \catcode`)=12
\begin{tikzpicture}
\draw[->] (-1,0) -- ++(4,0) node[right] {$x,y$};
\draw[->] (0,-2) -- ++(0,4) node[right] {$z$};
\filldraw (0,-1) circle (1.2pt);
\filldraw (0,1) circle (1.2pt);
\node[left] at (0,.65) {$\v p$};
\filldraw (0,0) -- (30:2.8) circle (.5pt) coordinate (r) node[right] {$\v r$};
\draw (0,.5) arc[radius=.5cm, start angle=90, end angle=30] node[midway,above] {$θ$};
\draw[->] (0,0) -- ++(0,-2) node[below,align=left] {keine Strahlung um\\ die Dipolachse!};
\end{tikzpicture}
  \catcode`(=\active
  \catcode`)=\active
\end{center}
  \end{minipage}
  #+END_EXPORT
  abgestrahlte Energie: Integration über eine Kugel mit Radius $R$
  \begin{align*}
  E &= \frac{1}{Δ t} ∫_0^{Δ t} \d t ∫ \d Ω R^2 S = \frac{1}{Δ t} ∫_0^{Δ t} \d t ∫_{-1}^{+1} \d μ \underbrace{∫_0^{2t}\d φ}_{=2π} \frac{\ddot p^2}{4π c^3 R^2} \underbrace{(1 - μ^2)}_{\sin^2 θ} R^2 \\
  &= \frac{1}{Δt} ∫_0^{Δ t} 2π · \frac{\ddot p^2}{4π c^3} ∫_{-1}^{+1} \d μ (1 - μ^2) \\
  &= \frac{2}{3 c^3} \frac{1}{Δt} ∫_0^{Δ t} \d t \ddot p^2 \\
  \intertext{falls $p = p_0 \sin(ω t) ⇒ \ddot p = - p_0 ω^2 \sin(ω t)$}
  E &= \frac{2}{3 c^3} p_0^2 ω^4 \frac{1}{Δt} ∫_0^{Δt} \d t \sin(ω t)^2 = \frac{p_0^2 ω^4}{3c^2} \quad\text{Rayleigh-Streuung + Himmelblau.}
  \end{align*}
\part{Lorentz-Geometrie und spezielle Relativität}
* Lorentz- und Galilei Transformationen
  Transformationen müssen lienar sei, falls sie die Homogenität des Raums (beziehungsweise der Raumzeit) erhalten sollen
  \[\text{2 Bezugssysteme } \begin{cases} S: (t, x^i) = x^{μ} \\ S': (t', x^{\prime i}) = x^{\prime μ}\end{cases}\]
  $S \xleftrightarrow{lineare Transformationen} S'$
  - eine Uhr bewegt sich frei durch $S$ und $S'$: Trajektorie $x^i(τ)$, Geschwindigkeit $\partial_τ x^i = \const$, "Inertialsystem"
  - $τ$ ist die von der Uhr angezeigte Zeit $\sim$ Eigenzeit
  - Homogenität: gleiche Zeitintervalle $\dd{t}{τ}$ überall
	\begin{align*}
	\dd{x^{μ}}{τ} &= \const \to	\frac{\d^2 x^μ}{\d τ^2} = 0 \quad\text{,genauso in $S'$:}\quad \frac{\d^2 x^{\prime μ}}{\d τ^2} = 0 \\
	\dd{x^{\prime μ}}{τ} &= \underbrace{\dd{x^{\prime μ}}{x^{ν}}}_{\mathclap{\text{Jacobi-Matrix}}} \dd{x^ν}{\d τ} \to \frac{\d^2 x^{\prime μ}}{\d τ^2} = \underbrace{\pp{x^{\prime μ}}{\d x^ν}}_{\mathclap{\text{Jacobi-Matrix}}} \frac{\d^2 x^ν}{\d τ^2} + \frac{\partial^2 x^{\prime μ}}{\partial x^ν \partial x^σ} \dd{x^ν}{\d τ} \dd{x^σ}{τ}
	\intertext{Falls die Terme mit zwei Ableitungen nach verschiedene Richtungen $= 0$ sind, ist die Transformation linear. Nur lineare Transformationen können die Homogenität erhalten:}
	⇒ \frac{\partial^2 x^{\prime μ}}{\partial x^ν \partial x^σ} &= 0 \to \pp{x^{\prime μ}}{x^ν} = a^μ ν \to x^{\prime μ} = a^{μ} ν x^ν + b^μ
   	\end{align*}
* allgemeinste lineare Transformationen	zwischen 2 Bezugssystemen
  #+BEGIN_EXPORT latex
  \catcode`(=12
  \catcode`)=12
\begin{center}
\begin{tikzpicture}
\draw[->] (-.2, 0) -- ++(2.2,0) node[below] {$x$} node[above right, xshift=-6pt] {$x = vt ⇔ x' = - vt'$};
\draw[->] (0,-.2) -- ++(0,2.2) node[right] {$S:(t,x^i) = x^μ$};
\draw[dotted] (2,0) -- ++(6,0);
\begin{scope}[shift={(6,0)}]
\draw[->] (-.2, 0) -- ++(2.2,0) node[below] {$x'$};
\draw[->] (0,-.2) -- ++(0,2.2) node[right] {$S':(t',x') = x^{\prime μ}$};
\end{scope}
\end{tikzpicture}
\end{center}
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
  $S$ und $S'$ bewegen sich mit der Relativgeschwindigkeit $v$. Allgemeiner Ansatz für eine lineare Transformation
  1. $x' = a x + b t$, aber $x = vt$ bedeutet $x' = 0$:
	 \[x' = 0 = a v t + b t = (a v + b) t\]
	 $\to$ $b = - av$, also $x' = a(x - vt)$
  2. $x = a x' + bt'$, aber $x' = - vt$ bedeutet $x = 0$:
	 \[x = 0 = - av x' + bt' = (-av + b) t'\]
	 $\to$ $b = + av$, also $x = a(x' + vt')$
  2 Möglichkeiten: \\
  \begin{minipage}{.45\textwidth}
  \textbf{Galilei} universelle Zeit $t = t'$
  \[\begin{cases} x' = a(x - vt) \\ x = a(x' + vt) & \text{falls } t = t'\end{cases}\]
  nur konsistent falls $a = 1$:
  \[\begin{cases} x' = x - vt \\ x = x' + vt\end{cases}\]
  \end{minipage}\hfill
  \begin{minipage}{.45\textwidth}
  \textbf{Lorentz}: universelle Lichtgeschwindigkeit \\
  $x = ct$ und $x' = c t'$
  \[\begin{cases} ct = a(ct' + vt') \\ ct' = a(ct - vt)\end{cases} \qquad (\ast)\]
  \end{minipage}
  \linebreak
  Multiplikation beider Gleichungen in $(\ast)$
  \begin{align*}
  c^2 tt' &= a^2 (c t' + vt')(c t - v t) = a^2 t t' (c + v)(c - v) = a^2 tt' (c^2 - v^2) \\
  a &\equiv γ= \sqrt{\frac{c^2}{c^2 - v^2}} = \frac{1}{\sqrt{1 - \frac{v^2}{c^2}}} = \frac{1}{\sqrt{1 - β^2}} \text{ ,mit } β = \frac{v}{c}
  \end{align*}
  #+BEGIN_EXPORT latex
  \catcode`(=12
  \catcode`)=12
\begin{center}
\begin{tikzpicture}
\draw[->] (-.2, 0) -- ++(6.2,0) node[below] {$β$};
\draw[->] (0,-.2) -- ++(0,4.2) node[left] {$γ$};
\draw[domain=0:1.938,smooth,samples=100] (0,0) plot ({2.5*\x},{1/sqrt(1 - (\x/2)^2)});
\draw[dashed] (5,4) -- ++(0,-4) node[below] {$1$};
\draw[<-] (4.9,4.1) -- ++(1,.2) node[right] {divergiert mit $β \to 1$};
\end{tikzpicture}
\end{center}
  \catcode`(=\active
  \catcode`)=\active
  #+END_EXPORT
  \[β\ll 1: \qquad γ \simeq 1 + \underbrace{\pp{γ}{β}\Big|_{β = 0}}_{= 0} β + \frac{1}{2} \underbrace{\frac{\partial^2 γ}{\partial β^2} \Big|_{β = 0}}_{=1} β^2 + \dots = 1 + \frac{β^2}{2}\]
  Standardform der Lorentz-Transformation
  \begin{align*}
  x' &= γ(x - v t) = γ(x - β ct) \\
  c t' &= γ(c t - β x)
  \end{align*}
  (aus $x' = γ(x - vt)$ und $x = γ(x' + v t')$ durch Eliminieren von $x'$, mit $\displaystyle{\frac{1 - γ^2}{γ} = - β^2}$)
  Matrix-Schreibweise
  \[\underbrace{\cvec{ct';x'}_{x^{\prime μ}}} = \underbrace{\begin{pmatrix} γ & - γ β \\ - γ β & y\end{pmatrix}}_{Λ^μ_ν} \underbrace{\cvec{c t; x}}_{x^ν}\]
  $\sim$ gemeinsame Transformation von $x$ und $t$ \\
  $c \simeq \SI{3e8}{\meter\per\second}$, "Lichtgeschwindikgeit" $\sim$ naja, können wir jetzt noch nicht wissen! \\
* Lorentz-Invarianten
  Idee: Rotation lassen $x_i x^i = x^2$ invariant
  \begin{align*}
  \string(c t'\string)^2 - x^{\prime 2} &= γ^2 ((ct)^2 - 2ct β x + β^2 x^2 - x^2 + 2 x β c t - β^2 c^2 t^2) \\
  &= γ^2 ((ct)^2 (1 - β^2) - x^2(1 - β^2)) \\
  &= γ^2 (1 - β^2) ((ct)^2 - x^2) = \frac{1}{\sqrt{1 - β^2}^2}(1 - β^2) ((ct)^2 - x^2) = ((ct)^2 - x^2)
  \end{align*}
  $s^2 = (ct)^2 - x^2$ ist invariant unter Lorentz-Transformationen. Minkowski-Metrik
  \[η_{μν} = \begin{pmatrix} 1 & & & 0 \\ & -1 & & \\ & & -1 & \\ 0 & & & -1\end{pmatrix}\]
  \begin{align*}
  s^2 &= η_{μν} x^μ x^ν = x_μ x^μ \quad\text{mit}\quad x_μ = η_{μ ν} x^ν \\
  s^2 &= η_{μν} x^μ x^ν = c^2 t^2 - \underbrace{x_i x^i}_{\mathclap{\text{invariant unter Rotation}}} \sim \text{identisch in allen Systemen}
  \end{align*}
* Rapidität und hyperbolische Rotation
* Vergleicht zwischen Lorentz-Transformationen und Drehungen
* Symmetrie der Raumzeit
* Additionstheorem für Geschwindigkeiten
* relativisitsche Effekte
* Eigenzeitintegral
  \begin{align*}
  \d s^2 &= η_{μν} \d x^μ \d x^ν
  \intertext{mit $x^μ = \cvec{c t; x^i}$}
  &= c^2 \d t^2 - \d x_i \d x^i = c^2 \d t^2 \tag{Eigenzeit}
  \end{align*}
  \(4\)-Geschwindigkeit: Tangente an der Weltlinie $x^μ(τ)$
  \begin{align*}
  u^μ(τ) &= \dd{}{τ} x^μ	= \dd{t}{τ} \dd{}{t} x^μ = γ \cvec{c;v^i} \\
  η_{μν} u^μ u^ν &= γ^2 (c^2 - v_i v_i) = c^2  γ^2 (1 - β^2) = c^2 \tag{Normierung} \\
  \to c^2 \d τ^2 &= c^2 \d t^2 - \d x_i \d x^i \\
  \d τ &= \sqrt{\d t^2 - \frac{\d x_i \d x^i}{c^2}} = \sqrt{1 - \frac{1}{c^2}\frac{x_i}{\d t}\frac{\d x^i}{\d t}} \d t \\
  &= \sqrt{1 - β^2} \d t = \frac{\d t}{γ} \\
  \end{align*}
  Zeitintervall, das von der Uhr angezeigt wird:
  \[Δτ = ∫_A^B \d τ = ∫_A^B \frac{\d t}{γ}\]
  \begin{align*}
  S &= - m c ∫ \d s = - m c ∫ \d t \sqrt{η_{μν} \dd{x^μ}{t} \dd{x^ν}{t}} = - m c ∫ \d t \sqrt{c^2 - v_i v^i} \\
  &= - m c^2 ∫ \d t \sqrt{1 - \frac{v_i v^i}{c^2}} \approx ∫ \d t \underbrace{\frac{m}{2} v_i v^i}_{\mathclap{T \sim \text{ kinetische Energie}}} + \const
  \end{align*}
  *relativistische Bewegung* \\
  klassische Mechanik $\mathcal{L}(x_i \dot x_i) = \frac{1}{2} \dot x_i \dot x^i - ϕ(x_i)$ \\
  invariante Langrange-Funktion $\xrightarrow{\text{Variation}}$ kovariante Bewegungsgleichung
  Variation $δ S = 0 \to \ddot x^i = - \partial^i ϕ$
  - keine offensichtliche Interpretation von $\mathcal{L}$ oder $S$
  - $\mathcal{L}$ oder $S$ nicht messbar
  - Invarianz $\to$ Kovariant-Argument funktioniert nicht:
	\[\dot x_i \to \dot x_i + v_i, \mathcal{L} \to \frac{1}{2}(\dot x_i + v_i)(\dot x^i + v^i) = \overbrace{\frac{1}{2} \dot x_i \dot x^i}^{= \mathcal{L}} + \underbrace{\dot x_i v^i + \frac{1}{2} v_i v^i}_{\mathclap{\dd{}{t}(x_i v^i + \frac{1}{2} v_i v^i t)}}\]
  $\to$ wir brauchen eine Lorentz-invariantet relativisitsche Lorentz-Funktion
  - $\mathcal{L}$ soll konvex sein
  - Legendre-Transformation $\displaystyle{\mathcal{H} = \dot x^i \pp{\mathcal{L}}{\dot x^i} - \mathcal{L}}$
  - $\mathcal{H}$ ist dann nach unten beschränkt
  - am besten aus maximal ersten Ableitungen
	\begin{align*}
	\mathcal{L} &= \mathcal{L}(x_i \dot x_i, \ddot x_i, \dots) \\
	δ S &= 0 = ∫ \d t (\pp{\mathcal{L}}{x}δ x^i + \pp{\mathcal{L}}{x_i}δ \dot x_i + \pp{\mathcal{L}}{\ddot x_i} δ \ddot x_i + \dots) \\
	\dd{}{t}(\mathcal{L} - \dot x_i \pp{\mathcal{L}}{\dot x_i}) = \pp{\mathcal{L}}{x_i} \dot x^i + \pp{\mathcal{L}}{\dot x^i} \ddot x^i + \dots - \ddot x^i \pp{\mathcal{L}}{x_i} - \dot x^i \dd{}{t} \pp{\mathcal{L}}{x^i} = 0 \text{ für } \mathcal{L} = \mathcal{L}(x^i, \dot x^i)
   	\end{align*}
  Idee: klasische Lagrange Funktion $\to$ relativistische Eigenzeit?
  - intuitiv (kein Unterschie von Fermat und Hamilton)
  - messbar
  - Lorentz-invariant
  - konvex
  - Möglichkeit zur Einbeziehung der Gravitation
  \begin{align*}
  S &= - m c ∫ \d s = - m c^2 ∫ \d τ = - m c^2 ∫ \frac{\d t}{γ}
  \intertext{vergleiche mit mit}
  S &= ∫ \d t \mathcal{L} \\
  \to \mathcal{L}(\dot x) &= - \frac{mc^2}{γ}
  \end{align*}
* relativistische Energie-Impuls-Beziehung
  \begin{align*}
  \mathcal{L} &= - \frac{1}{γ} = \sqrt{c^2 - v^2} \\
  \to p &= \pp{\mathcal{L}}{v} = \frac{v}{\sqrt{c^2 - v^2}} \\
  p^2 (c^2 - v^2) = v^2, p^2 c^2 = v^2 (1 + p^2), v = c \frac{p}{\sqrt{1 + p^2}} \\
  \mathcal{H} &= v \pp{L}{v} - \mathcal{L} = v \frac{v}{\sqrt{c^2 - v^2}} + \sqrt{c^2 - v^2} = v p + \frac{v}{p} = v(p + \frac{1}{p}) \\
  \to \mathcal{H} &= c \frac{p}{\sqrt{1 + p}} \frac{p^2 + 1}{p} = c \sqrt{1 + p^2} \\
  \intertext{mit $m c^2$:}
  \mathcal{H} &= \sqrt{(mc)^2 + c^2 p^2} \\
  \d S^2 &= (1 + \frac{2ϕ}{c^2}) c^2 \d t^2 - (1 - \frac{2ϕ}{c^2}) \d x_i \d x^i, \abs{ϕ} < c^2,	\text{ größer in der Schwarzschild-Metrik} \\
  S &= - m c ∫ \d s = - m c^2 ∫ \d t \sqrt{(1 + \frac{2ϕ}{c^2}) c^2 (1 - \frac{2ϕ}{c^2}) v^2} \\
  \d S^2 &\to g_{μν} \underbrace{\dd{x^μ}{t}}_{= \cvec{c; v_i}} \underbrace{\dd{x^ν}{t}}_{\cvec{c; v_i}} \d t^2 \\
  S &= - m c^2 ∫ \d t \sqrt{c^2(1 + \frac{2ϕ}{c} - β^2)} \simeq m c^2 ∫ \d t (1 + \frac{ϕ}{c^2} - \frac{β}{c^2}) \\
  \to S &= ∫ \d t (\underbrace{\frac{m}{2} v^2}_{T} - \underbrace{m ϕ}_{V})
  \end{align*}


  \begin{align*}
  E^2 &= p^2 + m^2, c = 1, E = \sqrt{p^2 + m^2} \\
  v_{ph} &= \frac{E}{p} = \frac{\sqrt{p^2 + m^2}}{p} \\
  v_{gr} &= \pp{E}{p} &= \frac{p}{\sqrt{p^2 + m^2}} \\
  v_{ph} v_{gr} &= \frac{\sqrt{p^2 + m^2}}{p} \frac{p}{\sqrt{p^2 + m^2}} = 1 \\
  c &= \sqrt{v_{ph} v_{gr}}
  \end{align*}
* geometrische Sicht auf Bewegung
  \begin{align*}
  δS &= - m c^2 δ ∫_A^B \d τ = - m c^2 ∫_A^B \frac{η_{μν}}{2 \d t}(\d x^μ δ \d x^ν + δ \d x^μ \d x^ν) \\
  &\underarrow[=]{Symmetrie $μ \leftrightarrow ν$} - m c^2 ∫ η_{μν} \dd{x^μ}{\d τ} δ δ x^ν \underarrow[=]{Partielle Integration} m c^2 ∫ η_{μν} \frac{\d^2 x^μ}{\d τ^2} \d τ δx^ν \overset{!}{=} 0 \\
  \to \text{Lösung:} x^μ(τ) &= a^μ τ + b^μ, \dd{x^μ}{τ} = a^μ, \const
  \end{align*}
  Prinzip der extremen Eigenzeit $\to$ Graden im kräftefreien Fall. \\
  mechanische Ähnlichkeit:
  \begin{align*}
  x &\to α x \\
  t &\to β t \\
  \intertext{für viele Fälle sieht die Larange Funktion so aus:}
  \mathcal{L} &= \frac{x^2}{2} - x^q \\
  \dd{}{t} \pp{\mathcal{L}}{\dot x} - \pp{\mathcal{L}}{x} &= 0 \\
  \dd{t}{τ} &= \const, \dd{x^μ}{τ} = \const
  \end{align*}
* Loretz-Kräfte und Feldstärketensor
  \begin{align*}
  \dd{\v p}{t} &= q(\v E + \v β × \v B), \v β = \frac{\v v}{c}, \v p = γ m \v v \\
  \v β γ \dd{\v p}{t} &= c \v β γ \dd{}{t}(m γ \v β) = \dots = m γ \dd{}{t}(γ c) = q \v β γ \v E \\
  γ \dd{\v β}{t} &= c m γ \dd{}{t}(γ \v β) = q γ(\v E + \v β × \v B) \\
  m \dd{u^μ}{τ} &= \underbrace{\begin{pmatrix}0 & -E_x & -E_y & -E_z \\ E_x & 0 & -B_x & B_y \\ E_y & B_x & 0 & B_z \\ E_z & -B_y & B_z & 0\end{pmatrix}}_{\mathclap{F^{μν} \sim \text{ Feldstärketensor}}} u_ν \\
  \intertext{Erhaltung der Normierung von $u_μ u^μ = c^2$}
  \frac{1}{2} \dd{}{τ}(u_μ u^μ) &= u_μ \dd{u^μ}{τ} = \frac{q}{m} u_μ F^{μν} u_ν = \frac{q}{m} \underbrace{u_μ u_ν}_{\mathclap{\text{symmetrisch}}} \overbrace{F^{μν}}^{\mathclap{\text{antisymmetrisch}}} \\
  F^{μν} \to Λ^μ_ρ Λ^ν_σ F^{ρσ} \quad\text{Lorentztransformation}
  \end{align*}
\part{kovariante Elektrodynamik}
* homogene Maxwell-Gleichungen
  \begin{align*}
  x^μ &= \cvec{c t; x^i} \to \partial_μ = \pp{}{x^μ} = (\partial_{ct}, \partial_i) \to \partial_μ x^μ = 4 \\
  x_ν &= η_{μν} x^μ = (ct, - x_i) \\
  \partial^λ F^{μν} + \partial^μ F^{νλ} + \partial^ν F^{λ μ} &= 0 \quad\text{Bianchi-Identität} \\
  ε_{μνρσ} \partial^ν F^{ρσ} &= 0 \\
  \partial^ν(ε_{μνρσ} F^{ρσ}) &= 0 \\
  \partial^ν \tilde F_{μν} &= 0 \qquad \tilde{F} \text{ dualer Feldtensor} \\
  μ = 0 (\text{nur \(B\)-Komponenten}): \partial^ν \tilde F_{0ν} &= \partial^i B_i = \Div \v B = 0 \checkmark \\
  μ = 1 (\text{\(E\)- und \(B\)-Komponenten}): \partial^ν \tilde F_{1ν} &= - \partial_0 B_x - \partial_y E_z + \partial_z E_y \to \rot \v E = - \partial_{ct} \v B
  \end{align*}
* Kontinuität der Ladungsdichte
  \begin{align*}
  j^μ = \cvec{ρ c; j^i} = ρ_0 γ \cvec{c; v^i} \to \partial_μ j^μ = \partial_t (ρ c) + \partial_i j^i = \partial_t ρ + \Div \v j = 0
  \end{align*}
  $\partial_μ j^μ \sim$ Lorentz-Invariante, in allen Systemen gleich!
  \[(\partial t ∫_V \d^3 r ρ = - ∫_{\partial V} \d \v S \v j)\]
  \begin{align*}
  \partial_μ F^{μν} &= \frac{4π}{c} j^ν \\
  \partial_ν \partial_μ F^{μν} &= \frac{4π}{c} \partial_ν j^ν
  \end{align*}
