#+AUTHOR: Robin Heinemann
#+TITLE: Lineare Algebra II (Vogel)

#+INCLUDE: "../header.org" :minlevel 1
#+LATEX_HEADER:	\setcounter{section}{17}
#+LATEX_HEADER:	\theoremsymbol{}
#+LATEX_HEADER: \theoremstyle{plain}
#+LATEX_HEADER: \newtheorem{defthm}[defn]{Satz+Definition}
#+LATEX_HEADER: \newtheorem{remdef}[defn]{Bemerkung+Definition}
#+LATEX_HEADER: \newtheorem{concdef}[defn]{Folgerung+Definition}
#+LATEX_HEADER: \theoremstyle{nonumberplain}
#+LATEX_HEADER: \renewtheorem{note}{Anmerkung}
#+LATEX_HEADER: \theoremstyle{break}
#+LATEX_HEADER: \renewtheorem{ex}[defn]{Beispiel}

#+LATEX_HEADER: \DeclareFontEncoding{LS1}{}{}
#+LATEX_HEADER: \DeclareFontSubstitution{LS1}{stix}{m}{n}
#+LATEX_HEADER: \DeclareSymbolFont{symbols2}{LS1}{stixfrak} {m} {n}
#+LATEX_HEADER: \DeclareMathSymbol{\operp}{\mathbin}{symbols2}{"A8}

#+INCLUDE: "eigen_values.org" :minlevel 1
#+INCLUDE: "dual_vector.org" :minlevel 1
# Kapitel 4 Bilinearformen und Skalarprodukte
#+INCLUDE: "bilinear_form.org" :minlevel 1
#+INCLUDE: "quadratic_groups.org" :minlevel 1
#+INCLUDE: "euclidic_groups.org" :minlevel 1
#+INCLUDE: "orthogonal_group.org" :minlevel 1
#+INCLUDE: "spectral_theorem.org" :minlevel 1
#+INCLUDE: "inner_product_space.org" :minlevel 1
#+INCLUDE: "divisibility.org" :minlevel 1
#+INCLUDE: "euclidean_rings.org" :minlevel 1
* Normalformen von Endomorphismen
  In diesem Abschnitt sei $K$ stets ein Körper und $n ∈ ℕ$. \\
  Ziel: $A, B ∈ M(n × n, K)$
  - Wann ist $A \approx B$ ?
  - Suche möglichst einfache Vertreter der Äquivalenzklasse bezüglich "$\approx$" ($\to$ Normalformen)
  In Termen von Endomorphismen: Gegeben sei $φ ∈ \End(V), V$ endlichdimensionaler K-Vektorraum. Wir suchen Basis $\mathcal{B}$ von $V$, sodass $M_{\mathcal{B}}(φ)$ möglichst eincah ist.
  #+begin_defn latex
  $A ∈ M(n × n, K)$.
  \[P_A := t E_n - A ∈ M(n × n, K[t])\]
  heißt die charakteristische Matrix von $A$.
  #+end_defn
  #+begin_note latex
  Insbesondere ist $χ_A^{char} = \det(P_A)$.
  #+end_note
  #+ATTR_LATEX: :options [Satz von Frobenius]
  #+begin_thm latex
  $A, B ∈ M(n × n, K)$. Dann sind äquivalent:
  1. $A \approx B$ (in $M(n × n, K)$)
  2. $P_A \sim P_B$ (in $M(n × n, K[t])$)
  #+end_thm
  #+begin_proof latex
  1. $⇒$ 2. Sei $A \approx B ⇒ ∃ S ∈ \GL(n, K): B = S A S^{-1}$
	 \begin{align*}
	 ⇒ P_B &= t E_n - B = t E_n - S A S^{-1} = S t E_n S {-1} - S A  S^{-1} \\
	 &= S \underbrace{(t E_n - A)}_{= P_A} S^{-1} \\
	 ⇒ P_B &\approx P_A ⇒ P_B \sim P_A
     \end{align*}
  2. $⇒$ 1. Sei	$P_A \sim P_B$:
	 1. Wir konstruieren $R ∈ M(n × n, K)$ mit $A R = R B$: \\
		$⇒ ∃ S, T ∈ \GL(n, K[t]): P_A = S P_B T^{-1}$, das heißt $S P_B = P_A T$
		\[⇒ S(t E_n - B) = (t E_n - A) T\]
		Wir schreiben $S, T$ in der folgenden Form:
		\[S = \sum_{i = 0}^{m} t^i S_i, T = \sum_{i = 0}^{m} t^i T_i, \quad S_i, T_i ∈ M(n × n, K)\]
		\begin{align*}
		⇒ S(t E_n - B) &= \sum_{i = 0}^{m} t^i S_i(t E_n - B) = \sum_{i = 0}^{m} (t^{i + 1} S_i - t^i S_i B) \\
		\string(t E_n - A\string) T &= (t E_n - A) \sum_{i = 0}^{m} t^i T_i = \sum_{i = 0}^{m} (t^{i + 1d T_i - t^i A T_i}) \\
		⇒ \sum_{i = 0}^{m + 1} (S_{i - 1} - S_i B) t^i &= \sum_{i = 0}^{m + 1}(T_{i - 1} - A T_i) t^i \\
		\intertext{wobei $S_{-1}, T_{-1}, S_{m + 1}, T_{m + 1} = 0$}
		⇒ S_{i - 1} - S_i  b &= T_{i - 1} -  a T_i\qquad 0 \leq i \leq m + 1 \\
		⇒ A^i S_{i - 1} - A^i S_i B &= A^i T_{i - 1} - A^{i + 1} T_i \qquad 0 \leq i \leq m + 1 \\
		⇒ \sum_{i = 0}^{m + 1}(A^i S_{i - 1} - A^i S_i B) &= \sum_{i = 0}^{m + 1}(A^i T_{i - 1} - A^{i + 1} T_i) \\
		&= (A^0 T_{-1} - A T_0) + (A T_0 - A^2 T_1) + \dots + (A^{m + 1} T_m - A^{m + 2} T_{m + 1}) \\
		&= A^0 T_{-1} - A^{m + 2} T_{m + 1} = 0 \\
		⇒ \sum_{i = 0}^{m + 1} A^i S_{i - 1} &= \sum_{i = 0}^{m + 1} A^i S_i B \\
		⇒ \sum_{i = 1}^{m + 1} A^i S_{i - 1} &= \sum_{i = 0}^{m} A_i S_i B \\
		⇒ A(\sum_{i = 0}^{m} A^i S_i) &= (\sum_{i = 0}^{m} A^i S_i) B \\
		⇒ R &:= \sum_{i = 0}^{m} A^i S_i
		\end{align*}
        dann $A R = R B$.
	 2. Wir zeigen $R ∈ \GL(n, K)$ (wegen $A R = R B$ ist dann $A = R B R^{-1}$, also $A \approx B$, fergit.)
		Nach Vorraussetzung ist $S ∈ \GL(n, K[t])$ $⇒ ∃ M ∈ \GL(n, K[lt]): S M = E_n, M = \sum_{i = 0}^{m} t^i M_i$ mit $M_i ∈ M(n × n, K)$, ohne Einschränkung dasselbe $n$ wie vorhin.
		Behauptung: Mit
		\[N := \sum_{j = 0}^{m} B^j M_j ∈ M(n × n, K)\]
		gilt $R N = E_n$ also $R ∈ \GL(n, K)$, denn: Es ist
		\[R N = \sum_{j = 0}^{m} R B^j M_j\]
		Wegen $R B = A R$ folgt $R B^j = R B B^{j - 1} = A R B^{j - 1} = \dots = A^j R$
		\[⇒ R N = \sum_{j = 0}^{m} A^j R M_j = \sum_{j = 0}^{m} A^j (\sum_{i = 0}^{m} A^i S_i) M_j = \sum_{i,j = 0}^{m} A^{i + j} S_i M_j\]
		Wegen $SM = E_n$ folgt
		\[(\sum_{i = 0}^{m} t^i S_i)(\sum_{j = 0}^{m} t^j M_j) = E_n\]
		\begin{align*}
		⇒ S_0 M_0 + \sum_{k = 1}^{2m}(\sum_{i + j = k} S_i M_j) t^k &= E_n \\
		⇒ S_0 M_0 = E_n, \sum_{i + j = k} S_i M_j &= 0 \quad k \geq 1 \\
		⇒ R N = \sum_{i,j = 0}^{m} A^{i + j} S_i M_j &= S_0 M_0 + \sum_{k = 1}^{2m} A^k \underbrace{\sum_{i + j = k} S_i M_j}_{= 0} = S_0 M_0 = E_n
		\end{align*}
  #+end_proof
  #+begin_remdef latex
  $A ∈ M(n × n, K)$. Dann gilt:
  1. Es gibt eindeutig bestimmte normierte Polynome $c_i(A), \dots, c_n(A) ∈ K[t]$ mit
	 \[P_A \sim \begin{pmatrix}c_1(A) &   & 3 \\  & \ddots &   \\ 0 &   & c_n(A)\end{pmatrix}, \quad c_1(A) \mid c_2(A) \mid \dots \mid c_n(A)\]
	 $c_1(A), \dots, c_n(A)$ heißen die *Invariantenteiler* von $A$.
  2. Es gibt eindeutig bestimmte normierte Polynorme $d_1(A), \dots, d_n(A) ∈ K[t]$ mit
	 \[\Fit_l(A) = (d_l(A)) \quad l = 1, \dots, n\]
	 Es ist \[d_l(A) = \ggT(\det(B) \mid B \text{ ist $l× l$ -Untermatrix von } P_A)\]. Insbesondere ist $d_n(A) = χ_A^{char}$.
	 $d_1(A), \dots, d_n(A)$ heißen die *Determinantenteiler* von $A$.
  #+end_remdef
  #+begin_proof latex
  1. Existenz: $K[t]$ ist ein Euklidischer Ring. Elementarteilersatz $⇒ ∃ \tilde c_1, \dots, \tilde c_r ∈ K[t]$:
	 \[P_a \sim	 \begin{pmatrix} \tilde c_1 & & & & & \\ & \ddots & & & & \\ & & \tilde c_r & & & \\ & & & 0 & & \\ & & & & \ddots & \\ & & & & & 0\end{pmatrix}\qquad \tilde c_1 \mid \dots \mid \tilde c_r\]
	 Es ist $\Fit_n(F_A) = (\det(P_A)) = (χ_A^{char}) \neq (0) \to r = 0$ und
	 \[\Fit_n(P_A) = (\tilde c_1 · \dots · \tilde c_n)\]
	 Da $\tilde c_1, \dots, \tilde c_n \neq 0$ eindeutig bis auf Assoziiertheit, existieren eindeutig bestimmte normierte Polynome $c_1(A), \dots, c_n(A)$ mit $c_1(A) \estimates \tilde c_1,  \dots, c_n(A) \estimates \tilde c_n$.
	 \[⇒ P_A \sim \begin{pmatrix}c_1(A) &   &   \\   & \ddots &   \\   &   & c_n(A)\end{pmatrix}\]
  2. $K[t]$ Hauptidealring $⇒ \Fit_l(P_A), l = 1, \dots, n$ sind Hauptideale und nach 27.16 ist $\Fit_l(P_A) = (c_1(A) · \dots · c_l(A))$ für $l = 1, \dots, n$, insbesondere $\Fit_l(P_a) \neq (0)$.
	 Erzeuger der Hauptideale $\Fit_l(P_A)$ sind eindeutig bis auf Assoziiertheit. $⇒$ Es existieren eindeutig bestimmte normierte Polynome $d_1(A), \dots, d_n(A) ∈ K[t]$ mit
	 $\Fit_l(P_A) = (d_l(A))$ für $l = 1, \dots, n$. $
     \[⇒ \Fit_l(P_A) = (\det(B) \mid B \text{ ist $l × l$ -Untermatrix von } A) = (d_l(A))\]
	 mit $d_l(A)$ normiert und $\ggT(\dots)$ normiert $⇒$ Behauptung.
  #+end_proof
  #+begin_note latex
  Also:
  - Invatriantenteiler von $A$ = normierte Elementarteiler von $P_A$
  -	Determinatenteiler von $A$ = normierte Erzeuger der Fittingideale von $P_A$.
  #+end_note
  #+begin_conc latex
  $A ∈ M(n × n, K)$. Dann gilt: $d_l(A) = c_1(A) · \dots · c_l(A) ∀ l = 1, \dots, n$. Insbesondere gilt:
  \[χ_A^{char} = d_n(A) = c_1(A) · \dots · c_n(A)\]
  sowie
  \[d_1(A) \mid \dots \mid d_n(A)\]
  #+end_conc
  #+ATTR_LATEX: :options [Invariantenteilersatz]
  #+begin_thm latex
  $A, B ∈ M(n × n, K)$. Dann sind äquivalent:
  1. $A \approx B$
  2. Die Invatiantenteiler von $A$ stimmen mit den Invariantenteilern von $B$ überein:
     \[c_1(A) = c_1(B), \dots, c_n(A) = c_n(B)\]
  3. Die Determinantenteiler von $A$ stimmen mit den Determinantenteilern von $B$ überein:
     \[d_1(A) = d_1(B), \dots, d_n(A) = d_n(B)\]
  #+end_thm
  #+begin_proof latex
  aus Satz von Probenius und Satz 27.18
  #+end_proof
  #+begin_ex latex
  Sei
  \[A = \begin{pmatrix}0 & 1 & 3 \\ 3 & 1 & -4 \\ -2 & 1 & 5\end{pmatrix} ∈ M(3 × 3, ℚ)\]
  Es ist
  \[P_A = \begin{pmatrix}t & -1 & -3 \\ -3 & t - 1 & 4 \\ 2 & -1 & t - 5\end{pmatrix} ∈ M(3 × 3, ℚ[t])\]
  Bestimmung der Determinantenteiler von $A: d_1(A) = \ggT(-1, \dots) = 1$
  \begin{align*}
  d_2(A) &= \ggT((-1) · 4 - (-3)(t - 1), (-3)(-1) - 2(t-1), \dots) \\
  &= \ggT(3t - 7, -2t + 5, \dots) = 1 \\
  d_3(A) &= χ_A^{char} &= (t - 2)^3 \\
  ⇒ c_1(A) &= 1, c_2(A) = 1, c_3(A) = (t - 2)^3
  \end{align*}
  Sei
  \[B = \begin{pmatrix}1 & 1 & 2 \\ 1 & 1 & -2 \\ -1 & 1 & 4\end{pmatrix} ∈ M(3 × 3, ℚ) ⇒ P_B = \begin{pmatrix}t - 1 & -1 & -2 \\ -1 & t - 1 & 2 \\ 1 & -1 & t - 4\end{pmatrix}\]
  Bestimme Invariantenteiler von $B$:
  \begin{align*}
  P_B &= \begin{pmatrix}t - 1 & -1 & -2 \\ -1 & t - 1 & 2 \\ 1 & -1 & t - 4\end{pmatrix} \sim \begin{pmatrix}-1 & t - 1 & 2 \\ t - 1 & -1 & -2 \\ 1 & -1 & t - 4\end{pmatrix} \\
  &\sim \begin{pmatrix}-1 & t - 1 & 2 \\ 0 & \string(t - 1\string)^2 - 1 & -2 + 2\string(t - 1\string) \\ 0 & t - 2 & t - 2\end{pmatrix} \sim \begin{pmatrix}-1 & 0 & 0 \\ 0 & t^2 - 2t & 2t - 4 \\ 0 & t - 2 & t - 2\end{pmatrix} \\
  &\sim \begin{pmatrix}-1 & 0 & 0 \\ 0 & t - 2 & t - 2 \\ 0 & t^2 -2t & 2t - 4\end{pmatrix} \sim \begin{pmatrix}-1 & 0 & 0 \\ 0 & t - 2 & 0 \\ 0 & t^2 - 2t & -t^2 + 3 t - 4\end{pmatrix} \\
  &\sim \begin{pmatrix}-1 & 0 & 0 \\ 0 & t - 2 & 0 \\ 0 & 0 & -\string(t - 2\string)^2\end{pmatrix} \sim \begin{pmatrix}1 & 0 & 0 \\ 0 & t - 2 & 0 \\ 0 & 0 & \string(t - 2\string)^2\end{pmatrix} \\
  ⇒ c_1(B) &= 1, c_2(B) = t - 2, c_3(B) = (t - 2)^2 \\
  d_1(B) &= 1, d_2(B) &= t - 2, d_3(B) = (t - 2)^3
  \end{align*}
  #+end_ex
  #+ATTR_LATEX: :options [28.7]
  #+begin_remark latex
  $A, B ∈ M(n × n, K)$, $K$ Teilkörper eines Körpers $L$, dann sind folgende Aussagen äquivalent
  1. $A \approx B$ in $M(n × n, K)$
  2. $A \approx B$ in $M(n × n, L)$
  #+end_remark
  #+begin_proof latex
  Übung
  #+end_proof
  Ziel: Such möglichst einfache Matrizen, die vorgegebne Invarianten- beziehungsweise Determinantenteiler haben.
  #+begin_defn latex
  $g = t^2 + a_{n - 1} t^{n - 1} + \dots + a_1 t + a_0 ∈ K[t], n \geq 1$
  \[\begin{pmatrix}0 &   &   &   & -a_0 \\ 1 & 0 &   &   & -a_1 \\   & 1 & \ddots &   & \vdots \\   &   & \ddots & 0 & -a_{n - 2} \\   &   &   & 1 & -a_{n - 1}\end{pmatrix}\]
  heißt die *Begleitmatrix* zu $g$.
  #+end_defn
  #+begin_remark latex
  $g ∈ K[t]$ nicht konstant, normiert. Dann	ist $c_1(B_g) = \dots = c_{n - 1}(B_g) = 1, c_n(B_g) = g$, also
  \[P_{B_g} \sim \begin{pmatrix}1 &   &   &   \\   & \ddots &   &   \\   &   & 1 &   \\   &   &   & g\end{pmatrix}\]
  $d_1(B_g) = \dots = d_{n - 1}(B_g) = 1, d_n(B_g) = χ_{B_g}^{char} = g$
  #+end_remark
  #+begin_proof latex
  Sei $g = t^n + a_{n - 1} t^{n - 1} + \dots + a_0$
  \[⇒ P_{B_g} = \begin{pmatrix}t &   &   &   & a_0  \\ -1 & t &   &   & a_1  \\   & -1 & \ddots &   & \vdots \\   &   & \ddots   & t & a_{n - 2} \\ & & & -1 & t + a_{n - 1}\end{pmatrix}\]
  streiche erste Zeile, letzte Spalte von $P_{B_g}$, erhalte Untermatrix
  \[C = \begin{pmatrix}-1 & t &   &   \\   & \ddots & \ddots &   \\   &   &  \ddots & t \\   &   &   & -1\end{pmatrix}\]
  mit $\det(C) = (-1)^{n - 1} ⇒ d_{n - 1}(B_g) = 1 ⇒ d_1(B_g) = \dots = d_{n - 1}(B_g) = 1$, sowie $c_1(B_g) = \dots = c_{n - 1}(B_g) = 1$. Wir zeigen per Induktion nach $n$, dass $d_n(B_g) = χ_{B_g}^{char} = g$. \\
  Induktionsanfang: $n = 1$: $g = t + a_0, B_g = (-a_0) ⇒ χ_{B_g}^{char} = t + a_0 = g$ \\
  Induktionsschritt:
  \begin{align*}
  χ_{b_g}^{char} &= \det \begin{pmatrix}t &   &   & a_0 \\ -1 & \ddots &   & \vdots \\  & \ddots & t & a_{n - 2} \\   &   & -1 & t + a_{n - 1}\end{pmatrix} \\
  &= t · \underbrace{\det\begin{pmatrix}t &   &   & a_1 \\ -1 & \ddots &   & \vdots \\  & \ddots & t & a_{n - 2} \\   &   & -1 & t + a_{n - 1}\end{pmatrix}}_{= a_1 + a_2 t + \dots + a_{n - 1} t^{n - 2} + t^{n - 1} =: \tilde g} + (-1)^{n + 1} a_0 \det	\underbrace{\begin{pmatrix}-1 & t &   &   \\   & \ddots & \ddots &   \\   &   &  \ddots & t \\   &   &   & -1\end{pmatrix}}_{= (-1)^{n - 1}} \\
  &= a_1 t + a_2 t^2 + \dots + a_{n - 1} t^{n - 1} + t^n + a_0 = g
  \end{align*}
  #+end_proof
  #+begin_remdef latex
  $g_1, \dots, g_r ∈ K[t]$ normiert, nichtkonstant mit $g_1 \mid g_2 \mid \dots \mid g_r$, $n := \deg(g_1) + \dots + \deg(g_r)$
  \[B_{g_1, \dots, g_r} := \begin{pmatrix}B_{g_1} &   &   &   \\   & B_{g_2} &   &   \\   &   & \ddots &   \\   &   &   & B_{g_r}\end{pmatrix} ∈ M(n × n K)\]
  Dann gilt:
  \begin{align*}
  c_1(B_{g_1, \dots, g_r}) &= 1, \dots, c_{n - 1}(B_{g_1, \dots, g_r}) = 1 \\
  c_{n - r + 1}(B_{g_1, \dots, g_r}) &= g_1, \dots, c_n(B_{g_1, \dots, g_r}) = g_r
  \end{align*}
  #+end_remdef
  #+begin_proof latex
  \begin{align*}
  P_{B_{g_1, \dots, g_r}} &= \begin{pmatrix}P_{B_{g_1}} &   &   \\   & \ddots &   \\   &   & P_{B_{g_r}}\end{pmatrix} \sim \begin{pmatrix}
  1 \\
  & \ddots \\
  & & 1 \\
  & & & g_1 \\
  & & & & \ddots \\
  & & & & & 1 \\
  & & & & & & \ddots \\
  & & & & & & & 1 \\
  & & & & & & & & g_r
  \end{pmatrix} \\
  &\sim \begin{pmatrix} 1 \\ & \ddots \\ & & 1 \\ & & & g_1 \\ & & & & \ddots \\ & & & & & g_r\end{pmatrix}
  \end{align*}
  #+end_proof
  #+ATTR_LATEX: :options [Frobenius-Normalform]
  #+begin_thm latex
  $A ∈ M(n × n, K)$. Dann existiert ein eindeutig bestimmtes $r ∈ ℕ$ sowie eindeutig bestimmte normierte nichtkonstante Polynome $g_1, \dots, g_r ∈ K[t]$ mit $g_1 \mid \dots \mid g_r$ und
  $A \approx B_{g_1, \dots, g_r}$. $g_1, \dots, g_r$ sind genau die nichtkonstanten Invariantenteiler von $A$. $B_{g_1, \dots, g_r}$ heißt die *Frobenius-Normalform* (FNF) von $A$.
  #+end_thm
  #+begin_proof latex
  1. Existenz: Setze
	 \begin{align*}
     k &:= \max \{l ∈ \{1, \dots, n\} \mid c_l(A) = 1\} \\
	 r &:= n - k \\
	 g_i &:= g_{k + i}(A) ∀ i = 1, \dots, r \\
	 ⇒ n &= \deg(χ_{A}^{char}) = \deg(d_n(A)) = \deg(c_1(A) · \dots · c_n(A)) = \deg(g_1 · \dots · g_r) \\
  	 &= \deg(g_1) + \dots + \deg(g_r)
     \end{align*}
	 $⇒$ Die Invariantenteiler von $A$ stimmen mit den Invariantenteilern von $B_{g_1, \dots, g_r}$ überein $⇒ A \approx B_{g_1, \dots, g_r}$
  2. Eindeutigkeit: $A \approx B_{g_1, \dots, g_r} \approx B_{k_1, \dots, k_s} ⇒ r = s ∧ g_1 = k_1, \dots, g_r = k_r$
  #+end_proof
  #+begin_ex latex
  1. \[A = \begin{pmatrix}0 & 1 & 3 \\ 3 & 1 & -4 \\ -2 & 1 & 5\end{pmatrix} ∈ M(3 × 3, ℚ)\]
	 $⇒ c_1(A) = 1, c_2(A) = 1, c_3(A) = (t - 2)^3 = t^3 - 6 t^2 + 12 t - 8 =: g_1$
	 \[⇒ A \approx B_{g_1} = \begin{pmatrix}0 & 0 & 8 \\ 1 & 0 & -12 \\ 0 & 1 & 6\end{pmatrix}\]
  2. \[A = \begin{pmatrix}1 & 1 & 2 \\ 1 & 1 & -2 \\ -1 & 1 & 4\end{pmatrix} ∈ M(3 × 3, ℚ)\]
	 $⇒ c_1(A) = 1, c_2(A) = t - 2 =: g_1, c_3(A) = (t - 2)^2 = t^2 - 4 t + 4 =: g_2$
	 \[⇒ A \approx B_{g_1, g_2} = \begin{pmatrix}2 & 0 & 0 \\ 0 & 0 & -4 \\ 0 & 1 & 4\end{pmatrix}\]
  3. \[A = \begin{pmatrix}4 & -1 & -2 & -3 \\ -1 & 5 & 2 & -4 \\ 0 & 1 & 3 & -1 \\ -1 & 2 & 2 & 1\end{pmatrix} ∈ M(4 × 4, ℚ)\]
	 $c_1(A) = 1, c_2(A) = 1, c_3(A) = t - 3 =: g_1, c_3(A) = (t - 3)^3(t - 2) = t^3 - 8t^3 + 21 t - 18 =: g_2$
	 \[⇒ A \approx B_{g_1, g_2} = \begin{pmatrix}3 & 0 & 0 & 0 \\ 0 & 0 & 0 & 18 \\ 0 & 1 & 0 & -21 \\ 0 & 0 & 1 & 8\end{pmatrix}\]
  #+end_ex
  #+begin_remark latex
  $A ∈ M(n × n, K)$. Dann ist $c_n(A) = χ_A^{min}$
  #+end_remark
  #+begin_proof latex
  Übung.
  #+end_proof
  #+begin_remark latex
  $g ∈ K[t], g = h_1 · \dots · h_k$ mit $h_1, \dots, h_k ∈ K[t]$ normiert, nicht konstant, paarweise teilerfremd
  \[⇒ B_g \approx \begin{pmatrix}B_{h_1} &   &   \\   & \ddots &   \\   &   & B_{h_k}\end{pmatrix}\]
  #+end_remark
  #+begin_proof latex
  1. Sei $C$ definiert als die rechte Seite, dann ist
	 \[P_c = \begin{pmatrix}P_{B_{h_1}} &   &   \\   & \ddots &   \\   &   & B_{B_{h_k}}\end{pmatrix} \sim \begin{pmatrix} 1 \\ & \ddots \\ & & 1 \\ & & & h_1 \\ & & & & \ddots \\ & & & & & 1 \\ & & & & & & \ddots \\ & & & & & & & 1 \\ & & & & & & & & h_k\end{pmatrix} \sim \begin{pmatrix} 1 \\ & \ddots \\ & & 1 \\ & & & h_1 \\ & & & & \ddots \\ & & & & & h_k\end{pmatrix} =: H\]
	 \[P_{B_g} \sim \begin{pmatrix}1 &   &   &   \\   & \ddots &   &   \\   &   & 1 &   \\   &   &   & g\end{pmatrix} =: G\]
  2. $G, H$ haben dieselben Fittingideale, denn: Sei $n = \deg(g)$, insbesondere $G, H ∈ M(n × n, K[t])$
	 - $\Fit_n(H) = (\det(H)) = (h_1 · \dots · h_k) = (g) = (\det(G)) = \Fit_n(G)$
	 - $\Fit_1(G) = \dots = \Fit_{n - 1}(G) = (1)$
	 - $\Fit_{n - 1}(H) \supseteq (h_1 · \dots · h_{i - 1} · h_{i + 1} · \dots · h_k \mid i = 1, \dots, k) = (1)$, also $\Fit_{n - 1}(H) = (1)$
	   (da $h_1, \dots, h_k$) paarweise teilerfremd. Analog: $\Fit_{n - k + i}(H) = (1)$ für $i = 1, \dots, k - 2$. Klar: $\Fit_l(H) = (1)$ für $l = 1, \dots, n - k$
  3. Wegen 2. ist $G \sim H ⇒ P_{B_g} \sim P_c ⇒ B_g \approx C$.
  #+end_proof
  #+ATTR_LATEX: :options [Weierstrass-Normalform]
  #+begin_defthm latex
  $A ∈ M(n × n, K)$. Dann existieren eindeutig bestimmte $m ∈ ℕ$, Polynome $h_1, \dots, h_m ∈ K[t]$, die Potenzen von irreduziblen, normierten Polynomen sind, sodass
  \[A \approx B_{h_1, \dots, h_m}\]
  $h_1, \dots, h_m$ sind bis auf Reihenfolge eindeutig bestimmt und heißen *Weierstrassteiler* von $A$. $B_{h_1, \dots, h_m}$ heißt eine *Weierstrass-Normalform* von $A$ (WNF). $h_1, \dots, h_m$ sind die	Potenzen
  irreduzibler Polynome, die in den Primfaktorzerlegung der nichtkonstanten Invariantenteiler von $A$ auftauchen.
  #+end_defthm
  #+begin_proof latex
  1. Existenz: (Algorithmus zuv Herstellung der Weierstrassnormalform) \\
	 Seien $g_1, \dots, g_r ∈ K[t]$ die nichtkonstanten Invariantenteiler von $A$ (mit $g_1 \mid \dots \mid g_r$)
	 \[A \approx B_{g_1, \dots, g_r} = \begin{pmatrix}B_{g_1} &   &   \\   & \ddots &   \\   &   & B_{g_r}\end{pmatrix}\]
	 Nach 27.5 ist $K[t]$ ein faktorieller Ring, das heißt für $i = 1, \dots, r$ existieren paarweise teilerfremde Polynome
	 $h_{i,1}, \dots, h_{i,k_i}$, deii Potenzen irreduzibler Polynome sind, sodass $g_i = h_{i,1} · \dots · h_{i,k_i}$
	 \[\xRightarrow{28.14} A \approx \begin{pmatrix} B_{h_{1,1}} \\ & \ddots \\ & & B_{h_{1, k_1}} \\ & & & \ddots \\ & & & & B_{h_{r,1}} \\ & & & & & \ddots \\ & & & & & & B_{h_{r,k_r}}\end{pmatrix}\]
  2. Eindeutigkeit von $m$ sowie von $h_1, \dots, h_m$ bis auf Reihenfolge. Sei
	 \[A \approx \begin{pmatrix} B_{h_1} \\ & \ddots \\ & & B_{h_m}\end{pmatrix}\]
	 wobei $h_1, \dots, h_m$ Potenzen irreduzibler Polynome. Wir sortieren $h_1, \dots, h_m$ so, dass $h_1 = p_1^{e_1}, \dots, b_k = p_{k}^{e_k}, p_1, \dots, p_k$ irreduzibel, normiert, paarweise verschieden,
	 sodass alle weiteren $h_i$ Potenzen von $p_1, \dots, p_k$ sind mit kleinerem oder gleichem Exponenten. Setze $f_1 := \kgV(h_1, \dots, h_m) = h_1 · \dots · h_k, h_1, \dots, h_k$ paarweise	teilerfremd, $f_1$ normiert vom Grad $\geq 1$.
	 \[A \approx \begin{pmatrix}B_{f_1} &   &   &   \\   & B_{h_{k + 1}} &   &   \\   &   & \ddots &   \\   &   &   & B_{h_m}\end{pmatrix}, f_1 · h_{k + 1} · \dots · h_m = h_1 · \dots · h_m\]
	 Wende dieses Verfahren auf die Matrix
	 \[\begin{pmatrix}B_{h_{k + 1}} &   &   \\   & \ddots &   \\   &   & B_{h_m}\end{pmatrix}\]
	 an: Nach Umsortieren von $h_{k + 1}, \dots, h_m$ wie oben erhalten wir $f_2 ∈ K[t]$ mit
	 \[A \approx \begin{pmatrix} B_{f_1} \\ & B_{f_2} \\ & & B_{h_l} \\ & & & \ddots \\ & & & & B_{h_m}\end{pmatrix}, f_2 \mid f_1, f_1 f_2 h_l · \dots · h_m = h_1 · \dots · h_m\]
	 $f_2$ normiert vom Grad $\geq 1$. Iteriere dieses Verfahren, dies bricht ab, erhalte normierte Polynome $f_1, \dots, f_r$ vom Grad $\geq 1$, sodass $f_r \mid f_{r - 1} \mid \dots \mid f_1, f_1 · \dots · f_r = h_1 · \dots · h_m$ und
	 \[A \approx \begin{pmatrix} B_{f_1} \\ & \ddots \\ & & B_{f_r} \end{pmatrix} \approx \begin{pmatrix} B_{f_r} \\ & \ddots \\ & & B_{f_1} \end{pmatrix} = B_{f_r, \dots, f_1}\]
	 Eindeutigkeit der Frobeniusnormalform $⇒$ $f_1, \dots, f_r$ eindeutig bestimmt. Über die Faktoren von $f_1, \dots, f_r$ bekommt man $m$ und $h_1, \dots, h_n$ (bis auf Reihenfolge) zurück. $⇒ m$
	 eindeutig bestimmt, $h_1, \dots, h_m$ eindeutig bis auf Reihenfolge.
  #+end_proof
  #+begin_ex latex
  1. \[A = \begin{pmatrix}-2 & 1 & 5 \\ 1 & 1 & -2 \\ 3 & 1 & 6\end{pmatrix} ∈ M(3 × 3, ℚ)\]
	 $⇒c_1(A) = 1, c_2(A) = 1, c_3(A) = (t - 1)(t - 2)^2$. Mit $h_1 = t - 1, h_2 = (t - 2)^2 = t^2 - 4 t + 4$ ist
	 \[A \approx B_{h_1, h_2} = \begin{pmatrix}1 & 0 & 0 \\ 0 & 0 & -4 \\ 0 & 1 & 4\end{pmatrix}\]
	 (Weierstrassnormalform von $A$)
  2. (vergleiche 28.6.2)
	 \[A = \begin{pmatrix}4 & -1 & -2 & 3 \\ -1 & 5 & 2 & -4 \\ 0 & 1 & 3 & -1 \\ -1 & 2 & 2 & 1\end{pmatrix} ∈ M(4 × 4, ℚ)\]
	 $⇒ c_1(A) = 1, c_2(A) = 1, c_3(A) = t - 3, c_4(A) = (t - 3)^2(t - 2)$. Mit $h_1 := t - 3, h_2 := (t - 3)^2 = t^2 - 6t + 9, h_3 := t - 2$ ist
	 \[A = B_{h_1, h_2, h_3} = \begin{pmatrix}3 & 0 & 0 & 0 \\ 0 & 0 & -9 & 0 \\ 0 & 1 & 6 & 0 \\ 0 & 0 & 0 & 2\end{pmatrix}\]
	 (Weierstrassnormalform von $A$)
  #+end_ex
  Ziel: Einfachere Normalform, falls $χ_A^{char}$ in Linearfakotren zerfällt (und damit alle Weierstrassteiler Potenzen linearer Polynome sind.)
  #+begin_remdef latex
  $λ ∈ K, f = (t - λ)^e ∈ K[t]$. Dann gilt:
  \[B_f \approx \begin{pmatrix}λ &   &   & 0 \\ 1 & \ddots &   &   \\   & \ddots & \ddots &   \\ 0 &   & 1 & λ\end{pmatrix} =: J(λ, e) ∈ M(e × e, K)\]
  ($e = 1: J(λ, 1) = (λ)$). Eine Matrix der Form $J(λ, e)$ heißt *Jordanmatrix* über $K$.
  #+end_remdef
  #+begin_proof latex
  Sei $J := J(λ, e)$
  \[⇒ P_J = \begin{pmatrix}t - λ &   &   &   \\ -1 & \ddots &   &   \\ & \ddots & \ddots &   \\   &   & -1 & t - λ\end{pmatrix} ⇒ d_e(J) = (t - λ)^e\]
  Es ist
  \[\det(\begin{pmatrix}t - λ &   &   &   \\ -1 & \ddots &   &   \\ & \ddots & \ddots &   \\   &   & -1 & t - λ\end{pmatrix}) = (-1)^{e - 1} ⇒ d_{e - 1} = 1\]
  $\xRightarrow{28.4} d_1(J) = \dots = d_{e - 2}(J) = 1$. $⇒$ Determinantenteiler von $J$ stimmen mit Determinatenteilern von $B_f$ überein $\xRightarrow{\text{Invariantenteilersatz}} B_f \approx J$
  #+end_proof
  #+ATTR_LATEX: :options [Jordansche Normalform]
  #+begin_defthm latex
  $A ∈ M(n × n, K), χ_A^{char}$ zerfalle in $K[t]$ in Linearfaktoren. Dann existieren Jordanmatrixen $J_1 = J(λ_1, e_1), \dots, J_m = J(λ_m, e_m)$ über $K$, sodass
  \[A \approx \begin{pmatrix}J_1 &   &   \\   & \ddots &   \\   &   & J_m\end{pmatrix} =: J\]
  Hierbei sind $λ_1, \dots, λ_m$ die (nicht notwendigerweise verschiedenen) Eigenwerte von $A$ (= Nullstellen von $χ_A^{char}$). $J_1, \dots, J_m$ sind bis auf Reihenfolge eindeutig bestimmt.
  Die Matrix $J$ heißt eine *Jordansche Normalform* (JNF) von $A$.
  #+end_defthm
  #+begin_proof latex
  1. Existenz: Es ist $χ_A^{char} = d_n(A) = c_1(A) · \dots · c_n(A) ⇒ c_1(A), \dots, c_n(A)$ zerfallen alle in Linearfaktoren. $⇒$ Alle Weierstrassteiler $h_1, \dots, h_m$ von $A$ sind Potenzen von linearen Polynomen
	 $h_i = (t - λ_i)^{e_i}$ für ein $λ_i ∈ K, e_i . ℕ$. Wegen $h_1 · \dots · h_m = c_1(A) · \dots · c_n(A) = χ_A^{char}$ sind die $λ_i$ genau die Eigenwerte von $A$. Setze $J_i := J(λ_i, e_i) \xRightarrow{28.17} B_{h_i} \approx J(λ_i, e_i) ∀ i = 1, \dots, m$.
	 \[⇒ A \approx \begin{pmatrix}B_{h_1} &   &   \\   & \ddots &   \\   &   & B_{h_m}\end{pmatrix} \approx \begin{pmatrix}J_1 &   &   \\   & \ddots &   \\   &   & J_m\end{pmatrix}\]
  2. Eindeutigkeit von $J_1, \dots, J_m$ bis auf Reihenfolge: folgt aus	Eindeutigkeit der Weierstrassnormalform bis auf Reihenfolge von $h_1, \dots, h_m$
  #+end_proof
  #+begin_note latex
  - Üblicherweise gruppiert man in der Jordanschen Normalform	Jordanmatrizen zu gleichen Eigenwerten zusammen. (zu einem Block mit aufsteigenden $e_i$ 's)
  -	Es gilt: $A$ diagonalisierbar $⇔$ Jordansche Normalform von $A$ ist eine Diagonalmatrix (denn: "$\impliedby$" trivial "$⇒$" da Diagonalmatrizen bereits in Jordanscher Normalform sind) (mit $1 × 1$ - Jordanmatrizen)
  #+end_note
  #+ATTR_LATEX: :options [Algorithmus zur Jordanschen Normalform]
  #+begin_algrthm latex
  *Eingabe:* $A ∈ M(n × n, K)$, sodass $χ_A^{char}$ in Linearfaktoren zerfällt. \\
  *Ausgabe:* Jordansche Normalform von $A$. \\
  *Durchführung:*
  1. Bestimme die nicht konstanten Invariantenteiler von $g_1, \dots, g_r$ von $A$.
  2. Bestimme die Primfaktorzerlegung
	 \[g_i = (t - λ_{i,1})^{m_{i,1}} · \dots · (t - λ_{i, k_i})^{m_{i,k_i}}\]
  3. Erhalte:
	 \[A \approx \begin{pmatrix}J(λ_{1,1}, m_{1,1}) &   &   \\   & \ddots &   \\   &   & J(λ_{r, k_r}, m_{r, k_r})\end{pmatrix}\]
  4. Gruppiere Jordanmatrizen zu gleichen Eigenwerten zusammen (jeweils nach aufsteigender Größe geordnet.)
  #+end_algrthm
  #+ATTR_LATEX: :options [28.20]
  #+begin_ex latex
  1. (vergleiche 28.16.2)
	 \[A = \begin{pmatrix}4 & -1 & -2 & 3 \\ -1 & 5 & 2 & -4 \\ 0 & 1 & 3 & -1 \\ -1 & 2 & 2 & 1\end{pmatrix} ∈ M(4 × 4, ℚ)\]
	 $⇒ c_1(A) = 1, c_2(A) = 1, c_3(A) = t - 1 =: g_1, c_4(A) = (t - 3)^2 (t - 2) =: g_2$. Weierstrassteiler von $A$: $h_1 = t - 3, h_2 = (t - 3)^2, h_3 = t -2$
	 \[⇒ A\approx B_{h_1, h_2, h_3} = \begin{pmatrix}B_{h_1} &   &   \\   & B_{h_2} &   \\   &   & B_{h_3}\end{pmatrix} \approx \begin{pmatrix}J(3, 1) &   &   \\ & J(3, 2) & \\   &   & J(2, 1)\end{pmatrix} = \begin{pmatrix}3 & 0 & 0 & 0 \\ 0 & 3 & 0 & 0 \\ 0 & 1 & 3 & 0 \\ 0 & 0 & 0 & 2\end{pmatrix}\]
  2. (vergleiche 28.6)
	 \[A = \begin{pmatrix}0 & 1 & 3 \\ 3 & 1 & -4 \\ -2 & 1 & 5\end{pmatrix} ∈ M(3 × 3, ℚ) ⇒ c_1(A) = 1, c_2(A) = 1, c_3(A) = (t - 2)^3\]
	 $⇒$ Weierstrassteiler von $A$: $h_1 = (t - 2)^3$
	 \[⇒ A \approx B_{h_1} = J(2, 3) = \begin{pmatrix}2 & 0 & 0 \\ 1 & 2 & 0 \\ 0 & 1 & 2\end{pmatrix}\]
  3. \[A = \begin{pmatrix}1 & 1 & 2 \\ 1 & 1 & -2 \\ -1 & 1 & 4\end{pmatrix} ∈ M(3 × 3, ℚ)\]
	 $⇒ c_1(A) = 1, c_2(A) = t - 2, c_3(A) = (t - 2)^2$ $⇒$ Weierstrassteiler von $A$: $h_1 = t - 2, h_2 = (t - 2)^2$
	 \[⇒ A \approx B_{h_1, h_2} = \begin{pmatrix}B_{h_1} &   \\   & B_{h_2}\end{pmatrix} \approx \begin{pmatrix}J(2, 1) &   \\   & J(2,2)\end{pmatrix} \begin{pmatrix}2 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 1 & 2\end{pmatrix}\]
  #+end_ex
* Moduln
  In diesem Abschnitt sei $R$ sets ein kommutativer Ring.
  #+ATTR_LATEX: :options [Modul]
  #+begin_defn latex
  Eine Menge $M$ zusammen mit einer Verknüpfung
  \[+: M × M \to M, (x, y) ↦ x + y\]
  (genannt *Addition*) und einer äußeren Verknüpfung
  \[·: R × M \to M, (a, x) × a x\]
  (genannt *skalare Multiplikation*) heißt ein *R-Modul*, wenn gilt:
  - (M1) $(M, +)$ ist eine abelsche Gruppe, Das neutrale Element bezeichnen wir mit $0$, das Inverse zu $x ∈ M$ mit $- x$.
  - (M2) Die skalare Multiplikation ist in folgender Weise mit den Verknüpfungen auf $M$ und $R$ verträglich:
	- $(a + b)  x = a x + b x$
	- $a(x + y) = a x + a y$
	- $(a b) x = a (b x)$
	- $1 · x = x$
	$∀ a, b ∈ R, x, y . M$
  #+end_defn
  #+begin_ex latex
  1. $K$ Körper, $V$ K-Vektorraum $⇒$ $V$ ist ein K-Modul.
  2. $(G, +)$ abelsche Gruppe wird zum $ℤ$ -Modul durch
	 \[ℤ × G \to G, (n, g) ↦ \begin{cases} \underbrace{g + \dots + g}_{n \text{ -mal}} & n ∈ ℕ \\ 0 & n = 0 \\ -\underbrace{(g + \dots + g)}_{n \text{ -mal}} & -n ∈ ℕ\end{cases}\]
	 Umgekhert ist jeder $ℤ$ -Modul eine abelsche Gruppe bezüglich "+".
  3. $I ⊆ R$ Ideal $⇒$ $I$ ist ein $R$ -Modul (Addition: auf $I$ eingeschränkte Addition von $R$, skalare Multiplikation: $R × I \to I, (a, x) ↦ a x$).
	 Insbesondere ist $R$ ein $R$ -Modul.
  4. $I ⊆ R$ Ideal $⇒ \faktor{R}{I}$ ist ein $R$ -Modul (skalare Multiplikation: $R × \faktor{R}{I} \to \faktor{R}{I}, (a, \bar x) ↦ \overline{a x}$)
  5. $K$ Körper, $V$ K-Vektorraum, $φ ∈ \End(V) ⇒ V$ ist $K[t]$ -Modul via skalare Multiplikation:
	 \[K[t] × V \to V, (f, v) ↦ f(φ)(v)\]
  #+end_ex
  #+begin_defn latex
  $M, N$ R-Moduln, $φ: M \to N$. $φ$ heißt R-Modul-*Homomorphisum* $\xLeftrightarrow{\text{Def}}$ Für alle $x, y ∈ M, a ∈ R$ gilt:
  \begin{align*}
  φ(x + y) &= φ(x) + φ(y) \\
  φ(a x) &= a φ(x)
  \end{align*}
  $φ$ heißt (R-Modul)-*Isomorphimus* $\xLeftrightarrow{\text{Def}}$ $φ$ ist ein bijektiver R-Modul-Homomorphismus. $∃$ ein Isomorphismus zwischen $M, N$, so scheiben wir $M \cong N$.
  #+end_defn
  #+begin_defn latex
  $M$ R-Modul, $N ⊆ M$. $N$ heißt ein *Untermodul* von $N \xLeftrightarrow{\text{Def}}$ Folgende Bedingungen sind erfüllt:
  - (U1) $0 ∈ N$
  - (U2) $x, y ∈ N ⇒ x + y ∈ N$
  -	(U3) $a ∈ R, x ∈ N ⇒ a x ∈ N$
  #+end_defn
  #+begin_ex latex
  1. $K$ Körper, $V$ K-Vektorraum $⇒$ Untermoduln von $V$ = Untervektorraum von $V$
  2. $M = R$ als R-Modul $⇒$ Untermodul von $M$ = Ideale in $R$.
  #+end_ex
  #+begin_remdef latex
  $M$ R-Modul, $N ⊆ M$ Untermodul. Dann gilt: Durch $x \sim y \xLeftrightarrow{\text{Def}} x - y ∈ N$ ein eine Äquivalentzrelation definiert.
  Die Äquivalenzklasse $\bar x$ von $x ∈ M$ ist gegeben durch
  \[\bar x = x + N = \{x + y \mid y ∈ N\}\]
  Die Menge aller Äquivalenzklassen bezeichenn wir mit $\faktor{M}{N}$.
  $\faktor{M}{N}$ wird mit den Verknüpfungen
  \begin{align*}
  &+: \faktor{M}{N} × \faktor{M}{N} \to \faktor{M}{N}, \bar x + \bar y := \overline{x + y} \\
  &·: R × \faktor{M}{N} \to \faktor{M}{N}, a · \bar x := \overline{a x}
  \end{align*}
  zu einem R-Modul, dem *Faktormodul* $\faktor{M}{N}$. Die *kanonische Projektion*
  \[π: M \to \faktor{M}{N}, x ↦ \bar x\]
  ist ein surjektiver R-Modulhomomorphismus
  #+end_remdef
  #+begin_proof latex
  analog zu K-Vektorraum, vergleiche 13.7,13.8
  #+end_proof
  #+begin_remdef latex
  $M, N$ R-Moduln, $φ: M \to N$ Homomorphismus. Dann gilt:
  1. $\ker φ := \{x ∈ M \mid φ(x) = 0\}$ ist ein Untermodul von $M$.
  2. $φ$ ist injektiv $⇔ \ker φ = \{ 0\}$
  3. $\im φ := φ(M)$ ist ein Untermodul von $N$.
  4. $\coker φ := \faktor{N}{\im φ}$ heißt der *Cokern* von $φ$, es gilt: $φ$ surjektiv $⇔$ $\coker φ = \{0\}$
  5. (Homomorphiesatz) $φ$ induziert einen Isomorphismus
	 \[Φ: \faktor{M}{\ker φ} \to \im φ, x + \ker φ ↦ φ(x)\]
  #+end_remdef
  #+begin_proof latex
  analog wie für K-Vektorraum.
  #+end_proof
  #+begin_remdef latex
  $M$ R-Modul, $(M_i)_{i ∈ I}$ Familie von Untermoduln von $M$. Dann gilt:
  1. \[\sum_{i = I} M_i := \{\sum_{i ∈ I} x_i \mid x_i ∈ M_I, x_i = 0 \text{ für fast alle } i ∈ I\}\]
	 ist ein Untermodul von $M$ und heißt die *Summe* der $M_i, i ∈ I$.
  2. \[∩_{i ∈ I} M_i\] ein ein Untermodul von $M$.
  #+end_remdef
  #+begin_proof latex
  nachrechnen.
  #+end_proof
  #+begin_remdef latex
  $(M_i)_{i ∈ I}$ Familie von R-Moduln. Dann gilt:
  1. \[\prod_{i ∈ I} M_i := \{(x_i)_{i ∈ I} \mid x_i ∈ M_i\}\]
	 wird mit komponentenweiser Addition und skalarer Multiplikation ein R-Modul, das *direkte Produkt* der $M_i, i ∈ I$
  2. \[\oplus_{i ∈ I} M_i := \{(x_i)_{i ∈ I} \mid x_i ∈ M_i, x_i = 0 \text{ für fast alle } i ∈ I\}\]
	 wird mit komponentenweiser Addiiton und skalarer Multiplikation ein R-Modul, die *direkte Summe* der $M_i, i ∈ I$
  Falls $I$ endlich, dann ist
  \[\prod_{i ∈ I} M_i = \oplus_{i ∈ I} M_i\]
  Spezialfall:
  \[R^n = \oplus_{i = 1}^n R\]
  #+end_remdef
  #+begin_proof latex
  nachrechnen.
  #+end_proof
  #+begin_note latex
  Zusammenhang zur direkten Summe von Untervektorräumen aus LA1: Sei $M$ R-Modul, $M_1, M_2 ⊆ M$ Untermoduln
  \[M_1 \oplus M_2 = \{(m_1, m_2) \mid m_1 ∈ M_1, m_2 ∈ M_2\}\]
  $⇒$ Erhaltne surjektiven Homomorphisums
  \[φ: M_1 \oplus M_2 \to M_1 + M_2, (m_1, m_2) ↦ m_1 + m_2\]
  ist $M_1 ∩ M_2 = \{0\}$, dann ist
  \[\ker φ = \{(m_1, m_2) ∈ M_1 \oplus M_2 \mid m_1 + m_2 = 0\} = \{0\}\]
  denn: $m_1 + m_2 = 0 ⇒ m_1 = - m_2 ∈ M_1 ∩ M_2 = \{0\}$, also $m_1 = m_2 = 0$.
  das heißt wir erhalten einen Isomorphismus von R-Moduln $M_1 \oplus M_2 \cong M_1 + M_2$. Insbesondere: ist $M_1 + M_2 = M, M_1 ∩ M_2 = \{0\}$, dann
  ist $M_1 \oplus M_2 \cong M$.
  #+end_note
  #+begin_remdef latex
  $I ⊆ R$ Ideal, $M$ R-Modul, $(x_i)_{i ∈ I}$ Familie von Elementen aus	$M$. Dann gilt:
  1. \[J M := \{\sum_{i = 1}^{n} a_i · x_i \mid a_i ∈ I, x_i ∈ M, n ∈ ℕ\}\]
	 ist ein Untermodul von $M$.
  2. \[\Lin((x_i)_{i ∈ I}) := \{\sum_{i ∈ I} a_i x_i \mid a_i ∈ R, a_i = 0 \text{ für fast alle } i ∈ I\}\] ist ein Untermodul von $M$, die
	 *lineare Hülle* von $(x_i)_{i ∈ I}$.
  #+end_remdef
  #+begin_defn latex
  $M$ R-Modul, $(x_i)_{i ∈ I}$ Familie von Elementen aus $M$. $(x_i)_{i ∈ I}$ heißt
  - *Erzeugendensystem* von $M \xLeftrightarrow{\text{Def}} M = \Lin((x_i)_{i ∈ I})$.
  - *linear unabhängig* $\xLeftrightarrow{\text{Def}}$ aus
	\[\sum_{i ∈ I} a_i x_i = 0\]
	wobei $a_i ∈ R, a_i = 0$ für fast alle $i ∈ I$ folgt $a_i = 0 ∀ i ∈ I$
  - *Basis* von $M \xLeftrightarrow{\text{Def}} (x_i)_{i ∈ I}$ ist ein linear unabhängiges Erzeugendessystem von $M$.
  $M$ heißt
  - *endlicherzeugt* $\xLeftrightarrow{\text{Def}}$ $M$ besitzt ein endliches Erzeugendessystem
  - *frei* $\xLeftrightarrow{\text{Def}}$ $M$ besitzt eine Basis
  -	*endlichfrei* $\xLeftrightarrow{\text{Def}}$ $M$ besitzt eine endliche Basis
  #+end_defn
  #+begin_ex latex
  1. $K$ Körper $⇒$ Jeder K-Vektorraum ist frei
  2. $R$ ist freier R-Modul ($(1)$ ist eine Basis)
  3. Sei $n ∈ ℕ, n > 1$
	 - $\faktor{ℤ}{nℤ}$ ist endlicherzeugtes $ℤ$ -Modul, denn:
	   - $\faktor{ℤ}{n ℤ}$ ist als abelsche Gruppe ein $ℤ$ -Modul.
	   - $\Lin((\bar 1)) = \{r · \bar 1 \mid r ∈ ℤ\} = \{\bar r \mid r ∈ ℤ\} = \faktor{ℤ}{nℤ}$. $(\bar 1)$ ist ein Erzeugendessystem von $ℤ$ als $ℤ$ -Modul.
	   - $\faktor{ℤ}{nℤ}$ ist kein freier $ℤ$ -Modul, denn: Sei $x = \bar a ∈ \faktor{ℤ}{nℤ} ⇒ n x = n \bar a = \overline{n a} = \bar 0$, aber $n \neq 0$.
		 $⇒ (x)$ linear abhängig $⇒$ Jede Familie $\neq ()$ von $\faktor{ℤ}{nℤ}$ ist linear abhängig. Insbesondere kann $\faktor{ℤ}{nℤ}$ keine Basis als $ℤ$ -Modul haben.
	   Beachte: Als $\faktor{ℤ}{n ℤ}$ -Modul ist $\faktor{ℤ}{nℤ}$ frei (siehe 2.)
  #+end_ex
  Fazit: Es gibt Moduln, die keine Basis haben.
  #+begin_remark latex
  $M$ freier R-Modul, $\mathcal{B} = (x_i)_{i ∈ I}$ Basis von $M$. Dann	existiert ein Modulisomorphisums
  \[Φ_{\mathcal{B}}: \oplus_{i ∈ I} R \to M, (a_i)_{i ∈ I} ↦ \sum_{i ∈ I} a_i x_i\]
  (beachte: $a_i = 0$ für fast alle $i ∈ I$)
  #+end_remark
  #+begin_proof latex
  - $Φ_{\mathcal{B}}$ Homomorphismus: klar
  - $Φ_{\mathcal{B}}$ surjektiv, denn: $\mathcal{B}$ Erzeugendessystem von $M$
  -	$Φ_{\mathcal{B}}$ injektiv, denn: $\mathcal{B}$ linear unabhängig
  #+end_proof
  #+begin_note latex
  - Man kann zeigen: Sind $(x_i)_{i ∈ I}, (y_j)_{j ∈ J}$ Basen des freien R-Moduls $M$, dass existiert eine Bijektion $I \to J$, das heißt $\abs{I} = \abs{J}$.
	Wir werden obige Aussage in 30 für endlich freie Moduln über Hauptidealringe zeigen.
  - Man kann zeigen: $M$ endlicherzeugt $⇔ M$ endlich frei
  -	Achtung: Es gilt im Allgemeinen kein Analogon des Basisauswahlsatzes: $(2, 3)$ ist ein Erzeugendensystem des freien $ℤ$ -Moduls $ℤ$ wegen $1 = (-1) · 2 + 1 · 3$,
	aber weder $(2)$ noch $(3)$ sind Basen von $ℤ$.
  #+end_note
  #+begin_note latex
  Man kann zeigen: Sind $M, N$ endlich freie R-Moduln, dann kann man ananlog zu LA1 jeden Modulhomomorphismus $φ: M \to N$ nach
  Wahl von Basen $\mathcal{A}$ von $M$, $\mathcal{B}$ von $N$ durch eine Darstellungsmatrix $M_{\mathcal{B}}^{\mathcal{A}}(φ)$ beschreiben. Es
  gilt die Basiswechselformel
  \[M_{\mathcal{B}'}^{\mathcal{B}'}(φ) = T_{\mathcal{B}'}^{\mathcal{B}} M^{\mathcal{A}}_{\mathcal{A}} T_{\mathcal{A}}^{\mathcal{A}'}\]
  wobei $T_{\mathcal{A}}^{\mathcal{A}'} = M_{\mathcal{A}}^{\mathcal{A}'}(\id_M), T_{\mathcal{B}'}^{\mathcal{B}} = M_{\mathcal{B}'}^{\mathcal{B}}(\id_M)$ (Beweis analog zu LA1).
  #+end_note
  #+begin_remark latex
  $M, N$ R-Moduln, $φ: M \to N$ Homomorphismus, sodass $\ker(φ), \im(φ)$ endlich erzeugt. Dann ist $M$ ein endlich erzeugtes R-Modul.
  #+end_remark
  #+begin_proof latex
  Sei $(x_1, \dots, x_m)$ ein Erzeugendensystem von $\ker φ ⊆ M$, $(y_1, \dots, y_n)$ ein Erzeugendensystem von $\im φ ⊆ N$.
  Wir wählen $\tilde y_i ∈ φ^{-1}(\{y_i\})$ für	$i = 1, \dots, n$. Behauptung: $(x_1, \dots, x_m, \tilde y_1, \dots, \tilde y_n)$ ist ein Erzeugendensystem von $M$, denn: Sei
  $m ∈ M ⇒ φ(m) ∈ \im φ$, das heißt $∃ a_1, \dots, a_n ∈ R$, sodass
  \begin{align*}
  φ(m) &= a_1 y_1 + \dots + a_n y_n = a_1 φ(\tilde y_1) + \dots + a_n φ(\tilde y_n) \\
  &= φ(a_1 \tilde y_1 + \dots + a_n \tilde y_n) \\
  ⇒ m - (a_1 \tilde y_1 + \dots + a_n \tilde y_n) ∈ \ker φ \\
  \end{align*}
  \[⇒ ∃ b_1, \dots, b_m ∈ R: m - (a_1 \tilde y_1 + \dots + a_n \tilde y_n) = b_1 x_1 + \dots b_m x_m\]
  \[⇒ m = b_1 x_1 + \dots + b_m x_m + a_1 \tilde y_1 + \dots + a_n \tilde y_n\]
  #+end_proof
  #+begin_remdef latex
  $M$ R-Modul. $x ∈ M$ heißt ein *Torsionselement* von $M$ $\xLeftrightarrow{\text{Def}}$ $∃ a ∈ R$, $a$ kein Nullteiler, mit $a x = 0$.
  \[T(M) = \{x ∈ M \mid x \text{ ist ein Torsionselement}\}\]
  ist ein Untermodul von $M$, der *Torsionsuntermodul* von $M$. $M$ heißt \\
  *Torsions-R-Modul* $\xLeftrightarrow{\text{Def}} T(M) = M$ \\
  *torsionsfreier R-Modul* $\xLeftrightarrow{\text{Def}} T(M) = \{0\}$
  #+end_remdef
  #+begin_proof latex
  U1: $0 ∈ T(M)$ wegen $1_R · 0 = 0$. \\
  U2: $x, y ∈ T(M) ⇒ ∃ a, b ∈ R$, $a, b$ keine Nullteiler mit $a x = 0, b y = 0$.
  \[⇒ a b x = 0, a b y = 0 ⇒ a b (x + y) = 0\]
  Wegen $a, b$ keine Nullteiler ist $a b$ auch kein Nullteiler $⇒ x + y ∈ T(M)$. \\
  U3: Sei $x ∈ T(M), a ∈ R ⇒ ∃ b ∈ R, b$ kein Nullteiler mit $b x = 0$
  \[⇒ b (a x) = 0 = (ba) x = (a b) x = a \underbrace{(b x)}_{= 0} = 0 ⇒ a x ∈ T(M)\]
  #+end_proof
  #+begin_note latex
  Falls $R$ nullteilerfrei, dann $T(M) = \{x ∈ M \mid ∃ a ∈ R, a \neq 0: a x = 0\}$
  #+end_note
  #+begin_ex latex
  1. $K$ Körper, $V$ K-Vektorraum $⇒ V$ ist torsionsfreier K-Modul, denn:
	 \[T(V) = \{x ∈ V \mid ∃ λ ∈ K, λ \neq 0: λ x = 0\} = \{0\}\]
  2. $ℤ$ ist ein torsionsfreier $ℤ$ -Modul, denn:
	 \[T(ℤ) = \{x ∈ ℤ \mid ∃ a ∈ ℤ, a \neq 0: a x = 0\} = \{0\}\]
  3. Für $n ∈ ℕ, n > 1$ ist $\faktor{ℤ}{nℤ}$ ist ein Torsions- $ℤ$ -Modul, denn für alle $\bar a ∈ \faktor{ℤ}{nℤ}$ ist
	 \[n · \bar a = \overline{n a} = \bar 0\]
	 das heißt
	 \[T(\faktor{ℤ}{nℤ}) = \faktor{ℤ}{nℤ}\]
  #+end_ex
  #+begin_remark latex
  $F$ freier R-Modul. Dann sit $F$ torsionsfrei, das heißt $T(F) = \{0\}$
  #+end_remark
  #+begin_proof latex
  Sei $(x_i)_{i ∈ I}$ eine Basis von $F, y ∈ T(F), a ∈ R$ kein Nullteiler mit $a y = 0$. $⇒ ∃ b_{i_1}, \dots, b_{i_j}: y = b_{i_1} x_{i_1} + \dots + b_{i_s} x_{i_s}$.
  \[⇒ 0 = a y = a b_{i_1} x_{i_1} + \dots + a b_{i_s} x_{i_s} ⇒ a b_{i_1} = \dots = a b_{i_s} = 0\]
  $⇒ b_{i_1} = \dots = b_{i_s} = 0 ⇒ y = 0$, also $T(F) = \{0\}$
  #+end_proof
  #+begin_note latex
  Die Umkehrung ist falsch: $ℚ$ ist torsionsfreier $ℤ$ -Modul, aber kein freier $ℤ$ -Modul.
  - $ℚ$ ist torsionsfreier $ℤ$ -Modul, denn: $T(ℚ) = \{x ∈ ℚ \mid ∃ a ∈ ℤ, a \neq 0: a x = 0\} = \{0\}$
  - $ℚ$ ist kein freier $ℤ$ -Modul, denn:
	- Sind $a, b ∈ ℚ$, dann ist die Familie $(a, b)$ $ℤ$ -linear abhängig, da: Ist $a = m_1 / n_1 \neq 0, b = m_2 / n_2 \neq 0$, dann ist
	  \[m_2 n_1 a - m_1 n_2 b = 0\]
	- Leere Familie, beziehungsweise einelementige Familien sind keine Erzeugendensysteme von $ℚ$ als $ℤ$ -Modul.
  #+end_note
  #+ATTR_LATEX: :options [Länge]
  #+begin_defn latex
  $M$ R-Modul.
  \[l_R(M) := \sup \{l ∈ ℕ_0 \mid M_0 = \{0\} \subsetneq M_1 \subsetneq M_2 \subsetneq \dots \subsetneq M_l = M \text{ ist eine Kette von Untermoduln von } M\} ∈ N_0 ∪ \{∞\}\]
  heißt die *Länge* von $M$.
  #+end_defn
  #+begin_ex latex
  1. $K$ Körper, $V$ K-Vektorraum $⇒ L_K(V) = \dim_K(V)$, denn:
	 - $\dim_K(V) = n < ∞ ⇒$ Wähle Basis $(v_1, \dots, v_n)$ von $V$, dann ist
	   \[M_0 = \{0\} \subsetneq \Lin(v_1) \subsetneq \Lin(v_1, v_2) \subsetneq \dots \subsetneq \Lin(v_1, \dots, v_n) = V\]
	   eine Kette von Untervektorräumen von $V ⇒ l_K(V) \geq n$. \\
	   Ist $M_0 = \{0\} \subsetneq M_1 \subsetneq \dots \subsetneq M_l = V$ eine Kette von Untermoduln, dann ist $0 < \dim M_1 < \dots < \dim M_l = \dim V = n$, insbesondere
	   $\dim V = \dim M_l \geq l$, also $l_ K(V) \leq n$.
	 - $\dim_K(V) = ∞ ⇒ l_K(V) = ∞$.
  2. $l_{ℤ}(ℤ) = ∞$, dann: für alle $n ∈ ℕ$ ist $0 \subsetneq 2^n ℤ \subsetneq 2^{n - 1} ℤ \subsetneq \dots \subsetneq 2 ℤ \subsetneq ℤ$ eine
	 Kette von Untermoduln von $ℤ$.
  3. $l_{ℤ}(\faktor{ℤ}{6ℤ}) = 2$, dann: Für $\bar a ∈ \faktor{ℤ}{6ℤ}$ ist
	 \[\Lin(\bar a) = \begin{cases} \faktor{ℤ}{6ℤ} & \bar a ∈ \{\bar 1, \bar 5\} \\ \{\bar 0\} & \bar a = \bar 0 \\ \{\bar 0, \bar 3\} & \bar a = \bar 3 \\ \{\bar 0, \bar 2, \bar 4\} & \bar a ∈ \{\bar 2, \bar 4\}\end{cases}\]
	 $⇒$ Die beiden Ketten $\{0\} \subsetneq \Lin(\{\bar 3\}) \subsetneq \faktor{ℤ}{6ℤ}, \{\bar 0\} \subsetneq \Lin(\bar 2) \subsetneq \faktor{ℤ}{6ℤ}$ können nicht weiter verfeinert werden, also
	 $l_{ℤ}(\faktor{ℤ}{6ℤ}) = 2$
  4. $l_R(M) = 0 ⇔ M = \{0\}$
  #+end_ex
  #+begin_remark latex
  $M$ R-Modul, $N ⊆ M$ Untermodul. Dann gilt: $l_R(N) \leq l_R(M)$.
  #+end_remark
  #+begin_proof latex
  Ist $0 \subsetneq N_1 \subsetneq N_2 \subsetneq \dots \subsetneq N_l = N$ eine Kette von Untermoduln von $N$, dann ist
  $0 \subsetneq N_1 \subsetneq \dots \subsetneq N_l = N ⊆ M$ eine Kette von Untermoduln von $M$ gleicher oder gröherer Länge.
  #+end_proof
  #+begin_remark latex
  $M', M''$ R-Moduln. Dann gilt: $l_R(M' \oplus M'') = l_R(M') + l_R(M'')$.
  #+end_remark
  #+begin_proof latex
  1. Es genügt zu zeigen: $M$ R-Modul, $M', M'' ⊆ M$ Untermoduln mit $M = M' \oplus M''$, dann ist
	 \[l_R(M) = l_R(M') + l_R(M'')\]
	 (Setze $M = M' \oplus M''$, ersetze $M', M''$ durch isomorphen Moduln $M' \oplus \{0\}, \{0\} \oplus M''$, $M$ ist die direkte Summe dieser Untermoduln)
  2. Beweis von "$\geq$" \\
	 Seien $\{0\} \subsetneq M_1' \subsetneq \dots \subsetneq M_r' = M', \{0\} \subsetneq M_1'' \subsetneq \dots \subsetneq M_s'' = M''$ Ketten von Untermoduln von $M'$ beziehungsweise von $M''$.
	 \[⇒ \{0\} \subsetneq M_1' \oplus \{0\} \subsetneq \dots \subsetneq M_r' \oplus \{0\} \subsetneq M_r' \oplus M_1'' \subsetneq \dots \subsetneq M_r' \oplus M_s'' = M\]
	 ist eine Kette von Untermoduln von $M$.
  3. Beweise von "$\leq$" \\
	 Sei $0 \subsetneq M_1 \subsetneq \dots \subsetneq M_l = M$ eine Kette von Untermoduln von $M$. Wir betrachten die Abbildung
	 \[π: M = M' \oplus M'' \to M'', a + b ↦ b\]
	 Behautung: Für alle $0 \leq i < l$ gilt:
	 \[M_i ∩ M' \subsetneq M_{i + 1} ∩ M' \text{ oder } π(M_i) \subsetneq π(M_{i + 1})\]
	 Annahme: Es existiert $i$ mit $M_i ∩ M' = M_{i + 1} ∩ M'$ und $π(M_i) = π(M_{i + 1})$. $⇒$ Für alle $a ∈ M_{i + 1} ∃ b ∈ M_i: π(a) = π(b)$.
	 \[⇒ a - b ∈ \ker π = M' ⇒ a - b ∈ M_{i + 1} ∈ M_{i + 1} ∩ M' = M_i ∩ M' ⊆ M_i\]
	 \[a = (a - b) + b ∈ M_i ⇒ M_{i + 1} ⊆ M_i ⊆ M_{i + 1} ⇒ M_{i + 1} = M_i \lightning\]
	 Wegen der Behautung gibt es in den Ketten $0 ⊆ π(M_1) ⊆ \dots ⊆ π(M_l) = M''$ und
	 $0 ⊆ M_1 ∩ M' ⊆ \dots ⊆ M_l ∩ M' = M'$ zusammen mindestens $l$ echte Inklusionen, höchstens aber $l_R(M'') + l_R(M')$ echte Inklusionen. $⇒ l \leq l_R(M') + l_R(M'')$
  #+end_proof
* Moduln über Hauptidealringen
  In diesem Abschnitt sei $R$ stets ein Hauptidealring. \\
  Ziel: Struktursatz für endlich erzeugte R-Moduln.
  #+begin_remdef latex
  $F$ endlich freier R-Modul. Dann gilt: Je zwei Basen von $F$ haben dieselbe Kardinalität. Diese heißt *Rang* von $F$.
  #+end_remdef
  #+begin_proof latex
  1. Falls $R$ Körper, dann $F$	endlichdimensionaler R-Vektorraum, Behautung folgt aus 9.8. Im Folgenden sei $R$ kein Körper.
  2. Da $F$ endlich frei, existiert endliche Basis $(v_1, \dots, v_s)$ von $F$. Sei $(w_i)_{i ∈ I}$ eine beliebige Basis von $F$
	 \[⇒ F \cong R^s, \quad F \cong \oplus_{i ∈ I} R =: M\]
	 $⇒ ∃$ R -Modulisomorphismus $ρ:R^s \to M$.
  3. Es	existiert irreduzibles Element $p ∈ R$. dann: $R$ kein Körper $⇒ ∃ a ∈ R \setminus (R^{\ast} ∪ \{0\}) ⇒ a$ lässt sich als Produkt irreduzibler Elemente schreiben $⇒$ es existieren irreduzible Elemente
	 $p ∈ R$.
  4. Wir betrachten Abbildung $\bar ρ: R^s \to \faktor{M}{pM}, x ↦ ρ(x) + p M$
	 - $\bar ρ$ ist	Homomorphismus, da $ρ$ Homomorphismus
	 - $\bar ρ$ ist surjektiv, da $ρ$ surjektiv
	 - $\ker \bar ρ = p R^s$, denn:
	   "$\supseteq$": Sei $x ∈ p R^s ∃ y ∈ R^s: x = p y ⇒ \bar ρ(x) = ρ(x) + p M = ρ(p y) + p M = \underbrace{p ρ(y)}_{∈ p M} + p M ⇒ x ∈ \ker \bar ρ$ \\
	   "$⊆$" Sei $x ∈ \ker \bar ρ ⇒ ρ(x) ∈ p M ⇒ ∃ y ∈ M: ρ(x) = p y ⇒ ∃ \tilde y ∈ R^s:$
	   \[y = ρ(\tilde y) ⇒ ρ(x) = p ρ(\tilde y) = ρ(p \tilde y) ⇒ x = p \tilde y ∈ p R^s\]
	   Nach Homomorphiesatz erhalten wir einen Isomorphismus
	   \[\faktor{R^s}{p R^s} \to \faktor{M}{p M}\]
	   von R-Moduln
  5. Die Abbildung $θ: \faktor{R^s}{p R^s} \to (\faktor{R}{p R})^s, (x_1, \dots, x_s) + p R^s ↦ (x_1 + p R, \dots, x_s + p R)$ ist ein Isomorphismus von R-Moduln:
	 - $θ$ Homomorphismus: klar
	 - $θ$ surjektiv: klar
	 - $θ$ injektiv: Sei $θ((x_1, \dots, x_s) + p R^s) = 0 = (p R, \dots, p R) ⇒ (x_1 + p R, \dots, x_s + p R) = (p R, \dots, p R)$
	   $⇒ x_1, \dots, x_s ∈ p R ⇒ (x_1, \dots, x_s) + p R^s = p R^s$.
	 Analog ist
	 \[\faktor{M}{p M} = \oplus_{i ∈ I} \faktor{R}{p \oplus_{i ∈ I} R} \cong \oplus_{i ∈ I} \faktor{R}{p R}\]
  6. Aus 4., 5. erhalten wir Isomorphismus $Φ:(\faktor{R}{p R})^s \to \oplus_{i ∈ I} \faktor{R}{p R}$ von R-Moduln.
	 Da $p$ irreduzibel, ist $K := \faktor{R}{p R}$ ein Körper (Anmerkung nach 26.26). Quelle / Ziel von $Φ$ sind K-Vektorräume via skalarer Multiplikation.
	 \[K × (\faktor{R}{p R})^s \to (\faktor{R}{p R})^s, (a + p R) · (x_1 + p_R, \dots, x_s + p R) := (a x_1 + p R, \dots, a x_s + p R) = a(x_1 + p R, \dots, x_s + p R)\]
	 analog für $\oplus_{i ∈ I} \faktor{R}{p R}$. $Φ$ ist auch ein Isomorphismus von K-Vektorräumen, denn
  	 \begin{align*}
	 Φ((a + p R)(x_1 + p R, \dots, x_s + p R)) &= Φ(a(x_1 + p R, \dots, x_s + p R)) = a Φ(x_1 + p R, \dots, x_s + p R) \\
	 &= (a + p R) Φ(x_1 + p R, \dots, x_s + p R)
     \end{align*}
  7. Wegen 6. ist $Φ: K^s \to \oplus_{i ∈ I} K$ ein K-Vektorraum-Isomorphismus. Wegen 1. folgt $\abs{I} = s$.
  #+end_proof
  #+begin_defthm latex
  $A ∈ M(m × n, R)$. Dann existeren $r ∈ ℕ_0, c_1, \dots, c_r ∈ R \setminus \{0\}$, sodass
  \[A \sim \begin{pmatrix} c_1 \\ & \ddots \\ & & c_r \\ & & & 0 \\ & & & & \ddots \\ & & & & & 0 \end{pmatrix}\]
  mit $c_1 \mid \dots \mid c_r$. $r$ ist eindeutig bestimmt, $c_1, \dots, c_r$ sind eindeutigb bestimmt bis auf Assoziiertheut und heißen die *Elementarteiler* von $A$.
  #+end_defthm
  #+begin_proof latex
  1. Eindeutigkeit: Wie im Beweis von 27.17 über Fittingideale
  2. Existenz: Wir gehen ähnlich vor wie bei Gauß-Diagonalisierung (vergleiche Beweis von 27.8) und modifizieren das Verfahren wie folgt: Setze $δ: R \setminus \{0\} \to ℕ_0, a ↦$ Anzahl der
	 Primfaktoren von $a$ (mit Vielfachheit gerechnet). (insbesondere $δ(a) = 0$ für $a ∈ R^{\ast}$)
	 1. Schritt: Erreiche durch Zeilen- und Spaltenvertauschung, dass $δ(a_11) \leq δ(a_{ij}) ∀ i, j$ mit $a_{ij} \neq 0$
	 2. Schritt: Bringe $A$ auf die Form
		\[(\begin{array}{c|ccc} a_{11} & & 0 & \\ \hline \\ 0 & & \ast & \\ \\ \end{array})\]
		Falls $a_{11} \mid a_{1i}$ und $a_{11} \mid a_{j1}$ für alle $i, j$, dann erreiche obige Form durch elementare Zeilen- und Spaltenumformungen. Andernfalls: Ohne Einschränkung gelte
		$a_{11} \nmid a_{i1}$ für ein $i > 1$. Da $R$ Hauptidealring, ist $\GGT(a_{i1}, a_{11}) \neq \emptyset$. Sei $β ∈ \GGT(a_{11}, a_{i1})$. Da $a_{11} \nmid a_{i1}$ ist
		$δ(β) < δ(a_{11})$ ($β$ kann nicht gleich viele Primteiler wie $a_{11}$ haben, sonst $β \estimates a_{11} ⇒ a_{11} \mid a_{i1} \lightning$)
		Nach 26.22 existieren $u, v ∈ R$ mit $β = u a_{11} + v a_{i1}$, und es existieren $\tilde u, \tilde v ∈ R$ mit
		\[a_{11} = β \tilde u, a_{i1} = β \tilde v ⇒ β = u β \tilde u + v β \tilde v = β(u \tilde u + v \tilde v) ⇒ β(1 - (u \tilde u + v \tilde v)) = 0\]
		$⇒ u \tilde u + v \tilde v = 1$. Es ist
		\[\underbrace{\begin{pmatrix} u & & & & v \\ & 1 \\ & & \ddots \\ & & & 1 \\ -\tilde v & & & & \tilde u \\ & & & & & 1 \\ & & & & & & \ddots \\ & & & & & & & 1\end{pmatrix}}_{=: B} \begin{pmatrix} u & & & & -v \\ & 1 \\ & & \ddots \\ & & & 1 \\ \tilde v & & & & \tilde u \\ & & & & & 1 \\ & & & & & & \ddots \\ & & & & & & & 1\end{pmatrix} = \begin{pmatrix} 1 & & & & 0 \\ & 1 \\ & & \ddots \\ & & & 1 \\ 0 & & & & 1 \\ & & & & & 1 \\ & & & & & & \ddots \\ & & & & & & & 1\end{pmatrix}\]
		das heißt $B ∈ \GL(n, R)$. Multiplikation von $B$ von links bewirkt folgende Zeilenoperationen:
		- neue erste Zeile = $u$ -faches der alten ersten Zeile + $v$ -faches der alten i-ten Zeile
		- neue i-te Zeile =	$- \tilde v$ -faches der alten ersten Zeile + $\tilde u$ -faches der alten i-ten Zeile
		In der Matrix $B A$ steht links oben das Element $β$ mit $δ(β) < δ(a_{11})$. Erhalte durch Zeilen-/Spaltenvertauschung an $A' = BA$ eine Matrix $A'' = (a_{ij}'')$ mit $δ(a_{11}'') < δ(a_{ij}'')$
		für alle $i, j, a_{ij}'' \neq 0$ und $δ(a_{11}'') < δ(a_{11})$.	Dieser Prozess bricht nach endlich vielen Iterationen ab. Wir erhalten eine Matrix der Form
		\[D = (\begin{array}{c|ccc} d_{11} & & 0 & \\ \hline \\ 0 & & \ast & \\ \\ \end{array}), d_{11} \neq 0, δ(d_{11}) \leq δ(a_{11}), δ(d_{11}) \leq δ(d_{ij}) ∀ i,j, d_{ij} \neq 0\]
	 3. Schritt: Führe das Verfahren analog zu der Gauß-Diagonalisierung über Euklidischen Ringen weiter (mit Modifikationen analog zu oben).
  #+end_proof
  #+begin_remark latex
  $R$ Hauptidealring, $a ∈ R \setminus (R^{\ast} ∪ \{0\}), a = p_1 · \dots · p_r$ mit irreduziblen Elementen $p_1, \dots, p_r$ (nicht notwendig paarweise verschieden). Dann ist
  \[l_{R}(\faktor{R}{a R}) = r\]
  insbesondere ist $l_R(\faktor{R}{aR}) < ∞$
  #+end_remark
  #+begin_proof latex
  1. Nach Übungen induziert die kanonische Projektion $π: R \to \faktor{R}{a R}$ eine Bijektion
	 \[Φ: \{\text{Ideale } I ⊆ R, I \supseteq a R\} \to \{\text{Ideale von } \faktor{R}{a R}\}\]
	 Hierbei: Ideale in $\faktor{R}{a R}$ = $\faktor{R}{aR}$ -Untermoduln von $\faktor{R}{a R}$ = $R$ -Untermoduln von $\faktor{R}{a R}$ (skalare Multiplikation: $R × \faktor{R}{a R} \to \faktor{R}{aR}, (b, x + a R) ↦ b x + a R$)
  2. Aus 1. folgt:
	 \begin{align*}
	 l_R(\faktor{R}{a R}) &= \sup \{l ∈ ℕ_0 \mid (a) \subsetneq I_1 \subsetneq \dots \subsetneq I_l = R, I_k \text{ Ideale in } R\} \\
	 &= \sup\{l ∈ ℕ_0 \mid (a) \subsetneq (a_1) \subsetneq \dots \subsetneq (a_l) = R, a_i ∈ R\} \\
	 &= \sup\{l ∈ ℕ_0 \mid a_l \mid a_{l - 1} \mid \dots \mid a_1 \mid a_0 := a, a_i ∈ R, a_l ∈ R^{\ast}, a_i \not \estimates a_{i + 1}, i = 0, \dots, l - 1\}
   	 \end{align*}
  3. Wegen $1 \mid p_1 \mid p_1 p_2 \mid \dots \mid p_1 · \dots · p_r = a$ folgt $l_R(\faktor{R}{aR}) \geq r$ \\
	 Da $R$ Hauptidealring und insbesondere faktoriell, hat $a$ bis auf Assoziiertheit nur endlich viele Teiler, insbesondere $l_R(\faktor{R}{aR}) < ∞$.
	 Annahme:
     \[l_R(\faktor{R}{a R}) = s > r ⇒ ∃ a_1, \dots, a_s ∈ R \setminus \{0\}: a_s \mid a_{s - 1} \mid \dots \mid a_{1} \mid a_0 = 0\]
	 ohne Einschränkung $a_s = 1, a_i \not \estimates a_{i + 1}$ für $i = 0, \dots, s - 1$. $⇒ ∃ c_1, \dots, c_s ∈ R \setminus (R^{\ast} ∪ \{0\})$ mit
	 \[a = c_1 a_1 = c_1 c_2 a_2 = \dots = c_1 · \dots · c_{s - 1} a_{s - 1} = c_1 · \dots · c_s \lightning\]
	 zu $a = p_1 · \dots · p_r, R$ faktoriell.
  #+end_proof
  #+begin_remark latex
  $c_1, \dots, c_r ∈ R \setminus (R^{\ast} ∪ \{0\})$ mit $c_1 \mid c_2 \mid \dots \mid c_r$. $M$ R-Modul mit
  \[M \cong \oplus_{i = 1}^r \faktor{R}{c_i R}\]
  Dann gilt: $r$ ist eindeutig bestimmt, $c_1, \dots, c_r$ sind eindeutig bestimmt bis auf Assoziertheit durch $M$.
  #+end_remark
  #+begin_proof latex
  Sei
  \[M\cong \oplus_{i = 1}^s \faktor{R}{(α_i)} \cong \oplus_{j = 1}^t \faktor{R}{(β_j)}\]
  mit \\
  $α_s \mid α_{s - 1} \mid \dots \mid α_1, α_i ∈ R \setminus (R^{\ast} ∪ \{0\})$ \\
  $β_t \mid β_{t - 1} \mid \dots \mid β_1, β_i ∈ R \setminus (R^{\ast} ∪ \{0\})$
  1. Behautung: Für alle $k \leq \min \{s, t\}$ ist $(α_k) = (β_k)$, das heißt $α_k \estimates β_k$, denn: \\
	 Annahme: Dies gilt nicht, ohne Einstränkung sei $k\leq \min \{s, t\}$ mit $(α_k) \neq (β_k)$. $⇒$ für $1 \leq i \leq k$ ist $(α_i) = (β_i)$.
	 \[⇒ α_k M \cong \oplus_{i = 1}^s α_k \faktor{R}{(α_i)} = \oplus_{i = 1}^{k - 1} α_k \faktor{R}{(α_i)}\]
	 denn für $i = k, \dots, s$ ist $α_i \mid α_k$ und somit $(α_k) ⊆ (α_i)$. Andererseits:
	 \begin{align*}
	 α_k M \cong \oplus_{j = 1}^t α_k \faktor{R}{(β_j)} &= \oplus_{j = 1}^{k - 1} α_k \faktor{R}{(β_j)} \oplus \oplus_{j = k}^t α_k \faktor{R}{(β_j)} \\
	 &= \oplus_{j = 1}^{k - 1} α_k \faktor{R}{(α_j)} \oplus \oplus_{j = k}^t α_k \faktor{R}{(β_j)}
   	 \end{align*}
	 Es ist
	 \[l_R(α_k M) \leq l_R(M) = \sum_{i = 1}^{r} l_R(\faktor{R}{c_i R}) < ∞\]
	 $⇒$ Längen aller auftretenden Moduln sind endlich. Es ist
	 \[l_R(α_k M) = \sum_{i = 1}^{k - 1} l_R(α_k \faktor{R}{(α_i)}) = \sum_{j = 1}^{k - 1} l_R(α_k \faktor{R}{(α_j)}) + \sum_{j = k}^{t} l_R(α_k \faktor{R}{(β_j)})\]
	 \[⇒ l_R(α_k \faktor{R}{(β_j)}) = 0, \quad j = k, \dots, t\]
	 \[⇒ α_k \faktor{R}{(β_j)} = 0\quad j = k, \dots, t\]
	 insbesondere $α_k \faktor{R}{(β_k)} = 0 ⇒ (α_k) ⊆ (β_k)$
	 Durch Vertauschen der Rollen von $α_i, β_i$ im obigen Beweis erhalten wir $(β_k) ⊆ (α_k) ⇒ (α_k) = (β_k) \lightning$
  2. Nach 1. ist $(α_i) = (β_i)$, das heißt $α_i \estimates β_i ∀ 1 \leq i \leq min \{s, t\}$, ohne Einschränkung $s \leq t$. Annahme: $s < t$
	 \[⇒ M \cong \oplus_{i = 1}^s \faktor{R}{(α_i)} \oplus \oplus_{j = s + 1}^k \faktor{R}{(β_i)} \cong \oplus_{i = 1}^s \faktor{R}{(α_i)}\]
	 \[⇒ 0 = l_R(\oplus_{j = s + 1}^t \faktor{R}{(β_j)}) = \sum_{j = s + 1}^{t} l_R(\faktor{R}{(β_j)}) ⇒ \faktor{R}{(β_j)} = 0\quad j = s + 1, \dots, t\]
	 $⇒ β_{s + 1}, \dots, β_t ∈ R^{\ast} \lightning$. Also $s = t$.
  #+end_proof
  #+ATTR_LATEX: :options [Elementarteilersatz]
  #+begin_defthm latex
  $F$ endlich freier R-Modul, $M ⊆ R$ Untermodul. Dann existiert eine Basis $(x_1, \dots x_m)$ von $F$ sowie $s ∈ ℕ_0, c_1, \dots, c_s ∈ R \setminus \{0\}$ mit folgenden Eigenschaften
  1. $(c_1 x_1, \dots, c_s x_s)$ ist eine Basis von $M$.
  2. $c_1 \mid c_2 \mid \dots \mid c_s$
  $s$ ist eindeutig, $c_1, \dots, c_s$ sind eindeutig bis aus Assoziiertheit durch $M$ bestimmt. (sind insbesondere unabhängig von der Wahl der Basis $(x_1, \dots, x_m)$)
  und heißen die *Elementarteiler* von $M ⊆ F$.
  #+end_defthm
  #+begin_proof latex
  *Existenz*: Sei $(y_1, \dots, y_m)$ eine Basis von $F$.
  1. Behauptung: $M$ ist endlich erzeugt, denn: Beweis per Induktion nach $m$ \\
	 $m = 1$: dann existiert ein Isomorphismus $φ: F \to R, φ(M) ⊆ R$ ist ein Untermodul, insbesondere endlich erzeugt, da $R$ Hauptidealring $⇒$ $M$ endlich erzeugt. \\
	 $m > 1$: Wir setzen $F' := \Lin((y_1, \dots, y_{m - 1})), F'' := \Lin((y_m))$. Wir betrachten die Projektiosabbildung $π: F = F' \oplus F'' \to F'', a + b \to b$ sowie $π \big|_M$.
	 Es ist $\ker(π\big|_M) = \ker(π) ∩ M = F' ∩ M ⊆ F', \im(π \big|_M) = π(M) ⊆ F''$. Nach Induktionsvorrausetzung sind die Untermoduln $\ker(π\big|_M) ⊆ F'$, sowie
	 $\im(π\big|_M) ⊆ F''$ endlich erzeugt $⇒$ $M$ endlich erzeugt.
  2. Sei $(z_1, \dots, z_n)$ ein endliches Erzeugendensystem von $M$. Wir betrachten den R-Modulhomomorphismus $φ:R^n \to F, e_j ↦ z_j, j = 1, \dots, n$ mit $e_1, \dots, e_n$ wie üblich.
	 $\im φ = \Lin((z_1, \dots, z_n)) = M$. Setze
	 \[A := M_{(y_1, \dots, y_m)}^{(e_1, \dots, e_n)}(φ) = (α_{ij}) ⇒ z_j = \sum_{i = 1}^{m} α_{ij} y_i \quad j = 1, \dots, n\]
	 nach 30.2 existieren $S, T$ invertierbare Matrizen	über $R, c_1, \dots, c_s ∈ R \setminus \{0\}$ mit
	 \[S A T^{-1} = (\begin{array}{ccc|c} c_1 \\ & \ddots & & 0 \\ & & c_s \\ \hline \\ & 0 & & 0 \end{array}), \quad c_1 \mid \dots \mid c_s\]
	 $⇒$ Es existieren Basen $(x_1, \dots, x_m)$ von F, $(v_1, \dots, v_n)$ von $R^n$ mit
	 \[M_{(x_1, \dots, x_m)}^{v_1, \dots, v_n}(φ) = (\begin{array}{ccc|c} c_1 \\ & \ddots & & 0 \\ & & c_s \\ \hline \\ & 0 & & 0 \end{array})\]
	 $⇒ (c_1 x_1, \dots, c_s x_s)$ ist ein Erzeugendensystem von $\im φ = M$.
  3. $(c_1 x_1, \dots, c_s x_s)$ ist linear unabhängig, denn: Sei
	 \[λ_1 c_1 x_1 + \dots + l_s c_s x_s = 0 ⇒ λ_1 c_1 = \dots = λ_s c_s = 0\]
	 $R$ nullteilerfrei $⇒ λ_1 = \dots = λ_s = 0$. Somit: $(c_1 x_1, \dots, c_s x_s)$ ist eine Basis von $M$.
  *Eindeutigkeitsaussage: Setze $T' := \Lin((x_1, \dots, x_s))$
  1. Behauptung: $F' = \{a ∈ F \mid ∃ λ ∈ R \setminus \{0\}: λ a ∈ M\}$, insbesondere hängt $F'$ nur von $M$ ab, denn: \\
	 "$⊆$" Sei $x ∈ \Lin((x_1, \dots, x_s)) = F'$, etwa $x = λ_1 x_1 + \dots + λ_s x_s$. $⇒ c_s x = λ_1 c_s x_1 + \dots + λ_s c_s x_s$. Wegen $c_1 \mid c_2 \mid \dots \mid c_s$ existiert $μ_i ∈ R$
	 mit $c_s = μ_i c_i, i = 1, \dots, s$.
	 \[⇒ c_s x = λ_1 μ_1 c_1 x_1 + \dots + λ_{s_ 1} μ_{s - 1} c_{s - 1} x_{s - 1} + λ_s c_s x_s ∈ \Lin((c_1 x_1, \dots, c_s x_s)) = M\]
	 "$\supseteq$" Sei $a ∈ F$, etwa $a = μ_1 x_1 + \dots + μ_m x_m$ und $λ ∈ R \setminus \{0\}$, sodass $λ a ∈ M$.
	 \[⇒ λ a = λ μ_1 x_1 + \dots + λ μ_m x_m ∈ M = \Lin((c_1 x_1, \dots, c_s x_s)) ⊆ \Lin((x_1, \dots, x_s)) = F'\]
	 $⇒ ∃ δ_1, \dots, δ_s ∈ R$ mit
	 \[λ a = δ_1 x_1 + \dots + δ_s x_s\]
	 \[⇒ 0 = (λ μ_1 - δ_1) x_1 + \dots + (λ μ_s - δ_s) x_s + λ μ_{s + 1} x_{s + 1} + \dots + λ μ_m x_m\]
	 \[⇒ λ μ_{s + 1} = \dots = λ μ_m = 0 ⇒ μ_{s + 1} = \dots = μ_m = 0 ⇒ a = μ_1 x_1 + \dots + μ_s x_s ∈ F'\]
  2. Wir betrachten die Abbildung
	 \[ψ: F' = \Lin((x_1, \dots, x_s)) \to \oplus_{i = 1}^s \faktor{R}{c_i R}, α_1 x_1 + \dots + α_s x_s ↦ (α_1 + c_1 R, \dots, α_s + c_s R)\]
	 $ψ$ ist ein wohldefinierter Homomorphimus, $ψ$ ist surjektiv.
	 \[\ker ψ = \{α_1 x_1 + \dots + α_s x_s ∈ F'1 \mid c_1 \mid α_1, \dots, c_s \mid a_s\} \Lin((c_1 x_1, \dots, c_s x_s)) = M\]
	 $⇒$ Erhalten Isomorphismus
	 \[\bar ψ: \faktor{F'}{M} \to \oplus_{i = 1}^{s} \faktor{R}{c_i R}\]
	 von R-Moduln, die linke Seite ist wegen 1. nur von $M$ abhängig. Ist $c_1 ∈ R^{\ast}$, dann ist $c_1 R = R$, also $\faktor{R}{c_i R} = 0$. Wegen 30.4 sind damit die
	 Nichteinheiten unter $c_1, \dots, c_s$ eindeutig bestimmt bis auf Asoziiertheit, ihre Anzahl ist eindeutig bestimmt. Da $(c_1 x_1, \dots, c_s x_s)$ Basis von $M$, ist
	 $s = \Rang(M)$ eindeutig bestimmt. $⇒$ Anzahl der Einheiten unter $c_1, \dots, c_s$ eindeutig bestimmt, Einheiten unter $c_1, \dots, c_s$ sind eindeutig bis aus Asoziiertheit.
  #+end_proof
  #+begin_conc latex
  $F$ endlich freier R-Modul, $M ⊆ F$ Untermodul. Dann ist $M$ endlich frei und $\Rang(M) \leq \Rang(F)$.
  #+end_conc
  #+begin_note latex
  - Aus $M \subsetneq$ folgt nicht $\Rang(M) < \Rang(F)$: zum Beispiel ist $ℤ$ ein freier $ℤ$ -Modul vom Rang 1, $2 ℤ \subsetneq ℤ$ ist ein freier $ℤ$ -Modul, aber $\Rang(2ℤ) = 1 = \Rang(ℤ)$.
  - Man kann zeigen (unter Verwendung des Auswahlaxiom): $F$ freier R-Modul, $M ⊆ F$ Untermodul $⇒$ $M$ frei ($R$ Hauptidealring!)
  -	ohne die Vorraussetzung, dann $R$ ein Hauptidealring ist, wird 30.6 falsch:
	Beispiel: $F = ℚ[X,Y]$ als $F = ℚ[X, Y]$ -Modul ($R$ ist kein Hauptidearing!), $M = \Lin((X, Y))$ ist *nicht* frei als R-Modul.
  #+end_note
  #+ATTR_LATEX: :options [Hautsatz für endlich erzeugte Modult über Hauptidealringen, Variante 1]
  #+begin_defthm latex
  $M$ eindlich erzeugt. Dann gilt:
  1. Es gibt einen endlich freien Untermodul $F ⊆ M$, etwa $F \cong R^d$ mit $M = F \oplus T(M)$. Hiebei ist $d = \Rang F$ eindeutig bestimmt.
  2. Es gibt $s ∈ ℕ_0, c_1, \dots, c_s ∈ R \setminus(R^{\ast} ∪ \{0\})$ mit
	 \[T(M) \cong \oplus_{j = 1}^s \faktor{R}{c_j R}\]
	 mit $c_1 \mid c_2 \mid \dots \mid c_s$
  3. Die Zahl $s$ ist eindeutig bestimmt, $c_1, \dots, c_s$ sind eindeutig bestimmt bis auf Assoziiertheit und heißen die *Elementarteiler* von $M$.
  Also:
  \[M \cong R^d \oplus \faktor{R}{c_1 R} \oplus \dots \oplus \faktor{R}{c_s R}\]
  #+end_defthm
  #+begin_proof latex
  1. Existenz: Setze $(z_1, \dots, z_m)$ ein endliches Erzeugendensystem von $M$. Wir betrachten den $R$ -Modulhomomorphismus
	 \[φ: R^m \to M, e_i ↦ z_i, i = 1, \dots, m\]
	 $φ$ ist surjektiv $⇒$
	 \[M \cong \faktor{R^m}{\ker φ}\]
	 Nach Elementarteiler-Satz für $\ker φ ⊆ R^m$ existiert eine Basis $(x_1, \dots, x_m)$ vom $R^m$, sowie $c_1, \dots, c_t ∈ R \setminus \{0\}$, sodass $(c_1 x_1, \dots, c_t x_t)$ eine Basis von $\ker φ$ ist.
	 Setze $c_{t + 1} = \dots = c_m := 0$, außerdem
	 \[ρ: R^m \to \faktor{R}{(c_1)} \oplus \dots \oplus \faktor{R}{(c_m)}, α_1 x_1 + \dots + α_m x_m ↦ (α_1 + (c_1), \dots, α_m + (c_m))\]
	 $⇒ ρ$ ist wohldefinierter R-Modulhomomorphismus, $ρ$ ist surjektiv mit $\ker ρ = \Lin((c_1 x_1, \dots, c_t x_t)) = \ker φ$.
	 \[⇒ M \cong \faktor{R^m}{\ker φ} = \faktor{R^m}{\ker ρ} \cong \faktor{R}{(c_1)} \oplus \dots \oplus \faktor{R}{(c_m)} \cong \faktor{R}{(c_1)} \oplus \faktor{R}{(c_t)} \oplus R^{m - t}\]
	 Setze $d := m - t$. Für $c_i ∈ R^{\ast}$ ist $c_i R = R$, also $\faktor{R}{(c_i)} = 0$. Nach Weglassen der Einheiten aus $c_1, \dots, c_t$ und Umordnen zu $c_1, \dots, c_s ∈ R \setminus (R^{\ast} ∪ \{0\})$
	 mit $c_1 \mid \dots \mid c_s$ ist
	 \[M \cong R^d \oplus \faktor{R}{(c_1)} \oplus \dots \oplus \faktor{R}{(c_s)}\]
  2. Eindeutigkeit: Wir betrachten die Abbildung:
	 \[δ: M \xrightarrow[γ]{\cong} R^d \oplus \faktor{R}{(c_1)} \oplus \dots \oplus \faktor{R}{(c_s)} \xrightarrow[\text{kan. Proj.}]{π} R^d\]
	 $σ$ ist surjektiver R-Modulhomomorphismus mit
	 \begin{align*}
	 \ker(δ) &= γ^{-1} (\ker π) = γ^{-1} (\faktor{R}{(c_1)} \oplus \dots \oplus \faktor{R}{(c_s)}) γ^{-1}(T(\faktor{R}{(c_1)} \oplus \dots \oplus \faktor{R}{(c_s)} \oplus R^d)) \\
	 &= T(M)
   	 \end{align*}
	 Homomorphiesatz: $\faktor{M}{T(M)} \cong R^d ⇒$ d eindeutig bestimmt. Wegen $T(M) \cong \faktor{R}{(c_1)} \oplus \dots \oplus \faktor{R}{(c_s)}$ sind nach 30.4 auch $s$ eindeutig bestimmt sowie $c_1, \dots, c_s$
	 eindeutig bis auf Assoziiertheit.
  3. Existenz (Teil 2): Es ist
	 \[M = γ^{-1}(R^d \oplus \faktor{R}{(c_1)} \oplus \dots \oplus \faktor{R}{(c_s)}) = \underbrace{γ^{-1}(R^d)}_{=: F} \oplus \underbrace{γ^{-1}(\faktor{R}{(c_1)} \oplus \dots \oplus \faktor{R}{(c_s)})}_{= T(M)}\]
  #+end_proof
  #+begin_note latex
  Ohne Vorraussetzung "M endlich erzeugt" wird die Aussage falsch: $ℚ$ ist ein (nicht endlich erzeugter) $ℤ$ -Modul mit $T(ℚ) = \{0\}$, aber $ℚ$ ist kein freier $ℤ$ -Modul (vergleiche Annahme nach 29.17)
  #+end_note
  #+begin_conc latex
  $M$ R-Modul. Dann sind äquivalent:
  1. $M$ ist endlich erzeugt und frei
  2. $M$ ist endlich frei
  #+end_conc
  #+begin_proof latex
  2. [@2] $⇒$ 1. trivial
  3. [@1] $⇒$ 2. Nach Hautsatz existiert eindlich freier Untermodul $F ⊆ M$ mit $M = F \oplus T(M)$. Wegen 29.17 ist $T(M) = \{0\}$, also $M = F ⇒ M$ endlich frei.
  #+end_proof
  #+ATTR_LATEX: :options [Hautsatz über endich erzeugte abersche Gruppen, Variante 1]
  #+begin_conc latex
  $G$ endlich erzeugte abersche Gruppe (= endlich erzeugter $ℤ$ -Modul). Dann existiert ein Isomorphismus
  \[G \cong ℤ^d \oplus \faktor{ℤ}{c_1 ℤ} \oplus \dots \oplus \faktor{ℤ}{c_s ℤ}\]
  mit $d ∈ ℕ_0, c_1, \dots, c_s ∈ ℕ_{> 1}, c_1, \dots, c_s$. $d$ sowie $s, c_1, \dots, c_s$ sind eindeutig bestimmt. Es ist $G$ endlich $⇔$ $d = 0$. In diesem Fall ist $\abs{G} = c_1 · \dots · c_s$
  #+end_conc
  #+begin_ex latex
  1. abelsche Grueen mit 4 Elementen bus auf Isomorphie:
	 1. Fall: $s = 1, c_1 = 4: \faktor{ℤ}{4ℤ}$
	 2. Fall: $s = 2, c_1 = 2, c_2 = 2: \faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{2ℤ}$
     $⇒$ bis auf Isomorphie gibt es 2 abelsche Gruppen mit 4 Elementen.
  2. abelsche Gruppen mit 24 Elementen bis auf Isomorphie
	 1. Fall: $s = 1, c_1 = 24: \faktor{ℤ}{24ℤ}$
	 2. Fall: $s = 2, c_1 = 2, c_2 = 12$: $\faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{12ℤ}$
	 3. Fall: $s = 3, c_1 = 2, c_2 = 2, c_3 = 6$: $\faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{6ℤ}$
  $⇒$ Bis auf Isomorphie gibt es 3 abelsche Gruppen mit 24 Elementen.
  #+end_ex
  Frage: $\faktor{ℤ}{3ℤ} \oplus \faktor{ℤ}{8ℤ}$ ist ebenfalls eine abelsche Gruppe mit 24 Elementen. Zu welcher der Gruppen aus der Liste von 30.16.b ist diese isomorph?
  #+ATTR_LATEX: :options [Spezialfall des Chinesischen Restsatzes]
  #+begin_remark latex
  $a ∈ R \setminus (R^{\ast} ∪ \{0\}), a = c p_1^{n_1} · \dots · p_r^{n_r}$ mit $c ∈ R^{\ast}, p_1, \dots, p_r$ irreduzibel, paarweise nicht-assoziiert.
  \[π_i: R \to \faktor{R}{(p_i^{n_i})}, b ↦ b + (p_i^{n_1})\]
  kanonische Projektion für $i = 1, \dots, r$. Dann ist die Abbildung
  \[φ: R \to \faktor{R}{(p_i^{n_1})} × \dots × \faktor{R}{(p_r^{n_r})}, b ↦ (π_1(b), \dots, π_r(b))\]
  ein surjektiver Ringhomomorphismus mit $\ker φ = (a)$, das heißt wir erhalten einen Ringisomorphismus
  \[Φ: \faktor{R}{(a)} \xrightarrow{\cong} \faktor{R}{(c_1^{n_1})} × \dots × \faktor{R}{(p_r^{n_r})}\]
  Hierbei ist $\faktor{R}{(c_1^{n_1})} × \dots × \faktor{R}{(p_r^{n_r})}$ via komponentenweiser Addition und Multiplikation ein Ring. Insbesondere erhalten wir einen Isomorphismus von R-Moduln
  \[\faktor{R}{(a)} \cong \faktor{R}{(p_1^{n_1})} × \dots × \faktor{R}{(p_r^{n_r})}\]
  #+end_remark
  #+begin_proof latex
  1. $φ$ Ringhomomorphismus, da $π_1, \dots, π_r$ Ringhomomorphismus
  2. $φ$ surjektiv: Es ist $1 ∈ \GGT(p_j^{n_j}, p_i^{n_1} · \dots · p_{j_ 1}^{n_{j - 1}} p_{j + 1}^{n_{j + 1}} · \dots · p_r^{n_r})$.
	 \[⇒ ∃ u_j, v_j ∈ R: 1 = \underbrace{u_j p_j^{n_j}}_{=: d_j} + \underbrace{v_j p_i^{n_1} · \dots · p_{j_ 1}^{n_{j - 1}} p_{j + 1}^{n_{j + 1}} · \dots · p_r^{n_r}}_{e_j}\]
	 \begin{align*}
	 ⇒ π_i(e_j) &= \bar 0 \text{ für } i \pm j, π_j(e_j) = π_j(1 - d_j) = π_j(1) - π_j(d_j) = \bar 1 - \bar 0 = \bar 1 \\
	 ⇒ φ(e_j) &= (\bar 0, \dots, \bar 0, \bar 1, \bar 0, \dots, \bar 0)
   	 \end{align*}
	 Für $(\bar a_1, \dots, \bar a_r) ∈ \faktor{R}{(p_1^{n_1})} × \dots × \faktor{R}{p_r^{n_r}}$ ist
	 \[φ(a_1 e_1 + \dots + a_r e_r) = \underbrace{φ(a_1) φ(e_1)}_{(\bar a_1, \bar 0, \dots, \bar 0)} + \dots + \underbrace{φ(a_r) φ(e_r)}_{=(\bar 0, \dots, \bar 0 \bar a_r)} = (\bar a_1, \dots, \bar a_r)\]
  3. \[\ker φ = \{a ∈ R \mid p_1^{n_1} \mid a, \dots, p_r^{n_r} \mid a\} = \{a ∈ R \mid p_1^{n_1} · \dots · p_r \mid a\} = (p_1^{n_1} · \dots · p_r^{n_r}) = (p p_1^{n_1} · \dots · p_r^{n_r}) = (a)\]
  4. Rest aus Homomorphiesatz für Ringe
  #+end_proof
  #+begin_ex latex
  Nach 30.11 ist $\faktor{ℤ}{24ℤ} \cong \faktor{ℤ}{3ℤ} \oplus \faktor{ℤ}{8ℤ}$
  #+end_ex
  #+ATTR_LATEX: :options [Hautsatz für endlich erzeugte Moduln über Hauptidealringen, Variante 2]
  #+begin_thm latex
  $M$ endlich erzeugter R-Modul, $\mathbb{P}$ sei ein Vertretersystem der Primelelemente von $R$ bis auf Assoziiertheit, für $p ∈ \mathbb{P}$ sei
  \[M_p := \{x ∈ M \mid ∃ n ∈ ℕ: p^n x = 0\} ⊆ T(M)\]
  (ist offenbar ein Untermodul). Dann gilt:
  1. Es gibt einen endlich erzeugten freien Untermodul $F ⊆ M$, sodass $M = F \oplus T(M)$, $d := \Rang F$ ist eindeutig bestimmt.
  2. $T(M) = \oplus_{p ∈ \mathbb{P}} M_p$, wobei $M_p = 0$ für fast alle $p ∈ \mathbb{P}$
  3. Für jedes $p ∈ \mathbb{P}$ mit $M_p \neq 0$ gibt es eindeutig bestimmte natürliche Zahlen $1 \leq n_{p,1} \_eq \dots \leq n_{p, s_p}$ mit
	 \[M \cong R^d \oplus \oplus_{p ∈ \mathbb{P}}(\faktor{R}{p^{n_{p,1}} R} \oplus \dots \oplus \faktor{R}{p^{n_{p,s_p}} R})\]
  #+end_thm
  #+begin_proof latex
  1. folgt aus 30.10
  2., 3.:
  1. Nach Hauptsatz für endlich erzeugte R-Moduln (Variante 1) ist $M = F \oplus T(M), T(M) \cong \faktor{R}{(c_1)} \oplus \dots \oplus \faktor{R}{(c_s)}$ mit $c_1, \dots, c_s ∈ R \setminus (R^{\ast} ∪ \{0\}), c_1 \mid \dots \mid c_s$.
	 Wir faktorisieren $c_1, \dots, c_s$ in $R$: $\{p_1, \dots, p_r\} ⊆ \mathbb{P}$ sei die Menge der Primteiler von $c_s$ (bis auf Assoziiertheit). Sei $c_j = ε_j p_1^{n_{1,j}} · \dots · p_r^{n_{r,j}}, ε_j ∈ R^{\ast}, n_{1,j}, \dots, n_{r,j} ∈ ℕ_0$ ($j = 1, \dots, r$).
	 \[⇒ T(M) \cong \oplus_{j = 1}^s \faktor{R}{(c_j)} \cong \oplus_{j = 1}^s \oplus_{i = 1}^r \faktor{R}{p_i^{n_{i,j}}} \cong \oplus_{i = 1}^r \oplus_{j = 1}^s \faktor{R}{(p_i^{n_{i,j}})}\]
  2. Es sei ein Isomorphismus $γ: T(M) \to \oplus_{i = 1}^r \oplus_{j = 1}^s \faktor{R}{(p_i^{n_{i,j}})}$ fixiert. Behauptung:
	 \[γ(M_{p_i}) = \oplus_{j = 1}^s \faktor{R}{(p_i^{n_{i,j}})}\]
	 denn: "$⊆$" Sei $a ∈ M_{p_i}$, etwa $p_i^m a = 0 ⇒ γ(p_i^m a) = 0 ⇒ p_i^m γ(a) = 0$. Es ist $γ(a)$ von der Form
	 \[γ(a) = (\underarrow[\bar x_{1,1}]{\(\faktor{R}{(p_i^{n_{1,1}})}\)}, \dots, \underarrow[\bar x_{1,s}]{\(\faktor{R}{(p_i^{n_{1,s}})}\)}, \dots, \underarrow[\bar x_{r,1}]{\(\faktor{R}{(p_i^{n_{r,1}})}\)}, \dots, \underarrow[\bar x_{r,s}]{\(\faktor{R}{(p_i^{n_{r,s}})}\)})\]
	 Für $j \neq i$ ist $1 ∈ \GGT(p_i^m, p_j^{n_{j,k}}), k ∈ \{1, \dots, r\}$. $⇒ ∃ u_1, v_i ∈ R: 1 = u_i p_i^m + v_i p_j^{n_{j,k}}$. In $\faktor{R}{(p_j^{n_{j, k}})}$ ist $\bar 1 = \bar u_i \bar p_i^m$,
	 das heißt $\bar p_i^m$ ist Einheit in $\faktor{R}{(p_j^{n_{j,k}})}$. Aus $p_i^m γ(a) = 0$ folgt für $j \neq i, k = 1, \dots, s: p_i^m \bar x_{j, k} = 0 ⇒ \bar p_i^m \bar x_{j, k} = 0 ⇒ \bar x_{j,k} = 0$
	 \[⇒ γ(a) ∈ \oplus_{j = 1}^s \faktor{R}{(p_i^{n_{i,j}})}\]
	 "$\supseteq$" Sei $x ∈ \oplus_{j = 1}^s \faktor{R}{(p_i^{n_{i,j}})}$. Setze $m := \max \{n_{i, 1}, \dots, n_{i, s}\} = n_{i, s}$, dann $p_i^m x = 0$.
	 Setze $y := γ^{-1}(x)$. Dann ist $p_i^m y = p_i^m y^{-1}(x) = γ^{-1}(p_i^m x) = 0$. $⇒ y ∈ M_{p_i}$ und $γ(y) = x$, das heißt $x ∈ γ(M_{p_i})$.
  3. Aus 2. folgt:
	 \[T(M) = γ^{-1}(\oplus_{i = 1}^r \oplus_{j = 1}^s \faktor{R}{(p_i^{n_{i,j}})}) = γ^{-1}(\oplus_{i = 1}^r γ(M_{p_i})) = \oplus_{i = 1}^r M_{p_i}\]
	 Behauptung: $M_p = 0$ für $p \neq p_1, \dots, p_r$, denn: Sei $p \neq p_1, \dots, p_r ⇒ 1 ∈ \GGT(p^m, c_j)$ für $j = 1, \dots, s, m ∈ ℕ$.
	 $⇒$ $p^m + (c_j) ∈ (\faktor{R}{(c_j)})^{\ast}$ für $j = 1, \dots, s$ \\
	 $⇒$ Aus $p^m x = 0$ für $x ∈ \oplus_{j = 1}^s \faktor{R}{(c_j)}$ folgt $x = 0$ \\
	 $⇒$ Aus $p^m x = 0$ für $x ∈ T(M)$ folgt $x = 0$ \\
	 $⇒$ Aus $p^m x = 0$ für $x ∈ M$ folgt $x = 0$ \\
	 $⇒$ $M_p = 0$ für $p \neq p_1, \dots, p_r, p ∈ \mathbb{P} ⇒ M_p = 0$ für fast alle $p ∈ \mathbb{P}$ und $T(M) = \oplus_{p ∈ \mathbb{P}} M_p$
  4. Nach Umbenennung erhalten wir
	 \[M_p \cong \oplus_{j = 1}^{s_p} \faktor{R}{(p^{n_{p,j}})}\]
	 mit $1 \leq n_{p,1} \leq \dots \leq n_{p, s_p}$, falls $s_p \neq 0$. $M_p$ mit $p \neq 0$ hängt nur von $M, p$ b. Die Zahlen $n_{p_1}, \dots, n_{p, s_p}$ sind wegen 30.4 eindeutig bestimmt.
  #+end_proof
  #+ATTR_LATEX: :options [Haupsatz für endlicherzeugte abelsche Gruppen, Variante 2]
  #+begin_conc latex
  $G$ endlich erzeugte Gruppe, $\mathbb{P}$ Menge der Primzahlen in $ℕ$. Dass existiert ein Isomorphismus
  \[G \cong ℤ^d \oplus \oplus_{p ∈ \mathbb{P}}(\faktor{ℤ}{(p^{n_{p, 1}})} \oplus \dots \oplus \faktor{ℤ}{(p^{n_{p, s_p}})}), 1 \leq n_{p,1} \leq \dots \leq n_{p, s_p}\]
  Die Zahlen $d, s_p, n_{p_i}$ sind eindeutig bestimmt. Es ist $s_p = 0$ für fast alle $p ∈ \mathbb{P}$. Es ist $G$ endlich $⇔$ $d = 0$. In diesem Fall ist $\abs{G} = \prod_{p ∈ \mathbb{P}} p^{n_{p, 1} + \dots + n_{p, s_p}}$.
  #+end_conc
  #+begin_ex latex
  Endliche abelsche Gruppen mit 24 Elementen, bis auf Isomorphie: Es ist $24 = 2^3 · 3 = 2 · 2^2 · 3 = 2 · 2 · 2 · 3$ $⇒$ Isomorphietypen:
  \[\faktor{ℤ}{8ℤ} \oplus \faktor{ℤ}{3ℤ}, \faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{4ℤ} \oplus \faktor{ℤ}{3ℤ}, \faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{3ℤ}\]
  Es ist
  \[\faktor{ℤ}{8ℤ} \oplus \faktor{ℤ}{3ℤ} \cong \faktor{ℤ}{24ℤ}\]
  \[\faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{4ℤ} \oplus \faktor{ℤ}{3ℤ} \cong \faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{12ℤ}\]
  \[\faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{3ℤ} \cong \faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{2ℤ} \oplus \faktor{ℤ}{6ℤ}\]
  #+end_ex
