* Elektrostatik
** Elektrische Ladung
   - Neue Kraft
   - anziehend oder abstoßend
   - Konzept der elektrischen Ladung
   Experimentelle Erkenntnisse:
   - Erzeugung von Ladungen durch Reibung
   - Ladungen gleicher Vorzeichen: Abstoßung
   - Ladungen ungleicher Vorzeichen: Anziehung
   - Ladung kann transportiert werden
   - Elektrische Kräfte	sind Fernkräfte
   - Ladungen sind erhalten
   #+begin_defn latex
   Influenz
   Ladungstrennung durch die (Fern) Wirkung elektrischer Kräfte nennt man Influenz oder elektrostatische Induktion.
   #+end_defn
** Mikroskopische Deutung
   Elektron: negativ \\
   Proton: positiv \\
   Atome elektrische neutral
   - Z: Anzahl Protonen / Elektronen
   - N: Anzahl Neutronen
   - A: Anzahl Neutronen + Protonen
   Leiter und Nichtleiter: Unterschiedliche Verfügbarkeit von Ladungsträgern
** Coulombsches Gesetz
   Experimentelles Resultat:
   \[\v F_C = K \frac{q_1 q_2}{r_{12}^2} \hat r_{12}\]
   #+begin_defn latex
   \[\v F_C = \frac{1}{4π ε_0} \frac{q_1 q_2}{r_{12}^2} \hat r_{12}\]
   mit $ε_0 = \SI{8.85416e-12}{\coulomb\per\newton\per\meter\squared}$
   #+end_defn
   Vergleich: Coulomb vs. Gravitation
   \begin{align*}
   \v F_G &= -G \frac{m_1 m_2}{r_{12}^2} \hat r_{12} \\
   \v F_C &= K \frac{q_1 q_2}{r_{12}^2} \hat r_{12} \\
   \frac{F_C}{F_G} &= \SI{227e39}{} \\
   \end{align*}
** elektrisches Feld
   #+ATTR_LATEX: :options [Elektrisches Feld]
   #+begin_defn latex
   \[\v E(\v r) = \frac{\v F_C(\v r)}{q} = \frac{1}{4 π ε_0} \frac{Q}{r^2} \hat r\]
   \[\v F(\v r) = q \v E(\v r)\]
   Das elektrische Feld hängt nur von der Ladung $Q$ ab, aber nicht von der Testladung $q$.
   Es gilt damit:
   \[\v F(\v r) = q \v E(\v r)\]
   #+end_defn
   Bedeutung das elektrischen Feldes: \\
   Coulomb-Gesetz beschreibt Fernwirkung. \\
   Aber: Wodurch wird diese Wirkung übertragen? \\
   Geschieht die Übertragung instantan? (nein!) \\
   Feldwirkungstheorie: Elektrische Kraftübertragung über Ausbreitung des elektrischen Feldes, das mit der Probeladung $q$.
   Elektrostatik:
   Fernwirkung- und Feldwirkungstheorie äquivalent. \\
   Elektrodynamik: Feldbegriff essentiell. \\
   Feld einer allgemeinen Ladungsverteilung: \\
   Wichtig: Es gilt das Superpositionsprinzips. Es gilt
   \[\d Q = ρ(\v r) \d V\]
   \[\v E(\v R) = \frac{1}{4π ε_0} ∫ \frac{\v R - \v r}{\abs{\v R - \v r}^3} ρ(\v r) \d V\]
   Für diskrete Ladungen:
   \[\v E = \frac{1}{4 π ε_0} \sum_{i} \frac{q_i}{r_i^2} \hat r\]
   Die Anwesenheit von Ladungen verändern den Raum. Es entsteht in Vektorfeld, dessen Stärke und Richtung in jedem Raumpunkt die normierte Kraft $\frac{\v F}{q}$ auf eine Probeladung angibt. \\
   Eigenschaften der Feldlinien
   1. Das $\v E$ -Feld zeigt tangential zu den Feldlinien
   2. Feldlinien zeigen weg von positiven Ladungen
   3. Feldliniendichte entspricht Stärke des Feldes.
** Elektrischer Fluss
   #+ATTR_LATEX: :options [Elektrischer Fluss $ϕ_E$]
   #+begin_defn latex
   Maß für die Anzahl der Feldlinien, die Fläche $A$ durchstoßen.
   #+end_defn
   Für geschlossene Oberflächen:
   \begin{align*}
   Q_{innen} &= 0 ⇒ ϕ_E = 0 \\
   Q_{innen} &> 0 ⇒ ϕ_E > 0 \\
   Q_{innen} &< 0 ⇒ ϕ_E < 0 \\
   \end{align*}
   Mathematisch:
   - Homogenes Feld, $\perp$ zur Oberfläche $⇒ ϕE = E A$
   - Homogenes elektrisches Feld $E A' = E A \cos{θ} = \v E \v A = \v E \v n A$
   Verallgemeinerung:
   \begin{align*}
   Δϕ_i &= \v E_i \v n_i ΔA_i \\
   ϕ_E &= \lim_{ΔA_i \to 0} \sum \v E_i \v n_i Δ A \\
   ϕ_A &= ∫ \v E \d \v A \tag{Definition von Elektrischem Fluss} \\
   \end{align*}
   Ladung einer Kugel:
   \begin{align*}
   ϕ_A &= ∫ \v E \d \v A \\
   &= \frac{1}{4 π ε_0} \frac{Q}{R^2} ∫ \d \v D \\
   &= \frac{1}{4 π ε_0} \frac{Q}{R^2} 4 π R^2 \\
   &= \frac{Q}{ε_0}
   \end{align*}
   #+ATTR_LATEX: :options [Gauß'sches Gesetz (1. Maxwell-Gleichung)]
   #+begin_defn latex
   \[∮ \v E \d \v A = \frac{Q_{\text{innen}}}{ε_0}\]
   Das Gauß'sche Gesetz ist allgemeingültig, da:
   \begin{align*}
   ∮_{A_2} \v E \d \v A - ∮_{A_1} \v E \d \v A &= 0 \\
   ∮_{A_2} \v E \d \v A &= ∮_{A_1} \v E \d \v A = \frac{Q_{\text{innen}}}{ε_0}
   \end{align*}
   Zusammen mit Superpositionsprinzip und homogener Fläche erhält man die Allgemeingültigkeit des Gauß'schen Gesetz.
   #+end_defn
   Herleitung des Coulombschen Gesetz mit Gauß'schen Gesetz:
   \begin{align*}
   ∮ \v E \d \v A &= \frac{Q}{ε_0} \\
   E ∮ \d \v A &= \frac{Q}{ε_0} \\
   E 4π R^2 &= \frac{Q}{ε_0} \\
   E(R) &= \frac{Q}{4 π ε_0} \frac{1}{R^2}
   \end{align*}
   #+ATTR_LATEX: :options [Unendlich langer Draht]
   #+begin_ex latex
   Ladungsdichte: $λ = Q / L$
   \[\v E(\v R) = \v E(R)\]
   - Mantelfläche:e $\v E \parallel \d \v A$
   - Deckel: $\v E \perp \d \v D$
   \[ϕ_E = ∮ \v E \d \v A = ∫_{\text{Mantel}} \v E \d \v A + \underbrace{∫_{\text{Deckel}} \v E \d \v A}_{= 0} = E ∫_{\text{Mantel}} \d A = E 2 π R L = \frac{V}{ε_0}\]
   \[E = \frac{\frac{Q}{L}}{2 π R ε_0} = \frac{λ}{2 π ε_0} \frac{1}{R}\]
   #+end_ex
   #+ATTR_LATEX: :options [Unendlich ausgedehnte Flächenladung]
   #+begin_ex latex
   Flächenladungsdichte: $σ = Q / A$ \\
   Symmetrie: \\
   $\v E$ konstant für festen Abstand. \\
   $\v E \parallel \v A$
   \begin{align*}
   ϕ_E &= ∮\v E \d \v A = \underbrace{∫_{\text{Mantel}}\v E\d \v A}_{0} + ∫_{\text{Deckel}} \v E \d \v A = E A_1 + E A_2 = 2 E A \\
   ϕ_E &= 2E A = \frac{Q}{ε_0} ⇒ E = \frac{σ}{2 ε_0} \\
   \end{align*}
   #+end_ex
   #+ATTR_LATEX: :options [Plattenkondensator]
   #+begin_ex latex
   \[\v E = \frac{σ}{2 ε_0}\]
   #+end_ex
** Elektrische Felder innerhalb von Leitern
   Innerhalb eines Leiters verschwindet das elektrostatische Feld. \\
   Bei einem geladenem, isolierten Leiter sitzen alle Ladungen auf der Oberfläche. \\
   Dazu betrachte Oberfläche, die gerade kleiner als der Leiter ist, dort ist das Elektrische Feld gleich Null, also folgt:
   \[∮ \v E \d \v A = 0 = \frac{Q_{\text{innen}}}{ε_0} ⇒ Q_{\text{innen}} = 0\]
   Leiter mit Hohlraum:
   \[∮_O \v E \d \v A = 0 ⇒ Q = 0\]
** Differentielle Form des Gaußschen Gesetzes
   \[∮_A \v E \d \v A = ∫_V \Div \v E \d V\]
   $\Div \v E = \partial_x E_x + \partial_y E_y + \partial_z E_z$ \\
   Zur Divergenz: \\
   Schreibweise: $\Div \v E = \v ∇ · \v E, \v ∇ = (\partial_x, \partial_y, \partial_z)$
   in Anschauung:
   \begin{align*}
   ϕ_E &= E_O Δ A - E_i Δ A \\
   &= Δ E_x Δ A \\
   &= \frac{Δ E_x}{Δ x} Δ x Δ A = \underbrace{\partial_x E_x}_{\text{"`div"'}} Δ V
   \end{align*}
   \[∫_V \Div \v E \d V = ∮ \v E \d \v A = \frac{Q}{ε_0} = \frac{1}{ε_0} ∫_V ρ \d V\]
   Differentielle Form des Gauß Gesetz, 1. Maxwell Gleichung:
   \[\Div \v E = \frac{ρ}{ε_0}\]
   $ρ$: Ladungsdichte.
** Elektrisches Potential
   Coulombkraft ist konservativ da radialsymmetrisch.
   \begin{align*}
   W &= E_{pot}(2) - E_{pot}(1) = -∫_1^2 \v F_C \d \v s \\
   \v F_C &= -\grad E_{pot} \\
   E_{pot}(\v r) &= -∫_∞^{+r} \v F_C \d \v r = -\frac{1}{4π ε_0} ∫ \frac{Q q}{r^2} \d r \\
   &= \frac{1}{4π ε_0} \frac{Qq}{r} \tag{Theorie: $Qq / r$}
   \end{align*}
   #+ATTR_LATEX: :options [Coulombpotential]
   #+begin_defn latex
   \[φ(\v r) = \frac{E_{pot}(\v r)}{q} = \frac{1}{4πε_0} \frac{Q}{r}, φ(∞) = 0\]
   #+end_defn
   \begin{align*}
   Δφ &= φ(\v r_2) l φ{\v r_1} = - ∫\v E \d \v s \\
   ∮\v E\d \v s &= 0 \\
   \v E(\v r) &= -\grad φ(\v r)
   \end{align*}
   Allgemeine Ladungsverteilung:
   \[φ(\v R) = \frac{1}{4πε_0} ∫\frac{ρ(\v r)}{\abs{\v R - \v r}} \d V\]
   #+ATTR_LATEX: :options [Elektrische Spannung]
   #+begin_defn latex
   \[U_{12} = φ_2 - φ_1 = Δφ_{21} = - ∫_1^2 \v E \d \v s\]
   #+end_defn
** Grundgleichungen der Elektrostatik
   \begin{align*}
   \intertext{Integralform:}
   ∮ \v E \d \v A &= \frac{Q}{ε_0} \quad ∮ \v E \d \v s = 0 \\
   \intertext{Differentialform:}
   \Div \v E &= \frac{ρ}{ε_0} \quad \rot \v E = 0
   \end{align*}
   Stokes-scher Satz:
   \[∮_C E\d \v s = ∫_A \rot \v E \d \v A\]
   Zur Rotation: \\
   Schreibweise:
   \[\rot \v E = \v ∇ × \v E, \v ∇ = (\partial_x, \partial_y, \partial_z)\]
   \[\rot \v E = (\partial_y E_z - \partial_z E_y, \partial_z E_x - \partial_x E_z, \partial_x E_y - \partial_y E_x)\]
   Anschauung:
   \begin{align*}
   ∮_C \v A \d \v s &= Δ E_2 Δz - ΔE_x Δx \\
   &= \frac{ΔE_z}{Δ_x} Δx Δz - \frac{ΔE_x}{Δz}Δz Δx \\
   &= \underbrace{(\partial_x E_z - \partial_z E_x)}_{\rot} Δ A
   \end{align*}
   Mathematik:
   \begin{align*}
   \rot \v E &= -\rot(\grad φ) = -\v ∇ × (\v ∇φ) = 0 \\
   \Div \v E &= -\Div(\grad φ) = -\v ∇ · (\v ∇ φ) = -\v ∇^2 φ = -Δ φ \\
   &= -(\frac{\partial^2 φ}{\partial x^2} + \frac{\partial^2 φ}{\partial y^2} + \frac{\partial^2 φ}{\partial z^2}) = \frac{ρ}{ε_0}
   \end{align*}
   #+ATTR_LATEX: :options [Poissongleichung]
   #+begin_defn latex
   \[Δφ = -\frac{φ}{ε_0}\]
   Zentrale Gleichung der Elektrostatik
   #+end_defn
   #+ATTR_LATEX: :options [Laplacegleichung]
   #+begin_defn latex
   \[Δφ = 0\]
   Eckstein der mathematischen Physik [PTP3]
   #+end_defn
   Realisierung eines Feldes der Form
   \begin{align*}
   φ &= ax^2 + by^2 + cz^2 \quad a, b, c > 0 \\
   Δφ &= 2a + 2b + 2c > 0 \\
   \end{align*}
   $2a + 2b + 2c$ ist immer $> 0 ⇒$ solches Feld nicht möglich.
** Elektrische Felder geladener Felder
   "Einfach": Berechnung für bekannte Ladungsverteilung. \\
   "Schwierg": Berechnung in Anwesenheit von Leitern. \\
   Für statische Felder gilt: \\
   im Leiter $\v E = 0$ \\
   im Hohlraum $q = 0, \v E = 0$ \\

   Oberfläche eines Leiters: \\
   1. $\v E \parallel \v A$
   2. $\v E = \frac{σ}{ε_0}$
      \begin{align*}
      \d ϕ_E &= \v A \d \v A = E \d A \\
      &= \dd{Q}{ε_0} \\
      E &= \underbrace{\dd{Q}{A}}_{σ} \frac{1}{ε_0} = \frac{σ}{ε_0}
      \end{align*}
   3. $φ = \const$ an Leiteroberfläche.
   Berechnung von Verteilungen von Ladungen schwierig. Hier nur qualitatives Verständnis. \\
   Kugelladung (Radius $R$): \\
   Innen: $E = 0, φ = \const$ \\
   Außen: $E = 1/(4πε_0) Q/r^2$ \\
   \begin{align*}
   \v E(\v R) &= \frac{σ}{ε_0} \\
   \v E(\v R) &= \frac{\v φ(R)}{R}
   \end{align*}
   $φ = \const ⇒$ Erzeugung hoher Felder für kleine $R$
   #+ATTR_LATEX: :options [Zwei Kugeln (verbunden)]
   #+begin_ex latex
   verbunden $⇒ φ = φ_1 = φ_2 ⇒ Q_1 / R_1 = Q_2 / R_2$
   \begin{align*}
   R_1 &> R_2 \\
   ⇒ Q_1 &> Q_2	\\
   σ_1 &< σ_2 \\
   E_1 &< E_2
   \end{align*}
   #+end_ex
   kleiner krümmungsradius $⇒$ größeres Feld, größere Flächenladungsdichte. \\
   Merke: Scharfe Kanten beziehungsweise kleiner Krümmugsradius bedeutet hohes E-Feld \\
   #+ATTR_LATEX: :options [Halbraumleiter mit Ladung]
   #+begin_ex latex
   #+end_ex
** Elektrischer Dipol
   #+ATTR_LATEX: :options [Dipol]
   #+begin_ex latex
   \begin{align*}
   φ(\v r) &= \frac{1}{4πε_0} \left[\frac{q}{\abs{\v r - \frac{1}{2}\v d}} + \frac{-q}{\abs{\v r + \frac{1}{2}\v d}}\right] \\
   φ(\v r) &= \frac{\v p \hat r}{4 π ε_0 r^2} \\
   \v p &= q \v d \\
   \v E &= y \grad φ \\
   E(\v r) &= \frac{3(\v p\v r)\v r - r^2 \v p}{r^5} \tag{Elektrisches Dipolfeld (ohne Beweis)}
   \end{align*}
   Merke: Elektrischer Dipol, $r \gg d$
   \[φ(\v r) \sim \frac{1}{r^2} \qquad E(\v r) \sim \frac{1}{r^3}\]
   #+end_ex
   Multipolentwicklung:
   \[φ(\v r) = \frac{a_0}{r} + \frac{a_1}{r^2} + \frac{a_2}{r^3} + \dots\]
   \[a_0 = \frac{Q}{4π ε_0} \quad a_1 = \frac{1}{4πε_0} · \v p \hat r\]
   \[\v p = ∫ρ(\v r) \v r \d Q\]
   Elektrischer Dipol im homogenem Feld: \\
   Drehmoment:
   \[\v M = \v d × \v F = q · \v d × \frac{1}{q} \v F = \v p × \v E\]
   Kräfepaar! $⇒$ Ausrichtung im Feld. Potentielle Energie: Drehung eines Dipols im homogenen Feld,
   das heißt Arbeit wird frei oder wird geleistet. Wähle: $E_{pot} = 0$ für $r = 90^{\circ}$
   \[E_{pot} = - \v F \v s = -\v p \v E\]
   Dipol im inhomogenen Feld: das heißt an den beiden Enden des Dipols wirken unterschiedliche Kräfte.
   $⇒$ Drehmoment + resultierende Kraft. Es gilt:
   \begin{align*}
   \v F &= q \v d \dd{\v E}{\v r} = \v p ∇ \v E \\
   F_x &= \v p \grad E_x \\
   F_y &= \v p \grad E_y \\
   F_x &= \v p \grad E_z \\
   \end{align*}
** Kapzität und Kondensator
   Leiter können Ladungen speichern (zum Beispiel: Leidener Flasche, Kondensator, Metallkugel). \\
   Kondensator = Ladungsspeicher (Ladungen werden im Kondensator "kondensiert", das heißt zusammengerängt)
   Fage: Was ist die Ladungsspeicherfähigkeit oder Kapazität eines Leiters? Dafür betrachte Kugelkonuktoren.
   Gespeicherte Ladungsmenge auf einzelner Metallkugel:
   \[Δφ = -∫_∞^R \v E \d \v r = \frac{1}{4 π ε_0} \frac{Q}{R} \to Q = 4π ε_0 R U\]
   ($Δφ = U$). Das heißt gespeicherte Ladung ist proportional zur angelegten Spannung $U$
   (Allgemein: $φ(Q) \sim Q$, Superpositionsprinzip). Definiere Ladungsspeicherfähigkeit "pro Volt"
   #+ATTR_LATEX: :options [Kapazität]
   #+begin_defn latex
   \[C = \frac{Q}{U} \qquad Q = C U\]
   $[C] = \SI{1}{\coulomb\per\volt} = \SI{1}{\farad}$
   #+end_defn
   Die Kapazität einer Leiteranordnung hängt von der Geometri (und vom Material) ab. Kapazität eines
   Kugelkondensators: $C 4π ε_0 R$ (hier: freistehende Kugel). Einheit Farad ist sehr groß, da
   $\SI{1}{\coulomb}$ sehr groß ist.
   #+begin_ex latex
   Kapazität einer Kugel mit $R = \SI{1}{\centi\meter} \to C \approx \SI{1e-12}{\farad} = \SI{1}{\pico\farad}$ \\
   Kapazität der Erde mit $R = \SI{7e8}{\centi\meter} \to C \approx \SI{7e-4}{\farad} = \SI{700}{\micro\farad}$ \\
   Trotzdem heute: Superkondensatornen mit Kapazitäten bis zu $\SI{1e4}{\farad}$
   #+end_ex
   Referenzpotential $φ= 0$ muss aber nicht im Unendlichen liegen. Allgemeiner Kondensator:
   Zwei Leiter mit Ladungen $+Q$ und $-Q$ (Realisierung durch Erdung)
   $⇒$ Erhöhung der Kapazität durch Influenz.
   #+ATTR_LATEX: :options [Kugelkondensator]
   #+begin_ex latex
   (siehe Übungen)
   #+end_ex
   #+ATTR_LATEX: :options [Plattenkondensator]
   #+begin_ex latex
   \begin{align*}
   E &= \frac{σ}{ε_0} = \frac{Q}{Aε_0} \\
   ⇒ U &= φ(x_2) - φ(x_1) = -∫_{x_1}^{x_2} \v E \d \v s \\
   &= -E ∫_{x_1}^{x_2}\d s = -\frac{Q}{ε_0 A} d \\
   ⇒ C &= \frac{Q}{U} = \frac{ε_0 A}{d}
   \end{align*}
   - $A$: Fläche der Leiterplatte
   - $d$: Leiterplattenabstand
   #+end_ex
   *Kondensatorschaltungen*: \\
   Parallelschaltung:
   - Gleiche Spannung an allen $C_i$
   - Verschiedene Werte $C_i$
   Es gilt:
   \begin{align*}
   Q &= Q_1 + Q_2 + \dots + Q_n \\
   \frac{Q}{U} &= \frac{Q_1}{U} + \frac{Q_1}{U} + \dots + \frac{Q_n}{U} \\
   ⇒ C &= C_1 + C_2 + \dots + C_n
   \end{align*}
   $⇒$ Gesamtkapazität parallelgeschalteter Kondensatoren
   \[C_{ges} = \sum_{i = 1}^{n} C_i\]
   Reihenschaltung:	Es gilt
   \begin{align*}
   U &= U_1 + U_2 + \dots + U_n \\
   \frac{Q}{C} &= \frac{Q}{C_1} + \frac{Q}{C_2} + \dots + \frac{Q}{C_n} \\
   ⇒ \frac{1}{C} &= \frac{1}{C_1} + \frac{1}{C_2} + \dots + \frac{1}{C_n}
   \end{align*}
   $⇒$ Gesamtkapazität von in Reihe geschalteter Kondensatoren:
   \[\frac{1}{C_{ges}} = \sum_{i = 1}^{n} \frac{1}{C_i}\]
   Kehrwert der Gesamtkapazität ergibt sich als Summe der Kehrwerte der Einzelkapazitäten
** Kondensator als Energiespeicher
   Energiedichte des elektrischen Feldes. Aufgeladener Kondensator = Energiespeicher. Frage:
   Wievie Energie ist gespeichert? Hierzu Betrachte Plattenkondensator:
   Ladungstransport von Platte $A$ zu Platte $B$ erfordert Arbeit
   \begin{align*}
   ⇒ \d W &= U \d Q = \frac{Q}{C} \d Q \\
   W_C &= ∫\frac{Q}{C} \d Q = \frac{1}{C}∫Q \d Q = \frac{1}{2} \frac{Q^2}{C} = \frac{1}{2} CU^2
   \end{align*}
   $⇒$ Im Plattenkondensator gespeicherte Energie:
   \[E_C = \frac{1}{2} C U^2\]
   gilt allgemein für in Kondensator gespeicherte Energie! (Herleitung unabhängig von Geometrie).
   Für Plattenkondensator gilt weiter:
   \[E_C = \frac{1}{2} C U^2 = \frac{1}{2} \frac{ε_0 A}{d}U^2 = \frac{1}{2}ε_0 (A d) \frac{U^2}{d^2} = \frac{1}{2}ε_0 V E^2\]
   Änderung des Blickwinkels:
   Energie im elektrischen Feld gespeichert $⇒$ Energiedichte $ω_e = E_c / V$
   \[⇒ ω_e = \frac{1}{2} ε_0 E^2\]
   Gilt allgemein für alle elektrischen Felder im Vakuum.
** Dielektrika - Elektrostatik in Matrie
   Beobachtung: Einbringen eines Isolators (Dielektrikum) in einen Kondensator hat großen Einfluh
   auf Kapazität. Spannung sinkt $⇒$ Kapazität steigt
   #+ATTR_LATEX: :options [Permitivität]
   #+begin_defn latex
   \[C_{Diel} = ε_r C_{Vakuum} = ε_r C_0\]
   auch Dielektrizitätskonstante, relative Dielektrizitätszahl, relative Permitivitätszahl.
   #+end_defn
   #+ATTR_LATEX: :options [Plattenkondensator]
   #+begin_ex latex
   \begin{align*}
   C_{Diel} &= ε_r ε_0 \frac{A}{d} \\
   C_{Vak} · U_{Vak} &= C_{Diel} U_{Diel} \\
   ⇒ \frac{C_{vak}}{C_{Diel}} &= \frac{U_{Diel}}{U_{vak}} = \frac{E_{Diel}}{E_{vak}} = \frac{1}{ε_r} \\
   E_{Diel} &= \frac{1}{ε_r} E_{vak}
   \end{align*}
   das heißt das Feld im Kondensator mit Dielektrikum reduziert.
   #+end_ex
   *Mikroskopische Beschreibung*: \\
   Isolator: Keine freinen, beweglichen Ladungsträger.
   Aber Polarisation, das heißt Ausrichtung von Dipolen. \\
   Kondensator
   \begin{align*}
   C_0 &= ε_0 \frac{A}{d} \\
   C_{Diel.} &= ε_r ε_0 \frac{A}{d} \\
   E_{Diel.} &= \frac{1}{ε_r} E_{\text{Vakuum}} \\
   &= \frac{1}{ε_r} E_0 \\
   \end{align*}
   \[σ_0 = \frac{Q_0}{A}\]
   \[σ_p = \frac{Q_p}{A}\]
   \[E_{Diel} = E_0 - E_p = \frac{σ_0}{ε_0} - \frac{σ_p}{e_0} = \frac{1}{ε_0}(σ_0 - σ_p) = \frac{1}{ε_r} \frac{σ_0}{ε_0}\]
   \[⇒ σ_p = σ_0(1 - \frac{1}{ε_r})\]
   \[⇒ σ_0 = σ_{frei} = ε_r σ_{tot}\]
   \[⇒ Q_0 = Q_{frei} = ε_r Q_{tot}\]
   #+ATTR_LATEX: :options [Polarisation]
   Polarisation mit Dipolmoment $\v p_i = q_i \v d_i, [P] = \si{\coulomb\per\meter\squared}$
   #+begin_defn latex
   \[\v P = \frac{1}{V} \sum \v p_i\]
   #+end_defn
   $\v P$ wächst mit stärkerer Ausrichtung des Dipols an. Und es gilt
   \[\abs{\v P} = \frac{Q_p d}{V} = \frac{σ_p A d}{V} = σ_p\]
   $⇒$ Makrospocische Polarisation = Oberflächenladungsdichte auf Dielektrikum.
   \begin{align*}
   P &= σ_p = σ_0(1 - \frac{1}{ε_r}) = ε_0 E_{vak}(1 - \frac{1}{ε_r}) \\
   &= (ε_r - 1)ε_0 E_{Diel.} \\
   \v P &= χ ε_0 \v E_{Diel.} \\
   χ &= ε_r - 1
   \end{align*}
   #+ATTR_LATEX: :options [Dielektrische Verschiebung]
   #+begin_defn latex
   \begin{align*}
   \v D &= ε_0 \v E_{Diel.} + \v P \\
   &= ε_0 \v E_{vak} = ε_0 ε_r \v E_{Diel.}
   \end{align*}
   #+end_defn
   Vakuum:
   \[\v E_{Diel} = \v E_{vak} \quad \v D = ε_0 \v E_{vak}\]
   Dielektrikum
   \[\v E_{Diel} = \frac{1}{ε_r} \v E_{vak} \quad \v D = ε_0 \v E_{vak}\]
   Allgemein:
   \[E_{vak}^{\parallel} = E_{Diel}^{\parallel}, E_{vak}^{\perp} = ε_r E_{Diel}^{\perp}\]
   \[D_{vak}^{\parallel} = \frac{1}{ε_r} D_{Diel}^{\parallel}, D_{vak}^{\perp} = D_{Diel}^{\perp}\]
   \begin{align*}
   \Div \v E_{vak} &= \frac{ρ_{innen}}{ε_0} \\
   ⇒ \Div \v D &= ρ_{frei}
   \end{align*}
   $⇒$ 1. Maxwell Gleichung in Materie
   \[\Div \v D = ρ_{frei} \quad ∮\v D \d \v A = Q_{frei}\]
   \[\Div \v E = \frac{ρ_{frei}}{ε_0 ε_r} \quad ∮\v D \d \v A = \frac{Q_{frei}}{ε_0 ε_r}\]
   Elektrische Feldenergie im Dielektrikum
   \[W_e = \frac{1}{2} C n^2 = \frac{1}{2} \frac{Q^2}{C} = \frac{1}{2} \frac{1}{ε_r} \frac{Q^2}{C_0}\]
   \[⇒ ω_C = \frac{1}{2} ε_r ε_0 \v E^2 = \frac{1}{2} \v E \v D\]
   Für gleiches Feld $\v E$ wächst die Energiedichte mit $ε_r$. Zur Energie des Feldes $\v E$ wird
   Polarisationsenergie der Dipole addiert.
* Elektrische Gleichströme
** Strom und Stromdichte
   #+ATTR_LATEX: :options [Elektrischer Strom]
   #+begin_defn latex
   \[I = \dd{Q}{t}\]
   \[[I] = \si{\coulomb\per\second} = \si{\ampere}\]
   \[\abs{\v j} = \frac{I}{A} = \frac{\d Q}{A\d t}\]
   \[\v j = ρ \v v = n q_e \v v_D\]
   \[\dots ρ = \div \v j = 0\]
   \[I = ∫\v j \d A = \dd{Q}{t} = ∫\dot ρ \d V\]
   #+end_defn
** Elektrischer Widerstand und Ohmsches Gesetz*
   Ladungsfluß entsteht aufgrund einer Potentialdifferenz beziehungsweise eines Elektrischen Feldes.
   \[U = φ_b - φ_a = E Δl\]
   Spannungsänderung
   - $⇒$ Änderung Elektrisches Feld
   - $⇒$ Änderung der Ladungsträgergeschwindigkeit
   - $⇒$ Änderung von Stromdischte und StromElektrisches Feld
   #+ATTR_LATEX: :options [Differentieller Wiederstand]
   #+begin_defn latex
   \[ϑ = \dd{U}{I}\]
   $[S] = \si{\ampere\per\volt} = \si{\siemens}$
   #+end_defn
   #+ATTR_LATEX: :options [Differentielle Leitfähigkeit]
   #+begin_defn latex
   \[S = \dd{I}{U}\]
   $[ϑ] = \si{\volt\per\ampere} = \si{\ohm}$
   #+end_defn
   Beobachtung: Elektischer Leiter: $ϑ = \const$
   \begin{align*}
   R &= \frac{U}{I} = \frac{E l}{I} ⇔ I = \frac{E l}{R} \\
   j &= \frac{I}{A} = \frac{l}{R A} E = σ E = η q_e v_D
   \end{align*}
   #+ATTR_LATEX: :options [Ohmsches Gesetz]
   #+begin_thm latex
   \begin{align*}
   U &= R I \\
   \v j &= σ \v E = η _E \v v_D \\
   \intertext{mit}
   σ &= \frac{l}{R A} = S \frac{l}{A} \tag{spezifische Leitfähigkeit} \\
   ρ &= \frac{1}{σ} &= R \frac{A}{l} \tag{spezifischer Widerstang}
   \end{align*}
   Für ohmschen Leiter muss $\v v_D \sim \v E$ gelten.
   #+end_thm
   *Durde Modell* \\
   Bewegung von Elektronen in Leitern.
   Thermische Bewegung: $v_{th} \approx \num{1e6} - \SI{1e7}{\meter\per\second}$. Bewegung wird
   gestört durch Stöhe mit Gitteratomen. Mittlere Zeit zwischen zwei Wechselwirkungen:
   \[τ = \frac{T}{N} ⇒ λ = τ v_m\]
   $T$: Messzeit, $N$: Anzahl der Stöße.
   Einschalten eines E-Feldes:
   Beschleunigung der Elektronen entgegen der Richtung des elektrischen Feldes $\v E$
   \begin{align*}
   \v A &= \frac{\v F}{m} = \frac{q \v E}{m} \\
   ⇒ \v v_D(t) &= \v v_{th} + \frac{q \v E}{m}t \\
   \v v_D &= \underbrace{<\v v_{th}>}_{= 0} + \frac{q \v E}{m}<t> = \frac{q}{\v E}m	τ = μ \v E
   \end{align*}
   Also gilt für einen ohmschen Leiter:
   \[\v v_D = μ \v E\]
   mit $μ$: Elektronenbeweglichkeit
   \[μ = \frac{q}{τ}m, [μ] = \si{\meter\squared\per\volt\second}\]
   Mit
   \[\v j = n q_e \v v_D = n q_e μ \v E\]
   \[σ = n _e μ = \frac{n q_e^2 τ}{m}\]
   #+ATTR_LATEX: :options [Kupferdraht]
   #+begin_ex latex
   \[A = \SI{1}{\milli\meter\squared}, I = \SI{1}{\ampere}, j = \frac{I}{A} ⇒ v_D = \SI{10e-4}{\meter\per\second}\]
   Jedes Athon liegt 1 Elektron bei.
   #+end_ex
   Ohmscher Leiter: $ϑ = \const$
   \[\dd{ϑ}{I} < 0 \text{ NTC, Heißleiter}\]
   \[\dd{ϑ}{I} > 0 \text{ PTC, Kaltleiter}\]
** Elektrische Leistung
   Strom $I$ fließt durch Widerstand beziehungsweise Verbraucher, gewonnene kinetische Energie
   der Elektronen wird durch Stöhe in Wärme umgewandelt.
   \[W = Q U = U I t\]
   #+ATTR_LATEX: :options [Leistung]
   #+begin_defn latex
   \[P = U I\]
   $[P] = \si{\watt} = \si{\joule\per\second} = \si{\ampere\per\volt}$
   #+end_defn
   Für ohmschen Leiter:
   \[P = R I^2 ⇔ P = \frac{U^2}{R}\]
   Anwendungsbeispiel: Hochspannungsleitung. Transport von elektrischer Energie:
   Verluste durch Wärmeerzeugung in Überlandleitung. Ziel: Minimierung von Leistungsverlusten.
   Kraftwerk: $F = U I$ \\
   Überlandleitung:
   - Spannungsabfall: $U_L = R_L I$
   - Verlustleistung: $P_L = U_L I = R_L I^2 = U^2 / R$
   das heißt Spannungsabfall beziehungsweise Verlustleistung klein falls $I$ klein und $U$ groß!
   $⇒$ Hochspannungsleitung.
   Verfügbare Leistung: $P_V = P - P_L$
** Stromkreise - Kirchhoffsche Regeln
   Haushalt, elektrische Schaltungen, $\dots$ Im Allgemeinen Netzwerke vieler Leiter,
   Spannungsquallen und Verbraucher. Zur Berechnung von Strömen und Spannungen: \\
   Kirchhoffsche Regeln:
   1. Knotenregel: An jedem Knoten gilt $\sum I_k = 0$ (Ladungserhaltung, folgt aus Kontinuitätsgleichung)
   2. Maschenregel: Für jede Masche gilt: $\sum U_k = 0$ (Zirkulationsgesetz)
   Für ohmsche Widerstände ergibt sich damit: \\
   Reihenschaltung:
   \[R = \sum_{i = 1}^{n} R_i\]
   Parallelschaltung:
   \[\frac{1}{R} = \sum_{i = 1}^{n} \frac{1}{R_i}\]
** Strom und Spannungsquellen
   Spannungsquelle mit Innenwiderstand $R_i$:
   \begin{align*}
   U_{kl} &= U_0 - I R_i \\
   &= U_0 \frac{R_a}{R_a + R_i}
   \end{align*}
   $⇒$ Ideale Spannungsquelle:
   \[R_i \approx 0 \quad I = \frac{U_0}{R_i + R_a}\]
   Stromquelle: Versorgung mit konstantem Strom. $⇒$ hoher Innenwiderstand ($R_i \to ∞, R_i \gg R_a$)
   \[I = \frac{U_0}{R_i + R_a} = \frac{U_0}{R_i} = \const\]
   Technische Realisierung? \\
   Prinzip: Ladungstrennung durch Energiezufuhr $⇒$ Potentialdifferenz, leitende Verbindung $⇒$ Stromfluß.
   Anwendung finden:
   - elektrodynamische Generatoren, magnetische Induktion
   - Batterie und Akkumulatoren, Ladungstrennung durch chemische Reaktionen
   - Solarzellen, Ladungstrennung durch Lichtenergie
   - Thermische Stromquellen, Ladungstrennung durch Temperaturabhängigkeit von Kontaktpotentialen.
   Galvanische Elemente $⇒$ Galvani-Spannung: $Δφ_C$ $⇒$ Volta-Element \\
   Minuspol: $Zn \to Zn^{++} + 2e^-$ \\
   Pluspol: $2H^+ + 2 e^- \to H_2$ \\
   $Z_n + H_2 SO_4 \to H_2 + Zn SO_4$ \\
   Daniel-Element: Diaphragma, dass nur $SO_4$ durchlässt verhindert *Vergiftung*. \\
   Thermische Stromquellen. Bei Kontakt zweier Metalle ergibt sich Potentialdifferenz $⇒$ Kontaktspannung.
   Ursache: Unterschiedlicshe Austrittarbeit für freie Elektronen. Austrittsarbeit und Kontaktspannung hängen von
   Temperatur ab.
   - Thermoelement
   - Peltierkühlung (Umkehrung)
** Strom und Spannugsmessung
   Ziel: Strom- und Spannungsmessung ohne Beeinflussung des zu messendes Systems. \\
   Strommessung: Ampermeter in Reihe mit Verbraucher, Ampermeter - $R_i \approx 0$ um zusätzlichen Spannungsabfall aus
   Messgrät zu minimieren. \\
   Spannungsmessung: Voltmeter parallel zum Verbraucher geschaltet. Voltmeter - $R_i \to \infty$, um
   Stromfluss durch Voltmeter zu minimieren. \\
   Messinstrumente:
   - Galvanometer
   - Digitalvoltmeter (mit Operationsverstärker)
	 (Messberecherweiterung durch Parallel- und Serienschaltung von Widerständen)
