* Induktion und elektromagnetische Wechselfelder
  Bisher: stationäre, das heißt zeitunabhängige Felder \\
  Jetzt:
  - zeitabhängige B-Felder $\to$ magnetische Induktion
  - zeitabhängige E-Felder $\to$ Verschiebungsstrom
** Magnetische Induktion
   Beobachtungen
   - Bewegte Leiterschleife im Magnetfeld resultiert in Induktion und Spannugsstößen
   - Vorzeichen abhängig von Bewegungsrichtung und Richtung des Magnetfelds
   - Mehrere Windungen (beziehungsweise größere Fläche) $\to$ höhere Spannungen
   - Drehung Leiterschleife $\to$ Wechselspannung
   \[∫ U(t) \d t = Δ ϕ_m \quad\text{mit}\quad ϕ_m= ∫ \v B \d \v A\]
   \[U_{ind}= - \dot ϕ_m \quad\text{beziehungsweise } U_{ind} = - N \dot ϕ_m\]
   Ursache? $⇒$ Lorentzkraft
   \[\v F = q(\v b × \v B)\]
   \begin{align*}
   \d U_{ind} &= E_{ind} \d l = \frac{F}{q} \d l = v B \d l \\
   U_{ind} &= ∫_1^2 E_{ind} \d l = v B l \\
   U_{ind} &= ∮ E \d l = ∫_1^2 E \d l + ∫_2^1 E \d l = v B l
   \end{align*}
   Beliebige Schleife
   \begin{align*}
   U_{ind} &= ∮(\v v × \v B) \d \v l \\
   &= ∮ \v E_{ind} \d \v l \\
   &= ∮ (\d \v l × \v v) \v B \\
   &= - ∮(\v v × \d \v l) \v B \\
   &= - ∮(\dd{\v s}{t} × \d \v l) \v B = - ∮ \dd{\v A}{t} \v B \\
   &= - \dd{}{t} ∫ \v B \d \v A = - \dot ϕ_m \tag{Für $\v B = \const$} \\
   ϕ_m &= ∫ \v B \d \v A = B l s \\
   \dot ϕ_m &= B l \dot s = B l v
   \end{align*}
   Neu: Induktion durch $\dot{\v B}$. Rein experimentelle Beobachtung
   #+ATTR_LATEX: :options [Faradaysches Induktionsgesetz]
   #+begin_thm latex
   \[U_{ind} = ∮ E_{ind} \d \v s = - \dot ϕ_m\]
   mit $ϕ_m = ∫ \v B \d \v A$
   #+end_thm
   Neue	grundlegende Eigenschaft: Wichtig: $\rot \v E \neq 0$
   \begin{align*}
   ∮_C \v E \d \v s &= - \dot ϕ_m = - \dd{}{t} ∫_O \v B \d \v A \\
   ⇒ ∫_O \rot \v E \d \v A &= - \dd{}{t} ∫_O \v B \d \v A = - ∫_O \dot{\v B} \d \v A \tag{Falls $O$ beziehungsweise $C$ konstant}
   \end{align*}
   #+ATTR_LATEX: :options [3. Maxwell-Gleichung]
   #+begin_thm latex
   \begin{align*}
   ∮_C \v E \d \v s &= - \dd{}{t} ∫_O \v B \d \v A \tag{E-Feld nicht mehr Wirbelfrei} \\
   \rot \v E &= - \dot{\v B} \tag{Induktion nur in Verbindung mit der Lorenzkraft}
   \end{align*}
   #+end_thm
   #+ATTR_LATEX: :options [Lenzsche-Regel]
   #+begin_thm latex
   Die durch Induktion entstehende Spannungen, Ströme, Felder und Kräfte wirken der die Induktion hervorrufenden Ursache stets entgegen.
   #+end_thm
** Generatoren
   \begin{align*}
   ϕ_m &= ∫\v B \d \v A = B A \cos ω t \\
   \dot{ϕ_m} &= - U_{ind} = ω B A \sin ω t
   \end{align*}
** Induktivität und Selbstinduktion
   Betrachte stromdurchflossene Leiterschleife
   $B \sim I, ϕ_m \sim I$
   #+ATTR_LATEX: :options [Induktivität]
   #+begin_defn latex
   \[ϕ_m = L I\]
   $L$: Eigenschaft des felderzeugenden Leiters.
   #+end_defn
   Induktivität einer Spule:
   $N$ Windungen, $l$ Länge, $n = N / l$, Querschnittsfläche $A$
   \begin{align*}
   B &= μ μ_0 n I \\
   ϕ_m &= N B A = n l B A \\
   ϕ_m &= \underbrace{μ μ_0 n^2 A l}_{L} I \\
   ⇒ U_{ind} &= - \dot{ϕ_m} = - L \dot I
   \end{align*}
   Weitere Beispiele:
   - Drahtschleife: $L = μ_0 R \ln R / r$
   - Doppelleitung: $L = μ_0 l / π \ln a / r$
   - Koaxialkabel: $L= μ_0 l / (2 π) \ln r_a / r_i$
   Außerdem:
   Zeitlich veränderlicher Stromfluß durch eine Leiteranordnug führt zu einer zeitlichen Veränderung des
   erzeugten B-Feldes $\to$ Flußänderung $\to$ Spannungsindukiton.
   \[U_{ind} = - \dot ϕ_m = - L \dot I\]
** Verschiebungsstrom
   Für zeitlich veränderliche B-Felder:
   \begin{align*}
   \rot \v E = 0 &\to \rot \v E = - \dot{\v B} \\
   ∮ \v E \d \v s = 0 &\to ∮ \v E \d s = - ∫ \dot{\v B} \d \v A
   \end{align*}
   Jetzt: Betrachte Ampersches Durchflutungsgesetz
   \[\rot \v B = μ_0 \v j ⇔ ∮ \v B \} \v s = μ_0 I\]
   Betrachte Leiter durch Kondensator. Danng gilt:
   \[∮ \v B \d \v s = B 2 π r = μ_0 I \to B = \frac{μ_0 I}{2 π r}\]
   Aber: Verschiebung des Integrationsweges zwischen die beiden Kondensatorplatten liefert:
   \[∮ \v B \d \v s = 0\]
   Dies erscheint unmöglich! B-Feld kann im Kondensator nicht abrupt verschwinden.
   Außerdem:
   \[∮_C \v B \d \v s = μ_0 ∫_A \v j \d \v A\]
   (gilt für alle Flächen mit Randkurve $C$). Fläche $A_1$: Kreisfläche um Leiter, Fläche $A_2$: Fläche mit
   Kondensator $⇒$
   - Fläche $A_1$: $B = μ_0 I / (2 π r)$
   - Fläche $A_2$: $B = 0$
   $⇒$ offensichtlicher Widerspruch. $⇒$ Etwas fehlt!
   Berücksichtigung des durch Kondensatoraufladung erzeugten zeitlich sich ändernden elektrischen Feldes.
   Kontinuitätsgleichung:
   \[\Div \v j = - \dot ρ ⇔ ∮ \v j \d \v A = - \dd{q}{t}\]
   Es gilt:
   \[∮ \v E \d \v A = q / ε_0 \to \dd{q}{t} = ε_0 \dd{}{t} ∮ \v E \d \v A = ε_0 ∮ \pp{\v E}{t} \d \v A = ε_0 ∮ \dot{\v E} \d \v A\]
   Konsistente Beschreibung falls:
   - Fläche $A_1$: $∮\v B \d \v s = μ_0 ∫_{A_1} \v j \d \v A$
   - Fläche $A_2$: $∮\v B \d \v s = μ_0 ε_0 ∫_{A_2} \dot{\v E}\d \v A = μ_0 ∫_{A_2} \v j_v \d \v A$ mit
	 \[\v j_v = ε_0 \pp{\v E}{t}\]
	 "Verschiebungsstrom"
  $\to$ Erweiterung des Ampereschen Durchflutungsgesetzes:
  #+ATTR_LATEX: :options [Ampere-Maxwell-Gesetz (4. Maxwell-Gleichung für Vakuum)]
  #+begin_thm latex
  \begin{align*}
  ∮ \v B \d \v s &= μ_0 ∫ \v j \d \v A + μ_0 ε_0 ∫ \pp{\v E}{t} \d \v A \\
  \rot \v B &= μ_0 \v j + μ_0 ε_0 \pp{\v E}{t} = μ_0 \v j + \frac{1}{c^2} \pp{\v E}{t}
  \end{align*}
  #+end_thm
  #+begin_remark latex
  Für $j = 0$ gilt: $\rot \v B = 1 / c^2 \dot{\v E}$, das heißt elektrische Wechselfelder erzeugen ein
  magnetisches Wirbelfeld, umgekehrt erzeugen wegen $\rot \v E = - \dot{\v B}$ magnetische Wechselfelder
  ein eletrisches Wirbelfeld. $\to$ elektromagnetische Wellen (siehe unten)
  #+end_remark
  Jetzt: Verschiebungsstrom in Matrie
  \[∮ \v B \d \v s = μ_0 I_{ges} = μ_0 I_L + μ_0 I_M + μ_0 I_v + μ_0 I_P\]
  - $I_L$: Leitungsstrom (frei Ströme)
  - $I_M$: Molekularstrom
  - $I_V$: Verschiebungsstrom
  -	$I_P$: Polarisationssrom (nur für nicht-stationäre E-Felder)
  Molekulorstrom:
  \begin{align*}
  ∮ \v M \d \v s &= I_M \\
  ∮ \v H \d \v s &= ∮ (\frac{1}{μ_0} \v B - \v M) \d \v s = I_L+ I_V + I_P = I_L + ε_0 ∫_A \dot{\v E} \d \v A + I_P \\
  &= I_L + ε_0 ∫_A \dot{\v E} \d \v A + ∫ \v j_P \d \v A
  \end{align*}
  Polarisationsstrom:
  Ergibt sich aufgrund des Flusses gebundener Ladungen in Richtung des elektrischen Feldes $\to$
  zeitlich veränderlicher Strom für zeitlich veränderliche E-Felder
  \begin{align*}
  \v j_P &= n q \v v = n q \dd{\v s}{t}, \d \v p = q \d \v s, \d \v P = n d \v p \\
  \v j_P &= n \dd{\v p}{t} = \dd{\v P}{t} ⇔ \v j_P ⇔ \pp{\v P}{t} = \dot{\v P} \\
  \intertext{Damit}
  ∮ \v H \d \v s &= I_L + ε_0 ∫\dot{\v E} \d \v A = I_L + ∫ \dot{\v D} \d \v A \\
  \v E &= ε_0 \v E + \v P
  \end{align*}
  #+ATTR_LATEX: :options [Ampere-Maxwell-Gesetz in Matrie (4. Maxwellsche Gleichung)]
  #+begin_thm latex
  \begin{align*}
  ∮ \v H \d \v s &= ∫ \v j \d \v A + ∫ \pp{\v E}{t} \d \v A \\
  \rot \v H &= \v j + \dot{\v D}
  \end{align*}
  #+end_thm
