#+AUTHOR: Robin Heinemann
#+TITLE: Experimentalphysik III (Oberthaler)
#+INCLUDE: "../header.org" :minlevel 1

# 60% Punkte aus Übungaufgaben
# Übungsblatt: jeden Dientstag ab 14:00 Uhr
# Abgabe der Übungen: nach der Vorlesung am Montag (ab 23. Oktorber) in der Vorlesung
# Klausur: voraussichtlich am 5.2.2018
# Experimentierraum: Do + Fr 14-18 Uhr, 3D-Drucker!


# Montag 13.11 13:30 Fragen

# Quantenphysik und Atome
# Ziele:
# Einführen der Grundkonzepte der Quantenmechanik
# Anwendung der QM für quanitiatives Verstehen der Natur
#   Verstehen der Struktur der Atome & Atom-Licht Wechselwirkung
#   Verbindung zur Thermodynamik - Bose und Fermi Gase
# Neueste Entwicklungen
#   Laserkühlung (N.P. 1996)
#   Ultrakalte Quantengase (N.P.)
#

# \tikzexternalize

* Vorspann
** Ein Experiment mit klassischen Teilchen
   1. Fall: Quelle von nicht weiter zerteilbaren Teilchen mit zufälliger Richtung. Es werden die Anzahl der Teilchen auf einem Raster $x$ mit Gitterkonstante $Δx$ gemessen.
	  Dann werden in der Mitte die meißten Teilchen ankommen. Die diskrete Verteilung kann mit einer kontinuierlichen Wahrscheinlichkeitsverteilung beschrieben werden. Die
	  wichtigen Größen sind hier die Position der maximalen Wahrscheinlichkeit und die Breite (FWHM - full width half maximum)
	  #+begin_export latex
      \catcode`(=12
      \catcode`)=12
      \begin{center}
      \begin{tikzpicture}[
            source/.style={draw=black,fill=black!10},
            ray/.style={>=latex,draw=black,fill=blue},
            axis/.style={black,font=\small},
            bin/.style={black,font=\small},
        ]
      \draw[source] (0,0) coordinate (base)
                           -- (0,-1) -- (-1,-1) coordinate[pos=0.5] (mid)
                           -- (-1, 0)
                           -- (base) -- cycle;
      \foreach \x in {-10,...,10}
          \draw[ray,->] ({0.03*\x - 0.5},-1) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});
      \begin{scope}[shift={(0,-2)}]
      \draw[axis,->] (-5,-5) -- (4,-5) node[right] {Ort $x$};
      \foreach \x in {-9,...,7}
          \draw[bin] ({0.5*\x},-5) -- ++(0,1.5);
      \foreach \count/\x\ in {2/0, 1/2, 2/3, 2/4, 3/5, 4/6, 7/7, 8/8, 6/9, 6/10, 5/11, 3/12, 2/14, 1/15}
          \foreach \y in {1,...,\count}
              \filldraw (0.5*\x - 4.25, 0.2*\y - 5.1) circle (2pt);
      \node[font=\scriptsize] at (-4.5,-5.2) {$x$};
      \node[font=\scriptsize] at (-4,-5.2) {$x\!\!+\!\!Δx$};
      \draw[domain=-4.5:4.5,smooth,variable=\x,red,shift={(-.5,-5)}] plot ({\x},{1.5*exp(-0.5*\x*\x)});
      \draw[axis,->,red, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};
      \node[font=\scriptsize,font=\tiny, red] at (-1,-3.4) {$P_1(x)$};
      \draw[axis,->,red] (-2.25,-4.08) -- (-1.5, -4.08) node[font=\tiny, above, midway, yshift=-2pt] {FWHM};
      \draw[axis,->,red] (1.25,-4.08) -- (0.5, -4.08);
      \end{scope}
      \end{tikzpicture}
      \end{center}
      \catcode`(=\active
      \catcode`)=\active
	  #+end_export
   2. Fall: 2 Quellen (mittels Doppelspalt der Breite $d$, $d \ll \text{FWHM}$)
	  #+begin_export latex
      \catcode`(=12
      \catcode`)=12
      \begin{center}
      \begin{tikzpicture}[
            source/.style={draw=black,fill=black!10},
            ray/.style={>=latex,draw=black,fill=blue},
            axis/.style={black,font=\small},
            bin/.style={black,font=\small},
        ]
      \draw[source] (0,0) coordinate (base)
                           -- (0,-1) -- (-1,-1) coordinate[pos=0.5] (mid)
                           -- (-1, 0)
                           -- (base) -- cycle;
      \foreach \x in {-10,...,10}
          \draw[ray,->] ({0.03*\x - 0.5},-1) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});

      \draw[source,green,fill=green!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
      \draw[source,green,fill=green!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
      \draw[source,green,fill=green!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
      \draw[<->,green] (-1.25, -3.5) -- (0.25, -3.5) node[midway, above,font=\tiny] {$d$};
      \node[green] at (4, -3.5) {$d \ll\text{FWHM}$};

      \foreach \x in {-3,...,3}
          \draw[ray,->,green] ({0.075*\x - 1.25},-4) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});

      \foreach \x in {-3,...,3}
          \draw[ray,->,green] ({0.075*\x + 0.25},-4) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});

      \begin{scope}[shift={(0,-4)}]
      \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
      \foreach \x in {-9,...,7}
          \draw[bin] ({0.5*\x},-5) -- ++(0,1.5);
      \foreach \count/\x\ in {1/1, 2/3, 2/4, 3/5, 4/6, 6/7, 7/8, 6/9, 4/10, 5/11, 2/14, 1/15}
          \foreach \y in {1,...,\count}
              \filldraw[green] (0.5*\x - 4.25, 0.2*\y - 5.1) circle (2pt);

      \node[font=\scriptsize] at (-4.5,-5.2) {$x$};
      \node[font=\scriptsize] at (-4,-5.2) {$x\!\!+\!\!Δx$};
      \draw[domain=-4.5:4.5,smooth,variable=\x,green,shift={(-1.25,-5)}] plot ({\x},{1.5*exp(-0.5*\x*\x)});
      \draw[domain=-4.5:4.5,smooth,variable=\x,green,shift={(.25,-5)}] plot ({\x},{1.5*exp(-0.5*\x*\x)});
      \draw[domain=-4.5:4.5,smooth,variable=\x,black,shift={(-.5,-5)}] plot ({\x},{1.5*exp(-0.5*\x*\x)});
      \draw[axis,->,green, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};
      \node[font=\scriptsize,font=\tiny, green] at (-1.45,-3.4) {$P_1$};
      \node[font=\scriptsize,font=\tiny, green] at (.45,-3.4) {$P_2$};
      \node[font=\scriptsize,font=\tiny, black] at (-.5,-3.3) {$(P_1 + P_2)/2$};
      \end{scope}

      \end{tikzpicture}
      \end{center}
      \catcode`(=\active
      \catcode`)=\active
	  #+end_export
   Wichtig: Diskrete Zahlen. Die theoretische Wahrscheinlichkeitsverteilung kann nur annähernd gemessen werden! Anzahl der Teilchen $\to ∞ ⇒ P_1(x)$.
** Ein Experiment mit klassischen Wellen
   Quelle sendet Kugelwellen aus (fixe Frequenz, fixe Amplitude), Doppelspalt. Ein Detektor misst Strom $\propto$ Intensität. Man erhält das Intensisätsmuster $I_{12}$ eines Doppelspalts.
   Bei blockieren eines der Öffnungen des Doppelspalt erhält man einen Einzelspalt und somit nurnoch das Intensitätsmuster eines Einzelspalts, mit Maximum bei dem nicht blockierten Spalt.
   Wichtig: Intensität ist kontinuierlich $I_{12}$ kann genau gemessen werden. \\
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \filldraw (-.5,-.5) circle (2pt);
   \draw (-.5,-.5) circle (7pt);
   \draw (-.5,-.5) circle (12pt);
   \centerarc[](-.5,-.5)(220:320:17pt);
   \centerarc[](-.5,-.5)(220:320:22pt);
   \centerarc[](-.5,-.5)(220:320:27pt);

   \draw[source,green,fill=green!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,green,fill=green!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,green,fill=green!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \draw[<->,green] (-1.25, -3.5) -- (0.25, -3.5) node[midway, above,font=\tiny] {$d$};

   \foreach \x in {1,...,4}
       \centerarc[]({-1.25},-4)(180:360:\x*7.5pt);
   \foreach \x in {1,...,4}
       \centerarc[]({.25},-4)(180:360:\x*7.5pt);

   \draw[source,red,fill=red!10] (-.1,-4.2) -- (-.1,-4.4) -- (.6, -4.4) -- (.6,-4.2) -- cycle;
   \node[red,font=\small,right] at (0.8, -4.3) {Blockierte Position 2};
   %    \draw[ray,->,green] ({0.075*\x - 1.25},-4) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});
   \begin{scope}[shift={(0,-4)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[right] {Ort $x$};
   \draw[axis,->,green, font=\small] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Intensität $I_{12}$};
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,green,shift={(-0.5,-5)}] plot ({\x},{4/sqrt(\x*\x + 4) * cos(\x/(0.0015*sqrt(\x*\x + 4)))^2});
   \draw[domain=-4.5:4.5,smooth,variable=\x,red,shift={(-1.25,-5)}] plot ({\x},{0.65*exp(-0.5*\x*\x)});
   \draw[source,black,fill=black!10] (-3,-4.8) -- (-3,-5) -- (-3.2, -5) -- (-3.2,-4.8) -- cycle;
   \node[font=\small,below] at (-3, -5) {Detektor};
   \draw[green] (-.40, -3.03) -- (-.60, -3.03);
   \draw[dotted] (-.5, -2.5) -- (-.5, -5);
   \node[green] at (-.40, -2.85) {1};
   \filldraw[red] (-.50, -4.5) circle (1pt);
   \node[red] at (-.20, -4.25) {1/4};
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Warum hat $I_{12}$ die angegebene Form?
   \begin{align*}
   I(x) &= c ε_0 \frac{1}{2T} ∫_{-T}^T E(x, t) \d t \\
   E(x, t) &= E_1 \cos(ω t + \v k \v R_1) + E_2 \cos(ω t + \v k \v R_2)
   \end{align*}
   mit Hilfe von komplexer Schreibweise
   \begin{align*}
   E(x, t) &= \Re \{\underarrow[E_1]{reell} e^{i(ω t - \v k \v R_1)} + \underarrow[E_2]{reell} e^{i(ω t - \v k \v R_2)}\} \\
   &= \Re \{(E_1 \underbrace{e^{-i(\v k \v R_1)}}_{a_1} + \underbrace{E_2 e^{-i \v k \v R_2}}_{a_2}) e^{i ω t}\} \\
   ⇒ I_{12}(x) &\propto \abs{a_1 + a_2}^2 \\
   \intertext{Wir interessieren uns nur für \(x\)-Abhängigkeit, nicht für absolute Werte}
   I_{12}(x) \propto \abs{a_1 + a_2}^2 &= (a_1^{\ast} + a_2^{\ast})(a_1 + a_2) \\
   &= \abs{a_1}^2 + \abs{a_2}^2 + a_1^{\ast} a_2 + a_2^{\ast} a_1 \\
   \abs{a_1}^2 &= E_1 e^{i k R_1} E_1 e^{-k R_1} = E_1^2 \sim I_1 \\
   \abs{a_2}^2 &= E_2 e^{i k R_2} E_2 e^{-k R_2} = E_2^2 \sim I_2 \\
   a_1^{\ast} a_2 + a_2^{\ast} a_1 &= a_1^{\ast} a_2 + \cc \\
   &= 2 \Re \{a_1^{\ast} a_2\} = 2\Re\{E_1 E_2 e^{i k(\v R_2 - \v R_1)}\} \\
   &= 2 \sqrt{I_1 I_2} \cos\underbrace{(\v k(\v R_2 - \v R_1))}_{ϕ} \\
   ⇒ \Aboxed{I_{12} &= I_1 + I_2 + 2 \sqrt{I_1 I_2} \cos ϕ}
   \end{align*}
   Maximale Intensität $ϕ = 0 \quad \abs{\v R_1} = \abs{\v R_2}$. Für $I_1 = I_2 = I_0$:
   \begin{align*}
   I_{\text{MAX}} &= I_1 + I_2 + 2 \sqrt{I_1 I_2} = 4 I_0 \\
   I_{\text{MIN}} &= I_1 + I_2 = 2 \sqrt{I_1 I_2} = 0
   \end{align*}
   Intensität wird räumlich	umverteilt,	gesamt Intensistät bleibt erhalten
   \[I_1 + I_2 = \text{Energieerhaltung}\]
** Ein Experiment mit Elektronen/Atomen
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \draw[source] (0,0) coordinate (base)
                        -- (0,-1) -- (-0.5, -2)-- (-1,-1) coordinate[pos=0.5] (mid)
                        -- (-1, 0)
                        -- (base) -- cycle;

   \foreach \x in {-10,...,10}
       \draw[ray,->] ({-.5 + 0.5*sin(4*\x)},{-2*cos(4*\x)}) -- ++({sin(4*\x)},{-cos(4*\x)});
   \node at (0.2,-1.4) {$e^-$};
   \draw[source,black,fill=black!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \node at (-1.5, -3.5) {\circled{1}};
   \node at (0.5, -3.5) {\circled{2}};

   \begin{scope}[shift={(0,-3)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
   \foreach \x in {-9,...,7}
       \draw[bin] ({0.5*\x},-5) -- ++(0,1.5);
   \foreach \count/\x\ in {1/1, 3/2, 2/5, 6/6, 7/6, 6/7, 5/8, 5/9, 3/10, 2/13, 2/14}
       \foreach \y in {1,...,\count}
           \filldraw[black] (0.5*\x - 4.25, 0.2*\y - 5.1) circle (2pt);

   \draw[axis,->,black, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};

   \node[font=\scriptsize] at (-4.5,-5.2) {$x$};
   \node[font=\scriptsize] at (-4,-5.2) {$x\!\!+\!\!Δx$};
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,red,shift={(-.5,-5)}] plot ({\x},{(cos(120*\x) + 1)*.7*exp(-0.1*\x*\x)});
   \node[red] at (2.7, -4.2) {$P_{12} = ?$};
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Quelle: Metallspitze aus hohem negativen Potential.
   Wieder diskrete Detektoren, Messung über Elektronenvervielfacher: durch anliegende Spannung löst
   ein Elektron aus einer Metallplatte weitere Elektronen aus, die wieder weiter auslösen. Es entsteht
   ein kurzer Strom-Peak, der gemessen werden kann. \\
   Annahmen:
   \begin{enumerate}
   \item Das Elektron geht entweder durch Blende \circled{1}, oder Blende \circled{2}
   \item Mit "`komplizierter"' Dynamik
   \end{enumerate}

   Einfacher Test für Annahme 2.: Blockieren einer Blende (hier \circled{2}). Man würde
   eine Verteilung ähnlich der mit zwei Blendern erwarten.
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \draw[source] (0,0) coordinate (base)
                        -- (0,-1) -- (-0.5, -2)-- (-1,-1) coordinate[pos=0.5] (mid)
                        -- (-1, 0)
                        -- (base) -- cycle;

   \foreach \x in {-10,...,10}
       \draw[ray,->] ({-.5 + 0.5*sin(4*\x)},{-2*cos(4*\x)}) -- ++({sin(4*\x)},{-cos(4*\x)});
   \node at (0.2,-1.4) {$e^-$};
   \draw[source,black,fill=black!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \node at (-1.5, -3.5) {\circled{1}};
   \node at (0.5, -3.5) {\circled{2}};

   \draw[source,red,fill=red!10] (-.1,-4.2) -- (-.1,-4.4) -- (.6, -4.4) -- (.6,-4.2) -- cycle;
   \node[red,font=\small,right] at (0.8, -4.3) {blockieren \circled{2}};
   \begin{scope}[shift={(0,-3)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
   \draw[axis,->,black, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};

   \node[font=\scriptsize] at (-4.5,-5.2) {$x$};
   \node[font=\scriptsize] at (-4,-5.2) {$x\!\!+\!\!Δx$};
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,black,shift={(-.5,-5)}] plot ({\x},{(cos(120*\x) + 1)*.7*exp(-0.1*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,red,shift={(-.5,-5)}] plot ({\x},{.35*exp(-0.1*\x*\x)});
   \node[red] at (-2.5, -4.5) {$P_{1}$};
   \node[black] at (2.7, -4.2) {$P_{12}$};

   \filldraw[black] (-.50, -3.60) circle (1pt);
   \node[black] at (-.20, -3.45) {1};
   \filldraw[red] (-.50, -4.65) circle (1pt);
   \node[red] at (-.20, -4.35) {\(\frac{1}{4}\)};
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Teilchen verschwinden in den Minima bei der $P_{12}$, obwohl sie nach der Verteilung für eine Blende
   auch dort ankommen müssten.
   \[⇒P_{12} \neq \frac{1}{2} \{P_1 + P_2\}\]
   Mathematische "`einfach"': Einführen der komplexen Wahrscheinlichkeitsamplitude \(ϕ\). Wahrscheinlichkeiten sind gegeben durch
   \begin{align*}
   P_1 &= \abs{ϕ_1}^2 \\
   P_2 &= \abs{ϕ_2}^2 \\
   P_{12} &= \abs{ϕ_1 + ϕ_2}^2
   \end{align*}

   \begin{important}
   Elektronen werden einzeln gezählt. Es gibt keine "halben" Elektronen. Wahrscheinlichkeitsverteilung kann nur annähernd gemessen werden. $P_{12} \estimates$ unendlich viele Experimente.
   \end{important}

   \begin{ibox}{Welle-Teilchen Dualismus}
   Elektronen werden nur als Einheiten detektiert, die räumliche Verteilung	kann als Interferenz von Wahrscheinlichkeits-Amplituden (komplexes $ϕ$) beschrieben werden.
   \end{ibox}
   Beobachtung der Elektronen an jedem Spalt.
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \draw[source,black,fill=black!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \node at (-1.5, -3.5) {\circled{1}};
   \node at (0.5, -3.5) {\circled{2}};
   \draw[orange,fill=orange!10] (-.5, -4.8) circle (6pt);
   \foreach \x in {0,...,10}
       \draw[ray,orange,->,fill=orange!10] ({-.5 + 0.22*sin(36*\x)},{-0.22*cos(36*\x) - 4.8}) -- ++({0.5*sin(36*\x)},{-0.5*cos(36*\x)});
   \node[orange] at (-.5, -5.6) {Lichtquelle};
   \filldraw[black] (-1.25, -4.5) circle (1pt);
   \draw[->,decoration={snake,pre length=3pt, post length=3pt,amplitude=5,segment length=20},decorate,orange] (-1.35, -4.5) -- (-4.5, -5);
   \eye{.7}{-5.5}{-5}{0}
   \node[black,every text node part/.style={align=center}] at (-5.5, -6.3) {Lichtblitz \\ durch gestreutes \\ Licht};

   \begin{scope}[shift={(0,-3)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
   \draw[axis,->,black, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};

   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,orange,shift={(-1.25,-5)}] plot ({\x},{1.5*exp(-0.3*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,orange,dashed,shift={(.25,-5)}] plot ({\x},{1.5*exp(-0.3*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,black,shift={(-.5,-5)}] plot ({\x},{1.5*exp(-0.3*\x*\x)});
   \node[orange] at (2.3, -4.2) {$P_{2}$};
   \node[orange] at (-3.3, -4.2) {$P_{2}$};
   \node[font=\scriptsize,black] at (-.5,-3.3) {$(P_1 + P_2)/2$};
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Es entstehen Lichtblitze durch gestreutes Licht. \(P_1\): Blitz bei \circled{1}, \(P_2\): Blitz bei \circled{2}. Blitz bei \circled{1} und	\circled{2} wird nie beobachtet.
   Dies bestätigt Annahme \circled{1}.
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \draw[source,black,fill=black!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \node at (-1.5, -3.5) {\circled{1}};
   \node at (0.5, -3.5) {\circled{2}};
   \draw[red,fill=orange!10] (-.5, -4.8) circle (6pt);
   \foreach \x in {0,1,2,3,7,8,9}
       \draw[->,red,decoration={snake,pre length=3pt, post length=3pt,amplitude=5,segment length=20},decorate] ({-.5 + 0.22*sin(36*\x)},{-0.22*cos(36*\x) - 4.8}) -- ++({1.5*sin(36*\x)},{-1.5*cos(36*\x)});
   \foreach \x in {0.5,1.5,2.5,7.5,8.5,9.5}
       \draw[->,green,decoration={snake,pre length=3pt, post length=3pt,amplitude=5,segment length=10},decorate] ({-.5 + 0.22*sin(36*\x)},{-0.22*cos(36*\x) - 4.8}) -- ++({1.5*sin(36*\x)},{-1.5*cos(36*\x)});

   \filldraw[black] (-1.25, -4.5) circle (1pt);
   \draw[->,decoration={snake,pre length=3pt, post length=3pt,amplitude=5,segment length=20},decorate,red] (-1.35, -4.5) -- (-4.5, -5);
   \eye{.7}{-5.5}{-5}{0}
   \node[red] at (1.7, -4.2) {$λ \gg d$};
   \node[green] at (1.7, -4.7) {$λ \sim d$};
   \draw[<->,black] (-1.25, -3.5) -- (0.25, -3.5) node[midway, above] {$d$};
   \begin{scope}[shift={(0,-4)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
   \draw[axis,->,black, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};

   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,red,shift={(-.5,-5)}] plot ({\x},{(cos(240*\x) + 1)*.7*exp(-0.1*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,green,shift={(-.5,-5)}] plot ({\x},{(cos(240*\x) + 1)*.7*exp(-0.1*\x*\x) + .35*exp(-0.1*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,green,dashed,shift={(-.5,-5)}] plot ({\x},{.35*exp(-0.1*\x*\x)});
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Bei $λ > d$ ist nicht mehr feststellbar, ob das Elektron durch \circled{1} oder \circled{2} kommt.
   Bei $λ \sim d$ erhält man eine Überlagerung von $\abs{ϕ_1 + ϕ_2}$ und $\frac{1}{2}(P_1 + P_2)$

   Quantenmechanik kann das beschreiben, weil das prinzipiell mögliche Wissen einer physikalischen
** Zusammenfassung
   Für fundierte Diskussion eines Quantenmechanischen Experiments mus definiert werden
   1. Präpration de Anfangszustand
   2. Wechselwirkung / Zeitlich Entwicklung
   3. Detektion - Was wird beobachtet
   Ein *Ereignis* ist definiert als ein spezielles Set von 1. bis 3..
   #+begin_ex latex
   Ein $e^-$ verlässt die Quelle kann nicht alle Orte in Raum erreichen (Blenden), $e^-$ wird
   in einem Ortsintervall $[x, x + Δx]$ detektiert.
   #+end_ex
   Vorhersagen nach folgenden Regeln
   1. Die Wahrscheinlichkeit eines Ereignisses in einem idealen Experiment ist gegeben als
	  das Quadrat des Absolutbetrages einer im allgemeinen komplexen Wahrscheinlichkeitsamplitude \\
	  $P\dots$ Wahrscheinlichkeit \\
	  $ϕ\dots$ Wahrscheinlichkeits-Amplitude \\
	  $P = \abs{ϕ}^2 = ϕ^{\ast} ϕ$
   2. Wenn ein Ereignis in verschiedener Art und Weise stattfinden kann, dann ist
	  die Wahrscheinlichkeits-Amplitude gegeben als Summe der einzelnen Wahrscheinlichkeits-Amplituden
	  der Möglichkeiten.
      #+begin_ex latex
	  $e^- \to$ Detektor über
	  - Blende \circled{1}
	  - Blende \circled{2}
	  \begin{align*}
	  ϕ &= ϕ_1 + ϕ_2 \tag{Superposition} \\
	  P &= \abs{ϕ}^2 = \abs{ϕ_1 + ϕ_2}^2
      \end{align*}
      #+end_ex
   3. Kann man die einzelnen Möglichkeiten prinzipiell unterscheiden, addieren sich die Wahrscheinlichkeiten
	  \[P = (P_1 + P_2) / 2\]
* Materiewellen
** Historische Herleitung von de Broglie
   Ziel:
   - Dispersionsrelation für massive Teilchen
   - Superpositionen von unphysikalischen Wellen können Natur beschreiben
   -	Zerlegungin de Broglie-Wellen erlaubt vorhersagen
   \fullcite{broglie1924xxxv} \\
   3 Grundlegende Hypothesen ($3×$ Einstein)
   1. $E = m_0 c^2$ Masse = Energie, $m_0$: Ruhemasse, $c$: Lichtgeschwindigkeit
   2. $E = h ν_0$ Photoeffekt, $h = \SI{6.626069934+-0.000000089e-34}{\joule\second}$ Planck Konstante, $ν_0$: Frequenz
   3. Gleichmäßig bewegte Bezugssysteme sind mit Lorenzt Transformation verknüpft
   Aus 1. und 2. folgt, dass man jedem Teilchen im Ruhesystem eine Frequenz zuordnen kann
   \[ν_0 = \frac{m_0 c^2}{h}\]
   Sei $S$ ein ruhendes Bezugssystem, betrachte ein ruhendes	Teilchen ($v = 0$). Man erhält
   \[ψ = e^{i ν_0 2π t}\]
   Nun betrachte ein bewegtes Bezugssystem $S'$ mit $v_x = v, v_{y,z} = 0$. Man erhält
   \[ψ = e^{i ν_0 2π t'}\]

   \[t' = \frac{t - \frac{v}{c^2}x}{\sqrt{1 - (\frac{v}{c})^2}}\]
   Die Zeit wird ortsabhängig!
   \begin{align*}
   S'&: e^{i2πν_0 t'} \\
   S&: e^{i2πν_0 (\frac{t - \frac{v}{c^2}x}{\sqrt{1 - (\frac{v}{c})^2}})} = e^{i(ω_{dB}t - k_{dB}x)} \tag{die de Broglie Welle} \\
   \intertext{mit}
   ω_{dB} &= \frac{2π ν_0}{\sqrt{1 - (\frac{v}{c})^2}} = \frac{2π}{h}\frac{m_0 c^2}{\sqrt{1 - (\frac{v}{c})^2}} = \frac{E_{\text{ges}^{\text{Ruhe}}}}{\hbar} \\
   \hbar &= \frac{h}{2π} \\
   \v k_{dB} &= \frac{2π ν_0 \v v}{c^2 \sqrt{1 - (\frac{\v v}{c})^2}} = \frac{2π}{h} \frac{m_0 c^2 \v v}{c^2 \sqrt{1 - (\frac{\v v}{c})^2}} = \frac{\v P_{\text{mel}}}{\hbar}
   \end{align*}
   \begin{ibox}{nicht relativistischer Limes $v \ll c$}
   \begin{align*}
   ω_{dB} &= \frac{1}{\hbar}(m_0 c^2 + \frac{m_0 \v v^2}{2} + \dots) \\
   \v k_{dB} &= \frac{1}{\hbar} m_0 \v v
   \end{align*}
   \end{ibox}
   \[ψ(x, t) = e^{-i(ω_{dB}t - \v k_{dB} \v x)} = \underbrace{e^{i \frac{m_0 c^2}{\hbar}t}}_{\mathclap{\const\text{ hängt nur von der Masse ab}}} e^{i(\underbrace{\frac{m_0 \v v^2}{2\hbar}}_{ω}t - \underbrace{\frac{m_0 \v v}{\hbar}}_{\v k} \v x)}\]
   \begin{ibox}{Materiewelle}
   \[ψ(x,t) = e^{-i(ω t - k x)}\]
   mit
   \begin{align*}
   ω &= \frac{\hbar k^2}{2m} \\
   \hbar k &= m v
   \end{align*}
   Beschreibt ein massives Teilchen mit Masse $m$, das sich mit wohldefinierter / scharf definerter Geschwindigkeit $v \ll c$ bewegt (Impuls Eigenzustand).
   \end{ibox}
   Den Zusammenhang $ω(k) = f(k)$ nennt man Dispersionsrelation.
   #+begin_important latex
   Unterschied zu elektromagnetischen Wellen im Vakuum:
   \[λν = c ⇒ ω = c k\]
   Materiewellen
   \[ω = \frac{\hbar}{2m} k^{\circled[red]{2}}\]
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{tikzpicture}
   \draw[->] (0,0) -- (6,0) node[anchor=north] {$k = \frac{p}{\hbar}$};
   \draw[->] (0,0) -- (0,4) node[anchor=east] {$ω=\frac{E}{\hbar}$};
   \draw (0,0) -- (6,3);
   \draw [red] (0,1) to [bend right=10] (6,3.2);
   \draw [red,decorate,decoration={brace,amplitude=3pt},xshift=-4pt,yshift=0pt] (0, 0) -- (0, 1)node [red,midway,xshift=-14pt] {\footnotesize $m_0 c^2$};
   \draw[<-] (3.9,1.9) to [bend left] (4.9,0.9) node[xshift=5pt,yshift=-10pt,every text node part/.style={align=center}] {Masseloses \\ Teilchen - Photonen};
   \draw[<-,red] (3.9,2.3) to [bend right=10] (2.9,2.9) node[xshift=-28pt,yshift=0pt,every text node part/.style={align=center}] {Dispersion \\ eines Atoms};
   \end{tikzpicture} \\
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   #+end_important
** Wie sieht die Materiewelle aus?
   \begin{align*}
   t = 0\quad ψ(x, t = 0) &= e^{ik_{dB} x} \\
   &= \cos(k_{dB} x) + i \sin(k_{dB} x) \\
   k_{dB} &= \frac{2π}{λ_{dB}} \\
   E &= \frac{\hbar^2 k_{dB}^2}{2m} = \frac{m v^2}{2} \\
   ⇒ \Aboxed{λ_{dB} &= \frac{h}{m v}} \tag*{de Broglie Beziehung}
   \end{align*}
   *Größenordnung* \\
   Thermisches Gas:
   \begin{align*}
   \bar v &= \sqrt{\frac{8 k_{B} T}{π m}} \tag*{mittlere Geschwindigkeit} \\
   \hat v &= \sqrt{\frac{2 k_{B} T}{m}} \tag*{wahrscheinlichste Geschwindigkeit}
   \end{align*}
   | $T$                      | $\hat v$                                | $\hat λ_{dB}$            |
   | $\SI{300}{\kelvin}$      | $\sim\SI{240}{\meter\per\second}$       | $\SI{19}{\pico\meter}$   |
   | $\SI{10}{\micro\kelvin}$ | $\sim\SI{4}{\centi\meter\per\second}$   | $\SI{0.1}{\micro\meter}$ |
   | $\SI{10}{\nano\kelvin}$  | $\sim\SI{1.4}{\milli\meter\per\second}$ | $\SI{3.3}{\micro\meter}$ |
   \[λ_{dB} \propto \frac{1}{\sqrt{T}}\]
   $ψ(x, t)$ ist ein komplexes Feld: \\
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{minipage}{0.45\linewidth}
   Zeit $t = 0$
   \[\displaystyle{ψ(x,t = 0) = e^{i k_{dB} x}}\] \\
   \end{minipage}
   \hfill%
   \begin{minipage}{0.45\linewidth}
   \begin{center}
   \begin{tikzpicture}
       \draw[->] (0,0) -- (6,0) node[anchor=north] {$x$};
       \draw[->] (0,0) -- (0,3) node[anchor=east] {$\Re(ψ)$};
       \draw[red,->] (6,0) -- (6,3) node[anchor=east] {$\Im(ψ)$};
       \draw[red] (0,0) sin (1,2) cos (2,0) sin (3,-2) cos (4,0)
              sin (5,2) cos (6,0);
       \begin{scope}[shift={(-1,0)}]
       \draw[black] (1,2) cos (2,0) sin (3,-2) cos (4,0)
              sin (5,2) cos (6,0) sin (7, -2);
       \end{scope}
   \end{tikzpicture}
   \end{center}
   \end{minipage} \\
   \begin{minipage}{0.45\linewidth}
   Zeit t
   \[\displaystyle{ψ(x,t) = e^{-i(ω_{dB} t - k_{dB} x)}}\] \\
   \end{minipage}
   \hfill%
   \begin{minipage}{0.45\linewidth}
   \begin{center}
   \begin{tikzpicture}
       \draw[->] (0,0) -- (6,0) node[anchor=north] {$x$};
       \draw[->] (0,0) -- (0,3) node[anchor=east] {$\Re(ψ)$};
       \draw[red,->] (6,0) -- (6,3) node[anchor=east] {$\Im(ψ)$};
       \draw[black] (0,0) sin (1,2) cos (2,0) sin (3,-2) cos (4,0)
              sin (5,2) cos (6,0);
       \begin{scope}[shift={(1,0)}]
           \draw[red] (-1, -2) cos (0, 0) sin (1,2) cos (2,0) sin (3,-2) cos (4,0)
              sin (5,2);
       \end{scope}

       \draw (1,.1) -- (1,-.1) node[below] {$x_m$};
       \draw[->] (0,2.1) -- (1,2.1);
       \draw (1,2.1) -- (1,1.975);
       \draw (0.95,2) -- (1.05,2) node[above,xshift=7pt] {$ω_{dB} t = k_{dB} x_m$};
   \end{tikzpicture}
   \end{center}
   \end{minipage}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   # \begin{align*}
   # ψ(x, t) &= e^{i(ω_{dB} t - k_{dB} x)} = \underbrace{e^{i \frac{m_0 c^2}{\hbar}t}}_{\mathclap{\text{hängt nicht von } x, v \text{ ab}}} e^{-i(\frac{m_0 \v v^2}{2\hbar}t - \frac{m_0 \v v}{\hbar}x)} \\
   # P &= \abs{ψ}^2 = \abs{e^{iϕ_0} ψ}^2
   # \end{align*}
   - globale Phase spielt keine Rolle
   - Energienullpunkt $E = m_0 c^2$
   $ψ(x, t)$ ist ein komplexes Feld:
   \begin{align*}
   ω_{dB} t &= k_{dB} x_m \\
   x_m &= \underbrace{\frac{ω_{dB}}{k_{dB}}}_{v_{ph}^{dB}} t \\
   v_{ph}^{dB} &= \frac{m v^2}{2\hbar}\frac{\hbar}{mv} = \frac{v}{2} \tag*{Phasengeschwindigkeit}
   \end{align*}
   Phasengeschwindigkeit ist nicht physikalisch! Gegeben eine de Broglie Welle mit $k_{dB} = k$.
   Wie groß ist die Wahrscheinlichkeit das Teilchen irgendwo zu finden?
   \[P = ∫_{∞}^∞ \underarrow[p]{W.-Dichte}(x) \d x = ∫_{-∞}^∞ \abs{ψ(x)}^2 \d x = ∫_{-∞}^∞ e^{i k x} e^{ - i k x} \d x = ∫_{-∞}^∞ \d x = ∞\]
   Eine de Broglie Welle ist nicht normierbar! Analoges Problem:	Energieinhalt in einer ebenen Elektromagnetischen Welle. \\
   $⇒$ Lösung: Superposition (Überlagerung) von ebenen (unphysikalischen) Wellen erlaubt, um
   physikalischen Situation zu beschreiben. \\
   Zusammenfassung: Neue Beschreibung der Bewegung von Teilchen $⇒$ Wellenoptik. Für
   $ψ(x, t) ⇒ \abs{ψ(x, t)^2} \d x$ ist die Wahrscheinlichkeit, ein Teilchen zur Zeit $t$ im
   Intervall $[x, x + \d x]$ zu beobachten. Klassische Teilchenmechanik entspricht dem geometrischen
   "Optik-Limit" der Wellenmechanik. \\
   \begin{ibox}{Fermat'sches Prinzip in der Wellenoptik}
   Licht breitet sich entlang des kürzesten optischen Weges aus
   \[\underarrow[δ]{Variation} ∫ \frac{\d s}{λ} = 0 = δ ∫ \frac{\d s}{\frac{h}{m v}} = \frac{1}{h} \underbrace{δ ∫ m v \d s = 0}_{\mathclap{\text{Maupertuis Prinzip der kleinsten Wirkung}}}\]
   \end{ibox}
** Das Wellenpaket - physikalische Wellenfunktion durch Überlagerung (Superposition von ebenen Wellen)
   Das Wellenpaket (ruhend) \\
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{minipage}{.45\linewidth}
   $t = 0$ \\
   \begin{center}
   \begin{tikzpicture}
    \draw[->] (0,0) -- (6,0) node[anchor=north] {$x$};
    \draw[->] (3,0) -- (3,3) node[anchor=east] {$ψ$};
    \draw[color=black, domain=-3:3, samples=100,shift={(3,0)}] plot (\x,{2*exp(-\x*\x)});
    \filldraw (3,2) circle (1.5pt);
    \node[above right] at (3,2) {$ψ_0$};
    \draw[<-] (4, .72) -- (5.5, .72) node[above] {$\frac{ψ_0}{e}$};
    \draw[<-] (2, .72) -- (0.5, .72);
    \draw (2,.72) -- (2,0) node[below] {$-a$};
    \draw (4,.72) -- (4,0) node[below] {$a$};
    \draw (2.9,0.72) -- (3.1,0.72) node[right,font=\scriptsize,xshift=-3pt] {$0,36$};
   \end{tikzpicture}
   \end{center}
   \end{minipage}
   \hfill%
   \begin{minipage}{.45\linewidth}
   \begin{align*}
   ψ(x, t= 0) &= \underbrace{(\frac{2}{π a^2})^{1/4}}_{\mathclap{\text{Normierung}}} e^{- \frac{x^2}{a^2}} \\
   ∫_{-∞}^∞ \abs{ψ}^2 \d x &= 1 \tag*{Quadrat-Integrabel}
   \end{align*}
   \end{minipage}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   $t = T?$ Wir wissen "nur" wie sich de Broglie Wellen ausbreiten $⇒$ zerlege $ψ(x, t = 0)$ in
   ebene Wellen mit Wellenvektor $k_{dB}$. Jede Welle wird sich entsprechend
   \[ω_{dB} = \frac{\hbar k^2_{dB}}{2m}\]
   ausbreiten.
   \begin{align*}
   ψ(x, t = 0) &= ∫_{-∞}^∞ \underarrow[\tilde ψ(k)]{Amplitude der Welle} \overarrow[e^{i k x}]{de Broglie Welle $t = 0$} \d k
   \intertext{$⇒$ triviale Zeitentwicklung}
   ψ(x, t = T) &= ∫_{-∞}^∞ \tilde ψ(k) e^{i k x} e^{-i ω T} \d k \\
   &= ∫_{-∞}^∞ \underbrace{\tilde ψ(k) e^{-i \frac{\hbar}{2m} k^2 T}}_{\text{Phase}} e^{i k x} \d k
   \end{align*}
   Nur die Phase der komplexen Wahrscheinlichkeits-Amplitude ändert sich. Die zeitliche Änderung ist *linear* in
   der Zeit, aber quadratisch in $k$. \\
   Da
   \[Ψ = \tilde ψ(k) e^{i(k x - ω t)}\]
   einer de Broglie Welle und damit einem Teilchen mit scharf definiertem Impuls $p = m v = \hbar k$
   entspricht, bezeichnet man $\tilde ψ(k)$ als Impulsdarstellung / Impulsamplitude. Entsprechend
   $Ψ(x)$ ist die Ortsdarstellung / Ortsamplitude des Quantenmechanischen-Zustandes.
   Die Ausbreitung im Impulsraum ist trivial
   \[\underbrace{\tilde ψ(k)}_{t = 0} \to \underbrace{\tilde ψ(k)}_{t} \underarrow[e^{-i \frac{\hbar k^2}{2m}t}]{Rotation in komplexer Zahlenebene}\]
   Aber wie sieht die räumlich Wahrscheinlichkeitsverteilung aus? \\
   Wiederholung: Fourier-Transformation. \\
   \begin{ibox}{Periodische Funktionen (Fourier 1822)}
   \begin{align*}
   f(x + d) &= f(x) \tag*{$d$: Periode} \\
   f(x) &= \sum_{n = -∞}^{∞} g_n e^{i n G x} \tag*{$G= \frac{2π}{d}$} \\
   g_n &= \frac{1}{d} ∫_{x}^{x + d} f(x) e^{- in G x} d x
   \end{align*}
   \end{ibox}
   \begin{align*}
   ∫_0^d f(x) e^{- i m G x} &= ∫_0^d \sum_{n = -∞}^{∞} g_n e^{i(n - m)G x} = g_m d \\
   ∫_{-∞}^∞ \abs{f(x)}^2 \d x &= ∫_{-∞}^∞ \sum_{n = -∞}^{∞} g_n^{\ast} e^{-i n G x} \sum_{m = -∞}^{∞} g_m e^{i m G x} \d x \\
   &= ∫_{- ∞}^∞ \sum_{n} \sum_{m} g_n^{\ast} g_m e^{i(m - n) G x} \d x \\
   &= \sum_{n = -∞}^{∞} \abs{g_n}^2 = 1 \tag*{Normierung}
   \end{align*}
   $f(x)$ reell $\to g_n = g_n^{\ast}$
   \begin{align*}
   \sum_{n = -∞}^{∞} g_n e^{i n G x} &= g_0 + \sum_{n = -∞}^{-1} g_n e^{i n G x} + \sum_{n = 1}^{∞} g_n e^{i n G x} \\
   &= g_0 +	\{\sum_{n = 1}^{∞} g_n^{\ast} e^{- i n G x} + \sum_{n = 1}^{∞} g_n e^{i n G x}\} \\
   z^{\ast} + z &= (a + i b)^{\ast} + (a + i b) = 2 \Re \{z\}
   \end{align*}
   Einfache Beispiele
   \[f(x) = \cos(G x) = \frac{1}{2} e^{-i G x} + \frac{1}{2} e^{i G x}\]
   Fouriertransformierte
   \[g_{-1} = \frac{1}{2} \qquad g_0 = 0 \qquad g_1 = \frac{1}{2} \qquad g_{\abs{n} > 1} = 0\]
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \[
       f(x) = \dots
       \begin{tikzpicture}[baseline={([yshift=-.5ex]current bounding box.center)}]
           \draw (0.5, 0) -- (1, 0) -- (1, 1) -- (2, 1)
                        -- (2, 0) -- (3, 0) -- (3, 1)
                        -- (4, 1) -- (4, 0) -- (4.5, 0);
           \draw[|-|] (1, 1.3) -- (2,1.3) node[midway,fill=white] {B};
           \draw[|-|] (1, -.3) -- (3,-.3) node[midway,fill=white] {d};
           \draw (.6, 1) node[left] {$1$} -- (.8, 1);
       \end{tikzpicture}
       \dots
   \]
   \begin{center}
   \begin{tikzpicture}
   \draw[->] (-4, 0) -- (4, 0) node[right] {$n$};
   \draw[->] (0, 0) -- (0, 3);
   \draw[domain=-4:4,smooth,variable=\x,red] plot ({\x},{2*sinc(1.8*\x)});
   \foreach \x in {-7,...,7}
       \draw ({.5*\x}, 0) -- ({.5*\x},{2*sinc(1.8*.5*\x)});
   \foreach \x in {0,...,7}
       \draw ({.5*\x}, 0) -- ({.5*\x}, -.1) node[below] {\x};
   \draw[red,<-] (1.75, -.1) -- (1.75, -.6) node[below] {$\frac{d}{B}$};
   \node[red,right] at (.5,3) {$n \neq 0\quad g_n = \frac{1}{nπ} \sin(n \frac{πB}{d})$};
   \node[red,right] at (2.5,2.5) {$g_0 = \frac{B}{a}$};
   \draw[->,red] (2,2.6) -- (1,1.3);
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Je kleiner die Struktur im Ortsraum, umso breiter wird die Verteilung im Impulsraum. \\
   \begin{ibox}{Aperiodische Funktionen}
   \begin{align*}
   f(x) &= \frac{1}{\sqrt{2π}}∫_{-∞}^∞ g(k) e^{ikx} \d k \\
   g(k) &= \frac{1}{\sqrt{2π}}∫_{-∞}^∞ f(x) e^{-ikx} \d x \\
   \end{align*}
   \end{ibox}
   Normierung:
   \[∫_{-∞}^∞ f(x) f^{\ast}(x) \d x = ∫_{-∞}^{∞} g(k) g^{\ast}(k) \d k = 1\]
   In der Quantenmechanik hat man
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{align*}
   ψ(x) &⇔ f(x) \\
   \tilde ψ(k) &⇔ g(k) \\
   \end{align*}
   Dirca-Delta Fuktion \\
   \begin{align*}
   f(x) &= δ(x) =
   \begin{tikzpicture}[baseline={([yshift=-.5ex]current bounding box.center)}]
   \draw[->] (0,0) -- (2,0) node[right] {$x$} node[below,midway] {$0$} ;
   \draw[very thick] (1,0) -- (1,1) node[right] {$∞$};
   \end{tikzpicture} \\
   ∫_{-∞}^∞ h(x) δ(x - x_0) \d x &= h(x_0) \\
   \intertext{Darstellung der Dirac \(δ\)-Funktion über Fourier-Transformation}
   g(k) &= \frac{1}{\sqrt{2π}}∫_{-∞}^{∞} δ(x) e^{-ikx} \d x = \frac{1}{\sqrt{2π}} \\
   δ(x) &= \frac{1}{2π} ∫_{-∞}^∞ e^{ikx} \d x
   \end{align*}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT

   Darstellung von komplexen Zahlen:
   \begin{align*}
   ψ &= \abs{ψ} e^{iϕ}\\
   ψ(x) &= ∫_{-∞}^{∞} \tilde ψ(k) e^{ikx} \d k
   \end{align*}

   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{equation*}
  \begin{array}{cc}
    \text{Ort} & \text{Impuls} \\
    ψ(x, t = 0) = (\frac{2}{πa^2})^{1/4} e^{-\frac{x^2}{a^2}} & \tilde ψ(k, t = 0) = \frac{\sqrt{a}}{(2π)^{3/4}} e^{-\frac{a^2}{4} k^2} \\
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
      \draw[->] (-3.5, 0) -- ++(0, 6) node[left] {$\abs{ψ}^{\circled[red]{$2$}}$};
      \draw (0,.1) -- (0,-.1) node[below] {$0$};
      \draw[variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {3*exp(-\x*\x)});
      \draw[green,variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {6*exp(-4*\x*\x)});
      \draw[->] (-2,{3*exp(-1)}) -- ++(1,0);
      \draw[->] (2,{3*exp(-1)}) node[right, above] {$\frac{1}{\sqrt{e}}$-Breite} -- ++(-1,0);
      \draw (1,{3*exp(-1) + .5}) -- ++(0,-1.9) node[below right,xshift=-2.7mm] {$Δx = \frac{a}{2}$};
    \end{tikzpicture}
    &
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
      \draw[->] (-3.5, 0) -- ++(0, 6) node[left] {$\tilde{\abs{ψ}}^{2}$};
      \draw (0,.1) -- (0,-.1) node[below] {$0$};
      \draw[variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {3*exp(-\x*\x)});
      \draw[green,variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {1.5*exp(-.25*\x*\x)});
      \draw[->] (-2,{3*exp(-1)}) -- ++(1,0);
      \draw[->] (2,{3*exp(-1)}) node[right, above] {$\frac{1}{\sqrt{e}}$-Breite} -- ++(-1,0);
      \draw (1,{3*exp(-1) + .5}) -- ++(0,-1.9) node[below right,xshift=-2.7mm] {$Δx = \frac{1}{k}$};
    \end{tikzpicture}
    \\
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
      \draw[->] (-3.5, 0) -- ++(0, 6) node[left] {$ϕ$};
      \draw (-3.6, 3) node[left] {$0$} -- (-3.4,3);
      \draw (-3.2, 3) -- (3.3,3);
    \end{tikzpicture}
    &
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
      \draw[->] (-3.5, 0) -- ++(0, 6) node[left] {$\tilde ϕ$};
      \draw (-3.6, 3) node[left] {$0$} -- (-3.4,3);
      \draw (-3.2, 3) -- (3.3,3);
    \end{tikzpicture}
  \end{array}
   \end{equation*}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT

   \begin{ibox}{Heisenberg Unschärfe}
   \[Δ x · Δ p = \hbar \underarrow[Δ x]{$\frac{1}{\sqrt{l}}$ Wert der W.-Verteilung} Δ k = \hbar \frac{a}{2} \frac{1}{a} = \frac{\hbar}{2}\]
   $Δ x = \underarrow[\text{RMS}]{Root Mean Square} = \sqrt{\angl{x^2} - \angl{x}^2}$
   \end{ibox}
   folgt aus der Beschreibung eines Teilchens mit Gewschwindigkeit $\v v$ / Impuls $m \v v$ durch
   $e^{i \v k \v x} ⇔$ de Broglie Welle und dem Superpositionsprinzip. \\
   Extremfall: Teilchen am Ort $x_0$:
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
  \begin{equation*}
  \begin{array}{cc}
    \text{Ort} & \text{Impuls} \\
    ψ(x, t = 0) = δ(x - x_0) & \tilde ψ(k, t = 0) = \frac{1}{2π}∫_{-∞}^{∞} e^{i k (x - x_0)} \d k \\
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
      \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\abs{ψ(x)}$};
      \draw[red] (0,0) node[below] {$x_0$} -- ++(0,3.5);
    \end{tikzpicture}
    &
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
      \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\abs{ψ(k)}$};
      \draw[red] (-3.5,2) -- ++(7,0);
    \end{tikzpicture}
    \\
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
      \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$ϕ$};
      \draw (-3.6, 1) node[left] {$0$} -- (-3.4,1);
      \draw[red] (-3.2, 1) -- (3.3,1);
    \end{tikzpicture}
    &
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
      \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\tilde ϕ$};
      \draw[red] (-3.4,2) node[left] {$-k x_0$} -- (3.4,2);
    \end{tikzpicture}
  \end{array}
  \end{equation*}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   $⇒$ Impuls maximal $[-∞,∞]$ unscharf. \\
   Analog: Ein Teilchen mit wohldefiniertem Impuls ist vollständig delokalisiert. \\
   # Impuls ist: $e^{ik_0 x}$
   Ausbreitung eines Wellenpakets:
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{alignat*}{2}
  \intertext{$t = 0$}
  &\begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\abs{ψ}$};
    \draw (0,.1) -- (0,-.1) node[below] {$0$};
    \draw[variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {4*exp(-4*\x*\x)});
  \end{tikzpicture}
  &&
  \begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\tilde{\abs{ψ}}$};
    \draw (0,.1) -- (0,-.1) node[below] {$0$};
    \draw[variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {3*exp(-\x*\x)});
  \end{tikzpicture}
  \\
  &\begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$ϕ$};
    \draw (-3.6, 1) node[left] {$0$} -- (-3.4,1);
    \draw (-3.2, 1) -- (3.3,1);
  \end{tikzpicture}
  &&
  \begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\tilde ϕ$};
    \draw (-3.6, 3) node[left] {$0$} -- (-3.4,3);
    \draw (-3.2, 3) -- (3.3,3);
  \end{tikzpicture}
  \\
  \intertext{{$\color{blue}t=T$}}
  &\begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\abs{ψ}$};
    \draw (0,.1) -- (0,-.1) node[below] {$0$};
    \draw[variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {4*exp(-4*\x*\x)});
    \draw[blue,variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {2*exp(-\x*\x)});
    \draw[blue,<-] (1,1.5) -- (2,2.5) node[align=center,above right,xshift=-.5cm] {Wellenpaket \\ zerläuft};
  \end{tikzpicture}
  &&
  \begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\tilde{\abs{ψ}}$};
    \draw (0,.1) -- (0,-.1) node[below] {$0$};
    \draw[variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {3*exp(-\x*\x)});
    \draw[<-] (1,1.5) -- (2,2.5) node[align=center,above right,xshift=-.5cm] {Keine Kraft \\ Impuls kann sich \\ nicht ändern};
  \end{tikzpicture}
  \\
  &\begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$ϕ$};
    \draw (-3.6, 1) node[left] {$0$} -- (-3.4,1);
    \draw (-3.2, 1) -- (3.3,1);
    \draw[mark position=.15(a),blue,domain=-3.5:3.5,variable=\x,samples=100,shift={(0,1)}] plot ({\x},{0.1*\x*\x});
    \node[blue,below left,xshift=7pt] at (a) {$ϕ\propto x^2$};
  \end{tikzpicture}
  &&
  \begin{tikzpicture}[remember picture]
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\tilde ϕ$};
    \draw (-3.6, 3) node[left] {$0$} -- (-3.4,3);
    \draw (-3.2, 3) -- (3.3,3);
    \draw[mark position=.75(a),mark position=.80(b),blue,domain=-3.5:3.5,variable=\x,samples=100,shift={(0,3)}] plot ({\x},{-0.15*\x*\x});
    \node[right,blue,xshift=7pt] at (a) {$ϕ \propto -k^2$};
%    \draw (0,0) -- (m-sq);
  \end{tikzpicture}
  \\
  & && \qquad\tilde ψ(k, t) = \tilde ψ(k) e^{-iω_{dB} t} = \tilde ψ(k) e^{-i \frac{\hbar k^{
        \text{\tikz[remember picture,overlay,baseline,anchor=base,inner sep=0pt]{
            \node[shape=circle,draw,inner sep=0,thin,blue,text=black] (m-sq) at (0,0) {$2$};
            \draw[->, blue] ([xshift=1pt,yshift=1pt]m-sq) to [bend left=5] ([yshift=-2pt,xshift=1pt]b);
          }
        }}}{2m}t}
\end{alignat*}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   \begin{align*}
   ψ(x, t) &= \frac{\sqrt{a}}{(2π)^{3/4}} ∫_{-∞}^∞ e^{-\frac{a^2}{4}(k - k_0)^2} e^{i(k x - ω(k)t)} \d k \\
   \text{mit} \quad ω(k) &= \frac{\hbar k^2}{2m} \\
   ψ(x, t) &= (\frac{2a^2}{π})^{1/4} \frac{e^{iφ}}{(a^4 + \frac{4\hbar^2 t^2}{m^2})^{1/4}} e^{i k_ 0 x} e^{- \frac{(x - \frac{\hbar k_0}{m}t)^2}{a^2 + \frac{2 i \hbar t}{m}}} \\
   \text{mit} \quad φ &= -θ - \frac{\hbar k_0^2}{2m}t \\
   \tan 2θ &= \frac{2\hbar t}{m a^2}
   \end{align*}
   Für die Breite $Δx(t)$ ergibt sich
   \begin{align*}
   Δx(t) &= \frac{a}{2}	\sqrt{1 + \frac{4\hbar^2 t^2}{m^2 a^4}} \\
   \intertext{Für kurze Zeiten:}
   Δx(t) &\sim \frac{a}{2} \frac{\hbar^2}{m^2 a^3}t^2 + \dots \tag*{Quadratisch} \\
   \intertext{Für lange Zeiten:}
   Δx(t) &\sim \frac{\hbar}{m a}t \tag*{Linear} \\
   \intertext{Bemerkung:}
   λ_{dB} &= 2 a  ⇔ v = \frac{\hbar}{m} \frac{2π}{λ_{dB}} = 2π \frac{\hbar}{m a}
   \end{align*}
   #+BEGIN_EXPORT latex
\begin{minipage}{.4\linewidth}
\begin{center}
\catcode`(=12
\catcode`)=12
\begin{tikzpicture}
  \draw[->] (-3.5, 0) -- ++(5, 0) node[below] {$t$};
  \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$Δx$};
  \draw[blue,domain=0:4.3,variable=\x,samples=100,shift={(-3.5,2)},smooth] node[left] {$2Δx_1$} plot ({\x},{0.1*\x*\x});
  \draw[red,domain=0:3.5,variable=\x,samples=100,shift={(-3.5,1)},smooth] node[left] {$Δx_1$} plot ({\x},{0.25*\x*\x}) node[right] {$\propto t^2$};
\end{tikzpicture}
\catcode`(=\active
\catcode`)=\active
\end{center}
\end{minipage}
\hfill%
\begin{minipage}{.6\linewidth}
Stärkere Lokalisierung führt zum schnellerem Zerfließen!
\end{minipage}
   #+END_EXPORT
** Allgemeine Ausbreitung eines Wellenpakets
   \[ψ(x, t) = ∫_{-∞}^∞ \tilde ψ(k) e^{i(k x - ω(k) t)} \d k\]
   $ω(k)$: Dispersionsrelation \\
   Wenn $\tilde ψ(k)$ im \(k\)-Raum (Impuls Raum) um $k_0$ konzentriert ist, kann
   die Dispersionsrelation $ω(k)$ durch eine Taylor Reihe genährert werden.
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
  \draw[->] (-5, 0) -- ++(10, 0) node[right] {$k$};
  \draw[->] (-5, 0) -- ++(0, 7) node[left] {$ω$};
  \draw (-5.1, 5) node[left] {$ω_0$} -- ++(0.2, 0);
  \draw[red] (0, -.1) node[below] {$k_0$} -- ++(0, 0.2);
  \draw[samples=100,smooth,red,variable=\x] plot ({\x},{4*exp(-\x*\x)});
  \draw[black,variable=\x,smooth,samples=100] plot ({\x},{0.02*\x*\x*\x - 0.05*\x*\x + 0.2*\x + 5});
  \draw[variable=\x,smooth,samples=100,orange] plot ({\x},{0.2*\x + 5});
  \draw[variable=\x,smooth,samples=100,blue] plot ({\x},{-0.05*\x*\x + 5});
  \draw[variable=\x,smooth,samples=100,green] plot ({\x},{0.02*\x*\x*\x + 5});
%  \foreach \color/\name/\x\ in {red/$\abs*{\tilde ψ(k)}$/0, black/$ω(k)$/1, orange/$\propto k$/2, blue/$\propto k^2$/3, green/$\propto k^2$/4}
%     \filldraw[\color] (4, 1+0.5*\x) -- ++(0.4, 0) node[right] {\name};
  \foreach \c/\n\ [count=\i] in {red/$\abs*{\tilde ψ(k)}$, black/$ω(k)$, orange/$\propto k$, blue/$\propto k^2$, green/$\propto k^3$}
      \draw[\c] (4, .5*\i) -- ++(.5, 0) node[right,black] {\n};
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Taylor Reihe für $ω(k)$:
   \begin{align*}
   ω(k) &= ω(k) \big|_{k_0} + \pp{ω}{k}\big|_{k_0}(k - k_0) + \frac{\partial^2 ω}{\partial k^2}\big|_{k_0} \frac{(k - k_0)^2}{2} + \dots \\
   ⇒ ψ(x, t) &= ∫_{-∞}^∞ \tilde ψ(k) e^{-i (ω_0 + ω_0'(k - k_0) + ω_0'' \frac{(k - k_0)^2}{2})t - k x} \d k \\
   \intertext{Definiere $κ= k - k_0 ⇒ k = κ + k_0$, damit}
   ψ(x, t) &= \underbrace{e^{i(k_0 x - ω_0 t)}}_{\mathclap{\text{de Broglie Welle}}} \underbrace{∫_{-∞}^∞ \tilde ψ(κ + k_0) e^{-i \underbrace{(ω_0' t - x)}_{x' = v_g t - x} κ + \frac{ω_0''}{2}κ^2 t} \d κ}_{\mathclap{\text{Einhüllende}}} \\
   \intertext{Einhüllende bewegt sich mit}
   v_g &= \pp{ω}{k} \big|_{k_0} \\
   \end{align*}
   $ω_0'' = 0$:
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
\draw[->] (-4,0) -- ++(8,0) node[right] {$x$};
\draw[->] (-4,0) -- ++(0,3) node[left] {$\Re ψ$};
\draw[variable=\x,smooth,samples=100,black!30!green,domain=-4:4] plot ({\x},{3*exp(-0.4*\x*\x)});
\draw[variable=\x,smooth,samples=500,red,domain=-4:4] plot ({\x},{3*exp(-0.4*\x*\x)*sin(400*\x)});
\draw[->,black!30!green] (0,3) |- (2,3.5) node[right] {$v_g$};
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   $ω_0'' \neq 0 ⇒$ Phase $\propto κ^2 t ⇒$ zerfließen. Interpretation:
   \[ω \sim ω_0 + \frac{ω''}{2} k^2 = ω_0 + \frac{\hbar}{2m^{\ast}} k^2\]
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{minipage}{.45\textwidth}
  \begin{center}
    \begin{tikzpicture}
      \draw[->] (-3.5,0) -- ++(7,0) node[right] {$k$};
      \draw[->] (-3.5,0) -- ++(0,4) node[left] {$ω$};
      \draw[black,variable=\x,samples=100,smooth,domain=-3.5:3.5]
      plot ({\x},{3*(.5*\x*\x + .5)/(2*(\x - 1)*\x + 1) + .1*(\x + 5) + 0.002*(\x - .5)*(\x - .5)*(\x - .5)*(\x - .5) - .7});
      \draw[red,dashed,variable=\x,samples=100,smooth,domain=-3:-0.5]
      plot ({\x},{.1738*(\x + 1.75)*(\x + 1.75) + .25});
      \draw[red,dashed,variable=\x,samples=100,smooth,domain=.3:.94]
      plot ({\x},{-15.8*(\x - 0.62)*(\x - 0.62) + 3.79});
      \draw [red,<-,every text node part/.style={align=center}] (.4, 2.2) -- ++(.5,-1) node[below] {negative \\ $\text{Masse}^{\ast}\ m_2^{\ast}$};
      \draw [red,<-,every text node part/.style={align=center}] (-2.9, 0.6) -- ++(.5,+1) node[above] {positive \\ $\text{Masse}^{\ast}\ m_1^{\ast}$};
    \end{tikzpicture}
  \end{center}
\end{minipage}\hfill
\begin{minipage}{.45\textwidth}
  Effektive Masse $m^{\ast}$ ist invers proportional zur Krümmung
  der Dispersionsrelation $ω(k)$. \\ {\color{red}$\abs*{m_1^{\ast}} > \abs*{m_2^{\ast}}$}
\end{minipage}
\catcode`(=\active
\catcode`)=\active
#+end_export
   Gauss'sches Wellenpaket:
   \[\tilde ψ(k) \sim e^{-\frac{a^2}{4}k^2}\]
   $⇒ω''$ Term führt zum zerfließen des Pakets $⇒$ Gauss bleibt Gauss. Hähere Ableitungen von $ω(k)$
   führen zur Verzerrung des Grauss'schen Wellenpakets.
** Beugung von Materiewellen
   Doppelspalt \(\to N\)-Spalten $=$ Gitter. (vergleiche Abschnitt 2.3 Fourier)
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
\begin{tikzpicture}
  \draw[->] (-5,0) -- ++(1,0) node[above] {$x$};
  \draw[->] (-5,0) -- ++(0,-1) node[left] {$z$};
  \draw (-5, -2) node[left] {$z = 0$} -- (-4.25,-2);
  \foreach \x in {1,...,6}
    \draw[very thick] (1.5*\x - 5.5, -2) -- ++(1,0);
  \draw[->] (-5,-4) -- ++(10,0) node[below] {$x$};
  \draw[->] (-5,-4) -- ++(0,1) node[left] {$ψ(x)$};
  \foreach \x in {1,...,5}
    \draw[blue] (1.5*\x - 5, -4) -- ++(.5, 0) -- ++(0,1) -- ++(.5,0) -- ++(0,-1) -- ++(.5,0);
  \draw[->] (-2.5,-.5) -- ++(0,-1) node[midway,right] {$k_z$};
  \foreach \x in {1,2,3}
    \draw (-3.5,-1 -.25*\x) -- ++(2, 0);
  \draw[|-|] (1.75, -1.75) -- ++(1.5, 0) node[midway, above] {$d$};
  \draw[|-|] (1.5, -2.25) -- ++(.5, 0) node[midway, below] {$B$};
  \node at (4, -2.25) {Gitter};
  \node[right] at (-2, -.5) {Doppelspalt $\to$ \(N\)-Spalten = Gitter};
\end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
   \begin{align*}
   \intertext{$ψ(x)$ dirket nach dem Gitter}
   ψ(x, z = 0) &= N \sum_{n = -∞}^{∞} g_n e^{in G x} \qquad G = \frac{2π}{d} \\
   \text{mit } g_n &= \frac{1}{nπ} \sin(n \frac{πB}{d}) \\
   \end{align*}
   Wie breitet sich $ψ(x, k, t)$ aus?
   1. Energieerhaltung: $ω_{dB}$ ändert sich nicht
   2. Impuls ändert die Richtung weil nach dem Gitter gilt:
	  \begin{align*}
      ψ(x, z, t) &= N \sum_{n = -∞}^{∞} g_n \underbrace{e^{i n G x} e^{i(k'_z z - ω t)}}_{\v k_n = \cvec{n G; k'_z}} \\
      &= N \sum_{n = -∞}^{∞} g_n e^{i(\v k_n \v x - ω t)} \\
      \end{align*}
      $k_z'$ folgt aus der Energieerhaltung
	  \[n^2 G^2 + \underarrow[k^{\prime 2}_z]{nach dem Gitter} = \overarrow[k_z^2]{vor dem Gitter}\]
   Wahrscheinlichkeit sich in Richtung $\v k_1 = \cvec{G; k_z'}$ auszubreiten /	gebeugt	zu werden:
   \[P(k_x = G) = \abs{N}^2 g_1^{\ast} g_1\]
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{minipage}{.35\textwidth}
  \begin{center}
    \begin{tikzpicture}
      \draw[->] (0,0) -- ++(0,-1.5) node[midway,right,every text node part/.style={align=left}] {einfallender \\ Wellenvektor $\v k = \cvec{0; k}$};
      \draw[->] (0,-1.7) -- ++(-90:1.5);
      \draw[->] (0,-1.7) -- ++(-60:1.5);
      \draw[->] (0,-1.7) -- ++(-120:1.5);
      \draw [domain=-60:-90,shift={(0,-1.7)}] plot ({cos(\x)}, {sin(\x)}) node[above,xshift=6pt,font=\small] {$α$};
      \draw[red,->] (0, {-1.7-1.5*sin(60)}) -- ++({1.5*cos(60)},0) node[below,midway] {$G$};
      \draw[decoration={brace,mirror,raise=2pt},decorate] (0,-1.7) -- node[left,yshift=5pt,xshift=-2pt] {$k$} ++(-120:1.5);
      \draw[red,decoration={brace,raise=2pt},decorate]  ({1.5*cos(60)},-1.7) -- node[right,xshift=2pt] {$k_z'$} ++(0,{-1.5*sin(60)});
      \draw [dashed,domain=-40:-140,shift={(0,-1.7)}] plot ({1.5*cos(\x)}, {1.5*sin(\x)});
      \draw[<-,bend left] (-1.1,-2.75) to [out=-80,in=-230] ++(1,-1) node[below,every text node part/.style={align=center}] {In\\Festkörperphysik:\\Ewald Kugel};
    \end{tikzpicture}
  \end{center}
\end{minipage}
\hfill%
\begin{minipage}{.55\textwidth}
  $\abs{\v k}$ ist erhalten aber die Richtung ändert sich durch Gittervektor $\v G$. \\
  Nur diskrete Impulse weil periodische Struktur im Raum.
\end{minipage}
\catcode`(=\active
\catcode`)=\active
#+end_export
   Für $\frac{G}{k} \ll 1$:
   Ergebnis wie in Beugung von elektromagnetischen Wellen an periodischen Strukturen.
   \[α = \frac{G}{k} = \frac{2π}{d} \frac{λ_{dB}}{2π} = \frac{λ_{dB}}{d}\]
*** Elektronen
	Beobachtung: Davisson & Germer (1927) $e^{-}$ Strahl mit $\SI{75}{\electronvolt}, λ_{dB} = \SI{1.4e-10}{\meter}$
	fällt auf NI-Kristall.
	#+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \draw[->,decorate,decoration={snake,amplitude=.4mm,segment length=2mm,post length=1mm}] node[left] {$e^{-}$} (0,0) -- ++(2,0);
    \draw[->] (2,-.3) -- ++(210:1.5);
    \draw [domain=180:212.5,shift={(2.4,0)}] plot ({1.5*cos(\x)}, {1.5*sin(\x)});
    \node at (1.5,-.3) {$α$};
    \begin{scope}[xshift=10pt,yshift=-5pt]
    \foreach \x in {1,...,5}
      \foreach \y in {1,...,5}
        \filldraw (.5*\x + 1.5, -.5*\y + 1) circle (1pt);
    \draw[|-|] (4.25,.5) -- ++(0,-.5) node[midway,right] {$d = \SI{3.52e-10}{\meter}$};
    \end{scope}
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
	\[⇒ α = \frac{λ_{dB}}{d} = 0.4 \estimates \sim \frac{\SI{40}{\centi\meter}}{\SI{1}{meter}} \sim \SI{23}{\degree}\]
	Die	Beugungswinkel sind vergleichbar zu Röntgenstrahlen, aber die Eindringtiefe für $e^{-}$
	ist geringer (Coulomb WW) $⇒$ werden heute standardmäßig eingesetzt um bei Molekularstrahl Epitaxie
	kristallines Wachsen nachzuweisen.
	#+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \draw (-3,0) -- ++(6,0);
    \foreach \x in {1,...,10}
       \draw ({(1cm/3pt)*\x - 50pt}, 3pt) circle (3pt);
    \foreach \x in {1,...,9}
       \draw ({(1cm/3pt)*\x + 4pt - 50pt}, 9pt) circle (3pt);
    \draw[->] (-4,2) -- ++(3,-1.5) node[midway,below left] {$e^{-}$-Strahl};
    \foreach \x/\y\ in {0/3, .5/2.5, -.5/2.5, 0/2} {
       \draw (\x, \y) circle (3pt);
       \draw[->] (\x, {\y - .1}) -- ++(0, -.3);
    }
    \draw[->] (0,.5) -- ++(10:3);
    \draw[->] (0,.5) -- ++(20:3);
    \draw[->] (0,.5) -- ++(30:3);
    \draw[line width=2] (3.2, 3) -- ++(0,-2.5) node[above right,every text node part/.style={align=left}] {Beugung \\ wird auf\\ Phosphor-\\schirm\\beobachtet};
  \end{tikzpicture}\\
\end{center}
Kristallines Wachstum \\
Klare Beugungsstruktur:\
\begin{tikzpicture}[anchor=base,baseline]
  \filldraw (0,0) circle (2pt);
  \filldraw (-.5,0) circle (2pt);
  \filldraw (.5,0) circle (2pt);
  \filldraw (0,.5) circle (2pt);
  \filldraw (0,-.5) circle (2pt);
  \filldraw (-.3,-.3) circle (1pt);
  \filldraw (.3,-.3) circle (1pt);
  \filldraw (-.3,.3) circle (1pt);
  \filldraw (.3,.3) circle (1pt);
\end{tikzpicture}\\
Amorphe Strukturen\\
Diffuse Beugungsstruktur:
\begin{tikzpicture}[anchor=base,baseline]
\foreach \x in {1,...,20}{
   \draw[decorate, decoration={random steps,segment length=1pt,amplitude=3pt}] (rand*.5,rand*.5) -- (rand*.5,rand*.5);
}
\end{tikzpicture}
\catcode`(=\active
\catcode`)=\active
#+end_export
*** Moleküle an einem Transmissionsgitter
	Beispiel: $Na_2$ Pritchard Group am MIT.
	#+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \draw[->] (0,0) -- ++(2,0) node[below,midway] {$\SI{800}{\meter\per\second}$} node[above,midway] {$Na$ Ofen};
    \draw (2.5, 1) -- ++(0,-0.75);
    \draw (2.5, -1) -- ++(0,0.75);
    \draw (5.5, 1) -- ++(0,-0.75);
    \draw (5.5, -1) -- ++(0,0.75);
    \foreach \y in {1,...,6}
      \draw (6,.5*\y - 1.875) -- ++(0,.25);
    \draw[<-] (6.2, -1) -- ++(1,-.5) node[right,every text node part/.style={align=left}] {Nanometer\\Gitter\\$d = \SI{160}{\nano\meter}$};
    \draw[->] (6.2, 0.1) -- ++(20:2);
    \draw[->] (6.2, 0) -- ++(0:2) node[right] {Beugung};
    \draw[->] (6.2, -0.1) -- ++(-20:2);
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
	\begin{align*}
	Na: \qquad λ_{dB} &= \SI{20}{\pico\meter} ⇒ θ = \frac{λ_{dB}}{d} \sim \SI{1.25e-4}{} \estimates \SI{125}{\micro\meter\per\meter} \\
	Na_2: \qquad λ_{dB} &= \SI{10}{\pico\meter} ⇒ θ = \frac{1}{2}\SI{125}{\micro\meter\per\meter}
	\end{align*}
*** Nachweis von sehr "fragilen" Molekülen
	Beispiel: $He_2$ \\
	Übliche Methode:
	#+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
\begin{tikzpicture}
\wigglecircle{1}{.25}{20}{0}{0}
\draw[<-] (-.8,.8) -- ++(-1,1) node[above right,midway] {$e^{-}$};
\draw[<-] (.9,.9) -- ++(.5,.5) node[above] {Molekül};
\draw[->] (0,0) -- ++(2,0);
\node at (3,0) {\Huge$\Rightarrow$};
\wigglecircle{1}{.25}{20}{5}{0}
\node at (5,0) {\Huge$+$};
\filldraw (6.5,1.5) circle (.5pt);
\draw (6.5,1.5) circle (5pt) node[above right] {$\v B$};
\draw[->] (6.5, 0) to [in=130,out=0] ++(2,-1);
\draw[decoration={ticks},decorate] (8,-2) -- ++(2,2);
\draw (8,-2) -- ++(2,2) node[below right,every text node part/.style={align=center},midway] {Proportional\\zur Masse};
\draw[decoration={mirror,brace},decorate] (6.5,-2.2) -- node[midway,below] {Massenspektrometer} ++(2.5,0);
%\draw[<-] ()
\end{tikzpicture}
\end{center}
\begin{tikzpicture}
\draw[->] (-.8,.8) -- ++(.5,-.5) node[above right,midway] {$e^{-}$} node[below right] {$He_2$};
\draw[->] (.7,0) -- ++(.7,0);
\node[align=left,right] at (1.5, .3) {$He + He + e^{-}$};
\node[align=left,right] at (1.5, -.3) {$He + He^{+} + 2e^{-}$};
\node at (5, 0) {\Huge$\Rightarrow$};
\node[align=left,right] at (5.7, .15) {misst immer};
\node[align=left,right] at (5.7, -.15) {nur $He$ Masse};
\end{tikzpicture}\\
\catcode`(=\active
\catcode`)=\active
#+end_export
	Verwendung von nanometer Transmissionsgitter $\to$ Analyse der Beugungswinkel\\
	#+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{minipage}{.45\textwidth}
\begin{center}
  \begin{tikzpicture}
    \draw[->] (0,0) -- ++(1,0) node[above,midway,every text node part/.style={align=left}] {{\color{blue}$He$}\\{\color{red}$He_2$}};
    \foreach \y in {1,...,6}
      \draw (1.5,.5*\y - 1.875) -- ++(0,.25);
    \draw[->,red] (2, 0) -- ++(-10:1.5);
    \draw[->,red] (2, 0) -- ++(10:1.5);
    \draw[->,red] (2, 0) -- ++(0:1.5);
    \draw[->,blue] (2, 0) -- ++(-20:1.5);
    \draw[->,blue] (2, 0) -- ++(20:1.5);
    \draw[<->,blue] (2,0) ++(20:1.7) to [out=-70,in=90] (3.7,0);
    \node[blue] at (3.9,.3) {$α$};
  \end{tikzpicture}
\end{center}
\end{minipage}\hfill
\begin{minipage}{.45\textwidth}
${\color{blue} α_{He}} = 2 × {\color{red}α_{He_2}}$
\end{minipage}
\catcode`(=\active
\catcode`)=\active
#+end_export
*** Beugung von Makro-Molekülen
	Beispile: $C_{60}, C_{60}F_{40}$
	#+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \node[rectangle,draw,every text node part/.style={align=left},right] at (0,0) {Ofen\\ $\SI{900}{\kelvin}$};
    \node[white] at (1.2,0) {$\bullet$};
    \draw (2.5, 1) -- ++(0,-0.75);
    \draw (2.5, -1) -- ++(0,0.75);
    \draw (5.5, 1) -- ++(0,-0.75);
    \draw (5.5, -1) -- ++(0,0.75);
    \node at (4, 1.2) {Kollimation};
    \foreach \y in {1,...,6}
      \draw (6,.5*\y - 1.875) -- ++(0,.25);
    \draw[<-] (6.2, -1) -- ++(1,-.5) node[right,every text node part/.style={align=left}] {Beugungsgitter\\$d \sim \SI{100}{\nano\meter}$};
    \draw[->] (6.2, 0.1) -- ++(20:2);
    \draw[->] (6.2, 0) -- ++(00:2) node[above right] {$α=\frac{λ_{dB}}{d} = \SI{30e-6}{}$};
    \draw[->] (6.2, -0.1) -- ++(-20:2);
  \end{tikzpicture}
  \begin{align*}
    m &= 60·^{12}C \\
    λ_{dB} &\sim \SI{3}{\pico\meter} \\
    \SI{30e-6}{} &\estimates \frac{\SI{30}{\micro\meter}}{\si{\meter}} \sim \frac{\SI{3}{\centi\meter}}{\si{\kilo\meter}}
  \end{align*}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
	Fundamentale Frage: Gibt es eine kritische Größe, ab der Quantenmechanik klassisch wird?
** Atom Interferometer
   1. Atom Interferometer - Doppelspalt aus dünnen Goldfolien \\
	  Gruppe-Mlynek: 1991 Konstanz
   2. Atom Interferometer - 3 Gitter Aufbau \\
	  Gruppe Pritchard: 1991 MIT/Boston
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \foreach \y in {1,...,6}
      \draw (2,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (4,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (6,.5*\y - 1.875) -- ++(0,.25);

    \draw[->] (0,.1) -- ++(1.5,0);
    \foreach \a in {-20,0,20}
      \draw[->] (2.1, .1) -- ++(\a:1.2);

    \foreach \y in {-1,0,1}
      \foreach \a in {-20,0,20}
        \draw[->] (4.1, \y+.1) -- ++(\a:1.2);
    \draw[green] (0,0) -- ++(2,0) -- ++(2,1) -- ++(4,0);
    \draw[green] (0,0) -- ++(4,0) -- ++(4,2);
    \filldraw (8.2,1) circle (3pt) node[right] {Atomdetektor};
    \node[green,draw,circle,inner sep=1pt] at (5.5, .5) {$1$};
    \node[green,draw,circle,inner sep=1pt] at (5.5, 1.25) {$2$};
    \draw[->] (3, -2.2) -- (2,-1.4);
    \draw[->] (3, -2.2) node[below] {Nanometer Gitter} -- (4,-1.4);
    \draw[->] (3, -2.2) -- (6,-1.4);
    \draw[->,green] (2.3,1) node[above,yshift=11pt,xshift=-5pt,every text node part/.style={align=left},right] {Beugungs-\\effizienz} -- ++(-.1,-.4) node[below] {$η$};
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
   Die Wahrscheinlichkeit das Atom zu detektieren ist $\abs{ψ}^2$ mit
   \begin{align*}
   ψ &= ψ_{1} + ψ_{2} = η^2 e^{ik l_1} + η^2 e^{ikl_2} \\
   &= η^2 \underarrow[e^{ik l_2}]{globale Phase}(1 + e^{ik(l_2 - l_1)}) \\
   Δl &= l_2 - l_1 = 0 ⇒ \abs{ψ}^2 = 4η^4
   \end{align*}
   Beobachtung des Interfernzmusters $\abs{ψ}^2 = 0$?\\
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{minipage}{.6\textwidth}
\begin{center}
  \begin{tikzpicture}
    \foreach \y in {1,...,6}
      \draw (2,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (4,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (6,.5*\y - 1.875) -- ++(0,.25);
    \draw[->] (0,0) -- ++(2,0) -- ++(2,1) -- ++(4,0) node[right] {$\abs{ψ}^2$};
    \draw[->] (0,0) -- ++(4,0) -- ++(4,2);
    \draw[->] (2,-1.4) -- ++(+.5,-.5) node[below] {Gitterperiode $d$};
    \draw[<->] (6.2, -1) -- ++(0,-.5) node[midway,right] {Verschiebe Gitter um $Δx$};
  \end{tikzpicture}
\end{center}
\end{minipage}
\begin{minipage}{.35\textwidth}
\begin{center}
  \begin{tikzpicture}
    \draw[->] (0,0) -- ++(5, 0) node[below right] {$Δx$};
    \draw[->] (0,0) -- ++(0, 3) node[above left] {$\abs{ψ}^2$};
    \draw[samples=100,smooth,domain=0:5] plot ({\x},{1-cos(360*\x)});
    \draw (.5,.1) -- ++(0, -.2) node[below] {$0$};
    \draw (1,.1) -- ++(0, -.2) node[below] {};
    \draw (1.5,.1) -- ++(0, -.2) node[below] {$d$};
    \draw (2,.1) -- ++(0, -.2) node[below] {};
    \draw (2.5,.1) -- ++(0, -.2) node[below] {$2d$};
  \end{tikzpicture}
\end{center}
\end{minipage}\\
\catcode`(=\active
\catcode`)=\active
#+end_export
   Warum:
   #+BEGIN_EXPORT latex
\catcode`(=12
\catcode`)=12
\begin{align*}
ψ(x) &= \sum_{n = -∞}^{∞} g_n e^{inGx} \\
x ↦ x + Δ x \qquad &= \sum_{n = -∞}^{∞} \underbrace{g_n e^{inG Δ x}}_{g_n e^{i2π n \frac{Δ x}{d}}} e^{inG x} \\
Δ x = d ⇒ e^{i 2π n} &= 1 ⇒ \text{keine Änderung} \\
\intertext{Letztes Gitter:}
&\begin{tikzpicture}
\draw[->] (0,0) -- ++(1,0) node[midway,draw,circle,inner sep=.5pt,above,yshift=2pt] {2};
\draw[green,->] (0,-1) -- ++(1,.8) node[midway,draw,circle,inner sep=.5pt,below,yshift=-2pt,xshift=2pt] {1};
\draw[->] (1.1, 0) -- ++(1,0) node[right] {$g_0$};
\draw[green,->] (1.1, -.2) --++(1,0) node[right] {$g_1 e^{i \frac{2π Δ x}{d}}$};
\end{tikzpicture} \\
\catcode`(=\active
\catcode`)=\active
⇒ ψ &= η^2 e^{i k l_1} e^{i \frac{2π Δ x}{d}} + η^2 e^{ik l_2} \\
\intertext{mit $l_1 = l_2 = l$} \\
ψ &= η^2 e^{i k l} (e^{i \frac{2π Δ x}{d}} + 1) \\
\abs{ψ}^2 &= η^4 ((e^{-i \frac{2π Δ x}{d}} + 1)(e^{i \frac{2π Δ x}{d}} + 1)) \\
&= η^4 \{2 + \underbrace{e^{-i \frac{2π Δ x}{d}} + e^{i \frac{2π Δ x}{d}}}_{= 2 \cos \frac{2π Δ x}{d}}\} \\
⇒ \abs{ψ}^2 &\propto 1 + \cos(\frac{2π}{d} Δ x)
\end{align*}
   #+END_EXPORT
   *Messen von Potentialen* \\
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \foreach \y in {1,...,6}
      \draw (2,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (4,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (6,.5*\y - 1.875) -- ++(0,.25);
    \node[draw,circle,inner sep=1pt] at (5.7, .5) {$1$};
    \node[draw,circle,inner sep=1pt] at (5.7, 1.25) {$2$};
    \draw[->] (0,0) -- ++(2,0) -- ++(2,1) -- ++(4,0);
    \draw[->] (0,0) -- ++(4,0) -- ++(4,2);
    \draw[green,pattern=north west lines, pattern color=green] (4.1,0.8) rectangle (5.4,1.2) node[above,midway,yshift=5pt] {$V$};
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
   Potential am Weg 2:
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \foreach \x/\xl/\yl\ in {3/Weg 2/$V$, 2/Weg 2/{Gesamt-\\energie}, 1/Weg 2/{Kintetische\\Energie\\$\frac{p^2}{2m}$}}{
      \draw[->] (0, 4*\x) -- ++(7,0) node[below,right] {\xl};
      \draw[->,every text node part/.style={align=center}] (0, 4*\x) -- ++(0,3) node[above,left] {\yl};
    }
    \draw[dashed] (5,4) -- ++(0,8);
    \draw[dashed] (3,4) -- ++(0,8);
    \draw[red] (0, 12) -- ++(3,0) -- ++(0,1) -- ++(2,0) -- ++(0,-1) -- ++(2,0);
    \draw (0,9.5) -- ++(7,0) node[right,every text node part/.style={align=center}] {Konstant \\ Zeit-Unabängig\\Energieerhaltung};
    \draw (0, 6) -- ++(3,0) -- ++(0,-1) -- ++(2,0) -- ++(0,+1) -- ++(2,0);
    \draw[black,pattern=north west lines, pattern color=black] (0,3.8) rectangle (3,4) node[above,midway,yshift=5pt,circle,draw,inner sep=1pt] {1};
    \draw[black,pattern=north west lines, pattern color=black] (5,3.8) rectangle (7,4) node[above,midway,yshift=5pt,circle,draw,inner sep=1pt] {3};
    \node[yshift=5pt,circle,draw,inner sep=1pt] at (4,4.09) {2};
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
   \begin{align*}
   1+3: &\qquad \frac{\hbar^2 k_{dB}^2}{2m} \\
   2: &\qquad \frac{p'^2}{2m} + V = \frac{p^2}{2m} \\
    &\qquad \frac{\hbar^2 k^{\prime 2}}{2m} + V = \frac{\hbar^2 k^2}{2m} \\
   \end{align*}
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \foreach \x/\xl/\yl\ in {1/$x$/$V$, 0/$x$/$\Re\{ψ\}$}{
      \draw[->] (0, 4*\x) -- ++(7,0) node[below,right] {\xl};
      \draw[->,every text node part/.style={align=center}] (0, 4*\x) -- ++(0,3) node[above,left] {\yl};
    }
    \draw (0,4) node[left] {$0$} -- ++(.5,0) -- ++(2,1) -- ++(2,0) -- ++(2,-1) -- ++(.5,0);
    \draw[samples=100,domain=-.5:0,smooth,shift={(.5,1.5)}] plot ({\x},{sin(720*\x)});
    \draw[samples=300,domain=0:2,smooth,shift={(.5,1.5)}] plot ({\x},{sin(-(600/4)*\x*\x + 720*\x)});
    \draw[samples=100,domain=2.5:4.5,smooth,shift={(0,1.5)}] plot ({\x},{-sin(120*\x)});
    \draw[samples=300,domain=0:2,smooth,shift={(4.5,1.5)}] plot ({\x},{sin(+(600/4)*\x*\x + 120*\x)});
    \draw (-.1,1.5) node[left] {$0$} -- ++(.2,0);
    \draw[dashed] (0.5,4) -- ++(0,-4);
    \draw[dashed] (2.5,5) -- ++(0,-5);
    \draw[dashed] (4.5,5) -- ++(0,-5);
    \draw[dashed] (6.5,4) -- ++(0,-4);
    \draw[every text node part/.style={align=center},decoration={mirror,brace},decorate] (0,-.1) -- node[midway,below] {Freies\\Teilchen} ++(.5,0);
    \draw[every text node part/.style={align=center},decoration={mirror,brace},decorate] (.5,-.1) -- node[midway,below] {$v$\\wird\\kleiner\\$⇒ λ_{dB} \uparrow$} ++(2,0);
    \draw[every text node part/.style={align=center},decoration={mirror,brace},decorate] (2.5,-.1) -- node[midway,below] {$v=\const$\\$λ_{dB} = \const$} ++(2,0);
    \draw[every text node part/.style={align=center},decoration={mirror,brace},decorate] (4.5,-.1) -- node[midway,below] {$v$\\wird\\größer\\$⇒ λ_{dB} \downarrow$} ++(2,0);
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
   Die Kraft verändert die Geschwindigkeit $⇒$ die de Broglie Wellenlänge ändert sich entsprechend
   $⇒ ϕ = k_{dB}^v · x$ die Phasenakkumulation ändert sich im Potential $⇒$ Phasenshift kann
   gemessen werden. Die de Broglie-Wellenlänge ändert sich $⇒$ sie wird im Bereich 2 länger, weil Atom langsamer wird.
   Einfach Beschreibung durch Einführung eines "Brechungs Index"
   \[n = \frac{k_{\text{Medium}}}{k_{\text{Vakuum}}} = \frac{k'_{\text{Potential}}}{k_{\text{frei}}} = \frac{λ_{dB}^{\text{frei}}}{λ_{dB}^{\text{Potential}}}\]
   Mit $2$:
   \begin{align*}
   k^{\prime 2} &= k^2 - \frac{2mV}{\hbar^2} \\
   k' &= k \sqrt{1 - \frac{2m}{\hbar^2 k^2} V} = k \underbrace{\sqrt{1 - \frac{V}{E_{\text{ges}}}}}_{n_{dB}} \\
   \intertext{Für $V \ll E_{\text{ges}}$}
   n_{dB} &\approx 1 - \frac{V}{2E_{\text{ges}}}
   \end{align*}
   Im Atom Interferometer: Empfindlichkeit abschätzen $\to$ welche Potentialhöhe
   führt zu einer Phasenverschiebung von $π \estimates$ Maxima des Interferenzmusters
   verschieben sich um eine halbe Periode.
   \begin{align*}
   Δ ϕ &= -π = (n - 1) k_{dB} · L = - \frac{V}{2E} k_{dB} L \\
   V &= \frac{\hbar^2 k_{dB}}{m} \frac{π}{L} \\
   \intertext{$m = Na, λ_{dB} \sim \SI{20}{\pico\meter}, L = \SI{1}{\centi\meter}$}
   V &= \SI{3e-29}{\joule} \estimates \SI{0.18}{\nano\electronvolt}
   \end{align*}
   Anwendungen: Messung der Erdbeschleunigung.
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \foreach \y in {1,...,6}
      \draw (2,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (4,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (6,.5*\y - 1.875) -- ++(0,.25);
    \draw[->] (0,0) -- ++(2,0) -- ++(2,1) -- ++(4,0);
    \draw[->] (0,0) -- ++(4,0) -- ++(4,2);
    \node[below] at (3,0) {$m g h_1$};
    \node[above] at (5,1) {$m g h_2$};
    \draw[->] (1,1.2) node[above] {$\v g$} -- ++(0,-1);
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
   $⇒$ Potentialdifferenz, für $m: Cs, Δ h = \SI{1}{\meter}$
   \[m g Δ h \sim \SI{13}{\micro\electronvolt}\]
   Gravitationsmessung mit Atomeren Fountain $⇒ g \pm 10^{-9} g$. Erste Messung mit Neutronen.
** Zusammenfassung
   Historische Herleitung von de Brogliewellen = $3×$ Einstein \\
   De Brocliewelle: Quantenmechanischer Zustand mit scharfen Impuls \\
   Dispersionsrelation für massive Teilchen \\
   Superposition von ebenen Wellen können physikalische (normierbare) Zustände beschreiben - $\abs{ψ(x)}^2 \d x$ ist die Wahlscheinlichkeit ein Teilchen im Intervall $[x,x + \d x]$ zu detektieren. \\
   Zerlegung einer allgemeinen Einteilchenwellenfunktion in de Broglie Wellen erlaubt Vorhersage der Dynamik \\
   Viele Experimente in Quantenmechanik mit einzelnen Teilchen, können mit diesen minimalen	Vorraussetzungen verstanden werden
* Allgemeine Quantenmechanik
** Quantenmechanischer Zustand und dessen Darstellung
   Besher nur den Fall der Ausbreitung eines massiven Teilchens $\to$ Wellenmechanik. Quantenmechanik ist allgemeiner!
   \begin{ibox}{}
   Das System (zum Beispiel Teilchen, drehendes Molekül, $\dots$) wird beschrieben durch einen Quantenmechanischen Zustand $\ket{ψ}$. Er beinhaltet alles,
   was wir vom System wissen können.
   \end{ibox}
   $\ket{ψ}$ nennt man "ket", eingeführt von Dirac. \\
   $\ket{ψ}^{\ast} = \bra{ψ}$ nennt man "bra". \\
   Skalarprodukt: $\braket{ψ|ψ}$ \\
#+BEGIN_EXPORT latex
\catcode`(=12
\catcode`)=12
   \begin{minipage}[t]{.45\textwidth}
   2D Raum:\\
   \begin{center}
   \begin{tikzpicture}
   \draw (-2,0) -- ++(5,0) -- ++(2,3) -- ++(-5,0) -- cycle;
   \draw[->] (.5,1) -- ++(1.5,0) node[below right] {$x$};
   \draw[->] (.5,1) -- ++(1,1.5) node[below right] {$y$};
   \draw[->] (.5,1) -- ++(1.5,.5) node[above, midway] {$r$};
   \draw[smooth,samples=20,domain=90:72,shift={(.5,1)}] plot ({sin(\x)},{cos(\x)}) node[right,yshift=-3pt] {$φ$};
   \filldraw[->] (.5,1) ++(1.5,.5) circle (1pt);
   \draw (2.1,1.6) -- ++(1,1.5) node[above] {Punkt $p$};
   \end{tikzpicture}
   \end{center}
   Darstellung des Punktes in einem Koordinatensystem durch einen Vektor: \\
   kartesich: $(x,y)$ \\
   polar: $(r, φ)$ \\
   \begin{align*}
   \v P &= x \v e_x + y \v e_y \\
   \intertext{$x, y$: Koordinaten, $\v e_x, \v e_y$: Basisvektoren, alternativ}
   \v P &= r \v e_r + φ + \v e_φ \\
   \end{align*}
   \vfill
   \end{minipage}
   \hfill
   \begin{minipage}[t]{.45\textwidth}
   Quantenmechanik \\
   \begin{center}
   \begin{tikzpicture}
   \wigglecircle{2.5}{.5}{20}{0}{0}
   \draw[->] (-2,2) node[every text node part/.style={align=center},left] {Raum\\aller\\Zustände}  -- ++(1,-1);
   \draw[->] (2,2) node[every text node part/.style={align=center},right] {Zustand\\$\ket{ψ}$}  -- ++(-.9,-.9);
   \filldraw (1,1) circle (1pt) node[right] {$\ket{ψ}$};
   \end{tikzpicture}
   \end{center}
   Darstellung des Zustandes $\ket{ψ}$ in einer Basis. \\
   Bisher: $\ket{\text{Wellenpaket}}$. \\
   Ortsdarstellung: $ψ(x) = \abs{ψ} e^{iϕ}$ \\
   \begin{center}
   \begin{tikzpicture}
     \draw[->] (-2,0) -- ++(4,0) node[below right] {$x$};
     \draw[->] (-2,0) -- ++(0,1.5) node[above left] {$\abs{ψ(x)}$};
     \draw[domain=-2:2,smooth] plot ({\x},{exp(-2*\x*\x)});
     \draw[red,->] (1.5,0) --++(0,1.5) node[above right] {$ϕ(x)$};
     \draw[red] (-2,.5) -- ++(3.6,0) node[right] {$0$};
   \end{tikzpicture}
   \end{center}
   Impulsdarstellung: $\tilde ψ(k) = \abs*{\tilde ψ} e^{iϕ}$ \\
   \begin{center}
   \begin{tikzpicture}
     \draw[->] (-2,0) -- ++(4,0) node[below right] {$\hbar k = p$};
     \draw[->] (-2,0) -- ++(0,1.5) node[above left] {$\abs*{\tilde ψ(k)}$};
     \draw[domain=-2:2,smooth] plot ({\x},{1.5*exp(-3*\x*\x)});
     \draw[red,->] (1.5,0) --++(0,1.5) node[above right] {$\tildeϕ(x)$};
     \draw[red] (-2,.5) -- ++(3.6,0) node[right] {$0$};
   \end{tikzpicture}
   \end{center}
   \vfill
   \end{minipage}\\
   Skalarprodukt\\
   \begin{minipage}{.45\textwidth}
   \begin{align*}
   \angl{\v e_x, \v e_x} &= \v e_x · \v e_x = 1 \tag*{Normiert} \\
   \angl{\v e_x, \v e_y} &= 0 \tag*{Orthogonal} \\
   \angl{\v v, a \v w + b \v x} &= a \angl{\v v, \v w} + b \angl{\v v, \v x} \\
   \intertext{"`nützlich"' um Koordinaten zu extrahieren:}
   \angl{\v e_x, \v P} &= \v e_x · (x \v e_x + y \v e_y) = x
   \end{align*}
   \end{minipage}
   \hfill
   \begin{minipage}{.45\textwidth}
   \begin{align*}
   \braket{φ|ψ} &\underarrow[=]{Ortsdarstellung} ∫ φ^{\ast}(\v x) ψ(\v x) \d^3 x \\
   &\underarrow[=]{Impulsdarstellung} ∫ \tilde φ^{\ast}(\v k) \tilde ψ(\v k) \d^3 k \\
   \intertext{"`nützlich"' um Wahrscheinlichkeitsamplituden zu extrahieren}
   \end{align*}
   \end{minipage}
\catcode`(=\active
\catcode`)=\active
#+END_EXPORT
   #+ATTR_LATEX: :options [1D-Wellenpaket]
   #+begin_ex latex
   Basis: Zustände mit wohldefiniertem Impuls $\hbar k$
   \[\ket{k} \estimates \text{ de Broglie Wellen}\]
   Wellenpaket ist eine Summe (Superposition) von de Broglie Wellen
   \[\ket{\text{Wellenpaket}} = \ket{ψ_{WP}} = ∫_{-∞}^{+∞} \underarrow[\tilde ψ(k)]{Koordinate} \overarrow[\ket{k}]{Basisvektor / Impuls Basis} \d k\]
   $\estimates$ Darstellung von $\ket{ψ_{WP}}$ in Impulsbasis. \\
   Korrdinate / Wahrscheinlichkeits-Amplitude von $\ket{k'} \to$ Impuls $\hbar k'$ zu messen:
   \begin{align*}
   \braket{k'|ψ_{WP}} &= \bra{k'} ∫ \tilde ψ(k) \ket{k} \d k = ∫ \bra{k'} \tilde ψ(k) \ket{k} \d k \\
   &= ∫ \tilde ψ(k) \braket{k'|k} \d k \\
   \braket{k'|k} &= ∫ \frac{1}{\sqrt{2π}} e^{-ik' x} \frac{1}{\sqrt{2π}} e^{ikx} \d x = \frac{1}{2π} ∫ e^{i(k - k')x} \d x = δ(k - k') \\
   \braket{k'|ψ_{WP}} &= ∫ \tilde ψ(k) δ(k - k') \d k = \tilde ψ(k')
   \end{align*}
   #+end_ex

#   \begin{tikzpicture}
#   \wigglecircle{2.5}{.5}{20}{0}{0}
#   \draw[->] (2,2) node[every text node part/.style={align=center},right] {Zustand\\$\ket{ψ}$}  -- ++(-.9,-.9);
#   \filldraw (1,1) circle (1pt);
#   #################### Bloch Kugel an Stelle x
#   \begin{align*}
#   \braket{x | ψ} &= f(x) = e^{i k x} \\
#   (\underarrow[v]{\ket{ψ}}, \underarrow[w]{\ket{φ}}) &↦ \uarrow[\text{Zahl}]{\braket{ψ | φ}} \\
#   \ket{ψ} &= a \ket{\uparrow} + b \ket{\downarrow} \\
#   \intertext{Bloch Kugel:}
#   ###################
#   \ket{ψ_{WP}} &= ∫_{-∞}^{+∞} \tilde ψ(k) \ket{k} \d k \\
#   \intertext{$φ, ψ$ Basiselemente $⇒$ orthonormal:}
#   \braket{ψ|φ} &= 0 \\
#   \braket{φ|φ} &= \braket{ψ|ψ} = 1 \\
#   \end{align*}
   Ortsdarstellung von $\ket{ψ_{WP}}$ \\
   "Ortskoordinate": $\braket{x | ψ_{WP}}$
   \begin{align*}
   \braket{x | ψ_{WP}} &= ψ_{WP}(x) = \bra{x} ∫_{-∞}^{+∞} \tilde ψ(k) \ket{k} \d k = ∫_{-∞}^{+∞} \tilde ψ(k) \underbrace{\braket{x|k}}_{\frac{1}{\sqrt{2π}} e^{i k x}} \d k \\
   &= \frac{1}{\sqrt{2π}} ∫_{-∞}^{+∞} \tilde ψ(k) e^{i k x} \d k \\
   \end{align*}
   Ortswellenfunktion $ψ(x)$ ist eine Darstellung von $\ket{ψ_{WP}} \estimates$ Ortsdarstellung. \medskip
   $\tilde ψ(k)$ ist eine andere Darstellung vom Zustand $\ket{ψ_{WP}} \estimates$ Impulsdarstellung. \medskip
   Das Ergebnis von Rechnungen hängt nicht ab von der Darstellung / Basis ab $\to$ die Berechnung kann in einer
   bestimmten Basis sehr einfach sein. Zum Beispiel: Wellenpaket Dynamik ist in der Impulsdarstellung einfach.
** Observable (beobachtbare Gröhen) und Operatoren
   Observablen können mit Hilfe von Operatoren extrahiert werden.
   #+ATTR_LATEX: :options [Impuls-Operator]
   #+begin_ex latex
   $\hat p$. Das $\hat{}$ symbolisiert Operator $\ket{ψ} ↦ \ket{ψ'}$. \\
   Eingenschaften:
   \[\hat p \underarrow[\ket{k}]{Ortsdarstelung\\de Broglie Welle} = \overarrow[\hbar k]{Zahl\\entspricht Impuls [$\si{\kilogram\meter\per\second}$]} \ket{k}\]
   $\ket{k}$ ist ein /spezieller/ Zustand, weil der Impulsoperator den Zustand nicht "ändert", sondern nur mit einer Zahl multipliziert.
   Daraus Folgt, dass der Zustand $\ket{k}$ einem wohldefiniereten/scharfen Impuls entspricht. $\ket{k}$ nennt man Impuls-Eigenzustand. \medskip
   Erwartungswert: Was erwarten man für den Mittelwert des Impulses?
   \[\overarrow[\bar p]{Mittelwert} = ∫_{-∞}^{+∞} p \underarrow[P(p)]{Probability\\Wahrscheinlichkeit} \d p = \hbar ∫_{-∞}^{+∞} k' \overbrace{\abs{\tilde ψ(k')}^2}^{\mathclap{\text{Für de Broglie Welle: }\tilde ψ(k) = δ(k' - k)}} \d k' = \hbar k\]
   In Dirac Notation
   \[\braket{k | \hat p | k} = \braket{k | \hbar k | k} = \hbar k \underbrace{\braket{k | k}}_{\mathbb{1}}\]
   Erwartungswert / Mittelwert ist $\v p = \hbar k ⇒$ zwei Möglichkeiten:
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
  \foreach \x in {0,8}{
    \draw[->] (\x, 0) -- ++(7, 0) node[below] {\#Experimente};
    \draw[->] (\x, 0) -- ++(0, 3) node[above left] {Impuls};
    \draw (\x, 1.5) -- ++(7,0);
    \foreach \c in {1,...,5}{
      \draw (\x + 0.5*\c, .1) -- ++(0,-.2) node[below] {$\c$};
      }
  }
  \node[left] at (0,1.5) {$\bar p = \braket{\hat p}$};
  \foreach \x in {1,...,13}{
    \node[cross out, draw=black, minimum size=4pt,inner sep=0pt,outer sep=0pt] at (.5*\x, 1.5 + .3*rand) {};
    }
  \foreach \x in {1,...,13}{
    \node[cross out, draw=black, minimum size=4pt,inner sep=0pt,outer sep=0pt] at (.5*\x + 8, 1.5) {};
  }
  \node[red] at (3.5,-1) {Unscharf};
  \node[green] at (11.5,-1) {Scharf};
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Obwohl beide	den gleichen Mittelwert	können diese Messreihen nicht das gleiche System beschreiben. $\to$ Berechne Varianz:
   \[\VAR(p) = \braket{\v p^2} - \braket{\hat p}^2\]
   Für Impulseigenzustand $\ket{k}$ \\
   Notation $\braket{\hat p} := \braket{ψ|\hat p| ψ}$ \\
   Jetzt speziell $\ket{ψ} = \ket{k}$
   \begin{align*}
   \braket{\hat p^2} &= \braket{k | \hat p \hat p | k} = \braket{k | \hat p \hbar | k} = \hbar k \braket{k | \hat p | k} = \hbar^2 k^2 \underbrace{\braket{k | k}}_{\mathbb{1}} \\
   \braket{\hat p}^2 &= (\braket{k | \hat p | k})^2 = (\hbar k)^2 \underbrace{\braket{k | k}}_{\mathbb{1}} \\
   \Aboxed{\VAR(p) &= 0 \qquad \text{für Zustand } \ket{k}}
   \end{align*}
   Alle Messungen ergeben exakt den gleichen Wert; es gibt keine Streuung der Messwerte $⇒$ Impuls scharf / wohldefiniert.
   #+end_ex
   #+begin_remark latex
   Dieser Zustand existiert nur in beliebig guter Nährung!
   #+end_remark
   \medskip Darstellung von Operatoren
   \[\hat p \ket{k} = \hbar k \ket{k}\]
   Darstellung des Impulsoperator in Impulsdarstellung $\estimates$ einfach nur Zahl. \medskip
   Wie sieht das in Ortsdarstellung aus?
   \begin{align*}
   \ket{k} &\mapsto e^{i k x} \ket{x} \\
   \hat p \ket{k} = \hbar k \ket{k} &\mapsto \hbar k (e^{i k x} \ket{x}) = -i \hbar \pp{}{x} (e^{i k x} \ket{x}) \\
   \intertext{Impulsoperator in Ortsdarstellung:}
   \hat p \underarrow[:=]{Ortsdarstellung} - i \hbar \pp{}{x} \\
   \end{align*}
   #+begin_remark latex
   \begin{align*}
   \braket{x | \hat p | ψ} = ∫ \d p \braket{x|p} \braket{p|\hat p | ψ} \\
   &= \frac{1}{\sqrt{2π}} ∫ \d k e^{i k x} \hbar k ψ(k) = -i \hbar \pp{}{x} ψ(x)
   \end{align*}
   #+end_remark
   Impuls Erwartungswert für allgemeine Wellenfunktion $ψ(x)$ für ein Teilchen:
   \begin{align*}
   \overarrow[\bar p_x]{Bezüglich einem $ket{ψ}$} &= \braket{ψ | \hat p_x | ψ}	\underarrow[=]{Ortsdarstellung} ∫_{-∞}^{+∞} ψ^{\ast}(x) (\frac{\hbar}{i} \pp{}{x}) ψ(x) \d x \\
   &= ∫_{-∞}^{+∞} \underbrace{\frac{1}{\sqrt{2π}} ∫ \tilde ψ^{\ast}(k') e^{i k' x} \d k'}_{ψ^{\ast}(x)} \frac{\hbar}{i} \pp{}{x} \underbrace{\frac{1}{\sqrt{2π}} ∫ \tilde ψ(k'') e^{i k'' x} \d k''}_{ψ(x)} \\
   &= ∫_{-∞}^{+∞}\d k' ∫_{-∞}^{+∞} \d k'' \tilde ψ^{\ast}(k') \tilde ψ(k'') \hbar k'' \underbrace{\frac{1}{2π} ∫ e^{i(k'' - k') x} \d x}_{δ(k'' - k')} \\
   &= ∫_{-∞}^{+∞} \d k' \underbrace{\tilde ψ^{\ast}(k') \tilde ψ(k')}_{P(k')} \hbar k' = ∫_{-∞}^{+∞} \d k' (\hbar k') P(k') = \braket{\hbar k}
   \end{align*}
   \medskip
   Gleichzeitige Messung von 2 Observablen $\hat A$ und $\hat B$. Wenn es einen Eigenzustand zu $\hat A$ und $\hat B$ gibt, dann ist das möglich:
   \begin{align*}
   \hat A \ket{a, b} &= a \ket{a, b} \\
   \hat B \ket{a, b} &= b \ket{a, b} \\
   \intertext{aber auch:}
   \hat A \hat B \ket{a, b} &= \hat A b \ket{a, b} = a b \ket{a, b} \\
   \hat B \hat B \ket{a, b} &= \hat B a \ket{a, b} = b a \ket{a, b} \\
   \hat A \hat B - \hat B \hat A \ket{a, b} &= 0 \\
   \intertext{$\hat A \hat B - \hat B \hat A$ Kommutator, Kurzschreibweise:}
   [A, B] &= 0
   \end{align*}
   Für vertauschende Operatoren gibt es gemeinsame scharfe Observablen. \\
   Heisenberg Unschärfe für Ort und Impuls \\
   Ortsdarstellung:
   \begin{align*}
   [\hat x, \hat p] &= \hat x \hat p - \hat p \hat x \\
   &= [x (-i \hbar) \pp{}{x} + i \hbar \pp{}{x} x] \\
   &= [-i \hbar x \pp{}{x} + i \hbar + i \hbar x \pp{}{x}] \\
   &= i \hbar
   \end{align*}
   $⇒$ Operatoren vertauschen nicht! $⇒$ es gibt keinen Eigenzustand zu $\hat x$ und $\hat p$! \\
   Theoretische Quantenmechnik: $[A, B] = i\const$
   \[⇒ \VAR(A) VAR(B) \geq \frac{\const}{2}\]
   Energie-Operator für ein freies Teilchen, klassisch: \\
   Impulsdarstellung (in Impulsdarstellung: $\hat p \to p$):
   \[\text{klassisch: } H = \frac{p^2}{2m} \to \text{Quantenmechanik: } \hat H = \frac{{\hat p}^2}{2m}\]
   Erwartungswert der Energie für Impuls Eigenzustand:
   \begin{align*}
   \hat H \ket{k} &= \frac{1}{2m} \hat p \hat p \ket{k} = \frac{\hbar^2 k^2}{2m} \ket{k} \\
   \hbar H &= \braket{k | \hat H | k} = \frac{\hbar^2 k^2}{2m} \braket{k | k} = \hbar ω_{dB} \\
   [\hat p^2, \hat p] &= \hat p^3 - \hat p^3 = 0
   \end{align*}
   Auch hier: Zustand unverändert, die Zahl gibt die Energie [$\si{\joule}$] an.
   $⇒$ $\ket{k} ist Energie Eigenzustand$
   \[\hat E \ket{ψ_E} = E \ket{ψ_E}\]
   $\hat H$ in Ortsdarstellung:
   \[\frac{\hat p \hat p}{2m} \xrightarrow{\text{Ortsdarstellung}} \frac{1}{2m}(- i \hbar \pp{}{x} - i \hbar \pp{}{x}) = -\frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2}\]
   #+ATTR_LATEX: :options [de Broglie Welle]
   #+begin_ex latex
   \[e^{i(k_{dB} x - ω_{dB} t)} \underarrow[↦]{$\hat E = i\hbar \pp{}{t}$} \underbrace{\hbar ω_{dB}}_{\mathclap{\text{Energie}}} e^{i k_{dB} x - ω_{dB} t}\]
   $⇒$ damit der Energie-Operator die Energie "liefert" muss er als
   \[\hat E = i \hbar \pp{}{t}\]
   definiert sein.
   #+end_ex
   Allgemein auch gültig, das heißt Energie Eigenzustände haben die einfache Zeitentwicklung
   \[e^{-i \frac{E}{\hbar}t}\]
   Deshalb sind diese Zustände eine gute Basis, um Zeitdynamik zu beschreiben. \medskip
   Generell: Jede klassische Größe
   \[a = f(\v x, \v p) ⇒ \hat a = f(\v x, \v p)\]
   zum Beispiel Drehimpuls: $\v L = \v x × \v p$
   \[H = κ \v L^2 \to \hat H = κ(\hat{\v x} × \hat{\v p})^2, \qquad [L_x, L_y] = i L_z\]
   Es gibt aber auch nicht-klassische Größen (zum Bespiel Spin).
** Die Schrödiger Gleichung (nicht relativistische Quantenmechanik)
   Klassische Gesamtenergie: $E$
   \[E = E_{\text{kin}} + E_{\text{pot}}\]
   Allgemeiner: $H$ Hamiltonfunktion
   \[H = \frac{\v p^2}{2m} + V(\v x) ↦ \hat H = \frac{{\hat{\v p}}^2}{2m} + V(\hat{\v x})\]
   \begin{ibox}{Axiom der nicht-relativisitischen Quantenmechanik}
   Operator	Gleichung:
   \[i \hbar \pp{}{t} \ket{ψ} = \hat H \ket{ψ}\]
   \end{ibox}
   Darstellung im Ortsraum: $\hat x \ket{x} = x \ket{x}$
   \begin{align*}
   \hat{\v x} &↦ \v x \\
   \hat{\v p} &↦ -i \hbar \cvec{\pp{}{x}; \pp{}{y}; \pp{}{z}} = -i \hbar \v ∇ \\
   {\hat{\v p}}^2 &= - \hbar^2 \v ∇^2 = - \hbar^2 \Laplace
   \end{align*}
   \begin{ibox}{Schrödinger Gleichung für nicht-relativischische Quantenmechanik}
   \begin{center}
   $\displaystyle{i\hbar \pp{}{t} ψ(\v x, t) = - \frac{\hbar^2}{2m} \Laplace ψ(\v x, t) + V(\v x) ψ(\v x, t)}$ \\
   \end{center}
   Randbedingung:
   \[∫ \abs{ψ}^2 \d V = 1\]
   \end{ibox}
   Damit wird die Dynamik in allgemeinen Potentialen beschrieben. Die Zeitdynamik kann als Interferenz verstanden werden, wenn
   man die Energie-Eigenzustände $\hat H \ket{ψ_E} = E \ket{ψ_E}$ als Basis verwendet $\to$	Zeitabhängigkeit kommt nur durch die verschiedene Phasenentwicklung der Energie-Eigenzustände zustande.
   
   #+ATTR_LATEX: :options [Drei Zustandsystem]
   #+begin_ex latex
   $\ket{a}, \ket{b}, \ket{c}$ Basiszustände, Eigenschaften:
   \begin{align*}
   \braket{a | b} &= \braket{ a | c} = \braket{b | c} = 0 \tag{Orthonormalität} \\
   \braket{a | a} &= \braket{b | b} = \braket{c | c} = 1 \tag{Normierung}
   \end{align*}
   Operatoren:
   \begin{align*}
   \hat A \ket{a} &= a \ket{a} \\
   \hat B \ket{b} &= b \ket{b} \\
   \hat C \ket{c} &= c \ket{c} \\
   \end{align*}
   Mögliche Definitionen:
   \begin{align*}
   \hat A &= a \ket{a} \bra{a} + \ket{b} \bra{c} + \ket{c} \bra b \\
   \hat B &= b \ket{b} \bra{b} \\
   \hat C &= c \ket{c} \bra{c} \\
   \end{align*} \\
   Anwenden auf die Basiszustände:
   \begin{align*}
   \hat A \ket{a} &= (a \ket{a} \bra{a} + \ket{b} \bra{c} + \ket{c} \bra b) \ket{a} = a \ket{a} \\
   \hat A \ket{b} &= (a \ket{a} \bra{a} + \ket{b} \bra{c} + \ket{c} \bra b) \ket{b} = \ket{c} \\
   \hat B \ket{b} &= (b\ket{b}\bra{b}) \ket{b} = b \ket{b} \\
   \intertext{Erwartungswert für $a$:}
   \braket{\hat A}_{\ket{a}} &= \braket{a | \hat A | a} = \braket{a | a | a} = a \braket{a | a} = a \\
   \VAR(A)_{\ket{a}} &= \braket{\hat A^2} - \braket{\hat A}^2 = \braket{a | \hat A a | a} - a^2 = 0 \\
   \braket{b | \hat A | b} &= \braket{b | c} = 0  \\
   \VAR(A)_{\ket{b}} &= \braket{b | \hat A^2 | b} - \braket{b | \hat A | b}^2 = 1 \\
   \end{align*}
   \[[\hat A, \hat B] = \hat A \hat B - \hat B \hat A = b \{\ket{c} \bra{b} + \ket{b} \bra{c}\} \neq 0\]
   #+end_ex
* Beispiele für Einteilchen Quantenmechanik
** Streuung von freien Teilchen an einer Potentialstufe
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}
   \draw[->] (0,0) -- ++(7,0) node[below] {$x$};
   \draw[->] (0,0) -- ++(0,3) node[left] {$E$};
   \draw (7,1.5) -- ++(-4,0) -- ++(0,-1.6) node[below] {$0$};
   \draw[<->] (5.5, 1.5) -- ++(0,-1.5) node[midway, right] {$V_0$};
   \draw[->] (.5, 1) -- ++(2,0) node[midway,above] {$E_{kin} < V_0$};
   \node[below] at (1.5, 0) {Bereich $\text{I}$};
   \node[below] at (5, 0) {Bereich $\text{II}$};
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Lösen Schrödinger Gleichung in *einer* Dimension in Ortsdarstellung: $\v x \to x$
   \[\v x ↦ x: \qquad i \hbar \pp{}{t} ψ(x, t) = - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} ψ(x,t) + V(x) ψ(x, t)\]
   Suchen Lösungen mit Separationsansatz
   \[ψ(x, t) = e^{-i \frac{E}{\hbar}t} ϕ(x)\]
   Warum: Die Zeitentwickung ist "`nur"' Rotation in komplexen Zahlenebene, dieser Zustand $\ket{ψ_E}$ in	Ortsdarstellung $ψ(x, t)$ ist Energie-Eigenzustand.
   \begin{align*}
     \hat E \ket{ψ_E} &= E \ket{ψ_E} \to i \hbar \pp{}{t} ψ(x, t) = i\hbar ϕ(x) (-i \frac{E}{\hbar} e^{i \frac{E}{\hbar}t}) = E e^{-i \frac{E}{\hbar}t} ϕ(x) = E ψ(x, t)\ \checkmark \\
   E &= E_{\text{ges}} = E_{\text{kin}}^{\text{I}} \\
   \intertext{Gleichung für $ϕ(x)$ folgt aus Einsetzen von $ψ(x, t)$ in Schrödinger Gleichung:}
   E e^{-i \frac{E}{\hbar}t} ϕ(x) &= - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} e^{-i \frac{E}{\hbar}} ϕ(x) + V(x) e^{-i \frac{E}{\hbar}t} ϕ(x) \\
   \intertext{Man erhält eine Differentialgeilchung zweiter Ordnung}
   E ϕ(x) &= - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} ϕ(x) + V(x) ϕ(x) \\
   \end{align*}
   Fall 1: $E_{\text{kin}} < V_0$, klassisch wird das Teilchen reflektiert
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}
   \draw[->] (0,0) -- ++(7,0) node[below] {$x$};
   \draw[->] (0,0) -- ++(0,3) node[left] {$E$};
   \draw (7,1.5) -- ++(-4,0) -- ++(0,-1.6) node[below] {$x = 0$};
   \draw[<->] (5.5, 1.5) -- ++(0,-1.5) node[midway, right] {$V_0$};
   \draw[->] (.5, 1) -- ++(2,0) node[midway,above] {$E_{kin} < V_0$};
   \node[below] at (1.5, 0) {Bereich $\text{I}$};
   \node[below] at (5, 0) {Bereich $\text{II}$};
   \end{tikzpicture}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   \end{center}
   \text{Bereich I}:
   \[V(x) = 0 ⇒ E ϕ_{\text{I}}(x) = - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} ϕ_{\text{I}}(x) \quad E = E_{\text{kin}} = \frac{\hbar^2 k^2}{2m}\]
   kennen Lösung:
   \[ϕ_{\text{I}}(x) = A e^{i k x} + B e^{- i k x}\]
   Check:
   \begin{align*}
     - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} ϕ_{\text{I}}(x) &= - \frac{\hbar^2}{2m} (A (-k^2) e^{i k x} + B (-k^2) e^{-ikx}) \\
                                                                          &= \underbrace{\frac{\hbar^2 k^2}{2m}}_{E_{\text{kin}}^{\text{I}}} ϕ_{\text{I}}(x) = \hbar ω_{dB} ϕ_{\text{I}} ϕ_{\text{I}}(x) = E ϕ_{\text{I}}(x) \checkmark
   \end{align*}
   Man erhält die Superposition von zwei Wellen, eine in positive \(x\)-Richtung und eine in negative \(x\)-Richtung
   \[ψ_{\text{I}} (x,t) = e^{-i \frac{E}{\hbar}t} ϕ(x) \underarrow[=]{$E = \frac{\hbar^2 k^2}{2m} = ω_{dB} \hbar$} A e^{i(k x - ω_{dB} t)} + B e^{i(-k x - ω_{dB} t)}\]
   Bereich II:
#   \begin{tikzpicture}
#   \draw[->] (0,0) -- ++(7,0) node[below right] {$x$};
#   \draw[->] (0,0) -- ++(0,3) node[above left] {$E$};
#   \draw[patter = stripen] (7,1.5) -- ++(-4,0) -- ++(0,-1.6) node[below] {$0$};
#   \draw[<->] (5.5, 1.5) -- ++(0,-1.5) node[midway, right] {$V_0$};
#   \draw (-.1,1) node[left] {$E_{\text{kin}}$};
#   \end{tikzpicture}
   \[E ϕ_{\text{II}} (x) = - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} ϕ_{\text{II}}(x) + V_0 ϕ_{\text{II}}(x)\]
   Allgemeine Lösung:
   \[ϕ_{\text{II}}(x) = C e^{-α x} + D e^{α x} \quad\text{mit}\quad α^2 = \frac{2m}{\hbar^2}(V_0 - E)\]
   Für den Fall $V_0 > E$ ist $α$ reell und, Kopffizient $D = 0$ macht $ϕ_{\text{II}}$ quadratintegrabel
   \[∫_0^∞ \abs{ϕ}^2 \d x = 0\]
   Bemerkung: Für $V_0 = 0 \to α$ imaginär, wie in Bereich I besprochen.
   Die spezielle Lösung des Problems folgt aus Randbedingungen bei $x = 0$:
   \[ψ_{\text{I}}(x = 0, t) = ψ_{\text{II}}(x = 0, t)\]
   1. Die zeitliche Entwicklung ist für beide Bereiche gleich, weil Energie-Eigenzustand zur gleichen
      Energie, rotieren gleich schnell in der komplexen Zahlebene.
   2. Für die Räumlische Wellenfunktion muss gelten:
\printbibliography
