#+AUTHOR: Robin Heinemann
#+TITLE: Experimentalphysik III (Oberthaler)
#+INCLUDE: "../header.org" :minlevel 1

# 60% Punkte aus Übungaufgaben
# Übungsblatt: jeden Dientstag ab 14:00 Uhr
# Abgabe der Übungen: nach der Vorlesung am Montag (ab 23. Oktorber) in der Vorlesung
# Klausur: voraussichtlich am 5.2.2018
# Experimentierraum: Do + Fr 14-18 Uhr, 3D-Drucker!

# Quantenphysik und Atome
# Ziele:
# Einführen der Grundkonzepte der Quantenmechanik
# Anwendung der QM für quanitiatives Verstehen der Natur
#   Verstehen der Struktur der Atome & Atom-Licht Wechselwirkung
#   Verbindung zur Thermodynamik - Bose und Fermi Gase
# Neueste Entwicklungen
#   Laserkühlung (N.P. 1996)
#   Ultrakalte Quantengase (N.P.)
#

* Vorspann
** Ein Experiment mit klassischen Teilchen
   1. Fall: Quelle von nicht weiter zerteilbaren Teilchen mit zufälliger Richtung. Es werden die Anzahl der Teilchen auf einem Raster $x$ mit Gitterkonstante $Δx$ gemessen.
	  Dann werden in der Mitte die meißten Teilchen ankommen. Die diskrete Verteilung kann mit einer kontinuierlichen Wahrscheinlichkeitsverteilung beschrieben werden. Die
	  wichtigen Größen sind hier die Position der maximalen Wahrscheinlichkeit und die Breite (FWHM - full width half maximum)
	  #+begin_export latex
      \catcode`(=12
      \catcode`)=12
      \begin{center}
      \begin{tikzpicture}[
            source/.style={draw=black,fill=black!10},
            ray/.style={>=latex,draw=black,fill=blue},
            axis/.style={black,font=\small},
            bin/.style={black,font=\small},
        ]
      \draw[source] (0,0) coordinate (base)
                           -- (0,-1) -- (-1,-1) coordinate[pos=0.5] (mid)
                           -- (-1, 0)
                           -- (base) -- cycle;
      \foreach \x in {-10,...,10}
          \draw[ray,->] ({0.03*\x - 0.5},-1) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});
      \begin{scope}[shift={(0,-2)}]
      \draw[axis,->] (-5,-5) -- (4,-5) node[right] {Ort $x$};
      \foreach \x in {-9,...,7}
          \draw[bin] ({0.5*\x},-5) -- ++(0,1.5);
      \foreach \count/\x\ in {2/0, 1/2, 2/3, 2/4, 3/5, 4/6, 7/7, 8/8, 6/9, 6/10, 5/11, 3/12, 2/14, 1/15}
          \foreach \y in {1,...,\count}
              \filldraw (0.5*\x - 4.25, 0.2*\y - 5.1) circle (2pt);
      \node[font=\scriptsize] at (-4.5,-5.2) {$x$};
      \node[font=\scriptsize] at (-4,-5.2) {$x\!\!+\!\!Δx$};
      \draw[domain=-4.5:4.5,smooth,variable=\x,red,shift={(-.5,-5)}] plot ({\x},{1.5*exp(-0.5*\x*\x)});
      \draw[axis,->,red, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};
      \node[font=\scriptsize,font=\tiny, red] at (-1,-3.4) {$P_1(x)$};
      \draw[axis,->,red] (-2.25,-4.08) -- (-1.5, -4.08) node[font=\tiny, above, midway, yshift=-2pt] {FWHM};
      \draw[axis,->,red] (1.25,-4.08) -- (0.5, -4.08);
      \end{scope}
      \end{tikzpicture}
      \end{center}
      \catcode`(=\active
      \catcode`)=\active
	  #+end_export
   2. Fall: 2 Quellen (mittels Doppelspalt der Breite $d$, $d \ll \text{FWHM}$)
	  #+begin_export latex
      \catcode`(=12
      \catcode`)=12
      \begin{center}
      \begin{tikzpicture}[
            source/.style={draw=black,fill=black!10},
            ray/.style={>=latex,draw=black,fill=blue},
            axis/.style={black,font=\small},
            bin/.style={black,font=\small},
        ]
      \draw[source] (0,0) coordinate (base)
                           -- (0,-1) -- (-1,-1) coordinate[pos=0.5] (mid)
                           -- (-1, 0)
                           -- (base) -- cycle;
      \foreach \x in {-10,...,10}
          \draw[ray,->] ({0.03*\x - 0.5},-1) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});

      \draw[source,green,fill=green!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
      \draw[source,green,fill=green!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
      \draw[source,green,fill=green!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
      \draw[<->,green] (-1.25, -3.5) -- (0.25, -3.5) node[midway, above,font=\tiny] {$d$};
      \node[green] at (4, -3.5) {$d \ll\text{FWHM}$};

      \foreach \x in {-3,...,3}
          \draw[ray,->,green] ({0.075*\x - 1.25},-4) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});

      \foreach \x in {-3,...,3}
          \draw[ray,->,green] ({0.075*\x + 0.25},-4) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});

      \begin{scope}[shift={(0,-4)}]
      \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
      \foreach \x in {-9,...,7}
          \draw[bin] ({0.5*\x},-5) -- ++(0,1.5);
      \foreach \count/\x\ in {1/1, 2/3, 2/4, 3/5, 4/6, 6/7, 7/8, 6/9, 4/10, 5/11, 2/14, 1/15}
          \foreach \y in {1,...,\count}
              \filldraw[green] (0.5*\x - 4.25, 0.2*\y - 5.1) circle (2pt);

      \node[font=\scriptsize] at (-4.5,-5.2) {$x$};
      \node[font=\scriptsize] at (-4,-5.2) {$x\!\!+\!\!Δx$};
      \draw[domain=-4.5:4.5,smooth,variable=\x,green,shift={(-1.25,-5)}] plot ({\x},{1.5*exp(-0.5*\x*\x)});
      \draw[domain=-4.5:4.5,smooth,variable=\x,green,shift={(.25,-5)}] plot ({\x},{1.5*exp(-0.5*\x*\x)});
      \draw[domain=-4.5:4.5,smooth,variable=\x,black,shift={(-.5,-5)}] plot ({\x},{1.5*exp(-0.5*\x*\x)});
      \draw[axis,->,green, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};
      \node[font=\scriptsize,font=\tiny, green] at (-1.45,-3.4) {$P_1$};
      \node[font=\scriptsize,font=\tiny, green] at (.45,-3.4) {$P_2$};
      \node[font=\scriptsize,font=\tiny, black] at (-.5,-3.3) {$(P_1 + P_2)/2$};
      \end{scope}

      \end{tikzpicture}
      \end{center}
      \catcode`(=\active
      \catcode`)=\active
	  #+end_export
   Wichtig: Diskrete Zahlen. Die theoretische Wahrscheinlichkeitsverteilung kann nur annähernd gemessen werden! Anzahl der Teilchen $\to ∞ ⇒ P_1(x)$.
** Ein Experiment mit klassischen Wellen
   Quelle sendet Kugelwellen aus (fixe Frequenz, fixe Amplitude), Doppelspalt. Ein Detektor misst Strom $\propto$ Intensität. Man erhält das Intensisätsmuster $I_{12}$ eines Doppelspalts.
   Bei blockieren eines der Öffnungen des Doppelspalt erhält man einen Einzelspalt und somit nurnoch das Intensitätsmuster eines Einzelspalts, mit Maximum bei dem nicht blockierten Spalt.
   Wichtig: Intensität ist kontinuierlich $I_{12}$ kann genau gemessen werden. \\
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \filldraw (-.5,-.5) circle (2pt);
   \draw (-.5,-.5) circle (7pt);
   \draw (-.5,-.5) circle (12pt);
   \centerarc[](-.5,-.5)(220:320:17pt);
   \centerarc[](-.5,-.5)(220:320:22pt);
   \centerarc[](-.5,-.5)(220:320:27pt);

   \draw[source,green,fill=green!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,green,fill=green!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,green,fill=green!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \draw[<->,green] (-1.25, -3.5) -- (0.25, -3.5) node[midway, above,font=\tiny] {$d$};

   \foreach \x in {1,...,4}
       \centerarc[]({-1.25},-4)(180:360:\x*7.5pt);
   \foreach \x in {1,...,4}
       \centerarc[]({.25},-4)(180:360:\x*7.5pt);

   \draw[source,red,fill=red!10] (-.1,-4.2) -- (-.1,-4.4) -- (.6, -4.4) -- (.6,-4.2) -- cycle;
   \node[red,font=\small,right] at (0.8, -4.3) {Blockierte Position 2};
   %    \draw[ray,->,green] ({0.075*\x - 1.25},-4) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});
   \begin{scope}[shift={(0,-4)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[right] {Ort $x$};
   \draw[axis,->,green, font=\small] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Intensität $I_{12}$};
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,green,shift={(-0.5,-5)}] plot ({\x},{4/sqrt(\x*\x + 4) * cos(\x/(0.0015*sqrt(\x*\x + 4)))^2});
   \draw[domain=-4.5:4.5,smooth,variable=\x,red,shift={(-1.25,-5)}] plot ({\x},{0.65*exp(-0.5*\x*\x)});
   \draw[source,black,fill=black!10] (-3,-4.8) -- (-3,-5) -- (-3.2, -5) -- (-3.2,-4.8) -- cycle;
   \node[font=\small,below] at (-3, -5) {Detektor};
   \draw[green] (-.40, -3.03) -- (-.60, -3.03);
   \draw[dotted] (-.5, -2.5) -- (-.5, -5);
   \node[green] at (-.40, -2.85) {1};
   \filldraw[red] (-.50, -4.5) circle (1pt);
   \node[red] at (-.20, -4.25) {1/4};
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Warum hat $I_{12}$ die angegebene Form?
   \begin{align*}
   I(x) &= c ε_0 \frac{1}{2T} ∫_{-T}^T E(x, t) \d t \\
   E(x, t) &= E_1 \cos(ω t + \v k \v R_1) + E_2 \cos(ω t + \v k \v R_2)
   \end{align*}
   mit Hilfe von komplexer Schreibweise
   \begin{align*}
   E(x, t) &= \Re \{\underarrow[E_1]{reell} e^{i(ω t - \v k \v R_1)} + \underarrow[E_2]{reell} e^{i(ω t - \v k \v R_2)}\} \\
   &= \Re \{(E_1 \underbrace{e^{-i(\v k \v R_1)}}_{a_1} + \underbrace{E_2 e^{-i \v k \v R_2}}_{a_2}) e^{i ω t}\} \\
   ⇒ I_{12}(x) &\propto \abs{a_1 + a_2}^2 \\
   \intertext{Wir interessieren uns nur für $x$ -Abhängigkeit, nicht für absolute Werte}
   I_{12}(x) \propto \abs{a_1 + a_2}^2 &= (a_1^{\ast} + a_2^{\ast})(a_1 + a_2) \\
   &= \abs{a_1}^2 + \abs{a_2}^2 + a_1^{\ast} a_2 + a_2^{\ast} a_1 \\
   \abs{a_1}^2 &= E_1 e^{i k R_1} E_1 e^{-k R_1} = E_1^2 \sim I_1 \\
   \abs{a_2}^2 &= E_2 e^{i k R_2} E_2 e^{-k R_2} = E_2^2 \sim I_2 \\
   a_1^{\ast} a_2 + a_2^{\ast} a_1 &= a_1^{\ast} a_2 + \cc \\
   &= 2 \Re \{a_1^{\ast} a_2\} = 2\Re\{E_1 E_2 e^{i k(\v R_2 - \v R_1)}\} \\
   &= 2 \sqrt{I_1 I_2} \cos\underbrace{(\v k(\v R_2 - \v R_1))}_{ϕ} \\
   ⇒ \Aboxed{I_{12} &= I_1 + I_2 + 2 \sqrt{I_1 I_2} \cos ϕ}
   \end{align*}
   Maximale Intensität $ϕ = 0 \quad \abs{\v R_1} = \abs{\v R_2}$. Für $I_1 = I_2 = I_0$:
   \begin{align*}
   I_{\text{MAX}} &= I_1 + I_2 + 2 \sqrt{I_1 I_2} = 4 I_0 \\
   I_{\text{MIN}} &= I_1 + I_2 = 2 \sqrt{I_1 I_2} = 0
   \end{align*}
   Intensität wird räumlich	umverteilt,	gesamt Intensistät bleibt erhalten
   \[I_1 + I_2 = \text{Energieerhaltung}\]
** Ein Experiment mit Elektronen/Atomen
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \draw[source] (0,0) coordinate (base)
                        -- (0,-1) -- (-0.5, -2)-- (-1,-1) coordinate[pos=0.5] (mid)
                        -- (-1, 0)
                        -- (base) -- cycle;

   \foreach \x in {-10,...,10}
       \draw[ray,->] ({-.5 + 0.5*sin(4*\x)},{-2*cos(4*\x)}) -- ++({sin(4*\x)},{-cos(4*\x)});
   \node at (0.2,-1.4) {$e^-$};
   \draw[source,black,fill=black!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \node at (-1.5, -3.5) {\circled{1}};
   \node at (0.5, -3.5) {\circled{2}};

   \begin{scope}[shift={(0,-3)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
   \foreach \x in {-9,...,7}
       \draw[bin] ({0.5*\x},-5) -- ++(0,1.5);
   \foreach \count/\x\ in {1/1, 3/2, 2/5, 6/6, 7/6, 6/7, 5/8, 5/9, 3/10, 2/13, 2/14}
       \foreach \y in {1,...,\count}
           \filldraw[black] (0.5*\x - 4.25, 0.2*\y - 5.1) circle (2pt);

   \draw[axis,->,black, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};

   \node[font=\scriptsize] at (-4.5,-5.2) {$x$};
   \node[font=\scriptsize] at (-4,-5.2) {$x\!\!+\!\!Δx$};
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,red,shift={(-.5,-5)}] plot ({\x},{(cos(120*\x) + 1)*.7*exp(-0.1*\x*\x)});
   \node[red] at (2.7, -4.2) {$P_{12} = ?$};
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Quelle: Metallspitze aus hohem negativen Potential.
   Wieder diskrete Detektoren, Messung über Elektronenvervielfacher: durch anliegende Spannung löst
   ein Elektron aus einer Metallplatte weitere Elektronen aus, die wieder weiter auslösen. Es entsteht
   ein kurzer Strom-Peak, der gemessen werden kann. \\
   Annahmen:
   \begin{enumerate}
   \item Das Elektron geht entweder durch Blende \circled{1}, oder Blende \circled{2}
   \item Mit "`komplizierter"' Dynamik
   \end{enumerate}

   Einfacher Test für Annahme 2.: Blockieren einer Blende (hier \circled{2}). Man würde
   eine Verteilung ähnlich der mit zwei Blendern erwarten.
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \draw[source] (0,0) coordinate (base)
                        -- (0,-1) -- (-0.5, -2)-- (-1,-1) coordinate[pos=0.5] (mid)
                        -- (-1, 0)
                        -- (base) -- cycle;

   \foreach \x in {-10,...,10}
       \draw[ray,->] ({-.5 + 0.5*sin(4*\x)},{-2*cos(4*\x)}) -- ++({sin(4*\x)},{-cos(4*\x)});
   \node at (0.2,-1.4) {$e^-$};
   \draw[source,black,fill=black!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \node at (-1.5, -3.5) {\circled{1}};
   \node at (0.5, -3.5) {\circled{2}};

   \draw[source,red,fill=red!10] (-.1,-4.2) -- (-.1,-4.4) -- (.6, -4.4) -- (.6,-4.2) -- cycle;
   \node[red,font=\small,right] at (0.8, -4.3) {blockieren \circled{2}};
   \begin{scope}[shift={(0,-3)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
   \draw[axis,->,black, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};

   \node[font=\scriptsize] at (-4.5,-5.2) {$x$};
   \node[font=\scriptsize] at (-4,-5.2) {$x\!\!+\!\!Δx$};
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,black,shift={(-.5,-5)}] plot ({\x},{(cos(120*\x) + 1)*.7*exp(-0.1*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,red,shift={(-.5,-5)}] plot ({\x},{.35*exp(-0.1*\x*\x)});
   \node[red] at (-2.5, -4.5) {$P_{1}$};
   \node[black] at (2.7, -4.2) {$P_{12}$};

   \filldraw[black] (-.50, -3.60) circle (1pt);
   \node[black] at (-.20, -3.45) {1};
   \filldraw[red] (-.50, -4.65) circle (1pt);
   \node[red] at (-.20, -4.35) {\(\frac{1}{4}\)};
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Teilchen verschwinden in den Minima bei der $P_{12}$, obwohl sie nach der Verteilung für eine Blende
   auch dort ankommen müssten.
   \[⇒P_{12} \neq \frac{1}{2} \{P_1 + P_2\}\]
   Mathematische "`einfach"': Einführen der komplexen Wahrscheinlichkeitsamplitude \(ϕ\). Wahrscheinlichkeiten sind gegeben durch
   \begin{align*}
   P_1 &= \abs{ϕ_1}^2 \\
   P_2 &= \abs{ϕ_2}^2 \\
   P_{12} &= \abs{ϕ_1 + ϕ_2}^2
   \end{align*}

   \begin{important}
   Elektronen werden einzeln gezählt. Es gibt keine "halben" Elektronen. Wahrscheinlichkeitsverteilung kann nur annähernd gemessen werden. $P_{12} \estimates$ unendlich viele Experimente.
   \end{important}

   \begin{ibox}{Welle-Teilchen Dualismus}
   Elektronen werden nur als Einheiten detektiert, die räumliche Verteilung	kann als Interferenz von Wahrscheinlichkeits-Amplituden (komplexes $ϕ$) beschrieben werden.
   \end{ibox}
   Beobachtung der Elektronen an jedem Spalt.
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \draw[source,black,fill=black!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \node at (-1.5, -3.5) {\circled{1}};
   \node at (0.5, -3.5) {\circled{2}};
   \draw[orange,fill=orange!10] (-.5, -4.8) circle (6pt);
   \foreach \x in {0,...,10}
       \draw[ray,orange,->,fill=orange!10] ({-.5 + 0.22*sin(36*\x)},{-0.22*cos(36*\x) - 4.8}) -- ++({0.5*sin(36*\x)},{-0.5*cos(36*\x)});
   \node[orange] at (-.5, -5.6) {Lichtquelle};
   \filldraw[black] (-1.25, -4.5) circle (1pt);
   \draw[->,decoration={snake,pre length=3pt, post length=3pt,amplitude=5,segment length=20},decorate,orange] (-1.35, -4.5) -- (-4.5, -5);
   \eye{.7}{-5.5}{-5}{0}
   \node[black,every text node part/.style={align=center}] at (-5.5, -6.3) {Lichtblitz \\ durch gestreutes \\ Licht};

   \begin{scope}[shift={(0,-3)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
   \draw[axis,->,black, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};

   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,orange,shift={(-1.25,-5)}] plot ({\x},{1.5*exp(-0.3*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,orange,dashed,shift={(.25,-5)}] plot ({\x},{1.5*exp(-0.3*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,black,shift={(-.5,-5)}] plot ({\x},{1.5*exp(-0.3*\x*\x)});
   \node[orange] at (2.3, -4.2) {$P_{2}$};
   \node[orange] at (-3.3, -4.2) {$P_{2}$};
   \node[font=\scriptsize,black] at (-.5,-3.3) {$(P_1 + P_2)/2$};
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Es entstehen Lichtblitze durch gestreutes Licht. \(P_1\): Blitz bei \circled{1}, \(P_2\): Blitz bei \circled{2}. Blitz bei \circled{1} und	\circled{2} wird nie beobachtet.
   Dies bestätigt Annahme \circled{1}.
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \draw[source,black,fill=black!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \node at (-1.5, -3.5) {\circled{1}};
   \node at (0.5, -3.5) {\circled{2}};
   \draw[red,fill=orange!10] (-.5, -4.8) circle (6pt);
   \foreach \x in {0,1,2,3,7,8,9}
       \draw[->,red,decoration={snake,pre length=3pt, post length=3pt,amplitude=5,segment length=20},decorate] ({-.5 + 0.22*sin(36*\x)},{-0.22*cos(36*\x) - 4.8}) -- ++({1.5*sin(36*\x)},{-1.5*cos(36*\x)});
   \foreach \x in {0.5,1.5,2.5,7.5,8.5,9.5}
       \draw[->,green,decoration={snake,pre length=3pt, post length=3pt,amplitude=5,segment length=10},decorate] ({-.5 + 0.22*sin(36*\x)},{-0.22*cos(36*\x) - 4.8}) -- ++({1.5*sin(36*\x)},{-1.5*cos(36*\x)});

   \filldraw[black] (-1.25, -4.5) circle (1pt);
   \draw[->,decoration={snake,pre length=3pt, post length=3pt,amplitude=5,segment length=20},decorate,red] (-1.35, -4.5) -- (-4.5, -5);
   \eye{.7}{-5.5}{-5}{0}
   \node[red] at (1.7, -4.2) {$λ \gg d$};
   \node[green] at (1.7, -4.7) {$λ \sim d$};
   \draw[<->,black] (-1.25, -3.5) -- (0.25, -3.5) node[midway, above] {$d$};
   \begin{scope}[shift={(0,-4)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
   \draw[axis,->,black, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};

   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,red,shift={(-.5,-5)}] plot ({\x},{(cos(240*\x) + 1)*.7*exp(-0.1*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,green,shift={(-.5,-5)}] plot ({\x},{(cos(240*\x) + 1)*.7*exp(-0.1*\x*\x) + .35*exp(-0.1*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,green,dashed,shift={(-.5,-5)}] plot ({\x},{.35*exp(-0.1*\x*\x)});
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Bei $λ > d$ ist nicht mehr feststellbar, ob das Elektron durch \circled{1} oder \circled{2} kommt.
   Bei $λ \sim d$ erhält man eine Überlagerung von $\abs{ϕ_1 + ϕ_2}$ und $\frac{1}{2}(P_1 + P_2)$

   Quantenmechanik kann das beschreiben, weil das prinzipiell mögliche Wissen einer physikalischen
** Zusammenfassung
   Für fundierte Diskussion eines Quantenmechanischen Experiments mus definiert werden
   1. Präpration de Anfangszustand
   2. Wechselwirkung / Zeitlich Entwicklung
   3. Detektion - Was wird beobachtet
   Ein *Ereignis* ist definiert als ein spezielles Set von 1. bis 3..
   #+begin_ex latex
   Ein $e^-$ verlässt die Quelle kann nicht alle Orte in Raum erreichen (Blenden), $e^-$ wird
   in einem Ortsintervall $[x, x + Δx]$ detektiert.
   #+end_ex
   Vorhersagen nach folgenden Regeln
   1. Die Wahrscheinlichkeit eines Ereignisses in einem idealen Experiment ist gegeben als
	  das Quadrat des Absolutbetrages einer im allgemeinen komplexen Wahrscheinlichkeitsamplitude \\
	  $P\dots$ Wahrscheinlichkeit \\
	  $ϕ\dots$ Wahrscheinlichkeits-Amplitude \\
	  $P = \abs{ϕ}^2 = ϕ^{\ast} ϕ$
   2. Wenn ein Ereignis in verschiedener Art und Weise stattfinden kann, dann ist
	  die Wahrscheinlichkeits-Amplitude gegeben als Summe der einzelnen Wahrscheinlichkeits-Amplituden
	  der Möglichkeiten.
      #+begin_ex latex
	  $e^- \to$ Detektor über
	  - Blende \circled{1}
	  - Blende \circled{2}
	  \begin{align*}
	  ϕ &= ϕ_1 + ϕ_2 \tag{Superposition} \\
	  P &= \abs{ϕ}^2 = \abs{ϕ_1 + ϕ_2}^2
      \end{align*}
      #+end_ex
   3. Kann man die einzelnen Möglichkeiten prinzipiell unterscheiden, addieren sich die Wahrscheinlichkeiten
	  \[P = (P_1 + P_2) / 2\]
* Materiewellen
** Historische Herleitung von de Broglie
   Ziel:
   - Dispersionsrelation für massive Teilchen
   - Superpositionen von unphysikalischen Wellen können Natur beschreiben
   -	Zerlegungin de Broglie-Wellen erlaubt vorhersagen
   \fullcite{broglie1924xxxv} \\
   3 Grundlegende Hypothesen ($3×$ Einstein)
   1. $E = m_0 c^2$ Masse = Energie, $m_0$: Ruhemasse, $c$: Lichtgeschwindigkeit
   2. $E = h ν_0$ Photoeffekt, $h = \SI{6.626069934+-0.000000089e-34}{\joule\second}$ Planck Konstante, $ν_0$: Frequenz
   3. Gleichmäßig bewegte Bezugssysteme sind mit Lorenzt Transformation verknüpft
   Aus 1. und 2. folgt, dass man jedem Teilchen im Ruhesystem eine Frequenz zuordnen kann
   \[ν_0 = \frac{m_0 c^2}{h}\]
   Sei $S$ ein ruhendes Bezugssystem, betrachte ein ruhendes	Teilchen ($v = 0$). Man erhält
   \[ψ = e^{i ν_0 2π t}\]
   Nun betrachte ein bewegtes Bezugssystem $S'$ mit $v_x = v, v_{y,z} = 0$. Man erhält
   \[ψ = e^{i ν_0 2π t'}\]

   \[t' = \frac{t - \frac{v}{c^2}x}{\sqrt{1 - (\frac{v}{c})^2}}\]
   Die Zeit wird ortsabhängig!
   \begin{align*}
   S'&: e^{i2πν_0 t'} \\
   S&: e^{i2πν_0 (\frac{t - \frac{v}{c^2}x}{\sqrt{1 - (\frac{v}{c})^2}})} = e^{i(ω_{dB}t - k_{dB}x)} \tag{die de Broglie Welle} \\
   \intertext{mit}
   ω_{dB} &= \frac{2π ν_0}{\sqrt{1 - (\frac{v}{c})^2}} = \frac{2π}{h}\frac{m_0 c^2}{\sqrt{1 - (\frac{v}{c})^2}} = \frac{E_{\text{ges}^{\text{Ruhe}}}}{\hbar} \\
   \hbar &= \frac{h}{2π} \\
   \v k_{dB} &= \frac{2π ν_0 \v v}{c^2 \sqrt{1 - (\frac{\v v}{c})^2}} = \frac{2π}{h} \frac{m_0 c^2 \v v}{c^2 \sqrt{1 - (\frac{\v v}{c})^2}} = \frac{\v P_{\text{mel}}}{\hbar}
   \end{align*}
   \begin{ibox}{nicht relativistischer Limes $v \ll c$}
   \begin{align*}
   ω_{dB} &= \frac{1}{\hbar}(m_0 c^2 + \frac{m_0 \v v^2}{2} + \dots) \\
   \v k_{dB} &= \frac{1}{\hbar} m_0 \v v
   \end{align*}
   \end{ibox}
   \[ψ(x, t) = e^{-i(ω_{dB}t - \v k_{dB} \v x)} = \underbrace{e^{i \frac{m_0 c^2}{\hbar}t}}_{\mathclap{\const\text{ hängt nur von der Masse ab}}} e^{i(\underbrace{\frac{m_0 \v v^2}{2\hbar}}_{ω}t - \underbrace{\frac{m_0 \v v}{\hbar}}_{\v k} \v x)}\]
   \begin{ibox}{Materiewelle}
   \[ψ(x,t) = e^{-i(ω t - k x)}\]
   mit
   \begin{align*}
   ω &= \frac{\hbar k^2}{2m} \\
   \hbar k &= m v
   \end{align*}
   Beschreibt ein massives Teilchen mit Masse $m$, das sich mit wohldefinierter / scharf definerter Geschwindigkeit $v \ll c$ bewegt (Impuls Eigenzustand).
   \end{ibox}
   Den Zusammenhang $ω(k) = f(k)$ nennt man Dispersionsrelation.
   #+begin_important latex
   Unterschied zu elektromagnetischen Wellen im Vakuum:
   \[λν = c ⇒ ω = c k\]
   Materiewellen
   \[ω = \frac{\hbar}{2m} k^{\circled[red]{2}}\]
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{tikzpicture}
   \draw[->] (0,0) -- (6,0) node[anchor=north] {$k = \frac{p}{\hbar}$};
   \draw[->] (0,0) -- (0,4) node[anchor=east] {$ω=\frac{E}{\hbar}$};
   \draw (0,0) -- (6,3);
   \draw [red] (0,1) to [bend right=10] (6,3.2);
   \draw [red,decorate,decoration={brace,amplitude=3pt},xshift=-4pt,yshift=0pt] (0, 0) -- (0, 1)node [red,midway,xshift=-14pt] {\footnotesize $m_0 c^2$};
   \draw[<-] (3.9,1.9) to [bend left] (4.9,0.9) node[xshift=5pt,yshift=-10pt,every text node part/.style={align=center}] {Masseloses \\ Teilchen - Photonen};
   \draw[<-,red] (3.9,2.3) to [bend right=10] (2.9,2.9) node[xshift=-28pt,yshift=0pt,every text node part/.style={align=center}] {Dispersion \\ eines Atoms};
   \end{tikzpicture} \\
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   #+end_important
** Wie sieht die Materiewelle aus?
   \begin{align*}
   t = 0\quad ψ(x, t = 0) &= e^{ik_{dB} x} \\
   &= \cos(k_{dB} x) + i \sin(k_{dB} x) \\
   k_{dB} &= \frac{2π}{λ_{dB}} \\
   E &= \frac{\hbar^2 k_{dB}^2}{2m} = \frac{m v^2}{2} \\
   ⇒ \Aboxed{λ_{dB} &= \frac{h}{m v}} \tag*{de Broglie Beziehung}
   \end{align*}
   *Größenordnung* \\
   Thermisches Gas:
   \begin{align*}
   \bar v &= \sqrt{\frac{8 k_{B} T}{π m}} \tag*{mittlere Geschwindigkeit} \\
   \hat v &= \sqrt{\frac{2 k_{B} T}{m}} \tag*{wahrscheinlichste Geschwindigkeit}
   \end{align*}
   | $T$                      | $\hat v$                                | $\hat λ_{dB}$            |
   | $\SI{300}{\kelvin}$      | $\sim\SI{240}{\meter\per\second}$       | $\SI{19}{\pico\meter}$   |
   | $\SI{10}{\micro\kelvin}$ | $\sim\SI{4}{\centi\meter\per\second}$   | $\SI{0.1}{\micro\meter}$ |
   | $\SI{10}{\nano\kelvin}$  | $\sim\SI{1.4}{\centi\meter\per\second}$ | $\SI{3.3}{\micro\meter}$ |
   \[λ_{dB} \propto \frac{1}{\sqrt{T}}\]
   $ψ(x, t)$ ist ein komplexes Feld: \\
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{minipage}{0.45\linewidth}
   Zeit $t = 0$
   \[\displaystyle{ψ(x,t = 0) = e^{i k_{dB} x}}\] \\
   \end{minipage}
   \hfill%
   \begin{minipage}{0.45\linewidth}
   \begin{center}
   \begin{tikzpicture}
       \draw[->] (0,0) -- (6,0) node[anchor=north] {$x$};
       \draw[->] (0,0) -- (0,3) node[anchor=east] {$\Re(ψ)$};
       \draw[red,->] (6,0) -- (6,3) node[anchor=east] {$\Im(ψ)$};
       \draw[red] (0,0) sin (1,2) cos (2,0) sin (3,-2) cos (4,0)
              sin (5,2) cos (6,0);
       \begin{scope}[shift={(-1,0)}]
       \draw[black] (1,2) cos (2,0) sin (3,-2) cos (4,0)
              sin (5,2) cos (6,0) sin (7, -2);
       \end{scope}
   \end{tikzpicture}
   \end{center}
   \end{minipage} \\
   \begin{minipage}{0.45\linewidth}
   Zeit t
   \[\displaystyle{ψ(x,t) = e^{-i(ω_{dB} t - k_{dB} x)}}\] \\
   \end{minipage}
   \hfill%
   \begin{minipage}{0.45\linewidth}
   \begin{center}
   \begin{tikzpicture}
       \draw[->] (0,0) -- (6,0) node[anchor=north] {$x$};
       \draw[->] (0,0) -- (0,3) node[anchor=east] {$\Re(ψ)$};
       \draw[red,->] (6,0) -- (6,3) node[anchor=east] {$\Im(ψ)$};
       \draw[black] (0,0) sin (1,2) cos (2,0) sin (3,-2) cos (4,0)
              sin (5,2) cos (6,0);
       \begin{scope}[shift={(1,0)}]
           \draw[red] (-1, -2) cos (0, 0) sin (1,2) cos (2,0) sin (3,-2) cos (4,0)
              sin (5,2);
       \end{scope}

       \draw (1,.1) -- (1,-.1) node[below] {$x_m$};
       \draw[->] (0,2.1) -- (1,2.1);
       \draw (1,2.1) -- (1,1.975);
       \draw (0.95,2) -- (1.05,2) node[above,xshift=7pt] {$ω_{dB} t = k_{dB} x_m$};
   \end{tikzpicture}
   \end{center}
   \end{minipage}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   # \begin{align*}
   # ψ(x, t) &= e^{i(ω_{dB} t - k_{dB} x)} = \underbrace{e^{i \frac{m_0 c^2}{\hbar}t}}_{\mathclap{\text{hängt nicht von } x, v \text{ ab}}} e^{-i(\frac{m_0 \v v^2}{2\hbar}t - \frac{m_0 \v v}{\hbar}x)} \\
   # P &= \abs{ψ}^2 = \abs{e^{iϕ_0} ψ}^2
   # \end{align*}
   - globale Phase spielt keine Rolle
   - Energienullpunkt $E = m_0 c^2$
   $ψ(x, t)$ ist ein komplexes Feld:
   \begin{align*}
   ω_{dB} t &= k_{dB} x_m \\
   x_m &= \underbrace{\frac{ω_{dB}}{k_{dB}}}_{v_{ph}^{dB}} t \\
   v_{ph}^{dB} &= \frac{m v^2}{2\hbar}\frac{\hbar}{mv} = \frac{v}{2} \tag*{Phasengeschwindigkeit}
   \end{align*}
   Phasengeschwindigkeit ist nicht physikalisch! Gegeben eine de Broglie Welle mit $k_{dB} = k$.
   Wie groß ist die Wahrscheinlichkeit das Teilchen irgendwo zu finden?
   \[P = ∫_{∞}^∞ \underarrow[p]{W.-Dichte}(x) \d x = ∫_{-∞}^∞ \abs{ψ(x)}^2 \d x = ∫_{-∞}^∞ e^{i k x} e^{ - i k x} \d x = ∫_{-∞}^∞ \d x = ∞\]
   Eine de Broglie Welle ist nicht normierbar! Analoges Problem:	Energieinhalt in einer ebenen Elektromagnetischen Welle. \\
   $⇒$ Lösung: Superposition (Überlagerung) von ebenen (unphysikalischen) Wellen erlaubt, um
   physikalischen Situation zu beschreiben. \\
   Zusammenfassung: Neue Beschreibung der Bewegung von Teilchen $⇒$ Wellenoptik. Für
   $ψ(x, t) ⇒ \abs{ψ(x, t)^2} \d x$ ist die Wahrscheinlichkeit, ein Teilchen zur Zeit $t$ im
   Intervall $[x, x + \d x]$ zu beobachten. Klassische Teilchenmechanik entspricht dem geometrischen
   "Optik-Limit" der Wellenmechanik. \\
   \begin{ibox}{Fermat'sches Prinzip in der Wellenoptik}
   Licht breitet sich entlang des kürzesten optischen Weges aus
   \[\underarrow[δ]{Variation} ∫ \frac{\d s}{λ} = 0 = δ ∫ \frac{\d s}{\frac{h}{m v}} = \frac{1}{h} \underbrace{δ ∫ m v \d s = 0}_{\mathclap{\text{Maupertuis Prinzip der kleinsten Wirkung}}}\]
   \end{ibox}
** Das Wellenpaket - physikalische Wellenfunktion durch Überlagerung (Superposition von ebenen Wellen)
   Das Wellenpaket (ruhend) \\
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{minipage}{.45\linewidth}
   $t = 0$ \\
   \begin{center}
   \begin{tikzpicture}
    \draw[->] (0,0) -- (6,0) node[anchor=north] {$x$};
    \draw[->] (3,0) -- (3,3) node[anchor=east] {$ψ$};
    \draw[color=black, domain=-3:3, samples=100,shift={(3,0)}] plot (\x,{(2*exp(-\x*\x)});
    \filldraw (3,2) circle (1.5pt);
    \node[above right] at (3,2) {$ψ_0$};
    \draw[<-] (4, .72) -- (5.5, .72) node[above] {$\frac{ψ_0}{e}$};
    \draw[<-] (2, .72) -- (0.5, .72);
    \draw (2,.72) -- (2,0) node[below] {$-a$};
    \draw (4,.72) -- (4,0) node[below] {$a$};
    \draw (2.9,0.72) -- (3.1,0.72) node[right,font=\scriptsize,xshift=-3pt] {$0,36$};
   \end{tikzpicture}
   \end{center}
   \end{minipage}
   \hfill%
   \begin{minipage}{.45\linewidth}
   \begin{align*}
   ψ(x, t= 0) &= \underbrace{(\frac{2}{π a^2})^{1/4}}_{\mathclap{\text{Normierung}}} e^{- \frac{x^2}{a^2}} \\
   ∫_{-∞}^∞ \abs{ψ}^2 \d x &= 1 \tag*{Quadrat-Integrabel}
   \end{align*}
   \end{minipage}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   $t = T?$ Wir wissen "nur" wie sich de Broglie Wellen ausbreiten $⇒$ zerlege $ψ(x, t = 0)$ in
   ebene Wellen mit Wellenvektor $k_{dB}$. Jede Welle wird sich entsprechend
   \[ω_{dB} = \frac{\hbar k^2_{dB}}{2m}\]
   ausbreiten.
   \begin{align*}
   ψ(x, t = 0) &= ∫_{-∞}^∞ \underarrow[\tilde ψ(k)]{Amplitude der Welle} \overarrow[e^{i k x}]{de Broglie Welle $t = 0$} \d k
   \intertext{$⇒$ triviale Zeitentwicklung}
   ψ(x, t = T) &= ∫_{-∞}^∞ \tilde ψ(k) e^{i k x} e^{-i ω T} \d k \\
   &= ∫_{-∞}^∞ \underbrace{\tilde ψ(k) e^{-i \frac{\hbar}{2m} k^2 T}}_{\text{Phase}} e^{i k x} \d k
   \end{align*}
   Nur die Phase der komplexen Wahrscheinlichkeits-Amplitude ändert sich. Die zeitliche Änderung ist *linear* in
   der Zeit, aber quadratisch in $k$. \\
   Da
   \[Ψ = \tilde ψ(k) e^{i(k x - ω t)}\]
   einer de Broglie Welle und damit einem Teilchen mit scharf definiertem Impuls $p = m v = \hbar k$
   entspricht, bezeichnet man $\tilde ψ(k)$ als Impulsdarstellung / Impulsamplitude. Entsprechend
   $Ψ(x)$ ist die Ortsdarstellung / Ortsamplitude des Quantenmechanischen-Zustandes.
   Die Ausbreitung im Impulsraum ist trivial
   \[\underbrace{\tilde ψ(k)}_{t = 0} \to \underbrace{\tilde ψ(k)}_{t} \underarrow[e^{-i \frac{\hbar k^2}{2m}t}]{Rotation in komplexer Zahlenebene}\]
   Aber wie sieht die räumlich Wahrscheinlichkeitsverteilung aus? \\
   Wiederholung: Fourier-Transformation. \\
   \begin{ibox}{Periodische Funktionen (Fourier 1822)}
   \begin{align*}
   f(x + d) &= f(x) \tag*{$d$: Periode} \\
   f(x) &= \sum_{n = -∞}^{∞} g_n e^{i n G x} \tag*{$G= \frac{2π}{d}$} \\
   g_n &= \frac{1}{d} ∫_{x}^{x + d} f(x) e^{- in G x} d x
   \end{align*}
   \end{ibox}
   \begin{align*}
   ∫_0^d f(x) e^{- i m G x} &= ∫_0^d \sum_{n = -∞}^{∞} g_n e^{i(n - m)G x} = g_m d \\
   ∫_{-∞}^∞ \abs{f(x)}^2 \d x &= ∫_{-∞}^∞ \sum_{n = -∞}^{∞} g_n^{\ast} e^{-i n G x} \sum_{m = -∞}^{∞} g_m e^{i m G x} \d x \\
   &= ∫_{- ∞}^∞ \sum_{n} \sum_{m} g_n^{\ast} g_m e^{i(m - n) G x} \d x \\
   &= \sum_{n = -∞}^{∞} \abs{g_n}^2 = 1 \tag*{Normierung}
   \end{align*}
   $f(x)$ reell $\to g_n = g_n^{\ast}$
   \begin{align*}
   \sum_{n = -∞}^{∞} g_n e^{i n G x} &= g_0 + \sum_{n = -∞}^{-1} g_n e^{i n G x} + \sum_{n = 1}^{∞} g_n e^{i n G x} \\
   &= g_0 +	\{\sum_{n = 1}^{∞} g_n^{\ast} e^{- i n G x} + \sum_{n = 1}^{∞} g_n e^{i n G x}\} \\
   z^{\ast} + z &= (a + i b)^{\ast} + (a + i b) = 2 \Re \{z\}
   \end{align*}
   Einfache Beispiele
   \[f(x) = \cos(G x) = \frac{1}{2} e^{-i G x} + \frac{1}{2} e^{i G x}\]
   Fouriertransformierte
   \[g_{-1} = \frac{1}{2} \qquad g_0 = 0 \qquad g_1 = \frac{1}{2} \qquad g_{\abs{n} > 1} = 0\]
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \[
       f(x) = \dots
       \begin{tikzpicture}[baseline={([yshift=-.5ex]current bounding box.center)}]
           \draw (0.5, 0) -- (1, 0) -- (1, 1) -- (2, 1)
                        -- (2, 0) -- (3, 0) -- (3, 1)
                        -- (4, 1) -- (4, 0) -- (4.5, 0);
           \draw[|-|] (1, 1.3) -- (2,1.3) node[midway,fill=white] {B};
           \draw[|-|] (1, -.3) -- (3,-.3) node[midway,fill=white] {d};
           \draw (.6, 1) node[left] {$1$} -- (.8, 1);
       \end{tikzpicture}
       \dots
   \]
   \begin{center}
   \begin{tikzpicture}
   \draw[->] (-4, 0) -- (4, 0) node[right] {$n$};
   \draw[->] (0, 0) -- (0, 3);
   \draw[domain=-4:4,smooth,variable=\x,red] plot ({\x},{2*sinc(1.8*\x)});
   \foreach \x in {-7,...,7}
       \draw ({.5*\x}, 0) -- ({.5*\x},{2*sinc(1.8*.5*\x)});
   \foreach \x in {0,...,7}
       \draw ({.5*\x}, 0) -- ({.5*\x}, -.1) node[below] {\x};
   \draw[red,<-] (1.75, -.1) -- (1.75, -.6) node[below] {$\frac{d}{B}$};
   \node[red,right] at (.5,3) {$n \neq 0\quad g_n = \frac{1}{nπ} \sin(n \frac{πB}{d})$};
   \node[red,right] at (2.5,2.5) {$g_0 = \frac{B}{a}$};
   \draw[->,red] (2,2.6) -- (1,1.3);
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Je kleiner die Struktur im Ortsraum, umso breiter wird die Verteilung im Impulsraum.
\printbibliography
