#+AUTHOR: Robin Heinemann
#+TITLE: Experimentalphysik III (Oberthaler)
#+INCLUDE: "../header.org" :minlevel 1

# 60% Punkte aus Übungaufgaben
# Übungsblatt: jeden Dientstag ab 14:00 Uhr
# Abgabe der Übungen: nach der Vorlesung am Montag (ab 23. Oktorber) in der Vorlesung
# Klausur: voraussichtlich am 5.2.2018
# Experimentierraum: Do + Fr 14-18 Uhr, 3D-Drucker!


# Montag 13.11 13:30 Fragen

# Quantenphysik und Atome
# Ziele:
# Einführen der Grundkonzepte der Quantenmechanik
# Anwendung der QM für quanitiatives Verstehen der Natur
#   Verstehen der Struktur der Atome & Atom-Licht Wechselwirkung
#   Verbindung zur Thermodynamik - Bose und Fermi Gase
# Neueste Entwicklungen
#   Laserkühlung (N.P. 1996)
#   Ultrakalte Quantengase (N.P.)
#

# \tikzexternalize

* Vorspann
** Ein Experiment mit klassischen Teilchen
   1. Fall: Quelle von nicht weiter zerteilbaren Teilchen mit zufälliger Richtung. Es werden die Anzahl der Teilchen auf einem Raster $x$ mit Gitterkonstante $Δx$ gemessen.
	  Dann werden in der Mitte die meißten Teilchen ankommen. Die diskrete Verteilung kann mit einer kontinuierlichen Wahrscheinlichkeitsverteilung beschrieben werden. Die
	  wichtigen Größen sind hier die Position der maximalen Wahrscheinlichkeit und die Breite (FWHM - full width half maximum)
	  #+begin_export latex
      \catcode`(=12
      \catcode`)=12
      \begin{center}
      \begin{tikzpicture}[
            source/.style={draw=black,fill=black!10},
            ray/.style={>=latex,draw=black,fill=blue},
            axis/.style={black,font=\small},
            bin/.style={black,font=\small},
        ]
      \draw[source] (0,0) coordinate (base)
                           -- (0,-1) -- (-1,-1) coordinate[pos=0.5] (mid)
                           -- (-1, 0)
                           -- (base) -- cycle;
      \foreach \x in {-10,...,10}
          \draw[ray,->] ({0.03*\x - 0.5},-1) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});
      \begin{scope}[shift={(0,-2)}]
      \draw[axis,->] (-5,-5) -- (4,-5) node[right] {Ort $x$};
      \foreach \x in {-9,...,7}
          \draw[bin] ({0.5*\x},-5) -- ++(0,1.5);
      \foreach \count/\x\ in {2/0, 1/2, 2/3, 2/4, 3/5, 4/6, 7/7, 8/8, 6/9, 6/10, 5/11, 3/12, 2/14, 1/15}
          \foreach \y in {1,...,\count}
              \filldraw (0.5*\x - 4.25, 0.2*\y - 5.1) circle (2pt);
      \node[font=\scriptsize] at (-4.5,-5.2) {$x$};
      \node[font=\scriptsize] at (-4,-5.2) {$x\!\!+\!\!Δx$};
      \draw[domain=-4.5:4.5,smooth,variable=\x,red,shift={(-.5,-5)}] plot ({\x},{1.5*exp(-0.5*\x*\x)});
      \draw[axis,->,red, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};
      \node[font=\scriptsize,font=\tiny, red] at (-1,-3.4) {$P_1(x)$};
      \draw[axis,->,red] (-2.25,-4.08) -- (-1.5, -4.08) node[font=\tiny, above, midway, yshift=-2pt] {FWHM};
      \draw[axis,->,red] (1.25,-4.08) -- (0.5, -4.08);
      \end{scope}
      \end{tikzpicture}
      \end{center}
      \catcode`(=\active
      \catcode`)=\active
	  #+end_export
   2. Fall: 2 Quellen (mittels Doppelspalt der Breite $d$, $d \ll \text{FWHM}$)
	  #+begin_export latex
      \catcode`(=12
      \catcode`)=12
      \begin{center}
      \begin{tikzpicture}[
            source/.style={draw=black,fill=black!10},
            ray/.style={>=latex,draw=black,fill=blue},
            axis/.style={black,font=\small},
            bin/.style={black,font=\small},
        ]
      \draw[source] (0,0) coordinate (base)
                           -- (0,-1) -- (-1,-1) coordinate[pos=0.5] (mid)
                           -- (-1, 0)
                           -- (base) -- cycle;
      \foreach \x in {-10,...,10}
          \draw[ray,->] ({0.03*\x - 0.5},-1) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});

      \draw[source,green,fill=green!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
      \draw[source,green,fill=green!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
      \draw[source,green,fill=green!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
      \draw[<->,green] (-1.25, -3.5) -- (0.25, -3.5) node[midway, above,font=\tiny] {$d$};
      \node[green] at (4, -3.5) {$d \ll\text{FWHM}$};

      \foreach \x in {-3,...,3}
          \draw[ray,->,green] ({0.075*\x - 1.25},-4) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});

      \foreach \x in {-3,...,3}
          \draw[ray,->,green] ({0.075*\x + 0.25},-4) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});

      \begin{scope}[shift={(0,-4)}]
      \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
      \foreach \x in {-9,...,7}
          \draw[bin] ({0.5*\x},-5) -- ++(0,1.5);
      \foreach \count/\x\ in {1/1, 2/3, 2/4, 3/5, 4/6, 6/7, 7/8, 6/9, 4/10, 5/11, 2/14, 1/15}
          \foreach \y in {1,...,\count}
              \filldraw[green] (0.5*\x - 4.25, 0.2*\y - 5.1) circle (2pt);

      \node[font=\scriptsize] at (-4.5,-5.2) {$x$};
      \node[font=\scriptsize] at (-4,-5.2) {$x\!\!+\!\!Δx$};
      \draw[domain=-4.5:4.5,smooth,variable=\x,green,shift={(-1.25,-5)}] plot ({\x},{1.5*exp(-0.5*\x*\x)});
      \draw[domain=-4.5:4.5,smooth,variable=\x,green,shift={(.25,-5)}] plot ({\x},{1.5*exp(-0.5*\x*\x)});
      \draw[domain=-4.5:4.5,smooth,variable=\x,black,shift={(-.5,-5)}] plot ({\x},{1.5*exp(-0.5*\x*\x)});
      \draw[axis,->,green, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};
      \node[font=\scriptsize,font=\tiny, green] at (-1.45,-3.4) {$P_1$};
      \node[font=\scriptsize,font=\tiny, green] at (.45,-3.4) {$P_2$};
      \node[font=\scriptsize,font=\tiny, black] at (-.5,-3.3) {$(P_1 + P_2)/2$};
      \end{scope}

      \end{tikzpicture}
      \end{center}
      \catcode`(=\active
      \catcode`)=\active
	  #+end_export
   Wichtig: Diskrete Zahlen. Die theoretische Wahrscheinlichkeitsverteilung kann nur annähernd gemessen werden! Anzahl der Teilchen $\to ∞ ⇒ P_1(x)$.
** Ein Experiment mit klassischen Wellen
   Quelle sendet Kugelwellen aus (fixe Frequenz, fixe Amplitude), Doppelspalt. Ein Detektor misst Strom $\propto$ Intensität. Man erhält das Intensisätsmuster $I_{12}$ eines Doppelspalts.
   Bei blockieren eines der Öffnungen des Doppelspalt erhält man einen Einzelspalt und somit nurnoch das Intensitätsmuster eines Einzelspalts, mit Maximum bei dem nicht blockierten Spalt.
   Wichtig: Intensität ist kontinuierlich $I_{12}$ kann genau gemessen werden. \\
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \filldraw (-.5,-.5) circle (2pt);
   \draw (-.5,-.5) circle (7pt);
   \draw (-.5,-.5) circle (12pt);
   \centerarc[](-.5,-.5)(220:320:17pt);
   \centerarc[](-.5,-.5)(220:320:22pt);
   \centerarc[](-.5,-.5)(220:320:27pt);

   \draw[source,green,fill=green!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,green,fill=green!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,green,fill=green!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \draw[<->,green] (-1.25, -3.5) -- (0.25, -3.5) node[midway, above,font=\tiny] {$d$};

   \foreach \x in {1,...,4}
       \centerarc[]({-1.25},-4)(180:360:\x*7.5pt);
   \foreach \x in {1,...,4}
       \centerarc[]({.25},-4)(180:360:\x*7.5pt);

   \draw[source,red,fill=red!10] (-.1,-4.2) -- (-.1,-4.4) -- (.6, -4.4) -- (.6,-4.2) -- cycle;
   \node[red,font=\small,right] at (0.8, -4.3) {Blockierte Position 2};
   %    \draw[ray,->,green] ({0.075*\x - 1.25},-4) -- ++({2*sin(4*\x)},{-2*cos(4*\x)});
   \begin{scope}[shift={(0,-4)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[right] {Ort $x$};
   \draw[axis,->,green, font=\small] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Intensität $I_{12}$};
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,green,shift={(-0.5,-5)}] plot ({\x},{4/sqrt(\x*\x + 4) * cos(\x/(0.0015*sqrt(\x*\x + 4)))^2});
   \draw[domain=-4.5:4.5,smooth,variable=\x,red,shift={(-1.25,-5)}] plot ({\x},{0.65*exp(-0.5*\x*\x)});
   \draw[source,black,fill=black!10] (-3,-4.8) -- (-3,-5) -- (-3.2, -5) -- (-3.2,-4.8) -- cycle;
   \node[font=\small,below] at (-3, -5) {Detektor};
   \draw[green] (-.40, -3.03) -- (-.60, -3.03);
   \draw[dotted] (-.5, -2.5) -- (-.5, -5);
   \node[green] at (-.40, -2.85) {1};
   \filldraw[red] (-.50, -4.5) circle (1pt);
   \node[red] at (-.20, -4.25) {1/4};
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Warum hat $I_{12}$ die angegebene Form?
   \begin{align*}
   I(x) &= c ε_0 \frac{1}{2T} ∫_{-T}^T E(x, t) \d t \\
   E(x, t) &= E_1 \cos(ω t + \v k \v R_1) + E_2 \cos(ω t + \v k \v R_2)
   \end{align*}
   mit Hilfe von komplexer Schreibweise
   \begin{align*}
   E(x, t) &= \Re \{\underarrow[E_1]{reell} e^{i(ω t - \v k \v R_1)} + \underarrow[E_2]{reell} e^{i(ω t - \v k \v R_2)}\} \\
   &= \Re \{(E_1 \underbrace{e^{-i(\v k \v R_1)}}_{a_1} + \underbrace{E_2 e^{-i \v k \v R_2}}_{a_2}) e^{i ω t}\} \\
   ⇒ I_{12}(x) &\propto \abs{a_1 + a_2}^2 \\
   \intertext{Wir interessieren uns nur für \(x\)-Abhängigkeit, nicht für absolute Werte}
   I_{12}(x) \propto \abs{a_1 + a_2}^2 &= (a_1^{\ast} + a_2^{\ast})(a_1 + a_2) \\
   &= \abs{a_1}^2 + \abs{a_2}^2 + a_1^{\ast} a_2 + a_2^{\ast} a_1 \\
   \abs{a_1}^2 &= E_1 e^{i k R_1} E_1 e^{-k R_1} = E_1^2 \sim I_1 \\
   \abs{a_2}^2 &= E_2 e^{i k R_2} E_2 e^{-k R_2} = E_2^2 \sim I_2 \\
   a_1^{\ast} a_2 + a_2^{\ast} a_1 &= a_1^{\ast} a_2 + \cc \\
   &= 2 \Re \{a_1^{\ast} a_2\} = 2\Re\{E_1 E_2 e^{i k(\v R_2 - \v R_1)}\} \\
   &= 2 \sqrt{I_1 I_2} \cos\underbrace{(\v k(\v R_2 - \v R_1))}_{ϕ} \\
   ⇒ \Aboxed{I_{12} &= I_1 + I_2 + 2 \sqrt{I_1 I_2} \cos ϕ}
   \end{align*}
   Maximale Intensität $ϕ = 0 \quad \abs{\v R_1} = \abs{\v R_2}$. Für $I_1 = I_2 = I_0$:
   \begin{align*}
   I_{\text{MAX}} &= I_1 + I_2 + 2 \sqrt{I_1 I_2} = 4 I_0 \\
   I_{\text{MIN}} &= I_1 + I_2 = 2 \sqrt{I_1 I_2} = 0
   \end{align*}
   Intensität wird räumlich	umverteilt,	gesamt Intensistät bleibt erhalten
   \[I_1 + I_2 = \text{Energieerhaltung}\]
** Ein Experiment mit Elektronen/Atomen
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \draw[source] (0,0) coordinate (base)
                        -- (0,-1) -- (-0.5, -2)-- (-1,-1) coordinate[pos=0.5] (mid)
                        -- (-1, 0)
                        -- (base) -- cycle;

   \foreach \x in {-10,...,10}
       \draw[ray,->] ({-.5 + 0.5*sin(4*\x)},{-2*cos(4*\x)}) -- ++({sin(4*\x)},{-cos(4*\x)});
   \node at (0.2,-1.4) {$e^-$};
   \draw[source,black,fill=black!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \node at (-1.5, -3.5) {\circled{1}};
   \node at (0.5, -3.5) {\circled{2}};

   \begin{scope}[shift={(0,-3)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
   \foreach \x in {-9,...,7}
       \draw[bin] ({0.5*\x},-5) -- ++(0,1.5);
   \foreach \count/\x\ in {1/1, 3/2, 2/5, 6/6, 7/6, 6/7, 5/8, 5/9, 3/10, 2/13, 2/14}
       \foreach \y in {1,...,\count}
           \filldraw[black] (0.5*\x - 4.25, 0.2*\y - 5.1) circle (2pt);

   \draw[axis,->,black, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};

   \node[font=\scriptsize] at (-4.5,-5.2) {$x$};
   \node[font=\scriptsize] at (-4,-5.2) {$x\!\!+\!\!Δx$};
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,red,shift={(-.5,-5)}] plot ({\x},{(cos(120*\x) + 1)*.7*exp(-0.1*\x*\x)});
   \node[red] at (2.7, -4.2) {$P_{12} = ?$};
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Quelle: Metallspitze aus hohem negativen Potential.
   Wieder diskrete Detektoren, Messung über Elektronenvervielfacher: durch anliegende Spannung löst
   ein Elektron aus einer Metallplatte weitere Elektronen aus, die wieder weiter auslösen. Es entsteht
   ein kurzer Strom-Peak, der gemessen werden kann. \\
   Annahmen:
   \begin{enumerate}
   \item Das Elektron geht entweder durch Blende \circled{1}, oder Blende \circled{2}
   \item Mit "`komplizierter"' Dynamik
   \end{enumerate}

   Einfacher Test für Annahme 2.: Blockieren einer Blende (hier \circled{2}). Man würde
   eine Verteilung ähnlich der mit zwei Blendern erwarten.
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \draw[source] (0,0) coordinate (base)
                        -- (0,-1) -- (-0.5, -2)-- (-1,-1) coordinate[pos=0.5] (mid)
                        -- (-1, 0)
                        -- (base) -- cycle;

   \foreach \x in {-10,...,10}
       \draw[ray,->] ({-.5 + 0.5*sin(4*\x)},{-2*cos(4*\x)}) -- ++({sin(4*\x)},{-cos(4*\x)});
   \node at (0.2,-1.4) {$e^-$};
   \draw[source,black,fill=black!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \node at (-1.5, -3.5) {\circled{1}};
   \node at (0.5, -3.5) {\circled{2}};

   \draw[source,red,fill=red!10] (-.1,-4.2) -- (-.1,-4.4) -- (.6, -4.4) -- (.6,-4.2) -- cycle;
   \node[red,font=\small,right] at (0.8, -4.3) {blockieren \circled{2}};
   \begin{scope}[shift={(0,-3)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
   \draw[axis,->,black, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};

   \node[font=\scriptsize] at (-4.5,-5.2) {$x$};
   \node[font=\scriptsize] at (-4,-5.2) {$x\!\!+\!\!Δx$};
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,black,shift={(-.5,-5)}] plot ({\x},{(cos(120*\x) + 1)*.7*exp(-0.1*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,red,shift={(-.5,-5)}] plot ({\x},{.35*exp(-0.1*\x*\x)});
   \node[red] at (-2.5, -4.5) {$P_{1}$};
   \node[black] at (2.7, -4.2) {$P_{12}$};

   \filldraw[black] (-.50, -3.60) circle (1pt);
   \node[black] at (-.20, -3.45) {1};
   \filldraw[red] (-.50, -4.65) circle (1pt);
   \node[red] at (-.20, -4.35) {\(\frac{1}{4}\)};
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Teilchen verschwinden in den Minima bei der $P_{12}$, obwohl sie nach der Verteilung für eine Blende
   auch dort ankommen müssten.
   \[⇒P_{12} \neq \frac{1}{2} \{P_1 + P_2\}\]
   Mathematische "`einfach"': Einführen der komplexen Wahrscheinlichkeitsamplitude \(ϕ\). Wahrscheinlichkeiten sind gegeben durch
   \begin{align*}
   P_1 &= \abs{ϕ_1}^2 \\
   P_2 &= \abs{ϕ_2}^2 \\
   P_{12} &= \abs{ϕ_1 + ϕ_2}^2
   \end{align*}

   \begin{important}
   Elektronen werden einzeln gezählt. Es gibt keine "halben" Elektronen. Wahrscheinlichkeitsverteilung kann nur annähernd gemessen werden. $P_{12} \estimates$ unendlich viele Experimente.
   \end{important}

   \begin{ibox}{Welle-Teilchen Dualismus}
   Elektronen werden nur als Einheiten detektiert, die räumliche Verteilung	kann als Interferenz von Wahrscheinlichkeits-Amplituden (komplexes $ϕ$) beschrieben werden.
   \end{ibox}
   Beobachtung der Elektronen an jedem Spalt.
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \draw[source,black,fill=black!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \node at (-1.5, -3.5) {\circled{1}};
   \node at (0.5, -3.5) {\circled{2}};
   \draw[orange,fill=orange!10] (-.5, -4.8) circle (6pt);
   \foreach \x in {0,...,10}
       \draw[ray,orange,->,fill=orange!10] ({-.5 + 0.22*sin(36*\x)},{-0.22*cos(36*\x) - 4.8}) -- ++({0.5*sin(36*\x)},{-0.5*cos(36*\x)});
   \node[orange] at (-.5, -5.6) {Lichtquelle};
   \filldraw[black] (-1.25, -4.5) circle (1pt);
   \draw[->,decoration={snake,pre length=3pt, post length=3pt,amplitude=5,segment length=20},decorate,orange] (-1.35, -4.5) -- (-4.5, -5);
   \eye{.7}{-5.5}{-5}{0}
   \node[black,every text node part/.style={align=center}] at (-5.5, -6.3) {Lichtblitz \\ durch gestreutes \\ Licht};

   \begin{scope}[shift={(0,-3)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
   \draw[axis,->,black, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};

   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,orange,shift={(-1.25,-5)}] plot ({\x},{1.5*exp(-0.3*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,orange,dashed,shift={(.25,-5)}] plot ({\x},{1.5*exp(-0.3*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,black,shift={(-.5,-5)}] plot ({\x},{1.5*exp(-0.3*\x*\x)});
   \node[orange] at (2.3, -4.2) {$P_{2}$};
   \node[orange] at (-3.3, -4.2) {$P_{2}$};
   \node[font=\scriptsize,black] at (-.5,-3.3) {$(P_1 + P_2)/2$};
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Es entstehen Lichtblitze durch gestreutes Licht. \(P_1\): Blitz bei \circled{1}, \(P_2\): Blitz bei \circled{2}. Blitz bei \circled{1} und	\circled{2} wird nie beobachtet.
   Dies bestätigt Annahme \circled{1}.
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}[
         source/.style={draw=black,fill=black!10},
         ray/.style={>=latex,draw=black,fill=blue},
         axis/.style={black,font=\small},
         bin/.style={black,font=\small},
     ]
   \draw[source,black,fill=black!10] (-4,-3.8) -- (-4,-4) -- (-1.5, -4) -- (-1.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (3,-3.8) -- (3,-4) -- (0.5, -4) -- (0.5,-3.8) -- cycle;
   \draw[source,black,fill=black!10] (-1,-3.8) -- (-1,-4) -- (0, -4) -- (0,-3.8) -- cycle;
   \node at (-1.5, -3.5) {\circled{1}};
   \node at (0.5, -3.5) {\circled{2}};
   \draw[red,fill=orange!10] (-.5, -4.8) circle (6pt);
   \foreach \x in {0,1,2,3,7,8,9}
       \draw[->,red,decoration={snake,pre length=3pt, post length=3pt,amplitude=5,segment length=20},decorate] ({-.5 + 0.22*sin(36*\x)},{-0.22*cos(36*\x) - 4.8}) -- ++({1.5*sin(36*\x)},{-1.5*cos(36*\x)});
   \foreach \x in {0.5,1.5,2.5,7.5,8.5,9.5}
       \draw[->,green,decoration={snake,pre length=3pt, post length=3pt,amplitude=5,segment length=10},decorate] ({-.5 + 0.22*sin(36*\x)},{-0.22*cos(36*\x) - 4.8}) -- ++({1.5*sin(36*\x)},{-1.5*cos(36*\x)});

   \filldraw[black] (-1.25, -4.5) circle (1pt);
   \draw[->,decoration={snake,pre length=3pt, post length=3pt,amplitude=5,segment length=20},decorate,red] (-1.35, -4.5) -- (-4.5, -5);
   \eye{.7}{-5.5}{-5}{0}
   \node[red] at (1.7, -4.2) {$λ \gg d$};
   \node[green] at (1.7, -4.7) {$λ \sim d$};
   \draw[<->,black] (-1.25, -3.5) -- (0.25, -3.5) node[midway, above] {$d$};
   \begin{scope}[shift={(0,-4)}]
   \draw[axis,->] (-5,-5) -- (4,-5) node[above right] {Ort $x$};
   \draw[axis,->,black, font=\tiny] (3.75, -5) -- ++(0,2) node[midway, above, rotate=-90] {Wahrscheinlichkeit};

   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,red,shift={(-.5,-5)}] plot ({\x},{(cos(240*\x) + 1)*.7*exp(-0.1*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,green,shift={(-.5,-5)}] plot ({\x},{(cos(240*\x) + 1)*.7*exp(-0.1*\x*\x) + .35*exp(-0.1*\x*\x)});
   \draw[domain=-4.5:4.5,samples=500,smooth,variable=\x,green,dashed,shift={(-.5,-5)}] plot ({\x},{.35*exp(-0.1*\x*\x)});
   \end{scope}
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Bei $λ > d$ ist nicht mehr feststellbar, ob das Elektron durch \circled{1} oder \circled{2} kommt.
   Bei $λ \sim d$ erhält man eine Überlagerung von $\abs{ϕ_1 + ϕ_2}$ und $\frac{1}{2}(P_1 + P_2)$

   Quantenmechanik kann das beschreiben, weil das prinzipiell mögliche Wissen einer physikalischen
** Zusammenfassung
   Für fundierte Diskussion eines Quantenmechanischen Experiments mus definiert werden
   1. Präpration de Anfangszustand
   2. Wechselwirkung / Zeitlich Entwicklung
   3. Detektion - Was wird beobachtet
   Ein *Ereignis* ist definiert als ein spezielles Set von 1. bis 3..
   #+begin_ex latex
   Ein $e^-$ verlässt die Quelle kann nicht alle Orte in Raum erreichen (Blenden), $e^-$ wird
   in einem Ortsintervall $[x, x + Δx]$ detektiert.
   #+end_ex
   Vorhersagen nach folgenden Regeln
   1. Die Wahrscheinlichkeit eines Ereignisses in einem idealen Experiment ist gegeben als
	  das Quadrat des Absolutbetrages einer im allgemeinen komplexen Wahrscheinlichkeitsamplitude \\
	  $P\dots$ Wahrscheinlichkeit \\
	  $ϕ\dots$ Wahrscheinlichkeits-Amplitude \\
	  $P = \abs{ϕ}^2 = ϕ^{\ast} ϕ$
   2. Wenn ein Ereignis in verschiedener Art und Weise stattfinden kann, dann ist
	  die Wahrscheinlichkeits-Amplitude gegeben als Summe der einzelnen Wahrscheinlichkeits-Amplituden
	  der Möglichkeiten.
      #+begin_ex latex
	  $e^- \to$ Detektor über
	  - Blende \circled{1}
	  - Blende \circled{2}
	  \begin{align*}
	  ϕ &= ϕ_1 + ϕ_2 \tag{Superposition} \\
	  P &= \abs{ϕ}^2 = \abs{ϕ_1 + ϕ_2}^2
      \end{align*}
      #+end_ex
   3. Kann man die einzelnen Möglichkeiten prinzipiell unterscheiden, addieren sich die Wahrscheinlichkeiten
	  \[P = (P_1 + P_2) / 2\]
* Materiewellen
** Historische Herleitung von de Broglie
   Ziel:
   - Dispersionsrelation für massive Teilchen
   - Superpositionen von unphysikalischen Wellen können Natur beschreiben
   -	Zerlegungin de Broglie-Wellen erlaubt vorhersagen
   \fullcite{broglie1924xxxv} \\
   3 Grundlegende Hypothesen ($3×$ Einstein)
   1. $E = m_0 c^2$ Masse = Energie, $m_0$: Ruhemasse, $c$: Lichtgeschwindigkeit
   2. $E = h ν_0$ Photoeffekt, $h = \SI{6.626069934+-0.000000089e-34}{\joule\second}$ Planck Konstante, $ν_0$: Frequenz
   3. Gleichmäßig bewegte Bezugssysteme sind mit Lorenzt Transformation verknüpft
   Aus 1. und 2. folgt, dass man jedem Teilchen im Ruhesystem eine Frequenz zuordnen kann
   \[ν_0 = \frac{m_0 c^2}{h}\]
   Sei $S$ ein ruhendes Bezugssystem, betrachte ein ruhendes	Teilchen ($v = 0$). Man erhält
   \[ψ = e^{i ν_0 2π t}\]
   Nun betrachte ein bewegtes Bezugssystem $S'$ mit $v_x = v, v_{y,z} = 0$. Man erhält
   \[ψ = e^{i ν_0 2π t'}\]

   \[t' = \frac{t - \frac{v}{c^2}x}{\sqrt{1 - (\frac{v}{c})^2}}\]
   Die Zeit wird ortsabhängig!
   \begin{align*}
   S'&: e^{i2πν_0 t'} \\
   S&: e^{i2πν_0 (\frac{t - \frac{v}{c^2}x}{\sqrt{1 - (\frac{v}{c})^2}})} = e^{i(ω_{dB}t - k_{dB}x)} \tag{die de Broglie Welle} \\
   \intertext{mit}
   ω_{dB} &= \frac{2π ν_0}{\sqrt{1 - (\frac{v}{c})^2}} = \frac{2π}{h}\frac{m_0 c^2}{\sqrt{1 - (\frac{v}{c})^2}} = \frac{E_{\text{ges}^{\text{Ruhe}}}}{\hbar} \\
   \hbar &= \frac{h}{2π} \\
   \v k_{dB} &= \frac{2π ν_0 \v v}{c^2 \sqrt{1 - (\frac{\v v}{c})^2}} = \frac{2π}{h} \frac{m_0 c^2 \v v}{c^2 \sqrt{1 - (\frac{\v v}{c})^2}} = \frac{\v P_{\text{mel}}}{\hbar}
   \end{align*}
   \begin{ibox}{nicht relativistischer Limes $v \ll c$}
   \begin{align*}
   ω_{dB} &= \frac{1}{\hbar}(m_0 c^2 + \frac{m_0 \v v^2}{2} + \dots) \\
   \v k_{dB} &= \frac{1}{\hbar} m_0 \v v
   \end{align*}
   \end{ibox}
   \[ψ(x, t) = e^{-i(ω_{dB}t - \v k_{dB} \v x)} = \underbrace{e^{i \frac{m_0 c^2}{\hbar}t}}_{\mathclap{\const\text{ hängt nur von der Masse ab}}} e^{i(\underbrace{\frac{m_0 \v v^2}{2\hbar}}_{ω}t - \underbrace{\frac{m_0 \v v}{\hbar}}_{\v k} \v x)}\]
   \begin{ibox}{Materiewelle}
   \[ψ(x,t) = e^{-i(ω t - k x)}\]
   mit
   \begin{align*}
   ω &= \frac{\hbar k^2}{2m} \\
   \hbar k &= m v
   \end{align*}
   Beschreibt ein massives Teilchen mit Masse $m$, das sich mit wohldefinierter / scharf definerter Geschwindigkeit $v \ll c$ bewegt (Impuls Eigenzustand).
   \end{ibox}
   Den Zusammenhang $ω(k) = f(k)$ nennt man Dispersionsrelation.
   #+begin_important latex
   Unterschied zu elektromagnetischen Wellen im Vakuum:
   \[λν = c ⇒ ω = c k\]
   Materiewellen
   \[ω = \frac{\hbar}{2m} k^{\circled[red]{2}}\]
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{tikzpicture}
   \draw[->] (0,0) -- (6,0) node[anchor=north] {$k = \frac{p}{\hbar}$};
   \draw[->] (0,0) -- (0,4) node[anchor=east] {$ω=\frac{E}{\hbar}$};
   \draw (0,0) -- (6,3);
   \draw [red] (0,1) to [bend right=10] (6,3.2);
   \draw [red,decorate,decoration={brace,amplitude=3pt},xshift=-4pt,yshift=0pt] (0, 0) -- (0, 1)node [red,midway,xshift=-14pt] {\footnotesize $m_0 c^2$};
   \draw[<-] (3.9,1.9) to [bend left] (4.9,0.9) node[xshift=5pt,yshift=-10pt,every text node part/.style={align=center}] {Masseloses \\ Teilchen - Photonen};
   \draw[<-,red] (3.9,2.3) to [bend right=10] (2.9,2.9) node[xshift=-28pt,yshift=0pt,every text node part/.style={align=center}] {Dispersion \\ eines Atoms};
   \end{tikzpicture} \\
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   #+end_important
** Wie sieht die Materiewelle aus?
   \begin{align*}
   t = 0\quad ψ(x, t = 0) &= e^{ik_{dB} x} \\
   &= \cos(k_{dB} x) + i \sin(k_{dB} x) \\
   k_{dB} &= \frac{2π}{λ_{dB}} \\
   E &= \frac{\hbar^2 k_{dB}^2}{2m} = \frac{m v^2}{2} \\
   ⇒ \Aboxed{λ_{dB} &= \frac{h}{m v}} \tag*{de Broglie Beziehung}
   \end{align*}
   *Größenordnung* \\
   Thermisches Gas:
   \begin{align*}
   \bar v &= \sqrt{\frac{8 k_{B} T}{π m}} \tag*{mittlere Geschwindigkeit} \\
   \hat v &= \sqrt{\frac{2 k_{B} T}{m}} \tag*{wahrscheinlichste Geschwindigkeit}
   \end{align*}
   | $T$                      | $\hat v$                                | $\hat λ_{dB}$            |
   | $\SI{300}{\kelvin}$      | $\sim\SI{240}{\meter\per\second}$       | $\SI{19}{\pico\meter}$   |
   | $\SI{10}{\micro\kelvin}$ | $\sim\SI{4}{\centi\meter\per\second}$   | $\SI{0.1}{\micro\meter}$ |
   | $\SI{10}{\nano\kelvin}$  | $\sim\SI{1.4}{\milli\meter\per\second}$ | $\SI{3.3}{\micro\meter}$ |
   \[λ_{dB} \propto \frac{1}{\sqrt{T}}\]
   $ψ(x, t)$ ist ein komplexes Feld: \\
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{minipage}{0.45\linewidth}
   Zeit $t = 0$
   \[\displaystyle{ψ(x,t = 0) = e^{i k_{dB} x}}\] \\
   \end{minipage}
   \hfill%
   \begin{minipage}{0.45\linewidth}
   \begin{center}
   \begin{tikzpicture}
       \draw[->] (0,0) -- (6,0) node[anchor=north] {$x$};
       \draw[->] (0,0) -- (0,3) node[anchor=east] {$\Re(ψ)$};
       \draw[red,->] (6,0) -- (6,3) node[anchor=east] {$\Im(ψ)$};
       \draw[red] (0,0) sin (1,2) cos (2,0) sin (3,-2) cos (4,0)
              sin (5,2) cos (6,0);
       \begin{scope}[shift={(-1,0)}]
       \draw[black] (1,2) cos (2,0) sin (3,-2) cos (4,0)
              sin (5,2) cos (6,0) sin (7, -2);
       \end{scope}
   \end{tikzpicture}
   \end{center}
   \end{minipage} \\
   \begin{minipage}{0.45\linewidth}
   Zeit t
   \[\displaystyle{ψ(x,t) = e^{-i(ω_{dB} t - k_{dB} x)}}\] \\
   \end{minipage}
   \hfill%
   \begin{minipage}{0.45\linewidth}
   \begin{center}
   \begin{tikzpicture}
       \draw[->] (0,0) -- (6,0) node[anchor=north] {$x$};
       \draw[->] (0,0) -- (0,3) node[anchor=east] {$\Re(ψ)$};
       \draw[red,->] (6,0) -- (6,3) node[anchor=east] {$\Im(ψ)$};
       \draw[black] (0,0) sin (1,2) cos (2,0) sin (3,-2) cos (4,0)
              sin (5,2) cos (6,0);
       \begin{scope}[shift={(1,0)}]
           \draw[red] (-1, -2) cos (0, 0) sin (1,2) cos (2,0) sin (3,-2) cos (4,0)
              sin (5,2);
       \end{scope}

       \draw (1,.1) -- (1,-.1) node[below] {$x_m$};
       \draw[->] (0,2.1) -- (1,2.1);
       \draw (1,2.1) -- (1,1.975);
       \draw (0.95,2) -- (1.05,2) node[above,xshift=7pt] {$ω_{dB} t = k_{dB} x_m$};
   \end{tikzpicture}
   \end{center}
   \end{minipage}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   # \begin{align*}
   # ψ(x, t) &= e^{i(ω_{dB} t - k_{dB} x)} = \underbrace{e^{i \frac{m_0 c^2}{\hbar}t}}_{\mathclap{\text{hängt nicht von } x, v \text{ ab}}} e^{-i(\frac{m_0 \v v^2}{2\hbar}t - \frac{m_0 \v v}{\hbar}x)} \\
   # P &= \abs{ψ}^2 = \abs{e^{iϕ_0} ψ}^2
   # \end{align*}
   - globale Phase spielt keine Rolle
   - Energienullpunkt $E = m_0 c^2$
   $ψ(x, t)$ ist ein komplexes Feld:
   \begin{align*}
   ω_{dB} t &= k_{dB} x_m \\
   x_m &= \underbrace{\frac{ω_{dB}}{k_{dB}}}_{v_{ph}^{dB}} t \\
   v_{ph}^{dB} &= \frac{m v^2}{2\hbar}\frac{\hbar}{mv} = \frac{v}{2} \tag*{Phasengeschwindigkeit}
   \end{align*}
   Phasengeschwindigkeit ist nicht physikalisch! Gegeben eine de Broglie Welle mit $k_{dB} = k$.
   Wie groß ist die Wahrscheinlichkeit das Teilchen irgendwo zu finden?
   \[P = ∫_{∞}^∞ \underarrow[p]{W.-Dichte}(x) \d x = ∫_{-∞}^∞ \abs{ψ(x)}^2 \d x = ∫_{-∞}^∞ e^{i k x} e^{ - i k x} \d x = ∫_{-∞}^∞ \d x = ∞\]
   Eine de Broglie Welle ist nicht normierbar! Analoges Problem:	Energieinhalt in einer ebenen Elektromagnetischen Welle. \\
   $⇒$ Lösung: Superposition (Überlagerung) von ebenen (unphysikalischen) Wellen erlaubt, um
   physikalischen Situation zu beschreiben. \\
   Zusammenfassung: Neue Beschreibung der Bewegung von Teilchen $⇒$ Wellenoptik. Für
   $ψ(x, t) ⇒ \abs{ψ(x, t)^2} \d x$ ist die Wahrscheinlichkeit, ein Teilchen zur Zeit $t$ im
   Intervall $[x, x + \d x]$ zu beobachten. Klassische Teilchenmechanik entspricht dem geometrischen
   "Optik-Limit" der Wellenmechanik. \\
   \begin{ibox}{Fermat'sches Prinzip in der Wellenoptik}
   Licht breitet sich entlang des kürzesten optischen Weges aus
   \[\underarrow[δ]{Variation} ∫ \frac{\d s}{λ} = 0 = δ ∫ \frac{\d s}{\frac{h}{m v}} = \frac{1}{h} \underbrace{δ ∫ m v \d s = 0}_{\mathclap{\text{Maupertuis Prinzip der kleinsten Wirkung}}}\]
   \end{ibox}
** Das Wellenpaket - physikalische Wellenfunktion durch Überlagerung (Superposition von ebenen Wellen)
   Das Wellenpaket (ruhend) \\
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{minipage}{.45\linewidth}
   $t = 0$ \\
   \begin{center}
   \begin{tikzpicture}
    \draw[->] (0,0) -- (6,0) node[anchor=north] {$x$};
    \draw[->] (3,0) -- (3,3) node[anchor=east] {$ψ$};
    \draw[color=black, domain=-3:3, samples=100,shift={(3,0)}] plot (\x,{2*exp(-\x*\x)});
    \filldraw (3,2) circle (1.5pt);
    \node[above right] at (3,2) {$ψ_0$};
    \draw[<-] (4, .72) -- (5.5, .72) node[above] {$\frac{ψ_0}{e}$};
    \draw[<-] (2, .72) -- (0.5, .72);
    \draw (2,.72) -- (2,0) node[below] {$-a$};
    \draw (4,.72) -- (4,0) node[below] {$a$};
    \draw (2.9,0.72) -- (3.1,0.72) node[right,font=\scriptsize,xshift=-3pt] {$0,36$};
   \end{tikzpicture}
   \end{center}
   \end{minipage}
   \hfill%
   \begin{minipage}{.45\linewidth}
   \begin{align*}
   ψ(x, t= 0) &= \underbrace{(\frac{2}{π a^2})^{1/4}}_{\mathclap{\text{Normierung}}} e^{- \frac{x^2}{a^2}} \\
   ∫_{-∞}^∞ \abs{ψ}^2 \d x &= 1 \tag*{Quadrat-Integrabel}
   \end{align*}
   \end{minipage}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   $t = T?$ Wir wissen "nur" wie sich de Broglie Wellen ausbreiten $⇒$ zerlege $ψ(x, t = 0)$ in
   ebene Wellen mit Wellenvektor $k_{dB}$. Jede Welle wird sich entsprechend
   \[ω_{dB} = \frac{\hbar k^2_{dB}}{2m}\]
   ausbreiten.
   \begin{align*}
   ψ(x, t = 0) &= ∫_{-∞}^∞ \underarrow[\tilde ψ(k)]{Amplitude der Welle} \overarrow[e^{i k x}]{de Broglie Welle $t = 0$} \d k
   \intertext{$⇒$ triviale Zeitentwicklung}
   ψ(x, t = T) &= ∫_{-∞}^∞ \tilde ψ(k) e^{i k x} e^{-i ω T} \d k \\
   &= ∫_{-∞}^∞ \underbrace{\tilde ψ(k) e^{-i \frac{\hbar}{2m} k^2 T}}_{\text{Phase}} e^{i k x} \d k
   \end{align*}
   Nur die Phase der komplexen Wahrscheinlichkeits-Amplitude ändert sich. Die zeitliche Änderung ist *linear* in
   der Zeit, aber quadratisch in $k$. \\
   Da
   \[Ψ = \tilde ψ(k) e^{i(k x - ω t)}\]
   einer de Broglie Welle und damit einem Teilchen mit scharf definiertem Impuls $p = m v = \hbar k$
   entspricht, bezeichnet man $\tilde ψ(k)$ als Impulsdarstellung / Impulsamplitude. Entsprechend
   $Ψ(x)$ ist die Ortsdarstellung / Ortsamplitude des Quantenmechanischen-Zustandes.
   Die Ausbreitung im Impulsraum ist trivial
   \[\underbrace{\tilde ψ(k)}_{t = 0} \to \underbrace{\tilde ψ(k)}_{t} \underarrow[e^{-i \frac{\hbar k^2}{2m}t}]{Rotation in komplexer Zahlenebene}\]
   Aber wie sieht die räumlich Wahrscheinlichkeitsverteilung aus? \\
   Wiederholung: Fourier-Transformation. \\
   \begin{ibox}{Periodische Funktionen (Fourier 1822)}
   \begin{align*}
   f(x + d) &= f(x) \tag*{$d$: Periode} \\
   f(x) &= \sum_{n = -∞}^{∞} g_n e^{i n G x} \tag*{$G= \frac{2π}{d}$} \\
   g_n &= \frac{1}{d} ∫_{x}^{x + d} f(x) e^{- in G x} d x
   \end{align*}
   \end{ibox}
   \begin{align*}
   ∫_0^d f(x) e^{- i m G x} &= ∫_0^d \sum_{n = -∞}^{∞} g_n e^{i(n - m)G x} = g_m d \\
   ∫_{-∞}^∞ \abs{f(x)}^2 \d x &= ∫_{-∞}^∞ \sum_{n = -∞}^{∞} g_n^{\ast} e^{-i n G x} \sum_{m = -∞}^{∞} g_m e^{i m G x} \d x \\
   &= ∫_{- ∞}^∞ \sum_{n} \sum_{m} g_n^{\ast} g_m e^{i(m - n) G x} \d x \\
   &= \sum_{n = -∞}^{∞} \abs{g_n}^2 = 1 \tag*{Normierung}
   \end{align*}
   $f(x)$ reell $\to g_n = g_n^{\ast}$
   \begin{align*}
   \sum_{n = -∞}^{∞} g_n e^{i n G x} &= g_0 + \sum_{n = -∞}^{-1} g_n e^{i n G x} + \sum_{n = 1}^{∞} g_n e^{i n G x} \\
   &= g_0 +	\{\sum_{n = 1}^{∞} g_n^{\ast} e^{- i n G x} + \sum_{n = 1}^{∞} g_n e^{i n G x}\} \\
   z^{\ast} + z &= (a + i b)^{\ast} + (a + i b) = 2 \Re \{z\}
   \end{align*}
   Einfache Beispiele
   \[f(x) = \cos(G x) = \frac{1}{2} e^{-i G x} + \frac{1}{2} e^{i G x}\]
   Fouriertransformierte
   \[g_{-1} = \frac{1}{2} \qquad g_0 = 0 \qquad g_1 = \frac{1}{2} \qquad g_{\abs{n} > 1} = 0\]
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \[
       f(x) = \dots
       \begin{tikzpicture}[baseline={([yshift=-.5ex]current bounding box.center)}]
           \draw (0.5, 0) -- (1, 0) -- (1, 1) -- (2, 1)
                        -- (2, 0) -- (3, 0) -- (3, 1)
                        -- (4, 1) -- (4, 0) -- (4.5, 0);
           \draw[|-|] (1, 1.3) -- (2,1.3) node[midway,fill=white] {B};
           \draw[|-|] (1, -.3) -- (3,-.3) node[midway,fill=white] {d};
           \draw (.6, 1) node[left] {$1$} -- (.8, 1);
       \end{tikzpicture}
       \dots
   \]
   \begin{center}
   \begin{tikzpicture}
   \draw[->] (-4, 0) -- (4, 0) node[right] {$n$};
   \draw[->] (0, 0) -- (0, 3);
   \draw[domain=-4:4,smooth,variable=\x,red] plot ({\x},{2*sinc(1.8*\x)});
   \foreach \x in {-7,...,7}
       \draw ({.5*\x}, 0) -- ({.5*\x},{2*sinc(1.8*.5*\x)});
   \foreach \x in {0,...,7}
       \draw ({.5*\x}, 0) -- ({.5*\x}, -.1) node[below] {\x};
   \draw[red,<-] (1.75, -.1) -- (1.75, -.6) node[below] {$\frac{d}{B}$};
   \node[red,right] at (.5,3) {$n \neq 0\quad g_n = \frac{1}{nπ} \sin(n \frac{πB}{d})$};
   \node[red,right] at (2.5,2.5) {$g_0 = \frac{B}{a}$};
   \draw[->,red] (2,2.6) -- (1,1.3);
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Je kleiner die Struktur im Ortsraum, umso breiter wird die Verteilung im Impulsraum. \\
   \begin{ibox}{Aperiodische Funktionen}
   \begin{align*}
   f(x) &= \frac{1}{\sqrt{2π}}∫_{-∞}^∞ g(k) e^{ikx} \d k \\
   g(k) &= \frac{1}{\sqrt{2π}}∫_{-∞}^∞ f(x) e^{-ikx} \d x \\
   \end{align*}
   \end{ibox}
   Normierung:
   \[∫_{-∞}^∞ f(x) f^{\ast}(x) \d x = ∫_{-∞}^{∞} g(k) g^{\ast}(k) \d k = 1\]
   In der Quantenmechanik hat man
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{align*}
   ψ(x) &⇔ f(x) \\
   \tilde ψ(k) &⇔ g(k) \\
   \end{align*}
   Dirca-Delta Fuktion \\
   \begin{align*}
   f(x) &= δ(x) =
   \begin{tikzpicture}[baseline={([yshift=-.5ex]current bounding box.center)}]
   \draw[->] (0,0) -- (2,0) node[right] {$x$} node[below,midway] {$0$} ;
   \draw[very thick] (1,0) -- (1,1) node[right] {$∞$};
   \end{tikzpicture} \\
   ∫_{-∞}^∞ h(x) δ(x - x_0) \d x &= h(x_0) \\
   \intertext{Darstellung der Dirac \(δ\)-Funktion über Fourier-Transformation}
   g(k) &= \frac{1}{\sqrt{2π}}∫_{-∞}^{∞} δ(x) e^{-ikx} \d x = \frac{1}{\sqrt{2π}} \\
   δ(x) &= \frac{1}{2π} ∫_{-∞}^∞ e^{ikx} \d x
   \end{align*}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT

   Darstellung von komplexen Zahlen:
   \begin{align*}
   ψ &= \abs{ψ} e^{iϕ}\\
   ψ(x) &= ∫_{-∞}^{∞} \tilde ψ(k) e^{ikx} \d k
   \end{align*}

   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{equation*}
  \begin{array}{cc}
    \text{Ort} & \text{Impuls} \\
    ψ(x, t = 0) = (\frac{2}{πa^2})^{1/4} e^{-\frac{x^2}{a^2}} & \tilde ψ(k, t = 0) = \frac{\sqrt{a}}{(2π)^{3/4}} e^{-\frac{a^2}{4} k^2} \\
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
      \draw[->] (-3.5, 0) -- ++(0, 6) node[left] {$\abs{ψ}^{\circled[red]{$2$}}$};
      \draw (0,.1) -- (0,-.1) node[below] {$0$};
      \draw[variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {3*exp(-\x*\x)});
      \draw[green,variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {6*exp(-4*\x*\x)});
      \draw[->] (-2,{3*exp(-1)}) -- ++(1,0);
      \draw[->] (2,{3*exp(-1)}) node[right, above] {$\frac{1}{\sqrt{e}}$-Breite} -- ++(-1,0);
      \draw (1,{3*exp(-1) + .5}) -- ++(0,-1.9) node[below right,xshift=-2.7mm] {$Δx = \frac{a}{2}$};
    \end{tikzpicture}
    &
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
      \draw[->] (-3.5, 0) -- ++(0, 6) node[left] {$\tilde{\abs{ψ}}^{2}$};
      \draw (0,.1) -- (0,-.1) node[below] {$0$};
      \draw[variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {3*exp(-\x*\x)});
      \draw[green,variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {1.5*exp(-.25*\x*\x)});
      \draw[->] (-2,{3*exp(-1)}) -- ++(1,0);
      \draw[->] (2,{3*exp(-1)}) node[right, above] {$\frac{1}{\sqrt{e}}$-Breite} -- ++(-1,0);
      \draw (1,{3*exp(-1) + .5}) -- ++(0,-1.9) node[below right,xshift=-2.7mm] {$Δx = \frac{1}{k}$};
    \end{tikzpicture}
    \\
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
      \draw[->] (-3.5, 0) -- ++(0, 6) node[left] {$ϕ$};
      \draw (-3.6, 3) node[left] {$0$} -- (-3.4,3);
      \draw (-3.2, 3) -- (3.3,3);
    \end{tikzpicture}
    &
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
      \draw[->] (-3.5, 0) -- ++(0, 6) node[left] {$\tilde ϕ$};
      \draw (-3.6, 3) node[left] {$0$} -- (-3.4,3);
      \draw (-3.2, 3) -- (3.3,3);
    \end{tikzpicture}
  \end{array}
   \end{equation*}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT

   \begin{ibox}{Heisenberg Unschärfe}
   \[Δ x · Δ p = \hbar \underarrow[Δ x]{$\frac{1}{\sqrt{l}}$ Wert der W.-Verteilung} Δ k = \hbar \frac{a}{2} \frac{1}{a} = \frac{\hbar}{2}\]
   $Δ x = \underarrow[\text{RMS}]{Root Mean Square} = \sqrt{\angl{x^2} - \angl{x}^2}$
   \end{ibox}
   folgt aus der Beschreibung eines Teilchens mit Gewschwindigkeit $\v v$ / Impuls $m \v v$ durch
   $e^{i \v k \v x} ⇔$ de Broglie Welle und dem Superpositionsprinzip. \\
   Extremfall: Teilchen am Ort $x_0$:
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
  \begin{equation*}
  \begin{array}{cc}
    \text{Ort} & \text{Impuls} \\
    ψ(x, t = 0) = δ(x - x_0) & \tilde ψ(k, t = 0) = \frac{1}{2π}∫_{-∞}^{∞} e^{i k (x - x_0)} \d k \\
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
      \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\abs{ψ(x)}$};
      \draw[red] (0,0) node[below] {$x_0$} -- ++(0,3.5);
    \end{tikzpicture}
    &
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
      \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\abs{ψ(k)}$};
      \draw[red] (-3.5,2) -- ++(7,0);
    \end{tikzpicture}
    \\
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
      \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$ϕ$};
      \draw (-3.6, 1) node[left] {$0$} -- (-3.4,1);
      \draw[red] (-3.2, 1) -- (3.3,1);
    \end{tikzpicture}
    &
    \begin{tikzpicture}
      \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
      \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\tilde ϕ$};
      \draw[red] (-3.4,2) node[left] {$-k x_0$} -- (3.4,2);
    \end{tikzpicture}
  \end{array}
  \end{equation*}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   $⇒$ Impuls maximal $[-∞,∞]$ unscharf. \\
   Analog: Ein Teilchen mit wohldefiniertem Impuls ist vollständig delokalisiert. \\
   # Impuls ist: $e^{ik_0 x}$
   Ausbreitung eines Wellenpakets:
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{alignat*}{2}
  \intertext{$t = 0$}
  &\begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\abs{ψ}$};
    \draw (0,.1) -- (0,-.1) node[below] {$0$};
    \draw[variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {4*exp(-4*\x*\x)});
  \end{tikzpicture}
  &&
  \begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\tilde{\abs{ψ}}$};
    \draw (0,.1) -- (0,-.1) node[below] {$0$};
    \draw[variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {3*exp(-\x*\x)});
  \end{tikzpicture}
  \\
  &\begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$ϕ$};
    \draw (-3.6, 1) node[left] {$0$} -- (-3.4,1);
    \draw (-3.2, 1) -- (3.3,1);
  \end{tikzpicture}
  &&
  \begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\tilde ϕ$};
    \draw (-3.6, 3) node[left] {$0$} -- (-3.4,3);
    \draw (-3.2, 3) -- (3.3,3);
  \end{tikzpicture}
  \\
  \intertext{{$\color{blue}t=T$}}
  &\begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\abs{ψ}$};
    \draw (0,.1) -- (0,-.1) node[below] {$0$};
    \draw[variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {4*exp(-4*\x*\x)});
    \draw[blue,variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {2*exp(-\x*\x)});
    \draw[blue,<-] (1,1.5) -- (2,2.5) node[align=center,above right,xshift=-.5cm] {Wellenpaket \\ zerläuft};
  \end{tikzpicture}
  &&
  \begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\tilde{\abs{ψ}}$};
    \draw (0,.1) -- (0,-.1) node[below] {$0$};
    \draw[variable=\x,smooth,domain=-3.5:3.5,samples=100] plot ({\x}, {3*exp(-\x*\x)});
    \draw[<-] (1,1.5) -- (2,2.5) node[align=center,above right,xshift=-.5cm] {Keine Kraft \\ Impuls kann sich \\ nicht ändern};
  \end{tikzpicture}
  \\
  &\begin{tikzpicture}
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$x$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$ϕ$};
    \draw (-3.6, 1) node[left] {$0$} -- (-3.4,1);
    \draw (-3.2, 1) -- (3.3,1);
    \draw[mark position=.15(a),blue,domain=-3.5:3.5,variable=\x,samples=100,shift={(0,1)}] plot ({\x},{0.1*\x*\x});
    \node[blue,below left,xshift=7pt] at (a) {$ϕ\propto x^2$};
  \end{tikzpicture}
  &&
  \begin{tikzpicture}[remember picture]
    \draw[->] (-3.5, 0) -- ++(7, 0) node[below] {$k$};
    \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$\tilde ϕ$};
    \draw (-3.6, 3) node[left] {$0$} -- (-3.4,3);
    \draw (-3.2, 3) -- (3.3,3);
    \draw[mark position=.75(a),mark position=.80(b),blue,domain=-3.5:3.5,variable=\x,samples=100,shift={(0,3)}] plot ({\x},{-0.15*\x*\x});
    \node[right,blue,xshift=7pt] at (a) {$ϕ \propto -k^2$};
%    \draw (0,0) -- (m-sq);
  \end{tikzpicture}
  \\
  & && \qquad\tilde ψ(k, t) = \tilde ψ(k) e^{-iω_{dB} t} = \tilde ψ(k) e^{-i \frac{\hbar k^{
        \text{\tikz[remember picture,overlay,baseline,anchor=base,inner sep=0pt]{
            \node[shape=circle,draw,inner sep=0,thin,blue,text=black] (m-sq) at (0,0) {$2$};
            \draw[->, blue] ([xshift=1pt,yshift=1pt]m-sq) to [bend left=5] ([yshift=-2pt,xshift=1pt]b);
          }
        }}}{2m}t}
\end{alignat*}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   \begin{align*}
   ψ(x, t) &= \frac{\sqrt{a}}{(2π)^{3/4}} ∫_{-∞}^∞ e^{-\frac{a^2}{4}(k - k_0)^2} e^{i(k x - ω(k)t)} \d k \\
   \text{mit} \quad ω(k) &= \frac{\hbar k^2}{2m} \\
   ψ(x, t) &= (\frac{2a^2}{π})^{1/4} \frac{e^{iφ}}{(a^4 + \frac{4\hbar^2 t^2}{m^2})^{1/4}} e^{i k_ 0 x} e^{- \frac{(x - \frac{\hbar k_0}{m}t)^2}{a^2 + \frac{2 i \hbar t}{m}}} \\
   \text{mit} \quad φ &= -θ - \frac{\hbar k_0^2}{2m}t \\
   \tan 2θ &= \frac{2\hbar t}{m a^2}
   \end{align*}
   Für die Breite $Δx(t)$ ergibt sich
   \begin{align*}
   Δx(t) &= \frac{a}{2}	\sqrt{1 + \frac{4\hbar^2 t^2}{m^2 a^4}} \\
   \intertext{Für kurze Zeiten:}
   Δx(t) &\sim \frac{a}{2} \frac{\hbar^2}{m^2 a^3}t^2 + \dots \tag*{Quadratisch} \\
   \intertext{Für lange Zeiten:}
   Δx(t) &\sim \frac{\hbar}{m a}t \tag*{Linear} \\
   \intertext{Bemerkung:}
   λ_{dB} &= 2 a  ⇔ v = \frac{\hbar}{m} \frac{2π}{λ_{dB}} = 2π \frac{\hbar}{m a}
   \end{align*}
   #+BEGIN_EXPORT latex
\begin{minipage}{.4\linewidth}
\begin{center}
\catcode`(=12
\catcode`)=12
\begin{tikzpicture}
  \draw[->] (-3.5, 0) -- ++(5, 0) node[below] {$t$};
  \draw[->] (-3.5, 0) -- ++(0, 4) node[left] {$Δx$};
  \draw[blue,domain=0:4.3,variable=\x,samples=100,shift={(-3.5,2)},smooth] node[left] {$2Δx_1$} plot ({\x},{0.1*\x*\x});
  \draw[red,domain=0:3.5,variable=\x,samples=100,shift={(-3.5,1)},smooth] node[left] {$Δx_1$} plot ({\x},{0.25*\x*\x}) node[right] {$\propto t^2$};
\end{tikzpicture}
\catcode`(=\active
\catcode`)=\active
\end{center}
\end{minipage}
\hfill%
\begin{minipage}{.6\linewidth}
Stärkere Lokalisierung führt zum schnellerem Zerfließen!
\end{minipage}
   #+END_EXPORT
** Allgemeine Ausbreitung eines Wellenpakets
   \[ψ(x, t) = ∫_{-∞}^∞ \tilde ψ(k) e^{i(k x - ω(k) t)} \d k\]
   $ω(k)$: Dispersionsrelation \\
   Wenn $\tilde ψ(k)$ im \(k\)-Raum (Impuls Raum) um $k_0$ konzentriert ist, kann
   die Dispersionsrelation $ω(k)$ durch eine Taylor Reihe genährert werden.
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
  \draw[->] (-5, 0) -- ++(10, 0) node[right] {$k$};
  \draw[->] (-5, 0) -- ++(0, 7) node[left] {$ω$};
  \draw (-5.1, 5) node[left] {$ω_0$} -- ++(0.2, 0);
  \draw[red] (0, -.1) node[below] {$k_0$} -- ++(0, 0.2);
  \draw[samples=100,smooth,red,variable=\x] plot ({\x},{4*exp(-\x*\x)});
  \draw[black,variable=\x,smooth,samples=100] plot ({\x},{0.02*\x*\x*\x - 0.05*\x*\x + 0.2*\x + 5});
  \draw[variable=\x,smooth,samples=100,orange] plot ({\x},{0.2*\x + 5});
  \draw[variable=\x,smooth,samples=100,blue] plot ({\x},{-0.05*\x*\x + 5});
  \draw[variable=\x,smooth,samples=100,green] plot ({\x},{0.02*\x*\x*\x + 5});
%  \foreach \color/\name/\x\ in {red/$\abs*{\tilde ψ(k)}$/0, black/$ω(k)$/1, orange/$\propto k$/2, blue/$\propto k^2$/3, green/$\propto k^2$/4}
%     \filldraw[\color] (4, 1+0.5*\x) -- ++(0.4, 0) node[right] {\name};
  \foreach \c/\n\ [count=\i] in {red/$\abs*{\tilde ψ(k)}$, black/$ω(k)$, orange/$\propto k$, blue/$\propto k^2$, green/$\propto k^3$}
      \draw[\c] (4, .5*\i) -- ++(.5, 0) node[right,black] {\n};
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   Taylor Reihe für $ω(k)$:
   \begin{align*}
   ω(k) &= ω(k) \big|_{k_0} + \pp{ω}{k}\big|_{k_0}(k - k_0) + \frac{\partial^2 ω}{\partial k^2}\big|_{k_0} \frac{(k - k_0)^2}{2} + \dots \\
   ⇒ ψ(x, t) &= ∫_{-∞}^∞ \tilde ψ(k) e^{-i (ω_0 + ω_0'(k - k_0) + ω_0'' \frac{(k - k_0)^2}{2})t - k x} \d k \\
   \intertext{Definiere $κ= k - k_0 ⇒ k = κ + k_0$, damit}
   ψ(x, t) &= \underbrace{e^{i(k_0 x - ω_0 t)}}_{\mathclap{\text{de Broglie Welle}}} \underbrace{∫_{-∞}^∞ \tilde ψ(κ + k_0) e^{-i \underbrace{(ω_0' t - x)}_{x' = v_g t - x} κ + \frac{ω_0''}{2}κ^2 t} \d κ}_{\mathclap{\text{Einhüllende}}} \\
   \intertext{Einhüllende bewegt sich mit}
   v_g &= \pp{ω}{k} \big|_{k_0} \\
   \end{align*}
   $ω_0'' = 0$:
   #+begin_export latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
\draw[->] (-4,0) -- ++(8,0) node[right] {$x$};
\draw[->] (-4,0) -- ++(0,3) node[left] {$\Re ψ$};
\draw[variable=\x,smooth,samples=100,black!30!green,domain=-4:4] plot ({\x},{3*exp(-0.4*\x*\x)});
\draw[variable=\x,smooth,samples=500,red,domain=-4:4] plot ({\x},{3*exp(-0.4*\x*\x)*sin(400*\x)});
\draw[->,black!30!green] (0,3) |- (2,3.5) node[right] {$v_g$};
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+end_export
   $ω_0'' \neq 0 ⇒$ Phase $\propto κ^2 t ⇒$ zerfließen. Interpretation:
   \[ω \sim ω_0 + \frac{ω''}{2} k^2 = ω_0 + \frac{\hbar}{2m^{\ast}} k^2\]
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{minipage}{.45\textwidth}
  \begin{center}
    \begin{tikzpicture}
      \draw[->] (-3.5,0) -- ++(7,0) node[right] {$k$};
      \draw[->] (-3.5,0) -- ++(0,4) node[left] {$ω$};
      \draw[black,variable=\x,samples=100,smooth,domain=-3.5:3.5]
      plot ({\x},{3*(.5*\x*\x + .5)/(2*(\x - 1)*\x + 1) + .1*(\x + 5) + 0.002*(\x - .5)*(\x - .5)*(\x - .5)*(\x - .5) - .7});
      \draw[red,dashed,variable=\x,samples=100,smooth,domain=-3:-0.5]
      plot ({\x},{.1738*(\x + 1.75)*(\x + 1.75) + .25});
      \draw[red,dashed,variable=\x,samples=100,smooth,domain=.3:.94]
      plot ({\x},{-15.8*(\x - 0.62)*(\x - 0.62) + 3.79});
      \draw [red,<-,every text node part/.style={align=center}] (.4, 2.2) -- ++(.5,-1) node[below] {negative \\ $\text{Masse}^{\ast}\ m_2^{\ast}$};
      \draw [red,<-,every text node part/.style={align=center}] (-2.9, 0.6) -- ++(.5,+1) node[above] {positive \\ $\text{Masse}^{\ast}\ m_1^{\ast}$};
    \end{tikzpicture}
  \end{center}
\end{minipage}\hfill
\begin{minipage}{.45\textwidth}
  Effektive Masse $m^{\ast}$ ist invers proportional zur Krümmung
  der Dispersionsrelation $ω(k)$. \\ {\color{red}$\abs*{m_1^{\ast}} > \abs*{m_2^{\ast}}$}
\end{minipage}
\catcode`(=\active
\catcode`)=\active
#+end_export
   Gauss'sches Wellenpaket:
   \[\tilde ψ(k) \sim e^{-\frac{a^2}{4}k^2}\]
   $⇒ω''$ Term führt zum zerfließen des Pakets $⇒$ Gauss bleibt Gauss. Hähere Ableitungen von $ω(k)$
   führen zur Verzerrung des Grauss'schen Wellenpakets.
** Beugung von Materiewellen
   Doppelspalt \(\to N\)-Spalten $=$ Gitter. (vergleiche Abschnitt 2.3 Fourier)
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
\begin{tikzpicture}
  \draw[->] (-5,0) -- ++(1,0) node[above] {$x$};
  \draw[->] (-5,0) -- ++(0,-1) node[left] {$z$};
  \draw (-5, -2) node[left] {$z = 0$} -- (-4.25,-2);
  \foreach \x in {1,...,6}
    \draw[very thick] (1.5*\x - 5.5, -2) -- ++(1,0);
  \draw[->] (-5,-4) -- ++(10,0) node[below] {$x$};
  \draw[->] (-5,-4) -- ++(0,1) node[left] {$ψ(x)$};
  \foreach \x in {1,...,5}
    \draw[blue] (1.5*\x - 5, -4) -- ++(.5, 0) -- ++(0,1) -- ++(.5,0) -- ++(0,-1) -- ++(.5,0);
  \draw[->] (-2.5,-.5) -- ++(0,-1) node[midway,right] {$k_z$};
  \foreach \x in {1,2,3}
    \draw (-3.5,-1 -.25*\x) -- ++(2, 0);
  \draw[|-|] (1.75, -1.75) -- ++(1.5, 0) node[midway, above] {$d$};
  \draw[|-|] (1.5, -2.25) -- ++(.5, 0) node[midway, below] {$B$};
  \node at (4, -2.25) {Gitter};
  \node[right] at (-2, -.5) {Doppelspalt $\to$ \(N\)-Spalten = Gitter};
\end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
   \begin{align*}
   \intertext{$ψ(x)$ dirket nach dem Gitter}
   ψ(x, z = 0) &= N \sum_{n = -∞}^{∞} g_n e^{in G x} \qquad G = \frac{2π}{d} \\
   \text{mit } g_n &= \frac{1}{nπ} \sin(n \frac{πB}{d}) \\
   \end{align*}
   Wie breitet sich $ψ(x, k, t)$ aus?
   1. Energieerhaltung: $ω_{dB}$ ändert sich nicht
   2. Impuls ändert die Richtung weil nach dem Gitter gilt:
	  \begin{align*}
      ψ(x, z, t) &= N \sum_{n = -∞}^{∞} g_n \underbrace{e^{i n G x} e^{i(k'_z z - ω t)}}_{\v k_n = \cvec{n G; k'_z}} \\
      &= N \sum_{n = -∞}^{∞} g_n e^{i(\v k_n \v x - ω t)} \\
      \end{align*}
      $k_z'$ folgt aus der Energieerhaltung
	  \[n^2 G^2 + \underarrow[k^{\prime 2}_z]{nach dem Gitter} = \overarrow[k_z^2]{vor dem Gitter}\]
   Wahrscheinlichkeit sich in Richtung $\v k_1 = \cvec{G; k_z'}$ auszubreiten /	gebeugt	zu werden:
   \[P(k_x = G) = \abs{N}^2 g_1^{\ast} g_1\]
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{minipage}{.35\textwidth}
  \begin{center}
    \begin{tikzpicture}
      \draw[->] (0,0) -- ++(0,-1.5) node[midway,right,every text node part/.style={align=left}] {einfallender \\ Wellenvektor $\v k = \cvec{0; k}$};
      \draw[->] (0,-1.7) -- ++(-90:1.5);
      \draw[->] (0,-1.7) -- ++(-60:1.5);
      \draw[->] (0,-1.7) -- ++(-120:1.5);
      \draw [domain=-60:-90,shift={(0,-1.7)}] plot ({cos(\x)}, {sin(\x)}) node[above,xshift=6pt,font=\small] {$α$};
      \draw[red,->] (0, {-1.7-1.5*sin(60)}) -- ++({1.5*cos(60)},0) node[below,midway] {$G$};
      \draw[decoration={brace,mirror,raise=2pt},decorate] (0,-1.7) -- node[left,yshift=5pt,xshift=-2pt] {$k$} ++(-120:1.5);
      \draw[red,decoration={brace,raise=2pt},decorate]  ({1.5*cos(60)},-1.7) -- node[right,xshift=2pt] {$k_z'$} ++(0,{-1.5*sin(60)});
      \draw [dashed,domain=-40:-140,shift={(0,-1.7)}] plot ({1.5*cos(\x)}, {1.5*sin(\x)});
      \draw[<-,bend left] (-1.1,-2.75) to [out=-80,in=-230] ++(1,-1) node[below,every text node part/.style={align=center}] {In\\Festkörperphysik:\\Ewald Kugel};
    \end{tikzpicture}
  \end{center}
\end{minipage}
\hfill%
\begin{minipage}{.55\textwidth}
  $\abs{\v k}$ ist erhalten aber die Richtung ändert sich durch Gittervektor $\v G$. \\
  Nur diskrete Impulse weil periodische Struktur im Raum.
\end{minipage}
\catcode`(=\active
\catcode`)=\active
#+end_export
   Für $\frac{G}{k} \ll 1$:
   Ergebnis wie in Beugung von elektromagnetischen Wellen an periodischen Strukturen.
   \[α = \frac{G}{k} = \frac{2π}{d} \frac{λ_{dB}}{2π} = \frac{λ_{dB}}{d}\]
*** Elektronen
	Beobachtung: Davisson & Germer (1927) $e^{-}$ Strahl mit $\SI{75}{\electronvolt}, λ_{dB} = \SI{1.4e-10}{\meter}$
	fällt auf NI-Kristall.
	#+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \draw[->,decorate,decoration={snake,amplitude=.4mm,segment length=2mm,post length=1mm}] node[left] {$e^{-}$} (0,0) -- ++(2,0);
    \draw[->] (2,-.3) -- ++(210:1.5);
    \draw [domain=180:212.5,shift={(2.4,0)}] plot ({1.5*cos(\x)}, {1.5*sin(\x)});
    \node at (1.5,-.3) {$α$};
    \begin{scope}[xshift=10pt,yshift=-5pt]
    \foreach \x in {1,...,5}
      \foreach \y in {1,...,5}
        \filldraw (.5*\x + 1.5, -.5*\y + 1) circle (1pt);
    \draw[|-|] (4.25,.5) -- ++(0,-.5) node[midway,right] {$d = \SI{3.52e-10}{\meter}$};
    \end{scope}
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
	\[⇒ α = \frac{λ_{dB}}{d} = 0.4 \estimates \sim \frac{\SI{40}{\centi\meter}}{\SI{1}{meter}} \sim \SI{23}{\degree}\]
	Die	Beugungswinkel sind vergleichbar zu Röntgenstrahlen, aber die Eindringtiefe für $e^{-}$
	ist geringer (Coulomb WW) $⇒$ werden heute standardmäßig eingesetzt um bei Molekularstrahl Epitaxie
	kristallines Wachsen nachzuweisen.
	#+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \draw (-3,0) -- ++(6,0);
    \foreach \x in {1,...,10}
       \draw ({(1cm/3pt)*\x - 50pt}, 3pt) circle (3pt);
    \foreach \x in {1,...,9}
       \draw ({(1cm/3pt)*\x + 4pt - 50pt}, 9pt) circle (3pt);
    \draw[->] (-4,2) -- ++(3,-1.5) node[midway,below left] {$e^{-}$-Strahl};
    \foreach \x/\y\ in {0/3, .5/2.5, -.5/2.5, 0/2} {
       \draw (\x, \y) circle (3pt);
       \draw[->] (\x, {\y - .1}) -- ++(0, -.3);
    }
    \draw[->] (0,.5) -- ++(10:3);
    \draw[->] (0,.5) -- ++(20:3);
    \draw[->] (0,.5) -- ++(30:3);
    \draw[line width=2] (3.2, 3) -- ++(0,-2.5) node[above right,every text node part/.style={align=left}] {Beugung \\ wird auf\\ Phosphor-\\schirm\\beobachtet};
  \end{tikzpicture}\\
\end{center}
Kristallines Wachstum \\
Klare Beugungsstruktur:\
\begin{tikzpicture}[anchor=base,baseline]
  \filldraw (0,0) circle (2pt);
  \filldraw (-.5,0) circle (2pt);
  \filldraw (.5,0) circle (2pt);
  \filldraw (0,.5) circle (2pt);
  \filldraw (0,-.5) circle (2pt);
  \filldraw (-.3,-.3) circle (1pt);
  \filldraw (.3,-.3) circle (1pt);
  \filldraw (-.3,.3) circle (1pt);
  \filldraw (.3,.3) circle (1pt);
\end{tikzpicture}\\
Amorphe Strukturen\\
Diffuse Beugungsstruktur:
\begin{tikzpicture}[anchor=base,baseline]
\foreach \x in {1,...,20}{
   \draw[decorate, decoration={random steps,segment length=1pt,amplitude=3pt}] (rand*.5,rand*.5) -- (rand*.5,rand*.5);
}
\end{tikzpicture}
\catcode`(=\active
\catcode`)=\active
#+end_export
*** Moleküle an einem Transmissionsgitter
	Beispiel: $Na_2$ Pritchard Group am MIT.
	#+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \draw[->] (0,0) -- ++(2,0) node[below,midway] {$\SI{800}{\meter\per\second}$} node[above,midway] {$Na$ Ofen};
    \draw (2.5, 1) -- ++(0,-0.75);
    \draw (2.5, -1) -- ++(0,0.75);
    \draw (5.5, 1) -- ++(0,-0.75);
    \draw (5.5, -1) -- ++(0,0.75);
    \foreach \y in {1,...,6}
      \draw (6,.5*\y - 1.875) -- ++(0,.25);
    \draw[<-] (6.2, -1) -- ++(1,-.5) node[right,every text node part/.style={align=left}] {Nanometer\\Gitter\\$d = \SI{160}{\nano\meter}$};
    \draw[->] (6.2, 0.1) -- ++(20:2);
    \draw[->] (6.2, 0) -- ++(0:2) node[right] {Beugung};
    \draw[->] (6.2, -0.1) -- ++(-20:2);
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
	\begin{align*}
	Na: \qquad λ_{dB} &= \SI{20}{\pico\meter} ⇒ θ = \frac{λ_{dB}}{d} \sim \SI{1.25e-4}{} \estimates \SI{125}{\micro\meter\per\meter} \\
	Na_2: \qquad λ_{dB} &= \SI{10}{\pico\meter} ⇒ θ = \frac{1}{2}\SI{125}{\micro\meter\per\meter}
	\end{align*}
*** Nachweis von sehr "fragilen" Molekülen
	Beispiel: $He_2$ \\
	Übliche Methode:
	#+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
\begin{tikzpicture}
\wigglecircle{1}{.25}{20}{0}{0}
\draw[<-] (-.8,.8) -- ++(-1,1) node[above right,midway] {$e^{-}$};
\draw[<-] (.9,.9) -- ++(.5,.5) node[above] {Molekül};
\draw[->] (0,0) -- ++(2,0);
\node at (3,0) {\Huge$\Rightarrow$};
\wigglecircle{1}{.25}{20}{5}{0}
\node at (5,0) {\Huge$+$};
\filldraw (6.5,1.5) circle (.5pt);
\draw (6.5,1.5) circle (5pt) node[above right] {$\v B$};
\draw[->] (6.5, 0) to [in=130,out=0] ++(2,-1);
\draw[decoration={ticks},decorate] (8,-2) -- ++(2,2);
\draw (8,-2) -- ++(2,2) node[below right,every text node part/.style={align=center},midway] {Proportional\\zur Masse};
\draw[decoration={mirror,brace},decorate] (6.5,-2.2) -- node[midway,below] {Massenspektrometer} ++(2.5,0);
%\draw[<-] ()
\end{tikzpicture}
\end{center}
\begin{tikzpicture}
\draw[->] (-.8,.8) -- ++(.5,-.5) node[above right,midway] {$e^{-}$} node[below right] {$He_2$};
\draw[->] (.7,0) -- ++(.7,0);
\node[align=left,right] at (1.5, .3) {$He + He + e^{-}$};
\node[align=left,right] at (1.5, -.3) {$He + He^{+} + 2e^{-}$};
\node at (5, 0) {\Huge$\Rightarrow$};
\node[align=left,right] at (5.7, .15) {misst immer};
\node[align=left,right] at (5.7, -.15) {nur $He$ Masse};
\end{tikzpicture}\\
\catcode`(=\active
\catcode`)=\active
#+end_export
	Verwendung von nanometer Transmissionsgitter $\to$ Analyse der Beugungswinkel\\
	#+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{minipage}{.45\textwidth}
\begin{center}
  \begin{tikzpicture}
    \draw[->] (0,0) -- ++(1,0) node[above,midway,every text node part/.style={align=left}] {{\color{blue}$He$}\\{\color{red}$He_2$}};
    \foreach \y in {1,...,6}
      \draw (1.5,.5*\y - 1.875) -- ++(0,.25);
    \draw[->,red] (2, 0) -- ++(-10:1.5);
    \draw[->,red] (2, 0) -- ++(10:1.5);
    \draw[->,red] (2, 0) -- ++(0:1.5);
    \draw[->,blue] (2, 0) -- ++(-20:1.5);
    \draw[->,blue] (2, 0) -- ++(20:1.5);
    \draw[<->,blue] (2,0) ++(20:1.7) to [out=-70,in=90] (3.7,0);
    \node[blue] at (3.9,.3) {$α$};
  \end{tikzpicture}
\end{center}
\end{minipage}\hfill
\begin{minipage}{.45\textwidth}
${\color{blue} α_{He}} = 2 × {\color{red}α_{He_2}}$
\end{minipage}
\catcode`(=\active
\catcode`)=\active
#+end_export
*** Beugung von Makro-Molekülen
	Beispile: $C_{60}, C_{60}F_{40}$
	#+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \node[rectangle,draw,every text node part/.style={align=left},right] at (0,0) {Ofen\\ $\SI{900}{\kelvin}$};
    \node[white] at (1.2,0) {$\bullet$};
    \draw (2.5, 1) -- ++(0,-0.75);
    \draw (2.5, -1) -- ++(0,0.75);
    \draw (5.5, 1) -- ++(0,-0.75);
    \draw (5.5, -1) -- ++(0,0.75);
    \node at (4, 1.2) {Kollimation};
    \foreach \y in {1,...,6}
      \draw (6,.5*\y - 1.875) -- ++(0,.25);
    \draw[<-] (6.2, -1) -- ++(1,-.5) node[right,every text node part/.style={align=left}] {Beugungsgitter\\$d \sim \SI{100}{\nano\meter}$};
    \draw[->] (6.2, 0.1) -- ++(20:2);
    \draw[->] (6.2, 0) -- ++(00:2) node[above right] {$α=\frac{λ_{dB}}{d} = \SI{30e-6}{}$};
    \draw[->] (6.2, -0.1) -- ++(-20:2);
  \end{tikzpicture}
  \begin{align*}
    m &= 60·^{12}C \\
    λ_{dB} &\sim \SI{3}{\pico\meter} \\
    \SI{30e-6}{} &\estimates \frac{\SI{30}{\micro\meter}}{\si{\meter}} \sim \frac{\SI{3}{\centi\meter}}{\si{\kilo\meter}}
  \end{align*}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
	Fundamentale Frage: Gibt es eine kritische Größe, ab der Quantenmechanik klassisch wird?
** Atom Interferometer
   1. Atom Interferometer - Doppelspalt aus dünnen Goldfolien \\
	  Gruppe-Mlynek: 1991 Konstanz
   2. Atom Interferometer - 3 Gitter Aufbau \\
	  Gruppe Pritchard: 1991 MIT/Boston
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \foreach \y in {1,...,6}
      \draw (2,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (4,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (6,.5*\y - 1.875) -- ++(0,.25);

    \draw[->] (0,.1) -- ++(1.5,0);
    \foreach \a in {-20,0,20}
      \draw[->] (2.1, .1) -- ++(\a:1.2);

    \foreach \y in {-1,0,1}
      \foreach \a in {-20,0,20}
        \draw[->] (4.1, \y+.1) -- ++(\a:1.2);
    \draw[green] (0,0) -- ++(2,0) -- ++(2,1) -- ++(4,0);
    \draw[green] (0,0) -- ++(4,0) -- ++(4,2);
    \filldraw (8.2,1) circle (3pt) node[right] {Atomdetektor};
    \node[green,draw,circle,inner sep=1pt] at (5.5, .5) {$1$};
    \node[green,draw,circle,inner sep=1pt] at (5.5, 1.25) {$2$};
    \draw[->] (3, -2.2) -- (2,-1.4);
    \draw[->] (3, -2.2) node[below] {Nanometer Gitter} -- (4,-1.4);
    \draw[->] (3, -2.2) -- (6,-1.4);
    \draw[->,green] (2.3,1) node[above,yshift=11pt,xshift=-5pt,every text node part/.style={align=left},right] {Beugungs-\\effizienz} -- ++(-.1,-.4) node[below] {$η$};
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
   Die Wahrscheinlichkeit das Atom zu detektieren ist $\abs{ψ}^2$ mit
   \begin{align*}
   ψ &= ψ_{1} + ψ_{2} = η^2 e^{ik l_1} + η^2 e^{ikl_2} \\
   &= η^2 \underarrow[e^{ik l_2}]{globale Phase}(1 + e^{ik(l_2 - l_1)}) \\
   Δl &= l_2 - l_1 = 0 ⇒ \abs{ψ}^2 = 4η^4
   \end{align*}
   Beobachtung des Interfernzmusters $\abs{ψ}^2 = 0$?\\
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{minipage}{.6\textwidth}
\begin{center}
  \begin{tikzpicture}
    \foreach \y in {1,...,6}
      \draw (2,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (4,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (6,.5*\y - 1.875) -- ++(0,.25);
    \draw[->] (0,0) -- ++(2,0) -- ++(2,1) -- ++(4,0) node[right] {$\abs{ψ}^2$};
    \draw[->] (0,0) -- ++(4,0) -- ++(4,2);
    \draw[->] (2,-1.4) -- ++(+.5,-.5) node[below] {Gitterperiode $d$};
    \draw[<->] (6.2, -1) -- ++(0,-.5) node[midway,right] {Verschiebe Gitter um $Δx$};
  \end{tikzpicture}
\end{center}
\end{minipage}
\begin{minipage}{.35\textwidth}
\begin{center}
  \begin{tikzpicture}
    \draw[->] (0,0) -- ++(5, 0) node[below right] {$Δx$};
    \draw[->] (0,0) -- ++(0, 3) node[above left] {$\abs{ψ}^2$};
    \draw[samples=100,smooth,domain=0:5] plot ({\x},{1-cos(360*\x)});
    \draw (.5,.1) -- ++(0, -.2) node[below] {$0$};
    \draw (1,.1) -- ++(0, -.2) node[below] {};
    \draw (1.5,.1) -- ++(0, -.2) node[below] {$d$};
    \draw (2,.1) -- ++(0, -.2) node[below] {};
    \draw (2.5,.1) -- ++(0, -.2) node[below] {$2d$};
  \end{tikzpicture}
\end{center}
\end{minipage}\\
\catcode`(=\active
\catcode`)=\active
#+end_export
   Warum:
   #+BEGIN_EXPORT latex
\catcode`(=12
\catcode`)=12
\begin{align*}
ψ(x) &= \sum_{n = -∞}^{∞} g_n e^{inGx} \\
x ↦ x + Δ x \qquad &= \sum_{n = -∞}^{∞} \underbrace{g_n e^{inG Δ x}}_{g_n e^{i2π n \frac{Δ x}{d}}} e^{inG x} \\
Δ x = d ⇒ e^{i 2π n} &= 1 ⇒ \text{keine Änderung} \\
\intertext{Letztes Gitter:}
&\begin{tikzpicture}
\draw[->] (0,0) -- ++(1,0) node[midway,draw,circle,inner sep=.5pt,above,yshift=2pt] {2};
\draw[green,->] (0,-1) -- ++(1,.8) node[midway,draw,circle,inner sep=.5pt,below,yshift=-2pt,xshift=2pt] {1};
\draw[->] (1.1, 0) -- ++(1,0) node[right] {$g_0$};
\draw[green,->] (1.1, -.2) --++(1,0) node[right] {$g_1 e^{i \frac{2π Δ x}{d}}$};
\end{tikzpicture} \\
\catcode`(=\active
\catcode`)=\active
⇒ ψ &= η^2 e^{i k l_1} e^{i \frac{2π Δ x}{d}} + η^2 e^{ik l_2} \\
\intertext{mit $l_1 = l_2 = l$} \\
ψ &= η^2 e^{i k l} (e^{i \frac{2π Δ x}{d}} + 1) \\
\abs{ψ}^2 &= η^4 ((e^{-i \frac{2π Δ x}{d}} + 1)(e^{i \frac{2π Δ x}{d}} + 1)) \\
&= η^4 \{2 + \underbrace{e^{-i \frac{2π Δ x}{d}} + e^{i \frac{2π Δ x}{d}}}_{= 2 \cos \frac{2π Δ x}{d}}\} \\
⇒ \abs{ψ}^2 &\propto 1 + \cos(\frac{2π}{d} Δ x)
\end{align*}
   #+END_EXPORT
   *Messen von Potentialen* \\
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \foreach \y in {1,...,6}
      \draw (2,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (4,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (6,.5*\y - 1.875) -- ++(0,.25);
    \node[draw,circle,inner sep=1pt] at (5.7, .5) {$1$};
    \node[draw,circle,inner sep=1pt] at (5.7, 1.25) {$2$};
    \draw[->] (0,0) -- ++(2,0) -- ++(2,1) -- ++(4,0);
    \draw[->] (0,0) -- ++(4,0) -- ++(4,2);
    \draw[green,pattern=north west lines, pattern color=green] (4.1,0.8) rectangle (5.4,1.2) node[above,midway,yshift=5pt] {$V$};
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
   Potential am Weg 2:
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \foreach \x/\xl/\yl\ in {3/Weg 2/$V$, 2/Weg 2/{Gesamt-\\energie}, 1/Weg 2/{Kintetische\\Energie\\$\frac{p^2}{2m}$}}{
      \draw[->] (0, 4*\x) -- ++(7,0) node[below,right] {\xl};
      \draw[->,every text node part/.style={align=center}] (0, 4*\x) -- ++(0,3) node[above,left] {\yl};
    }
    \draw[dashed] (5,4) -- ++(0,8);
    \draw[dashed] (3,4) -- ++(0,8);
    \draw[red] (0, 12) -- ++(3,0) -- ++(0,1) -- ++(2,0) -- ++(0,-1) -- ++(2,0);
    \draw (0,9.5) -- ++(7,0) node[right,every text node part/.style={align=center}] {Konstant \\ Zeit-Unabängig\\Energieerhaltung};
    \draw (0, 6) -- ++(3,0) -- ++(0,-1) -- ++(2,0) -- ++(0,+1) -- ++(2,0);
    \draw[black,pattern=north west lines, pattern color=black] (0,3.8) rectangle (3,4) node[above,midway,yshift=5pt,circle,draw,inner sep=1pt] {1};
    \draw[black,pattern=north west lines, pattern color=black] (5,3.8) rectangle (7,4) node[above,midway,yshift=5pt,circle,draw,inner sep=1pt] {3};
    \node[yshift=5pt,circle,draw,inner sep=1pt] at (4,4.09) {2};
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
   \begin{align*}
   1+3: &\qquad \frac{\hbar^2 k_{dB}^2}{2m} \\
   2: &\qquad \frac{p'^2}{2m} + V = \frac{p^2}{2m} \\
    &\qquad \frac{\hbar^2 k^{\prime 2}}{2m} + V = \frac{\hbar^2 k^2}{2m} \\
   \end{align*}
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \foreach \x/\xl/\yl\ in {1/$x$/$V$, 0/$x$/$\Re\{ψ\}$}{
      \draw[->] (0, 4*\x) -- ++(7,0) node[below,right] {\xl};
      \draw[->,every text node part/.style={align=center}] (0, 4*\x) -- ++(0,3) node[above,left] {\yl};
    }
    \draw (0,4) node[left] {$0$} -- ++(.5,0) -- ++(2,1) -- ++(2,0) -- ++(2,-1) -- ++(.5,0);
    \draw[samples=100,domain=-.5:0,smooth,shift={(.5,1.5)}] plot ({\x},{sin(720*\x)});
    \draw[samples=300,domain=0:2,smooth,shift={(.5,1.5)}] plot ({\x},{sin(-(600/4)*\x*\x + 720*\x)});
    \draw[samples=100,domain=2.5:4.5,smooth,shift={(0,1.5)}] plot ({\x},{-sin(120*\x)});
    \draw[samples=300,domain=0:2,smooth,shift={(4.5,1.5)}] plot ({\x},{sin(+(600/4)*\x*\x + 120*\x)});
    \draw (-.1,1.5) node[left] {$0$} -- ++(.2,0);
    \draw[dashed] (0.5,4) -- ++(0,-4);
    \draw[dashed] (2.5,5) -- ++(0,-5);
    \draw[dashed] (4.5,5) -- ++(0,-5);
    \draw[dashed] (6.5,4) -- ++(0,-4);
    \draw[every text node part/.style={align=center},decoration={mirror,brace},decorate] (0,-.1) -- node[midway,below] {Freies\\Teilchen} ++(.5,0);
    \draw[every text node part/.style={align=center},decoration={mirror,brace},decorate] (.5,-.1) -- node[midway,below] {$v$\\wird\\kleiner\\$⇒ λ_{dB} \uparrow$} ++(2,0);
    \draw[every text node part/.style={align=center},decoration={mirror,brace},decorate] (2.5,-.1) -- node[midway,below] {$v=\const$\\$λ_{dB} = \const$} ++(2,0);
    \draw[every text node part/.style={align=center},decoration={mirror,brace},decorate] (4.5,-.1) -- node[midway,below] {$v$\\wird\\größer\\$⇒ λ_{dB} \downarrow$} ++(2,0);
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
   Die Kraft verändert die Geschwindigkeit $⇒$ die de Broglie Wellenlänge ändert sich entsprechend
   $⇒ ϕ = k_{dB}^v · x$ die Phasenakkumulation ändert sich im Potential $⇒$ Phasenshift kann
   gemessen werden. Die de Broglie-Wellenlänge ändert sich $⇒$ sie wird im Bereich 2 länger, weil Atom langsamer wird.
   Einfach Beschreibung durch Einführung eines "Brechungs Index"
   \[n = \frac{k_{\text{Medium}}}{k_{\text{Vakuum}}} = \frac{k'_{\text{Potential}}}{k_{\text{frei}}} = \frac{λ_{dB}^{\text{frei}}}{λ_{dB}^{\text{Potential}}}\]
   Mit $2$:
   \begin{align*}
   k^{\prime 2} &= k^2 - \frac{2mV}{\hbar^2} \\
   k' &= k \sqrt{1 - \frac{2m}{\hbar^2 k^2} V} = k \underbrace{\sqrt{1 - \frac{V}{E_{\text{ges}}}}}_{n_{dB}} \\
   \intertext{Für $V \ll E_{\text{ges}}$}
   n_{dB} &\approx 1 - \frac{V}{2E_{\text{ges}}}
   \end{align*}
   Im Atom Interferometer: Empfindlichkeit abschätzen $\to$ welche Potentialhöhe
   führt zu einer Phasenverschiebung von $π \estimates$ Maxima des Interferenzmusters
   verschieben sich um eine halbe Periode.
   \begin{align*}
   Δ ϕ &= -π = (n - 1) k_{dB} · L = - \frac{V}{2E} k_{dB} L \\
   V &= \frac{\hbar^2 k_{dB}}{m} \frac{π}{L} \\
   \intertext{$m = Na, λ_{dB} \sim \SI{20}{\pico\meter}, L = \SI{1}{\centi\meter}$}
   V &= \SI{3e-29}{\joule} \estimates \SI{0.18}{\nano\electronvolt}
   \end{align*}
   Anwendungen: Messung der Erdbeschleunigung.
   #+begin_export latex
\catcode`(=12
\catcode`)=12
\begin{center}
  \begin{tikzpicture}
    \foreach \y in {1,...,6}
      \draw (2,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (4,.5*\y - 1.875) -- ++(0,.25);
    \foreach \y in {1,...,6}
      \draw (6,.5*\y - 1.875) -- ++(0,.25);
    \draw[->] (0,0) -- ++(2,0) -- ++(2,1) -- ++(4,0);
    \draw[->] (0,0) -- ++(4,0) -- ++(4,2);
    \node[below] at (3,0) {$m g h_1$};
    \node[above] at (5,1) {$m g h_2$};
    \draw[->] (1,1.2) node[above] {$\v g$} -- ++(0,-1);
  \end{tikzpicture}
\end{center}
\catcode`(=\active
\catcode`)=\active
#+end_export
   $⇒$ Potentialdifferenz, für $m: Cs, Δ h = \SI{1}{\meter}$
   \[m g Δ h \sim \SI{13}{\micro\electronvolt}\]
   Gravitationsmessung mit Atomeren Fountain $⇒ g \pm 10^{-9} g$. Erste Messung mit Neutronen.
** Zusammenfassung
   Historische Herleitung von de Brogliewellen = $3×$ Einstein \\
   De Brocliewelle: Quantenmechanischer Zustand mit scharfen Impuls \\
   Dispersionsrelation für massive Teilchen \\
   Superposition von ebenen Wellen können physikalische (normierbare) Zustände beschreiben - $\abs{ψ(x)}^2 \d x$ ist die Wahlscheinlichkeit ein Teilchen im Intervall $[x,x + \d x]$ zu detektieren. \\
   Zerlegung einer allgemeinen Einteilchenwellenfunktion in de Broglie Wellen erlaubt Vorhersage der Dynamik \\
   Viele Experimente in Quantenmechanik mit einzelnen Teilchen, können mit diesen minimalen	Vorraussetzungen verstanden werden
* Allgemeine Quantenmechanik
** Quantenmechanischer Zustand und dessen Darstellung
   Besher nur den Fall der Ausbreitung eines massiven Teilchens $\to$ Wellenmechanik. Quantenmechanik ist allgemeiner!
   \begin{ibox}{}
   Das System (zum Beispiel Teilchen, drehendes Molekül, $\dots$) wird beschrieben durch einen Quantenmechanischen Zustand $\ket{ψ}$. Er beinhaltet alles,
   was wir vom System wissen können.
   \end{ibox}
   $\ket{ψ}$ nennt man "ket", eingeführt von Dirac. \\
   $\ket{ψ}^{\ast} = \bra{ψ}$ nennt man "bra". \\
   Skalarprodukt: $\braket{ψ|ψ}$ \\
#+BEGIN_EXPORT latex
\catcode`(=12
\catcode`)=12
   \begin{minipage}[t]{.45\textwidth}
   2D Raum:\\
   \begin{center}
   \begin{tikzpicture}
   \draw (-2,0) -- ++(5,0) -- ++(2,3) -- ++(-5,0) -- cycle;
   \draw[->] (.5,1) -- ++(1.5,0) node[below right] {$x$};
   \draw[->] (.5,1) -- ++(1,1.5) node[below right] {$y$};
   \draw[->] (.5,1) -- ++(1.5,.5) node[above, midway] {$r$};
   \draw[smooth,samples=20,domain=90:72,shift={(.5,1)}] plot ({sin(\x)},{cos(\x)}) node[right,yshift=-3pt] {$φ$};
   \filldraw[->] (.5,1) ++(1.5,.5) circle (1pt);
   \draw (2.1,1.6) -- ++(1,1.5) node[above] {Punkt $p$};
   \end{tikzpicture}
   \end{center}
   Darstellung des Punktes in einem Koordinatensystem durch einen Vektor: \\
   kartesich: $(x,y)$ \\
   polar: $(r, φ)$ \\
   \begin{align*}
   \v P &= x \v e_x + y \v e_y \\
   \intertext{$x, y$: Koordinaten, $\v e_x, \v e_y$: Basisvektoren, alternativ}
   \v P &= r \v e_r + φ + \v e_φ \\
   \end{align*}
   \vfill
   \end{minipage}
   \hfill
   \begin{minipage}[t]{.45\textwidth}
   Quantenmechanik \\
   \begin{center}
   \begin{tikzpicture}
   \wigglecircle{2.5}{.5}{20}{0}{0}
   \draw[->] (-2,2) node[every text node part/.style={align=center},left] {Raum\\aller\\Zustände}  -- ++(1,-1);
   \draw[->] (2,2) node[every text node part/.style={align=center},right] {Zustand\\$\ket{ψ}$}  -- ++(-.9,-.9);
   \filldraw (1,1) circle (1pt) node[right] {$\ket{ψ}$};
   \end{tikzpicture}
   \end{center}
   Darstellung des Zustandes $\ket{ψ}$ in einer Basis. \\
   Bisher: $\ket{\text{Wellenpaket}}$. \\
   Ortsdarstellung: $ψ(x) = \abs{ψ} e^{iϕ}$ \\
   \begin{center}
   \begin{tikzpicture}
     \draw[->] (-2,0) -- ++(4,0) node[below right] {$x$};
     \draw[->] (-2,0) -- ++(0,1.5) node[above left] {$\abs{ψ(x)}$};
     \draw[domain=-2:2,smooth] plot ({\x},{exp(-2*\x*\x)});
     \draw[red,->] (1.5,0) --++(0,1.5) node[above right] {$ϕ(x)$};
     \draw[red] (-2,.5) -- ++(3.6,0) node[right] {$0$};
   \end{tikzpicture}
   \end{center}
   Impulsdarstellung: $\tilde ψ(k) = \abs*{\tilde ψ} e^{iϕ}$ \\
   \begin{center}
   \begin{tikzpicture}
     \draw[->] (-2,0) -- ++(4,0) node[below right] {$\hbar k = p$};
     \draw[->] (-2,0) -- ++(0,1.5) node[above left] {$\abs*{\tilde ψ(k)}$};
     \draw[domain=-2:2,smooth] plot ({\x},{1.5*exp(-3*\x*\x)});
     \draw[red,->] (1.5,0) --++(0,1.5) node[above right] {$\tildeϕ(x)$};
     \draw[red] (-2,.5) -- ++(3.6,0) node[right] {$0$};
   \end{tikzpicture}
   \end{center}
   \vfill
   \end{minipage}\\
   Skalarprodukt\\
   \begin{minipage}{.45\textwidth}
   \begin{align*}
   \angl{\v e_x, \v e_x} &= \v e_x · \v e_x = 1 \tag*{Normiert} \\
   \angl{\v e_x, \v e_y} &= 0 \tag*{Orthogonal} \\
   \angl{\v v, a \v w + b \v x} &= a \angl{\v v, \v w} + b \angl{\v v, \v x} \\
   \intertext{"`nützlich"' um Koordinaten zu extrahieren:}
   \angl{\v e_x, \v P} &= \v e_x · (x \v e_x + y \v e_y) = x
   \end{align*}
   \end{minipage}
   \hfill
   \begin{minipage}{.45\textwidth}
   \begin{align*}
   \braket{φ|ψ} &\underarrow[=]{Ortsdarstellung} ∫ φ^{\ast}(\v x) ψ(\v x) \d^3 x \\
   &\underarrow[=]{Impulsdarstellung} ∫ \tilde φ^{\ast}(\v k) \tilde ψ(\v k) \d^3 k \\
   \intertext{"`nützlich"' um Wahrscheinlichkeitsamplituden zu extrahieren}
   \end{align*}
   \end{minipage}
\catcode`(=\active
\catcode`)=\active
#+END_EXPORT
   #+ATTR_LATEX: :options [1D-Wellenpaket]
   #+begin_ex latex
   Basis: Zustände mit wohldefiniertem Impuls $\hbar k$
   \[\ket{k} \estimates \text{ de Broglie Wellen}\]
   Wellenpaket ist eine Summe (Superposition) von de Broglie Wellen
   \[\ket{\text{Wellenpaket}} = \ket{ψ_{WP}} = ∫_{-∞}^{+∞} \underarrow[\tilde ψ(k)]{Koordinate} \overarrow[\ket{k}]{Basisvektor / Impuls Basis} \d k\]
   $\estimates$ Darstellung von $\ket{ψ_{WP}}$ in Impulsbasis. \\
   Korrdinate / Wahrscheinlichkeits-Amplitude von $\ket{k'} \to$ Impuls $\hbar k'$ zu messen:
   \begin{align*}
   \braket{k'|ψ_{WP}} &= \bra{k'} ∫ \tilde ψ(k) \ket{k} \d k = ∫ \bra{k'} \tilde ψ(k) \ket{k} \d k \\
   &= ∫ \tilde ψ(k) \braket{k'|k} \d k \\
   \braket{k'|k} &= ∫ \frac{1}{\sqrt{2π}} e^{-ik' x} \frac{1}{\sqrt{2π}} e^{ikx} \d x = \frac{1}{2π} ∫ e^{i(k - k')x} \d x = δ(k - k') \\
   \braket{k'|ψ_{WP}} &= ∫ \tilde ψ(k) δ(k - k') \d k = \tilde ψ(k')
   \end{align*}
   #+end_ex

#   \begin{tikzpicture}
#   \wigglecircle{2.5}{.5}{20}{0}{0}
#   \draw[->] (2,2) node[every text node part/.style={align=center},right] {Zustand\\$\ket{ψ}$}  -- ++(-.9,-.9);
#   \filldraw (1,1) circle (1pt);
#   #################### Bloch Kugel an Stelle x
#   \begin{align*}
#   \braket{x | ψ} &= f(x) = e^{i k x} \\
#   (\underarrow[v]{\ket{ψ}}, \underarrow[w]{\ket{φ}}) &↦ \uarrow[\text{Zahl}]{\braket{ψ | φ}} \\
#   \ket{ψ} &= a \ket{\uparrow} + b \ket{\downarrow} \\
#   \intertext{Bloch Kugel:}
#   ###################
#   \ket{ψ_{WP}} &= ∫_{-∞}^{+∞} \tilde ψ(k) \ket{k} \d k \\
#   \intertext{$φ, ψ$ Basiselemente $⇒$ orthonormal:}
#   \braket{ψ|φ} &= 0 \\
#   \braket{φ|φ} &= \braket{ψ|ψ} = 1 \\
#   \end{align*}
   Ortsdarstellung von $\ket{ψ_{WP}}$ \\
   "Ortskoordinate": $\braket{x | ψ_{WP}}$
   \begin{align*}
   \braket{x | ψ_{WP}} &= ψ_{WP}(x) = \bra{x} ∫_{-∞}^{+∞} \tilde ψ(k) \ket{k} \d k = ∫_{-∞}^{+∞} \tilde ψ(k) \underbrace{\braket{x|k}}_{\frac{1}{\sqrt{2π}} e^{i k x}} \d k \\
   &= \frac{1}{\sqrt{2π}} ∫_{-∞}^{+∞} \tilde ψ(k) e^{i k x} \d k \\
   \end{align*}
   Ortswellenfunktion $ψ(x)$ ist eine Darstellung von $\ket{ψ_{WP}} \estimates$ Ortsdarstellung. \medskip
   $\tilde ψ(k)$ ist eine andere Darstellung vom Zustand $\ket{ψ_{WP}} \estimates$ Impulsdarstellung. \medskip
   Das Ergebnis von Rechnungen hängt nicht ab von der Darstellung / Basis ab $\to$ die Berechnung kann in einer
   bestimmten Basis sehr einfach sein. Zum Beispiel: Wellenpaket Dynamik ist in der Impulsdarstellung einfach.
** Observable (beobachtbare Gröhen) und Operatoren
   Observablen können mit Hilfe von Operatoren extrahiert werden.
   #+ATTR_LATEX: :options [Impuls-Operator]
   #+begin_ex latex
   $\hat p$. Das $\hat{}$ symbolisiert Operator $\ket{ψ} ↦ \ket{ψ'}$. \\
   Eingenschaften:
   \[\hat p \underarrow[\ket{k}]{Ortsdarstelung\\de Broglie Welle} = \overarrow[\hbar k]{Zahl\\entspricht Impuls [$\si{\kilogram\meter\per\second}$]} \ket{k}\]
   $\ket{k}$ ist ein /spezieller/ Zustand, weil der Impulsoperator den Zustand nicht "ändert", sondern nur mit einer Zahl multipliziert.
   Daraus Folgt, dass der Zustand $\ket{k}$ einem wohldefiniereten/scharfen Impuls entspricht. $\ket{k}$ nennt man Impuls-Eigenzustand. \medskip
   Erwartungswert: Was erwarten man für den Mittelwert des Impulses?
   \[\overarrow[\bar p]{Mittelwert} = ∫_{-∞}^{+∞} p \underarrow[P(p)]{Probability\\Wahrscheinlichkeit} \d p = \hbar ∫_{-∞}^{+∞} k' \overbrace{\abs{\tilde ψ(k')}^2}^{\mathclap{\text{Für de Broglie Welle: }\tilde ψ(k) = δ(k' - k)}} \d k' = \hbar k\]
   In Dirac Notation
   \[\braket{k | \hat p | k} = \braket{k | \hbar k | k} = \hbar k \underbrace{\braket{k | k}}_{\mathbb{1}}\]
   Erwartungswert / Mittelwert ist $\v p = \hbar k ⇒$ zwei Möglichkeiten:
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
  \foreach \x in {0,8}{
    \draw[->] (\x, 0) -- ++(7, 0) node[below] {\#Experimente};
    \draw[->] (\x, 0) -- ++(0, 3) node[above left] {Impuls};
    \draw (\x, 1.5) -- ++(7,0);
    \foreach \c in {1,...,5}{
      \draw (\x + 0.5*\c, .1) -- ++(0,-.2) node[below] {$\c$};
      }
  }
  \node[left] at (0,1.5) {$\bar p = \braket{\hat p}$};
  \foreach \x in {1,...,13}{
    \node[cross out, draw=black, minimum size=4pt,inner sep=0pt,outer sep=0pt] at (.5*\x, 1.5 + .3*rand) {};
    }
  \foreach \x in {1,...,13}{
    \node[cross out, draw=black, minimum size=4pt,inner sep=0pt,outer sep=0pt] at (.5*\x + 8, 1.5) {};
  }
  \node[red] at (3.5,-1) {Unscharf};
  \node[green] at (11.5,-1) {Scharf};
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Obwohl beide	den gleichen Mittelwert	können diese Messreihen nicht das gleiche System beschreiben. $\to$ Berechne Varianz:
   \[\VAR(p) = \braket{\v p^2} - \braket{\hat p}^2\]
   Für Impulseigenzustand $\ket{k}$ \\
   Notation $\braket{\hat p} := \braket{ψ|\hat p| ψ}$ \\
   Jetzt speziell $\ket{ψ} = \ket{k}$
   \begin{align*}
   \braket{\hat p^2} &= \braket{k | \hat p \hat p | k} = \braket{k | \hat p \hbar | k} = \hbar k \braket{k | \hat p | k} = \hbar^2 k^2 \underbrace{\braket{k | k}}_{\mathbb{1}} \\
   \braket{\hat p}^2 &= (\braket{k | \hat p | k})^2 = (\hbar k)^2 \underbrace{\braket{k | k}}_{\mathbb{1}} \\
   \Aboxed{\VAR(p) &= 0 \qquad \text{für Zustand } \ket{k}}
   \end{align*}
   Alle Messungen ergeben exakt den gleichen Wert; es gibt keine Streuung der Messwerte $⇒$ Impuls scharf / wohldefiniert.
   #+end_ex
   #+begin_remark latex
   Dieser Zustand existiert nur in beliebig guter Nährung!
   #+end_remark
   \medskip Darstellung von Operatoren
   \[\hat p \ket{k} = \hbar k \ket{k}\]
   Darstellung des Impulsoperator in Impulsdarstellung $\estimates$ einfach nur Zahl. \medskip
   Wie sieht das in Ortsdarstellung aus?
   \begin{align*}
   \ket{k} &\mapsto e^{i k x} \ket{x} \\
   \hat p \ket{k} = \hbar k \ket{k} &\mapsto \hbar k (e^{i k x} \ket{x}) = -i \hbar \pp{}{x} (e^{i k x} \ket{x}) \\
   \intertext{Impulsoperator in Ortsdarstellung:}
   \hat p \underarrow[:=]{Ortsdarstellung} - i \hbar \pp{}{x} \\
   \end{align*}
   #+begin_remark latex
   \begin{align*}
   \braket{x | \hat p | ψ} = ∫ \d p \braket{x|p} \braket{p|\hat p | ψ} \\
   &= \frac{1}{\sqrt{2π}} ∫ \d k e^{i k x} \hbar k ψ(k) = -i \hbar \pp{}{x} ψ(x)
   \end{align*}
   #+end_remark
   Impuls Erwartungswert für allgemeine Wellenfunktion $ψ(x)$ für ein Teilchen:
   \begin{align*}
   \overarrow[\bar p_x]{Bezüglich einem $ket{ψ}$} &= \braket{ψ | \hat p_x | ψ}	\underarrow[=]{Ortsdarstellung} ∫_{-∞}^{+∞} ψ^{\ast}(x) (\frac{\hbar}{i} \pp{}{x}) ψ(x) \d x \\
   &= ∫_{-∞}^{+∞} \underbrace{\frac{1}{\sqrt{2π}} ∫ \tilde ψ^{\ast}(k') e^{i k' x} \d k'}_{ψ^{\ast}(x)} \frac{\hbar}{i} \pp{}{x} \underbrace{\frac{1}{\sqrt{2π}} ∫ \tilde ψ(k'') e^{i k'' x} \d k''}_{ψ(x)} \\
   &= ∫_{-∞}^{+∞}\d k' ∫_{-∞}^{+∞} \d k'' \tilde ψ^{\ast}(k') \tilde ψ(k'') \hbar k'' \underbrace{\frac{1}{2π} ∫ e^{i(k'' - k') x} \d x}_{δ(k'' - k')} \\
   &= ∫_{-∞}^{+∞} \d k' \underbrace{\tilde ψ^{\ast}(k') \tilde ψ(k')}_{P(k')} \hbar k' = ∫_{-∞}^{+∞} \d k' (\hbar k') P(k') = \braket{\hbar k}
   \end{align*}
   \medskip
   Gleichzeitige Messung von 2 Observablen $\hat A$ und $\hat B$. Wenn es einen Eigenzustand zu $\hat A$ und $\hat B$ gibt, dann ist das möglich:
   \begin{align*}
   \hat A \ket{a, b} &= a \ket{a, b} \\
   \hat B \ket{a, b} &= b \ket{a, b} \\
   \intertext{aber auch:}
   \hat A \hat B \ket{a, b} &= \hat A b \ket{a, b} = a b \ket{a, b} \\
   \hat B \hat B \ket{a, b} &= \hat B a \ket{a, b} = b a \ket{a, b} \\
   \string(\hat A \hat B - \hat B \hat A\string) \ket{a, b} &= 0 \\
   \intertext{$\hat A \hat B - \hat B \hat A$ Kommutator, Kurzschreibweise:}
   [A, B] &= 0
   \end{align*}
   Für vertauschende Operatoren gibt es gemeinsame scharfe Observablen. \\
   Heisenberg Unschärfe für Ort und Impuls \\
   Ortsdarstellung:
   \begin{align*}
   [\hat x, \hat p] &= \hat x \hat p - \hat p \hat x \\
   &= [x (-i \hbar) \pp{}{x} + i \hbar \pp{}{x} x] \\
   &= [-i \hbar x \pp{}{x} + i \hbar + i \hbar x \pp{}{x}] \\
   &= i \hbar
   \end{align*}
   $⇒$ Operatoren vertauschen nicht! $⇒$ es gibt keinen Eigenzustand zu $\hat x$ und $\hat p$! \\
   Theoretische Quantenmechnik: $[A, B] = i\const$
   \[⇒ \VAR(A) VAR(B) \geq \frac{\const}{2}\]
   Energie-Operator für ein freies Teilchen, klassisch: \\
   Impulsdarstellung (in Impulsdarstellung: $\hat p \to p$):
   \[\text{klassisch: } H = \frac{p^2}{2m} \to \text{Quantenmechanik: } \hat H = \frac{{\hat p}^2}{2m}\]
   Erwartungswert der Energie für Impuls Eigenzustand:
   \begin{align*}
   \hat H \ket{k} &= \frac{1}{2m} \hat p \hat p \ket{k} = \frac{\hbar^2 k^2}{2m} \ket{k} \\
   \hbar H &= \braket{k | \hat H | k} = \frac{\hbar^2 k^2}{2m} \braket{k | k} = \hbar ω_{dB} \\
   [\hat p^2, \hat p] &= \hat p^3 - \hat p^3 = 0
   \end{align*}
   Auch hier: Zustand unverändert, die Zahl gibt die Energie [$\si{\joule}$] an.
   $⇒$ $\ket{k} ist Energie Eigenzustand$
   \[\hat E \ket{ψ_E} = E \ket{ψ_E}\]
   $\hat H$ in Ortsdarstellung:
   \[\frac{\hat p \hat p}{2m} \xrightarrow{\text{Ortsdarstellung}} \frac{1}{2m}(- i \hbar \pp{}{x} - i \hbar \pp{}{x}) = -\frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2}\]
   #+ATTR_LATEX: :options [de Broglie Welle]
   #+begin_ex latex
   \[e^{i(k_{dB} x - ω_{dB} t)} \underarrow[↦]{$\hat E = i\hbar \pp{}{t}$} \underbrace{\hbar ω_{dB}}_{\mathclap{\text{Energie}}} e^{i k_{dB} x - ω_{dB} t}\]
   $⇒$ damit der Energie-Operator die Energie "liefert" muss er als
   \[\hat E = i \hbar \pp{}{t}\]
   definiert sein.
   #+end_ex
   Allgemein auch gültig, das heißt Energie Eigenzustände haben die einfache Zeitentwicklung
   \[e^{-i \frac{E}{\hbar}t}\]
   Deshalb sind diese Zustände eine gute Basis, um Zeitdynamik zu beschreiben. \medskip
   Generell: Jede klassische Größe
   \[a = f(\v x, \v p) ⇒ \hat a = f(\v x, \v p)\]
   zum Beispiel Drehimpuls: $\v L = \v x × \v p$
   \[H = κ \v L^2 \to \hat H = κ(\hat{\v x} × \hat{\v p})^2, \qquad [L_x, L_y] = i L_z\]
   Es gibt aber auch nicht-klassische Größen (zum Bespiel Spin).
** Die Schrödiger Gleichung (nicht relativistische Quantenmechanik)
   Klassische Gesamtenergie: $E$
   \[E = E_{\text{kin}} + E_{\text{pot}}\]
   Allgemeiner: $H$ Hamiltonfunktion
   \[H = \frac{\v p^2}{2m} + V(\v x) ↦ \hat H = \frac{{\hat{\v p}}^2}{2m} + V(\hat{\v x})\]
   \begin{ibox}{Axiom der nicht-relativisitischen Quantenmechanik}
   Operator	Gleichung:
   \[i \hbar \pp{}{t} \ket{ψ} = \hat H \ket{ψ}\]
   \end{ibox}
   Darstellung im Ortsraum: $\hat x \ket{x} = x \ket{x}$
   \begin{align*}
   \hat{\v x} &↦ \v x \\
   \hat{\v p} &↦ -i \hbar \cvec{\pp{}{x}; \pp{}{y}; \pp{}{z}} = -i \hbar \v ∇ \\
   {\hat{\v p}}^2 &= - \hbar^2 \v ∇^2 = - \hbar^2 \Laplace
   \end{align*}
   \begin{ibox}{Schrödinger Gleichung für nicht-relativischische Quantenmechanik}
   \begin{center}
   $\displaystyle{i\hbar \pp{}{t} ψ(\v x, t) = - \frac{\hbar^2}{2m} \Laplace ψ(\v x, t) + V(\v x) ψ(\v x, t)}$ \\
   \end{center}
   Randbedingung:
   \[∫ \abs{ψ}^2 \d V = 1\]
   \end{ibox}
   Damit wird die Dynamik in allgemeinen Potentialen beschrieben. Die Zeitdynamik kann als Interferenz verstanden werden, wenn
   man die Energie-Eigenzustände $\hat H \ket{ψ_E} = E \ket{ψ_E}$ als Basis verwendet $\to$	Zeitabhängigkeit kommt nur durch die verschiedene Phasenentwicklung der Energie-Eigenzustände zustande.
   
   #+ATTR_LATEX: :options [Drei Zustandsystem]
   #+begin_ex latex
   $\ket{a}, \ket{b}, \ket{c}$ Basiszustände, Eigenschaften:
   \begin{align*}
   \braket{a | b} &= \braket{ a | c} = \braket{b | c} = 0 \tag{Orthonormalität} \\
   \braket{a | a} &= \braket{b | b} = \braket{c | c} = 1 \tag{Normierung}
   \end{align*}
   Operatoren:
   \begin{align*}
   \hat A \ket{a} &= a \ket{a} \\
   \hat B \ket{b} &= b \ket{b} \\
   \hat C \ket{c} &= c \ket{c} \\
   \end{align*}
   Mögliche Definitionen:
   \begin{align*}
   \hat A &= a \ket{a} \bra{a} + \ket{b} \bra{c} + \ket{c} \bra b \\
   \hat B &= b \ket{b} \bra{b} \\
   \hat C &= c \ket{c} \bra{c} \\
   \end{align*} \\
   Anwenden auf die Basiszustände:
   \begin{align*}
   \hat A \ket{a} &= (a \ket{a} \bra{a} + \ket{b} \bra{c} + \ket{c} \bra b) \ket{a} = a \ket{a} \\
   \hat A \ket{b} &= (a \ket{a} \bra{a} + \ket{b} \bra{c} + \ket{c} \bra b) \ket{b} = \ket{c} \\
   \hat B \ket{b} &= (b\ket{b}\bra{b}) \ket{b} = b \ket{b} \\
   \intertext{Erwartungswert für $a$:}
   \braket{\hat A}_{\ket{a}} &= \braket{a | \hat A | a} = \braket{a | a | a} = a \braket{a | a} = a \\
   \VAR(A)_{\ket{a}} &= \braket{\hat A^2} - \braket{\hat A}^2 = \braket{a | \hat A a | a} - a^2 = 0 \\
   \braket{b | \hat A | b} &= \braket{b | c} = 0  \\
   \VAR(A)_{\ket{b}} &= \braket{b | \hat A^2 | b} - \braket{b | \hat A | b}^2 = 1 \\
   \end{align*}
   \[[\hat A, \hat B] = \hat A \hat B - \hat B \hat A = b \{\ket{c} \bra{b} + \ket{b} \bra{c}\} \neq 0\]
   #+end_ex
* Beispiele für Einteilchen Quantenmechanik
** Streuung von freien Teilchen an einer Potentialstufe
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}
   \draw[->] (0,0) -- ++(7,0) node[below] {$x$};
   \draw[->] (0,0) -- ++(0,3) node[left] {$E$};
   \draw (7,1.5) -- ++(-4,0) -- ++(0,-1.6) node[below] {$0$};
   \draw[<->] (5.5, 1.5) -- ++(0,-1.5) node[midway, right] {$V_0$};
   \draw[->] (.5, 1) -- ++(2,0) node[midway,above] {$E_{kin} < V_0$};
   \node[below] at (1.5, 0) {Bereich $\text{I}$};
   \node[below] at (5, 0) {Bereich $\text{II}$};
   \end{tikzpicture}
   \end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Lösen Schrödinger Gleichung in *einer* Dimension in Ortsdarstellung: $\v x \to x$
   \[\v x ↦ x: \qquad i \hbar \pp{}{t} ψ(x, t) = - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} ψ(x,t) + V(x) ψ(x, t)\]
   Suchen Lösungen mit Separationsansatz
   \[ψ(x, t) = e^{-i \frac{E}{\hbar}t} ϕ(x)\]
   Warum: Die Zeitentwickung ist "`nur"' Rotation in komplexen Zahlenebene, dieser Zustand $\ket{ψ_E}$ in	Ortsdarstellung $ψ(x, t)$ ist Energie-Eigenzustand.
   \begin{align*}
     \hat E \ket{ψ_E} &= E \ket{ψ_E} \to i \hbar \pp{}{t} ψ(x, t) = i\hbar ϕ(x) (-i \frac{E}{\hbar} e^{i \frac{E}{\hbar}t}) = E e^{-i \frac{E}{\hbar}t} ϕ(x) = E ψ(x, t)\ \checkmark \\
   E &= E_{\text{ges}} = E_{\text{kin}}^{\text{I}} \\
   \intertext{Gleichung für $ϕ(x)$ folgt aus Einsetzen von $ψ(x, t)$ in Schrödinger Gleichung:}
   E e^{-i \frac{E}{\hbar}t} ϕ(x) &= - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} e^{-i \frac{E}{\hbar}} ϕ(x) + V(x) e^{-i \frac{E}{\hbar}t} ϕ(x) \\
   \intertext{Man erhält eine Differentialgeilchung zweiter Ordnung}
   E ϕ(x) &= - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} ϕ(x) + V(x) ϕ(x) \\
   \end{align*}
   Fall 1: $E_{\text{kin}} < V_0$, klassisch wird das Teilchen reflektiert
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
   \begin{center}
   \begin{tikzpicture}
   \draw[->] (0,0) -- ++(7,0) node[below] {$x$};
   \draw[->] (0,0) -- ++(0,3) node[left] {$E$};
   \draw (7,1.5) -- ++(-4,0) -- ++(0,-1.6) node[below] {$x = 0$};
   \draw[<->] (5.5, 1.5) -- ++(0,-1.5) node[midway, right] {$V_0$};
   \draw[->] (.5, 1) -- ++(2,0) node[midway,above] {$E_{kin} < V_0$};
   \node[below] at (1.5, 0) {Bereich $\text{I}$};
   \node[below] at (5, 0) {Bereich $\text{II}$};
   \end{tikzpicture}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   \end{center}
   \text{Bereich I}:
   \[V(x) = 0 ⇒ E ϕ_{\text{I}}(x) = - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} ϕ_{\text{I}}(x) \quad E = E_{\text{kin}} = \frac{\hbar^2 k^2}{2m}\]
   kennen Lösung:
   \[ϕ_{\text{I}}(x) = A e^{i k x} + B e^{- i k x}\]
   Check:
   \begin{align*}
     - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} ϕ_{\text{I}}(x) &= - \frac{\hbar^2}{2m} (A (-k^2) e^{i k x} + B (-k^2) e^{-ikx}) \\
                                                                          &= \underbrace{\frac{\hbar^2 k^2}{2m}}_{E_{\text{kin}}^{\text{I}}} ϕ_{\text{I}}(x) = \hbar ω_{dB} ϕ_{\text{I}} ϕ_{\text{I}}(x) = E ϕ_{\text{I}}(x) \checkmark
   \end{align*}
   Man erhält die Superposition von zwei Wellen, eine in positive \(x\)-Richtung und eine in negative \(x\)-Richtung
   \[ψ_{\text{I}} (x,t) = e^{-i \frac{E}{\hbar}t} ϕ(x) \underarrow[=]{$E = \frac{\hbar^2 k^2}{2m} = ω_{dB} \hbar$} A e^{i(k x - ω_{dB} t)} + B e^{i(-k x - ω_{dB} t)}\]
   Bereich II:
#   \begin{tikzpicture}
#   \draw[->] (0,0) -- ++(7,0) node[below right] {$x$};
#   \draw[->] (0,0) -- ++(0,3) node[above left] {$E$};
#   \draw[patter = stripen] (7,1.5) -- ++(-4,0) -- ++(0,-1.6) node[below] {$0$};
#   \draw[<->] (5.5, 1.5) -- ++(0,-1.5) node[midway, right] {$V_0$};
#   \draw (-.1,1) node[left] {$E_{\text{kin}}$};
#   \end{tikzpicture}
   \[E ϕ_{\text{II}} (x) = - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} ϕ_{\text{II}}(x) + V_0 ϕ_{\text{II}}(x)\]
   Allgemeine Lösung:
   \[ϕ_{\text{II}}(x) = C e^{-α x} + D e^{α x} \quad\text{mit}\quad α^2 = \frac{2m}{\hbar^2}(V_0 - E)\]
   Für den Fall $V_0 > E$ ist $α$ reell und, Kopffizient $D = 0$ macht $ϕ_{\text{II}}$ quadratintegrabel
   \[∫_0^∞ \abs{ϕ}^2 \d x = 0\]
   Bemerkung: Für $V_0 = 0 \to α$ imaginär, wie in Bereich I besprochen.
   Die spezielle Lösung des Problems folgt aus Randbedingungen bei $x = 0$:
   \begin{gather*}
   \begin{aligned}
   \intertext{Wahrscheinlichkeit muss eindeutig sein}
   ϕ_{\text{I}}(x = 0, t) &= ϕ_{\text{II}}(x = 0, t) \\
   \intertext{Impuls muss eindeutig sein}
   \dd{ϕ_{\text{I}}}{x}\Big|_{x = 0} &= \dd{ϕ_{\text{II}}}{x}\Big|_{x = 0} \\
   \end{aligned} \\
   \left.\begin{matrix}
   ⇒ A + B = C \\
   ⇒ A ik - B ik = - C α \\
   \end{matrix}\right\}
   \begin{matrix}
   B = A \frac{i k + α}{i k - α} \\
   C = A \frac{2i k}{i k - α} \\
   \end{matrix}
   \end{gather*}
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
  \draw[->] (0,0) -- ++(10,0) node[below] {$x$};
  \draw[->] (0,0) -- ++(0,3) node[left] {$\Re\{ψ\}$};
  \draw[green, domain=0:5.5, smooth, samples=100] plot ({\x},{2.5*sin(108*\x + 90)});
  \draw[domain=0:5.5, smooth, samples=100] plot ({\x},{-2.5*sin(108*\x + 90)});
  \draw[smooth, domain=0:4, shift={(5.5, 0)}] plot ({\x}, {1.46946*exp{-3.81240*\x}});
  \draw[green, smooth, domain=0:4, shift={(5.5, 0)}] plot ({\x}, {-1.46946*exp{-3.81240*\x}});
  \draw (5, 3) node[above] {$V_0 = 0$} -- ++(0, -6);
  \filldraw (5, 2.5) circle (1pt);
  \filldraw[green] (5, -2.5) circle (1pt);
  \draw (5.5, 0) node[below] {$x = 0$} -- ++(0,3);
  \foreach \y in {0,1,2,3,4}
    \draw (5.5, 3 - .1*\y) -- ++(.3,.3);
  \node[right, every text node part/.style={align=left}] at (6, 3) {$V_0 > E_{\text{kin}}$ \\ klassich verboten};
  \node[right] at (7,1.0) {$t = 0$};
  \draw (6, .5) edge[<-,out=40, in=180] (7,1.0);
  \draw[|-|] (0,-3) -- ++(3.333, 0) node[fill=white,midway] {$λ_{dB}$};
  \node[green, right] at (7, -1.5) {$\displaystyle{t = \frac{h}{2E}\quad e^{- \frac{iE}{\hbar}t} = e^{-iπ}}$};
  \begin{scope}[shift={(7, -5.5)}]
    \draw(-.3, -.3) rectangle (5.3,3.45);
    \draw[->] (0, 1) -- ++(3,0) node[below] {$\Re \{ψ\}$};
    \draw[->] (1, 0) -- ++(0,3) node[left] {$\Im \{ψ\}$};
    \draw[green] (1,1) --++(-1,-1);
    \filldraw[green] (0,0) circle (1pt);
    \draw (1,1) --++(1,1);
    \filldraw (2,2) circle (1pt);
    \draw (2,2) edge[->, out=135, in=45] (0,2);
    \draw (1.8, 2.3) edge[out=60, in=40] (2.2,2.7);
    \node[right,every text node part/.style={align=left}] at (2.2, 2.7) {rotiert proportional \\ zu Energie};
  \end{scope}
  \draw (5.2, -2.6) edge[->, out=-40, in=170] (6.5, -3.2);
  \begin{scope}[shift={(0,-8)}]
  \draw[->] (0,0) -- ++(10,0) node[below] {$x$};
  \draw[->] (0,0) -- ++(0,3) node[left] {$\Re\{ψ\}$};
  \draw[domain=0:5.5, smooth, samples=100] plot ({\x},{2.5*(sin(108*\x + 90))*(sin(108*\x + 90))});
  \draw[smooth, samples=100,domain=0:4, shift={(5.5, 0)}] plot ({\x}, {0.86372*exp{-5.18889*\x}});
  \draw (5, 3) node[above] {$V_0 = 0$} -- ++(0, -3);
  \filldraw (5, 2.5) circle (1pt);
  \draw (5.5, 0) node[below] {$x = 0$} -- ++(0,3);
  \foreach \y in {0,1,2,3,4}
    \draw (5.5, 3 - .1*\y) -- ++(.3,.3);
  \draw[|-|] (1.6666,-.5) -- ++(1.6666, 0) node[fill=white,midway] {$\displaystyle{\frac{λ_{dB}}{2}}$};
  \node[every text node part/.style={align=center}] at (2.5, -1.5) {Interferenz zwischen\\einlaufender und reflektierter\\Welle};
  \node[every text node part/.style={align=center}] at (9, 1) {Teilchen kann im\\klassisch verbotenen Bereich\\detektiert werden; nimmt\\aber exponentiell ab.};
  \draw (5.625, .125) edge[->, out=65, in=210] (6.9, 1.20);
  \end{scope}
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Fall 2: $E_{kin} > V_0$, Fall $E_{kin} \gg V$ wurde im Abschnitt 2.7 - Interferometer diskutiert.
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
 \draw[->] (0,0) -- ++(7,0) node[below] {$x$};
 \draw[->] (0,0) -- ++(0,3) node[left] {$E$};
 \draw (7,1.5) -- ++(-4,0) -- ++(0,-1.6) node[below] {$x = 0$};
 \draw[<->] (5.5, 1.5) -- ++(0,-1.5) node[midway, right] {$V_0$};
 \draw[->] (.5, 2) -- ++(2,0) node[midway,above] {$E_{kin} > V_0$};
 \node[below] at (1.5, 0) {Bereich $\text{I}$};
 \node[below] at (5, 0) {Bereich $\text{II}$};
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Analoge Vorgehensweise; Im Bereich II findet man propangierende Lösungen $\estimates$ de Broglie Wellen:
   \[ϕ_{\text{II}}(x) = C e^{i k_2 x} \quad\text{mit}\quad \frac{\hbar^2 k_2^2}{2m} = E - V_0, k_2 \text{ reell}\]
   Randbedingung bei $x = 0$:
   \[B = \frac{k - k_2}{k + k_2} \qquad C = \frac{2k}{k + k_2} A\]
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
  \draw[->] (0,0) -- ++(10,0) node[below] {$x$};
  \draw[->] (0,0) -- ++(0,2) node[left] {$\Re\{ψ\}$};
  \draw[smooth, samples=100, domain=0:5.5] plot ({\x}, {1.5*sin(180*\x)});
  \draw[smooth, samples=100, domain=5.5:10] plot ({\x}, {-1.5*sin(90*\x - 45)});
  \draw (5.5, .1) -- ++(0, -.2) node[below] {$x = 0$};
  \draw[|-|] (1.5, -1.75) -- ++(2, 0) node[midway, fill=white] {$λ_{dB}$};
  \draw[|-|] (5.5, -1.75) -- ++(4, 0) node[midway, fill=white] {$λ_{dB}$};
  \draw[dashed] (5.5, 2) --++(0, -6);
  \begin{scope}[shift={(0,-4)}]
    \draw[->] (0,0) -- ++(10,0) node[below] {$x$};
    \draw[->] (0,0) -- ++(0,2) node[left] {$\abs{ψ}^2$};
    \draw (5.5, .1) -- ++(0, -.2) node[below] {$x = 0$};
    \draw[domain=0:5.5, smooth, samples=100] plot ({\x}, {.3*sin(\x*278) + 1});
    \draw[domain=5.5:10] plot ({\x}, {1.3});
  \end{scope}
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
** Tunneleffekt durch eine Potentialbarriere
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
  \draw[->] (-3, 0) -- ++(2, 0) node[below] {$x$};
  \draw[->] (-3, 0) -- ++(0, 3) node[left] {$E$};
  \draw[->] (0, 0) -- ++(4, 0) node[midway, below] {$\text{Bereich I}$} -- ++(0, 2) -- ++(3, 0) -- ++(0, -2) -- ++(4, 0) node[midway, below] {$\text{Bereich III}$};
  \draw[<->] (.5, 0) -- ++(0, 1.25) node[midway, right] {$E_{kin}$};
  \draw[->] (0, 1.25) -- ++ (1.5, 0);
  \draw[|-|] (4, 2.3) -- ++(3, 0) node[midway, fill=white] {$d$};
  \draw[<->] (5.5, 2) -- ++(0, -2) node[midway, right] {$V_0$} node[below] {$\text{Bereich II}$};
  \node[right] at (-3, -1) {Lösung: Ansätze wie vorher, 4 Randbedingungen};
  \draw (4, 0) -- ++(0, -8);
  \draw (7, 0) -- ++(0, -8);
  \begin{scope}[shift={(0, -4)}]
    \draw[->] (0,0) -- ++(11, 0);
    \draw[->] (0,0) -- ++(0, 2) node[left] {$\Re\{ψ\}$};
    \draw[domain=1.5:5.5, shift={(-1.5,0)}, smooth, samples=100] plot ({\x},{-1.5*sin(103.5*\x + 90)});
    \draw[smooth, domain=0:3, shift={(4, 0)}] plot ({\x}, {1.3*exp{-1*\x}});
    \draw[domain=0:4, shift={(7,0)}, smooth, samples=100] plot ({\x},{.065*sin(103.5*\x + 90)});
    \filldraw (4, 1.3) circle (1pt);
    \filldraw (7, .065) circle (1pt);
    \draw[|-|] (0.25, 1.7) -- ++(3.47, 0) node[midway, fill=white] {$λ_{dB}$};
    \draw[|-|] (7, .3) -- ++(3.47, 0) node[midway, fill=white] {$λ_{dB}$};
    \draw[<-] (5.3, .5) -- ++ (.5, 1) node[above, every text node part/.style={align=center}] {exponentieller\\Abfall};
    \draw[<-] (1, -.5) -- ++(-1, -.5) node[left, every text node part/.style={align=left}] {Interferenz von\\ein- und auslaufender\\ Welle};
    \node[below, every text node part/.style={align=left}] at (9, 0) {transmittierte\\de Broglie Welle};
  \end{scope}
  \begin{scope}[shift={(0, -8)}]
    \draw[dotted] (1.11, 0) -- ++(0, 4);
    \draw[dotted] (2.85, 0) -- ++(0, 4);
    \draw[->] (0,0) -- ++(11, 0);
    \draw[->] (0,0) -- ++(0, 2) node[left] {$\abs{ψ}^2$};
    \draw[smooth, samples=100, domain=1.5:5.33, shift={(-1.5, 0)}] plot ({\x}, {1.5*sin(103.5*\x + 90)*sin(103.5*\x + 90)});
    \draw[smooth, domain=0:3.17, shift={(3.83, 0)}] plot ({\x}, {1.44*exp(-.8*\x)});
    \draw[domain=0:4, shift={(7,0)}, smooth, samples=100] plot ({\x},{.116});
    \node[below, every text node part/.style={align=left}] at (9, 0) {Transmissions-Wahrscheinlichkeit\\konstant, weil nur auslaufende Welle};
  \end{scope}
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Bereich II:
   \[\abs{ψ_{\text{II}}}^2 = \frac{4k^2}{k^2 + α^2}\abs{ψ(0)}^2 e^{-2α x}\qquad \hbar α = \sqrt{2m(V_0 - E_{\text{kin}})}\]
   Transmissions Wahrscheinlichkeit:
   \[T = \frac{\abs{ψ_{\text{II}}(d)}^2}{\abs{ψ_{\text{II}}(0)}^2} \propto e^{-2αd}\]
   Exponentiell empfindlich auf Änderungen von Barrierenbreite $d$.
   Anwendung: Scanning tunneling microscope ((STM) - Rastertunnelmikroskop)
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
  \draw (0,0) -- ++(4,0);
  \foreach \x in {0,...,20}
    \draw (\x / 5,0) -- ++(-.1,-.2);
  \node[below,yshift=-3pt] at (2, 0) {Substrat};
  \draw (0,0) -- ++(0,1) ++(0,.2) -- ++(0,2) -- ++(.5, 0);
  \draw (.9,3.2) circle (.4) node[above,yshift=9pt] {$I$};
  \draw[->] (.5,2.8) -- ++(.9,.9);
  \draw (-.2,1) -- ++(.4,0);
  \draw (.4,1.2) -- ++(-.8,0) node[left] {$\sim \SI{4}{\volt}$};
  \draw (1.3, 3.2) -- ++(1, 0);
  \draw[red] (2.3, 3.5) -- ++(1,0) -- ++(0,-2) -- ++(-.5,-1.4) -- ++(-.5,1.4) -- ++(0,2);
  \draw (2.8, 3.2) circle (3pt) node[below,yshift=-1pt] {$x$};
  \draw [->] (2.8, 3.2) -- ++(1,0) node[below] {$y$};
  \draw [->] (2.8, 3.2) -- ++(0,1) node[left] {$z$};
  \node[right] at (2.9, 3.9) {verschiebbar};
  \node[red,right] at (3.3, 2) {Spitze};
  \begin{scope}[shift={(6,0)}]
    \foreach \y/\n/\o in {1/10/0,2/9/.5,3/10/0}{
      \foreach \x in {1,...,\n}
        \draw ({.23*(\x + \o)}, .22*\y) circle (3pt);
    }

    \foreach \y/\n/\o in {1/1/2,2/2/1.5,3/3/1,4/4/.5,5/5/0}{
      \foreach \x in {1,...,\n}
        \draw[red] ({.23*(\x + \o) + .23*2.5}, .22*\y + 1) circle (3pt);
    }
    \draw[|-|] (.23*7,.22*3.5) -- (.23*7,1.11) node[right,midway] {$d$};
    \draw[red] (.23*3, 1+.22*5.7) -- ++(0,1);
    \draw[red] (.23*8, 1+.22*5.7) -- ++(0,1);
    \draw[<-] (1.5, 2.5) -- ++(.5,.5) node[right] {ein Atom an der Spitze};
    \node[above,right] at (2.5, .4) {zum Beispiel Grahpit};
  \end{scope}
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Elektronen können zur Spitze tunneln $⇒$ Strom $\sim \SI{1}{\nano\ampere}$
   \begin{alignat*}{2}
     I &\propto T \propto e^{-2α d} &&\qquad α \sim \SI{1e10}{\per\meter} \\
     d &= \SI{.1}{\nano\meter} &&\qquad T \sim \SI{.13}{} \\
     d &= \SI{1}{\nano\meter} &&\qquad T \sim \SI{2e-9}{} \\
   \end{alignat*}
   extrem empfindlich auf $d ⇒$ atomare Auflösung.
** Kasten-Potential
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
  \draw[->] (0,0) -- ++(15,0) node[below] {$x$};
  \draw[->] (-1,.5) -- ++(0,3) node[left] {$E$};
  \draw[red] (0,4) -- ++(4, 0) node[midway,below] {$V_0 \gg 0$} node[below right] {$V = 0$} -- ++(0,-4) -- ++(7,0) -- ++(0,4) -- ++(4,0) node[midway,below] {$V_0 \gg 0$};
  \node[below] at (2,0) {Bereich I};
  \node[below] at (7.5,0) {Bereich II};
  \node[below] at (13,0) {Bereich III};
  \draw (4,0) -- ++(0,-.2) node[below] {$x = 0$};
  \draw (11,0) -- ++(0,-.2) node[below] {$x = d$};
  \draw[dashed] (4,-.7) -- ++(0,-9.3);
  \draw[dashed] (11,-.7) -- ++(0,-9.3);
  \begin{scope}[shift={(0,-5)}]
  \draw[->] (0,0) -- ++(15,0) node[below] {$x$};
  \draw[domain=0:7, shift={(4,0)}, smooth, samples=100] plot ({\x},{2*cos(95*\x - 31)});
  \draw[smooth, domain=-4:0, shift={(4, 0)}] plot ({\x}, {1.72*exp(\x)});
  \draw[smooth, domain=0:4, shift={(11, 0)}] plot ({\x}, {1.333*1.08*exp(-\x)});
  \draw[|-|] (3.8 * 31 / 360 + 4, 2.2) -- ++(360 / 95, 0) node[midway,fill=white] {$λ_{dB}$} node[above, midway,yshift = 5pt] {freie Welle};
  \node[every text node part/.style={align=left}] at (1,2) {Raten falsche Lösung der\\Schrödinger Gleichung};
  \node[red,every text node part/.style={align=left},right] at (12,1.2) {?\lightning\ Diese Welle "`passt"' nicht\\ $\estimates$ Randbedingungen kann\\ erfüllt werden};
  \draw[red] (11, .75) circle (1);
  \end{scope}
  \begin{scope}[shift={(0,-10)}]
  \draw[->] (0,0) -- ++(15,0) node[below] {$x$};
  \draw[domain=-3.5:3.5, shift={(7.5,0)}, smooth, samples=100] plot ({\x},{-2*cos(64*\x)});
  \draw[smooth, domain=-4:0, shift={(4, 0)}] plot ({\x}, {1.333*1.08*exp(\x)});
  \draw[smooth, domain=0:4, shift={(11, 0)}] plot ({\x}, {1.333*1.08*exp(-\x)});
  \draw (4,0) -- ++(0,-.2) node[below] {$0$};
  \draw (11,0) -- ++(0,-.2) node[below] {$d$};
  \node[every text node part/.style={align=left}] at (1,2) {eine möglich Lösung\\der Schrödinger Gleichung};
  \end{scope}
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Limes $V_0 \to ∞ ⇒$ Lösung in Bereich I + Bereich III $e^{-α x} \to 0$ $⇒$ Randbedingungen für Bereich II:
   \[ψ_{\text{II}}(0) = ψ_{\text{II}}(d) = 0\]
   Suchen Energie-Eigenzustände
   \begin{align*}
     ψ_ε(x, t) &= e^{-i \frac{E}{\hbar}t} ϕ(x) \\
     \intertext{mit}
     ϕ(0) &= ϕ(d) = 0 \\
     - \frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} ϕ(x) &= E ϕ(x)
   \end{align*}
   Lösung:
   \begin{alignat*}{2}
     ϕ(x) &= A e^{i k x} + B e^{-i k x} \\
     \intertext{mit}
     ϕ(x) &= A + B = 0 &&\qquad\to A = - B \\
     ϕ(d) &= A e^{i k d} + B e^{-i k d} = 0 &&\qquad\to A(e^{i k d}  - e^{-i k d}) = 2 A i \sin k d = 0
   \end{alignat*}
   $⇒ k$ kann nur ganz bestimmte / diskrete Werte annehmen: $k d = n π, n ∈ ℕ, n$: Quantenzahlen. \\
   $A$: folgt aus Normierungsbedingung. Lösung für Energie-Eigenzustände in Ortsdarstellung:
   \[ϕ_n(x) = \sqrt{\frac{2}{d}} \sin(\frac{n π}{d}x) \quad\text{mit Energie}\quad E_n = \frac{\hbar^2 π^2}{2md^2} n^2\]
   In Dirac Schreibweise:
   \begin{align*}
     \hat H \ket{ψ_E} &= E \ket{ψ_E} \to \ket{ψ_E} = \ket{n} \\
     \intertext{Definiere $E_G$ für den Grundzustand:}
     E_n &= \frac{\hbar^2 π^2}{2m d^2} n^2 = E_G n^2 \\
     \to \hat H\ket{n} &= E_G n^2 \ket{n}
   \end{align*}
   für den energetisch niedrigsten Zustand = Grundzustand erhält man $E = E_G$
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
  \draw[->] (-.25, 0) -- ++(6,0) node[below] {$x$};
  \draw[->] (0, -.25) -- ++(0,4) node[left] {$E$};
  \draw[->] (1.9,0) -- ++(0,3.5) node[above] {$∞$};
  \draw[->] (4.5,0) -- ++(0,3.5) node[above] {$∞$};
  \foreach \y/\c [count=\i] in {1/1,4/3,9/5}{
    \draw (1.9, \y / 3) node[left] {$E_{\i} = \y E_G$} -- ++(2.6,0) node[right] {$n = \i$};
    \foreach \a in {1,...,\c}
      \draw[<->] (2.2,\y / 3 - \a / 3) -- ++(0,1/3);
  }
  \draw[->,every text node part/.style={align=left}] (6,2) -- ++(3, 0) node[midway,below] {Ortsdarstellung\\ des Zustands} node[midway,above] {zu jeder Energie\\gehört eine\\räumliches\\Wellenpaket};
  \begin{scope}[shift={(10, 0)}]
  \draw[->] (-.25, 0) -- ++(6,0) node[below] {$x$};
  \draw[->] (0, -.25) -- ++(0,4) node[left] {$ψ$};
  \draw[smooth,domain=0:5,samples=100] plot ({\x},{sin(\x*540/5) + 1.5});
  \draw[dotted] (0,1.5) -- ++(5,0);
  \draw (0,1.5) -- ++(-.2,0) node[left] {$0$};
  \draw (5,.2) -- ++(0,-.4) node[below] {$d$};
  \node[right] at (.5,3) {zum Beispiel $n = 3\quad ϕ_3(x)$};
  \end{scope}
\end{tikzpicture}
\end{center}
Typische Darstellung:
\begin{center}
\begin{tikzpicture}
  \draw[->] (1.5, 0) -- ++(4,0) node[below] {$x$};
  \draw[->] (.75, 2) -- ++(0,2) node[left] {$E$};
  \draw[->] (1.9,-.2) node[below] {$0$} -- ++(0,3.9) node[above] {$∞$};
  \draw[->] (4.5,-.2) node[below] {$d$} -- ++(0,3.9) node[above] {$∞$};
  \foreach \y/\c [count=\i] in {1/1,4/3,9/5}{
    \draw (1.9, \y / 3) node[left] {$\y E_G$} -- ++(2.6,0);
    \draw[red,smooth, domain=0:2.6,shift={(1.9, \y / 3)}] plot ({\x}, {.4*sin(\i*\x*180/2.6)});
    \draw[red,->] (4.6, \y / 3) -- ++(0,.5) node[midway,right] {$ψ_{\i}(t = 0)$};
  }
  \draw[->] (7, 2) -- ++(2,0) node[midway,above,green] {$P(x) = \abs{ψ}^2$};
  \begin{scope}[shift={(9, 0)}]
  \draw[->] (1.5, 0) -- ++(4,0);
  \draw[->] (1.9,-.2) node[below] {$0$} -- ++(0,3.9) node[above] {$∞$};
  \draw[->] (4.5,-.2) node[below] {$d$} -- ++(0,3.9) node[above] {$∞$};
  \foreach \y/\c [count=\i] in {1/1,4/3,9/5}{
    \draw (1.9, \y / 3) -- ++(2.6,0);
    \draw[green,smooth, domain=0:2.6,shift={(1.9, \y / 3)}] plot ({\x}, {.4*sin(\i*\x*180/2.6)*sin(\i*\x*180/2.6)});
    \draw[green,->] (4.6, \y / 3) -- ++(0,.5) node[midway,right] {$P$};
  }
  \end{scope}
\end{tikzpicture}
\end{center}
Vorhersage für ein Teilchen anfänglich lokalisiert: \\
\begin{minipage}{.4\textwidth}
 \begin{center}
 \begin{tikzpicture}
  \draw[->] (1.5, 0) -- ++(4,0) node[below] {$x$};
  \draw[->] (.75, 2) -- ++(0,2) node[left] {$E$};
  \draw[->] (1.9,-.2) node[below] {$0$} -- ++(0,3.9) node[above] {$∞$};
  \draw[->] (4.5,-.2) node[below] {$d$} -- ++(0,3.9) node[above] {$∞$};
  \draw[shift={(3.2,0)},smooth,domain=-1.3:1.3] plot ({\x}, {2*exp(-6*\x*\x)});
  \draw (3.2,.2) -- ++(0,-.4) node[below] {$\frac{d}{2}$};
  \draw (3.5,1.5) edge[->, out=65, in=200] (5,2.5);
  \node[right] at (5,2.5) {$ψ_{WP}(x, t = 0)$};
 \end{tikzpicture}
 \end{center}
\end{minipage}
\hfill\begin{minipage}{.50\textwidth}
  $\to$ später?
  \begin{align*}
    \ket{ψ_{WP}}_t &= \sum_{n = 1}^{∞} c_n e^{-i \frac{E_n}{\hbar}t} \ket{n} \\
    \to \text{finde } c_n: \braket{n | ψ_{WP}} &= c_n \\
    \text{Ortsdarstellung: } \ket{n} &= \sin(\frac{nπ}{d}x)
  \end{align*}
\end{minipage}
\begin{center}
\begin{tikzpicture}
    \draw[->] (-.25, 0) -- ++(5, 0) node[below] {$x$};
    \draw[->] (0,-.25) node[below] {$0$} -- ++(0, 3);
    \draw[shift={(2,0)},smooth,domain=-2:2] plot ({\x}, {2*exp(-8*\x*\x)});
    \node[right] at (5,1.5) {$\displaystyle{ψ(x,t=0) = (\frac{2}{π d^2})^{1/4} e^{-\frac{x^2}{d^2}}}$};
    \node[right] at (5.5,0) {\rotatebox{90}{$=$}$\leftarrow$ Summe von Energie Eigenzuständen};
    \node[right] at (5.5,-1.2) {$\vdots$};
    \draw (4,.1) -- ++(0,-.2);
    \begin{scope}[shift={(0,-7.5)}]
        \draw[->] (0, 0) -- ++(4.5,0) node[below] {$x$};
        \draw[->] (0,-.2) node[below] {$0$} -- ++(0,6.5) node[left] {$E$};
        \draw (4,-.2) node[below] {$d$} -- ++(0,6.5);
        \foreach \n/\q in {1/\sin(\frac{π}{d}x),2/0,3/\sin(\frac{3π}{d}),4/0}{
            \draw (0, \n*\n / 3) node[left] {$n = \n$} -- ++(4,0);
            \draw[shift={(0,\n*\n / 3)},smooth,samples=100,domain=0:4] plot ({\x},{.25*\n*sin(\x * \n * 180 / 4)});
            \node[right] at (5,\n*\n / 3) {$c_{\n} = \q$};
        }
    \filldraw (2,1/3) circle (2pt);
    \filldraw (2,3) circle (2pt);
    \end{scope}
\end{tikzpicture}
\end{center}
$ϕ_2$ ungerade und $ψ(x, t = 0)$ gerade
\[⇒ ∫ ϕ_2 ψ \d x = 0\]
\begin{center}
    \begin{tikzpicture}
        \draw[->] (-.1, 0) -- ++(10,0) node[below] {$n$};
        \draw[->] (0,-.1) -- ++(0,5) node[left] {$c_n$};
        \foreach \n in {1,...,9}
            \draw (\n,.1) -- ++(0,-.2) node[below] {$\n$};
        \foreach \n in {1,3,5,7,9}
            \filldraw (\n,{4*exp(-.03*\n*\n)}) circle (1.5pt);
        \foreach \n in {2,4,6,8}
            \filldraw (\n,0) circle (1.5pt);
        \draw[domain=1:10,smooth] plot ({\x},{4*exp(-.03*\x*\x)});
        \draw[<-] (1.1,4.05) -- ++(1,.5) node[right] {$\abs{c_1}^2$ Besetzung von Zustand $\ket{n = 1}$};
        \draw[<-] (4,2.6) -- ++(1,.5) node[right] {gaussförmig};
    \end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   $⇒$ Anfangsdynamik wie freies Wellenpaket $⇒$ Reflexionen am Rand $⇒$ lange Zeiten "`Revival"' = der Anfangszustand wird wieder erreicht.
** "Revival" in der Quantenmechanik
   Die Quantenmechanik in Systemen mit diskreten Energieen zeigt das Phänomen des "`rephasieren"' das heißt die Phasenunterschiede zwischen allen Energieeigenzuständen sind $n·2π$ mit $n ∈ ℤ$.
   Im Fall des Wellenpakets im Kastenpotential:
   \[e^{i \frac{E_n - E_{n'}}{\hbar} t} = 1\]
   Revival wenn $\frac{E_n - E_{n'}}{\hbar} t = m 2π, m ∈ ℤ$
   \(⇒ 1.\) Revival:
   \[\frac{E_3 - E_1}{\hbar} · T_{\text{Revival}} = 2π \to \frac{E_G}{\hbar}(3^2 - 1^2) T_{\text{Revival}} = 2π ⇒ T_{\text{Revival}} = \frac{h}{E_G} \frac{1}{(9-1)} = \frac{h}{E_G}\frac{1}{8}\]
   Allgemeine Energiedifferenz:
   \begin{align*}
       Δ E &= E_G(n^2 - n^{\prime 2}) = E_G(n - n')(n + n') \\
       ⇒ Δ E_{min} &= E_G(3^2 - 1) \\
       \intertext{wenn Phasendifferenz für Grund- und 2. angeregter Zustand $2π$ ist, sind alle anderen Phasendifferenzen ein gerades Vielfaches davon}
   \end{align*}
   mit $d \to ∞$ geht die Grundzustandsenergie $E_G = \frac{\hbar^2 π^2}{2m d^2} \to 0$, damit wird die "`revival"' Zeit $T_{\text{Revival}} \to ∞$ unendlich lang. Deshalb zerfließt ein Wellenpaket im
   freien Raum ($d \to ∞$) für immer.
** Harmonischer Oszillator
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
Klassisch:
\begin{minipage}{.3\textwidth}
\begin{center}
\begin{tikzpicture}
    \draw (0,0) rectangle (2,1) node[above,midway,yshift=12pt] {$m$};
    \draw[<->] (-.1,-.2) -- ++(2.2,0) node[below,midway] {oszilliert mit $ω$};
    \draw[->,decorate,decoration={zigzag,amplitude=1mm,segment length=1.5mm,pre length=2mm,post length=2mm}] (2,.5) -- ++(2,0) node[midway,above] {$k$};
    \draw (4,0) -- ++(0,1.5);
    \foreach \y in {1,...,12}
        \draw (4,\y / 8 - .066) -- ++(.1,.1);
\end{tikzpicture}
\end{center}
\end{minipage}
\begin{minipage}{.65\textwidth}
    \begin{equation*}
        \left.
        \begin{matrix}
            \begin{aligned}
                F &= - k x \\
                V &= \frac{k}{2} x^2
            \end{aligned}
        \end{matrix}
        \right\}
        ⇒\begin{matrix}
            \begin{aligned}
                x &= x_0 \sin(ω_0 t) \\
                ω_0^2 &= \frac{k}{m}
            \end{aligned}
        \end{matrix}
    \end{equation*}
\end{minipage}
$⇒$ schreiben harmonisches Potential so, dass man die Frequenz ablesen kann
\[V(x) = \frac{m ω^2}{2} x^2\]
\begin{center}
    \begin{tikzpicture}
        \draw[->] (-4, 0) -- ++(8,0) node[below] {$x$};
        \draw[->] (0,0) -- ++(0,4) node[left] {$E$};
        \draw[smooth,domain=-2:2] plot ({\x},{.75*\x*\x});
        \draw[->,smooth,domain=-1.5:1] plot ({\x},{.75*\x*\x +.2});
        \node at (2.2,2) {$V(x)$};
        \filldraw (-1.5,1.5*1.5*.75 + .2) circle (1pt);
        \draw[<-] (-1.65, 1.89) -- ++(-.5,0) node[left,every text node part/.style={align=left}] {Teilchen mit Masse $m$\\schwingt mit Frequenz $ω$};
    \end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Quantenmechanische Beschreibung: $ψ(x,t) \to$ suchen Energie-Eigenzustände:
   \[ψ_E(x,t) = e^{-i \frac{E}{\hbar} t} ϕ(x)\]
   Schrödinger Gleichung:
   \[-\frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} ϕ(x) + \frac{1}{2} m ω^2 x^2 ϕ(x) = E ϕ(x)\]
   Suche Lösung der Form:
   \[ϕ(x) = N e^{- \frac{b}{2} x^2} \underbrace{(a_0 + a_1 x + a_2 x^2 + a_3 x^3 + \dots)}_{\text{Potenzreihenansatz}}\]
   Polynome haben die Form:
   \begin{align*}
       \tilde H_0(x) &= 1 \\
       \tilde H_1(x) &= 2 \sqrt{b} x \\
       \tilde H_{n+1}(x) &= 2 \sqrt{b} x \tilde H_n(x) - 2n \tilde H_{n - 1}(x)
   \end{align*}
   Was sind die Eigenenergieen $\to$ einsetzen in Schrödinger Gleichung:
   \begin{align*}
       ϕ_0 &= N e^{-\frac{b}{2} x^2} \\
       ϕ_0'' &= N(b^2 x^2 - b) e^{-\frac{b}{2} x^2} \\
       -\frac{\hbar^2}{2m}(b^2 x^2 - b) + \frac{m ω^2}{2} = E_0 \\
       \intertext{die \(x\)-Abhängigkeit muss verschwinden, weil $E$ eine Konstante ist (hängt nicht von $x$ ab)}
       ⇒ \frac{\hbar^2}{2m} b^2 &= \frac{m ω^2}{2} \\
       b &= \frac{m ω}{\hbar} \\
       ϕ_0 &= N e^{-\frac{b}{2} x^2} = N e^{-\frac{1}{2} (\frac{x}{a_{ho}})^2} \\
       \intertext{$a_{ho}$: charakteristische Länge; harmonic oscillator length}
       a_{ho} &= \sqrt{\frac{\hbar}{m ω}} \\
       E_0 &= \frac{\hbar^2}{2m} b = \frac{\hbar^2}{2m} \frac{m ω}{\hbar} = \frac{\hbar ω}{2} \\
       \intertext{weitere Beispiele:}
       ϕ_1 &= N 2 \sqrt{b} x e^{-\frac{b}{2} x^2} \\
       ϕ_1'' &= N 2(-3bx + b^2 x^3) \sqrt{b} x e^{-\frac{b}{2} x^2} \\
       E_1 2 N \sqrt{b} x &= -\frac{\hbar^2}{2m} 2N \sqrt{b} (-2bx + b^2 x^3) + 2N \sqrt{b} \frac{m ω^2}{2} x^3 \\
       x^3: &\text{ Koeffizient ist null, weil } b = \frac{m ω}{\hbar} \\
       x: &+\frac{\hbar^2}{2m} 2b = E_1 = \hbar ω \frac{3}{2} = \hbar ω(1 + \frac{1}{2})
   \end{align*}
   $N$: folgt aus Normierungsbedingung. \\
   Allgemeine Lösung:
   \begin{gather*}
       ϕ_n = \sqrt{\frac{1}{\sqrt{π} a_{ho}}} \frac{1}{\sqrt{2^n n!}} H_n(\frac{x}{a_{ho}}) e^{-\frac{1}{2}(\frac{x}{a_{ho}})^2} \\
       \text{mit}\quad E_n = \hbar ω(n + \frac{1}{2}) \qquad a_{ho} = \sqrt{\frac{\hbar}{m ω}} \\
       \text{mit}\quad H_0(x) = 1\qquad H_1(x) = 2x \qquad H_{n + 1}(x) = 2x H_n(x) - 2n H_{n - 1}(x)
   \end{gather*}
   $H_n$: Hermitesche Polynome.
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
    \draw[->] (-4,0) -- ++(10,0) node[below] {$x$};
    \draw[->] (-4,0) -- ++(0,5) node[left] {$E$};
    \draw[smooth,domain=-3:3] plot ({\x},{.5*\x*\x});
    \foreach \i in {0,...,3}
        \draw (-3,.5 + \i) node[left] {$ϕ_\i$} -- ++(6,0) node[right] {$E_\i = (\i + \frac{1}{2}) \hbar ω$};
    \draw[domain=-3:3,shift={(0,.5)},smooth] plot ({\x},{(.5/sqrt(sqrt(3.1415)))*exp(-.5*\x*\x)});
    \draw[domain=-3:3,shift={(0,1.5)},smooth] plot ({\x},{(.5/sqrt(sqrt(3.1415)*2))*2*\x*exp(-.5*\x*\x)});
    \draw[domain=-3:3,shift={(0,2.5)},smooth] plot ({\x},{(.5/sqrt(sqrt(3.1415)*8))*(4*\x*\x - 2)*exp(-.5*\x*\x)});
    \draw[domain=-3:3,shift={(0,3.5)},smooth] plot ({\x},{(.5/sqrt(sqrt(3.1415)*48))*(8*\x*\x*\x - 12*\x)*exp(-.5*\x*\x)});
    \draw[<-] (-.9,3.8) -- ++(-.5,.5) node[above] {$ϕ_n$ hat $n$ Knoten};
\end{tikzpicture}
\end{center}
\[ψ_n(x,t) = e^{-i\frac{E_n}{\hbar} t ϕ_n(x) \to \abs{ψ_n}^2} = \abs{ϕ_n(x)}^2\]
\begin{center}
\begin{tikzpicture}
    \draw[->] (-4,0) -- ++(10,0) node[below] {$x$};
    \draw[->] (-4,0) -- ++(0,5) node[left] {$E$};
    \draw[smooth,domain=-3:3] plot ({\x},{.5*\x*\x});
    \foreach \i in {0,...,3}
        \draw (-3,.5 + \i) node[left] {$\abs{ψ_\i}^2$} -- ++(6,0) node[right] {$n = \i$};
    \draw[domain=-3:3,shift={(0,0.5)},smooth,samples=100] plot ({\x},{((1.2/sqrt(sqrt(3.1415)))*exp(-.5*\x*\x))^2});
    \draw[domain=-3:3,shift={(0,1.5)},smooth,samples=100] plot ({\x},{((1.2/sqrt(sqrt(3.1415)*2))*2*\x*exp(-.5*\x*\x))^2});
    \draw[domain=-3:3,shift={(0,2.5)},smooth,samples=100] plot ({\x},{((1.2/sqrt(sqrt(3.1415)*8))*(4*\x*\x - 2)*exp(-.5*\x*\x))^2});
    \draw[domain=-3:3,shift={(0,3.5)},smooth,samples=100] plot ({\x},{((1.2/sqrt(sqrt(3.1415)*48))*(8*\x*\x*\x - 12*\x)*exp(-.5*\x*\x))^2});
\end{tikzpicture}
\end{center}
$n \estimates$ Quantenzahl.
\[\hat H_{\text{Harmonischer Oszillator}} \ket{n} = \hbar ω (n + \frac{1}{2}) \ket{n}\]
Grundzustand: $E_G = E_0 = \frac{1}{2} \hbar ω$ \\
\begin{minipage}{.45\textwidth}
\begin{center}
Klassisch:\\
\begin{tikzpicture}
    \draw[->] (-.1,0) node[left] {$0$} -- ++(1,0) node[below] {$x$};
    \draw[->] (0,-.1) -- ++(0,3) node[left] {$E$};
    \draw[shift={(3,0)},smooth,domain=-2:2] plot ({\x},{.75*\x*\x});
    \filldraw (3,2pt) circle (2pt) node[below] {$x = 0$};
    \draw[dotted] (1,0) -- ++(2,0);
\end{tikzpicture}
\end{center}
\end{minipage}
\hfill\begin{minipage}{.45\textwidth}
\begin{center}
Quantenmechanisch:\\
\begin{tikzpicture}
    \draw[shift={(3,0)},smooth,domain=-2:2] plot ({\x},{.75*\x*\x});
    \draw (3,.1) -- ++(0,-.2) node[below] {$x = 0$};
    \draw (2,.5) -- ++(2,0) node[right] {$E_G$};
    \draw[shift={(3,.5)},smooth,domain=-2.2:2.2] plot ({\x},{exp(-8*\x*\x)});
\end{tikzpicture}
\end{center}
\end{minipage}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Grundzustand: \\
   Quantenmechanischer Zustand kann nicht beliebig räumlich lokalisiert sein. Heisenberg Unschärfe
   gibt
   \[\VAR(x) · \VAR(p) \geq \frac{\hbar^2}{4}\]
   kinetische Energie steigt mit Lokalisierung. \\
   Allgemeiner Grundzustand ergibt sich aus dem "`Gleichgewicht"' zwischen potentieller Energie und kinetischer Energie (nennt man auch Quantendruck) \\
   Der Grundzustand des harmonischen Oszillators erfüllt minimale Heisenberg Unschärfe.
   Harmonischer Oszillator:
   \begin{align*}
       \hat H &= \frac{1}{2m} \hat p^2 + \frac{m ω^2}{2} \hat x^2 \\
       \braket{\hat H} &= \frac{1}{2m} \braket{\hat p^2} + \frac{m ω^2}{2} \braket{\hat x^2} \\
       \intertext{harmonischer Oszillator symmetrisch in $x,p ⇒ \braket{\hat x} = \braket{p} = 0$}
       \VAR(x) &= \braket{\hat x^2} - \braket{\hat x}^2 = \braket{\hat x^2} \\
       \VAR(p) &= \braket{\hat p^2} \\
       \braket{\hat H} &= \frac{1}{2m} \VAR(p) + \frac{m ω^2}{2} \VAR(x) \\
       V_x &:= \VAR(x) \\
       \braket{\hat H} &= \frac{\hbar^2}{8m} \frac{1}{V_x} + \frac{m ω^2}{2} V_x \\
       \intertext{suchen Minimum}
       \dd{\braket{\hat H}}{V_x} &= -\frac{\hbar^2}{8m} \frac{1}{V_x^2} + \frac{m ω^2}{2} \overset{!}{=} 0 \\
       ⇒ V_x &= \frac{\hbar}{2mω} \\
       ⇒ \braket{\hat H}_{\text{min}} &= \hbar ω(\frac{1}{4} + \frac{1}{4}) = \frac{1}{2}\hbar ω \checkmark
   \end{align*}
   Grundzustand ist Zustand minimaler Heisenberg-Unschärfe.
** Klassische Korrespondenz beim harmonischen Oszillator
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{minipage}{.45\textwidth}
\begin{center}
\begin{tikzpicture}
    \draw[->] (0,0) -- ++(1,0) node[below] {$x$};
    \draw[->] (0,0) -- ++(0,1) node[left] {$E$};
    \begin{scope}[shift={(1,0)}]
    \draw[smooth, domain=-2.6:2.6,shift={(3,-3)}] plot ({\x},{1*\x*\x});
    \draw[smooth, samples=50, domain=-3:3,shift={(3,-6)}] plot ({\x},{2*exp(-4*\x*\x)});
    \begin{scope}[shift={(-.45,-10)}]
    \begin{axis}[at={(3,-7)},axis lines=middle,hide axis,ymin=-.001,ymax=.3]
        \addplot[at={(3,-7)},smooth,samples=200,domain=-6:6]{.5*((1/sqrt(sqrt(3.14) * 10321920)) * (256*\x^8 - 3584*\x^6 + 13440*\x^4 - 13440*\x^2 + 1680)*exp(-.5*\x^2))^2};
    \end{axis}
    \end{scope}
    \end{scope}
    \draw[dotted] (1.7,2.3^2 - 3) -- ++(0,-2.3^2 - 7.12);
    \draw[dotted] (6.3,2.3^2 - 3) -- ++(0,-2.3^2 - 7.12);
    \draw (1.7, 2.3^2 - 3) node[left] {$(8 + \frac{1}{2}) \hbar ω$} -- ++ (4.6, 0) node[right] {$n = 8$};
    \draw (3.44, .311 - 3) node[left] {$\frac{\hbar ω}{2}$} -- ++ (1.12, 0) node[right] {$n = 0$};
    \draw (3, -3) -- ++ (2, 0);
    \draw (3.44, .2 - 3) -- ++ (0, -.3);
    \draw (4.56, .2 - 3) -- ++ (0, -.3);
    \draw[dotted] (3.44,.311 - 3) -- ++(0,-.311 - 3);
    \draw[dotted] (4.56,.311 - 3) -- ++(0,-.311 - 3);
    \draw[->] (1, -6) -- ++ (6,0) node[below] {$x$};
    \draw[->] (1, -6) -- ++ (0,3);
    \draw (.9, 0.57 - 6) node[left] {$\frac{1}{e}$} -- ++ (.2, 0);
    \draw (.9, 2 - 6) node[left] {$1$} -- ++ (.2, 0);
    \draw (4.56, -5.9) -- ++(0,-.2) node[below,xshift=3pt,yshift=2pt] {$x_u^{n = 0}$};
    \draw (4, -5.9) -- ++(0,-.2) node[below] {$0$};
    \draw[<-] (4.7, -5.5) -- ++(.5,.5) node[above right,xshift=-2pt,yshift=-6pt] {$\abs{ψ_{n = 0}}^2$};
    \draw[->] (1, -10.12) -- ++ (6,0) node[below] {$x$};
    \draw[->] (1, -10.12) -- ++ (0,3);
    \draw (6.3, -10.02) -- ++(0,-.2) node[below,xshift=3pt,yshift=2pt] {$x_u$};
    \draw (4, -10.02) -- ++(0,-.2) node[below] {$0$};
    \foreach \x in {1,...,8}
        \node[font=\footnotesize] at ({.483*(\x - 1) + 2.30}, -10.25) {$\x$};
\end{tikzpicture}
\end{center}
\end{minipage}
\hfill\begin{minipage}{.5\textwidth}
    $x_u$: klassischer Umkehrpunkt
    \begin{align*}
        E &= \frac{m ω^2}{2} x_u^2  \\
        x_u &= \sqrt{\frac{2E}{m}} \frac{1}{ω} \\
        \text{für } n = 0\quad E &= \frac{\hbar ω}{2} \\
        x_u &= \sqrt{\frac{\hbar}{mω}} = A_{ho} \\
        \text{mit } ψ_{n = 0} &= e^{-i \frac{ω}{2} t} e^{-\frac{1}{2}(\frac{x}{a_{ho}})^2} \\
        \abs{ψ_{n = 0}(x_u)}^2 &= \frac{1}{e} \abs{ψ_{n = 0}(x = 0)}^2
    \end{align*}
\end{minipage}
Die Quantenmechanische Wahrscheinlichkeitsdichte nähert sich der klassischen
Wahrscheinlichkeitsdichte für $n \to ∞$ an.

Was entspricht einem klassisch oszilierenden Teilchen?
\begin{center}
\begin{tikzpicture}
    \draw[domain=-2.5:2.5, samples=50,smooth] plot ({\x}, {.5*\x*\x});
    \draw[domain=-2.5:2.5, samples=50,smooth,shift={(2.5,0)}] plot ({\x}, {.5*\x*\x});
    \foreach \x in {1,...,16}
        \draw ({2.5 - sqrt(.4*(\x - .5))}, {.2*(\x - .5)}) -- ++({2 * sqrt(.4*(\x - .5))}, 0);
    \draw[domain=-1:1, samples=50,smooth] plot ({\x}, {exp(-16*\x*\x) + .2*.5});
    \draw (-1, +.2*.5) -- ++(2,0);
    \draw[->] (-1.5,.5) node[left] {$ψ_0$} -- ++(1,0);
    \draw[<-] (5,2) -- ++(1,0) node[right,every text node part/.style={align=left}] {verschobenes harmonisches Potential; \\ Kreisfrequenz $ω$ führt zur Oszillationsdauer $T = \frac{2π}{ω}$};
    \begin{scope}[shift={(-1, -4)}]
        \draw[->] (0,0) -- ++(10, 0) node[below] {$x$};
        \draw[->] (0,0) -- ++(0, 3) node[left] {$\abs{ψ}^2$};
        \draw[domain=-1:2, samples=50,smooth,shift={(1,0)}] plot ({\x}, {1.5*exp(-16*\x*\x)});
        \draw[domain=-2:2, samples=50,smooth,shift={(3.5,0)}] plot ({\x}, {1.5*exp(-16*\x*\x)});
        \draw[domain=-2:2, samples=50,smooth,shift={(6,0)}] plot ({\x}, {1.5*exp(-16*\x*\x)});
        \draw[dotted] (3.5,4) -- ++(0,-4);
        \draw[->] (1,1.6) node[above] {$t = 0$} -- ++(1,0);
        \draw[->] (3.5,1.6) node[above] {$t = \frac{T}{4}$} -- ++(1,0);
        \draw[->] (6,1.6) node[above] {$t = \frac{T}{2}$} -- ++(-1,0);
    \end{scope}
\end{tikzpicture}
Oszillierendes, nicht zerfließendes Wellenpaket.
\end{center}
Quadratisches Potential in $x$ kompensiert quadratische Phasenentwicklung in $x$ des expandierenden Wellenpakets $⇒$ Paket zerfließt nicht und oszilliert mit der Kreisfrequenz $ω$.
Dieses Wellenpaket nennt man auch "`verschobenes Vakuum ($n = 0$)"' beziehungsweise kohärenten Zustand $\ket{α}$. Wahrscheinlichkeit $P$:
\[P(n) = \abs{\braket{n|α}}^2 = \frac{\abs{α}^{2n}}{n!} e^{-\abs{α}^2}\]
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
* Wasserstoff
** Ausgestrahltes Licht einer H2 Gasentladung
** Wasserstoff ist mehr als zusammengesetztes ein negatives Teilchen gebunden an ein positives Teilchen
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
Man könnte meinen ein einfachen zwei-Körper Problem mit Coulomb-Anziehung, aber: \\
\begin{minipage}{.48\textwidth}
\[\estimates V(\v x) = \frac{-e^2}{2π ε_0 \abs{r}}\]
\begin{center}
\begin{tikzpicture}
    \pgfdeclareverticalshading{myshading}{100bp}{color(0bp)=(red); color(50bp)=(red); color(50bp)=(blue); color(100bp)=(blue)}
    \draw (0,0) circle (3);
    \node[draw,circle, inner sep=.4pt] (p) at (0,0) {\phantom{$+$}};
    \draw[->] (p) -- (55:2.4) node[midway,left] {$\v r$};
    \node[draw, shading=myshading, transform shape, rotate=55, shading angle=90+60, minimum width=1cm] at (0,0) {};
    \node[thick,inner sep=1pt] at (0,0) {$\mathbf{+}$};
    \node[draw, shading=myshading, transform shape, rotate=100, shading angle=183, inner sep=0pt, minimum width=.7cm, minimum height=.1cm] at (55:2.4) (e) {};
    \node[right] at (e) {$-$};
    \node[below right] at (e) {Elektron};
    \node[below right] at (p) {Proton};
    \draw[->] (0,-3) -- ++(0,-.5) -- ++(-4,0) node[midway, below] {$v$};
    \draw[<-] (2.2,-2.2) -- ++(.5,-.5) node[below] {Wasserstoff};
\end{tikzpicture}
\end{center}
\end{minipage}\hfill
\begin{minipage}{.48\textwidth}
\begin{enumerate}
\item Atom bewegt sich konstant mit Geschwindigkeit $v$
\item Das Proton bewirkt ein Potential:
    \[V = \frac{-q^2}{2π ε_0 \abs{\v r}} = \frac{-e^2}{2π ε_0 \abs{\v r}}\]
\item Elektron hat Spin (folgt aus relativistischer Behandlung). Damit verbunden hat das
Elektron ein magnetisches Moment
\begin{center}
\begin{tikzpicture}
\pgfdeclareverticalshading{myshading}{100bp}{color(0bp)=(red); color(50bp)=(red); color(50bp)=(blue); color(100bp)=(blue)}
\filldraw (0, 0) circle (1pt);
\draw[<-] (0, -.1) -- ++(0,-.5) node[below] {Punkt};
\draw[->] (.25, 0) -- ++(.75, 0);
\draw[->] (1.25, -.35) -- ++(0,.7);
\draw[<-] (1.25, -.45) -- ++(0,-.5) node[below] {Teilchen};
\node[right] at (1.5, 0) {$\estimates$};
\node[draw, shading=myshading, transform shape, rotate=90, shading angle=180, minimum width=1cm] at (2.30,-.05) {};
\node at (2.7, 0) {$\v μ_e$};
\end{tikzpicture}
\end{center}
$⇒$ Feinstruktur, weil zusätzliche Energie
\begin{align*}
E &= - \v μ_e · \v B \\
Δ E &\sim \SI{e-4}{\eV}
\end{align*}
\item Proton ist zusammengesetztes Teilchen mit Spin $⇒$ gesamt Spin $⇒$ Magnetisches Moment
$\v μ_p$ $⇒$ Energie durch $\v μ_p · \v μ_e$. Hyper-Feinstruktur $ΔE \sim \SI{e-6}{\eV}$
\item Vakuum ist nicht leer $⇒$ Vielteilchen-Problem, $Δ E \sim \SI{e-6}{\eV}$
\end{enumerate}
\end{minipage}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Aber:
   \begin{enumerate}
   \item Atom bewegt sich; Lösung: Einführen von Schwerpunktsbewegung ($λ_{dB}$ wie bisher) und Relativbewegung (analog wie in Mechanik) $⇒$
   \item Schrödinger Gleichnug. 3D und $1/r$ Potential
   \end{enumerate}
** Wasserstoff - ein einfaches Modell
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{minipage}{.48\textwidth}
\begin{center}
\begin{tikzpicture}
\draw[->] (0,0) -- ++(1.5,0) node[below] {$y$};
\draw[->] (0,0) -- ++(0,1.5) node[left] {$z$};
\draw[->] (0,0) -- ++({-.5*sqrt(2)},{-.5*sqrt(2)}) node[below] {$x$};
\node[fill=black,circle,draw,inner sep=2.5pt] (p) at (2.5, .7) {};
\node[fill=black,circle,draw,inner sep=.7pt] (e) at (2.7, -1.4) {};
\node[right, xshift=3pt,every text node part/.style={align=left}] at (p) {positiv geladener Kern;\\ zum Beispiel Proton};
\node[right,xshift=3pt,every text node part/.style={align=left}] at (e) {negativ geladenes Teilchen;\\ zum Beispiel Elektron};
\node[inner sep=0pt] at (0,0) (o) {};
\draw[->] (o) -- (p) node[midway,above] {$\v r_2$};
\draw[->] (o) -- (e) node[midway,below] {$\v r_1$};
\draw[->] (p) -- (e) node[midway,right] {$\v r$};
\draw[->] (o) -- ($(p)!.2!(e)$) node[below,pos=.75] {$\v r_s$};
\end{tikzpicture}
\end{center}
$\v μ_2$: Ort des positiven Kerns \\
$\v μ_1$: Ort des negativen Teilchens \\
$\v μ_s$: Ort des Schwerpunkts \\
\end{minipage}\hfill
\begin{minipage}{.48\textwidth}
Wasserstoff: Kern $\estimates$ Proton
\begin{align*}
    m_p &= \SI{1.67e-27}{\kilo\gram} \\
    &= \SI{938}{\mega\eV} \\
    &= \SI{1}{\amu} \text{ (atomic mass unit)}
\end{align*}
negativ geladenes Teilchen $\estimates$ Elektron
\begin{align*}
    m_e &= \SI{9.1e-31}{\kilo\gram} \\
    &= \SI{510}{\kilo\eV} \\
    &= \SI{1/1835}{\amu}
\end{align*}
\end{minipage}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Suchen Energie-Eigenzustände
   \begin{align*}
       \hat H \ket{ψ} &= E \ket{ψ} \\
       \hat H &= \hat E_{\text{kin}} + \hat E_{\text{pot}} = \underbrace{\frac{\hat p_2^2}{2m_k}}_{\mathclap{\text{Kern}}} + \overbrace{\frac{\hat p_1^2}{2m_e}}^{\mathclap{\text{Elektron}}} - \underbrace{\frac{Z e^2}{2πε_0 \abs{\v r}}}_{\mathclap{\text{Wechselwirkung}}} \\
       \intertext{in Ortsdarstellung}
       E_{\text{ges}}ψ(\v r_1, \v r_2) &= -\frac{\hbar^2}{2m_k} \Laplace_2 ψ(\v r_1, \v r_2) - \frac{\hbar^2}{2m_e} \Laplace_1 ψ(\v r_1,\v r_2) - \frac{Z e^2}{4πε_0 \abs{r}} ψ(\v r_1, \v r_2)\\
   \end{align*}
   Zu Frage 1: Vereinfachung durch Trennung von Schwerpunkts- ($\v r_s$) und Relativbewegung ($\v r$)
   \begin{align*}
       \v r_s &= \frac{m_k \v r_2 + m_e \v r_2}{\underbrace{m_k + m_e}_{M}} = \cvec{x_s;y_s;z_s} \qquad \v r = \v r_1 - \v r_2 = \cvec{x;y;z} \\
       ψ(\v r_1, \v r_2) &= Ψ(\v r_s, \v r) \\
       \text{mit}\quad \pp{}{x_1} Ψ(x_s, x) &= \pp{Ψ}{x_s} \pp{x_s}{x_1} + \pp{Ψ}{x} \pp{x}{x_1} = (\frac{m_e}{M} \pp{}{x_s} + \pp{}{x})Ψ(x_s, x) \\
       \intertext{analog: $y_1, z_1$}
       ⇒ E_{\text{ges}} Ψ(\v r_s, \v r) &= - \frac{\hbar^2}{2M} \Laplace_s Ψ(\v r_s, \v r) +
       \string(-\frac{\hbar^2}{2μ} \Laplace_r - \frac{Z e^2}{4π ε_0 \abs{\v r}}\string)Ψ(\v r_s, \v r) = E_{\text{ges}} Ψ(\v r_s, \v r) \\
       μ &= \frac{m_k m_e}{m_k + m_e}
   \end{align*}
   Dabei erhälte man für die kinetische Energie des Schwerpunkts:
   \[-\frac{\hbar^2}{2M} \Laplace_s Ψ(\v r_s, \v r)\]
   dies ist entkoppelt von $\v r$ $⇒$ Atom als ganzes verhält sich wie eine De-Broglie-Welle. Zum Beispiel: Doppelspalt, Atom-Molekülinterferometer. $\estimates$ externe Dynamik. \\
   Für die kinetische und potentielle Energie der Relativbewegung erhält man:
   \[(-\frac{\hbar^2}{2μ} \Laplace_r - \frac{Z e^2}{4π ε_0 \abs{\v r}})Ψ(\v r_s, \v r)\]
   $\estimates$ interne Dynamik. \\
   Löse mit Separationsansatz
   \[Ψ(\v r_s, \v r) = Ψ_s(\v r_s) Ψ(\v r) \quad \text{und}\quad E_{\text{ges}} = E_s + E\]
   $⇒$ Externe Dynamik:
   \[-\frac{\hbar^2}{2M} \Laplace_s ψ_s(\v r_s) = E_s ψ_s(\v r_s)\]
   Lösung: de-Broglie Welle für das Atom mit
   \[λ_s = \frac{h}{\sqrt{2M E_s}}\]
   $⇒$ Interne Dynamik: Lösung etwas langwieriger. \\
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{minipage}{.45\textwidth}
Zentral Potential $⇒$ sinnvoll in Kugelkoordinaten
\end{minipage}
\begin{minipage}{.38\textwidth}
\begin{center}
\begin{tikzpicture}
\draw[->] (0,0) -- ++(1.5,0) node[below] {$y$};
\draw[->] (0,0) -- ++(0,1.5) node[left] {$z$};
\draw[->] (0,0) -- ++({-.5*sqrt(2)},{-.5*sqrt(2)}) node[below] {$x$};
\node[fill=black,draw,circle,inner sep=1pt] (p) at (1,1) {};
\draw[->] (0,0) -- (p);
\draw (0,.45) arc[radius=.45cm,start angle=90,end angle=45] node[midway,xshift=2pt,above,font=\small] {$θ$};
\draw[dotted] (p) -- ++(0,-1.5);
\draw[dotted] (0,0) -- ($(p) + (0,-1.5)$);
\draw (-.25,-.25) arc[radius=.45cm,start angle=225,end angle=322] node[midway,xshift=2pt,below,font=\small] {$φ$};
\end{tikzpicture}
\end{center}
\end{minipage} \\
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   \[-\frac{\hbar^2}{2μ} \Laplace_r = \underbrace{-\frac{\hbar^2}{2μ} \frac{1}{r^2}\pp{}{r}(r^2 \pp{}{r})}_{\mathclap{\text{hängt nur von $r$ ab}}} - \underbrace{\frac{\hbar^2}{2μr^2} (\frac{1}{\sin θ} \pp{}{θ}(\sin θ \pp{}{θ}) + \frac{1}{\sin^2 θ} \frac{\partial^2}{\partial φ^2})}_{\mathclap{\text{hängt nur von \(θ\)-Polarwinkel und \(φ\)-Azimutwinkel ab}}}\]
   $⇒$ Separationsansatz:
   \[ψ(r,θ,φ) = R(r)P(θ)Q(φ)\]
   3 gewöhnliche Differentialgleichnugen 2. Grades für $R(r), P(θ), Q(φ)$. Zusätzliche Bedingung
   \[∫ \abs{ψ}^2 \d V = 1\]
   grenzt die Lösungen der Differentialgleichnugen stark ein.
   \begin{ibox}{}
   \begin{align*}
   ψ_{n,l,m} (r,θ,φ) &= R_{n,e}(r) P_l^m (\cos θ) e^{imφ} \\
   E_n &= - \frac{μ e^4}{8h^2 ε_0^2} \frac{z^2}{n^2} = -R_y^{\ast} \frac{z^2}{n^2}
   \end{align*}
   $R_y^{\ast}$: reduzierte Rydberg Konstante $\approx \SI{13.6}{\eV}$ \\
   $n = 1,2,3, \dots$ Hauptquantenzahl \\
   Für gegebenens $n$ ist $l = 0,1,2, \dots, (n - 1)$ \\
   Für gegebenes $l$ ist $m = -l, -l + 1, \dots, l - 1, l$
   \end{ibox}{}
   \[\hat H \ket{ψ} = E\ket{ψ} \to \ket{n,l,m}\qquad ψ_{n,l,m} = \braket{x|n,l,m}\]
   Wichtig: Energie = $-\SI{13.6}{\eV} · 1/n^2$
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
\draw[<->] (0,3.5) node[left] {$∞$} -- ++(0,-3.5) -- ++(2.5,0) -- ++(0,3.5) node[right] {$∞$};
\foreach \i in {1,2,3}
\draw (0,\i*\i / 3) -- ++(2.5, 0);
\node[right,every text node part/.style={align=left}] at (2.7,2) {$E_n \propto n^2$\\$n= 1,2,\dots$};
\begin{scope}[shift={(5,0)}]
    \draw[smooth,domain=-1.25:1.25,shift={(1.25,0)}] plot ({\x},{\x*\x*2.1});
    \foreach \i in {0,...,6}
        \draw ({1.25-sqrt(.5*(\i + .5)/2.1)},{.5*(\i + .5)}) -- ({1.25+sqrt(.5*(\i + .5)/2.1)},{.5*(\i + .5)});
    \node[right,every text node part/.style={align=left}] at (2.7,2) {$E_n \propto (n + 1/n)$\\$n =0,1,2,\dots$};
\end{scope}
\begin{scope}[shift={(11,0)}]
\draw[->] (-.1,3) -- ++(2.6,0);
\draw (0,3.1) -- ++(0,-3.1);
    \draw[smooth,domain=0.09:2.5] plot ({\x},{-.27/\x + 3});
    \foreach \i in {1,...,9}
        \draw (0,{3 - 2.5/(\i*\i)}) -- ++({min(-.27/(-2.5/(\i*\i)),2.5)},0);
    \draw[<-] (.3,2) -- ++(.5,-.5) node[right,yshift=-1pt,xshift=-2.5pt] {$\frac{1}{r}$};
    \node[right,every text node part/.style={align=left}] at (1.1,2) {$E_n \propto \frac{1}{n^2}$\\$n = 1,2,\dots$};
\end{scope}
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
** Wasserstoff - radiale Wellenfunktion
   Radiale Wellenfunktion: \\
   $R_{nl}$: skalierter Radius
   \[ρ = 2 Z \frac{r}{na_B'}\]
   Mit Bohrschem Radius $a_B'$:
   \[a_B' \frac{4πε_0 \hbar^2}{μ e^2}\]
   (normaler Bohrscher Radius ist mit Elektronmasse anstatt $μ$ definiert).
   $L_m^n(ρ)$: zugeordnete Laguere Polynome. \\
   \[R_{nl}(r) = \sqrt{(\frac{Z}{n A_B'})^3 \frac{(n - l - 1)!}{2n(n + l)!}} e^{-\frac{ρ}{2}} ρ^l \underbrace{L_{n - l - 1}^{2l + 1}}_{\mathclap{\text{Polynom $n - l - 1$ Grades $\estimates$ Anzahl der Nullstellen}}} (ρ)\]
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
    \draw [->] (-.1,0) -- ++(8.1,0) node[above] {$r$};
    \draw [->] (0,+.1) -- ++(0,-8.1) node[left] {$E$};
    \draw[samples=50,smooth,domain=1.0:8] plot ({\x},{-8/\x});
    \foreach \i in {1,...,25}
        \draw (0,{-7/(\i*\i)}) -- ++({min(8/(7/(\i*\i)),8)},0);
    \draw[smooth,domain=0:8,shift={(0,-7)}] plot ({.5*\x},{exp(-\x/2)});
    \draw[smooth,domain=0:12,shift={(0,-7/4)}] plot ({.5*\x},{exp(-\x/2)*(-\x + 1)});
    \draw[smooth,domain=0:12,shift={(0,-7/4)}] plot ({.5*\x},{exp(-\x/2)*\x});
    \draw[->] (0,-7) -- ++(5, 0) node[below] {$r$};
    \node[left] at (0,-7) {$\SI{-13.6}{\eV}\ \ n = 1$};
    \node[left] at (0,-7/4) {$\SI{-3.4}{\eV}\ \ n = 2$};
    \node[yshift=-3pt,below left] at (0,-7/4) {$l = 0,1$};
    \node[left] at (0,-7/9) {$\SI{-1.5}{\eV}\ \ n = 3$};
    \node[above left] at (-1,-7/16) {$(\frac{-13.6}{n^2})$};
    \draw[->] (0,-7/4) -- ++(7, 0) node[below] {$r$};
    \node[left] at (0,-6) {$ψ_{10,0}$};
    \draw[<-] (2,-6.8) -- ++(.5,.5) node[right,xshift=-1pt] {$R_{10}(r)$};
    \draw[<-] (1.3,-2.3) -- ++(0,-.5) node[below] {$R_{20}(r)$};
    \draw[<-] (3.5, -1.6) -- ++(.5,-1) node[below right,every text node part/.style={align=left}] {$R_{21}(r)$ nur Nullstelle bei $r = 0$;\\trotzdem gleiche Energie\\$⇒$ in Winkelkoordinaten gibt\\es Nullstelle};
    \draw[<-] (2.1, -4.1) -- ++(.5,-.5) node[below right,yshift=7pt,xshift=-9pt] {$\displaystyle{-\frac{Z e^2}{4π ε_0 r}}$};
\end{tikzpicture}
\end{center}
\begin{minipage}{.3\textwidth}
\begin{center}
\begin{tikzpicture}
\node[fill=black,draw,circle,inner sep=3pt] (p) at (0,0) {};
\node[fill=black,draw,circle,inner sep=.5pt] (e) at (2,.5) {};
\node[below,yshift=-2pt] at (p) {$p^{+}$};
\node[below] at (e) {$e^{-}$};
\draw (p) -- (e) node[midway,above] {$r$};
\begin{scope}[shift={(0,-3.5)}]
\draw[black,pattern=north east lines, pattern color=black] (0,0) circle (1.5);
\filldraw[black,fill=white] (0,0) circle (1.3);
\draw[->] (0,0) -- ++(2.3,0) node[below] {$y$};
\draw[->] (0,0) -- ++(0,2.3) node[left] {$z$};
\draw[->] (0,0) -- ++({-2.3/sqrt(2)},{-2.3/sqrt(2)}) node[below] {$x$};
\draw[->] (0,0) -- (300:1.3) node[midway,below left,xshift=2pt,yshift=2pt] {$r$};
\draw[->] (300:2.0) -- (300:1.5) node[midway,above right,xshift=0pt,yshift=-4pt] {$\d r$};
\draw  (1.15,1.15) -- ++(.6,.4) node[right,yshift=1pt] {Volumen: $4π r^2 \d r$};
\end{scope}
\end{tikzpicture}
\end{center}
\end{minipage}\hfill
\begin{minipage}{.6\textwidth}
Wie groß ist die Wahrscheinlichkeit das Elektron im Abstand $[r, r + \d r]$ zu finden?
\[\d P = \abs{R_{n,l}(r)}^2 r^2 \d r\]
$⇒ \abs{R_{n,l}(r)}^2 r^2$ ist eine sinnvolle Größe um Aufentaltswahrscheinlichkeit darzustellen.
\end{minipage}
\begin{center}
%\pgfkeys{/pgf/fpu=true}
\begin{tikzpicture}
    \draw[->] (0,0) -- ++(7,0) node[below] {$r$};;
    \draw[->] (0,0) -- ++(0,3) node[left] {$r^2 \abs{R}^2$};
    \draw[smooth,samples=50,domain=0:7] plot ({\x}, {5*\x*\x*exp(-\x)});
    \node[left,every text node part/.style={align=left}] at (0,2) {$n = 1$ \\ $l = 0$};
    \draw (2,2.8) -- ++(0,-.2);
    \draw (2,.1) -- ++(0,-.2) node[below] {$\frac{a_b'}{z}$};
    \draw (3,2.4) -- ++(0,-2.5) node[below] {$\frac{a_b'}{z} \frac{3}{2}$};
    \draw[<-] (3.1,2.5) -- ++(.5,.5) node[right,every text node part/.style={align=left}] {Erwartungswert $\estimates$ mitlerer Abstand\\$\displaystyle{\braket{r}_{\ket{n,l,m}} = \frac{a_b'}{z} n^2 (1 + \frac{1}{2}(1 - \frac{l(l + 1)}{n^2}))}$};
    \begin{scope}[shift={(0,-5)}]
        \node[left,every text node part/.style={align=left}] at (0,2) {$n = 2$ \\ $l = 0$ \\{\color{red}$l = 1$}};
    \draw[->] (0,0) -- ++(12,0) node[below] {$r$};
    \draw[->] (0,0) -- ++(0,3) node[left] {$r^2 \abs{R}^2$};
    \begin{axis}[x=1cm,axis lines=middle,hide axis,ymin=-.0,ymax=.6]
        \addplot[smooth,samples=80,domain=0:12] {2.8*.583*.583*\x*\x*exp(-1.5*\x*.583)*(-0.65*.583*\x + 1)^2};
        \addplot[red,smooth,samples=80,domain=0:12] {1*\x*\x*.583*.583*.583*.583*exp(-2*\x*.583)*\x*\x};
    \end{axis}
    \draw[red] (3.42,2.9) -- ++(0,-.2);
    \draw[red] (3.42,.1) -- ++(0,-.2) node[below] {$4\frac{a_b'}{z}$};
    \draw (8.6,.1) -- ++(0,-.2) node[below] {$4\frac{a_b'}{z}\frac{3}{2}$};
    \draw[dotted] (8.6,2.3) -- ++(0,-2.4);
    \draw[dotted] (8.6,2.3) -- ++(0,-2.4);
    \draw (8.6,2.3) -- ++(0,-0.4);
    \draw[<-] (8.7,2.4) -- ++(.5,.5) node[right,yshift=1pt] {Mittlerer Abstand};
    \end{scope}
\end{tikzpicture}
\end{center}
Allgemein: $l = n - 1$
\[r_{\text{max}} = n^2 \frac{a_b'}{Z}\]
(ergibt auch Bohr Modell)
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
** Wasserstoff - Winkelanteil der elektronischen Wellenfunktion
   Winkelanteil der Wellenfunktion:
   \[P_l^m(\cos θ) e^{i m φ}\]
   $P_l^m(x)$: Legendre-Polynome. Klassischer Drehimpuls:
   \[\v L = \v x × \v p = \cvec{y p_z - z p_y;z p_x - x p_z;x p_y - y p_x} = \cvec{L_x;L_y;L_z}\]
   Quantenmechanische Beschreibung
   \[\v x \to \hat{\v x} \qquad \v p \to \hat{\v p}; \qquad \hat{\v L} = \hat{\v x} × \hat{\v p}\]
   In Ortsdarstellung: $\hat x ↦ x\qquad \hat p_x ↦ - i \hbar \pp{}{x}$
   \[\to \hat L_z ↦ - i \hbar (x \pp{}{y} - y \pp{}{x}) = -i\hbar \pp{}{φ} \text{ in Kugelkoordinaten}\]
   $\hat L_Z \ket{n,l,m}$: Ortsdarstellung
   \begin{align*}
   -i\hbar \pp{}{φ} (R_{n,l}(r) P_l^m(\cos θ) e^{im φ}) &= -i\hbar (i m) R_{n,l}(r) P_l^m(\cos θ) e^{im φ} \\
   ⇒ \hat L_z \ket{n,l,m} &= m \hbar \ket{n,l,m}
   \end{align*}
   das heißt Eigenzustand zu $\hat L_z$ Operator! Damit ist die \(z\)-Komponente des Drehimpulses des Elektrons scharf definiert. $\braket{L_z^2} - \braket{L_z}^2 = 0$ \\
   Teilchen im Zustand $\braket{5,3,2}$ messen wir mit Wahrscheinlichkeit $1$ für die Drehimpulskomponente in z-Richtung $2\hbar$. Das gilt nicht für \(x,y\)-Richtung:
   \[[\hat L_x, \hat L_y] = i \hat L_z\]
   Quadrat des Beitrages des Drehimpulses: $\v L^2 = L_x^2 + L_y^2 + L_z^2$. Es gilt $[\hat{\v L}^2, \hat L_z] = 0$
   \begin{align*}
       \hat{\v L}^2 \ket{n,l,m} &= \underbrace{-\hbar^2 (\frac{1}{\sin θ} \pp{}{θ}(\sin θ \pp{}{θ}) + \frac{1}{\sin^2 θ} \frac{\partial^2}{\partial φ^2})}_{\mathclap{\text{Ortsdarstellung von $\hat{\v L}^2$ in Kugelkoordinaten}}} ψ_{n,l,m} \\
       &= -\hbar^2 (\frac{1}{\sin θ} \pp{}{θ}(\sin θ \pp{}{θ}) + \frac{1}{\sin^2 θ} \frac{\partial^2}{\partial φ^2}) R_{n,l}(r) P_l^m(\cos θ) e^{imφ} = \hbar^2 l(l + 1) ψ_{n,l,m} \\
   \hat{\v L}^2 \ket{n,l,m} &= \hbar^2 l(l + 1) \ket{n,l,m}
   \end{align*}
   Allgemeine Drehimpuls-Eigenzustände: Drehimpuls ist gequantelt: $\abs*{\v L}$ kann nur diskrete $\hbar\sqrt{l(l + 1)}$ Werte annehmen. \\
   Für gegebenen Betrag des Drehimpulses gibt es $2 l + 1$ Einstellmöglichkeiten in \(z\)-Richtung
   $m = -l, -l + 1, \dots, l - 1, l$; Der Wert in \(x\)- und in \(y\)-Richtung ist unbestimmt.
   Typische Darstellung:
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
\begin{tikzpicture}
    \node at (3,2.5) {$l = 1$};
    \draw[->] (0,0) -- ++(3,0) node[below] {$y$};
    \draw[->] (0,-3) node[left] {$0$} -- ++(0,6) node[left] {$L_z$};
    \draw[dotted] (0,-2) arc[radius=2cm,start angle=270,end angle=450];
    \draw[->] (0,0) -- (0:2) node[above right] {$\ket{l = 1, m = 0}$};
    \draw[->] (0,0) -- (45:2) node[above right] {$\ket{l = 1, m = 1}$};
    \draw[->] (0,0) -- (-45:2) node[below right] {$\ket{l = 1, m = -1}$};
    \draw[<-] ({2/sqrt(2)},.1) -- ++(1,1) node[right] {$\hbar \sqrt{l(l + 1)}$ mit $l= 1$};
    \draw[red] (45:2) -- (135:2);
    \draw[red] (0:2) -- (180:2);
    \draw[red] (-45:2) -- (-135:2);
    \draw[dotted] (45:2) -- (0,{2/sqrt(2)}) node[left] {$\hbar$};
    \draw[red,<-] ({-2/sqrt(2) - .1},{2/sqrt(2) -.1}) -- (-2.0,-3.1);
    \draw[red,<-] ({-2 - .1},0) -- (-2.0,-3.1);
    \draw[red,<-] ({-2/sqrt(2) - .1},{-2/sqrt(2) -.1}) -- (-2.0,-3.1) node[below,every text node part/.style={align=left}] {Quantenmechanisch ist $x$ - und $y$-Richtung nicht festgelegt, das heißt unscharf. $[\hat L_x, \hat L_y] = i \hat L_z$ in 3D Darstellung $\estimates$ Kegel};
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
   Nomenkatur:
   \begin{align*}
   l &= 0 &\text{s - Zustand} \\
   l &= 1 &\text{p - Zustand} \\
   l &= 2 &\text{d - Zustand} \\
   l &= 3 &\text{f - Zustand} \\
   \end{align*}
   \begin{align*}
       \hat L_z \ket{l,m} &= \hbar m \ket{l,m} \\
       \hat{\v L}^2 \ket{l,m} &= \hbar l(l + 1) \ket{l,m}
   \end{align*}
   $\ket{l,m}$ sind Drehimpulseigenzustände. In Ortsdarstellung (Kugelkoordinaten):
   \[\ket{l,m} = \frac{1}{\sqrt{2π}} P_l^m (\cos θ) e^{i m φ} = N_{l,m} Y_l^m (θ,φ)\]
   $N$: Normierung. $Y_l^m$: Kugelflächen-Funktion.
   $⇒$ Funktion definiert auf einer Kugeloberfläche kann in $Y_l^{m_l}$ zerlegt werden "Fourierzerlegung auf einer Kugel". $Y_l^{m_l}$ sind
   \begin{align*}
   \text{normiert}\quad ∫_0^{2π} \d φ ∫_0^π \sin θ \d θ \abs{Y_l^{m_l}}^2 &= 1 \\
   \text{orthogonal}\quad ∫_0^{2π} \d φ ∫_0^∞ \sin θ \d θ Y_l^{m\ast} Y_{l'}^{m'} &= δ_{ll'} δ_{mm'}
   \end{align*}
   #+BEGIN_EXPORT latex
   \catcode`(=12
   \catcode`)=12
\begin{center}
    \begin{tikzpicture}[declare function={Y00(\x)=1/(2*sqrt(pi));Y10(\x)=.5*sqrt(3/pi)*sin(\x);Y20(\x)=.25*sqrt(5/pi)*(2*sin(\x)^2 - cos(\x)^2;Y11(\x)=.5*sqrt(1.5/pi)*cos(\x);Y11r(\x)=.5*sqrt(1.5/pi)*sin(\x);Y11i(\x)=-.5*sqrt(1.5/pi)*cos(\x);}]
    \begin{scope}
    \begin{scope}
        \node[right] at (-1,2.4) {$\displaystyle{\ket{l,m_l} = \ket{0,0} \xrightarrow{\text{Ortsdarstellung}} Y_{l = 0}^{m_l = 0} = \frac{1}{2\sqrt{π}}}$};
        \draw [scale=1,domain=0:360, samples=201, smooth] plot ({\x}:{1});
        \draw [black!50!white,scale=1,domain=0:360, samples=201, smooth] plot ({\x}:{1 + Y00(\x)});
        \draw[->] (0,0) -- ++(1.8,0) node[below] {$x$};
        \draw[->] (0,0) -- ++(0,1.8) node[left] {$z$};
        \draw (0,0) node[cross out, draw, minimum size=.2cm, inner sep=0pt, outer sep=0pt] {} node[left,xshift=-2pt] {$y$};
        \draw (0,0) circle (.135cm);
        \draw[->] (2.4,0) -- ++(2,0) node[midway,above] {abrollen};
    \end{scope}
    \begin{scope}[shift={(5,-1)}]
        \draw[->] (0,0) -- ++(5.3,0);
        \draw[->] (0,0) -- ++(0,2);
        \draw [black!50!white,scale=1,domain=0:360, samples=201, smooth] plot ({\x*2.5/180},{4*Y00(\x + 90)});
        \foreach \i/\l in {1/$\frac{π}{2}$,2/$π$,3/$\frac{3π}{2}$,4/$2π$}
            \draw (\i*pi/2.5, .1) -- ++(0, -.2) node[below] {\l};
        \draw[->] (5.2,1) -- ++(2.5,0) node[midway,above] {Polardiagramm};
    \end{scope}
    \begin{scope}[shift={(14,0)}]
    \draw[->] (0,0) -- ++(0,1.8);
    \draw[-latex] (0,1.6) [partial ellipse=400:120:.3cm and .15cm];
    \draw[->,black!50!white] (0,0) -- (45:{4/(2*sqrt(pi))});
    \draw (0,.45) arc[radius=.45cm,start angle=90,end angle=45] node[midway,xshift=-2pt,yshift=2pt,below,font=\small] {$θ$};
    \draw [scale=4,domain=0:360, samples=201, smooth] plot ({\x}:{Y00(\x)});
    \end{scope}
    \end{scope}

    \begin{scope}[shift={(0,-4.8)}]
    \begin{scope}
    \node[right] at (-1,2.4) {$\displaystyle{\ket{l,m_l} = \ket{1,0} \xrightarrow{\text{Ortsdarstellung}} Y_{1}^{0} = \frac{1}{2}\sqrt{\frac{3}{π}}\cos θ}$};
    \draw [scale=1,domain=0:360, samples=201, smooth] plot ({\x}:{1});
    \draw [black!50!white,scale=1,domain=0:360, samples=201, smooth] plot ({\x}:{1 + Y10(\x)});
        \draw[->] (0,0) -- ++(1.8,0) node[below] {$x$};
        \draw[->] (0,0) -- ++(0,1.8) node[left] {$z$};
        \draw (0,0) node[cross out, draw, minimum size=.2cm, inner sep=0pt, outer sep=0pt] {} node[left,xshift=-2pt] {$y$};
        \draw (0,0) circle (.135cm);
        \draw[->] (2.4,0) -- ++(2,0) node[midway,above] {abrollen};
    \end{scope}
    \begin{scope}[shift={(5,-1)}]
        \draw[->] (0,0) -- ++(5.3,0);
        \draw[->] (0,0) -- ++(0,2);
        \draw [black!50!white,scale=1,domain=0:360, samples=201, smooth] plot ({\x*2.5/180},{3*Y10(\x + 90)});
        \foreach \i/\l in {1/$\frac{π}{2}$,2/$π$,3/$\frac{3π}{2}$,4/$2π$}
            \draw (\i*pi/2.5, .1) -- ++(0, -.2) node[below] {\l};
        \draw[->] (5.2,1) -- ++(2.5,0) node[midway,above] {Polardiagramm};
        \draw[white,pattern=north east lines, pattern color=black] (2.5,2) rectangle (5,-2);
        \draw (2.5,2) -- ++(0,-4);
        \draw[<-] (4,1.5) -- ++(.5,.7) node[right] {$θ ∈ [0,π]$};
    \end{scope}
    \begin{scope}[shift={(14,0)}]
    \draw[->] (0,0) -- ++(0,2.4);
    \draw[-latex] (0,2.2) [partial ellipse=400:120:.3cm and .15cm];
    \draw[->,black!50!white] (0,0) -- (45:{4*Y10(45)});
    \draw (0,.45) arc[radius=.45cm,start angle=90,end angle=45] node[midway,xshift=-2pt,yshift=2pt,below,font=\small] {$θ$};
    \draw [scale=4,domain=0:360, samples=201, smooth] plot ({\x}:{Y10(\x)});
    \draw [scale=4,domain=0:360, samples=201, smooth] plot ({\x}:{-Y10(\x)});
    \end{scope}
    \end{scope}

    \begin{scope}[shift={(0,-10.8)}]
    \begin{scope}
    \node[right] at (-1,2.4) {$\displaystyle{\ket{l,m_l} = \ket{2,0} \xrightarrow{\text{Ortsdarstellung}} Y_{2}^{0} = \frac{1}{4}\sqrt{\frac{5}{π}}(2 \cos^2 θ - \sin^2 φ)}$};
    \draw [scale=1,domain=0:360, samples=201, smooth] plot ({\x}:{1});
    \draw [black!50!white,scale=1,domain=0:360, samples=201, smooth] plot ({\x}:{1 + Y20(\x)});
        \draw[->] (0,0) -- ++(1.8,0) node[below] {$x$};
        \draw[->] (0,0) -- ++(0,1.8) node[left] {$z$};
        \draw (0,0) node[cross out, draw, minimum size=.2cm, inner sep=0pt, outer sep=0pt] {} node[left,xshift=-2pt] {$y$};
        \draw (0,0) circle (.135cm);
        \draw[->] (2.4,0) -- ++(2,0) node[midway,above] {abrollen};
    \end{scope}
    \begin{scope}[shift={(5,-1)}]
        \draw[->] (0,0) -- ++(5.3,0);
        \draw[->] (0,0) -- ++(0,2);
        \draw [black!50!white,scale=1,domain=0:360, samples=201, smooth] plot ({\x*2.5/180},{2*Y20(\x + 90)});
        \foreach \i/\l in {1/$\frac{π}{2}$,2/$π$,3/$\frac{3π}{2}$,4/$2π$}
            \draw (\i*pi/2.5, .1) -- ++(0, -.2) node[below] {\l};
        \draw[white,pattern=north east lines, pattern color=black] (2.5,2) rectangle (5,-2);
        \draw (2.5,2) -- ++(0,-4);
        \draw[<-] (4,1.5) -- ++(.5,.7) node[right] {$θ ∈ [0,π]$};
        \draw[->] (5.2,1) -- ++(2.5,0) node[midway,above] {Polardiagramm};
    \end{scope}
    \begin{scope}[shift={(14,0)}]
    \draw[->] (0,0) -- ++(0,3.0);
    \draw[-latex] (0,2.8) [partial ellipse=400:120:.3cm and .15cm];
    \draw[black!50!white] (0,0) -- (36:1.5);
    \draw (0,.7) arc[radius=.7cm,start angle=90,end angle=36] node[midway,xshift=1pt,yshift=2pt,above,font=\small] {$\sim\!\!.3 π$};
    \draw [scale=4,domain=0:360, samples=201, smooth] plot ({\x}:{Y20(\x)});
    \end{scope}
    \end{scope}

    \begin{scope}[shift={(0,-17.5)}] % -18 insert empty page
        \node[right,every text node part/.style={align=left}] at (-1,2.9) {$⇒ Y_{l}^{0}$ erlaubt Polarwinkel-Abhängigkeiten zu beschreiben; $Y_l^{m_l}$ mit $m_l \neq 0 ⇒$ Azimut-Abhängigkeiten zum Beispiel:\\ $\displaystyle{\ket{l,m_l} = \ket{1,\mp 1} \xrightarrow{\text{Ortsdarstellung}} Y_{1}^{\pm 1} = \mp \frac{1}{2}\sqrt{\frac{3}{π}}\sin θ e^{\pm i φ}}$};
    \begin{scope}
        \draw [scale=1,domain=0:360, samples=201, smooth] plot ({\x}:{1});
%\draw [black!50!white,scale=1,domain=0:360, samples=101, smooth] plot ({cos(\x) + Y11(\x)},{sin(\x)});
        \draw [black!50!white,scale=1,domain=0:360, samples=201, smooth] plot ({\x}:{1 - Y11(\x)});
        \draw[->] (0,0) -- ++(1.8,0) node[below] {$x$};
        \draw[->] (0,0) -- ++(0,1.8) node[left] {$z$};
        \draw (0,0) node[cross out, draw, minimum size=.2cm, inner sep=0pt, outer sep=0pt] {} node[left,xshift=-2pt] {$y$};
        \draw (0,0) circle (.135cm);
        \draw[->] (2.4,0) -- ++(2,0) node[midway,above] {abrollen};
    \end{scope}
    \begin{scope}[shift={(5,-1)}]
        \draw[->] (5.2,1) -- ++(2.3,0) node[midway,above] {Polardiagramm};
        \begin{scope}[shift={(0,1.2)}]
        \draw[->] (0,0) -- ++(5.3,0);
        \draw[->] (0,0) -- ++(0,2);
        \draw [black!50!white,scale=1,domain=0:180, samples=201, smooth] plot ({\x*5/180},{4*Y11(\x - 90)});
        \foreach \i/\l in {1/$\frac{π}{2}$,2/$π$}
            \draw (\i*pi/1.25, .1) -- ++(0, -.2) node[below] {\l};
        \node at (4.5,1.3) {$φ = 0$};
        \end{scope}
        \begin{scope}[shift={(0,-1.2)}]
        \draw[->] (0,0) -- ++(5.3,0);
        \draw[->] (0,0) -- ++(0,2);
        \draw [black,scale=1,domain=0:360, samples=201, smooth] plot ({\x*2.5/180},{4*Y11r(\x + 90)});
        \draw [black!50!white,scale=1,domain=0:360, samples=201, smooth] plot ({\x*2.5/180},{4*Y11i(\x - 90)});
        \foreach \i/\l in {1/$\frac{π}{2}$,2/$π$,3/$\frac{3π}{2}$,4/$2π$}
            \draw (\i*pi/2.5, .1) -- ++(0, -.2) node[below] {\l};
        \node at (4.5,1.6) {$φ = \frac{π}{2}$};
        \node[black!50!white,left] at (0,0) {$\Im \{Y_1^{-1}\} \propto -\sin φ$};
        \node[left] at (0,1.4) {$\Re \{Y_1^{-1}\} \propto \cos φ$};
        \end{scope}
    \end{scope}
    \begin{scope}[shift={(14,0)}]
        \draw[->] (0,0) -- ++(0,1.8);
        \draw[-latex] (0,1.6) [partial ellipse=400:120:.3cm and .15cm];
        \draw[->,black!50!white] (0,0) -- (45:{4*Y11(45)});
        \draw [scale=4,domain=0:360, samples=201, smooth] plot ({\x}:{Y11(\x)});
        \draw [scale=4,domain=0:360, samples=201, smooth] plot ({\x}:{-Y11(\x)});
    \end{scope}
    \end{scope}
\end{tikzpicture}
\end{center}
   \catcode`(=\active
   \catcode`)=\active
   #+END_EXPORT
** Zusammenfassung des Modells für Wasserstoff
** Optische Übergänge
  Lich aus Gasentladung von $H_2$ Gas zeigt charakteristische Frequenzen, die bestimmten Energie-Differenzen im Energieeigenwert Spektrum entsprechen. \\
  Behauptung: Die Emission von Licht folgt aus der Superposition von verschiedenen Energieeigenzuständen $n$ und $n'$ mit der zusätzlichen Bedingung $\abs{l - l'} = Δ l = 1$
  (Dipol Auswahlregel)
  Plausibilisierung:

  klassische Elektrodynamik: oszillierender Dipol strahl ab
  \[\v d = q \v x \qquad \v x = \cvec{0;0;z_0 \cos ω t}\]
  $⇒$ Quantenmechanik: $\v d \to \hat{\v d}$, Erwartungswert
  \[\braket{\hat{\v d}} = \braket{ψ | \hat{\v d} | ψ}\]
  1D-lineare Emmision $\v d \to d_z = e z$ \\
  Grundzustand:
  \[\braket{1\,0\,0| e \hat z | 1\,0\,0} = ∫ \underbrace{ψ^{\ast}_{100}(r,θ,φ)}_{\mathclap{\text{gerade}}} \overbrace{e z \underbrace{ψ_{100}(r,θ,φ)}_{\mathclap{\text{gerade}}}}^{\mathclap{\text{ungerade}}} \d V = 0\]
  $⇒$ Zustand hat kein elektrisches Dipolmoment
  \[\braket{ψ_{nlm} | e \hat{\v x} | ψ_{nlm}} = 0 ∀ n,l,m\]
  Das Elektron ist eine Superposition von zwei Zuständen
  \begin{align*}
  \ket{ψ}_{t = 0} &= \frac{1}{\sqrt{2}} \{\underbrace{\ket{n,l,m}}_{\ket{ϕ}} + \underbrace{\ket{n',l',m'}}_{\ket{ϕ'}}\} \\
  \braket{\hat{\v d}} &= \frac{e}{2} ((\bra{ϕ} + \bra{ϕ'}) \hat{\v d} (\ket{ϕ} + \ket{ϕ'})) \\
  &= \frac{e}{2} (\underbrace{\braket{ϕ|\hat{\v d}|ϕ}}_{= 0} + \underbrace{\braket{ϕ'|\hat{\v d}|ϕ'}}_{= 0} + \underbrace{\braket{ϕ | \hat{\v d} | ϕ'} + \braket{ϕ' | \hat{\v d} | ϕ}}_{\mathclap{c + c^{\ast} ⇒ \text{ reelle Zahl}}})
  \end{align*}
  \begin{align*}
  \ket{ψ_t} &= e^{-i \frac{E_1}{\hbar}t} \frac{1}{\sqrt{2}} (\ket{ϕ_s} + e^{-i \frac{E_2 - E_1}{\hbar}t} \ket{ϕ_p}) \\
  \braket{\hat d}_ψ &= \Re (\bra{ϕ_s} e \hat{\v x} e^{-i \frac{E_2 - E_1}{\hbar}t} \ket{ϕ_p}) \\
  &= e \Re (e^{-i ω_{12} t} \underbrace{\braket{ϕ_s | \hat z | ϕ_p}}_{\mathclap{\neq 0 \text{ für $Δ l = \pm 1$, Dipolmatrix Element $D_z$}}}) \\
  &= e \underarrow[D_z]{Dipol in \(z\)-Richtung} \overarrow[\cos{ω_{12} t}]{Oszilliert mit der Frequenz, die der Energie-Differenz entspricht}
  \end{align*}
  Licht emission mit Polarisation in \(z\)-Richtung in \(x\)-\(y\)-Richtung; keine Emission in \(z\)-Richtung; $\v ∇ · \v E = 0$ transversale elektromagnetische Welle.

  Quantitative siehe Lehrbücker zu Quanten-Elektrodynamik (QED) $\estimates$ Photon Konzept; als Ergebnis findet man, dass die Superposition exponentiell zerfällt $\to$ natürliche Lebensdauer.

  Welche Energie hat das Photon? \\
  Der Erwartungswert des Diplos $\v D \propto \braket{a | \hat{\v d} | g}$ zerfällt auch exponentiell

  Welche Frequenzen hat das Licht? \\
  Äquivalent: was misst man in einem Spektrometer? \\
  Lösung: zerlegen elektromagnetisches Feld in $e^{iωt}$
  \begin{align*}
  \to E(t) &= \frac{1}{\sqrt{2π}} ∫_{-∞}^{+∞} E(ω) e^{i ω t} \d ω \\
  ⇒ E(ω) &= \frac{1}{\sqrt{2π}} ∫_{-∞}^{+∞} E(t) e^{-i ω t} \d t
  \end{align*}
  Spektrometer misst $I(ω) = E^{\ast}(ω) E(ω) = \abs{E(ω)}^2$

  \begin{align*}
  ⇒ i \hbar \pp{ψ}{t} &= - \frac{\hbar^2}{2m} \pp{}{x^2} ψ \\
  i \hbar \dd{}{t} \ket{ψ} &= \hat H \ket{ψ} \\
  \ket{ψ} \to \ket{ψ}_{t + \d t} &= e^{-i \frac{\hat H^2}{\hbar}} \ket{ψ}_t
  \end{align*}
  Split-Step-Fourier
** Externe Felder - Zeeman-Effekt (1896)
   Klassisch:
   \[H = \frac{1}{2m_e}(\v p + e \v A(\v x))^2 + V(\v x)\]
   mit $\v A$: Vektorpotential, $\v B = \v ∇ × \v A$
   Quantenmechanik:
   \begin{align*}
   \hat H &= \frac{1}{2m_e}(\hat{\v p}^2 + e \hat{\v p} \hat{\v A} + e \hat{\v A} \hat{\v p} + e^2 \hat{\v A}^2) + V(\hat{\v x}) \\
   \intertext{in Ortsdarstellung mit}
   \v B &= \cvec{0;0;B_z} \estimates \v A = \frac{B_z}{2} \cvec{-y;x;0} \\
   \hat{\v p} \hat{\v A} + \hat{\v A} \hat{\v p} &= -i \hbar \frac{B_z}{2}(\cvec{\partial_x;\partial_y;\partial_z} · \cvec{-y;x;0} + \cvec{-y;x;0}\cvec{\partial_x;\partial_y;\partial_z})
   &= -i \hbar \frac{B_z}{2} (-\partial_x y + \partial_y x - y \partial_x + x \partial_y) = -i \hbar B_z (x \partial_y - y \partial_x)= B_z \hat L_z \\
   \hat H &\underarrow[=]{in Ortsdarstellung} \underbrace{\frac{1}{2m_e} \Laplace + V(\v x)}_{\mathclap{\text{Wasserstoff ohne Magnetfeld}}} + \frac{e}{2m_e} \underbrace{\frac{\hbar}{i}(x \partial_y - y \partial_x)}_{\hat L_z} + \underbrace{\frac{e^2}{2 m_e} \frac{B_z^2}{4}(x^2 + y^2)}_{\mathclap{\sim \SI{1e-6}{\per\tesla}B_z}\text{ kleiner als $\braket{B_z · \hat L_z}$ Term in "`standard"' Labor $B\sim \SI{10}{\tesla}$}}
   \end{align*}
   Der $\hat L_z$ Term ist nur in \(z\)-Richtung, das legt das Koordinatensystem fest.
   \begin{align*}
   \hat H &= \hat H_0 + \frac{e}{2 m_e} B_z \hat L_z \\
   \hat H_0 \ket{n\, l\, m} &= E_n \ket{n\,l\,m} \\
   \intertext{mit $m \estimates z$-Komponente des Drehimpulses, wird auch Magnet-Quantenzahl genannt}
   ⇒ \hat H \ket{n\, l\, m} &= E_n + \frac{e\hbar}{2m_e} m B_z \ket{n\, l\, m}
   \intertext{wir definieren $μ_B$ - Bohrsches Magneton}
   μ_B &= \frac{e \hbar}{2 m_e}
   \end{align*}
* Spin
   Darwin Term ist nur für Zustände mit	$l = 0$ nicht null
   \[ΔE_D = \frac{π \hbar^2}{2m^2 c^2} \frac{Z e^2}{4π ε_0} \underbrace{∫ ψ_{n00}^{\ast} (n) δ(n) μ_{n00}(n) \d V}_{= \abs{Ψ_{n00}(0)}} = - E_n \frac{(2α)^2}{n}\]
   Alle Terme bis $\mathcal{O}(\frac{v}{c})^2$
   \begin{align*}
   E_{nj} &= E_n (1 + \frac{Z^2 α^2}{n^2}(\frac{n}{j + \frac{1}{2}} - \frac{3}{4}))
   \end{align*}

   $\v S$ und $\v L$ liegen in unterschiedlichen Vektorräumen $⇒$
   \[[\v L, \v S] = 0\]
* 2 Elektronen System am Beispiel Helium
** Helium - $2p, 2n, 2e^{-}$: Modell: $Z = 2$
   Wichtig:	Zusätzlich zur anziehenden Wechselwirkung (\(e^{-}\)-Kern) gibt es abstoßende Wechselwirkungen (\(e^{-}\)-\(e^{-}\)) \\
   Ortsdarstellung:
   \begin{align*}
   H &= \underbrace{-\frac{\hbar^u}{2μ}(\Laplace_1 + \Laplace_2)}_{\mathclap{\text{kinetische Energie}}} - \overbrace{\frac{Z e^2}{4π ε_0 \abs{\v r_1}} - \frac{Z e^2}{4π ε_0 \abs{\v r_2}}}^{\mathclap{\text{Elektron-Kern Wechselwirkung}}} + \underbrace{\frac{e^2}{4π ε_0 \abs{\v r_{12}}}}_{Elektron Elektron Wechselwirkung} \\
   μ &= \frac{m_e m_k}{m_e + m_k} \sim m_e
   \end{align*}
   Grundzustandsenergie ohne Elektron-Elektron-Wechselwirkung: $2×$	 Wasserstoff mit $Z = 2$
   \[E_{n - 1} = 2 × Z^2 (\SI{-13.6}{\electronvolt}) = \SI{-108.8}{\electronvolt}\]
   Beobachtet wird, dass die vollständige Ionisierung
   \[H_e \to H_e^{++} + e^{-} \]
   $\SI{79}{\electronvolt}$ benötigt wird.
   kleinere Bindungsenergie folgt aus Elektron-Elektron-Wechselwirkung. Schätzen Elektron-Elektron-Wechselwirkung mit Störungstheorie (1. Ordnung) ab:
   \[\Laplace E_{e^{-} - e^{-}-\text{WW}} = \frac{e^2}{4π ε_0} \braket{ψ | \frac{1}{\abs{\v r_{12}}} | ψ}\]
   $\ket{ψ}$ ist ein zwei-Elektronen Zustand. Nehmen zwei unabhängig gebundene $e^{-}$ an $⇒$ $\ket{ψ}$ in Ortsdarstellung
   \[ψ_n(\v r_1, \v r_2) = \underbrace{ψ_n(\v r_1)}_{\mathclap{\text{Lösung von Wasserstoff mit $Z = 2$}}} ψ_n(\v r_2) \]
   Für Grundzustand: $ψ_{n = 1}^1(\v r) = ψ_{n = 1}^2(\v r) = ψ_{100}(\v r)$
   \[⇒ ψ(\v r_1, \v r_2) = \frac{1}{π} \frac{Z^3}{a_B^3} e^{- \frac{Z}{a_B}}\]
** Spin Feiheitsgrad
   $⇒$ Energie-Eigenzustände werden Gesamtspin haben $hat{\v S} = \hat{\v S_1} + \hat{\v S_2}$ \\
   Analog zu $\v j ⇒ \hat{\v S}^2, \hat S_{z}$ Eigenzustände $\ket{s, r_s}$.
   \begin{align*}
   \hat{\v S}^2 &: s_1 - s_2 \leq S \leq s_1 + s_2 \\
   \hat{S_z}&: - s \leq r_s \leq s
   \end{align*}
   Beispiel:
   \begin{align*}
   s_1 &= \frac{1}{2} \\
   s_2 &= \frac{1}{2} \\
   s &= 0, r_s = 0 \tag{Singulett} \\
   s &= 1, r_s = -1, 0, 1 \tag{Triplett}
   \end{align*}
   Wie sehen die Eigenzustände zu $S = 0$ und $S = 1$ aus? \\
   Wähle Basis $\ket{\uparrow \downarrow}$ Teilchen $1$ und $\ket{\uparrow}$, Teilchen 2 ind $\ket{\downarrow}$, $\ket{\downarrow,\uparrow}, \ket{\downarrow, \downarrow}, \ket{\uparrow, \uparrow}$
   \[\hat{\v S}^2 \ket{ψ} = (\hat{\v S_1} + \hat{\v S_2})^2 \ket{ψ} = \hat{\v S_1}^2 + \hat{\v S_2}^2 + 2 \hat{\v S_1} \hat{\v S_2} \ket{ψ} = \hbar^2 s(s + 1) \ket{ψ}\]
   \begin{alignat*}{3}
   S^x \ket{\uparrow} = \frac{\hbar}{2} \ket{\downarrow} && S^y \ket{\uparrow} = \frac{\hbar}{2} \ket{\downarrow} && S^z \ket{\uparrow} = \frac{\hbar}{2} \ket{\downarrow} \\
   S^x \ket{\downarrow} = -\frac{\hbar}{2} \ket{\downarrow} && S^y \ket{\downarrow} = -\frac{\hbar}{2} \ket{\downarrow} && S^z \ket{\downarrow} = -\frac{\hbar}{2} \ket{\downarrow} \\
   \ket{ψ} &= \ket{\uparrow \downarrow}
   \end{alignat*}{3}
\printbibliography
