* Zentralkraftproblem
** Motivation
   für Kräfte zwischen Massenpunkten die parallel zur Verbindungslinie wirken: Potentialbeschreibung
   \[\v F_1 = \underarrow[-\v \nabla_1]{$\v x_1$} V(\abs{\v x_1 - \v x_2})\]
   Besonders wichtig:
   \[V(r) \sim \frac{1}{r}\]
   #+ATTR_LATEX: :options [Gravitation]
   #+begin_ex latex
   \begin{align*}
   V(\abs{\v x_1 - \v x_2}) &= - \frac{G_N m_1 m_2}{\abs{\v x_1 - \v x_2}} \\
   \v F_1 = -\frac{-\v x_1 - \v x_2}{\abs{\v x_1 - \v x_2}^3} F_n m_1 m_2 \\
   &= -\frac{\v x_1 - \v x_2}{\abs{\v x_1 - \v x_2}} \frac{G_N}{(\v x_1 - \v x_2)^2}
   \end{align*}
   Nichttriviale Aussage: "träge Masse = schwere Masse"
   #+end_ex
   #+ATTR_LATEX: :options [Elektrostatik]
   #+begin_ex latex
   \[V = \frac{q_1 q_2}{4\pi \eps \abs{\v x_1 -\v x_2}}\]
   #+end_ex
   Vereinfachung:
   1. Masse $m_2$ bei $\v 0$ fixiert
   2. $m_2 \gg m_2 \implies$ analog zu 1.
   \[\implies V(\v x) = - \frac{G_N m_1 m_2}{\abs{\v x}} = V(r) = - \frac{G_n m_1 m_2}{r}\]
** Zweikörperproblem
   Lassen Bewegung beider Massen zu
   \begin{align*}
   m_1 \ddot{\v x}_1 &= - \v\nabla_1 V(\abs{\v x_1 - \v x_2}) \\
   m_2 \ddot{\v x}_2 &= - \v\nabla_2 V(\abs{\v x_1 - \v x_2}) \\
   \intertext{Betrachte passende Linearkombination:}
   \ddot{\v x}_1 - \ddot{\v x}_2 &= \frac{1}{m_1}(-\v\nabla V(\abs{\v x_1 - \v x_2})) - \frac{1}{m_2}(-\v\nabla_2(\abs{\v x_1 - \v x_2})) \\
   &= \underbrace{(\frac{1}{m_1} + \frac{1}{m_2})}_{\equiv \frac{1}{m}}(-\v\nabla_1(\abs{\v x_1 - \v x_2})) \\
   \intertext{Man erhält Gleichung für die "Relativkoordinate" $\v x_1 - \v x_2$}
   \hspace{0pt}(\v x_1 - \v x_2)^{..} &= \frac{1}{m}(-\v\nabla V(\abs{\v x_1 - \v x_2}))
   \frac{1}{m} \equiv \frac{1}{m_1} + \frac{1}{m_2} = \frac{m_1 m_2}{m_1 + m_2}\tag{Reduzierte Masse}
   \intertext{Zusätzlich: Addition der beiden Gleichungen gibt:}
   m_1 \ddot{\v x}_1 + m_2 \ddot{\v x}_2 &= 0 \\
   \implies \ddot{\v x}_s &= 0 \\
   \intertext{Mit $\v x_s \equiv$ Schwerpunktskoordinate, bewegt sich frei}
   \v x_s &\equiv \frac{m_1 \v x_1 + m_2 \v x_2}{m_1 + m_2}
   \intertext{$\implies$ Das zu lösende Problem ist also nur die Bewegung der Relativkoordinate}
   m\ddot{\v x} = - \v\nabla V(\abs{\v x})
   \intertext{Das ist Zentralkraftproblem mit ursprünglichem Potential, aber mit der reduzierten Masse}
   \end{align*}
** Allgemeine Koordinatensysteme
   Kenne bereits: $\mathbb{C} = \mathbb{R}^2$
   \begin{align*}
   x^1 &= \Re z \\
   x^2 &= \Im z
   \intertext{$\implies$}
   r &= \abs{z} \\
   \phi &= \arg{z}
   \end{align*}
   "Polarkoordinaten", sind einfaches Beispiel für mögliche allgemeine Parametrisierung.
   #+ATTR_LATEX: :options [Zylinderkoordinaten]
   #+begin_ex latex
   \begin{align*}
   x^1 &= r\cos{\phi} \\
   x^2 &= r\sin{\phi} \\
   x^3 &= z
   \end{align*}
   Wichtig: Eineindeutige Abbildung $(x^1, x^2, x^3) \leftrightarrow (r, \phi, z)$ (und allgemein). Hier:
   \begin{align*}
   r &= \sqrt{(x^1)^2 + (x^2)^2} \\
   \phi &= \arctan{\frac{x^2}{x^1}} \\
   z &= x^3
   \end{align*}
   #+end_ex
   #+ATTR_LATEX: :options [Kugelkoodinaten]
   #+begin_ex latex
   \begin{align*}
   x^1 &= r\sin{\theta}\cos{\phi} \\
   x^2 &= r\sin{\theta}\sin{\phi} \\
   x^3 &= r\cos{\theta}
   \end{align*}
   #+end_ex
** Zentralkraftproblem
   (Nach allgemeines $V(r)$). Wir wissen bereits:
   \[\v L = \v r \times \v p = ~\text{const}, \v p = m\dot{\v r}, \v r = ~\text{Koordinaten des Teilchens}\]
   Es gilt $\v L \perp \v r \wedge \v L =~\text{const} \implies$ Bewegung in gester Ebene. Also
   ohne Beschränkung der Allgemeinheit ist die Bewegung in der $(1-2)$ -Ebene. Außerdem:
   Problem rotationssymmetrisch. \\
   $\implies$ angemessene Beschreibung: Polarkoordinaten (Winkel und Rotation) \\
   naiv: \[m \underarrow[\ddot{\v x}]{durch $r,\phi$ ausdrücken} = \v F(\v x)\]
   eleganter: Weiter mit Drehimpulserhaltung (wieder: $\v x \to \v r$)
   \[\v L = ~\text{const}, ~\text{const} = \abs{\v L} = m\abs{\v r \times \dot{\v r}} = m r\cdot r\dot{\phi} = mr^2\dot{\phi}\]
   Nachrechnen:
   \begin{align*}
   \dot{\v r} &= (r\cos{\phi}, r\sin{\phi})^{.} \\
   &= \underbrace{(\dot{\v r}\cos{\phi},\dot{\v r}\sin{\phi})}_{\parallel \v r \implies ~\text{Radialgeschwindigkeit}} + \underbrace{(r(-\sin{\phi}), r\cos{\phi})\dot{\phi}}_{\perp \v r \implies ~\text{Tangentialgeschwindigkeit}}
   \intertext{Insbesondere:}
   r\dot{\phi} \equiv~\text{Betrag der Tangentengeschwindigkeit}
   \end{align*}
   Konstanz von $\abs{\v L}$ geometrische Interpretation: \\
   Berechne die von "Leitstrahl" in Zeit $\d t$ überstrichene Fläche: "Die Flächengeschwindigkeit ist konstant" (2. Keplersches Gesetz)
   \begin{align*}
   \d f = \frac{1}{2}r r \d\phi \\
   \dd{f}{t} = \frac{1}{2}r^2 \dot{\phi} = ~\text{const}
   \end{align*}
   Energieerhaltung:
   \[E = \frac{m}{2} \dot{\v r}^2 + V(r) = \frac{m}{2}(\dot{r}^2 + r^2 \dot{\phi}^2 + V(r) = ~\text{const})\]
   Kombinieren mit Drehimpulserhaltung gibt: ($L \equiv \abs{\v L}$)
   \begin{align*}
   \dot{\phi} &= \frac{L}{m r^2} \\
   E &= \frac{m}{2} r^2 + \frac{L^2}{2mr^2} + V(r) \\
   \intertext{Definiere:}
   U(r) \equiv \frac{L^2}{2mr^2} + V(r) \\
   \intertext{$\implies$ Energieerhaltung:}
   E = \frac{m}{2} \dot{r}^2 + U(r)
   \end{align*}
   Dies ist die Energieerhaltung für das "effektive 1-dimensionale Problem mit dem effektiven Potential".
   Dieses ist allgemein lösbar mit
   \[\int \d t = \int \frac{\d r}{\sqrt{\frac{2}{m}(E - U(r))}}\]
   Damit $t = t(r)$
   \[\implies r = r(t) \implies \dot{\phi}(t) \implies \phi(t) \tag{Integrieren}\]
   Explizit lösbar: $V\sim \frac{1}{r}, V\sim r^2$
** Qualitative Lösung des Zentralkraftproblems
   \begin{align*}
   E &= \frac{m}{2} \dot{r^2} + U(r) \\
   U(r) &= \frac{L^2}{2mr^2} + V(r) \\
   &= \frac{L^2}{2mr^2} - \frac{\alpha}{r} \tag{Kepler} \\
   \alpha &= g_N m_1 m_2
   \end{align*}
   - Fall 1: $E > 0 \implies$ minimales, aber kein maximales $r$
   - Fall 2: $E < 0 \implies r$ zwischen zwei Extrema
   $V \sim \frac{1}{r} \implies$ keine Periheldrehung. \\
   allgemeiner: Periheldrehung triff auf! (kein Schließen der Bahn)
** Kepler-Problem: Bahnform
   \begin{align*}
   E &= \frac{m}{2} \dot{r}^2 + \frac{L^2}{2 m r^2} - \frac{\alpha}{r} \\
   \dot{E} = 0 &= m \dot{r}\ddot{r} - \frac{L^2}{m r^3}\dot{r} + \frac{\alpha}{r^2}\dot{r} \\
   m \ddot{r} = \frac{L^2}{mr^3} - \frac{\alpha}{r^2} \\
   \intertext{Schreibe $\dd{}{t}$ in $\dd{}{\phi}$ um, da $r(t)$ nicht lösbar:}
   \dd{}{t}(\ldots) &= \dd{\phi}{t} \dd{}{\phi}(\ldots) \\
   &= \frac{L}{m r^2} \dd{}{\phi}(\ldots) \\
   \intertext{speziell:}
   \dot{r} &= \frac{L}{m r^2} \dd{}{\phi}(r) = -\frac{L}{m} \dd{}{\phi}(\frac{1}{r}) \\
   m \ddot{r} &= m \frac{L^2}{m r^2} \dd{}{\phi}(- \frac{L}{m} \dd{}{\phi}(\frac{1}{r})) \\
   &= -\frac{L^2}{mr^2}\frac{\d^2}{\d \phi^2}(\frac{1}{r}) \\
   -\frac{L^2}{mr^2}\frac{\d^2}{\d \phi^2}(\frac{1}{r}) &=  \frac{L^2}{m r^3} - \frac{\alpha}{r^2} \\
   \frac{\d^2}{\d\phi^2}(\frac{1}{r}) &= -\frac{1}{r} + \frac{m \alpha}{L^2} \\
   \intertext{Definiere $u \equiv \frac{1}{r}, \dd{}{\phi}(\ldots) = (\ldots)'$}
   u'' &= -u + \frac{m \alpha}{L^2} \\
   \intertext{harmonischer Oszillator mit äußerer Kraft, weiter mit $w \equiv u - \frac{m \alpha}{L^2}$}
   w'' &= -w \\
   \intertext{Allgemeine Lösung:}
   w &= A\cos{\phi - \phi_0} \\
   \intertext{Ohne Beschränkung der Allgemeinheit: $\phi_0 = 0$, so dass}
   \frac{1}{r} - \frac{m\alpha}{L^2} &= A\cos{\phi} \\
   r &= \frac{1}{\frac{m\alpha}{L^2} + A\cos{\phi}} \\
   r &= \frac{p}{1 + e\cos{\phi}} \\
   p &= \frac{L^2}{m\alpha} \\
   e &= \sqrt{2 + \frac{2EL^2}{m\alpha^2}}
   \end{align*}
   Herleitung der letzten Formel für $e$:
   \begin{align*}
   \intertext{leite nach $t$ ab:}
   r &= \frac{p}{1 + e\cos{\phi}} \\
   \intertext{Diese verschwindet bei $\phi = 0$. Dort gilt dann:}
   E &= \frac{L^2}{2mr^2} - \frac{\alpha}{r} \\
   r &= \frac{p}{1 + e} = \frac{\frac{L^2}{m\alpha}}{1 + e} \\
   \intertext{Beides zusammen ergibt:}
   e = \sqrt{1 + \frac{2 EL^2}{m\alpha^2}}
   \end{align*}
** Kegelschnitte
   Kreis, Ellipse, Parabel, Hyperbel
   \[r = \frac{p}{1 + e\cos{\phi}}\]
   - Kreis: $e = 0, r =~\text{const}$, physikalisch: $E = U_{min}$
   - Ellipse: $0 < e < 1 \implies r$ beschränkt
	 \begin{align*}
	 \phi = 0 &\implies r = \frac{p}{1 + e} \\
	 \phi = \pi &\implies r = \frac{p}{1 - e} \\
	 \phi = \pi \frac{\pi}{2} &\implies r = p \\
	 \frac{p}{1 + e} \tag{Perihelabstand}
	 \intertext{Außerdem}
	 2 a &= p(\frac{1}{1 + e} - \frac{1}{1 - e}) = \frac{2p}{1 - e^2} \\
	 a &= \frac{p}{1 - e^2}
	 \intertext{Für die kleine Halbachse: Maximiere $y \implies$ maximiere $y^2$ (äquivalent)}
	 0 &\overset{=}{!} \dd{y^2}{r} \\
	 y^2 &= (r\sin{\phi})^2 = r^2(1 - \cos^2{\phi}) = r^2(1 - \frac{1}{e^2}(\frac{p}{r} - 1)^2) = r^2 - \frac{1}{e^2}(p - r)^2 \\
	 0 &= 2(r + \frac{1}{e^2}(p - r)) \\
	 r_0 &= \frac{\frac{-p}{e}}{1 - \frac{1}{e^2}} = \frac{p}{1 - e^2} \\
	 \intertext{Einsetzen in obige Formel für $y$:}
	 y_{max} = \frac{p}{\sqrt{1 - e^2} \equiv b}
	 \end{align*}
	 Andere Definition der Ellipse
	 \[\frac{\tilde x^2}{a^2} + \frac{\tilde y^2}{b^2} = 1\]
	 Vorsicht: $x,y$ verschieden von $\tilde x, \tilde y$.
   - Parabel: $e = 1$, physikalisch: $E = 0$, Körper "kommt im Unendlichen zur Ruhe", weil
	 \[\frac{m}{2}v^2 = E - U(r) \wedge U(\infty) = 0\]
	 Skizze, etc.: DIY
   - Hyperbel: $e > 1, E > 0$, Körper hat für $r\to\infty$ nicht verschwindende Grenzgeschwindigkeit.
	 \begin{align*}
	 \phi = 0 &\implies r = \frac{p}{1 + e} \\
	 \phi = \pm \frac{\pi}{2} &\implies r = p \\
	 r = \infty &\implies 0 = 1 + e\cos{\phi} \iff \phi = \arccos{-\frac{1}{e}} \\
	 \intertext{Wichtiger: Streuwinkel $\theta$:}
	 \theta &= \pi - 2(\pi - \phi) = 2\phi - \pi
	 \end{align*}
** Die Trajektorie
   Wie bekannt:
   \[t = \int \frac{r\d r}{\sqrt{\frac{2E}{m}r^2 + \frac{2\alpha}{m}r - \frac{L^2}{m^2}}}\]
   Brauchen Fallunterscheidung für $E$
*** Ellipse
	\begin{align*}
	t &= \sqrt{\frac{m}{2\abs{E}}} \int \frac{r \d r}{\sqrt{-r^2 + \frac{2\alpha}{m} r - \frac{L^2}{m^2}}} \\
	\intertext{Ersetze: $r \to s, r -a \equiv s a e$}
	&= \frac{\d s(s + \frac{1}{e})}{\sqrt{1 - s^2}} \\
	\intertext{Ersetze $s = -\cos{\eta}$}
	t = \sqrt{\frac{ma^2}{2\abs{E}}}(\eta - e\sin{\eta}) \\
	r = a(1 - e\cos{\eta})
	\end{align*}
	Dies ist die Parameterdarstellung.
** Umlaufzeit
   (Ellipsenbahn)
   \[T = \int_{1~\text{Umlauf}} \d t \underarrow[=]{$\dd{f}{t} = \frac{1}{2} r^2 \dot{\phi}$}, L = mr^2\dot{\phi} \frac{2m}{L} \int_{1~\text{Umlauf}} \d f = \frac{2m}{L} F_{ell} = \frac{2m}{L} \pi ab\]
   Begründung von $F_{ell} = \pi ab$:
   Ellipse: \[\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1 \xrightarrow{\text{Koordinatenwechsel}} x^{\prime 2} + y^{\prime 2} = 1\]
   Also:
   \[F_{ell} = \int_{\text{Ell}} \d x \d y = ab \int_{Einh.kreis} \d x' \d y' = \pi ab \checkmark\]
   \begin{align*}
   T &= \frac{2\pi m}{L} ab = \frac{2\pi m}{L} \frac{p^2}{\sqrt{1 - e^2}^3} = \frac{2\pi m}{L} \frac{(\frac{L^2}{m\alpha})^2}{(\frac{2\abs{E}L^2}{m\alpha^2})^{\frac{3}{2}}} = \pi \alpha \sqrt{\frac{m}{2\abs{E}^3}} \\
   \intertext{Mit $a = \frac{\alpha}{2 \abs{E}}$:}
   &= 2\pi a^{\frac{3}{2}} \sqrt{\frac{m}{\alpha}}
   \end{align*}
   #+ATTR_LATEX: :options [Zweites Keplersches Gesetz]
   #+begin_thm latex
   $T$ ist proportional zu $a^{\frac{3}{2}}$.
   #+end_thm
   (Zur Vollständigkeit:)
   #+ATTR_LATEX: :options [Erstes Keplersches Gesetz]
   #+begin_thm latex
   Umlaufbahnen sind Ellipsen, in deren einem Brennpunkt die Sonne steht.
   #+end_thm
   #+begin_remark latex
   Analoge Analyse für $V = \frac{+\alpha}{r} \implies$ stets Hyperbelbahnen:
   \[r = \frac{p}{-1 + e\cos{\phi}}\]
   Es existiert eine *dritte* Erhaltungsgröße. Lenzscher Vektor:
   \[\bar v \times \bar L - \frac{\alpha \bar r}{r} \implies ~\text{noch elegantere Analyse möglich}\]
   Die Annahme $m_2 \gg m_1$ stimmt für System Erde-Mond nicht sehr gut. $\implies$ Gezeitenberge, Zentrifugalkraft, örtlich variierende Gravitationskraft.
   #+end_remark
