* Zerfalls und Stoßprozesse
  Chemie, Kernphysik, Teilchenphysik (QM-Aspekte sehr wichtig $\to$ später), astrophysikalische  Prozesse (zum Beispiel kollisionsfreie Begegnung zweier Himmelskörper)
** Stoßparameter und Streuwinkel
   Streuwinkel $\theta$ folgt eindeutig aus $b$ (bei mechanischem System) $\implies$ Funktion $\theta = \theta(b)$. Bei perfekt reflektierender Kugel leicht zu berechnen:
   \begin{align*}
   \pi &= 2\Delta\phi + \theta, b = R\sin(\Delta\phi) \\
   \intertext{Auflösen nach $\theta$}
   \theta(b) = \pi - 2\arcsin{\frac{b}{R}} = r\arccos(\frac{b}{R})
   \end{align*}
   Allgemeiner: Streuung an Zentralpotential $V(r)$ (hier mit abstoßender Kraft)
   Obige starre Kugel entspricht dann dem Grenzfall
   \[V(r) = \begin{cases} 0 & r > R \\ \infty r \leq R\end{cases}\]
   \begin{align*}
   \intertext{Starte mit}
   \d t &= \frac{\d r}{\sqrt{\frac{2}{m}(E - U(r))}}, L = m r^2 \dd{\phi}{t} \\
   \intertext{Hierbei: $E = \frac{m}{2}v_\infty^2, L = m v_\infty b$}
   \phi &= \int \frac{\frac{L^2}{r^2}\d r}{\sqrt{2m(E - V(r)) - \frac{L^2}{r^2}}} \\
   \Delta \phi &= \int_{r_{min}}^{\infty} \frac{\frac{b\d r}{r^2}}{\sqrt{1 - \frac{V(r)}{E} - \frac{b^2}{r^2}}} \\
   \intertext{$r_{min}$ ist Lösung zu}
   1 - \frac{V(r)}{E} - \frac{b^2}{r^2} &= 0 \\
   \intertext{In der Tat: Bei $r_{min}$ ist gerade $\d r = 0$ obgleich $\d \phi \neq 0$ ist. Diest geschieht exakt wenn $\sqrt{\ldots} = 0$}
   \implies \theta(b) &= \pi - 2\Delta\phi \tag{allgemein bekannt} \\
   \intertext{Für konkreten Fall $V(r) = -\frac{\alpha}{r}$ kennen wir Ergebnis:}
   \theta &= 2\phi - \pi, \cos\phi = -\frac{1}{e}
   \intertext{Wir haben also:}
   \sin \frac{\Theta}{2} &= \sin(\phi - \frac{\pi}{2}) = -\sin(\frac{\pi}{2} - \phi) = -\cos \phi = \frac{1}{\sqrt{1 - \frac{2EL}{m\alpha^2}}}
   \intertext{Nutze: $L = mr_\infty b, E = \frac{m}{2} v_\infty^2$}
   \theta(b) &= 2\arcsin(\frac{1}{\sqrt{1 + (\frac{2Eb}{\alpha})^2}})
   \end{align*}
** Wirkungsquerschnitt
   Teilchenstrahldichte:
   \[n = \frac{\text{Teilchenzahl}}{\text{Fläche}\cdot\text{Zeit}}, [n] = \si{\per\meter\squared\per\second}\]
   $\implies \overarrow[Zahl der gestreuten Teilchen pro Zeit]{N}= n \cdot \underarrow[\sigma_{tot}]{Querschnittsfläche des Targets}, [N] = \si{\per\second}$ \\
   $\sigma_{tot}$- totaler Wirkungsquerschnitt, $\sigma_{tot} \equiv \frac{N}{n}$ \\
*** Differentieller Qirkungsquerschnitt
	\begin{align*}
	\d N &= n(\dd{\sigma}{\theta}(\theta)) \\
	\intertext{Ring im Bild hat Fläche:}
	2 \pi b \cdot \d b &= \d \sigma \\
	\d \Theta = \abs{\frac{\d \Theta(b)}{\d b}}\abs{\d b} \\
	\intertext{Damit können wir $\frac{\d \sigma}{\d \theta}(\theta)$ bei bekannter Funktion $\theta(b)$ berechnen:}
	\d N &= n\d\sigma = n2\pi b \d b = n 2pi b \abs{\frac{\d \theta}{\d b}}^{-1} \d \theta \equiv n (\frac{\d \sigma}{\d \theta})\d \theta \\
	\frac{\d\sigma}{\d\theta}&= 2\pi b \abs{\frac{\d\theta}{\d b}}^{-1} = 2\pi b \abs{\frac{\d b}{\d\theta}} \\
	\intertext{speziell:}
	b(\theta) &= R\cos(\frac{\theta}{2}) \tag{Starre Kugel} \\
	\frac{\d \sigma}{\d \theta} &= \pi b R\sin \frac{\theta}{2}
	\intertext{Es ist üblich $\d \theta$ in den differentiellen Raumwinkel umzurechnen:}
	\sigma^2 \d \Omega &= 2\pi \sin{\theta} \sigma \d \theta \sigma \\
	b(\theta) &= R\cos(\frac{\theta}{2}) \\
	\dd{\sigma}{\theta} &= \pi b R \sin{\frac{\theta}{2}} \\
	\dd{\sigma}{\Omega} &= \frac{R^2}{4} \\
	\dd{\sigma}{\Omega} &= \frac{\d \sigma}{2\pi \sim{\theta \d\theta}} = \frac{\pi b R\sin{\frac{\theta}{2}}}{2\pi\sin{\theta}} = \frac{\pi R^2 \cos{\frac{\theta}{2}}\sin{\frac{\theta}{2}}}{2\pi\sin{\theta}} \checkmark \\
	\intertext{$\implies$ gleichberechtigte Streuing in alle Richtungen. Integration:}
	\sigma_{tot} &= \int \d \Omega (\frac{\d \sigma}{\d \Omega}) = (\int \d \Omega) \frac{R^2}{4} = \pi R^2 \checkmark \\
	\intertext{Analoge allgemeine Rechung:}
	\sigma_{tot} &= \int_{0}^{\pi}\d \theta (\frac{\d \sigma}{\d \theta}) = \int_{0}^{\pi}\d\theta 2\pi b \abs{\frac{\d b}{\d \theta}} = \int_{0}^{R} \d b2\pi b = \pi R^2 \\
	\intertext{gilt nur, wenn $\theta(b)$ bei eindlichem $b$ verschwindet}
	\end{align*}
** Rutherford-Streuung
   \begin{align*}
   V(r) &= \frac{\alpha}{r}, \alpha = \frac{q_1 q_2}{4\pi \eps_0} \\
   \intertext{außerdem:}
   \sin \frac{\theta}{2} &= \frac{1}{\sqrt{1 + x^2}} \implies x = \frac{\cos{\frac{\theta}{2}}}{\sin{\frac{\theta}{2}}} \\
   \implies \dd{x}{\theta} &= -\frac{\frac{1}{2}}{\sin^2 \frac{\theta}{2}} \implies \abs{x \dd{x}{\theta}} = \frac{\cos{\frac{\theta}{2}}}{2 \sin^3{\frac{\theta}{2}}} \\
   \dd{\sigma}{\theta} &= \pi (\frac{\alpha}{m v^2})^2 \frac{\cos{\frac{\theta}{2}}}{\sin^3{\frac{\theta}{2}}}, \d \Omega = \d \theta 4\pi \sin \frac{\theta}{2} \cos \frac{\theta}{2} \\
   \implies \dd{\sigma}{\Omega} = (\frac{\alpha}{2mv^2})^2 \frac{1}{\sin^4(\frac{\theta}{2})}
   \end{align*}
   $\implies$ Rutherford-Streuung:
   \[\dd{\sigma}{\Omega} = (\frac{\alpha}{2mv^2})^2 \frac{1}{\sin^4 \frac{\theta}{2}} \sim \frac{1}{\theta^4}\]
   $\implies \sigma_{tot} = \infty$
   Begründung:
   \begin{align*}
   \int \dd{\sigma}{\Omega}\d\Omega &= \int_{0}^{\pi} \dd{\sigma}{\Omega}2\pi \sin{\theta} \d\theta \\
   \intertext{Bei kleinem $\theta$:}
   &\sim \int_{0}^{..}\d\theta \theta \frac{1}{\theta^4} \sim \int_{0}^{...} \dd{\theta}{theta^3} `"='" ~\text{$\infty$}
   \end{align*}
   #+begin_ex latex
   \[\int_{\eps}^{1} \frac{\d x}{x^\alpha} \sim \frac{1}{x^{\alpha - 1}} \Big|_1^\eps \sim (\frac{1}{\eps})^{\alpha - 1} \xrightarrow{\alpha > 1} \infty\]
   #+end_ex
** Teilchenzerfall
   #+ATTR_LATEX: :options
   #+begin_ex latex
   - Mesonen-Zerfall: $\rho \to \pi \pi$
   - nicht-quaten-mechanisch: Explosionen
   - Higgs-Zefälle am LHC: $H \to \gamma \gamma, H \to b b$
   #+end_ex

   Masse $M$, innere Energei $U$:
   \[M, U \to m_1, U_1 "+" m_2, U_2\]
   1. Massenerhaltung: $M = m_1 + m_2$ (nicht in Spezielle Relativitätstheorie)
   2. Energie: $U + \frac{M}{2} \bar{\v v}^2 = (U_1 + \frac{m_1}{2}\v v_1^2) + (U_2 + \frac{m_2}{2} \v v_2^2)$
   3. Impuls: $\v p = \v p_1 + \v p_2, (\v p = M\v v)$
   Ohne Beschränkung der Allgemeinheit ruhe $M$ vor dem Zerfall (Schwerpunktsystem) $\v p = 0, \v v = 0$ (immer durch Boost erreichbar) $\implies$
   \begin{align*}
   \v p_1 + \v p_2 &= 0, U - U_1 - U_2 \equiv (\Delta U) = \frac{\v p_1^2}{2 m_1} + \frac{\v p_2^2}{2 m_2} \\
   \abs{\Delta U} &= \frac{p_1^21}{2}(\frac{1}{m_1} + \frac{1}{m_2}) = \frac{p_1^2}{2} \frac{M}{m_1 m_2} \\
   \intertext{mit $\v p_1 = -\v p_2$:}
   \abs{\v p_1} = \abs{\v p_2} &= \sqrt{\frac{2(\Delta U)m_1 m_2}{M}}
   \intertext{Es gilt außerdem:}
   \frac{\abs{v_1}}{\abs{v_2}} &= \frac{m_2}{m_1}
   \end{align*}
   Diese Beschreibung durch Erhaltungsätze bleibt unvollständig! Richtungsinformation fehlt.
   (In QM-Beispielen wird die Richtungs-information oft im Spin/Drehimpuls von $M$ liegen)
** Schwerpunkts vs Laborsystem
   Interessanter Fall: $\theta \equiv \theta_s$ im Schwerpunktsystem sei bekannt. Frage: Wingel
   $\theta_L$ im Laborsystem?
   Wir wissen bereits
   \begin{align*}
   \abs{\v p_{1, s}} &= \sqrt{\frac{2\abs{\Delta U}m_1 m_2}{M}} \\
   \v p_{1,s} = \abs{\v p_{1,s}} \cvec{\cos \theta_s ; \sin \theta_s}, \v v_{1,s} = \frac{\v p_{1,s}}{m_1}
   \end{align*}
