* Wechsel der Koordinatensystms und Scheinkräfte
** Wechsel des Koordinatensystems im euklidischen Raum
   $V = \mathbb{R}^n, n = 3$ \\
   *Bisher:* \\
   Immer feste Basis
   \[\v x = \cvec{x^1 ; x^2 ; x^3} = x^1 \cvec{1 ; 0 ; 0} + x^2 \cvec{0 ; 1 ; 0} + x^3 \cvec{0 ; 0 ; 1} = x^i \v e^i\]
   $\{e^i\}$ - duch "$i$" nummerierte Basisvektoren. \\
   *Wichtig*:
   - In Physik gibt es keine ausgezeichnete Basis.
   - können Basis / Koordinatensystem wechseln

   \[\v e^{\prime k} = R^{ik} \v e^k\]
   (analog zu $\v x = x^i \v e^i$)
   *Wichig*: $\{\v e^{\prime i}\}$ wieder Basis $\iff R \in GL(n)$ \\
   *Hier*: euklidischer Raum: Orthonormalbasen: $\v e^i \v e^j = \delta^{ij}$ \\
   Wenn $\{\v e^{i}\}$ Orthonormalbasis, so wird $\{\v e^{\prime i}\}$ auch eine sein, falls $R\in O(n)$
   \[\v e^{\prime i} \v e^{\prime j} = (R^{ik} \v e^k)(R^{jl} \v e^l) = R^{ik} R^{jl} \delta^{kl} = \delta^{ij}\]
   Wir können festen Vektor $\v x$ bezüglich neuer Basis zerlegen:
   \begin{align*}
   \v x &= x^{\prime i} \v e^{\prime i} = x^{\prime i} R^{ij} \v e^{j} = x^j \v e^j \\
   &\implies x^j = x^{\prime i} R^{ij} \\
   &\xRightarrow{\cdot (R^T)^{jk}} x^j (R^T)^{jk} = x^{\prime i} R^{ij} (R^t)^{jk} \\
   x^{\prime k} &= R^{kj} x^j \tag{gleiche Formel, wei bei Drehung um $R$}
   \end{align*}
   Dies ist nicht unerwartet, da $\{\v e^{\prime i}\}$ aus $\{\v e^i\}$ durch Drehung $R^{-1}$ hervorgeht:
   \begin{align*}
   \intertext{*Dazu*: Die Vektoren $\{\v e^i\}$ haben bezüglich der Basis $\{\v e^i\}$ die Komponenten $\delta^{ij}$:}
   \v e^i &= \delta^{ij} \v e^j, (\v e^i)^j = \delta^{ij} \\
   \v e^{\prime i} &= R^{ij} \v e^j, (\v e^{\prime i})^j = R^{ij} \\
   \intertext{also gilt:}
   \hspace{0pt}(\v e^{\prime i})^j &= R^{ij} = (R^{-1})^{ji} = (R^{-1})^{jk} \delta^{ki} = (R^{-1})^{jk} (\v e^i)^k \\
   \hspace{0pt}(\v e^{\prime i})^j &= (R^{-1})^{jk} (\v e^i)^k \\
   \intertext{$\implies$ Behauptung ist gezeigt}
   \end{align*}
** Aktive und Passive Beschreibung von Symmetrien
   - Aktiv: Transformieren pyhsikalisches Objekt
   - Passiv: Wechsle Koordinatensystem
   #+ATTR_LATEX: :options []
   #+begin_ex latex
   \mbox{}
   - Aktiv: $x \to x' = Rx$. Symmetrieforderung: $\v x' \cdot \v y' = \v x \cdot \v y$, also: Skalarproduktinvariant
   - Passiv: $\v x$ fest. Komponenten
	 (Es gilt: $\v e^{\prime i} = R^{ij} \v e^j$)
	 - $x^i$ in Basis $\{\v e^i\}$
	 - $x^{\prime i} = R^{ij} x^j$ in Basis $\{\v e^{\prime i}\}$
	 Symmetrieforderung: Mathematischer Ausdruch für Skalarprodukt soll in neuen Komponenten die *gleiche Form haben*.
	 In der Tat:
	 - alt: $\v x \cdot \v y = x^i y^i$
	 - neu: $\v \cdot \v y = x^i y^i = (R^{-1})^{ij} x^{\prime j} (R^{-1})^{ik} y^{\prime k} = x^{\prime i} y^{\prime i} \checkmark$
   #+end_ex
   #+ATTR_LATEX: :options [Galilei-Transformation]
   #+begin_ex latex
   - Aktiv: $(t, x(t)) \to (t + s, R x(t) + y + (t + s) v)$. Symmetrieforderung: Neue
	 Trajektorie ist auch physikalische Bewegung.
   - Passiv: Sei $\v x_0 = \v a + \v b t$ der Vektor, der vom alten zum neuen Koordinatenursprung zeigt:
	 \[\v x_n = \v x - (\v a + \v b t)\]
	 Bezeichne Komponenten von $\v x_n$ bezüglich der neuen, gedrehten Basis mit $x^{\prime j}$
	 \[x'(t) = A^{-1}(x - a - bt) = Rx + y + v t\]
	 mit $R\equiv A^{-1}, y\equiv -A^{-1}a, v\equiv -A^{-1}b$ (könnte auch noch Uhren umstellen $\to s$)
	 - Transformation sieht formal so aus, wie im aktiven Fall \\
	   Symmetrieforderung: "Newton" soll gleiche Form haben: Prüfen dies:
	   \[\ddot{x}' = \underarrow[R]{"noch" zeitunabhängig}\ddot{x} = R \frac{F}{m} = \frac{F'}{m} \checkmark\]
   #+end_ex
** Beschleunigte, nichtrotierende Koordinatensysteme
   keine Symmetrietransformation! Nichinertialsysteme! \\
   $\v x_0(t)$ beschreibe Bewegung des "neuen" Ursprungs
   \begin{align*}
   \v x_I = \v x_0 + \v x \implies \ddot{\v x} = \ddot{\v x_I} - \ddot{\ v x}_0 \tag{\textbf{I}nertial} \\
   m \ddot{\v x} = m \ddot{\v x}_i - m\ddot{\v x}_0 = \v F + \underarrow[\v F_s]{Scheinkraft} \\
   F_s \equiv -m \ddot{\v x_0}
   \end{align*}
   $\implies$ Im Nichtinertialsystem bewegt sich ein Punkt so, als gäbe es eine zusätzliche Kraft: $m\ddot{\v x} = \v F + \v F_s$
** Kleine Drehungen
   #+ATTR_LATEX: :options [Spur]
   #+begin_defn latex
   \[M_{ii} = \Sp(M) = \sum_i a_i\]
   $\Sp(M)$ wird als Spur bezeichnet, und entspricht der Summe über die Diagnoalelemente
   #+end_defn
   rotierendes Bezugssystem (NIS) \\
   Drehungen: $R(t) \in SO(u), R^{T} R = \mathbb{1}$ für $t \sim \epsilon, R(0) = \mathbb{1}$
   \begin{align*}
   R(\epsilon) = \mathbb{1} + \eps M + O(\eps^2) \\
   R(\epsilon) R^{T}(\eps) &= (\mathbb{1} + \eps M)(\mathbb{1} + \eps M^T) \overset{!}{=} \\
   &= \mathbb{1} + \epsilon(\underbrace{M + M^T}_{0}) \overset{!}{=} \mathbb{1} \\
   \end{align*}
   $\implies M$ ist antisymmetrisch!, $M_{ij} = -M_{ji}$. Es gibt $N_A = \frac{n(n - 1)}{2}$ linear unabhängige Basismatrizen $T_a$.
   #+ATTR_LATEX: :options [$n = 3$]
   #+begin_ex latex
   Für $n = 3: N_A = 3$:
   \begin{align*}
   M &= \epsilon_a t_a
   t_1 &= \begin{pmatrix} 0 & 0 & 0 \\ 0 & 0 & 1 \\ 0 & -1 & 0\end{pmatrix}
   t_2 &= \begin{pmatrix} 0 & 0 & -1 \\ 0 & 0 & 0 \\ 1 & 0 & 0\end{pmatrix}
   t_3 &= \begin{pmatrix} 0 & 1 & 0 \\ -1 & 0 & 0 \\ 0 & 0 & 0\end{pmatrix}
   R(\v \epsilon)\hspace{0pt} &=\mathbb{1} + \v \eps \v T, \eps = \abs{\v \eps} \\
   \hspace{0pt}(T_i)_{j,k} &= \eps_{ijk} \\
   \v \epsilon &= \abs{\v \epsilon} \cvec{0; 0; 1} \\
   R(\v \epsilon)\hspace{0pt} &= \mathbb{1} + \abs{\epsilon} \begin{pmatrix} 0 & 1 & 0 \\ -1 & 0 & 0 \\ 0 & 0 & 0\end{pmatrix} + O(\abs{\v \epsilon}^2) = \begin{pmatrix} 1 & \abs{\v \epsilon} & 0 \\ -\abs{\v \epsilon} & 1 & 0 \\ 0 & 0 & 1\end{pmatrix} + O(\abs{\v\epsilon}^2) \\
   &= \begin{pmatrix} \cos{\abs{\v \epsilon}} & \sin{\abs{\v \epsilon}} & 0 \\ -\sin{\abs{\v \epsilon}} & \cos{\abs{\v \epsilon}} & 0 \\ 0 & 0 & 1 \end{pmatrix} + O(\abs{\v \epsilon}^2) \\
   \end{align*}
   #+end_ex
   Anwendung:
   \begin{align*}
   \v{\Delta\phi} &= -\v \epsilon \\
   R(\v{\Delta\phi}) &= \mathbb{1} - \v{\Delta\phi} \v T \\
   R(\v{\Delta\phi})_{ij} &= \delta_{ij} - \Delta\phi_k \eps_{ijk} \\
   R(\v{\Delta\phi})_{ij}v_j &= v_i + \Delta\phi_k \eps_{ikj} v_j \\
   R(\v{\Delta\phi})\v v &= \v v + \v{\Delta\phi} \times \v v \\
   \intertext{Trivia: Wenn jemand mit Deltas anfängt, dann hört er auch mit $\d$'s auf.}
   \v v(t) &= v  \\
   \v v(t + \Delta t) &= R(\v{\Delta\phi})\v v \\
   \lim_{\Delta t \to 0} \frac{\v v(t +\Delta t) - \v v(t)}{\Delta t} &= \frac{(R(\v{\Delta \phi}) - \mathbb{1})}{\Delta t}\v v = \underbrace{\frac{\v{\Delta\phi}}{\Delta t}}_{\v \omega} \times \v v = \v \omega \times \v v = \dd{\v v}{t} \\
   \v \omega &= \lim_{\Delta t \to 0} \frac{\v{\Delta \phi}}{\Delta t} = \dd{\v\phi}{t} = \dot{\v \phi} \\
   \end{align*}
** Rotierendes Koordinatensystem
   In diesem Abschnitt sei $r_x, \omega_x \in\mathbb{R}^3$ \\
   $r_I$: Geschwindigkeit im Intertialsystem
   \begin{align*}
   \intertext{Im Inertialsystem}
   r_I &= r_0(t) + r_N \\
   &= r_0(t) + R(t) r \\
   \intertext{Newton im Intertext}
   m\ddot{r_I} &= F_I \\
   \implies m\ddot{r_0} + (R\cdot r)^{..} &= F_I = R\cdot F \\
   \dot{R}(t)\cdot r &= \lim_{\Delta t \to 0} \frac{R(t + \Delta t) - R(t)}{\Delta t} r \\
   \intertext{wichtge Formel: $\dot{R}(t)\cdot r = R(\omega\times r)$, damit erhält man:}
   &= \frac{(R(\Delta t) - \mathbb{1})}{\Delta t} R(t) r = \underarrow[\omega_{IS}]{$R\omega$} \times R(t)\cdot r = (R\omega) \times (R r) = R(\omega\times r) \\
   \hspace{0pt}(R r)^{..} &= (\dot{R} r + R \dot{r})^{.} = (R(\omega \times r) + R\dot{r})^{.} = \dot{R}(\omega\times r) + R(\dot{\omega}\times r) + R(\omega\times\dot{r}) + \dot{R}\dot{r} + R \ddot{r} \\
   &= R(\omega\times(\omega \times r) + \dot{\omega} \times r + 2(\omega\times \dot{r}) + \ddot{r}) \\
   \implies m\ddot{r} &= F - m((R^{-1})\ddot{r}_0 + \underbrace{\omega\times(\omega\times r)}_{F_{Zentrifugal}} + \underbrace{2\omega\times\dot{r}}_{F_{Coriolis}} + \underbrace{\dot{\omega}\times r}_{E_{Tangential}})
   \end{align*}
   #+ATTR_LATEX: :options [Zentrifugalkraft]
   #+begin_remark latex
   \begin{align*}
   \intertext{$F_z$:}
   \hspace{0pt}(-\omega\times(\omega\times r))_k = -\eps_{ijk}\omega_i \eps_{lmj} \omega_l r_m \\
   &= -(\delta_{lk} \delta_{mi} - \delta_{mk} \delta_{li}) \omega_l r_m \omega_i \\
   &= -(\omega r) \omega_k + r_k(\omega^2) \\
   \intertext{für $\omega\perp r$:}
   \v F_z = m\omega^2 \v r
   \end{align*}
   #+end_remark
   #+ATTR_LATEX: :options [Corioliskraft]
   #+begin_remark latex
   \begin{align*}
   \intertext{$F_c$ zum Beispiel: $r\perp \omega$}
   \v F_c &= -2m \abs{\v\omega}\abs{\v v}\v e_3 \times \v e_1 = 2m\abs{\omega}\abs{\omega v} \v e_2
   \end{align*}
   #+end_remark
** Trägheitstensor
   Massenpunkte bei $\v r_a$
   \begin{align*}
   \lim_{\Delta t\to 0} \frac{\Delta \v r_a}{\Delta t} = \frac{\v{\Delta \phi}}{\Delta t} \times \v r_a = \dd{\v r_a}{t} = \v \omega \times \v r_A \\
   E_{kin} = \sum_a \frac{m a}{2}(\dot{\v r}_a^2) = \sum_a \frac{m_a}{2}(\v \omega \times \v r_a)^2 \\
   &= \sum_a \frac{m_a}{2}\eps_{ijk} \eps_{lmk} \omega_i (r_a)_j \omega_l (r_a)_m \\
   &= \sum_a \frac{m_a}{2}(\delta_{jm}\delta_{ij} - \delta_{jl}\delta_{im})\omega_i \omega_l (r_a)_j(r_a)_m \\
   &= \sum_a \frac{1}{2}\underbrace{m_a(\Delta_{ij}r_a^2 - (r_a)_i (r_a)_j)\omega_i \omega_j}_{I_{ij}} = \frac{1}{2}I_{ij}\omega_i \omega_j \\
   &= \frac{1}{2}\omega^T I \omega \\
   I &= \int \d^3 r \underarrow[\rho]{Massendichte}(r)(\mathbb{1} \v r^2 - \v r \otimes \v r^T) \\
   I_{ij} = \int \d^3 r \rho(r) (\v r^2 \delta_{ij} - r_i r_j)
   \end{align*}
   \begin{align*}
   \eps^{ijk} \eps^{lmn} = N(\delta^{il} \delta^{jm} \delta^kn + \ldots) \\
   \delta^{ij} = i
   \end{align*}
