#+AUTHOR: Robin Heinemann
#+TITLE: Theoretische Physik (Hebecker)

# Einleitung: \\
# - Website: www.thphys.uni-heidelberg.de/hebecker/TP1/tp1.html
# - Bartelman Skripte

#+INCLUDE: "../header.org" :minlevel 1

#+INCLUDE: "overview.org" :minlevel 1
#+INCLUDE: "mass_points.org" :minlevel 1
#+INCLUDE: "newton_mechanics.org" :minlevel 1
#+INCLUDE: "conservation_laws.org" :minlevel 1
#+INCLUDE: "harmonic_oscillator.org" :minlevel 1
#+INCLUDE: "symmetries.org" :minlevel 1
#+INCLUDE: "pseudo_forces.org" :minlevel 1
#+INCLUDE: "central_forces.org" :minlevel 1
#+INCLUDE: "collision.org" :minlevel 1
* Gravitation ausgedehnter Körper
  Punktmassennäherung oft schlecht, Aber: leicht korrigierbar wegen Additivität der Kräfte (Genauer: Newtonsche Gravitation ist linearisierte Näherung der ART).
** Potential einer Massenverteilung
   potentielle Energie für Gravitation zwischen $m_0$ und $m_1$
   \[V(\abs{\v r_0 - \v r_1}) = - \frac{m_0 m_1 G}{\abs{\v r_0 - \v r_1}}, \v F_{01} = -\v \nabla_0 V(\abs{\v r_0 - \v r_1}) \equiv -(\frac{\partial}{\partial(r_0)^1}, \frac{\partial}{\partial(r_0)^2}, \frac{\partial}{\partial(r_0)^3})^T V(\abs{\v r_0 - \v r_1})\]
   Wir wollen hier nur sehr kleine "Testmassen" $m_0$ betrachten $\implies$ Bewegung von $m_0$ im unveränderlichen Fled von $m_1, m_2, m_3, \ldots \implies$ Schreibe
   \[V(\v r_0) = -\frac{m_0 m_1 G}{\abs{\v r_0 - \v r_1}}, \v F = -\v \nabla_{(0)}V(\v r_0)\]
   Nützlich, ein von $m_0$ unabhäniiges Gravitationspotential $\phi$ zu definieren: $\phi \equiv \frac{V}{m_0} \implies$
   \[\phi(\v r_0) = -\frac{m_1 G}{\abs{\v r_0 - \v r_1}}, \v F = -m_0 \v \nabla_0\phi(\v r_0)\]
   ($m_0$ verschwindet völlig in Bewegungsgleichung der Testmasse: $\ddot{\v r_0} = - \v \nabla_0 \phi(\v r_0)$) \\
   Ziel: Gravitationspotential einer Ansammlung von Punktmassen:
   \[\phi(\v r_0) = \sum_{a = 1}^{N} \frac{m_a G}{\abs{\v r_0 - \v r_a}}\]
   Limes sehr vieler, sehr kleiner Elemente: Volumenintegral:
   \[\phi(\v r_0) = -G \int \frac{\d^3 t \rho(\v r)}{\abs{\v r_0 - \v r}}\]
   Idee: diskrete Summe von $\v r_a \to$ kontinuierliche Integral Variable $\v r$. Erinnerung an Flächenintegral:
   \[\int_A \d^2 \v x f(\v x) \equiv \int_{x_{min}^1}^{x_{max}^1} \d x^1\int_{x_{min}^2}^{x_{max}^2} \d x^2 f(x^1, x^2)\]
   Volumenintegral:
   \[\int_V \d^3 \v x f(\v x) = \int_{x^2_{min}}^{x^2_{max}}\d x^2 \int_A \d^2 \v y f(x^1, x^2, x^3), \v y = (x^1, x^3)^T\]
   Anstatt das Volumen stupide zu zerlegen ist es oft sinnvoller, Symmetrien auszunutzen ($\implies$ Kugel, etc),
   Bei Rotationssymmetrie:
   \[\int_{\text{Kreisfläche}} \d^2 \v x f(\v x) = \int_{0}^{R}\d r \underbrace{\int_{0}^{2\pi} r\d \phi f(r, \phi)}_{\text{Kreis mit Radius $r$}} = \int_{0}^{R}r\d r \int_{0}^{2\pi}\d \phi f(r, \phi)\]
   In 3D: (Volumenintegral)
   \[\int_{\text{Kugel}} \d^3 \v x f(\v x) = \int_{0}^{R}\d r r^2 \underbrace{\int_{0}^{\pi} \sin{\theta} \d \theta \int_{0}^{2\pi} \d \phi f(r, \theta, \phi)}_{\text{Sphäre mit Radius $r$}}\]
** Gravitationspotential einer Kugelschale
   Kugelschale sei dünn $\implies$ Flächendichte $\rho_F, [\rho_F] = \si{\kilo\gram\per\meter\squared}$
   Brauche eigentlich nur Flächenintegral:
   \[\int \d^3 \v r\rho (\v r)\ldots = \int \d^2 \v r \rho_F(\v r)\]
   Genauer: Koordinaten $r, \theta, \phi$, Kugelschale: $r\in (R, R + \Delta R)$
   \[\int_{R}^{R + \Delta R} r^2 \d r \int_{0}^{\pi} \sin{\theta} \d\theta \int_{0}^{2\pi}d\phi \rho(\v r) \ldots \cong R^2 \int_{0}^{\pi}\sin{\theta} \d \theta \int_{0}^{2\pi} \d\phi \rho_F(\theta,\phi) \ldots\]
   \[A \rho_F = \Delta R \rho A = M\]
   Kommentar:
   \[\underbrace{\int_{0}^{\pi}\sin{\theta} \d\theta \int_{0}^{2pi}\d \phi}_{\mathclap{\text{Integrieren über Raumwinkel}}} \ldots = \int \d \Omega\]
   Noch direkter zum konkretem Problem:
   \begin{align*}
   \d \phi &= - G \frac{\d M}{r} = -G \frac{\rho_F \d A}{r} = - \frac{G \rho_F}{r}\underbrace{(R\d\theta)}_{\text{Breite}}\underbrace{(2\pi R\sin(\theta))}_{\text{Länge}} \\
   r &= \sqrt{(a - R\cos{\theta})^2 + (R\sin{\theta})^2} = \sqrt{\underbrace{a^2 + R^2}_{A} - \underbrace{2aR}_{B}\cos{\theta}} \\
   \phi &= -G \rho_F 2\pi R^2 \int \frac{\sin\theta \d \theta}{\sqrt{A - B\cos{\theta}}} \\
   \intertext{Substituiere: $x = \cos\theta, \d x = -\sin \theta \d \theta, \theta = 0 \implies x = 1, \theta = \pi \implies x = 1$}
   \phi &=  -G \rho_F 2\pi R^2 \int_{1}^{-1} \frac{-\d x}{\sqrt{A - Bx}} \\
   \phi &= -G\rho_F2\pi R^2 \frac{2}{2aR}(\sqrt{a^2 + R^2 + 2aR} - \sqrt{a^2 + R^2 - 2aR}) \\
   \phi &= -G\rho_F2\pi R^2 \frac{1}{aT}((a + R) - (a - R)) = -G\rho_f \frac{4\pi R^2}{a} \\
   \phi &= -\frac{GM}{a}
   \end{align*}
   $\implies$ Potential so, als sei die Masse im Zentrum konzentriert. Analoge Rechnung zeigt: Keine Gravitationskraft (also Potential konstant) im Inneren.
   Pol. jedes sphärisch symmetrischen Körpers (auch inhomogen) ist so wie bei enbph Punktmasse im Zentrum
** Gaußscher Satz und Gravitation
   $O$: Oberfläche deines Volumen
   \[M = -\frac{1}{4\pi G} \int_{O} \frac{1}{m} \underarrow[\v F]{Kraft durch $M$ auf Probemasse} \d \v f\]
   "Integrale Formulierung des Newtonsches Gravitationsgesetzes"
** Divergenz und Gaußscher Satz
   Betrachte Integrale vom Typ
   \begin{align*}
   I &= \int_{\underarrow[O]{Oberfläche eines Volumens}}\overarrow[\d \v f]{Flächenelement} \v F \\
   \intertext{$\v F$: Vektorfeld. Betrache Würfel:}
   I &= I_{12} + I_{23} + \underarrow[I_{31}]{Betrag der zwei Flächen in der $x^3-x^1$ Ebene} \\
   I_{12} &= \int_{12,\text{oben}} \d x^1 \d x^2 F^3(x^1, x^2, \Delta x^3) + \int_{12,\text{unten}} \d x^1 \d x^2 (-F^3(x^1, x^2, 0)) \\
   \intertext{$\implies$ *ein* Interal, Integrand:}
   \underbrace{F^3(x^1, x^2, \Delta x^3 - F^3(x^1, x^2, 0))}_{\text{Taylor um $x^3 \equiv 0$}} \\
   I_{12} &= \int_{12}\d x^1 \d x^2 \Delta x^3 \frac{\partial F^3}{\partial x^3}(x^1, x^2, 0) \\
   I_{12} &= \Delta x^1 \Delta x^2, \Delta x^3 (\frac{\partial F^3}{\partial x^3})(0,0,0) + O(\Delta^4) \\
   \intertext{Zusammen mit analoger Rechnung für $I_{23}, I_{31}$:}
   I &= \underarrow[V]{$\Delta x^1 Delta x^2 \Delta x^3$} (\frac{\partial F^1}{\partial x^1} + \frac{\partial F^2}{\partial x^2} + \frac{\partial F^2}{\partial x^2}) = V(\partial^i F^i) = V(\v \nabla \v F) = V(\div \v F) \\
   \end{align*}
