* D'Alembertsches Prinzip und Lagrange Gleichungen 1. und 2. Art
  Unter anderem "Herleitung" (historisch) der Euler-Lagrange-Gleichungen, immer noch Anwendungsrelevant: Lagrange-Gleichungen 1. Art / nichtholonome Zwänge
** Arten von Zwangsbedingungen
   1. Gasmoleküle in einem Kasten
   2.
	  1. Perle auf Draht, Draht unbewegt
	  2. Perle auf Draht, Draht bewegt
   3. Senkrecht stehendes Rad, ohne Rutschen
   4. Durch massenlose Stangen verbundene Punktmassen
   Zwänge heißen *holonom* falls sie durch nicht-differentielle Gleichungen ausdrückbar sind, zum Beispiel
   \[ϕ_α(\v x_1, \dots, \v x_N, t) = 0, α ∈ \{0, \dots, d\}\]
   Genauer: \\
   $t$ kommt vor: "rheonom" \\
   $t$ kommt nicht vor: "skleronom" \\
   Besonders interessant: Zwänge in differentieller, nicht-integriebarer Form (*nicht-holonom*). (Fall 3).
   Im Moment nicht klassifiziert 1. Also betrachte Fall 3.:
   4 Parameter: $(\v x, θ, φ), \v x ∈ ℝ^2$. Zwänge: $\d x^1 = R\d φ \cos θ, \d x^2 = R \d φ \sin θ$. Hoffnung: (wenigstens eine) dieser Bedingungen *ausdrückbar* als
   \[ϕ(x^1, x^2, φ, θ) = 0\]
   Das heißt Differenzieren dieser Gleichung gibt eine der obigen Zwänge:
   \[0 = \d ϕ = \pp{ϕ}{x^1} \d x^1 + \pp{ϕ}{x^2} \d x^2 + \pp{ϕ}{φ} \d φ + \pp{ϕ}{θ} \d θ\]
   Falls dies für beide differentiellen Zwänge ginge, wäre unser System doch *holonom*. (beziehungsweise "integrierbar").
   Aber im konkreten Fall geht das *nicht*.
   #+begin_proof latex
   per Widerspruch: Wenn es ginge, könnten wir nach $φ$ auflösen $⇒ φ = /(x^1, x^2, θ)$. Dies ist unmöglich,
   weil man durch "Rollen im Kreis" beliebiges $φ$ zu vorgegebenen $x^1, x^2, θ$ erreichen kann.
   #+end_proof
** Prinzip der virtuellen Arbeit und "D'Alembert"
   Betrachte eine masselose starre Stange, die zwei Massen $m_1, m_2$ verbindet. Auf $m_1, m_2$ wirken die Zwangskräfte $\v F_{12}^c, \v F_{21}^c$ "constraint".
   Wir wissen schon: Energie erhalten $⇒$ Zwangskräfte verrichten keine Arbeit. $⇒ δA = \v F_{12}^c \d \v x_1 + \v F_{21}^] \d \v x_2 = 0$.
   Ebenso für Perle auf Draht (Draht fest): $\v F_c \perp \text{Draht} \parallel \d \v x$
   \[⇒ δA = \v F^c \d \v x = 0\]
   Wir wollen die Aussage "Zwangskräfte verrichten keine Arbeit" allgemein formulieren. \\
   Problem: bei einem bewegtem Draht gilt die Aussage $\d \v x \parallel$ Draht nicht
   und damit gilt dann auch $⇒ δA = 0$ im Allgemeinen nicht mehr. \\
   Lösung: Definiere *virtuelle Verrückung* $δx$ bei $t = \const$. Dies ist eine *gedachte* Verschiebung des Systems in eine andere Lage - keine echte Bewegung.
   Fakt: in einfachen Beispielen (bewegter Draht, etc.) gilt jetzt wieder $δA = 0$.	$⇒$ Formulieren: "*Prinzip der virtuellen Arbeit*"
   \[\sum_{a} \v F_a^c δ\v x_a = 0\]
   für jede virtuelle Verrückung $\{δ\v x_a, a = 1, \dots, N\}$
   $⇒$ Definition eines "glatt geführten Systems".
   Für jede der Punktmassen gilt: $\v F_a^{tot} = \v F_A + \v F_a^c$
   \begin{align*}
   ⇒ \sum_{a}(\v F_a - \v F_a^{tot}) δ\v x_a = 0 \\
   ⇒ \sum_{a}(\v F_a - m_a \ddot{\v x}_a) δ\v x_a = 0 \tag{d'Alembertsches Prinzip}
   \end{align*}
   Das D'Alembertsche Prinzip ist äquivalent zum Prinzip der virtuellen Arbeit. Vorteil: ohne Zwangkräft.
   Nützliches Korollar: Im Gleichgewicht gilt:
   \[\sum_{a} \v F_a δ\v x_a = 0\]
   Elementare Anwendung: Wippe: $m_1, m_2$ im Abstand $l_1, l_2$ von dem Auflagepunkt.
   Offensichtlich gilt:
   \[δ x_2 = - \frac{l_2}{l_1} δx_1\]
   (für jede virtuelle Verrückung $\{δx_1, δx_2\}$). Wir setzen in d'Alembert (im Gleichgewicht) ein: $F_1 δx_i + F_2δx_2 = 0$
   \[⇒ F_1 δx_i + F_2 (-\frac{l_2}{l_1})δx_1 = 0 ⇒ \frac{F_1}{F_2} = \frac{l_2}{l_1}\]
   (Hebelgesetz).
** D'Alembertsches Prinzip mit verallgemeinerten Koordinaten und Kräften.
   Betrachte $N$ Massenpunkte, $d$ holonome Zwänge.
   \[ϕ_α(\v x_1, \dots, \v x_N, t) = 0, α = 1, \dots, d\]
   mit verallgemeinerten Koordinaten $q_m$, sodass
   \[\v x_a = \v x_a(q_1, \dots, q_{3N - d},t)\]
   Laut D'Alembert:
   \[\sum_{a}(\v F_a - m_a \ddot{\v x}_a) δ\v x_a = 0\]
   für alle virtuellen Verrückungen $δ\v x_a$. In verallgemeinerten Koordinaten kann man schreiben
   \[δ\v x_a = \sum_{m} \pp{\v x_a}{q_m} δq_m\]
   Für den ersten Term findet man
   \[\sum_{a} \v F_a δ\v x_a = \sum_{m} Q_m δq_m\]
   mit den verallgemeinerten Kräften.
   \[Q_m := \sum_{a} \v F_a \pp{\v x_a}{q_m}\]
   Für den zweiten Term erhält man:
   \[\ddot{\v x}_a δ\v x_a = \sum_{m} \ddot{\v x}_a \pp{\v x_a}{q_m} δq_m = \sum_{m} (\dd{}{t}(\dot{\v x}_a \pp{\v x_a}{q_m}) - \dot{\v x}_a \dd{}{t}(\pp{\v x_a}{q_m}))δq_m\]
   Nebenrechnung: Gegeben $x = x(q, t)$. Totale Zeitableitung:
   \[\dot x = \pp{x}{q} \dot q + \pp{x}{t} := \dot x(q, \dot q, t)\]
   Offensichtlich gilt:
   \[\pp{\dot x}{\dot q} = \pp{x}{q}\]
   Wir berechnen:
   \begin{align*}
   \dd{}{t}(\pp{x}{q}) &= \frac{\partial^2 x}{\partial q^2} \dot q + \frac{\partial^2 x}{\partial q \partial t} \tag{A} \\
   \pp{\dot x}{q} &= \frac{\partial^2 x}{\partial q^2} \dot q + \frac{\partial^2 x}{\partial q \partial t} \tag{B} \\
   ⇒ \dd{}{t}(\pp{x}{q})&= \pp{\dot x}{q}
   \end{align*}
   Weiterführung vom zweitem Term:
   \begin{align*}
   \ddot{\v x}_a δ\v x_a &= \sum_{m} (\dd{}{t}(\dot{\v x}_a \pp{\dot{\v x}_a}{\dot q_m}) - \dot{\v x}_a \pp{\dot{\v x}_a}{q_m})δq_m \\
   ⇒ \sum_{a} m_a \ddot{\v x}_a δ\v x_a &= \sum_{m,a} m_a (\dd{}{t}(\dot{\v x}_a \pp{\dot{\v x}_a}{\dot q_m}) - \dot{\v x}_a \pp{\dot{\v x}_a}{q_m})δq_m \\
   &= \sum_{m,a} m_a (\dd{}{t}\pp{}{\dot q_m}(\frac{1}{2} \dot{\v x}_a^2) - \pp{}{q_m}(\frac{1}{2}\dot{\v x}_a^2))δq_m \\
   &= \sum_{m} (\dd{}{t}\pp{}{\dot q_m} - \pp{}{q_m})T δq_m, \quad T = \sum_{a} \frac{1}{2}m_a \dot{\v x}_a^2 \\
   \intertext{Zusammen mit 1. Term folgt:}
   0 &= \sum_{m}(Q_m - (\dd{}{t}\pp{}{\dot q_m} - \pp{}{q_m})T)δ q_m \\
   \end{align*}
   $δ q_m$ unabhängig! $⇒$ jeder der Klammer-Ausdrücke verschwindet getrennt.
   $⇒ 3d -d$ Differentialgleichungen 2. Ordnung $⇒$ Problem prinzipiell gelöst.
** Lagrange-Gleichungen 1. Art
   Jetzt *zusätzlich* $p$ nichtholomome (differentielle) Zwänge.
   \[α = 1, \dots, p: \sum_{m} f_m^α dq_m + f_t^α \d t = 0\]
   $f_m^α$ sind Funktionen der $q_m, t$. Wir wollen mit Vektoren in $ℝ^{3N - d}$ arbeiten:
   \[δ\v q := \{δ_m\}, \v f^α := \{f_m^α\}, \v p := \{Q_M - (\dd{}{t}\pp{}{\dot q_m} - \pp{}{q_m})T\}\]
   Bedingung für virtuelle Verrückung:
   \[\sum_{m} f_m^α δq_m = 0 ⇔ \v f^α δ\v q = 0\]
   Sei $\Span\{\v f^α\}$ der von dem $\v f^α$ aufgespannte lineare Unterraum von $ℝ^{3N - d}$.
   Sei $\Span\{\v f^α\}_{\perp}$ das orthogonale Komplement. $⇒$ Zwänge $δ\v q ∈ \Span \{\v f^α\}_{\perp}$.
   D'Alembert besagt nun: $\v p δ\v q = 0$. Äquivalent: $\v p ∈ \{δ\v q\}_{\perp}$
   \[⇒ \v p \{\Span\{\v f_α\}_{\perp}\}_{\perp} = \Span\{\v f_α\}\]
   $⇒ ∃ λ^α(t)$, sodass
   \begin{align*}
   Q_m - (\dd{}{t}\pp{}{\dot q_m} - \pp{}{q_m})T + \sum_{α} λ^α f_m^α &= 0 \\
   \sum_{m} f_m^α \dot q_m + f^α_t &= 0
   \end{align*}
   Sie haben: $(3N - d) + p$ Differentialgleichungen für die $(3N - d) + p$ Funktionen $q_m$ und $λ^α$
   $⇒$ Problem prinzipiell gelöst.
** Lagrange-Multiplikatoren und Zwangskräfte
   Aus unserer Herleitung von D'Alembert folgt als technisches Zwischenergebnis:
   \[(\dd{}{t} \pp{}{\dot q_m} - \pp{}{q_m}) T = \sum_{a} m_a \ddot{\v x}_a \pp{\v x_a}{q_m}\]
   Ersetze: $m_a \ddot{\v x}_a = \v F_a^{tot} = \v F_a + \v F_a^c$. Definiere
   \[Q_m := \sum_{a} \v F_a \pp{\v x_a}{q_m}, Q_m^c := \sum_{a} \v F_a^c \pp{\v x_a}{q_m}\]
   Schreibe rechte Seite von der Gleichung in $Q$ 's um. Setze in "Lagrange-1" ein. Finde:
   \[Q_m^C= \sum_{α} λ^α f_m^α\]
   $⇒$ Lagrange-Multiplikatoren bestimmen Zwangskräfte. \\
   *Schlusskommentar*: Einfacherer Spezialfall: keine holonomen Zwänge. $⇒$ Lagrange-1 direkt in kartesischen Koordinaten formulierbar.
   \begin{align*}
   F_m - m_m \ddot x_m + \sum_{α} λ^α f^α_m &= 0 \\
   \sum_{m = 1}^{3N} f_m^α \dot x_m + f_t^α &= 0
   \end{align*}
   $m = 1, \dots, 3N, m_1 = m_2 = m_3, etc$
** Lagrange-Gleichungen 2. Art
   Betrachte System wie in 5.4 mit verallgemeinerten Koordinaten $q_m$ und *ohne* nichtholonome Zwänge. Seien die äußeren Kräfte konservativ: $\v F_a = - \v ∇_a V(\v x_1, \dots, \v x_N)$
   $\v ∇_a$: Gradient bezüglich $\v x_a$
   \begin{align*}
   ⇒ Q_m &= \sum_{a} \v F_a \pp{\v x_a}{q_m} = -\sum_{a} (\v ∇_a V)\pp{\v x_a}{q_m} = -\pp{V}{q_m} \\
   &= (\dd{}{t} \pp{}{\dot q_m} - \pp{}{q_m})V \\
   \intertext{D'Alembert sagt:}
   Q_m - (\dd{}{t} \pp{}{\dot q_m} - \pp{q_m}{})T &= 0 \\
   ⇒ (\dd{}{t}\pp{}{\dot q_m} - \pp{}{q_m})V - (\dd{}{t}\pp{}{\dot q_m} - \pp{}{q_m})T &= 0 \\
   \string(\dd{}{t}\pp{}{\dot q_m} - \pp{}{q_m}\string)(V - T) &= 0 \\
   \string(\dd{}{t}\pp{}{\dot q_m} - \pp{}{q_m}\string)(L) &= 0 \\
   \end{align*}
   $⇒$ "Herleitung" von "Lagrange-2" aus Newton, "glatt geführte Systeme", konservative Kräfte.
** Lagrange-Multiplikatoren - allgemeine Sicht
   Höhenfunktion $f(x, y)$ im Gebirge. Gipfel:
   \begin{align*}
   \pp{f}{x} &= 0 \\
   \pp{f}{y} &= 0 \\
   \end{align*}
   Andere Frage: Höchster Punkt auf einem Weg. Weg: gegeben durch $g(x, y) = 0$. Können (im Allgemeinen) nicht Gipfel und Weg Bedingung gleichzeitig lösen!
   Allgemeine Methode:
   \begin{align*}
   \pp{}{x}(f + λ g) &= 0 \\
   \pp{}{y}(f + λ g) &= 0 \\
   g(x, y) &= 0 (⇔ \pp{}{λ}(f + λg) = 0)
   \end{align*}
   $⇒ \{x_0, y_0, λ_0\}$. Diese Lösung liefert die Funktion $(f + λ_0 g)$, deren auf dem Weg Extremum liegt. Auf dem Weg ist aber $g = 0$. Damit liegt aber auch das Extremum von $f$ (auf dem Weg) bei $x_0, y_0$.
   Zunächst zu Lagrange 1: Betrachte *eine* nichtholonome Zwangsbedingung: $\v f \d \v q = 0$. ($f_t = 0$). Naiv:
   \[\v p \equiv \{Q_m - (\dd{}{t} \pp{}{\dot q_m} - \pp{}{q_m}) T\} = 0\]
   zusammen mit $\v f · \dot{\v q} = 0$. Das ist aber unmöglich, weil zu viele Differentialgleichungen. In der Tat wir wollen nur $\v p δ \v y = 0$.
   Lösung: Fordere $\v p + λ \v fs = 0$ und $\v f \dot{\v q} = 0$. \\
   Noch allgemeiner Anwendung der Lagrange-Multiplikatoren: Seien $F[f], G[f]$ Funktionale. Wir wollen $F$ extremalisieren mit der Nebenbedingung $G = 0$.
   Lösung: Extremalisieren $F[f] + λG[f]$ bezüglich $f$ und $λ$. Konkrete Anwendung: Sei $L$ Lagrange Funktion und $f = 0$ sei zusätzlich holomoner Zwang.
   $⇒$ Wir müssen jetzt nur	Extremalisierungs (Variationsproblem)
   \[δ ∫\d t [L(\v x, \dot{\v x}, t) + λ(t) f(\v x)] = 0\]
   bezüglich $\v x(t), λ(t)$ lösen.
