* Trägheitstensor
** Trägheitsmoment und Satz von Steiner
   Rotation von Körper um feste Achse $A$. Körper besteht aus Elementen $m_a$ mit Radius $r_{a, \perp}$.
   Kontinuierlich: $m_a = \rho ΔV$. Einzige erlaubte Bewegung sei Drehung um Achse $A$:
   \begin{align*}
   T &\simeq \sum_{a} \frac{m_a}{2}v_a^2 = \sum_{a} \frac{m_a}{2} ω_2 r_{a,\perp}^2 \\
   &= \frac{1}{2} I_A ω^2 \\
   ⇒ I_A &\equiv \sum_{a} m_a r_{a, \perp}^2 \\
   \intertext{Trägheitsmoment im Kontinuum:}
   I_A = ∫ \d^2 \v r ρ(\v r) r_{\perp}^2
   \end{align*}
   Einziger Freiheitsgrad: Drehwinkel $φ$ (wobei $ω = \dot φ$)
   \begin{align*}
   L(φ, \dots φ) &= \frac{1}{2} I_A \dot φ^2 - V(φ) \\
   ⇒ I_A \ddot{φ} &= -\pp{V}{φ}
   \end{align*}
   Annahme: $V$ ergibt sich als Summe der Potentiale aller Teilmassen:
   \[V(φ) = \sum_{a} V_a(\v r_a(φ))\]
   Betrachte
   \begin{align*}
   V(φ + δφ) &= \sum_{a} V_a(\v r_a(φ) + δ\v v_a) \\
   &= \sum_{a} V_a(\v r_a(φ) + δ\v φ × \v r_a(φ)) \\
   &= \sum_{a} V_a + \sum_{a}(δ\v φ × \v r_a) · \v ∇ V_a(\v r_a(φ)) \\
   V(φ + δφ) - V(φ) &= \sum_{a}(δ\v φ × \v r_a) \v ∇ V_a(\v r_a(φ)) \\
   \intertext{Limes $δφ \to 0, δ\v φ = \v e_A δφ, \v e_A$ Einheitsvektor der Achse}
   -\dd{V(φ)}{φ} &= -\sum_{a} \frac{δ\v φ × \v r_a}{δφ} \v ∇V \\
   &= \sum_{a} ε_{ijk}(\v e_A)_j (\v r_a)_k · (F_a)_i \\
   &= \sum_{a} (\v e_A)_j (\v r_a × \v F_a)_j = \sum_{a} \v e_A · \v M_a
   \end{align*}
   $\v M_a$: Drehmoment auf Punkt "$a$". \\
   Zuletzt: $I_A \ddot φ = -\dd{V}{φ}$
   \[⇒ \dd{}{t}(I_A \dot φ) = \v e_A \v M\]
   $\v M$: Gesamtdrehmoment. \\
   Erinnerung: Drehimpuls für Punktmasse: $\v L = m\v r × \v v$
   \[⇒ \v e_A · \v L = m \v e_A [(\v r_{\parallel} + \v r_{\perp}) × \v r]\]
   \[\abs{\v r_{\perp} × \v v} = \abs{\v r_{\perp}} \abs{\v v} = \abs{\v r_{\perp}} \abs{\v r_{\perp}} \dot φ\]
   \[⇒ \v e_A \v L = m r_{\perp}^2 \dot φ ⇒ \v e_A \v L = I_A \dot φ\]
   \[⇒ \v e_A · \dot{\v L} = \v e_A \v M\]
   Bemerkung: $I_A$ ist besonders einfach zu berechnen falls $A \parallel S$ (Schwerpunktsachse) und $I_S$ bekannt, $\v R_{\perp}$ ist der (senkrechte) Abstand der beiden Achsen.
   \begin{align*}
   I_A &= \sum_{a} m_a v_{0,\perp}^2 = \sum_{a} m_a (\v R_{\perp} + \v r_{\perp, a}')^2 \\
   \intertext{Summe der Mischterme fällt weg}
   I_A &= \sum_{a} m_a (\v R_{\perp}^2 + \v r_{a, \perp}^{\prime 2}) \\
   \intertext{Satz von Steiner:}
   ⇒ I_A &= M \v R_{\perp}^2 + I_s
   \end{align*}
** Trägheitstensor
   Berechne kinetische Energie einen Körpers der sich mit $\v v$ und mit $\v ω$ um Achse durch Schwerpunkt dreht.
   \begin{align*}
   T &= \sum_{a} \frac{m_a}{2} \v v_a^2 = \sum_{a} \frac{m_a}{2}(\v v + \v ω × \v r_a)^2 \\
   &= \sum_{a} \frac{m_a}{2}(\v v^2 + 2\v v(\v ω × \v r_a) + (\v ω × \v r_a)^2) \\
   \intertext{"Mischterm" fällt weg, da $\sum_a m_a \v r_a = 0$, wegen Schwerpunktbedingung}
   &= \frac{M}{2}\v v^2 + \sum_{a} \frac{m_a}{2}(\v ω + \v r_a)^2 \\
   &= \frac{M}{2}\v v^2 + \frac{1}{2} I_{ij} ω_i ω_j \\
   I_{ij} &\equiv \sum_{a} m_a (δ_{ij} \v r_a^2 - (\v r_a)_j (\v r_a)_j) \\
   \intertext{Integralform:}
   I_{ij} = ∫ \d^3 \v r ρ(\v r)(δ_{ij} \v r^2 - r_i r_j)
   \end{align*}
   Speziell für $\v r = (x, y, z)$ findet man:
   \[I = ∫\d x \d y \d z ρ(\v r) \begin{pmatrix}y^2 + z^2 &  -xy & -xz \\ -xy & x^2 + z^2 & -yz \\  -xz & -yz & x^2 + y^2\end{pmatrix}\]
   #+ATTR_LATEX: :options [homogener Würfel]
   #+begin_ex latex
   $∫\d x \to ∫_{-a/2}^{a/2}\d x$
   \[∫_{-a/2}^{a/2} \d x ∫_{-a/2}^{a/2} \d y y^2 ∫_{-a/2}^{a/2} \d z = a · \frac{a^3}{12} · a\]
   Insgesamt:
   \[I = a^2 ρ \begin{pmatrix}\frac{1}{6}a^3 &  &  \\  & \frac{1}{6} a^3 &  \\  &  & \frac{1}{6} a^3\end{pmatrix} = \frac{1}{6} M a^2 \mathbb{1}\]
   #+end_ex
** Hauptträgheitsachsen
   Tensor ist (wie) Vektor ein geometrisches Objekt. Er beschreibt Dichte/ Form des Körpers.
   Bei Drehungen des Körpers: Dreht sich mit: $I_{ij}' = R_{ik} R_{jl} I_{kl} ⇔ I' = R I R^T = R I R^{-1}$ (aktive Sicht). \\
   Passive Sicht: Für die Komponenten von $I$ im gedrehten Koordinatensystem gilt:
   \[I_{ij}' = R_{ik}R_{jl}I_{kl}\]
   Zentraler Satz: Jede symmetrische, reelle Matrix kann durch eine orthogonale Transformation auf Diagonalform gebracht werden.
   $⇒$ Wir können als stets den Körper so drehen beziehungsweise das Koordinatensystem so wählen, dass
   \[I = \begin{pmatrix}I_1 & 0 & 0 \\ 0 & I_2 & 0 \\ 0 & 0 & I_3\end{pmatrix}\]
   $I_1, I_2, I_3$ heißen Hauptträgheitsmonente. Die Koordinaten $\hat e_1, \hat e_2, \hat e_3$ des Systems in dem $I$ diagonal ist heißen
   Hauptträgheitsachsen. (im Allgemeinen sind dies die Symmetrieachsen des Körpers, soweit vorhanden). \\
   Sei $\v v = 0$, sei $\v ω = ω \hat e$ ($\hat e$ beliebiger Einheitsvektor).
   \[⇒ T = \frac{1}{2}I_{ij}ω_i ω_j = \frac{1}{2} I_{ij} \hat e_i \hat e_j ω^2 \equiv \frac{1}{2} I_e ω^2\]
   (Daher ist $I_e \equiv I_{ij} \hat e_i \hat e_j$) das Trägheitsmoment bezüglich $\hat e$. \\
   Sei speziell $I$ diagonal und $\hat e = \hat e_1 = (1, 0, 0)$. Es folgt $I_e = I_{11} = I_1$, sprich: Die Hauptträgheitsmomente sind also gerade die Trägheitsmomente bezüglich die
   Hauptträgheitsachsen. \\
   Außerdem gilt:
   \[I_{ij}(\hat e_1)_j = I_{ij} δ_{j1} = I_{i1} = I_1 δ_{i1} = I_1(\hat e_1)_i\]
   Matrixschreibweise:
   \[I \hat e_1 = I_1 \hat e_1\]
   Demnach ist $\hat e_1$ ein *Eigenvektor* von $I$ mit *Eigenwert* $I_1$. Die Existenz
   eines gewissen Eigenvektors und dessen Eigenwert sind *koordinatenunabhängig*!
   In der Tat:
   \begin{align*}
   R · I \hat e_1 &= I_1 R \hat e_1 \\
   \string(R I R^{-1}\string) R &= I_1 R \hat e_1 \\
   I' \hat e_1' &= I_1 \hat e_1' \qquad \hat e_1' = R\hat e_1
   \end{align*}
   Wir sehen: Die Matrix $I$ hat 3 Eigenvektoren $\hat e_{(a)}$. Diese Eigenvektoren
   definieren die Hauptträgheitsachsen. Die Eigenwerte $I_a$ sind die entsprechenden Hauptträgheitsmomente.
** Eigenwerte, Eigenvektoren, Diagonlisierbarkeit
   Sei $\mathbb{V} = ℂ^n$ ein Vektorraum über $ℂ$. Definiere das Skalarprodukt $(∀x, y ∈ \mathbb{V})$
   \[x, y ↦ \angl{x, y} \equiv x^{\dagger} y ∈ ℂ\]
   Notation: $M^{\dagger} \equiv \bar M^T$ für alle komplexenen Matrizen. Sei $H$ eine hermitesche Matrix ($n × n$), das heißt $H^{\dagger} = H$.
   Wir können $H$ wie folgt diagonalisieren:
   - Löse $\det(H - λ \mathbb{1}) = 0$. (Fundamentalsatz der Algebra)
	 Nenne diese Lösung $λ_1$. Da nun $\det(H - λ_1 \mathbb{1}) = 0$ hat die Gleichung $(H - λ_1 \mathbb{1}) · x = 0$
	 eine nichttriviale Lösung $x_1 ∈ \mathbb{V}$. (Wegen Nicht-Invertierbarkeit $(H - λ_1 \mathbb{1})$).
	 Notation: $x_1$ heißt Eigenvektor von $H$ zum Eigenwert $λ_1$. Es gilt $Hx_1 = λ_1 x_1$
   - Behauptung: $H$ bildet $\{x_1\}_{\perp}$ auf $\{x_1\}_{\perp}$ ab.
   - Begründung: Sei $\angl{y, x_1} = 0$. Dann gilt
	 \[\angl{Hy, x_1} = (Hy)^{\dagger} x_1 = y^{\dagger} H^{\dagger} x_1 = y^{\dagger} H x_1 = λ_1 y^{\dagger} x_1 = λ_1 \angl{y, x_1} = 0~\checkmark\]
   Betrachte jetzt die $(n - 1) × (n - 1)$ -Matrix $H_1$ welce die Wirkung von $H$ auf $\{x_1\}_{\perp}$ beschreibt. Wiedehohle
   obiges Argument. Finde $λ_2, x_2$ und so weiter.
   - Wähle normierte Basis $e_1, \dots, e_n \sim x_1, \dots, x_n$. Diese Basis ist nach obigem auch orthogonal.
   - Wir nennen Matrizen welche eine Orthonormalbasis in eine Orthonormalbasis überführen unitär.
	 Ohne Beweis: Für solche Matrizen gilt $U^{\dagger} = U^{-1}$
   - Damit haben wir Diagonalisierbarkeit vod hermitesche Matrizen durch unitäre Transformationen!
   - Behauptung: $λ_i$ sind reell.
   - Begründung: $\angl{H x_1, x_1} = \angl{λ x_1, x_1} = \bar λ \angl{x_1, x_1} = \angl{x_1, H x_1} = λ\angl{x_1, x_1} \checkmark$
   Korollar: Reelle, symmetrische Matrizen $(H = H^{\dagger}, H_{ij} ∈ ℝ)$ können durch orthogonale Transformationen diagonalisiert werden. \\
   Dazu: Finde wie oben $λ_1 ∈ ℂ$. Wir wissen aber, dass auch $λ_1 ∈ ℝ$. Dann existiert ein reelles
   $x_1$ mit $(H - λ_1 \mathbb{1}) x_1 = 0$. Fortsetzung wie oben, nur "unitär" $\to$ "orthogonal".
** Trägheitsellipsoid
   Bisher: $I_{\text{würfel}} = \frac{1}{6} M a^2 \mathbb{1}$ \\
   Nächstes Beispiel: homogene Kugel, ohne Rechnung: $I \sim \mathbb{1}$, Warum? \\
   Es muss gelten: $I = R I R^{-1} ∀ R ∈ SO(3)$. Fakt: $δ_{ij}$ ist der einzige invariante Tensor von $SO(3)$
   mit zwei Indizes (vom Rang 2). \\
   Betrachte nun ein weniger symmetrisches Beispiel:
   #+ATTR_LATEX: :options [Hantel]
   #+begin_ex latex
   Hantel mit masseloser Stange, $m_1 = m_2 = m$
   \begin{align*}
   I_{ij} &= \sum_{m} m · (δ_{ij} \v r^2 - r_i r_j) \\
   &= 2m(δ_{ij} \v r^2 - r_i r_j) \qquad \v r = (0, 0, a) \\
   &= 2m a^2 \begin{pmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0\end{pmatrix}_{ij} \\
   \intertext{realistische Hantel (keine Punktmassen)}
   &= 2m a^2 \begin{pmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & ε\end{pmatrix}_{ij} \\
   \end{align*}
   #+end_ex
   Vermutung: "einfache" Beziehung zwischen Form des Körpers und Trägheitstensors. \\
   So wie ein Vektor einen Pfeil in $ℝ^3$ entspricht, so entspricht ein symmetrischer Tensor vom Rang $2$ einer *Fläche 2. Grades*:
   \[t_{ij} x_i x_j = 1\]
   Wir setzen nun $t \equiv I$ und gehen ins Hauptträgheitsachsensystem.
   \[I_{ij}x_i x_j = 1 ⇒ I_1 x_1^2 + I_2 x_2^2 + I_3 x_3^2 = 1\]
   Dies beschreibt einen Ellipsoid. Betrachte beliebige Achse $\hat e$ ($\hat e^2 = 1$).
   Diese schniede Ellipsoid bei $\v x_e$.
   \begin{align*}
   \v x_e &= \hat e · \abs{\v x_e} \\
   1 &= I_{ij} (x_e)_i (x_e)_j \\
   1 &= \abs{\v x_e}^2 I_{ij} \hat e_i \hat e_j = I_e \abs{\v x_e}^2 \\
   ⇒ \abs{\v x_e} &= \frac{1}{\sqrt{I_e}}
   \end{align*}
   $\abs{\v x_e}$ groß $⇔ I_e$ klein $⇔$ Körer hat in den "anderen" Richtungen eine kleine Ausdehnung.
   $⇒$ Trägheitsellipsoid folgt ungefähr Form des Körpers:
   | Körper    | Würfel / Kugel | Hantel / Quader            | gekreutzte Hantel / "Buch"                 |
   | Ellipsoid | Sphäre         | vertikal gestreckte Sphäre | vertikal gestauchte ("abgeflachte") Sphäre |
** Trägheitstensor und Drehimpuls (mehr zur Geometrie)
   Erinnerung: Tensor $t$ vom Rang $2$ ist bilineare Abbildung
   \[t: \mathbb{V} × \mathbb{V} \to ℝ, (x, y) ↦ t_{ij} x_i y_j\]
   Unser Fall:
   \[I: (\v ω, \v ω) ↦ I_{ij} ω_i ω_j = 2 T\]
   $⇒$ Die formale mathematische Definition vom $I$ hat unmittelbare physikalische Bedeutung.
   Sie ordnet $\v ω$ die kinetische Energie zu. Im euklidischen Raum definiert ein Tensor außerdem eine Abbildung
   \[t: \mathbb{V} \to \mathbb{V}, \{x_i\} ↦ \{t_{ij} x_j\} \text{ beziehungsweise } x \to tx\]
   Auch dies hat bei uns physikalische Bedeutung:
   \[I: \{ω_i\} ↦ \{I_{ij} ω_j\} = \{L_i\} \text{ also } \v ω ↦ \v L\]
   Wir behaupten hier, dass $L_i = I_{ij} ω_j$ gilt. Das ist leicht zu prüfen: Betrachte Massenpunkt bei der Position $\v r$.
   Drehe jetzt um Achse $\v ω$ mit Winkelgeschwindigkeit $\v ω$:
   \begin{align*}
   \v L &= \v r × \v p = m \v r × \dot{\v r} = m\v r × (\v w × \v r) \\
   L_i &= m ε_{ijk} r_j (ε_{klm} ω_l r_m) = \dots \\
   &= m(δ_{ij} \v r^2 - r_1 r_j) ω_j
   \end{align*}
   Nach Summation über viele Massenpunkte:
   \[L_i = \sum_{a} m_a (δ_{ij} \v r_a^2 - (r_a)_i (r_a)_j) ω_j = I_{ij} ω_j, L = I ω\]
