* Lagrange - Formalismus
** Grundidee (1788, Joseph-Louis Lagrange)
   Vorteile gegenüber Newton:
   - Flexibilität
   - Zwangskräfte
   - Zusammenhang zwischen Symmetrie und Erhaltungsgrößen
   Zentrales Objekt: Wirkungsfunktional $S$. \\
   Abbildung $S:$ Trajektorie $↦$ reelle Zahl \\
   ($S$ definiert mittels Lagrange-Funktion $L$) \\
   Zentrale physikalische Aussage des Formalismus: "Wirkungsprinzip" ("Hamilton-Prinzip") \\
   Letztes besagt: Eine physikalische Bewegung verläuft so, dass das Wirkungsfunktional minimal wird. \\
   $\to$ DGL ("Euler-Lagrange-Gleichung"), im einfachen Fall $\equiv$ Newton Gleichung
** Variationsrechnung: Der Funktionalbegriff
   Funktion (mehrerer Variablen) $y$;
   \[y: ℝ^n \to ℝ, y: \v x ↦ y(\v x)\]
   Funktional: analog, mit $ℝ^n$ ersetzt durch eine Menge von Funktionen (Vektorraum $\mathbb{V}$)
   \[F: \mathbb{V} \to ℝ, F: y ↦ F[y]\]
   #+begin_ex latex
   $\mathbb{V}$ seinen differenzierbare Funktionen auf $[0, 1]$ mit $y(0) = y(1) = 0$ \\
   Diskretisierung: \[x_1, \dots, x_n \to \underarrow[\{y(x_1), \dots, y(x_n)\}]{Vektor $\equiv$ Funktion}\] \\
   $⇒$ im diskreten Fall ist unser Funktional schlicht eine Funktion mit Vektor-Argument. (Eigentlicher Funktionalbegriff folgt im Limes $n \to ∞$). \\
   Beispielfunktionale zu obigem $\mathbb{V}$.
   - $F_1[y] = y(0.5)$
   - $F_2[y] = y'(0.3)$
   - $F_3[y] = y(0.1) + y(0.5) + y'(0.9)$
   - $F_4[y] = ∫_0^1 \d x (x · y(x)^2 + y'(x)^2)$
   - $F_5[y] = ∫_0^1 \d x f(y(x), y'(x), x)$
   $F_5$ hängt von Funktion $f$ (von $3$ Variablen) ab. Falls wir $f(a, b, c) = c a^2 + b^2$ wählen, folgt $F_4$ wählen.
   Noch konkreter: wähle Beispielfunktion (ignoriere zur Einfachheit Randbedingung $y(1) = 0$)
   \begin{gather*}
   y_0: x ↦ x^2; y_0(x) = x^2; y_0'(x) = 2x; \\
   ⇒ F_1[y_0] = 0.25; F_2[y_0] = 0.6, F_3[y_0] = 0.01 + 0.25 + 1.8 = 2.06 \\
   F_4[y_0] = ∫_0^1 \d x (x^5 + 4 x^2) = \frac{1}{6} + \frac{4}{3} = \frac{3}{2}
   \end{gather*}
   #+end_ex
** Weglänge als Funktional
   Weg von $\v y_a$ nach $\v y_b$: $\v y: τ ↦ \v y(τ), τ ∈ [0, 1]; \v y(0) = \v y_a, \v y(1) = \v y_b$ \\
   Weglänge:
   \[F[\v y] = ∫_{\v y_a}^{\v y_b} \abs{\d \v y} = ∫_0^1 \d τ \sqrt{(\frac{\d \v y(τ)}{\d τ})^2}\]
   (Eigentlich haben wir sogar ein Funktional einer vektorwertigen Funktion beziehungsweise ein Funktional mit $3$ Argumenten: $F[y] = F[y^1, y^2, y^3]$) \\
   Etwas interessanter: Weglänge im Gebirge: \\
   Sei $\v x(τ) = \{x^1(τ), x^2(τ)\}$ die Projektion des Weges auf Horizontale. Zu jedem solchen Weg gehört die "echte" Weglänge im Gebirge.
   Beachte: Höhenfunktion $z: \v x ↦ z(\v x)$ \\
   $⇒$ 3-d Weg:
   \begin{align*}
   \v y(τ) &= \{y^1(τ), y^2(τ), y^3(τ)\} \\
   &\equiv \{x^1(τ), x^2(τ), z(\v x(τ))\} \\
   F_{Geb.}[x] &= F[\v y[\v x]] = ∫\d t \sqrt{(\frac{\d x^1(τ)}{\d τ})^2 + (\frac{\d x^2(τ)}{\d τ})^2 + (\frac{\d z(x^1(τ), x^2(τ))}{\d τ})}
   \end{align*}
** Variationsrechnung: Extremalisierung von Funktionalen
   Funktionen: $y: x ↦ y(x)$; wir wissen $y$ hat Extremum bei $x_0 ⇒ y'(x_0) = 0$ \\
   Funktionale der Form: $F[y] = ∫_0^1 \d x f(y, y', x); y:[0, 1] \to ℝ; y(0) = y_a; y(1) = y_b$ \\
   Annahme: $y_0$ extremalisiert $F$. Sei weiterhin $δ y$ eine beliebige 2-fach differenzierbare Funktion mit $δ y(0) = δ y(1) = 0$ \\
   \[⇒ \underbrace{y_α \equiv y_0 + α · δ y}_{\mathclap{\text{Ist eine Funktion aus unserem Wertevorrat von } F}}\quad (α ∈ (-ε, ε))\]
   $⇒$ Betrachte Abbildung $(-ε, ε) \to ℝ, α ↦ F[y_α]$. Per unserer Annahme hat diese Abbildung Extremum bei $α = 0$.
   Also gilt \[\dd{}{α} F[y_α] = 0\big|_{α = 0}\]
   Taylor-Entwicklung um $α = 0$:
   \begin{align*}
   F[y_α] &= ∫_0^1 \d x f(y_0 + α δy, y_0' + α δy', x) \\
   &= F[y_0] + ∫_0^1 \d x (\frac{\partial f}{\partial y}(y_0, y_0', x) · α δy + \frac{\partial f}{\partial y'}(y_0, y_0', x) · α δy') + \mathcal{O}(α^2) \\
   \shortintertext{Term linear in $α$ muss verschwinden:}
   0 &= ∫_0^1 \d x (\frac{\partial f}{\partial y} δy + \frac{\partial f}{\partial y'} \dd{}{x} (δy)) \\
   \intertext{$\frac{\partial f}{\partial y'} δy = 0$ bei $0,1$}
   &= ∫_0^1 \d x (\frac{\partial f}{\partial y} - \dd{}{x}(\frac{\partial f}{\partial y'}))	δy = 0
   \intertext{für beliebige $δy ⇒$ der Koeffizient von $δy$ im Integral muss verschwinden}
   0 &= \frac{\partial f}{\partial y} - \dd{}{x}(\frac{\partial t}{\partial y'})  \tag{Eulersche Differentialgleichung}
   \end{align*}
   Falls $y_0$ das Funktional $F$ extremalisiert, so gilt die obige Gleichung für $y_0 ∀ x ∈ [0, 1]$
   #+begin_ex latex
   $f(y, y', x) = y^2 + y^{\prime 2}$
   \begin{align*}
   \frac{\partial f}{\partial y} &= 2 y \\
   \dd{}{x}(\frac{\partial f}{\partial y'}) &= \dd{}{x} 2y' = 2y'' \\
   ⇒ y_0'' - y_0 &= 0
   \end{align*}
   #+end_ex
   Beachte: $y$ und	$y'$ sind hier unabhängig, das heißt es spielt für die Herleitung der Eulerschen Differentialgleichung keine Rolle, dass $y'$ die Ableitung von $y$ ist.
** Das Hamiltonsche Prinzip (Prinzip der kleinsten Wirkung)
   Die Lage einer sehr großen Klasse von Systemen beschreiben durch verallgemeinerte Koordinaten $(q_1, \dots, q_s), s:$ Zahl der Freiheitsgrade.
   #+begin_ex latex
   - $N$ Massenpunkte: $s = 3N, (q_1, \dots, q_ {3N}) = (x_1^1, x_1^2, x_1^3, \dots, x_N^1, x_N^2, x_N^3)$
   - $1$ Massenpunkt in Kugelkoordinaten: $s = 3, (q_1, q_2, q_3) = (r, θ, φ)$
   - eine dünne Stange: $s = 5$. Schwerpunktskoordinaten $x_s^1, x_s^2, x_s^3$. 2 Winkel zur Ausrichtung $θ, φ$
   - Rad auf einer Welle: $s = 1, q_1 = φ$
   - Perle auf einem Draht: $s = 1, q_1 = s$ (Bogenlänge)
   #+end_ex
   *Hamiltonsches Prinzip*: \\
   Für jedes (in einer sehr großen Klasse) mechanische System $s$ Freiheitsgraden existiert die Lagrange-Funktion
   $L(q_1, \dots, q_s, \dot q_1, \dots, \dot q_s, t)$ (kurz $L(q, \dot q, t)$), für die gilt: \\
   Die physikalische Bewegung aus einer Lage $q(t_1) = q^{(1)}$ in eine Lage $q(t_2) = q^{(2)}$ verläuft so,
   dass das Wirkungsfunktional
   \[S[q] = ∫_{t_1}^{t_2} \d t L(q, \dot q, t)\]
   extremal wird.
   #+begin_note latex
   - für kleine Bahnabschnitte: Minimalität
   - DGL. aus Stationalität
   - Wirkung: Dimensionsgründe $[S] = \text{ Zeit } · \text{ Wirkung}$
   - Bedeutung des Wirkungsprinzip kann man kaum überschätzen. [spezielle + allgemeine Relativitätstheorie, Feldtheorie (Elektro-Dynamik), Quantenfeldtheorie (Teilchenphysik, kondensierte Materie), Quantengravitation]
   #+end_note
   für $s = 1$ folgt aus dem Hamiltonschen Prinzip:
   \[\dd{}{t} \frac{\partial L}{\dot q} - \frac{\partial L}{\partial q} = 0\]
   (Euler-Lagrange-Gleichung, oder Lagrange-Gleichung der 2. Art) \\
   für $s \geq 1$:
   \[\dd{}{t} \frac{\partial L}{\dot q_i} - \frac{\partial L}{\partial q_i} = 0, i = 1,\dots,s\]
** Form der Lagrange-Funktion und erste Anwendungen
   Fundamentaler Fakt:
   \[L = T - V\]
   - $T$: kinetische Energie
   - $V$: potentielle Energie
   #+ATTR_LATEX: :options [Massenpunkt im Potenzial]
   #+begin_ex latex
   \begin{align*}
   L(\v x, \dot{\v x}, t) &= \frac{m}{2} \dot{\v x}^2 - V(\v x) \\
   \dd{}{t} \frac{\partial L}{\partial \dot x^i} - \frac{\partial}{\partial x^i} L &= 0 \\
   \dd{}{t} (m \dot x^i) - (-\frac{\partial V}{\partial x_i}) &= 0 \\
   m \ddot x^i - F^i &= 0 \\
   m \ddot{\v x} - \v F = 0
   \end{align*}
   #+end_ex
   #+ATTR_LATEX: :options [System wechselwirkender Massenpunkte]
   #+begin_ex latex
   \begin{align*}
   T &= \sum_{a} T_a = \sum_{a} \frac{m_a}{2} \dot{\v x_a}^2 \\
   V &= \sum_{\substack{a, b\\a < b}} V_{ab} (\abs{x_a - x_b})
   \end{align*}
   Lagrange Gleichung für $x_a^i$:
   \begin{align*}
   m_a \ddot{x}_a^i - \frac{\partial}{\partial x_a^i}(\sum_{b} V_{ab} (\abs{\v x_a - \v x_b})) &= 0 \\
   m_a \ddot{\v x}_a - \v ∇_a \sum_{b} V_{ab} (\abs{\v x_a - \v x_b}) &= 0 \\
   \end{align*}
   #+end_ex
   #+ATTR_LATEX: :options [Perle auf Draht]
   #+begin_ex latex
   Draht: beschrieben durch $\v x(s)$ ($s$: Bogenlänge)
   \begin{align*}
   L &= \frac{m}{2} v^2 - V(\v x(s)) \\
   v &= \abs{\dd{\v x}{s}} \dd{s}{t} \\
   L &= \frac{m}{2} \dot{s}^2 - V(\v x(s)) \\
   \dd{}{t} \frac{\partial L}{\partial \dot s} - \frac{\partial L}{\partial s} &= 0 \\
   m \ddot{s} - \sum_{i} \underbrace{\frac{\partial L}{\partial x^i}}_{-\frac{\partial V}{\partial x^i}} \frac{\partial x^i}{\partial s} &= 0 \\
   m \ddot{s} - \v F · \frac{\v x}{s} &= 0
   \end{align*}
   #+end_ex
   #+ATTR_LATEX: :options [Mathematisches Pendel im Fahrstuhl]
   #+begin_ex latex
   Beschleunigung des Fahrstuhls: $v_y = a·t$
   \begin{align*}
   L &= \frac{m}{2} \v v^2 - V \\
   \v v &= (\dd{}{t}(l \sin{φ}), a t - \dd{}{t}(l \cos{φ})) \\
   &= (l \cos(φ)\dot φ, a t + l \sin φ \dot φ) \\
   V &= m g (\frac{a}{2} t^2 - l \cos{φ}) \\
   0 &= \dd{}{t} \frac{\partial L}{\partial \dot φ} - \frac{\partial L}{\partial φ} \\
   \end{align*}
   \begin{multline*}
   = \dd{}{t} (\frac{m}{2}(l^2 \cos^2 φ 2 \dot φ + 2 a t l \sin φ + l^2 \sin^2 φ 2 \dot φ)) - \\
   \left\string(\frac{m}{2} (l^2 \dot φ^2 2 \cos φ (-\sin φ) + 2 a t l \dot φ \cos φ + l^2 \dot φ^2 2 \sin φ \cos φ) - m g l \sin φ\right\string)
   \end{multline*}
   \begin{multline*}
   0 = (2 l^2 \cos φ (-\sin φ) \dot φ^2 + l^2 \cos^2 φ \ddot{φ} + a l \sin{φ} + a t l \cos φ \dot φ + l^2 2\sin φ \cos φ \dot φ^2 + l^2 \sin^2 φ \ddot φ) \\
   - t a l \dot φ \cos{φ} + g l \sin φ
   \end{multline*}
   \[0 = l^2 \ddot{φ} + l \sin φ(a + g)\]
   #+end_ex
** Vereinfachte Herleitung der Lagrange-Gleichungen
   $q(t)$ Trajektorie, Variation der Trajektorie: $δq(t)$
   - neue Trajektorie: $q(t) + δq(t)$.
   - neue Wirkung $S + δS$
	 Anders gesagt: $δS \equiv S[q + δq] - S[q]$.
   Extremalität:
   \begin{align*}
   0 &= δS = ∫_{t_1}^{t_2} \d t δ L(q, \dot q, t) \\
   &= ∫_{t_1}^{t_2} \d t\left[\frac{\partial L(q, \dot q, t)}{\partial q} δ q + \frac{\partial L(q, \dot q, t)}{\partial \dot q} δ\dot q\right] \\
   &= ∫_{t_1}^{t_2} \d t\left[\frac{\partial L}{\partial q} δ q + \frac{\partial L}{\partial \dot q} \dd{}{t}(δ q)\right] \\
   \intertext{Partielle Integration, nutze $δq(t_1) = δq(t_2) = 0$}
   0 &= ∫_{t_1}^{t_2} \d t (\frac{\partial L}{\partial q} δq - \dd{}{t}(\frac{\partial L}{\partial \dot q})δq) \\
   0 &= ∫_{t_1}^{t_2} \d t (\frac{\partial L}{\partial q} - \dd{}{t} \frac{\partial L}{\partial \dot q}) δq \\
   \intertext{$δq$ beliebig $⇒$ Term muss verschwinden}
   0 &= \frac{\partial L}{\partial q} - \dd{}{t} \frac{\partial L}{\partial \dot q} = 0~\checkmark
   \end{align*}
** Kommentare
   *Argumente von $L$*: $\ddot{q}, \dddot{q}$, etc. dürfen nicht in $L$ vorkommen, weil sonst $\dddot{q}, \ddddot{q}$, etc. in den Bewegungsgleichungen
   vorkommen würden. Dann reichen $\v x(t_0) ∧ \v v(t_0)$ nicht mehr zur Lösung des Anfangswertproblems. \\
   *Totale Zeitableitungen*: \\
   Seinen $L, L'$ zwei Lagrangefunktionen mit
   \begin{align*}
   L' &= L + \dd{}{t} f(q, t) \\
   ⇒ S' &= S + ∫_{t_1}^{t_2} \d t \dd{}{t} f(q, t) = S + \underbrace{(f(q(t_2), t_2) - f(q(t_1), t_1))}_{\text{variiert nicht}} \\
   ⇒ δS' &= δ S
   \end{align*}
   $⇒ L'$ physikalisch äquivalent zu $L$ ($L$ ist nur bis auf totale Zeitableitungen definiert.) \\
   *Bedeutung von $S$ in der QM*: \\
   In der Quantenmechanik ist die Wahrscheinlichkeit $w$ für den Übergang von $(q^{(1)}, t_1)$ zu $(q^{(2)}, t_2)$ gegeben durch
   \[w \sim \abs{A}^2\], $A ∈ ℂ$ ist "Amplitude", mit
   \[A \sim ∫ D q e^{\frac{i S[q]}{\hbar}}\]
   $∫D q$ - Summe über alle mögliche Trajektorien ("Wege"), ("Pfade"). \\
   Im Limes $\hbar \to 0$ dominiert klassischer Weg. Grund: $S$ ist an dieser Stelle stationär. Beiträge von "ganz anderen" Wegen heben sich wegen schneller Oszillation von $\exp[i S / \hbar]$ weg.
