#+AUTHOR: Robin Heinemann
#+TITLE: Theoretische Physik II (Hebecker)

# Einleitung: \\
# - Website: www.thphys.uni-heidelberg.de/hebecker/TP2/tp2.html
# - Bartelman Skripte
# Dienstag, 2. Mai: Zetter hier abgehen

#+INCLUDE: "../header.org" :minlevel 1

# Inhalt
# - Analytische Mechanik (2 / 3)
#   - Lagrange und Hamitlon-Formalismus
#     sehr wichtig für: Quantentheorie (Teilchenphysik, Gravitation)
# - Statistik & Thermadynamik (1 / 3)
#   mehr zu TD / S.: in Theo 5: Vuantenstatistik

* Lagrange - Formalismus
** Grundidee (1788, Joseph-Louis Lagrange)
   Vorteile gegenüber Newton:
   - Flexibelität
   - Zwangskräfte
   - Zusammenhang zwischen Symmetrie und Erhaltungsgrößen
   Zentrales Objekt: Wirkungsfunktional $S$. \\
   Abbildung $S:$ Trajektorie $↦$ reelle Zahl \\
   ($S$ definiiert mittls Lagrange-Funktion $L$) \\
   Zentrale physikalische Aussage des Formalimus: "Wirkungsprinzip" ("Hamilton-Prinzip") \\
   Letztes besagt: Eine physikalische Bewegung verläuft so, dass das Wirkungsfunktional minimal wird. \\
   $\to$ DGL ("Euler-Lagrange-Gleichung"), im einfachen Fall $\equiv$ Newton Gleichung
** Variationsrechnung: Der Funktionalbegriff
   Funktion (mehrerer Variablen) $y$;
   \[y: ℝ^n \to ℝ, y: \v x ↦ y(\v x)\]
   Funktional: analg, mit $ℝ^n$ ersetzt durch eine Menge von Funktionen (Vektorraum $\mathbb{V}$)
   \[F: \mathbb{V} \to ℝ, F: y ↦ F[y]\]
   #+begin_ex latex
   $\mathbb{V}$ seinen differenziebare Funktionen auf $[0, 1]$ mit $y(0) = y(1) = 0$ \\
   Diskretisierung: \[x_1, \dots, x_n \to \underarrow[\{y(x_1), \dots, y(x_n)\}]{Vektor $\equiv$ Funktion}\] \\
   $⇒$ im diskreten Fall ist unser Funktional schlicht eine Funktion mit Vektor-Argument. (Eigentlicher Funktionalbegriff folgt im Limes $n \to ∞$). \\
   Beispielfunktionale zu obigem $\mathbb{V}$.
   - $F_1[y] = y(0.5)$
   - $F_2[y] = y'(0.3)$
   - $F_3[y] = y(0.1) + y(0.5) + y'(0.9)$
   - $F_4[y] = ∫_0^1 \d x (x · y(x)^2 + y'(x)^2)$
   - $F_5[y] = ∫_0^1 \d x f(y(x), y'(x), x)$
   $F_5$ hängt von Funktion $f$ (von $3$ Variablen) ab. Falls wir $f(a, b, c) = c a^2 + b^2$ wählen, folgt $F_4$ wählen, folgt $F_4$.
   Noch konkreter: wähle Beispielfunktion (ignoriere zur Einfachheit Randbedingung $y(1) = 0$)
   \begin{gather*}
   y_0: x ↦ x^2; y_0(x) = x^2; y_0'(x) = 2x; \\
   ⇒ F_1[y_0] = 0.25; F_2[y_0] = 0.6, F_3[y_0] = 0.01 + 0.25 + 1.8 = 2.06 \\
   F_4[y_0] = ∫_0^1 \d x (x^5 + 4 x^2) = \frac{1}{6} + \frac{4}{3} = \frac{3}{2}
   \end{gather*}
   #+end_ex
** Weglänge als Funktional
   Weg von $\v y_a$ nach $\v y_b$: $\v y: τ ↦ \v y(τ), τ ∈ [0, 1]; \v y(0) = \v y_a, \v y(1) = \v y_b$ \\
   Weglänge:
   \[F[\v y] = ∫_{\v y_a}^{\v y_b} \abs{\d \v y} = ∫_0^1 \d τ \sqrt{(\frac{\d \v y(τ)}{\d τ})^2}\]
   (Eigentlich haben wir sogar ein Funktional einer vektorwertigen Funktion beziehungsweise ein Funktional mit $3$ Argumenten: $F[y] = F[y^1, y^2, y^3]$) \\
   Etwas interessater: Weglänge im Gebirge: \\
   Sei $\v x(τ) = \{x^1(τ), x^2(τ)\}$ die Projektion des Weges auf Horizontale. Zu jedem solchen Weg gehört die "echte" Weglänge im Gebirge.
   Beachte: Höhenfunktion $z: \v x ↦ z(\v x)$ \\
   $⇒$ 3-d Weg:
   \begin{align*}
   \v y(τ) &= \{y^1(τ), y^2(τ), y^3(τ)\} \\
   &\equiv \{x^1(τ), x^2(τ), z(\v x(τ))\} \\
   F_{Geb.}[x] &= F[\v y[\v x]] = ∫\d t \sqrt{(\frac{\d x^1(τ)}{\d τ})^2 + (\frac{\d x^2(τ)}{\d τ})^2 + (\frac{\d z(x^1(τ), x^2(τ))}{\d τ})}
   \end{align*}
** Variationsrechnung: Extremalisieung von Funktionalen
   Funktionen: $y: x ↦ y(x)$; wir wissen $y$ hat Extremum bei $x_0 ⇒ y'(x_0) = 0$ \\
   Funktionale der Form: $F[y] = ∫_0^1 \d x f(y, y', x); y:[0, 1] \to ℝ; y(0) = y_a; y(1) = y_b$ \\
   Annahme: $y_0$ extremalisiert $F$. Sei weiterhin $δ y$ eine beliebige 2-fach differenziebare Funktion mit $δ y(0) = δ y(1) = 0$ \\
   \[⇒ \underbrace{y_α \equiv y_0 + α · δ y}_{\mathclap{\text{Ist eine Funktion aus unserem Wertevorrat von } F}}\quad (α ∈ (-ε, ε))\]
   $⇒$ Betrachte Abbildung $(-ε, ε) \to ℝ, α ↦ F[y_α]$. Per unserer Annahme hat diese Abbildung Extremum bei $α = 0$.
   Also gilt \[\dd{}{α} F[y_α] = 0\big|_{α = 0}\]
   Taylor.entwickle um $α = 0$:
   \begin{align*}
   F[y_α] &= ∫_0^1 \d x f(y_0 + α δy, y_0' + α δy', x) \\
   &= F[y_0] + ∫_0^1 \d x (\frac{\partial f}{\partial y}(y_0, y_0', x) · α δy + \frac{\partial f}{\partial y'}(y_0, y_0', x) · α δy') + O(α^2) \\
   \shortintertext{Term linear in $α$ muss verschwinden:}
   0 &= ∫_0^1 \d x (\frac{\partial f}{\partial y} δy x \frac{\partial f}{\partial y'} \dd{}{x} (δy)) \\
   \intertext{$\frac{\partial f}{\partial y'} δy = 0$ bei $0,1$}
   &= ∫_0^1 \d x (\frac{\partial f}{\partial y} - \dd{}{x}(\frac{\partial f}{\partial y'}))	δy = 0
   \end{align*}
