#+AUTHOR: Robin Heinemann
#+TITLE: Theoretische Physik II (Hebecker)

# Einleitung: \\
# - Website: www.thphys.uni-heidelberg.de/hebecker/TP2/tp2.html
# - Bartelman Skripte
# Dienstag, 2. Mai: Zetter hier abgehen

#+INCLUDE: "../header.org" :minlevel 1

# Inhalt
# - Analytische Mechanik (2 / 3)
#   - Lagrange und Hamitlon-Formalismus
#     sehr wichtig für: Quantentheorie (Teilchenphysik, Gravitation)
# - Statistik & Thermadynamik (1 / 3)
#   mehr zu TD / S.: in Theo 5: Vuantenstatistik

#+INCLUDE: "lagrange_variation.org" :minlevel 1
#+INCLUDE: "symmetries_conservation_laws.org" :minlevel 1
* Trägheitstensor
** Trägheitsmoment und Satz von Steiner
   Rotation von Körper um feste Achse $A$. Körper besteht aus Elementen $m_a$ mit Radius $r_{a, \perp}$.
   Kontinuierlich: $m_a = \rho ΔV$. Einzige erlaubte Bewegung sei Drehung um Achse $A$:
   \begin{align*}
   T &\simeq \sum_{a} \frac{m_a}{2}v_a^2 = \sum_{a} \frac{m_a}{2} ω_2 r_{a,\perp}^2 \\
   &= \frac{1}{2} I_A ω^2 \\
   ⇒ I_A &\equiv \sum_{a} m_a r_{a, \perp}^2 \\
   \intertext{Trägheitsmoment im Kontinuum:}
   I_A = ∫ \d^2 \v r ρ(\v r) r_{\perp}^2
   \end{align*}
   Einziger Freiheitsgrad: Drehwinkel $φ$ (wobei $ω = \dot φ$)
   \begin{align*}
   L(φ, \dots φ) &= \frac{1}{2} I_A \dot φ^2 - V(φ) \\
   ⇒ I_A \ddot{φ} &= -\pp{V}{φ}
   \end{align*}
   Annahme: $V$ ergibt sich als Summe der Potentiale aller Teilmassen:
   \[V(φ) = \sum_{a} V_a(\v r_a(φ))\]
   Betrachte
   \begin{align*}
   V(φ + δφ) &= \sum_{a} V_a(\v r_a(φ) + δ\v v_a) \\
   &= \sum_{a} V_a(\v r_a(φ) + δ\v φ × \v r_a(φ)) \\
   &= \sum_{a} V_a + \sum_{a}(δ\v φ × \v r_a) · \v ∇ V_a(\v r_a(φ)) \\
   V(φ + δφ) - V(φ) &= \sum_{a}(δ\v φ × \v r_a) \v ∇ V_a(\v r_a(φ)) \\
   \intertext{Limes $δφ \to 0, δ\v φ = \v e_A δφ, \v e_A$ Einheitsvektor der Achse}
   -\dd{V(φ)}{φ} &= -\sum_{a} \frac{δ\v φ × \v r_a}{δφ} \v ∇V \\
   &= \sum_{a} ε_{ijk}(\v e_A)_j (\v r_a)_k · (F_a)_i \\
   &= \sum_{a} (\v e_A)_j (\v r_a × \v F_a)_j = \sum_{a} \v e_A · \v M_a
   \end{align*}
   $\v M_a$: Drehmoment auf Punkt "$a$". \\
   Zuletzt: $I_A \ddot φ = -\dd{V}{φ}$
   \[⇒ \dd{}{t}(I_A \dot φ) = \v e_A \v M\]
   $\v M$: Gesamtdrehmoment. \\
   Erinnerung: Drehimpuls für Punktmasse: $\v L = m\v r × \v v$
   \[⇒ \v e_A · \v L = m \v e_A [(\v r_{\parallel} + \v r_{\perp}) × \v r]\]
   \[\abs{\v r_{\perp} × \v v} = \abs{\v r_{\perp}} \abs{\v v} = \abs{\v r_{\perp}} \abs{\v r_{\perp}} \dot φ\]
   \[⇒ \v e_A \v L = m r_{\perp}^2 \dot φ ⇒ \v e_A \v L = I_A \dot φ\]
   \[⇒ \v e_A · \dot{\v L} = \v e_A \v M\]
   Bemerkung: $I_A$ ist besonders einfach zu berechnen falls $A \parallel S$ (Schwerpunktsachse) und $I_S$ bekannt, $\v R_{\perp}$ ist der (senkrechte) Abstand der beiden Achsen.
   \begin{align*}
   I_A &= \sum_{a} m_a v_{0,\perp}^2 = \sum_{a} m_a (\v R_{\perp} + \v r_{\perp, a}')^2 \\
   \intertext{Summe der Mischterme fällt weg}
   I_A &= \sum_{a} m_a (\v R_{\perp}^2 + \v r_{a, \perp}^{\prime 2}) \\
   \intertext{Satz von Steiner:}
   ⇒ I_A &= M \v R_{\perp}^2 + I_s
   \end{align*}
** Trägheitstensor
   Berechne kinetische Energie einen Körpers der sich mit $\v v$ und mit $\v ω$ um Achse durch Schwerpunkt dreht.
   \begin{align*}
   T &= \sum_{a} \frac{m_a}{2} \v v_a^2 = \sum_{a} \frac{m_a}{2}(\v v + \v ω × \v r_a)^2 \\
   &= \sum_{a} \frac{m_a}{2}(\v v^2 + 2\v v(\v ω × \v r_a) + (\v ω × \v r_a)^2) \\
   \intertext{"Mischterm" fällt weg, da $\sum_a m_a \v r_a = 0$, wegen Schwerpunktbedingung}
   &= \frac{M}{2}\v v^2 + \sum_{a} \frac{m_a}{2}(\v ω + \v r_a)^2 \\
   &= \frac{M}{2}\v v^2 + \frac{1}{2} I_{ij} ω_i ω_j \\
   I_{ij} &\equiv \sum_{a} m_a (δ_{ij} \v r_a^2 - (\v r_a)_j (\v r_a)_j) \\
   \intertext{Integralform:}
   I_{ij} = ∫ \d^3 \v r ρ(\v r)(δ_{ij} \v r^2 - r_i r_j)
   \end{align*}
   Speziell für $\v r = (x, y, z)$ findet man:
   \[I = ∫\d x \d y \d z ρ(\v r) \begin{pmatrix}y^2 + z^2 &  -xy & -xz \\ -xy & x^2 + z^2 & -yz \\  -xz & -yz & x^2 + y^2\end{pmatrix}\]
   #+ATTR_LATEX: :options [homogener Würfel]
   #+begin_ex latex
   $∫\d x \to ∫_{-a/2}^{a/2}\d x$
   \[∫_{-a/2}^{a/2} \d x ∫_{-a/2}^{a/2} \d y y^2 ∫_{-a/2}^{a/2} \d z = a · \frac{a^3}{12} · a\]
   Insgesamt:
   \[I = a^2 ρ \begin{pmatrix}\frac{1}{6}a^3 &  &  \\  & \frac{1}{6} a^3 &  \\  &  & \frac{1}{6} a^3\end{pmatrix} = \frac{1}{6} M a^2 \mathbb{1}\]
   #+end_ex
** Hauptträgheitsachsen
   Tensor ist (wie) Vektor ein geometrisches Objekt. Er beschreibt Dichte/ Form des Körpers.
   Bei Drehungen des Körpers: Dreht sich mit: $I_{ij}' = R_{ik} R_{jl} I_{kl} ⇔ I' = R I R^T = R I R^{-1}$ (aktive Sicht). \\
   Passive Sicht: Für die Komponenten von $I$ im gedrehten Koordinatensystem gilt:
   \[I_{ij}' = R_{ik}R_{jl}I_{kl}\]
   Zentraler Satz: Jede symmetrische, reelle Matrix kann durch eine orthogonale Transformation auf Diagonalform gebracht werden.
   $⇒$ Wir können als stets den Körper so drehen beziehungsweise das Koordinatensystem so wählen, dass
   \[I = \begin{pmatrix}I_1 & 0 & 0 \\ 0 & I_2 & 0 \\ 0 & 0 & I_3\end{pmatrix}\]
   $I_1, I_2, I_3$ heißen Hauptträgheitsmonente. Die Koordinaten $\hat e_1, \hat e_2, \hat e_3$ des Systems in dem $I$ diagonal ist heißen
   Hauptträgheitsachsen. (im Allgemeinen sind dies die Symmetrieachsen des Körpers, soweit vorhanden). \\
   Sei $\v v = 0$, sei $\v ω = ω \hat e$ ($\hat e$ beliebiger Einheitsvektor).
   \[⇒ T = \frac{1}{2}I_{ij}ω_i ω_j = \frac{1}{2} I_{ij} \hat e_i \hat e_j ω^2 \equiv \frac{1}{2} I_e ω^2\]
   (Daher ist $I_e \equiv I_{ij} \hat e_i \hat e_j$) das Trägheitsmoment bezüglich $\hat e$. \\
   Sei speziell $I$ diagonal und $\hat e = \hat e_1 = (1, 0, 0)$. Es folgt $I_e = I_{11} = I_1$, sprich: Die Hauptträgheitsmomente sind also gerade die Trägheitsmomente bezüglich die
   Hauptträgheitsachsen. \\
   Außerdem gilt:
   \[I_{ij}(\hat e_1)_j = I_{ij} δ_{j1} = I_{i1} = I_1 δ_{i1} = I_1(\hat e_1)_i\]
   Matrixschreibweise:
   \[I \hat e_1 = I_1 \hat e_1\]
   Demnach ist $\hat e_1$ ein *Eigenvektor* von $I$ mit *Eigenwert* $I_1$. Die Existenz
   eines gewissen Eigenvektors und dessen Eigenwert sind *koordinatenunabhängig*!
   In der Tat:
   \begin{align*}
   R · I \hat e_1 &= I_1 R \hat e_1 \\
   \string(R I R^{-1}\string) R &= I_1 R \hat e_1 \\
   I' \hat e_1' &= I_1 \hat e_1' \qquad \hat e_1' = R\hat e_1
   \end{align*}
   Wir sehen: Die Matrix $I$ hat 3 Eigenvektoren $\hat e_{(a)}$. Diese Eigenvektoren
   definieren die Hauptträgheitsachsen. Die Eigenwerte $I_a$ sind die entsprechenden Hauptträgheitsmomente.
** Eigenwerte, Eigenvektoren, Diagonlisierbarkeit
   Sei $\mathbb{V} = ℂ^n$ ein Vektorraum über $ℂ$. Definiere das Skalarprodukt $(∀x, y ∈ \mathbb{V})$
   \[x, y ↦ <x, y> \equiv x^{\dagger} y ∈ ℂ\]
   Notation: $M^{\dagger} \equiv \bar M^T$ für alle komplexenen Matrizen. Sei $H$ eine hermitesche Matrix ($n × n$), das heißt $H^{\dagger} = H$.
   Wir können $H$ wie folgt diagonalisieren:
   - Löse $\det(H - λ \mathbb{1}) = 0$. (Fundamentalsatz der Algebra)
	 Nenne diese Lösung $λ_1$. Da nun $\det(H - λ_1 \mathbb{1}) = 0$ hat die Gleichung $(H - λ_1 \mathbb{1}) · x = 0$
	 eine nichttriviale Lösung $x_1 ∈ \mathbb{V}$. (Wegen Nicht-Invertierbarkeit $(H - λ_1 \mathbb{1})$).
	 Notation: $x_1$ heißt Eigenvektor von $H$ zum Eigenwert $λ_1$. Es gilt $Hx_1 = λ_1 x_1$
   - Behauptung: $H$ bildet $\{x_1\}_{\perp}$ auf $\{x_1\}_{\perp}$ ab.
   - Begründung: Sei $<y, x_1> = 0$. Dann gilt
	 \[<Hy, x_1> = (Hy)^{\dagger} x_1 = y^{\dagger} H^{\dagger} x_1 = y^{\dagger} H x_1 = λ_1 y^{\dagger} x_1 = λ_1 <y, x_1> = 0~\checkmark\]
   Betrachte jetzt die $(n - 1) × (n - 1)$ -Matrix $H_1$ welce die Wirkung von $H$ auf $\{x_1\}_{\perp}$ beschreibt. Wiedehohle
   obiges Argument. Finde $λ_2, x_2$ und so weiter.
   - Wähle normierte Basis $e_1, \dots, e_n \sim x_1, \dots, x_n$. Diese Basis ist nach obigem auch orthogonal.
   - Wir nennen Matrizen welche eine Orthonormalbasis in eine Orthonormalbasis überführen unitär.
	 Ohne Beweis: Für solche Matrizen gilt $U^{\dagger} = U^{-1}$
   - Damit haben wir Diagonalisierbarkeit vod hermitesche Matrizen durch unitäre Transformationen!
   - Behauptung: $λ_i$ sind reell.
   - Begründung: $<H x_1, x_1> = <λ x_1, x_1> = \bar λ <x_1, x_1> = <x_1, H x_1> = λ<x_1, x_1> \checkmark$
   Korollar: Reelle, symmetrische Matrizen $(H = H^{\dagger}, H_{ij} ∈ ℝ)$ können durch orthogonale Transformationen diagonalisiert werden. \\
   Dazu: Finde wie oben $λ_1 ∈ ℂ$. Wir wissen aber, dass auch $λ_1 ∈ ℝ$. Dann existiert ein reelles
   $x_1$ mit $(H - λ_1 \mathbb{1}) x_1 = 0$. Fortsetzung wie oben, nur "unitär" $\to$ "orthogonal".
** Trägheitsellipsoid
   Bisher: $I_{\text{würfel}} = \frac{1}{6} M a^2 \mathbb{1}$ \\
   Nächstes Beispiel: homogene Kugel, ohne Rechnung: $I \sim \mathbb{1}$, Warum? \\
   Es muss gelten: $I = R I R^{-1} ∀ R ∈ SO(3)$. Fakt: $δ_{ij}$ ist der einzige invariante Tensor von $SO(3)$
   mit zwei Indizes (vom Rang 2). \\
   Betrachte nun ein weniger symmetrisches Beispiel:
   #+ATTR_LATEX: :options [Hantel]
   #+begin_ex latex
   Hantel mit masseloser Stange, $m_1 = m_2 = m$
   \begin{align*}
   I_{ij} &= \sum_{m} m · (δ_{ij} \v r^2 - r_i r_j) \\
   &= 2m(δ_{ij} \v r^2 - r_i r_j) \qquad \v r = (0, 0, a) \\
   &= 2m a^2 \begin{pmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 0\end{pmatrix}_{ij} \\
   \intertext{realistische Hantel (keine Punktmassen)}
   &= 2m a^2 \begin{pmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & ε\end{pmatrix}_{ij} \\
   \end{align*}
   #+end_ex
   Vermutung: "einfache" Beziehung zwischen Form des Körpers und Trägheitstensors. \\
   So wie ein Vektor einen Pfeil in $ℝ^3$ entspricht, so entspricht ein symmetrischer Tensor vom Rang $2$ einer *Fläche 2. Grades*:
   \[t_{ij} x_i x_j = 1\]
   Wir setzen nun $t \equiv I$ und gehen ins Hauptträgheitsachsensystem.
   \[I_{ij}x_i x_j = 1 ⇒ I_1 x_1^2 + I_2 x_2^2 + I_3 x_3^2 = 1\]
   Dies beschreibt einen Ellipsoid. Betrachte beliebige Achse $\hat e$ ($\hat e^2 = 1$).
   Diese schniede Ellipsoid bei $\v x_e$.
   \begin{align*}
   \v x_e &= \hat e · \abs{\v x_e} \\
   1 &= I_{ij} (x_e)_i (x_e)_j \\
   1 &= \abs{\v x_e}^2 I_{ij} \hat e_i \hat e_j = I_e \abs{\v x_e}^2 \\
   ⇒ \abs{\v x_e} &= \frac{1}{\sqrt{I_e}}
   \end{align*}
   $\abs{\v x_e}$ groß $⇔ I_e$ klein $⇔$ Körer hat in den "anderen" Richtungen eine kleine Ausdehnung.
   $⇒$ Trägheitsellipsoid folgt ungefähr Form des Körpers:
   | Körper    | Würfel / Kugel | Hantel / Quader            | gekreutzte Hantel / "Buch"                 |
   | Ellipsoid | Sphäre         | vertikal gestreckte Sphäre | vertikal gestauchte ("abgeflachte") Sphäre |
** Trägheitstensor und Drehimpuls (mehr zur Geometrie)
   Erinnerung: Tensor $t$ vom Rang $2$ ist bilineare Abbildung
   \[t: \mathbb{V} × \mathbb{V} \to ℝ, (x, y) ↦ t_{ij} x_i y_j\]
   Unser Fall:
   \[I: (\v ω, \v ω) ↦ I_{ij} ω_i ω_j = 2 T\]
   $⇒$ Die formale mathematische Definition vom $I$ hat unmittelbare physikalische Bedeutung.
   Sie ordnet $\v ω$ die kinetische Energie zu. Im euklidischen Raum definiert ein Tensor außerdem eine Abbildung
   \[t: \mathbb{V} \to \mathbb{V}, \{x_i\} ↦ \{t_{ij} x_j\} \text{ beziehungsweise } x \to tx\]
   Auch dies hat bei uns physikalische Bedeutung:
   \[I: \{ω_i\} ↦ \{I_{ij} ω_j\} = \{L_i\} \text{ also } \v ω ↦ \v L\]
   Wir behaupten hier, dass $L_i = I_{ij} ω_j$ gilt. Das ist leicht zu prüfen: Betrachte Massenpunkt bei der Position $\v r$.
   Drehe jetzt um Achse $\v ω$ mit Winkelgeschwindigkeit $\v ω$:
   \begin{align*}
   \v L &= \v r × \v p = m \v r × \dot{\v r} = m\v r × (\v w × \v r) \\
   L_i &= m ε_{ijk} r_j (ε_{klm} ω_l r_m) = \dots \\
   &= m(δ_{ij} \v r^2 - r_1 r_j) ω_j
   \end{align*}
   Nach Summation über viele Massenpunkte:
   \[L_i = \sum_{a} m_a (δ_{ij} \v r_a^2 - (r_a)_i (r_a)_j) ω_j = I_{ij} ω_j, L = I ω\]
* Kreisel
** Euler-Gleichungen
   Körperfestes System vs. Raumfestes System. Drehmatrix $R(t) ∈ SO(3)$
   \[L' = RL, v' = Rv\]
   Bewegungsgleichungen:
   \begin{align*}
   \dot{\v L'} = \v M' \qquad \dd{}{t}(R · L) &= RM \\
   \dot R L + R \to L &= RM \\
   \intertext{Erinnerung: $\dot R r = R(ω × r)$}
   R(ω × L) + R \dot L &= R  M \\
   \dot R &= M + L × ω \\
   L &= I ω \\
   I \dot ω = M + (I ω) × ω
   \end{align*}
   Wähle als körperfestes System speziell das Hauptachsensystem $⇒ I = \begin{pmatrix}I_1 &   &   \\   & I_2 &   \\   &   & I_3\end{pmatrix}$.
   $⇒$ Euler-Gleichungen
   \begin{align*}
   I_1 \dot ω_1 &= M_1 + ω_2 ω_3(I_2 - I_3) \\
   I_2 \dot ω_2 &= M_2 + ω_3 ω_1(I_3 - I_1) \\
   I_3 \dot ω_3 &= M_3 + ω_1 ω_3(I_1 - I_2)
   \end{align*}
** Freier Kreisel
   Energieerhaltung:
   \[E = T = \frac{1}{2}ω^T I ω = \frac{1}{2}\sum_{i = 1}^{3}I_i ω_i^2\]
   \[L_i = I_i ω_i ⇒ E = \frac{1}{2} \sum_{i = 1}^{3} \frac{L_i^2}{I_i}\]
   oder
   \[\frac{L_1^2}{2E I_1} + \frac{L_2^2}{2E I_2} + \frac{L_3^2}{2E I_3} = 1\]
   $⇒ L$ ist auf ein Ellipsoid ("Binet-Ellipsoid" (Ellipsoid im "L-Raum")) eingeschränkt. \\
   Drehimpulserhaltung:
   \[L' = \const, L' = RL, R ∈ SO(3) ⇒ \abs{L} = \const\]
   $⇒ L$ bewegt sich im körperfesten System auf Schnittkurven von Binet-Ellipsoid und Sphäre mit Radius $\abs{\v L} = \abs{\v L'}$
   Ohne Beschränkung der Allgemeinheit: $I_1 > I_2 > I_3$ \\
   Fall 1: $\abs{\v L} < \sqrt{2 E I_3} ⇒$ Sphäre und Ellipsoid haben keine gemeinsamen Punkte $⇒$ physikalische unmöglich \\
   Fall 2: $\abs{\v L} = \sqrt{2 E E_3}$ ("einbeschriebene Kugel") $⇒ L = \pm (0, 0, \sqrt{2 E I_3})^T, ω_2 \parallel e_3$ fest. \\
   Fall 3: $\sqrt{2 E I_3} < \abs{\v L} < \sqrt{2 E I_2} ⇒$ Sphäre stößt aus Ellipsoid heraus $⇒ L$ bewegt sich im körperfesten System auf einer geschlossenen Kurve
   $⇒$ kräftefreie Präzession des Kreisels im Laborsystem. \\
   Fall 4: $\abs{\v L} = sqrt(2 E I_2)$ Zwei kreuzende Kurven $L$ sitzt am Kreuzungspunkt (instabil) oder bewegt sich entlang Kurve \\
   Fall 5: $\sqrt{2 E I_2} < \abs{\v L} < \sqrt{2 E I_1}$ "Gurke", nur Enden sind abgeschnitten $⇒ L$ bewegt sich im körperfesten System auf einer geschlossenen Kurve $⇒$ kräftefreie Präzessions des Kreisels im Laborsystem \\
   Fall 6: $\abs{\v L} = \sqrt{2 E I_1}$ ("einbeschriebene Kugel"), wie Fall 2 \\
   Fall 7: $\sqrt{2 E I_1} < \abs{\v L}$ unmöglich \\
   Auch möglich: Geometrische Diskussion im raumfesten System $⇒$ Poinsot-Konstruktion: Ellipse rollt rutschfrei auf Ebene ab.
** Freier Kreisel analytisch
   Euler-Gleichungen
   \begin{align*}
   I_1 \dot ω_1 &= ω_2 ω_3(I_2 - I_3) \\
   I_2 \dot ω_2 &= ω_3 ω_1(I_3 - I_1) \\
   I_3 \dot ω_3 &= ω_1 ω_3(I_1 - I_2)
   \end{align*}
   $⇒$ Falls 2 der 3 Komponenten von $\v ω$ Null sind $⇒ \v ω = \const$. Jetzt zur Vereinfachung sei $I_1 = I_2 < I_3$.
   Definiere $I_0 \equiv I_1 = I_2$ (Beispiel: abgeflachte Kugel, wie etwa Erde).
   \begin{align*}
   I_0 \dot ω_1 &= ω_2 ω_3(I_0 - I_3) \\
   I_0 \dot ω_2 &= -ω_3 ω_1(I_0 - I_3) \\
   I_3 \dot ω_3 &= 0
   \end{align*}
   $ω_3 = \const$. Definiere $α \equiv -ω_3(1 - \frac{I_3}{I_0}) = \const$. Man erhält:
   \begin{align*}
   \dot ω_1 = -α ω_2 \\
   \dot ω_2 = -a ω_1 \\
   ⇒ \ddot ω_1 &= -α^2 ω_1 \\
   ⇒ ω_1 &= A \cos(α t + φ) \\
   \end{align*}
   (ohne Beschränkung der Allgemeinheit $φ = 0$).
   $⇒$ freie Präzession:
   \begin{align*}
   ω_1 &= A\cos α t \\
   ω_2 &= A\sin α t \\
   ω_3 &= \const
   \end{align*}
   $\v ω$ bewegt sich auf Kreis in der $ω_3 = \const$ Ebene. \\
   Konkreter Fall: Erde
   \[-(1 - \frac{I_3}{I_0}) \approx 0.003 \equiv ε\]
   $⇒ α = ω_3 · ε ⇒ T_{\text{Präz}} = \frac{T_{\text{Erde}}}{ε} \sim 300 \text{Tage}$ \\
   $⇒$ Realität ist leider komplizierter, "Chandler-Wobble"
** Schwerer Kreisel (vereinfacht)
   Raumfestes System!
   - $\v S'$: Schwerpunktsachse des Kreisels
   - $φ$: Winkel der Schräglage des Kreisels
   entscheidende Näherung: $\v L' \parallel \v S'$
   \[\v M' = \v r' × \v F' \sim \v S' × \v F'\]
   Also in unserer Näherung: $\v L' \perp \v M'$. Betrachte:
   \[(\v L^{\prime 2})^{·} = 2\v L' \dot{\v L}' \qquad \dot{\v L}' = \v M'\]
   $⇒ (\v L^{\prime 2})^{·} = 0$ beziehungsweise $\abs{\v L'} = \const$
   Weiterhin: $\v F' \parallel \hat e_z' ⇒ \v M'$ liegt in x-y-Ebene. $⇒$ Spitze von $\v L'$ bewegt sich auf Kreis in horizontaler Ebene. \\
   Kreisradius = $\abs{\v L'} \sin φ$, Geschwindigkeit = $\abs{\v M'}$. Periodendauer:
   \[T = \frac{2π R}{v} = \frac{2π \abs{\v L'}\sin φ}{\abs{\v M'}} = \frac{2 π \abs{\v L'}}{m g l}\]
   Anwendung auf Erde: kein fester Punk, stattdessen Drehmoment durch Sonne/Mond und Abflachung der Erde. $⇒$ Präzession der Äquinoktialpunkte (precession of the equinoxes).
   $T \sim \SI{26000}{\year}$
** Eulersche Winkel
   *Ziel*: exakte Analyse der symmetrischen schweren Kreiseln. \\
   *Brauchen*: Parametrisierung der relativen Lage zweier Koordinatensysteme. \\
   $⇒$ Drehe um $\hat e_3' = \hat e_3$ um $φ$, dann Drehe um $\hat e_1$ um $θ$ und dann drehe um $\hat e_3$ um $\dot ψ$
   *Wichtig*: kleine Winkel (als Vektoren) sind bezüglich Drehungen additiv. (folgt aus $ℝ = \mathbb{1} + \mathcal{0}(δ\v φ)$).
   $⇒$ Winkelgeschwindigkeiten addieren sich vektoriell.
   \[⇒ \v ω' = \dot φ \hat e_3' + \dot ψ \hat e_3 + \dot θ \hat e_N\]
** Schwerer Kreisel (exakt)
   Ungestrichenes System - fest verbunden mit Kreisel. ($I_1 = I_2 \equiv I_0$)
   \[\mathcal{L} = \frac{1}{2}[I_0(ω_1^2 + ω_2^2) + I_3ω_3^2] - m g l \cos θ\]
   Wegen Rotationssymmetrie von Schwerefeld und Kreisel sind $φ, ψ$ zyklisch $⇒$ können die Umschreibung von $\{ω_1, ω_2, ω_3\} \to \{φ, ψ, θ, \dot φ, \dot ψ, \dot θ\}$
   bei $φ = ψ = 0$ durchführen: Wir haben (bei $φ = ψ = 0$):
   \begin{align*}
   \hat e_N &= \hat e_1, \hat e_3 = \hat e_3 \cos θ + \hat e_2 \sin θ \\
   \v ω' &= \dot φ(\hat e_3 \cos θ + \hat e_ 2 \sin θ) + \dot ψ \hat e_3 + \dot θ \hat e_1 \\
   &= \hat e_1 \underbrace{\dot θ}_{ω_1} + \hat e_2 \underbrace{(\dot φ \sin θ)}_{ω_2} + \hat e_3 \underbrace{(\dot ψ + \dot φ \cos θ)}_{ω_3} \\
   \mathcal{L} &= \frac{1}{2}(I_0(\dot θ^2 + \dot φ^2 \sin^2 θ) + I_3(\dot ψ + \dot φ \cos θ)^2) - m g l \cos θ
   \end{align*}
   Energie: $E = T + V = \const_1$
   \[\pp{\mathcal{L}}{\dot φ} = L_3' = \const_2\]
   \[\pp{\mathcal{L}}{\dot ψ} = L_3 = \const_3\]
   Auflösen nach $\dot φ, \dot ψ$ und einsetzen in $T + V = E$ gibt:
   \begin{align*}
   E &= \frac{1}{2}I_0 \frac{\dot U^2}{1 - U^2} + V_{eff}(u), \quad u \equiv \cos θ \\
   V_{eff}(u) &= m g l u + \frac{L_3^2}{2 I_3^2} + \frac{(L_3' - L_3 u)^2}{2 I_0 (1 - u^2)} \\
   - \dot U^2 = \frac{2}{I_0}\{(m g l u + \frac{L_3^2}{2 I_3} - E)(1 - U^2) + \frac{(L_3' - L_3U)^2}{2I_0}\}
   \end{align*}
   $⇒$ Kurvendiskussion $⇒$ $u$ oszilliert zwischen $u_{min}, u_{max} ⇒$ $θ$ oszilliert zwischen $θ_{min}, θ_{max}$. Währenddessen schreitet $φ$ unregelmäßig voran:
   \[\dot φ = \frac{L_3' - L_3 \cos θ}{I_0 \sin^2 θ}\]
