#+AUTHOR: Robin Heinemann
#+TITLE: Theoretische Physik II (Hebecker)

# Einleitung: \\
# - Website: www.thphys.uni-heidelberg.de/hebecker/TP2/tp2.html
# - Bartelman Skripte
# Dienstag, 2. Mai: Zetter hier abgehen

#+INCLUDE: "../header.org" :minlevel 1

# Inhalt
# - Analytische Mechanik (2 / 3)
#   - Lagrange und Hamitlon-Formalismus
#     sehr wichtig für: Quantentheorie (Teilchenphysik, Gravitation)
# - Statistik & Thermadynamik (1 / 3)
#   mehr zu TD / S.: in Theo 5: Vuantenstatistik

#+INCLUDE: "lagrange_variation.org" :minlevel 1
#+INCLUDE: "symmetries_conservation_laws.org" :minlevel 1
#+INCLUDE: "inertia_tensor.org" :minlevel 1
#+INCLUDE: "spinning_tops.org" :minlevel 1
#+INCLUDE: "d_alembert.org" :minlevel 1
#+INCLUDE: "hamilton.org" :minlevel 1
#+INCLUDE: "poisson_bracket.org" :minlevel 1
#+INCLUDE: "differential_forms_hamilton.org" :minlevel 1
#+INCLUDE: "canonic_transformation_integrability_chaos.org" :minlevel 1
#+INCLUDE: "oscillations.org" :minlevel 1

* Statistische Machanik: Kinetik
  Wir stellen die peranente ungordnete Bewegung der Teilchen (eines Gases) in den Vordergrund unserer Betrachtungen.
** Verteilungsfunktion im Phasenraum
   Betrachte große Zahl (zunächst nicht wechselwirkender) Teilchen, eingesperrt im Volumen $V$.
   Größenordnung: Avogadro-Konstante: $N \sim 10^{23}$.	Betrachte nun Teilvolumen $Δq^3 · Δ p^3$ im
   Phasenraum. Darin seinen $Δ N$ Teilchen. Es gilt immernoch $Δ N \gg 1$. $⇒$ definiere *Verteilungsfunktion:*
   \[f(\v q, \v p, t) = \lim_{Δ q, Δ p \to 0}  \frac{Δ N}{Δ q^3 · Δ p^3}\]
   Beachte: Der Limes ist nicht mathematisch, $Δq^3, Δp^3$ müssen groß genug bleiben, sodass $Δ N \gg 1$, beziehungweise wir
   betrachten nur Systeme für die $N$ groß genug ist, sodass dieser Kompromiss möglich ist.
   Die Verteilungsfunktion ist anschaulich also die "Teilchen-Dichte" im Phasenraum. Offensichtlich
   \[N = ∫_V \d^3 \v q ∫_{ℝ^3} \d^3 \v p · f(\v q, \v p, t)\]
   Außerdem ist
   \[n(\v q, t) = ∫_{ℝ^3} \d^3 \v p · f(\v q, \v p, t)\]
   die Teilchendichte am Ort $\v q$.

   Uns interessiert die zeitliche Entwicklung von $f$. Jedes Teilchen unterliegt der Hamilton-Dynamik $⇒$ Satz von Liouville.
   $⇒$ Größe der Teilvolumina ändert sich bei Strömen nicht. $⇒$ $f$ ändert sich also auch nicht ($ΔN$ konstant nach Definition von Strömen)
   \[0 = \dd{f}{t} = \pp{f}{t} + (\v ∇_q f) · \dot{\v q} + (\v ∇_p f) · \dot{\v p}\]
   Hier ist $\d f / \d t$ die Ableitung entlang der Phasenraumtrajektorien, analog zur Matrialableitung der Hydrodynamik.
   Kurz: Die Dynamik ist eine inkompressible Stömung im Phasenraum.

   Mit Hamilton folgt:
   \[0 = \pp{f}{t} + (\v ∇_q f) · \frac{\v p}{m} + (\v ∇_p f) · \v P\]
   wobei $\v F$ die äußere Kraft ist, zum Beispiel $\v P = - m \v g$.

   Entscheidender Schritt: zulassen von *Stößen zwischen den Teilchen*. $⇒$ es kommt vor,
   das ein Teilchen auf dem Weg vom Phasenraumvolumen $P V_1$ nach $P V_2$ die (nicht wechselwirkende)
   Trajektroie verlässt, also nie in $P V_2$ ankommt $⇒$ $\d f / \d t \neq 0$ und somit
   \[\pp{f}{t} = - (\v ∇_q f) · \frac{\v p}{m} - (\v ∇_p f) · \v P + \dd{f}{t}\]
   Geben den drei TErmen auf der rechten Seite Namen, um physikalische Bedeutung widerzuspiegeln und
   schreiben die obige Gleichung als
   \[\pp{f}{t} = (\pp{f}{t})_{\text{Diffusion}} + (\pp{f}{t})_{\text{äußere Kraft}} + (\pp{f}{t})_{\text{Collision}}\]
   Die Ausdrücke sind entsprechend der vorigen Gleichung definiert.
   Dies ist in einer sehr allgemeinen Form die *Boltzmann-Gleichung*
** Bolzmann-Gleichung
   Bei der eigentlichen Boltzmann-Gleichung ist er *Kollisionsterm* spezifiziert.
   Dazu zwei wichtige Annahmen:
   - *starke Verdünnung* ($⇒$ nur *binäre Stöße*)
   - *Stoßzahlansatz* $⇒$ Anzahl der Teilchenpaare am Ort $\v q$ (also Volumen im $Δ q^3$) mit
	 Impulsen $\v p_1$ (im Volumen $Δ p^3$) und $\v p_2$ (im Volumen $Δ p^3$) ist proportional zu
	 \[f(\v q, \v p_1, t) · f(\v q, \v p_2, t)\]
   Anschauung: Stöße harter Kugeln (Theo 1). Aber andere kurzreichweitige Wechselwirkungen sind auch zugelassen.
   Jetzt betrachte ersten Beitrag zum Kollisionsterm: *Ein Teilchen* (mit Implus $\v p = \v p_1$)
   stößt ein anderes Teilchen (mit Impuls $\v p_2$) und verschwindet dadurch aus unserem Volumen $Δ^3 Δp^3$. Dies wird quantifiziert durch
   \[(\dd{f}{t})^{(a)}(\v q, \v p_1, t) = - ∫ \d^3 \v p_2 \d^3 \v p_1' \d^3 \v p_2' \tilde τ(\v p_1, \v p_2, \v p_1', \v p_2')·f(\v q, \v p_1, t) · f(\v q, \v p_2, t)\]
   In diesem Ausdruck wird über den Impuls $p_2$ des Partners sowie über die Impulse $p'_{1,2}$
   der Endprodukte. Das Minuszeichen steht für das Verschwinden. Die Funktion $τ$ spezifiziert,
   wei oft die Kollision von Teilchen mit $\v p_1, \v p_2$ zu Teilchen mit Impulsen $\v p_1', \v p_2'$
   führt. Dieser Ausdruck hängt von den Details der Dynamik ab,
   er spezifiziert, was im Zentrum einer Kollision wirklich passiert. Man spricht hier von
   *collision kernel* oder *Integrationskern* $τ$, der sich allerdings noch geringsfügig von unserem $\tilde τ$ unterscheidet.
** Die Delta-Funktion
   Um diesen Unterschie zwischen $τ$ und $\tilde τ$ konkretisieren zu können, brauchen wir
   zumindest grobe Vorstellung von der sogenannten $δ$ -*Funktion*:
   Sei dazu die Funktion $δ_ε(x)$ als ein Rechteck von $-ε$ nach $ε$ mit der Höhe $1/(2ε)$.
   Diese ist speziell so gebaut, dass
   \[∫ δ_ε(x) \d x = 1 \quad \lim_{ε \to 0} δ_ε, ∀ x \neq 0\]
   Diese spezielle "Kasteform" haben wir zwecks einfacherer Rechnung gewählt - sie ist unwesentlich.
   Wir hätten zum Beispiel ebeso eine entsprechend normierte Gaußkurve wählen können.
   $⇒$ eine (sehr grobe!) Definition der $δ$ Funktion ist nun
   \[δ(x) = \lim_{ε \to 0} δ_ε(x)\]
   mit einem der obigen $δ_ε$. Etwas besser ist zu sagen, dass $δ(x)$ durch die beiden Bedingungen
   \[∫ δ(x) \d x = 1 \quad δ(x) = 0, ∀ x \neq 0\]
   definiert, wobei man nur Ausdrücke mit $δ(x)$ zulässt, die aufgrund dieser beiden Bedingungen eindeutig auswertbar sind.
   Noch besser ist es sich $δ$ als Funktional vorzustellen,
   \[f ↦ ∫ f(x) δ(x) \d x = f(0)\]
   wobei das Integral rechts nur eine bequeme Schreibweise ist - der eigentliche Gehalt ist die Zuordnung $f \to f(x)$.
   Für $δ(x - x_0)$ erhält man dann:
   \[∫f(x) δ(x - x_0) \d x = f(x_0)\]
   Weiterhin
   \[δ^3(\v x) = δ(x^1) · δ(x^2) · δ(x^3)\]
   wenn wir zum Beispiel mit drei Variablen gleichzeitug arbeiten.
\subsection*{Bolzmann-Gleichung (Fortsetzung)}
   Jetzt können wir die beim elastischen Stoß stets geltende Energie- und Impulserhaltung durch
   \[δ^4(P_f - P_i) \equiv δ(E_f - E_i)δ^3(\v p_f - \v p_i)\]
   erzwingen, wobei
   \[\v p_i \equiv \v p_1 + \v p_2, \quad \v p_f \equiv \v p_1' + \v p_2'\]
   und
   \[E_i \equiv E_1 + E_2 = \frac{\v p_1^2}{2m} + \frac{\v p_2^2}{2m}, \quad E_f \equiv E_1' + E_2' = \frac{\v p_1^{\prime 2}}{2m} + \frac{\v p_2^{\prime 2}}{2m}\]
   wobei Indizes $i / f$ für "initial" und "final" stehen.
   Für "Teil a" des Stohterms kann man nun schreiben
   \[(\dd{f_1}{t})^{(a)}(\v q, \v p_1, t) = -∫ \d^3 \v p_2 \d^3 \v p_1' \d^3 \v p_2' δ^4(P_f - P_i) · τ(\v p_1, \v p_2, \v p_1', \v p_2') · f(\v q, \v p_1, t) f(\v q, \v p_2, t)\]
   Dabei haben wir von der sehr wichtigen Größe, dem Integrationskern oder *Collision kernel*, den
   prozessunabhängigen Energie- und Impulserhaltungs Constraint in Form der $δ^4$ -Funktion abgetrennt.

   Es ist jetzt offesichtlich wie "Teil b" aussieht, welcher die Streuung eines "fremden"
   Teilchen in "unser" Phasenraumvolumen $Δ q^3 Δp^3$ beschreibt:
   \[(\dd{f_1}{t})^{(b)} = + ∫ \d^3 \v p_2 \d^3 \v p_1' \d^3 \v p_2' δ^4(P_f - P_i) · τ(\v p_1', \v p_2', \v p_1, \v p_2) · f(\v q, \v p_1', t) f(\v q, \v p_2', t)\]
   Die relevanten Wahrscheinlichkeiten sind jetzt durch die Phasenraum-Dichten bei Impulsen $p_1', p_2'$ gegeben
   und der dynamische Prozess ist schlicht die Streudynamik im Besonderen *zeitumkehrinvariant* ist,
   und zwar sowohl klassisch als auch quantermechanisch:
   \[τ(\v p_1', \v p_2', \v p_1, \v p_2) = τ(\v p_1, \v p_2, \v p_1', \v p_2')\]
   Damit folgt
   \[(\pp{f_1}{t})_{\text{Collision}} = ∫ \d^3 \v p_2 \d^3 \v p_1' \d^3 \v p_2' · δ^4(P_f - P_i) · τ(\v p_1, \v p_2, \v p_1', \v p_2')(f(\v q, \v q_1', t)f(\v q, \v p_2', t) - f(\v q, \v p_1, t)f(\v q, \v p_2, t))\]
   Eingesetzt in obige Formel für die Boltzmanngleichung liefert dies die allgemeine Formulierung.
   Man kann nun (mit einiger rechnerischen Mühen aber ohne neue Ideen) den Integrationskern durch
   den Wirkungsquerschnitt ausdrücken. Wir geben das Resultat ohne Beweis an,
   \[(\pp{f}{t})_{\text{Collision}} = ∫ \d^3 \v p_2 ∫ \d Ω \abs{\v v_1 - \v v_2} \dd{σ}{Ω}(\v p_1, \v p_2, Ω)(f_1'f_2' - f_1 f_2)\]
   wobei $\d Ω$ die Integration über die Richtung der Streuprodukte im Schwerpunkssystem bezeichnet und wir für die
   relevante Kombination der Verteilungsfunktionen eine hoffentlich selbsterklärende Kurzform gewählt haben.
   Mehr Details finden sich zum Beispiel in Fasano / Marmi. Die Boltzmann-Gleichung ist also
   \[\pp{f}{t} = (\pp{f}{t})_{\text{Diffusion}} + (\pp{f}{t})_{\text{äußere Kraft}} + (\pp{f}{t})_{\text{Collision}}\]
   Mit obiger Formel für $(\partial f / \partial t)_{\text{Collision}}$.
** Die Maxwell-Bolzmann-Verteilung
   Zur Vereinfachung sei nun die äußer Kraft Null, $\v F = 0$, und die Dichte im Konfigurationsraum homogen,
   $f(\v q, \v p, t) = f(\v p, t)$. Es folgt
   \[\pp{f(\v p_1, t)}{t} = ∫_{\v p_2, \v p_1', \v p_2'} δ^4(P_f - P_i) · τ · (f_1' f_2' - f_1 f_2)\]
   Wir sehen, dass die Bedingung
   \[f_1 f_2 = f_1' f_2'\]
   *hinreichend* für das Vorliegen von *Gleichgewicht* (also Zeitunabhängigkeit von $f$) ist.
   Die *Notwendigkeit* dieser Bedingung folgt aus *Bolzmanns* H- *Theorem*. Dazu definiert man
   das Funktional
   \[H[f] \equiv ∫ \d^3 \v p · f(\v p) \ln(f(\v p))\]
   Wenn nun sich $f$ zeitlich gemäß der ersten Gleichung entwickelt, so kann man zeigen, dass
   \[\dd{H}{t} \leq 0\]
   und sogar
   \[\dd{H}{t} = 0 ⇔ f_1' f_2' = f_1 f_2\]
   Herleitung, welche im wesentlichen nur aus algebraischen Manipulationen besteht findet sich
   zum Beispiel in Fasano/Marmi, Huang. $H$ ist eng mit der Entropie und das $H$ -Theorem mit dem 2. Hauptsatz der
   Thermodynamik verbunden. Für uns impliziert es vor allem, dass die Bedingung $f_1' f_2' - f_1 f_2 = 0$ notwendig für das Vorliegen von Gleichgewicht ist.
   Eine äquivalente Schreibweise der Gleichgewichtsbedingung ist
   \[\ln f(\v p_1) + \ln f(\v p_2) = \ln f(\v p_1') + \ln f(\v p_2')\]
   Dies hat die Form eines Erhaltungssatzes für $2 \to 2$ -Prozesse (man denke zum Beispiel an $E_1 + E_2 = E_1' + E_2'$). Wenn wir also
   eine Erhaltungsgröhe $χ(\v p)$ kennen und $f$ durch
   \[\ln f(\v p) \equiv \const · χ(\v p)\]
   definieren, erhalten wir stets eine Gleichgewichtsverteilung. Der allgemeine Ansatz für $f$ ist also
   \[\ln f(\v p) = \sum_{i} χ_i(\v p)\]
   wobei $χ_i$ über alle Erhaltungsgrößen läuft. Mögliche Erhaltungsgrößen: $1, \v p, E = \v p^2 /(2m)$
   \[⇒ \ln f = a + b p_1 + c p_2 + d p_3 + e \frac{\v p^2}{2m}\]
   Dies kann man umschreiben zu
   \begin{align*}
   \ln f &= -A(\v p - \v p_0)^2 + \ln c \\
   f(\v p) &= C e^{- A(\v p - \v p_0)^2}
   \end{align*}
   Man sieht: $\v p_0$ ist Mittelwert des Impulses.
** Mittelwert
   Messen eine Größe $F$ mehrmals ($N$ Mal).
   #+begin_defn latex
   \[\angl{F} = \frac{1}{N} \sum_{i = 1}^{N} F(i) = \frac{\sum_{i = 1}^{N} F(i)}{\sum_{i = 1}^{N} 1}\]
   #+end_defn
   jetzt für Gas: Meßgröße: $F = F(\v q, \v p)$, außerdem: Verteilungsfunktion $f(\v q, \v p)$
   \[\angl{F} = \frac{1}{N} \sum_{i =¹}^{N} F(\v q_i, \v p_i) = \frac{1}{N} \sum_{α} F(\v q_α, \v p_α) f(\v q_α · \v p_α) (Δq^3 Δ p^3)_α\]
   (Summe über kleine Zellen $α$). Grenzwert kleiner Zellen:
   \[\angl{F} = \frac{1}{N} ∫ \d^3 \v p \d^3 \v q f(\v q, \v p) F(\v q, \v p) = \frac{∫ \d^3 \v p \d^3 \v q f(\v q, \v p) F(\v q, \v p)}{∫\d^3 \v p \d^3 \v q f(\v q, \v p)}\]
   $F, f$ unabhängig von $\v q$:
   \[\angl{F} = \frac{∫ \d^3 \v p f(\v p) F(\v p)}{∫ \d^3 \v p f(\v p)}\]
\subsection*{Maxwell-Bolzmann-Verteilung - Fortsetzung}
   Wähle Observablen $\{F_1, F_2, F_3\} \equiv \v P = \v p$. Behauptung: $\angl{\v F} = \v p_0$. (Nachprüfen für erste Komponente reicht)
   \[\angl{p_1} = \frac{∫ \d^3 \v p p_1 C e^{-A(\v p - \v p_0)^2}}{∫ \d^3 \v p C e^{- A(\v p - \v p_0)^2}}\]
   1. $\d^3 \v p = \d p_1 \d p_2 \d p_3$
   2. $(\v p - \v p_0)^2 = (p_1 - p_{0,1})^2 + \dots$
   Zur Vereinfachung: Boost ins Ruhesystem das Gases $\to \v p_0 = 0$ ohne Beschränkung der Allgemeinheit.
   Betrachte jetzt Observable
   \[F(\v p) = \frac{\v p^2}{2m}, ε \angl{\frac{\v p^2}{2m}} = \frac{3}{4 A m}\]
   Definiere Temperatur $T$:
   \[\frac{1}{2} k T \equiv \frac{ε}{n_f}\]
   - $k = k_B$ - Konstante
   - $n_f$: Zahl der Freiheitsgrade
   \[⇒ f(\v p) = C e^{- A \v p^2} = C e^{-(\v p^2 / (2m) / (k T))} = C e^{- \frac{E(\v p)}{k T}}\]
   außerdem:
   \begin{align*}
   N &= ∫ \d^3 \v p \d^3 \v q f(\v p) = V ∫ \d^3 \v p f(\v p) \\
   n &= \frac{N}{V} = ∫ \d^3 \v p f(\v p) \\
   ⇒ f(\v p) &= \frac{n}{(2 π m k T)^{3 / 2}} e^{- E(\v p) / (k T)}
   \end{align*}
** Maxwell-Bolztmann-Verteilung mit konservativen äußeren Kräften
   Wir lassen eine konservative äußere Kraft zu:
   \[\v F(\v q) = - \v ∇_q V(\v q)\]
   Ansatz:
   \[f(\v q, \v p) = f_0(\v p) g(\v q)\]
   $f 0$ sei das eben graduierte $f(\v p)$. Es gilt:
   \[\pp{f_1}{t} = - \frac{\v p_1}{m} \v ∇_q f_1 - \v F · \v ∇_p f_1 + ∫ δ^4 (\dots) τ(f_1' f_2' - f_1 f_2)\]
   (Notation: $f_1' t f(\v p_1', \v q_1) \equiv f(\v p_1', \v q)$). Kollisions-Term bleibt mit unserem Ansatz Null. DAs liegt an der Stillschweigenden Annahme, das die mittlere frei Weglänge klein ist gegen typische $\v q$ -Skala.
   Gegeben:
   \[0 = - \v p_m \v ∇_q(f_0(\v p) g(\v q)) + (\v ∇_q V) · \v ∇_p(f_0(\v p) g(\v p))\]
   Nebenrechnung:
   \[\v ∇_p f_0(\v p) = - \frac{\v p}{m k T} f_0(\v p)\]
   \begin{align*}
   ⇒ 0 &= - \frac{\v p}{m} · (\v ∇_q g(\v q)) f_0(\v p) - f_0(\v p) g(\v q) \frac{\v p}{m k T}(\v ∇_q V) \\
   ⇒ \frac{\v ∇ g}{g} &= \frac{\v ∇ V}{k T} \\
   ⇒ \v ∇ (\ln g) &= - \v ∇ (\frac{V}{k T}) \\
   ⇒ g &= \const x e^{- \frac{V}{kT}} \\
   ⇒ f(\v q, \v p) &= C e^{-E(\v q, \v p)/ (k T)} \\
   \intertext{mit}
   E(\v q, \v p) &\equiv \frac{p^2}{2 m} + V(\v q) \\
   \intertext{$C$ ist definiert durch}
   N &= ∫_{Vol.} \d^3 \v q ∫_{ℝ^3} \d^3 \v p f
   \end{align*}
** Diffusion
   Betrachte Fläche $A$, Zahl der Teilchen, die von links kommen und $Δ A$ in Zeit $Δ t$ durchfliegen:
   \[N_L \sim \frac{1}{6} n(x, y_0 - Δ y, z) Δ A Δ y\]
   $Δ A · Δ y$: Volumen des relevanten Quaders links von der Wand.
   Dies	macht nur Sinn, wenn
   \[v \equiv \angl{\abs{\v v}} \sim \frac{Δ y}{Δ t}\]
   $⇒$ Stromdichte:
   \begin{align*}
   j_y &= \frac{N_L - N_R}{Δ A Δ t} \sim \frac{1}{6} \frac{Δ y}{Δ t}(n(y_0 - Δ y) - n(y_0 + Δ y)) \\
   &\sim \frac{v}{6}(\pp{n}{y})(-2 Δ y)
   \end{align*}
   Sei $λ$ die mittlere freie Weglänge. Falls wir $Δ y \ll λ$ wählen, unterschätzen wir $j_q$ aufgrund
   der aus größeren	Entfernung kommenden Teilchen, die wir schlicht vergessen. Falls wir
   $Δ y \gg λ$ wählen, überschätzen wir $j_y$, da viele Teilchen zwischenzeitlich stoßen
   und $y_0$ nicht erreichen. Also
   \[Δ y \sim λ ⇒ j_y \sim \frac{v λ}{3} \pp{n}{y}\]
   Analog für $j_x, j_z ⇒$
   \[\v j = - D \v ∇ n\]
   ($D \sim v λ / 3$ "Diffusionskonstante"). Da Teilchen nicht verloren gehen, gilt die Kontinuitätsgleichnug
   \[\pp{n}{t} = - \v ∇ · \v j\]
   (vergleiche Hydrodynamik, wo $n \to ρ$ und $\v j \to ρ \v v$)
   $\v j$ einsetzen $⇒$ Diffusionsgleichnung:
   \[\pp{n(\v x, t)}{t} = D Δ n(\v x, t)\]
   ($Δ$: Laplace-Operator)
   Dies ist eine partielle Differentialgleichung. Eine schöne und anschauliche Lösung der obigen partiellen Differentialgleichung ist
   \[n(\v x, t) = \frac{N}{(4 π D t)^{3/2}} e^{-\frac{\v x^2}{4 D t}}\]
   $⇒$ breitlaufende 3D Gaußkurve! \\
   Kommentar: Wir bringen keine ordentlihce Herleitung der Diffusion aus der Bolzmann-Gleichung. Wir wollen aber wenigstens sehen, dass der obige "Diffusionsterm" das richtige tut (bei $\v F = 0$, Kollisionsterm = 0). Also:
   \begin{align*}
   \pp{f}{t} &\sim - \pp{\v p}{m} \v ∇_q f, n(\v q) = ∫ \d^3 \v p f(\v q, \v p) \\
   ⇒ \pp{n(\v q)}{t} &\sim \v ∇_q \underbrace{∫ \d^3 \v p f(\v q, \v p) \frac{\v p}{m}}_{\angl{\v v} n = \v j} \sim \v ∇_q \v j
   \end{align*}
   In der Tat: Änderung von $n$ durch $\v ∇_q \v j$
* Thermodynamische Gesamtheiten
  Thermodynamische Gesamtheiten: Ensembles = Gibbs stes
** Der $Γ$ -Raum
   Bisher haben wir unser (nur schwach wechselwirkendes, verdünntes) Gas beschrieben durch Verteilungsfunkion $f(\v q, \v p)$ im 1-Teilchen Phasenraum (der $μ$ -Raum) beschrieben.
   Jetzt: Wechsel zum $N$ -Teilchen-Phasenraum (der $Γ$ -Raum). Dieser Raum ist $6N$ -dimensional mit Koordianten: $\v q_1, \dots, \v q_N, \v p_1, \dots, \v p_N$.
   Ein bestimmter Zustand unseres gesamten Gases entspricht nur einem einzigen Punkt im $Γ$ -Raum! (Vergleiche $μ$ -Raum: $N$ Punkte in $6$ Dimensionen, $Γ$ -Raum: 1 Punkt in $6N$ Dimensionen).
   Zur Erinnerung: $N \sim 10^{23}$ ud die Dynamik im $Γ$ -Raum schließt die freie Bewegung und die Stöße aller $\sim 10^{23}$ Teilchen ein. Eine explizite Kenntnis des relevanten Punktes im $Γ$ -Raum
   und dessen Bewegung ist aussichtslos. Uns interessiert der makroskopische Zustand eines Systems mit vielen Freiheitsgraden. Wir denken weiter primär an unser Gas in einem Kasten, aber andere Systeme,
   zum Beispiel Festkörper sind auch beschrieben.
   #+ATTR_LATEX: :options [Makroskopische Zustand]
   #+begin_defn latex
   Gesamtheit aller Mikrozustände, die zu einem bestimmten Makrozustand gehören (durch beschränkte Präzision unserer Beobachtung).
   #+end_defn
** Wahrscheinlichkeit
   Ereignisraum $M$ (Menge aller Elemetarereignisse)
   #+ATTR_LATEX: :options [2-facher Münzwurf]
   #+begin_ex latex
   \[M = \{WW, WZ, ZW, ZZ\}\]
   Ergbnis:
   1. $\{WW, ZZ\}$
   2. unmögliches Ereignis: $\emptyset$
   #+end_ex
   Wahrscheinlichkeit:
   Anschaulich sagt die Wahrscheinlichkeit etwas über unserer Erwartung bezüglich des Ausgangs eines Experimentes (des Eintreten eines Ereignisses) aus. Etwas genauer könnte man die
   relative Häufigkeit eines Ereignisses bei vielfacher Wiederholung ("limiting frequency") definieren:
   \[P(\{WW, ZZ\}) = \lim_{N \to ∞} \frac{\# (WW \text{ oder } ZZ)}{N}\]
   #+ATTR_LATEX: :options [Wahrscheinlichkeit]
   #+begin_defn latex
   \[P: A ↦ P(A) ∈ ℝ\]
   Kolomogorov-Axiome:
   1. $P(A) \geq 0 A A ⊂ M$
   2. $P(M) = 1$
   3. $\{A_i, i ∈ I\}, A_i ∩ A_j = \emptyset ∀ i \neq j$
	  \[⇒ P(∪_{i ∈ I} A_i) = \sum_{i ∈ I} P(A_i)\]
   #+end_defn
** Maß
   Menge $M \neq \emptyset, \mathcal{A}$ Familie von Untermengen von $M$. $\mathcal{A}$ heißt $σ$ -Algebra falls
   1. $A ⊂ \mathcal{A} ⇒ M \setminus A ∈ \mathcal{A}$
   2. $∀ \{A_i\}, i ∈ ℕ, A_i ∈ \mathcal{A}$ gilt
	  \[∪_{i ∈ ℕ} A_i ∈ \mathcal{A}\]
   Ein Maß $μ: \mathcal{A} \to [0, ∞]$ hat die Eigenschaften
   1. $μ(\emptyset) = 0$
   2. $μ(∪_{i ∈ ℕ} A_i) = \sum_{i ∈ ℕ} μ(A_i)$ ($A_i$ disjunkt)
   $(M, \mathcal{A}, μ)$ nennt man einen Wahrschenlichkeitsraum falls $μ(M) = 1$.
   Wir haben meistens $M = ℝ$
   \[P([x_1, x_2]) = ∫_{x_1}^{x_2} p(x) \d x\]
   $p$: Wahrscheinlichkeitsdichte. Für Phasenraum $M = ℝ^{6N}, O ⊂ ℝ^{6N}$
   \[P(O) = ∫_A \d^{6N} \v ξ p(\v ξ)\]
   $M = Γ = ℝ^{6N}, P(O) = ∫_d^{6N} + p(\v ξ)$ mit $\v ξ = (q_1, \dots, p_{3N})$. Man nennt $M$ den Raum der Elementarereignisse = Ergebisraum.
** Mikrokanonisches Ensemble
   Ensemble: Ansammlung verschiedener Möglichkeiten, Objekte, Hier: Ereignisraum, Ergebnisraum. Zum Beispiel: alle Mikrozustände, die zu einem Makrozustand gehören.
   Betrachte alle Mikrozustände mit Energie $E = E_{tot} = \const$
   Gleichwahrschenlichkeitsannahme:
   Alle Zellen kompatibel mit $E_{tot}$ gleich wahrscheinlich. Wahrscheinlichkeitsdichte:
   \[ρ(q_1, \dots, q_{3N}, p_1, \dots, p_{3N}) = ρ(p_1, \dots, 3N) = \const δ(E - \sum_{i = 1}^{3N} \frac{p_i^2}{2m})\]
   Messunsicherheit: $H ∈ [E - Δ E, E]$. Für hinreichend kleine $Δ E$ ist $ρ = \const$ in einer 3N-dimensionalen Kugelschale.
   \[⇒ ∫_Γ \d^{6N} \v ξ ρ(\v ξ) = V^N ∫ \d^{3N} \v p ρ(\v p) = V^N \const V_{\text{Kugelschale}} = 1\]
** Bolzmannverteilung als wahrscheinlichste Verteilung
   Verbindung zu $f(\v q, \v p)$ und Wahrscheinlichkeitsdichten auf $N$ -Teilhen Phasenräume. Betrache Phasenräume aus Zellen aufgebaut mit diskrete Werte für $\v p, \v q$
   gegeben $f(\v q, \v p) \estimates O[f]$ in $Γ$ -Raum $⇒$ Volumen $Ω[f]$.
   Toy-model $f(\v q, \v p) \to f(x)$, $x$ nimmt zwei Werte an
   \[f(x) = \frac{1}{Δ x}\]
   Nummeriere Zellen im $μ$ -Raum. $k$ Stück $(k \gg 1), ω = Δq^2 Δp^2$
   \[n_i = ∫_{\text{Zelle i}} \d^3 \v p \d^3 \v q f(\v q, \v p) = f_i ω\]
   \[Ω[f] = ω^N \frac{N!}{n_1! n_2! \dots n_k!}\]
   (Anzahl Möglichkeiten $N$ Teilchen auf $k$ Zellen zu verteilen, sodass $n_i$ in Zelle $i$ sind)
   Die Wahrschenlichkeit ist dann
   \begin{align*}
   P[f] &= ∫_Γ \d^{6N} \v ξ ρ_f(\v ξ) \\
   \intertext{Wir wollen $Ω[f]$ (beziehungsweise $\ln Ω[f]$) maximieren. Also suche Maximum von}
   \ln(Ω) &= \ln N! - \sum_{i = 1}^{k} \ln(n_i!) + \const \\
   \intertext{bezüglich der $\{n_i\}$ mit Nebenbedingungen}
   \sum_{i} n_i = N, \sum_{i} n_i E_i = E
   \end{align*}
   Nutze Striling-Formel: für $n \gg 1$
   \[\ln n! \approx n(\ln(n) - 1)\]
   Benutze Lagrange-Multiplikatoren $α, β$:
   \[⇒ δ_{α,β, \{n_i\}} \{- \sum_{i} n_i(\ln n_i - 1) - α (\sum_{i} n_i - N) - β(\sum_{i} n_i E_i - E)\} = 0\]
   \begin{align*}
   \partial_α \{\dots\} &= 0, \partial β \{\dots\} = 0, \partial n_{j} \{\dots\} = 0 \\
   ⇒ - \ln n_j - 1 + n_j \frac{1}{n_j} - α - β E_j &= 0 \\
   ⇒ n_j &= e^{-α - β E_i} \\
   ⇒ f_i &= \frac{1}{ω} e^{-α - β E_i}
   \end{align*}
** Kanonisches Ensemble
   Jetzt: Energie *nicht* fixiert. System im Gleichgewicht mit zeiwten, viel größerem System (Resevoir) mit Temperatur $T$. \\
   Konkret: Gas, fixiert: $V, N, T$. \\
   Betrachte: Obervable $F = F(\v p)$ des Systems. System: $p = (p_1, \dots, p_{3N})$. Reservoir: $\v P(P_1, \dots, P_{3M})$, $M \gg N \gg 1$.
   \[\angl{F} = C ∫ \d^{3N} \v p ∫ \d^{3M} \v P F(\v p) δ(E_{tot} - H_1(\v p) - H_2(\v P))\]
   \begin{align*}
   H_1(\v p) &= \sum_{i = 1}^{3N} \frac{p_i^3}{2m} \\
   H_2(\v P) &= \sum_{i = 1}^{3N} \frac{P_i^3}{2m} \\
   \end{align*}
   Nebenrechnung: $\v p$ sei fest, demnach $E_1 = H_1(\v p)$ fest. Integration über $\v P$ ausführen:
   \[I \equiv ∫ \d^{3N} \v P δ(E_{tot} - E_1 - H_2(\v P))\]
   $δ$ -Funktion erzwingt:
   \[\v P^2 = \abs{\v P}^2 = 2m(E_{tot} - E_1)\]
   $I$ enpspricht der Oberfläche einer $3N$ dimensionalen Sphäre von Radius $R = \sqrt{2m(E_{tot} - E_1)}$. Aus Dimensionsgründen:
   $I \sim R^{3M - 1}$ $3M \gg 1$ $⇒$ für uns ok: $I \sim R^{3M}$.
   \[I \sim R^{3M} \sim (E_{tot} - E_1)^{3M/2} \sim (1 - \frac{E_1}{E_{tot}})^{3M/2}\]
   (uns interessiert nur die $E_1$ Abhängigkeit). Außerdem:	$E_1 \ll E_{tot}$.
   \[(1 - \frac{E_1}{E_{tot}})^{3M/2} = \exp(\frac{3M}{2} \ln(1 - \frac{E_1}{E_{tot}})) = \exp(\frac{3M}{2}(-\frac{E_1}{E_{tot}} - \underarrow[\frac{1}{2}(\frac{E_1}{E_{tot}})^2]{irrelevant} + \dots))\]
   Grenzwert:
   \[M \to ∞, E_{tot} \to ∞, \frac{E_{tot}}{3M} = \frac{k T}{2} = \const\]
   zweiter Summand:
   \[M(\frac{E_1}{E_{tot}})^2 = \frac{1}{M}(\frac{E_1}{E_{tot} / M})^2 \to 0\]
   \[⇒ I \sim \exp(-\frac{E_1}{kT})\]
   $I$ ist gerade die Bolzmann-Verteilung.
   \[⇒ \angl{F} \sim ∫ \d^{3N} \v p F(\v p) \exp(\frac{-H_1(\v p)}{k T})\]
   allgemein:
   \[\angl{F} = \frac{1}{Z} ∫_V \d^{3N} \v q ∫ \d^{3N} \v p F(\v p, \v q) \exp(\frac{-H(\v p, \v q)}{kT})\]
   Weil $\angl{1} = 1$ folgt:
   \[Z = Z(T, V) = ∫_V \d^{3N} \v q ∫ \d^{3N} \v p \exp(\frac{-H(\v p, \v q)}{kT})\]
   $Z(T, V)$: "Zustandssumme". Zum Namen: In Quantenmachanik: Nur ein Zustand pro Phasenraumzelle der Größe $h^{3N}$ (planksches Wirkungsquantum).
   \[∫ \frac{\d^{3N} \v q \d^{3N} \v p}{h^{3N}} = \sum_{\text{alle Zustände}}\]
** Vergleich von mikrakanonischen und kanonischen Ensemble
   Wahrscheinlichkeitsverteilung auf $Γ$ parametrisiert durch $p_1, \dots, p_{3N}, q_1, \dots, q_{3N}$.
   \[ρ_{mikrok} \sim δ(E - H(\v p, \v q))\]
   \[ρ_{kanon} \sim \exp(\frac{-H(\v p, \v q)}{kT})\]
   Bei großen Systemen: beide äquivalent! Unter $\d^{3N} \v p$ -Integral:
   \[∫ \d^{3N} \v p \dots \sim ∫ \abs{\v p}^{3N - 1} \d \abs{\v p} \dots \sim ∫ E^{3N/2} \d E\]
   Jetzt mit Verteilungsfunktion:
   \[∫ ρ_{kan.} \d^{3N} \v p \sim ∫ \d E E^{3N/2} e^{-E/kT} \sim ∫ \d E e^{-g(E)}\]
   mit
   \[g(E) \equiv \frac{E}{kT} - \frac{3N}{2} \ln(E)\]
   $g(E)$ hit ein extrem scharfes Minimum bei $E_{max} = 3N k T / 2$.
   1. "$E_{max}$" weil dort $e^{-g(E)}$ maximal wird.
   2. "Extrem scharf" heißt:
	  \[g(E_{max} + ΔE) - g(E_{max}) = 1 ⇒ ΔE/E \ll 1\]
   3. Selbst nachprüfen: $⇒$ können $e^{-g}$ nähern:
	  \[e^{-g(E)} \sim e^{-α(E - E_{max})^2}\]
	  (Taylor) Für alle praktischen Zwecke ist das so gut wie $δ(E_{max} - E)$
   $⇒$ kanonisches Ensemble enpspricht mikrokanonischen Ensemble mit Energie $E = E_{max} = 3Nk T / 2$. Intuitiver Grund:
   Volumen einer hochdimensionalen Kugel "sitzt unter der Oberfläche".
* Entropie und thermodynamische Potentiale
** Erwartungswerte in gekoppelten Systemen
   \[\angl{F} = ∫_{V(1)} \d^{3N} q ∫\d^{3N} p F(H_1(\v q, \v p)) ∫_{V(2)} \d^{3N} Q ∫\d^{3N} P δ(E_{tot} - H_1(\v q, \v p) - H_2(\v Q, \v P))\]
   Kurznotation:
   \[∫_{V(1)} \d^{3N} q ∫ \d^{3N} p \equiv ∫_{q,p}\]
   \begin{align*}
   \angl{F} &\sim ∫_{q, p} F(H_1) ∫_{Q, P} δ(E_{tot} - H_1 - H_2) \\
   \angl{F} &\sim ∫ \d E ∫_{q, p} F(H_1) δ(E - H_1) ∫_{Q, P} δ(E_{tot} - H_1 - H_2) \\
   \angl{F} &\sim ∫ \d E F(E) ∫_{q, p} δ(E - H_1) ∫_{Q, P} δ(E_{tot} - E - H_2) \\
   \end{align*}
   Definiere: Zustandsdichte eines Systems mit Variablen $q, p$
   \[ω(E) \equiv ∫_{q, p} δ(E - H(q, p))\]
   \[\angl{F} \sim ∫ \d E F(E) ω_1(E) ω_2(E_{tot} - E)\]
** Zustandsdichte
   Phasenraumvolumen $Σ(E)$ für Energie $< E$.
   \begin{align*}
   Σ(E) &= ∫_V \d^{3N} \v q ∫_{ℝ^{3N}} \v p θ(E - H(\v q, \v p)) \\
   θ(x) &= \begin{cases} 0 & x \leq 0 \\ 1 & x > 0\end{cases}
   \end{align*}
   "$θ$" -Funktion, "Heavyside Step Funktion". \\
   Zustandsdichte: $ω(E) \equiv \partial Σ(E) / \partial E$
   \[⇒ ∫_{q,p} δ(E - H(\v q, \v p))\]
   weil:
   \[\dd{θ(x)}{x} = δ(x)\]
   Genauer: $δ$ -Funktion:
   \[∫_{-a}^{a} δ(x) \d x = 1, δ(x) = 0 ∀ x \neq 0\]
   \[⇒ ∫_{-a}^{a} θ'(x) \d x = θ(x)\mid_{-a}^{a} = 1 - 0 = 1 \checkmark\]
   Weiterer Begriff: Phasenrauvolumen für Energieintervall $E \to E + Δ E$: Zustandszahl:
   \[Γ(E): Σ(E + Δ E) - Σ(E) \simeq ω(E) Δ E\]
** Entropie
   $\angl{F} \sim ∫ \d E \dots$ bekommt Hauptbeitrag aus dem Bereich wo $ω_1 · ω_2$ maximal wird. $⇒$ Bereich wo $Γ_1 · Γ_2$ maximal wird $⇒$ wo $\ln(Γ_1) + \ln(Γ_2)$ maximal wird
   $⇒$ Ableitung nach $E$ verschwindet. $⇒$ Es muss gelten:
   \begin{align*}
   \partial_{E_1} \ln Γ(E_1) &= - \partial_{E_1} \ln Γ(E_{tot} - E_1) \\
   ⇒ \partial_{E_1} \ln Γ(E_1) &= - \partial_{E_2} \ln Γ(E_2) \\
   \end{align*}
   Dies ist die Gleichgewichts-Bedingung ($\equiv$ Energieaufteilung). $⇒$ legt Definition nahe:
   \[S(E, V) \equiv k \ln Γ(E, V)\]
   Gleichgewichts-Bedingung:
   \[\partial_{E_1} S_1(E_1) = \partial_{E_2} S_2(E_2)\]
   $⇒$ Definition von $T$:
   \[\frac{1}{T} \equiv \pp{S(E,V)}{E}\]
   äquivalent: $S = k \ln ω, S = k \ln Σ$
   $⇒$ Entropie $\sim$ $\ln(\text{Zahl der Zustände})$. Konsistenzcheck:
   \begin{align*}
   S &= k \ln(E^{3N/2}) \\
   ⇒ \frac{1}{T} &= \pp{S}{E} = k \partial_E \ln E^{3N/2} = k \frac{3N}{2} \frac{1}{E} \\
   ⇒ \frac{E}{3N} &= \frac{kT}{2} \checkmark
   \end{align*}
** Die innere Enegie als thermodynamisches Potential das mikrokanonischen Ensembles
   Können $S(E, V)$ berechnen. Wir haben also:
   \[\d S = \pp{S}{E} \d E + \pp{S}{V} \d V = \frac{\d E}{T} + \pp{S}{V} \d V\]
   auch:
   \[\d E = T \d S - T \pp{S}{V} \d V\]
   ($E \equiv$ innere Energie, auch "$U$")
   #+ATTR_LATEX: :options [1. Hauptsatz der Thermodynamik]
   #+begin_thm latex
   \[\d E = \d Q - p \d V\]
   #+end_thm
   Naheliegend:
   \[\d Q = T \d S,\quad \pp{S}{V} = \frac{1}{T} p\]
   Zur Begründung: Berechne $\partial S / \partial V$
   \begin{align*}
   - \pp{S}{V} &= k \pp{}{V} \ln Σ(E, V) = -k \pp{}{V} \ln(∫_Γ θ(E - H)) \\
   &= -k \frac{∫_Γ \partial θ(E - H)}{∫_Γ θ(E - H)} \\
   \end{align*}
   Vorstellung: $H(\v q, \v p) \to H(\v q, \v p, V)$. Berechne:
   \begin{align*}
   \angl{\partial_V H} &= ∫_Γ δ(E - H) \partial_V H \\
   - \pp{S}{V} &= - k \frac{∫_Γ δ(E - H) (-\partial H)}{∫_Γ θ(E - H)} = k \angl{\partial_V H} \frac{∫_Γ δ(E - H)}{∫_Γ θ(E - H)} \\
   &= k \angl{\partial_V H} \partial_E \ln(∫_Γ θ(E - H)) = \angl{\partial_V H} \partial E(k \ln Σ(E, V)) \\
   &= \angl{\partial_V H} \partial_E S = \frac{1}{T}\angl{\partial_V H} = - \frac{p}{T} \checkmark
   \end{align*}
   Weiterhin:
   \[p = T \pp{S(E, V)}{V}, \quad \frac{1}{T} = \pp{S(E, V)}{E}\]
   $⇒$ $E$ eliminieren $⇒$
   \[p = p(V, t)\]
   Zustandsgleichung! Weiter:
   \begin{align*}
   S &= S(E, V) \to E = E(S, V) \tag{Auflösen} \\
   \d E &= \pp{E}{S} \d S + \pp{E}{V} \d V,\quad \pp{E}{S} = T, \pp{E}{V} = -p
   \end{align*}
   Lösen wir jetzt
   \[\frac{1}{T} = \pp{S(E, V)}{E}\]
   nach $E$ auf.
   \[⇒ E =  E(T, V) ⇒ \pp{E(T, V)}{T} \equiv c_V\]
   $⇒$ Viele weitere Größen:
   \begin{align*}
   S &= k \ln Σ \\
   \frac{1}{T} &= \pp{S}{E} \\
   p &= T \pp{S}{V}
   \end{align*}
** Die freie Energie als thermodynamisches Potential des kanonischen Ensembles
   #+ATTR_LATEX: :options [Freie Energie]
   #+begin_defn latex
   $E = E(S, V)$ $\to$ Legendre-Transformation in $S$ $\to$
   \[-F = -F(T, V)\]
   \[⇒ T \equiv \pp{E(S, V)}{S} ⇒ S = S(T, V)\]
   \[⇒ F \equiv E(S(T, V), V) - T S(T, V)\]
   \[\d F = \underbrace{- S \d T}_{\pp{F}{T}} - \underbrace{p \d V}_{\pp{F}{V}}\]
   #+end_defn
   mikrokanonisch: $S$ aus $Γ(E, V) \to E = E(S, V)$ \\
   kanonische: $F$ aus $Z(T, V)$
   Fakt:
   \[F = - k T \ln(Z(T, V))\]
** "Makroskopischer Zugang"
   #+ATTR_LATEX: :options [2. Hautsatz]
   #+begin_defn latex
   \[\d S = \frac{\d Q}{T}\]
   #+end_defn
