#+AUTHOR: Robin Heinemann
#+TITLE: Analysis III (Marciniak-Czochra)

#+INCLUDE: "../header.org" :minlevel 1
#+LATEX_HEADER:	\theoremsymbol{}
#+LATEX_HEADER: \theoremstyle{nonumberplain}
#+LATEX_HEADER: \renewtheorem{remark}{Bemerkung}
#+LATEX_HEADER: \theoremstyle{}
#+LATEX_HEADER: \renewtheorem*{ex*}{Beispiel}

# Klausur 20.2.18
# Nachklausur 10.4.18

# Forster: Analysis 3 (Springer 2012)
# Elstrodt: Maß- und Integrationstheorie (Springer 2011)
# Bauer: Maß- und Integrationstheorie (De Gruyter 2011)
# Rudin
# Amman
# Hildebrandt

* Grundlagen der Maß- und Integrationstheorie
  Motivation: Erweiterung des Riemannintegrals auf einen größeren Bereich von Funktionen
  #+ATTR_LATEX: :options [Kriterium für Riemann Integrierbarkeit]
  #+begin_thm latex
  Sei $f:[a,b] \to ℝ$ beschränkt. Dann ist $f$ genau dann Riemann integrierbar, falls die Menge $S$ der Unstetigkeiten von $f$ eine Nullmenge ist, im Sinne, dass es
  für jedes für jedes $ε > 0$ eine abzählbare Familie von Intervallen $I_i$ gibt, mit
  \begin{align*}
  S &⊂ \bigcup_{i = 1}^∞ I_i \\
  \sum_{i = 1}^{∞} \abs{I_i} &< ε
  \end{align*}
  #+end_thm
  #+begin_remark latex
  Insbesondere ist die Funktion
  \[f:[0,1] \to ℝ, f(x) = \begin{cases} 1 & x ∈ ℚ \\  0 & x ∈ ℝ \setminus ℚ \end{cases}\]
  nicht Riemann integrierbar.
  #+end_remark
  Das Riemann-Integral der Funktion ist definiert über eine Zerlegnug des Definitionsbereiches in kleine Intervalle.
  Beim Lebesgue Integral wird stattdessen der Bildbereich zerlegt! Für eine nichtnegative $f: Ω \to [0, ∞], Ω ⊂ ℝ^n$
  betrachten wir die Mengen
  \[E_k := f^{-1}(\string(t_k, t_{k + 1}]) ⊂ ℝ^n\]
  wobei $t_k = h k$ für ein vorgegebenens $h > 0$, und approximieren dann das Integral von $f$ durch
  \begin{equation*}
  \sum_{i = 1}^{∞} t_k^{(h)} μ(E_k) \leq ∫ f(x) \d x \leq \sum_{i = 1}^{∞} t_{k + 1}^{(h)} μ(E_k) \tag{$\ast$}
  \end{equation*}
  wobei das *Maß* $μ: \mathcal{P}(ℝ^n) \to [0, ∞]$ eine Abbildung ist, welche das Maß
  der Menge $E = \mathcal{P}(ℝ^n)$ misst. Das Integral ergibt sich aus $(\ast)$ im Limes $h \to 0$.
  Für das Lebesgue-Integral müssen wir ein geeignetes Maß definieren $\to$ Lebesguemaß $\mathcal{L}^n$
  \[∫_0^1 f(x) \d \mathcal{L}^1(x) = \underbrace{\mathcal{L}^1(ℚ)}_{0} · 1 + \underbrace{\mathcal{L}^2(ℝ\setminus ℚ)}_{1} · 0 = 0\]
  #+ATTR_LATEX: :options [Maßproblem]
  #+begin_defn latex
  Wir suchen eine Abbildung $μ:\mathcal{P}(ℝ^n) \to [0, ∞]$ mit den folgenden Eigenschaft
  1. $μ(A) ⊆ μ(B) ∀ A ⊂ B$ \hfill (Monotonie)
  2. $\displaystyle{μ(\bigcup_{i = 1}^∞ A_i) = \sum_{i = 1}^{∞}μ(A_i)}$ falls $A_i \cap A_j = \emptyset ∀ i \neq j$ \hfill (\(σ\)-Additivität)
  3. $μ([0,1]^n) = 1$ \hfill (Normierung)
  4. $μ(Q A + y) = μ(A)$ falls $Q ∈ O(n), y ∈ ℝ^n$ \hfill (Euklidische Invarianz)
  Dieses Problem heißt Maßproblem. In einer etwas schwächeren Version kann man auch fordern
  2. [@2] $\displaystyle{μ(\bigcup_{i = 1}^k A_i) = \sum_{i = 1}^{k} μ(A_i)}$
  4. [@4] $μ(A + y) = μ(A)$ für $y ∈ ℝ^n$
  #+end_defn
  #+ATTR_LATEX: :options [Vitali: 1908]
  #+begin_thm latex
  Es gibt keine Abbildung $μ:\mathcal{P}(ℝ^n) \to [0, ∞]$ welche die Forderungen des Maßproblems erfüllt.
  #+end_thm
  #+begin_proof latex
  Sei $μ: \mathcal{P}(ℝ^n) \to [0, ∞]$ eine Abbildung die die Forderungen des Maßproblems erfüllt.
  Sei $q_i, i ∈ ℕ$ eine Abzählung von $[0, 1]^n \cap ℚ^n$. Wir definieren die Äquivalenzrelation
  $x \sim y$ auf $E := [0, 1]^n$ durch $x \sim y ⇔ x - y ∈ ℚ$. Nach dem Auswahlaxiom gibt es eine
  Menge $M_0 ⊂ [0,1]^n$, welche aus jeder Äquivalenzklasse genau ein Element enthält, das heißt es
  gilt:
  1. $∀ y ∈ [0, 1]^n ∃ x ∈ M_0: x \sim y ∈ ℚ$
  2. Aus $x, y ∈ M_0, x - y ∈ ℚ ⇒ x = y$
  Wir definieren $M_i = M_0 + q_i$. Aus der	Definition von $M_i$ folgt $M_i \cap M_j = \emptyset ∀ i \neq j$.
  In der Tat falls $x ∈ M_i \cap M_j$, dann $x - q_i ∈ M_0$ und $x - q_j ∈ M_0 \xRightarrow{1.} q_i = q_j$.
  Außerdem gilt $[0, 1]^n ⊂ \bigcup_{i = 1}^∞ M_i ⊂ [0, 2]^n$. Die erste Einbettung folgt aus 1., die zweite
  Einbettung gilt, da $y + q_j ∈ [0, 2]^n ∀ y ∈ M_0$ und $y ∈ [0, 1]^n$ schließlich gilt
  $μ(M_j) = μ(M_0) ∀ j ∈ ℕ$. Dies folgt aus den Forderungen 1., 3., 4. (abgeschwächte Version reicht).
  \[⇒ 1 = μ([0, 1]^n) \leq μ(\bigcup_{j = 0}^∞ M_j) = \sum_{i = 0}^{∞}μ(M_i) = \sum_{i = 0}^{∞} μ(M_0) ⇒ μ(M_i) = μ(M_0) > 0\]
  und
  \[μ(\bigcup_{i = 0}^∞ M_i) = ∞\]
  Aus 3. und 4. folgt andererseits
  \begin{align*}
  μ([0,2]^n) &= 2^n μ([0,1]^n) = 2^n \\
  \xRightarrow{(\ast)} μ(\bigcup_{i = 0}^∞ M_i) &\leq μ([0,2]^n) = 2^n < ∞ \lightning
  \end{align*}
  #+end_proof
  #+begin_remark latex
  Jedes Maß, welche die Eigenschaften des Maßproblems erfüllt, kann also nicht auf der ganzen
  $\mathcal{P}(ℝ^n)$ definiert sein, sondern auf einer Untermenge der $\mathcal{P}(ℝ^n)$.
  #+end_remark
  Frage: Welche ist die "größte" (eine "gute") Untermenge $\mathcal{A} ⊂ \mathcal{P}(ℝ^n)$, sodass
  es eine Lösung des Maßproblems gibt?
  #+ATTR_LATEX: :options [Algebra und \(σ\)-Algebra]
  #+begin_defn latex
  Eine Algebra $\mathcal{A}$ ist die Familie von Teilmengen einer gegebenen Menge $X$ mit
  - $X ∈ \mathcal{A}$
  - $A ∈ \mathcal{A} ⇒ A^C := X \setminus A ∈ \mathcal{A}$
  - $A, B ∈ \mathcal{A} ⇒ A \cup B ∈ \mathcal{A}$
  Falls
  \[(A_k)_{k ∈ ℕ} ⊂ \mathcal{A} ⇒ \bigcup_{k ∈ ℕ} A ∈ \mathcal{A}\]
  so spricht man von einer \(σ\)-Algebra.
  #+end_defn
  #+begin_lemma latex
  Sei $X$ eine Menge, $\mathcal{A}$ eine $σ$ Algebra und $(A_k)_{k ∈ ℕ} ⊂ \mathcal{A}$. Dann gehören $\emptyset, \bigcap_{k ∈ ℕ} A_k$ und $A_1 \setminus A_2$ zu $\mathcal{A}$.
  #+end_lemma
  #+begin_proof latex
  (Übung)
  #+end_proof
  #+ATTR_LATEX: :options [Erzeugte und relative \(σ\)-Algebra]
  #+begin_defn latex
  Für $S ⊂ \mathcal{P}(X)$ wird
  \[Σ(S) = Σ(S \mid X) := \bigcap \{\mathcal{A} ⊂ \mathcal{P}(X) \mid \mathcal{A} \text{ ist eine \(σ\)-Algebra mit \(S ⊆ \mathcal{A}\)}\}\]
  als die von $S$ erzeugte \(σ\)-Algebra bezeichnet.
  $∀ Y ⊂ X$ definieren wir die relative \(σ\)-Algebra
  \[\mathcal{A} \cap Y := \{A \cap Y \mid A ∈ \mathcal{A}\}\]
  #+end_defn
  #+begin_lemma latex
  Die erzeugte relative \(σ\)-Algebra sind wohldefiniert. Für alle Mengen $S ⊂ \mathcal{P}(X), Y ⊂ X$ gilt
  \[Σ(S \cap Y \mid Y) = Σ(S \mid X) \cap Y\]
  #+end_lemma
  #+begin_proof latex
  (Übungen)
  #+end_proof
  #+ATTR_LATEX: :options [Topologischer Raum]
  #+begin_defn latex
  Ein topologischer Raum ist ein Paar $(X,\mathcal{O})$ bestehend aus Menge $X$ und $\mathcal{O} ⊂ \mathcal{P}(X)$ mit
  - $\emptyset, X ∈ \mathcal{O}$
  - $U, V ∈ \mathcal{O} ⇒ U \cap V ∈ \mathcal{O}$
  - $(U_k)_{k ∈ I} ⊂ \mathcal{O} ⇒ \bigcup_{k ∈ I} U_k ∈ \mathcal{O}$ für eine beliebige Indexmenge $I$.
  Die Elemente von $\mathcal{O}$ werden als *offene Menge* bezeichnet.
  #+end_defn
  #+begin_remark latex
  Topologische Raum ist abgeschlossen unter endlichen Schnitten und abzählbaren Vereinigungen.
  #+end_remark
  #+ATTR_LATEX: :options [Borel-\(σ\)-Algebra, Borel Menge]
  #+begin_defn latex
  Ist $X$ ein topologischer Raum, so ist die Borel-\(σ\)-Algebra $\mathcal{B}(X)$ diejenige \(σ\)-Algebra, die von den offenen Mengen erzeugt wird. Ihre Elemente heißen Borel-Mengen.
  \begin{align*}
  \mathcal{B}^n &:= \mathcal{B}(ℝ^n) \\
  \mathcal{B} &:= \mathcal{B}^1 \\
  \end{align*}
  #+end_defn
  #+begin_remark latex
  Die \(σ\)-Algebra die von den abgeschlossenen Mengen erzeugt wird, ist ebenfalls identisch mit der Borel \(σ\)-Algebra.
  #+end_remark
  #+ATTR_LATEX: :options [Messraum, Maß, Maßraum]
  #+begin_defn latex
  Eine Menge $X$ mit einer \(σ\)-Algebra $\mathcal{A} ⊂ \mathcal{P}(X)$ heißt *Messraum*. Ein *Maß* ist eine Abbildung $μ: \mathcal{A} \to [0, ∞]$ mit
  - $μ(\emptyset) = 0$
  - $μ(\bigcup_{k ∈ ℕ} A_k) = \sum_{k ∈ ℕ} μ(A_k)$ für disjunkte Mengen \hfill\(σ\)-Additivität
  Die Elemente in $\mathcal{A}$ heißen messbar, und $(X, \mathcal{A}, μ)$ heißt *Maßraum*.
  #+end_defn
  #+ATTR_LATEX: :options [\(σ\)-Finitheit]
  #+begin_defn latex
  Ein Mah heißt \(σ\)-finit, falls es eine abzählbare Überdeckung $\{X_k\}_{k ∈ ℕ} ⊂ \mathcal{A}$ von $X$ gibt, also
  \[X = \bigcup_{k ∈ ℕ} X_k\]
  sodass $μ(X_k) < ∞ ∀ k$. \\
  $μ$ heißt endlich falls $μ(X) < ∞$. Bei Wahrscheinlichkeitsmaß $μ(X) = 1$.
  #+end_defn
  #+begin_ex latex
  1. Zählmaß: Für $X$ und $\mathcal{A} = \mathcal{P}(X)$ setze für $A ∈ \mathcal{A}$:
	 \[μ(A) = \begin{cases} \# A & A \text{ endlich} \\ ∞ & \text{sonst}\end{cases}\]
	 $μ$ ist endlich falls $X$ endlich und \(σ\)-finit wenn $X$ abzählbar.
  2. Dirac-Maß: Für einen fest gewählten $x_0 ∈ X$ und $\mathcal{A} = \mathcal{P}(X)$ setzen wir für $A ⊂ X$
	 \[μ(A) := \begin{cases} 0 & x_0 \not∈ A \\ 1 & x_0 ∈ A\end{cases}\]
  3. Positive Linearkombination: $μ_1, μ_2$ Maße auf $(X, \mathcal{A})$. Dann ist $μ := α_1 μ_1 + α_2 μ_2$ für $α_1, α_2 \geq 0$ wieder
	 ein Maß
  #+end_ex
  #+begin_lemma latex
  Sei $(X, \mathcal{A}, μ)$ ein Maßraum und $Y ∈ \mathcal{A}$. Dann ist $μ\mid_Y(A) := μ(A \cap Y) ∀ A ∈ \mathcal{A}$ wieder ein Maß auf $(X, \mathcal{A})$.
  Durch Einschränken der \(σ\)-Algebra $\mathcal{A}$ auf $\mathcal{A}\mid_Y := \{A ∈ \mathcal{A} \mid A ⊂ Y\}$ wird $(Y, \mathcal{A}\mid_Y, μ\mid_Y)$ auch ein Maßraum.
  Falls $(X, \mathcal{A}, μ)$ \(σ\)-finit, dann $(Y, \mathcal{A}\mid_Y, μ\mid_Y)$ auch.
  #+end_lemma
  *Notation*: Zu $(A_k)_{k ∈ ℕ} ⊂ X$ schreiben wir
  - $A_k \nearrow A (k \to ∞)$ falls $A_k ⊂ A_{k + 1} ∀ k ∈ ℕ$ und $A = \bigcup_{k ∈ ℕ} A_k$
  - $A_k \searrow A (k \to ∞)$ falls $A_k \supset A_{k + 1} ∀ k ∈ ℕ$ und $A = \bigcap_{k ∈ ℕ} A_k$

  #+begin_thm latex
  Für jeden Maßraum $(X, \mathcal{A}, μ)$ und $(A_k)_{k ∈ ℕ} ⊂ \mathcal{A}$ gilt
  1. $A_1 ⊂ A_2 ⇒ μ(A_1) \leq μ(A_2)$ \hfill (Monotonie)
  2. $μ(\bigcup_{k ∈ ℕ} A_k) \leq \sum_{k ∈ ℕ} μ(A_k)$ \hfill (\(σ\)-Subadditivität)
  3. $A_k \nearrow A ⇒ μ(A_k) \nearrow μ(A)$ für $(k \to ∞)$ \hfill (Stetigkeit von Unten)
  4. $A_k \searrow A ⇒ μ(A_k) \searrow μ(A)$ für $(k \to ∞)$ und $μ(A_1) < ∞$ \hfill (Stetigkeit von Oben)
  #+end_thm
  #+begin_proof latex
  1. $A, B ∈ \mathcal{A}, A ⊂ B ⇒ B = A \dcup (B \setminus A), B \setminus A ∈ \mathcal{A} ⇒ μ(B) = μ(A) + μ(B\setminus A) \geq μ(A)$
  2. Wir definieren $(B_k)_{k ∈ ℕ} ⊂ \mathcal{A}$ durch
	 \begin{align*}
	 B_1 &:= A_1, B_{k + 1} := A_{k + 1} \setminus \bigcup_{j = 1}^k A_k
	 ⇒ \bigdcup_{k ∈ ℕ} B_k &= \bigcup_{k ∈ ℕ} A_k
	 \end{align*}
	 Nach Definition gilt
	 \[μ(\bigcup_{k ∈ ℕ} A_k) = μ(\bigcup_{k ∈ ℕ} B_k) = \sum_{k ∈ ℕ}μ(B_k) \leq \sum_{k ∈ ℕ} μ(A_k)\]
  3. Definieren $(C_k)_{k ∈ ℕ} ⊂ \mathcal{A}$ durch
	 \begin{align*}
	 C_1 &:= A_1 \\
	 C_{k + 1} &:= A_{k + 1} \setminus A_k
   	 \end{align*}
	 Es gilt
	 \begin{align*}
	 ⇒ \bigdcup_{k ∈ ℕ} C_k &= \bigcup_{k ∈ ℕ} A_k = A \\
	 μ(A_k) &= \sum_{j = 1}^{k} μ(C_j) \xrightarrow{k \to ∞} \sum_{k ∈ ℕ} μ(C_k) = μ(A) \leq \sum_{k ∈ ℕ} μ(A_k)
   	 \end{align*}
  4. $D_k := A_1 \setminus A_k ∀ k ∈ ℕ$. Damit ist $D_k \nearrow A_1 \setminus A$ und
	 \[μ(A_1) - μ(A_k) = μ(A_1 \setminus A_k) \xrightarrow{k \to ∞}[3.] μ(A_1 \setminus A) = μ(A_1) - μ(A)\]
	 Subtraktion von $μ(A_1) < ∞$ liefert die Behaptung.
  #+end_proof
  #+begin_ex latex
  $μ: \mathcal{P}(ℕ) \to [0, ∞], μ(A) := \# A$. Die Mengenfolge $A_n := \{n, n + 1, n + 2, \dots\}$ ist fallend gegen die leere Menge, aber es ist
  \[0 = μ(\emptyset) \neq \lim_{n \to ∞} μ(A_n) = ∞\]
  #+end_ex
  #+ATTR_LATEX: :options [Borel-Maß]
  #+begin_defn latex
  Set $X$ ein topologischer Raum. Ein Maß auf einer Borel-\(σ\)-Algebra $\mathcal{B}(X)$ heißt Borel-Maß, falls es auf Kompakta stets endlich Werte annimmt.
  #+end_defn
  #+begin_ex latex
  Für $X = ℝ$ ist das Dirac-Maß ein Brel-Maß, aber nicht das Zählmaß.
  #+end_ex
  #+ATTR_LATEX: :options [Regularität]
  #+begin_defn latex
  Sei $X$ ein topologischer Raum, $(X, \mathcal{A}, μ)$ ein Maßraum. Das Maß $μ$ heißt *regulär von außen*, wenn für $A ∈ \mathcal{A}$ gilt
  \[μ(A) = \inf \{μ(U) \mid A ⊂ U, U \text{ offen}\}\]
  $μ$ heißt *regulär von innen*, wenn für $A ∈ \mathcal{A}$ gilt
  \[μ(A) = \sup\{μ(K) \mid K ⊂ A, K \text{kompakt}\}\]
  #+end_defn
  #+begin_ex latex
  Das Zählmaß mit $X = ℝ, \mathcal{A} = \mathcal{B}$, ist regulär von inne, aber nicht von außen. Das Dirac-Maß ist regulär.
  #+end_ex
  \begin{defn*}[Kompaktheit]
  Sei $X$ ein topologischer Raum und $A ⊂ X$. Dann nennt man $A$ kompakt, wenn \textbf{jede} offene Überdeckung von $A$ eine \textbf{endliche} Teilüberdeckung besitzt.
  Das beutet:
  \[∀ I ∃ I' ⊂ I, \abs{I'} < ∞: A ⊂ \bigcup_{i ∈ I} A_i ⇒ A ⊂ \bigcup_{i ∈ I'} A_i\]
  \end{defn*}
  #+begin_remark latex
  In einem metrischen Raum isnd die bisherigen Definitionen der Kompaktheit mit der neu eingeführten äquivalent.
  #+end_remark
  *Konstruktion von Maßen* \\
  Strategie:
  1. Starte mit einem Prämaß $λ$ auf einer Algebra endlichen, disjunkten Vereinigungen von Intervallen, $λ$ = Summe der Längen
  2. Dieses Prämaß kann zu einem äußeren Maß auf $\mathcal{P}(ℝ)$ fortgesetzt werden (keine \(σ\)-Additivität)
  3. Einschränkung auf Borel-\(σ\)-Algebra liefert ein Maß.

  #+ATTR_LATEX: :options [Dynkin-System]
  #+begin_defn latex
  Eine Familie $\mathcal{D} ⊂ \mathcal{P}(X)$, $X$ Menge, heißt Dynkin-System, falls gilt:
  1. $X ∈ \mathcal{D}$
  2. $A ∈ \mathcal{D} ⇒ A^C ∈ \mathcal{D}$
  3. $\displaystyle{(A_k)_{k ∈ ℕ} ⊂ \mathcal{D}, A_k ∩ A_l = \emptyset ∀ k, l ∈ ℕ, k \neq l ⇒ \bigcup_{k ∈ ℕ A_k ∈ \mathcal{D}}}$
  #+end_defn
  #+begin_remark latex
  1. Ein Dynkin-System ist abgeschlossen bezüglich Mengensubtraktion:
	 \[A, B ∈ \mathcal{D}, B ⊂ A ⇒ A \setminus B = A ∩ B^C = (A^C ∪ B)^C ∈ \mathcal{D}\]
  2. Ist $S ⊂ \mathcal{P}(X)$, so ist
	 \[\mathcal{D}(S) = \bigcap \{\mathcal{D} \mid \mathcal{D} \text{ Dynkin-System}, S ⊂ \mathcal{D}\}\]
	 das von $S$ erzeugte Dynkin-System
  3. Das von $S$ erzeugte Dynkin-System ist	wohldefinieret, dass heiß, es ist eindeutig und tatsächlich ein Dynkin-System.
  #+end_remark
  #+begin_lemma latex
  Ist $\mathcal{D}$ ein Dynkin-System und abgeschlossen bezüglich endlicher Schnitte oder alternativ bezüglich beliebiger (also nicht disjunkter)
  endlicher Vereinigung, so ist $\mathcal{D}$ eine \(σ\)-Algebra
  #+end_lemma
  #+begin_proof latex
  Übungen
  #+end_proof
  #+begin_lemma latex
  Sei $S$ eine (nicht leere) Familie von Teilmengen einer Menge $X$, die abgeschlossen ist unter endlichen Schnitten sind, dann folgt $\mathcal{D}(S) = Σ(S)$
  #+end_lemma
  #+begin_proof latex
  Nach Definition gilt $\mathcal{D} ⊂ Σ(S)$. Die andere Inklusion folgt sofort, wenn wir zeigen, dass $\mathcal{D}(S)$ \(σ\)-Algebra ist.
  Nach Lemma 1.21 genügt es zu zeigen, dass $\mathcal{D}(S)$ abgeschlossen ist unter endlichen Schnitten. Definiere für ein	beliebiges $A ∈ \mathcal{D}(S)$
  \[D(A) := \{B ∈ \mathcal{D} \mid A ∩ B ∈ \mathcal{D}\} ⊂ \mathcal{D}\]
  wir müssen beweisen $D(A) = \mathcal{D}$ für alle $A ∈ \mathcal{D}$. Es gilt
  1. $X ∈ \mathcal{D}, A ∩ X = A ∈ \mathcal{D} ⇒ X ∈ D(A)$
  2. $B ∈ D(A) ⇒ B ∈ \mathcal{D}, A ∩ B ∈ \mathcal{D}$ woraus folgt
	 \[A ∩ B^C = A \setminus (B ∩ A) ∈ \mathcal{D} ⇒ B^C ∈ D(A)\]
  3. $B = \bigcup_{k ∈ ℕ} B_k, B_k ∈ D(A) ⇒ B_k ∈ \mathcal{D}, A ∩ B_k ∈ \mathcal{D}$ woraus folgt, dass $B ∈ \mathcal{D}$ und
	 \[B ∩ A = \bigcup_{k ∈ ℕ} (B_k ∩ A) ∈ \mathcal{D} ⇒ B ∈ D(A)\]
  Behauptung: $A ∈ S ⇒ S ⊂ D(A)$, denn: $B ∈ S ⇒ A ∩ B ∈ S ⇒ B ∈ D(A)$.
  Da $\mathcal{D} = D(S)$ das kleinste Dynkin-System ist, das $S$ enthätlt folgt $\mathcal{D} ⊂ D(A) ⇒ \mathcal{D} = D(A)$.
  Für beliebiges $U ∈ S, V ∈ \tilde{\mathcal{D}} = D(U)$ folgt nach Definition $U ∩ V ∈ \mathcal{D}$. Dies impliziert $U ∈ D(V)$, also $S ⊂ D(V) ∀ V ∈ \mathcal{D}$.
  Wie eben ist $D(V) ⊂ \mathcal{D}$, also $D(V) = \mathcal{D} ∀ V ∈ \mathcal{D}$.
  #+end_proof
  #+begin_remark latex
  Lemma 1.22 lässt sich wie folgt anwenden:
  1. Verifiziere eine Eigenschaft $ε$ auf einer Menge $S ⊂ \mathcal{P}(X)$, die abgeschlossen ist unter endlichen Schnitten ist.
  2. Zeige, dass die Menge aller Mengen, die $ε$ erfüllen ein Dynkin-System ist.
  3. Schließe, dass $ε$ auf $Σ(S)$ gilt.
  #+end_remark
  #+ATTR_LATEX: :options [Eindeutigkeit von Maßen]
  #+begin_thm latex
  Sei $(X, Σ, μ)$ ein Maßraum und $S ⊂ \mathcal{P}(X)$ Familie von Menge, die abgeschlossen unter endlichen Schnitten und $Σ = Σ(S)$.
  Weiter enthalte $S$ eine Folge aufsteigender Mengen $(X_k)_{k ∈ ℕ} ⊂ S$ mit $X_k \nearrow X$ und $μ(X_k) < ∞$ für alle $k ∈ ℕ$. Dann ist $μ$ auf $Σ = Σ(S)$ durch die Werte auf $S$ eindeutig bestimmt.
  #+end_thm
  #+begin_proof latex
  Sei $\tilde μ$ ein weiteres Maß mit $\tilde μ = μ$ auf $S$. Dann gilt
  \[\tilde μ(X) = \lim_{k \to ∞} \tilde μ(X_k) = \lim_{k \to ∞} μ(X_k) = μ(X)\]
  zunächst $μ(X) < ∞$. Idee:
  \[\mathcal{D}= \{A ∈ Σ \mid \tilde μ(A) = μ(A)\}\]
  ist ein Dynkin-System. \\
  $X ∈ \mathcal{D}$ bereits gezeigt. Für $A ∈ \mathcal{D}$ ist
  \[\tilde μ(A^C) = \tilde μ(X) - \tilde μ(A) = μ(X) - μ(A) = μ(A^C)\]
  $⇒ A^C ∈ \mathcal{D}$. Betrachte $(B_k)_{k ∈ ℕ}, B_k ∩ B_l = \emptyset ∀ k, l ∈ ℕ, k \neq l$ und $B_k ∈ \mathcal{D}$ sowie $B = \bigcup_{k ∈ ℕ} B_k$. Dann gilt
  \[\tilde μ(B) = \sum_{k ∈ ℕ} \tilde μ(B_k) = \sum_{k ∈ ℕ} μ(B_k) = μ(B)\]
  Nach Lemma 1.22 folgt also $Σ = Σ(S) = \mathcal{D}(S) ⊂ \mathcal{D} ⊂ Σ ⇒ \mathcal{D} = Σ$. \\
  Im allgemeinen Fall erhalten wir für $A ∈ Σ$:
  \[\tilde μ(A) = \lim_{k \to ∞}  \tilde μ(A ∩ X_k) = \lim_{k \to ∞} μ(X_k ∩ A)\]
  #+end_proof
  #+ATTR_LATEX: :options [Prämaß]
  #+begin_defn latex
  Sei $X$ eine Menge und $\mathcal{A} ⊂ \mathcal{P}(X)$ eine Algebra. Ein *Prämaß* auf $X$ ist eine \(σ\)-additive Abbildung $μ: \mathcal{A} \to [0, ∞]$ mit $μ(\emptyset) = 0$.
  #+end_defn
  #+begin_remark latex
  Man braucht nur die \(σ\)-Additivität für solche (paarweise disjunkte) Folgen $(A_k)_{k ∈ ℕ} ⊂ \mathcal{A}$ gewährleisten, deren Vereinigung
  \[\bigcup_{k ∈ ℕ} A_k ∈ \mathcal{A}\]
  Ein Prämaß auf einer \(σ\)-Algebra ist ein Maß.
  #+end_remark
  #+begin_korollar latex
  Sei $μ$ ein \(σ\)-finites Prämaß auf einer Algebra $\mathcal{A}$, dann gibt es höchstens eine Fortsetzung auf $Σ(\mathcal{A})$.
  #+end_korollar
  #+begin_proof latex
  Setze $S = \mathcal{A}$ wie im Satz 1.23. Offenbar ist abgeschlossen unter endlichen Schnitten. Da $X$ \(σ\)-finit ist, gibt es eine
  Folge $(X_k)_{k ∈ ℕ}$ mit $X = \bigcup_{k ∈ ℕ} X_k$ und $μ(X_k) < ∞ ∀ k ∈ ℕ$. Für $A_k := \bigcup_{j = 1}^k X_j$ ist $A_k \nearrow X$ und
  \[μ(A_k) \leq \sum_{j = 1}^{k} μ(X_k) < ∞\]
  Nach dem Setz 1.23 ist das auf $(X, Σ)$, so es denn existiert, eindeutig.
  #+end_proof
  #+begin_ex latex
  Die Menge $S$, sei die Menge, die alle Intervalle $[a, b\string), -∞ \leq a \_eq b \leq ∞$ erzeugt dann unter endlichen Vereinigungen eine Algebra $\mathcal{A}$.
  Wir setzen
  \begin{align*}
  μ(\emptyset) &= 0 \\
  μ([a, b\string)) &= ∞ \\
  \end{align*}
  Dieses $μ$ ist Prämaß auf $\mathcal{A}$. Es gibt (mindestens) zwei Fortsetzungen:
  1. Zählmaß ist eine Fortsetzung
  2. $μ(A) = ∞ ∀ A \neq \emptyset$
  #+end_ex
  #+ATTR_LATEX: :options [äußeres Maß]
  #+begin_defn latex
  EIne Funktion $μ^{\ast}: \mathcal{P}(X) \to [0, ∞]$ ist ein äußeres Maß auf $X$, falls für alle $(A_k)_{k ∈ ℕ} ⊂ \mathcal{P}(X)$ die folgenden Eigenschaften erfüllt sind:
  1. $μ^{\ast}(\emptyset) = 0$
  2. $μ^{\ast}(A_1) \leq μ^{\ast}(A_2)$, falls $A_1 ⊂ A_2$ \hfill (Monotonie)
  3. $\displaystyle{μ^{\ast}(\bigcup_{k ∈ ℕ} A_k) \leq \sum_{k ∈ ℕ} μ^{\ast}(A_k)}$ \hfill (\(σ\)-Subadditivität)
  #+end_defn
  #+begin_thm latex
  Sei $μ^{\ast}$ ein äußeres Maß auf eine Menge $X$. Wir sagen, die Menge $A ⊂ X$ erfüllt die Caratheodory-Bedingung (CB) falls
  \[μ^{\ast}(E) = μ^{\ast}(E ∩ A) + μ^{\ast}(E ∩ A^C) ∀ E ⊂ X\]
  Die Familie $Σ$ aller Mengen, die die Caratheodory-Bedingung erfüllen bildet eine \(σ\)-Algebra und $μ^{\ast}|_Σ$ ist ein Maß.
  #+end_thm
  #+begin_proof latex
  Wir zeigen zunächst, dass $Σ$ eine Algebra ist. Offenbar $X ∈ Σ$. Abgeschlossen unter Komplementbildung ist klar. Für endliche Vereinigungen wähle $A, B ∈ Σ$. Sei $E ⊂ X$ beliebig.
  \begin{align*}
  μ^{\ast}((A ∪ B) ∩ E) &\leq μ^{\ast}(A ∩ B^C ∩ E) + μ^{\ast}(A^C ∩ B ∩ E) + μ^{\ast}(A ∩ B ∩ E) \\
  \intertext{Nun wird die Caratheodory-Bedingung zweimal angewandt}
  μ^{\ast}(E) &= μ^{\ast}(E ∩ A) + μ^{\ast}(E ∩ A^C) \\
  &= μ^{\ast}(E ∩ A ∩ B) + μ^{\ast}(E ∩ A ∩ B^C) + μ^{\ast}(E ∩ A^C ∩ B) + μ^{\ast}(E ∩ A^C ∩ B^C) \\
  \intertext{Mit obiger Abschätzung erhalten wir}
  μ^{\ast}(E) &\geq μ^{\ast}((A ∪ B) ∩ E) + μ^{\ast}(E ∩ A^C ∩ B^C) = μ^{\ast}((A ∪ B) ∩ E) + μ^{\ast}((A ∪ B)^C ∩ E) \\
  \end{align*}
  Die andere Richtung folgt aus der \(σ\)-Subadditivität \\
  Sei nun also $(A_k)_{k ∈ ℕ} ⊂ Σ$. Wir können ohne Beschränkung der Allgemeinheit annehmen, dass die $A_k$ paarweise disjunkt sind. Nun ist für jedes $E ⊂ X$ und
  \begin{align*}
  B_k &= \bigcup_{j = 1}^k A_k ∈ Σ,\qquad B_k \nearrow \bigcup_{k ∈ ℕ} A_k \\
  μ^{\ast}(B_k ∪ E) &= μ^{\ast}(B_k ∩ E ∩ A_k) + μ^{\ast}(B_k ∩ E ∩ A_k^C) \\
  &= \sum_{j = 1}^{k} μ^{\ast}(E ∩ A_j) \\
  \intertext{Also haben wir}
  μ^{\ast}(E) &= μ^{\ast}(E ∩ B_k) + μ^{\ast}(E ∩ B_k^C) \\
  \intertext{Mit $k \to ∞$ erhält man}
  μ^{\ast}(E) &\geq \sum_{k ∈ ℕ} μ^{\ast}(E ∩ A_k) + μ^{\ast}(E ∩ A^C) \geq μ^{\ast}(\bigcup_{k ∈ ℕ} (A_k ∩ E) + μ^{\ast}(E ∩ A^C)) \\
  & \geq μ^{\ast}(E) \\
  \intertext{Also gilt}
  A &= \bigcup_{k ∈ ℕ} A_k ∈ Σ
  \end{align*}
  Damit $μ^{\ast}|_{Σ}$ ein Maß ist, betrachte Folge $(A_k)_{k ∈ ℕ}$ paarweise disjunkt. Da $Σ$
  eine \(σ\)-Algebra ist wähle in der Caratheodory-Bedingung $E = A = \bigcup_{k ∈ ℕ}A_k$.
  \begin{align*}
  μ^{\ast}(E) = μ^{\ast}(A) = \sum_{k ∈ ℕ} μ^{\ast}(A ∩ A_k) + μ^{\ast}(A ∩ A^C) = \sum_{k ∈ ℕ} μ^{\ast}(A_k)
  \end{align*}
  $μ^{\ast}(\emptyset) = 0$ gilt nach Definition des äußeren Maßes.
  #+end_proof
  #+begin_remark latex
  Das soeben konstruierte Maß $μ^{\ast}\mid_{Σ}$ ist vollständig, jede Teilmenge einer Nullmenge ist messbar.
  #+end_remark
  #+begin_proof latex
  Sei $A ∈ Σ$, $μ^{\ast}(A) = 0$ und $B ⊂ A$. Es gilt für $E = X$ in der Caratheodory-Bedingung
  \[μ^{\ast}(E ∩ B) \leq μ^{\ast}(A) + μ^{\ast}(E ∩ B^C) \leq μ^{\ast}(E)\]
  Insofern ist $B ∈ Σ$
  #+end_proof
  *Fahrplan für das Lebesgue-Maß* \\
  Für ein verallgemeinertes Intervall $I$ der Form $(a, b), \string(a,b], [a,b\string), [a, b]$ mit $-∞ \leq a \leq b \leq ∞$ setzen wir $λ(I) := b - a ∈ [0, ∞]$
  \begingroup
  \def\thedefn{1.31}
  #+begin_lemma latex
  Dies ergibt ein eindeutiges \(σ\)-finites Prämaß auf der Algebra $\mathcal{A}$, die aus endliches Vereinigungen disjunkter Intervalle besteßt
  \[λ(\bigcup_{j = 1}^k I_j) = \sum_{j = 1}^{k} λ(I_j)\]
  #+end_lemma
  Wir erhalten zunechst eine Fortsetzung von $λ$ zu einem äußeren Maß $λ^{\ast}$, also $λ = λ^{\ast}$ auf $\mathcal{A}$, wobei jede Menge aus $\mathcal{A}$ die Caratheodory-Bedingung erfüllt.
  Satz 1.27 liefert eine \(σ\)-Algebra $Λ \supset \mathcal{A}$, sodass $λ := λ^{\ast}\mid_Λ$ ein Maß ist
  \def\thedefn{1.32}
  #+begin_defn latex
  Die Elemente von $Λ$ nennt man Lebesque-messbare Mengen und $λ$ das Lebesque-Maß.
  #+end_defn
  \endgroup
  \begingroup

  #+begin_lemma latex
  Sei $μ$ ein Prämaß auf einer Algebra $\mathcal{A} ⊂ \mathcal{P}(X)$. Wir setzen für $A ⊂ X$
  \[μ^{\ast}(A) = \inf \{\sum_{k ∈ ℕ} μ(A_k) \mid (A_k)_{k ∈ ℕ} ⊂ \mathcal{A}, A ⊂ \bigcup_{k ∈ ℕ} A_k\}\]
  Dies ist ein äußeres Maß mit $μ^{\ast} = μ$ auf $\mathcal{A}$	und jede Menge aus $\mathcal{A}$ erfüllt die Caratheodory-Bedingung.
  #+end_lemma
  #+ATTR_LATEX: :options [Caratheodory-Eigenschaft]
  #+begin_proof latex
  Sei $E ⊂ X$ und $A ⊂ \mathcal{A}$. Zu zeigen:
  \[μ^{\ast}(E) = μ^{\ast}(E ∩ A^C) + μ^{\ast}(E ∩ A)\]
  "$\leq$" folgt aus Subadditivität. Noch zu zeigen: $\geq$. Wir betrachten eine beliebige Überdeckung von $E$ durch $(B_k)_{k ∈ ℕ} ⊂ \mathcal{A}, B := \bigcup_{k ∈ ℕ} B_k \supset E$.
  Dann ist zunächst auch $(B_k ∩ A)_{k ∈ ℕ}$ eine Überdeckung von $E ∩ A$ und entsprechend $(B_k ∩ A^C)_{k ∈ ℕ}$ von $E ∩ A^C$. Wir erhalten
  \begin{align*}
  \sum_{k ∈ ℕ} μ(B_k) &= \sum_{k ∈ ℕ} μ(B_k ∩ A) + \sum_{k ∈ ℕ} μ(B_k ∩ A^C) \\
  &\geq μ^{\ast}(E ∩ A) + μ^{\ast}(E ∩ A^C)
  \end{align*}
  Infimum über $(B_k)_{k ∈ ℕ}$ mit $\bigcup_{k ∈ ℕ} \supset E$ liefert
  \[μ(E^{\ast}) \geq μ^{\ast}(E ∩ A) + μ^{\ast}(E ∩ A^C)\]
  #+end_proof
  #+ATTR_LATEX: :options [von Lemma 1.31]
  #+begin_proof latex
  - $\mathcal{A}$ ist Algebra ($ℝ = (-∞, ∞)$, das Komplement einer endlichen Vereinigung disjunkter Intervalle besitzt wieder diese Form)
  -	Offenbar gilt $λ(\emptyset) = 0$
  zu zeigen (für \(σ\)-Algebra): für alle paarweise disjunkten Folgen $(I_k)_{k ∈ ℕ} ⊂ \mathcal{A}$
  \begin{align*}
  λ(\bigcup_{k ∈ ℕ} I_k) &= \sum_{k ∈ ℕ} λ(I_k) \\
  \intertext{Wir bekommen}
  \sum_{j= 1}^{k} λ(I_j) \underarrow[=]{Additivität} λ(\bigcup_{j = 1}^k I_j) \overarrow[\leq]{Monotonie} λ(\bigcup_{j = 1}^∞ I_j) = λ(I) \\
  \end{align*}
  "$\geq$": wür wählen $∀ k ∈ ℕ$ ein offenes $J_k \supset I_k$ mit
  \[λ(J_k) \leq λ(I_k) + \frac{ε}{2^k}\qquad \text{für ein } ε > 0\]
  Sei zunächst $I$ kompakt. Dann können wir endlich viele $J_k$ auswählen, sodass diese $I$ überdecken. Wir nehmen an, dass dies die ersten $K$ Elemente sind (Umnummerierung). Es
  gilt
  \[λ(I) \overarrow[=]{Monotonie} λ(\bigcup_{j = 1}^k J_j) \leq	\underarrow[=]{Subadditivität} \sum_{j = 1}^{k} λ(J_j) \overarrow[\leq]{aus Konstruktion} \sum_{j = 1}^{k} λ(I) + ε\]
  Mit $ε \searrow 0$ folgt \(σ\)-Additivität für kompakte $I$. Die Behauptung folgt auch für beschränkte $I$ (weil mit Additivität und $λ(\{x\}) = λ([x, x]) = 0 ∀ x ∈ ℝ$ können wir
  die Endpunkte an Intervalle hinzufügen oder entfernen).
  Sei $I$ ein unbeschränkts Intervall $λ(I) = ∞$. Zu zeigen
  \[\sum_{j = 1}^{∞} λ(I_j) = ∞\]
  Sei $ξ ∈ I, I ∩ [ξ - x, ξ + x]$ kompakt. $∀ x ∈ ℝ$ und von den ersten $K$ Elementen überdeckt. $K = K(ξ)$. Wir bekommen
  \begin{align*}
  \sum_{j = 1}^{∞} λ(I_j) &\geq \sum_{j = 1}^{k} λ(I_j) \underarrow[\geq]{Konstruktion} \sum_{j = 1}^{k} λ(J_i) - ε \\
  &\geq λ(I ∩ [ξ - x, ξ + x]) - ε \geq	x - \abs{ξ} - ε \\
  ⇒ \sum_{j = 1}^{∞} λ(I_j) &\geq x - \abs{ξ} - ε \xrightarrow{x \to ∞} ∞
  \end{align*}
  #+end_proof
** Messbare Funktionen
  #+begin_defn latex
  Seien $(X, Σ_X), (Y, Σ_Y)$, $f: X \to Y$ heißt *messbar* ($Σ_X - Σ_Y$ messbar) falls
  \[∀ A ∈ Σ_Y f^{-1}(A) ∈ Σ_X\]
  Ist $X$ ein topologischer Raum und $Σ_X$ die entsprechende Borel-\(σ\)-Algebra so nennen wir eine messbare Funktion die Borel-Funktion.
  #+end_defn
  #+begin_remark latex
  Es genügt, Messbarkeit für ein Messsystem $S ⊂ \mathcal{P}(Y)$ mit $Σ(S) = Σ_Y$ zu überprüfen. In der Tat ist $f^{-1}(A) ∈ Σ_X ∀ A ∈ S$ so folgt
  \begin{align*}
  f^{-1}(A^C) &= f^{-1}(Y \setminus A) = X \setminus f^{-1}(A) = (f^{-1}(A))^C ∈ Σ_x \\
  \intertext{weiter ist}
  f^{-1}(\bigcup_{k ∈ ℕ} A_k) &= \bigcup_{k ∈ ℕ} f^{-1}(A_k) ∈ Σ_x
  \end{align*}
  #+end_remark
  Wir werden häufig nutzen $(Y, Σ) = (ℝ^n, \mathcal{B}^n)$
  #+begin_lemma latex
  $f: (X, Σ) \to (ℝ^n, \mathcal{B}^n)$ ist genau dann messbar, wenn
  \[f^{-1}(I) ∈ Σ ∀ I = \bigtimes_{j = 1}^n (a_j, ∞), a_j ∈ ℝ\]
  insbesondere ist $f$ genau dann messbar, wenn jede seiner Komponenten $x \to \angl{f(x), e_i}, i = 1, \dots, n$ messbar ist
  und eine komplexwertige Funktion ist messbar genau dann wenn Real- und Imaginärteil messbar sind.
  #+end_lemma
  #+begin_proof latex
  Die \(σ\)-Algebra die von den verallgemeinerten Quadern erzeugt wird enthält die Quader der Form
  \[\bigtimes_{j = 1}^n (a_j, b_j)\]
  Diese bilden eine	Basis für die Topologie $⇒$ führen auf $\mathcal{B}^n$.
  #+end_proof
  #+begin_lemma latex
  Seien $(X, Σ_X), (Y, Σ_Y), (Z,Σ_Z)$ Messräume. Sind $f: X \to Y, g: Y \to Z$ messbar , dann ist auch $g \circ f: X \to Z$ messbar.
  Sind $X, Y$ topologische Räume, $Σ_X, Σ_Y$ \(\mathcal{B}\)-\(\mathcal{σ}\)-Algebren so ist jede stetige Funktion $f: X \to Y$ messbar.
  #+end_lemma
  #+begin_proof latex
  Das Urbild offener Mengen (diese erzeugen \(\mathcal{B}\)-\(σ\)-Algebra $Σ_Y$) ist aufgrund der stetigkeit offen, also messbar.
  Ist $C ∈ Σ_Z$ messbar, so ist es auch $B := g^{-1}(C) ∈ Σ_y$ und $A := f^{-1}(B) ∈ Σ_x$
  #+end_proof
  #+ATTR_LATEX: :options [1.36]
  #+begin_lemma latex
  Sind $f, g: (X, Σ) \to (ℝ, \mathcal{B})$ messbar, so auch $f + g, f - g$.
  #+end_lemma
  #+begin_proof latex
  Aus Stetigkeit von Addition und Subtraktion auf $(ℝ, \mathcal{B}) × (ℝ, \mathcal{B}) \to (ℝ, \mathcal{B})$ und Lemma 1.36.
  #+end_proof
  #+begin_remark latex
  Für $\bar ℝ := ℝ ∪ \{-∞, ∞\}$ ist $f: X \to \bar ℝ$ eine Borel-Funktion, wenn $f^{-1}(\{-∞;∞\})$ beiden Borel-Mengen sind und $f\big|_{X \setminus f^{-1}(\{\pm ∞\})}$ eine Borel-Funktion.
  #+end_remark
  #+ATTR_LATEX: :options [1.40]
  #+begin_lemma latex
  Sei $(f_k)$ eine Folge messbarer Funktionen $(X, \bar Z) \to (\bar ℝ, \bar{\mathcal{B}})$. Dann sind auch
  \[\sup_{k ∈ ℕ} f_k, \inf_{k ∈ ℕ} f_k, \limsup_{k \to ∞} f_k, \liminf_{k \to ∞} f_k\]
  messbar.
  #+end_lemma
** Integration
   #+begin_defn latex
   Eine messbare Funktion $f:(X, Σ) \to (ℝ, \mathcal{B})$ heißt *einfach*, wenn ihr Bild endlich ist, das heiß $∃ A_1, \dots, A_m ∈ Σ, α_1, \dots, α_m ∈ ℝ$ mit
   \[f = \sum_{j = 1}^{m} α_j χ_{A_j}\]
   wobei $χ_M$ die charakteristische Funktion ist.
   \[χ_M(x) = \begin{cases} 1 & x ∈ M \\ 0 & x \not ∈ M\end{cases}\]
   Wir können fordern, dass $A_j$ paarweise disjunkt	sind, $α_i \neq α_j, i \neq j$ und $\bigcup A_j = X$ gilt.
   \[⇒ f(x) = \{α_1, \dots, α_m\}, \qquad f^{-1}(\{α_j\})= A_j\quad ∀ j = 1, \dots, m\]
   und diese Darstellung ist eindeutig.	\\
   Den Vektorraum einfacher Funktionen bezeichnen wir mit $S(X,μ)$
   #+end_defn
   #+ATTR_LATEX: :options [Integral auf $S(X,μ)$]
   #+begin_defn latex
   Das Integral	einer nicht negativen einfachen	Funktion über die Menge $A ∈ Σ$ wird durch
   \[∫_A f \d μ := \sum_{j= 1}^{n} α_j μ(A_j ∩ A)\]
   erklärt, wobei wir $0 · ∞ = 0$ vereinbaren.
   #+end_defn
   #+begin_lemma latex
   Das Integral hat die folgenden Eigenschaften
   \begin{alignat*}{2}
   &1. \qquad ∫_A f \d ψ &&= ∫_X χ_A f \d μ \qquad \text{für } f ∈ S(X, μ) \\
   &2. \qquad ∫_{\bigcup_{k ∈ ℕ} B_k} f\d μ &&= \sum_{k ∈ ℕ} ∫_{B_k} f \d μ \qquad B_k \text{ paarweise disjunkt}, (B_k)_{k ∈ ℕ} ∈ Σ \\
   &3. \qquad ∫_A α f \d μ &&= α ∫_A f \d μ \qquad \text{für } α \geq 0 \\
   &4. \qquad ∫_A (f + g) \d μ &&= ∫_A f \d μ + ∫_A g \d μ \qquad \text{für } g \geq S(X,μ) \\
   &5. \qquad A ⊂ B, B ∈ Σ ⇒ ∫_A f \d μ &&\leq ∫_B f \d μ \\
   &6. \qquad f \leq g ⇒ ∫_A f \d μ &&\leq ∫_A g \d μ, g ∈ S(Σ,μ), g \geq 0
   \end{alignat*}
   #+end_lemma
   #+begin_proof latex
   1. aus Definition
   2. $\displaystyle{μ(A_j ∩ \bigcup_{n ∈ ℕ} B_n) = \sum_{k ∈ ℕ} μ(A_j ∩ B_k)}$ (man darf die Reihe über nichtnegative Zahlen umsortieren)
   3. klar
   4. Für
      \begin{align*}
	  f &= \sum_{j = 1}^{n} α_j χ_{A_j} \\
      g &= \sum_{k = 1}^{n} β_k χ_{B_k} \\
	  \intertext{gilt mit $C_{jk} = A_j ∩ B_k$}
	  ∫_A (f + g) \d μ &= \sum_{j,k} ∫_{C_{jk}} (f + g) \d μ = \sum_{j,k} (α_j + β_k) μ(C_{jk}) \\
	  &= \sum_{j,k} α_j μ(C_{jk}) + \sum_{j,k} β_k μ(C_{jk}) = ∫_A f\d μ + ∫_A g \d μ
      \end{align*}
   5. Aus Monotonie von $μ$
   6. Wie in 4. mit
	  \[∫_A f \d μ = \sum_{j,k} α_j μ(C_{jk}) \leq \sum_{j,k} β_k μ(C_{jk}) = ∫_A g \d μ\]
   #+end_proof
   #+ATTR_LATEX: :options [Integral  von nichtnegativen Funktionen]
   #+begin_defn latex
   Sei $(X, Σ, μ)$ Maßraum, $A ∈ Σ, f:(X,Σ) \to (ℝ, \mathcal{B})$ messbar und nichtnegtiv. Dann ist
   \[∫_A f \d μ := \sup \{∫_a g \d μ \mid g ∈ S(X, μ), g \leq f, g \geq 0\}\]
   #+end_defn
   #+begin_remark latex
   Bis auf 2. und 4. übertragen sich die Eigenschaften des Integrals über einfache Funktionen.
   #+end_remark
   #+ATTR_LATEX: :options [Monotone Konvergenz / Beppo Levi]
   #+begin_thm latex
   Sei $(f_k)_{k ∈ ℕ}$ eine Folge messbarer nichtnegativer Funktionen
   \[f_k:(X, Σ) \to (ℝ, \mathcal{B}) \quad\text{mit}\quad f_k \nearrow f\]
   ($f_k \nearrow f ⇒ f_k \xrightarrow{k \to ∞} f$ punktweise und (implizit aus Nichtnegativität) $\sum_{k = 1}^n f_k$ monoton) \\
   Dann ist für $A ∈ Σ$
   \[∫_A f_k \d μ \to ∫_A f \d μ\]
   #+end_thm
   #+begin_proof latex
   $f$ messbar,	damit erhält man die Monotonie von
   \[∫_A f_k \d μ\]
   und hieraus Konvergenz gegen $φ ∈ [0, ∞]$. Aus $f_k \leq f$ und Monotonie den Integral:
   \[φ \leq ∫_A f \dμ\]
   Für "\(\geq\)" nehmen wir $g ∈ S(X, μ), g \geq 0, g \leq f$ mit
   \[A_k := \{x ∈ A \mid f_k(x) \geq θ · g(x)\}\]
   für ein festes $θ ∈ (0,1)$ und hierraus
   \begin{align*}
   φ \xleftarrow{k \to ∞} ∫_A f_k \d μ &\geq ∫_{A_k} f_k \d μ \geq ∫_A θ g \d μ \\
   &\geq θ ∫_{A_k} g \d μ \to θ ∫_A g \d μ
   \end{align*}
   Insbesondere gilt für $θ = 1$
   \begin{align*}
   ⇒ φ &\geq ∫_A g \d μ \\
   ⇒ φ &= ∫_A f \d μ
   \end{align*}
   #+end_proof
   #+begin_remark latex
   $∀ f \geq 0$, mit einer monoton steigenden Folge nicht negativer einfacher Funktionen $(g_k)_{k ∈ ℕ}, g_k \nearrow f$ ist
   \[∫_A g_k \d μ \nearrow ∫_A f \d μ\]
   Eine geeignete Funktion ist
   \begin{align*}
   g_k(x) &:= \sum_{j = 0}^{k 2^k} \frac{j}{2^k} χ_{f^{-1}(A_j)}(x)
   \intertext{mit}
   A_j &= \{[\frac{j}{2^k}, \frac{j + 1}{2^k}\string) \mid j = 0, \dots, k 2^k - 1\}
   \end{align*}
   Ist $f$ gleichmäßig beschränkt $⇒$ $(g_k)_{k ∈ ℕ}$ konvergiert gleichmäcßig (denn $0 \leq f - g_k \leq \frac{1}{2^k}$ für $k$ groß genug)
   Mit Satz von Beppo Levi erhält man somit
   \begin{align*}
   2. \qquad ∫_{\bigcup_{k ∈ ℕ} B_k} f\d μ &= \sum_{k ∈ ℕ} ∫_{B_k} f \d μ \qquad B_k \text{ paarweise disjunkt}, (B_k)_{k ∈ ℕ} ∈ Σ \\
   4. \qquad ∫_A (f + g) \d μ &= ∫_A f \d μ + ∫_A g \d μ \qquad \text{für } g \geq S(X,μ) \\
   \end{align*}
   #+end_remark
   #+begin_lemma latex
   Ist $f \geq 0$ messbar, so wird durch
   \[ν(A) := ∫ f \d μ\]
   ein Maß mit
   \[∫ d \d ν = ∫ g f \d μ\]
   für jedes messbare $g \geq 0$ definiert (Bezeichnung: $\d ν = f \d μ$)
   #+end_lemma
   #+begin_proof latex
   \begin{align*}
   ν(\emptyset) &= ∫_{\emptyset} f \d μ = ∫ χ_{\emptyset} f \d μ = 0 · ∫ f \d μ = 0 \\
   ν(A ∪ B) &= ∫_{A ∪ B} f \d μ = ∫_A f \d μ + ∫_B \d μ = ν(A) + ν(B) \quad\text{für } A ∩ B = \emptyset \\
   \intertext{Für abzählbare Vereinigungen äquivalent}
   ν(\bigdcup_{k ∈ ℕ} A_k) &= \sum_{k ∈ ℕ} ν(A_k) \\
   \end{align*}
   Ist $g$ einfach und $\geq 0$
   \[⇒ g = \sum_{i = 1}^{n} α_j χ_{B_j}\]
   für disjunkte $B_j ∈ Σ, \bigcup B_j = X, α_j \geq 0$
   \begin{align*}
   ∫ g \d ν &= \sum_{j = 1}^{n} α_j ν(A_j) = \sum_{j = 1}^{n} α_j ∫_{B_j} f \d μ = \sum_{j = 1}^{n} ∫ α_j f χ_{B_j} \d μ \\
   &= ∫ \sum_{j = 1}^{n} \underbrace{(α_j χ_{B_j})}_{= g} f \d μ = ∫ g f \d μ
   \end{align*}
   Appoximation liefert die Behauptung für beliebigte $g \geq 0$.
   #+end_proof
   #+ATTR_LATEX: :options [Fatou Lemma]
   #+begin_thm latex
   Sei $(X, Σ, μ)$ ein Maßraum. Ist $f_k$ eine Folge nicht-negativer Funktionen $(X, Σ) \to (ℝ, \mathcal{B})$ so gilt $∀ A ∈ Σ$
   \begin{align*}
   ∫_A \liminf_{k \to ∞} f_k \d μ &\leq \liminf_{k \to ∞} ∫_A f_k \d μ
   \end{align*}
   #+end_thm
   #+begin_proof latex
   Wir setzen $g_k := \inf_{j \geq k} f_j$, also
   \[g_k \nearrow \liminf_{j \to ∞} f_j\]
   Weiterhin $g_k \leq f_k ∀ k ∈ ℕ$
   \[⇒ ∫_A g_k \d μ \leq ∫_A f_k \d μ\]
   Übergang zum $\liminf$
   \begin{align*}
   ⇒ \liminf ∫ g_k \d μ &= \lim_{k \to ∞} ∫ g_k \d μ = ∫_A \lim_{k \to ∞} g_k \d μ \\
   &= ∫_A \liminf_{k \to ∞} f_k \d μ
   \end{align*}
   #+end_proof
   #+begin_remark latex
   Im Allgemeinen können wir keine Gleichheit erwarten. Zum Beispiel ist für $f_x := χ_{(k,k + 1)}, k ∈ ℕ$ einerseits $f_k(x) \to 0$ punktweise,
   andererseits
   \[∫_ℝ f_k \d x = 1, f_k = k χ_{(0,\frac{1}{k})} \text{ und } f_k = \frac{1}{k} χ_{(0,k)}\]
   #+end_remark
   #+begin_defn latex
   Sei $(X, Σ, μ)$ ein Maßraum, $A ∈ Σ$ und $f:(X, Σ) \to (ℝ, \mathcal{B})$ messbar. Ist
   \[∫_A f^{\pm} \d μ < ∞\]
   so nennen wir $f$ integrierbar über $A$ und wir setzen
   \[∫A f \d μ = ∫_A f^{+} \d μ - ∫_A f^{-} \d μ ∈ ℝ\]
   Die Menge der über $A$ integrierbaren Funktionen bezeichnen wir mit $\mathcal{L}^1(A,μ)$
   #+end_defn
   #+begin_lemma latex
   Unter den Bedingungen der Defininiton ist das Integral linear und es erfüllt sämtlich Eigenschaften von Lemma 1.39.
   Eine	Funktion ist genau dann integrierbar, wenn ihr Betrag integrierbar ist. Darüber hinaus gilt für integrierbare Funktionen $f,g: X \to ℝ$
   \[\abs{∫_A f \d μ} \leq ∫_A \abs{f} \d μ \quad\text{und}\quad ∫_A \abs{f + g} \d μ \leq ∫_A \abs{f} \d μ + ∫_A \abs{g} \d μ\]
   #+end_lemma
   #+begin_proof latex
   Die Linearität und die Eigenschaften aus dem Lemma 1.39 wird dem geneigten Leser überlassen. Setze $φ := ∫_A f \d μ$, dann ist
   \[\abs{φ} = (\sgn φ) φ = ∫_A (\sgn φ) f \d μ \leq ∫_A \abs{f} \d μ\]
   Die Dreiecksungleichung folgt aus $\abs{f + g} \leq \abs{f} + \abs{g}$ und der Linearität des Integrals.
   #+end_proof
   #+begin_lemma latex
   Sei $(X, Σ, μ)$ ein Maßraum, $f: X \to ℝ$ messbar.
   1. $∫_X \abs{f} \d μ = 0 ⇔ f(x) = 0$ für \(μ\)-fast alle $x ∈ X$
   2. Ist $f$ außerdem integrierbar oder nicht negativ  und $A ∈ Σ$ so gilt
	  \[μ(A) = 0 ⇒ ∫_A f \d μ = 0\]
   #+end_lemma
   #+begin_proof latex
   Übungen.
   #+end_proof
   #+begin_lemma latex
   Sei $(X, Σ, μ)$ ein Maßraum, $A ∈ Σ, (f_k)_{k ∈ ℕ}$ eine Folge aus messbaren Funktionen mit $f_k: X \to ℝ ∀ k ∈ ℕ$ und $g: X \to ℝ$ integrierbar, dann gilt
   \begin{align*}
   ∫_A \liminf_{k \to ∞} f_k \d μ &\leq \liminf_{k ∈ ∞} ∫_A f_k \d μ \quad\text{falls } g \leq f_k ∀ k ∈ ℕ \\
   \limsup_{k \to ∞} f_k \d μ &\leq ∫_A \limsup_{k ∈ ∞} f_k \d μ \quad\text{falls } f_k \leq g ∀ k ∈ ℕ \\
   \end{align*}
   #+end_lemma
   #+begin_proof latex
   Man wende für die erste Ungleichung das Fatou-Lemma auf $f_k - g$ an und subtrahiere $∫_A g \d μ$ auf beiden Seiten. Die zweite Ungleichung folgt mit $\liminf(-f_k) = - \limsup f_k$.
   #+end_proof
   #+ATTR_LATEX: :options [Satz von der dominierten Konvergenz]
   #+begin_thm latex
   Sie $(X, Σ, μ)$ ein Maßraum, $A ∈ Σ, (f_k)$ ein Folge messbarer Funktionen von $X$ nach $ℝ$, die punktweise fast überall gegen ein $f: X \to ℝ$ konvergiere.
   (Punktweise fast überall bedeutet: $f_k(x) \to f(x)$ für \(μ\)-fast alle von $X$).
   Gibt es eine Majorante, dah heißt eine integrierbare Funktion $g: X \to ℝ$ mit $\sup_{k ∈ ℕ} \abs{f_k} \leq g$ so ist auch $f$ integrierbar und wir erhalten
   \[∫_A f_k \d μ \xrightarrow{k \to ∞} ∫_A f \d μ\]
   #+end_thm
   #+begin_proof latex
   Nach Vorraussetzung ist $-g \leq f_k \leq g$ für alle $k ∈ ℕ$ und folglich erhalten wir mit dem erweiterten Fatou-Lemma
   \[∫_A f = ∫A \liminf_{k \to ∞} f_k \d μ \leq \liminf_{k \to ∞} ∫_a f_k \d μ \leq \limsup_{k \to ∞} ∫_A f_k \leq ∫_A \limsup_{k \to ∞} f_k \d μ = ∫_A f \d μ\]
   #+end_proof
   #+begin_remark latex
   Für stetige und Lebesgue-integrierbare Funktionen auf reellen Intervallen stimmen Riemann- und Lebesgue-Integrierbarkeit überein. Ist $f$ stetig auf einem kompakten Intervall, so ist $f$
   beschränkt und messbar, also Lebesgue-Integrierbar. \\
   Allgemeiner ist jede beschränkte, messbare Funktion auf einem kompakten Intervall genau dann Riemann-integrierar, wenn die Menge ihrer Unstetigkeiten eine Lebesgue-Nullmenge ist.
   In diesem Fall stimmen die beiden Integralbegriffe überein. Diese Aussage gilt nicht für verallgemeinerte Intervalle.
   #+end_remark
   #+begin_ex latex
   \[∫_0^∞ \frac{\sin(x)}{x}\d x\]
   existiert als Riemann-Integral
   \[\lim_{R \to ∞} ∫_0^R \frac{\sin(x)}{x} \d x\]
   andererseits
   \[∫_0^∞ \abs{\frac{\sin(x)}{x}} \d x = ∞\]
   also keine Lebesgue-Integrierbarkeit.
   #+end_ex
** Produktmaße
   Notation: Für Messräume $(X_1, Σ_1),(X_2,Σ_2)$ bezeichnen wir die \(σ\)-A-gebra, die alle "Rechtecke" der $A_1 × A_2$ mit $A_1 ∈ Σ_1, A_2 ∈ Σ_2$ enthält mit $Σ_1 \otimes Σ_2$.
   #+begin_lemma latex
   Für Messräume $(X_1, Σ_1), (X_1, Σ_2)$ und $A ∈ Σ_1 \otimes Σ_2$ liegen die Schnitte
   \begin{align*}
   A_1(x_2) &:= \{x_1 ∈ X_1 \mid (x_1, x_2) ∈ A\} \\
   A_2(x_1) &:= \{x_2 ∈ X_2 \mid (x_1, x_2) ∈ A\}
   \end{align*}
   in $Σ_1$	beziehungsweise $Σ_2$
   #+end_lemma
   #+begin_proof latex
   Setze $S := \{A ∈ Σ_1 \otimes Σ_2 \mid A_1(x_2) ∈ Σ_1\}$. Natürlich gilt $A_1 × A_2 ∈ S$ für
   alle $A_1 ∈ Σ_1, A_2 ∈ Σ_2$. Isofern genügt es zu zeigen, dass $S$ eine \(σ\)-Algebra bildet. In der Tat ist $X_1 × X_2 ∈ S$ und für $A ∈ S$ ist
   \[(A^C)_1 (x_2) = \{x_1 ∈ X_1 \mid (x_1, x_2) ∈ A^C\} = \{x_1 ∈ X_1 \mid (x_1, x_2) ∈ A\}^C = (A_1(x_2))^C ∈ Σ_1\]
   Für $(A_k)_{k ∈ ℕ} ⊂ S$ haben wir
   \[(\bigcup_{k ∈ ℕ} A_k)_1 (x_2) = \{x_1 ∈ X_1 \mid (x_1, x_2) ∈ \bigcup_{k ∈ ℕ} A_k\} = \bigcup_{k ∈ ℕ} \{x_1 ∈ X_1 \mid (x_1, x_2) ∈ A_k\} = \bigcup_{k ∈ ℕ} (A_k)_1(x_2) ∈ Σ_1\]
   Für $A_2(x_1)$ argumentiert man analog.
   #+end_proof
   #+begin_korollar latex
   Seien $(X_1, Σ_2), (X_2, Σ_2)$ Messräume und sei $f:(X_1 × X_2, Σ_1 \otimes Σ_2) \to (ℝ, \mathcal{B})$ messbar. Dann ist auch $x_1 ↦ f(x_1, x_2)$ für jedes $x_2 ∈ X_2$ auf $X_1$ messbar und
   entsprechend $x_2 ↦ f(x_1, x_2)$ für jedes $x_1 ∈ X_1$ auf $X_2$
   #+end_korollar
   #+begin_proof latex
   Für $B ∈ \mathcal{B}$ und $x_2 ∈ X_2$ ist $f^{-1}(·,x_2)(B) ∈ Σ_1$, denn für $A = f^{-1}(B), A ∈ Σ_1 \otimes Σ_2$ ist
   \[f^{-1}(·,x_2)(B) = \{x_1 ∈ X_1 \mid f(x_1, x_2) ∈ B\} = \{x_1 ∈ X_1 \mid (x_1, x_2) ∈ A\} = A_1(x_2)\]
   #+end_proof
