* Numerische Integration
  Approximation von bestimmten Integralen reeller Funktionen $f ∈ C[a, b]$ durch Quadraturformeln
  \[I(f) = ∫_a^b f(x) \d x \approx I^{(n)}(f) = \sum_{i = 1}^{n} α_i f(x_i)\]
  mit Stützstellen $a \leq x_0 < x_1 < \dots < x_n \leq b$ und Gewichten $α_i ∈ ℝ$.
  #+ATTR_LATEX: :options [Summierte Rechteckregel]
  #+begin_ex latex
  \[∫_a^b f(x) \d x \approx \sum_{i = 0}^{n - 1}(x_{i + 1} - x_i) f(x_i)\]
  #+end_ex
  Interpolatorische Quadraturformeln. \\
  Idee: Interpoliere $f$ durch ein Interpolationspolynom auf $[a, b]$!
  \[p_n(x) = \sum_{i = 0}^{n} f(x_i) L_i^{(n)}(x)\]
  \[⇒ I^{(n)}(f) = ∫_a^b p_n(x) \d x = \sum_{i = 0}^{n} f(x_i) ∫_a^b \underbrace{L_i^{(n)}(x) \d x}_{= α_i}\]
  Quadraturgewichte hängen nur von $a, x_0, \dots, x_n, b$ ab.
  #+ATTR_LATEX: :options [Lagrange-Quadratur]
  #+begin_thm latex
  Für interpolatorische Quadraturformeln gilt
  \[I(f) - I^{(n)}(f) = ∫_a^b f[x_0, \dots, x_n, x] \prod_{i = 0}^n (x - x_i) \d x\]
  #+end_thm
  #+begin_proof latex
  Restglieddarstellung der Interpolation.
  #+end_proof
  #+begin_defn latex
  Eine Quadraturformel $I^{(n)}$ wird "von der Ordnung $m$" genannt, wenn sie alle $p ∈ P_{m - 1}$ exakt integriert. Das heißt
  \[∫_a^b p(x) \d x = I^{(n)}(p) ∀ p ∈ P_{m - 1}\]
  $⇒$ Interpolatorische Quadraturformeln zu $n + 1$ Stützstellen sind (mindestens) von der Ordnung $n + 1$.
  #+end_defn
  Spezialfall: Äquidistante Stützstellen: Newton-Cotes-Formeln:
  1. Abgeschlossene Formeln ($H = \frac{b - a}{n}, x_i = a + iH, a = x_0, b = x_n$)
	 \begin{align*}
	 I^{(1)}(f) &= \frac{b - a}{2}[f(a) + f(b)] \tag{Trapezregel} \\
	 I^{(2)}(f) &= \frac{b - a}{6}[f(a) + 4f(\frac{a + b}{2}) + f(b)] \tag{Simpsonregel, Keplersche Fassregel} \\
	 I^{(3)}(f) &= \frac{b - a}{8}[f(a) + 3f(a + H) + 3f(b - H) + f(b)] \tag{$3/8$ Regel}
     \end{align*}
  2. Offene Formeln $(H = \frac{b - a}{n + 2}, x_i = a + (i + 1)H, a < x_0, x_n < b)$
	 \begin{align*}
	 I^{(0)}(f) &= (b - a) f(\frac{a + b}{2}) \tag{Mittelpunktregel} \\
	 I^{(1)}(f) &= \frac{(b - a)}{2} (f(a + H) + f(b - H)) \\
	 I^{(1)}(f) &= \frac{(b - a)}{3} (2f(a + H) - f(\frac{a + b}{2}) + 2f(b - H)) \\
     \end{align*}
  #+ATTR_LATEX: :options [Quadraturrestglieder]
  #+begin_thm latex
  1. Trapezregel: Für jedes $f ∈ C^2[a, b]$ gibt es ein $ξ ∈ [a, b]$ mit
	 \[∫_a^b f(x) \d x - \frac{b - a}{2}[f(a) + f(b)] = -\frac{(b - a)^3}{12}f''(ξ)\]
  2. Simpson-Regel: Für jedes $f ∈ C^4[a, b] ∃ ξ ∈ [a, b]$ sodass
	 \[∫_a^b f(x) \d x - \frac{b - a}{6}[f(a) + 4f(\frac{a + b}{2}) + f(b)] = - \frac{(b - a)^5}{2880}f^{(4)}(ξ)\]
  3. Mittelpunktregel: $∀ f ∈ C^2[a, b] ∃ ξ ∈ [a, b]$ sodass
	 \[∫_a^b f(x)\d x - (b - a)f(\frac{a + b}{2}) = \frac{(b - a)^3}{24} f''(ξ)\]
  #+end_thm
  #+ATTR_LATEX: :options [Verallgemeinerter Mittelwertsatz]
  #+begin_thm latex
  Sei $f ∈ C[a, b], g \geq 0$ oder $g \leq 0$ integriebar. Dann $∃ ξ ∈ [a, b]$, sodass
  \[∫_a^b f(x) g(x) \d x = f(ξ)∫_a^b g(x) \d x\]
  #+end_thm
  #+begin_proof latex
  (Beweis der Quadraturrestglieder).
  1. Für $x ∈ [a, b]$ ist $(x - a)(x - b) \leq 0$
	 \begin{align*}
	 ⇒ I(f) - I^{(1)}(f) &= ∫_a^b f[x_0, x_1, x] \prod_{i = 1}^1 (x - x_i) \d x \\
	 \intertext{Verallgemeinerter Mitterwertsatz: $∃ ξ ∈ [a, b]$, sodass}
	 &= \frac{f''(ξ)}{2!} (-\frac{1}{6}(b - a)^3) \\
	 &= - \frac{f''(ξ)}{12}(b - a)^3
     \end{align*}
  2.
	  \begin{align*}
	  I(f) - I^{(2)}(f) &= ∫_a^b f[a, \frac{a + b}{2}, b, x](x - a)(x - \frac{a + b}{2})(x - b) \\
	  &= ∫_a^b \frac{f[a, \frac{a + b}{2}, b, x] - f[\frac{a + b}{2}, a, \frac{a + b}{2}, b]}{x - \frac{a + b}{2}}(x - a)(x - \frac{a + b}{2})^2(x - b) \d x + f[\frac{a + b}{2}, a, \frac{a + b}{2}, b]∫_a^b (x - a)(x - \frac{a + b}{2})(x - b) \d x \\
	  &= \frac{f^{(4)}(ξ)}{4!}∫_a^b (x - a)(x - \frac{a + b}{2})^2 (x - b) \d x \\
	  &= -\frac{f^{(4)}(ξ)}{2880}(b - a)^5
      \end{align*}
  3. analog zu 2.
  #+end_proof
  Probleme:
  - negative Gewichte $α_i$ ab $n = 7$ (geschlossen) und $n = 2$ (offen) $⇒$ Auslöschungsgefahr
  -	Oszillationen des Lagrange-Interpolanten für äquidistante Gitter (Runge-Phänomen), im Allgemeinen $I^{(n)}(f) \not \to I(f), n \to ∞$
  Abhilfe: Summierte Quadraturformeln
  \[I_n^{(n)}(f) = \sum_{i = 1}^{N - 1}I_{[x_i, x_i + 1]}^{(n)}(f), h = \frac{b - a}{N}, x_i = a + ih\]
  Gilt die lokale Fehlerdarstellung:
  \[I_{[x_i, x_{i + 1}]}(f) - I_{[x_i, x_{i + 1}]}^{(n)}(f) = ω_n h^{n + 2} f^{(m + 1)}(ξ_i), \quad ξ_i ∈ [a, b]\]
  für $m \geq n$ gilt:
  \begin{align*}
  I(f) - I_{n}^{(n)}(f) &= \sum_{i = 0}^{N - 1}[I_{[x_i, x_{i + 1}]}(f) - I_{[x_i, x_{i + 1}]}^{(n)}(f)] \\
  &= ω_n h^{m + 2} N \underbrace{\sum_{i = 0}^{N - 1} \frac{f^{(m + 1)}(ξ_i)}{N}}_{∈ [\min_i f^{(m + 1)}(ξ_i), \max_i f^{(m + 1)}(ξ_i)]} \\
  &= ω_n h^{m + 2} N f^{(m + 1)}(ξ) \tag{für ein $ξ ∈ [a, b]$ (Verallg. Mittelwertsatz)} \\
  &= ω_n h^{(m + 1)}(b - a)f^{(m + 1)}(ξ)
  \end{align*}
  #+begin_ex latex
  1. Summierte Trapezregel $(m = 1)$
	 \begin{align*}
	 I_h^{(1)} &= \sum_{i = 0}^{N - 1}\frac{x_{i + 1} - x_i}{2}[f(x_i) + f(x_{i + 1})] \\
	 &= \frac{h}{2} f(a) + h \sum_{i = 1}^{N - 1} f(x_i) + \frac{h}{2}f(b) \\
	 I(f) - I_{h}^{(n)}(f) &= -\frac{b - a}{12} h^2 f''(ξ), ξ ∈ [a, b]
     \end{align*}
  2. Summierte Simpson-Regel $(m = 3)$
	 \begin{align*}
	 I_h^{(2)}(f) &= \sum_{i = 0}^{N - 1} \frac{x_{i + 1} - x_i}{6}[f(x_i) + 4f(\frac{x_i + x_{i + 1}}{2}) + f(x_{i + 1})] \\
	 &= \frac{h}{6}[f(a) + 2 \sum_{i = 1}^{N - 1} f(x_i) + 4 \sum_{i = 0}^{N - 1}f(\frac{x_i + x_{i + 1}}{2}) + f(b)] \\
	 I(f) - I_h^{(2)}(f) &= -\frac{b - a}{2880}h^4 f^{(4)}(ξ), ξ ∈ [a, b]
     \end{align*}
  3. Summierte Mittelpunktsregel $(m = 1)$
	 \begin{align*}
	 I_h^{(0)}(f) &= \sum_{i = 0}^{N - 1}(x_{i + 1} - x_i)f(\frac{x_i + x_{i + 1}}{2}) = h \sum_{i = 0}^{N - 1}f(\frac{x_i + x_{i + 1}}{2}) \\
	 I(f) - I_h^{(0)}(f) &= \frac{b - a}{24} h^2 f''(ξ), \quad ξ ∈ [a, b]
     \end{align*}
  #+end_ex
  Widerholung Quadratur
  \[∫_a^b f(x) \d x \approx \sum_{i = 0}^{n} α_i f(x_i) = I^{(n) f}\]
  - Interpolatorische Quadraturregel, Äquidistante Stützstellen \\
    $\to$ Newton-Cotes Formeln (abgeschlossen, offen)
  - Summierte Formeln $x_i = a + i H, H > 0$
	\[I_H^{(n)}(f) = \sum_{i = 1}^{n} I_{[x_{i - 1}, x_i]}^{(n)}(f)\]
** Gaußsche Quadraturformeln
   Frage: Wie wählt man $x_i$ in
   \[I^{(n)}(f) = \sum_{i = 0}^{N} α_i f(x_i)\]
   optimal? Nach Konstruktion ist $I^{(n)}$ mindestens von der Ordnung $n + 1$
   #+begin_lemma latex
   Interpolatorische Quadraturformeln sind höchstens von der Ordnung $2n + 2$
   #+end_lemma
   #+begin_proof latex
   Wähle
   \begin{align*}
   p(x) &= \prod_{i = 0}^n (x - x_i)^2 ∈ P_{2 n + 2} \\
   ⇒ 0 &< ∫_a^b p(x) \d x = \sum_{i = 0}^{n} α_i \underbrace{p(x_i)}_{0} = 0 \lightning
   \end{align*}
   #+end_proof
   Gaußsche Quadraturformen erreichen die Maximalordnung $2n + 2$ (exakt für $p ∈ P_{2n + 1}$)
   Herleitung: Für $x_0, \dots, x_n, x_{n + 1}, \dots, x_{2n + 1} ∈ [a, b]$ betrachte $I^{(n)}(t)$ und I^{(2n + 1)}(f)
   \begin{align*}
   I(f) - I^{(2n + 1)}(f) &= I(f) - \sum_{i = 0}^{2n + 1} f[x_0, \dots, x_i] \big|_a^b ∫_a^b \prod_{j = 0}^{i - 1} (x - x_j) \d x \\
   &= I(f) - I^{(n)}(f) - \sum_{i= n + 1}^{2n + 1}f[x_0, \dots, x_i] ∫_a^b \prod_{j = 0}^{i - 1}(x - x_j) \d x \\
   \intertext{Für $i > n$ gilt}
   ∫_a^b \prod_{j = 0}^{i - 1}(x - x_j) \d x &= ∫_a^b \underbrace{\prod_{j = 0}^{n}(x - x_j)}_{P_{n + 1}} \underbrace{\prod_{j = n + 1}^{i - 1} (x - x_j)}_{∈ P_n} \d x \\
   \intertext{Wähle Stützstellen so, dass}
   0 &= ∫_a^b \prod_{j = 0}^n (x - x_j) q(x) \d x = (\prod_{j = 0}^n (x - x_j), q) ∀ q ∈ P_n \\
   I(f) - I^{(n)}(f) &= I(f) - I^{(2n + 1)}(f) \\
   \end{align*}
   $⇒ I^{(n)}$ ist exakt für $p ∈ P_{2n + 1}$, das heißt von Ordnung $2n + 2$. Mit einem Orthogonalsystem $\{p_0, \dots, p_{n + 1}\}$ von $P_{n + 1}$ sind die Nullstellen
   $λ_0, \dots, λ_n$ von $p_{n + 1}$ von Interesse. Frage: Sind die Nullstellen von $p_{n + 1}$ reell, einfach und in $[a, b]$?
   #+begin_thm latex
   Gegeben sei ein Skalarprodukt auf $C[a, b]$
   \[(f, g)_ω = ∫_a^b f(x) g(x) ω(x) \d x\]
   mit integrierbarer Gewichtsfunktion $ω(x) \geq 0, x ∈ (a, b)$ mit höchstens endlich vielen Nullstellen. Dann haben die mittels Gram-Schmidt aus \{1, x^1, \dots\} bezüglich $(·,·)_ω$ orthogonalisierten Polynome
   $\{p_0, p_1, \dots\}$ lauter reelle, einfache Nullstellen in $[a, b]$
   #+end_thm
   #+begin_proof latex
   Sei $N_n := \{λ ∈ (a, b) \mid λ \text{ Nullstelle ungerader Vielfachheit von } p_n\}$. Setze
   \[q(x) = \begin{cases} 1 & N_n \neq \emptyset \\ \prod_{i = 1}^m (x - λ_i) & N_n = \{λ_1, \dots, λ_m\}, m > 0\end{cases}\]
   Nach dem Fundamentalsetz der Algebra und wegen $p(x) = x^n - r(x), r ∈ P_{n - 1}$, nach Konstruktion mit Gram-Schmidt (ohne Normalisieren) gilt
   \[p_n(x) = \prod_{i = 1}^n (x - λ_i), λ_i ∈ ℂ, i = 1, \dots, n\]
   Ist $λ_I$ nicht reell, so ist $\bar λ_i$ auch eine Nullstellen von $p_N$ und
   \[(x - λ_i)x - \bar λ_i\ = (x - λ_I)(x - λ_i) ⇒ \abs{x - λ_i}^2 \geq 0\]
   $⇒ p_n q ∈ P_{n + m}$ ist reell und hat in $[a, b]$ keinen Vorzeichenwechsel.
   \[(p_n, q)_ω = ∫_a^b p_n(x) (x) ω(x) \d k \neq 0\]
   Für $m < n$ ist das ein Wiederspruch zu $p_n \perp p_{n - 1} ⇒ μ_n = \{λ_1, \dots, λ_n\}$. Für $[a, b] = [-1, 1]$ und  $ω \equiv 1$, das heißt $(·, ·)_ω = (·,·)_2$
   sind die $p_n$ mittels $p_n(x) = x^n + \dots$ mormiere Legendre-Polynome $L_n$(x). Wir wählen also die Nullstellen $ζ_0,ndots, λ_n$ von $p_{n + 1}$ beziehungsweise $L_{n + 2}$ als
   Stützstellen einer interpolatorischen Quadraturformel auf $[-1, 1]$.
   \[I^{(n)}(f) = \sum_{i = 9}^{n} α_i f(λ_i), α_i = ∫_{-1}^1 \prod_{\substack{j = 0 \\ j \neq i}} \frac{x - λ_j}{λ_i - λ_j} \d x\]
   #+end_proof
   #+ATTR_LATEX: :options [Gauß-Quadratur]
   #+begin_thm latex
   Es gibt genau eine interpolatorische Quadraturformel zu $n + 1$ paarweise verschiedenen Stützstellen auf $[-1, b]$ mit Ordnung $2n + 2$. Ihre Stützstellen sind gerade die Nullstellen.
   $λ_0, \dots, λ_n ∈ (-1, 1)$ das $(n + 1)$ - ten Legendre Polynom $L_{n + 1} ∈ P_{n + 1}$ und die Gewichte erfüllen
   \[α_i = ∫_{-1}^1 \prod_{\substack{j = 0 \\ j \neq i}} (\frac{x - λ_j}{λ_i - λ_j})^2 \d x > 0, i = 0, \dots, n\]
   Für $f ∈ C^{2 n + 2}[-1, 1]$ besitzt des Restglied die Darstellung
   \[R^{(n)} = \frac{f^{(2n + 2)}(ξ)}{(2n + 2)!} ∫_{-1}^1 \prod_{j = 0}^n (x - λ_j)^2 \d x, ξ ∈ (-1, 1)\]
   #+end_thm
   #+begin_proof latex
   *Existenz*:
   Es gilt $p_{n + 1} \perp P_n$ Für $ω = 1$ und $p_n(x) = \prod_{i = 0}^n(x - λ_i) = x^n + \dots$
   \[⇒ I^{(n)}(f) = I^{(2n + 1)}(f)\]
   $⇒ I^{(n)}$ hat Ordnung $2n + 2$. Gewichte:
   \[L_i^{(x)}(x) = \prod_{\substack{j = 0 \\ j \neq i}}^n \frac{x - λ_j}{λ_i - λ_j} ∈ P_n\]
   $⇒ (L_i^{(n)}(x))^2 ∈ P_{2n}$
   \[⇒ 0 < ∫_{-1}^1 (L_i^{(n)})^2 \d x = \sum_{j = 0}^{n} α_j \underbrace{(L_i^{(n)}(x_i))}_{δ_{ij}} = α_i\]
   *Eindeutigkeit*: Sei $\tilde I^{(n)}(f) = \sum_{i = 0}^{n} \tilde a_I f(\tilde λ_i)$ ebenfalls der Ordnung $2n + 2$. Wie oben folgt $\tilde α_i > 0$ mithilfe
   \[\tilde L_i^{(n)}(x) = \prod_{j = 0 \\ j \neq i}^n \frac{n - \tilde λ_j}{\tilde λ_i - \tilde λ_j}\]
   \begin{align*}
   0 &= ∫_{-1}^1 \frac{1}{\tilde α_i} \tilde L_i^{(n)} p_{n + 1}(x) \d x \\
   &= \sum_{j = 0}^{n} \frac{\tilde α_i}{\tilde α_i} \underbrace{\tilde L_i^{(n)} (\tilde λ_j)}_{δ_{ij}} p_{n + 1}(\tilde λ_j) = p_{n + 1}(\tilde λ_i), i = 0, \dots, n
   \end{align*}
   $⇒ \tilde λ_i = λ_i$ und $\tilde α_i = α_i, i = 1, \dots, n$. \\
   *Restglied*: Für $f ∈ C^{(2n + 2)}[-1, 1]$ hat der Hermite-Interpolant $h ∈ P_{2n + 1}$ zu den Bedingungen
   \[h(λ_i) = f(λ_i), h'(λ_i) = f'(λ_i), i = 0, \dots, n\]
   die Darstellung:
   \[f(x) - h(x) = f[λ_0, λ_0, \dots, λ_n, λ_n, x] \prod_{i = 0}^n (x - λ_i)^2\]
   \begin{align*}
   ⇒ I(f) - I^{(f)} &= I(f) - \underbrace{I^{(n)}(h)}_{= I(h)} - (I^{(n)}(f) - I^{(n)}(h)) \\
   &= I(f - h) - I^{(n)}(f - h) \\
   &= ∫_{-1}^1 f[λ_0, λ_0, \dots, λ_n, λ_n] \underbrace{\prod_{i = 0}^n (x - λ_i)^2}_{> 0} \d x - \underbrace{\sum_{i = 0}^{n} α_i [f(λ_i) - h(λ_i)]}_{0} \\
   \intertext{Mit verallgemeinertem Mittelwertsatz folgt:}
   &= \frac{f^{(2n + 2)}(ξ)}{(2n + 2)!} ∫_{-1}^1 \prod_{i = 0}^n (x - λ_i)^2 \d x
   \end{align*}
   #+end_proof
   Die $λ_i^{(n)}$ (Nullstellen von $p_{n + 1}$) und die dazugehörigen $α_i$ lassen sich tabellieren. Durch Transformation von $[a, b]$ auf $[-1, 1]$ erhält man eine allgemeine Quadraturformel.
   #+ATTR_LATEX: :options [Konvergenz der Gauß-Quadratur]
   #+begin_thm latex
   Sei $I^{(n)}(f)$ die $(n + 1)$ punktige Grauß-Formel zur Berechnung von $I(f) = ∫_{-1}^1 f(x) \d x$. Für jedes $f ∈ C[-1, 1]$ konvergiert $I^{(n)}(f) \xrightarrow{n \to ∞} I(f)$
   #+end_thm
   #+begin_proof latex
   Es gilt
   \[I^{(n)}(f) = \sum_{i = 0}^{n} α_i^{(n)} f(λ_i^{(n)}), α_i^{(n)} > 0, \sum_{i = 0}^{n} α_i^{(n)} = 2\]
   Sei $ε > 0$. Nach dem Weierstrassschem Approximationssatz gibt es $p_ε ∈ P_n$ mit
   \[\max_{x ∈ [-1, 1]} \abs{f(x) - p_ε(x)} \leq \frac{ε}{4}\]
   Für $n > \frac{1}{2}m - 1$ (das heißt $2n + 2 > m$) gilt
   \[\abs{I(f) - I^{(n)}(f)} \leq \underbrace{\abs{I(f - p_ε)}}_{\leq \frac{ε}{4}2} + \underbrace{\abs{I(p_ε) - I^{(n)}(p_ε)}}_{0} + \underbrace{\abs{I^{(n)}(f - p_ε)}}_{\leq \frac{ε}{4}2} \leq ε\]
   #+end_proof
   Wiederholung: Gauß-Quadratur
   - $n + 1$ Stützstellen, Ordnung $2n + 2$ (optimal)
   - $x_i$ Nullstellen des Legendre Polynoms $p_{n + 1}$
   - $I^{(n)}(f) \xrightarrow{n \to ∞} I(f)$ für $f$ stetig
   - Verallgemeinerung auf gewichtete Integrale
	 \[∫_a^bf(x) ω(x) \d x I(fω) I_ω(f)\]
	 $⇒$ Orthogonalisiere bezüglich
	 \[(f,g)_ω = ∫_a^b f(x) g(x) ω(x) \d x\]
** Praktische Aspekte der Quadratur
   Ziel: Möglichst hohe Genauigkeit bei möglichst wenig Funktionsauswertungen. Schwierigkeiten:
   - Fehlerschätzung: $f^{(k)}$ nur schwer zugänglich für $k > 2$ $⇒$ a-posteriori Fehlerschätzer.
     #+begin_ex latex
	 1. Vergleiche $I_n(f)$ und $I_{\frac{n}{2}}(f)$ bei summierten Quadraturformeln
	 2. Extrapolationfehler
     #+end_ex
   - Wiederbenutzung bereits berechneter Werte von $f$
	 - schwierig bei Gauß
	 - einfach bei Newton-Cotes
