#+AUTHOR: Robin Heinemann
#+TITLE: Analysis I (Marciniak-Czochra)
#+OPTIONS: H:6
#+LATEX_CLASS: koma-article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage{siunitx}%
#+LATEX_HEADER: \usepackage{fontspec}%
#+LATEX_HEADER: \sisetup{load-configurations = abbrevations}%
#+LATEX_HEADER: \newcommand{\estimates}{\overset{\scriptscriptstyle\wedge}{=}}%
#+LATEX_HEADER: \usepackage{mathtools}%
#+LATEX_HEADER: \DeclarePairedDelimiter\abs{\lvert}{\rvert}%
#+LATEX_HEADER: \DeclarePairedDelimiter\norm{\lVert}{\rVert}%
#+LATEX_HEADER: \DeclareMathOperator{\Exists}{\exists}%
#+LATEX_HEADER: \DeclareMathOperator{\Forall}{\forall}%
#+LATEX_HEADER: \DeclareMathOperator{\sgn}{sgn}
#+LATEX_HEADER: \def\colvec#1{\left(\vcenter{\halign{\hfil$##$\hfil\cr \colvecA#1;;}}\right)}
#+LATEX_HEADER: \def\colvecA#1;{\if;#1;\else #1\cr \expandafter \colvecA \fi}
#+LATEX_HEADER: \usepackage{xparse}% http://ctan.org/pkg/xparse
#+LATEX_HEADER: \NewDocumentCommand{\overarrow}{O{=} O{\uparrow} m}{%
#+LATEX_HEADER:  \overset{\makebox[0pt]{\begin{tabular}{@{}c@{}}#3\\[0pt]\ensuremath{#2}\end{tabular}}}{#1}
#+LATEX_HEADER: }
#+LATEX_HEADER: \NewDocumentCommand{\underarrow}{O{=} O{\downarrow} m}{%
#+LATEX_HEADER:  \underset{\makebox[0pt]{\begin{tabular}{@{}c@{}}\ensuremath{#2}\\[0pt]#3\end{tabular}}}{#1}
#+LATEX_HEADER: }
#+LATEX_HEADER: \newcommand{\ubar}[1]{\text{\b{$#1$}}}
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \newcommand{\pushright}[1]{\ifmeasuring@#1\else\omit\hfill$\displaystyle#1$\fi\ignorespaces}
#+LATEX_HEADER: \newcommand{\pushleft}[1]{\ifmeasuring@#1\else\omit$\displaystyle#1$\hfill\fi\ignorespaces}
#+LATEX_HEADER: \makeatother
#+LATEX_HEADER: \newcommand{\I}{\ensuremath{\imath}}%
#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER: \theoremstyle{definition}
#+LATEX_HEADER: \newtheorem{defn}{Definition}
#+LATEX_HEADER: \theoremstyle{plain}
#+LATEX_HEADER: \newtheorem{thm}{Satz}
#+LATEX_HEADER: \theoremstyle{plain}
#+LATEX_HEADER: \newtheorem{lemma}{Lemma}
#+LATEX_HEADER: \theoremstyle{remark}
#+LATEX_HEADER: \newtheorem{remark}{Bemerkung}
#+LATEX_HEADER: \theoremstyle{remark}
#+LATEX_HEADER: \newtheorem{ex}{Beispiel}
#+LATEX_HEADER: \theoremstyle{remark}
#+LATEX_HEADER: \newtheorem{conc}{Folgerung}
#+LATEX_HEADER: \usepackage{etoolbox}
#+LATEX_HEADER: \patchcmd{\thmhead}{(#3)}{#3}{}{}
#+LATEX_HEADER: \renewcommand*{\proofname}{Beweis}
#+LATEX_HEADER: \usepackage{wasysym}
#+LATEX_HEADER: \newcommand{\euler}{e}
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \def\resetMathstrut@{%
#+LATEX_HEADER:   \setbox\z@\hbox{%
#+LATEX_HEADER:     \mathchardef\@tempa\mathcode`\[\relax
#+LATEX_HEADER:     \def\@tempb##1"##2##3{\the\textfont"##3\char"}%
#+LATEX_HEADER:     \expandafter\@tempb\meaning\@tempa \relax
#+LATEX_HEADER:   }%
#+LATEX_HEADER:   \ht\Mathstrutbox@\ht\z@ \dp\Mathstrutbox@\dp\z@}
#+LATEX_HEADER: \makeatother
#+LATEX_HEADER: \catcode`(=\active
#+LATEX_HEADER: \catcode`)=\active
#+LATEX_HEADER: \newcommand{(}{\ifmmode\left\string(\else\string(\fi}
#+LATEX_HEADER: \newcommand{)}{\ifmmode\right\string)\else\string)\fi}

* Einleitung
  Webseite www.biostruct.uni-heidelberg.de/Analysis1.php
  Klausurzulassung: 50%
  Klausur 18.2.2017 9-12Uhr
* Mengen und Zahlen
** Logische Regeln und Zeichen
*** Quantoren
    | $\Forall x$  | für alle $x$                 |
    | $\exists x$  | es gibt (mindestens) ein $x$ |
    | $\exists! x$ | es gibt genau ein $x$        |
*** Hinreichend und Notwendig
	- $A\Rightarrow B$: wenn $A$ gilt, gilt auch $B$, $A$ ist *hinreichend* für $B$, daraus folgt: $B$ ist *notwendig* für $A$, Ungültigkeit von $B$ impliziert die Ungültigkeit von $A$ ($\neg B \Rightarrow \neg A$)
	- $A \Leftrightarrow B$: $A$ gilt, genau dann, wenn $B$ gilt
*** Beweistypen
**** Direkter Schluss
	 $A\Rightarrow B$
***** Beispiel
	  $m$ gerade Zahl $\Rightarrow$ $m^2$ gerade Zahl
****** Beweis
	   $m$ gerade $\Rightarrow \exists n\in\mathbb{N}~\text{sodass}~m = 2n \Rightarrow m^2 = 4n^2 = 2k,~\text{wobei}~k=2n^2\in\mathbb{N} \square$
**** Beweis der Transponerten (der Kontraposition)
	 Zum Beweis $A\Rightarrow B$ zeigt man $\neg B\Rightarrow \neg A~(A\Rightarrow B)\Leftrightarrow (\neg B) \Rightarrow (\neg A)$
***** Beispiel
	  Sei $m\in\mathbb{N}$, dann gilt $m^2~\text{gerade}~\Rightarrow m~\text{gerade}$
****** Beweis
	   Wir zeigen: $m$ ist ungerade $\Rightarrow m^2$ ungerade
	   \[\exists n\in\mathbb{N}:~m=2n+1\Rightarrow m^2 = (2n+1)^2 = 2k+1, k=2n^2 + 2n\in\mathbb{N}\Rightarrow m^2~\text{ungerade} \square\]
**** Indirekter Schluss ( Beweis durch Wiederspruch)
	 Man nimmt an, dass $A\Rightarrow B$ nicht gilt, das heißt $A \wedge \neg B$ und zeigt, dass dann für eine Aussage $C$ gelten muss $C\Rightarrow \neg C$, also ein Wiederspruch
***** Beispiel
	  $\not\exists q\in\mathbb{Q}: a^2 = 2$
****** Beweis
	   Wir nehmen an, dass $\exists a\in\mathbb{Q}: a^2=2$ Dann folgt:
	   $\exists b,c\in\mathbb{Z}$ teilfremd (ohne Einschränkung, denn sonst kürzen soweit wie möglich) mit $a=\frac{b}{c}$
	   Falls \[a^2=2\Rightarrow (\frac{b}{c})^2=2=\frac{b^2}{c^2}=2 \Rightarrow b^2 = 2c^2 \Rightarrow b^2~\text{gerade}~\Rightarrow b~\text{ist gerade (schon gezeigt)}\] \[\Rightarrow\exists d\in\mathbb{N}~\text{sodass}~b=2d\Rightarrow b^2=4d^2\]
	   Außerdem $b^2=2c^2\Rightarrow 2c^2=4d^2\Rightarrow c^2=2d^2\Rightarrow c$ ist auch gerade. Also müssen $b$ und $c$ beide gerade sein, also nicht teilerfremd, damit haben wir einen Widerspruch hergeleitet $\square$
*** Summenzeichen und Produktzeichen
**** Summenzeichen
	 Wir definieren für $m > 0$ \[\sum_{k=m}^m a_k := a_m + \ldots + a_n\] falls $n\geq m$
	 \[\sum_{k=m}^n a_k := 0\] falls $n < m$ (sogennante leere Summe)
**** Produktzeichen
	 \[\prod_{k=m}^n a_k := \begin{cases} a_m \cdot ... \cdot a_n & \text{falls}~n\geq m\\ 1 & \text{falls}~n<m~\text{(sog. leeres Produkt)}\end{cases}\]
** Mengen
*** Definition
	(Georg cantor 1885) Unter einer _Menge_ verstehen wir jede Zusammenfassung $M$ von bestimmten wohlunterschiedenen Objekten (welche die Elemente von $M$ genannt werden), zu einem Ganzen
	$M$ dadurch ist charakterisiert, dass von jedem vorliegendem Objekt $x$ feststeht, ab gilt
	- $x\in M$ (x Element von M)
	- x \not\in M (x kein Element von M)
	\[M = \{x_1, x_2, \ldots, x_n\}\]
	\[M=\{x\mid A(x)\} \rightarrow~\text{eine Menge}~M\text{für die}~x\in\ M \Leftrightarrow A(x)\]
*** Mengenrelationen
	- Mengeninklusion $A\subseteq M$ ($A$ ist eine Teilmenge von $M$)
	  \[\Forall x: (x\in A \Rightarrow x\in M)\] ,zum Beispiel $\mathbb{N} \subseteq \mathbb{Z}$
	- \[A = B \Leftrightarrow \Forall x: (x\in A \Leftrightarrow x\in B)\]
	- \[A \subset M~\text{(strikte Teilmenge)}~\Leftrightarrow A\subset M \wedge A \neq M\]
	- \[\emptyset:~\text{leere Menge}~\not\exists x: x\in\emptyset\]. Wir setzen fest, dass $\emptyset$ eine Teilmenge jeder Menge ist. Zum Beispiel \[\{x\in\mathbb{R}: x^2 + 1 = 0\}\]
	- Durchschnitt \[A\cap B := \{x\mid x\in A \wedge x\in B\}\]
	- Vereinigung \[A\cup B := \{x \mid x\in A \vee x\in B\}\]
	- Differenz (auch Komplement von $B$ in $A$) \[A\setminus B := \{x\mid x\in A \wedge x\not\in B\} := C_a B~\text{(auch $B^c$)}\]
*** Potenzmenge
	Potenzmenge $A$
	\[\mathcal{P}(A) := \{B\mid B\subseteq A\}\]
	Alle Teilmengen von $A$
**** Beispiel
	 \[\mathcal{P}(\{1,2\}) = \{\{1\}, \{2\}, \{1,2\}, \emptyset\}\]
*** Familien von Mengen
	Sei $I$ eine Indexmenge, $I \subseteq \mathbb{N}, (A_i)_{i\in I}$ eine Familie von Mengen $A$
**** Durchschnitt von $A$
	 \[\cap_{i\in I} = \{x\mid \Forall_{i\in I} x\in A_i\}\]
**** Vereinigung
	 \[\cup_{i\in I} = \{x\mid\exists i\in I: x\in A_i\}\]
*** Rechenregeln
	$A,B,C,D$ seien Mengen
	- $\emptyset \subseteq A$
	- $A\subseteq A$ \hfill Reflexivität
	- $A\subseteq B, B\subseteq C \Rightarrow A\subseteq C$ \hfill Transitivität
	- $A\cap B = B\cap A$ \\ $A\cup B = B\cup A$ \hfill Kommutativität
	- $(A\cap B)\cap C = A\cap (B\cap C)$ \\ $(A\cup B) \cup C = A\cup (B\cup C)$ \hfill Assoziativität
	- $A\cap (B\cup C) =(A\cap B) \cup (A\cap C)$ \\ $A\cup (B\cap C) =(A\cup B) \cap (A\cup C)$
	- Eigenschaften der Komplementbildung: \\
	  Seien $A,B \subseteq D (C_D A: = D\setminus A)$, dann gilt \[C_D (C_D A) = A\] \[C_D(A\cap B) = C_D A \cup C_D B\] \[C_D(A\cup B) = C_D A \cap C_D B\]
	  - Beweis:
		\[x\in C_D(A\cap B) \Leftrightarrow x\in D \wedge (x\not\in (A\cap B)) \Leftrightarrow x\in D \wedge (x\not\in A \vee x\not\in B)\] \[\Leftrightarrow (x\in D\wedge x\not\in A) \vee (x\in D \wedge x\not\in B)\] \[\Leftrightarrow (x\in D\setminus A) \vee (x\in D\setminus B) \Leftrightarrow x\in D\setminus(A\cup B)~\square\]
      - Bemerkung: Komplement kann man auch mit $A^c$ bezeichnen
*** geordneter Tupel
   	Sei $x_1, x_2, \ldots, x_n$ (nicht notwendig verschiedene) Objekte. Ein geordneter n-Tupel \[(x_1,x_2,\ldots,x_n) = (y_1,\ldots,y_n) \Leftrightarrow x_1 = y_1, \ldots, x_n = y_n\]
   	Beachte:
   	\[\{x_1, \ldots, x_n\} = \{y_i,\ldots,y_n\}\not\implies x_1 = y_1, \ldots, x_n = y_n\]
*** Kartesisches Produkt
	Seien \[A_1\times A_2\times \ldots \times A_n = \{(x_1,x_2,\ldots,x_n)\mid x_j \in A_j j\in\mathbb{N}, j \leq n\}\]
**** Beispiel
	 - \[\mathbb{Z}^2 = \mathbb{Z}\times \mathbb{Z}\]
	 - $R^n$ n-dimensionaler Raum von reellen Zahlen
*** Äquivalenzrelation
	Eine Äquivalenzrelation auf eine Menge $A$ ist eine Beziehung zwischen ihren Elementen (Bezeichnung: $a \sim b$), sodass
	- Für jede zwei $a,b\in A$ gilt entweder $a\sim b \vee a\not\sim b$
	- $a\sim a$ \hfill Reflexivität
	- $a\sim b \Rightarrow b\sim a$ \hfill Symmetrie
	- $a \sim b, b \sim c \Rightarrow a \sim c$ \hfill Transitivität
    Mit Hilfe einer Äquivalenzrelation lassen sich die Elemente einer Menge in sogenannte Äquivalenzklassen einordnen: $[a]:\{b\in A\mid b\sim a\}$
** Relationen und Abbildungen
*** Relationen
	Unter einer *Relation* verstehen wir eine Teilmenge $R\subseteq X\times Y$ wobei $X, Y$ Mengen sind. Für $x\in X$ definieren wir, das *Bild* von $x$ unter $R$
	\[R(X) := \{y\in Y \mid (x,y) \in R\}\]
	und *Definitionsbereiche von $R$ (bezüglich $X$)
	\[D(R):= \{x\in X\mid R(x)\neq\emptyset\}\]
*** Graph der Abbildung
	$R\subseteq X\times Y$ heißt Graph der Abbildung (Funktion) \[f:X\rightarrow Y \Leftrightarrow D(R) = X, \Forall x\in X: R(x) = \{f(x)\}\]
	also enthält $R(x)$ genau ein Element. \\
	$X$ heißt Definitionsbereich von $f$ \\
	$Y$ heißt Werte- oder Bildbereich von $f$ (Bild) \\
	$x\in X$ heißt Argument \\
	$f(x)\in Y$ heißt Wert von $f$ an der Stelle x
**** Beispiel
	 $f: \mathbb{R}\rightarrow\mathbb{R}, x\rightarrow x^2$ dann ist der Graph von $f = \{(x,y)\in\mathbb{R}^2, y=x^2\}$
***** Bemerkung
	  \[M^{*}(x) = \{(x,y)\in\mathbb{R}^2;x=y^2\} = \{(x,y)\in\mathbb{R}^2: x \geq 0, y=\sqrt{x} \vee y = -\sqrt{x}\}\]
	  Ist kein Graph einer Funktion $\mathbb{R}\rightarrow\mathbb{R}$, denn $M^{ *}(x) = \{\sqrt{x},-\sqrt{x}, x\geq 0\}$
	  $f$ heißt
	  - surjektiv, wenn gilt $f(X) = Y$
	  - injectiv, $\Forall x_1,x_2\in X: f(x_1) = f(x_2) \Rightarrow x_1 = x_2$
	  - bijektiv, wenn $f$ surjektiv und injectiv ist
*** Umkehrabbildung
	Sei die Abbildung $f: X\rightarrow Y$ bijektiv. Dann definieren wir die Umkehrabbildung $f^{-1}:Y\rightarrow X$ durch $y\rightarrow x\in X$, eindeutig bestimmt durch $y = f(x)$
**** Bemerkung
	 \[(x,y) \in~\text{Graph }f\Leftrightarrow (y,x)\in~\text{Graph }f^{-1}\]
*** Komposition
	Seien $f:X\rightarrow Y, g:Y\rightarrow Z$ Abbildungen. Die Komposition von $g$ und $f$ \[g\circ f: X\rightarrow Z~\text{ist durch}~x\rightarrow g(f(x))~\text{definiert}\]
*** Identitäts Abbildung
	Für jede Menge $X$ definieren wir die identische Abbildung \[I_d(A) = I_A: A\rightarrow A,~\text{durch}~x\rightarrow x\]
**** Beispiel
	 - \[\{(x,y)\in\mathbb{R}^2\mid x^2 + y^2 = 1\} = S^1\] \[S^{n-1} := \{(x_1 \ldots x_n) \in \mathbb{R}^n; \sum_{i = 1}^n x_i^2 = 1\}\] $(n - 1)$ dimensionale sphere in $\mathbb{R}^n$
	 - Seien $X,Y$ Mengen, $M\subseteq X\times Y, f:M\rightarrow X$ \\ $f$ heißt Projektion, $f$ surjektiv \[f(M) = \{x\mid \exists y \in Y : (x,y) \in M\} = X\]
*** Homomorphe Abbildungen
	Existieren auf Mengen $X$ und $Y$ mit gewissen Operationen $\oplus_x$ bzw. $\oplus_y$ (zum Beispiel Addition, Ordungsrelation), ho heißt die Abbildung $f:X\to Y$ homomorph (strukturerhaltend), wenn gilt $\Forall x_1,x_2 \in X f(x_1\oplus_x x_2) = f(x_1)\oplus_y f(x_2)$
	Eine bijektive Homomorphie heißt Isomorphisumus, beziehungsweise $X\approx Y$ (äquivalent, isomorph)
** Natürliche Zahlen
   $\mathbb{N} = \{1,2,3,\ldots\},~\mathbb{N}_0 := \mathbb{N}\cup \{0\}$
*** Peanosche Axiomensystem der natürlichen Zahlen
	1. Die Zahl $1$ ist eine natürliche Zahl $1\in\mathbb{N}$
	2. Zu jeder natürlichen Zahl $n$, gibt es genau einen "Nachfolger" $n' (=: n+1)$
	3. Die Zahl 1 ist kein Nachfolger einer natürlichen Zahl
	4. $n' = m' \Rightarrow n = m$
	5. Enthält eine Teilmenge  $M \subseteq \mathbb{N}$ die Zahl $1$ und von jedem $n\in m$ auch den Nachfolger $n'$ ist $M = \mathbb{N}$
	Bemerkung: \\
	Mit Hilfe der Axiome lassen sich auf $\mathbb{N}$ Addition ($+$), Multiplikation ($\cdot$) und Ordung ($\leq$) einführen.
	Wir definieren: \\
	$1' = 2, 2' = 3, \ldots$
	$n + 1 := m'$
	$n + m' := (n+m)';~n\cdot m' := n m + n$
	Man kann zeigen, dass jede Menge, welche die Peano Axiome erfüllt isomorph bezüglich Multiplikation und Addition zu $\mathbb{N}$ ist
	Wir definieren $n < m \Leftrightarrow \exists x\in \mathbb{N}: x + m = m$
*** Vollständige Induktion
**** Induktionsprinzip
	 Es seien die folgende Schritte vollzogen:
	 1. Induktionsverankerung (Induktionsanfang): Die Aussage $A(1)$ gilt
	 2. Induktionsschluss: Ist für ein $n\in\mathbb{N}~A(n)$ gültig, so folgt auch die Gültigkeit von $A(n+1)$
     Dann sind alle Aussagen $A(n),n\in\mathbb{N}$ gültig.
**** Beweis:
	 Wir definieren die Tailmenge $M\subseteq\mathbb{N},~M:=\{n\in \mathbb{N}\mid A(N)~\text{ist gültig}\}$
	 Die Induktionsverankerung besagt, dass $1\in M$ und die Induktionsannahme $n\in M\Rightarrow n + 1 \in M$. Folglich ist nach dem 5. Axiom von Peano $M = \mathbb{N}\hfill\square$
**** Beispiel 1
	 Zu Beweisen: \[\Forall n\in\mathbb{N} \sum_{i = 1}^n i^2 = \frac{n(n+1)(2n+1)}{6}\]
***** Beweis
	  1. Induktionsverankerung: $1^2 = \frac{1}{6}\cdot 1\cdot 2\cdot 3$
	  2. Annahme: $A(n)$ gültig für $n\in\mathbb{N}: \sum_{i = 1}^n i^2 = \frac{n(n+1)(2n+1)}{6}$ \\
		 Zu zeigen $A(n + 1): 1^2 + \ldots + (n+1)^2 = \frac{1}{6} (n+1)(n+2)(2n+3)$
		 \[1^2 + \ldots + n^2 + (n+1)^2 = \frac{1}{2} n(n+1)(2n+1) + (n+1)^2 = (n+1)(\frac{1}{3}n^2 + \frac{1}{6}n + n + 1)\]
		 \[= \frac{1}{6}(n+1)(2n^2+7n+6) = \frac{1}{6}(n+1)(2n+3)(n+2)\hfill\square\]
**** Beispiel 2
	 Definition von Potenzen
	 \[x^0 := 1\]
	 \[\Forall n\in\mathbb{N} x^n := x^{n - 1}x\]
	 (iterative (rekursive) Definition) \\
	 Auf $\mathbb{N}$ sind diese elementaren Operationene erklärt:
	 - Addition $a+b$
	 - Multiplikation $a\cdot b$
	 - (unter gewissen Vorraussetzungen):
	   - Subtraktion $a-b$
	   - Division $\frac{a}{b}$
     $\mathbb{N}$ ist bezüglich "$-$" oder "$/$" nicht vollständig, das heißt $n+x = m$ ist nicht lösbar in $\mathbb{N}$
	 Erweiterungen:
	 - Ganze Zahlen $\mathbb{Z}:=\{0; \pm, n\in\mathbb{N}\}$ \\
	   Negative Zahl $(-n)$ ist definiert duch $n+(-n) = 0$
	 - Rationale Zahlen $\mathbb{Q}~(b x = y)$
     Man sagt, dass $(\mathbb{Q},+,\cdot)$ einen Körper bildet.
*** Definition Körper
	$\mathbb{K}$ sei eine Menge auf der Addition und Multiplikation sei. $\mathbb{K}$ heißt ein Körper, wenn die folgende Axiome erfüllt sind:
	- Addition: $(\mathbb{K}, +)$ ist eine kummutative Gruppe, das heißt $\Forall a,b,c\in \mathbb{K}$:
	  1. \((a+b)+c = a+(b+c)\) \hfill Assoziativität
	  2. \(a+b = b+a\) \hfill Kommutativität
	  3. \(\exists! 0\in\mathbb{K}:a+0 = a\)\hfill Existenz des Nullelement
	  4. \(\exists x\in\mathbb{K}: a+x = 0\)\hfill Existstenz des Nagativen
	- Multiplikation: $(\mathbb{K}\setminus\{0\},\cdot)$ ist eine kommutative Gruppte, das heißt $\Forall a,b,c\in\mathbb{K}$
	  1. \((a\cdot b)\cdot c = a\cdot(b\cdot c)\)\hfill Assozativität
	  2. \(a\cdot b = b\cdot a\)\hfill Kummutativität
	  3. \(\exists!1\in\mathbb{K}:a\cdot 1 = a\)\hfill Existenz des Einselement
	  4. Für \(a\neq 0, \exists! y\in\mathbb{K}:a\cdot y = 1\)\hfill Inverse
	- Verträglichkeit
	  1. \(a\cdot (b + c) = (a\cdot b)+ (a\cdot c)\)\hfill Distributivität
**** Satz
	 $(\mathbb{Q},+,\cdot)$ ist ein Körper. Definieren auf $\mathbb{Q}$ eine Ordnung "$\leq$" duch \[x\leq y \Leftrightarrow\exists m\in\mathbb{N}_0, n\in\mathbb{N}:y - x = \frac{m}{n}\]
	 dann ist auch diese Ordnung mit der Addition und Multiplikation in $\mathbb{Q}$ in folgendem Sinne verträglich (Axiom M0):
	 - \(a\leq b\Rightarrow a+c \leq b + c\)
	 - \(0\leq a\wedge 0\leq b \Rightarrow 0\leq a\cdot b\)
**** Bemerkung
	 \[\{a\in\mathbb{Q}: a = \frac{r}{s},r\in\mathbb{N}_0,s\in\mathbb{N}\} =: \mathbb{Q}_+ (\mathbb{Q}_{\geq 0})\]
** Abzählbarkeit
*** Abzählbarkeit von Mengen
	Sei $A$ eine Menge\\
	- $A$ heißt endlich mit $\abs{A} = n$ Elementen ist äquivalent zu
	  \[\abs{A} = \begin{cases} A = \emptyset & n = 0 \\ \exists f:A\to \{1,\ldots,n\} &f~\text{bijektiv},n < \infty\end{cases}\]
	- $A$ heißt abzählbar unendlich genau dann wenn \[\exists f: A\to \mathbb{N}~\text{bijektiv}\]
	- $A$ heißt überabzählbar genau dann wenn: $A$ ist weder endlich oder abzählbar unendlich
**** Beispiel
	 $\mathbb{Z}$ ist abzählbar unendlich
***** Beweis
	  Die Abbildung $f:\mathbb{Z}\to\mathbb{N}$
	  \[z\mapsto \begin{cases} 2z & z\geq 0\\ -2z - 1 & x < 0\end{cases}\]
	  - Surjektivität: zu zeigen $f(\mathbb{Z}) = \mathbb{N}$ \\
	   	Offenbar $f(\mathbb{Z}) \subseteq \mathbb{N}$. Wir zeigen $\mathbb{N} \subseteq f(\mathbb{Z})$. Sei $n\in\mathbb{N}$, finde $z\in\mathbb{Z}$ mit $f(z) = n$.
	   	Man unterscheide:
	   	- n gerade \rightarrow Wähle $z=\frac{n}{2}$
	   	- n ungerade \rightarrow $z=-\frac{n + 1}{2}$
      - Injektivität: Sei $z_1,z_2 \in\mathbb{Z}$ und $f(z_1) = f(z_2)$ \\
	   	ohne Beschränkung der Allgemeinheit $z_1 \leq z_2$. Entweder $z_1,z_2 \geq 0$ oder $z_1,z_2 < 0$, denn sonst währe $f(z_1)$ ungerade und $f(z_1)$ gerade *Wiederspruch*.
	   	Falls
       	- $z_1,z-2 \geq 0 \Rightarrow 2z_1 = f(z_1) = f(z_2) = 2z_2 \Rightarrow z_1 = z_2$
       	- $z_1,z-2 < 0 \Rightarrow -2z_1 -1 = f(z_1) = f(z_2) = -2z_2-1 \Rightarrow z_1 = z_2 \hfill\square$
**** Beispiel
	 - $\mathbb{N}^2 = \mathbb{N}\times\mathbb{N}$ abzählbar unendlich
	 - $\mathbb{Q}$ abzählbar unendlich
	 - $\mathbb{R}$ überabzählbar
**** Abzählbarkeit von $\mathbb{N}\times\mathbb{N}$
	 \[(1,1) \to (1,2) \to (2,1) \to (2,2) \to (1,3) \to (2,3) \to (3,2) \to (3,1)\]
**** Korollar 1.30
	 $M_1,M_2,\ldots,M_n$ abzählbar $\Rightarrow M_1 \times \ldots \times M_n$ abzählbar.
***** Beweis
	  Durch vollständige Induktion $M_1\times(M_2\times\ldots \times M_n)\approx \mathbb{N}\times\mathbb{N}\approx\mathbb{N}$
**** Satz
	 Die Menge aller Folgen $f:\mathbb{N}\to\{0,1\}$ ist überabzählbar. (Zum Beispiel: $1,0,0,0,\ldots, \underarrow[1]{\text{k-te Stelle}},\ldots,0,\ldots$)
***** Beweis
	  $M$ ist unendlich, denn die Folgen $f_k:0,,\ldots,0,1,0,\ldots$ sind parrweise verschieden. Angenommen $M$ wäre abzählbar. Sei $f_1,f_2, \ldots$ eine Abzählung mit $f_k = ({z_{kn}}_{n\in \mathbb{N}})$.
	  \[\begin{matrix}1 & 0 & 0 & \ldots \\ 0 & 1 & \ldots \\ 0 & 0 & 0 & \ldots \\ 1 & 1 & 1 & 1 & \ldots \end{matrix}\]
	  $f:0 0 1 0$ Man setze $f=(z_n)_{n\in\mathbb{N}}$ mit \[z_n := \begin{cases} 1 & z_{nn} = 0 \\ 0 & z_{nn} = 1\end{cases}\]
	  Dann $f\in M$, aber $f\neq f_k \Forall k\in\mathbb{N}$. Also ist $M$ nicht abzählbar. ("Cantorsche Diagonalverfahren").
** Ordnung
*** Definition
	Sei $A$ eine Menge. Relation $R\subseteq A\times A$ heißt Teilordnung (Halbordnung) auf $A$, wenn $\Forall y,x,z\in A$ gilt:
   1. $x\leq x$ \hfill (Reflexivität)
   2. $x\leq y \wedge y\leq x \Rightarrow x = y$ \hfill (Symmetrie)
   3. $x\leq y \wedge y\leq z \Rightarrow x\leq z$ \hfill (Transitivität)
   Wenn außerdem noch $\Forall x,y\in A$ gilt:
   4. [@4] $x\leq y \vee y\leq x$ \hfill (Vergleichbarkeit je zweier Elemente)
   so heißt $R$ (totale) Ordung auf $A$. $(A,\leq) heißt teilweise beziehungsweise (total) geordnete Menge.
**** Beispiel
	 1. $(\mathbb{Q},\leq)$ mit der üblichen Ordnung ist eine total geordnete Menge
	 2. Wir definieren auf der Potenzmenge $\mathcal{P}(A)$ einer Menge $A$ eine Teilordnung "$\leq$": \[B\leq C \Leftrightarrow B \subseteq C\Forall B,C\in \mathcal{P}(A)\] \\
		*Beweis*: 1. - 3. sind trivial, 4. geht nicht (keine Totalordung). Wähle $B,C\in \mathcal{P}(a), B,C\neq \emptyset, B\cap C = \emptyset$. Dann gilt weder $B\subseteq C$ noch $C\subseteq B\hfill\square$
	 3. Sei $F:=\{f\mid f:A\to\mathbb{R}\}$ für eine Menge $A\subseteq \mathbb{R}$. Wir definieren $f\leq g \Leftrightarrow \Forall x\in A: f(x) \leq g(x)$ \\
		(1.) - (3.) trivial, 4. gilt nicht. Falls $A$ mehr als ein Element hat, gibt es eine Funktion, die nicht miteinander verglichen werden können.
** Maximum und Minimum einer Menge
*** Definition
	Sei $(A,\leq)$ eine teilweise geordnete Menge, $a\in A$ \\
	Maximum:
	\[a = \max A \Leftrightarrow \Forall x\in A: x\leq a\]
	Minimum:
	\[a = \max A \Leftrightarrow \Forall x\in A: a\leq x\]
*** Bemerkung
	Durch die Aussagen ist $a$ eindeutig bestimmt, denn seien:
	\[a_1,a_2\in A:\Forall x\in A \begin{cases}x\leq a_1 \\ x\leq a_2 \end{cases} \Rightarrow \begin{cases} a_2 \leq a_1 \\ a_1 \leq a_2 \end{cases} \xRightarrow{\text{Symmetrie}} a_1 = a_2 \]
** Schranken
   Sei $(A,\leq)$ eine (total geordnete) Menge, $B\subseteq A$
   1. $S\in A$ heißt obere Schranke zu $B \Leftrightarrow \Forall x\in B: x\leq S$ \\
      $S\in A$ heißt untere Schranke zu $B \Leftrightarrow \Forall x\in B: S\leq x$
   2. $\bar{S}(B):= \{S\in A \mid S~\text{S ist untere Schranke zu}~B\}$ \\
      $\ubar{S}(B):= \{S\in A \mid S~\text{S ist obere Schranke zu}~B\}$
   3. Existiert $g:=\min \ubar{S}(B)$ beziehungsweise $g:=\max \bar{S}$ so sagen wir: \\
	  $g = \sup B$ (kleinste obere Schranke, _supremum_, obere "Grenze" von $B$ in $A$)
	  $g = \inf B$ (größte obere Schranke, _infimum_, untere "Grenze" von $B$ in $A$)
*** Bemerkung
	1. Existiert $\max B = \bar{b}$, so folt $\sup B = \bar{b}$, denn $\bar{b} \in \ubar{S}(B)$ nach Definition.
	   \[s\in \ubar{S}(B) \Rightarrow \bar{b} \leq s,~\text{da}~\bar{b}\in B\]
	   Ebeso gilt: $\exists\min B = \ubar{b} \Rightarrow \inf B = \ubar{b}$
*** Beispiel
	1. $B = \{\frac{1}{n}\mid n\in\mathbb{N}\}, A = \mathbb{R},~(1, \frac{1}{2},\ldots)$
	   - Es gilt $1\in B, \Forall n\in\mathbb{N}$ gilt $\frac{1}{n} \leq 1$, daher folgt $\max B = \sup B = 1$
	   - Sei $s\leq 0$, dann gilt $\Forall n\in\mathbb{N}: s\leq \frac{1}{n}$, also $s\in \bar{S}(B)$ \\
	     Sei $s > 0 \Rightarrow s > \frac{1}{n} \Leftrightarrow n > \frac{1}{s}$, also $s\not\in\bar{S}(B)$ \\
		 Es folgt $\bar{S}(B) = \{x\in\mathbb{R}\mid s\leq 0\}$ insbesondere $0\in\bar{S}(B)$ \\
		 Ferner gilt $\Forall s\in \bar{S}(B):s\leq 0 \Rightarrow \ubar{0} = \max \bar{S}(B) = \inf B$
	2. $A = \mathbb{Q}, B = \{x\in\mathbb{Q} : 0 \leq x \wedge x^2 \leq 2\}$. Es gilt $0 = \min B = \inf B$, aber $\sup B$ existiert nicht in $\mathbb{Q}$
** Reelle Zahlen
   $x^2 = 2$ hat keine Lösungen in $\mathbb{Q}$. Allerdings können wir $\sqrt{2}$ "beliebig gut" durch $y\in \mathbb{Q}$ approximieren, das heißt $\Forall \varepsilon > 0\exists y\in\mathbb{Q}:2 - \varepsilon \leq y^2 \leq 2 + \varepsilon$
   Das motiviert die folgende Vorstellung:
   1. $\mathbb{Q}$ ist "unvollständig"
   2. $\mathbb{Q}$ ist "dicht" in $\mathbb{R}$
*** Vollständigkeitsaxiom (Archimedes)
   	Jede nach oben (unten) beschränkte Teilmenge hat ein Supremum oder Infimum.
*** Axiomatischer Standpunkt
	Es gibt eine Menge $\mathbb{R}$ (genannt Menge der reellen Zahlen) mit Addition, Multiplikation, Ordung, die die Definition eines Körper und das Vollständigkeitsaxiom erfüllt und $(\mathbb{R},+,\cdot)$ mit "$\leq$" eine Ordung bildet.
*** Bemerkung
	1. Bis auf Isomorphie gibt es höchstens ein solches $\mathbb{R}$, das heißt $\tilde{\mathbb{R}}$ ein weiteres System der reellen Zahlen ist, dann $\exists$ bijektive Abbildung $f:\mathbb{R}\to\tilde{\mathbb{R}}$ die bezüglich Additoin, Multiplikation, Ordung eine Homomorphie ist.
	   \[\Forall x,y\in \mathbb{R}:\]
	   \[f(x+y) = f(x) + f(y)\]
	   \[f(x y) = f(x) f(y)\]
	   \[x\leq y \Rightarrow f(x) \leq f(y)\]
	2. $\mathbb{N}$ (und damit auch $\mathbb{Z},\mathbb{Q}$) lassen sich durch injektive Homomorphismus $g:\mathbb{N}\to\mathbb{R}$ in $\mathbb{R}$ einbetten
	   \[g(\tilde{0}_{\in\mathbb{N}}) = 0_{\in\mathbb{R}}\]
	   \[g(\tilde{n}_{\in\mathbb{N}} + 1) = g(n_{\in\mathbb{R}}) + 1\]
	   \[g(1_{\in\mathbb{N}}) = 1_{\in\mathbb{R}}\]
*** Konstruktiver Standpunkt
	Wir können $\mathbb{R}$ ausgehend von $\mathbb{Q}$ konstruieren.
**** Methode der Abschnitte
	 Jede reelle Zahl wird charakterisiert durch ein "rechts offenes, unbeschränktes Interval", dessen "rechte Grenze" die Zahl erstellt.
	 \[\mathbb{R}:=\{A\subseteq \mathbb{Q}\begin{cases}A\neq\emptyset \\ x\in A, y\leq x\Rightarrow y\in A \\ \Forall x\in A\exists y\in A, x<y\end{cases}\]
**** Mehtode der Cauchy-Folgen
	 Jede reelle Zahl wird charaktierisiert als "Grenzwert" eine Klasser äquivalenter "Cauchy Folgen" aus $\mathbb{Q}$ (später)
*** Definition 1.37
	- \[x\in \mathbb{R}~\text{heißt}~\begin{cases}\text{positiv} & 0 < x \\ \text{nichtnegativ} & 0\leq x \\ \text{negativ} & x < 0 \\ \text{nichtpositiv} & x\geq 0 \end{cases}\]
	- Die Betragsfunktion $\abs \cdot:\mathbb{R} \to \mathbb{R}$ wird definiert durch $\abs{x} = \max \{x,-x\} = \begin{cases} x & x \geq 0 \\ -x & x < 0\end{cases}$
	- Die Vorzeichen- oder Signumfunktion \[\sgn:\mathbb{R}\to\mathbb{R},\sgn{x} = \begin{cases}\frac{x}{\abs{x}} & x \neq 0 \\ 0 & x = 0\end{cases} = \begin{cases} 1 & x > 0 \\ -1 & x < 0 \\ 0 & x = 0\end{cases}\]
*** Satz 1.38
	1. $\abs{x y} = \abs{x} \abs{y}$
	2. $\abs{x + y} \leq \abs{x} + \abs{y}$ \\
	   *Beweis:* \\
	   \begin{align}
	   \abs{x + y}^2 &= (x+y)^2 = x^2 + 2x y + y^2 = \abs{x}^2 + 2xy + \abs{y}^2 \\
	   &\leq \abs{x}^2 + 2\abs{x y} + \abs{y}^2 = \abs{x}^2 + 2\abs{x}\abs{y} + \abs{y^2} \\
	   &= (\abs{x} + \abs{y})^2 \Rightarrow \abs{x + y} \leq \abs{\abs{x} + \abs{y}} = \abs{x} + \abs{y} \tag*{$\square$}
	   \end{align}
	3. $\abs{x + y} = \abs{x} + \abs{y} \Leftrightarrow x y \geq 0$
*** Satz 1.39
	1. $\abs{\abs{x} - \abs{y}} \leq \abs{x - y}$ \\
	   *Beweis:* \\
	   \begin{align}
	   \abs{x} &= \abs{x - y + y} \leq \abs{x - y} + \abs{y} \Rightarrow \abs{x} - \abs{y} \leq \abs{x - y} \\
	   \abs{y} &= \abs{y - x + x} \leq \abs{y - x} + \abs{x} \Rightarrow \abs{y} - \abs{x} \leq \abs{x - y} \\
	   \abs{\abs{x} - \abs{y}} &= \max \{\abs{x} - \abs{y},\abs{y} - \abs{x}\} \leq \abs{x - y} \tag*{$\square$}
	   \end{align}
	2. \[\abs{x - y} \leq \varepsilon \Leftrightarrow \begin{cases} x - \varepsilon \leq y \leq x + \varepsilon \\ y - \varepsilon \leq x \leq y + \varepsilon \end{cases}\]
	   *Beweis:* \\
	   \begin{align}
	   \abs{x - y} = \max\{x - y , y - x\} \leq \varepsilon \Leftrightarrow \begin{cases} x - y \leq \varepsilon \\ y - x \leq \varepsilon\end{cases} \Leftrightarrow \begin{cases} x \leq y + \varepsilon \\ y - x \leq \varepsilon \end{cases} \Leftrightarrow y - \varepsilon \leq x \leq y + \varepsilon
	   \end{align}
	   Vertausche $x$ und $y$ \Rightarrow $x - \varepsilon \leq x + \varepsilon \hfill \square$
*** Definition 1.40
	Sei $a,b\in\mathbb{R},a\leq b$
	- $[a,b]:=\{x\in\mathbb{R}: a\leq x \leq b\}$ \hfill abgeschlossenes Intervall
	- $(a,b):= \{x\in\mathbb{R}: a < x < b\} = ]a,b[$ \hfill offenes Intervall
	- $\left[a,b) := \{x\in\mathbb{R}:a\leq x < b\}$ \hfill rechts-halboffenes Intervall
	- $(a,b\right]:=\{x\in\mathbb{R}:a<x\leq b\}$ \hfill links-halboffenes Intervall
	- $\varepsilon > 0, I_\varepsilon (x) := (x -\varepsilon,x + \varepsilon) = \{y\in\mathbb{R}:\abs{x - y} < \varepsilon = B_\varepsilon (x) (\text{Kugel})\}$
*** Lemma 1.41
	Es gilt $y\in I_\varepsilon (x) \Rightarrow \exists \delta > 0: I_\delta (y) \subseteq I_\varepsilon (x)$
**** Beweis
	 Sei $y\in I_\varepsilon (x) \Rightarrow \abs{x - y}  < \varepsilon \Leftrightarrow \varepsilon - \abs{x - y} > 0$
	 Wähle $0 < \delta < \varepsilon - \abs{x - y}$. Es ist nun zu zeigen $I_\delta (y) \subseteq I_\varepsilon (x)$, das heißt
	 $z\in I_\delta(y) \Rightarrow z\in I_\varepsilon(x)$. Es gilt
	 \begin{align}
	 &z\in I_\delta (y) \Rightarrow \abs{z - y}  <\delta \\
	 \Rightarrow &\abs{z - x} = \abs{z - y + y - x} \leq \abs{z - y} + \abs{y - x} \leq \delta + \abs{x - y} < \varepsilon \\
	 \Rightarrow &z\in I_\varepsilon (x) \tag*{$\square$}
	 \end{align}
*** Definition 1.42
	$A,B$ seien geordnete Mengen, $f:A\to B$ heißt:
	- monoton $\begin{cases} \text{wachsed} & x \leq y \Rightarrow f(x) \leq f(y)  \\ \text{fallend} & x \leq y \Rightarrow  f(x) \leq f(y) \end{cases}$
	- streng monoton $\begin{cases} \text{wachsend} & x < y \Rightarrow f(x) < f(y) \\ \text{fallend} & x < y \Rightarrow f(x) > f(y) \end{cases}$
**** Beispiel 1.43
	 $\mathbb{R}_+\setminus \{0\} \to \mathbb{R}_+\setminus\{0\}, x\mapsto x^n$ ist streng monoton wachsend $\Forall n\in\mathbb{N}$
***** Beweis
	  Induktion + Axiom M0 $\hfill\square$
*** Lemma 1.44
	Sei $M,N \subseteq \mathbb{R}, f:M\to N$ streng monoton und bijektiv. Dann ist $f^{-1}$ streng monoton.
**** Beweis
	 Wir betrachten den Fall $f$ streng monoton wachsend. Seien $y_1,y_2 \in N, y_1 < y_2,x_1 = f^{-1}(y_1), x_2 = f^{-1}(y_2). \\
	 Behauptung $x_1 < x_2$ (sonst wäre $x_1 \geq x_2). \\
	 Falls $x_1 > x_2 \xRightarrow{\text{streng monoton}} f(x_2) > f(x_2)$ *Widerspruch* zu $y_1 < y_2$ \\
	 Falls $x_1 = x_2 \Rightarrow y_1 = y_2$ *Widerspruch* zur Annahme $y_1 < y_2 \hfill \square$
*** Definition 1.45 Produktzeichen
	Für $a\in\mathbb{R},n\in\mathbb{N}$ definieren wir $a^n := \prod_{j=1}^n a$ und für $a\in\mathbb{R}\setminus\{0\},n\in\mathbb{N}$ $a^{-n} := \frac{1}{a^n}$.
*** Satz 1.46
	Es gilt $\Forall a,b\in\mathbb{R}$ (beziehungsweise $\mathbb{R}\setminus \{0\}$),$n,m\in\mathbb{N}_0$ (beziehungsweise $\mathbb{Z}$)
	1. $a^n a^m = a^{n+m}$
	2. $(a^n)^m$ = a^{n m}$
	3. $(ab)^m = a^m b^m$
**** Beweis
	 Zunächst f+r $n,m\in\mathbb{N}_0$ durch Indukton nach $n$, dann für $n,m\in\mathbb{Z}$ (mit Hilfe der Definition von $a^{-n}$)
*** Definition 1.47
	Sei $n,k\in\mathbb{N}_0$ \[\binom{n}{k}:=\prod_{j=1}^k \frac{n -j + 1}{j}\]
*** Lemma 1.48
	Sei $k,n\in\mathbb{N}_0$
	1. $\binom{n}{k} = 0$ für $k > n$ \\
	   $\binom{n}{k} = \frac{n!}{k!(n -k)!} = \binom{n}{n - k}$ für $k\leq n$
	2. $\binom{n}{k} = \binom{n - 1}{k - 1} + \binom{n - 1}{k}$ für $1 \leq k \leq n$
*** Satz 1.49
	$\Forall n\in\mathbb{N}_0,\Forall x,y\in\mathbb{R}$ gilt
	\[(x + y)^n = \sum_{j = 0}^n \binom{n}{j}x^{n - j}y^j\]
**** Beweis
	 Induktion:
	 - Induktionsanfang: $n = 0,(x+y)^0 = 1,\binom{0}{j}x^0y^0 = 1$ nach Definition
	 - Induktionsschritt $n \to n + 1:$
	   \begin{align*}
	   \left\string(x + y\right\string)^{n + 1} &= (x +y)(x+y)^n \\
	   \shortintertext{mit der Induktionsvoraussetzung}
	   &=(x + y)\sum_{j = 0}^n \binom{n}{j}x^{n - j} y^j \\
	   &= \sum_{j=0}^n \binom{n}{j}x^{n - j + 1}y^j + \sum_{j = 0}^n \binom{n}{j} x^{n - j} y^{j + 1} \\
	   &= \binom{n}{0}x^{n + 1} + \sum_{j = 1}^n \binom{n}{j}x^{n + 1 - j}y^j + \underbrace{\sum_{i = 1}^n \binom{n}{i - 1} x^{n - i + 1} y^i}_{\text{Substitution $i:= j + 1$}} + \binom{n}{n}y^{n + 1} \\
	   &= x^{n + 1} + \sum_{j = 1}^n \underbrace{(\binom{n}{j} + \binom{n}{j - 1})}_{\binom{n + 1}{j}\text{nach Lemma 1.48}} x^{n + 1 - j} y^j + y^{n + 1} \\
	   &= \sum{j = 0}^{n + 1} \binom{n + 1}{j}x^{n + 1 - j}y^j\tag*{$\square$}
	   \end{align*}
*** Folgerung 1.50
	1. $\sum_{j = 0}^n \binom{n}{j} = 2^n$
	2. $\sum_{j = 0}^n \binom{n}{j} (-1)^j = \begin{cases}0 & n \neq 0 \\ 1 & n = 0\end{cases}$
**** Beweis:
	 Setze in Binomische Formel $x = 1, y = 1$ beziehungsweise $y = -1 \hfill\square$
*** Lemma 1.51
	Sei $m\in R$ nach oben (beziehungsweise nach unten) beschränkt \\
	Dann gilt
	1. $s = \sup M \Leftrightarrow \Forall \varepsilon > 0 \exists x\in M: s - \varepsilon < x (\geq s)$
	2. $l=\inf M \Leftrightarrow \Forall \varepsilon > 0 \exists x\in M: (l \leq) x < l + \varepsilon$
**** Beweis
	 Wir beweisen 1. \\
	 $s\neq \sup M\Leftrightarrow s$ ist nicht die kleinste obere Schranke von $m$ $\Leftrightarrow$ es gibt eine kleinere obere Schranke $s' = s - \varepsilon$ von $M$ $\Leftrightarrow$
	 nicht $\Forall \varepsilon > 0\exists x\in M: x > s - \varepsilon \hfill \square$
*** Lemma 1.52
	$\mathbb{N}$ ist unbeschränkt in $\mathbb{R}$
**** Beweis
	 sonst $\exists x = \sup \mathbb{N}$ (nach Vollständigkeits Axiom), $x$ kleinste obere Schranke $\xRightarrow{\text{[[Lemma 1.51]]}} \varepsilon= \frac{1}{2} \exists m_o \in \mathbb{N}:x - \frac{1}{2} < m_0 \Rightarrow m_0 + 1 \in \mathbb{N},m_0 + 1 > x + \frac{1}{2} > x$
	 \Rightarrow $x$ inst nicht die obere Schranke von $\mathbb{N}\hfill\square$
*** Lemma 1.53 (Bernoullische Ungleichung)
	<<Lemma 1.53>>
	\[\Forall x\in \left[-1,\infty),n\in\mathbb{N}_0: (1 + x)^n \geq 1 + n x\]
**** Beweis
	 Beweis durch Induktion:
	 - *IA*: $n = 0$ klar
	 - *IS*:
	   \begin{align}
	   n\to n + 1: (1 + x)^{n + 1} &= (1 + x)^n(1 + x) \\
	   &\geq (1 + n x) (1 + x) = 1 + nx^2 + (n + 1) x \\
	   &\geq 1 + (n + 1) x~\text{da $x^2 \geq 0$} \tag*{$\square$}
	   \end{align}
*** Folgerung 1.54
	1. Sei $y\in(1,\infty)$. Dann gilt $\Forall c > 0 \exists n_0 \in \mathbb{N},\Forall n\geq n_0 y^n \in (c,\infty)$ ("Konvergenz" von $y^n$ gegen 0)
	2. Sei $y \in (-1,1)$. Dann gilt $\Forall \varepsilon > 0\exists n_0 \in \mathbb{N}\Forall n\geq n_0:y^n \in I_\varepsilon (0)$ ("Konvergenz" $y^n$ gegen 0)
**** Beweis
	 1. <<1541>> Für $x = y - 1 > 0$ gilt dann nach [[Lemma 1.53]] \[\underbrace{(1 + x)^n}_y \geq 1 + n x \Rightarrow y^n > n x\]
		Nach [[Lemma 1.52]] existiert für $c > 0$ ein $n_0 \in \mathbb{N}$ mit $n_0 > \frac{c}{x} \Rightarrow$
		\[\Forall n\geq n_0: y^n > n x \geq n_0 x \geq \frac{c}{x} x = c \Rightarrow \Forall n\geq n_0: y^n\in(c,\infty)\]
	 2. Für  $x = \frac{1}{\abs{y}} > 1 \xRightarrow{\text{nach [[1541]] mit } c = \frac{1}{\varepsilon}}$
		\[\Forall \varepsilon > 0\exists n_0\in\mathbb{N}\Forall n\geq n_0: x^n > \frac{1}{\varepsilon}\]
		\[\Rightarrow \frac{1}{\abs{y^n}} > \frac{1}{\varepsilon} \Rightarrow \abs{y^n} < \varepsilon \hfill \square\]
*** Satz 1.55 (Existenz der m-ten Wurzel)
	\[\Forall m\in\mathbb{N}, a\in\left[a,\infty)~\text{gilt}~\exists ! x\in\left[0,\infty): x^m = a\]
**** Beweis (Skizze 1, 2)
	 Wir geben ein Iterationsverfahren
	 \[p_3 (x) = m\]
	 \[a_3 x^3 + a_2 x^2 + a_1 x + a_0, a_3 > 0\]
	 Ohne Beschränkung der Allgemeinheit $a > 0,m\geq 2$, $x$ muss die Gleichung $x^m -a = 0$ lösen, das heißt Nullstelle der Funktion $f:\left[0,\infty) \to \mathbb{R},x\mapsto x^m - a$ suchen.
	 Diese approximieren wir nach dem *Newton Verfahren* \\
	 $x_0$ sodass $x_0^m - a \geq 0$
	 \[x_n - x_{n + 1} = \frac{f(x_n)}{f'(x_n)} \Leftarrow \frac{f(x_n)}{x_n - x_{n + 1}} = f'(x_n)\]
	 \[x_{n+1} := \underbrace{x_n - \frac{f(x_n)}{f'(x_n)}}_{F(x_n)} = x_n - \frac{x_n^m - a}{m x_n^{m - 1}}\]
	 \[= x_n(1 - \frac{1}{m}(1 - \frac{a}{x_n^m}))\]
	 Hoffnung: $x_n \to x^*$

	 [[Skizze 3]]

	 Sei $x_0^m > a$. Wir zeigen
	 1. <<1.55.1>> $x_n > 0$
	 2. <<1.55.2>> $x_n^m \geq a$
	 3. $x_{n + 1} \leq x_n$
	 *Beweis:*
	 1. Induktion
	 2. Induktion
		- $n = 0, x_0^m \geq \Rightarrow x_0 > 0$, da $a > 0,x_0\geq 0$
		- $n\to n + 1$ \[x_n > 0, x_n^m\geq a \Rightarrow x_{n + 1} = x_n(1 - \frac{1}{m}(1 - \frac{a}{x_n^m})) \geq 0\]
		  weil \[x_{n + 1}^n = \underbrace{x_n^m}_{\geq 0} (1 - \frac{1}{m}(1 - \frac{a}{x_n^m}))^m \underbrace{\geq}_{\text{Bernoulli}} x_n^m(1 - \frac{1}{m}(1 - \frac{a}{x_n^m}))  = 0\]
		  \Rightarrow $x_{n + 1} > 0$, da $a > 0$
	 3. Nach [[1.55.2]]: \[x_n^m \geq a \Rightarrow 0 \leq 1 - \frac{1}{m}(1 - \frac{1}{x_n^m}) \leq 1\]
		Nach [[1.55.1]]: \[x_m > 0 \Rightarrow x_{n + 1} = x_n(1 - \frac{1}{m}(1-\frac{a}{x_n^m})) < x_n\]
		Wegen [[1.55.1]] ist $M = \{x_n:n\in\mathbb{N}_0\}$ nach unten beschränkt \Rightarrow
		\[x:= \inf M~\text{existiert}\]
		Wir wollen zeigen, dass $x^m = a$. Es gilt \[x \leq x_{n + 1} = (1 - \frac{1}{m})x_n + \frac{1}{m}\frac{a}{x^{m -1}_n}\]
		\[\leq (1 - \frac{1}{m})x_n + \frac{a}{m}\sup \{\frac{1}{x_n^{m - 1}\mid x\in\mathbb{N}_0}\} \]
	 4. <<1.55.4>> Es gilt nach nach [[1.56.2]]
		\[a\leq \inf \{x_n^m \mid n\in \mathbb{N}_0\} = (\inf \{x_n \mid n\in \mathbb{N}_0\})^m = x^m\]
		und damit $x > 0$ \\
		Ferner gilt
		\[y = \sup \{\frac{1}{x_n^{m - 1}} \mid n\in\mathbb{N}_0\} = \inf \{x_n^{m - 1}\mid x \in \mathbb{N}_0\}^{-1}\]
		mit [[Lemma 1.56]] \[= (\frac{1}{\inf\{x_n \mid n\in\mathbb{N}_0\}})^{m - 1} = \frac{1}{x^{m -1}} \Rightarrow a y\leq \frac{a}{x^{m - 1}}\]
	 5. <<1.55.5>> Von oben wissen wir, dass $x \leq a y$
		\[\Rightarrow x\leq a y  \leq \frac{a}{x^{m -1}} \Rightarrow x^m \leq a\]

	 Aus [[1.55.4]] und [[1.55.5]] folgt $x^m = a\hfill\square$

*** Lemma 1.56
	1. Seien für $n\in \mathbb{N}_0:y_n > 0$ und $\inf \{x_n\mid x\in\mathbb{N}_0\} > 0$ \\
	   Dann gilt \[\sup \{\frac{1}{y_n} \mid n\in \mathbb{N}_0\} = \frac{1}{\inf \{y_n \mid n\in\mathbb{N}_0\}}\]
	2. <<1.56.2>> Seien für $n\in\mathbb{N}_0,y_n > 0, k\in\mathbb{N}_0$. Dann gilt:
	   \[\inf \{y_n^k \mid n\in\mathbb{N}_0\} = (\inf \{y_n\mid n\in\mathbb{N}_0\})^k\]
	(ohne Beweis)

* Komplexe Zahlen
  *Motivation:* $x^2 + 1 = 0$ nicht lösbar in $\mathbb{R}$ \\
  Wir betracheten die Menge der Paare $\{x,y\} = \mathbb{R}\times\mathbb{R}$ auf denen die Addition und Multiplikation wie folgt definiert ist:
   - <<KA>> (KA) $\{x_1,y_1\} + \{x_2,y_2\} = \{x_1 + x_2, y_2 + y_2\}$
   - <<KM>> (KM) $\{x_1,y_1\} \cdot \{x_2,y_2\} = \{x_1 x_2 - y_1 y_2, x_1 y_2 + x_2 y_1\}
** Komplexer Zahlkörper
   1. Die Menge der Paare $z = \{x,y\} \in \mathbb{R}\times\mathbb{R}$ mit Addition [[KA]] und Multiplikation [[KM]] bildet den Körper $\mathbb{C}$ der *komplexen Zahlen* mit den neutralen Elementn $\{0,0\}$ und $\{1,0\}$
   2. Die Gleichung $z^2 + \{1,0\} = \{0,0\}$ hat in $\mathbb{C}$ zwei Lösungen, welche mit $\I:= \{0,\pm 1\}$ bezeichnet werden
   3. Der Körper $\mathbb{R}$ ist mit der Abbildung $x\in\mathbb{R}:x\mapsto\{x,0\}\in\mathbb{C}$ isomorph zu einem Unterkörper von $\mathbb{C}$
*** Beweis
	1. Die Gültigkeit des Kommutativitäts-, Assoziativs-, und Distributibitätsgesetzes verifiziert man durch Nachrechenen. \\
	   Neutrale Elemente: Wir lösen die Gleichung $a + z = \{0,0\}$ für beliebige gegebene $a\in\mathbb{C},a=\{a_1,a_2\}$
	   \[\Rightarrow z = \{-a_1, -a_2\}\]
	   \[a\cdot z = \{1,0\}\]
	   \[z = \frac{1}{a}:=\{\frac{a_1}{a_1^2 + a_2^2},-\frac{a_2}{a_1^2 + a_2^2}\},~\text{weil}~a\cdot\frac{1}{a}\]
	   \[\text{weil}~a\frac{1}{a}=\{a_1\frac{a_1}{a_1^2 + a_2^2} + \frac{a_2^2}{a_1^2 + a_2^2},\frac{a_1 a_2}{a_1^2 + a_2^2} - \frac{a_2 a_1}{a_1^2 + a_2^2}\}\]
	2. $i:= \{0,1\}$ hat die Eigenschaft
	   \[1 + \I^2 = \{1,0\} + \{0^2 - 1^2, 0\} = \{0,0\} \Rightarrow 1+\I^2 = 0\]
	   Ähnlich $1 + (-\I)^2 = 0$
	3. Die Zuordnung $x\in\mathbb{R}:x\mapsto\{x,0\}\in\mathbb{C}$ bildet $\mathbb{R}$ bijektiv auf eine Untermenge von $\mathbb{C}$ ab, welche bezüglich der komplexen Addition und Multiplikation wieder ein Körper ist $\hfill\square$
** Notation
   $z = \{x,y\} =: x + \I y,~x,y\in\mathbb{R}$
   - $x$ ist Realteil $x = \Re{z}$
   - $y$ ist Imaginärteil $x = \Im{z}$
   \[z_1 + z_2 = (x_1 + \I y_1) + (x_2 + \I y_2) = \underbrace{x_1 + x_2}_{\Re (z_1 + z_2)} + \I\underbrace{(y_1 + y_2)}_{\Im (z_1 + z_2)}\]
   \[z_1 z_2 = (x_1 + \I y_1)(x_1 + \I y_2) = x_1 x_2 + \I y_1 x_2 + \I y_2 x_1 + (\I y_1)(\I y_2) = \underbrace{x_1 x_2 - y_1 y_2}_{\Re (z_1 z_2)} + \I\underbrace{(x_1y_2 + y_1 x_2)}_{\Im (z_1,z_2)}\]
** TODO Graphische Darstellung
** Bemerkung
   Die reellen Zahlen  sind durch $\Im z = 0$ charakterisiert.
   \[z_1 = z_2 \Rightarrow x_1 + \I y_i = x_2 + \I y_2 \Leftrightarrow x_1 = x_2,y_1 = y_2\]
** Korollar 1.59
   Jede quadratische Gleichung
   \[z^2+p z + q = 0,~p,q\in\mathbb{R}\]
   besitzt in $\mathbb{C}$ genau zwei Lösungen
   \[z_1,2 = \begin{cases} -\frac{1}{2}\pm \frac{1}{2}\sqrt{p^2 - 4q} & p^2 \geq 4q \\ -\frac{1}{2}\pm \I\frac{1}{2}\sqrt{\abs{p^2 - 4q}} & p^2 - 4q < 0 \end{cases} \]
** Fundamentalsatz der Algebra
   Jede algebraische Gleichung der Form \[z^n + \sum_{i = 0}^{n - 1} a_i z^i = 0\]
   hat in $\mathbb{C}$ mindestens eine Lösung. Beweis \rightarrow Funktionstheorie
** Betrag
   Für komplese Zahlen lässt sich ein Absolutbetrag definieren
   \[r = \abs{z} = \sqrt{x^2 + y^2}\]
   Damit:
   \begin{align}
   x &= r\cos{\alpha}
   y &= r\sin{\alpha}
   z &= x + \I y = r(\cos{alpha} + \I\sin{\alpha})
   \end{align}
** Konjugation
   Zu einem $z = x + \I y\in\mathbb{C}$ definieren wir eine konjugierte komplexe Zahl \[\bar z = x - \I y \in\mathbb{C}\]
   Dann gilt \[\abs{z}^2 = x^2 + y^2 = z\bar z\]
   Aus der Definition:
   - $\overline{z_1 + z_2} = \overline{z_1} + \overline{z_2}$
   - $\overline{z_1 * z_2} = \overline{z_1} * \overline{z_2}$
   - $x = \frac{z + \bar z}{2}$
   - $y = \frac{z - \bar z}{2\I}$
* Folgen
  Eine Folge von reellen Zahlen wird gegeben durch eine Abbildung \[\mathbb{N}_0 \to \mathbb{R},n\mapsto x_n\]
  Wir bezeichnen die Folge auch mit $(x_n)_{n\in\mathbb{N}_0}$

  Topologische Struktur auf Mengen.
  - Abstände in $\mathbb{R}^1$ Betrag $\abs{x - y}$ $\xrightarrow{\text{Verallgemeinerung}}$ Norm / Metrik
  - Umgebung in $\mathbb{R}^1$ $\varepsilon$-Intervall $\xrightarrow{\text{Verallgemeinerung}}$ Kugel Umgebung

  Wir betrachten Folgen $\mathbb{N}\to\mathbb{R}, n\mapsto a_n$ (oder $\mathbb{C}$)
** Definition 2.1 Konverenz
   Wir sagen, dass die Folge $(a_n)_{n\in\mathbb{N}}$ in $\mathbb{K}$ ($\mathbb{R}$ oder $\mathbb{C}$) gegen den Grenzwert (oder Limes) $a\in\mathbb{K}$ konvergiert
   \[a_n \xrightarrow{n\to\infty} a~(a=\lim_{n\to\infty} a_n)\]
   wenn für beliebiges $\varepsilon > 0$ von einem $n_\varepsilon \in\mathbb{N}$ an gilt
   \[\abs{a_n - a} < \varepsilon,n\geq n_\varepsilon\]
   \[\Leftrightarrow \Forall\varepsilon > 0\exists n\varepsilon \in\mathbb{N}:\Forall n\geq n_\varepsilon a_n \in I_\varepsilon(a)\]
** Folgerung 2.2
   Sei $(a_n)_{n\in\mathbb{N}}$ eine monoton wachsende beziehungsweise fallende Folge reeller Zahlen $M=\{a_n\mid n\in\mathbb{N}\}$ und sei nach oben beziehungsweise unten beschränkt. Dann gilt \[a_n\to\sup M, a_n\to\inf M\]
   Beweis \to Übungen
** Definition 2.3 Cauchy Folgen
   Eine Folge $(a_n)_{n\in\mathbb{N}}$ heißt Cauchy-Folge wenn:
   \[\Forall\varepsilon > 0\exists n_\varepsilon \in\mathbb{N}\Forall n,m \geq n_\varepsilon: \abs{a_n - a_m} < \varepsilon \]
   (Cauchy Kriterium)
** Definition 2.4 Teilfolge
   Eine Teilfolge einer gegebenen Folge $(a_n)_{n\in\mathbb{N}}$ ist eine Auswahl $(a_{n_k})_{k\in\mathbb{N}}$, wobei $a_{n_k}$ auch die Glieder von $(a_n)_{n\in\mathbb{N}}$ sind
   \begin{ex}[Beispiel 2.5]
   \[a_n = \frac{1}{m}\] ist eine Cauchy-Folge. Für ein $\varepsilon > 0$ wählen wir $n_\varepsilon$ so dass $n_\varepsilon > \frac{1}{\varepsilon}$. Für beliebiges $n\geq m > N$
   \[\abs{a_m - a_n} = \abs{\frac{1}{m} - \frac{1}{n}} = \frac{n - m}{m n} \leq \frac{n}{m n} = \frac{1}{m} < \frac{1}{n_\varepsilon} < \varepsilon\hfill\square\]
   \end{ex}
   \begin{thm}[Jede Cauchy-Folge ist beschränkt]
   \end{thm}
   \begin{proof}
   Sei $(a_n)_{n\in\mathbb{N}}$ eine Cauchy-Folge. Angenommen, die Folge ist nicht beschränkt. Dann gibt es eine Teilfolge $(a_{n_k})_{k\in\mathbb{N}}$ mit
   \[\abs{a_{n_k}}\xrightarrow[k\to\infty]{} \infty\]
   Aus dieser Teilfolge kann man eine weitere Teilfolge
   \[(a_{n_{k_l}})_{l\in\mathbb{N}}\]
   extrahieren
   \[\abs{a_{n_{k_{i + 1}}}} > 2 \abs{a_{n_{k_l}}}\quad l\in\mathbb{N}\]
   Dann gilt
   \[\abs{a_{n_{k_{i + 1}}} - a_{n_{k_l}}} \geq \abs{a_{n_{k_{i + 1}}}} - \abs{a_{n_{k_l}}} > \abs{a_{n_{k_l}}}\xrightarrow[k\to\infty]{} \infty\]
   im Widerspruch zur Cauchy-Folgen Eigenschaft.
   \end{proof}
   \begin{thm}[Jede konvergente Folge ist Cauchy-Folge]
   \end{thm}
   \begin{proof}
   \begin{align*}
   a_n \xrightarrow[k\to\infty]{} a &\Rightarrow \Forall \varepsilon > 0 \exists n_\varepsilon \in\mathbb{N} \Forall n\geq n_\varepsilon: \abs{a - a_n} < \frac{\varepsilon}{2} \\
   &\Rightarrow \Forall n,m\in n_\varepsilon: \abs{a_n - a_m} \leq \abs{a_n - a} + \abs{a - a_m} <\frac{\varepsilon}{2} + \frac{\varepsilon}{2} \tag*{\qedhere}
   \end{align*}
   \end{proof}
   \begin{lemma}
   \label{lemma:one_limit}
   Sei $(a_n)_{n\in\mathbb{N}}$ eine Folge in $\mathbb{K}$ ($\mathbb{R}$ oder $\mathbb{C}$) welche gegen $a\in\mathbb{K}$ und $\tilde a \in \mathbb{K}$ konvergiert. Dann ist $a = \tilde a$.
   \end{lemma}
   \begin{proof}
   Beweis durch Wiederspruch. \\
   Falls $\abs{a - \tilde a} > 0$, dann
   \[\exists n_\varepsilon \in\mathbb{N}\Forall n\geq n_\varepsilon \varepsilon = \abs{a - \tilde a}, \abs{a_n - a} < \frac{\varepsilon}{2}\]
   und ein $m_\varepsilon$, sodass
   \[\abs{a_n - \tilde a < \frac{\varepsilon}{2}} \Forall n\geq m_\varepsilon\]
   Dann für $n \geq \max \{n_\varepsilon, m_\varepsilon\}$:
   \[\abs{a - \tilde a} \leq \abs{a - a_n} + \abs{a_n - \tilde a} < \varepsilon\text{\lightning}\]
   \textbf{Wiederspruch} $\Rightarrow a = \tilde a$
   \end{proof}
   \begin{remark}
   Die Mengen Abständen heißen *vollständig*, wenn jede Cauchy-Folge in $M$ konvergiert
   \end{remark}
   \begin{defn}[Häufungwert, Häufungspunkt]
   Ein $a\in\mathbb{K}$ heißt Häufungswert einer Folge $(a_n)_{n\in\mathbb{N}}$ in $\mathbb{K}$, wenn es zu beliebigen $\varepsilon > 0$ unendlich viele Folgenelemente $a_n$ gibt mit $\abs{a - a_n} < \varepsilon$

   Ein $a\in\mathbb{K}$ heißt Häufungspunkt einer Teilmenge $M$ von $\mathbb{K}$, wenn $\Forall \varepsilon > 0$ existieren unendlich viele $x\in M$, sodass $\abs{a - x} < \varepsilon$
   \end{defn}
   \begin{ex} \mbox{}
   \begin{enumerate}
   \item $a_n = (-1)^n, n\in\mathbb{N}$
   \begin{itemize}
	  \item divergente Folge
	  \item besitzt 2 Häufungswerte $a^{(1)} = 1, a^{(2)} = -1$
   \end{itemize}
   \item Wir nehmen $a_n \xrightarrow[n\to\infty]{} a, b_n \xrightarrow[n\to\infty]{} b$ und definieren eine neue Folge $c_n$ sodass
	  \begin{align*}
	  c_{2n} &:= b_n,n\in\mathbb{N} \\
	  c_{2n + 1} &:= a_n,n\in\mathbb{N}
	  \end{align*}
	  $(c_n)_{n\in\mathbb{N}}$ hat 2 Häufungswerte $a$ und $b$
   \end{enumerate}
   \end{ex}
   \begin{remark}
   Nach \ref{lemma:one_limit} hat die konvergente Folge 1 Haufungswert
   \end{remark}
   \begin{lemma}[2.11]
   \label{lemma:cauchy_haufungswert}
   Sei $(a_n)_{n_\in\mathbb{N}}$ eine Cauchy-Folge in $\mathbb{K}$ und $a$ ein Häufungswert von $(a_n)_{n\in\mathbb{N}}$, dann konvergiert $a_n \xrightarrow[n\to\infty]{} a$
   \end{lemma}
   \begin{proof}
   Sei $\varepsilon > 0$ beliebig vorgegeben. Wir wählen $n_\varepsilon \in\mathbb{N}$ sodass
   \[\abs{a_n - a_m} < \frac{\varepsilon}{2}\Forall n,m > n_\varepsilon\hfill\text{ (aus Cauchy-Folge)}\]
   und $m_\varepsilon > n_\varepsilon$ mit
   \[\abs{a - a_{m_\varepsilon}} < \frac{\varepsilon}{2}\hfill\text{ (Häufungswert)}\]
   Dann folgt
   \[\Forall n > m_\varepsilon: \abs{a - a_n} \leq \abs{a - a_{m_\varepsilon}} + \abs{a_{m_\varepsilon} - a_n} < \varepsilon \Rightarrow a_n \xrightarrow[n\to\infty]{} a \qedhere\]
   \end{proof}
   \begin{thm}
   \label{thm:finite}
   $A$ abgeschlossen $\Leftrightarrow$ ($a$ Häufungspunkt von $A \Rightarrow a\in A$)
   $A$ abgeschlossen in M $\Leftrightarrow$ $M\setminus A =: CA$ offen
   \end{thm}
   \begin{proof}
   $(\Leftarrow)$: \\
   Sei jeder Häufungspunkt von $A$ in $A$
   $x\in CA (=\mathbb{R}\setminus A) \Rightarrow x$ kein Häufungspunkt von $A, x\not\in A$
   \[\Rightarrow \varepsilon: I_\varepsilon (x) \cap A = \emptyset \Rightarrow \exists \varepsilon > 0: I_\varepsilon \subseteq CA\]
   $\Rightarrow CA$ offen $\Rightarrow A$ abgeschlossen \\
   $(\Rightarrow)$: \\
   Sei $A$ abgeschlossen, also $CA$ offen, ist Häufungspunkt $x\not\in A$ das heißt $x \in CA$, so gilt
   \[\exists \varepsilon > 0: I_\varepsilon \subseteq CA \Rightarrow I_\varepsilon (x) \cap A = \emptyset \text{lightning}\]
   \textbf{Wiederspruch} zur Definition von Häufungspunkt $\Rightarrow$ jeder Häufungspunk von $A$ ist in $A$
   \end{proof}
   \begin{lemma}[2.14]
   \label{lemma:monoton_in_r}
   Jede Folge $(a_n)_{n\in\mathbb{N}} \in \mathbb{R}$ besitzt eine monotone Teilfolge
   \end{lemma}
   #+begin_proof latex
   Sei $B=\{n\in\mathbb{N}\mid \Forall k\geq n, a_n \geq a_k\}$
   - Fall 1: $B$ unendlich. Wir zählen $B\subseteq \mathbb{N}$ monoton wachsed \
	 \begin{align*}
	 n_0 &= \min{B} \\
	 n_{k+1} &= \min\{n\in B, n > n_k\}
	 \end{align*}
	 Dann ist die Teilfolge $(a_{n_k})_{k\in\mathbb{N}}$ von $(a_n)_{n\in\mathbb{N}}$ monoton fallend
   - Fall 2: $B$ ist endlich oder leer
	 \begin{align*}
	 \Rightarrow &\exists n_0 \in\mathbb{N}: \Forall n\geq n_0: n\not\in B \\
	 \shortintertext{das heißt}
	 \exists k\leq n: a_n < a_k
	 \end{align*}
	 Damit können wir definieren
	 \[n_{k + 1} = \min\{k \geq n_k: a_{n_k} < a_k\}\]
	 und die Folge $(a_{n_k})_{k\in\mathbb{N}}$ ist monoton wachsed
   #+end_proof
   #+begin_ex latex
   1. $a_n = (-1)^n (1 + \frac{1}{n + 1}),\quad B=\{2 n \mid n \in\mathbb{N}\}$ monoton fallend
   2. $a_n = (-1)^n n, (a_{2k})_{k\in\mathbb{N}}$ ist monotone Teilfolge
   #+end_ex
   \begin{thm}[Satz von Bolzano Weierstrass]
   Sei $A\subseteq \mathbb{R}$ ( gilt in $\mathbb{R}^n$!) Folgende Aussagen sind äquivalent:
   \begin{enumerate}
   \item \label{bolzano:1} $A$ ist beschränkt abgeschlossen
   \item \label{bolzano:2} Jede Folge $(a_n)_{n\in\mathbb{N}}$ aus $A$ hat einen Häufungswert in $A$
   \item \label{bolzano:3} Jede Folge $(a_n)_{n\in\mathbb{N}}$ aus $A$ hesitzt eine in $A$ konvergente Teilfolge $(a_{n_k})_{k\in\mathbb{N}}$
   \end{enumerate}
   \end{thm}
   #+begin_proof latex
   Wir zeigen \ref{bolzano:3} $\Rightarrow$ \ref{bolzano:2} $\Rightarrow$ \ref{bolzano:1} $\Rightarrow$ \ref{bolzano:3} \\
   \ref{bolzano:3} $\Rightarrow$ \ref{bolzano:2}: \\
   Sei $(a_{n_k})_{k\in\mathbb{N}}$ konvergente Teilfolge von $(a_n)_{n\in\mathbb{N}}$ und $a = \lim_{k\to\infty} a_{n_k}$
   $a$ ist auch der Häufungswert der Folge $(a_n)_{n\in\mathbb{N}}$ \\
   \ref{bolzano:2} $\Rightarrow$ \ref{bolzano:1}: \\
   \begin{enumerate}
   \item Beschränktheit:
   Angenommen dies ist falsch. Dann
   \[\exists (a_n)_{n\in\mathbb{N}} \in A: \abs{a_n - a} \geq n \Forall n\in\mathbb{N}~(a\in A)\]
   Nach Voraussetzungen hat jede diese Folge einen Häufungspunkt $x\in A$ und es gilt
   \[\abs{x - a} \geq \abs{a_n - a} - \abs{a_n - x} \geq n - \abs{x - a_n}\]
   Dabei gilt $\abs{x - a_n} < 1$ für unendlich viele $n\in\mathbb{N}$ (aus Häufungswert)
   \[\Rightarrow \abs{x - a} \geq n - 1\]
   Für unendlich viele $n\in\mathbb{N}$ \lightning
   \item Abgeschlossenheit: Wir nutzen Satz \ref{thm:finite}
   Zu zeigen: wenn $a$ Häufungspunkt von $A \Rightarrow a\in A$
   Für
   \[I_{\frac{1}{n}}(a) = \{x\in\mathbb{R} \mid \abs{x - a} < \frac{1}{n}\}\]
   gilt
   \[I_{\frac{1}{n}}(a) \cap A \neq \emptyset \Rightarrow \exists a_n\in A: \abs{a_n - a} < \frac{1}{n}\]
   Die Folge $(a_{n_k})_{k\in\mathbb{N}} \to a$, da $\frac{1}{n}\to 0$
   Nach Voraussetzung hat $(a_n)_{n\in\mathbb{N}}$ einen Häufungswert $\tilde a \in A$. Wir zeigen $a = \tilde a$
   Sei $\varepsilon > 0$ beliebig.
   \begin{align*}
   &\exists n_\varepsilon\in\mathbb{N}: \abs{a - a_n} <\frac{\varepsilon}{2}\Forall n\geq n_\varepsilon \tag{\text{Aus }$a_n \to a$} \\
   &\exists m_\varepsilon\geq n_\varepsilon: \abs{\tilde a - a_{m_\varepsilon}} <\frac{\varepsilon}{2} \tag{\text{Aus Häufungswert}} \\
   &\Rightarrow \abs{a - \tilde a} \leq \abs{a - a_{m_\varepsilon}} + \abs{a_{m_\varepsilon}} < \varepsilon \\
   &\Rightarrow \abs{a - \tilde a} = 0 \\
   &\Rightarrow \tilde a = a \in A
   \end{align*}
   \end{enumerate}
   \ref{bolzano:1} $\Rightarrow$ \ref{bolzano:3}: \\
   Sei nun $(a_n)_{n\in\mathbb{N}}$ eine Folge in $A$, $(a_{n_k})_{k\in\mathbb{N}}$ eine monotone Teilfolge (nach \ref{lemma:monoton_in_r}), $(a_{n_k})$ ist beschränkt, da $A$ beschränkt ist $\Rightarrow (a_{n_k})$ ist konvergent ([[Folgerung 2.2]]) \\
   Wir müssen zeigen, dass
   \[a = \lim_{n\to\infty} a_{n_k} \in A\]
   \begin{align*}
   \intertext{Angenommen $a\not\in A \Rightarrow a \in \mathcal{C} A, \mathcal{C} A$ ist offen}
   \Rightarrow \exists I_\varepsilon (a) \subseteq \mathcal{C}A \Rightarrow I_\varepsilon (a) \cap A = \emptyset \\
   \shortintertext{Nun ist aber mit geeigneten $n_\varepsilon \in\mathbb{N}$}
   \Forall n\geq n_\varepsilon: a_{n_k} \in I_\varepsilon (a): a_{n_k} \in A \Rightarrow a_{n_k} \in I_\varepsilon (a) \cap A~\lightning \tag*{\qedhere}
   \end{align*}
   #+end_proof
   #+begin_remark latex
   - Erweiterung zu $\mathbb{R}^n$ möglich
   - Ein Raum heißt folgenkompakt, wenn jede beschränkte Folge eine konvergente Teilfolge hat
	 - Nach B-W Satz ist $\mathbb{R} (\mathbb{R}^n)$ folgenkompakt
   - In $\mathbb{R}$ alle Cauchy-Folgen konvergieren
	 - Cauchy Folge in $\mathbb{R} \Rightarrow$ beschränkt und Wertemenge ist abgeschlossen $\xRightarrow{B-W Satz} (a_n)_{n\in\mathbb{N}}$ hat einen Häufungswert in $A \xRightarrow{\ref{lemma:cauchy_haufungswert}}$ konvergiert gegen $a\in A$
   #+end_remark
** Rechenregeln für Grenzwerte von Folgen
   #+begin_thm latex
   Seien $(a_n)_{n\in\mathbb{N}}, (b_n)_{n\in\mathbb{N}}$ konvergente Folgen in $\mathbb{K} (\mathbb{R}~\text{oder}~\mathbb{C})$
   \[b_0 \neq 0 \Forall n\in\mathbb{N}, \lim_{n\to\infty} b_n \neq 0\]
   Dann gilt:
   1. $\displaystyle \lim_{n\to\infty} (a_n + b_n) = \lim_{n\to\infty} a_n + \lim_{n\to\infty} b_n$
   2. $\displaystyle \lim_{n\to\infty} (a_n b_n) = \lim_{n\to\infty} a_n \lim_{n\to\infty} b_n$
   3. $\displaystyle \lim_{n\to\infty} (\frac{a_n}{b_n}) = \frac{\lim_{n\to\infty} a_n}{\lim_{n\to\infty} b_n}$
   #+end_thm

   #+ATTR_LATEX: :options [2.15]
   #+begin_thm latex
   Seien $(a_n)_{n\in\mathbb{N}}, (b_n)_{n\in\mathbb{N}}$ konvergente Folgen in $\mathbb{R}$. Dann gilt
   1. $\displaystyle a_n \leq b_n \Forall n\in\mathbb{N} \Rightarrow \lim_{n\to\infty} a_n \leq \lim_{n\to\infty} b_n$
   2. $\displaystyle \abs{a_n} \leq b_n \Forall n\in\mathbb{N} \Rightarrow \abs*{\lim_{n\to\infty a_n}} \leq \lim b_n$
   #+end_thm
   #+begin_proof latex
   1. Sei $\varepsilon > 0$ vorgegeben
	  \begin{align*}
	  \exists n_\varepsilon:\Forall n\geq n_\varepsilon: b_n \leq \lim_{k\to\infty} b_n + \frac{\varepsilon}{2} \\
	  \shortintertext{und}
	  \lim_{k\to\infty} a_k \leq a_n + \frac{\varepsilon}{2} \\
	  &\Rightarrow \lim_{k\to\infty} a_k \leq a_n + \frac{\varepsilon}{2} \leq b_n + \frac{\varepsilon}{2} \leq \lim_{k\to\infty} b_k + \varepsilon \Forall \varepsilon > 0 \\
	  &\Rightarrow \lim_{\k\to\infty} a_k \leq \lim_{k\to\infty} b_k
	  \end{align*}
   2. Wir wählen $a_n = \abs{a_n}$ und müssen noch zeigen
	  \[\lim_{n\to\infty} \abs{a_n} = \abs{\lim_{n\to\infty}} a_n\tag{Übung}\]
   #+end_proof
** Geometrische Folge
   Die geometrische Folge ist definiert durch
   \[a_n = c q^n\]

   #+ATTR_LATEX: :options [2.16]
   #+begin_lemma latex
   $\Forall q\in\mathbb{R},\abs{q} < 1$ konvergiert die geometrische Folge $a_n = c q^n$ gegen Null.
   #+end_lemma
   #+begin_proof latex
   Sei $\varepsilon > 0$ gegeben. Nach Annahme ist $\abs{q} < 1 \Rightarrow \abs{q}^{-1} > 1$, somit $\abs{q}^{-1} = 1 + x$ für ein $x > 0$. \\
   \begin{align*}
   \intertext{Zu zeigen: $\abs{c q^n - 0} < \varepsilon$ für genug große $n$, das heißt}
   c(\frac{1}{1+x})^n < \varepsilon \Leftrightarrow \frac{c}{\varepsilon} < (1 + x)^n \\
   \intertext{Das Archimedische Axiom garantiert die Existenz von $n_0\in\mathbb{N}$:}
   n_0 > \frac{c}{x\varepsilon} - \frac{1}{x} = \frac{c - \varepsilon}{x\varepsilon} \\
   \Forall n\geq n_0: \frac{c}{\varepsilon} = (\frac{c}{x\varepsilon} - \frac{1}{x}x + 1 < n_0 x + 1 \leq n x + 1)
   \intertext{daraus folgt aus der Bernoulli Ungleichung}
   \frac{c}{\varepsilon} < (1 + x)^n \Rightarrow c q^n \to 0 \tag*{\qedhere}
   \end{align*}
   #+end_proof
   #+ATTR_LATEX: :options [2.17]
   #+begin_conc latex
   Die geometrische Reihe
   \[S_n = 1 + q + q^2 + \ldots + q^n = \sum_{i = 0}^n q^i\]
   konvergiert für $\abs{q} < 1$ und $\lim_{n\to\infty} S_n = \frac{1}{1 - q}$
   #+end_conc
   #+begin_proof latex
   \begin{gather*}
   \intertext{zu Beweisen mit Induktion}
   \string(1 - q\string)\string(1 + q + q^2 + \ldots + q^n\string) = 1 + q^{n + 1} \\
   \Rightarrow S_n - \frac{1}{1 - q} = \frac{1 - q^{n + 1} - 1}{1 - q} = -\frac{q^{n + 1}}{1 - q} \\
   \abs{S_n - \frac{1}{1 - q}} = c\abs{q}^n < \varepsilon \Forall n\geq n_\varepsilon \\
   \intertext{$c = \abs*{\frac{1}{1 - q}}$}
   s_n \to \frac{1}{1 -q} \tag*{\qedhere}
   \end{gather*}
   #+end_proof
   #+ATTR_LATEX: :options [2.18]
   #+begin_ex latex
   \mbox{}
   1. $\displaystyle \lim_{n\to\infty} \frac{10^n}{n!} \leq \lim_{n\to\infty}cq^n$ mit $\abs{q} < 1$
   2. $a_n = \sqrt{n}(\sqrt{n + 1} - \sqrt{n}) = \sqrt{n} \frac{n + 1 - 1}{\sqrt{n + 1} + \sqrt{n}} = \frac{\sqrt{n}}{\sqrt{n + 1}} + \sqrt{n} = \frac{1}{\sqrt{1 + 1_n} + 1} \xrightarrow{n \to \infty} \frac{1}{2}$
   3. $a_n = \sqrt[m]{x}$, $x$ gegeben, $\xrightarrow{n\to\infty} 1$ \hfill Übungen
   4. $a_n = \sqrt[n]{m}\xrightarrow{n\to\infty} 1$
   5. $a_n = \sum_{i = 0}^{n} \frac{1}{i!}$
	  - $(a_n)_{n\in\mathbb{N}}$ ist monoton wachsend
	  - beschränkt: $a_n < 3 \Forall n\in\mathbb{N}$
	  - $\Rightarrow (a_n)_{n\in\mathbb{N}}$ konvergiert, Limes ist sogennante Zahl $\euler$
   6. $(a_n)_{n\in\mathbb{N}}$ rekursiev definiert: $a_0 = 0, a_1 = 1, a_n = a_{n - 1} + a_{n - 2}$ Fibonacci Folge
   #+end_ex
