#+AUTHOR: Robin Heinemann
#+TITLE: Analysis I (Marciniak-Czochra)
#+LATEX_HEADER: \usepackage{siunitx}%
#+LATEX_HEADER: \usepackage{fontspec}%
#+LATEX_HEADER: \sisetup{load-configurations = abbrevations}%
#+LATEX_HEADER: \newcommand{\estimates}{\overset{\scriptscriptstyle\wedge}{=}}%
#+LATEX_HEADER: \usepackage{mathtools}%
#+LATEX_HEADER: \DeclarePairedDelimiter\abs{\lvert}{\rvert}%
#+LATEX_HEADER: \DeclarePairedDelimiter\norm{\lVert}{\rVert}%
#+LATEX_HEADER: \DeclareMathOperator{\Exists}{\exists}%
#+LATEX_HEADER: \DeclareMathOperator{\Forall}{\forall}%
#+LATEX_HEADER: \def\colvec#1{\left(\vcenter{\halign{\hfil$##$\hfil\cr \colvecA#1;;}}\right)}
#+LATEX_HEADER: \def\colvecA#1;{\if;#1;\else #1\cr \expandafter \colvecA \fi}

* Einleitung
  Webseite www.biostruct.uni-heidelberg.de/Analysis1.php
  Klausurzulassung: 50%
  Klausur 18.2.2017 9-12Uhr
* Mengen und Zahlen
** Logische Regeln und Zeichen
*** Quantoren
    | $\Forall x$  | für alle $x$                 |
    | $\exists x$  | es gibt (mindestens) ein $x$ |
    | $\exists! x$ | es gibt genau ein $x$        |
*** Hinreichend und Notwendig
	- $A\Rightarrow B$: wenn $A$ gilt, gilt auch $B$, $A$ ist *hinreichend* für $B$, daraus folgt: $B$ ist *notwendig* für $A$, Ungültigkeit von $B$ impliziert die Ungültigkeit von $A$ ($\neg B \Rightarrow \neg A$)
	- $A \Leftrightarrow B$: $A$ gilt, genau dann, wenn $B$ gilt
*** Beweistypen
**** Direkter Schluss
	 $A\Rightarrow B$
***** Beispiel
	  $m$ gerade Zahl $\Rightarrow$ $m^2$ gerade Zahl
****** Beweis
	   $m$ gerade $\Rightarrow \exists n\in\mathbb{N}~\text{sodass}~m = 2n \Rightarrow m^2 = 4n^2 = 2k,~\text{wobei}~k=2n^2\in\mathbb{N} \square$
**** Beweis der Transponerten (der Kontraposition)
	 Zum Beweis $A\Rightarrow B$ zeigt man $\neg B\Rightarrow \neg A~(A\Rightarrow B)\Leftrightarrow (\neg B) \Rightarrow (\neg A)$
***** Beispiel
	  Sei $m\in\mathbb{N}$, dann gilt $m^2~\text{gerade}~\Rightarrow m~\text{gerade}$
****** Beweis
	   Wir zeigen: $m$ ist ungerade $\Rightarrow m^2$ ungerade
	   \[\exists n\in\mathbb{N}:~m=2n+1\Rightarrow m^2 = (2n+1)^2 = 2k+1, k=2n^2 + 2n\in\mathbb{N}\Rightarrow m^2~\text{ungerade} \square\]
**** Indirekter Schluss ( Beweis durch Wiederspruch)
	 Man nimmt an, dass $A\Rightarrow B$ nicht gilt, das heißt $A \wedge \neg B$ und zeigt, dass dann für eine Aussage $C$ gelten muss $C\Rightarrow \neg C$, also ein Wiederspruch
***** Beispiel
	  $\not\exists q\in\mathbb{Q}: a^2 = 2$
****** Beweis
	   Wir nehmen an, dass $\exists a\in\mathbb{Q}: a^2=2$ Dann folgt:
	   $\exists b,c\in\mathbb{Z}$ teilfremd (ohne Einschränkung, denn sonst kürzen soweit wie möglich) mit $a=\frac{b}{c}$
	   Falls \[a^2=2\Rightarrow (\frac{b}{c})^2=2=\frac{b^2}{c^2}=2 \Rightarrow b^2 = 2c^2 \Rightarrow b^2~\text{gerade}~\Rightarrow b~\text{ist gerade (schon gezeight)}\] \[\Rightarrow\exists d\in\mathbb{N}~\text{sodass}~b=2d\Rightarrow b^2=4d^2\]
	   Außerdem $b^2=2c^2\Rightarrow 2c^2=4d^2\Rightarrow c^2=2d^2\Rightarrow c$ ist auch gerade. Also müssen $b$ und $c$ beide gerade sein, also nicht teilerfremd, damit haben wir einen Widerspruch hergeleitet $\square$
*** Summenzeichen und Produktzeichen
**** Summenzeichen
	 Wir definieren für $m > 0$ \[\sum_{k=m}^m a_k := a_m + \ldots + a_n\] falls $n\geq m$
	 \[\sum_{k=m}^n a_k := 0\] falls $n < m$ (sogennante leere Summe)
**** Produktzeichen
	 \[\prod_{k=m}^n a_k := \begin{cases} a_m \cdot ... \cdot a_n & \text{falls}~n\geq m\\ 1 & \text{falls}~n<m~\text{(sog. leeres Produkt)}\end{cases}\]
** Mengen
*** Definition
	(Georg cantor 1885) Unger einer _Menge_ verstehen wir jede Zusammenfassung $M$ von bestimmten wohlunterschiedenen Objekten (welche die Elemente von $M$ genannt werden), zu einem Ganzen
	$M$ dadurch ist charakterisiert, dass von jedem vorliegendem Objekt $x$ feststeht, ab gilt
	- $x\in M$ (x Element von M)
	- x \not\in M (x kein Element von M)
	\[M = \{x_1, x_2, \ldots, x_n\}\]
	\[M=\{x\mid A(x)\} \rightarrow~\text{eine Menge}~M\text{für die}~x\in\ M \Leftrightarrow A(x)\]
*** Mengenrelationen
	- Mengeninklusion $A\subseteq M$ ($A$ ist eine Teilmenge von $M$)
	  \[\Forall x: (x\in A \Rightarrow x\in M)\], zum Beispiel $\mathbb{N} \subseteq \mathbb{Z}$
	- \[A = B \Leftrightarrow \Forall x: (x\in A \Leftrightarrow x\in B)\]
	- \[A \subset M~\text{(strikte Teilmenge)}~\Leftrightarrow A\subset M \wedge A \neq M\]
	- \[\emptyset:~\text{leere Menge}~\not\exists x: x\in\emptyset\]. Wir setzen fest, dass $\emptyset$ eine Teilmenge jeder Menge ist. Zum Beipsiel \[\{x\in\mathbb{R}: x^2 + 1 = 0\}\]
	- Durchschnitt \[A\cup B := \{x\mid x\in A \wedge x\in B\}\]
	- Vereinigung \[A\cap B := \{x \mid x\in A \vee x\in B\}\]
	- Differenz (auch Komplement von $B$ in $A$) \[A\setminus B := \{x\mid x\in A \wedge x\not\in B\} := C_a B~\text{(auch $B^c$)}\]
*** Potenzmenge
	Potenzmenge $A$
	\[\mathcal{P}(A) := \{B\mid B\subseteq A\}\]
	Alle Teilmengen von $A$
**** Beispiel
	 \[\mathcal{P}(\{1,2\}) = \{1\}, \{2\}, \{1,2\}, \emptyset\]
*** Familien von Mengen
	Sei $I$ eine Indexmenge, $I \subseteq \mathbb{N}, (A_i)_{i\in I}$ eine Familie von Mengen $A$
**** Durchschnitt von $A$
	 \[\cap_{i\in I} = \{x\mid \Forall_{i\in I} x\in A_i\}\]
**** Vereinigung
	 \[\cup_{i\in I} = \{x\mid\exists i\in I: x\in A_i\}\]
*** Rechenregeln
	$A,B,C,D$ seien Mengen
	- $\emptyset \subseteq A$
	- $A\subseteq A$ \hfill Reflexivität
	- $A\subseteq B, B\subseteq C \Rightarrow A\subseteq C$ \hfill Transitivität
	- $A\cap B = B\cap A$ \\ $A\cup B = B\cup A$ \hfill Kommutativität
	- $(A\cap B)\cap C = A\cap (B\cap C)$ \\ $(A\cup B) \cup C = A\cup (B\cup C)$ \hfill Assoziativität
	- $A\cap (B\cup C) =(A\cap B) \cup (A\cap C)$ \\ $A\cup (B\cap C) =(A\cup B) \cap (A\cup C)$
	- Eigenschaften der Komplementbildung: \\
	  Seien $A,B \subseteq D (C_D A: = D\setminus A)$, dann gilt \[C_D (C_D A) = A\] \[C_D(A\cap B) = C_D A \cup C_D B\] \[C_D(A\cup B) = C_D A \cap C_D B\]
	  - Beweis:
		\[x\in C_D(A\cap B) \Leftrightarrow x\in D \wedge (x\not\in (A\cap B)) \Leftrightarrow x\in D \wedge (x\not\in A \vee x\not\in B)\] \[\Leftrightarrow (c\in D\wedge x\not\in A) \cup x\in D \wedge x\not\in B\] \[\Leftrightarrow x\in D\setminus A \cup x\in D\setminus B \Leftrightarrow x\in D\setminus(A\cup B)~\square\]
      - Bemerkung: Komplement kann man auch mit $A^c$ bezeichnen
*** geordneter Tupel
   	Sei $x_1, x_2, \ldots, x_n$ (nicht notwendig verschiedene) Objekte. Ein geordneter n-Tupel \[(x_1,x_2,\ldots,x_n) = (y_1,\ldots,y_n) \Leftrightarrow x_1 = y_1, \ldots, x_n = y_n\]
   	Beachte:
   	\[\{x_1, \ldots, x_n\} = \{y_i,\ldots,y_n\}\not\implies x_1 = y_1, \ldots, x_n = y_n\]
*** Kartesisches Produkt
	Seien \[A_1\times A_2\times \ldots \times A_n = \{(x_1,x_2,\ldots,x_n)\mid x_j \in A_j j\in\mathbb{N}, j \leq n\}\]
**** Beispiel
	 - \[\mathbb{Z}^2 = \mathbb{Z}\times \mathbb{Z}\]
	 - $R^n$ m-dimensionaler Raum von reellen Zahlen
*** Äquivalenzrelation
	Eine Äquivalenzrelation auf eine Menge $A$ ist eine Beziehung zwischen ihren Elementen (Bezeichnung: $a\tilde b$), sodass
	- Für jede zwei $a,b\in A$ gilt entweder $a\tilde b \vee a\not\tilde b$
	- $a\tilde a$ \hfill Reflexivität
	- $a\tilde b \Rightarrow b\tilde a$ \hfill Symmetrie
	- $a\tilde b, b\tilde c \Rightarrow a\tilde c$\hfill Transitivität
    Mit Hilfe einer Äquivalenzrelation lassen sich die Elemente einer Menge in sogenannte Äquivalenzklassen einordnen: $[a]:\{b\in A\mid b\tilde a\}$
** Relationen und Abbildungen
*** Relationen
	Unter einer *Relation* verstehen wir eine Teilmenge $R\subseteq X\times Y$ wobei $X, Y$ Mengen sind. Für $x\in X$ definieren wir, das *Bild* von $x$ unter $R$
	\[R(X) := \{y\in Y | mid (x,y) \in R\}\]
	und *Definitionsbereiche von $R$ (bezüglich $X$)
	\[D(R):= \{x\in X\mid R(x)\neq\emptyset\}\]
*** Graph der Abbildung
	$R\subseteq X\times Y$ heißt Graph der Abbildung (Funktion) \[f:X\rightarrow Y \Leftrightarrow D(R) = X, \Forall x\in X: R(x) = \{f(x)\}\]
	also enthält $R(X)$ genau ein Element. \\
	$X$ heißt Definitionsbereich von $f$ \\
	$Y$ heißt Werte- oder Bildbereich von $f$ (Bild) \\
	$x\in X$ heißt Argument \\
	$f(x)\in Y$ heißt Wert von $f$ an der Stelle x
**** Beispiel
	 $f: \mathbb{R}\rightarrow\mathbb{R}, x\rightarrow x^2$ dann ist der Graph von $f = \{(x,y)\in\mathbb{R^2}, y=x^2\}$
***** Bemerkung
	  \[M^{*}(x) = \{(x,y)\in\mathbb{R}^2;x=y^2\} = \{(x,y)\in\mathbb{R}^2: x \geq 0, y=\sqrt{x} \vee y = -\sqrt{x}\}\]
	  Ist kein Graph einer Funktion $\mathbb{R}\rightarrow\mathbb{R}$, denn $M^{ *}(x) = \{\sqrt{x},-\sqrt{x}, x\geq 0\}$
	  $f$ heißt
	  - surjektiv, wenn gilt $f(X) = Y$
	  - injectiv, $\Forall x_1,x_2\in X: f(x_1) = f(x_2) \Rightarrow x_1 = x_2$
	  - bijektiv, wenn $f$ surjektiv und injectiv ist
*** Umkehrabbildung
	Sei die Abbildung $f: X\rightarrow Y$ bijektiv. Dann definieren wir die Umkehrabbildung $f^{-1}:Y\rightarrow X$ durch $y\rightarrow x\in X$, eindeutig bestimmt durch $y = f(x)$
**** Bemerkung
	 \[(x,y) \in~\text{Graph }f\Leftrightarrow (y,x)\in~\text{Graph }f^{-1}\]
*** Komposition
	Seien $f:X\rightarrow Y, g:Y\rightarrow Z$ Abbildungen. Die Komposition von $g$ und $f$ \[g\circ f: X\rightarrow Z~\text{ist durch}~x\rightarrow g(f(x))~\text{definiert}\]
*** Identitäts Abbildung
	Für jede Menge $X$ definieren wir dei identische Abbildung \[I_d(A) = I_A: A\rightarrow A,~\text{durch}~x\rightarrow x\]
**** Beispiel
	 - \[\{(x,y)\in\mathbb{R}^2\mid x^2 + y^2 = 1\} = S^1\] \[S^{n-1} := \{(x_1 \ldots x_n) \in \mathbb{R}^n; \sum_{i = 1}^n x_i^2 = 1\}\] $(n - 1)$ dimensionale sphere in $\mathbb{R}^n$
	 - Seien $X,Y$ Mengen, $M\subseteq X\times Y, f:M\rightarrow X$ \\ $f$ heißt Projektion, $f$ surjektiv \[f(M) = \{x\mid \exists y \in Y : (x,y) \in M\} = X\]
*** Homomorphe Abbildungen
	Existieren auf Mengen $X$ und $Y$ mit gewissen Operationen $\oplus_x$ bzw. $\oplus_y$ (zum Beispiel AAddition, Ordungsrelation), ho heißt die Abbildung $f:X\to Y$ homomorph (strukturerhaltend), wenn gilt $\Forall x_1,x_2 \in X f(x_1\oplus_x x_2) = f(x_1)\oplus_y f(x_2)$
	Eine bijektive Homomorphie heißt Isomorphisumus, beziehungsweise $X\approx Y$ (äquivalent, isomorph)
** Natürliche Zahlen
   $\mathbb{N} = \{1,2,3,\ldots\},~\mathbb{N}_0 := \mathbb{N}\cup \{0\}$
*** Peanosche Axiomensystem der natürlichen Zahlen
	1. Die Zahl $1$ ist eine natürliche Zahl $1\in\mathbb{N}$
	2. Zu jeder natürlichen Zahl $n$, gibt es genau einen "Nachfolger" $n' (=: n+1)$
	3. Die Zahl 1 ist kein Nachfolger einer natürlichen Zahl
	4. $n' = m' \Rightarrow n = m$
	5. Enthält eine Teilmenge  $M \subseteq \mathbb{N}$ die Zahl $1$ und von jedem $n\in m$ auch den Nachfolger $n'$ ist $M = \mathbb{N}$
	Bemerkung: \\
	Mit Hilfe der Axiome lassen sich auf $\mathbb{N}$ Addition ($+$), Multiplikation ($\cdot$) und Ordung ($\leq$) einführen.
	Wir definieren: \\
	$1' = 2, 2' = 3, \ldots$
	$n + 1 := m'$
	$n + m' := (n+m)';~n\cdot m' := n m + n$
	Man kann zeigen, dass jede Menge, welche die Peano Axiome erfüllt isomorph bezüglich Multiplikation und Addition zu $\mathbb{N}$ ist
	Wir definieren $n < m \Leftrightarrow \exists x\in \mathbb{N}: x + m = m$
*** Vollständige Induktion
**** Induktionsprinzip
	 Es seien die folgende Schritte vollzogen:
	 1. Induktionsverankerung (Induktionsanfang): Die Aussage $A(1)$ gilt
	 2. Induktionsschluss: Ist für ein $n\in\mathbb{N}~A(n)$ gültig, so folgt auch die Gültigkeit von $A(n+1)$
     Dann sind alle Aussagen $A(n),n\in\mathbb{N}$ gültig.
**** Beweis:
	 Wir definieren die Tailmenge $M\subseteq\mathbb{N},~M:=\{n\in \mathbb{N}\mid A(N)~\text{ist gültig}\}$
	 Die Induktionsverankerung besagt, dass $1\in M$ und die Induktionsannahme $n\in M\Rightarrow n + 1 \in M$. Folglich ist nach dem 5. Axiom von Peano $M = \mathbb{N}\hfill\square$
**** Beispiel 1
	 Zu Beweisen: \[\Forall n\in\mathbb{N} \sum_{i = 1}^n i^2 = \frac{n(n+1)(2n+1)}{6}\]
***** Beweis
	  1. Induktionsverankerung: $1^2 = \frac{1}{6}\cdot 1\cdot 2\cdot 3$
	  2. Annahme: $A(n)$ gültig für $n\in\mathbb{N}: \sum_{i = 1}^n i^2 = \frac{n(n+1)(2n+1)}{6}$ \\
		 Zu zeigen $A(n + 1): 1^2 + \ldots + (n+1)^2 = \frac{1}{6} (n+1)(n+2)(2n+3)$
		 \[1^2 + \ldots + n^2 + (n+1)^2 = \frac{1}{2} n(n+1)(2n+1) + (n+1)^2 = (n+1)(\frac{1}{3}n^2 + \frac{1}{6}n + n + 1)\]
		 \[= \frac{1}{6}(n+1)(2n^2+7n+6) = \frac{1}{6}(n+1)(2n+3)(n+2)\hfill\square\]
**** Beispiel 2
	 Definition von Potenzen
	 \[x^0 := 1\]
	 \[\Forall n\in\mathbb{N} x^n := x^{n - 1}x\]
	 (iterative (rekursive) Definition) \\
	 Auf $\mathbb{N}$ sind diese elementaren Operationene erklärt:
	 - Addition $a+b$
	 - Multiplikation $a\cdot b$
	 - (unter gewissen Vorraussetzungen):
	   - Subtraktion $a-b$
	   - Division $\frac{a}{b}$
     $\mathbb{N}$ ist bezüglich "$-$" oder "$/$" nicht vollständig, das heißt $n+x = m$ ist nicht lösbar in $\mathbb{N}$
	 Erweiterungen:
	 - Ganze Zahlen $\mathbb{Z}:=\{0; \pm, n\in\mathbb{N}\}$ \\
	   Negative Zahl $(-n)$ ist definiert duch $n+(-n) = 0$
	 - Rationale Zahlen $\mathbb{Q}~(b x = y)$
     Man sagt, dass $(\mathbb{Q},+,\cdot)$ einen Körper bildet.
*** Definition Körper
	$\mathbb{K}$ sei eine Menge auf der Addition und Multiplikation sei. $\mathbb{K}$ heißt ein Körper, wenn die folgende Axiome erfüllt sind:
	- Addition: $(\mathbb{K}, +)$ ist eine kummutative Gruppe, das heißt $\Forall a,b,c\in \mathbb{K}$:
	  1. \((a+b)+c = a+(b+c)\) \hfill Assoziativität
	  2. \(a+b = b+a\) \hfill Kommutativität
	  3. \(\exists! 0\in\mathbb{K}:a+0 = a\)\hfill Existenz des Nullelement
	  4. \(\exists x\in\mathbb{K}: a+x = 0\)\hfill Existstenz des Nagativen
	- Multiplikation: $(\mathbb{K}\setminus\{0\},\cdot)$ ist eine kommutative Gruppte, das heißt $\Forall a,b,c\in\mathbb{K}$
	  1. \((a\cdot b)\cdot c = a\cdot(b\cdot c)\)\hfill Assozativität
	  2. \(a\cdot b = b\cdot a\)\hfill Kummutativität
	  3. \(\exists!1\in\mathbb{K}:a\cdot 1 = a\)\hfill Existenz des Einselement
	  4. Für \(a\neq 0, \exists! y\in\mathbb{K}:a\cdot y = 1\)\hfill Inverse
	- Verträglichkeit
	  1. \(a\cdot (b + c) = (a\cdot b)+ (a\cdot c)\)\hfill Distributivität
**** Satz
	 $(\mathbb{Q},+,\cdot)$ ist ein Körper. Definieren auf $\mathbb{Q}$ eine Ordnung "$\leq$" duch \[x\leq y \Leftrightarrow\exists m\in\mathbb{N}_0, n\in\mathbb{N}:y - x = \frac{m}{n}\]
	 dann ist auch diese Ordnung mit der Addition und Multiplikation in $\mathbb{Q}$ in folgendem Sinne verträglich:
	 - \(a\leq b\Rightarrow a+c \leq b + c\)
	 - \(0\leq a\wedge 0\leq b \Rightarrow 0\leq a\cdot b\)
**** Bemerkung
	 \[\{a\in\mathbb{Q}: a = \frac{r}{s},r\in\mathbb{N}_0,s\in\mathbb{N}\} =: \mathbb{Q}_+ (\mathbb{Q}_{\geq 0})\]
** Abzählbarkeit
*** Abzählbarkeit von Mengen
	Sei $A$ eine Menge\\
	- $A$ heißt endlich mit $\abs{A} = n$ Elementen ist äquivalent zu
	  \[\abs{A} = \begin{cases} A = \emptyset &(n = 0) \\ \exists f:A\to \{1,\ldots,n\} &f~\text{bijektiv},n < \infty\end{cases}\]
	- $A$ heißt abzählbar undendlich genau dann wenn \[\exists f: A\to \mathbb{N}~\text{bijektiv}\]
	- $A$ heißt überabzählbar genau dann wenn: $A$ ist weder endlich oder abzählbar unendlich
*** Beispiel
	$\mathbb{Z}$ ist abzählbar unendlich
**** Beweis
	 Die Abbildung $f:\mathbb{Z}\to\mathbb{N}$
	 \[z\mapsto \begin{cases} 2z & z\geq 0\\ -2z - 1 & 2 < 0\end{cases}\]
	 - Surjektivität: zu zeigen $f(\mathbb{Z}) = \mathbb{N}$ \\
	   Offenbar $f(\mathbb{Z}) \subseteq \mathbb{N}$. Wir zeigen $\mathbb{N} \subseteq f(\mathbb{Z})$. Sei $n\in\mathbb{N}$, finde $z\in\mathbb{Z}$ mit $f(z) = n$.
	   Man unterscheide:
	   - n gerade \rightarrow Wähle $z=\frac{n}{2}$
	   - n ungerade \rightarrow $z=-\frac{n + 1}{2}$
     - Injektivität: Sei $z_1,z_2 \in\mathbb{Z}$ und $f(z_1) = f(z_2)$ \\
	   ohne Beschränkung der Allgemeinheit $z_1 \leq z_2$. Entweder $z_1,z_2 \geq 0$ oder $z_1,z_2 < 0$, denn sonst währe $f(z_1)$ ungerade und $f(z_1)$ gerade *Wiederspruch*.
	   Falls
       - $z_1,z-2 \geq 0 \Rightarrow 2z_1 = f(z_1) = f(z_2) = 2z_2 \Rightarrow z_1 = z_2$
       - $z_1,z-2 < 0 \Rightarrow -2z_1 -1 = f(z_1) = f(z_2) = -2z_2-1 \Rightarrow z_1 = z_2 \hfill\square$
*** Beispiel
	- $\mathbb{N}^2 = \mathbb{N}\times\mathbb{N}$ abzählbar unendlich
	- $\mathbb{Q}$ abzählbar unendlich
	- $\mathbb{R}$ überabzählbar
