#+AUTHOR: Robin Heinemann
#+TITLE: Analysis I (Marciniak-Czochra)

#+INCLUDE: "../header.org" :minlevel 1

#+INCLUDE: "introduction.org" :minlevel 1
#+INCLUDE: "sets.org" :minlevel 1
#+INCLUDE: "complex_numbers.org" :minlevel 1
#+INCLUDE: "sequence.org" :minlevel 1
#+INCLUDE: "series.org" :minlevel 1
#+INCLUDE: "continous_functions.org" :minlevel 1
#+INCLUDE: "differential_calculus.org" :minlevel 1
* Integration
  Auf analytischer Seite kann die Integration als inverser Prozess zur
  Differentation angesehen werden. Geometrisch kann man für einfache Klasse von Funktionen
  (etwa stetige Funktionen), das (bestimmte) Integral einer (positiven) Funktion $f$ auf
  einem Intervall $[a, b]$ interpretieren als den Flächeninhalt zwischen der reellen Achse und dem
  Funktionsgraph (/insert Symbolbild here/)
** Das Riemannsche Integral
   Wir betrachten ein beschränktes Intervall $I = [a, b]$ und eine (endliche) *Zerlegung* $Z$
   von \[I, Z = \{x_0, \ldots, x_n\}, a:= x_0 < x_1 < \ldots < x_n =: b\]
   Wir bezeichnen
   \[h := \max_{k = 1, \ldots, n} \abs{x_k - x_{k - 1}}\] als die *Feinheit der Zerlegung*. Die
   Menge aller solcher Zerlegungen sei mit $\mathcal{Z}(a, b)$ bezeichnet eine Verfeinerung
   \[\tilde Z = \{\tilde x_0, \ldots, \tilde x_m\} \in \mathcal{Z}(a,b)\] mit $m \geq n$ von
   $Z \in \mathcal{Z}(a,b)$ enthält die Zerlegungspunkte von $Z$ (und möglichst noch weitere).
   Es gilt \[\tilde h = \max_{k = 1,\ldots, m} \abs{\tilde x_{k} - \tilde x_{k - 1}} \leq h\]
   Für zwei Zerlegungen $Z_1, Z_2 \in \mathcal{Z}(a,b)$ besteht eine gemeinsame Verfeinerug $Z_{12}$
   und $h_{12} \leq \min\{h_1, h_2\}$. Eine Zerlegung $Z\in\mathcal{Z}(a, b)$ mit \[\abs{x_k - x_{k - 1}} = h \Forall k = 1,\ldots, n\]
   heißt *äquidistant*.
   #+ATTR_LATEX: :options [5.1 Ober- und Untersumme]
   #+begin_defn latex
   Sei $f:I = [a,b] \to\mathbb{R}$ und $Z \in \mathcal{Z}(a, b)$ eine Zerlegung mit $Z = \{x_0, \ldots, x_n\}$.
   Wir setzen $I_k := [x_{k - 1}, x_k]$ für $k =1, \ldots, n$. Damit definieren wir die Obersumme der Funktion $f$ bezüglich der Zerlegung $Z$ mittels
   \[\bar S_Z f(x) := \sum_{k = 1}^{n}\sup_{x \in[x_{k - 1}, x_k]}f(x)(x_k - x_{k - 1})\]
   Völlig analog setzen wir die Untersumme von $f$ bezüglich $Z$:
   \[\ubar S_Z f(x) := \sum_{k = 1}^{n}\inf_{x \in I_k}f(x)(x_k - x_{k - 1})\]
   #+end_defn
   #+ATTR_LATEX: :options [5.2 Ober und Unterintegral]
   #+begin_defn latex
   Wir definieren das *Oberintegral* $f$ auf $I$ als
   \[\overline{\int_{a}^{b}}f(x) \d x := \inf_{Z\in \mathcal{Z}(a,b)} \bar S_Zf(x)\]
   Analog definieren wir das *Unterintegral* von $f$ auf $I$
   \[\underline{\int_{a}^{b}} f(x)\d x := \sup_{Z\in\mathcal{Z}(a,b)} \ubar S_Z f(x)\]
   #+end_defn
   #+ATTR_LATEX: :options [5.3]
   #+begin_lemma latex
   1. Für eine beschränkte Funktion $f: I = [a, b] \to \mathbb{R}$ existieren das Oberintegral und das Unterintegral
   2. Sei $(Z_n)$ eine Folge von Zerlegungen aus $Z_n \in \mathcal{Z}(a, b), n\in\mathbb{N}$. Sei $h_n$
	  die Feinheit von $Z_n$ mit $h_n \to 0$ für $n \to \infty$. Dann gilt
	  \[\lim_{n\to\infty} \ubar S_{Z_n} = \underline{\int_{a}^{b}} f(x) \d x \leq \overline{\int_{a}^{b}} f(x) \d x = \lim_{n\to\infty} \ubar S_{Z_n}\]
   #+end_lemma
   #+begin_proof latex
   1. Sei $Z\in \mathcal{Z}(a, b)$ eine beliebige Zerlegung. $\ubar S_Z$ und $\bar S_Z$ sind beschränkt, da
	  \[\inf_{x\in[a,b]} f(x)(b - a) \leq \ubar S_Z \leq \bar S_Z \leq \sup_{x\in[a,b]} f(x)(b - a)\]
	  Die Existenz des Ober- und Unterintegrals folgt aus Existenz von Supremum und Infimum beschränkter Zahlenmengen
   2. Sei $(Z_n)_{n\in\mathbb{N}}$ eine Folge von Elementen aus $\mathcal{Z}(a,b)$ mit $h_n \xrightarrow{n\to\infty} 0$.
	  Nach Definition von Supremum und Infimum gilt
	  \[\Forall \eps > 0 \Exists Z_\eps, Z^\eps \in \mathcal{Z}(a,b): \underline{\int_{a}^{b}} f(x) \d x \leq \ubar S_{Z_\eps}(f) + \frac{\eps}{2} \wedge \bar S_{Z^\eps}(f) \leq \overline{\int_{a}^{b}}f(x) \d x + \frac{\eps}{2}\]
	  Da nun $Z_\eps$ und $Z^\eps$ nur endlich viele Unterteilungspunkte haben und $h_n \to 0$ gilt,
	  kann $n\in \mathbb{N}$ so groß gewählt werden, dass die Teilintervalle von $Z_n$ die Zerlegungspunkte
	  von $Z^\eps, Z_\eps$ enthalten und insgesamt eine Länge $L < \frac{\eps}{2M}$ mit
	  \[M = \sup_{x\in I} \abs{f(x)}\]
	  haben. dann gilt
	  \[\ubar S_{Z_\eps}(f) \leq \ubar S_{Z_n}(f) + \frac{\eps}{2} \wedge \bar S_{z_n}(f) \leq \bar S_{Z^\eps}(f) + \frac{\eps}{2}\]
	  und daraus folgt
	  \begin{align*}
	  &\underline{\int_{a}^{b}}f(x) \d x \leq \ubar S_{Z_n}(f) + \eps \\
	  \bar S_{Z_n}(f) \leq &\overline{\int_{a}^{b}}f(x) \d x + \eps
      \end{align*}
	  Dies impliziert wegen der Beliebigkeit der Wahl von $\eps$ die Behauptung.
   #+end_proof
   #+ATTR_LATEX: :options [5.4 Riemann Integral]
   #+begin_defn latex
   Sei $f:I = [a, b] \to \mathbb{R}$ eine beschränkte Funktion. Sind Ober- und Unterintegral gleich,
   so heißt der gemeinsame Wert das (bestimmte) Riemann Integral von $f$ über $I$
   \[\underline{\int_{a}^{b}}f(x) \d x = \int_{a}^{b} f(x) \d x = \overline{\int_{a}^{b}} f(x) \d x\]
   #+end_defn
   #+ATTR_LATEX: :options [5.5]
   #+begin_ex latex
   Nicht alle beschränkten Funktionen sind Riemann-integrierbar.
   \[f:[0,1] \to \mathbb{R} x \mapsto \begin{cases} 0 & x \in\mathbb{Q} \\ 1 & x \in \mathbb{R} \setminus \mathbb{Q}\end{cases}\]
   Auf jeder Zerlegung $Z\in\mathcal{Z}(0, 1)$
   \[\ubar S_Z(f) = 0 < 1 = \bar S_Z(f)\]
   #+end_ex
   #+ATTR_LATEX: :options [5.6 Riemannsches Integrabilitätskriterium]
   #+begin_thm latex
   Eine beschränkte Funktion $f:I =[a,b] \to \mathbb{R}$ ist genau dann über $I$ Riemann-integrierbar,
   wenn es zu beliebigen $\eps > 0$ ein Zerlegung $Z\in\mathcal{Z}(a, b)$ gibt, sodass
   für die zugehörige Ober- und Untersummen gilt
   \[\abs{\bar S_Z(f) - \ubar S_Z(f)} < \eps\]
   #+end_thm
   #+ATTR_LATEX: :options [5.7 Riemannsche Summe]
   #+begin_defn latex
   Für eine Funktion $f:[a, b] \to \mathbb{R}$ und eine Zerlegung $Z \in\mathcal{Z}(a,b)$ wird die mit einem Punkten $\xi_k \in [x_{k - 1}, x_k]$ gebildete Summe
   \[\RS_z(f) := \sum_{k = 1}^{n} f(\xi_k)(x_k - x_{k - 1})\]
   als eine Riemannsche Summe von $f$ bezeichnet.
   #+end_defn
   #+ATTR_LATEX: :options [5.9]
   #+begin_thm latex
   Eine Funktion $f:[a, b] \to \mathbb{R}$ ist genau dann Riemann-integrierbar, wenn für jede Folge von Zerlegungen $Z_n \in\mathcal{Z}(a, b)$ mit
   $h_n \xrightarrow{n\to\infty} 0$ alle zugehörigen Riemann-Summen konvergieren und denselben Limes haben
   \[\RS_{Z_n}(f) \xrightarrow{n \to\infty} \int_{a}^{b} f(x) \d x\]
   #+end_thm
   #+begin_proof latex
   Sei $f: I\to\mathbb{R}$ Riemann-integrierbar. $\Forall Z\in\mathcal{Z}(a,b)$ mit Feinheit $h$ gilt offenbar
   \[\ubar S_Z(f) \leq \RS_Z(f) \leq \bar S_Z(f)\]
   Aus
   \[\abs{\ubar S_Z(f) - \bar S_Z(f)} \xrightarrow{h \to 0} 0\]
   folgt die Konvergenz der Riemann-Summe. Seien alle Riemann-Summen von $f$ konvergent gegen den selben Limes.
   \[\Forall \bar S_Z(f), \ubar S_Z(f), Z\in\mathcal{Z}(a,b)\Exists \overline{\RS}_Z(f), \underline{\RS}_Z(f):\Forall \eps > 0: \underline{\RS}_Z(f) - \eps \leq \ubar S_Z(f) \leq \bar S_Z(f) \leq \overline{\RS}_Z(f) + \eps\]
   Aus Konvergenz (für $h\to 0$) alle Riemann-Summen gegen denselben Limes und aus der Beliebigkeit von $\eps$ folgt
   \[\abs{\ubar S_Z(f) - \bar S_Z(f)} \xrightarrow{h\to 0} 0\]
   #+end_proof
   #+ATTR_LATEX: :options [5.9]
   #+begin_thm latex
   Eine stetige Funktion $f:[a, b] \to \mathbb{R}$ ist Riemann-integrierbar.
   #+end_thm
   #+begin_proof latex
   Auf dem kompakten (beschränkten und abgeschlossenen) Intervall ist $f$ gleichmäßig stetig.
   \[\Forall \eps > 0 \Exists \delta_\eps > 0: \Forall x, \tilde x \in I:\abs{x - \tilde x} < \delta_\eps \implies \abs{f(x) - f(\tilde x)} < \eps\]
   $\Forall$ Zerlegung $Z\in\mathcal{Z}$ mit der Feinheit $h < \delta_\eps$ gilt
   \[\abs{\bar S_Z(f) - \ubar S_Z(f)} \leq \sum_{k = 1}^{n} \abs{\sup_{x\in I_k}f(x) - \inf_{x\in I_k} f(x)}(x_k - x_{k - 1}) \leq \eps(b - a)\]
   Dies impliziert die Existenz des Riemann-Integral von $f$
   #+end_proof
   #+ATTR_LATEX: :options [5.10]
   #+begin_thm latex
   Eine (beschränkte) monotone Funktion $f:[a, b] \to \mathbb{R}$ ist Riemann-integrierbar.
   #+end_thm
   #+begin_proof latex
   Ohne Beschränkung der Allgemeinheit sei $f$ monoton steigend. Dann gilt $f(a) \leq f(x) \leq f(b) \Forall x\in I$.
   $\Forall$ Zerlegung $Z\in\mathcal{Z}(a, b)$ mit Feinheit $h$ gilt:
   \[\bar S_Z(f) - \ubar S_Z(f) = \sum_{k = 1}^{n}(f(x_k) - f(x_{k - 1}))(x_k - x_{k - 1}) \leq h(f(b) - f(a))\]
   Für beliebige $\eps > 0 \Exists h_\eps > 0$ sodass für $h\leq h_\eps$ gilt
   \[\abs{\bar S_Z(f) - \ubar S_Z(f)} < \eps \tag*{\qedhere}\]
   #+end_proof
   #+ATTR_LATEX: :options [5.11 Zusammengesetzte Integrale]
   #+begin_thm latex
   1. Eine (beschränkte) Riemann-integrierbare Funktion $f:[a,b]\to\mathbb{R}$ ist auch über jedem Teilintervall $[\tilde a, \tilde b] \in [a,b]$ Riemann-itegrierbar. Insobesondere gilt für $c \in (a,b)$
	  \[\int_{a}^{b}f(x) \d x = \int_{a}^{c} f(x) \d x + \int_{c}^{b} f(x) \d x\]
   2. Ist eine (beschränkte) Funktion $f:[a,b] \to\mathbb{R}$ für $c\in (a,b)$ über den Teilintervallen $[a,c]$ und $[c, b]$ Riemann-integrierbar, so ist sie auch über $[a,b]$ Riemann-integrierbar und es
	  gilt 1.
   #+end_thm
   #+begin_proof latex
   1. Seien $Z_n \in \mathcal{Z}(a,b)$ mit Feinheit $h_n \to 0$ und $\RS_{z_n}(f)$ zugehörige Riemann-Summan, sodass
	  \[\RS_{Z_n}(f)\xrightarrow{n\to\infty} \int_{a}^{b}f(x) \d x\]
	  Wir zeigen Integrierbarkeit von $f$ über $(\tilde a, \tilde b)$. Ohne Beschränkung der Allgemeinheit können wir annehmen, dass $Z_n$ die Punkte $\{\tilde a,\tilde b\}$ als Teilungspunkte enthalten.
	  Wir betrachten zwei beliebige Folge $\tilde Z_n^{(1)}, \tilde Z_n^{(2)} \in \mathcal{Z}(\tilde a, \tilde b)$ mit Feinheiten $\tilde h_n^{(1)}, \tilde h_n^{(2)} \to 0$
	  und irgendwelche zugehörigen Riemann-Summen $\RS_{\tilde Z_n^{(1)}}(f), \RS_{\tilde Z_n^{(2)}}(f)$. $\tilde Z_n^{(1)}, \tilde Z_n^{(2)}$ lassen sich erweitern zu $Z_n^{(1)}, Z_n^{(2)}$ auf $[a, b]$
	  (durch Verwendung von gleichen Teilungspunkten aus $[a,\tilde a] \cup [\tilde b, b]$). Wir bekommen zugehörige $\RS_{Z_n^{(1)}}, \RS_{Z_n^{(2)}}(f)$. Nach Konstruktion gilt
	  \[\abs{\RS_{\tilde Z_n^{(1)}}(f) - \RS_{\tilde Z_n^{(2)}}(f)} = \abs{\RS_{Z_n^{(1)}}(f) - \RS_{Z_n^{(2)}}(f)} \xrightarrow{n\to\infty} 0\]
	  Hieraus folgt, dass jede  Folge von Riemann-Summen $\RS_{\tilde Z_n}(f)$ zu Zerlegung $Z_n\in\mathcal{Z}(\tilde a,\tilde b)$ mit $\tilde h\to 0$ Cauchy Folge ist
	  und dass alle solche Folgen gegen den selben Limes konvergieren, also $f$ ist über $[\tilde a, \tilde b]$ Riemann-integrierbar.

	  Sei $c\in (a,b) \implies f$ ist Riemann-integrierbar über $[a,c]$ und $[c, b]$. Da jedes Paar $\RS_{Z^{(1)}}(f)$ und $\RS_{Z^{(2)}}(f)$ zu einer $\RS_{Z}(f)$ über $[a,b]$ erweitert werden kann
	  bekommen wir durch Grenzübergang $h\to 0$
	  \begin{align*}
	  \int_{a}^{c}f(x)\d x + \int_{c}^{b}f(x)\d x &= \lim_{h\to 0} \RS_{Z^{(1)}}(f) + \lim_{h \to 0} \RS_{Z^{(2)}}(f) \\
	  &= \lim_{h\to 0} (\RS_{Z^{(1)}} + \RS_{Z^{(2)}}(f)) = \lim_{h\to 0} \RS_Z(f) = \int_{a}^{b}f(x) \d x
	  \end{align*}
   2. Sei $f$ über $[a,c]$ beziehungsweise $[c,b]$ integrierbar. Die Konverenz
	  \begin{align*}
	  \lim_{h\to 0}\RS_{Z^{(1)}}(f) &= \int_{a}^{c}f(x) \d x \\
	  \lim_{h\to 0}\RS_{Z^{(2)}}(f) &= \int_{c}^{b}f(x) \d x
	  \implies \int_{a}^{c}f(x) \d x + \int_{c}^{b}f(x) \d x &= \lim_{h\to 0} \RS_{Z^{(1)}}(f) + \lim_{h\to 0} \RS_{Z^{(2)}}(f) \\
	  &= \lim_{h\to 0} (\RS_{Z^{(1)}}(f) + \RS_{Z^{(2)}}(f)) = \lim_{h\to 0} \RS_Z(f) \\
	  &=: \int_{a}^{b}f(x) \d x \tag*{\qedhere}
      \end{align*}
   #+end_proof
   #+ATTR_LATEX: :options [5.12 Linearität des Riemann-Integrals]
   #+begin_defn latex
   Sind $f, g:[a,b]\to\mathbb{R}$ (beschränkt) Riemann-integrierbar, so ist auch jede Linearkombination
   \[\alpha f + \beta g, \alpha,\beta \in\mathbb{R}\]
   über $I$ Riemann-intgerierbar und es gilt
   \[\int_{a}^{b}(\alpha f(x) + \beta g(x))\d x = \alpha \int_{a}^{b}f(x) \d x + \beta \int_{a}^{b}g(x) \d x\]
   #+end_defn
   #+begin_proof latex
   Wegen der Integrierbarkeit von $f$ und $g$ existieren $\RS_Z(f)$ und $\RS_Z(g)$ mit Feinheiten $h\to 0$, sodass
   \[\lim_{h\to 0} \RS_Z(f) = \int_{y}^{b}f(x) \d x\]
   und ähnlich für $g$, wobei ohne Beschränkung der Allgemeinheit angenommen werden kann, dass $Z\in\mathcal{Z}(a,b)$ sowie die Anwendungspunkte $\xi_k \in [x_{k - 1, x_k}]$ für beide Riemann-Summen
   die selben sind. Dann ist für $\alpha,\beta \in\mathbb{R}$ auch
   \[\RS_Z(\alpha f + \beta g) := \RS_Z(\alpha f) + \RS_Z(\beta g) = \alpha \RS_Z(f) + \beta \RS_Z(g)\]
	Riemann-Summe für $\alpha f + \beta g$
	Es gilt
	\begin{align*}
	\alpha \int_{a}^{b}f(x)\d x + \beta \int_{a}^{b}g(x) &= \alpha \lim_{h\to 0} \RS_Z(f) + \beta \lim_{h\to 0} \RS_Z(g) \\
	&= \lim_{h\to 0} \RS_Z(\alpha f + \beta g) \\
	&= \int_{a}^{b}(\alpha f + \beta g) \d x
	\end{align*}
   #+end_proof
   #+ATTR_LATEX: :options [5.13 Monotonie des Riemann-Integrals]
   #+begin_thm latex
   Seien $f, g:[a,b] \to \mathbb{R}$ (beschränkt) Riemann-integrierebare Fukntion mit $g(x) \geq f(x) \Forall x\in[a,b]$. Dann gilt auch
   \[\int_{a}^{b}g(x) \d x \geq \int_{a}^{b}f(x) \d x\]
   (ohne Beweis)
   #+end_thm
   #+ATTR_LATEX: :options [5.14]
   #+begin_korollar latex
   Für eine (beschränkte) Riemann-integrierbare Funktion $f:[a,b]\to\mathbb{R}$ mit $m\leq f(x) \leq M$, dann gilt
   \[m(b - a) \leq \int_{a}^{b}f(x) \d x \leq M(b - a)\]
   #+end_korollar
   #+ATTR_LATEX: :options [5.15]
   #+begin_korollar latex
   Es seien $f,g:[a,b]\to\mathbb{R}$ (beschränkt) Riemann-integrierbar. Dann gilt
   1. Die Funktion $f_+ := \max\{f,0\}, f_{-} := \min\{f, 0\}$ sind Riemann-integrierbar
   2. $\abs{f}$ ist Riemann-integrierbar und es gilt
	  \[\abs{\int_{a}^{b}f(x) \d x} \leq \int_{a}^{b}\abs{f(x)} \d x\]
   3. $\Forall p\in [1, \infty]$ ist $\abs{f}^p$ Riemann-integrierbar
   4. Das Produkt $f g$ ist Riemann-integrierbar
   #+end_korollar
   #+begin_proof latex
   1. $\Forall Z\in \mathcal{Z}(a,b)$ gilt
      \begin{align*}
      0 &\leq \bar S_Z(f_+) - \ubar S_Z(f_+) \leq \bar S_Z(f) - \ubar S_Z(f) \\
      0 &\leq \bar S_Z(f_-) - \ubar S_Z(f_-) \leq \bar S_Z(f) - \ubar S_Z(f)
      \end{align*}
      das hei0t mit $f$ sind auch $f_+$ und $f_{-}$ Riemann-integrierbar
   2. $\abs{f} = f_+ - f_{-} \implies \abs{f}$ ist Riemann-integrierbar als linear Kombination von $f_+$ und $f_{-}$
	  \[\abs{\int_{a}^{b}f(x) \d x} \leq \int_{a}^{b} \abs{f(x) \d x}\]
	  folgt aus Monotonie des Riemann-Integrals, wil $f \leq \abs{f}, -f \leq \abs{f}$
   3. Sei $\displaystyle M:= \sup_{x\in[a,b]}\abs{f}, \frac{\abs{f}}{M}$ ist Riemann-integrierbar. Wir brauchen also nur die Ausage für $0 < f \leq 1$.
	  Mit Hilfe des Mittelwertsatzes folgt für $0\leq x < y \leq 1$
	  \[y^p - x^p = p\xi \xi^{p-1}, x < \xi < y\]
	  $\Forall Z\in\mathcal{Z}(a,b)$ gilt daher
	  \[\bar S_Z(\abs{f}^p) - \ubar S_Z(\abs{f}^p) \leq p(\bar S_Z(\abs{f}) - \ubar S_Z(\abs{f}))\]
	  das heißt mit $\abs{f}$ ist auch $\abs{f}^p$ integrierbar
   4. Wegen $f g = \frac{1}{4}((f + g)^2 - (f - g)^2)$ folgt die Riemann-integrierbarkeint von $fg$ mit Hilfe von 3.
   #+end_proof
   #+begin_remark latex
   Im Allgemeinen
   \[\int_{a}^{b}f(x) g(x) \d x \neq (\int_{a}^{b}f(x) \d x)(\int_{a}^{b}g(x)\d x)\]
   #+end_remark
   #+begin_ex latex
   $f\equiv 1$
   \[\int_{a}^{b}f(x)g(x) \d x  = \int_{a}^{b} g(x)\d x \neq (\int_{a}^{b}f(x) \d x)(\int_{a}^{b}g(x) \d x) = (b - a) \int_{a}^{b}g(x) \d x\]
   für $b - a \neq 1$
   #+end_ex
   #+ATTR_LATEX: :options [5.16 Definitheit des Riemann-Integral]
   #+begin_korollar latex
   Sei $f:[a, b] \to \mathbb{R}$ stetig mit $f(x) \geq 0$ für $x\in [a,b]$. Dann gilt:
   \[\int_{a}^{b}f(x) \d x = 0 \iff f \equiv 0\]
   #+end_korollar
   #+begin_proof latex
   Angenommen $f\not\equiv 0$, das heißt
   \[\Exists x_0 \in [a,b]: f(x_0) > 0\]
   Dann, aus Stetigkeit von $f$ gibt es ein $I_\eps := [x_0, x_0 + \eps]$ sodass
   \[f(x) \geq \delta > 0 \Forall x\in I_\eps\]
   Da jede Zerlegung $Z$ vin $i$ mit hinreichend kleiner Feinheit $h$ ein Teilintervall $I_k \subseteq I_\eps$ beinhaltet, git fpr die
   zugehörigen Summen
   \[0 <  \delta(x_k - x_{k - 1}) \leq \inf_{x\in I_k}f(x)(x_k - x_{k - 1}) \leq \ubar S_Z(f) \leq \int_{a}^{b}f(x) \d x \tag*{\lightning\qedhere}\]
   #+end_proof
   #+begin_remark latex
   Wir haben Riemann-Integral definiert für $a < b$. Für $b \geq a$ definieren wir
   \[\int_{a}^{b} f(x) \d x := - \int_{a}^{b}f(x) \d x,\quad \int_{a}^{a} f(x) \d x := 0\]
   #+end_remark
   #+ATTR_LATEX: :options [5.17 Mittelwertsatz für Integrale]
   #+begin_thm latex
   Es seien $f:I=[a,b] \to\mathbb{R}$ stetig und $g:I\to\mathbb{R}$ Riemann-integrierbar und $g$ habe in $I$ keinen Vorzeichenwechsel.
   Dann gibt es eine Zwischenstelle $\xi [a,b]$ sodass
   \[\int_{a}^{b}f(x)g(x)\d x = f(\xi)\int_{a}^{b}g(x) \d x\]
   #+end_thm
   #+begin_proof latex
   Es folgt aus dem Zwischenwertsatz für stetig Funktionen: Ohne Beschränkung der Allgemeinheit behalten wir den Fall $g\geq 0$
   Aus stetigkeit von $f$ folgt:
   \[\Exists m := \min_{x\in I} f(x), M:= \max_{x\in I}f(x)\]
   Damit, wegen $g\geq 0$
   \[m \int_{a}^{b} g(x) \d x \leq \int_{a}^{b}f(x)g(x) \d x \leq M \int_{a}^{b} g(x) \d x\]
   Wir nehmen eine lineare Funktion mit $t \in [0,1]$
   \[l(g) .= (m(1 - t) + Mt) \int_{a}^{b}g(x) \d x\]
   $\implies \Exists \mu\in[m,M]$ mit
   \[\int_{a}^{b}f(x)g(x)\d x = \mu \int_{a}^{b}g(x) \d x\]
   und dann (Stetigkeit von $f$) $\Exists \xi \in [a,b]$, sodass $\mu = f(\xi)$
   #+end_proof
   #+ATTR_LATEX: :options [5.18]
   #+begin_korollar latex
   Sei $f:I = [a,b] \to \mathbb{R}$ stetig, dann $\Exists \xi \in I$ sodass
   \[\int_{a}^{b}f(x) \d x = f(\xi)(b - a)\]
   Seien $f:[a,b] \to \mathbb{R}$ stetig mit
   \[m\leq f(x) \leq M \Forall x\in I\]
   und $g$ Riemann-integrierbar mit $g\geq 0$, Dann gilt
   \[m \int_{a}^{b} f(x) \d x \leq \int_{a}^{b} f(x) g(x) \d x  \leq M \int_{a}^{b} g(x) \d x\]
   #+end_korollar
   #+ATTR_LATEX: :options [5.19 (Notwendigkeit von Vorraussetzungen)]
   #+begin_ex latex
   1. Stetigkeit von $f$. Wir nehmen
	  \[f:[0,2] \to \mathbb{R},x \mapsto \begin{cases} 0 & 0\leq x < 1 \\ 1 & 1 \leq x \leq 2\end{cases}\]
	  $f$ ist Unstetig und $\Forall \xi\in [0,2]$
	  \[\int_{0}^{2} f(x) \d x = 1 \neq f(\xi)(2 - 0)\]
   2. Positivität von $g$: Für
	  \begin{align*}
	  f(x) &:= x \\
	  g(x) &:= \begin{cases} -1 & 0\leq x \leq 1 \\ 1 & 1\leq x \leq 2\end{cases}
      \end{align*}
	  $\Forall \xi \in [0,2]$ gilt
	  \[\int_{0}^{2}f(x)g(x) \d x = -\int_{0}^{1}x\d x + \int_{1}^{2} x\d x = 1 \neq f(\xi)\int_{0}^{2}g(x) \d x = 0\]
   #+end_ex
   #+ATTR_LATEX: :options [5.20]
   #+begin_defn latex
   Eine Funktion $F:I = [a,b] \to \mathbb{R}$ heißt *unbestimmtes Integral* (oder Stammfunktion) einer Funktion $f:I \to \mathbb{R}$, wenn sie differenzerbar ist und
   \[F'(x) = f(x) \Forall x\in I\]
   Wir schreiben
   \[F = \int f(x) \d x\]
   #+end_defn
   #+ATTR_LATEX: :options [5.21 Fundamentalsatz der Analysis]
   #+begin_thm latex
   \mbox{}
   1. Für eine stetige Funktion $f: I = [a,b] \to \mathbb{R}$ ist das unbestimmte Integral
	  \[F(x) := \int_{a}^{x} f(y) \d y, x \in [a,b]\]
	  aufgefasst als Funktion der Oberen Grenze $x$ eine Stammfunktion von $f$. Jede weitere Stammfunktion von $f$
	  unterscheidet sich von $F$ durch eine Konstante
   2. Ist umgekehrt die Funktion $F:I = [a,b] \to \mathbb{R}$ Stammfunktion einer stetigen Funktion $f$, so gilt
	  \[\int_{a}^{b}f(x) \d x = F(x) \big|_a^b := F(b) - F(a)\]
   #+end_thm
   #+begin_proof latex
   1. Wir betrachten Differenzenquotienten von $F(x)$
      \[\frac{F(x + h) - F(x)}{h} = \frac{1}{h}(\int_{a}^{x + h}f(y \d y) - \int_{a}^{x}f(y) \d y) = \frac{1}{h} \int_{x}^{x + h} f(y) \d y\]
      Nach Mittelwertsatz gilt mit einem $\xi_h \in [x, x + h]$
      \[\frac{F(x + h) - F(x)}{h} = f(\xi_h)\]
      Für $h\to 0$, konvergiert $\xi_h \to x$, sodass $F'(x) = f(x)$ (aus Stetigkeit von $f$).
      Sei $G$ eine weitere Stammfunktion von $f$. Dann gilt
      \[0 = F' - G' = (F - G)'\]
      das heißt $F - G$ ist konstant.
   2. Sei $F$ eine Stammfunktion von $f$, das heißt $F'(x) = f(x)$. Mit der Funktion
	  \[G(x) := \int_{a}^{x}f(y) \d y, G(a) = 0\]
	  ist $F - G$ konstant (aus 1.). Deshalb
      \[F(b) - F(a) = G(b) - G(a) = \int_{a}^{b}f(x) \d x \tag{\qedhere}\]
   #+end_proof
   #+begin_remark latex
   Integration und Differenzierung sind zueinander inverse Prozesse
   \begin{align*}
   \frac{\d}{\d x} \int_{a}^{x}f(y) \d y &= f(x) \\
   f(x) &= f(a) + \int_{a}^{x}f'(y) \d y
   \end{align*}
   Die Regeln für die Differenzierung liefern
   1. $\int y^\alpha \d y = \frac{1}{\alpha + 1}x^{\alpha + 1}$
   2. $\int a^y \d y = \int e^{y\ln a}\d y = \frac{e^{x\ln a}}{\ln a} = \frac{a^x}{\ln a}$
   3. $\int \sin{y} \d y = -\cos x$ \\
      $\int \cos{y} \d y = \sin x$
   4. $\int \frac{1}{y}\d y = \ln\abs{x}$
   #+end_remark
   #+ATTR_LATEX: :options [5.21 Partielle Integration]
   #+begin_lemma latex
   Seien $f,g:I\to \mathbb{R}$ zwei stetig differenzierbare Funktionen. Dann gilt
   \[\int_{a}^{b}f(x)g'(x)\d x = (fg)(x)\big|_a^b - \int_{a}^{b} f'(x)g(x)\d x\]
   #+end_lemma
   #+begin_proof latex
   \begin{align*}
   \hspace{0pt}(fg)'(x) &= f'(x)g(x) + f(x)g'(x) \\
   fg\big|^b &= \int_{b}^{a}f'(x)g(x)\d x + \int_{a}^{b}f(x) g'(x)\d x \tag*{\qedhere}
   \end{align*}
   #+end_proof
   #+ATTR_LATEX: :options [5.23]
   #+begin_ex latex
   \[\int_{a}^{b} x e^x \d x = x e^x \big|_a^b - \int_{a}^{b} e^x \d x = e^b(b - 1) - e^a(a - 1)\]
   \[\int_{a}^{b} \ln(x) \d x = x\ln (x) \big|_a^b - \int_{a}^{b} \frac{1}{x} x \d x = b\ln b - a\ln a - (b - a)\]
   #+end_ex
   #+ATTR_LATEX: :options [5.24 Substitutionsregel]
   #+begin_thm latex
   Seien $f:I \to \mathbb{R}$ eine stetige Funktion und $\phi:[a,b]\to I$ eine stetig differenzierbare
   Funktion. Dann gilt
   \[\int_{a}^{b}f(\phi(y))\phi'(y)\d y = \int_{\phi(a)}^{\phi(b)} f(x) \d x\]
   (sogenannte Substitutionsregel)
   #+end_thm
   #+begin_proof latex
   Sei $F:I\to \mathbb{R}$ eine Stammfunktion von $f$. Die Komposition $F\circ \phi:[a,b]\to \mathbb{R}$.
   ist stetig differenzierbar, und nach der Kettenregel
   \[(F\circ \phi)'(y) = F'(\phi(y))\phi'(y) = f(\phi(y))\phi'(y)\]
   Aufgrund des Fundamentalsatzes gilt
   \[\int_{a}^{b}f(\phi(y))\phi'(y)\d y = \int_{a}^{b}(F\circ \phi)'(y)\d y = F\circ\phi(y)\big|_a^b = (F\circ \phi)(b) - (F\circ \phi)(a) = F(\phi(b)) - F(\phi(a)) = \int_{\phi(a)}^{\phi(b)}f(x) \d x\]
   #+end_proof
