* Stetige Abbildungen
** Grenzwert einer Funktion, Stetigkeit
   Wir betrachten die Funktion
   \[f:\mathbb{R}\setminus\{0\} \to \mathbb{R}, x\mapsto \frac{e^x - }{x} \]
   und wolllen diese auf ganz $\mathbb{R}$ fortsetzen, das heißt Wir suchen ein $\tilde f: \mathbb{R} \to \mathbb{R}$
   mit $\tilde f\mid \mathbb{R}\setminus \{0\} = f$ und einen Wert $\tilde f(0) \in \mathbb{R}$

   Allgemeiner überprüft man für Funktionen $f: D \subseteq \mathbb{K} \to \mathbb{K}$ die
   Fortsetzbarkeit auf den Abschluss $\bar D \subseteq \mathbb{K}$, wobei
   \begin{align*}
   \bar D &= \{x \in\mathbb{K} \mid x\in D \vee~\text{oder $x$ ist HP von D}\} \\
   &= \{x \in \mathbb{K} \mid \Exists (x_n)_{n\in\mathbb{N}} \subseteq D \wedge x = \lim_{n \to 0} x_n\}
   \end{align*}
   (analog zur Plenarübung)

   #+ATTR_LATEX: :options [3.1]
   #+begin_defn latex
   Eine Funktion $f: D\subseteq \mathbb{K} \to \mathbb{K}$ hat im Punkt $x_0 \in \bar D$ einen
   Grenzwert $a \in\mathbb{K}$, wenn alle Folgen $(x_n)_{n\int\mathbb{N}} \subseteq D$ gilt:
   \[x_n \to x_0 (n \to \infty) \implies f(x_n) \to a (n\to\infty)\]
   Wir schreiben kurz: $\lim_{x\to x_0} f(x) = a$
   #+end_defn
   #+begin_remark latex
   - Falls der Grenzwert existiert, ist er eindeutig.
   - Ist $T\subseteq D \subseteq \mathbb{R}, T\neq \emptyset, f: D\to\mathbb{R}, x_\in \bar T$, dann
	 verstehen wir unter
	 \[\lim_{\substack{x\to x_0 \\ x\in T}} f(x)\]
	 den Grenzwert $\lim_{x\to x_0} f\mid T$, falls er existiert.
   - Spezialfällte:
	 \begin{align*}
	 T_{>} := \{x\in D\mid x > x_0\}: f(x_0^{+}) := \lim_{\substack{x\to x_0 \\ x\in T_{>}}} f(x) = \lim_{x\to x_0^{+}} f(x) \tag{rechtsseitiger Grenwzwert} \\
	 T_{<} := \{x\in D\mid x < x_0\}: f(x_0^{-}) := \lim_{\substack{x\to x_0 \\ x\in T_{<}}} f(x) = \lim_{x\to x_0^{-}} f(x) \tag{linksseitiger Grenwzwert}
	 \end{align*}
   - Existiert $\lim_{x\to x_0} f(x), x_0 \in \bar T \subseteq \bar D$, dann gilt
	 \[\lim_{x\to x_0 \\ x\in T} f(x) = \lim_{x\to x_0}  f(x)\]
   - Es gelten die üblichen Rechenregeln für Grenzwerte $(x,\cdot, :)$
   #+end_remark
   #+ATTR_LATEX: :options [3.2]
   #+begin_ex latex
   1. $f:\mathbb{R}\setminus\{0\}, x\mapsto \frac{x}{\abs{x}}$
	  \[\lim_{x\to 0^+} f(x) = 1 \wedge \lim_{x \to 0^-} f(x) = -1\]
	  Also existiert $\lim_{x\to 0} f(x)$ nicht
   2. $f:\mathbb{R}\setminus\{0\}, x\mapsto \frac{e^x - 1}{x}$ \\
	  Es gilt $\lim_{x\to 0} f(x) = 1$, denn für $\abs{x} \leq 1, x\neq 0$ gilt
	  \[\abs{f(x) - 1} = \abs{\frac{e^x - 1 - x}{x}} = \abs{\sum_{k = 2}^{\infty} \frac{x^{k - 1}}{k!}} \leq \abs{x} \sum_{k = 2}^{\infty} \frac{\abs{x}^{k - 2}}{k!} \leq \abs{x} \sum_{k = 2}^{\infty} \frac{1}{k!} = \abs{x} \underbrace{(e - 2)}_{> 0}\]
	  Für Nullfolgen $(x_n)_{n\in\mathbb{N}} \subseteq [-1, 1]\setminus \{0\}$ folgt $\lim_{n \to \infty} f(x_n) = 1$
	  Das heißt $f$ besitzt eine Fortsetzung
	  \[\tilde f: \mathbb{R} \to \mathbb{R}, x\mapsto \begin{cases} \frac{e^x - 1}{x} & x \neq 0 \\ 1 & x = 0\end{cases}\]
   #+end_ex
   #+ATTR_LATEX: :options [3.3 Asymptotisches Verhalten]
   #+begin_defn latex
   Sei $\emptyset \neq D \subseteq \mathbb{R}$ nach oben (nach unten) unbeschränkt.
   Die Funktion $f: D\to \mathbb{R}$ hat für $x \to + \infty (x \to -\infty)$ einen Grenzwert $a\in \mathbb{R}$, wenn gilt:
   \[\Forall \eps > 0 \Exists y\in \mathbb{R}: \abs{f(x) - a} < \eps \Forall x\in D, x > y (x < y)\]
   Schreibweise: $\lim_{x \to \infty}f(x) = a$, oder $\lim_{x\to -\infty} f(x) = a$

   Sei $x_0 \in \bar D$. Die FUnktion $f$ divergiert bestimmt gegen $+\infty (-\infty) :\iff \Forall K\in\mathbb{R}_{+} \Exists \delta > 0: f(x) > K (f(x) < -K) \Forall x\in I_\delta (x_0) \cap (D\setminus\{x_0\})$ \\
   Schreibweise: $f(x) \to +\infty (f(x) \to -\infty)$ für $x\to x_0$
   #+end_defn
   #+ATTR_LATEX: :options [3.4]
   #+begin_ex latex
   1. $f:\mathbb{R}\setminus\{1\}, x\mapsto \frac{1}{x - 1}$
	  \[\lim_{x\to\infty} \frac{1}{x} = 0 = \lim_{x\to -\infty} \frac{1}{x}\]
	  wir schreiben kurz $\lim_{\abs{x} \to \infty} \frac{1}{x} = 0$
   2. $\Forall k\in\mathbb{N}$ gilt
	  \[\lim_{x\to\infty} \frac{x^k}{e^x} = 0 = \lim_{x\to -\infty} x^k e^x,~\text{denn}~ e^x = \exp(x) \geq \frac{x^{k + 1}}{(k + 1)!}, x\geq 0 \]
	  \[\implies \frac{x^k}{e^x} \leq \frac{(k + 1)!}{x} \to 0 (x\to \infty)\]
	  \[x^k e^x = \frac{(-1)^k \abs{x}^k}{e^{\abs{x}}}, x < 0\]
   #+end_ex
   #+ATTR_LATEX: :options [3.5]
   #+begin_defn latex
   Eine Funktion $f:D \subseteq \mathbb{K} \to \mathbb{K}$ heißt stetig im Punkt $x_0 \in D$, wenn gilt:
   Für alle Folgen $x_n \to x_0 (n\to\infty) \implies f(x_n) \to f(x_0) (n \to \infty)$
   Andernfalls heißt sie unstetig in $x_0 \in D$.
   $f$ heißt stetig (auf ganz $D$), wenn sie in jedem $x_0 \in D$ stetig ist. (/insert Symbolbild hier/) \\
   #+ATTR_LATEX: :options [3.5]
   #+begin_lemma latex
   1. Ist $f: D\to \mathbb{K}$ stetig, dann ist auch $f\mid T$ statig, $T\subseteq D$
   2. Ist $f:D\to \mathbb{K}$ stetig, so auch $\Re(f):D\to\mathbb{R}$, $\Im(f): D\to \mathbb{R}$, $\abs{f}: D\to\mathbb{R}_+$ stetig (auf ganz $D$)
   3. Sind $f,g:D\to\mathbb{K}$ stetig, so auch $f + g, f\cdot g: D\to\mathbb{K}$
   4. Ist $f:D\to f(D)\subseteq \mathbb{K},g:f(D) \to \mathbb{K}$ stetig in $x_0$, beziehungsweise in $f(x_0) =: y_0$ so auch $f \circ f: D\to\mathbb{K}$ stetig in $x_0 \in D:$
   #+end_lemma
   #+begin_proof latex
   1. Siehe Bemerkung zu Grenzwerte
   2. Für $z = a + \I b$ gilt $\abs{\abs{a} - \abs{b}} \leq \abs{a - b}$ sowie $\abs{z}^2 = a^2 + b^2 \geq a^2 \geq b^2$
   3. Siehe Bemerkung zu Grenzwerte
   4. Sei $(x_n)_{n\in\mathbb{N}} \subseteq D$ mit $\lim_{n \to\infty} x_n = x_0$, dann folgt aus Stetigkeit von $f: \lim_{n\to\infty} f(x_n) = f(x_0)$ \\
	  $(g\circ f)(x_n) = g(f(x_n)) \rightarrow g(f(x_0)) = (g\circ f)(x_0) (n\to\infty)$
   #+end_proof
   #+ATTR_LATEX: :options [3.7 $\eps/\delta$ Kriterium]
   #+begin_lemma latex
   Eine Funktion $f: D \to \mathbb{K}$ ist in $x_0 \in D$ genau dann stetig, wenn es zu jedem $\eps > 0$ ein $\delta = \delta(\eps) > 0$ gibt, sodass Für alle $x \in D$ gilt:
   \[\abs{x - x_0} < \delta \implies \abs{f(x) - f(x_0)} < \eps\]
   #+end_lemma
   #+begin_proof latex
   $(\impliedby)$: Gilt das $\eps / \delta$ Kriterium, so ist $f$ auch in $x_0$ offensichtlich stetig \\
   $(\implies)$: Sei also $f$ stetig in $x_0$. Angenommen, dass $\eps / \delta$-Kriterium gälte nicht,
   das heißt es gibt ein $\eps > 0$, sodass $\Forall \delta > 0$ ein $x\in D$ mit $\abs{x - x_0} < \delta$ und $\abs{f(x) - f(x_0)} \geq \eps$ gibt. Wiederspruch zu
   \[\lim_{x \to x_0} f(x) = f(x_0)\]
   #+end_proof
   #+ATTR_LATEX: :options [3.8]
   #+begin_korollar latex
   Sei $f: D \to \mathbb{K}$ stetig in $x_0 \in D$ mit $f(x_0) \neq 0$. Dann gibt es ein $\delta > 0$ mit $f(x) \neq 0$.
   Dann gibt es ein $\delta > 0$ mit $f(x) \neq 0 \Forall x\in I_\sigma (x_0) \cap D$. Insbesondere ist $\frac{1}{f}: D\to\mathbb{K}$ stetig in $x_0 \in D$
   #+end_korollar
   #+begin_proof latex
   Setze $\eps := \abs{f(x_0)} > 0$. Dann gibt es ein $\delta > 0$, sodass $\Forall x\in D$ mit $\abs{x - x_0} < \delta$ folgt $\abs{f(x) - f(x_0)} < \eps$ (aus Stetigkeit von $f$),
   das heißt für $x \in I_\sigma (x_0) \cap D$ gilt
   \[\abs{f(x)} \geq \abs{f(x_0)} - \abs{f(x) - f(x_0)} > \eps - \eps = 0\]
   Insbesondere sind Folgen $x_n \to x_0$ wohldefiniert und die Aussage resultiert aus den Rechenregeln für Folgen
   #+end_proof
   #+ATTR_LATEX: :options [3.9]
   #+begin_ex latex
   \mbox{}
   1. $f: \mathbb{R} \to \mathbb{R}, f(x) = x$ ist stetig auf $\mathbb{R}$
   2. Konstante Funktionen $f(x) = c \Forall x\in \mathbb{R}$ sind stetig auf $\mathbb{R}$
   3. Seien $a_0, \ldots, a_n \in \mathbb{R}, a_n\neq 0$, Dann heißt
	  \[p: \mathbb{R} \to \mathbb{R}, x\mapsto \sum_{k = 0}^{n} a_k x^k\]
	  *Polynom* vom Grad $n\in\mathbb{N}_0$ und ist stetig (wegen 1. und 2. und Lemma 3.6)
   4. Seien $p,q$ Polynome, dann heißt \[f: \{x\in\mathbb{R} \mid q(x) \neq 0\} \to \mathbb{R}, x\mapsto \frac{p(x)}{q(x)}\]
	  *rationale Funktion* und ist stetig nach 3. und Korollar 3.8
   5. $g:\mathbb{R} \to \mathbb{R}, x\mapsto \sqrt{1 + 3x^2}$ ist stetig nach 3., Lemma 3.6 und Übung 5.1
   6. $\exp: \mathbb{R} \to \mathbb{R} \setminus \{0\}, x\mapsto e^x$ ist stetig auf $\mathbb{R}$, denn für $x \neq x_0$ ist
	  \[e^x = e^{x_0} e^{x - x_0} = e^{x_0} (1 + \underbrace{(x - x_0)}_{\to 0} \frac{e^{x - x_0} - 1}{\underbrace{(x - x_0)}_{1}})\]
	  (nach Beispiel 3.2)
   7. $\displaystyle f(x) = \begin{cases} 1 & x \in\mathbb{Q} \\ 0 & x \in \mathbb{R} \setminus \mathbb{Q} \end{cases}$
   #+end_ex
   #+ATTR_LATEX: :options [3.10 Gleichmäßige Stetigkeit]
   #+begin_defn latex
   Eine Abbildung $f: D \to \mathbb{K}$ heißt *gleichmäßig stetig* auf $D$, wenn $\Forall \eps > 0 \Exists \delta = \delta(\eps) < 0: \Forall x,y \in D: \abs{x - y} < \delta \implies \abs{f(x) - f(y)} < \eps$
   #+end_defn
   #+begin_remark latex
   Gleichmäßige Stetigkeit heißt, dass die $\delta$ gleichmäßig für alle Punkte $x\in D$ gewählt werden kann.
   #+end_remark
   #+ATTR_LATEX: :options [3.11]
   #+begin_ex latex
   \[f: \mathbb{R} \setminus \{0\} \to \mathbb{R}, x \mapsto \frac{1}{x}\]
   1. $f$ ist gleichmäßig stetig auf $A = \mathbb{R} \setminus (-a, a), a > 0$
   2. $f$ ist *nicht* gleichmäßig stetig auf $\mathbb{R} \setminus \{0\}$
   #+end_ex
   #+begin_proof latex
   \[\abs{f(x) - f(y)} = \abs{\frac{1}{x} - \frac{1}{y}} = \frac{1}{\abs{xy}} \abs{x - y}\]
   also $\abs{f(x) - f(y)} < \eps \iff \abs{x - y} < \abs{xy} \eps$
   1. Für $x,y \in \mathbb{R} \setminus (-a, a)$ gilt $\abs{xy} \geq a^2$, also $\abs{x - y} < \eps a^2 := \delta \implies \abs{x - y} < \eps \abs{xy}$.
	  Daher $\Forall \eps > 0 \Forall x,y\in A: \abs{x - y} < \delta:= \eps a^2 \implies \abs{f(x) - f(y)} < \eps$
   2. Dagegen können wir $\Forall \delta > 0, x, y \in \mathbb{R} \setminus \{0\}$ finden wir
	  $\abs{x - y} < \delta$, aber $\abs{f(x) - f(y)} \geq 1 \iff \abs{x - y} \geq \abs{xy}$ \\
	  Sei $\delta > 0$. Wähle $n\in \mathbb{N}$, sodass $\frac{\delta}{n} < 1$. Nun gilt für
	  \begin{align*}
	  \abs{x - y} &= \frac{\delta}{2n} \\
	  \abs{xy} &< (\abs{x - y} + \abs{x}) \abs{x} \\
	  \intertext{für $\abs{x} < \frac{\delta}{2n}$}
	  &= (\frac{\delta}{2n} + \abs{x}) \abs{x} < \frac{\delta^2}{2n^2} \\
	  &= \frac{\delta}{n} \abs{x - y} \leq \abs{x - y}, ~\text{da}~ \frac{\delta}{n} \leq 1
	  \end{align*}
   #+end_proof
   #+ATTR_LATEX: :options [3.12 Lipschitz Stetigkeit]
   #+begin_defn latex
   Eine Funktion $f:D\to\mathbb{K}$ heißt Lipschitz stetig (kurz L-stetig) auf $D$, wenn
   $\Exists L > 0$ (sogenannte Lipschitz Konstante), sodass
   \[f(x) - f(y) \leq L \abs{x - y} \Forall x,y \in D\]
   #+end_defn
   #+begin_remark latex
   Menge von stetigen Funktionen $\supset$ Menge von gleichmäßig stetigen Funktionen $\supset$
   Menge von Lipschitz-stetigen Funktionen
   #+end_remark
   #+ATTR_LATEX: :options [3.13 Satz von der gleichmäßigen Stetigkeit, Satz von Heine für folgenkompakte metrische Räume]
   #+begin_defn latex
   Eine auf einer beschränkten, abgeschlossenen (das heißt kompakten) Teilmenge $D \subseteq \mathbb{K}$
   stetige Funktion ist gleichmäßig stetig.
   #+end_defn
   #+begin_proof latex
   Angenommen $f$ ist nicht gleichmäßig stetig. Dann gibt es ein $\eps > 0$, sodass $\Forall n\in \mathbb{N}$ Punkte $x_n, y_n \in D$ existieren mit
   $\abs{x_n - y_n} < \frac{1}{n}, \abs{f(x_n) - f(y_n)} \geq \eps$ \\
   Nach dem Satz von Bolzano-Weierstrass besitzt die beschränkte Folge $(x_n)_{n\in\mathbb{N}}$ eine
   konvergente Teilfolge $x_{n_k} \to x \in D$. Wegen $\abs{x_n - y_n}  < \frac{1}{n}$ ist auch $\lim_{k\to\infty} y_{n_k} = y = x$
   Aus der Stetigkeit von $f$ folgt, dass
   \[\abs{f(x_{n_k}) - f(y_{n_k})} \to \abs{f(x) - f(y)} = 0 \lightning\]
   #+end_proof
   #+begin_remark latex
   \mbox{}
   1. Wichtigkeit von Annahmen
	  - Abgeschlossenheit: $f(x) = x^{-1}$ für $x\in [-A, A] \setminus \{0\}$ Stetig, aber nicht gleichmäßig Stetig
	  - Beschränktheit: $f(x) =x^2$ für $x\in\mathbb{R}$ ist stetig, aber nicht gleichmäßig stetig auf $\mathbb{R}$ \\
		für $x = m$ und $y = x + \frac{1}{n}$ gilt
		\[\abs{x - y} \to 0, ~\text{aber}~ \abs{f(x) - f(y)} = \abs{x^2 - y^2} = \abs{(x - y)(x + y)} = 2 + \frac{1}{n} \to 2\]
   2. Libschitz-Stetigkeit von $f(x) = x^2$ \\
	  \[\abs{f(x) - f(y)} = \abs{(x - y)(x + y)} \leq L \abs{x y}\]
	  wenn $D$ beschränkt $D = [-A, A] \implies \abs{x + y} \leq 2A \implies L = 2A \implies$ Libschitz-Stetigkeit,
	  aber wenn $D = R \implies$ gibt keine $L < \infty$
   3. Libschitz-Stetigkeit impliziert gleichmäßige Stetigkeit, aber nicht umgekehrt. Zum Beispiel: $f(x) = \sqrt{x}, x \in [0, A]$ ist gleichmäßig stetig nach Satz 3.13, aber nicht Libschitz-stetig in $0$.
	  \begin{align*}
	  \abs{\sqrt{x} - \sqrt{y}} \leq L \abs{x - y} \\
	  \abs{\frac{y - x}{\sqrt{x} - \sqrt{y}}} > n \abs{x - y}
	  \intertext{$\implies \not\Exists L > 0$}
	  \end{align*}
   #+end_remark
   #+begin_remark latex
   Stetigkeit kann interpretiert werden als "lokale Approximation" durch Konstanten, das heißt Funktion $f$ nach der Stelle $x_0$ durch eine Konstante $f(x_0)$ approximiert werden
   kann und die Fehelr der Approximation $\abs{f(x) - f(x_0)} < \eps$
   #+end_remark
