* Stetige Abbildungen
** Grenzwert einer Funktion, Stetigkeit
   Wir betrachten die Funktion
   \[f:\mathbb{R}\setminus\{0\} \to \mathbb{R}, x\mapsto \frac{e^x - }{x} \]
   und wolllen diese auf ganz $\mathbb{R}$ fortsetzen, das heißt Wir suchen ein $\tilde f: \mathbb{R} \to \mathbb{R}$
   mit $\tilde f\mid \mathbb{R}\setminus \{0\} = f$ und einen Wert $\tilde f(0) \in \mathbb{R}$

   Allgemeiner überprüft man für Funktionen $f: D \subseteq \mathbb{K} \to \mathbb{K}$ die
   Fortsetzbarkeit auf den Abschluss $\bar D \subseteq \mathbb{K}$, wobei
   \begin{align*}
   \bar D &= \{x \in\mathbb{K} \mid x\in D \vee~\text{oder $x$ ist HP von D}\} \\
   &= \{x \in \mathbb{K} \mid \Exists (x_n)_{n\in\mathbb{N}} \subseteq D \wedge x = \lim_{n \to 0} x_n\}
   \end{align*}
   (analog zur Plenarübung)

   #+ATTR_LATEX: :options [3.1]
   #+begin_defn latex
   Eine Funktion $f: D\subseteq \mathbb{K} \to \mathbb{K}$ hat im Punkt $x_0 \in \bar D$ einen
   Grenzwert $a \in\mathbb{K}$, wenn alle Folgen $(x_n)_{n\int\mathbb{N}} \subseteq D$ gilt:
   \[x_n \to x_0 (n \to \infty) \Rightarrow f(x_n) \to a (n\to\infty)\]
   Wir schreiben kurz: $\lim_{x\to x_0} f(x) = a$
   #+end_defn
   #+begin_remark latex
   - Falls der Grenzwert existiert, ist er eindeutig.
   - Ist $T\subseteq D \subseteq \mathbb{R}, T\neq \emptyset, f: D\to\mathbb{R}, x_\in \bar T$, dann
	 verstehen wir unter
	 \[\lim_{\substack{x\to x_0 \\ x\in T}} f(x)\]
	 den Grenzwert $\lim_{x\to x_0} f\mid T$, falls er existiert.
   - Spezialfällte:
	 \begin{align*}
	 T_{>} := \{x\in D\mid x > x_0\}: f(x_0^{+}) := \lim_{\substack{x\to x_0 \\ x\in T_{>}}} f(x) = \lim_{x\to x_0^{+}} f(x) \tag{rechtsseitiger Grenwzwert} \\
	 T_{<} := \{x\in D\mid x < x_0\}: f(x_0^{-}) := \lim_{\substack{x\to x_0 \\ x\in T_{<}}} f(x) = \lim_{x\to x_0^{-}} f(x) \tag{linksseitiger Grenwzwert}
	 \end{align*}
   - Existiert $\lim_{x\to x_0} f(x), x_0 \in \bar T \subseteq \bar D$, dann gilt
	 \[\lim_{x\to x_0 \\ x\in T} f(x) = \lim_{x\to x_0}  f(x)\]
   - Es gelten die üblichen Rechenregeln für Grenzwerte $(x,\cdot, :)$
   #+end_remark
   #+ATTR_LATEX: :options [3.2]
   #+begin_ex latex
   1. $f:\mathbb{R}\setminus\{0\}, x\mapsto \frac{x}{\abs{x}}$
	  \[\lim_{x\to 0^+} f(x) = 1 \wedge \lim_{x \to 0^-} f(x) = -1\]
	  Also existiert $\lim_{x\to 0} f(x)$ nicht
   2. $f:\mathbb{R}\setminus\{0\}, x\mapsto \frac{e^x - 1}{x}$ \\
	  Es gilt $\lim_{x\to 0} f(x) = 1$, denn für $\abs{x} \leq 1, x\neq 0$ gilt
	  \[\abs{f(x) - 1} = \abs{\frac{e^x - 1 - x}{x}} = \abs{\sum_{k = 2}^{\infty} \frac{x^{k - 1}}{k!}} \leq \abs{x} \sum_{k = 2}^{\infty} \frac{\abs{x}^{k - 2}}{k!} \leq \abs{x} \sum_{k = 2}^{\infty} \frac{1}{k!} = \abs{x} \underbrace{(e - 2)}_{> 0}\]
	  Für Nullfolgen $(x_n)_{n\in\mathbb{N}} \subseteq [-1, 1]\setminus \{0\}$ folgt $\lim_{n \to \infty} f(x_n) = 1$
	  Das heißt $f$ besitzt eine Fortsetzung
	  \[\tilde f: \mathbb{R} \to \mathbb{R}, x\mapsto \begin{cases} \frac{e^x - 1}{x} & x \neq 0 \\ 1 & x = 0\end{cases}\]
   #+end_ex
   #+ATTR_LATEX: :options [3.3 Asymptotisches Verhalten]
   #+begin_defn latex
   Sei $\emptyset \neq D \subseteq \mathbb{R}$ nach oben (nach unten) unbeschränkt.
   Die Funktion $f: D\to \mathbb{R}$ hat für $x \to + \infty (x \to -\infty)$ einen Grenzwert $a\in \mathbb{R}$, wenn gilt:
   \[\Forall \eps > 0 \Exists y\in \mathbb{R}: \abs{f(x) - a} < \eps \Forall x\in D, x > y (x < y)\]
   Schreibweise: $\lim_{x \to \infty}f(x) = a$, oder $\lim_{x\to -\infty} f(x) = a$

   Sei $x_0 \in \bar D$. Die FUnktion $f$ divergiert bestimmt gegen $+\infty (-\infty) :\Leftrightarrow \Forall K\in\mathbb{R}_{+} \Exists \delta > 0: f(x) > K (f(x) < -K) \Forall x\in I_\delta (x_0) \cap (D\setminus\{x_0\})$ \\
   Schreibweise: $f(x) \to +\infty (f(x) \to -\infty)$ für $x\to x_0$
   #+end_defn
   #+ATTR_LATEX: :options [3.4]
   #+begin_ex latex
   1. $f:\mathbb{R}\setminus\{1\}, x\mapsto \frac{1}{x - 1}$
	  \[\lim_{x\to\infty} \frac{1}{x} = 0 = \lim_{x\to -\infty} \frac{1}{x}\]
	  wir schreiben kurz $\lim_{\abs{x} \to \infty} \frac{1}{x} = 0$
   2. $\Forall k\in\mathbb{N}$ gilt
	  \[\lim_{x\to\infty} \frac{x^k}{e^x} = 0 = \lim_{x\to -\infty} x^k e^x,~\text{denn}~ e^x = \exp(x) \geq \frac{x^{k + 1}}{(k + 1)!}, x\geq 0 \]
	  \[\Rightarrow \frac{x^k}{e^x} \leq \frac{(k + 1)!}{x} \to 0 (x\to \infty)\]
	  \[x^k e^x = \frac{(-1)^k \abs{x}^k}{e^{\abs{x}}}, x < 0\]
   #+end_ex
   #+ATTR_LATEX: :options [3.5]
   #+begin_defn latex
   Eine Funktion $f:D \subseteq \mathbb{K} \to \mathbb{K}$ heißt stetig im Punkt $x_0 \in D$, wenn gilt:
   Für alle Folgen $x_n \to x_0 (n\to\infty) \Rightarrow f(x_n) \to f(x_0) (n \to \infty)$
   Andernfalls heißt sie unstetig in $x_0 \in D$.
   $f$ heißt stetig (auf ganz $D$), wenn sie in jedem $x_0 \in D$ stetig ist. (/insert Symbolbild hier/) \\
   #+ATTR_LATEX: :options [3.5]
   #+begin_lemma latex
   1. Ist $f: D\to \mathbb{K}$ stetig, dann ist auch $f\mid T$ statig, $T\subseteq D$
   2. Ist $f:D\to \mathbb{K}$ stetig, so auch $\Re(f):D\to\mathbb{R}$, $\Im(f): D\to \mathbb{R}$, $\abs{f}: D\to\mathbb{R}_+$ stetig (auf ganz $D$)
   3. Sind $f,g:D\to\mathbb{K}$ stetig, so auch $f + g, f\cdot g: D\to\mathbb{K}$
   4. Ist $f:D\to f(D)\subseteq \mathbb{K},g:f(D) \to \mathbb{K}$ stetig in $x_0$, beziehungsweise in $f(x_0) =: y_0$ so auch $f \circ f: D\to\mathbb{K}$ stetig in $x_0 \in D:$
   #+end_lemma
   #+begin_proof latex
   1. Siehe Bemerkung zu Grenzwerte
   2. Für $z = a + \I b$ gilt $\abs{\abs{a} - \abs{b}} \leq \abs{a - b}$ sowie $\abs{z}^2 = a^2 + b^2 \geq a^2 \geq b^2$
   3. Siehe Bemerkung zu Grenzwerte
   4. Sei $(x_n)_{n\in\mathbb{N}} \subseteq D$ mit $\lim_{n \to\infty} x_n = x_0$, dann folgt aus Stetigkeit von $f: \lim_{n\to\infty} f(x_n) = f(x_0)$ \\
	  $(g\circ f)(x_n) = g(f(x_n)) \rightarrow g(f(x_0)) = (g\circ f)(x_0) (n\to\infty)$
   #+end_proof
   #+ATTR_LATEX: :options [3.7 $\eps/\delta$ Kriterium]
   #+begin_lemma latex
   Eine Funktion $f: D \to \matbb{K}$ ist in $x_0 \in D$ genau dann stetig, wenn es zu jedem $\eps > 0$ ein $\delta = \delta(\eps) > 0$ gibt, sodass Für alle $x \in D$ gilt:
   \[\abs{x - x_0} < \delta \Rightarrow \abs{f(x) - f(x_0)} < \eps\]
   #+end_lemma
   #+begin_proof latex
   $(\Leftarrow)$: Gilt das $\eps / \delta$ Kriterium, so ist $f$ auch in $x_0$ offensichtlich stetig \\
   $(\Rightarrow)$: Sei also $f$ stetig in $x_0$. Angenommen, dass $\eps / \delta$-Kriterium gälte nicht,
   das heißt es gibt ein $\eps > 0$, sodass $\Forall \delta > 0$ ein $x\in D$ mit $\æbs{x - x_0} < \delta$ und $\abs{f(x) - f(x_0)} \geq \eps$ gibt. Wiederspruch zu
   \[\lim_{x \to x_0} f(x) = f(x_0)\]
   #+end_proof
   #+ATTR_LATEX: :options [3.8]
   #+begin_korollar latex
   Sei $f: D \to \mathbb{K}$ stetig in $x_0 \in D$ mit $f(x_0) \neq 0$. Dann gibt es ein $\delta > 0$ mit $f(x) \neq 0$
   #+end_korollar
