* Folgen
  Eine Folge von reellen Zahlen wird gegeben durch eine Abbildung \[\mathbb{N}_0 \to \mathbb{R},n\mapsto x_n\]
  Wir bezeichnen die Folge auch mit $(x_n)_{n\in\mathbb{N}_0}$

  Topologische Struktur auf Mengen.
  - Abstände in $\mathbb{R}^1$ Betrag $\abs{x - y}$ $\xrightarrow{\text{Verallgemeinerung}}$ Norm / Metrik
  - Umgebung in $\mathbb{R}^1$ \(\eps\)-Intervall $\xrightarrow{\text{Verallgemeinerung}}$ Kugel Umgebung

  Wir betrachten Folgen $\mathbb{N}\to\mathbb{R}, n\mapsto a_n$ (oder $\mathbb{C}$)
** Definition 2.1 Konvergenz
   Wir sagen, dass die Folge $(a_n)_{n\in\mathbb{N}}$ in $\mathbb{K}$ ($\mathbb{R}$ oder $\mathbb{C}$) gegen den Grenzwert (oder Limes) $a\in\mathbb{K}$ konvergiert
   \[a_n \xrightarrow{n\to\infty} a~(a=\lim_{n\to\infty} a_n)\]
   wenn für beliebiges $\eps > 0$ von einem $n_\eps \in\mathbb{N}$ an gilt
   \[\abs{a_n - a} < \eps,n\geq n_\eps\]
   \[\iff \Forall\eps > 0\exists n_\eps \in\mathbb{N}:\Forall n\geq n_\eps a_n \in I_\eps(a)\]
** Folgerung 2.2
   Sei $(a_n)_{n\in\mathbb{N}}$ eine monoton wachsende beziehungsweise fallende Folge reeller Zahlen $M=\{a_n\mid n\in\mathbb{N}\}$ und sei nach oben beziehungsweise unten beschränkt. Dann gilt \[a_n\to\sup M, a_n\to\inf M\]
   Beweis \to Übungen
** Definition 2.3 Cauchy Folgen
   Eine Folge $(a_n)_{n\in\mathbb{N}}$ heißt Cauchy-Folge wenn:
   \[\Forall\eps > 0 \exists n_\eps \in\mathbb{N}\Forall n,m \geq n_\eps: \abs{a_n - a_m} < \eps \]
   (Cauchy Kriterium)
** Definition 2.4 Teilfolge
   Eine Teilfolge einer gegebenen Folge $(a_n)_{n\in\mathbb{N}}$ ist eine Auswahl $(a_{n_k})_{k\in\mathbb{N}}$, wobei $a_{n_k}$ auch die Glieder von $(a_n)_{n\in\mathbb{N}}$ sind
   \begin{ex}[Beispiel 2.5]
   \[a_n = \frac{1}{m}\] ist eine Cauchy-Folge. Für ein $\eps > 0$ wählen wir $n_\eps$ so dass $n_\eps > \frac{1}{\eps}$. Für beliebiges $n\geq m > N$
   \[\abs{a_m - a_n} = \abs{\frac{1}{m} - \frac{1}{n}} = \frac{n - m}{m n} \leq \frac{n}{m n} = \frac{1}{m} < \frac{1}{n_\eps} < \eps\hfill\square\]
   \end{ex}
   \begin{thm}[Jede Cauchy-Folge ist beschränkt]
   \end{thm}
   \begin{proof}
   Sei $(a_n)_{n\in\mathbb{N}}$ eine Cauchy-Folge. Angenommen, die Folge ist nicht beschränkt. Dann gibt es eine Teilfolge $(a_{n_k})_{k\in\mathbb{N}}$ mit
   \[\abs{a_{n_k}}\xrightarrow[k\to\infty]{} \infty\]
   Aus dieser Teilfolge kann man eine weitere Teilfolge
   \[(a_{n_{k_l}})_{l\in\mathbb{N}}\]
   extrahieren
   \[\abs{a_{n_{k_{i + 1}}}} > 2 \abs{a_{n_{k_l}}}\quad l\in\mathbb{N}\]
   Dann gilt
   \[\abs{a_{n_{k_{i + 1}}} - a_{n_{k_l}}} \geq \abs{a_{n_{k_{i + 1}}}} - \abs{a_{n_{k_l}}} > \abs{a_{n_{k_l}}}\xrightarrow[k\to\infty]{} \infty\]
   im Widerspruch zur Cauchy-Folgen Eigenschaft.
   \end{proof}
   \begin{thm}[Jede konvergente Folge ist Cauchy-Folge]
   \end{thm}
   \begin{proof}
   \begin{align*}
   a_n \xrightarrow[k\to\infty]{} a &\implies \Forall \eps > 0 \exists n_\eps \in\mathbb{N} \Forall n\geq n_\eps: \abs{a - a_n} < \frac{\eps}{2} \\
   &\implies \Forall n,m\in n_\eps: \abs{a_n - a_m} \leq \abs{a_n - a} + \abs{a - a_m} <\frac{\eps}{2} + \frac{\eps}{2}
   \end{align*}
   \end{proof}
   \begin{lemma}
   \label{lemma:one_limit}
   Sei $(a_n)_{n\in\mathbb{N}}$ eine Folge in $\mathbb{K}$ ($\mathbb{R}$ oder $\mathbb{C}$) welche gegen $a\in\mathbb{K}$ und $\tilde a \in \mathbb{K}$ konvergiert. Dann ist $a = \tilde a$.
   \end{lemma}
   \begin{proof}
   Beweis durch Widerspruch. \\
   Falls $\abs{a - \tilde a} > 0$, dann
   \[\exists n_\eps \in\mathbb{N}\Forall n\geq n_\eps \eps = \abs{a - \tilde a}, \abs{a_n - a} < \frac{\eps}{2}\]
   und ein $m_\eps$, sodass
   \[\abs{a_n - \tilde a < \frac{\eps}{2}} \Forall n\geq m_\eps\]
   Dann für $n \geq \max \{n_\eps, m_\eps\}$:
   \[\abs{a - \tilde a} \leq \abs{a - a_n} + \abs{a_n - \tilde a} < \eps\lightning\]
   \textbf{Widerspruch} $\implies a = \tilde a$
   \end{proof}
   \begin{remark}
   Die Mengen Abständen heißen *vollständig*, wenn jede Cauchy-Folge in $M$ konvergiert
   \end{remark}
   \begin{defn}[Häufungwert, Häufungspunkt]
   Ein $a\in\mathbb{K}$ heißt Häufungswert einer Folge $(a_n)_{n\in\mathbb{N}}$ in $\mathbb{K}$, wenn es zu beliebigen $\eps > 0$ unendlich viele Folgenelemente $a_n$ gibt mit $\abs{a - a_n} < \eps$

   Ein $a\in\mathbb{K}$ heißt Häufungspunkt einer Teilmenge $M$ von $\mathbb{K}$, wenn $\Forall \eps > 0$ existieren unendlich viele $x\in M$, sodass $\abs{a - x} < \eps$
   \end{defn}
   \begin{ex} \mbox{}
   \begin{enumerate}
   \item $a_n = (-1)^n, n\in\mathbb{N}$
   \begin{itemize}
	  \item divergente Folge
	  \item besitzt 2 Häufungswerte $a^{(1)} = 1, a^{(2)} = -1$
   \end{itemize}
   \item Wir nehmen $a_n \xrightarrow[n\to\infty]{} a, b_n \xrightarrow[n\to\infty]{} b$ und definieren eine neue Folge $c_n$ sodass
	  \begin{align*}
	  c_{2n} &:= b_n,n\in\mathbb{N} \\
	  c_{2n + 1} &:= a_n,n\in\mathbb{N}
	  \end{align*}
	  $(c_n)_{n\in\mathbb{N}}$ hat 2 Häufungswerte $a$ und $b$
   \end{enumerate}
   \end{ex}
   \begin{remark}
   Nach \ref{lemma:one_limit} hat die konvergente Folge 1 Häufungswert
   \end{remark}
   \begin{lemma}[2.11]
   \label{lemma:cauchy_haufungswert}
   Sei $(a_n)_{n_\in\mathbb{N}}$ eine Cauchy-Folge in $\mathbb{K}$ und $a$ ein Häufungswert von $(a_n)_{n\in\mathbb{N}}$, dann konvergiert $a_n \xrightarrow[n\to\infty]{} a$
   \end{lemma}
   \begin{proof}
   Sei $\eps > 0$ beliebig vorgegeben. Wir wählen $n_\eps \in\mathbb{N}$ sodass
   \[\abs{a_n - a_m} < \frac{\eps}{2}\Forall n,m > n_\eps\hfill\text{ (aus Cauchy-Folge)}\]
   und $m_\eps > n_\eps$ mit
   \[\abs{a - a_{m_\eps}} < \frac{\eps}{2}\hfill\text{ (Häufungswert)}\]
   Dann folgt
   \[\Forall n > m_\eps: \abs{a - a_n} \leq \abs{a - a_{m_\eps}} + \abs{a_{m_\eps} - a_n} < \eps \implies a_n \xrightarrow[n\to\infty]{} a\]
   \end{proof}
   \begin{thm}
   \label{thm:finite}
   $A$ abgeschlossen $\iff$ ($a$ Häufungspunkt von $A \implies a\in A$)
   $A$ abgeschlossen in M $\iff$ $M\setminus A =: CA$ offen
   \end{thm}
   \begin{proof}
   $(\impliedby)$: \\
   Sei jeder Häufungspunkt von $A$ in $A$
   $x\in CA (=\mathbb{R}\setminus A) \implies x$ kein Häufungspunkt von $A, x\not\in A$
   \[\implies \eps: I_\eps (x) \cap A = \emptyset \implies \exists \eps > 0: I_\eps \subseteq CA\]
   $\implies CA$ offen $\implies A$ abgeschlossen \\
   $(\implies)$: \\
   Sei $A$ abgeschlossen, also $CA$ offen, ist Häufungspunkt $x\not\in A$ das heißt $x \in CA$, so gilt
   \[\exists \eps > 0: I_\eps \subseteq CA \implies I_\eps (x) \cap A = \emptyset \text{\lightning}\]
   \textbf{Widerspruch} zur Definition von Häufungspunkt $\implies$ jeder Häufungspunkt von $A$ ist in $A$
   \end{proof}
   \begin{lemma}[2.14]
   \label{lemma:monoton_in_r}
   Jede Folge $(a_n)_{n\in\mathbb{N}} \in \mathbb{R}$ besitzt eine monotone Teilfolge
   \end{lemma}
   #+begin_proof latex
   Sei $B=\{n\in\mathbb{N}\mid \Forall k\geq n, a_n \geq a_k\}$
   - Fall 1: $B$ unendlich. Wir zählen $B\subseteq \mathbb{N}$ monoton wachsend \\
	 \begin{align*}
	 n_0 &= \min{B} \\
	 n_{k+1} &= \min\{n\in B, n > n_k\}
	 \end{align*}
	 Dann ist die Teilfolge $(a_{n_k})_{k\in\mathbb{N}}$ von $(a_n)_{n\in\mathbb{N}}$ monoton fallend
   - Fall 2: $B$ ist endlich oder leer
	 \begin{align*}
	 \implies &\exists n_0 \in\mathbb{N}: \Forall n\geq n_0: n\not\in B \\
	 \shortintertext{das heißt}
	 \exists k\leq n: a_n < a_k
	 \end{align*}
	 Damit können wir definieren
	 \[n_{k + 1} = \min\{k \geq n_k: a_{n_k} < a_k\}\]
	 und die Folge $(a_{n_k})_{k\in\mathbb{N}}$ ist monoton wachsend
   #+end_proof
   #+begin_ex latex
   1. $a_n = (-1)^n (1 + \frac{1}{n + 1}),\quad B=\{2 n \mid n \in\mathbb{N}\}$ monoton fallend
   2. $a_n = (-1)^n n, (a_{2k})_{k\in\mathbb{N}}$ ist monotone Teilfolge
   #+end_ex
   \begin{thm}[Satz von Bolzano Weierstrass]
   Sei $A\subseteq \mathbb{R}$ ( gilt in $\mathbb{R}^n$!) Folgende Aussagen sind äquivalent:
   \begin{enumerate}
   \item \label{bolzano:1} $A$ ist beschränkt abgeschlossen
   \item \label{bolzano:2} Jede Folge $(a_n)_{n\in\mathbb{N}}$ aus $A$ hat einen Häufungswert in $A$
   \item \label{bolzano:3} Jede Folge $(a_n)_{n\in\mathbb{N}}$ aus $A$ besitzt eine in $A$ konvergente Teilfolge $(a_{n_k})_{k\in\mathbb{N}}$
   \end{enumerate}
   \end{thm}
   #+begin_proof latex
   Wir zeigen \ref{bolzano:3} $\implies$ \ref{bolzano:2} $\implies$ \ref{bolzano:1} $\implies$ \ref{bolzano:3} \\
   \ref{bolzano:3} $\implies$ \ref{bolzano:2}: \\
   Sei $(a_{n_k})_{k\in\mathbb{N}}$ konvergente Teilfolge von $(a_n)_{n\in\mathbb{N}}$ und $a = \lim_{k\to\infty} a_{n_k}$
   $a$ ist auch der Häufungswert der Folge $(a_n)_{n\in\mathbb{N}}$ \\
   \ref{bolzano:2} $\implies$ \ref{bolzano:1}: \\
   \begin{enumerate}
   \item Beschränktheit:
   Angenommen dies ist falsch. Dann
   \[\exists (a_n)_{n\in\mathbb{N}} \in A: \abs{a_n - a} \geq n \Forall n\in\mathbb{N}~(a\in A)\]
   Nach Voraussetzungen hat jede diese Folge einen Häufungspunkt $x\in A$ und es gilt
   \[\abs{x - a} \geq \abs{a_n - a} - \abs{a_n - x} \geq n - \abs{x - a_n}\]
   Dabei gilt $\abs{x - a_n} < 1$ für unendlich viele $n\in\mathbb{N}$ (aus Häufungswert)
   \[\implies \abs{x - a} \geq n - 1\]
   Für unendlich viele $n\in\mathbb{N} \lightning$
   \item Abgeschlossenheit: Wir nutzen Satz \ref{thm:finite}
   Zu zeigen: wenn $a$ Häufungspunkt von $A \implies a\in A$
   Für
   \[I_{\frac{1}{n}}(a) = \{x\in\mathbb{R} \mid \abs{x - a} < \frac{1}{n}\}\]
   gilt
   \[I_{\frac{1}{n}}(a) \cap A \neq \emptyset \implies \exists a_n\in A: \abs{a_n - a} < \frac{1}{n}\]
   Die Folge $(a_{n_k})_{k\in\mathbb{N}} \to a$, da $\frac{1}{n}\to 0$
   Nach Voraussetzung hat $(a_n)_{n\in\mathbb{N}}$ einen Häufungswert $\tilde a \in A$. Wir zeigen $a = \tilde a$
   Sei $\eps > 0$ beliebig.
   \begin{align*}
   &\exists n_\eps\in\mathbb{N}: \abs{a - a_n} <\frac{\eps}{2}\Forall n\geq n_\eps \tag{\text{Aus }$a_n \to a$} \\
   &\exists m_\eps\geq n_\eps: \abs{\tilde a - a_{m_\eps}} <\frac{\eps}{2} \tag{\text{Aus Häufungswert}} \\
   &\implies \abs{a - \tilde a} \leq \abs{a - a_{m_\eps}} + \abs{a_{m_\eps}} < \eps \\
   &\implies \abs{a - \tilde a} = 0 \\
   &\implies \tilde a = a \in A
   \end{align*}
   \end{enumerate}
   \ref{bolzano:1} $\implies$ \ref{bolzano:3}: \\
   Sei nun $(a_n)_{n\in\mathbb{N}}$ eine Folge in $A$, $(a_{n_k})_{k\in\mathbb{N}}$ eine monotone Teilfolge (nach \ref{lemma:monoton_in_r}), $(a_{n_k})$ ist beschränkt, da $A$ beschränkt ist $\implies (a_{n_k})$ ist konvergent ([[Folgerung 2.2]]) \\
   Wir müssen zeigen, dass
   \[a = \lim_{n\to\infty} a_{n_k} \in A\]
   \begin{align*}
   \intertext{Angenommen $a\not\in A \implies a \in \mathcal{C} A, \mathcal{C} A$ ist offen}
   \implies \exists I_\eps (a) \subseteq \mathcal{C}A \implies I_\eps (a) \cap A = \emptyset \\
   \shortintertext{Nun ist aber mit geeigneten $n_\eps \in\mathbb{N}$}
   \Forall n\geq n_\eps: a_{n_k} \in I_\eps (a): a_{n_k} \in A \implies a_{n_k} \in I_\eps (a) \cap A~\lightning
   \end{align*}
   #+end_proof
   #+begin_remark latex
   - Erweiterung zu $\mathbb{R}^n$ möglich
   - Ein Raum heißt folgenkompakt, wenn jede beschränkte Folge eine konvergente Teilfolge hat
	 - Nach B-W Satz ist $\mathbb{R} (\mathbb{R}^n)$ folgenkompakt
   - In $\mathbb{R}$ alle Cauchy-Folgen konvergieren
	 - Cauchy Folge in $\mathbb{R} \implies$ beschränkt und Wertemenge ist abgeschlossen $\xRightarrow{B-W Satz} (a_n)_{n\in\mathbb{N}}$ hat einen Häufungswert in $A \xRightarrow{\ref{lemma:cauchy_haufungswert}}$ konvergiert gegen $a\in A$
   #+end_remark
** Rechenregeln für Grenzwerte von Folgen
   #+begin_thm latex
   Seien $(a_n)_{n\in\mathbb{N}}, (b_n)_{n\in\mathbb{N}}$ konvergente Folgen in $\mathbb{K} (\mathbb{R}~\text{oder}~\mathbb{C})$
   \[b_0 \neq 0 \Forall n\in\mathbb{N}, \lim_{n\to\infty} b_n \neq 0\]
   Dann gilt:
   1. $\displaystyle \lim_{n\to\infty} (a_n + b_n) = \lim_{n\to\infty} a_n + \lim_{n\to\infty} b_n$
   2. $\displaystyle \lim_{n\to\infty} (a_n b_n) = \lim_{n\to\infty} a_n \lim_{n\to\infty} b_n$
   3. $\displaystyle \lim_{n\to\infty} (\frac{a_n}{b_n}) = \frac{\lim_{n\to\infty} a_n}{\lim_{n\to\infty} b_n}$
   #+end_thm

   #+ATTR_LATEX: :options [2.15]
   #+begin_thm latex
   Seien $(a_n)_{n\in\mathbb{N}}, (b_n)_{n\in\mathbb{N}}$ konvergente Folgen in $\mathbb{R}$. Dann gilt
   1. $\displaystyle a_n \leq b_n \Forall n\in\mathbb{N} \implies \lim_{n\to\infty} a_n \leq \lim_{n\to\infty} b_n$
   2. $\displaystyle \abs{a_n} \leq b_n \Forall n\in\mathbb{N} \implies \abs*{\lim_{n\to\infty a_n}} \leq \lim b_n$
   #+end_thm
   #+begin_proof latex
   1. Sei $\eps > 0$ vorgegeben
	  \begin{align*}
	  \exists n_\eps:\Forall n\geq n_\eps: b_n \leq \lim_{k\to\infty} b_n + \frac{\eps}{2} \\
	  \shortintertext{und}
	  \lim_{k\to\infty} a_k \leq a_n + \frac{\eps}{2} \\
	  &\implies \lim_{k\to\infty} a_k \leq a_n + \frac{\eps}{2} \leq b_n + \frac{\eps}{2} \leq \lim_{k\to\infty} b_k + \eps \Forall \eps > 0 \\
	  &\implies \lim_{\k\to\infty} a_k \leq \lim_{k\to\infty} b_k
	  \end{align*}
   2. Wir wählen $a_n = \abs{a_n}$ und müssen noch zeigen
	  \[\lim_{n\to\infty} \abs{a_n} = \abs{\lim_{n\to\infty}} a_n\text{ (Übung)}\]
   #+end_proof
** Geometrische Folge
   Die geometrische Folge ist definiert durch
   \[a_n = c q^n\]

   #+ATTR_LATEX: :options [2.16]
   #+begin_lemma latex
   $\Forall q\in\mathbb{R},\abs{q} < 1$ konvergiert die geometrische Folge $a_n = c q^n$ gegen Null.
   #+end_lemma
   #+begin_proof latex
   Sei $\eps > 0$ gegeben. Nach Annahme ist $\abs{q} < 1 \implies \abs{q}^{-1} > 1$, somit $\abs{q}^{-1} = 1 + x$ für ein $x > 0$. \\
   \begin{align*}
   \intertext{Zu zeigen: $\abs{c q^n - 0} < \eps$ für genug große $n$, das heißt}
   c(\frac{1}{1+x})^n < \eps \iff \frac{c}{\eps} < (1 + x)^n \\
   \intertext{Das Archimedisches Axiom garantiert die Existenz von $n_0\in\mathbb{N}$:}
   n_0 > \frac{c}{x\eps} - \frac{1}{x} = \frac{c - \eps}{x\eps} \\
   \Forall n\geq n_0: \frac{c}{\eps} = (\frac{c}{x\eps} - \frac{1}{x}x + 1 < n_0 x + 1 \leq n x + 1)
   \intertext{daraus folgt aus der Bernoulli Ungleichung}
   \frac{c}{\eps} < (1 + x)^n \implies c q^n \to 0
   \end{align*}
   #+end_proof
   #+ATTR_LATEX: :options [2.17]
   #+begin_conc latex
   Die geometrische Reihe
   \[S_n = 1 + q + q^2 + \ldots + q^n = \sum_{i = 0}^n q^i\]
   konvergiert für $\abs{q} < 1$ und $\lim_{n\to\infty} S_n = \frac{1}{1 - q}$
   #+end_conc
   #+begin_proof latex
   \begin{gather*}
   \intertext{zu Beweisen mit Induktion}
   \string(1 - q\string)\string(1 + q + q^2 + \ldots + q^n\string) = 1 + q^{n + 1} \\
   \implies S_n - \frac{1}{1 - q} = \frac{1 - q^{n + 1} - 1}{1 - q} = -\frac{q^{n + 1}}{1 - q} \\
   \abs{S_n - \frac{1}{1 - q}} = c\abs{q}^n < \eps \Forall n\geq n_\eps \\
   \intertext{$c = \abs*{\frac{1}{1 - q}}$}
   s_n \to \frac{1}{1 -q}
   \end{gather*}
   #+end_proof
   #+ATTR_LATEX: :options [2.18]
   #+begin_ex latex
   \mbox{}
   1. $\displaystyle \lim_{n\to\infty} \frac{10^n}{n!} \leq \lim_{n\to\infty}cq^n$ mit $\abs{q} < 1$
   2. $a_n = \sqrt{n}(\sqrt{n + 1} - \sqrt{n}) = \sqrt{n} \frac{n + 1 - 1}{\sqrt{n + 1} + \sqrt{n}} = \frac{\sqrt{n}}{\sqrt{n + 1}} + \sqrt{n} = \frac{1}{\sqrt{1 + 1_n} + 1} \xrightarrow{n \to \infty} \frac{1}{2}$
   3. $a_n = \sqrt[m]{x}$, $x$ gegeben, $\xrightarrow{n\to\infty} 1$ \hfill Übungen
   4. $a_n = \sqrt[n]{m}\xrightarrow{n\to\infty} 1$
   5. $a_n = \sum_{i = 0}^{n} \frac{1}{i!}$
	  - $(a_n)_{n\in\mathbb{N}}$ ist monoton wachsend
	  - beschränkt: $a_n < 3 \Forall n\in\mathbb{N}$
	  - $\implies (a_n)_{n\in\mathbb{N}}$ konvergiert, Limes ist sogenannten Zahl $\euler$
   6. $(a_n)_{n\in\mathbb{N}}$ rekursiv definiert: $a_0 = 0, a_1 = 1, a_n = a_{n - 1} + a_{n - 2}$ Fibonacci Folge
   #+end_ex
** Umgebung
   #+ATTR_LATEX: :options [2.19]
   #+begin_defn latex
   $A\subseteq \mathbb{K}$ heißt Umgebung von $a\in\mathbb{K} \iff \Exists \eps > 0 I_\eps (a) \subseteq A$
   #+end_defn
   #+ATTR_LATEX: :options [2.20]
   #+begin_conc latex
   Aus der Definition folgt
   1. Sei $U_i, i\in I$ Umgebung von $a$, so ist $\bigcup\limits_{i\in I}  U_i$ Umgebung von $a$
   2. Sind $U_1,\ldots, U_n$ Umgebung von $a$, so ist auch $U_1 \cap \ldots U_n$ Umgebung von $a$
   3. $\Forall$ Umgebung von $a: \Exists$ Umgebung von $a$, sodass $\Forall y\in V, U$ Umgebung von $y$ ist
   #+end_conc
   #+begin_proof latex
   1. Für irgendein \[i_0 \in I \Exists \eps > 0: I_\eps (a) \subseteq U_{i_0} \subseteq \bigcup_{i \in I} U_i\]
   2. Es gilt nach Voraussetzung $\eps_1, \ldots \eps_n > 0$ mit $I_{\eps_i}(a) \subseteq U_i$ für $i = 1,\ldots,n$. Folglich gilt für $\eps:= \min \{\eps_1, \ldots, \eps_n\} > 0,~I_\eps(a) \subseteq U_i (\Forall i = 1,\ldots,n) \implies I_\eps (a) \subseteq U_1 \cap \ldots U_n$
   3. Nach Voraussetzung gibt es für eine Umgebung $U$ von $a$ ein $\eps > 0$ mit $I_\eps(a) \subseteq U$ \\
	  $V:= I_{\frac{\eps}{2}}(a) \subseteq U$ ist ebenfalls Umgebung von $a$ und $\Forall y\in V$ gilt
	  \[I_{\frac{\eps}{2}} \subseteq I_\eps(x) \subseteq U,~\text{denn}~ \underbrace{\abs{y - z}}_{z\in I_{\frac{\eps}{2}}} < \frac{\eps}{2} \implies \abs{x - z} \leq \abs{x - y} + \abs{x - z} < \eps\]
   #+end_proof
   #+ATTR_LATEX: :options [2.21]
   #+begin_defn latex
   \mbox{}
   1. $A\subseteq \mathbb{K}$ ist offen $\iff \Forall a\in A$ ist $A$ die Umgebung von $a$ \\
	  (in $\mathbb{R}\Forall a\in A \Exists \eps > 0 I_\eps (a) \subseteq A$)
	  Für Intervalle $(a,b)$ haben wir schon gezeigt, dass sie offen sind
   2. $A\subseteq \mathbb{K}$ heißt abgeschlossen $\iff C_\mathbb{K} A$ offen
   3. Abschließung von $A$: \[\bar A := \{a \in \mathbb{K} \mid a \in A \vee a ~\text{Häufungspunkt von}~A\}\]
   4. Rand von $A$: \[\partial A:= \{a\in\mathbb{K}\mid \Forall ~\text{Umgebung $U$ von $a$}: A \cap U \neq \emptyset \wedge CA \cap U \neq \emptyset\}\]
   #+end_defn
   #+ATTR_LATEX: :options [2.22]
   #+begin_ex latex
   \begin{align*}
   A&= \string(a,b] \\
   \bar A &= [a,b] \\
   \partial A &= \{ a,b \} \\
   \Forall \eps > 0 I_\eps(a) \cap \string(a,b] \neq \emptyset \\
   I_\eps (a) \cap \mathbb{R} \setminus \string(a,b] \neq \emptyset
   \end{align*}
   Sei $A = \mathbb{Q}$, dann $\bar A =\mathbb{\mathbb{R}}$, $\partial A =\mathbb{R}$ denn in jedem \(\eps\)-Intervall um eine rationale Zahl gibt es sowohl rationale als auch irrationale Zahlen
   #+end_ex
   #+begin_remark latex
   \mbox{}
   - Die Grenzwerte und Häufungswerte kann man auch in ganz \[\mathbb{R} \cup \{\infty\} \cup \{\infty\} =: \hat{\mathbb{R}}\]
	 mit einer neuen Definition von Abstand: \[(x,y) := \abs{\xi(x) - \abs{\xi(y)}}\]
	 \[\xi(x) := \begin{cases} \frac{\abs{x}}{1 + \abs{x}} & x\in\mathbb{R} \\ \pm 1 & x = \pm \infty \end{cases}\]
   - $\hat{\mathbb{R}}$ ist folgenkompakt
   - Algebraische Operationen in $\hat{\mathbb{R}}$
	 \begin{align*}
	 x + \infty &:= \infty + x := \infty \Forall x \in \mathbb{R} \cup \{\infty\} \\
	 x - \infty &:= -\infty + x := -\infty \Forall x \in \mathbb{R} \cup \{-\infty\} \\
	 x\cdot\infty &:= \infty \cdot x := \begin{cases} \infty & \Forall x\in\hat{\mathbb{R}}, x > 0 \\ -\infty & \Forall x\in\hat{\mathbb{R}},x < 0\end{cases} \\
	 \frac{1}{\infty} = \frac{1}{-\infty} =: 0 \\
	 \intertext{Sinnlos wäre:}
	 \infty - \infty, 0\cdot \infty, 0\cdot (-\infty), \frac{\infty}{\infty}, \ldots
	 \end{align*}
   - Damit könne wir die Rechenregeln auch für Folgen in $\hat{\mathbb{R}}$ formulieren
   - In $\hat{\mathbb{R}}$ hat jede Folge einen Häufungswert
   #+end_remark
   #+ATTR_LATEX: :options [2.23]
   #+begin_defn latex
   \label{defn:223}
   Sei $(a_n)_{n\in\mathbb{N}}$ ein Folge von reellen Zahlen, $\emptyset \neq H\subseteq \hat{\mathbb{R}}$ die Menge der Häufungswerte von $(a_n)$ in $\hat{\mathbb{R}}$. \\
   Dann sei:
   \begin{align*}
   \overline{\lim} a_n := \lim_{n\to\infty} \inf a_n := \inf H \tag{Limes inferior} \\
   \underline{\lim} a_n := \lim_{n\to\infty} \sup a_n := \inf H \tag{Limes superior}
   \end{align*}
   #+end_defn
   #+begin_remark latex
   \mbox{}
   1. Definition \ref{defn:223} kann man auch für $\mathbb{R}$ formulieren
   2. \[a = \lim_{n\to\infty} \inf a_n \iff \Forall \eps \begin{cases} \string(1\string) \{n \mid \abs{a - a_n} < \eps\} ~\text{ist unendlich (weil $a$ Häufungswert ist)} \\ \string(2\string) \{n \mid a_n < a - \eps\} ~\text{ist endlich ($a$ ist kleinste Häufungswert)}\end{cases}\]
   #+end_remark
   #+ATTR_LATEX: :options [2.24]
   #+begin_ex latex
   \begin{align*}
   a_n = n + (-1)^n n \\
   a_{2n + 1} = 0 \Forall n \implies 0 ~\text{ist Häufungswert} \\
   a_{2n} = 4n \to \infty \implies \infty~\text{ist Häufungswert}
   \intertext{also gilt}
   \lim_{n\to\infty} \inf a_n = 0 \\
   \lim_{n\to\infty} \sup a_n = \infty \\
   \end{align*}
   #+end_ex
   #+begin_remark latex
   \mbox{}
   - $a_n \to a$ in $\displaystyle \hat{\mathbb{R}} \iff \lim_{n\to\infty} \inf a_n = a = \lim_{n\to\infty}\sup a_n$
   - $\displaystyle \lim_{n\to\infty} \inf a_n + \lim_{n\to\infty}\inf b_n \leq \lim_{n\to\infty} \inf (a_n + b_n)$
   - $\displaystyle \lim_{n\to\infty} \inf a_n \cdot \lim_{n\to\infty}\inf b_n \leq \lim_{n\to\infty} \inf (a_n \cdot b_n)$ für $a_n,b_n > 0$
   - $\displaystyle \lim_{n\to\infty} \sup a_n + \lim_{n\to\infty}\sup b_n \geq \lim_{n\to\infty} (a_n + b_n)$ (zum Beispiel betrachte $a_n = n^2, b_n = \frac{1}{n}$)
   #+end_remark
