* Reihen (Unendliche Summen)
  #+ATTR_LATEX: :options [2.19]
  #+begin_defn latex
  Eine Reihe \[\sum_{k = 1}^\infty a_k\] (*unendliche Summe*) konvergiert, wenn die Folge ihrer *Partialsummen* konvergiert
  \[s_n = \sum_{k = 1}^n\xrightarrow{n\to\infty} S_\infty < \infty\]
  #+end_defn
  #+begin_ex latex
  \mbox{}
  1. $\displaystyle \sum_{k = 1}^n k = \frac{n(n + 1)}{n}\xrightarrow{n\to\infty} \infty$
  2. $\displaystyle S_n = \sum_{k = 1}^n (-1)^k = \begin{cases} -1 & n~\text{ungerade} \\ 0 & n~\text{gerade}\end{cases}$ S_n ($= -1, 0, -1, 0,\ldots$) konvergiert nicht
  3. $\displaystyle S_n = \sum_{j = 0}^n z^j = \frac{1 - z^{n + 1}}{1 - z}$ Für $\abs{z} < 1$ konvergiert $\displaystyle S_n \to \frac{1}{1 - z} \Rightarrow \sum_{j = 0}^\infty z^j = \frac{1}{1 - z}$
  4. Harmonische Reihe: Seien $\displaystyle S_n = \sum_{k = 1}^n \frac{1}{k}$, Behauptung $\displaystyle \lim_{n\to\infty} S_n = \infty$, also divergent
  #+end_ex
  #+ATTR_LATEX: :options [Beweis von 4.]
  #+begin_proof latex
  \begin{align*}
  S_{2^{n + 1}} = \sum_{k = 1}^{2^{n + 1}} \frac{1}{k} = 1 + \frac{1}{2} + \sum_{j = 1}^n \sum_{k = 2^j + 1}^{2^{j + 1}} \frac{1}{k} \geq 1 + \frac{1}{2} + \sum_{j = 1}^{n}\underbrace{\sum_{k = 2^j +1}^{2^{j + 1}}}_{\mathclap{2^j~\text{Summanden}}} \frac{1}{2^{j + 1}} \\
  = 1+ \frac{1}{2} + \sum_{j = 1}^n 2^{j} \frac{1}{2^{j + 1}} = 1 + \frac{1}{2} + \sum_{j = 1}^{n} \frac{1}{2} = 1 + \frac{1}{2} + \frac{1}{2}n \xrightarrow{n\to\infty} \infty
  \end{align*}
  #+end_proof
  #+begin_thm latex
  Seien $\displaystyle \sum_{k = 0}^\infty a_k , \sum_{k = 0}^\infty b_k$ konvergente Reihen, $\alpha \in \mathbb{R}$, dann sind auch die Reihen
  \[\sum_{k = 0}^\infty (a_k + b_k), \sum_{k = 0}^\infty \alpha a_k\]
  konvergent und es gilt
  \[\sum_{k = 0}^\infty (a_k + b_k) = \sum_{k = 0}^\infty a_k + \sum_{k = 0}^\infty b_k, \sum_{k = 0}^\infty \alpha a_k = \alpha \sum_{k = 0}^\infty a_k\]
  #+end_thm
  #+begin_proof latex
  Aus den Rechenregeln für konvergente Folgen
  #+end_proof
** Konvergenzkriterien
   Cauchy Kriterium für Paritalsummen besagt, dass eine Reihe genau dann konvergent ist, wenn
   \[\Forall \eps > 0 \Exists n_\eps \in \mathbb{N}: \Forall n > m \geq n_\eps: \abs{s_n - s_m} = \abs{\sum_{k = m + 1}^n a_k} < \eps\]

   #+ATTR_LATEX: :options [2.28 Reihenkonvergenz]
   #+begin_lemma latex
   Eine Reihe $\displaystyle \sum_{k = 1}^\infty a_k$ kann nur dann knvergent sein, wenn ihre Partialsummen beschränkt sind und ihre Glieder eine Nullfolge bilden
   #+end_lemma
   #+begin_proof latex
   Sei $\displaystyle s_\infty = \sum_{k = 1}^\infty a_k = \lim_{n \to \infty} s_n$. Dann gilt
   \[\lim_{n\to\infty} a_n = \lim_{n\to\infty} (s_n - s_{n - 1}) = \lim_{n\to\infty} s_n - \lim_{n\to\infty} s_{n - 1} = s_\infty - s_\infty = 0\]
   Die Beschränktheit der Paritalsummen folgt notwendig aus der Beschränktheit konvergenter Folgen.
   #+end_proof
   #+ATTR_LATEX: :options [2.29]
   #+begin_thm latex
   Sei $(a_k)_{k\in\mathbb{N}}$ eine Nullfolge. Dann $\displaystyle \sum_{k = 1}^\infty (a_k - a_{k + 1}) = a_1$
   #+end_thm
   #+begin_proof latex
   \[s_n = \sum_{k = 1}^n (a_k - a_{k + 1}) = \sum_{k = 1}^n a_k - \sum_{k = 2}^{n + 1} a_k = a_1 - a_{n + 1} \Rightarrow \abs{s_n - a_1} = \abs{a_{n + 1}} \xrightarrow{n\to\infty} 0\]
   #+end_proof
   #+ATTR_LATEX: :options [2.30]
   #+begin_ex latex
   \[\sum_{k = 1}^\infty \frac{1}{k(k + 1)} = \sum_{k = 1}^\infty (\underbrace{\frac{1}{k}}_{\mathclap{a_k}} - \underbrace{\frac{1}{k + 1}}_{\mathclap{a_{n + 1}}}) = a_1 = \frac{1}{2}\]
   #+end_ex
   #+ATTR_LATEX: :options [2.31]
   #+begin_defn latex
   Eine Reihe $\displaystyle s_\infty = \sum_{k = 1}^\infty a_k$ in $\mathbb{R}$ heißt alternierend, wenn ihre Elemente alternierende Vorzeichen haben, das heißt $a_n \cdot a_n + 1 \leq 0$
   #+end_defn
   #+ATTR_LATEX: :options [2.32]
   #+begin_thm latex
   1. Eine alternierende Reihe $\displaystyle s_\infty = \sum_{k = 1}^\infty a_k$ ist konvergent, wenn die Absolutbeträge ihrer Glieder eine monoton fallende Nullfolge bilden
   2. Für die Reihenreste gilt dabei die Abschätzung
	  \[\abs{\sum_{k = m}^\infty a_k} \leq \abs{a_m}\]
   #+end_thm
   #+begin_proof latex
   1. Sei ohne Beschränkung der Allgemeinheit $a_1 > 0$. Dannist $a_{2n - 1} + a_{2 n} \geq 0, a_{2n} + a_{2n + 1} \geq 0$
	  Und folglich
	  \begin{align*}
	  s_{2n + 1} = a_1 + a_2 + a_3 + \ldots + a_{2 n} + a_{2 n + 1} \leq s_{2n - 1} \leq \ldots \leq s_3 \leq s_1 \\
	  s_{2n} = (a_1) + (a_2 + a_4) + \ldots + (\underbrace{a_{2n - 1} + a_{2n}}_{\geq 0}) \geq s_{2n - 2} \geq \ldots \geq s_2 \\
	  \intertext{Ferner gilt}
	  s_{2n + 1} - s_{2 n} = a_{2n + 1} \geq 0
	  \intertext{und somit}
	  s_2 \leq \ldots \leq s_{2n} \leq s_{2n + 1} \leq \ldots \leq s_1
	  \intertext{$(S_{2n})$ monoton wachsend, $s_{2n + 1}$ monoton fallend, beide beschränkt}
	  \Rightarrow s_{2n} \xrightarrow{n\to\infty} s_\ast, \Rightarrow s_{2n + 1} \xrightarrow{n\to\infty} s^\ast \\
	  s_{sn} \leq s_\ast \leq s^\ast \leq s_{2n + 1} \\
	  \intertext{da $(a_n)$ Nullfolge}
	  \abs{s_{2n + 1} - s_{2 n}} = \abs{a_{2n + 1}} \to 0 \\
	  s_\ast = s^\ast = s_\infty
	  \end{align*}
   2. Aus 1. folgt $m = 2n + 1$
	  \[0 \leq s_\infty - s_{2n} = \sum_{k = 2n + 1}^\infty a_k = s_\infty - s_{2n + 1} + a_{2n + 1} \leq a_{2n + 1}\]
	  und sonst
	  \[\abs{\sum_{k = 2n + 1}^\infty a_k} \leq \abs{a_{2n + 1}}\]
	  Ana log im Fall $m = 2n$
   #+end_proof
   #+ATTR_LATEX: :options [2.33]
   #+begin_ex latex
   1. $\displaystyle s_\infty = \sum_{k = 1}^\infty \frac{(-1)^{k - 1}}{k} = 1 - \frac{1}{2} + \frac{1}{3} - \ldots$ konvergiert nach dem Leibnitz Kriterium
	  \[\abs{\frac{(-1)^{k - 1}}{k}} = \frac{1}{k} \to 0~\text{monoton}\]
   2. Die Leibnitz Reihe $\displaystyle s_\infty =  \sum_{k = 0}^\infty \frac{(-1)^k}{2k + 1} = 1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \ldots$ konverget nach Leibnitz Kriterium
   #+end_ex
   #+ATTR_LATEX: :options [Monotonie ist wichtig]
   #+begin_remark latex
   \[\sum_{k = 1}^\infty a_k~\text{mit}~ a_{2k} := -\frac{1}{2^k}, a_{2k - 1}:= \frac{1}{k}\]
   ist divertent:
   - $(1 - 1) + (1 - 1) + (1 - 1) + \ldots = 0$, aber
   - $1 + (-1 + 1) + (-1 + 1) + \ldots = 1$
   #+end_remark
   #+ATTR_LATEX: :options [2.34]
   #+begin_defn latex
   $\displaystyle \sum_{k = 1}^\infty a_k$ heißt absolut konvergent, genau dann wenn $\displaystyle \sum_{k = 1}^\infty \abs{a_k}$ konvergent ist
   #+end_defn
   #+ATTR_LATEX: :options [2.35]
   #+begin_thm latex
   Sei $\displaystyle \sum_{k = 1}^\infty \abs{a_k}$ konvergent in $\mathbb{R}$. Dann ist $\displaystyle \sum_{k = 1}^\infty a_k$ konvergent
   #+end_thm
   #+begin_proof latex
   Mit Cauchy Kriterium:
   \[\abs{\sum_{k = m}^n a_k} \leq \sum_{k = m}^n \abs{a_k} < \eps\]
   aus der Absolutkonverenz
   #+end_proof
   #+ATTR_LATEX: :options [2.36 Umordnungssatz]
   #+begin_thm latex
   Sei $\displaystyle \sum_{k = 1}^\infty a_k$ eine absolut konvergente Reihe in $\mathbb{R}$. Dann gilt
   für jede bijektive Abbildung $\tau: \mathbb{N} \to \mathbb{N}$
   \[\sum_{k = 1}^\infty a_{\tau(k)} = \sum_{k = 1}^\infty a_k\]
   #+end_thm
   #+begin_proof latex
   Ranacher für spezifische Umordung
   #+end_proof
   #+ATTR_LATEX: :options [2.37]
   #+begin_ex latex
   $\displaystyle \sum_{k = 1}^\infty \frac{(-1)^{k - 1}}{k}$ konvergent (aber nicht absolut) \\
   Behauptung: $\Exists$ Umordnung $\tau$, sodass $\displaystyle \sum_{k = 1}^\infty \frac{(-1)^{\tau(k) - 1}}{\tau(k)}$ divergiert
   Beachte
   \[\frac{1}{2^j + 1} + \frac{1}{2^j + 3} + \ldots + \frac{2\cdot 2^j - 1} \leq 2^{j - 1} \frac{1}{2^{j + 1}} = \frac{1}{4}\]
   \Rightarrow Die Umordung
   \[1 - \frac{1}{2} + \frac{1}{3} - \frac{1}{4} + (\frac{1}{5} + \frac{1}{7}) - \frac{1}{6} + \underbrace{(\frac{1}{9} + \frac{1}{11} + \frac{1}{13} + \frac{1}{15})}_{\geq \frac{1}{4} - \frac{1}{8} = \frac{1}{8}} - \frac{1}{8} + \ldots + \underbrace{(\frac{1}{2^j + 1} + \frac{1}{2^j + 3} + \ldots + \frac{1}{2^{j + 1} - 1})}_{> \frac{1}{4} - \frac{1}{8} = \frac{1}{8}} - \frac{1}{2^k + 2}\]
   konvergiert nicht
   #+end_ex
   #+ATTR_LATEX: :options [2.38 Cauchyprodukt für Reihen]
   #+begin_thm latex
   Seien $\displaystyle \sum_{k = 1}^\infty a_k, \sum_{k = 1}^\infty b_k$ absolut konvergente Reihen (in $\mathbb{R}$ oder $\mathbb{C}$). Sei $\displaystyle c_m = \sum_{k = 1}^m a_k b_{m-k}$. Dann konvergiert
   \[\sum_{m = 1}^\infty = (\sum_{k = 1}^\infty a_k)(\sum_{k = 1}^\infty b_k)\]
   (ohne Beweis)
   #+end_thm
   #+ATTR_LATEX: :options [2.39 Vergleichkriterium]
   #+begin_thm latex
   Gegeben seien zwei Reihen $\displaystyle s_\infty = \sum_{k = 1}^\infty a_k, \tilde s_\infty = \sum_{k = 1}^\infty \tilde a_k$
   1. Gilt für fast alle $k \in \mathbb{N}$ mit einer Konstante $\alpha > 0\quad \abs{a_k} \leq \alpha \tilde a_k$ \\
	  (für fast alle $n\in\mathbb{N} :=$ Für alle $n\in\mathbb{N}$ außer endlich viele) \\
	  so ist $\tilde s_\infty$ eine *Majorante* von $s_\infty$ und aus der absoluten Konvergenz von $\tilde s_\infty$ folgt auch die von $s_\infty$, absolute Divergenz von $s_\infty$ impliziert die absolute Divergenz von $\tilde s_\infty$
   #+end_thm
   #+begin_proof latex
   ohne Beschränkung der Allgemeinheit nehmen wir an, dass die Vorraussetzungen $\Forall k \in \mathbb{N}$ gelten
   1. Ist $\tilde s_\infty$ konvergent
	  \[\Rightarrow \sum_{k = 1}^{n}\abs{a_k} \leq \alpha \sum_{k = 1}^{n} \abs{\tilde a_k} \leq \alpha \sum_{k = 1}^{\infty} \tilde a_k, \Forall n\in\mathbb{N}\]
	  \Rightarrow S_n sind beschränkt, $S_\infty$ absolut konverent
	  Umgekehrt folgt aus Divergenz von $\tilde S_\infty$ auch $\sum_{k = 1}^{\infty} \abs{a_k} \to \infty \Rightarrow \tilde S_\infty$ auch Divergent
   2. Aus Vorraussetzung
	  \begin{align*}
	  \abs{\frac{a_{k + 1}}{\tilde a_{k + 1}}} \leq \abs{\frac{a_{k + 1}}{a_k}} \abs{\frac{a_k}{\tilde a_{k + 1}}} \leq \abs{\frac{\tilde a_{k + 1}}{\tilde a_k}} \abs{\frac{a_k}{\tilde a_{k + 1}}} = \abs{\frac{a_k}{\tilde a_k}} \leq \ldots \leq \abs{\frac{a_1}{\tilde a_1}} =: \alpha
	  \end{align*}
	  \Rightarrow $\abs{a_{k + 1}} \leq \alpha \abs{a_k}$. Aus 1. folgt die Aussage
   #+end_proof
   #+ATTR_LATEX: :options [2.34 Wurzelkriterium]
   #+begin_korollar latex
   Eine Reihe $\displaystyle \sum_{k = 1}^{\infty}a_k$ konvergiert absolut, wenn es ein $g\in (0,1)$ gibt, mit dem für f.a. (fast alle) $k\in \mathbb{n}$ gilt $\sqrt[k]{\abs{a_k}} \leq q \leq 1$,
   beziehungsweise $\lim_{k \to \infty} \sup \sqrt{\abs{a_k}} < 1$ \\
   Wenn für unendlich viele $k \in \mathbb{N}$ gilt $\sqrt[k]{\abs{a_k}} > 1$, beziehungsweise $\abs{a_k} > 1$, so ist die Reihe absolut divergent.
   #+end_korollar
   #+begin_proof latex
   Nach Vorraussetzung $\abs{a_k} \leq q^k$, das heißt die konvergierende geometrische Reihe $\tilde s_\infty$ mit $q\in(0,1)$ ist Majorante fpr $s_\infty$
   #+end_proof
   #+ATTR_LATEX: :options [2.41 Quotientenkriterium]
   #+begin_korollar latex
   Eine Reihe $\displaystyle \sum_{k = 0}^{\infty} a_k$ konvergiert absolut, wenn es ein $q\in (0,1)$ gibt mit dem für f.a. $k\in\mathbb{N}$ gilt
   \[\abs{\frac{a_{k + 1}}{a_k}} \leq q < 1, ~\text{bzw.}~ \lim_{k\to\infty} \sup \abs{\frac{a_{k + 1}}{a_k}} < 1\]
   Wenn für fast alle $k\in\mathbb{N}$ gilt $\displaystyle \abs{\frac{a_{k + 1}}{a_k}} \geq 1$, so ist die Reihe absolut divergent
   #+end_korollar
   #+begin_proof latex
   Vergleich mit
   \[\tilde s_\infty \sum_{k = 1}^{\infty}q^k\]
   #+end_proof
   #+ATTR_LATEX: :options [2.42]
   #+begin_ex latex
   \mbox{}
   1. $\displaystyle s_\infty \sum_{k = 1}^{\infty} \frac{z^k}{k!}, z\in\mathbb{C}$ \\
	  Qutientenkriterium: \[\abs{\frac{a_{k + 1}}{a_k}} = \abs{\frac{z^{k + 1}}{(k + 1)!} \frac{k!}{z^k}} = \abs{\frac{z}{k + 1}}\]
	  Sei $k \geq 2 \abs{z} \Rightarrow \abs{\frac{z}{k + 1}} \leq \frac{1}{2} \Rightarrow s_\infty$ absolut konvergent.
   2. $\displaystyle \sum_{k = 1}^{\infty} \frac{k!}{k^k}$
	  \[\abs{\frac{(k + 1)!}{(k + 1)^{k + 1}} \frac{k^k}{k!}} = \abs{\frac{k}{k + 1}}^k = \frac{1}{(1 + \frac{1}{k})^k} \leq \frac{1}{1 + k \frac{1}{k}} = \frac{1}{2}\]
	  $\Rightarrow s_\infty$ absolut konvergent
   #+end_ex
   #+begin_remark latex
   1. Falls $q = 1$ \Rightarrow die Kriterien geben keine Entscheidung, zum Beispiel:
	  \begin{align*}
	  \sum_{k = 1}^{\infty} \frac{1}{k} \vee \sum_{k = 1}^{\infty} \frac{1}{k^2} \\
	  \abs{\frac{a_{k + 1}}{a_k}} = \abs{\frac{k}{k + 1}} \to 1 \\
	  \abs{\frac{a_{k + 1}}{a_k}} = \frac{k^2}{(k + 1)^2} \to 1 \\
	  \end{align*}
   2. Für die Divergenz ist es wichtig, dass $\Exists n_0 \Forall n\geq n_0 a_n > 0$, Wir nehmen
	  \[a_n = \begin{cases} \frac{1}{n^2} & n = 2^k \\ 2(2^{-k})^2 & n - 1 = 2^k \\ 0\end{cases}\]
	  $\sum a_n$ konvergiert, aber $\lim_{a_n \neq 0} \frac{a_{n + 1}}{a_n} = 2$
   #+end_remark
   #+ATTR_LATEX: :options [2.43 Cauchy Verdichtungssatz]
   #+begin_lemma latex
   Eine Reihe $\displaystyle s_\infty = \sum_{k = 1}^{\infty} a_k$, mit $a_k \in \mathbb{R}_+$, die monoton fallende Nullfolge bilden hat dasselbe Konvergenzverhalten wie die verdichtete Reihe
   \[\sum_{k = 0}^{\infty} 2^k a_{2^k} = a_1 + 2 a_2 + 4 a_4 + 8 a_8 + \ldots\]
   #+end_lemma
   #+begin_proof latex
   Wir setzen $\displaystyle s_n := \sum_{k = 1}^{n} a_k, \tilde s_n := \sum_{k = 0}^{n} 2^k a_{2^k}$ \\
   Für $n < 2^{k + 1}$
   \[S_n = a_1 + (a_2 + a_3) + \ldots + (a_{2^k} + \ldots + a_{k^{k + 1} - 1}) \leq a_1 + 2 a_2 + 4 a_4 + \ldots + 2^k a_{2^k} = \tilde s_n\]
   \Rightarow Konvergenz von $\ilde s_k$ impliziert Konvergenz von $S_n$
   #+end_proof
