#+AUTHOR: Robin Heinemann
#+TITLE: Analysis II (Marciniak-Czochra)

#+INCLUDE: "../header.org" :minlevel 1
#+LATEX_HEADER:	\theoremsymbol{}
#+LATEX_HEADER: \theoremstyle{nonumberplain}
#+LATEX_HEADER: \renewtheorem{remark}{Bemerkung}
#+LATEX_HEADER: \theoremstyle{}
#+LATEX_HEADER: \renewtheorem*{ex*}{Beispiel}

#+INCLUDE: "metric_norm.org" :minlevel 1
#+INCLUDE: "differentiation.org" :minlevel 1
* Gewöhnliche Differentialgleichungen
  *Grundbegriffe* \\
  Zu einer gegebenen Funktion $f: ℝ\to ℝ$ suchen wir eine differenzierbare Funktion $x: ℝ \to ℝ$, deren Ableitung durch $f(·)$ beschrieben wird.
  Wir suchen also eine Funktion sodass
  \[\dd{}{t} x(t) = f(t) ∀ t ∈ ℝ\]
  *Bemerkung zur Notation* \\
  \begin{align*}
  x' &= f\\
  \dot x &= f
  \end{align*}
  #+begin_ex latex
  Für gegebene Geschwindigkeit (in Ableitung von Zeit) suchen wir die Position des Körpers auf einer festen eindimensionalen Achse.
  \[\dd{}{t} x(t) = f(t) ∀ t ∈ ℝ\]
  Wir müssen noch die Position zu irgendeinem Zeitpunkt kennen. Das heißt die Lösung ist nicht eindeutig solange wir keinen Wert $x(t_0) ∈ ℝ$ festlegen.
  Das Problem
  \begin{align*}
  \dd{}{t} x(t) &= f(t) \\
  x(t_0) &= x_0
  \end{align*}
  lässt sich lösen wenn $f: ℝ \to ℝ$ stetig ist. Dann besagt nämlich des Hauptsatz der Integralrechnung, dass
  \[x(·): ℝ \to ℝ, t \to x_0 + ∫_{t_0}^{t} f(s) \d s\]
  differenzierbar ist und die Ableitung $f(t)$ begrenzt ist.
  #+end_ex
  *Ziel*:
  - Existenz von Lösung
  - Eindeutigkeit von Lösung
  - Verhalten
  #+begin_ex latex
  \[\dd{x}{t} = r x\]
  $r$: Konstante. In $t_0 = 0: x(0) = x_0$
  \begin{align*}
  x(·) &= c · e^{rt} \\
  x_0 &= x(0) = c \\
  ⇒ x(t) &= x_0 e^{rt}
  \end{align*}
  #+end_ex
  #+begin_defn latex
  Gegeben sei eine nicht leere Teilmenge $D ⊂ ℝ × ℝ^m$ und eine Funktion $f: D \to ℝ^m$. Dann nennt man
  \[x' = f(·, x)\]
  eine explizite Gewöhnliche Differenzialgleichung (GDGL)(ODE - ordinary differential equation) 1. Ordnung.
  Im Fall $m = 0$ wird die Gleichung als *Skalar* bezeichnet. Eine solche Differentialgleichung heißt *autonom* falls $f$ nicht explizit von $t$ abhängt (sonst: *nichtautonom*).
  Für $m > 1$ bekommen wir ein System von Gewöhnlichen Differentialgleichungen. Eine Funktion $x: I \to ℝ^m, I ⊂ ℝ$, heißt eine Lösung der Differentialgleichung, wenn
  1. $∀ t ∈ R ⊂ ℝ$ liegt $(t, x(t)) ∈ D$
  2. $x(·)$ ist differenzierbar, das heißt
	 \[∀t ∈ I ∃ x'(t) = \lim_{\substack{h \to 0\\ t + h ∈ I}} \frac{x(t + h) - x(t)}{h} ∈ ℝ^m\]
  3. $∀ t ∈ I$ gilt $x'(t) = f(t, x(t))$
  Bei *Anfangswertproblemen* zu dieser Gewöhnlichen Differentialgleichung ist noch ein Tupel $(t_0, x_0) ∈ D$ gegeben und gesucht ist eine Funktion die Bedingungen 1. bis 3. und $x(t_0) = x_0$ erfüllt.
  #+end_defn
  *Konstruktion von Lösungen* \\
  *Geometrische Interpretation*: Eine skalare Gleichung $x' = f(t, x)$ bestimmt ein *Richtungsfeld*, das heißt $∀ (t, x) ∈ ℝ^2$ wird durch $x' = f(t, x)$ eine *Steigung* gegeben. Gesucht sind
  $x(t)$ deren Graph $G(x) =\{(t, x)\}$ in jedem Punkt die vorgegebene Steigung hat. In einfachen Fällen kann mit aus ihrem Richtungsfeld die mögliche Lösung ergeben.
  \begin{tikzpicture}
  \begin{axis}[title={$x' = x$},domain=-2:2,view={0}{90},axis background/.style={fill=white}]
  \addplot3 [gray,quiver={u={1},v={x},scale arrows=0.15},-stealth,samples=15] {0.5*x^2};
  \end{axis}
  \end{tikzpicture}
  \begin{tikzpicture}
  \begin{axis}[title={$x' = 1 / x$},domain=0:2,view={0}{90},axis background/.style={fill=white}]
  \addplot3 [gray,quiver={u={1},v={1/x},scale arrows=0.15},-stealth,samples=15] {ln(x)};
  \end{axis}
  \end{tikzpicture}
  \begin{tikzpicture}
  \begin{axis}[title={$x' = x / t$},domain=-2:2,view={0}{90},axis background/.style={fill=white}]
  \addplot3 [gray,quiver={u={1},v={y/x},scale arrows=0.15},-stealth,samples=15] {x};
  \end{axis}
  \end{tikzpicture}
  *Methode der Trennung der Variablen* \\
  Wir betrachten die separable Differentialgleichung
  \[x' = f(x, t) = a(t) g(x)\]
  Sei $x$ einen Lösung. Falls $g(t) \neq 0$ bekommen wir
  \[∫_{t_0}^t \frac{x'(s)}{g(x(s))} \d s = ∫_{t_0}^t a(s) \d s\]
  Mit Hilfe der Substitution $z := x(s)$ ergibt sich (mit $\dd{z}{x} = x'(s)$)
  \[∫_{x_0}^{x(t)} \frac{1}{g(z)} \d z = ∫_{t_0}^{t} a(s) \d s\]
  #+ATTR_LATEX: :options [3.4]
  #+begin_ex latex
  \[\begin{cases} x' = x^2 \\ x(t_0) = x_0 \end{cases}\]
  \begin{align*}
  ∫_{x_0}^{x(t)} \frac{\d z}{z^2} &= ∫_{t_0}^{t} 1 \d s \\
  -\frac{1}{z} \big|_{x_0}^{x(t)} &= t - t_0 \\
  t - t_0 &= \frac{1}{x_0} - \frac{1}{x(t)} \\
  x(t) &= \frac{x_0}{1 - x_0(t - t_0)}
  \end{align*}
  Falls $t_0 = 0, x(0) = 1$:
  \[x(t) = \frac{1}{1 - t}\]
  \begin{tikzpicture}
  \begin{axis}[domain=0.8:1.2,axis background/.style={fill=white},restrict y to domain=0:80]
  \addplot[samples=100] {1 / (1 - x)};
  \end{axis}
  \end{tikzpicture}
  
  Dies ist keine *globale* ($∀t ∈ ℝ_+$) Lösung, da man $x(t)$ nicht nach $t = t^{\ast}$ fortsetzen kann.
  #+end_ex
  *Methode der Variation die Konstanten* \\
  Wir betrachten Differentialgleichung $x' = a(t) x(t) + b(t), t ∈ I = [t_0, t_0 + τ] ⊂ ℝ$
  mit stetigen Funktionen $a, b: I \to ℝ$
  Die zugehörige homogene Differentialgleichung $y' = ay$ hat eine Lösung die Form
  \[y(t) = c \exp ∫_{t_0}^{t} a(s) \d s, \quad c ∈ ℝ\]
  (Seperation der Variablen). Sei $y(t)$ eine Lösung mit $c = 1$.
  Zur Bestimmung einer Lösung der *inhomogenen Differentialgleichung* wird $c$ als Funktion von $t$ angesetzt.
  Ansatz: $x(t) = c(t) y(t)$
  \begin{align*}
  ⇒ x'(t) &= c'(t) y(t) + c(t) y'(t) \\
  &= c'(t) \exp ∫_{t_0}^{t} a(s) \d s + a(t) x(t) \\
  &\overset{?}{=} a(t) x(t) + b(t) ⇔ c'(t)\exp(∫_{t_0}^{t} a(x) \d s) = b(t)
  \end{align*}
  Wir bekommen
  \[c(t) = ∫_{t_0}^{t} \exp(-∫_{t_0}^τ a(s) \d s) b(τ) \d τ + r\]
  mit einer freien Konstanten $r ∈ ℝ$. Damit wird
  \[x(t) = \exp(∫_{t_0}^{t} a(s) \d s)∫_{t_0}^t \exp(-∫_{t_0}^t a(s) \d s) b(τ) \d τ + r \exp(∫_{t_0}^{t} a(s) \d s)\]
  Durch die Wahl der Konstanten $r = x_0$ ergibt sich $x(t_0) = x_0$
  \[⇒ x(t) = \exp(∫_{t_0}^t a(s) \d s)[x_0 + ∫_{t_0}^t \exp(-∫_{t_0}^τ a(s) \d s) b(τ) \d τ]\]
  #+begin_ex latex
  \[x' = a x(t) + b(t), \quad x(0) = x_0\]
  $a$: Konstante
  \[⇒ x(t) = x_0 e^{at} + ∫_{t_0}^{t} e^{a(t - τ)} b(τ) \d τ\]
  \[(c(t) e^{at})' = c' e^{at} + c e^{at} a = a e^{at} + b\]
  \begin{align*}
  ⇒ c' &= b(t) e^{-at} \\
  c(t) &= ∫_{t_0}^{t} b(τ) e^{-aτ} \d τ \\
  x(t) &= x_0 e^{at} + c(t) e^{at}
  \end{align*}
  #+end_ex
  *Anfangswertproblem* \\
  \begin{align*}
  x' &= f(t, x) \\
  x(0) &= x_0
  \end{align*}
  *Existenzsatz von Peano* \\
  #+ATTR_LATEX: :options [Peano]
  #+begin_thm latex
  Die Funktion $f(t, x)$ sei *stetig* auf einem Zylinder
  \[D = \{(t, x) ∈ ℝ^1 × ℝ^m \mid \abs{t - t_0} \leq α, \norm{x - x_0} \leq β\}\]
  Dann existiert eine Lösung $x(t)$ auf dem Intervall $I := [t_0 - T, t_0 + T]$ wobei
  \[T := \min(α, \frac{β}{M}), \quad M := \max_{(t, x) ∈ D} \norm{f(t, x)}\]
  #+end_thm
  #+begin_proof latex
  Mit Hilfe der Differenzenmethode konstruieren wir eine Folge von stückweise linearer Funktionen, welche eine Teilfolge besitzt, die (gleichmäßig) gegen eine Lösung des Anfangswertproblems konvergiert.
  Ohne Beschränkung der Allgemeinheit genügt es das Halbintervall $I = [t_0, t_0 + T]$ zu betrachten. Zu einem Schrittweitenparameter $h > 0$ wird eine äquidistante Unterteilung des $I$ gewählt.
  \[t_0 < \dots < t_N = t_0 + T\qquad h = t_n - t_{n - 1}\]
  Ausgehend von $x_0^h := x_0$ erzeugt dann das sogenannte Eulersche Polygonzugverfahren Werte für $x_n^h$ durch
  \[x_n^h = x_{n - 1}^h + h f(t_{n - 1}, x_{n - 1}^h), n \geq 0\]
  Diese diskreten Funktionswirte wirden linear interpoliert zu einer stetigen Funktion:
  \[x_n^h(t) := x_{n - 1}^h + (t - t_{n - 1}) f(t_{n - 1}, x_{n - 1}^h)\]
  *Schritt 1*: Wir zeigen Graph $(x^n) ⊂ D$. \\
  Sei $(t, x^h(t)) ∈ D$ für $t_0 \leq t \leq t_{k - 1}$. Es gilt
  \[(x(t)^h)' = f(t_{k - 1}, x_{k - 1}^k), t ∈ [t_{k - 1}, t_k]\]
  Nach Konstruktion gilt dann für $t ∈ [t_{k - 1}, t_k]$
  \begin{align*}
  x^h(t) - x_0 = x^h(t) - x_{k - 1}^h + \sum_{i = 1}^{k - 1}(x_i^h - x_{i - 1}^h) \\
  &= (t - t_{k - 1})f(t_{k - 1}, x_{k - 1}^h) + h \sum_{i = 1}^{k - 1}f(t_{i - 1}, x_{i - 1}^h) \\
  ⇒ \norm{x^h(t) - x_0} &\leq (t - t_{k - 1})M + (t_{k - 1} - t_0)M = (t - t_0)M
  \end{align*}
  Also $(t, x^h(t)) ∈ D$ für $0 \leq t \leq t_k$ \\
  *Schritt 2*: Wir zeigen gleichgradige Stetigkeit \\
  Seien dazu $t, \tilde t ∈ I, \tilde t \leq t$ mit $t ∈ [t_{k - 1}, t_k], \tilde t ∈ [t_{j - 1}, t_j]$ für gewisse $t_j \leq t_k$. Im Fall $t, \tilde t ∈ [t_{k - 1}, t_k]$ gilt
  \begin{align*}
  x^h(t) - x^h(\tilde t) &= (t - \tilde t)f(t_{k - 1}, x^h (t_{k - 1})) \\
  ⇒ \norm{x^h(t) - x^h(\tilde t)} &\leq M(t - \tilde T) \\
  \end{align*}
  Für $t_j < t_k$
  \begin{align*}
  x^h(t) - x^h(\tilde t) &= (t - t_{k - 1})f(t_{k - 1}, x_{k - 1}^h) + h \sum_{i = j}^{k - 1}f(t_{i - 1}, x_{i - 1}^h) + (t_{j - 1} - \tilde t) f(t_{j - 1}, x_{j - 1}^h) \\
  &= (t - t_{k - 1})f(t_{k - 1}, x_{k - 1}^h) + h \sum_{i = j + 1}^{k - 1} f(t_{i - 1}, x_{i - 1}^h) + (h + t_{j - 1} - \tilde t) f(t_{j - 1}, x_{j - 1}^h) \\
  ⇒ \norm{x^h(t) - x^h(\tilde t)} &\leq M((t - t_{k - 1}) + (t_{k - 1} - t_j) + (t_j - \tilde t)) \leq M \abs{t - \tilde t}
  \end{align*}
  Also $x^h_{h > 0}$ gleichgradig stetig. Die Funktionen sind auch gleichmäßig beschränkt:
  \[\norm{x^h(t)} \leq \norm{x^h(t) - x_0} + \norm{x_0} \leq MT + \norm{x_0}, t ∈ (t_0, t_0 + T)\]
  Arzela-Ascoli Satz: $∃$ eine Nullfolge $(h_i)_{i ∈ ℕ}$ und stetiges $x(t)$ sodass
  \[\norm{x^{h_i}(t) - x(t)} \xrightarrow{i \to ∞} 0\]
  und Graph $(x) ⊂ D$
  #+end_proof
