* Das Lebesque Integral
** Inhalte von Mengen in $ℝ^n$
   Die Idee ist einen "Inhalt" ("Masse") von Mengen zu definieren, sodass
   - $\abs{M} \geq 0$ \hfill (Positivität)
   - $\abs{M} = \abs{M'}$ falls $M$ und $M'$ isometrisch (durch Abstandserhaltende Transformation) sind. \hfill (Bewegungsinvarianz)
   - $M ∩ N = \emptyset ⇒ \abs{M ∪ N} = \abs{M} + \abs{N}$
   In $ℝ^1$ oder $ℝ^2$ können wir $∀ M ⊂ ℝ^2$ einen "Inhalt" mit solchen Eigenschaften zuordnen (Banach), aber nicht in $ℝ^3$ (Hausdorff)
   Wir beginnen mit $n$ -dimensionalen (abgeschlossenen) Intervallen $I := I_1 × \dots × I_n$, wobei $I_i = [a_1, b_i], i = 1, \dots, n, a_i < b_i, a_i, b_i ∈ ℝ$.
   \[\abs{I} := \prod_{i = 1}^n (b_i - a_i)\]
   Für Intervallsummen $S$ mit einer nicht überlappenden Darstellung
   \[S = ∪_{k = 1, \dots, m} I_k\]
   ist der Inhalt
   \[\abs{S} := \sum_{k = 1}^{n} \abs{I_k}\]
   #+ATTR_LATEX: :options [Jordan-Inhalt und Nullmengen]
   #+begin_defn latex
   1. Für *beschränkte* (nicht leere) Mengen $M ⊂ ℝ^n$ sind der inneren Inhalt $\abs{M}_i$ und der äußere Inhalt $\abs{M}_a$ definiert durch
	  \[\abs{M}_i := \sup_{S ⊂ M} \abs{S} \leq \inf_{M ⊂ S} \abs{S} =: \abs{M}_a, \qquad \abs{\emptyset}_i = \abs{\emptyset}_a = 00\]
	  Im Fall $\abs{M}_a = \abs{M}_i =: M$ heißt die Menge quadrierbar (messbar) im Jordanischen Sinne mit sogenanntem Jordan Inhalt.
   2. Mengen $M ⊂ ℝ^n$ mit $\abs{M}_a = 0$ werden Jordan-Nullmengen genannt
   #+end_defn
   #+ATTR_LATEX: :options [Äußeres Lebesque-Maß]
   #+begin_defn latex
   Das *äußere Lebesque-Maß* einer Menge $A ⊂ ℝ^n$ ist definiert durch
   \[μ^{\ast}(A) := \inf\{\sum_{i} \abs{I_i}, A ⊂ ∪_i I_i\}\]
   Die Menge darf auch unbeschränkt sein und dann $μ^{\ast}(A) = ∞$. Wir setzen $μ^{\ast}(\emptyset) = 0$
   #+end_defn
   Wir werden hie die Arithmetik von $\bar ℝ := ℝ ∪ \{π\}$ nutzen ($a + ∞ := ∞, a · ∞ := ∞ ∀ a ∈ \bar ℝ, 0 · ∞ := 0$)
   #+begin_remark latex
   $∞ - ∞$ ist undefiniert.
   #+end_remark
   Das Lebesque Integral wird mit Hilfe von Ober- und Untersummen bezüglich endlicher oder abzählbar unendlicher Zerlegungen definiert.
   Wir benötigen noch Regeln für Reihen in $\bar ℝ$. Für $0 \leq a_k \leq ∞$ ist
   \[S_∞= \sum_{k = 1}^{∞} a_k\]
   wohldefiniert mit $S_∞ := ∞$ falls die Reihe divergent ist oder ein $a_k = ∞$. Für $λ ∈ \bar ℝ$ gilt
   \[\sum_{k = 1}^{π} λ a_k = λ \sum_{k = 1}^{∞} a_k\]
   Außerdem
   \[\sum_{i,j = 1}^{∞} a_{ij} = \sum_{i = 1}^{π} \sum_{j = 1}^{∞} a_{ij} = \sum_{j = 1}^{∞} \sum_{i = 1}^{∞} a_{ij}\]
   sofern eine der Reihen absolut konvergent.
   #+begin_remark latex
   Das äußere Lebesque-Maß:
   \[0 \leq μ^{\ast}(A) \leq ∞, μ^{\ast}(\{a\}) = 0\]
   #+end_remark
   #+begin_lemma latex
   Für das äußere Lebesque-Maß gelten die folgenden Aussagen
   1. Aus $A ⊂ B$ folgt $μ^{\ast}(A) \leq μ^{\ast}(B)$ \hfill (Monotonie)
   2. Für endliche oder abzählbare Mengenfolgen $(A_i)_i$ gilt
	  \[μ^{\ast} (∪_i A_i) \leq \sum_{i} μ^{\ast} (A_i)\]
	  (Subadditivität)
   3. Für beschränkte Mengen ist
	  \[\abs{A}_i \leq μ^{\ast}(A) \leq \abs{A}_a\]
	  das heißt für Jordan-quadrierbare Mengen ist $μ^{\ast}(A) = \abs{A}$.
   4. Das äußere Lebesque-Maß ist Bewegungsinvariant gegenüber Translationen und Drehungen
   #+end_lemma
   #+begin_proof latex
   1. Da im Fall $A ⊂ B$ jede Intervallüberdeckung von $B$ auch eine solche von $A$ ist, folgt aus der Definiton
	  \[μ^{\ast}(A) \leq μ^{\ast}(B)\]
   2. Wir nehmen an, dass die rechte Seite in der Ungleichung ist (sonst nichts weiter zu beweisen). Es sei $ε > 0$ vorgegeben und eine Folge $(ε_i)_i$ positiver Zahlen mit
	  $ε = \sum_i ε_i$. Dann $∀ i ∈ ℕ ∃ (I_{ij})_j$ mit $A_i ⊂ ∪_j I_{ij}$
	  \[\sum_{j} \abs{I_{ij}} \leq μ^{\ast}(A_i) + ε_i\]
	  Die Doppelfolge $I_{ij}$ überdeckt die Menge $A = ∪_i A_i$
	  \[⇒ μ^{\ast}(A) \leq \sum_{i,j} \abs{I_{ij}} \leq \sum_{i} (μ^{\ast}(A_i) + ε_i) = \sum_{i} μ^{\ast}(A_i) + ε\]
   3. Der äußere Jordan-Inhalt von $A$ ist definiert als das Infimum des Inhalts aller endlichen Intervall-Überdeckungen von $A$. Beim Lebesque-Maß	sind allgemeine abzählbare Überdeckungen zugelassen
	  $⇒ μ^{\ast}(A) \leq \abs{A}_a$
	  Jetzt zeigen wir $∀$ endlich abgeschlossenen
	  \[S = ∪_{i = 1}^m I_i\]
	  gilt $\abs{S} \leq μ^{\ast}(S)$. Dazu geben wir ein $ε > 0$ mit $ε = \sum ε_i$ (mit $ε_i$ > 0) vor und wählen eine abzählbare Überdeckung
	  \[∪_i I_i \supset S, \sum_{i} \abs{I_i} \leq μ^{\ast}(S) + ε\]
	  $∀ I_i$ wählen wir $J_i$, sodass $\abs{J_i} > \abs{I_i} ∧ \abs{J_i} \leq \abs{I_i} + e_i$. Dann ist
	  $(J_i)_i$ eine offene Überdeckung der kompakten Menge $S$ und nach dem Satz von Heine Borel wird $S$ bereits von endlich vielen der $J_i$ überdeckt
	  \[S ⊂ ∪_{i = 1}^m J_m\]
   4. Die Invarianz von $μ^{\ast}(x)$ gegenüber Translation folgt, da diese Intervalle bei Translation in solche mit demselben Inhalt überführen. Sei $S$ eine Drehung ($S$ eine orthogonale $n × n$ Matrix)
	  Aus $A ⊂ ∪_i I_i ⇒ S(A) ∈ ∪_i S(I_i)$ mit 1., 2. und Bewegungsinvatianz von Jordan Inhalt (zeigen wir später) bekommer wir
	  \[μ^{\ast}(S(A)) \leq \sum_{i} μ^{\ast}(S(I)) = \sum_{i} \abs{S(I_i)} = \sum_{i} \abs{I_i}\]
	  Da die überdeckende Intervallsumme beliebig ist, folgt
	  \[μ^{\ast}(A) \geq μ^{\ast}(S(A))\]
	  Dasselbe gilt auch für die transponierte $S^T$
	  \[⇒ μ^{\ast}(S(A)) \geq μ^{\ast}(S^T S(A)) = μ^{\ast}(A) ⇒ μ^{\ast}(S(A)) = μ^{\ast}(A)\]
   #+end_proof
   #+ATTR_LATEX: :options [Lebesque Nullmenge]
   #+begin_defn latex
   Eine Menge $A ⊂ ℝ^n$ mit äußerem Lebesque-Maß $μ^{\ast}(A) = 0$ wird (Lebesque) Nullmenge genannt. Gibt es eine Aussage
   von $A$ bis auf die aus einer Nullmenge, sagen wir, dass sie "fast überall" in $A$ gilt.
   #+end_defn
   #+begin_lemma latex
   Die Vereinigung von abzählbar vielen Lebesque-Nullmengen ist wieder eine Lebesque-Nullmenge. Insbesondere sind abzählbare Menge Lebesque-Nullmengen
   #+end_lemma
   #+begin_proof latex
   Aus der Subadditivität.
   #+end_proof
   #+begin_remark latex
   Das Konzept ist allgemeiner als bei Jordan-Inhalten, wo nur endliche Intervall-Überdeckung zugelassen wird.
   - $ℚ^n$ ist eine Lebesque-Nullmenge in $ℝ^n$
   - $ℝ^{n - i}$ iste eine Lebesque-Nullmenge in $ℝ^n$
   - Die endliche Mengen in $ℝ^n$ sind Jordan-Nullmengen
   - Für abzählbare Menge kann es der Fall sei (zum Beispiel für jede konvergente Folge $(x_k)_{k ∈ ℕ}$ in $ℝ^n$, die Menge $M = \{x_k, k ∈ ℕ\}$ Jordan-Nullmenge ist)
	 Im Allgemeinen ist dies nicht der Fall	(zum Beispiel $M = ℚ^n ∩ [0, 1]^n ⊂ ℝ^n$), $\abs{M}_a = 1$, Aber $μ^{\ast}(M) = 0$: Für beliebiges $ε > 0$ ist jeder Punkt $x_k$
	 in einem Würfel $I_k$ mit $\abs{I_k} = ε^{-nk}$
	 \[⇒ μ^{\ast}(A) \leq \sum_{k = 1}^{∞} \abs{I_k} = \sum_{k = 1}^{∞} ε 2^{-nk} = \frac{ε}{1 - 2^n} ⇒ μ^{\ast}(A) = 0\]
   #+end_remark
   #+begin_remark latex
   $μ^{\ast}$ ist nicht $σ$ -additiv auf allen Mengen in $ℝ^n$. Dafür brauchen wir eine geeignete Klasse von Mengen in $ℝ^n$.
   #+end_remark
   #+ATTR_LATEX: :options [Mengenalgebra]
   #+begin_defn latex
   DIe nicht-leere Teilmenge $\mathcal{A} ⊂ \mathcal{P}(X)$ heißt Albebrag auf $X$, wenn sie $X$ und $\emptyset$ enthält und wenn mit $A, B ∈ \mathcal{A}$ auf $A \setminus B, A ∪ B, A ∩ B ∈ \mathcal{A}$ sind.
   Sie heißt $σ$ -Algebra, wenn sie zusätzlich mit $A_i ∈ \mathcal{A}, i ∈ ℕ$ auch
   \[∪_{i ∈ ℕ} A_i, ∩_{i ∈ ℕ} A_i ∈ \mathcal{A}\]
   sind.
   #+end_defn
   #+begin_ex latex
   1. $\mathcal{A} = \{\emptyset, X\}$ die kleinste $σ$ -Algebra für eine Menge $X$, $\mathcal{A} = \mathcal{P}(X)$ ist die größte $σ$ -Alebrag auf $X$
   2. Für eine Menge $X$ und Teilmenge $A ⊂ X$ ist
	  \[\mathcal{A} = \{\emptyset, X, A, A^C = X \setminus A\}\]
	  die kleinste $σ$ -Algebra, die $A$ enthält
   3. Für $X = ℝ^n$ heißt die kleinste $σ$ -Algebra welche die alle offene und abgeschlossene Teilmengen enthält die *Borelsche $σ$ -Algebra*.
   4. Ist $X ⊂ ℝ^n$ eine Jordan-quadrierbare Menge, so ist die Menge der Jordan-quadrierbaren Teilmengen von $X$ eine Algebra, aber keine $σ$ -Algebra
   5. Die Lebesque-Nullmengen in $ℝ^n$ und ihre Komplemente bilden eine $σ$ -Algebra (nicht in dem Fall von Jordan-Nullmengen)
   #+end_ex
   #+begin_lemma latex
   Eine (nicht-leere) Teilmenge $\mathcal{A} ⊂ \mathcal{P}(X)$ ist bereits eine Algebra, wenn die folgenden Bedingungen erfült sind
   1. Mit $A ∈ \mathcal{A}$ ist $A^C = X \setminus A ∈ \mathcal{A}$
   2. Mit $A, B ∈ \mathcal{A}, A ∪ B ∈ \mathcal{A}$
   Es ist eine $σ$ -Algebra, wenn zusätzlich gilt:
   3. [@3] Für beliebige, paarweise disjunkte Mengen $A_i ∈ \mathcal{A}_i, i ∈ ℕ$ ist
	  \[∪_{i ∈ ℕ} A_i ∈ \mathcal{A}\]
   #+end_lemma
   #+begin_proof latex
   Wir müssen zeigen, dass für $\mathcal{A} ⊂ \mathcal{P}(X), X, \emptyset ∈ \mathcal{A}$ und $B, C ∈ \mathcal{A}$ auch $A \setminus B, A ∩ B ∈ \mathcal{A}$.
   Da $\mathcal{A}$ nicht leer ist $∃$ ein $A ∈ \mathcal{A}$ und folglich
   \[X = (X\setminus A) ∪ A = A^C ∪ A ∈ \mathcal{A}\]
   sowie $X^C = \emptyset ∈ \mathcal{A}$. Mit $A, B ∈ \mathcal{A}$ ist $A^C, B^C ∈ \mathcal{A}$
   \[⇒ A ∩ B = (A^C ∪ B^C) ∈ \mathcal{A}\]
   und folglich auch $A \setminus B = A ∩ B^C ∈ \mathcal{A}$. Für die $σ$ -Algebra muss zusätzlich $∩_{i ∈ ℕ} A_i ∈ \mathcal{A}$. Für $A_i ∈ \mathcal{A}, i ∈ ℕ$ gilt die disjunkte Darstellung
   \[∪_{i ∈ ℕ} A_i = ∪_{i ∈ ℕ} A_i\]
   \[B_1 := A_1, B_2 := A_2 \setminus A_1, \dots, B_j = A_j \setminus ∪_{i = 1}^{j - 1} A_i\]
   alle $B_i ∈ \mathcal{A}$ sowit
   \[∪_{i ∈ ℕ} A_i = ∪_{i ∈ ℕ} B_i ∈ \mathcal{A}, ∩_{i ∈ ℕ} A_i = (∩_{i ∈ ℕ} A_i^C)^C ∈ \mathcal{A}\]
   #+end_proof
** Abbildungen von Mengen
   Frage: In wie weit erhält die Abbildung $ϕ: ℝ^n \to ℝ^n$ Eigenschaften von Mengen (zum Beispiel offen, quadrierbar)?
   #+begin_lemma latex
   Sei $D ⊂ ℝ^n$ (nicht leer) beschränkt und $ϕ: D \to ℝ^n$ eine Lipschitzstetige Abbildung. Dann gilt
   \[\abs{ϕ(D)}_a \leq α \abs{D}_a, α_i= (L \sqrt{n})^n\]
   $L$: Lipschitz-Konstante.
   #+end_lemma
   (ohne Beweis)
   #+begin_thm latex
<<<<<<< HEAD
   Sei $D ⊂ ℝ^n$ (nicht leer) offen und quadrierbar. Die Abbildung $ϕ: \bar D \to ℝ^n$ sein in $\bar D$ Lipschitzstetig und in $D$ regulär, das heißt stetig differenzierbar mit $\det ϕ'(x) \neq 0$.
=======
   Sei $D ⊂ ℝ^n$ (nicht leer) offen und quadrirbar. Die Abbildung $ϕ: \bar D \to ℝ^n$ sein in $\bar D$ Lipschitzstetig und in $D$ regulär, das heißt stetig differenzierbar beziehungsweise $\det ϕ'(x) \neq 0$.
>>>>>>> 28344d773c12a7a243ad8045350acc84fb4bcaa4
   1. Die Bildmenge $ϕ(D)$ ist offen und quadrierbar, und es ist
	  \begin{align*}
	  \overline{ϕ(D)} &= ϕ(\bar D) \\
	  \partial ϕ(D) &⊂ ϕ(\partial D)
      \end{align*}
   2. Ist $ϕ$ in $D$ injektiv, so gilt $\partial ϕ(D) = ϕ(\partial D)$. Ferner ist für jede quadrierbare Teilmenge $A ⊂ \bar D$ auch die Bildmenge $ϕ(A)$ quadrierbar.
   #+end_thm
   #+begin_proof latex
   Das Bild $ϕ(D)$ der offenen Menge $D$ unter der regulären Abbildung $""$ ist offen (folgt aus Umkehr Funktions Satz). Aus der Stetigkeit von $ϕ$ ist das Bild $ϕ(\bar D)$ der beschränkten, abgeschlossenen
   Menge $\bar D$ abgeschlossen. $⇒ \overline{θ(D)} ⊂ ϕ(\bar D)$, da $\overline{ϕ(D)}$ die kleinste abgeschlossene Menge von $ϕ(D)$ ist.
   \[⇒ \partial ϕ(D) = \bar ϕ(D) \setminus ϕ(D) ⊂ ϕ(\bar D) \setminus ϕ(D) ⊂ ϕ(\partial D)\]
   Da $D$ quadrierbar ist, muss $\abs{\partial D}_a = 0$. Nach Lemma 4.9 $\abs{ϕ(\partial D)}_a = 0$
   und damit $\abs{\partial ϕ(D)}_a = 0$. $ϕ(D)$ ist also quadrierbar. Zu $x ∈ \bar D$ gibt es eine Folge $(x_k)_{k ∈ ℕ}$ in $D$ mit $x = \lim_{k \to ∞} x_k$. $ϕ(x) = \lim_{k \to ∞} ϕ(x_k)$.
   Dies und $\overline{ϕ(D) ⊂ ϕ(\bar D)} ⇒ \overline{ϕ(D)} = ϕ(\bar D)$. \\
   Sei nun $ϕ$ zusatzlich injektiv auf $Di$. Wir nehmen $x ∈ \partial D$ und eine Folge $(x_k)_{k ∈ ℕ}$ in $D$ mit $x = \lim_{k \to ∞} x_k$ und $ϕ(x) = \lim_{k \to ∞} ϕ(x_k)$. Wir zeigen, dass
   $ϕ(x) ∈ \partial ϕ(D)$. Wäre $ϕ(x) ∈ ϕ(D)$, dass heißt es gäbe $\tilde x ∈ D$ mit $ϕ(x) = ϕ(\tilde x)$. $⇒$ Wegen der Offenheit von $ϕ(D)$ eine Umgebung
   $V(ϕ(x)) ⊂ ϕ(D)$ und eine Umgebung $U(\tilde x) ⊂ D$ mit $ϕ(U(\tilde x)) = V(ϕ(x))$. Wegen $\lim_{k \to ∞} x_k = x ∈ \partial D$ ist dann aber $x_k \dot ∈ U(\tilde x)$ für hinreichund graßes $k$.
   $⇒ ϕ(x_k) \not ∈ V(ϕ(x))$ \lightning zu $ϕ(\tilde x) = ϕ(x) = \lim_{k \to ∞} ϕ(x_k)$. Zusammen mit $\partial ϕ(D) ⊂ ϕ(\partial D) ⇒ \partial ϕ(D) = ϕ(\partial D)$.
   Sei $A ⊂ D$ quadrierbar. Dann ist auch das Innere $A^0 = A \setminus \partial A$ quadrierbar und mit dem vorherigen Argument, dass $ϕ(A)$ quadrierbar ist.
   Wegen $A \setminus A^0 ⊂ \partial A$ ist $A \setminus A^0$ eine Nullmenge $⇒ ϕ(A \setminus A^0)$ eine Nullmenge $⇒ ϕ(A) = ϕ(A^0) ∪ ϕ(A \setminus A^0)$ quadrierbar.
   #+end_proof
   #+ATTR_LATEX: :options [4.11]
   #+begin_lemma latex
   Sei $D ⊂ ℝ^n$ nicht leer und $ϕ:D \to ℝ^n$ eine Lipschitzstetige Abbildung. Dann besitzt $ϕ$ eine Lipschitzstetige Fortsetzung $\bar ϕ: \bar D \to ℝ^n$ mit
   $\bar ϕ\big|_D = ϕ$.
   #+end_lemma
   #+begin_proof latex
   Sei $x ∈ \bar D$ mit $x = \lim_{k \to ∞} x_k, x_k ∈ D$. Aus Lipschitzstetigkeit von $ϕ$ aus $D$
   \[⇒ \norm{ϕ(x_k) - ϕ(x_i)} \leq L \norm{x_k - x_i}\]
   das heißt $(ϕ(x_k))_{k ∈ ℕ}$ ist eine Cauchy-Folge. Sei $y = \lim ϕ(x_k)$ im Falle $x \to ∈ D$ setzen wir $\overline{ϕ(x)} := y$. Dadurch wird eine Punktion $\bar ϕ: \bar D \to ℝ^n$ definiert.
   Die Definition ist eindeutig, da für zweite Folge $(ξ_k)_{~ ∈ ℕ}$ mit $x = \lim_{k \to ∞} ξ_k$, die $ϕ(ξ_k) \to y$ wegen
   \[\norm{ϕ(x_k) - ϕ(ξ_k)} \leq L \norm{x_k - ξ_k}\]
   Für $x ∈ D$ ist $\overline{ϕ(x)} = ϕ(x)$. Seinen $x, ξ ∈ \bar D$ und $(x_k)_{k ∈ ℕ}, (ξ_k)_{k ∈ ℕ}$ die Approximationen in $D$
   \[⇒ \norm{\bar ϕ(x) - \bar ϕ(ξ)} = \lim_{k \to ∞} \norm{\bar ϕ(x_k) - \bar ϕ(ξ_k)} \leq L \lim_{k \to ∞} \norm{x_k - ξ_k} = L\norm{x - ξ}\]
   $⇒ \bar ϕ$ ist Lipschitzstetig mit derselben Lipschitzkonstante wie $ϕ$.
   #+end_proof
   #+begin_thm latex
   Es sei $D ⊂ ℝ^n$ eine quadrierbare Menge und $A ∈ ℝ^{n × n}$ eine Matrix und $b ∈ ℝ^n$ ein Vektor. Damit ist auch $ϕ(D) ⊂ ℝ^n$ mit $ϕ(x) := A x + b$ (affin-lineare Abbildung) quadrierbar und $\abs{ϕ(D)} = \abs{\det A} \abs{D}$
   #+end_thm
   #+begin_proof latex
   1. $ϕ(x) = x + b$. Hier $\abs{ϕ(s)} = \abs{s}$. Ferner ist $A ⊂ B ⊂ C$ äquivalent zu $ϕ(A) ⊂ ϕ(B) ⊂ ϕ(C)$. Also $∀ D ⊂ ℝ^n$ quadrierbar gilt
	  \[\abs{ϕ(D)}_i = \lim_{k \to ∞} \abs{ϕ(D_k)} = \lim_{k \to ∞} \abs{D_k} = \abs{D}_i = \abs{D}_a = \lim_{k \to ∞} \abs{D^k} = \lim_{k \to ∞} \abs{ϕ(D^k)} = \abs{ϕ(D)}_a\]
	  wobei
      - $D_k := ∪ \{W ∈ W_k \mid W ⊂ D\}$
	  - $D^k := ∪ \{W ∈ W_k \mid W ∩ D \neq \emptyset\}$
	  Für beschränkte Menge
	  \[\abs{D}_i = \lim_{k \to ∞} \abs{D_k}, \abs{D}_a = \lim_{k \to ∞} \abs{D^k}\]
   2. Sei $\det A \neq 0$, das heißt $A$ gibt eine bijektive Abbildung. Bild $ϕ(W)$ einses Würfels $W$ ist quadrierbar (Satz 4.10). Sei $W_1$ der Einheitswürfel $\abs{W_1} = 1$ und
	  $α := \abs{ϕ(W_1)}$. $∀ W = r W_1 + b$ gilt
	  \[\abs{ϕ(W)} = \abs{ϕ(r W_1)} = r^n \abs{ϕ(W_1)} = α r^n \abs{W_1} = α \abs{W}\]
	  Ähnlich für beliebige Würfelsummen.
      \begin{align*}
      \abs{ϕ(D^k)} &= α \abs{D^k} \\
      \abs{ϕ(D_k)} &= α \abs{D_k}
      \end{align*}
      $W$ Aus
      \[ϕ(D_k) ⊂ ϕ(D) ⊂ ϕ(D^k) ⇒ α (D_k) = \abs{ϕ(D_k)} \leq \abs{ϕ(D)}_i \leq \abs{ϕ(D)}_a \leq α \abs{D^k}\]
      $⇒ α \abs{D} = \abs{ϕ(D)}$. Um zu zeige, dass $α = \det A$ nutzen wir $A = Q_1 Λ Q_2$, wobei $Q_1, Q_2$ ortonormal, und $Λ = \diag(λ_1, \dots, λ_n)$ mit $λ_1 > 0$.
      Da
      \[\abs{\det A} = \abs{\det(Q_1 Λ Q_2)} = \abs{λ_1 · \dots · λ_n}\]
      und
      \[\abs{ϕ K_1(0)} = \abs{λ_1 \dots λ_n} \abs{Q_2(K)} = \abs{λ_1 \dots λ_n} \abs{K}\]
      $K_1$: Einheitskugel. Im Fall $\det A = 0$, die beschränkte Mengen $ϕ(D)$ sind Nullmengen.
   #+end_proof
