* Lineare Abbildungen
  In diesem Kapitel sei $K$ stets ein Körper, $U, V, W$ stets ein $K$ -VR.
  #+ATTR_LATEX: :options [12.1 Lineare Abbildung]
  #+begin_defn latex
  $f: V\to W$ Abbildung. $f$ heißt $K$ -lineare Abbildung (Homomorphismus von K-VR, kurz lineare Abbildung) $\xleftrightarrow{\text{Def.}}$ Die folgende Bedingungen sind erfüllt:
  - (L1) $f(u + v) = f(u) + f(v) \Forall u,v\in V$
  - (L1) $f(\lambda v) = \lambda f(v) \Forall u,v\in V \Forall w\in V, \lambda \in K$
  #+end_defn
  #+ATTR_LATEX: :options [12.2]
  #+begin_ex latex
  1. $A = (a_{i,j}) \in M(m\times n, K)$. Wir schreiben die Elemente von $K^n$ als Spaltenvektoren und betrachten die Abbildung:
	 \[\tilde A : K^n \to K^m, x = \cvec{x_1; \vdots; x_n} \mapsto Ax\]
	 Es gilt für $u,v \in K^n, \lambda \in K:$
	 \begin{gather*}
	 \tilde A(u + v) = A(u + v) = Au + Av = \tilde A(u) + \tilde A(v) \\
	 \tilde A(\lambda v) = A(\lambda v) = \lambda (A v) = \lambda \tilde A(v)
	 \end{gather*}
	 Wegen $\tilde A(e_i) = A e_i = \cvec{a_{i1} ; \vdots ; a_{in}}$ stehen in den Spalten von $A$ genau die Bilder der kanonischen Basisvektoren $e_1, \ldots e_n$ von $K^n$ unter $\tilde A$.
	 Sind $A\in M(m\times n, K), B\in M(n\times r, K), x\in K^r$, dann ist
	 \[\reallywidetilde{AB} (x) = (AB)(x) = A(B(x)) = A \tilde B(x) = \tilde A(\tilde B(x)) = (\tilde A \tilde B)(x)\]
	 das heißt die Verknüpfung von $\tilde A, \tilde B$ entspricht der Multiplikation der Matrizen $A,B: \tilde A \cdot \tilde B = \reallywidetilde{AB}$
  2. Wir betrachten die Abbildung \[f: \mathbb{R}^2 \to \mathbb{R}^2, \cvec{x_1; x_2} \mapsto \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}\cvec{x_1; x_2} = \cvec{x_1; -x_2}\]
	 Diese ist linear nach 1., beschreibt Spiegelung an der $x_1$ -Achse.
  3. Sei $V = \{f: (0,1)\to \mathbb{R}\mid f~\text{ist differenzierbar}\}$ (ist ein $\mathbb{R}$ -VR)
	 \[\prime: V\to \{g:(0,1) \to \mathbb{R} ~\text{Abb}\}, f\mapsto f'\]
	 ist eine lineare Abbildung, denn es gilt für $f,g \in V, \lambda \in\mathbb{R}$:
	 \begin{align*}
	 \string(f + g\string)' &= f' + g' \\
	 \string(\lambda f\string)' &= \lambda f'
	 \end{align*}
  #+end_ex
  #+ATTR_LATEX: :options [12.3]
  #+begin_remark latex
  $f: V\to W$ lineare Abbildung. Dann gilt:
  1. $f(0) = 0$
  2. $f(\lambda_1 v_1 + \ldots + \lambda_n v_n) = \lambda_1 f(v_1) + \ldots + \lambda_n f(v_n) \Forall v_1, \ldots v_n \in V, \lambda_1,\ldots\lambda_n \in K$
  3. $V'\subseteq V$ UVR $\implies f(V') \subseteq W$ ist UVR
  4. $W'\subseteq W$ UVR $\implies f^{1}(W') \subseteq V$ ist UVR
  5. $(v_i)_{i\in I}$ linear abhängige Familie in $V \implies (f(v_i))_{i\in I}$ linear abhängige Familie in $W$
  6. $V' = \Lin((v_i)_{i\in I}) \implies f(V') = \Lin((f(v_i))_{i\in I})$
  7. $W$ endlich dimensional $\implies f(V)$ endlich dimensionaler UVR von $W$ mit $\dim f(V) \leq \sim W$
  #+end_remark
  #+begin_proof latex
  1. $f(0) * f(0 + 0) = f(0) + f(0) \implies f(0) = 0$
  2. $f(\lambda_1 v_1 + \ldots + \lambda_n v_n) = f(\lambda_1 v_1) + \ldots + f(\lambda_n v_n) = \lambda_1 f(v_1) + \ldots \lambda_n f(v_n)$
  3. Sei $V' \subseteq V$ UVR. \\
	 Behauptung: $F(V') \subseteq W$ ist UVR denn:
	 - (U1): $0 \in V' \implies f(0) \in f(V')$
	 - (U2): Seien $w_1, w_2 \in f(V') \implies \Exists v_1, v_2 \in V': w_1 = f(v_1), v_2 = f(v_2)$
	   \[\implies w_1 + w_2 = f(v_1) + f(v_2) = f(\underbrace{v_1 + v_2}_{\in V'}) \in f(V')\]
	 - (U3): Sei $\lambda \in K, w\in f(V') \implies \Exists v\in V': w = f(v)$
	   \[\implies \lambda w = \lambda f(v) = f(\underbrace{\lambda v}_{\in V'} \in f(V'))\]
  4. Sei $W'\subseteq W$ UVR. \\
	 Behauptung: $f^{-1}(w') \subseteq V$ ist UVR, denn
	 - (U1): $f(0) = 0 \in W' \implies 0 \in f^{-1}(W')$
	 - (U2): Seien $v_1, v_2\in f^{-1}(w')$:
	   \[\implies f(v_1), f(v_2) \in W' \implies f(v_1 + v_2) = f(v_1) + f(v_2) \in W' \implies v_1 + v_2 \in f^{-1}(W')\]
	 - (U3): Sei $\lambda \in K, v\in f^{-1}(W')$:
	   \[\implies f(v) \in W' \implies f(\lambda v) = \lambda f(v) \in W' \implies \lambda v \in f^{-1}(W')\]
  5. Sei $(v_i)_{i\in I}$ linear abhängig
	 \begin{align*}
	 &\implies \Exists r\in \mathbb{N}, i_1, \ldots, i_r \in I, \lambda_{i_1}, \lambda_{i_r} \in K: (\lambda_{i_1}, \ldots, \lambda_{i_r}) \neq (0, \ldots, 0) \wedge \lambda_{i_1} v_{i_1} + \ldots + \lambda_{i_r} v_{i_r} = 0 \\
	 &\implies 0 = f(0) = f(\lambda_{i_1} v_{i_1} + \ldots + \lambda_{i_r} v_{i_r}) = \lambda_{i_1} f(v_{i_1}) + \ldots + \lambda_{i_1} f(v_{i_1}) \\
	 &\implies (f(v_i))_{i\in I} ~\text{linear abhängig}
	 \end{align*}
  6. zu zeigen: $V' = \Lin((v_i)_{i\in I}) \implies f(V') = \Lin((f(v_i))_{i\in I})$ \\
	 "$\subseteq$" Sei $w \in f(V') \implies \Exists v\in V': w = f(v)$. wegen $V'$ = $\Lin((v_i)_{i\in I})$:
	 \begin{align*}
	 &\Exists i_1, \ldots, i_r \in I, \lambda_{i_1}, \ldots, \lambda_{i_r} \in K: v = \lambda_{i_1} v_{i_1} + \ldots + \lambda_{i_r} v_{i_r} \\
	 &\implies f(v) = \lambda_{i_1} f(v_{i_1}) + \ldots + \lambda_{i_r} f(v_{i_r}) \in \Lin((f(v_i))_{i\in I})
	 \end{align*}
	 "$\supseteq$" Sei $w\in \Lin((f(v_i))_{i\in I}) \implies \Exists i_1, \ldots, i_r \in I, \lambda_{i_1}, \ldots, \lambda_{i_r} \in K$ mit
	 \[w = \lambda_{i_1} f(v_{i_1}) + \ldots + \lambda_{i_r} f(v_{i_r}) = f(\lambda_{i_1} v_{i_1} + \ldots + \lambda_{i_r} v_{i_r}) \in f(V')\]
  7. $f(V)$ ist UVR von $W$ nach 3. Rest aus Eigenschaften von $\dim$.
  #+end_proof
  #+ATTR_LATEX: :options [12.4 Verknüpfung von Linearen Abbildungen]
  #+begin_remark latex
  $f:V \to W, g: U\to V$ lineare Abbildungen. Dann ist $f\circ g: U\to W$ ebenfalls eine lineare
  Abbildung.
  #+end_remark
  #+begin_proof latex
  \begin{align*}
  \intertext{(L1): Seien $u_1, u_2 \in U$}
  \implies (f\circ g)(u_1 + u_2) &= f(g(u_1 + u_2)) = f(g(u_1) + g(u_2)) \\
  &= f(g(u_1)) + f(g(u_2)) = (f\circ g)(u_1) + (f\circ g)(u_2)
  \intertext{(L2:) Seien $u\in U, \lambda\in K$}
  \implies (f\circ g)(\lambda u) &= f(g(\lambda u)) = f(\lambda g(u)) \\
  &= \lambda f(g(u)) = \lambda(f\circ g)(u)
  \end{align*}
  #+end_proof
  #+ATTR_LATEX: :options [12.5]
  #+begin_defn latex
  \[\Hom_K(V, W) := \{f: V\to W \mid f~\text{ist $K$ -linear}\}\]
  Eine $K$ -lineare Abbildung $f:V \to V$ heißt ein *Endomorphismus* von $V$.
  \[\End_K(V):= \{f: V\to V\mid f~\text{ist Endomorphismus}\} = \Hom_K(V,V)\]
  #+end_defn
  #+ATTR_LATEX: :options [12.6]
  #+begin_remark latex
  Es gilt:
  1. $\Hom_K(V,W)$ ist bezüglich
	 - $+: \Hom_K(V,W)\times\Hom_K(V,W) \to \Hom_K(V,W), (f,g)\mapsto f + g$ \\
	   mit $(f + g)(v):= f(v) + g(v)$ für $v\in V$
	 - $\cdot : D\times \Hom_K(V,W) \to \Hom_k(V,W), (\lambda, f) \mapsto \lambda f$ \\
	   mit $(\lambda f)(c) := \lambda f(v)$ für $v\in V$
	 ein K-Vektorraum. Nullvektor ist die Nullabbildung. $0: V\to W$ mit $0(v) = 0$
  2. $\End_k(V)$ ist bezüglich
	 - $+: \End_K(V)\times \End_K(V)\to \End_K(V), (f,g) \mapsto f + g$
	 - $\circ: \End_K(V) \times \End_K(V) \to \End_K(V), (f,g)\mapsto f\circ g$
	 ein Ring, Einselement ist $\id_V$
  #+end_remark
  #+begin_proof latex
  Nachrechnen.
  #+end_proof
  #+ATTR_LATEX: :options [12.7]
  #+begin_defn latex
  Eine bijektive $K$ -lineare Abbildung $f:V\to W$ heißt ein *Isomorphismus* von $V$ nach $W$.
  Eine bijektive $K$ -lineare Abbildung $f:V\to V$ heißt *Automorphismus* von $V$.
  \begin{align*}
  \Iso_K(V,W) := \{f:V\to W\mid f~\text{ist ein Isomorphismus}\} \\
  \Aut_K(V):= \{f:V\to V\mid f~\text{ist ein Automorphismus}\} = \Iso_K(V,V)
  \end{align*}
  #+end_defn
  #+ATTR_LATEX: :options [12.8]
  #+begin_remark latex
  $f: V\to W$ lineare Abbildung. Dann gilt: Ist $f$ ein Isomorphismus, dann ist auch $f^{-1}: W\to V$
  ein Isomorphismus. Existiert zwischen $V$ und $W$ ein Isomorphismus, dann nennen wir $V,W$ isomorph.
  (Notation: $V \cong W$)
  #+end_remark
  #+begin_proof latex
  analog zu 5.23c.
  #+end_proof
  #+ATTR_LATEX: :options [12.9]
  #+begin_defn latex
  $f:V\to W$ lineare Abbildung. \\
  $\im f:= f(V)$ heißt das Bild von $f$ \\
  $\ker f:= f^{-1}({0}) = \{v\in V\mid f(v) = 0\}$ heißt der Kern von $f$
  #+end_defn
  #+ATTR_LATEX: :options [12.10]
  #+begin_remark latex
  $f:V\to W$ lineare Abbildung. Dann gilt:
  1. $\im f \subseteq W \wedge \ker f\subseteq V$ sind UVR
  2. $f$ surjektiv $\iff \im f = W$
  3. $f$ injektiv $\iff \ker f = \{0\}$
  4. $f$ injektiv $\wedge (v_i)_{i\in I}$ linear unabhängige Familie in $V \implies ((f(v_i))_{i\in I})$ ist linear unabhängig
  #+end_remark
  #+begin_proof latex
  1. folgt aus 12.3 3.,4.
  2. klar
  3. "$\implies$" sei $f$ injektiv zu zeigen: $\ker f = \{0\}$
	 - "$\subseteq$" Sei $a\in \ker f\implies f(a) = 0 = f(0) \implies a = 0$
	 - "$\supseteq$" $f(0) = 0 \implies 0 \in \ker f$
	 "$\impliedby$" Sei $\ker f = \{0\}$ zu zeigen: $f$ ist injektiv.
	 Seien $v_1, v_2 \in V, f(v_1) = f(v_2) \implies f(v_1 - v_2) = f(v_1) - f(v_2) = 0 \implies v_1 - v_2 \in \ker f = \{0\} \implies v_1 - v_2 = 0 \implies v_1 = v_2$
  4. Sei $f$ injektiv, $(v_i)_{i\in I}$ linear unabhängige Familie in $V$ zu zeigen: $((f(v_i))_{i\in I})$ linear unabhängig.
	 Seien $i_1,\ldots, i_r \in I, \lambda_{i_1}, \ldots, \lambda_{i_r} \in K, \lambda_{i_1}f(v_{i_1}) + \ldots + \lambda_{i_r}f(v_{i_r}) = 0$
	 \begin{align*}
	 &\implies f(\underbrace{\lambda_{i_1}v_{i_1} + \ldots + \lambda_{i_r}v_{i_r}}_{\in \ker f = \{0\}~\text{wegen $f$ injektiv}}) = 0 \implies \lambda_{i_1}v_{i_1} + \ldots + \lambda_{i_r}v_{i_r} = 0 \\
	 &\implies \lambda_{i_1} = \ldots = \lambda_{i_r} = 0
	 \end{align*}
  #+end_proof
  #+ATTR_LATEX: :options [12.11]
  #+begin_defn latex
  $f:V\to W$ lineare Abbildung.
  \[\Rang(f) := \dim(\im f)\]
  heißt der Rang von $f$
  #+end_defn
  #+ATTR_LATEX: :options [12.12]
  #+begin_defn latex
  $A\in M(m\times n, K)$. Wir betrachten die zu $A$ gehörende lineare Abbildung $\tilde A: K^n \to K^m, x\mapsto Ax$.
  Wegen $K^n = \Lin((e_1, \ldots, e_n))$ aus 12.3 5.:
  \[\im \tilde A = \Lin((\tilde A(e_1), \ldots, \tilde A(e_n)))\]
  Nach 12.2 1. sind $\tilde A(e_1), \ldots, \tilde A(e_n)$ genau die Spalten von $A$, das heißt:
  \[\Rang(\tilde A) = \dim (\im \tilde A) = \dim SR(A) = ~\text{Spaltenrang}(A)\]
  Wir setzen $\Rang(A) := \Rang(\tilde A) = ~\text{Spaltenrang}(A)$
  #+end_defn
  #+ATTR_LATEX: :options [Dimensionsformel für lineare Abbildungen]
  #+begin_thm latex
  $V$ endlichdimensionaler $K$ -Vektorraum, $f:V\to W$ lineare Abbildung.
  $(v_1, \ldots, v_k)$ Basis von $\ker f$, $(w_1, \ldots, w_r)$ Basis von $\im f$
  (beachte $\im f$ endlichdimensional wegen 12.3 5.). Für $i = 1, \ldots r$ sei $u_i \in V$ mit
  $f(u_i) = w_i$. Dann ist
  \[\mathcal{A}:= (u_1, \ldots, u_r, v_1, \ldots v_k)\]
  eine Basis von $V$. Insbesondere ist $\dim V = \dim (\ker f) + \dim(\im f)$
  #+end_thm
  #+begin_proof latex
  1. $\mathcal{A}$ ist ein ES von $V$:
	 \begin{align*}
	 \intertext{Sei $v\in V$}
	 &\implies f(v) \in \im f \implies \Exists \mu_1, \ldots, \mu_r \in K: f(v) = \mu_1 w_1 + \ldots + \mu_r w_r \\
	 \intertext{Setze $u:= \mu_1 u_1 + \ldots + \mu_r u_r$, dann ist}
	 f(u) &= \mu_1 f(u_1) + \ldots + \mu_r f(u_r) = \mu_1 w_1 + \ldots + \mu_r w_r = f(v) \\
	 &\implies f(u - v) = 0 \implies u - v \in \ker f \\
	 &\Exists \lambda_1 + \ldots + \lambda_k \in K: u - v = \lambda_1 v_1 + \ldots + \lambda_k v_k \\
	 &\implies v = -\lambda_1 v_1 - \ldots - \lambda_k v_k + \mu_1 u_1 + \ldots + \mu_r u_r \in \Lin((v_1, \ldots, v_k, u_1, \ldots, u_r))
	 \end{align*}
  2. $\mathcal{A}$ ist linear unabhängig:
	 \begin{align*}
	 \intertext{Seien $\mu_1, \ldots, \mu_r, \lambda_1, \ldots, \lambda_k \in K$ mit}
	 &\mu_1 u_1 + \ldots + \mu_r u_r + \lambda_1 v_1 + \ldots + \lambda_k v_k = 0 \\
	 &\implies \mu_1 f(u_1) + \ldots + \mu_r f(u_r) + \lambda_1 f(v_1) + \ldots + \lambda_k f(v_k) = 0 \\
	 &\implies \mu_1 w_1 + \ldots + \mu_r w_r = 0 \implies \mu_1 = \ldots = \mu_r = 0 \\
	 &\implies \lambda_1 v_1 + \ldots + \lambda_k v_k = 0 \implies \lambda_1 = \ldots = \lambda_k = 0
	 \end{align*}
	 $\implies \mathcal{A}$ ist linear unabhängig.
  #+end_proof
  #+ATTR_LATEX: :options [12.14]
  #+begin_conc latex
  $V,W$ endlichdimensionale K-Vektorräume. Dann sind äquivalent
  1. $V\cong W$
  2. $\dim V = \dim W$
  #+end_conc
  #+begin_proof latex
  1. $\implies$ 2. Sei $V\cong W$, das heißt $\Exists f: V \to W: f$ isomorph. Sei $(v_1, \ldots, v_r)$ eine Basis von $V$.
	 Wegen $f$ injektiv folgt aus 12.10: $(f(v_1), \ldots, f(v_r))$ linear unabhängig. Wegen $f$
	 surjektiv ist $W = f(V) = \Lin((f(v_1), \ldots, f(v_r))) \implies (f(v_1), \ldots, f(v_r))$ ist eine
	 Basis von $W$. $\implies \dim W = r = \dim V$.
  2. $\implies$ 1. Sei $\dim V = \dim W =: r$. Sei $(v_1, \ldots, v_r)$ Basis von $V, (w_1, \ldots, w_r)$ Basis von $W$.
	 Wir definieren $f: V\to W, \lambda_1 v_1 + \ldots + \lambda_r v_r \mapsto \lambda_1 w_1 + \ldots + \lambda_r w_r$
	 - $f$ wohldefiniert, da $(v_1, \ldots, v_r)$ Basis von $V$ ist
	 - $f$ ist linear, denn: Seien $u,v \in V$, etwa $u = \lambda_1 u_1 + \ldots + \lambda_r u_r, v = \mu_1 v_1 + \ldots + \mu_r v_r$
	   $\implies f(u + v) = f((\lambda_1 + \mu_1) v_1 + \ldots + (\lambda_r + \mu_r) v_r) = (\lambda_1 + \mu_1)w_1 + \ldots + (\lambda_r + \mu_r) w_r = \lambda_1 w_r + \ldots + \lambda_r w_r + \mu_1 w_1 + \ldots + \mu_r w_r = f(u) + f(v)$
	   Für $\lambda \in K$ ist $f(\lambda v) = f(\lambda \mu_1 v_1 + \ldots + \lambda \mu_r v_r) = \lambda \mu_1 w_1 + \ldots + \lambda\mu_r w_r = \lambda f(v)$
	 - Es ist $\im f = \Lin((w_1, \ldots, w_r)) = W$, das heißt $f$ ist surjektiv
	 - $f$ ist injektiv, denn $\dim V = \dim (\ker f) + \underbrace{\dim (\im f)}_{= \dim W = \dim V} \implies \dim (\ker f) = 0 \implies \ker f = \{0\}$, das
	   heißt $f$ injektiv.
  #+end_proof
  #+ATTR_LATEX: :options [12.15]
  #+begin_conc latex
  $n,m \in \mathbb{N}$. Dann gilt: $K^n \cong K^m \iff n = m$.
  #+end_conc
  #+ATTR_LATEX: :options [12.16]
  #+begin_conc latex
  $V$ endlich dimensionaler K-Vektorraum. Dann gilt:
  \[\Exists n\in\mathbb{N}_0: V\cong K^n\]
  #+end_conc
  #+begin_proof latex
  Setze $n:= \dim V$
  #+end_proof
  #+ATTR_LATEX: :options [12.17]
  #+begin_conc latex
  $V,W$ endlich dimensionale K-Vektorraum mit $\dim V = \dim W, f:V\to W$ lineare Abbildung. Dann sind äquivalent:
  1. $f$ injektiv
  2. $f$ surjektiv
  3. $f$ bijektiv
  #+end_conc
  #+begin_proof latex
  1. $\implies$ 2. Sei $f$ injektiv $\implies \ker f = \{0\}$, also $\dim (\ker f) = 0$.
	 Wegen $\dim V = \underbrace{\dim (\ker f)}_{= 0} + \dim (\im f) \implies \dim (\im f) = \dim V = \dim W \implies \im f = W$, das heißt $f$ surjektiv.
  2. $\implies$ 3. Sei $f$ surjektiv $\implies \dim (\ker f) = \dim(V) - \dim(\underbrace{\im f}_{= W}) = \dim V - \dim W = 0 \implies \ker f = \{0\} \implies f$ injektiv $\implies f$ bijektiv
  3. $\implies$ 1. klar
  #+end_proof
