* Basis und Dimension
  In diesem Abschnitt sei $V$ stets ein K-VR
  #+ATTR_LATEX: :options [9.1]
  #+begin_defn latex
  $(v_i)_{i\in I}$ Familie von Vektoren aus $V$. $(v_i)_{i\i I}$ heißt *Erzeugendessystem* (ES) von $V \xLeftrightarrow{Def} V = \Lin((v_i)_{i\in I})$ \\
  $V$ heißt *endlich erzeugt* $\xLeftrightarrow{\text{Def}} V$ besitzt ein endliches Erzeugendessystem (das heißt es existiert eine endliche Familie $(v_1, \ldots, v_n)$ von Vektoren aus $V$ mit $V = \Lin((v_1, \ldots, v_n))$) \\
  $(v_i)_{i\in I}$ heißt *Basis* von $V \xLeftrightarrow{\text{Def}} (v_i)_{i\in I}$ ist linear unabhängiges Erzeugendessystem von $V$ \\
  Ist $\mathcal{B} = (v_1, \ldots, v_n)$ eine endliche Basis von $V$, dann heißt $n$ die *Länge* von $\mathcal{B}$
  +end_defn
  #+ATTR_LATEX: :options [9.2]
  #+begin_ex latex
  1. Die Familie $(e_1, \ldots, e_n)$ ist eine Basis des K_VR $K^n$, da $\Lin((e_1, \ldots, e_n)) = K^n$ (vergleiche 8.10.2) und somit $(e_1,\ldots, e_n)$ Erzeugendessystem des $K^n$, und $(e_1, \ldots, e_n)$ linear unabhängig nach 8.15.1.
	 Die Länge der Basis ist $(e_1, \ldots, e_n)$ ist $n$. $(e_1, \ldots, e_n)$ heißt die kanonische Basis oder Standardbasis der $K^n$.
  2. Die Familie $(t^n)_{n\in\mathbb{N}_0}$ ist eine Basis der K-VR $K[t]$, denn: $\Lin((t^n)_{n\in\mathbb{N}_0}) = K[t]$ nach 8.12, $(t^n)_{n\in\mathbb{N}_0}$ ist linear unabhängig nach 8.15.3
  3. $((1, -1), (0,2), (1,2))$ ist ein Erzeugendessystem des $\mathbb{R}$-VR $\mathbb{R}^2$, denn für jedes $(x_1, x_2) \in \mathbb{R}^2$ ist $(x_1, x_2) = x_1(1, -1) + \frac{x_1 + x_2}{e}(0,2)\in \Lin((1,-1, (0,2), (1,2))$,
	 $((1, -1), (0,2), (1,2))$ ist jedoch keine Basis des $\mathbb{R}$, da linear abhängig nach 8.15.2
  4. Die leere Familie $()$ ist eine Basis des Nullraums $\{0\}$: vergleiche 8.11 und Annahme nach 8.14
  #+end_ex
  #+ATTR_LATEX: :options
  #+begin_note latex
  Jeder Vektorraum $V$ besitzt ein ES, denn es ist $V = \Lin((v)_{v \in V})$ \\
  Spannende Frage: Besitzt jeder VR eine Basis? \\
  Wir werden das zunächst für den Fall endlich erzeugter Vektorräqume untersuchen
  #+end_note
  #+ATTR_LATEX: :options [9.3]
  #+begin_thm latex
  $V \neq \{0\}, \mathcal{B} = (v_1, \ldots, v_n)$ endliche Familie von Vektoren aus $V$, dann sind äquivalent:
  1. $\mathcal{B}$ ist eine Basis von $V$, das heißt eine linear unabhängiges ES von $V$
  2. $\mathcal{B}$ ist ein unverkürzbares ES von $V$, das heißt $\mathcal{B}$ ist ein ES und für jedes $r\in\{1,\ldots,n\}$ ist $(v_1, \ldots, v_{r - 1}, v_{r + 1}, \ldots, v_n)$ kein ES von $V$ mehr.
  3. Zu jedem $v\in V$ gibt es eindeutig bestimmte $\lambda_1, \ldots, \lambda_n \in K$ mit
	 \[v = \lambda_1 v_1 + \ldots + \lambda_v v_n\]
  4. $\mathcal{B}$ ist unverlängerbar linear unabhängig, das heißt $\mathcal{B}$ ist linear unabhängig und für jedes $v\in V$ ist die Familie $(v_1, \ldots, v_n, v)$ linear abhängig
  #+end_thm
  #+begin_proof latex
  Wir zeigen 1. \Rightarrow 2. \Rightarrow 3. \Rightarrow 4. \Rightarrow 1. \\
  1. \Rightarrow 2.: Sei $\mathcal{B} = (v_1, \ldots, v_n)$ eine Basis von $V \Rightarrow \mathcal{B}$ ist ES von $V$ \\
	 Annahme: $\mathcal{B}$ ist verkürzbar, das heißt es gibt ein $r\in\{r, \ldots, n\}$, sodass $(v_1, \ldots, v_{r - 1}, v_{r + 1}, \ldots, v_n)$ immernoch ein ES von $V$
	 \Rightarrow $v_r \in \Lin((v_1, \ldots, v_{r - 1}, v_{r + 1}, \ldots, v_n))$, das heißt
	 \[\Exists \lambda_1, \ldots, \lambda_{r - 1}, \lambda_{r + 1}, \ldots, \lambda_n\in K: v_r = \lambda_1 v_1 + \ldots + \lambda_{r - 1} v_{r - 1} + (-1)v_r + \lambda_{r + 1} v_{r + 1} + \ldots + \lambda_n v_n\]
	 \Rightarrow $\mathcal{B}$ linear abhängig $\lightning$ zu $\mathcal{B}$ Basis von $V$
  2. \Rightarrow 1.: Sei $\mathcal{B} = (v_1, \ldots, v_n)$ ein unverkürzbares ES von $V$ \Rightarrow Für jedes $v\in V$ existiert $\lambda_1, \ldots, \lambda_n \in K$ mit $v = \lambda_1 v_1 + \ldots + \lambda_n v_n$
	 Annahme: Es gibt $v\in V, \lambda_1, \ldots, \lambda_v v_n = \mu_1 v_1 + \ldots \mu_n v_n$
	 \begin{align*}
	 \Rightarrow (\lambda_i - \mu_i) v_i = (\mu_1 - \lambda_1)v_i + \ldots + (\mu_{i - 1} - \lambda_{i - 1})v_{i - 1} + (\mu_{i + 1} - \lambda_{i + 1}) v_{i + 1} + \ldots + (\mu_n - \lambda_n) v_n \\
	 \Rightarrow v_1 = \frac{\mu_{1} - \lambda_{1}}{\lambda_{i} - \mu_{i}} v_1 + \ldots + \frac{\mu_{i - 1} - \lambda_{i - 1}}{\lambda_{i} - \mu_{i}} v_{i - 1} + \frac{\mu_{i + 1} - \lambda_{i + 1}}{\lambda_{i} - \mu_{i}} v_{i + 1} + \ldots + \frac{\mu_{n} - \lambda_{n}}{\lambda_{i} - \mu_{i}} v_n \\
	 \end{align*}
	 \Rightarrow Jeder UVR von $v_i$ der $v_1, \ldots, v_{i - 1}, v_{i + 1}, \ldots, v_n$  enthält, enthält auch $v_i$ \\
	 \Rightarrow $\Lin((v_1, \ldots, v_{i - 1}, v_{i + 1}, \ldots, v_n)) = \Lin((v_1, \ldots, v_n)) = v$ \\
	 \Rightarrow $\mathcal{B}$ ist verkürzbar $\lightning$
  3. \Rightarrow 4.: Wir setzte 3. vorraus, das heißt für jedes $v\in V$ existieren eindeutig bestimmt $\lambda_1, \ldots, \lambda_n \in K$ mit $v = \lambda_1 v_1 + \ldots + \lambda_n v_n$. \\
	 zu zeigen: $\mathcal{B}$ ist unverlängerbar linear unabhängig \\
	 denn Insbesondere existiert für jedes $v\in \Lin((c_1, \ldots, v_n))$ eindeutig bestimmt $\lambda_1, \ldots, \lambda_n \in K$ mit $v = \lambda_1 v_1 + \ldots + \lambda_n v_n \Rightarrow (v_1,\ldots, v_n)$ linear unabhängig.
	 Ist $v\in V$, dann existiert $\lambda_1, \ldots, \lambda_n \in K$ mit $v = \lambda_1 v_1 + \ldots + \lambda_n v_n \Rightarrow (v_1, \ldots, v_n)$ linear abhängig. Somit: $\mathcal{B}$ unverlängerbar linear unabhängig
  4. \Rightarrow 1. Sei $\mathcal{B}$ unverlängerbar linear unabhängig
	 zu zeigen: $\mathcal{B}$ ist Basis von $V$, das heißt es bleibt noch zu zeigen, dass $\mathcal{B}$ ein ES von $V$ ist \\
	 Sei $v\in V \Rightarrow (v_1, \ldots, v_n, v)$ linear abhängig \Rightarrow $\Exists \lambda_1, \ldots, \lambda_n \in K, (\lambda_1, \ldots, \lambda_n) \neq (0, \ldots, 0): \lambda_1 v_1 + \ldots + \lambda_n v_n + \lambda v = 0$
	 Es ist $\lambda \neq 0$, da sonst $(v_1, \ldots, v_n)$ linear abhängig
	 \[\Rightarrow v = -\frac{\lambda_1}{\lambda} v_1 - \ldots - -\frac{\lambda_n}{\lambda} v_n \in \Lin((v_1, \ldots, v_n))\]
	 \Rightarrow $\mathcal{B}$ ist ES von $V$
  #+end_proof
  #+ATTR_LATEX: :options [9.4 Basiswahlsatz]
  #+begin_conc latex
  Besitzt $V$ ein endliches ES $(v_1, \ldots, v_n)$, dan kann man aus diesem eine Basis auswählen, das heißt es gibt eine Teilmenge $\{i_1, \ldots, i_r\} \subseteq \{1, \ldots, n\}$, sodass $(v_{i_0}, \ldots, v_{i_r})$ ein Basis von $V$ ist. Insbesondere bestitz jeder endlich erzeuge Vektorraum eine Basis
  #+end_conc
  #+begin_proof latex
  Entferne aus dem ES $(v_1, \ldots, v_n)$ nacheinander solange Elemente, bis die resultierende Familie ein unverkürzbares ES und somit nach 8.3 eine Basis von $V$ ist.
  #+end_proof
  #+ATTR_LATEX: :options [9.5]
  #+begin_conc latex
  Jeder endlich erzeugte K-VR besitzt eine Basis von endlicher Länge. \\
  Fragen:
  - Ist jede Basis von $V$ von endlicher Länge?
  - Sind je zwei endliche Basen von $V$ gleicher Länge
  #+end_conc
  #+ATTR_LATEX: :options [9.6 Austauschlemma]
  #+begin_thm latex
  $V$ endlich erzeugter K-VR, $\mathcal{B} = (v_1, \ldots, v_r)$ von $V,\lambda_1, \ldots,\lambda_r \in K,w = \lambda_1 v_1 + \ldots + \lambda_r v_r$. Dann gilt:
  Ist $k\in \{1,\ldots, r\}$ mit $\lambda_k \neq 0$, dann ist
  \[\mathcal{B}' = (v_1, \ldots, v_{k - 1}, w, v_{k + 1}, \ldots, v_r)\]
  ebenfalls eine Basis von $V$, das heißt man kann $v_k$ gegen $w$ austuaschen
  #+end_thm
  #+begin_proof latex
  Wir können ohne Einschränkung ("ohne Beschränkung der Allgemeinheit") annehmen, dass $k = 1$ ist (können wir duch Umsortieren erreichen). Gegeben ist $w = \lambda_1 v_1 + \ldots + \lambda_r v_r \in V$, mit $\lambda_1 \neq 0$
  zu zeigen ist, dass $\mathcal{B}' = (w, v_2, \ldots, v_r)$ ein Basis von $V$ ist.
  1. $\mathcal{B}'$ ist ein ES von $V$ \\
	 Sei $v\in V \Rightarrow \Exists \mu_1, \ldots, \mu_r \in K: v = \mu_1 v_1 + \ldots + \mu_r v_r$ \\
	 Aus $w = \lambda_1 v_1 + \ldots + \lambda_r v_r$ folgt wegen $\lambda_1 \neq 0$:
	 \begin{align*}
	 v_1 = \frac{1}{\lambda_1} w - \frac{\lambda_2}{\lambda_1} v_2 - \ldots - \frac{\lambda_r}{\lambda_1} v \\
	 v =\frac{\mu_1}{\lambda_1} w + (\mu_2 - \mu_1 \frac{\lambda_2}{\lambda_1}) v_2 + \ldots + (\mu_r - \mu_1 \frac{\lambda_r}{\lambda_1}) v_r \in \Lin ((w, v_2, \ldots, v_r))
	 \end{align*}
  2. $\mathcal{B}'$ ist linear unabhängig, denn: \\
	 \begin{align*}
	 \intertext{Sei $\mu, \mu_2, \ldots, \mu_r \in K$ mit $\mu w + \mu_2 v_2 + \ldots + \mu_r v_r = 0$}
	 \Rightarrow \mu(\lambda_1 v_1 + \ldots + \lambda_r v_r) + \mu_2 v_2 + \ldots + \mu_r v_r = 0 \\
	 \Rightarrow \mu \lambda_1 v_1 + (\mu \lambda_2 + \mu_2) v_2 + \ldots + (\mu \lambda_r + \mu_r) v_r = 0 \\
	 \Rightarrow \mu \lambda_1 = 0 \Rightarrow \mu = 0 \Rightarrow \mu_2 v_2 + \ldots + \mu_r v_r = 0 \Rightarrow \mu_2 = \ldots = \mu_r = 0
	 \end{align*}
  #+end_proof
  #+ATTR_LATEX: :options [Austauschsatz]
  #+begin_thm latex
  $V$ endlich erzeugter K-VR, $(w_1, \ldots, w_n)$ linear unabhängige Familie in $V$. Dann gilt
  1. Ist $\mathcal{B} = (v_1, \ldots, v_r)$ eine Basis von $V$, dann ist $r \geq n$
  2. Es giibt Indizes $i_1, \ldots, i_n \in \{1, \ldots, r\}$ derart, dass man aus der Basis $\mathcal{B} = (v_1, \ldots v_r)$ von $V$ nach Austausch von $v_{i_1}$ gegen $w_1$, $v_{i_2}$ gegen $w_2$, $\ldots$, $v_{i_n}$ gegen $w_n$ wieder eine Basis von $V$ erhält.
	 Nummeriert man $\mathcal{B}$ so um, dass $i_1 = 1, i_2 = 2, \ldots, i_n = n$, bedeutet dies, dass $\mathcal{B}^\ast :=(w_1, \ldots, w_n, w_{n + 1}, \ldots, v_r)$ eine Basis von $V$ ist.
  #+end_thm
  #+begin_proof latex
  Wir zeigen 1. und 2. zusammen per Induktion nach $n$ \\
  Induktionsanfang: $n = 0$: $(w_1, \ldots, w_n)$ leere Familie \\
  Induktionsschritt: Sei $n \geq 1$, und die Aussage sei für $n - 1$ schon bewiesen. Wegen $(w_1, \ldots, w_a)$ linear unabhängige Familie ist auch $(w_1, \ldots, w_{n - 1})$ linear unabhängig $\Rightarrow n - 1 \leq r$ und nach Umnummerieren von $\mathcal{B}$ ist auch
  \[\tilde{\mathcal{B}} := (v_1, \ldots, w_{n - 1}, v_n, \ldots, v_r)\]
  eine Basis von $V$.

  Falls $n - 1 = r$, dann wäre $\tilde{\mathcal{B}} = (w_1, \ldots, w_{n - 1})$ eine Basis von V $\lightning$ (zu 9.3, denn auch $(w_1, \ldots, w_n)$ linear unabhängig).
  Also $n - 1 < r$, das heißt $n \leq r$

  Da $\tilde{\mathcal{B}}$ Basis von $V, \Exists \lambda_1, \ldots, \lambda_r \in K: w_n = \lambda_1 w_1 + \ldots, \lambda_{n - 1} w_{n - 1} \lambda_n w_n + \ldots + \lambda_r$ \\
  Falls $\lambda_n = \ldots = \lambda_r = 0$, dann $(w_1, \ldots, w_n)$ linear abhängig $\lightning$ \\
  Also existiert ein $k \in \{n, \ldots, r\}$ mit $\lambda_k \neq 0$ Nach umnummerieren von $v_n, \ldots, v_r$ kann man $\lambda_n \neq 0$ erreichen
  \[\Rightarrow \mathcal{B}^\ast := (w_1, \ldots, w_{n - 1}, w _n, v_{n + 1}, \ldots, v_r)\] ist eine Basis von $V$ (tausche $v_n$ gegen $w_n$)
  #+end_proof
  #+ATTR_LATEX: :options [9.8]
  #+begin_conc latex
  Es gilt:
  1. Ist $V$ endlich erzeutgt, dann ist jede Basis von $V$ von endlicher Länge und je zwei Basen haben dieselbe Länge
  2. Ist $V$ nicht endlich erzeugt, dann existiert für $V$ keine Basis von endlicher Länge
  #+end_conc
  #+begin_proof latex
  1.
	 - $V$ endlich erzeugt $\Rightarrow$ ex existiert eine endliche Basis $(v_1, \ldots, v_r)$ von $V$, sei $(w_i)_{i\in I}$ beliebige Basis von $V$. Falls $I$ unendlich, dann existiert $i_1, \ldots, i_{r + 1} \in I$, dosass $(w_{i_1} + \ldots + w_{i_{r + 1}})$
		linear unabhängig \Rightarrow $r + 1 \leq r \lightning$
	 - Sind $(v_1, \ldots, v_r), (w_1, \ldots, w_k)$ endliche Basen von $V$, dann folgt nach Austauschsatz $k \leq r$, sowie $r\leq k \Rightarrow r = k$
  2. Besitzt $V$ eine Basis endlicher Länge, dann ist diese auch ein endliches ES, das heißt $V$ endlich erzeugt $\lightning$
  #+end_proof
  #+ATTR_LATEX: :options [9.9]
  #+begin_defn latex
  \[\dim_k V := \begin{cases} r & ~\text{falls $V$ endlich erzeugt, $r$ Länge jeder Basis von $V$} \\ \infty & ~\text{falls $V$ nicht endlich erzeugt}\end{cases}\]
  heißt die Dimension von $V$ über $K$. Ist $\dim_k V\in\mathbb{N}_0$, dann heißt $V$ endlichdimensional über $K$.
  #+end_defn
  #+begin_note latex
  - Der Dimensionsbegriff ist wohldefiniert nach 9.8
  #+end_note
  #+ATTR_LATEX: :options [9.10]
  #+begin_ex latex
  1. $V = K^n$ Die Standardbasis $(e_1, \ldots, e_n)$ von $K^n$ hat Länge von $n$, das heißt $\dim_k K^n = n$. Insbesondere hat jede Basis von $K^n$ die Länge $n$
  2. In $K[t]$ ist die Familie $(t^n)_{n\in\mathbb{N}_0}$ eine Basis unendlicher Länge. Wäre $K[t]$ endlichdimensional über $K$, dann wäre jede Basis von $K[t]$ als K-VR von endlicher Länge. Also $\dim_k K[t] = \infty$
  3. $\dim_\mathbb{C} \mathbb{C} = 1$, aber $\dim_\mathbb{R} \mathbb{C} = 2$, (denn: $(1,\I)$ inst eine Basis von $\mathbb{C}$ also $\mathbb{R}$-VR)
  #+end_ex
  #+begin_note latex
  - Ist klar, welcher Körper gemeint ist schreibt man kurz $\dim V$ statt $\dim_K V$.
  - Offenbar gilt $V$ endlich erzeugt $\Leftrightarrow$ $V$ endlichdimensional
  #+end_note
  #+ATTR_LATEX: :options [9.11]
  #+begin_conc latex
  $V$ endlichdimensionaler K-VR, $U\subseteq V$ UVR von $V$ Dann gilt:
  1. $U$ ist endlichdimensional
  2. $\dim_k U \leq \dim_K V$
  3. Es ist $U = V \Leftrightarrow \dim_k U = \dim_k V$
  #+end_conc
  #+begin_proof latex
  1. Annahme: $U$ ist nicht endlichdimensional \\
	 Beweis: per Induktion nach $N$ \\
	 Induktionsanfang: $n = 1$: Da $n\neq \{0\}$ wegen $\dim_k U = \infty$ existiert $u_1 \in U \setminus \{0\}, (u_1)$ ist linear unabhängig
	 Induktionsschritt: Sei $n > 1$, die Assage sei für $n - 1$ bewiesen. \Rightarrow ex existiert linear unabhängige Familie $(u_1, \ldots, u_{n - 1})$.
	 Falls $(u_1, \ldots, u_{n - 1}, u)$ linear abhängig für alle $u \in U$, dann wäre $(u_1, \ldots u_{n - 1})$ unverlängerbar linear abhängig und somit nach 9.3 eine Basis von $U~\lightning$ zu $U$ nicht endlichdimensional.
	 Also existiert ein $u_1 \in U$ mit $(u_1, \ldots, u_n)$ linear unabhängig \Rightarrow Behauptung
	 Wir setzen $r:= \sum_K V$, dann existiert nach 1. eine lineare Familie $(u_1, \ldots, u_{r + 1})$ in $U$. Die Familie $(u_1, \ldots, u_{r + 1})$ ist auch eine linear unabhängige Famnile in $V \Rightarrow r + 1 \leq r ~ \lightning$ Das heißt $U$ ist endlich
  2. Annahme: $n := \dim_k U > \dim V$ \\
	 Sei $(u_1, \ldots, u_n)$ Basis von $U$, das heißt insbesondere ist die Familie $(u_1, \ldots, u_n)$ eine linear unabhängige Familie in $V$ \Rightarrow $n \leq \sum_k V ~\lightning$
  3. "$\Rightarrow$" trivial \\
	 "$\Leftarrow$" Annahme: $U \subsetneq V$ \\
	 Sei $(u_1, \ldots, u_r)$ Basis von $U$. Wegen $U \subsetneq V$ ist $(u_1, \ldots, u_r)$ keine Basis von $V$ \Rightarrow $\Exists v\in V: (u_1, \ldots, u_r, v)$ linear unabhängig.
	 $\Rightarrow$ es existiert $v \in V$, sodass $(u_1, \ldots, u_r, v)$ linear unabhänig \Rightarrow $r + 1 \leq \dim V = \dim U = r \lightning$
  #+end_proof
  #+ATTR_LATEX: :options [9.12 Besisergänzungssatz]
  #+begin_thm latex
  $V$ endlichdimensionaler K-VR, $(u_1, \ldots, u_n)$ linear unabhängige Famile von $V$ \\
  Dass existiert $u_{n + 1}, \ldots, u_r \in V, r = \sum V$, sodass $\mathcal{B} = (u_1, \ldots, u_n, u_{n + 1}, \ldots, u_r)$ eine Basis von $V$ ist (das heißt $(u_1, \ldots, u_n)$ kann zu einer Basis erhänzt werden)
  #+end_thm
  #+begin_proof latex
  Sei $(v_1, \ldots, v_r)$ eine Basis von $V$. Aus Austauschsatz folgt: Nach umnummerierung von $v_1, \ldots, v_r$ ist $(u_1, \ldots, u_n,  v_{n + 1}, \ldots, v_r)$ eine Basis von $B$ Setze $u_{n + 1} := v_{n + 1}, \ldots, u_r := v_r$
  #+end_proof
  #+ATTR_LATEX: :options [9.13 Zorsches Lemma]
  #+begin_thm latex
  Jede induktiv geordnete nichtleere Menge $(M, \leq)$ besitzt ein maximales Element.
  Hierbei heißt eine halbgeordnete Menge $(m, \leq)$ *induktiv geordnet* $\xLeftrightarrow{\text{Def}}$ Jede Teilmenge $T\subseteq M$, für die $(T, \leq)$ totalgeordnet ist,
  besitzt eine obere Schanke in $(M, \leq)$, das heißt $\Exists S\in M: t\leq S \Forall t\in T$
  #+end_thm
  #+begin_note latex
  Das Zornsche Lemma ist äquivalent zum Auswahlaxiom
  #+end_note
  #+ATTR_LATEX: :options [9.14]
  #+begin_defn latex
  $(u_j)_{j\in J}$ linear unabhängige Familie in $V$. Dann kann $(u_j)_{j \in J}$ zu einer
  Basis von $V$ ergänzt werden, das heißt $\Exists I: J\subseteq I, (v_i)_{i\in I}: v_j = u_j \Forall j\in J$, sodass $(v_i)_{i\in I}$  eine Basis von $V$ ist.
  Insbesondere besitzt jeder K-VR eine Basis.
  #+end_defn
  #+begin_proof latex
  1. Wir setzen $A:= \{uj \mid j \in J\}, M:= \{X \subseteq V \mid A\subseteq X \wedge X ~\text{ist linear unabhängig}\}$
	 - $(M, \subseteq)$ ist eine halbgeordnete Menge
	 - $(M \neq \emptyset)$, denn $A\in M$
	 - $(m, \subseteq)$ ist induktiv geordnet, denn:
	   Sei $T\subseteq M$, sodass $(T,\subseteq)$ totalgeordnet ist. \\
	   zu zeigen: $T$ besitzt eine obere Schranke in $M$. \\
	   Wir setzen $\displaystyle S:= \bigcup_{X\in T} X$, dann ist $X\subseteq S \Forall X\in T$.
	   Noch zu zeigen: $S\in M$, das heißt $A\subseteq S$ und $S$ ist linear unabhängig
	   - $A\subseteq S$ klar, denn $A\subseteq X\Forall X\in T$
	   - $S$ ist linear unabhängig, das heißt jede endliche Teilfamilie von $(s)_{s\in S}$ inst linear unabhägig: \\
		 Seien $s_1, \ldots, s_n \in S$ paarweise verschieden $\Rightarrow \Exists X_1, \ldots X_n \in T: s_i \in X_i, i = 1, \ldots, n$ \\
		 Da $(T, \subseteq)$ totalgeordnet ist existiert ein $i\in \{1, \ldots, n\}$ mit $X_j \subseteq X_i$ für alle $j\in \{1,\ldots,n\} \Rightarrow s_1, \ldots, s_n \subseteq X_i \xRightarrow{X_i \in M} (x_1, \ldots, s_n)$ linear unabhängig.
  2. Nach 1. können wir das Zornsche Lemma auf $(M,\subseteq)$ anwenden $\Rightarrow \Exists \max B \in M$ \\
	 Behauptung: $(b)_{b\in B}$ ist eine Basis von $V$ mit $A\subseteq B$, denn: Da $(b)_{b\in B}$ linear unabhängig wegen $V\in M$, gilt zu Zeigen, dass $\Lin(B) = V)$ \\
	 "$\subseteq$" klar \\
	 "$\supseteq$"
	 \begin{align*}
	 \intertext{Sei $v \in V$. Falls $v\in B$, dann $v\in\Lin(B)$, falls $v = 0$, dann $v\in \Lin(B)$, im Folgenden sei $v\not\in B, v\neq 0$}
	 \Rightarrow A \subseteq B \subsetneq B\cup \{v\} \\
	 \intertext{Da $B$ Maximum von $(M,\subseteq)$ ist, ist $B \cup \{v\} \not \in M$, das heißt $B\cup \{v\}$ ist linear abhängig}
	 \Rightarrow \Exists n\in\mathbb{N}_0, \lambda_1, \ldots, \lambda_n \in K, \lambda \in K, (\lambda, \lambda_1, \ldots, \lambda_n) \neq (0, \ldots, 0), b_1, \ldots, b_n \in B: \\
	 \lambda v + \lambda_1 b_1 + \ldots + \lambda_n b_n = 0 \\
	 \intertext{Falls $n = 0$}
	 \lambda v = 0 \xRightarrow{v \neq 0} \lambda = 0 \lightning \\
	 \intertext{Also $n \geq 1$, Falls $\lambda = 0$}
	 (b_1, \ldots, b_n) ~\text{linear abhängig} \lightning \\
	 \intertext{Also $\lambda \neq 0$, somit:}
	 v = -\frac{\lambda_1}{\lambda} v_1 - \ldots - \frac{\lambda_n}{\lambda} b_n \in\Lin((b_1, \ldots, b_n)) \subseteq \Lin(B)
	 \end{align*}
  #+end_proof
  #+begin_note latex
  Der Satz "Jeder VR hat eine Basis" ist äquivalent zum Auswahlaxiom.
  #+end_note
