* Determinanten
  In diesem Abschnitt sei $n\in \mathbb{N}$ \\
  Ziel: Ordne jeder Matrix aus $M(n\times n, K)$ ein Element aus $K$ zu, dass genau dann $= 0$ ist,
  wenn die Matrix nicht invertierbar ist. Die Zuordnung soll mehreren Bedingungen genügen.
  #+ATTR_LATEX: :options [17.1]
  #+begin_defn latex
  Eine Abbildung $\det: M(n\times n, K) \to K, A\mapsto \det A$ heißt *Determinante* $\xLeftrightarrow{\text{Def}}$ Die folgenden Bedingungen sind erfüllt:
  - (D1) $\det$ ist *linear in jeder Zeile*, das heißt ist
	\[A = \cvec{a_1; \vdots; a_n} \in M(n\times n, K)\]
	mit Zeilen $a_1, \ldots, a_n$, dann gilt für jedes $i\in \{1, \ldots, n\}$:
	- (D1a) Ist $a_i = a_i' + a_i''$, dann ist
	  \[\det \cvec{a_1; \vdots; a_i; \vdots; a_n} = \det \cvec{a_1; \vdots; a_i'; \vdots; a_n} + \det \cvec{a_1; \vdots; a_i''; \vdots; a_n}\]
	- (D1b) Ist $a_i = \lambda a_i'$ mit $\lambda \in K$, dann ist
	  \[\det \cvec{a_1; \vdots; a_i; \vdots; a_n} = \lambda \det \cvec{a_1; \vdots; a_i'; \vdots; a_n}\]
  - (D2) $\det$ ist *alternierend*, das heißt: Hat $A\in M(n\times n, K)$ zwei gleiche Zeilen, dann ist $\det A = 0$
  - (D3) $\det$ ist *normiert*, das heißt $\det E_n = 1$
  Weitere Schreibweise: Für $A = (a_{ij})$ schreiben wir auch
  \[\begin{vmatrix} a_{11} & \ldots & a_{1n} \\ \vdots & & \\ a_{n1} & \ldots & a_{nn}\end{vmatrix} := \det \begin{pmatrix} a_{11} & \ldots & a_{1n} \\ \vdots & & \\ a_{n1} & \ldots & a_{nn}\end{pmatrix}\]
  #+end_defn
  #+begin_note latex
  Wir müssen erst noch zeigen, dass es Determinanten überhaupt gibt.
  - geometrische Motivation für (D1)-(D3) für den Fall $K = \mathbb{R}$:
	ist $A = \cvec{a_1; \vdots; a_n} \in M(n\times n, \mathbb{R})$, dann spannen die Vektoren
	$a_1, \ldots, a_n$ ein "Parallelotop im $\mathbb{R}$ auf ($n = 2$: Parallogramm). \\
	D1-D3 sind sinnvolle Forderungen für ein Volumen im $\mathbb{R}^n$:
	- D2: Volumen ist Null, wenn $i\neq j$ mit $a_i = a_j$ existiert.
	- D3: Volumen des "Einheitspolytops" ist 1
	- D1b: Volumen ist "homogen"
	- D1 + D2 implizieren (siehe Satz 17.2): Für $\lambda \in \mathbb{R}, i \neq j$ ist
	  \[\det \cvec{a_1; \vdots; a_1 + \lambda a_j; \vdots; a_n} = \det \cvec{a_1; \vdots; a_n}\]
	  ("Scherungsinvarianz")
  #+end_note
  #+ATTR_LATEX: :options [17.2]
  #+begin_thm latex
  $\det: M(n\times n, K) \to K$ sei einen Determinante,
  \[A = \cvec{a_1; \vdots; a_n}, B \in M(n\times n, K)\]
  Dann gilt:
  - (D4) $\det (\lambda A) = \lambda^n \det(A)$
  - (D5) Ist eine Zeile von $A$ gleich Null, dann ist $\det A = 0$
  - (D6) \[\det \cvec{a_1; \vdots; a_j; \vdots; a_i; \vdots; a_n} = -\det (A)\]
	das heißt bei Zeilenumformungen vom Typ 4 wird das Ergebnis mit $-1$ multipliziert.
  - (D7) \[\det\cvec{a_1; \vdots; a_i + \lambda a_j; \vdots; a_n} = \det A\]
	für $i\neq j, \lambda \in K$, das heißt $\det$ ist invariant unter Zeilenumformungen vom Typ 3
  - (D8) Ist $A$ eine obere Dreiecksmatrix, das heißt
	\[A = \begin{pmatrix} \lambda_1 & & \ast \\ & \ddots & \\ 0 & & \lambda_n \end{pmatrix}\]
	dann ist $\det A = \lambda_1 \cdots \ldots \cdots \lambda_n$ Analog für untere Dreiecksmatrizen.
  - (D9) Ist $n\geq 2$ und $A$ von der Gestalt
	\[A = \begin{pmatrix} A_1 & C \\ 0 & A_2\end{pmatrix}\]
	mit $A_1 \in M(r\times r, K), A_2 \in M(s\times s, K), r + s = n$, dann ist $\det A = \det(A_1) \cdots \det(A_2)$.
  - (D10) $\det A = 0 \iff \Rang A < 0$ (das heißt $\det A \neq 0 \iff A \in GL(n, K)$)
  - (D11) $\det (AB) = \det(A)\det(B)$. Insbesondere ist $\det(A^{-1}) = \det(A)^{-1}$
  #+end_thm
  #+begin_proof latex
  (D4) \[\det (\lambda A) = \det \cvec{\lambda a_1; \vdots; \lambda a_n} = \lambda \det \cvec{a_1; \lambda a_2; \vdots; \lambda a_n} = \ldots = \lambda^n \det \cvec{a_1; \vdots; a_n} = \lambda^n \det(A)\]
  (D5) Sei etwa $a_1 = 0 = 0_k \cdots 0$. Es ist
  \[\det \cvec{a_1; \vdots; 0; \vdots; a_n} = \det \cvec{a_1; \vdots; 0_K \cdot 0; \vdots 0} = 0_K \det\cvec{a_1; \vdots; 0; \vdots; a_n} = 0\]
  (D6) \[\det \cvec{a_1; \vdots; a_i; \vdots; a_j; \vdots; a_n} + \det \cvec{a_1; \vdots; a_j; \vdots; a_i; \vdots; a_n} = \det \cvec{a_1; \vdots; a_i; \vdots; a_i; \vdots; a_n} + \det \cvec{a_1; \vdots; a_i; \vdots; a_j; \vdots; a_n} + \det \cvec{a_1; \vdots; a_j; \vdots; a_i; \vdots; a_n} + \cvec{a_1; \vdots; a_j; \vdots; a_j; \vdots; a_n} = \det \cvec{a_1; \vdots; a_i; \vdots; a_i + a_j; \vdots; a_n} + \det \cvec{a_1; \vdots; a_j; \vdots; a_i + a_j; \vdots; a_n} = \det \cvec{a_1; \vdots; a_i + a_j; \vdots; a_1 + a_j; \vdots; a_n} = 0\]
  (D7) \[\det \cvec{a_1; \vdots; a_i + \lambda a_j; \vdots; a_j; \vdots; a_n} = \det \cvec{a_1; \vdots; a_i; \vdots; a_j; \vdots; a_n} + \lambda \det \cvec{a_1; \vdots; a_j; \vdots; a_j; \vdots; a_n} = \det \cvec{a_1; \vdots; \vdots; \vdots; \vdots; \vdots; a_n}\]
  (D8) $A$ sei von der Form
  \[\begin{pmatrix} \lambda_1 & & \ast \\ & \ddots &  \\ 0 & & \lambda_n\end{pmatrix}\]
  1. Fall: $\lambda_i \neq 0 \Forall i \in \{1, \ldots, n\}$. Durch Zeilenumformungen von Typ 3 kann
	 man $A$ auf die Form
	 \[\begin{pmatrix} \lambda_1 & & 0 \\ & \ddots &  \\ 0 & & \lambda_n\end{pmatrix}\]
	 bringen
	 \[\implies \det(A) = \begin{pmatrix} \lambda_1 & & 0 \\ & \ddots & \\ 0 & & \lambda_n\end{pmatrix} = \lambda_1 \cdot \ldots \cdot \lambda_n \det \begin{pmatrix} 1 & & 0 \\  & \ddots & \\ 0 & & 1\end{pmatrix} = \lambda_1 \cdot \ldots \cdot \lambda_n\]
  2. Fall: $\Exists i\in \{1, \ldots, n\}: \lambda_i = 0$. Wir setzen $j := \max\{i\in \{1, \ldots, n\} \mid \lambda_i = 0\}$, dann ist
	 \[\begin{pmatrix}
       \lambda_1 & & & & & & \\
	   & \ddots & & & \ast & & \\
	   & & \lambda_{j - 1} & & & & \\
	   & & & 0 & & & \\
	   & & & & \lambda_{j + 1} & & \\
	   & & & & & \ddots & \\
	   & & & & & & \lambda_n
       \end{pmatrix}\]
	   wobei $\lambda_{j + 1}, \ldots, \lambda_n \neq 0$. Insbesondere kann man die j-te Zeile durch Zeilenumformung vom Typ 3 zu einer Nullzeile machen.
	   $\implies \det A = 0 = \lambda_1 \cdot\ldots\cdot\lambda_n$
  (D9) Sei
  \[A = \begin{pmatrix} A_1 & c \\ 0 & A_2\end{pmatrix}, A_1 \in M(r\times r, K), A_2 \in M(s\times s,K), r + s = n\]
  Brige $A_1$ durch elementare Zeilenumformungen an $A$ vom Typ 3, 4 auf obere Dreiecksgestalt (das geht!)
  \begin{equation*}
  A \to \begin{pmatrix} B_1 & C' \\ 0 & A_2\end{pmatrix}
  \end{equation*}
  Wurden dabei $k$ Zeilenvertauschungen gemacht, dann ist nach D6
  \[\det(B_1) = (-1)^k \det(A^1)\]
  Überführe $A_2$ durch Zeilenumformugen vom Typ 3, 4 auf obere Dreiecksgestalt
  \[A \to \begin{pmatrix} B_1 & C' \\ 0 & B_2\end{pmatrix} =: B\]
  Es ist $\det(B_2) = (-1)^l\det(A_2)$, wenn dabei $l$ Zeilenvertauschungen gemacht wurden.
  $B_1, B_2, B$ sind obere Dreiecksmatrizen
  \[\implies \det (B) = \det(B_1)\det(B_2) = (-1)^{k + l}\det(A_1)\det(A_2)\]
  $B$ kann man aus $A$ durch Zelienumformungen vom Typ 3, 4 mit $k + l$ Zeilenumformungen erhalten
  \[\implies \det(B) = (-1)^{k + l}\det(A) \implies \det(A) = \det(A_1) \det(A_2)\]
  (D10) Wir bringen $A$ durch Zeilenumformungen vom Typ 3,4 auf obere Dreichsgestalt
  \[A \to \begin{pmatrix} \lambda_1 & & x \\ & \ddots & \\ 0 & & \lambda_n\end{pmatrix} =: B \implies \det(A) = \pm \det(B)\]
  Außderdem $\ZR(A) = ZR(B)$ und somit
  \[\Rang A = \Rang B\]. Es ist \[\Rang A = n \iff \Rang B = n \iff \lambda_1 \cdot \ldots \cdot \lambda_n \neq 0 \iff \det(B) \neq 0 \iff \det (A) \neq 0\]
  (D11)
  1. Fall: \[\Rang A < n \implies \dim (\im \tilde A) < n \implies \dim(\im(\tilde A \circ \tilde B)) < n \implies \Rang(AB) < n \implies \det(AB) = 0 = \det (A) \det(B)\]
  2. Fall: $\Rang A = n$, das heißt $A \in GL(n, K)$
	 1. Überlegung: $A$ lässt sich schreiben als Produkt von Elementarmatrizen vom Typ $D_i(\lambda), E_{ij}(1)$, etwa
		$A = C_1 \cdot \ldots \cdot C_s$, wobei $C_1, \ldots, C_s$ Elementarmatrizen obigen Types
		\[\implies AB = C_1 \cdot \ldots \cdot C_s B\]
	 2. Nach 1. gilt zu zeigen: Ist
		\[B = \cvec{b_1; \vdots; b_n} \in M(n\times n, K)\]
        und ist $C$ eine Elementarmatrix vom Typ $D_i(\lambda)$ beziehungsweise $E_{ij}(1)$, dann ist
		\[\det(CB) = \det(C) \det(B)\]
		(Dann ist nämlich
		\[\det(AB) = \det(C_1(C_2 \cdot \ldots \cdot C_s B)) = \det(C_1) \det(C_2 \cdot \ldots \cdot C_s B) = \ldots = \det(C_1) \cdot \ldots \cdot \det(C_s)\det(B) = \det(C_1 \cdot \ldots C_s)\det(B) = \det(A) \det(B)\]
		1. Fall:
		   \[C = D_i(\lambda) = \begin{pmatrix} 1 & & & & 0 \\ & \ddots & & & \\ & & \lambda & & \\ & & & \ddots & \\ 0 & & & & 1\end{pmatrix} \implies \det(CB) = \det{\cvec{b_1;\vdots;\lambda b_i;\vdots;b_n}} = \lambda \det(B)\]
		   und es ist $\det(C) = \lambda$, somit $\det(CB) = \det(C)\det(B)$
		2. Fall:
		   \[C = \begin{pmatrix} 1 & & & \\ & \ddots & 1 & \\ 0 & & & 1\end{pmatrix}, \det(C) = 1\]
		   Es ist
		   \[CB = \cvec{b_1;\vdots;b_i + b_j;\vdots;b_j;\vdots;b_n}\]
		   das heißt
		   \[\det(CB) = \det(B) = \det(C)\det(B)\]
		   Insbesondere für $A\in GL(n,K)$ gilt:
		   \[1 = \det(E_n) = \det(A A^{-1}) = \det(A) \det(A^{-1}) \implies \det(A^{-1}) = (\det(A))^{-1}\]
  #+end_proof
  #+begin_note latex
  Wir müssen imer noch zeigen, dass es überhaupt Abbildungen $\det:M(n\times n, K) \to K$ gibt,
  die D1-D3 erfüllen. Wir werden dies tun, indem wir eine explizite Formel angeben (Lebniz-Formel)
  #+end_note
  #+ATTR_LATEX: :options [17.3]
  #+begin_defn latex
  $\sigma \in S_n$
  \[\sgn(\sigma) := \prod_{1\leq i < j \leq n} \frac{\sigma(j) - \sigma(i)}{j - 1}\]
  heißt das *Sigma* von $\sigma$. $\sigma$ heißt *gerade* $\xleftrightarrow{\text{Defn.}} \sgn(\sigma) = 1, \sigma$ heißt *ungerade* $\xleftrightarrow{\text{Def.}} \sgn(\sigma) = -1$
  \[(i,j) \in \{1, \ldots, n\} \times \{1, \ldots, n\}, i < j, \sigma(i) > \sigma(j)\]
  heißt ein *Fehlstand* von $\sigma$
  #+end_defn
  #+ATTR_LATEX: :options [17.4]
  #+begin_remark latex
  Es gilt:
  1. $\sgn: S_n \to \{\pm 1\}$ ist ein Gruppenhomomorphismus von $(S_n, \circ)$ nach $(\{\pm\}, \cdot)$, das heißt
	 \[\sgn(\sigma \circ \tau) = \sgn(\sigma)\sgn(\tau) \Forall \sigma,\tau \in S_n\]
  2. $\sgn(\sigma^{-1}) = \sgn(\sigma)\Forall \sigma \in S_n$
  3. Es ist
	 \[\sgn(\sigma) = \begin{cases} 1 & \text{wenn $\sigma$ eine gerade Anzahl von Fehlständen hat} \\ -1 & \text{wenn $\sigma$ eine ungerade Anzahl von Fehlständen hat}\end{cases} = (-1)^k, k ~\text{Anzahl der Fehlstände von $\sigma$}\]
  #+end_remark
  #+begin_proof latex
  1. und 3. nachrechnen
  2. $1 = \sgn(\id) = \sgn(\sigma \circ \sigma^{-1}) = \sgn(\sigma)\sgn(\sigma^{-1}) \implies \sgn(\sigma) = \sgn(\sigma^{-1})$
  #+end_proof
  #+ATTR_LATEX: :options [17.5]
  #+begin_defn latex
  $\tau \in S_n$ heißt *Transposition* $\xleftrightarrow{\text{Def.}}$ Es existeirt $a, b \in \{1, \ldots, n\}, a\in b$ mit $\tau(a) = b, \tau(b) = a$ und $\tau(c) = c\Forall c\in \{1, \ldots, n\}\setminus\{a, b\}$
  #+end_defn
  #+ATTR_LATEX: :options [17.6]
  #+begin_remark latex
  $n \geq 2$. Dann gilt
  1. Für jedes $\sigma \in S_n$ existieren Transposiitionen $\tau_1, \ldots, \tau_k \in S_k$ mit $\sigma = \tau_1 \circ \ldots \circ \tau_k$,
	 das heißt für jedes Element aus $S_n$ kann (auf nicht notwendig eindeutige Weise!) als Produkt von
	 Transpositionen geschrieben werden.
  2. Ist $\tau \in S_n$ eine Transposition, dann existiert ein $\sigma \in S_n$ mit $\tau = \sigma \delta \sigma^{-1}$ wobei
	 \[\delta = \begin{pmatrix} 1 & 2 & 4 & \ldots & n \\ 2 & 1 & 3 & \ldots & n \end{pmatrix}\]
  #+end_remark
  #+begin_proof latex
  1. per Induktion nach $n$: \\
	 Induktionsanfang: \[p = 2, S_2 = \{\id, \begin{pmatrix} 1 & 2 \\ 2 & 1\end{pmatrix}\}\]
	 $\begin{pmatrix} 1 & 2 \\ 2 & 1\end{pmatrix}$ ist eine Transposition,
	 \[\id = \begin{pmatrix} 1 & 2 \\ 2 & 1\end{pmatrix} \circ \begin{pmatrix} 1 & 2 \\ 2 & 1\end{pmatrix}\]
	 Induktionsschritt: Die Aussage sei für $n - 1$ bewiesen. Wir betrachten die Abbildung
	 \[\phi: S_{n - 1} \to S_n, \pi \mapsto \begin{pmatrix} 1 & \ldots & n - 1 & n \\ \pi(1) & & \pi(n -1) & n\end{pmatrix}\]
	 $\phi$ ist ein injektiver Gruppenhomomorphismus.
	 1. Fall: \[\sigma \in S_n~\text{mit}~ \sigma(n) = n \implies \Exists \pi \in S_{n - 1}: \sigma = \phi(\pi)\]
		Nach Induktionsannahme existieren Transpositionen $\tau_1, \ldots, \tau_k \in S_{n - 1}$ mit $\pi = \tau_1 \circ \ldots \circ \tau_k$
		\[\implies \sigma = \phi(\pi) = \phi(\tau_1) \circ \ldots \circ \phi(\tau_k)\]
		$\phi(\tau_1), \ldots, \phi(\tau_k)$ sind wieder Transpositionen $\implies$ Behauptung
	 2. $\sigma \in S_n$ mit $\sigma(n) = m$ mit $1 \leq m \leq n -1$. Wir setzen
		\[\eps := \begin{pmatrix} 1 & \ldots & m & \ldots & n \\ 1 & \ldots & n & \ldots & m\end{pmatrix}, \tilde \sigma := \eps \circ \sigma\]
		\[\implies \tilde \sigma(n) = \eps(\sigma(n)) = \eps(m) = n\]
		$\implies$ Es existieren Transpositionen $\tilde \tau_1, \ldots, \tilde \tau_k \in S_n$ mit
		\[\tilde \sigma = \tilde\tau_1 \circ \ldots \circ \tilde\tau_m \implies \sigma = \eps \circ \tilde \tau = \eps \circ \tilde \tau_1 \circ \ldots \circ \tilde \tau_k \]
		$\implies$ Behauptung
  2. Sei
	 \[\tau = \begin{pmatrix} 1 & \ldots & k & \ldots & l & \ldots & n \\ 1 & \ldots & l & \ldots & k & \ldots & n\end{pmatrix}\]
	 Wir setzen
	 \[\sigma := \begin{pmatrix} 1 & 2 & 3 & \ldots & n \\ k & l & \ast & \ldots & \ast\end{pmatrix}\]
     \begin{align*}
	 \hspace{0pt}(\sigma \circ \delta \circ \sigma^{-1})(k) &= \hspace{0pt}(\sigma\circ \delta)(1) = \sigma(2) = l \\
	 \hspace{0pt}(\sigma \circ \delta \circ \sigma^{-1})(l) &= \hspace{0pt}(\sigma\circ \delta)(2) = \sigma(1) = k \\
     \end{align*}
	 für $i \not\in \{k, l\}$ ist $(\sigma\circ\delta\circ\sigma^{-1})(i) = (\sigma)(\sigma^{-1}(i)) = \sigma(\sigma^{-1}(i)) = i \implies \sigma\circ\delta\circ\sigma^{-1} = \tau$
  #+end_proof
  #+ATTR_LATEX: :options [Folgerung 17.7]
  #+begin_conc latex
  $n \geq 2$. Dann gilt:
  1. Ist $\tau \in S_n$ eine Transposition, dann ist $\sgn(\tau) = -1$
  2. Ist $\sigma \in S_n, \sigma = \tau_1 \circ \ldots \circ \tau_k$ mit Transpositionen $\tau_1, \ldots, \tau_k \in S_n$, dann ist $\sgn(\sigma) = (-1)^k$
  #+end_conc
  #+begin_proof latex
  1. Nach 17.6.2 existiert ein $\sigma \in S_n$ mit
     \[\tau = \sigma \circ \begin{pmatrix} 1 & 2 & 3 & \ldots & n \\ 2 & 1 & 3 & \ldots & n\end{pmatrix} \circ \sigma^{-1}\]
     \[\implies \sgn{\tau} = \sgn(\sigma)\sgn(\begin{pmatrix}1 & 2 & 3 & \ldots & n \\ 2 & 1 & 3 & \ldots & n\end{pmatrix})\sgn(\sigma^{-1}) = \sgn(\begin{pmatrix} 1 & 2 & 3 & \ldots & n \\ 2 & 1 & 3 & \ldots & n\end{pmatrix})\]
     Die Transponierte
     \[\begin{pmatrix} 1 & 2 & 3 & \ldots & n \\ 2 & 1 & 3 & \ldots & n\end{pmatrix}\]
     hat genau einen Fehlstand, nämlich $(1, 2)$, also $\sgn(\tau) = -1$
  2. $\sgn(\sigma) = \sgn(\tau_1 \circ \ldots \circ \tau_k) = \sgn(\tau_1) \cdot \ldots \cdot \sgn(\tau_k) = (-1)^k$
  #+end_proof
  #+ATTR_LATEX: :options [17.8]
  #+begin_conc latex
  $\det: M(n\times n, K) \to K$ sei eine Determinante, $\sigma \in S_n$. Dann gilt
  \[\det(\cvec{e_{sigma(1)}; \vdots; e_{\sigma(n)}}) = \sgn(\sigma)\]
  #+end_conc
  #+begin_proof latex
  Nach 17.6 existieren Transpositionen $\tau_1, \ldots, \tau_k \in S_n$ mit $\sigma = \tau_1 \circ \ldots \circ \tau_k$. Wir
  erhalten folgende Sequenz von $k$ Zeilenvertauschungen:
  \[E_n = \cvec{e_1; \vdots; e_n} \to \cvec{e_{\tau_k(1)}; \vdots; e_{\tau_k(n)}} \to \cvec{e_{\tau_{k - 1} \circ \tau_k(1)}; \vdots; e_{\tau_{k - 1}\circ\tau_k(n)}} \to \ldots \to \cvec{e_{\sigma(1)};\vdots;e_{\sigma(n)}}\]
  \[\implies \det\cvec{e_{\sigma(1)}, \vdots, e_{\sigma(n)}} = (-1)^k \det(E_n) = (-1)^k = \sgn(\sigma)\]
  #+end_proof
  #+ATTR_LATEX: :options [17.9]
  #+begin_defn latex
  $A_n := \{\sigma \in S_n \mid \sgn(\sigma) = 1\}$ ist eine Gruppe bezüglich "$\circ$",
  die sogenannte *alternierende Gruppe*
  #+end_defn
  #+begin_proof latex
  Übung
  #+end_proof
  #+ATTR_LATEX: :options [17.10]
  #+begin_ex latex
  Es ist \[S_3= \{\id, \begin{pmatrix} 1 & 2 & 3 \\ 2 & 1 & 3\end{pmatrix}, \begin{pmatrix} 1 & 2 & 3 \\ 3 & 2 & 1\end{pmatrix}, \begin{pmatrix} 1 & 2 & 3 \\ 1 & 3 & 2\end{pmatrix}, \begin{pmatrix} 1 & 2 & 3 \\ 2 & 3 & 1\end{pmatrix}, \begin{pmatrix} 1 & 2 & 3 \\ 3 & 1 & 2\end{pmatrix}\}\]
  Es ist \[\begin{pmatrix}1 & 2 & 3 \\ 2 & 3 & 1\end{pmatrix}= \begin{pmatrix}1 & 2 & 3 \\ 3 & 2 & 1\end{pmatrix} \circ \begin{pmatrix}1 & 2 & 3 \\ 2 & 1 & 3\end{pmatrix}\]
  das heißt
  \[\sgn(\begin{pmatrix}1 & 2 & 3 \\ 2 & 3 & 1\end{pmatrix}) = (-1)^2 = 1\]
  Vergleiche Definition $\sgn$:
  \[\sgn(\begin{pmatrix}1 & 2 & 3 \\ 2 & 3 & 1\end{pmatrix}) = \prod_{1\leq i < j \leq 3} \frac{\sigma(j) - \sigma(i)}{j - i} = \frac{3 - 2}{2 - 1}\frac{1 - 2}{3 - 1}\frac{1 - 3}{3 - 2} = 1\]
  \[\begin{pmatrix}1 & 2 & 3 \\ 3 & 1 & 2\end{pmatrix} = \begin{pmatrix}1 & 2 & 3 \\ 2 & 1 & 3\end{pmatrix} \circ \begin{pmatrix}1 & 2 & 3 \\ 3 & 2 & 1\end{pmatrix} \implies \sgn(\begin{pmatrix}1 & 2 & 3\\ 3 & 1 & 2\end{pmatrix}) = 1\]
  \[\implies A_3 = \{\id, \begin{pmatrix}1 & 2 & 3 \\ 2 & 3 & 1\end{pmatrix}, \begin{pmatrix}1 & 2 & 3 \\ 3 & 1 & 2\end{pmatrix}\}\]
  #+end_ex
  #+ATTR_LATEX: :options [17.11]
  #+begin_remark latex
  $n\geq 2, \pi \in S_n \setminus A_n$. Dann gilt:
  1. $S_n = S_n \cup A_n \pi, A_n \cap A_n \pi = \emptyset$. Hierbei ist $A_n\pi \{\sigma \circ \pi \mid \sigma \in A_n\}$. Also:
	 \[S_n = A_n \dot\cup A_n \pi\]
  2. $\abs{A_n} = \frac{1}{2}\abs{S_n} = \frac{1}{2}n!$
  #+end_remark
  #+begin_proof latex
  1. "$\supseteq$" trivial \\
	 "$\subseteq$" Sei $\sigma \in S_n$
	 1. Fall: $\sgn(\sigma) = 1 \implies \sigma\in A_n \subseteq S_n \cup A_n \pi$
	 2. Fall: $\sgn(\sigma) = -1 \implies \sgn(\sigma\circ \pi^{-1}) = \sgn(\sigma)\sgn(\pi^{-1}) = \sgn(\sigma) \sgn(\pi) = (-1)(-1) = 1 \implies \sigma\circ\pi^{-1}\in A_n\implies \sigma = \underbrace{(\sigma \circ\pi^{-1})}_{\in A_n} \circ \pi \in A_n \pi \subseteq A_n\cup A_n\pi$ \\
		Annahme: $A_n \cap A_n\pi \neq \emptyset \implies \Exists \sigma \in A_n \cap A_n \pi \implies \sgn(\sigma) = 1$ und es existiert $\eps\in A_n$ mit
		\[\sigma = \eps\circ \pi\implies \sgn(\sigma) = \sgn(\eps)\sgn(\pi) = 1(-1) = -1\lightning\]
  2. Die Abbildung $A_n \to A_n\pi,\sigma\mapsto \sigma\circ \pi$ ist
	 - surjektiv nach Definition
	 - injektiv, denn: $\sigma_1 \circ \pi = \sigma_2 \circ \pi\implies \sigma_1 = \sigma_2$
	 \[\implies\abs{A_n} = \abs{A_n \pi}\]
	 Wegen $S_n = A_n \dot{\cup} A_n\pi$ folgt $\abs{A_n} = \abs{A_n\pi} = \frac{1}{2}\abs{S_n} = \frac{1}{2}n!$
  #+end_proof
  #+ATTR_LATEX: :options [17.12]
  #+begin_thm latex
  Es gibt genau eine Determinante
  \[\det: M(n\times n,K)\to K\]
  Diese st durch
  \[\det(A) = \sum_{\sigma\in S_n} \sgn(\sigma) a_{1\sigma(1)}\cdot \ldots \cdot a_{n\sigma(n)}, A = (a_{ij}) \in M(n\times n,K)\]
  #+end_thm
  #+ATTR_LATEX: :options [17.13]
  #+begin_ex latex
  1. $n = 2$
	 \[\det\begin{pmatrix}a_{11} & a_{12} \\ a_{21} & a_{22}\end{pmatrix} = \sum_{\sigma \in S_2}\sgn(\sigma) a_{1\sigma(1)}a_{2\sigma(2)} = \sgn(\id) a_{11} a_{22} + \sgn(\begin{pmatrix}1 & 2 \\ 2 & 1\end{pmatrix})a_{12}a_{21} = a_{11} a_{22} - a_{12} a_{21}\]
  2. $n = 3$: Erinnerung (vergleiche 17.10)
	 \[S_3 = \{\underbrace{\id}_{1}, \underbrace{\begin{pmatrix} 1 & 2 & 3 \\ 2 & 1 & 3\end{pmatrix}}_{1}, \underbrace{\begin{pmatrix} 1 & 2 & 3 \\ 3 & 2 & 1\end{pmatrix}}_{1}, \underbrace{\begin{pmatrix} 1 & 2 & 3 \\ 1 & 3 & 2\end{pmatrix}}_{-1}, \underbrace{\begin{pmatrix} 1 & 2 & 3 \\ 2 & 3 & 1\end{pmatrix}}_{-1}, \underbrace{\begin{pmatrix} 1 & 2 & 3 \\ 3 & 1 & 2\end{pmatrix}}_{-1}\}\]
	 \[\implies \det \begin{pmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33}\end{pmatrix} = a_{11}a_{22}a_{33} + a_{12}a_{23}a_{31} + a_{13}a_{21}a_{32} - a_{11}a_{23}a_{32} - a_{12}a_{21}a_{33} - a_{13}a_{22}a_{31}\]
     #+begin_export latex
	 \begin{figure}[H]
     \catcode`(=12
     \catcode`)=12
	 \centering
	 \begin{tikzpicture}[>=stealth]
    \matrix [matrix of math nodes,column sep=1em,row sep=1em] (sarrus) {a_{11} & a_{12} & a_{13} & a_{11} & a_{12} \\ a_{21} & a_{22} & a_{23} & a_{21} & a_{22} \\ a_{31} & a_{32} & a_{33} & a_{31} & a_{32} \\ };

    \path ($(sarrus-1-1.north west)-(0.5em,0)$) edge ($(sarrus-3-1.south west)-(0.5em,0)$)
          ($(sarrus-1-3.north east)+(0.5em,0)$) edge ($(sarrus-3-3.south east)+(0.5em,0)$)
          (sarrus-1-1)                          edge            (sarrus-2-2)
          (sarrus-2-2)                          edge[->]        (sarrus-3-3)
          (sarrus-1-2)                          edge            (sarrus-2-3)
          (sarrus-2-3)                          edge[->]        (sarrus-3-4)
          (sarrus-1-3)                          edge            (sarrus-2-4)
          (sarrus-2-4)                          edge[->]        (sarrus-3-5)
          (sarrus-3-1)                          edge[dashed]    (sarrus-2-2)
          (sarrus-2-2)                          edge[->,dashed] (sarrus-1-3)
          (sarrus-3-2)                          edge[dashed]    (sarrus-2-3)
          (sarrus-2-3)                          edge[->,dashed] (sarrus-1-4)
          (sarrus-3-3)                          edge[dashed]    (sarrus-2-4)
          (sarrus-2-4)                          edge[->,dashed] (sarrus-1-5);

    \foreach \c in {1,2,3} {\node[anchor=south] at (sarrus-1-\c.north) {$+$};};
    \foreach \c in {1,2,3} {\node[anchor=north] at (sarrus-3-\c.south) {$-$};};
  \end{tikzpicture}
  \end{figure}
     \catcode`(=\active
     \catcode`)=\active
     #+end_export
	 Achtung: Die Sarussche Regel gilt nicht für $n\geq 4$. Die LEibnizformel für $n = 4$ hat $4! = 24$ Terme.
  #+end_ex
  #+begin_proof latex
  1. Eindeutigkeit: Sei $A = \cvec{a_1;\vdots;a_n}$ mit Zeilenvektoren $a_1,\ldots, a_n\in K^n$
	 Für $i = 1,\ldots, n$ schrieben wir $a_i = a_{i1} e_1 + \ldots + a_{in} e_n$ ($e_i$ als Zeilenvektoren)
	 \begin{align*}
	 \implies \det(A) &= \det\cvec{a_1;\vdots;a_n} = \det\cvec{a_{11}e_1 + \ldots + a_{1n} e_n; a_2;\vdots;a_n} = \sum_{i_1 = 1}^{n}a_{1i}\det\cvec{e_{i1}; a_2;\vdots;a_n} \\
	 &= \sum_{i_1 = 1}^{n} a_{1 i_1} \sum_{i_2 = 1}^{n}a_{2 i_2} \det\cvec{e_{i_1};e_{i_2};a_3;\vdots; a_n} = \ldots = \sum_{i_1 = 1}^{n} \ldots \sum_{i_n = 1}^{n}a_{1 i_1} \cdot \ldots \cdot a_{n i_n} \det \cvec{e_{i_1};\vdots;e_{i_n}}
	 \end{align*}
	 Falls $\{i_1,\ldots, i_n\} \subsetneq \{1, \ldots, n\}$, danng gilt nach D2:
	 \[\det\cvec{e_{i_1}; \vdots; e_{i_n}} = 0\]
	 Falls $\{i_1,\ldots, i_n\} = \{1,\ldots, n\}$, dann existiert ein $\sigma\in S_n$ mit $\sigma(k) = i_k$ für $k = 1,\ldots, n$, und es ist
	 \[\det\cvec{e_{i_1};\vdots; e_{1_n}} = \det\cvec{e_{\sigma(1)};\vdots;e_{\sigma(n)}} = \sgn(\sigma)\]
	 und jedes $\sigma \in S_n$ kommt in obiger Summe genau einmal vor
	 \[\implies \det(A) = \sum_{\sigma\in S_n}\sgn(\sigma)a_{1\sigma(1)} \cdot \ldots \cdot a_{n\sigma(n)}\]
  2. Existenz: Wir definieren $\det:M(n\times n, K) \to K$ durch die Leibnizformel und müssen D1-D3
	 nachrechnen. \\
	 D1a:
	 \begin{align*}
	 \det\cvec{a_1;\vdots; a_i' + a_i'';\vdots; a_n} &= \sum_{\sigma\in S_n}\sgn(\sigma)a_{1 \sigma(1)} \cdot \ldots \cdot (a_{i \sigma(i)}' + a_{i\sigma(i)}'') \cdot\ldots \cdot a_{n\sigma(n)} \\
	 &= \sum_{\sigma\i S_n}\sgn(\sigma)a_{1\sigma(1)}\cdot \ldots \cdot a_{i\sigma(1)}' \cdot \ldots \cdot a_{n\sigma(n)} + \sum_{\sigma\in S_n} \sgn(\sigma) a_{1\sigma(1)}\cdot \ldots \cdot a_{i\sigma(1)}'' \cdot \ldots \cdot a_{n\sigma(n)} \\
	 &= \det\cvec{a_1;\vdots;a_i';\vdots;a_n} + \det\cvec{a_1;\vdots;a_i'';\vdots;a_n}
	 \end{align*}
	 D1b: analog \\
	 D2: Sei $A=\cvec{a_1;\vdots; a_n}\in M(n\times n,K)$ mit $a_k = a_l$ ohne Einschränkung $k < l$.
	 Sei
	 \[\tau = \begin{pmatrix} 1 & \ldots & k & \ldots & l & \ldots & n \\ 1 & \ldots & l & \ldots & k & \ldots & n\end{pmatrix}\in S_n\setminus A_n\]
	 dann ist $S_n = A_n \dot{\cup} A_n\tau$ nach 17.11. Ist $\sigma\in A_n$, dann ist $\sgn(\sigma) = 1, \sgn(\sigma\circ \tau) = -1$
	 \begin{align*}
	 \implies\det A =& \sum_{\sigma\in S_n}\sgn(\sigma)a_{1\sigma(1)}\cdot \ldots \cdot a_{n\sigma(n)} = \sum_{\sigma\in A_n}\sgn(\sigma) a_{1\sigma(1)}\cdot \ldots \cdot a_{n\sigma(n)} + \sum_{sigma\in A_n} \sgn(\sigma\circ \tau) a_{1, \sigma\circ\tau(1)}\cdot \ldots \cdot a_{n\sigma\circ\tau(n)} \\
	 =& \sum_{\sigma\in A_n}a_{1\sigma(1)}\cdot \ldots \cdot a_{n\sigma(n)} - \sum_{\sigma\in A_n}a_{1,\sigma\circ\tau(1)} \cdot \ldots \cdot a_{n\sigma\circ\tau(n)}
	 \intertext{Es ist}
	 & a_{1,\sigma\tau(1)}\cdot \ldots \cdot a_{k,\sigma\tau(k)}\cdot \ldots \cdot a_{l,\sigma\tau(l)}\cdot \ldots \cdot a_{n,\sigma\tau(n)} \\
	 =& a_{1,\sigma(1)}\cdot \ldots \cdot a_{k,\sigma(l)}\cdot \ldots \cdot a_{l,\sigma(k)}\cdot \ldots \cdot a_{n,\sigma\tau(n)} \\
	 =& a_{1,\sigma(1)}\cdot \ldots \cdot a_{l,\sigma(l)}\cdot \ldots \cdot a_{k,\sigma(k)}\cdot \ldots \cdot a_{n,\sigma\tau(n)} \\
	 =& a_{1,\sigma(1)}\cdot \ldots \cdot a_{n,\sigma\tau(n)} \\
	 &\implies \det(A) = 0
	 \end{align*}
	 D3: Sei
	 \[\delta_{ij} = \begin{cases} 1 & i = j \\ 0 & i\neq j\end{cases}\tag{Kronecker-Symbol, dann ist $E_n = (\delta_{ij})$}\]
	 und
	 \[\delta_{1,\sigma(1)}\cdot\ldots\cdot \delta_{n,\sigma(n)} = \begin{cases}0 & \sigma \neq id \\ 1 & \sigma = \id\end{cases}\implies\det(E_n) = \det((\delta_{ij})) = \sum_{\sigma\in S_n}\sgn(\sigma)\delta_{1\sigma(1)}\cdot \ldots \cdot \delta_{n\sigma(n)} = 1\]
  #+end_proof
  #+ATTR_LATEX: :options [17.14]
  #+begin_thm latex
  $A\in M(n\times n, K)$. Dann gilt:
  \[\det(A^T) = \det(A)\]
  #+end_thm
  #+begin_proof latex
  Sei $A = (a_{ij})$
  \[\implies \det(A^{T}) = \sum_{\sigma\in S_n} \sgn(\sigma) a_{\sigma(1)1} \cdot \ldots \cdot a_{\sigma(n)n} = \sum_{\sigma\in S_n}\sgn(\sigma) A_{1\sigma^{-1}(1)} \cdot \ldots \cdot a_{n\sigma^{-1}(n)}\]
  Die Abbildung $\psi:S_n \to S_n,\sigma\mapsto \sigma^{-1}$ ist bijektiv wegen $\psi \circ \psi = \id_{S_n}$.
   \[\implies \det(A^T) = \sum_{\sigma\in S_n}\sgn(\sigma) a_{1\sigma(1)}\cdot \ldots \cdot a_{n\sigma(n)} = \det(A)\]
  #+end_proof
  #+ATTR_LATEX: :options [17.15]
  #+begin_algorithm latex
  *Eingabe*: $A\in M(n\times n, K)$ \\
  *Ausgabe*: $\det(A)$ \\
  *Durchführung*:
  1. Bringe $A$ durch elementare Zeilen- und Spaltenumformungen vom Typ 3, 4 auf obere Dreiecksgestalt
	 \[B = \begin{pmatrix}\lambda_1 & & \ast \\ & \ddots & \\ 0 & & \lambda_n\end{pmatrix}\]
  2. Ist $k$ die Zahl der benötigten Vertauschungen von Zeilen und Spalten, dann ist
	 \[\det(A) = (-1)^{k}\lambda_1 \cdot \ldots \cdot \lambda_n\]
  #+end_algorithm
  #+begin_proof latex
  folgt aus 17.2, 17.12, 17.14.
  #+end_proof
  #+ATTR_LATEX: :options [17.16]
  #+begin_defn latex
  $A = (a_{ij}) \in M(n\times n, K)$
  \begin{gather*}
  A_{ij} :=
  \begin{pmatrix}
  a_{1,1} & \ldots & a_{1,j - 1} & 0 & a_{1, j + 1} & \ldots & a_{1,n} \\
  \vdots & & & \vdots & & & \\
  a_{i - 1,1} & \ldots & a_{i - 1, j - 1} & 0 & a_{i - 1, j + 1} & \ldots & a_{i - 1, n} \\
  0 & \ldots & 0 & 1 & 0 & \ldots & 0 \\
  a_{i + 1,1} & \ldots & a_{i + 1, j - 1} & 0 & a_{i + 1, j + 1} & \ldots & a_{i + 1, n} \\
  \vdots & & & \vdots & & & \\
  a_{n,1} & \ldots & a_{n,j - 1} & 0 & a_{n, j + 1} & \ldots & a_{n,n} \\
  \end{pmatrix} \\
  a_{ij}^\# := \det(A_{ji}) \in K \\
  A^\# := (a_{ij}^\#) \in M(n\times n, K) = (\det(A_{ij}))^T \\
  \intertext{$A^\#$ heißt die zu $A$ komplementäre Matrix:}
  A_{ij}' :=
  \begin{pmatrix}
  a_{1,1} & \ldots & a_{1,j - 1} & a_{1,j + 1} & \ldots & a_{1, n}\\
  \vdots & & \vdots & \vdots & & \vdots \\
  a_{i-1,1} & \ldots & a_{i-1,j - 1} & a_{i-1,j + 1} & \ldots & a_{1-1, n}\\
  a_{i+1,1} & \ldots & a_{i+1,j - 1} & a_{i+1,j + 1} & \ldots & a_{1+1, n}\\
  \vdots & & \vdots & \vdots & & \vdots \\
  a_{n,1} & \ldots & a_{n,j - 1} & a_{n,j + 1} & \ldots & a_{n, n}\\
  \end{pmatrix} \in M((n - 1) \times (n - 1),K)
  \end{gather*}
  #+end_defn
  #+ATTR_LATEX: :options [17.17]
  #+begin_ex latex
  \begin{gather*}
  A = \begin{pmatrix} 1 & 2 \\ 3 & 4\end{pmatrix} \\
  A_{11} = \begin{pmatrix} 1 & 0 \\ 0 & 4\end{pmatrix}, A_{12} = \begin{pmatrix} 0 & 1 \\ 3 & 0\end{pmatrix}, A_{21} = \begin{pmatrix} 0 & 2 \\ 1 & 0\end{pmatrix}, A_{22} = \begin{pmatrix} 1 & 0 \\ 0 & 1\end{pmatrix} \\
  A^\# = \begin{pmatrix} 4 & -3 \\ -2 & 1\end{pmatrix}^{T} = \begin{pmatrix}4 & -2 \\ -3 & 1\end{pmatrix}
  \end{gather*}
  #+end_ex
  #+ATTR_LATEX: :options [17.18]
  #+begin_remark latex
  $A \in M(n\times n, K), i, j \in \{1, \ldots, n\}$. Dann gilt:
  \[\det(A_{ij}) = (-i)^{i + j} \det(A_{ij}')\]
  #+end_remark
  #+begin_proof latex
  Durch $i - 1$ Vertauschungen benachbarter Zeilen und $j - 1$ Vertauschungen benachbarter Spalten
  kann man $A_{ij}$ auf die Form
  \[\begin{pmatrix} 1 & 0 \\ & 0 & A_{ij}\end{pmatrix}\]
  bringen $\implies$
  \[\det(A_{ij}) = (-1)^{i - 1 + j - 1} \det(A_{ij}') = (-1)^{i + j}\det{A_{ij}'}\]
  #+end_proof
  #+ATTR_LATEX: :options [17.19]
  #+begin_remark latex
  $A = (a^1, \ldots, a^n) \in M(n\times n, K)$ mit Spaltenvektoren $a^1, \ldots, a^n$,
  \[e^i := \cvec{0;\vdots;1;\vdots;0}\]
  Dann gilt:
  \[\det(A_{ij}) = \det((a^1, \ldots, a^{j - 1}, e^i, a^{j + 1}, \ldots, a^n))\]
  #+end_remark
  #+begin_proof latex
  Führe $(a^i, \ldots, a^{j - 1}, e^i, a^{j + 1}, \ldots, a^n)$ durch Addition von geeigneten Vielfachen
  der j-ten Spalte in $A_{ij}$ über ("i-te Zeile ausräumen") $\xRightarrow{\text{D7}}$ Behauptung
  #+end_proof
  #+ATTR_LATEX: :options [17.20]
  #+begin_thm latex
  $A\in M(n\times n, K)$. Dann gilt:
  \[A \cdot A^\# = \det(A) \cdot E_n = A^\# \cdot A\]
  #+end_thm
  #+begin_proof latex
  Sei $A = (a^i, \ldots, a^n) = (a_{ij})$. Es ist $A^\# A = (b_{ik})$ mit
  \begin{align*}
  b_{ij} &= \sum_{j = 1}^{n} a_{ij}^\# a_{ik} = \sum_{j = 1}^{n}a_{jk} \det(A_{ji}) = \sum_{j = 1}^{n} a_{jk} \det((a^1, \ldots, a^{i - 1}, e^j, a^{i + 1}, \ldots, a^n)) \\
  &= \det((a^1, \ldots, a^{i - 1}, \underbrace{\sum_{j = 1}^{n} a_{jk}e^j}_{a^k}, a^{i + 1}, \ldots, a^n)) = \delta_{ij} \det(A)
  \end{align*}
  \[\implies A^\# \cdot A = \det(A) E_n\]
  Analog: $A\cdot A^\# = \det(A) E_n$.
  #+end_proof
  #+ATTR_LATEX: :options [17.21 Entwicklungssatz von Laplace]
  #+begin_thm latex
  $n\geq 2, A\in M(n\times n, K)$. Dann gilt: Für jede $i \in \{1, \ldots, n\}$ ist
  \[\det(A) = \sum_{j = 1}^{n} (-1)^{i + j} a_{ij} \det(A_{ij}')\tag{Entwicklung nach der i-ten Zeile}\]
  und für jedes $j\in\{1, \ldots, n\}$ ist
  \[\det(A) = \sum_{i = 1}^{n} (-1)^{i + j} a_{ij} \det(A_{ij}')\tag{Entwicklung nach der j-ten Spalte}\]
  #+end_thm
  #+begin_proof latex
  Nach 17.20 ist $A\cdot A^\# = \det(A) = E_n$, insbesondere ist für jedes $i\in \{1, \ldots, n\}$:
  \[\det(A) = \sum_{j = 1}^{n} a_{ij} a_{ij}^\# = \sum_{j = 1}^{n} a_{ij} \det(A_{ij}) = \sum_{j = 1}^{n}(-1)^{i + j} a_{ij} \det(A_{ij}')\]
  Analog für Entwicklung nach j-ten Spalte über $A^\# \cdot A = \det(A) E_n$
  #+end_proof
  #+ATTR_LATEX: :options [17.22]
  #+begin_ex latex
  \begin{align*}
  \det\begin{pmatrix}
  -2 & 2 & 3 \\
  -1 & 1 & 1 \\
  -1 & 0 & 1 \\
  \end{pmatrix}
  &= (-1)^{1 + 2} \cdot 2 \cdot \det \begin{pmatrix} -1 & 1 \\ -1 & 1\end{pmatrix} +
  (-1)^{2 + 2} \cdot 2 \cdot \det \begin{pmatrix} -2 & 3 \\ -1 & 1\end{pmatrix} +
  (-1)^{3 + 2} \cdot 0 \cdot \det \begin{pmatrix} -2 & 3 \\ -1 & 1\end{pmatrix} \\
  &= 0 + \det\begin{pmatrix} -2 & 3 \\ -1 & 1\end{pmatrix} + 0 = (-2)1 -4(-1) = 1
  \end{align*}
  #+end_ex
  #+begin_note latex
  - Versuche, nach Zeilen beziehungsweise Spalten mit möglichst vielen Nullen zu entwickeln.
  - Vorzeichenverteilung durch $(-1)^{i + j}$:
	\[\begin{pmatrix} + & - & + & \\ - & + & & \\ + & & \ddots & \\ \end{pmatrix}\]
  #+end_note
  #+ATTR_LATEX: :options [17.23]
  #+begin_thm latex
  $A\in GL(n, K)$. Dann gilt:
  \[A^{-1} = \frac{1}{\det(A)} A^\# = \frac{1}{\det(A)} B^T\]
  wobei
  \[B = (\det(A_{ij})) = ((-1)^{i + j} \det A_{ij}')\]
  #+end_thm
  #+begin_proof latex
  folgt aus 17.20
  #+end_proof
  #+ATTR_LATEX: :options [17.24]
  #+begin_ex latex
  Sei
  \[A = \begin{pmatrix} a & b \\ c & d\end{pmatrix} \in GL(2, K)\]
  \[\implies A^{-1} = \frac{1}{ad - bc} \begin{pmatrix}d & -c \\ -b & a\end{pmatrix}^{T} = \frac{1}{ad - bc} \begin{pmatrix} d & -b \\ -c & a\end{pmatrix}\]
  #+end_ex
  #+ATTR_LATEX: :options [17.25 Cramersche Regel]
  #+begin_thm latex
  $A = (a^1, \ldots, a^n) \in GL(n, K), b\in K^n, x\in\cvec{x_1;\vdots;x_n}\in K^n$ Sei die eindeutig
  bestimmte Lösung des LGS $Ax = b$ (es ist $x = A^{-1}b$)
  Dann: für jedes $i \in \{1, \ldots, n\}$ ist
  \[x_1 = \frac{\det(a^1, \ldots, a^{i - 1}, b, a^{i + 1}, \ldots, a^n)}{\det(A)}\]
  #+end_thm
  #+begin_proof latex
  Es ist $x = A^{-1} b$, und $A^{-1} = (d_{ij})$ mit $d_{ij} = \frac{1}{\det(A)} a_{ij}^\#$, also
  \[\d_{ij} = \frac{1}{\det(A)} \det(A_{ji}) = \frac{\det(a^1, \ldots, a^{i - 1}, e^j, a^{i + 1}, \ldots, a^n)}{\det(A)}\]
  \begin{align*}
  \implies x_i &= \sum_{j = 1}^{n} d_{ij} b_j = \sum_{j = 1}^{n} b_j \frac{\det(a^1, \ldots, a^{i - 1}, e^j, a^{i + 1}, \ldots, a^n)}{\det(A)} \\
  &= \frac{\det(a^1, \ldots, a^{i - 1}, \sum_{j = 1}^{n}b_j e^j, a^{i + 1}, \ldots, a^n)}{\det(A)} = \frac{\det(a^1,\ldots, a^{i - 1}, b, a^{i + 1}, \ldots, a^n)}{\det(A)}
  \end{align*}
  #+end_proof
  #+ATTR_LATEX: :options [17.26]
  #+begin_ex latex
  Wir betrachten das reelle $3\times 3$ LGS
  \[\underbrace{\begin{pmatrix}-2 & 2 & 3 \\ -1 & 1 & 1 \\ -1 & 0 & 1\end{pmatrix}}_{=:A}\cvec{x_1;x_2;x_3} = \underbrace{\cvec{1;2;0}}_{=: b}\]
  Nach Beispiel 17.22 ist $\det(A) = 1$
  \begin{align*}
  \implies x_1 &= \det \begin{pmatrix}1 & 2 & 3 \\ 2 & 1 & 1 \\ 0 & 0 & 1\end{pmatrix} = 1\det\begin{pmatrix}1 & 2 \\ 2 & 1\end{pmatrix} = -3 \\
  x_2 &= \det\begin{pmatrix}-2 & 2 & 3 \\ -1 & 1 & 1 \\ -1 & 0 & 1\end{pmatrix} = 1(-1)\det\begin{pmatrix}1 & 3 \\ 2 & 1\end{pmatrix} + 1 \cdot 1 \det\begin{pmatrix} -2 & 1 \\ -1 & 2\end{pmatrix} = 5 + (-3) = 2 \\
  x_3 &= \det\begin{pmatrix}-2 & 2 & 3 \\ -1 & 1 & 1 \\ -1 & 0 & 1\end{pmatrix} = 1(-1)\det\begin{pmatrix}2 & 1 \\ 1 & 2\end{pmatrix} = -3
  \end{align*}
  #+end_ex
  #+begin_note latex
  In der Praxis findet die Cramersche Regel wegend er vielen zu berechnenden Determinanten kaum Anwendung.
  #+end_note
  #+ATTR_LATEX: :options [17.27]
  #+begin_defn latex
  $V$ endlichdimensionaler K-VR, $f\in\End_K(V)$. Wir wählen eine Basis $\mathcal{B}$ von $V$ und setzen
  \[\det(f) := \det(M_{\mathcal{B}}(f))\]
  Dann gilt:
  1. $\det(f)$ ist wohldefiniert.
  2. $f$ ist ein Isomorphismus $\iff \det(f)\neq 0$
  #+end_defn
  #+begin_proof latex
  1. Sei $\mathcal{A}$ eine weitere Basis von $V, S:= T_{\mathcal{A}}^{\mathcal{B}}$
	 \begin{align*}
	 \implies M_{\mathcal{A}}(f) = S M_{\mathcal{B}}(f) S^{-1} \implies \det(M_{\mathcal{A}}(f)) &= \det(M_{\mathcal{B}}(f)S^{-1}) = \det(S)\det(M_{\mathcal{B}}(f))\det(S^{-1}) \\
	 &= \det(S)\det(S^{-1})\det(M_{\mathcal{B}}(f)) = \det(M_{\mathcal{B}}(f))
     \end{align*}
  2. $f$ Isomorphismus
	 \begin{align*}
	 &\iff \Phi_{\mathcal{B}}^{-1} \circ f \circ \Phi_{\mathcal{B}} = \reallywidetilde{M_{\mathcal{B}}(f)}~\text{Isomorphismus} \\
	 &\iff M_{\mathcal{B}}(f) \in GL(n, K) \\
	 &\iff \det(M_{\mathcal{B}}(f)) \neq 0 \\
	 &\iff \det(f) \neq 0
	 \end{align*}
  #+end_proof
  #+begin_note latex
  Ist $R$ ein kommutativer Ring, dann kann man (in Analogie zu $M(n\times n, K)$ für einen Körper $K$)
  den Ring $M(n\times n, R)$ der $n\times n$ -Matrizen mit Einträgen in $R$ betrachten. Im Beweis von 17.12 wird nicht dividiert.
  Somit: Definiert man
  \[\det: M(n\times n, R) \to R, \det(A) = \sum_{\sigma\in S_n}\sgn(\sigma) a_{1\sigma(1)} \cdot \ldots \cdot A_{n\sigma(n)}, A = (a_{ij})\]
  dann sind D1-D3 (für $R$ statt $K$) erfüllt. (und man kann zeigen: D4 - D9, D11 sind erfüllt, $\det(A) = \det(A^T), A\cdot A^\# = A^\# \cdot A = \det(A) E_n$, Entwicklungssatz von Laplace)
  #+end_note
