#+AUTHOR: Robin Heinemann
#+TITLE: Lineare Algebra (Vogel)
#+OPTIONS: H:6
#+LATEX_CLASS: koma-article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage{siunitx}
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \sisetup{load-configurations = abbrevations}
#+LATEX_HEADER: \newcommand{\estimates}{\overset{\scriptscriptstyle\wedge}{=}}
#+LATEX_HEADER: \usepackage{mathtools}
#+LATEX_HEADER: \DeclarePairedDelimiter\abs{\lvert}{\rvert}%
#+LATEX_HEADER: \DeclarePairedDelimiter\norm{\lVert}{\rVert}%
#+LATEX_HEADER: \DeclareMathOperator{\Exists}{\exists}
#+LATEX_HEADER: \DeclareMathOperator{\Forall}{\forall}
#+LATEX_HEADER: \DeclareMathOperator{\cha}{char}
#+LATEX_HEADER: \def\colvec#1{\left(\vcenter{\halign{\hfil$##$\hfil\cr \colvecA#1;;}}\right)}
#+LATEX_HEADER: \def\colvecA#1;{\if;#1;\else #1\cr \expandafter \colvecA \fi}
#+LATEX_HEADER: \usepackage{stmaryrd}
#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER: \theoremstyle{definition}
#+LATEX_HEADER: \newtheorem{defn}{Definition}
#+LATEX_HEADER: \theoremstyle{plain}
#+LATEX_HEADER: \newtheorem{thm}{Satz}
#+LATEX_HEADER: \theoremstyle{plain}
#+LATEX_HEADER: \newtheorem{lemma}{Lemma}
#+LATEX_HEADER: \theoremstyle{remark}
#+LATEX_HEADER: \newtheorem{remark}{Bemerkung}
#+LATEX_HEADER: \theoremstyle{remark}
#+LATEX_HEADER: \newtheorem{conc}{Folgerung}
#+LATEX_HEADER: \theoremstyle{remark}
#+LATEX_HEADER: \newtheorem{ex}{Beispiel}
#+LATEX_HEADER: \usepackage{etoolbox}
#+LATEX_HEADER: \patchcmd{\thmhead}{(#3)}{#3}{}{}
#+LATEX_HEADER: \renewcommand*{\proofname}{Beweis}
#+LATEX_HEADER: \usepackage{wasysym}
#+LATEX_HEADER: \usepackage{xparse}% http://ctan.org/pkg/xparse
#+LATEX_HEADER: \NewDocumentCommand{\overarrow}{O{=} O{\uparrow} m}{%
#+LATEX_HEADER:  \overset{\makebox[0pt]{\begin{tabular}{@{}c@{}}#3\\[0pt]\ensuremath{#2}\end{tabular}}}{#1}
#+LATEX_HEADER: }
#+LATEX_HEADER: \NewDocumentCommand{\underarrow}{O{=} O{\downarrow} m}{%
#+LATEX_HEADER:  \underset{\makebox[0pt]{\begin{tabular}{@{}c@{}}\ensuremath{#2}\\[0pt]#3\end{tabular}}}{#1}
#+LATEX_HEADER: }

* Einleitung
  # Passwort für Downloads (Webseite Prof. Gade): GRUNDVORLESUNG
  Übungsblätter/Lösungen:
  jew. Donnerstag / folgender Donnerstag
  Abgabe Donnerstag 9:30
  50% der Übungsblätter
** Plenarübung
   Aufgeteilt
** Moodle
   Passwort: vektorraumhomomorphismus
** Klausur
   24.02.2017
* Grundlagen
** Naive Aussagenlogik
   naive Logik: wir vewenden die sprachliche Vorstellung ($\neq$ mathematische Logik: eigne Vorlesung)
   Eine Aussage ist ein festehender Satz, dem genau einer der Wahrheitswerte "wahr" oder "falsch" zugeordnet werden kann.
   Aus einfachen Aussagen kann man durch logische Verknüpfungen kompliziertere Aussagen bilden.
   Angabe der Wahrheitswertes der zusammengesetzten Aussage erfolgt duch Wahrheitstafeln (liefern den Wahrheitswert der zusammengesetzten Aussage, aus dem Wahrheitswert der einzelnen Aussagen).
   Im folgenden seien $A$ und $B$ Aussagen.
   - Negation (NICHT-Verknüpfung)
	 - Symbol: $\neg
     - Wahrheitstafel:
       | $A$ | $\neg A$ |
       |-----+----------|
       | w   | f        |
       | f   | w        |
	 - Beispiel: $A$: 7 ist eine Primzahl (w)
	   $\neg A$: 7 ist keine Primzahl (f)

   - Konjunktion (UND-Verknüpfung)
	 - Symbol $\wedge$
	 - Wahrheitstafel:
       | $A$ | $B$ | $A\wedge B$ |
       |-----+-----+-------------|
       | w   | w   | w           |
       | w   | f   | f           |
       | f   | w   | f           |
       | f   | f   | f           |

   - Disjunktion (ODER-Verknüpfung)
	 - Symbol: $\vee$
	 - Wahrheitstafel:
       | $A$ | $B$ | $A\vee B$ |
       |-----+-----+-----------|
       | w   | w   | w         |
       | w   | f   | w         |
       | f   | w   | w         |
       | f   | f   | f         |
	 - exklusives oder: $(A\vee B) \wedge (\neg(A\wedge B))$
   - Beispiel $A$: 7 ist eine Primzahl (w), $B$: 5 ist gerade (f)
	 - $A\wedge B$ 7 ist eine Primzahl und 5 ist gerade (f)
	 - $A\vee B$ 7 ist eine Primzahl oder 5 ist gerade (w)

   - Implikation (WENN-DANN-Verknüpfung)
	 - Symbol: $\Rightarrow$
	 - Wahrheitstafel:
       | $A$ | $B$ | $A\Rightarrow B$ |
       |-----+-----+------------------|
       | w   | w   | w                |
       | w   | f   | f                |
       | f   | w   | w                |
       | f   | f   | w                |
	 - Sprechweise: $A$ impliziert $B$, aus $A$ folgt $B$, $A$ ist eine hinreichende Bedingung für $B$ (ist $A\Rightarrow B$ wahr, dann folgt aus $A$ wahr, $B$ ist wahr), $B$ ist eine notwendige Bedingung für $A$ (ist $A\Rightarrow B$ wahr, dann kann $A$ nur dann wahr sein, wenn Aussage $B$ wahr ist)
	 - Beispiel Es seinen $m,n\in\mathbb{N}$
	   - $A$: m ist gerade
	   - $B$: $mn$ ist gerade
	   - Dann gilt $\Forall m,n \in\mathbb{N}~A\Rightarrow B~\text{wahr}$ \\
		 Fallunterscheidung:
		 - $m$ gerade, $n$ gerade, dann ist $A$ wahr, $B$ wahr, d.h. $A\Rightarrow B$ wahr
		 - $m$ gerade, $n$ ungerade, dann ist $A$ wahr, $B$ wahr, d.h. $A\Rightarrow B$ wahr
		 - $m$ ungerade, $n$ gerade, dann ist $A$ falsch, $B$ wahr, d.h. $A\Rightarrow B$ wahr
		 - $m$ ungerade, $n$ ungerade, dann ist $A$ falsch, $B$ falsh, d.h. $A\Rightarrow B$ wahr
   - Äquivalenz (GENAU-DANN-WENN-Verknüpfung)
	 - Symbol $\Leftrightarrow$
	 - Wahrheitstafel:
       | $A$ | $B$ | $A\Leftrightarrow$ B |
       |-----+-----+----------------------|
       | w   | w   | w                    |
       | w   | f   | f                    |
       | f   | w   | f                    |
       | f   | f   | w                    |
	 - Sprechweise: $A$ gilt genau dann, wenn $B$ gilt, $A$ ist hinreichend und notwendig für $B$ \\
	   Die Aussagen $A\Leftrightarrow B$ und $(A\Rightarrow B)\wedge (B\Rightarrow A)$ sind gleichbedeutend:
       | $A$ | $B$ | $A\Leftrightarrow B$ | $A\Rightarrow B$ | $B\Rightarrow A$ | $(A\Rightarrow B)\wedge (B\Rightarrow A)$ |
       |-----+-----+----------------------+------------------+------------------+-------------------------------------------|
       | w   | w   | w                    | w                | w                | w                                         |
       | w   | f   | f                    | f                | w                | f                                         |
       | f   | w   | f                    | w                | f                | f                                         |
       | f   | w   | f                    | w                | f                | f                                         |
       | f   | f   | w                    | w                | w                | w                                         |
	 - Beispiel: Es sei $n$ eine ganze Zahl \\
	   $A:~n-2>1$ \\
	   $B:~n>3$ \\
	   $\Forall n\in\mathbb{N}~\text{gilt}~A\Leftrightarrow B$
	   $C:~n>0$ \\
	   $D:~n^2>0$ \\
	   Für $n=-1$ ist die Äquivalenz $C\Leftrightarrow$ falsch ($C$ falsch, $D$ wahr) \\
	   Für alle ganzen Zahlen $n$ gilt zumindest die Implikation $C\Rightarrow D$
** Beweis
   Mathematische Sätze, Bemerkungen, Folgerungen, etc. sind meistens in Form wahrer Implikationen formuliert
*** beweisen
	Begründen warum diese Implikation wahr ist
*** Beweismethoden for diese Implikation $A\Rightarrow B$
	- direkter Beweis ($A\Rightarrow B$)
	- Beweis durch Kontraposition ($\neq B \Rightarrow \neg A$)
	- Widerspruchbeweis ($\neg (A\wedge \neg B)$)
    Diese sind äquivalent zueinander
    | $A$ | $B$ | $\neg A$ | $\neg B$ | $A\Rightarrow B$ | $\neg B \Rightarrow \neg A$ | $\neg (A \wedge \neg B)$ |
    |-----+-----+----------+----------+------------------+-----------------------------+--------------------------|
    | w   | w   | f        | f        | w                | w                           | w                        |
    | w   | f   | f        | w        | f                | f                           | f                        |
    | f   | w   | w        | f        | w                | w                           | w                        |
    | f   | f   | w        | w        | w                | w                           | w                        |
**** Beispiel
	 $m,n$ natürliche Zahlen \\
	 \[A:~m^2 < n^2\]
	 \[B:~m < n\]
	 Wir wollen zeigen, dass $A\Rightarrow B$ für alle natürlichen Zahlen $m,n$ wahr ist
	 - direkter Beweis: \\
	   \[A:~m^2 < n^2 \Rightarrow 0 < n^2 - m^2 \Rightarrow 0 < (n-m)\underbrace{(n+m)}_{>0} \Rightarrow 0 < n-m \Rightarrow m<n\]
	 - Beweis durch Kontraposition: \\
	   \[\neg B:~m \geq n \Rightarrow m^2\geq n m \wedge m n \geq n^2 \Rightarrow m^2 \geq n^2 \Rightarrow \neg A\]
	 - Beweis durch Widerspruch: \\
	   \[A\wedge \neg B \Rightarrow m^2 < n^2 \wedge n\leq m \Rightarrow m^2 < n^2 \wedge m n \leq m^2 \wedge n^2 \leq m n \Rightarrow m n \leq m^2 < n^2 \leq m n\]
	   Wiederspruch
** Existenz- und Allquantor
*** Existenzquantor
	$A(x) Aussage, die von Variable x abhängt \\
	$\exists x:~A(x)$ ist gleichbedeutend mit "Es existiert ein x, für das $A(x)$ wahr ist" (hierbei ist "existiert ein x" im Sinne von "existiert mindestens ein x" zu verstehen) \\
	Beispiel:
	\[\exists n\in\mathbb{N}:~n>5\quad\text{(w)}\]
	$\exists !x:~A(x)$ ist gleichbedeutend mit "Es existiert genau ein x, für dass $A(x)$ wahr ist" 
*** Allquantor
	$\Forall x:~A(x)$ ist gleichbedeutend mit "Für alle x ist A(x) wahr"
	Beispiel:
	\[\Forall n\in\mathbb{N}: 4n~\text{ist gerade}\]
*** Negation von Existenz- und Allquantor
	\[\neg(\exists x:~A(x)) \Leftrightarrow \Forall x:~\neg A(x)\]
	\[\neg(\Forall x:~A(x)) \Leftrightarrow \exists x:~\neg A(x)\]
*** Spezielle Beweistechniken für Existenz und Allaussagen
	- Angabe eines Beispiel, um zu zeigen, dass deine Existenzaussage wahr ist. \\
	  Beispiel:
	  \[\exists n\in\mathbb{N}:~n>5 \text{ist wahr, denn für $n = 7$ ist die Aussage $n > 5$ wahr}\]
	- Angabe eines Gegenbeispiel, um zu zeigen, dass eine Allausage falsch ist. \\
	  Beispiel:
	  \[\Forall n\in\mathbb{N}:~n\leq 5 \text{ist flasch, dann für $n=7$ ist die Aussage $n\leq 5$ falsch}\]
** Naive Mengenlehre
   Mengenbegriff nach Cantor: \\
   Eine Menge ist eine Zusammenfassung von bestimmten, wohlunterschiedenen Objekten userer Anschauung oder useres Denkens (die Elemente genannt werden) zu einem Ganzen

*** Schreibweise
   - $x\in M$, falls $x$ ein Element von $M$ ist
   - $x\not\in M$, falls $x$ kein Element von $M$ ist
   - $M=N$, falls $M$ und $N$ die gleichen Elemente besitzen, $M\subseteq N \wedge N\subseteq M$

***  Angabe von Mengen
   - Reihenfolge ist unrelevant ($\{1,2,3\}=\{1,3,2\})
   - Elemente sind wohlunterschieden $\{1,2,2\} = \{1,2\}$
   - Auflisten der Elemente $M=\{a,b,c,\ldots\}$
   - Beschreibung der Elemente durch Eigenschaften: $M=\{x\mid E(x)\}$ \\
	 (Elemente x, für die E(x) wahr)
	 - Beispiel:
	   \[\{2,4,6,8\} = \{x\mid x\in\mathbb{N}, x~\text{gerade}, 1 < x < 10\}\]
*** leere Menge
	Die leere Menge $\emptyset$ enthält keine Elemente
**** Beispiel
	 \[\{x\mid x\in\mathbb{N}, x < -5\} = \emptyset\]

*** Zahlenbereiche
	Menge der natürlichen Zahlen:
	\[\mathbb{N} := \{1,2,3,\ldots\}\]

	Menge der natürlichen Zahlen mit Null:
	\[\mathbb{N}_0 := \{0, 1,2,3,\ldots\}\]

	Menge der Ganzen Zahlen:
	\[\mathbb{Z} := \{0,1,-1,2,-2\}\]

	Menge der rationalen Zahlen:
	\[\mathbb{Q} := \{\frac{m}{n} \mid m\in\mathbb{Z}, n\in\mathbb{N}\}\]

	Menge der reellen Zahlen: $\mathbb{R}$

*** Teilmenge
	$A,B$ seien Mengen. \\
	$A$ heißt Teilmenge von $B~(A\subseteq B) \xLeftrightarrow{\text{Def.}} \Forall x\in A: x\in B$
	$A$ heißt echte Teilmenge von $B~(A\subset B) \xLeftrightarrow{\text{Def.}} A\subseteq B \wedge A\neq B$
**** Anmerkung
	 Offenbar gilt für Mengen $A,B$:
	 \[A=B \Leftrightarrow A\subseteq B \wedge B\subseteq A\]
	 $\emptyset$ ist Teilmenge jeder Menge

**** Beipspiel
	 \[\mathbb{N}\subset\mathbb{N}_0\subset\mathbb{Z}\subset\mathbb{Q}\]

*** Durschnitt
	\[A \cap B := \{x\mid x\in A \wedge x\in B\}\]
**** Beispiel
	 \[A=\{2,3,5,7\}, B=\{3,4,6,7\}, A\cap B = \{3,7\}\]

*** Vereinigung
	\[A\cup B := \{x\mid x\in A \vee x\in B\}\]
**** Beispiel
	 \[A=\{2,3,5,7\}, B=\{3,4,6,7\}, A\cup B = \{2,3,4,5,6,7\}\]

*** Differenz
	\[A\setminus B := \{x\mid x\in A \wedge x\not\in B\}\]
	Im Fall $B\subseteq A$ nennt man $A\setminus B$ auch das Komplement von $B$ in $A$ und schreibt $\mathcal{c}_A(B) = A\setminus B$
**** Beispiel
	 \[A=\{2,3,5,7\}, B=\{3,4,6,7\}, A\setminus B = \{2,5\}\]
*** Bemerkung zu Vereinigung und Durschnitt
	$A,B$ seien zwei Mengen. Dann gilt \[A\cap (B\cup C) = (A\cap B) \cup (A\cap C)\]
**** Beweis
	 \[A\cap(B\cup C) \subseteq (A\cap B) \cup (A\cap C)\]
	 \[A\cap(B\cup C) \supseteq (A\cap B) \cup (A\cap C)\]
	 "$\subseteq$" Sei $x\in A \cap (B\cup C)$. Dann ist $x\in A \wedge x\in B\cup C$
	 - 1. Fall: $x\in A \wedge x\in B$
	   \[\Rightarrow x\in A\cap B \Rightarrow x \in (A\cap B) \cup (A\cap C)\]
	 - 2. Fall $x\in A \wedge x\in C$
	   \[\Rightarrow x\in A\cap C \Rightarrow x\in (A\cap B)\cup(A\cap C)\]
	 Damit ist "$\subseteq$" gezeigt.
	 "$\supseteq$" Sei $x\in (A\cap B) \cup (A\cap C)
	 \[\Rightarrow x\in A\cap B \vee x\in A\cap C \\ \Rightarrow (x\in A \wedge x\in B) \vee (x\in A \wedge x\in C) \\ \Rightarrow x\in A \wedge (x\in B\vee x\in C) \\ \Rightarrow x\in A \wedge x\in B\cup C \\ \Rightarrow x\in A\cap (B\cup C)\]
	 Damit ist "$\supseteq$" gezeigt.
*** Bemerkung zu Äquivalenz von Mengen
	Seien $A,B$ Mengen, dann sind äquivalent:
	1) $A\cup B = B$
	2) $A\subseteq B$
**** Beweis
	 Wir zeigen 1) $\Rightarrow$ 2) und 2) $\Rightarrow$ 1.
	 \[1) \Rightarrow 2):~\text{Es gelte}~A\cup B = B,~\text{zu zeigen ist}~A\subseteq B \\ \text{Sei}~x\in A \Rightarrow x\in A \wedge x \in B \Rightarrow x\in A\cup B = B\]
	 \[2) \Rightarrow 1):~\text{Es gelte}~A\subseteq B\text{, zu zeigen ist}~A\cup B = B \]
	 "$\subseteq$": Sei $x\in A\cup B \Rightarrow x\in A \vee x\in B \xRightarrow{A\subseteq B} x\in B$
	 "$\supseteq$": $B\subseteq A\cup B$ klar
*** Kartesisches Produkt
	Seien $A,B$ Mengen
	\[A\times B := \{(a,b)\mid a\in A, b\in B\}\]
	heipt das kartesische Produkt von $A$ und $B$. Hierbei ist $(a,b) = (a',b') \xLeftrightarrow{\text{Def}} a = a' \wedge b = b'$ a = a' \wedge b = b'$

**** Beispiel
	 - \[\{1,2\}\times \{1,3,4\} = \{(1,1),(1,3),(1,4),(2,1),(2,3),(2,4)\}\]
	 - \[\mathbb{R}\times\mathbb{R}=\{(x,y)|mid x,y \in \mathbb{R}\} = \mathbb{R}^2\]
*** Potenzmenge
	$A$ sei eine Menge
	\[\mathcal{P} (A) := \{M\mid M\subseteq A\}\]
	heißt die Potenzmenge von $A$
**** Beispiel
	 \[\mathcal{P} (\{1,2,3\}) =  \{\emptyset, \{1\}, \{2\},\{3\},\{1,2\},\{1,3\},\{2,3\}\{1,2,3,4\}\}\]
*** Kardinalität
	$M$ sei eine Menge. Wir setzen
	\[\abs{M} := \begin{cases} n & \text{falls $M$ eine endliche Menge ist und $n$ Elemente enthält} \\ \infty & \text{falls $M$ nicht endlich ist} \end{cases}\]
	$\abs{M}$ heißt Kardinalität von A
**** Beispiel
	 - $\abs{\{7,11,16\}} = 3$
	 - $\abs{\mathbb{N}} = \infty$
*** Bemerkung zu natürlichen Zahlen
	Für die natürlichen Zahlen gilt das Induktionsaxiom
	Ist $M\subseteq N$ eine Teilmenge, für die gilt:
	\[1\in M \wedge \Forall n\in M : n\in M \Rightarrow n+1 \in M\]
	dann ist $M = \mathbb{N}$
*** Prinzip der vollständigen Induktion
	Für jedes $n\in \mathbb{N}$ sei eine Aussage $A(n)$ gegeben. Die Aussagen $A(N)$ gelten für alle $n\in\mathbb{N}$, wenn man folgendes zeigen kann: \\
	- (IA) $A(1)$ ist wahr
	- (IS) Für jedes $n\in\mathbb{N}$ gilt: $A(n) \Rightarrow A(n+1)$
    Der Schritt (IA) heißt Induktionsanfang, die Implikation $A(n) \Rightarrow A(n+1)$ heißt Induktionsschritt
**** Beweis
	 Setze $M := \{n\in \mathbb{N}\mid A(n)~\text{ist wahr}\}$
	 Wegen (IA) ist $1\in M$, wegen (IS) gilt: $n\in M \Rightarrow n+1 \in M$ \\
	 Nach Induktionsaxiom folgt $M = \mathbb{N}$, das heißt $A(n)$ ist wahr für alle $n\in \mathbb{N}$
**** Beispiel
	 Für $n\in\mathbb{N}$ sei $A(n)$ die Aussage: $1+\ldots + n = \frac{n(n+1)}{2}$
	 Wir zeigen: $A(n)$ ist wahr für alle $n\in \mathbb{N}$, und zwar durch vollständige Induktion
	 - (IA) $A(1)$ ist wahr, denn $1 = \frac{1(1+1)}{2}$
	 - (IS) zu zeigen: $A(n) \Rightarrow A(n+1)$ \\
	   Es gelte $A(n)$, das heißt $1+\ldots+n = \frac{n(n+1)}{2}$ ist wahr \[\Rightarrow 1 + \ldots + n + (n + 1) = \frac{n(n+1)}{2} + (n+1) =  \frac{n(n+1) + 2(n+1)}{2} = \frac{(n+1)(n+2)}{2} \square\]
** Relationen
*** Definiton
	Eine Relation auf $M$ ist eine Teilmenge $R\subseteq M\times M$
	Wir schreiben $a\sim b \xLeftrightarrow{\text{Def}} (a,b) \in R$ ("a steht in Relation zu b")

	- anschaulich: eine Relation auf $M$ stellt eine "Beziehung" zwischen den Elementen von $M$ her.
	- Für $a,b \in M$ gilt entweder $a\sim b$ oder $a\not\sim b$, denn: entweder ist $(a,b) \in R$ oder $(a,b)\not\in R$
**** Anmerkung
	 Aufgrund der obigen Notation spricht man in der Regel von Relation "$\sim" auf $M$ als von der Relation $R \subseteq M\times M$
**** Beispiel
	 $M = \{1,2,3\}. Durch $R = \{(1,1), (1,2), (3,3) \subseteq M\times M\}$ ist eine Relation auf $M$ gegeben. Es gilt dann: $1\sim 1, 1\sim 2, 3\sim 3$ (aber zum Beispiel: $1\not\sim 3, 2\not\sim 1, 2\not\sim 2$)

*** Eigenschaften von Relationen
	$M$ Menge, $\sim$ Relation auf $M$ \\
	$\sim$ heißt:
	- reflexiv $\xLeftrightarrow{\text{Def}}$ für alle $a\in M$ gilt $a\sim a$
	- symmetrisch $\xLeftrightarrow{\text{Def}}$ für alle $a,b\in M$ gilt: $a\sim b \Rightarrow b\sim a$
	- antisymmetrisch $\xLeftrightarrow{\text{Def}}$ für alle $a,b \in M$ gilt: $a\sim b \wedge b\sim a \Rightarrow a = b$
	- transitiv $\xLeftrightarrow{\text{Def}}$ für alle $a,b,c\in M$ gilt: $a\sim b \wedge b\sim v \Rightarrow a\sim c$
	- total $\xLeftrightarrow{\text{Def}}$ für alle $a,b\in M$ gilt: $a\sim b \vee b\sim a$
**** Beispiel
	 Sei $M$ die Menge der Studierenden in der LA1-Vorlesung
	 1. Für $a,b \in M$ sei $a\sim b \xLeftrightarrow{\text{Def}}$ $a$ hat den selben Vornamen wie $b$ \\
		$\sim$ reflexiv, symmetrisch, nicht antisymmetrisch, transitiv, nicht total
	 2. Für $a,b \in M$ sei $a\sim b \xLeftrightarrow{\text{Def}}$ Martrikelnummer von $a$ ist kleiner gleich als die Martrikelnummer von $b$ \\
		$\sim$ ist reflexiv, nicht symmetrisch, antisymmetrisch, transitiv, total
	 3. Für $a,b \in M$ sei $a\sim b \xLeftrightarrow{\text{Def}}$ $a$ sitzt auf dem Platz recht von $b$ \\
		$\sim$ ist nicht reflexiv, nicht symmetrisch, nicht antisymmetrisch, nicht transitiv, nicht total
*** Halbordnung / Totalordung
	$\sim$ heißt
    - Halbordnung auf $M\xLeftrightarrow{\text{Def}}~\sim$ ist reflexiv, antisymmetrisch und transitiv
	- Totalordung auf $M\xLeftrightarrow{\text{Def}}~\sim$ ist eine Halbordnung und $\sim$ ist total
    In diesen Fällen sagt man auch: Das Tupel $(M,\sim)$ ist eine halbgeordnete, beziehungsweise totalgeordnete Menge.
**** Beispiel
	 1. $\leq$ auf $\mathbb{N}$ ist eine Totalordung
	 2. Sei $M = \mathcal{P}(\{1,2,3\})$. $\subseteq$ ist auf $M$ eine Halbordung, aber keine Totalordung (es ist zum Beispiel weder $\{1\} \subseteq \{3\}$ noch $\{3\}\subseteq \{\}$)
**** Anmerkung
	 Wegen der Analogie zur $\leq$ auf $\mathbb{N}$ bezeichnen wir Halbordnungen in der Regel mit $\leq$
*** Größtes / kleinstes Element
	$(M, \leq)$ halbgeordnete Menge, $a\in M$ \\
	$a$ heißt ein
	- größtes Element von $M\xLeftrightarrow{\text{Def}}$ Für alle $x\in M$ gilt $x\leq a$
	- kleinstes Element von $M\xLeftrightarrow{\text{Def}}$ Für alle $x\in M$ gilt $a\leq x$
**** Bemerkung
	 $(M,\leq)$ halbgeordnete Menge \\
	 Dann gilt: Existiert in $M$ ein größtes (beziehungsweise kleinstes) Element, so ist dieses eindeutig bestimmt
***** Beweis
	  Es seien $a,b\in M$ größte Elemente von $M$ \\
	  $\Rightarrow x\leq a$ für alle $x\in M$, also auch $b\leq a$ \\
	  Außerdem: $x \leq b$ für alle $x\in M$, also auch $a\leq b$ \\
	  $\xRightarrow{\text{Antisymmetrie}} a = b$ \\
	  Analog für kleinstes Element
***** Anmerkung
	  Dies sagt nichts darüber aus, ob ein größtes (beziehungsweise kleinstes) Element in $M$ überhaupt existiert.
**** Beispiel
	 1. In $(\mathbb{N},\leq)$ ist 1 das kleinste Element, ein größtes Element gibt es nicht
	 2. $(\{\{1\},\{2\},\{3\},\{1,2\},\{1,3\},\{2,3\}\}, \subseteq)$ ist eine halbgeordnete Menge ohne kleinstes beziehungsweise größtes Element
*** maximales / minimales Element
	$(M,\leq)$ halbgeordnete Menge, $a\in M$ \\
	$a$ heißt ein
    - maximales Element von $M \xLeftrightarrow{\text{Def}}$ für alle $x\in M$ gilt: $a\leq x \Rightarrow a = x$
    - minmales Element von $M \xLeftrightarrow{\text{Def}}$ für alle $x\in M$ gilt: $x\leq a \Rightarrow a = x$
**** Beispiel
     In $(\{\{1\},\{2\},\{3\},\{1,2\},\{1,3\},\{2,3\}\}, \subseteq)$ sind $\{1,2\},\{1,3\},\{2,3\}$ maximale Elemente und $\{1\},\{2\},\{3\}$ sind minimale Elemente.
**** Bemerkung
	 $(M,\leq)$ halbgeordnete Menge, $a\in M$ \\
	 Dann gilt: Ist $a$ ein größtes (beziehungsweise kleinstes) Element von $M$, dann ist $a$ ein maximales (beziehungsweise minimales) Element von $M$.
***** Beweis
	  Sei $a$ ein größtes Element von $M$. \\
	  zu zeigen ist: Für alle $x\in M$ gilt $a\leq x \Rightarrow a = x$
	  Sei $x\in M$ mit $a\leq x$. Da $a$ größtes Element von $M$ ist, gilt auch $x\leq a$ \\
	  $\xLeftrightarrow{\text{Antisymmetrie}} a = x$ \\
	  Analog für kleinstes Element.
*** Äquivalenzrelation
	$M$ Menge, $\sim$ auf $M$ \\
	$\sim$ heißt Äquivalenzrelation $\xLeftrightarrow{\text{Def}}~\sim$ ist reflexiv, symmetrisch und transitiv.
	In dem Fll sagen wir für $a\sim b$ auch $a$ ist äquivalent zu $b$. Für $a\in M$ heißt $[a]:=\{b\in M \mid b\sim a\}$ heißt die Äquivalentklasse von $a$.
	Elemente aus $[a]$ nennt man Vertreter oder Repräsentanten von $a$
**** Beispiel
	 $M$ Menge aller Bürgerinnen und Bürger Deutschlands. \\
	 Wir definieren für $a,b\in M$ $a\sim b \xLeftrightarrow{\text{Def}} a$ und $b$ sind im selben Jahr geboren. \\
	 $\sim$ ist ein Äquivalenzrelation. \\
	 Jerôme Boateng wurde 1988 geboren. \\
	 $[\text{Jerôme Boateng}] = \{b\in M\mid b~\text{ist im selben Jahr geboren wie Jerôme Boateng}\} = \{b\in M\mid b~\text{wurde 1988 geboren}\}$
	 Weitere Vertreter von $[\text{Jerôme Boateng}]$ sind zum Beispiel Mesut Özil, Mats Hummels.
	 Es ist $[\text{Jerôme Boateng}] = [\text{Mesut Özil}] = [\text{Mats Hummels}]$.
	 Man sieht in diesem Beispiel: Die Menge $M$ zerfällt komplett in verschiedene Äquivalentzklassen:
	 - Jeder Bürger / jede Bürgerinn Detuschalnds ist in genau einer Äquivalenzklasse enthalten
	 - Jede zwei Äquivalentklasse sind entweder gleich oder disjunkt (haben leeren Durchschnitt)
**** Bemerkung
	 $M$ Menge, $\sim$ Äquivalenzrelation auf $M$ \\
	 Dann gilt:
	 1. Jedes Element von $M$ liegt in genau einer Äquivalenzklasse
	 2. Je zwei Äquivalenzklassen sind entweder gleich oder disjunkt
     Man sagt auch: Die Äquivalenzklassen bezüglich "$\sim$" bilden eine *Partition* von $M$.
***** Beweis
	  1. Sei $a\in M$ \\
		 zu zeigen: Es gibt genau eine Äquivalenzklassen, in der $a$ liegt
		 1. Es gibt eine Äquivalenzklasse, in der $a$ liegt, denn $a\in [a], denn $a\sim a$
		 2. Ist $a\in[b] und a\in[c], dann ist [b]=[c] (d.h. $a$ liegt in höchstens einer Äquivalenzklasse) \\
			denn: Seien $b,c\in M$ mit $a\in[b]$ und $a\in[c]$
			$\Rightarrow a\sim b$ und $a\sim c \xRightarrow{\text{Symmetrie}} b\sim a$ und $a\sim c \xRightarrow{\text{Transitivität}} b\sim c$
			Behautptung $[b] =[c]$
			denn: "$\subseteq$" Sei $x\in [b] \Rightarrow x\sim b \xRightarrow{Transitivität}^{b\sim c} x\sim c \Rightarrow x\in [c]$
			denn: "$\supseteq$" Sei $x\in [c] \Rightarrow x\sim c \xRightarrow{Transitivität}^{c\sim b} x\sim b \Rightarrow x\in [b]$
	  2. Sind $b,c\in M$ mit $[b] \cap [c] \neq \emptyset$, dann existiert ein $a\in [b]\cap [c], und es folgt wie in 2.: \\
		 $[b] = [c]$
		 Für $b,c\in M$ gilt also entweder $[b]\cap[c] =\emptyset$ oder $[b] = [c]\hfill\square$
**** Faktormenge
	 $M$ Menge, $\sim$ Äquivalenzrelation auf $M$
	 $M/\sim := \{[a]|a\in M\}$ (Menge der Äquivalenzklassen) heißt die Faktormenge (Quotientenmenge) von $M$ nach $\sim$
***** Beispiel
	  \[M= \{1,2,3,-1,-2,-3\}\]
	  Für $a,b,c \in M$ setzen wir $a\sim b \xLeftrightarrow{\text{Def.}} \abs{x} = \abs{b}$
	  Das ist eine Äquivalenzrelation auf $M$
	  Es ist $[1] = \{1,-1\},[2]=\{2,-2\},[3]=\{3,-3\}$
	  Somit: $M/sim := \{[1],[2],[3]\} = \{\{1,-1\},\{2,-2\},\{3,-3\}\}$
***** Anmerkung
	  Der Übergang zur Äquivalenzklassen soll (für eine jeweils gegebene Relation) irrelevante Informationen abstreifen.
** Abbildungen
   *naive Definition*: \\
   Eine Abbildung $f$ von $M$ nach $N$ ist eine Vorschrift, die jedem $n\in M$ genau ein Element aus $N$ zuordnet, dieses wird mit $f(n)$ bezeichnet.
   *Notation*: \\
   \[f:M\to N,m\mapsto f(m)\]

   Zwei Abbildungen $f,g:M\to N$ sind gleich, wenn gilt $\Forall n\in M:f(n) = g(n)$
   $M$ heißt die Definitionsmenge von $f$, $N$ heißt die Zielmenge von $f$
*** Definition
	Eine Abbildung $f$ von $M$ nach $N$ ist ein Tupel $(M,N,G_f)$, wobei $G_f$ eine Teilmenge von $M\times N$ mit der Eigenschaft ist, dass für jedes Element $m\in M$ genau ein Element $n\in N$ mit $(m,n) \in G_f$ existiert.
	(für dieses Element $n$ schreiben wir auch $f(m)$). $G_f$ heißt der Graph von $f$.
*** Beispiel
	1. $f:\mathbb{R}\to\mathbb{R}, x\mapsto x^2$
	2. $f:\mathbb{R}\to\mathbb{R}^2,x\mapsto (x,x+1)$
	3. $M$ Menge, $id_M: M\to M,m\mapsto m$ heißt Identität (identische Abbildung) auf $M$
	4. $I$,$M$ Mengen: Eine über $I$ indizierte Familie von Elementen von $M$ ist eine Abbildung: \\
	   $m:I\to M,i\mapsto m(i) =: m_i$. Wir schreiben für die Familie auch kurz $(m_i)_{i\in I}$. $I$ heißt Indexmenge der Familie.
	5. Spezialfall von 4.: $I = \mathbb{N},M = \mathbb{R}:~((m_i)_{i\in\mathbb{N}})$ nennt man auch Folge reeler Zahlen.
*** Anmerkung über den Begriff der Familie
	Über den Begriff der Familie lassen sich diverse Konstruktionen aus der naiven Mengenlehre verallgemeinern.
	Ist $(M_i)_{i\in I}$ eine Familie von Mengen, dann ist:
	\[\cup_{i\in I} M_i:=\{x\mid\exists i\in I: x\in M_i\}\]
	\[\cap_{i\in I}M_i := \{x\mid\Forall i\in I: x\in M_i\}\]
	\[\prod_{i\in I}M_i := \{(x_i)_{i\in I}\mid \Forall i\in I: x_i \in M\}\]
*** Bild
	$m,N$ Mengen, $f:M\to n$ Abbildung. \\
	Sind $m\in M,n\in N$ mit $n = f(m)$ dann nennen wir $n$ ein *Bild* von $m$ unter $f$ und wir nennen $m$ ein *Urbild* von $n$ unter $f$.
**** Anmerkung
	 In obiger Situation ist das Bild von $m$ unter $f$ eindeutig bestimmt (nach der Definition einer Abbildung)
	 Urbilder sind im allgemeinen nicht eindeutig bestimmt, und im Allgemeinen besitzt nicht jedes Element aus $N$ ein Urbild.
**** Beispiel
	 $f:\mathbb{R}\to\mathbb{R},x\mapsto x^2$, dann ist $4=f(2) = f(-2)$, das heißt $2$ und $-2$ sind Urbilder von $4$, das Element $-5$ hat kein Urbild unter $f$, denn es existiert kein $x\in\mathbb{R}$ mit $x^2 = -5$
**** Definition
	 $M, N$ Mengen, $f:M\to N$ Abbildung, $A\subseteq M, B\subseteq N$ \\
	 $f(A) := \{f(a)\mid a\in A\} \subseteq N$ heißt das Bild von $A$ unter $f$. \\
	 $f^-1(B) := \{m\in M\mid f(m) \in B\} \subseteq M$ heißt das Urbild von $B$ unter $f$
***** Beispiel
	  \[f:\mathbb{R}\to\mathbb{R},x\mapsto x^2\]
	  \[f(\{1,2,3\}) = \{1,4,9\}\]
	  \[f^-1(\{4,-5\}) = \{2,-2\}\]
	  \[f^-1(\{4\}) = \{2,-2\}\]
	  \[f^-1(\{-5\}) = \emptyset\]
	  \[f(\mathbb{R}) = {x^2\mid x\in \mathbb{R}} = \{x\in\mathbb{R}\mid x\geq 0\} =:\mathbb{R}_{\geq 0}\]
*** Restriktion
	$M,N$ Mengen, $f:M\to N$ Abbildung, $A\subseteq M$
	\[f\mid_A:A\to N, m\mapsto f(m)\]
	heißt die Restriktion von $f$ auf $A$.
	Ist $B\subseteq N$ mit $f(A) \subseteq B$, dann setzen wir
	\[f\mid_A^B: A\to B,m\mapsto f(m)\]
	Ist $f(M) \subseteq B$ dann setzen wir:
	\[f\mid^B := f\mid_M^B,M\to B, m\mapsto f(m)\]
*** Komposition
	$L,M,N$ Mengen, $f:L\to M,g:M\to N$ Abbildung \\
	\[g\circ f: L\to N, x\mapsto(g\circ f)(x):=g(f(x))\]
	heißt die Komposition (Hintereinanderausführung) von $f$ und $g$
**** Beispiel
	 \[f:\mathbb{R}\to\mathbb{R},x\mapsto x^2, g:\mathbb{R}\to\mathbb{R}:x\mapsto x + 1\]
	 \[\Rightarrow g\circ f:\mathbb{R}\to\mathbb{R},x\mapsto g(f(x)) = g(x^2) = x^2 + 1\]
**** Assoziativität
	 $L,M,N,P$ Mengen, $f:L\to M, g:M\to N,h:n\to p$ \\
	 Dann gilt
	 \[h\circ (g\circ f) = (h\circ g)\circ f\]
	 das heißt die Verknüpfung von Abbildungen ist assoziativ.
***** Beweis
	  Für $x\in L ist$ \\
	  \[(h\circ (g\circ f)) = h((g\circ f)(x)) = h(g(f(x))) = (h\circ g)(f(x)) = ((h\circ g)\circ f)(x)\hfill\square\]
*** Eigenschaften von Abbildungen
	$M,N$ Mengen, $f:M\to N$ Abbildung
**** Injektivität
	 $f$ heißt injektiv: \[\xLeftrightarrow{\text{Def}} \Forall m_1,m_2\in M: f(m_1) = f(m_2) \Rightarrow m_1 = m_2 \Leftrightarrow \Forall m_1,m_2\in M: m_1\neq m_2 \Rightarrow f(m_1)\neq f(m_2)\]
**** Surjektivität
	 $f$ heißt sujektiv:
	 \[\xLeftrightarrow{\text{Def}} \Forall n\in M :\exists m\in M: f(m) = n \Leftrightarrow f(M) = N\]
**** Bijektivität
	 $f$ heißt bijektiv: $\xLeftrightarrow{\text{Def}}$ $f$ ist injektiv und surjektiv
**** Beispiel
	 1. $f:\mathbb{R}\to\mathbb{R},x\mapsto x^2$ ist:
		- nicht injektiv, denn $f(2) = f(-2)$, aber $2\neq -2$
		- nicht surjektiv, denn es existier kein $m\in\mathbb{R}$ mit $f(m) = -1$
		- nicht bijektiv
	 2. $f:\mathbb{R}_{\geq 0} \to \mathbb{R}, x\mapsto x^2$ ist:
		- injektiv, denn für $m_1,m_2 \in\mathbb{R}_{\geq 0}$ gilt: $f(m_1) = f(m_2) \Rightarrow m_1^2 = m_2^2 \xRightarrow{m_1,m_2 > 0} m_1 = m_2$
		- nicht surjektiv, denn es existier kein $m\in\mathbb{R}_{\geq 0}$ mit $f(m) = -1$
		- nicht bijektiv
	 3. $f:\mathbb{R}_{\geq 0} \to \mathbb{R}_{\geq 0}, x\mapsto x^2$ ist:
		- injektiv, denn für $m_1,m_2 \in\mathbb{R}_{\geq 0}$ gilt: $f(m_1) = f(m_2) \Rightarrow m_1^2 = m_2^2 \xRightarrow{m_1,m_2 > 0} m_1 = m_2$
		- surjektiv, denn für $m\in\mathbb{R}_{\geq 0}$ ist $f(\sqrt{m}) = (\sqrt{m})^2 = m$
		- bijektiv
**** Bemerkung 4.12
	 $M,N$ Mengen, $f:M\to N, g:n\to M$ mit $g\circ f = id_M$
	 Dann ist $f$ injektiv und $g$ surjektiv.
***** Beweis
	  1. $f$ ist injektiv, denn: \\
		 Seien $m_1, m_2 \in M$ mit $f(m_1) = f(m_2) \Rightarrow g(f(m_1)) = g(f(m_2)) \Rightarrow (g\circ f)(m_1) = (g\circ f)(m_2) \Rightarrow id_m(m_1) = id_M(m_2)\Rightarrow m_1 = m_2$
	  2. $g$ ist surjektiv, denn: \\
		 Sei $m\in M$ Dann ist $m=id_M(m) = (g\circ f)(m) = g(f(m))$
**** Bemerkung
	 Sei $f:M\to N$, $N,M$ Mengen
	 Dann sind äquivalent:
	 1. $f$ ist bijektiv
	 2. Zu jedem $n\in N$ gibt es genau ein $m\in M$ mit $f(m) = n$
	 3. Es gibt genau eine Abbildung $g:N\to M$ mit $g\circ f = id_M$ und $f\circ g = id_N$
	 In diesem Fall bezeichnen wir die Abbildung $g:N\to M$ aus 3. mit $f^{-1}$ und nennen $f^{-1}$ die Umkehrabbildung von $f$. Sie ist gegeben durch
	 \[f^{-1} : N\to M, n\mapsto~\text{Das eindeutig bestimmte Element $m\in M$ mit $f(m) = n$}\]
***** Beweis
	  Statt 1. \Leftrightarrow 2. und 2. \Leftrightarrow 3. zeigen 1. \Rightarrow 2. \Rightarrow 3. \Rightarrow 1.
	  - 1. \Rightarrow 2. Sei $f$ bijektiv \\
		zz: Ist $n\in N$, dann existiert genau ein $m\in M$ mit $f(m) = n$ \\
		- Existenz folg aus Surjektivität von $f$
		- Eindeutigkeit: Seien $m_1,m_2 \in M  mit \(f(m_1) = n, f(m_2) = n \Rightarrow f(m_1) = f(m_2) \xRightarrow{f injektiv} m_1 = m_2\)
	  - 2. \Rightarrow 3. Zu jedem $n\in M$ existiere genau ein $m\in M$ mit $f(m) = n$ \\
		zz: Ex existert genau eine Abbildung $g:N\to M$ mit $f\circ f = id_M$ und $f\circ g = id_N$
		- Existenz: Wir definieren \(g:N\to M, n\mapsto~\text{das nach 2. eindeutig \\ 
		  bestimmte Element $m\in M$ mit $f(m) = n$}\) \\
		  Dann gilt für $m\in M$: \[(g\circ f)(m) = f(f(m)) = m,~text{das heißt}~ g\circ f = id_M\]
		  und für $n\in N$ ist $(f\circ g)(n) = f(g(n)) = n$ also $f\circ g = id_N$
		- Eindeutigkeit: Es seinen $g_1,g_2:N\to M$ mit $g_i \circ f = id_M, f\circ g_i = id_N$ für $i = 1,2$ \\
		  \[\Rightarrow g_1 = g_1 \circ id_N = g_1 \circ (f\circ g_2) = (g_1 \circ f) \circ g_2 = id_M \circ g_2 = g_2\]
	  - 3. \Rightarrow 1. Wegen 3. existier $g:N\to M$ mit $g\circ f = id_M,f\circ g = id_N$ \\
		\[\xRightarrow{[[Bemerkung 4.12]]} f~\text{injektiv}~,f~\text{surjektiv}~\Rightarrow f~\text{bijektiv}\Rightarrow~\text{1.}\]
***** Anmerkung
	  - Bitte stets aufpassen, ob mit $f^{-1}$ die Unmkerhabbildung (falls existent) oder das Bilden der Urbildmenge gemeint ist.
	  - Im Beweis von 3. \Rightarrow 1. haben wir die Eindeutigkeit von $g$ garnicht verwendet, das heißt wir haben sogar gezeigt: \\
		$f$ bijektiv \Leftrightarrow 3.' Es existiert eine Abbildung $g:N\to M$ mit $f\circ g = id_N$ und $f\circ f = id_M$ Soch eine Abbildung $g$ ist in diesem Fall automatisch bestimmt.
***** Beispiel
	  Im Beispiel vorher haben wir gesehen $f:\mathbb{R}_{\geq 0} \to \mathbb{R}_{\geq 0}, x\mapsto x^2$ ist bijektiv.
	  Die Umkehrabbildung ist gegeben durch $f^{-1}:\mathbb{R}_{\geq 0} \to \mathbb{R}_{\geq 0}, x\mapsto \sqrt{x}$
**** Bemerkung
	 $M,N$ Mengen, $f:M\to N$ Dann gilt:
	 1. $f$ injektiv \Leftrightarrow Es existiert $g:N\to M$ mit $g\circ f = id_M$ \\
		*Beweis:*
		- "\Leftarrow" folgt aus [[Bemerkung 4.12]]
		- "\Rightarrow" Sei $f$ injektiv. Sein $x$ ein beliebiges Element aus $M$
		  Wir definieren \[g:N\to M,n\mapsto \begin{cases} x & n\not\in f(M) \\ \text{das eindeutig bestimmte Element $m\in M$ mit $f(m) = n$} & n\in f(M) \end{cases}\]
		  Für alle $m\in M$ ist dann $(g\circ f)(m) = g(f(m)) = m$ das geißt $g\circ f = id_M$
	 2. $f$ surjektiv \Leftrightarrow Es existiert $g:N\to M$ mit $f\circ g = id_N$ \\
		*Beweis:*
		- "\Leftarrow" folgt aus [[Bemerkung 4.12]]
		- "\Rightarrow" Sei $f$ surjektiv. Für jedes Element $n\in N$ wählen wir ein Element $\tilde n\in f^{-1}(\{n\}) \neq \emptyset$ und sehen
		  $g:N\to M,n\mapsto \tilde n$. Dann ist $(f\circ g)(n) = f(g(n)) = n$ für alle $n\in N$ und das heißt $f\circ g = id_N \hfill\square$
***** Anmerkung
	  Das wir stets einen Auswahlprozess wie im Beweis von 2. "\Rightarrow" vornehmen können ist ein Axiom der Mengenlehre (erkennen wir als gültig an, ist jedoch nicht beweisbar), das *Auswahlaxiom*: \\
	  Ist $I$ eine Indexmenge und $(A_i)_{i\in I}$ eine Familie von nichtleeren Mengen, dann gibt es eine Abbildung $\gamma:I\to \bigcup_{i\in I} A_i$ mit $\gamma (i) \in A_i$ für alle $i\in I$ (im obigen Beweis ist $I = N,A_n = f^{-1}(\{n\})$ für $n\in N$)
**** Bemerkung 4.16
	 $L,M,N$ Mengen, $f:L\to M, g:M\to N$ \\
	 Dann gilt: $g,f$ beide injektiv (beziehungsweise surjektiv oder bijektiv) \Rightarrow $g\circ f$ injektiv (beziehungsweise sujektiv oder bijektiv)
**** Definition 4.17
**** Bemerkung 4.19
	 $M,N$ endliche Mengen mit $\abs{M} = \abs{N},f:M\to N$ Dann sind äquivalent:
	 1. $f$ ist injektiv
	 2. $f$ ist surjektiv
	 3. $f$ ist bijektiv
***** Beweis
	  - 1. \Rightarrow 2. Sei $f$ injektiv \Rightarrow $\abs{f(M)} = \abs{M} = \abs{N}$ wegen $f(M) \subseteq N$ folgt $f(M) = N$ \Rightarrow $f$ surjektiv
	  - 2. \Rightarrow 3. Sei $f$ sujektiv, das heißt $f(M) = N$ \\
		Annahme: $f$ ist nicht bijektiv \Rightarrow $f$ nicht injektiv \Rightarrow $\exists m_1,m_2\in M: m_1\neq m_2 \wedge f(M_1) = f(m_2) \Rightarrow \abs{f(M)} < \abs{M} = \abs{N}$ Wiederspruch zu $f(M) = N$
	  - 3. \Rightarrow 1. trivial
* Gruppen, Ringe, Körper
** Gruppe
*** Verknüpfung
	$M$ Menge, Eine Verknüpfung (inverse Verknüpfung) auf $M$ ist ein Abbildung \[*:M\times M \to M\]
	Anstelle von $*(a,b)$ schreiben wir $a * b$
**** Beispiel
	 - $+: \mathbb{R} \times \mathbb{R} \to \mathbb{R},(a,b) \mapsto a + b$
	 - $\cdot: \mathbb{R} \times \mathbb{R} \to \mathbb{R},(a,b) \mapsto a\cdot b$
	 sind Verknüpfungen
*** Monoid
	Ein Monoid ist ein Tupel $(M,*)$, bestehend aus einer Menge $M$ und einer Verküpfung \\
	$*:M\times M \to M$, welche folgende Bedingungen genügt:
	- (M1) Die Verküpfung ist assoziativ, das heißt \[\Forall a,b,c\in M:(a*b)*c = a*(b*c) \]
	- (M2) Ex existiert ein neutrales Element $e$ in $M$, das heißt \[\exists e\in M:\Forall a\in M e*a = a = a*e\]
**** Beispiel
	 - $(\mathbb{N}_0,+), (\mathbb{Z},+)$ sind Monoide (neutrales Element: $0$)
	 - $(\mathbb{N},+)$ ist kein Monoid (ex existiert kein neutrales Element)
	 - $(\mathbb{N},\cdot),(\mathbb{Z},\cdot)$ sind Monoide (neutrales Element: $1$)
**** Bemerkung
	 $(M,*)$ Monoid. Dann gibt es in $M$ genau ein neutrales Element.
***** Beweis
	  - Existenz: Es existert ein neutrales Element: folgt aus Definition eines Monoids
	  - Eindeutigkeit: Seien $e,\tilde e \in M$ neutrale Element \[\Rightarrow e = e * \tilde e = \tilde e\]
*** Inverses
	$(M,*)$ Monoid mit neutralem Element $e$, $a\in M$
	Ein Element $b\in M$ heit Inverses zu $a \xLeftrightarrow{\text{Def}} a * b = e = b * a$
**** Beispiel
	 - In $(\mathbb{Z},+)$ ist $-2$ ein Inverses zu $2$ denn $2 + (-2) = 0 = (-2) + 2$
	 - In $(\mathbb{N}_0,+)$ existiert kein Inverses zu $2$, denn es existiert kein $n\in \mathbb{N}_0$ mit $n + n = 0 = n + 2$
	 - <<invex>> In $(\mathbb{Z},\cdot)$ existiert kein Inverses zu $2$, denn es existiert kein $n\in\mathbb{Z}$ mit $2\cdot n = 1 = n \cdot 2$
**** Bemerkung
	 <<beminv>>
	 $(M,*)$ Monid, $a\in M$ Dann gilt: besitzt $a$ ein Inverses, dann ist dieses eindeutig bestimmt.
***** Beweis
	  Seinen $b,\tilde b$ Inversen zu $a$, sein $e\in M$ das neutrale Element
	  \[\Rightarrow b = e * b = (\tilde b * a) * b = \tilde b * (a * b) = \tilde b\]
*** Gruppe
	Eine Gruppe ist ein Tupel $(G,*)$, bestehen aus einer Menge $G$ und einer Verknüpfung $*:G\times G \to G$, sodass gilt:
	- (G1) $(G,*)$ ist ein Monoid
	- (G2) Jedes Element aus $G$ besitzt ein Inverses
	In diesem Fall schreiben wir $a'$ für das nach [[beminv]] eindeutig bestimmte Inverse eines Elements $a\in G$
**** Beispiel
	 - $(\mathbb{Z},+)$ ist eine Gruppe, denn $(\mathbb{Z},+)$ ist ein Monoid und für $a\in\mathbb{Z}$ ist $-a$ das inverse Element: $a + (-a) = 0 = (-a) + a$
	 - $(\mathbb{Z},\cdot)$ ist keine Gruppe, denn das Element $2\in\mathbb{Z}$ hat kein Inverses (vergleiche [[invex]]).
	 - $(\mathbb{Q}\setminus \{0\},\cdot)$ ist eine Gruppe denn es ist ein Monoid mit neutralem Element $1$ und für jedes Element $a\in\mathbb{Q}\setminus\{0\}$ existiert ein $b\in \mathbb{Q}\setminus \{0\}$ mit $a\cdot b = 1 = b\cdot a$, nämlich $b = \frac{1}{a}$
**** Bemerkung 5.11
	 $(G,*)$ Gruppe mit neutralem Element $e,a,b,c \in G$. Dann gilt
	 1. (Kürzungsregel) \[a*b = a*c \Rightarrow b = c\] \[a*c = b * c \Rightarrow a = b\]
	 2. $a*b = e \Rightarrow b = a'$
	 3. $(a')' = a$
	 4. (Regel von Hemd und Jacke) $(a*b)' = b' * a'$
***** Beweis
	  1. Sei $a * b = a * c \Rightarrow a'*(a*b) = a'*(a*c) \Rightarrow (a'*a)*b=(a'*a)*c \Rightarrow e*b = e*c \Rightarrow b = c$
	  2. aus 1. $a*b = c = a*a' \Rightarrow b = a'$
	  3. Es ist $a*a' = e = a' * a$, das heißt $a$ ist Inverses zu $a' \Rightarrow (a')' = a$
	  4. Es ist $(a*b)*(b'*a') = a*(b*b')*a' = a*a' = e \Rightarrow b' * a' \xRightarrow{\text{2.}} (a *b)'$
*** Abelsche Gruppe
	$(M,*)$ Monoid / Gruppe heißt kommutativ (abelsch)
	\[\xLeftrightarrow{\text{Def}} \Forall a,b\in M: a*b = b*a\]
**** Beispiel
	 Alle bisher betrachteten Beispiele von Monoiden beziehungsweise Gruppen sind abelsch
**** Bemerkung 5.14
	 $M$ Menge, Wir setzten $S(M):= \{f:M\to M | f~\text{bijektiv}\}$
	 Dann ist $(S(M),\circ)$ eine Gruppen, die *symmetrische* Gruppe auf $M$
***** Beweis
	  1. "$\circ" ist wohl definiert, das heißt für $f,g\in S(M)$ ist $f\circ g \in S(M)$ folgt aus [[Bemerkung 4.19]]
	  2. "$\circ" ist assoziativ $f\circ(g\circ h) = (f\circ g) \circ h \Forall f,g\in S(M)$ nach [[4.9]]
	  3. $id_M$ ist neutral: $id_M \in S(M)$ und $id_M\circ f = f = f\circ id_M \Forall f\in S(M)$
	  4. Existenz von Inversen: $f\in S(M) \Rightarrow f$ bijektiv \Rightarrow Es existiert Umkehrabbildung $f^{-1}\in S(M)$ zu $f$
		 für diese gilt: $f\circ f^{-1} = id_M = f^{-1}\circ f$ das heißt $f^{-1}$ ist immer zu $f$ bezüglich "$\circ"
*** Permutationen
	$n\in\mathbb{N}$
	\[S_n := S(\{1,\ldots,n\}) = \{\pi \{1,\ldots,n\} \to \{1,\ldots,n\} \mid \pi~\text{ist bijektiv}\}\]
	$(S_n,\circ)$ heißt die symmetrische Gruppe auf $n$ Ziffern, Elemente aus $S_n$ heißen Permutationen.
	Wir schreiben Permutationen $\pi \in S_n$ in der Form:
	\begin{equation}
	\pi =
	\begin{pmatrix}
	1 & 2 & \ldots & n \\
	\pi(1) & \pi(2) & \ldots & \pi(n)
	\end{pmatrix}
	\end{equation}
**** Beispiel
	 In $S_3$ ist
	 \begin{equation}
	 \begin{pmatrix}
	 1 & 2 & 3 \\
	 1 & 3 & 2 \\
	 \end{pmatrix}
	 \circ
	 \begin{pmatrix}
	 1 & 2 & 3 \\
	 3 & 2 & 1 \\
	 \end{pmatrix}
	 =
	 \begin{pmatrix}
	 1 & 2 & 3 \\
	 2 & 3 & 1 \\
	 \end{pmatrix}
	 \end{equation}

	 \begin{equation}
	 \begin{pmatrix}
	 1 & 2 & 3 \\
	 3 & 2 & 1 \\
	 \end{pmatrix}
	 \circ
	 \begin{pmatrix}
	 1 & 2 & 3 \\
	 1 & 3 & 2 \\
	 \end{pmatrix}
	 =
	 \begin{pmatrix}
	 1 & 2 & 3 \\
	 3 & 1 & 2 \\
	 \end{pmatrix}
	 \end{equation}
	 das heißt $(S_3,\circ)$ ist nicht abelsch.
*** Restklassen
**** Motivation
	 Im täglischen Leben verwendet man zur Bestimmung von Uhrzeiten das Rechnen "modulo $24$", zum Beispiel 22Uhr + 7h = 5Uhr. Wir wollen dies mathematisch präzisieren und verallgemeinern
**** Bemerkung 5.17
	 $n\in\mathbb{N}$. Dann ist durch \[a \sim b \xLeftrightarrow{\text{Def}} \Exists q\in\mathbb{Z}:a - b = q n\]
	 eine Äquivalenzrelatioin auf $\mathbb{Z}$ gegeben.
	 Anstelle von $a\sim b$ schreiben wir auch $a\equiv b(\mod n)$ ("$n$ ist kongruent $b$ modulo $n$")
	 Die Äquivalenzklasse von $a\in \mathbb{Z}$ ist durch
	 \[\bar a := \{b\in\mathbb{Z}\mid b\equiv a(\mod n)\} = a + n\mathbb{Z} := \{a + n q \mid q\in \mathbb{Z}\}\]
	 gegeben und heißt die Restklasse von $a$ modulo $n$.
	 Die Menge aller Restklassen modulo $n$ wird $\frac{\mathbb{Z}}{n\mathbb{Z}}$ bezeichnet ("$\mathbb{Z}$ modulo $n\mathbb{Z}$")
	 Es ist: \[\frac{\mathbb{Z}}{n\mathbb{Z}} = \{\bar 0, \bar 1, \ldots, \overline{n - 1}\}\]
	 und die Restklassen $\bar 0, \ldots, \overline{n - 1}$ sind paarweise verschieden
***** Beweis
	  1. "$\equiv$" ist eine Äquivalenzrelation, denn:
		 - "$\equiv$" ist reflexiv: Fpr $a\in\mathbb{Z}$ ist $a\equiv a(\mod n)$ denn $a - a = 0 = 0 n$
		 - "$\equiv$" ist symmetrisch: Seien $a,b\in\mathbb{Z}$ mit $a\equiv b(\mod n) \exists q\in\mathbb{Z}:a - b = q n$ \\
		   \Rightarrow $b - a = (-q) n \Rightarrow b \equiv a(\mod n)$
		 - "$\equiv$" ist transitiv: Seien $a,b,c\in\mathbb{Z}$ mit $a\equiv b(\mod n), b\equiv c(\mod n)$
		   - \Rightarrow $\exists q_1,q_2 \in\mathbb{Z}$ mit $a - b = q_1 n, b - c = q_2 n$
		   - \Rightarrow $a - c = (a - b) + (b - c) = q_1 n + q_2 n = (q_1 + 1_2) n \Rightarrow a \equiv c(\mod n)$
	  2. Die Äquivalenzklasse von $n\in\mathbb{Z}$ ist gegeben durch
		 \[\{b\in\mathbb{Z} \mid b = a(\mod n)\}\]
		 \[= \{b\in\mathbb{Z} \mid \exists q\in\mathbb{Z}:b - a = qn\}\]
		 \[= \{b\in\mathbb{Z} \mid \exists q\in\mathbb{Z}:b = a + q n\}\]
		 \[= a + n\mathbb{Z} \]
	  3. \[\frac{\mathbb{Z}}{n\mathbb{Z}} = \{\bar 0, \bar 1, \ldots, \overline{n - 1}\}\]
		 denn:
		 - Ist $a\in\mathbb{Z}$ beliebig, dann liefert Division mit Rest durch $n$: \\
		   Es gibt $q,r\in\mathbb{Z}$ mit $a = q n + r,0\leq r < n$
		   \[\Rightarrow a - r = q n \Rightarrow q \equiv r(\mod n) \Rightarrow \bar a = \bar r\]
		   Das heißt: Jede Restklasse ist von der Form $\bar r$ mit $r\in \{0,\ldots,n - 1\}$ \\
		 - Die Restklassen $\bar 0, \bar 1, \ldots, \overline{n - 1}$ sind paarweise verschieden denn: \\
		   Seien $a,b\in\{0,\ldots,n - 1\}$ mit $\bar a = \bar b \Rightarrow a \equiv b(\mod n) \Rightarrow \exists q\in \mathbb{Z}: a - b = q n \Rightarrow \abs{a - b} = \abs{q} n$.
		   - Wäre $q\neq 0$, dann $\abs{q} \geq 1$ wegen $q\in\mathbb{Z} \Rightarrow \abs{a - b} \geq n$ *Wiederspruch* zu $a,b\in\{0,\ldots,n - 1\}$ \\
			 Also: $q = 0$ das heißt $a = b$
**** Beispiel
	 $n = 3: a\equiv b (\mod 3) \Leftrightarrow \exists q\in\mathbb{Z}: a - b = 3 q$ \\
	 zum Beispiel: $11 \equiv 5(\mod 3)$, denn $11 - 5 = 6 = 2 \cdot 3$ \\
	 zum Beispiel: $7 \not\equiv 2(\mod 3)$, denn $7 - 2 = 5$ und es gibt kein $q\in\mathbb{Z}$ mit $5 = 3 q$
	 \[\bar 0 = \{a\in\mathbb{Z}\mid a \equiv 0 (\mod 3)\} = \{a\in\mathbb{Z} \mid  \exists q\in\mathbb{Z}: a = 3q\} = 3\mathbb{Z} = \{\ldots,-6,-3,0,3,6,\ldots\}\]
	 \[\bar 1 = \{a\in\mathbb{Z}\mid a \equiv 1 (\mod 3)\} = \{a\in\mathbb{Z} \mid  \exists q\in\mathbb{Z}: a - 1 = 3q\} = 1 + 3\mathbb{Z} = \{\ldots,-5,-2,1,4,7,\ldots\}\]
	 \[\bar 2 = \{a\in\mathbb{Z}\mid a \equiv 2 (\mod 3)\} = \{a\in\mathbb{Z} \mid  \exists q\in\mathbb{Z}: a - 2 = 3q\} = 2 + 3\mathbb{Z} = \{\ldots,-4,-1,2,5,8,\ldots\}\]
	 \[\bar 3 = \{a\in\mathbb{Z}\mid a \equiv 3 (\mod 3)\} = \{a\in\mathbb{Z} \mid  \exists q\in\mathbb{Z}: a - 3 = 3q\} = \{a\in\mathbb{Z}\mid \exists q\in\mathbb{Z}:a=3(q + 1)\}3\mathbb{Z} = \bar 0\]
	 \[\bar 4 = \bar 1,\bar 5 = \bar 2,\overline{-1} = \bar 2\]
**** Bemerkung 5.18
	 $n\in\mathbb{N}$ wir definieren eine Verküpfung (Addition) auf $\frac{\mathbb{Z}}{n\mathbb{Z}}$ wie folgt: \\
	 Für $\bar a,\bar b \in\frac{\mathbb{Z}}{n\mathbb{Z}}$ setzen wir $\bar a + \bar b = \overline{a + b}$
	 Dann gilt $(\frac{\mathbb{Z}}{n\mathbb{Z}},+)$ ist eine abelsche Gruppe
***** Beweis
	  1. Die Verknüpfung ist wohldefiniert: \\ Problem: Die Addition verweendet Vertreter von Restklassen. Es ist zum Beispiel in $\frac{\mathbb{Z}}{n\mathbb{Z}}: \bar 3 + \bar 4 = \overline{3 + 4} = \bar 7 = \bar 2$, aber man könnte auch Rechnen:
		 $\bar 3 + \bar 4 = \bar 8 + \bar 9 = \overline{8 + 9} = \overline{17} = \bar 2$ \\
		 Wir müssen nachweisen, dass die Wahl der Vertreter keinen Einfluss auf das Ergebnis hat, das heißt die Verknüfung ist "vertreter unahbhängig": \\
		 Seien $a_1,a_2 ,b_1,b_2 \in\mathbb{Z},\overline{a_1} = \overline{a_2},\overline{b_1} = \overline{b_2}$
		 \begin{align}
		 &\Rightarrow a_1 \equiv a_2(\mod n), b_1 \equiv b_2(\mod n) \\
		 &\Rightarrow\exists q_1,q_2\in\mathbb{Z}: a_1 - a_2 = q_1 n, b_1 - b_2 = q_2 n n, b_1 - b_2 = q_2 n \\
		 &\Rightarrow (a_1 + b_1) - (a_2 + b_2) = (a_1 - a_2)+ (b_1 - b_2) = q_1 n + q_2 n = (q_1 + q_2) n \\
		 &\Rightarrow a_1 + b_ 1 \equiv a_2 + b_2 (\mod n) \\
		 &\Rightarrow \overline{a_1 + b_1} = \overline{a_2 + b_2}
		 \end{align}
	  3. $(\frac{\mathbb{Z}}{n\mathbb{Z}})$ ist eine abelsche Gruppe:
		 - Assoziativgesetz: Für alle $a,b,c\in\mathbb{Z}$ ist
		   \[(\bar a + \bar b) + \bar c = \overline{a + b} + \bar c = \overline{(a + b) + c} = \overline{a + (b + c)} = \bar a + \overline{b + c} = \bar a + (\bar b + \bar c)\]
		 - $\bar 0$ ist neutrales Element, denn $\Forall a\in\mathbb{Z}:\bar 0 + \bar a = \overline{0 + a} = \bar a = \bar a + \bar 0$
		 - Für $a\in\mathbb{Z}$ inst $\overline{-a}$ das inverse Element zu $\bar a$, denn $\bar a + \overline{-a} = \overline{a + (- a)} = \bar 0 = \overline{-a} + \bar a$
		 - Kommutativgesetz: $\Forall a,b\in\mathbb{Z}:\bar a + \bar b = \overline{a + b} = \overline{b + a} = \bar b + \bar a$
***** Beispiel
	  Wir tragen die Ergebnisse der Verknüpfung "$+$" in einer Verknüpfungstafel zusamme:
	  n = 3
	  | $+$      | $\bar 0$ | $\bar 1$ | $\bar 2$ |
	  |----------+----------+----------+----------|
	  | $\bar 0$ | $\bar 0$ | $\bar 1$ | $\bar 2$ |
	  | $\bar 1$ | $\bar 1$ | $\bar 2$ | $\bar 0$ |
	  | $\bar 2$ | $\bar 2$ | $\bar 0$ | $\bar 1$ |

	  n = 4
	  | $+$      | $\bar 0$ | $\bar 1$ | $\bar 2$ | $\bar 3$ |
	  |----------+----------+----------+----------+----------|
	  | $\bar 0$ | $\bar 0$ | $\bar 1$ | $\bar 2$ | $\bar 3$ |
	  | $\bar 1$ | $\bar 1$ | $\bar 2$ | $\bar 3$ | $\bar 0$ |
	  | $\bar 2$ | $\bar 2$ | $\bar 3$ | $\bar 0$ | $\bar 1$ |
	  | $\bar 3$ | $\bar 3$ | $\bar 0$ | $\bar 1$ | $\bar 2$ |
*** Gruppenhomomorphismus
	$(G,+),(H,\oast), \varphi : G \to H$ Abbildung \\
	$\varphi$ heißt ein Gruppenhomomorphismus $\xLeftrightarrow{\text{Def}} \Forall a,b,c\in G: \varphi(a*b) = \varphi(a) \oast \varphi(b)$ \\
	$\varphi$ heißt ein Gruppenisomorphismus $\xLeftrightarrow{\text{Def}} \varphi$ ist bijektiver Gruppenhomomorphismus
**** Beispiel
	 1. $\varphi:\mathbb{Z} \to \mathbb{Z}, a\mapsto 2 a$ ist Gruppenhomomorphismus von $(\mathbb{Z},+)$ nach $(\mathbb{Z},+)$ denn:
		\[\varphi( a+ b) = 2(a + b) = 2 a + 2 b = \varphi(a) + \varphi(b) \Forall a,b\in\mathbb{Z}\]
		$\varphi$ ist aber kein Gruppenisomorphismus, denn $\varphi$ ist nicht surjektiv $(1\not\in \varphi = \varphi{\mathbb{Z}})$
	 2. $n\in\mathbb{N}$. Dann gilt $\varphi:\mathbb{Z}\to\frac{\mathbb{Z}}{n\mathbb{Z}},a\mapsto\bar a$ ist ein Gruppenhomomorphismus von $(\mathbb{Z},+)$ nach $(\frac{\mathbb{Z}}{n\mathbb{Z}}, +)$, denn
		\[\Forall a,b\in\mathbb{Z}:\varphi(a+b) = \overline{a + b} = \bar a + \bar b =\varphi(a) + \varphi(b)\]
		$\varphi$ ist kein Gruppenisomorphismus, denn $\varphi$ ist nicht injektiv ($\varphi(0) = \bar 0 = \bar n = \varphi(n)$, aber $0\neq n$)
	 3. $\varphi:\mathbb{Z}\to\mathbb{Z},a\mapsto a + 1$ ist kein Gruppenhomomorphismus von $(\mathbb{Z},+)$ nach $(\mathbb{Z},+)$, denn
		\[\varphi(2 + 6) = \varphi(8) = 9,~\text{aber}~\varphi(2)+\varphi(6) = 3 + 7 = 10\]
	 4. $\exp:\mathbb{R}\to\mathbb{R}_{\geq 0}, x\mapsto \exp{x} = e^x$ ist ein Gruppenisomorphismus von $(\mathbb{R},+)$ nach $(\mathbb{R}_{\geq 0},\cdot)$, denn:
		- \[\exp(a + b) = \exp(a)\exp(b) \Forall a,b\in\mathbb{R}\]
		- $exp$ ist bijektiv (vgl. Ana1 - Vorlesung)
**** Bemerkung 5.23
	 $(G,*),(H,\oast)$ Gruppen mit neutralen Elementen $e_G$ beziehungsweise $e_H,\varphi:G\to H$ Gruppenhomomorphismus. Dann gilt
	 1. $\varphi(e_G) = e_H$
	 2. $\Forall a\in G:\varphi(a') = \varphi(a)'$ (Hierbei ist $'$ das Inverse)
	 3. Ist \varphi Gruppenisomorphismus, dann gilt $\varphi^{-1}:H\to G$ ebenfalls Gruppenisomorphismus
	 $(G,*),(H,\oast)$ heißen isomorph $\xLeftrightarrow{\text{Def}}$ Ex existert ein Gruppenisomorphismus $\phi:G\to H$ Wir schreiben dann $(G,*) \cong (H,\oast)$
***** Beweis
	  1. Es $e_H\oast \varphi(e_G) = \varphi(e_G) = \varphi(e_G*e_G) = \varphi(e_G) \oast(e_G) \Rightarrow e_H = \varphi(e_G)$
	  2. Sei $a\in G$ Dann ist $e_H = \varphi(e_G) = \varphi(a*a') = \varphi(a)\oast(a') \Rightarrow \varphi(a') = \varphi(a)'$
	  3. $\varphi^{-1}$ ist bijektiv, noch zu zeigen: $\varphi^{-1}$ ist ein Gruppehomomorphismus, das heißt
		 \[\varphi^{-1}(c\oast d) = \varphi^{-1}(c)*\varphi^{-1}(d) \Forall c,d\in H\]
		 Seien $c,d\in H$ Weil $\varphi$ bijektiv: $\exists a,b\in G:\varphi(a) = c,\varphi(b) =d$
		 \[\Rightarrow \varphi^{-1}(c\oast d) = \varphi^{-1}(\varphi(a)*\varphi(b)) = \varphi^{-1}(\varphi(a*b)) = a*b = \varphi^{-1}(c)*\varphi^{-1}(d)\hfill\square\]
** Ring
   Ein Ring ist ein Tupel $(R,+,\cdot)$, bestehend aus einer Menge R und 2 Verknüpfungen:
   - $+:R\times R \to R,(a,b)\mapsto a + b$ \hfill genannt Addition
   - $\cdot:R\times R\to R, (a,b)\mapsto a\cdot b$ \hfill genannt Multiplikation
   welche den folgenden Bedingungen genügen
   - (R1) $(R,+)$ ist eine abelsche Gruppe
   - (R2) $(R,\cdot)$ ist ein Monoid
   - (R3) Es gelten die Distributivgeseze, das heisßt
	 \[\Forall a,b,c\in R: a\cdot(a + b) = a\cdot b + a\cdot c, (a+b)\cdot c = a\cdot c + b\cdot c\]
   Ein Ring heißt *kommutativ* $\xLeftrightarrow{\text{Def}}$ die Multiplikation ist kommutativ, das heißt $\Forall a,b\in R: a\cdot b = b\cdot a$
*** Anmerkung
	- ohne Klammerung gilt die Konvention "$\cdot$" vor "$+$", "$\cdot$" wird häufig weggelassen
	- das neutrale Element bezüglich "$+$" bezeichnen wri mit $0_R$ (Nullelement), das neutrale Element bezüglich "$\cdot$" mit $1_R$ (Einselement). Das zu $a\in R$ bezüglich "$+$" inverse Element bezeichnen wir mit $-a$,
	  für $a + (-b)$ schreben wir $a - b$. Existiert zu $a\in R$ ein Inverses bezüglich "$\cdot$", so bezeichnen wir diesses mit $a^{-1}$
	- Wir schreiben häufig verkürzend "$R$ Ring" statt "$(R,+,\cdot)$ Ring"
	- In der Literatur wird gelegentlich die Forderung der Existenz eines neutralen Elements bezüglich "$\cdot$" weggelassen, "unser" Ringbegriff entspricht dort dem Begriff "Ring mit Eins"
*** Beispiel
	1. $(\mathbb{Z},+,\cdot)$ ist ein kommutativer Ring
	2. Nullring $(\{0\},+,\cdot)$ mit $0 + 0 = 0, 0\cdot 0 = 0$ ist ein kummutativer Ring \\
	   (hier ist Nullelement = Einselement = 0). Wir bezeichnen den Nullring kurz mit $0$.
*** Bemerkung 6.3
	$R$ Ring. Dann gilt:
	1. $0_R\cdot a = 0_R = a\cdot 0_R\Forall a\in R$
	2. $a\cdot (-a) = - a b = (-a) \cdot b \Forall a,b\in R$
	3. Ist $R\neq 0$, dann ist $1_R\neq 0_R$
**** Beweis
	 1. $0_R + 0_R\cdot a = 0_R\cdot a = (0_R + 0_R)\cdot a = 0_R\cdot a + 0_R\cdot \xRightarrow{\text{"kürzen s. [[Bemerkung 5.11]]"}} 0_R = 0_R \cdot a$, $a\cdot 0_R = 0_R$ analog
	 2. $0_R = 0_R\cdot b = (a + (-a))\cdot b = a\cdot b + (-a) \cdot b \Rightarrow{\text{[[Bemerkung 5.11]]}} - a b = (-a)\cdot b$, $a\cdot(-b) 0 -a b$ analog
	 3. Beweis durch Kontraposition: Sei $1_R = 0_R$
		\[\Rightarrow \Forall a\in R: a = a\cdot 1_R = a\cdot 0_R = 0_R\]
		das heißt $R = 0\hfill\square$
*** Bemerkung 6.4
	$n\in\mathbb{N}$ Für $\bar a, \bar b \in\frac{\mathbb{Z}}{n\mathbb{Z}}$ setzen wir $\bar a + \bar b := \overline{a + b}, \bar a\cdot \bar b := \overline{ab}$, dann ist $(\frac{\mathbb{Z}}{n\mathbb{Z}},+,\cdot)$ ein kommutativer Ring.

	Wenn wir ab jetzt vom Ring $\frac{\mathbb{Z}}{n\mathbb{Z}}$ sprechen, dann meinen wir $(\frac{\mathbb{Z}}{n\mathbb{Z}},+,\cdot)$ mit den obigen Verknüpfungen
**** Beweis
	 1. Multiplikaiton ist wohldefiniert (das heißt "vertreterunabhängig", vergleiche [[Bemerkung 5.18]]) \\
		Sei $a_1,a_2,b_1,b_2 \in\mathbb{Z}$ mit $\overline{a_1} = \overline{a_2},\overline{b_2} = \overline{b_2}$
		\begin{align}
		&\Rightarrow a_1 \equiv a_2 (\mod n), b_1\equiv b_2 (\mod n) \\
		&\Rightarrow \exists q_1,q_2\in\mathbb{Z}:a_1 - a_2 = q_1 n, b_1 - b_2 = q_2 n \\
		&\Rightarrow a_1 b_2 - a_2 b_2 = a_1(b_1 - b_2) + b_2 (a_1 - a_2) = a_q q_2 n + b_2 q_1 n = (a_1 q_2 + b_2 q_1) n \\
		&\Rightarrow a_1 b_1 \equiv a_2 b_2 (\mod n) \\
		&\Rightarrow \overline{a_1 b_1} = \overline{a_2 b_2}
		\end{align}
	 2. Multiplikation ist assoziativ, Für $a,b,c\in\mathbb{Z}$ ist
		\[\bar a\cdot (\bar b\cdot \bar c) = \bar a \cdot \overline{a\cdot c} = \overline{a\cdot(b\cdot c)} = \overline{(a\cdot b)\cdot c} = \overline{a\cdot b} \cdot \bar c = (\bar a\cdot \bar b) \cdot \bar c\]
	 3. Existenz eines Enselements: $\Forall a\in\mathbb{Z}:\bar 1 \cdot \bar a = \overline{1\cdot a} = \bar a = \bar a\cdot \bar 1$
	 4. Multiplikation ist kommutativ:
		\[\Forall a,b\in\mathbb{Z}:\bar a\cdot \bar b = \overline{a\cdot b} = \overline{b\cdot a} = \bar b \cdot \bar a\]
	 5. $(\frac{\mathbb{Z}}{n\mathbb{Z}},+)$ ist abelsche Gruppe nach [[Bemerkung 5.18]]
	 6. Distributivgesetz:
		\begin{align}
		\bar a\cdot (\bar b + \bar c) &= \bar a \cdot \overline{b + c} \\
		&= \overline{a\cdot (b + c)} \\
		&= \overline{a\cdot b + a\cdot c} \\
		&= \overline{a\cdot b} + \overline{a\cdot c}
		&= \bar a\cdot \bar b + \bar a \cdot\bar c
		\end{align}
		$(\bar a + \bar b)\cdot \bar c = \bar a\cdot \bar c + \bar b \cdot \bar c$ folgt wegen Kommutativität der Multiplikation
**** Beispiel 6.5
	 Verknüpfungstafeln für $\frac{\mathbb{Z}}{n\mathbb{Z}}$
	 n = 3:
	 | $+$      | $\bar 0$ | $\bar 1$ | $\bar 2$ |
	 |----------+----------+----------+----------|
	 | $\bar 0$ | $\bar 0$ | $\bar 1$ | $\bar 2$ |
	 | $\bar 1$ | $\bar 1$ | $\bar 2$ | $\bar 0$ |
	 | $\bar 2$ | $\bar 2$ | $\bar 0$ | $\bar 1$ |
	 
	 | $\cdot$  | $\bar 0$ | $\bar 1$ | $\bar 2$ |
	 |----------+----------+----------+----------|
	 | $\bar 0$ | $\bar 0$ | $\bar 0$ | $\bar 0$ |
	 | $\bar 1$ | $\bar 0$ | $\bar 1$ | $\bar 2$ |
	 | $\bar 2$ | $\bar 0$ | $\bar 2$ | $\bar 1$ |
	 n = 4:
	 | $+$      | $\bar 0$ | $\bar 1$ | $\bar 2$ | $\bar 3$ |
	 |----------+----------+----------+----------+----------|
	 | $\bar 0$ | $\bar 0$ | $\bar 1$ | $\bar 2$ | $\bar 3$ |
	 | $\bar 1$ | $\bar 1$ | $\bar 2$ | $\bar 3$ | $\bar 0$ |
	 | $\bar 2$ | $\bar 2$ | $\bar 3$ | $\bar 0$ | $\bar 1$ |
	 | $\bar 3$ | $\bar 3$ | $\bar 0$ | $\bar 1$ | $\bar 2$ |

	 | $\cdot$  | $\bar 0$ | $\bar 1$ | $\bar 2$ | $\bar 3$ |
	 |----------+----------+----------+----------+----------|
	 | $\bar 0$ | $\bar 0$ | $\bar 0$ | $\bar 0$ | $\bar 0$ |
	 | $\bar 1$ | $\bar 0$ | $\bar 1$ | $\bar 2$ | $\bar 3$ |
	 | $\bar 2$ | $\bar 0$ | $\bar 2$ | $\bar 0$ | $\bar 2$ |
	 | $\bar 3$ | $\bar 0$ | $\bar 3$ | $\bar 2$ | $\bar 1$ |

	 In $\frac{\mathbb{Z}}{n\mathbb{Z}}$ ist $\bar 2 \cdot \bar 2 = \bar 0$, aber $\bar 2\neq \bar 0$.
*** Integritätsbereich
	<<Definition 6.6>>
	ist ein kommuativer Ring $(R,+,\cdot)$ mit $R\neq 0$, in dem gilt:
	\[\Forall a,b\in R: a\cdot b = 0_R \Rightarrow a = 0_R\vee b = 0_R\]
	beziehungsweise äquivalent dazu:
	\[a\neq 0_R \wedge b\neq 0_R \Rightarrow a\cdot b \neq 0_R\]
**** Beispiel 6.7
	 - $\frac{\mathbb{Z}}{3\mathbb{Z}}$ ist ein Integritätsbereich, $\frac{\mathbb{Z}}{4\mathbb{Z}}$ ist kein Integritätsbereich, denn $\bar 2\cdot \bar 2 = \bar 0$, aber $\bar 2 \neq \bar 0$
**** Bemerkung 6.8
	 $n\in\mathbb{N}$ Dann sind äquivalent
	 1. <<6.8.1>> $\frac{\mathbb{Z}}{n\mathbb{Z}}$ ist ein Integritätsbereich
	 2. <<6.8.2>> $n$ ist eine Primzahl
***** Beweis
	  [[6.8.1]] \Rightarrow [[6.8.2]] zeigen wir durch Kontraposition, das heißt $\neq$[[ 6.8.2]] \Rightarrow $\neq$ [[6.8.1]] \\
	  Sei $n\in\mathbb{N}$ keine Primzahl. Falls $n = 1$ dann ist $\frac{\mathbb{Z}}{n\mathbb{Z}} = \{\bar 0\}$ (Nullring), das heißt $\frac{\mathbb{Z}}{n\mathbb{Z}}$ ist kein Integritätsbereich. Seim im Folgenden $n > 1$ und keine Primzahl.
	  \begin{align}
	  &\Rightarrow \exists a,b\in\mathbb{N}:1\ <a,b<n \wedge n = a\cdot b \\
	  &\Rightarrow \bar 0 = \bar n = \overline{a b} = \bar a \cdot \bar b
	  \end{align}
	  und es ist $bar a,\bar b\neq \bar 0$ \Rightarrow $\frac{\mathbb{Z}}{n\mathbb{Z}}$ kein Integrationsbereich. \\
	  [[6.8.2]] \Rightarrow [[6.8.1]]: Sein $n$ eine Primzahl \Rightarrow $n > 1$, insbesondere $\frac{\mathbb{Z}}{n\mathbb{Z}} \neq 0$. Seien $\bar a, \bar b \in \frac{\mathbb{Z}}{n\mathbb{Z}}$ mit $\bar a\cdot \bar b = \bar 0$
	  \[\Rightarrow \exists q\in\mathbb{Z}:a b = q n\]
	  Da $n$ Primzahl, kommt $n$ n der Primfaktorzerlengung von $a b$ als Primfaktor vor \\
	  \Rightarrow $n$ kommt in der Primfaktorzerlegung von $a$ oder $b$ als Primfaktor vor \[\Rightarrow n\mid a \vee n\mid b \Rightarrow \bar a = \bar 0 \vee \bar b = \bar 0\]
** Körper
   <<Definition 6.9>>
   Ein Körper ist ein kommutativer Ring $(K,+,\cdot)$, in dem gilt $K\neq 0$ und jedes Element $a\in K, a\neq 0$ besitzt ein Inverses in $K$ bezüglich "$\cdot$", das heißt: $\exists b\in K:a\cdot b = 1_K$. Wir setzen $K^\ast := K\setminus\{0\}$
*** Beispiel
	1. $(\mathbb{R},+,\cdot),(\mathbb{Q},+,\cdot)$ sind Körper (mit den üblichen $+,\cdot$)
	2. $\frac{\mathbb{Z}}{3\mathbb{Z}}$ ist ein Körper (betrachte Verknüpfungstafel)
	3. $\frac{\mathbb{Z}}{4\mathbb{Z}}$ ist ein kein Körper: Das Element $\bar 2$ besitzt kein Inverses bezüglich "$\cdot$"
*** Bemerkung 6.11
	\label{remark:integ_neutral}
	$K$ Körper, Dann gilt:
	1. $0_K \neq 1_K$
	2. <<6.11.2>> $K$ ist ein Integritätsbereich
	3. $(K^\ast,\cdot)$ ist eine abelsche Gruppe mit neutralem Element $1_K$
**** Beweis
	 1. folgt aus [[Bemerkung 6.3]]
	 2. $K\neq 0$ nach Definition. Seien $a,b\in K$ mit $a b = 0_K$. Falls $a\neq 0_K$ dann
		\[b = 1_K \cdot b = (a^{-1} a)\cdot b = a^{-a}(a b) = a^{-1}\cdot 0_K = 0_K\]
		Insebesondere gilt: $a = 0\vee b = 0$
	 3. $K^\ast\times K^\ast \to K^\ast$ ist wohldefiniert nach [[6.11.2]] (aus $a,b\in K^\ast$ folgt $a b\in K^\ast$) \\
		Da $(K,\cdot)$ abelscher Monoid mit neutralem Element $1_K$ ist auch $(K^\ast,\cdot)$ abelscher Monid mit neutralem Element $1_K$.
		Nach [[Definition 6.9]] besitzt jedes Element $a\in K^\ast$ ein Inverses $b\in K$ mit $a b = 1_K$ Wegen $0_K \neq 1_K$ ist $b\neq 0_K$ (sonst $a b = a\cdot 0_K = 0_K \neq 1_K$), das heißt $b\in K^\ast\hfill\square$
*** Bemerkung 6.12
	$R$ Integritätsbereich, der nur endlich viele Elemente hat. Dann ist $R$ ein Körper.
**** Beweis
	 $R$ Integritätsbereich \Rightarrow $R\neq 0$ \\
	 Noch zu zeigen: $a\in R\setminus\{0_R\} \Rightarrow \exists b\in R: a b = 1_R$
	 Sei $a\in R\setminus\{0_R\}$. Wir betrachten die Abbildung $\varphi_a: R\to R,x\mapsto a x$
	 1. Behauptung: $\varphi_a$ ist injektiv, denn:
		\begin{align}
		\intertext{Seien $x,y\in R$ mit}
		\varphi_a(x) =\varphi_a(y) \Rightarrow a x = a y \Rightarrow a x + (-(a y)) = 0_R \\
		\intertext{Mit [[Bemerkung 6.3]] folgt:}
		\Rightarrow a x + a(-a) = -R \Rightarrow a(x - y) = 0_R  \\
		\intertext{Aus $R$ Integrationsbereich und $a\neq 0$ folgt:}
		x - y = 0 \Rightarrow x = y
		\end{align}
	 2. Da $R$ endlich ist und $\varphi_a$ inejktiv ist, ist $\varphi_a$ nach [[Bemerkung 4.19]] surjektiv
		\[\Rightarrow  \exists b\in R: \varphi_a(b) = 1_R \Rightarrow a b = 1_R\]
*** Folgerung 6.13
	$n\in\mathbb{N}$ Dann sind äquivalent
	1. <<6.13.1>> $\frac{\mathbb{Z}}{n\mathbb{Z}}$ ist ein Körper
	2. <<6.13.2>> $n$ ist eine Primzahl
**** Beweis
	 [[6.13.1]] \Rightarrow [[6.13.2]] durch Kontraposition: $\neq$ [[6.13.2]] \Rightarrow [[6.13.1]] \\
	 Sei $n$ keine Primzahl \Rightarrow $\frac{\mathbb{Z}}{n\mathbb{Z}}$ kein Integritätsbereich \Rightarrow $\frac{\mathbb{Z}}{n\mathbb{Z}}$ kein Körper \\
	 [[6.13.2]] \Rightarrow [[6.13.1]] Sei $n$ eine Primzahl \Rightarrow $\frac{\mathbb{Z}}{n\mathbb{Z}}$ Integritätsbereich, der nur endlich viele Elemente hat \Rightarrow $\frac{\mathbb{Z}}{n\mathbb{Z}}$ Körper
**** Notation
	 $p$ Primzahl. Man nennt $\mathbb{F}_P := \frac{\mathbb{Z}}{p\mathbb{Z}}$ auch den endlichen Körper mit $p$ Elemente
*** Definition 6.14
	$R$ Ring
	\[\cha(R):=\begin{cases} 0 & \sum_{k = 1}^n 1_R \neq 0 \Forall n\in\mathbb{N} \\ \min\{n\in\mathbb{N}\mid \sum_{k = 1}^n 1_R = 0_R\} & \text{sonst}\end{cases}\]
	heißt die Charakteristik von $R$
	\begin{ex} \mbox{}
	\begin{enumerate}
	\item $\cha(\mathbb{Z}) = \cha(\mathbb{Q}) = \cha(\mathbb{R}) = 0$
	\item $\cha(\frac{\mathbb{Z}}{n\mathbb{Z}}) = n$, denn $\sum_{k = 1}^n \bar 1 = \bar n = \bar 0$ und $\sum_{k = 1}^m \bar 1 = \bar m \neq \bar 0$ für $m\in\{1,\ldots,n - 1\}$
	\end{enumerate}
	\end{ex}
	\begin{remark}
	\label{remark:cha_prim}
	$R$ Integritätsbereich. Dann ist $\cha(R) = 0$ oder $\cha(R)$ ist eine Primzahl
	\end{remark}
	\begin{proof}
	Beweis durch Widerspruch. Annahme: $\cha(R) \neq 0$ und $\cha(R)$ ist keine Primzahl. \\
	Da $R$ Integritätsbereich ist ist $1_R \neq 0_R$ also $\cha(R) \neq 1$
	\begin{align*}
	&\Rightarrow \exists a,b\in\mathbb{N}, 1 < a,b < \cha(R): \cha(R) = a b \\
	&\Rightarrow 0_R = \sum_{k = 1}^{\cha(R)} 1_R = \sum_{k = 1}^a 1_R \cdot \sum_{k = 1}^b 1_R \\
	&\xRightarrow{R~\text{Integritätsbereich}} \sum_{k = 1}^a 1_R = 0_R \vee \sum_{k = 1}^b = 0_R \\
	&\Rightarrow \cha(R) \leq a \vee \cha(R)\leq b \lightning~\text{zu}~ a,b < \cha(R) \tag*{\qedhere}
	\end{align*}
	\end{proof}
	\begin{remark}
	$K$ Körper, dann ist $\cha(K) = 0$ oder $\cha(K)$ ist Primzahl.
	\end{remark}
	\begin{proof}
	Folgt aus \ref{remark:cha_prim} und \ref{remark:integ_neutral}
	\end{proof}
	\begin{ex}
	$p$ Primzahl, dann ist $\cha(\mathbb{F_p}) = p$
	\end{ex}
* Polynome
  \begin{defn}[7.1 Polynome]
  $K$ Körper, ein Polynom in der Varablen $t$ über $K$ ist ein Ausdruch der Form
  \[f = \sum_{k = 0}^n a_k t^k\]
  mit $n\in\mathbb{N}_0$ (das heißt insbesondere nur endliche Summanden), $a_0,\ldots,a_n \in K$ (fehlende $a = 0$, ebenso setzen wir $a_{k > n} = 0)$. Die $a_k$ heißen die Koeffizienten von $f$
  \[\deg(f) := \begin{cases}-\infty & f = 0 \\  \max\{k\in\mathbb{N}_0 \mid a_k \neq 0\} & f\neq 0\end{cases}\]
  heißt Grad von $f$. für $f\neq 0$ heißt $l(f) := a_{\deg(f)}$ heißt der Leitkoeffizient von $f$, $l(0) := 0$. $f$ heißt normiert $\xLeftrightarrow{\text{Def}} l(f) = 1$
  Hierbei sind zei Polynome $f = \sum_{k = 0}^n a_k t^k,g = \sum_{k =0}^m b_m t^k$ gleich ($f = g$) $\xLeftrightarrow{\text{Def}} \deg(f) = \deg(g) =: r$ und $a_r = b_r,\ldots,a_1 = b_1, a_0 = b_0$
  \end{defn}
  \begin{remark}
  Man kann das auch präzise machen (Algebra 1, WS15/16, Blatt 5, Aufgabe 3)
  \end{remark}
  \begin{ex}[7.2] \mbox{}
  \begin{enumerate}
  \item $f = \frac{3}{4}x^2 - 7 x + \frac{1}{2} \in \mathbb{Q}[x] \Rightarrow \deg(f) = 2, l(f) = \frac{3}{4}, f$ ist nicht normiert
  \item $f = x^5 - \frac{1}{3} x + \frac{2}{5} \in\mathbb{Q}[x] \Rightarrow \deg(f) = 5, l(f) = 1, f$ ist normiert
  \end{enumerate}
  \end{ex}
  \begin{remark}[7.3]
  $K$ Körper, $f,g \in K[t], f = \sum_{k = 0}^n a_k t^k, g = \sum_{k = 0}^m b_k t^k$. Wir setzen $r:= \max\{m,n\}$ und definieren
  \begin{align*}
  f + g &= (a_r + b_r)t^r + \ldots + (a_1 + b_1)t + (a_0 + b_0) \\
  f \cdot g &= c_{n + m} t^{n + m} + \ldots + c_1 t + c_0, c_k := \sum_{\substack{i,j \in\mathbb{N}_0 \\ i + j = k}} a_i b_j
  \end{align*}
  Mittels der Verknüpfung $+,\cdot$ wir die Menge aller Polynome über $K$ in der Variablen $t (=: K[t])$ zu einem kommutativen Ring, dem Polynomring über $K$ in der Variablen $t$
  \end{remark}
  \begin{proof}
  Man rechnet die Ringaxiome nach
  \end{proof}
  #+ATTR_LATEX: :options [7.4]
  #+BEGIN_REMARK latex
  \label{remark:74}
  $K$ Körper, $f,g\in K[t]$, Dann gilt:
  1. $\deg(f + g) \leq \max\{\deg(f),\deg(g)\}$
  2. $\deg(f g) = \deg(f) + \deg(g)$
  (Hierbei setzt man Formel für $n\in\mathbb{N}_0: -\infty < n, n + (-\infty) = -\infty = (-\infty) + n, (-\infty) + -(\infty) = -\infty)$
  #+END_REMARK
  #+BEGIN_PROOF latex
  Falls $f = 0$ oder $g = 0$, dann sind 1. und 2. klar. Im Folgenden seien $f,g\neq 0$, etwa $f = \sum_{k = 0}^n a_k t^k, g = \sum_{k =0}^m b_k t^k$ mit $a_n, b_m \neq 0$ (insbesondere $\deg(f) = n, \deg(g) = m$)
  1. Wir setzen $k:= \max\{m,n\}$
	 \begin{align*}
	 &\Rightarrow f + g = (a_k + b_k)t^k + \ldots + (a_1 + b_1)t + (a_0 + b_0) \\
	 &\Rightarrow \deg(f + g) \leq k \tag{\text{beachte: Ex könnte $a_k + b_k = 0$ sein}}
	 \end{align*}
  2. Es sei $f g = a_n b_m t^{n + m} + \ldots + a_0 b_0$ und es ist $a_n b_m \neq 0$ da $K$ als Körper ein Integritätsbereich ist $\Rightarrow \deg(f g) = n + m$
  #+END_PROOF
  #+ATTR_LATEX: :options [7.5]
  #+BEGIN_CONC latex
  $K$ Körper, dann ist $K[t]$ ein Integritätsbereich
  #+END_CONC
  #+BEGIN_PROOF latex
  $K[t] \neq 0$ klar (zum Beispiel $t\in\mathbb{t}$)
  Seien $f,g\in K[t], f,g\neq 0 \Rightarrow \deg(f),\deg(g) \geq 0 \Rightarrow \deg(f g) = \deg(f) + \deg(g) \geq 0 \Rightarrow f g \neq 0$
  #+END_PROOF
  #+begin_remark latex
  $K[t]$ ist kein Körper: Das Polynom $t\in K[t]$ besitzt kein Inverses bezüglich "$\cdot$", denn: \\
  Wäre $f\in K[t]$ invers zu $t$, dann wäre $f t = 0 \Rightarrow \deg(1) = 0 \deg(f t) = \deg(f) + \deg(t) = \deg (f) + 1 \Rightarrow \deg(f) = -1 \lightning$
  #+end_remark

  #+ATTR_LATEX: :options [7.6 Polynomdivision]
  #+begin_thm latex
  \label{thm:poly_div}
  $K$ Körper, $f,g\in K[t], g\neq 0$ \\
  Dann existieren eindeutig bestimmte Polynome $q,r \in K[t]$, mit $f = q g + r$ und $\deg(r) < \deg(g)$
  #+end_thm

  #+ATTR_LATEX: :options [7.7]
  #+begin_ex latex
  $f = 3 t^3 + 5 t + 1, g = t^2 + 1 \in\mathbb{Q}[t]$
  \[(3 t^3 + 5 t + 1) : (t ^2 + 1) = 3 t\]
  Also $3 t^3 + 5t + 1 = 3^t (t^2 + 1) + 2 t + 1, q = 3 t, r = 2 t + 1$
  #+end_ex

  #+ATTR_LATEX:
  #+begin_proof latex
  1. Existenz: \\
	 Falls $f = 0$, setzen wir $q := 0, r:= 0$ fertig. \\
	 Im Folgenden sei $f\neq 0$, das Polynom $g$ sei fixiert. Wir zeigen die Existenz von $q,r$ per Induktion nach $\deg(f) \in\mathbb{N}_0$ \\
	 - Induktionsanfang: (etwas unkonventionell, geht aber auch): $\deg(f) \in \{0,\ldots,\deg(g) - 1\}$ (das heißt $\deg(f) < \deg(g)$) \\
	   Setze $q:= 0, r:= g$, dann ist $f = q g + r, \deg(r) = \deg(f) < \deg(g)$.
	 - Induktionsschritt: Es sei $\deg(f) \geq \deg(g)$ und die Behauptung sei für alle Polynome aus $K[t]$ von Grad < $\deg(f)$ schon gezeigt. \\
	   Wir sezen $n:= \deg(f), m:=\deg(g)$ und schreiben:
	   \[f = l(f)t^n + ~\text{Terme kleineren Grades}\]
	   \[g = l(g) t^m + ~\text{Terme kleineren Grades}\]
	   Es ist $f - \frac{l(f)}{l(g)}t^{n - m}g =$
	   \[l(f) t^n + ~\text{Terme kleineren Grades} - \underbrace{\frac{l(f)}{l(g)} t^{n - m}l(g) t^m}_{l(f)t^n} + ~\text{Terme kleineren Grades}\]
	   \[\Rightarrow \deg(f - \frac{l(f)}{l(g)}t^{n - m}) < n\]
	   Nach Induktionsannahme gilt: Es existert $q_1,r_1 \in K[t]$ mit
	   \[f - \frac{l(f)}{l(g)}t^{n -m}g = q_1 g + r_1, ~\text{mit}~\deg{r_1} < \deg(g)\]
	   \[\rightarrow f = (q_1 + \frac{l(f)}{l(g)} t^{n - 1})g + r_1\]
	   Setze $q:= q_1 + \frac{l(f)}{l(g)}t^{n - m}, r:= r_1$, dann ist $f = q g + r$ und $\deg(r) < \deg(g)$
  2. Eindeutigkeit: Seien $q_1,q_2,r_1,r_2\in K[T]$ mit $f = q_1 g + r_1 + q_2 g + r_2$ und $\deg(r_1) < \deg(g), \deg(r_2) < \deg(g)$
	 \begin{align*}
	 &\Rightarrow (q_1 - q_2) g = r_2 - r_1 \\
	 &\Rightarrow \deg(g_1 - q_2) + \deg(g) = \deg(r_1 - r_2)
	 \end{align*}
	 Falls $q_1 \neq q_2$, dann sind beide Seiten der Gleichung in $\mathbb{N}_0$ und es wäre
	 \[\deg(g) \leq \deg(r_2 - r_1)\]
	 Nach \ref{remark:74} ist $\deg(r_2 - r_1) \leq \max\{\deg(r_2),\deg(-r_1)\} < \deg(g) \lightning$
	 Also $q_1 = q_2$, somit $r_2 - r_1 = \underbrace{q_1 - q_2}_{= 0} g = 0$, also $r_1 = r_2$
  #+end_proof
  #+ATTR_LATEX: :options [7.8, Nullstelle]
  #+begin_defn latex
  $\in K[t], f = a_n t^n + \ldots + a_1 t + a_0, \lambda \in K$ \\
  Wir setzen $f(\lambda) := a_n \lambda^n + \ldots + a_1\lambda + a_0 \in K$
  $\lambda$ heißt Nullstelle von $f \xLeftrightarrow{Def.} f(\lambda) = 0$
  #+end_defn
  #+ATTR_LATEX: :options [7.9]
  #+begin_remark latex
  \label{remark:79}
  $K$ Körper, $f\in K[t], \lambda \in K$ Nullstelle von $f$. Dann gibt es in $K[t]$ ein eindeutig bestimmtes Polynom $q$ mit $f = (t - \lambda)q$.
  Es ist $\deg(q) = \deg(f) - 1$
  #+end_remark
  #+begin_proof latex
  *Existenz:* Nach \ref{thm:poly_div} existiert $q,r\in K[t]$ mit $f = (t - \lambda)q + r$ und $\deg(r) < \underbrace{\deg(t - \lambda)}_{= 1}$ \\
  \Rightarrow $r$ ist konstantes Polynom und es gilt
  \[0 = f(\lambda) = \underbrace{(\lambda - \lambda)}_{= 0} q + r(\lambda) = r(\lambda) \Rightarrow r = 0 \Rightarrow f = (t - \lambda) q\]
  *Eindeutigkeit:* aus Eindeutigkeit aus \ref{thm:poly_div}
  #+end_proof
  #+begin_conc latex
  $K$ Körper, $f\in K[t], f\neq 0, n:= \deg(f)$ \\
  Dann besitzt $f$ in $K$ höchstens $n$ Nullstellen.
  #+end_conc
  #+begin_proof latex
  per Induktion nach $n$
  *Induktionsanfang:* $n = 0$ Ein konstantes Polynom $\neq 0$ besitzt keine Nullstellen. \\
  *Induktionsschritt:* Es sein $n > 0$ und die Aussage sei für alle Polynome von Grad $< n$ schon gezeigt.
  Falls $f$ keine Nullstelle besitzt, dann fertig.
  Im Folgenden besitzte $f$ eine Nullstelle sei $\lambda \in K$ eine solche, daraus folgt mit \ref{label:79}
  \[\exists q\in K[t]: f(t - \lambda)q, \deg{q} = n - 1\]
  Ist $\varepsilon \neq \lambda$ eine weitere Nullstelle von $f$ dann ist
  \[0 = f(\varepsilon) = \underbrace{\varepsilon - \lambda}_{\neq 0}q(\varepsilon)\]
  Da $K$ als Körper ein Integritätsbereich ist folt: $q(\varepsilon) = 0$, das heißt $\varepsilon$ ist Nullstelle von $q$.
  Nach Induktionsvorraussetzung hat $q$ höchstens $n-1$ Nullstellen \Rightarrow $f$ hat höchstens $n$ Nullstellen
  #+end_proof
  #+ATTR_LATEX: :options [7.11]
  #+begin_defn latex
  \label{dfn:zero}
  $K$ Körper, $f\in K[t], f\neq 0,\lambda \in K$
  \[\mu (f,\lambda) := \max\{e\in\mathbb{N}_0 \mid \Exists g\in K[t]: f = (t - \lambda)^e g\}\]
  heißt die Vielfachheit der Nullstelle $\lambda$ von $f$.
  #+end_defn
  #+begin_remark latex
  - Es ist $\mu(f,\lambda) = 0 \Leftrightarrow f(\lambda) \neq 0 \lambda$ keine Nullstelle von $f$ (denn: $f(\lambda) = 0 \Leftrightarrow \Exists q\in K[t]: f=(t - \lambda)q \Leftrightarrow \mu(f,\lambda) \neq 0$)
  - Die Vielfachheit von $\lambda$ gibt an, wie oft der Linearfaktor $t - \lambda$ in $f$ vorkommt
  - Sind $\lambda_1,\ldots,\lambda_m \in K$ sämtliche verschiedene Nullstellen von $f$ und es ist $e_i := \mu(f,\lambda_i),i = 1,\ldots,m$ dann existerit ein Polynom $g\in K[t]$ mit
	\[f = (t - \lambda_1)^{e_1}\cdot\ldots\cdot(t-\lambda_m)^{e_m}g\]
	und den Eigenschaften, dass $g$ in $K$ kein Nullstelle besitzt und, dass $\deg(g) = \deg(f) - (e_1 + \ldots + e_m)$.
  - "bester Fall:" $\deg(g) = 0$ ("$f$ zerfällt in Linearfaktoren"):
	Dann existert $a\in K\setminus\{0\}, \lambda_1,\ldots, \lambda_m \in k$ paarweise verschieden, $e_1,\ldots,e_n \in \mathbb{N}$  mit
	\[f = a(t - \lambda_1)^{e_1}\cdot\ldots\cdot(t - \lambda_m)^{e_m}, e_1 + \ldots + e_m = \deg(f)\]
	Alternative Darstellung:
	\[f = a(t - \tilde\lambda_1) \cdot \ldots\cdot(t - \tilde\lambda_n), n = \deg(f), \tilde\lambda_1,\ldots\tilde\lambda_n~\text{nicht notwendig verschieden}\]
  #+end_remark
  #+ATTR_LATEX: :options [7.12 Fundamentalsatz der Algebra]
  #+begin_thm latex
  Jedes Polynom $f \in \mathbb{C}[t]$ mit $\deg(f) \geq 1$ besitzt eine Nullstelle.
  #+end_thm
  #+begin_proof latex
  Zum Beispiel in Vorlesung Funktionentheorie 1, Algebra 1
  #+end_proof
  #+ATTR_LATEX: :options [7.13]
  #+begin_conc latex
  $f\in\mathbb{C}[t], f\neq 0$
  Dann zerfällt $f$ in Linearfaktoren.
  #+end_conc
  #+begin_proof latex
  *Induktionsanfang:* $n = 0 \Rightarrow f$ ist konstantes Polynom, fertig \\
  *Induktionsscritt:* Sei $n\geq 1$ und die Assage sei für alle Polynome vom Grad $< n$ bereits bewiesen. Nach Fundamentalsatz der Algebra existiert eine Nullstelle $\lambda$ von $f$
  \[\xRightarrow{\ref{remark:79}} \Exists g\in \mathbb{C}[t]: f = (t - \lambda)g, \deg(g) = n - 1 \]
  Nach Induktionsannahme $\Exists a\in\mathbb{C},\lambda_1,\ldots,\lambda_{n - 1} \in \mathbb{C}$ (nicht notwendig verschieden)
  \[g = a(t - \lambda_1)\cdot\ldots\cdot(t - \lambda_{n-1})\]
  Setze $\lambda_n := x \Rightarrow f = g(t - \lambda_n) = a(t - \lambda_1)\cdot\ldots\cdot(t - \lambda_{n - 1})(t - \lambda_n)$
  #+end_proof

  #+ATTR_LATEX: :options [7.14]
  #+begin_defn
  $K$ Körper, $f\in K[t]$
  $f$ induziert eine Abbildung $\tilde f: K\to K,\lambda\to f(\lambda)$, $\tilde f$ heißt die Polynomfunktion zum Polynom $f$
  #+end_defn
  #+ATTR_LATEX: :options [7.15]
  #+begin_ex latex
  \label{ex:715}
  Es ist wichtig zwischen dem Polynom $f\in K[t]$ und der dazugehörigen Polynomfunktion $\tilde f: K\to K$ zu unterscheiden
  Sei $f = t^2 + t \in \mathbb{F}_2 [t]$. Dann ist $f(\bar 0) = \bar 0^2 + \bar 0 = \bar 0, f(\bar 1) = \bar 1^2 + \bar 1 = \bar 0$
  das heißt $\tilde f: \mathbb{F}_2 \to \mathbb{F}_2$ ist die Nullabbildung, aber $f$ ist nicht das Nullpolynom
  #+end_ex
  #+ATTR_LATEX: :options [7.16]
  #+begin_remark latex
  \label{remark:716}
  $K$ Körper mit unendlich vielen Elementen. \\
  Dann ist die Abbildung $\tilde : K[t]\to$ Abb$(K,K):=\{g:K\to K ~\text{Abbildung}\}, f\mapsto \tilde f$ injektiv, das heißt:
  Ist $K$ unendlich und sind $f_1,f_2 \in K[t]$, dann gilt $f_1 = f_2 \Leftrightarrow \tilde f_1 = \tilde f_2$
  #+end_remark
  #+begin_proof latex
  Es seien $f_1,f_2 \in K[t]$ mit $\tilde f_1 = \tilde f_2$ wir setzen $g:= f_1 - f_2$ \\
  \Rightarrow Für alle $a\in K$ ist $g(a) = (f_1 - f_2)(a) = f_1(a) - f_2(a) = \tilde f_1(a) - \tilde f_2(a) = 0$
  $\xRightarrow{K~\text{unendlich}}$ g hat unendlich viele Nullstellen, mit \ref{dfn:zero} folgt: $g = 0\Rightarrow f_1 = f_2$
  #+end_proof
  #+begin_remark latex
  - Lässt man \ref{remark:716} die Vorraussetzung $K$ hat unendlich viele Elemente weg, wird die Aussage falsch, siehe Beispiel \ref{ex:715}
  - Mit dem Wissen von \ref{ex:715} und \ref{remark:716} im Hintergrund bezeichnet man die vom Polynom $f$ induzierte Polynomfunktion mit $f$ anstelle von $\tilde f$
  #+end_remark
* Vektorräume
  In diesem Kapitel sei $K$ stets ein Körper
  #+ATTR_LATEX: :options [8.1]
  #+begin_defn latex
  Ein K-Vektorraum ist ein Tripel $(V,+,\cdot)$ bestehend aus
  - einer Menge $V$
  - einer Verknüpfung $+:V\times V \to V, (v,w)\mapsto v + w$ \hfill (Addition)
  - und einer äußeren Verknüpfung $\cdot : K\times V \to V, (\lambda,v) \mapsto \lambda \cdot v$ \hfill (skalare Multiplikaiton)
  Welche folgende Bedingungen genügen:
  1. (V1) $(V,+)$ ist eine abelsche Gruppe
  2. (V2) Die skalare Multiplikaiton ist in folgender Weise mit der anderen Verknüpfung (auf $V$ und $K$) verträglich:
	 \begin{align*}
	 \intertext{$\Forall \lambda,\mu \in K, v,w\in V$}
	 (\lambda + \mu) \cdot v  &= \lambda \cdot v + \mu \cdot v \\
	 \lambda \cdot (v + w) = \lambda \cdot v + \lambda \cdot w \\
	 \lambda \cdot (\mu \cdot w) = (\lambda \cdot \mu) \cdot v \\
	 1\cdot v = v
	 \end{align*}
  #+end_defn
  #+begin_remark latex
  - Es ist wichtig, zwischen Addition "$+$" und skalarer Multiplikation "$\cdot$" auf $V$ und Addition und Multiplikation in $K$ zu unterschieden:
	In der Gleichung $(\lambda + \mu) \cdot v = \lambda \cdot v + \mu\cdot v$ sind die Verknüpfungen wie folgt zu verstehen:
	\[(\lambda \qquad\underarrow[+]{Addition in $K$}\qquad \mu) \qquad \overarrow[\cdot]{skalare Multiplikation} \qquad v = \lambda \qquad \underarrow[\cdot]{skal. Mult.} \qquad v \overarrow[+]{Addition in $V$} \mu\qquad\underarrow[\cdot]{skal. Mult.} \qquad v\]
  - Das neutrale Element bezüglich "$+$" auf $V$ bezeichnen wir mit $0_v$ (Nullvektor), das inverse zu $v\in V$ bezüglich "$+$" mit $-v$. Das Zeichen "$\cdot$" fpr die skalare Multiplikation lassen wir ab jetzt meistens weg und schreiben $\lambda v$ statt $\lambda\cdot v$ ($\Forall \lambda\in K, v\in V$)
  - Wir schreiben meist verkürzend "V K-Vektorraum" (beziehungsweise: "V K-VR") anstelle von $(V,+,\cdot)$ K-Vektorraum.
  #+end_remark
  #+ATTR_LATEX: :options [8.2]
  #+begin_ex latex
  1. \[K^n := \{(x_1,\ldots,x_n) \mid x_1,\ldots,x_n \in K\}\]
	 mit
	 \[(x_1,\ldots,x_n) + (y_1,\ldots,y_n) := (x_1 + y_1,\ldots,x_n + y_n)\]
	 \[\lambda\cdot(x_1,\ldots,x_1) := (\lambda x_1,\ldots,\lambda x_n)\]
	 \[\lambda \in K, (x_1,\ldots,x_n),(y_1,\ldots,y_n)\in K^n\]
	 ist ein K-Vektorraum, der sogenannte Standardvektorraum über $K$
	 Die Axiome rechnet man nach, exemplarisch: sind $\lambda,\mu\in K, (x_1,\ldots,x_n)\in K^n$, dann ist
	 \[(\lambda + \mu) \cdot (x-1,\ldots,x_n) = ((\lambda + \mu)x_1,\ldots,(\lambda + \mu)x_n)\]
	 Mit dem Distributivgesetz in $K$ folgt:
	 \[(\lambda x_1,\ldots,\lambda x_n) + (\mu x_1,\ldots,\mu x_n) = \lambda(x_1,\ldots,x_n) + \mu(x_1,\ldots,x_n)\]
	 Der Nullvektor ist gegeben duch $0_{K^n} = (0,\ldots,0)$, für $x =(x_1,\ldots,x_n)$ ist $-x = (-x_1,\ldots,-x_n)$
  2.
  #+end_ex
