#+AUTHOR: Robin Heinemann
#+TITLE: Lineare Algebra (Vogel)
#+LATEX_HEADER: \usepackage{siunitx}
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \sisetup{load-configurations = abbrevations}
#+LATEX_HEADER: \newcommand{\estimates}{\overset{\scriptscriptstyle\wedge}{=}}
#+LATEX_HEADER: \usepackage{mathtools}
#+LATEX_HEADER: \DeclarePairedDelimiter\abs{\lvert}{\rvert}%
#+LATEX_HEADER: \DeclarePairedDelimiter\norm{\lVert}{\rVert}%
#+LATEX_HEADER: \DeclareMathOperator{\Exists}{\exists}
#+LATEX_HEADER: \DeclareMathOperator{\Forall}{\forall}
#+LATEX_HEADER: \def\colvec#1{\left(\vcenter{\halign{\hfil$##$\hfil\cr \colvecA#1;;}}\right)}
#+LATEX_HEADER: \def\colvecA#1;{\if;#1;\else #1\cr \expandafter \colvecA \fi}

* Einleitung
  # Passwort für Downloads (Webseite Prof. Gade): GRUNDVORLESUNG
  Übungsblätter/Lösungen:
  jew. Donnerstag / folgender Donnerstag
  Abgabe Donnerstag 9:30
  50% der Übungsblätter
** Plenarübung
   Aufgeteilt
** Moodle
   Passwort: vektorraumhomomorphismus
** Klausur
   24.02.2017
* Grundlagen
** Naive Aussagenlogik
   naive Logik: wir vewenden die sprachliche Vorstellung ($\neq$ mathematische Logik: eigne Vorlesung)
   Eine Aussage ist ein festehender Satz, dem genau einer der Wahrheitswerte "wahr" oder "falsch" zugeordnet werden kann.
   Aus einfachen Aussagen kann man durch logische Verknüpfungen kompliziertere Aussagen bilden.
   Angabe der Wahrheitswertes der zusammengesetzten Aussage erfolgt duch Wahrheitstafeln (liefern den Wahrheitswert der zusammengesetzten Aussage, aus dem Wahrheitswert der einzelnen Aussagen).
   Im folgenden seien $A$ und $B$ Aussagen.
   - Negation (NICHT-Verknüpfung)
	 - Symbol: $\neg
     - Wahrheitstafel:
       | $A$ | $\neg A$ |
       |-----+----------|
       | w   | f        |
       | f   | w        |
	 - Beispiel: $A$: 7 ist eine Primzahl (w)
	   $\neg A$: 7 ist keine Primzahl (f)

   - Konjunktion (UND-Verknüpfung)
	 - Symbol $\wedge$
	 - Wahrheitstafel:
       | $A$ | $B$ | $A\wedge B$ |
       |-----+-----+-------------|
       | w   | w   | w           |
       | w   | f   | f           |
       | f   | w   | f           |
       | f   | f   | f           |

   - Disjunktion (ODER-Verknüpfung)
	 - Symbol: $\vee$
	 - Wahrheitstafel:
       | $A$ | $B$ | $A\vee B$ |
       |-----+-----+-----------|
       | w   | w   | w         |
       | w   | f   | w         |
       | f   | w   | w         |
       | f   | f   | f         |
	 - exklusives oder: $(A\vee B) \wedge (\neg(A\wedge B))$
   - Beispiel $A$: 7 ist eine Primzahl (w), $B$: 5 ist gerade (f)
	 - $A\wedge B$ 7 ist eine Primzahl und 5 ist gerade (f)
	 - $A\vee B$ 7 ist eine Primzahl oder 5 ist gerade (w)

   - Implikation (WENN-DANN-Verknüpfung)
	 - Symbol: $\Rightarrow$
	 - Wahrheitstafel:
       | $A$ | $B$ | $A\Rightarrow B$ |
       | w   | w   | w                |
       | w   | f   | f                |
       | f   | w   | w                |
       | f   | f   | w                |
	 - Sprechweise: $A$ impliziert $B$, aus $A$ folgt $B$, $A$ ist eine hinreichende Bedingung für $B$ (ist $A\Rightarrow B$ wahr, dann folgt aus $A$ wahr, $B$ ist wahr), $B$ ist eine notwendige Bedingung für $A$ (ist $A\Rightarrow B$ wahr, dann kann $A$ nur dann wahr sein, wenn Aussage $B$ wahr ist)
	 - Beispiel Es seinen $m,n\in\mathbb{N}$
	   - $A$: m ist gerade
	   - $B$: $mn$ ist gerade
	   - Dann gilt $\Forall m,n \in\mathbb{N}~A\Rightarrow B~\text{wahr}$ \\
		 Fallunterscheidung:
		 - $m$ gerade, $n$ gerade, dann ist $A$ wahr, $B$ wahr, d.h. $A\Rightarrow B$ wahr
		 - $m$ gerade, $n$ ungerade, dann ist $A$ wahr, $B$ wahr, d.h. $A\Rightarrow B$ wahr
		 - $m$ ungerade, $n$ gerade, dann ist $A$ falsch, $B$ wahr, d.h. $A\Rightarrow B$ wahr
		 - $m$ ungerade, $n$ ungerade, dann ist $A$ falsch, $B$ falsh, d.h. $A\Rightarrow B$ wahr
   - Äquivalenz (GENAU-DANN-WENN-Verknüpfung)
	 - Symbol $\Leftrightarrow$
	 - Wahrheitstafel:
       | $A$ | $B$ | $A\Leftrightarrow$ B |
       |-----+-----+----------------------|
       | w   | w   | w                    |
       | w   | f   | f                    |
       | f   | w   | f                    |
       | f   | f   | w                    |
	 - Sprechweise: $A$ gilt genau dann, wenn $B$ gilt, $A$ ist hinreichend und notwendig für $B$ \\
	   Die Aussagen $A\Leftrightarrow B$ und $(A\Rightarrow B)\wedge (B\Rightarrow A)$ sind gleichbedeutend:
       | $A$ | $B$ | $A\Leftrightarrow B$ | $A\Rightarrow B$ | $B\Rightarrow A$ | $(A\Rightarrow B)\wedge (B\Rightarrow A)$ |
       |-----+-----+----------------------+------------------+------------------+-------------------------------------------|
       | w   | w   | w                    | w                | w                | w                                         |
       | w   | f   | f                    | f                | w                | f                                         |
       | f   | w   | f                    | w                | f                | f                                         |
       | f   | w   | f                    | w                | f                | f                                         |
       | f   | f   | w                    | w                | w                | w                                         |
	 - Beispiel: Es sei $n$ eine ganze Zahl \\
	   $A:~n-2>1$ \\
	   $B:~n>3$ \\
	   $\Forall n\in\mathbb{N}~\text{gilt}~A\Leftrightarrow B$
	   $C:~n>0$ \\
	   $D:~n^2>0$ \\
	   Für $n=-1$ ist die Äquivalenz $C\Leftrightarrow$ falsch ($C$ falsch, $D$ wahr) \\
	   Für alle ganzen Zahlen $n$ gilt zumindest die Implikation $C\Rightarrow D$
** Beweis
   Mathematische Sätze, Bemerkungen, Folgerungen, etc. sind meistens in Form wahrer Implikationen formuliert
*** beweisen
	Begründen warum diese Implikation wahr ist
*** Beweismethoden for diese Implikation $A\Rightarrow B$
	- direkter Beweis ($A\Rightarrow B$)
	- Beweis durch Kontraposition ($\neq B \Rightarrow \neg A$)
	- Widerspruchbeweis ($\neg (A\wedge \neg B)$)
    Diese sind äquivalent zueinander
    | $A$ | $B$ | $\neg A$ | $\neg B$ | $A\Rightarrow B$ | $\neg B \Rightarrow \neg A$ | $\neg (A \wedge \neg B)$ |
    |-----+-----+----------+----------+------------------+-----------------------------+--------------------------|
    | w   | w   | f        | f        | w                | w                           | w                        |
    | w   | f   | f        | w        | f                | f                           | f                        |
    | f   | w   | w        | f        | w                | w                           | w                        |
    | f   | f   | w        | w        | w                | w                           | w                        |
**** Beispiel
	 $m,n$ natürliche Zahlen \\
	 \[A:~m^2 < n^2\]
	 \[B:~m < n\]
	 Wir wollen zeigen, dass $A\Rightarrow B$ für alle natürlichen Zahlen $m,n$ wahr ist
	 - direkter Beweis: \\
	   \[A:~m^2 < n^2 \Rightarrow 0 < n^2 - m^2 \Rightarrow 0 < (n-m)\underbrace{(n+m)}_{>0} \Rightarrow 0 < n-m \Rightarrow m<n\]
	 - Beweis durch Kontraposition: \\
	   \[\neg B:~m \geq n \Rightarrow m^2\geq n m \wedge m n \geq n^2 \Rightarrow m^2 \geq n^2 \Rightarrow \neg A\]
	 - Beweis durch Widerspruch: \\
	   \[A\wedge \neg B \Rightarrow m^2 < n^2 \wedge n\leq m \Rightarrow m^2 < n^2 \wedge m n \leq m^2 \wedge n^2 \leq m n \Rightarrow m n \leq m^2 < n^2 \leq m n\]
	   Wiederspruch
** Existenz- und Allquantor
*** Existenzquantor
	$A(x) Aussage, die von Variable x abhängt \\
	$\exists x:~A(x)$ ist gleichbedeutend mit "Es existiert ein x, für das $A(x)$ wahr ist" (hierbei ist "existiert ein x" im Sinne von "existiert mindestens ein x" zu verstehen) \\
	Beispiel:
	\[\exists n\in\mathbb{N}:~n>5\quad\text{(w)}\]
	$\exists !x:~A(x)$ ist gleichbedeutend mit "Es existiert genau ein x, für dass $A(x)$ wahr ist" \
*** Allquantor
	$\Forall x:~A(x)$ ist gleichbedeutend mit "Für alle x ist A(x) wahr"
	Beispiel:
	\[\Forall n\in\mathbb{N}: 4n~\text{ist gerade}\]
*** Negation von Existenz- und Allquantor
	\[\neg(\exists x:~A(x)) \Leftrightarrow \Forall x:~\neg A(x)\]
	\[\neg(\Forall x:~A(x)) \Leftrightarrow \exists x:~\neg A(x)\]
*** Spezielle Beweistechniken für Existenz und Allaussagen
	- Angabe eines Beispiel, um zu zeigen, dass deine Existenzaussage wahr ist. \\
	  Beispiel:
	  \[\exists n\in\mathbb{N}:~n>5 \text{ist wahr, denn für $n = 7$ ist die Aussage $n > 5$ wahr}\]
	- Angabe eines Gegenbeispiel, um zu zeigen, dass eine Allausage falsch ist. \\
	  Beispiel:
	  \[\Forall n\in\mathbb{N}:~n\leq 5 \text{ist flasch, dann für $n=7$ ist die Aussage $n\leq 5$ falsch}\]
** Naive Mengenlehre
   Mengenbegriff nach Cantor: \\
   Eine Menge ist eine Zusammenfassung von bestimmten, wohlunterschiedenen Objekten userer Anschauung oder useres Denkens (die Elemente genannt werden) zu einem Ganzen

*** Schreibweise
   - $x\in M$, falls $x$ ein Element von $M$ ist
   - $x\not\in M$, falls $x$ kein Element von $M$ ist
   - $M=N$, falls $M$ und $N$ die gleichen Elemente besitzen, $M\subseteq N \wedge N\subseteq M$

***  Angabe von Mengen
   - Reihenfolge ist unrelevant ($\{1,2,3\}=\{1,3,2\})
   - Elemente sind wohlunterschieden $\{1,2,2\} = \{1,2\}$
   - Auflisten der Elemente $M=\{a,b,c,\ldots\}$
   - Beschreibung der Elemente durch Eigenschaften: $M=\{x\mid E(x)\}$ \\
	 (Elemente x, für die E(x) wahr)
	 - Beispiel:
	   \[\{2,4,6,8\} = \{x\mid x\in\mathbb{N}, x~\text{gerade}, 1 < x < 10\}\]
*** leere Menge
	Die leere Menge $\emptyset$ enthält keine Elemente
**** Beispiel
	 \[\{x\mid x\in\mathbb{N}, x < -5\} = \emptyset\]

*** Zahlenbereiche
	Menge der natürlichen Zahlen:
	\[\mathbb{N} := \{1,2,3,\ldots\}\]

	Menge der natürlichen Zahlen mit Null:
	\[\mathbb{N}_0 := \{0, 1,2,3,\ldots\}\]

	Menge der Ganzen Zahlen:
	\[\mathbb{Z} := \{0,1,-1,2,-2\}\]

	Menge der rationalen Zahlen:
	\[\mathbb{Q} := \{\frac{m}{n} \mid m\in\mathbb{Z}, n\in\mathbb{N}\}\]

	Menge der reellen Zahlen: $\mathbb{R}$

*** Teilmenge
	$A,B$ seien Mengen. \\
	$A$ heißt Teilmenge von $B~(A\subseteq B) \xLeftrightarrow{\text{Def.}} \Forall x\in A: x\in B$
	$A$ heißt echte Teilmenge von $B~(A\subset B) \xLeftrightarrow{\text{Def.}} A\subseteq B \wedge A\neq B$
**** Anmerkung
	 Offenbar gilt für Mengen $A,B$:
	 \[A=B \Leftrightarrow A\subseteq B \wedge B\subseteq A\]
	 $\emptyset$ ist Teilmenge jeder Menge

**** Beipspiel
	 \[\mathbb{N}\subset\mathbb{N}_0\subset\mathbb{Z}\subset\mathbb{Q}\]

*** Durschnitt
	\[A \cap B := \{x\mid x\in A \wedge x\in B\}\]
**** Beispiel
	 \[A=\{2,3,5,7\}, B=\{3,4,6,7\}, A\cap B = \{3,7\}\]

*** Vereinigung
	\[A\cup B := \{x\mid x\in A \vee x\in B\}\]
**** Beispiel
	 \[A=\{2,3,5,7\}, B=\{3,4,6,7\}, A\cup B = \{2,3,4,5,6,7\}\]

*** Differenz
	\[A\setminus B := \{x\mid x\in A \wedge x\not\in B\}\]
	Im Fall $B\subseteq A$ nennt man $A\setminus B$ auch das Komplement von $B$ in $A$ und schreibt $\mathcal{c}_A(B) = A\setminus B$
**** Beispiel
	 \[A=\{2,3,5,7\}, B=\{3,4,6,7\}, A\setminus B = \{2,5\}\]
*** Bemerkung zu Vereinigung und Durschnitt
	$A,B$ seien zwei Mengen. Dann gilt \[A\cap (B\cup C) = (A\cap B) \cup (A\cap C)\]
**** Beweis
	 \[A\cap(B\cup C) \subseteq (A\cap B) \cup (A\cap C)\]
	 \[A\cap(B\cup C) \supseteq (A\cap B) \cup (A\cap C)\]
	 "$\subseteq$" Sei $x\in A \cap (B\cup C)$. Dann ist $x\in A \wedge x\in B\cup C$
	 - 1. Fall: $x\in A \wedge x\in B$
	   \[\Rightarrow x\in A\cap B \Rightarrow x \in (A\cap B) \cup (A\cap C)\]
	 - 2. Fall $x\in A \wedge x\in C$
	   \[\Rightarrow x\in A\cap C \Rightarrow x\in (A\cap B)\cup(A\cap C)\]
	 Damit ist "$\subseteq$" gezeigt.
	 "$\supseteq$" Sei $x\in (A\cap B) \cup (A\cap C)
	 \[\Rightarrow x\in A\cap B \vee x\in A\cap C \\ \Rightarrow (x\in A \wedge x\in B) \vee (x\in A \wedge x\in C) \\ \Rightarrow x\in A \wedge (x\in B\vee x\in C) \\ \Rightarrow x\in A \wedge x\in B\cup C \\ \Rightarrow x\in A\cap (B\cup C)\]
	 Damit ist "$\supseteq$" gezeigt.
*** Bemerkung zu Äquivalenz von Mengen
	Seien $A,B$ Mengen, dann sind äquivalent:
	1) $A\cup B = B$
	2) $A\subseteq B$
**** Beweis
	 Wir zeigen 1) $\Rightarrow$ 2) und 2) $\Rightarrow$ 1.
	 \[1) \Rightarrow 2):~\text{Es gelte}~A\cup B = B,~\text{zu zeigen ist}~A\subseteq B \\ \text{Sei}~x\in A \Rightarrow x\in A \wedge x \in B \Rightarrow x\in A\cup B = B\]
	 \[2) \Rightarrow 1):~\text{Es gelte}~A\subseteq B\text{, zu zeigen ist}~A\cup B = B \]
	 "$\subseteq$": Sei $x\in A\cup B \Rightarrow x\in A \vee x\in B \xRightarrow{A\subseteq B} x\in B$
	 "$\supseteq$": $B\subseteq A\cup B$ klar
*** Kartesisches Produkt
	Seien $A,B$ Mengen
	\[A\times B := \{(a,b)\mid a\in A, b\in B\}\]
	heipt das kartesische Produkt von $A$ und $B$. Hierbei ist $(a,b) = (a',b') \xLeftrightarrow{\text{Def}} a = a' \wedge b = b'$ a = a' \wedge b = b'$

**** Beispiel
	 - \[\{1,2\}\times \{1,3,4\} = \{(1,1),(1,3),(1,4),(2,1),(2,3),(2,4)\}\]
	 - \[\mathbb{R}\times\mathbb{R}=\{(x,y)|mid x,y \in \mathbb{R}\} = \mathbb{R}^2\]
*** Potenzmenge
	$A$ sei eine Menge
	\[\mathcal{P} (A) := \{M\mid M\subseteq A\}\]
	heißt die Potenzmenge von $A$
**** Beispiel
	 \[\mathcal{P} (\{1,2,3\}) =  \{\emptyset, \{1\}, \{2\},\{3\},\{1,2\},\{1,3\},\{2,3\}\{1,2,3,4\}\}\]
*** Kardinalität
	$M$ sei eine Menge. Wir setzen
	\[\abs{M} := \begin{cases} n & \text{falls $M$ eine endliche Menge ist und $n$ Elemente enthält} \\ \infty & \text{falls $M$ nicht endlich ist} \end{cases}\]
	$\abs{M}$ heißt Kardinalität von A
**** Beispiel
	 - $\abs{\{7,11,16\}} = 3$
	 - $\abs{\mathbb{N}} = \infty$
*** Bemerkung zu natürlichen Zahlen
	Für die natürlichen Zahlen gilt das Induktionsaxiom
	Ist $M\subseteq N$ eine Teilmenge, für die gilt:
	\[1\in M \wedge \Forall n\in M : n\in M \Rightarrow n+1 \in M\]
	dann ist $M = \mathbb{N}$
*** Prinzip der vollständigen Induktion
	Für jedes $n\in \mathbb{N}$ sei eine Aussage $A(n)$ gegeben. Die Aussagen $A(N)$ gelten für alle $n\in\mathbb{N}$, wenn man folgendes zeigen kann: \\
	- (IA) $A(1)$ ist wahr
	- (IS) Für jedes $n\in\mathbb{N}$ gilt: $A(n) \Rightarrow A(n+1)$
    Der Schritt (IA) heißt Induktionsanfang, die Implikation $A(n) \Rightarrow A(n+1)$ heißt Induktionsschritt
**** Beweis
	 Setze $M := \{n\in \mathbb{N}\mid A(n)~\text{ist wahr}\}$
	 Wegen (IA) ist $1\in M$, wegen (IS) gilt: $n\in M \Rightarrow n+1 \in M$ \\
	 Nach Induktionsaxiom folgt $M = \mathbb{N}$, das heißt $A(n)$ ist wahr für alle $n\in \mathbb{N}$
**** Beispiel
	 Für $n\in\mathbb{N}$ sei $A(n)$ die Aussage: $1+\ldots + n = \frac{n(n+1)}{2}$
	 Wir zeigen: $A(n)$ ist wahr für alle $n\in \mathbb{N}$, und zwar durch vollständige Induktion
	 - (IA) $A(1)$ ist wahr, denn $1 = \frac{1(1+1)}{2}$
	 - (IS) zu zeigen: $A(n) \Rightarrow A(n+1)$ \\
	   Es gelte $A(n)$, das heißt $1+\ldots+n = \frac{n(n+1)}{2}$ ist wahr \[\Rightarrow 1 + \ldots + n + (n + 1) = \frac{n(n+1)}{2} + (n+1) =  \frac{n(n+1) + 2(n+1)}{2} = \frac{(n+1)(n+2)}{2} \square\]
** Relationen
*** Definiton
	Eine Relation auf $M$ ist eine Teilmenge $R\subseteq M\times M$
	Wir schreiben $a\sim b \xLeftrightarrow{\text{Def}} (a,b) \in R$ ("a steht in Relation zu b")

	- anschaulich: eine Relation auf $M$ stellt eine "Beziehung" zwischen den Elementen von $M$ her.
	- Für $a,b \in M$ gilt entweder $a\sim b$ oder $a\not\sim b$, denn: entweder ist $(a,b) \in R$ oder $(a,b)\not\in R$
**** Anmerkung
	 Aufgrund der obigen Notation spricht man in der Regel von Relation "$\sim" auf $M$ als von der Relation $R \subseteq M\times M$
**** Beispiel
	 $M = \{1,2,3\}. Durch $R = \{(1,1), (1,2), (3,3) \subseteq M\times M\}$ ist eine Relation auf $M$ gegeben. Es gilt dann: $1\sim 1, 1\sim 2, 3\sim 3$ (aber zum Beispiel: $1\not\sim 3, 2\not\sim 1, 2\not\sim 2$)

*** Eigenschaften von Relationen
	$M$ Menge, $\sim$ Relation auf $M$ \\
	$\sim$ heißt:
	- reflexiv $\xLeftrightarrow{\text{Def}}$ für alle $a\in M$ gilt $a\sim a$
	- symmetrisch $\xLeftrightarrow{\text{Def}}$ für alle $a,b\in M$ gilt: $a\sim b \Rightarrow b\sim a$
	- antisymmetrisch $\xLeftrightarrow{\text{Def}}$ für alle $a,b \in M$ gilt: $a\sim b \wedge b\sim a \Rightarrow a = b$
	- transitiv $\xLeftrightarrow{\text{Def}}$ für alle $a,b,c\in M$ gilt: $a\sim b \wedge b\sim v \Rightarrow a\sim c$
	- total $\xLeftrightarrow{\text{Def}}$ für alle $a,b\in M$ gilt: $a\sim b \vee b\sim a$
**** Beispiel
	 Sei $M$ die Menge der Studierenden in der LA1-Vorlesung
	 1. Für $a,b \in M$ sei $a\sim b \xLeftrightarrow{\text{Def}}$ $a$ hat den selben Vornamen wie $b$ \\
		$\sim$ reflexiv, symmetrisch, nicht antisymmetrisch, transitiv, nicht total
	 2. Für $a,b \in M$ sei $a\sim b \xLeftrightarrow{\text{Def}}$ Martrikelnummer von $a$ ist kleiner gleich als die Martrikelnummer von $b$ \\
		$\sim$ ist reflexiv, nicht symmetrisch, antisymmetrisch, transitiv, total
	 3. Für $a,b \in M$ sei $a\sim b \xLeftrightarrow{\text{Def}}$ $a$ sitzt auf dem Platz recht von $b$ \\
		$\sim$ ist nicht reflexiv, nicht symmetrisch, nicht antisymmetrisch, nicht transitiv, nicht total
*** Halbordnung / Totalordung
	$\sim$ heißt
    - Halbordnung auf $M\xLeftrightarrow{\text{Def}}~\sim$ ist reflexiv, antisymmetrisch und transitiv
	- Totalordung auf $M\xLeftrightarrow{\text{Def}}~\sim$ ist eine Halbordnung und $\sim$ ist total
    In diesen Fällen sagt man auch: Das Tupel $(M,\sim)$ ist eine halbgeordnete, beziehungsweise totalgeordnete Menge.
**** Beispiel
	 1. $\leq$ auf $\mathbb{N}$ ist eine Totalordung
	 2. Sei $M = \mathcal{P}(\{1,2,3\})$. $\subseteq$ ist auf $M$ eine Halbordung, aber keine Totalordung (es ist zum Beispiel weder $\{1\} \subseteq \{3\}$ noch $\{3\}\subseteq \{\}$)
**** Anmerkung
	 Wegen der Analogie zur $\leq$ auf $\mathbb{N}$ bezeichnen wir Halbordnungen in der Regel mit $\leq$
*** Größtes / kleistes Element
	$(M, \leq)$ halbgeordnete Menge, $a\in M$ \\
	$a$ heißt ein
	- größtes Element von $M\xLeftrightarrow{\text{Def}}$ Für alle $x\in M$ gilt $x\leq a$
	- kleinstes Element von $M\xLeftrightarrow{\text{Def}}$ Für alle $x\in M$ gilt $a\leq x$
**** Bemerkung
	 $(M,\leq)$ halbgeordnete Menge \\
	 Dann gilt: Existiert in $M$ ein größtes (beziehungsweise kleinstes) Element, so ist dieses eindeutig bestimmt
***** Beweis
	  Es seien $a,b\in M$ größte Elemente von $M$ \\
	  $\Rightarrow x\leq a$ für alle $x\in M$, also auch $b\leq a$ \\
	  Außerdem: $x \leq b für alle $x\in M$, also auch $a\leq b$ \\
	  $\xRightarrow{\text{Antisymmetrie}} a = b$ \\
	  Analog für kleinstes Element
***** Anmerkung
	  Dies sagt nichts darüber aus, ob ein größtes (beziehungsweise kleinstes) Element in $M$ überhaupt existiert.
**** Beispiel
	 1. In $(\mathbb{N},\leq)$ ist 1 das kleinste Element, ein größtes Element gibt es nicht
	 2. $(\{\{1\},\{2\},\{3\},\{1,2\},\{1,3\},\{2,3\}\}, \subseteq)$ ist eine halbgeordnete Menge ohne kleinstes beziehungsweise größtes Element
*** maximales / minimales Element
	$(M,\leq)$ halbgeordnete Menge, $a\in M$ \\
	$a$ heißt ein
    - maximales Element von $M \xLeftrightarrow{\text{Def}}$ für alle $x\in M$ gilt: $a\leq x \Rightarrow a = x$
    - minmales Element von $M \xLeftrightarrow{\text{Def}}$ für alle $x\in M$ gilt: $x\leq a \Rightarrow a = x$
**** Beispiel
     In $(\{\{1\},\{2\},\{3\},\{1,2\},\{1,3\},\{2,3\}\}, \subseteq)$ sind $\{1,2\},\{1,3\},\{2,3\}$ maximale Elemente und $\{1\},\{2\},\{3\}$ sind minimale Elemente.
**** Bemerkung
	 $(M,\leq)$ halbgeordnete Menge, $a\in M$ \\
	 Dann gilt: Ist $a$ ein größtes (beziehungsweise kleinstes) Element von $M$, dann ist $a$ ein maximales (beziehungsweise minimales) Element von $M$.
***** Beweis
	  Sei $a$ ein größtes Element von $M$. \\
	  zu zeigen ist: Für alle $x\in M$ gilt $a\leq x \Rightarrow a = x$
	  Sei $x\in M$ mit $a\leq x$. Da $a$ größtes Element von $M$ ist, gilt auch $x\leq a$ \\
	  $\xLeftrightarrow{\text{Antisymmetrie}} a = x$ \\
	  Analog für kleinstes Element.
*** Äquivalenzrelation
	$M$ Menge, $\sim$ auf $M$ \\
	$\sim$ heißt Äquivalenzrelation $\xLeftrightarrow{\text{Def}}~\sim$ ist reflexiv, symmetrisch und transitiv.
	In dem Fll sagen wir für $a\sim b$ auch $a$ ist äquivalent zu $b$. Für $a\in M$ heißt $[a]:=\{b\in M \mid b\sim a\}$ heißt die Äquivalentklasse von $a$.
	Elemente aus $[a]$ nennt man Vertreter oder Repräsentanten von $a$
**** Beispiel
	 $M$ Menge aller Bürgerinnen und Bürger Deutschlands. \\
	 Wir definieren für $a,b\in M$ $a\sim b \xLeftrightarrow{\text{Def}} a$ und $b$ sind im selben Jahr geboren. \\
	 $\sim$ ist ein Äquivalenzrelation. \\
	 Jerôme Boateng wrude 1988 geboren. $[\text{Jerôme Boateng}] = \{b\in M\mid b~\text{ist im selben Jarh geboren wei Jerôme Boateng}\} = \{b\in M\mid b~\text{wurde 1988 geboren}\}$
	 Weitere Vertreter von $[\text{Jerôme Boateng}]$ sind zum Beispiel Mesut Özil, Mats Hummels.
	 Es ist $[\text{Jerôme Boateng}] = [\text{Mesut Özil}] = [\text{Mats Hummels}]$.
	 Man sieht in diesem Beispiel: Die Menge $M$ zerfällt komplett in verschiedene Äquivalentzklassen:
	 - Jeder Bürger / jede Bürgerinn Detuschalnds ist in genau einer Äquivalenzklasse enthalten
	 - Jede zwei Äquivalentklasse sind endweder gleich oder disjunkt (haben leeren Durchschnitt)
**** Bemerkung
	 $M$ Menge, $\sim$ Äquivalenzrelation auf $M$ \\
	 Dann gilt:
	 1. Jedes Element von $M$ liegt in genau einer Äquivalenzklasse
	 2. Je zwei Äquivalenzklassen sind entweder gleich oder disjunkt
     Man sagt auch: Die Äquivalenzklassen bezüglich "$\sim$" bilden eine *Partition* von $M$.
***** Beweis
	  1. Sei $a\in M$ \\
		 zu zeigen: Es gibt genau eine Äquivalenzklassen, in der $a$ liegt
		 1. Es gibt eine Äquivalenzklasse, in der $a$ liegt, denn $a\in [a], denn $a\sim a$
		 2. Ist $a\in[b] und a\in[c], dann ist [b]=[c] (d.h. $a$ liegt in höchstens einer Äquivalenzklasse) \\
			denn: Seien $b,c\in M$ mit $a\in[b]$ und $a\in[c]$
			$\Rightarrow a\sim b$ und $a\sim c \xRightarrow{\text{Symmetrie}} b\sim a und a\sim c \xRightarrow{\text{Transitivität}} b\sim c$
			Behautptung $[b] =[c]$
			denn: "$\subseteq$" Sei $x\in [b] \Rightarrow x\sim b \xRightarrow{Transitivität}^{b\sim c} x\sim c \Rightarrow x\in [c]$
			denn: "$\supseteq$" Sei $x\in [c] \Rightarrow x\sim c \xRightarrow{Transitivität}^{c\sim b} x\sim b \Rightarrow x\in [b]$
	  2. Sind $b,c\in M$ mit $[b] \cap [c] \neq \emptyset$, dann existiert ein $a\in [b]\cap [c], und es folgt wie in 2.: \\
		 $[b] = [c]$
		 Für $b,c\in M$ gilt also entweder $[b]\cap[c] =\emptyset$ oder $[b] = [c]\hfill\square$
**** Faktormenge
	 $M$ Menge, $\sim$ Äquivalenzrelation auf $M$
	 $M/\sim := \{[a]|a\in M\}$ (Menge der Äquivalenzklassen) heißt die Faktormenge (Quotientenmenge) von $M$ nach $\sim$
***** Beispiel
	  \[M= \{1,2,3,-1,-2,-3\}\]
	  Für $a,b,c \in M$ setzen wir $a\sim b \xLeftrightarrow{\text{Def.}} \abs{x} = \abs{b}$
	  Das ist eine Äquivalenzrelation auf $M$
	  Es ist $[1] = \{1,-1\},[2]=\{2,-2\},[3]=\{3,-3\}
	  Somit: $M/sim := \{[1],[2],[3]\} = \{\{1,-1\},\{2,-2\},\{3,-3\}\}
***** Anmerkung
	  Der Übergang zur Äquivalenzklassen soll (für eine jeweils gegebene Relation) irrelevante Informationen abstreifen.
** Abbildungen
    *naive Definition*: \\
	Eine Abbildung $f$ von $M$ nach $N$ ist eine Vorschrift, die jedem $n\in M$ genau ein Element aus $N$ zuordnet, dieses wird mit $f(n)$ bezeichnet.
	*Notation*: \\
	\[f:M\to N,m\mapsto f(m)\]

	Zwei Abbildungen $f,g:M\to N$ sind gleich, wenn gilt $\Forall n\in M:f(n) = g(n)$
	$M$ heißt die Definitionsmenge von $f$, $N$ heißt die Zielmenge von $f$
*** Definition
	Eine Abbildung $f$ von $M$ nach $N$ ist ein Tupel $(M,N,G_f)$, wobei $G_f$ eine Teilmenge von $M\times N$ mit der Eigenschaft ist, dass für jedes Element $m\in M$ genau ein Element $n\in N$ mit $(m,n) \in G_f$ existiert.
	(für dieses Element $n$ schreiben wir auch $f(m)$). $G_f$ heißt der Graph von $f$.
*** Beispiel
	1. $f:\mathbb{R}\to\mathbb{R}, x\mapsto x^2$
	2. $f:\mathbb{R}\to\mathbb{R}^2,x\mapsto (x,x+1)$
	3. $M$ Menge, $id_M: M\to M,m\mapsto m$ heißt Identität (identische Abbildung) auf $M$
	4. $I$,$M$ Mengen: Eine über $I$ indizierte Familie von Elementen von $M$ ist eine Abbildung: \\
	   $m:I\to M,i\mapsto m(i) =: m_i$. Wir schreiben für die Familie auch kurz $(m_i)_{i\in I}$. $I$ heißt Indexmenge der Familie.
	5. Spezialfall von 4.: $I = \mathbb{N},M = \mathbb{R}:~((m_i)_{i\in\mathbb{N}})$ nennt man auch Folge reeler Zahlen.
*** Anmerkung über den Begriff der Familie
	Über den Begriff der Familie lassen sich diverse Konstruktionen aus der naiven Mengenlehre verallgemeinern.
	Ist $(M_i)_{i\in I}$ eine Familie von Mengen, dann ist:
	\[\cup_{i\in I} M_i:=\{x\mid\exists i\in I: x\in M_i\}\]
	\[\cap_{i\in I}M_i := \{x\mid\Forall i\in I: x\in M_i\}\]
	\[\prod_{i\in I}M_i := \{(x_i)_{i\in I}\mid \Forall i\in I: x_i \in M\}\]
*** Bild
	$m,N$ Mengen, $f:M\to n$ Abbildung. \\
	Sind $m\in M,n\in N$ mit $n = f(m)$ dann nennen wir $n$ ein *Bild* von $m$ unter $f$ und wir nennen $m$ ein *Urbild* von $n$ unter $f$.
**** Anmerkung
	 In obiger Situation ist das Bild von $m$ unter $f$ eindeutig bestimmt (nach der Definition einer Abbildung)
	 Urbilder sind im allgemeinen nicht eindeutig bestimmt, und im Allgemeinen besitzt nicht jedes Element aus $N$ ein Urbild.
**** Beispiel
	 $f:\mathbb{R}\to\mathbb{R},x\mapsto x^2$, dann ist $4=f(2) = f(-2)$, das heißt $2$ und $-2$ sind Urbilder von $4$, das Element $-5$ hat kein Urbild unter $f$, denn es existiert kein $x\in\mathbb{R}$ mit $x^2 = -5$
**** Definition
	 $M, N$ Mengen, $f:M\to N$ Abbildung, $A\subseteq M, B\subseteq N$ \\
	 $f(A) := \{f(a)\mid a\in A\} \subseteq N$ heißt das Bild von $A$ unter $f$. \\
	 $f^-1(B) := \{m\in M\mid f(m) \in B\} \subseteq M$ heißt das Urbild von $B$ unter $f$
***** Beispiel
	  \[f:\mathbb{R}\to\mathbb{R},x\mapsto x^2\]
	  \[f(\{1,2,3\}) = \{1,4,9\}\]
	  \[f^-1(\{4,-5\}) = \{2,-2\}\]
	  \[f^-1(\{4\}) = \{2,-2\}\]
	  \[f^-1(\{-5\}) = \emptyset\]
	  \[f(\mathbb{R}) = {x^2\mid x\in \mathbb{R}} = \{x\in\mathbb{R}\mid x\geq 0\} =:\mathbb{R}_{\geq 0}\]
*** Restriktion
	$M,N$ Mengen, $f:M\to N$ Abbildung, $A\subseteq M$
	\[f\mid_A:A\to N, m\mapsto f(m)\]
	heißt die Restriktion von $f$ auf $A$.
	Ist $B\subseteq N$ mit $f(A) \subseteq B$, dann setzen wir
	\[f\mid_A^B: A\to B,m\mapsto f(m)\]
	Ist $f(M) \subseteq B$ dann setzen wir:
	\[f\mid^B := f\mid_M^B,M\to B, m\mapsto f(m)\]
*** Komposition
	$L,M,N$ Mengen, $f:L\to M,g:M\to N$ Abbildung \\
	\[g\circ f: L\to N, x\mapsto(g\circ f)(x):=g(f(x))\]
	heißt die Komposition (Hintereinanderausführung) von $f$ und $g$
**** Beispiel
	 \[f:\mathbb{R}\to\mathbb{R},x\mapsto x^2, g:\mathbb{R}\to\mathbb{R}:x\mapsto x + 1\]
	 \[\Rightarrow g\circ f:\mathbb{R}\to\mathbb{R},x\mapsto g(f(x)) = g(x^2) = x^2 + 1\]
**** Assoziativität
	 $L,M,N,P$ Mengen, $f:L\to M, g:M\to N,h:n\to p$ \\
	 Dann gilt
	 \[h\circ (g\circ f) = (h\circ g)\circ f\]
	 das heißt die Verknüpfung von Abbildungen ist assoziativ.
***** Beweis
	  Für $x\in L ist$ \\
	  \[(h\circ (g\circ f)) = h((g\circ f)(x)) = h(g(f(x))) = (h\circ g)(f(x)) = ((h\circ g)\circ f)(x)\hfill\square\]
*** Eigenschaften von Abbildungen
	$M,N$ Mengen, $f:M\to N$ Abbildung
**** Injektivität
	 $f$ heißt injektiv: \[\xLeftrightarrow{\text{Def}} \Forall m_1,m_2\in M: f(m_1) = f(m_2) \Rightarrow m_1 = m_2 \Leftrightarrow \Forall m_1,m_2\in M: m_1\neq m_2 \Rightarrow f(m_1)\neq f(m_2)\]
**** Surjektivität
	 $f$ heißt sujektiv:
	 \[\xLeftrightarrow{\text{Def}} \Forall n\in M :\exists m\in M: f(m) = n \Leftrightarrow f(M) = N\]
**** Bijektivität
	 $f$ heißt bijektiv: $\xLeftrightarrow{\text{Def}}$ $f$ ist injektiv und surjektiv
**** Beispiel
	 1. $f:\mathbb{R}\to\mathbb{R},x\mapsto x^2$ ist:
		- nicht injektiv, denn $f(2) = f(-2)$, aber $2\neq -2$
		- nicht surjektiv, denn es existier kein $m\in\mathbb{R}$ mit $f(m) = -1$
		- nicht bijektiv
	 2. $f:\mathbb{R}_{\geq 0} \to \mathbb{R}, x\mapsto x^2$ ist:
		- injektiv, denn für $m_1,m_2 \in\mathbb{R}_{\geq 0}$ gilt: $f(m_1) = f(m_2) \Rightarrow m_1^2 = m_2^2 \xRightarrow{m_1,m_2 > 0} m_1 = m_2$
		- nicht surjektiv, denn es existier kein $m\in\mathbb{R}_{\geq 0}$ mit $f(m) = -1$
		- nicht bijektiv
	 3. $f:\mathbb{R}_{\geq 0} \to \mathbb{R}_{\geq 0}, x\mapsto x^2$ ist:
		- injektiv, denn für $m_1,m_2 \in\mathbb{R}_{\geq 0}$ gilt: $f(m_1) = f(m_2) \Rightarrow m_1^2 = m_2^2 \xRightarrow{m_1,m_2 > 0} m_1 = m_2$
		- surjektiv, denn für $m\in\mathbb{R}_{\geq 0}$ ist $f(\sqrt{m}) = (\sqrt{m})^2 = m$
		- bijektiv
**** Bemerkung 4.12
	 $M,N$ Mengen, $f:M\to N, g:n\to M$ mit $g\circ f = id_M$
	 Dann ist $f$ injektiv und $g$ surjektiv.
***** Beweis
	  1. $f$ ist injektiv, denn: \\
		 Seien $m_1, m_2 \in M$ mit $f(m_1) = f(m_2) \Rightarrow g(f(m_1)) = g(f(m_2)) \Rightarrow (g\circ f)(m_1) = (g\circ f)(m_2) \Rightarrow id_m(m_1) = id_M(m_2)\Rightarrow m_1 = m_2$
	  2. $g$ ist surjektiv, denn: \\
		 Sei $m\in M$ Dann ist $m=id_M(m) = (g\circ f)(m) = g(f(m))$
**** Bemerkung
	 Sei $f:M\to N$, $N,M$ Mengen
	 Dann sind äquivalent:
	 1. $f$ ist bijektiv
	 2. Zu jedem $n\in N$ gibt es genau ein $m\in M$ mit $f(m) = n$
	 3. Es gibt genau eine Abbildung $g:N\to M$ mit $g\circ f = id_M$ und $f\circ g = id_N$
	 In diesem Fall bezeichnen wir die Abbildung $g:N\to M$ aus 3. mit $f^{-1}$ und nennen $f^{-1}$ die Umkehrabbildung von $f$. Sie ist gegeben durch
	 \[f^{-1} : N\to M, n\mapsto~\text{Das eindeutig bestimmte Element $m\in M$ mit $f(m) = n$}\]
***** Beweis
	  Statt 1. \Leftrightarrow 2. und 2. \Leftrightarrow 3. zeigen 1. \Rightarrow 2. \Rightarrow 3. \Rightarrow 1.
	  - 1. \Rightarrow 2. Sei $f$ bijektiv \\
		zz: Ist $n\in N$, dann existiert genau ein $m\in M$ mit $f(m) = n$ \\
		- Existenz folg aus Surjektivität von $f$
		- Eindeutigkeit: Seien $m_1,m_2 \in M  mit \(f(m_1) = n, f(m_2) = n \Rightarrow f(m_1) = f(m_2) \xRightarrow{f injektiv} m_1 = m_2\)
	  - 2. \Rightarrow 3. Zu jedem $n\in M$ existiere genau ein $m\in M$ mit $f(m) = n$ \\
		zz: Ex existert genau eine Abbildung $g:N\to M$ mit $f\circ f = id_M$ und $f\circ g = id_N$
		- Existenz: Wir definieren \(g:N\to M, n\mapsto~\text{das nach 2. eindeutig bestimmte Element $m\in M$ mit $f(m) = n$}\) \\
		  Dann gilt für $m\in M$: \[(g\circ f)(m) = f(f(m)) = m,~text{das heißt}~ g\circ f = id_M\]
		  und für $n\in N$ ist $(f\circ g)(n) = f(g(n)) = n$ also $f\circ g = id_N$
		- Eindeutigkeit: Es seinen $g_1,g_2:N\to M$ mit $g_i \circ f = id_M, f\circ g_i = id_N$ für $i = 1,2$ \\
		  \[\Rightarrow g_1 = g_1 \circ id_N = g_1 \circ (f\circ g_2) = (g_1 \circ f) \circ g_2 = id_M \circ g_2 = g_2\]
	  - 3. \Rightarrow 1. Wegen 3. existier $g:N\to M$ mit $g\circ f = id_M,f\circ g = id_N$ \\
		\[\xRightarrow{[[Bemerkung 4.12]]} f~\text{injektiv}~,f~\text{surjektiv}~\Rightarrow f~\text{bijektiv}\Rightarrow~\text{1.}\]
***** Anmerkung
	  - Bitte stets aufpassen, ob mit $f^{-1}$ die Unmkerhabbildung (falls existent) oder das Bilden der Urbildmenge gemeint ist.
	  - Im Beweis von 3. \Rightarrow 1. haben wir die Eindeutigkeit von $g$ garnicht verwendet, das heißt wir haben sogar gezeigt: \\
		$f$ bijektiv \Leftrightarrow 3.' Es existiert eine Abbildung $g:N\to M$ mit $f\circ g = id_N$ und $f\circ f = id_M$ Soch eine Abbildung $g$ ist in diesem Fall automatisch bestimmt.
***** Beispiel
	  Im Beispiel vorher haben wir gesehen $f:\mathbb{R}_{\geq 0} \to \mathbb{R}_{\geq 0}, x\mapsto x^2$ ist bijektiv.
	  Die Umkehrabbildung ist gegeben durch $f^{-1}:\mathbb{R}_{\geq 0} \to \mathbb{R}_{\geq 0}, x\mapsto \sqrt{x}$
**** Bemerkung
	 $M,N$ Mengen, $f:M\to N$ Dann gilt:
	 1. $f$ injektiv \Leftrightarrow Es existiert $g:N\to M$ mit $g\circ f = id_M$ \\
		*Beweis:*
		- "\Leftarrow" folgt aus [[Bemerkung 4.12]]
		- "\Rightarrow" Sei $f$ injektiv. Sein $x$ ein beliebiges Element aus $M$
		  Wir definieren \[g:N\to M,n\mapsto \begin{cases} x & n\not\in f(M) \\ \text{das eindeutig bestimmte Element $m\in M$ mit $f(m) = n$} & n\in f(M) \end{cases}\]
		  Für alle $m\in M$ ist dann $(g\circ f)(m) = g(f(m)) = m$ das geißt $g\circ f = id_M$
	 2. $f$ surjektiv \Leftrightarrow Es existiert $g:N\to M$ mit $f\circ g = id_N$ \\
		*Beweis:*
		- "\Leftarrow" folgt aus [[Bemerkung 4.12]]
		- "\Rightarrow" Sei $f$ surjektiv. Für jedes Element $n\in N$ wählen wir ein Element $\tilde n\in f^{-1}(\{n\}) \neq \emptyset$ und sehen
		  $g:N\to M,n\mapsto \tilde n$. Dann ist $(f\circ g)(n) = f(g(n)) = n$ für alle $n\in N$ und das heißt $f\circ g = id_N \hfill\square$
***** Anmerkung
	  Das wir stets einen Auswahlprozess wie im Beweis von 2. "\Rightarrow" vornehmen können ist ein Axiom der Mengenlehre (erkennen wir als gültig an, ist jedoch nicht beweisbar), das *Auswahlaxiom*: \\
	  Ist $I$ eine Indexmenge und $(A_i)_{i\in I}$ eine Familie von nichtleeren Mengen, dann gibt es eine Abbildung $\gamma:I\to \bigcup_{i\in I} A_i$ mit $\gamma (i) \in A_i$ für alle $i\in I$ (im obigen Beweis ist $I = N,A_n = f^{-1}(\{n\})$ für $n\in N$)
**** Bemerkung 4.16
	 $L,M,N$ Mengen, $f:L\to M, g:M\to N$ \\
	 Dann gilt: $g,f$ beide injektiv (beziehungsweise surjektiv oder bijektiv) \Rightarrow $g\circ f$ injektiv (beziehungsweise sujektiv oder bijektiv)
**** Definition 4.17
**** Bemerkung 4.19
	 $M,N$ endliche Mengen mit $\abs{M} = \abs{N},f:M\to N$ Dann sind äquivalent:
	 1. $f$ ist injektiv
	 2. $f$ ist surjektiv
	 3. $f$ ist bijektiv
***** Beweis
	  - 1. \Rightarrow 2. Sei $f$ injektiv \Rightarrow $\abs{f(M)} = \abs{M} = \abs{N}$ wegen $f(M) \subseteq N$ folgt $f(M) = N$ \Rightarrow $f$ surjektiv
	  - 2. \Rightarrow 3. Sei $f$ sujektiv, das heißt $f(M) = N$ \\
		Annahme: $f$ ist nicht bijektiv \Rightarrow $f$ nicht injektiv \Rightarrow $\exists m_1,m_2\in M: m_1\neq m_2 \wedge f(M_1) = f(m_2) \Rightarrow \abs{f(M)} < \abs{M} = \abs{N}$ Wiederspruch zu $f(M) = N$
	  - 3. \Rightarrow 1. trivial
* Gruppen, Ringe, Körper
** Gruppe
*** Verknüpfung
   $M$ Menge, Eine Verknüpfung (inverse Verknüpfung) auf $M$ ist ein Abbildung \[*:M\times M \to M\]
   Anstelle von $*(a,b)$ schreiben wir $a * b$
**** Beispiel
	 - $+: \mathbb{R} \times \mathbb{R} \to \mathbb{R},(a,b) \mapsto a + b$
	 - $\cdot: \mathbb{R} \times \mathbb{R} \to \mathbb{R},(a,b) \mapsto a\cdot b$
	 sind Verknüpfungen
*** Monoid
	Ein Monoid ist ein Tupel $(M,*)$, bestehend aus einer Menge $M$ und einer Verküpfung \\
	$*:M\times M \to M$, welche folgende Bedingungen genügt:
	- (M1) Die Verküpfung ist assoziativ, das heißt \[\Forall a,b,c\in M:(a*b)*c = a*(b*c) \]
	- (M2) Ex existiert ein neutrales Element $e$ in $M$, das heißt \[\exists e\in M:\Forall a\in M e*a = a = a*e\]
**** Beispiel
	 - $(\mathbb{N}_0,+), (\mathbb{Z},+)$ sind Monoide (neutrales Element: $0$)
	 - $(\mathbb{N},+)$ ist kein Monoid (ex existiert kein neutrales Element)
	 - $(\mathbb{N},\cdot),(\mathbb{Z},\cdot)$ sind Monoide (neutrales Element: $1$)
**** Bemerkung
	 $(M,*)$ Monoid. Dann gibt es in $M$ genau ein neutrales Element.
***** Beweis
	  - Existenz: Es existert ein neutrales Element: folgt aus Definition eines Monoids
	  - Eindeutigkeit: Seien $e,\tilde e \in M$ neutrale Element \[\Rightarrow e = e * \tilde e = \tilde e\]
*** Inverses
	$(M,*)$ Monoid mit neutralem Element $e$, $a\in M$
	Ein Element $b\in M$ heit Inverses zu $a \xLeftrightarrow{\text{Def}} a * b = e = b * a$
**** Beispiel
	 - In $(\mathbb{Z},+)$ ist $-2$ ein Inverses zu $2$ denn $2 + (-2) = 0 = (-2) + 2$
	 - In $(\mathbb{N}_0,+)$ existiert kein Inverses zu $2$, denn es existiert kein $n\in \mathbb{N}_0$ mit $n + n = 0 = n + 2$
	 - <<invex>> In $(\mathbb{Z},\cdot)$ existiert kein Inverses zu $2$, denn es existiert kein $n\in\mathbb{Z}$ mit $2\cdot n = 1 = n \cdot 2$
**** Bemerkung
	 <<beminv>>
	 $(M,*)$ Monid, $a\in M$ Dann gilt: besitzt $a$ ein Inverses, dann ist dieses eindeutig bestimmt.
***** Beweis
	  Seinen $b,\tilde b$ Inversen zu $a$, sein $e\in M$ das neutrale Element
	  \[\Rightarrow b = e * b = (\tilde b * a) * b = \tilde b * (a * b) = \tilde b\]
*** Gruppe
	Eine Gruppe ist ein Tupel $(G,*)$, bestehen aus einer Menge $G$ und einer Verknüpfung $*:G\times G \to G$, sodass gilt:
	- (G1) $(G,*)$ ist ein Monoid
	- (G2) Jedes Element aus $G$ besitzt ein Inverses
	In diesem Fall schreiben wir $a'$ für das nach [[beminv]] eindeutig bestimmte Inverse eines Elements $a\in G$
**** Beispiel
	 - $(\mathbb{Z},+)$ ist eine Gruppe, denn $(\mathbb{Z},+)$ ist ein Monoid und für $a\in\mathbb{Z}$ ist $-a$ das inverse Element: $a + (-a) = 0 = (-a) + a$
	 - $(\mathbb{Z},\cdot)$ ist keine Gruppe, denn das Element $2\in\mathbb{Z}$ hat kein Inverses (vergleiche [[invex]]).
	 - $(\mathbb{Q}\setminus \{0\},\cdot)$ ist eine Gruppe denn es ist ein Monoid mit neutralem Element $1$ und für jedes Element $a\in\mathbb{Q}\setminus\{0\}$ existiert ein $b\in \mathbb{Q}\setminus \{0\}$ mit $a\cdot b = 1 = b\cdot a$, nämlich $b = \frac{1}{a}$
**** Bemerkung
	 $(G,*)$ Gruppe mit neutralem Element $e,a,b,c \in G$. Dann gilt
	 1. (Kürzungsregel) \[a*b = a*c \Rightarrow b = c\] \[a*c = b * c \Rightarrow a = b\]
	 2. $a*b = e \Rightarrow b = a'$
	 3. $(a')' = a$
	 4. (Regel von Hemd und Jacke) $(a*b)' = b' * a'$
***** Beweis
	  1. Sei $a * b = a * c \Rightarrow a'*(a*b) = a'*(a*c) \Rightarrow (a'*a)*b=(a'*a)*c \Rightarrow e*b = e*c \Rightarrow b = c$
	  2. aus 1. $a*b = c = a*a' \Rightarrow b = a'$
	  3. Es ist $a*a' = e = a' * a$, das heißt $a$ ist Inverses zu $a' \Rightarrow (a')' = a$
	  4. Es ist $(a*b)*(b'*a') = a*(b*b')*a' = a*a' = e \Rightarrow b' * a' \xRightarrow{\text{2.}} (a *b)'$
*** Abelsche Gruppe
	$(M,*)$ Monoid / Gruppe heißt kommutativ (abelsch)
	\[\xLeftrightarrow{\text{Def}} \Forall a,b\in M: a*b = b*a\]
**** Beispiel
	 Alle bisher betrachteten Beispiele von Monoiden beziehungsweise Gruppen sind abelsch
**** Bemerkung 5.14
	 $M$ Menge, Wir setzten $S(M):= \{f:M\to M | f~\text{bijektiv}\}$
	 Dann ist $(S(M),\cdot)$ eine Gruppen, die *symmetrische* Gruppe auf $M$
***** Beweis
	  1. "$\cdot$" ist wohl definiert, das heißt für $f,g\in S(M)$ ist $f\circ g \in S(M)$ folgt aus [[Bemerkung 4.19]]
	  2. "$\cdot$" ist assoziativ $f\circ(g\circ h) = (f\circ g) \circ h \Forall f,g\in S(M)$ nach [[4.9]]
	  3. $id_M$ ist neutral: $id_M \in S(M)$ und $id_M\circ f = f = f\circ id_M \Forall f\in S(M)$
	  4. Existenz von Inversen: $f\in S(M) \Rightarrow f$ bijektiv \Rightarrow Es existiert Unmekrabbildung $f^{-1}\in S(M)$ zu $f$
		 für diese gilt: $f\circ f^{-1} = id_M = f^{-1}\circ f$ das heißt $f^{-1}$ ist immer zu $f$ bezüglich "$\cdot$"
*** Permutationen
	$n\in\mathbb{N}$
	\[S_n := S(\{1,\ldots,n\}) = \{\pi \{1,\ldots,n\} \to \{1,\ldots,n\} \mid \pi~\text{ist bijektiv}\}\]
	$(S_n,\circ)$ heißt die symmetrische Gruppe auf $n$ Ziffern, Elemente aus $S_n$ heißen Permutationen.
	Wir schreiben Permutationen $\pi \in S_n$ in der Form:
	\begin{equation}
	\pi =
	\begin{pmatrix}
	1 & 2 & \ldots & n \\
	\pi(1) & \pi(2) & \ldots & \pi(n)
	\end{pmatrix}
	\end{equation}
**** Beispiel
	 In $S_3$ ist
	\begin{equation}
	\begin{pmatrix}
	1 & 2 & 3 \\
	1 & 3 & 2 \\
	\end{pmatrix}
	\circ
	\begin{pmatrix}
	1 & 2 & 3 \\
	3 & 2 & 1 \\
	\end{pmatrix}
	=
	\begin{pmatrix}
	1 & 2 & 3 \\
	2 & 3 & 1 \\
	\end{pmatrix}
	\end{equation}

	\begin{equation}
	\begin{pmatrix}
	1 & 2 & 3 \\
	3 & 2 & 1 \\
	\end{pmatrix}
	\circ
	\begin{pmatrix}
	1 & 2 & 3 \\
	1 & 3 & 2 \\
	\end{pmatrix}
	=
	\begin{pmatrix}
	1 & 2 & 3 \\
	3 & 1 & 2 \\
	\end{pmatrix}
	\end{equation}
	das heißt $(S_3,\circ)$ ist nicht abelsch.
*** Restklassen
**** Motivation
	 Im täglischen Leben verwendet man zur Bestimmung von Uhrzeiten das Rechnen "modulo $24$", zum Beispiel 22Uhr + 7h = 5Uhr. Wir wollen dies mathematisch präzisieren und verallgemeinern
**** Bemerkung 5.17
	 $n\in\mathbb{N}$. Dann ist durch \[a \sim b \xLeftrightarrow{\text{Def}} \Exists q\in\mathbb{Z}:a - b = q n\]
	 eine Äquivalenzrelatioin auf $\mathbb{Z}$ gegeben.
	 Anstelle von $a\sim b$ schreiben wir auch $a\equiv b(\mod n)$ ("$n$ ist kongruent $b$ modulo $n$")
	 Die Äquivalenzklasse von $a\in \mathbb{Z}$ ist durch
	 \[\bar a := \{b\in\mathbb{Z}\mid b\equiv a(\mod n)\} = a + n\mathbb{Z} := \{a + n q \mid q\in \mathbb{Z}\}\]
	 gegeben und heißt die Restklasse von $a$ modulo $n$.
	 Die Menge aller Restklassen modulo $n$ wird $\frac{\mathbb{Z}}{n\mathbb{Z}}$ bezeichnet ("$\mathbb{Z}$ modulo $n\mathbb{Z}$")
	 Es ist: \[\frac{\mathbb{Z}}{n\mathbb{Z}} = \{\bar 0, \bar 1, \ldots, \overline{n - 1}\}\]
	 und die Restklassen $\bar 0, \ldots, \overline{n - 1}$ sind paarweise verschieden
***** Beweis
	  1. "$\equiv$" ist eine Äquivalenzrelation, denn:
		 - "$\equiv$" ist reflexiv: Fpr $a\in\mathbb{Z}$ ist $a\equiv a(\mod n)$ denn $a - a = 0 = 0 n$
		 - "$\equiv$" ist symmetrisch: Seien $a,b\in\mathbb{Z}$ mit $a\equiv b(\mod n), b\equiv c(\mod n)$
		   - \Rightarrow $b - a = (-q) n \Rightarrow b = a(\mod n)$
		 - "$\equiv$" ist transitiv: Seien $a,b,c\in\mathbb{Z}$ mit $a\equiv b(\mod n), b\equiv c(\mod n)$
		   - \Rightarrow $\exists q_1,q_2 \in\mathbb{Z}$ mit $a - b = q_1 n, b - c = q_2 n$
		   - \Rightarrow $a - c = (a - b) + (b - c) = q_1 n + q_2 n = (q_1 + 1_2) n \Rightarrow a \equiv c(\mod n)$
	  2. Die Äquivalenzklasse von $n\in\mathbb{Z}$ ist gegeben durch
		 \[\{b\in\mathbb{Z} \mid b = a(\mod n)\}\]
		 \[= \{b\in\mathbb{Z} \mid \exists q\in\mathbb{Z}:b - a = qn\}\]
		 \[= \{b\in\mathbb{Z} \mid \exists q\in\mathbb{Z}:b = a + q n\}\]
		 \[= a + n\mathbb{Z} \]
	  3. \[\frac{\mathbb{Z}}{n\mathbb{Z}} = \{\bar 0, \bar 1, \ldots, \overline{n - 1}\}\]
		 denn:
		 - Ist $a\in\mathbb{Z}$ beliebig, dann liefert Division mit Rest durch $n$: \\
		   Es gibt $q,r\in\mathbb{Z}$ mit $a = q n + r,0\leq r < n$
		   \[\Rightarrow a - r = q n \Rightarrow q \equiv r(\mod n) \Rightarrow \bar a = \bar r\]
		   Das heißt: Jede Restklasse ist von der Form $\bar r$ mit $r\in \{0,\ldots,n - 1\}$ \\
		 - Die Restklassen $\bar 0, \bar 1, \ldots, \overline{n - 1}$ sind paarweise verschieden denn: \\
		   Seien $a,b\in\{0,\ldots,n - 1\}$ mit $\bar a = \bar b \Rightarrow a \equiv b(\mod n) \Rightarrow \exists q\in \mathbb{Z}: a - b = q n \Rightarrow \abs{a - b} = \abs{q} n.
		   - Wäre $q\neq 0$, dasnn $\abs{q} \geq 1$ wegen $q\in\mathbb{Z} \Rightarrow \abs{a - b} \geq n$ *Wiederspruch* zu $a,b\in\{0,\ldots,n - 1\}$ \\
			 Also: $q = 0$ das heißt $a = b$
**** Beispiel
	 $n = 3: a\equiv b (\mod 3) \Leftrightarrow \exists q\in\mathbb{Z}: a - b = 3 q$ \\
	 zum Beispiel: $11 \equiv 5(\mod 3)$, denn $11 - 5 = 6 = 2 * 3$ \\
	 zum Beispiel: $7 \not\equiv 2(\mod 3)$, denn $7 - 2 = 5$ und es gibt kein $q\in\mathbb{Z}$ mit $5 = 3 q$
	 \[\bar 0 = \{a\in\mathbb{Z}\mid a = 0 (\mod 3)\} = \{a\in\mathbb{Z} \mid \}\]
	 \[\bar 1 = \{a\in\mathbb{Z}\mid a = 1 (\mod 3)\} = \{a\in\mathbb{Z} \mid \}\]
	 \[\bar 2 = \{a\in\mathbb{Z}\mid a = 2 (\mod 3)\} = \{a\in\mathbb{Z} \mid  \exists q\in\mathbb{Z}: a - 2 = 3q\} = 2 + 3\mathbb{Z} = \{\ldots,-4,-1,2,5,7,\ldots\}\]
	 \[\bar 3 = \{a\in\mathbb{Z}\mid a = 3 (\mod 3)\} = \{a\in\mathbb{Z} \mid  \exists q\in\mathbb{Z}: a - 3 = 3q\} = 3\mathbb{Z} = \bar 0\]
	 \[\bar 4 = \bar 1,\bar 5 = \bar 2,\overline{-1} = \bar 2\]
**** Bemerkung 5.19
	 $n\in\mathbb{N}$ wir definieren eine Verküpfung (Addition) auf $\frac{\mathbb{Z}}{n\mathbb{Z}}$ wie folgt: \\
	 Für $\bar a,\bar b \in\frac{\mathbb{Z}}{n\mathbb{Z}}$ setzen wir $\bar a + \bar b = \overline{a + b}$
	 Dann gilt $(\frac{\mathbb{Z}}{n\mathbb{Z}},+)$ ist eine abelsche Gruppe
***** Beweis
	  1. Die Verknüpfung ist wohldefiniert: \\ Problem: Die Addition verweendet Vertreter von Restklassen. Es ist zum Beispiel in $\frac{\mathbb{Z}}{n\mathbb{Z}}: \bar 3 + \bar 4 = \overline{3 + 4} = \bar 7 = \bar 2$, aber man könnte auch Rechnen:
		 $\bar 3 + \bar 4 = \bar 8 + \bar 9 = \overline{8 + 9} = \overline{17} = \bar 2$ \\
		 Wir müssen nachweisen, dass die Wahl der Vertreter keinen Einfluss auf das Ergebnis hat, das heißt die Verknüfung ist "vertreter unahbhängig": \\
		 Seien $a_1,a_2 ,b_1,b_2 \in\mathbb{Z},\overline{a_1} = \overline{a_2},\overline{b_1} = \overline{b_2}$
		 \[\Rightarrow a_1 (\mod n), b_1 \equiv b_2(\mod n)\]
		 \[\Ŗightarrow\exists q_1,q_2\in\mathbb{Z}: a_1 - a_2 = q_1 n, b_1 - b_2 = q_2 n n, b_1 - b_2 = q_2 n\]
		 \[\Rightarrow (a_1 + b_1) - (a_2 + b_2) = (a_1 - a_2)+ (b_1 - b_2) = q_1 n + q_2 n = (q_1 + q_2) n\]
		 \[\Rightarrow a_1 + b_ 1 \equiv a_2 + b_2 (\mod n)\]
		 \[\Rightarrow \overline{a_1 + b_1} = \overline{a_2 + b_2}\]
	  2. $(\frac{\mathbb{Z}}{n\mathbb{Z}})$ ist eine abelsche Gruppe:
		 - Assoziativgesetz: Für alle $a,b,c\in\mathbb{Z}$ ist
		   \[(\bar a + \bar b) + \bar c = \overline{a + b} + \bar c = \overline{(a + b) + c} = \overline{a + (b + c)} = \bar a + \overline{b + c} = \bar a + (\bar b + \bar c)\]
		 - $\bar 0$ ist neutrales Element, denn $\Forall a\in\mathbb{Z}:\bar 0 + \bar a = \overline{0 + a} = \bar a = \bar a + \bar 0$
		 - Fpr $a\in\mathbb{Z}$ inst $\overline{-a}$ das inverse Element zu $\bar a$, denn $\bar a + \overline{-a} = \overline{a + (- a)} = \bar 0 = \overline{-a} + \bar a$
		 - Kommutativgesetz: $\Forall a,b\in\mathbb{Z}:\bar a + \bar b = \overline{a + b} = \overline{b + a} = \bar b + \bar a$
***** Beispiel
	  Wir tragen die Ergebnisse der Verknüpfung "$+$" in einer Verknüpfungstafel zusamme:
	  n = 3
	  | $+$    | \bar 0 | \bar 1 | \bar 2 |
	  |--------+--------+--------+--------|
	  | \bar 0 | \bar 0 | \bar 1 | \bar 2 |
	  | \bar 1 | \bar 1 | \bar 2 | \bar 0 |
	  | \bar 2 | \bar 2 | \bar 0 | \bar 1 |

	  n = 4
	  | $+$    | \bar 0 | \bar 1 | \bar 2 | \bar 3 |
	  |--------+--------+--------+--------+--------|
	  | \bar 0 | \bar 0 | \bar 1 | \bar 2 | \bar 3 |
	  | \bar 1 | \bar 1 | \bar 2 | \bar 3 | \bar 0 |
	  | \bar 2 | \bar 2 | \bar 3 | \bar 0 | \bar 1 |
	  | \bar 3 | \bar 3 | \bar 0 | \bar 1 | \bar 2 |
*** Gruppenhomomorphismus
	$(G,+),(H,\otimes), \varphi : G \to H$ Abbildung \\
	$\varphi$ heißt ein Gruppenhomomorphismus $\xLeftrightarrow{Def} \Forall a,b,c\in G: \varphi(a*b) = \varphi(a) \otimes \varphi(b)$ \\
	$\varphi$ heißt ein Gruppenisomorphismus $\xLeftrightarrow{Def} \varphi$ ist bijektiver Gruppenhomomorphismus
**** Beispiel
	 1. $\varphi:\mathbb{Z} \to \mathbb{Z}, a\mapsto 2 a$ ist Gruppenhomomorphismus von $(\mathbb{Z},+)$ nach $(\mathbb{Z},+)$ denn:
		\[\varphi( a+ b) = 2(a + b) = 2 a + 2 b = \varphi(a) + \varphi(b) \Forall a,b\in\mathbb{Z}\]
		$\varphi$ ist aber kein Gruppenisomorphismus, denn $\varphi$ ist nicht surjektiv $(1\not\in \varphi = \varphi{\mathbb{Z}})$
	 2. $n\in\mathbb{N}$. Dann gilt $\varphi:\mathbb{Z}\to\frac{\mathbb{Z}}{n\mathbb{Z}},a\mapsto\bar a$ ist ein Gruppenhomomorphismus von $(\mathbb{Z},+)$ nach $(\frac{\mathbb{Z}}{n\mathbb{Z}}, +)$, denn
		\[\Forall a,b\in\mathbb{Z}:\varphi(a+b) = \overline{a + b} = \bar a + \bar b =\varphi(a) + \varphi(b)\]
		$\varphi$ ist kein Gruppenisomorphismus, denn $\varphi$ ist nicht injektiv ($\varphi(0) = \bar 0 = \bar n = \varphi(n)$, aber $0\neq n$)
	 3. $\varphi:\mathbb{Z}\to\mathbb{Z},a\mapsto a + 1$ ist kein Gruppenhomomorphismus von $(\mathbb{Z},+)$ nach $(\mathbb{Z},+)$, denn
		\[\varphi(2 + 6) = \varphi(8) = 9,~\text{aber}~\varphi(2)+\varphi(6) = 3 + 7 = 10\]
	 4. $\exp:\mathbb{R}\to\mathbb{R}_{\geq 0}, x\mapsto \exp{x} = e^x$ ist ein Gruppenisomorphismus von $(\mathbb{R},+)$ nach $(\mathbb{R}_{\geq 0},\cdot)$, denn:
		- \[\exp(a + b) = \exp(a)\exp(b) \Foral a,b\in\mathbb{R}\]
		- $exp$ ist bijektiv (vgl. Ana1 - Vorlesung)
**** Bemerkung 5.23
	 $(G,*),(H,\otimes)$ Gruppen mit neutralen Elementen $e_G$ beziehungsweise $e_H,\varphi:G\to H$ Gruppenhomomorphismus. Dann gilt
	 1. $\varphi(e_G) = e_H$
	 2. $\Forall a\in G:\varphi(a') = \varphi(a)'$ (Hierbei ist $'$ das Inverse)
	 3. Ist \varphi Gruppenisomorphismus, dann gilt $\varphi^{-1}:H\to G$ ebenfalls Gruppenisomorphismus
	 $(G,*),(H,\otimes)$ heißen isomorph $\xLeftrightarrow$ Ex existert ein Gruppenisomorphismus $\phi:G\to H$ Wir schreiben dann $(G,*) \cong (H,\otimes)$
***** Beweis
	  1. Es $e_H\otimes \varphi(e_G) = \varphi(e_G) = \varphi(e_G*e_G) = \varphi(e_G) \otimes\varphi(e_G) \Rightarrow e_H = \varphi(e_G)$
	  2. Sei $a\in G$ Dann ist $e_H = \varphi(e_G) = \varphi(a*a') = \varphi(a)\otimes\varphi(a') \Rightarrow \varphi(a') = \varphi(a)'$
