* Matrizen
  In diesem Abschnitt seinen $m,n,r\in\mathbb{N}$ \\
  Frage: Gegeben sei ein UVR $U = \Lin((v_1, \ldots, v_m)) \subseteq K^n$ Wie bestimmt man effizient die Basis von $U$?
  #+ATTR_LATEX: :options [10.1]
  #+begin_defn latex
  Eine $m\times n$ -Matrix mit Einträgen aus $K$ ist eine Familie $(a_{11}, \ldots, a_{1n}, a_{21}, \ldots, a_{2n}, \ldots, a_{m1}, \ldots, a_{mn})$
  von $m n$ Elementen aus $K$, die wir in der Form
  \[(a_{ij})_{\substack{1\leq i \leq m \\ 1 \leq j \leq n}} = \begin{pmatrix} a_{11} & \ldots & a_{1n} \\ \vdots & & \vdots \\ a_{m 1} & \ldots & a_{mn} \end{pmatrix} \tag{kurz $(a_{ij})$ wenn $m,n$ klar sind}\]
  schreiben. Die Menge aller $m\times n$ Matrizen mit Einträgen aus $K$ bezeichnen wir mit $M(m\times n, K)$.
  Für $A = (a_{ij})$ wie oben heißen
  \[a_i := (1_{i1} \ldots a_{in}), i = 1,\ldots, m\]
  Die Zeilen der Matrix $A$. Im Folgenden fassen wir die Zeilen von $A$ als Elemente von $K^n$ auf: $a_i = (a_{i1}, \ldots, a_{in})$
  \[\begin{pmatrix} a_{1j} \\ \vdots \\ a_{mj}\end{pmatrix} \in M(m\times 1, K), j = 1, \ldots, n\]
  heißen die Spalten der Matrix $A$
  #+end_defn
  #+ATTR_LATEX: :options [10.2]
  #+begin_remark latex
  Es gilt:
  1. $M(m\times n, K)$ ist bezüglich der Verknüpfungen
	 \begin{align*}
	 + &: M(m\times n, K) \times M(m\times n, K) \to M(m\times n, K), (a_{ij}) + (b_ij):= (a_{ij} + b_{ij}) \\
	 \cdot &:K\times M(m\times n, K) \to M(m\times n, K), \lambda \cdot (a_{ij}):=(\lambda a_{ij})
	 \end{align*}
	 ein K_VR. Es ist $\dim_k M(m\times n, K) = m\cdot n$
  2. Durch
	 \[\cdot : M(m\times n, K) \times M(n\times r, K) \to M(m\times r, K)\]
	 \[(a_{ij})_{\substack{1\leq i \leq m \\ 1\leq j\leq n}} \cdot (b_{jk})_{\substack{1\leq j \leq n \\ 1\leq k \leq r}} := (c_{ik})_{\substack{1\leq i \leq m \\ 1\leq k \leq r}}\]
	 mit
	 \[c_{ik} := \sum_{j = 1}^{n}a_{ij} b_{jk}\]
	 ist die Multiplikation von Matrizen erklärt. Visualisierung:
	 \begin{equation}
	 \begin{pmatrix}
	 \\
	 a_{i1} & a_{i2} & \ldots & a_{in} \\
	 \\
	 \end{pmatrix}
	 \cdot
	 \begin{pmatrix}
	 & b_{1k} & \\
	 & \vdots & \\
	 & b_{nk} & \\
	 \end{pmatrix}
	 =
	 \begin{pmatrix}
	 &  & \\
	 & c_{ij} & \\
	 &  & \\
	 \end{pmatrix}
	 \end{equation}
	 Für diese gilt: Sind $A_1, A_2 \in M(m\times n, K), B_1, B_2 \in M(n\times r, K), C\in M(r\times s, K), \lambda \in K$, dann ist
	 - $A(B_1 + B_2) = A\cdot B_1 + A \cdot B_2, (A_1 + A_2) B = A_1 B + A_2 B$
	 - $A(\lambda B) = (\lambda A) B = \lambda (A B)$
	 - $A(B C) = (AB) C$
	 - $E_m \cdot A = A \cdot E_n = A$
	 Hierbei ist für $l \in \mathbb{N}$
	 \[E_l := \begin{pmatrix} 1 & & 0 \\ & \ddots & \\ 0 & & 1 \end{pmatrix} \in M(l\times l, K)\]
	 die $l\times l$ -Einheitsmatrix über $K$
  3. $M(n\times n, K)$ ist bezüglich
	 \[+,\cdot : M(n\times n, K) \times M(n\times n, K) \to M(n\times n, K)\]
	 ("$+$" siehe 1., "$\cdot$" siehe 2.) \\
	 ein Ring. (Einselement: $E_n$). Für $n > 1$ ist dieser Ring *nicht* kommutativ
  #+end_remark
  #+begin_proof latex
  Nachrechnen \\
  Zu $\dim M(m\times n, K) = m\cdot n$: Eine Basis von $M(m\times n, K)$ ist durch die Familie der Matrizen $E_{ij}, i = 1, \ldots, m, j = 1,\ldots, n$ gegeben, wobei $E_{ij}$ diejenige $m\times n$ -Matrix mit Einträgen in $K$ bezeichnen, die in der i-ten Zeile, j-ten Spalte eine Eins
  und sonst nur Nullen stehen hat. \\
  zu 3.: $M(n\times n, K)$ ist nicht kommutativ für $n > 1$:
  \begin{align*}
  &\sbox0{$\begin{matrix} 1 & 0 \\ 0 & 0 \end{matrix}$}%
  \sbox1{$\begin{matrix} 0 & 1 \\ 0 & 0 \end{matrix}$}%
  \left\string(
  \begin{array}{c|c}
  \usebox{0}&\makebox[\wd0]{$0$} \\
  \hline
  \vphantom{\usebox{0}}\makebox[\wd0]{$0$}&\makebox[\wd0]{$0$}
  \end{array}
  \right\string)
  \cdot
  \left\string(
  \begin{array}{c|c}
  \usebox{1}&\makebox[\wd1]{$0$} \\
  \hline
  \vphantom{\usebox{1}}\makebox[\wd1]{$0$}&\makebox[\wd1]{$0$}
  \end{array}
  \right\string)
  =
  \left\string(
  \begin{array}{c|c}
  \usebox{1}&\makebox[\wd1]{$0$} \\
  \hline
  \vphantom{\usebox{1}}\makebox[\wd1]{$0$}&\makebox[\wd1]{$0$}
  \end{array}
  \right\string) \\
  \neq&
  \sbox0{$\begin{matrix} 1 & 0 \\ 0 & 0 \end{matrix}$}%
  \sbox1{$\begin{matrix} 0 & 1 \\ 0 & 0 \end{matrix}$}%
  \sbox2{$\begin{matrix} 0 & 0 \\ 0 & 0 \end{matrix}$}%
  \left\string(
  \begin{array}{c|c}
  \usebox{1}&\makebox[\wd1]{$0$} \\
  \hline
  \vphantom{\usebox{1}}\makebox[\wd1]{$0$}&\makebox[\wd1]{$0$}
  \end{array}
  \right\string)
  \cdot
  \left\string(
  \begin{array}{c|c}
  \usebox{0}&\makebox[\wd0]{$0$} \\
  \hline
  \vphantom{\usebox{0}}\makebox[\wd0]{$0$}&\makebox[\wd0]{$0$}
  \end{array}
  \right\string)
  =
  \left\string(
  \begin{array}{c|c}
  \usebox{2}&\makebox[\wd1]{$0$} \\
  \hline
  \vphantom{\usebox{1}}\makebox[\wd1]{$0$}&\makebox[\wd1]{$0$}
  \end{array}
  \right\string) \\
  \end{align*}
  #+end_proof
  #+ATTR_LATEX: :options [10.3]
  #+begin_defn latex
  $A$ heißt invertierbar $\xLeftrightarrow{\text{Def}} \Exists B\in M(n\times n, K): AB = BA = E_n$
  #+end_defn
  #+ATTR_LATEX: :options [10.4]
  #+begin_remark latex
  Es gilt:
  \[GL(n, K) := \{A\in M(n\times n, K) \mid A ~\text{ist invertierbar}\}\]
  ist bezüglich der Matrizenmultiplikation eine Gruppe, die so genannte allgemeine lineare Gruppe.
  Das neutrale Element ist $E_n$, das zu $A\in GL(n,K)$ inverse Element bezeichnen wir mit $A^{-1}$.
  #+end_remark
  #+begin_proof latex
  Wohldefiniertheit von "$\cdot$" auf $GL(n, K)$ \\
  zu zeigen ist: $A_1, A_2 \in GL(n, K) \implies A_1 A_2 \in GL(n,K)$ \\
  Dies gilt, denn:
  \begin{gather*}
  A_1, A_2 \in GL\string(n, K\string) \implies \Exists B_1, B_2 \in M\string(n\times n, K\string): A_1 B_1 = B_1 A_1 = E_n, A_2 B_2 = B_2 A_2 = E_N \\
  \implies \string(A_1 A_2\string) \cdot \string(B_2 B_1\string) = A_1\string(A_2 B_2\string) B_1 = A_1 E_n B_1 = A_1 B_1 = E_n \\
  \string(B_2 B_1\string) \cdot \string(A_1 A_2\string) = B_2 \string(B_1 A_1\string) A_2 = B_2 E_n A_2 = B_2 A_2 = E_n
  \end{gather*}
  das heißt $A_1 A_2 \in GL(n,K)$
  - Assoziativität: Vererbt sich von $M(n\times n, K)$
  - neutrales Element: $E_n$
  - Existenz von Inversen: Sei $A\in GL(n,K) \implies \Exists B\in M(n\times n, K): AB = BA = E_n$ also ist $B\in GL(n,K)$ und $B$ ist invers zu $A$ bezüglich "$\cdot$".
  #+end_proof
  #+ATTR_LATEX: :options [10.5]
  #+begin_defn latex
  $A \in M(m\times n, K)$ mit Zeilen $a_1, \ldots, a_m \in K^n$ \\
  Unter elementaren Zeilenumformungen von $A$ verstehen wir die folgende Umformungen von $A$
  1. Multiplikation der i-ten Zeile mit $\lambda \in K^\ast = K \setminus\{0\}$
	 \[\begin{pmatrix} \vdots \\ a_i \\ \vdots \end{pmatrix} \to \begin{pmatrix} \vdots \\ \lambda a_i \\ \vdots \end{pmatrix}\]
  2. Addition der j-ten Zeile zur i-ten Zeile, $i\neq j$
	 \[\begin{pmatrix} \vdots \\ a_i \\ \vdots \\ a_j \\ \vdots\end{pmatrix} \to \begin{pmatrix} \vdots \\ a_i + a_j \\ \vdots \\ a_j  \\ \vdots \end{pmatrix}\]
  3. Addition der $\lambda$ fachen der j-ten Zeile zur i-ten Zeile, $\lambda \in K^\ast, i\neq j$
	 \[\begin{pmatrix} \vdots \\ a_i \\ \vdots \\ a_j \\ \vdots\end{pmatrix} \to \begin{pmatrix} \vdots \\ a_i + \lambda a_j \\ \vdots \\ a_j  \\ \vdots \end{pmatrix}\]
  4. Vertauschen der i-ten Zeile mit der j-ten Zeile, $i\neq j$
	 \[\begin{pmatrix} \vdots \\ a_i \\ \vdots \\ a_j \\ \vdots\end{pmatrix} \to \begin{pmatrix} \vdots \\ a_j \\ \vdots \\ a_i  \\ \vdots \end{pmatrix}\]
  #+end_defn
  #+begin_note latex
  \mbox{}
  - Typ 3. und 4. kann man durch Kombination von Umformungen vom Typ 1. und 2. erhalten, 3.:
	\begin{equation}
	\begin{pmatrix} \vdots \\ a_i \\ \vdots \\ a_j \\ \vdots\end{pmatrix}
	\to \begin{pmatrix} \vdots \\ a_i \\ \vdots \\ \lambda a_j  \\ \vdots \end{pmatrix}
	\to \begin{pmatrix} \vdots \\ a_i \\ \vdots \\ \lambda a_j \\ \vdots\end{pmatrix}
	\to \begin{pmatrix} \vdots \\ a_i + \lambda a_j \\ \vdots \\ \lambda a_j  \\ \vdots \end{pmatrix}
	\to \begin{pmatrix} \vdots \\ a_i + \lambda a_j \\ \vdots \\ a_j  \\ \vdots \end{pmatrix}
	\end{equation}
	Typ 4.:
	\begin{equation}
	\begin{pmatrix} \vdots \\ a_i \\ \vdots \\ a_j \\ \vdots\end{pmatrix}
	\to \begin{pmatrix} \vdots \\ a_i + a_j \\ \vdots \\ a_j  \\ \vdots \end{pmatrix}
	\to \begin{pmatrix} \vdots \\ a_i + a_j \\ \vdots \\ -a_j  \\ \vdots \end{pmatrix}
	\to \begin{pmatrix} \vdots \\ a_i + a_j \\ \vdots \\ a_i  \\ \vdots \end{pmatrix}
	\to \begin{pmatrix} \vdots \\ a_i \\ \vdots \\ a_j  \\ \vdots \end{pmatrix}
	\end{equation}
  - Analog zu den elementaren Zeilenumformungen definiert man elementare Spaltenumformungen in nahe liegender Weise
  - Elementare Zeilenumformungen erhält man durch Multiplikation von $A$ mit sogenannten *Elementarmatrizen* von links,
	elementare Spaltenumformungen durch Multiplikation mit Elementarmatrizen von recht.
  #+end_note
  #+ATTR_LATEX: :options [10.6]
  #+begin_defn latex
  $A\in M(m\times n, K)$ mit Zeilen $a_1, \ldots, a_m \in K^n$ \\
  \[ZR(A) := \Lin((a_1, \ldots, a_m)) \subseteq K^n\]
  heißt Zeilenraum von $A$.
  #+end_defn
  #+ATTR_LATEX: :options [10.7]
  #+begin_ex latex
  \begin{equation}
  A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 5 \end{pmatrix} \in M(2,\times 3, \mathbb{Q}) \implies ZR(A) = \Lin((1,2,3), (4,5,6)) \subseteq \mathbb{Q}^2
  \end{equation}
  #+end_ex
  #+ATTR_LATEX: :options [10.8]
  #+begin_remark latex
  $A,B \in M(m\times n, K)$ \\
  Dann gilt: Ist $B$ aus $A$ durch eine endliche Folge von elementaren Zeilenumformungen entstanden, dann ist $ZR(B) = ZR(A)$
  #+end_remark
  #+begin_proof latex
  Wegen Anmerkung nach 10.5 genügt es, einzelne Zeilenumformungen vom Typ 1. und 2. zu betrachten
  1. Typ 1-Umformung:
	 \[A = \begin{pmatrix} a_1 \\ \vdots \\ a_m \end{pmatrix}, B = \begin{pmatrix} a_1 \\ \vdots \\ \lambda a_j \\ \vdots \\ a_m\end{pmatrix}, \lambda \in K^\ast\]
	 zu zeigen: \[ZR(A) = \Lin((a_1, \ldots, a_m)) = \Lin((a_1, \ldots, a_{j - 1}, \lambda a_j, a_{j + 1},\ldots, a_m)) = ZR(B)\]
	 Dies gilt, da jeder UVR von $K^n$, der $a_1, \ldots, a_m$ enthält, auch $a_1, \ldots, a_{j -1}, \lambda a_j, a_{j + 1}, \ldots, a_m$ enthält und umgekehrt (Behauptung folgt dann aus 8.13)
  2. Typ 2-Umformungen:
	 \[A = \begin{pmatrix} a_1 \\ \vdots \\ a_m \end{pmatrix}, B = \begin{pmatrix} a_1 \\ \vdots \\ a_i + a_j \\ \vdots \\ a_m\end{pmatrix}, \lambda \in K^\ast\]
	 zu zeigen:
	 \[ZR(A) = \Lin((a_1, \ldots, a_m)) = \Lin((a_1, \ldots, a_{i - 1}, a_i + a_j, a_{i + 1}, \ldots, a_m)) = ZR(B)\]
	 Dies gilt, denn jeder UVR von $K^n$, der $a_1, \ldots a_m$ enthält auch $a_1, \ldots, a_{i - 1}, a_i + a_j, a_{i + 1}, \ldots, a_m$ enthält und umgekehrt (Behauptung folgt dann aus 8.13)
  #+end_proof
  Ziel: Bringe Matrix $A \in M(m\times n, K)$ mit Zeilen $a_1, \ldots, a_m \in K^n$ durch elementare Zeilenumformungen auf "einfache Gestalt", aus oder man eine Basis von $\Lin((a_1, \dots, a_m)) = ZR(A) = ZR(B)$
  ablesen kann.
  #+ATTR_LATEX: :options [10.9]
  #+begin_defn latex
  $A = (a_{ij}) \in M(m\times n, K)$ \\
  $A$ ist in Zeilenstufenform (ZSF) $\xLeftrightarrow{\text{Def}}$ die folgenden Bedingungen sind erfüllt
  - (Z1) Es gibt eine Zahl $r\in\mathbb{N}_0$, mit $0\leq r \leq m$, so dass in den Zeilen mit Index $1$ bis $r$ jeweils nicht nur Nullen stehen und in der Zeile mit den Indizes $r + 1$ bis $m$ stehen nur Nullen.
  - (Z2) Setzen wir für $i$ mit $1 \leq i \leq r$
	\[j_{i} := \min\{j\in \{1, \ldots, n\} \mid a_{ij} \neq 0\}\]
	dann gilt: $j_1 < j_2 < \ldots < j_r$ (Stufenbedingung), die Elemente $a_{1j_1}, \ldots, a_{1j_r}$ heißen die Pivots von $A$
  #+end_defn
  #+ATTR_LATEX: :options [10.10]
  #+begin_ex latex
  \begin{equation}
  A =
  \begin{pmatrix}
  0 & 3 & 1 & 0 & 3 & 4 \\
  0 & 0 & 0 & 2 & 3 & 4 \\
  0 & 0 & 0 & 0 & 6 & -1 \\
  0 & 0 & 0 & 0 & 0 & 0
  \end{pmatrix}
  \in M(4\times 6, \mathbb{R})
  \end{equation}
  ist in ZSF. Es ist $r = 3, j_1 = 2, j_2 = 4, j_3 = 5$, Pivots: $a_{12} = 3, a_{24} = 2, a_{35} = 6$
  #+end_ex
  #+ATTR_LATEX: :options [10.11]
  #+begin_defn latex
  $A \in M(m\times n, K)$ \\
  Dann lässt sich $A$ durch endlich viele elementare Zeilenstufenumformungen in eine Matrix $B$ in ZSF umformen:
  \begin{equation}
  \begin{pmatrix}
  & b_{1j_1} & \ast & & & & \\
  & & b_{1j_2} & \ast & & & \\
  & & & \ldots & & \\
  & & & & b_{1j_r} & \ast & \\
  0 & & & & & & \\
  \end{pmatrix}
  \end{equation}
  Die ersten $r$ Zeilen von $B$ bilden eine Basis von $ZR(A)$.
  #+end_defn
  #+begin_proof latex
  1. $A$ lässt sich wie behauptet auf ZSF bringen: \\
	 Falls $A = 0$, dann ist $A$ bereits in ZSF (mit r = 0), also im Folgenden sei $A \neq 0$ \\
	 1) Bestimme minimalen Index $j_1 \in \{1, \ldots, n\}$, so dass es ein $i_1 \in \{1, \ldots, m\}$ gibt mit $a_{i_1 j_1} \neq 0$ ("Wie weit links in der Matrix $A$ befinden sich Einträge $\neq 0$?") \\
		Wähle solch ein $i_1$ aus.
	 2) Vertausche $i_1$ -te Zeile mit erster Zeile, erhalte ersten Pivot:
		\begin{equation}
		\tilde a_{1, j_1} := a_{i_1, j_1} \neq 0 \\
		A_1 :=
		\begin{pmatrix}
		0 & \ldots & 0 & \tilde a_{1, j_1} & \ast & \ldots & \ast \\
		  &        &   &       \ast        &  & & \\
		& \text{\huge0} & & \vdots & & \text{\huge$\ast$} & \\
		& & & \ast & & & \\
		\end{pmatrix}
		\end{equation}
	 3) Durch Umformungen vom Typ 3. können alle Einträge der $j_1$ -ten Spalte unterhalb der ersten Zeile zu Null gemacht werden, erhalte:
		\begin{equation}
		\begin{pmatrix}
		0 & \ldots & 0 & \tilde a_{1, j_1} & \ast & \ldots & \ast \\
		  &        &   &       0        &  & & \\
		& \text{\huge0} & & \vdots & & A_2 & \\
		& & & 0 & & & \\
		\end{pmatrix}
		\end{equation}
	 4) Wende das Verfahren 1. - 3. auf $A_2$ an. Die dafür benötigten elementaren Zeilenumformungen von $A_2$ kann man
		auf die Zeilen $2$ bis $m$ von $\tilde A_1$ ausdehnen, ohne dass sich in den Spalten $1$ bis $j_1$ von $\tilde A_1$ etwas ändert, denn
		dort stehen Nullen. Erhalte auf diese Weise $\tilde A_2$ beziehungsweise $A_3$. Iteriere dieses Verfahren.
		Das Verfahren bricht ab, weil die Folge der Spaltenzahlen der Matrizen $A_k$ string monoton fallend in $\mathbb{N}$ ist, oder irgendwann eine Matrix $A_k = 0$ entsteht. \\
		$\implies$ erhalte ZSF.
		Die ersten $r$ Zeilen $b_1, \ldots, b_r$ von $B$ bilden eine Basis von $ZR(A)$, denn Es ist $ZR(A) = ZR(B) = \Lin((b_1, \ldots, b_r))$ \\
		noch zu zeigen: $(b_1, \ldots, b_r)$ ist linear unabhängig. \\
		Es seien $\lambda_1, \dots, \lambda_r \in K$ mit $\lambda_1 b_1 + \ldots + \lambda_r b_r = 0$. In der $j_1$ -ten Komponente von $\lambda_1 b_1 + \ldots + \lambda_r b_r$ steht $\lambda_1 b_{1 j_1}$ = 0.
		Wegen $b_{1 j_1} = 0$ folgt $\lambda_1$ = 0.
		In der $j_2$ -ten Komponente von $\lambda_1 v_1 + \ldots + \lambda_r b_r = \lambda_2 b_2 + \ldots + \lambda_r b_r$ steht $\lambda_2 b_{2 j_2} = 0$
		Wegen $b_{2 j_2} \neq 0$ folgt $\lambda_2 = 0$.
		Durch Iterieren dieses Arguments erhalten wir $\lambda_1 = \ldots = \lambda_r = 0$
  #+end_proof
  #+ATTR_LATEX: :options [10.12]
  #+begin_algorithm latex
  Eingabe: $W = \Lin((v_1, \ldots, v_m)) \subseteq K^n$ \\
  Ausgabe: Eine Basis $(w_1, \ldots, w_r)$ von $W$ \\
  Durchführung: \\
  1. Bilde aus den Zeilenvektoren $v_1, \ldots, v_m$ die Matrix $A\in M(m\times n, K)$
  2. Bringe die Matrix $A$ durch elementare Zeilenumformung auf ZSF $B$
  3. Die Familie $(w_1, \ldots, w_r)$ der ersten $r$ Zeilenvektoren von $B$ ist ein Basis von $W$
  #+end_algorithm
  #+ATTR_LATEX: :options [10.13]
  #+begin_ex latex
  $W = \Lin((0,0,3,-1), (0, 1, 2, 0), (0, 3, 0, 2)) \subseteq \mathbb{R}^4$
  \begin{gather}
  A = \begin{pmatrix}
  0 & 0 & 3 & -1 \\
  0 & 1 & 2 & 0 \\
  0 & 3 & 0 & 2
  \end{pmatrix}
  \to
  \begin{pmatrix}
  0 & 1 & 2 & 0 \\
  0 & 0 & 3 & -1 \\
  0 & 3 & 0 & 2
  \end{pmatrix}
  \to
  \begin{pmatrix}
  0 & 1 & 2 & 0 \\
  0 & 0 & 3 & -1 \\
  0 & 0 & -6 & 2
  \end{pmatrix}
  \to
  \begin{pmatrix}
  0 & 1 & 2 & 0 \\
  0 & 0 & 3 & -1 \\
  0 & 0 & 0 & 0
  \end{pmatrix}
  \end{gather}
  $\implies ((0,1,2,0), (0,0,3,-1))$ ist eine Basis von $W$ insbesondere ist $\dim_W = 2$
  #+end_ex
  #+ATTR_LATEX: :options [10.14 transponierte Matrix]
  #+begin_defn latex
  $A = (a_{ij}) \in M(m\times n, K)$
  \[A^t := \begin{pmatrix} a_{11} & & a_{m1} \\ \vdots & \ldots & \vdots \\ a_{1n} & & a_{mn} \end{pmatrix} \in M(n\times m, K)\]
  heißt die zu $A$ transponierte Matrix (Transponierte von $A$).
  #+end_defn
  #+ATTR_LATEX: :options [10.15]
  #+begin_ex latex
  \[A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6\end{pmatrix} \in M(2\times 3, \mathbb{R}) \implies A^t = \begin{pmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{pmatrix} \in M(3\times 2, \mathbb{R})\]
  #+end_ex
  #+ATTR_LATEX: :options [10.16]
  #+begin_remark latex
  $A, A_2, A_2 \in M(m\times n, K), B\in M(n\times r, K), \lambda K$ dann gilt:
  1. $(A_1 + A_2)^t = A_1^t + A_2^t$
  2. $(\lambda A)^t = \lambda A^t$
  3. $(A^t)^t = A$
  4. $(AB)^t = B^t A^t$
  #+end_remark
  #+begin_proof latex
  1. trivial
  2. trivial
  3. trivial
  4. Nach 3. gezeigt: $AB = (B^t A^t)^t \implies (AB)^t = ((B^t A^t)^t)^t = B^t A^t$.
	 Sei $A = (a_{ij})_{\substack{1 \leq 1 \leq m \\ 1 \leq j \leq n}}, B = (b_{ij})_{\substack{1 \leq 1 \leq n \\ 1 \leq j \leq r}}$ \\
	 $\implies$ Eintrag an Position $(i,k)$ von $AB$ ist gegeben durch
	 \[\sum_{1\leq j\leq n}{a_{ij}b_{jk}}\]
	 Eintrag an Position $(i,k)$ in $(B^t A^t)^t =$ Eintrag an Position $(r,i)$ von $B^t A^t$.
	 Dieser ist gegeben durch:
     \[\sum_{i\leq j \leq n} b'_{kj} a'_{ji} = \sum_{1\leq j\leq n} b_{jk} a_{ij} = \sum_{1 \leq j \leq m} a_{ij} b_{jk} \]
	 wobei:
	 - $b'_{kj} =$ Eintrag an Position $(k,j)$ von $B^t = b_{jk}$
	 - $a'_{ji} =$ Eintrag an Position $(j,i)$ von $A^t = a_{ij}$
	 Somit $AB = (B^t A^t)^t$
  #+end_proof
  #+ATTR_LATEX: :options [10.17]
  #+begin_defn latex
  $A\in M(m\times n, K)$
  - Zeilenrang$(A):= \dim_k \ZR(A)$ heißt der *Zeilenrang* von $A$
  - $\SR(A):= \ZR(A^t) \subseteq k^m$ heißt der *Spaltenraum* von $A$
  - Spaltenrang$(A):= \dim_k \SR(A)$ heißt der *Spaltenrang* von $A$
  #+end_defn
  #+ATTR_LATEX: :options [10.18]
  #+begin_ex latex
  Wir betrachten die Matrix $A$ aus Beispiel 10.13
  \begin{align*}
  A &= \begin{pmatrix} 0 & 0 & 3 & -1 \\ 0 & 1 & 2 & 0 \\ 0 & 3 & 0 & 2\end{pmatrix} \in M(3\times 4, \mathbb{R}), \dim \ZR(A) = 2 \\
  A^t &= \begin{pmatrix} 0 & 0 & 0 \\ 0 & 1 & 3 \\ 3 & 2 & 0 \\ -1 & 0 & 2\end{pmatrix} \in M(4\times 3, \mathbb{R}) \implies \SR(A) := \Lin((0,0,0), (0,1,3), (3,2,0), (-1,0,2)) \\
  \end{align*}
  Wir bestimmen eine Basis von $\SR(A)$:
  \begin{equation*}
  A^t = \begin{pmatrix} 0 & 0 & 0 \\ 0 & 1 & 3 \\ 3 & 2 & 0 \\ -1 & 0 & 2\end{pmatrix} \to
  \begin{pmatrix} -1 & 0 & 2 \\ 0 & 1 & 3 \\ 3 & 2 & 0 \\ 0 & 0 & 0\end{pmatrix} \to
  \begin{pmatrix} -1 & 0 & 2 \\ 0 & 1 & 3 \\ 0 & 2 & 6 \\ 0 & 0 & 0\end{pmatrix} \to
  \begin{pmatrix} -1 & 0 & 2 \\ 0 & 1 & 3 \\ 0 & 0 & 0 \\ 0 & 0 & 0\end{pmatrix}
  \end{equation*}
  $\implies ((-1, 0, 2), (0, 1, 3))$ ist eine Basis von $\SR(A) \implies$ Spaltenrang$(A)$ = 2.
  In diesem Beispiel ist also Zeilenrang$(A) =$ Spaltenrang$(A)$.
  #+end_ex
  #+begin_note latex
  Wir werden später zeigen: Für jedes $A\in M(m\times n, K)$ ist Zeilenrang$(A) =$ Spaltenrang$(A)$.
  #+end_note
