* Mechanik deformierbarer Körper
  Starrer Körper: $\v r_i - \v r_j = ~\text{const}$, das heißt Abstand zwischen Massenpunkten konstant. \\
  Wirklichkeit: Verformung bei Anwendung äußerer Kräfte.
** Atomares Modell
   Experiment: Alle Körper sind aus Atomen oder Molekülen aufgebaut.
   Beschreibung von Kräften zwischen Atomen und Molekülen durch Lennard-Jones-Potential. (Dipol-Dipol-Wechselwirkung, Van-der-Waals Kräfte) \\
   Gleichgewichtsabstand: $r_0$ ($E_{pot} =$ minimal)
   Für kleine Auslenkung gilt:
   \begin{align*}
   E_{pot} &= \frac{1}{2}k(r - r_0)^2 \\
   F &= -\dd{E_{pot}}{r} = -k(r - r_0) = -k Ar
   \end{align*}
   Federkraft!
   $\implies$
   - Modell eines Festkörper: Federmodell. \\
	 Temperatur unterhalb des Schmelzpunktes. Mittlere kinetische Energie klein gegen $E_{pot}(r_0)$.
	 Atome können Gitterplätze nicht verlassen. Fernordung!
   - Modell einer Flüssigkeit: Kugelmodell: \\
	 Auch hier mittlerer Abstand $= r_0$, das heißt Dichte ähnlich die des Festkörpers.
	 Aber: Temperatur zu hoch für feste Zuordnung auf Kristallgitterplätzen $\implies$ flüssiger Zustand. Nahordung!
   - Modell eines Gases: frei bewegliche Teilchen. \\
	 Mittlere kinetische Energie ist grob gegen Bindungsenergie, hohe Temperatur!
** Feste Körper.
   - Elastischer fester Körper \rightarrow Formelastizität, Volumenelastizität aufgrund rücktreibender Kräfte (Hookscher Bereich)
   - Plastisch feste Körper \rightarrow Formänderungen verbleiben
   Hier: Elastische Körper!
   Experimentell findet man:
   \begin{align*}
   \Delta f &\sim F \\
   \Delta L &\sim L, \Delta L \sim A^{-1} \\
   \Delta L &\sim L \frac{F}{A} = L r \tag{$r$: Zugspannung}
   \end{align*}
   #+ATTR_LATEX: :options [Hooksches Gesetz:]
   #+begin_defn latex
   \[\sigma = E \frac{\Delta L}{L} = E \eps\]
   - $E:$ Elastizitätsmodul, E-Modul
   - $\eps:$ Elongation, relative Längenänderung
   - $\sigma:$ Zugspannung, $\sigma = \frac{F}{A}$
   #+end_defn
   Auswertung Hooksches Gesetz:
   Material-Stahl, $D = \SI{0.3}{\milli\meter}, L = \SI{6}{\meter}, A = \SI{0.07}{\meter\squared}$
   \begin{align*}
   F &= \SI{1.2}{\kilo\pascal} = \SI{11.8}{\newton}, \Delta L = \SI{5}{\milli\meter}, \eps = \SI{8e-4}{} \rightarrow \sigma = \SI{168.6}{\newton\per\milli\meter\squared} \\
   F &= \SI{2.4}{\kilo\pascal} = \SI{13.5}{\newton}, \Delta L = \SI{10}{\milli\meter}, \eps = \SI{1.7e-3}{} \rightarrow \sigma = \SI{337.2}{\newton\per\milli\meter\squared}
   \implies E&= \frac{\sigma}{\eps} \SI{2e5}{\newton\per\milli\meter\squared} = \SI{200e9}{\newton\per\meter\squared}
   \end{align*}
   Einfaches Atomares Modell: Lineare Kette.
   Es gilt:
   \[L = n a, \Delta a \sim F, \Delta L \sim m \Delta a \sim n F\]
   Außerdem wegen \[L \sim m : \Delta L \sim L F \to F \sim \frac{\Delta L}{L}\]
   Für eine lineare Kette ist $\eps \frac{\Delta L}{L}$ tatsächlich proportional zur Kraft $F$. \\
   Für $\eps \sim A^{-1}$ braucht man mehrere lineare Ketten parallel aneinander.

   Aber: Auch Wechselwirkung in transversaler Richtung! \\
   #+ATTR_LATEX: :options [Querkontraktion]
   #+begin_defn latex
   $\frac{\Delta D}{D} \sim \frac{\Delta L}{L}$
   \[\frac{\Delta D}{D} = -\mu \frac{\Delta L}{L}\]
   $\mu$: Poissonsche Zahl $\approx 0.3$
   #+end_defn

   Volumenänderung (kleine Änderung)
   \begin{align*}
   V &= (\frac{\pi}{4}) D^2 L \\
   \Delta \xi &= \frac{\Delta V}{V} = ? \\
   \xi &= \ln V \\
   &= 2 \ln D + \ln L + ~\text{const} \\
   \Delta \xi &\approx \frac{1}{V} \Delta V \approx 2 \frac{1}{D} \Delta D + \frac{1}{L} \Delta L = \dd{\xi}{V} \Delta V = \dd{\xi}{D} \Delta D + \dd{\xi}{L} \delta L \\
   \frac{V}{V} &= -2 \mu \frac{\Delta L}{L} + \frac{\Delta L}{L} = \frac{\Delta L}{L} (1 - 2\mu) \\
   \frac{\Delta V}{V} &= \frac{\sigma}{E} (1 - 2\mu) \tag{Volumenänderung}
   \end{align*}

   Kompression (von Flüssigkeiten)
   \begin{align*}
   \frac{\Delta V}{V} &= - \chi \Delta p \\
   \chi = 3 \frac{1}{E}(1 - 2 \mu)
   \end{align*}
   $\chi$: Kompressibilität

** Scherung und Torsion
   \begin{align*}
   \intertext{Normalspannung oder Zugspannung}
   \sigma &= \frac{F_N}{A} \\
   \intertext{Tangentialspannung oder Scherspannung}
   \tau &= \frac{F_T}{A}
   \intertext{F+r kleine Scherwinkel}
   \tau = G \alpha \tag{$G$: Schubmodul, Torsionsmodul} \\
   \end{align*}

   Torsion eines Drahtes (Vollzylinder)
   \begin{align*}
   \tau &= \dd{F}{A} \\
   R \phi &= L \alpha \\
   \d M &= \d F R \\
   \d A &= 2\pi R \d R \\
   \tau &= \dd{F}{A} = \underbrace{\frac{\d M}{R}}_{\d F} \frac{1}{2\pi R \d R} = G \alpha = G \frac{R \phi}{L} \\
   \d M &= \frac{2\pi G \phi}{L} \bar R^3 \d \bar R \\
   M &= \underbrace{\frac{2\pi G R^4}{2 L}}_{\text{const}} \phi = k_0 \phi \\
   \intertext{Empfindlichkeit:}
   \frac{\phi}{M} &\sim \frac{1}{R^4} \\
   M &= I \ddot{\phi} = -k_D \phi, k_D = \frac{\pi G R^4}{2L} \\
   \phi(t) &= \phi_{max} \sin(\omega_0 t + \phi_0) \\
   \omega_0 &= \sqrt{\frac{k_K}{I}} \\
   T &= \frac{2\pi}{\omega_0} \sim \sqrt{\frac{I}{k_D}} \frac{1}{R^2} \\
   \end{align*}
   Ein bisschen was für Ingenieure
   \begin{align*}
   \phi &= \frac{L}{\rho} = \frac{L + \Delta L}{\rho + \eta} \\
   \eps &= \frac{\Delta L}{L} = \frac{\eta}{\rho} \\
   \d M &= \eta \d F \\
   \d M &= \eta \d F = \eta \sigma \d A = \eta \eps E \d A = \eta^2 \frac{1}{\rho} E \d A \tag{wegen $\eps = \frac{\eta}{\rho}$}\\
   M &= \frac{E}{\rho} \int \eta^2 \d A
   \end{align*}
   #+ATTR_LATEX: :options [Flächenträgheitsmoment]
   #+begin_defn latex
   \[J = \int \eta^2 \d A\]
   - Integral über Querschnittsfläche
   - $\eta:$ senkrechter Abstand der Punkte der Querschnittsfläche von neutraler Ebene
   #+end_defn
   #+ATTR_LATEX: :options [Quader]
   #+begin_ex latex
   \begin{align*}
   J &= \int_{-\frac{h}{2}}^{\frac{h}{2}} \eta^2 v \d\eta \\
   &= \frac{1}{12} b h^3
   \end{align*}
   Bautechnik:
   Krümmung $\kappa$:
   \[\kappa = \frac{1}{\rho} = \frac{M}{E J}\]
   #+end_ex
** Ruhende Flüssigkeiten-Hydrostatik
   keine Formelastizität, $G = 0$ ! \\
   aber: Hohe Volumenelastizität \\
   Das heißt: Alle Kräfte senkrecht zur Oberfläche.
   #+ATTR_LATEX: :options [Druck]
   #+begin_defn latex
   Hydrostatischer Druck
   \[p = \frac{F}{A}\]
   Also die auf die Fläche wirkende Normalkraft pro Fläche.
   \begin{align*}
   [p] &= \si{\newton\per\meter\squared} = \si{\pascal} \\
   \SI{1}{\bar} &= \SI{1e5}{\pascal} \\
   %\SI{1}{\torr} &= \SI{1}{\milli\meter\hg} = \SI{133.322}{\pascal} \\
   \SI{1}{\torr} &= \SI{133.322}{\pascal} \\
   \SI{1}{\atm} &= \SI{1.013}{\bar} \\
   \end{align*}
   #+end_defn

   \begin{align*}
   \frac{\Delta V}{V} &= \kappa \Delta p = \frac{1}{K} \Delta p \\
   \intertext{Wasser:}
   \kappa &= \SI{5e-10}{\meter\squared\per\newton}
   \intertext{Aluminium:}
   \kappa &= \SI{1.4e-10}{\meter\squared\per\newton}
   \end{align*}
   Im Folgende: $\kappa = 0, V =~\text{const}$, das heißt Wasser "inkompresible"
   #+ATTR_LATEX: :options [Pascalsches Prinzip]
   #+begin_thm latex
   Wird auf eine in einem Gefäß eingeschlossene Flüssigkeit ein Druck ausgeübt, dann verteilt sich dieser
   ungehindert auf jeden Punkt in der Flüssigkeit und die Wände.
   #+end_thm
   Zur Veranschaulichung: betrachte frei schwebendes Flüssigkeitsprisma in ruhender Flüssigkeit,
   frei wählbar... (hier noch: ohne Schwerkraft)
   \begin{align*}
   F_x &= F_{xc} - F_{xb} = F_c \sin{\alpha} - F_b \\
   &= P_c h c \sin{\alpha} - p_b h b \overset{=}{!} 0 \\
   F_y &= F_{ya} - F_{yc} = F_a - F_c \cos{\alpha} \\
   &= p_a a h - p_c h c \cos{\alpha} \overset{=}{!} 0 \\
   \intertext{Mit $\sin{\alpha} = \frac{b}{a}, \cos{\alpha} = \frac{a}{c}$ folgt:}
   p_c h c \frac{b}{c} - p_b b h &= 0 \implies p_c = p_b \\
   p_a a h - p_c h c \frac{a}{c} &= 0 \implies p_a = p_c
   \end{align*}
   #+begin_remark latex
   In z-Richtung sind Kräfte aus Symmetriegründen ebenfalls Null!
   da Flüssigkeitsprisma frei gewählt, das heißt beliebig orientiert werden kann folgt Pascalsches Prinzip
   #+end_remark
   Anwendung: Hydraulische Presse. Druck überall gleich!
   $\implies$
   \begin{align*}
   p &= \frac{F_1}{A_1} = \frac{F_2}{A_2} \\
   F_2 = F_1 \frac{A_2}{A_1}
   \end{align*}
   Arbeit:
   \begin{align*}
   W_1 &= F_1 a_1 = p A_1 a_1 = p V \\
   W_2 = F_2 a_2 = p A_2 a_2 = pV
   \end{align*}
   Bisher: Vernachlässigung der Schwerkraft. \\
   Jetzt: Druck im Schwerefeld.

   Eigengewicht einer Flüssigkeit verursacht einen von der Tiefe abhängenden Druck.
   Kraftwirkung auch Fläche $A$:
   \begin{align*}
   F &= m g = \rho V g = \rho A h g \\
   \intertext{mit Tiefe $h$}
   p = \frac{F}{A} = \rho g h
   \end{align*}
   #+ATTR_LATEX: :options [Hydrostatischer Druck]
   #+begin_defn latex
   Der Druck in einer ruhenden, inkompressiblen Flüssigkeit nimmt unter Einfluss der
   Schwerkraft linear mit der Tiefe $h$ zu:
   \[p = p_0 + \rho g h\]
   Der Hydrostatische Druck ist unabhängig von Form und Volumen
   des einschließenden Behältnisses
   #+end_defn
   Anwendung: Quecksilberbarometer
   \begin{align*}
   p_{Luft} + \rho g x &= \rho g h + \rho g x \\
   p_{Luft} &= \rho g h \\
   \end{align*}
   Druckeinheit: $\SI{1}{\milli\meter}\,\text{Hg}~= \SI{133.322}{\pascal}$
*** Auftrieb
	Erfahrung: Ein in eine Flüssigkeit eingetauchter Körper erfährt Auftrieb. \\
	Grund: Auf Körper einwirkende Druckkräfte.
	#+ATTR_LATEX: :options [Prinzip des Archimedes]
	#+begin_thm latex
	Ein Körper, der in eine Flüssigkeit eingetaucht ist
	erfährt eine Auftriebskraft, deren Betrag gleich der
	Gewichtskraft der verdrängten Flüssigkeit ist.
	#+end_thm
	\begin{align*}
	p_1 &= \rho g x_1 + p_0 \\
	p_2 = \rho g x_2 + p_0 \\
	E_1 = \rho g x_1 A + p_0 A \\
	E_2 = \rho g x_2 A + p_0 A \\
	F_2 - F_1 = \rho g A \Delta x = m g = F_g
	\end{align*}

	Es folgt: Ein Körper schwimmt, wenn seine Dichte kleiner ist als
	die Flüssigkeit, in die er eingetaucht ist.
*** Oberflächenspannung
	Beobachtung: Flüssigkeiten bilden Oberflächen. \\
	Grund: Potentielle Energie an Oberfläche größer. \\
	Im Inneren: Kräftegleichgewicht \\
	An Oberfläche: Kraftwirkung nach Inneren \\
	Minimierung der potentiellen Energie $\implies$ Minimierung der Oberfläche.
	#+ATTR_LATEX: :options [Oberflächenspannung]
	#+begin_defn latex
	\[\sigma = \frac{\text{Zunahme der Oberflächenenergie}}{\text{Zunahme der Oberfläche}}\]
	Achtung: Anders als Zugspannung. Hier: Kraft pro Länge
	#+end_defn

** Gase
   Wesentlicher Unterschied zu Festkörpern und Flüssigkeiten: Hohe Kompressibilität.
   #+ATTR_LATEX: :options [Gesetz von Boyle-Mariette]
   #+begin_defn latex
   \[p V = ~\text{const}\]
   falls Temperatur $T = ~\text{const}$, siehe später
   #+end_defn
*** Barometrische Höhenformel:
	Flüssigkeiten: $p = \rho g h + p_0$, das heißt Druck steigt linear mit der Tiefe. (Ausnahme: Inkompressibilität, also $\rho =~\text{const}$, das heißt Druck steigt linear mit der Tiefe. (Ausnahme: Inkompressibilität, also $\rho =~\text{const}$)) \\
	Gase: Hohe Kompressibilität! Das heißt Dichteänderungen müssen berücksichtigt werden. \\
	Frage: $p(h) = ?, \rho(h) = ?$ \\
	Es gilt:
	\begin{align*}
	p V &=~\text{const} \\
	p V &= p \frac{M}{\rho} = p_0 V_0 = p_0 \frac{M}{\rho_0} \\
	\intertext{für konstante Masse $M$:}
	\frac{p}{\rho} &= \frac{p_0}{\rho_0}
	\d p &= -\rho g\d h - p \frac{\rho_0}{p_0} g\d h \\
	\frac{\d p}{p} &= -\frac{\rho_0 g}{p_0} \d h \\
	\ln{p} - \ln{p_0} &= -\frac{\rho_0 g}{p_0} h \\
	p &= p_0 \exp{(-\frac{\rho_0 g h}{p_0})} \\
	\intertext{Barometrische Höhenformel:}
	p(h) &= p_0 \exp(-\frac{\rho_0 g}{p_0} h)
	\end{align*}
	das heißt: in Atmosphäre mit kompressiblem Gas nimmt der Druck mit der Höhe exponentiell ab.
** Strömende Flüssigkeiten und Gase
   Experiment: Flüssigkeitsströmung durch Rohr \\
   Beobachtung: Druckabfall entlang des Rohres \\
   \begin{align*}
   F_p &= A(p(x) - p(x + \Delta x)) \\
   &=  -\dd{p}{x} \Delta A \\
   &= -\dd{p}{x}\Delta V \\
   &= -\frac{\Delta p}{\Delta x}\Delta V \\
   F_p &= -F_{visc} \\
   F\Delta x &= -\Delta p \Delta V \\
   F &= -\grad p \Delta v \\
   \end{align*}
   - $\v F_p$: Kraft aufgrund des Druckgradienten
   - $\v F_{visc}$: Kraft aufgrund innerer Reibung
   Also: Bei der Strömung von Flüssigkeiten muss Arbeit gegen die innere Reibung aufgebracht werden
   Es gilt
   \[F\Delta x = -\Delta p \Delta V, F\d x = -\d p \Delta V\]
   Eigentlich ist das ganze deutlich komplizierter:
   \begin{align*}
   \v u (x,y,z,t) \tag{Geschwindigkeitsfeld} \\
   p(x,y,z,t) \tag{Druckfeld} \\
   \rho(x,y,z,t) \tag{Dichtefeld} \\
   \d m \dd{\v u}{t} = \v F_p + \v F_{visc} + \v F_{ext} \\
   \intertext{Navier-Stokes-Gleichung}
   \rho(\frac{\partial}{\partial t} + \v u \ v v) \v u = -\underarrow[\grad p]{"$F_p$"} + \rho \underarrow[\v g]{"$F_{ext}$"} + \underarrow[\eta \Delta \v n]{"$F_{visc}$"} \\
   \end{align*}
*** Kontinuitätsgleichung:
	\begin{align*}
	\phi &= \frac{\Delta m}{\Delta t} = ~\text{const} \\
	\phi &= \frac{\Delta m}{\Delta t} = \frac{\rho A_i \Delta x}{\Delta t} \\
	&= \rho A_i v_i \\
	\rho A_1 v_1 &= \rho A_2 v_2 \\
	A_1 v_1 &= A_2 v_2 \\
	W &= F \Delta x = - \Delta p \Delta V = \frac{1}{2} \Delta m(v_2^2 - v_1^2) + \Delta mg(h_2 - h_1) \\
	-\Delta p &= \frac{1}{2} \rho v_2^2 - \frac{1}{2} \rho v_1^2 + \rho gh_2 - \rho gh_1 \\
	p_1- p_2 &= \ldots \\
	p_1 + \frac{1}{2} \rho v_1^2 + \rho g h_1 = p_2 \frac{1}{2} \rho v_2^2 + \rho g h_2 \\
	\end{align*}
	#+ATTR_LATEX: :options [Bernoullische Gleichung]
	#+begin_defn latex
	\[p + \frac{1}{2} \rho v^2 + \rho g h = ~\text{const}\]
	#+end_defn
*** Reibung in Flüssigkeiten
	Merke für Flüssigkeiten keine statischen Scherkräfte, aber es gibt dynamische Scherkräfte. \\
	Experiment: Notwendige Schubspannung
	\[\tau = \frac{F}{A} \sim \dd{v_x}{y}\]
	Schubspannung ist proportional zum Geschwindigkeitsgradienten.
	#+ATTR_LATEX: :options [Newtonsches Reibungsgesetz:]
	#+begin_defn latex
	\[\tau = \frac{F_R}{A} = \eta \dd{v_x}{y}\]
	\[F_R = \eta A \dd{v_x}{y}\]
	$\eta$ nennt man dynamische Scherviskosität.
	#+end_defn
*** Strömung durch ein Rohr mit kreisförmigen Querschnitt (Hagen-Poiseuille)
	\begin{align*}
	\Delta p &= p_2 - p_1 \\
	F &= \Delta \pi r^2 \\
	A &= 2\pi r L \\
	\tau &= \frac{F}{A} = \frac{\Delta p \pi r^2}{2\pi r L} = -\eta \dd{v}{r} \tag{Newton!} \\
	v(r) &= \int_{v(r)}^{v(R) = 0}- \d v = \int_{r}^{R} \frac{\Delta p r}{2 \eta L} \d r = \frac{\Delta p}{4 \eta L}(R^2 - r^2)a \\
	\d V &= 2\pi r \d r v(r) \Delta t \\
	\Delta V &= \int_{0}^{R}2\pi r \d r v(r) \Delta t \\
	&= \frac{2\pi \Delta p}{2\eta L}\Delta t \int_{0}^{R}(R^2 r - r^3) \d r \\
	&= \frac{2\pi \Delta p}{2\eta L}(\frac{1}{4} R^4 - \frac{1}{4} R^4) \Delta t \\
	\dot{V} &= \dd{v}{t} = \frac{\pi \Delta p}{8\eta L} R^4 \sim R^4 \tag{Hagen-Poiseuille-Gesetz}
	\bar v = \frac{\dot{V}}{A} = \frac{A \Delta x}{A \Delta t} = \dd{V}{t} \frac{1}{\pi R^2} = \frac{R^2}{8\eta L}\Delta p \\
	\bar v \sim \Delta p ~\text{typisch für laminare Strömung} \\
	\end{align*}

	Turbulenz:
	$\Delta p \sim \bar v^2$

	Vergleich:
	| Stationäre laminare Strömung | Turbulente Strömung                 |
	|------------------------------+-------------------------------------|
	| $\dot{v} = \dd{\v v}{t} = 0$ | $\v v = \v v(x,y,z,t)$              |
	| Stromflächen                 | keine Vorhersage der Teilchenbahnen |
	| $F_R \sim \v v$              | $F_W \sim \bar v^2$                 |

	Reynold-Kriterium:
	\begin{align*}
	R_e < R_{e_{krit}} \tag{laminar} \\
	R_e > R_{e_{krit}} \tag{turbulent}
	\end{align*}
	#+begin_ex latex
	Für ein rundes Rohr mit Radius $R$ gilt:
	\[R_e = \frac{2\rho \bar v R}{\eta}, R_{e_{krit}} = 2000 - 2300\]
	#+end_ex
*** Strömungswiderstand von glatten Körper
	Frage: Welche Kraft wird auf einem Körper ausgeübt, der sich mit Geschwindigkeit $v$ durch
	eine Flüssigkeit bewegt?
	1. Laminare Strömung: $F_N \sim v$
	   #+ATTR_LATEX: :options [Gesetz von Stokes]
 	   #+begin_defn latex
	   Strömungswiderstand einer Kugel
	   \[F_W = F_R = 6\pi \eta r v\]
	   #+end_defn
	   Gesetz von Stokes wichtig für die gesamte Naturwissenschaft! (Sedimentation, Staubteilchen, Milikanversuch...)
	2. Turbulente Strömung: $F_N \sim v^2$
	   Qualitativer Beweis: Teilchen, die mit der Strömungsgeschwindigkeit $\v v_K$ auf den
	   Körper mit Konturfläche $A$ auftreffen, werde im Staupunkt gebremst. Dadurch steigt der Druck
	   $p_0$ um $\Delta p$. Hinter dem Körper werden die Teilchen in eine turbulente Strömung
	   überführt. Deren Geschwindigkeit entspricht ungefähr der Strömungsgeschwindigkeit $v_k$,
	   weshalb der Druck hinter dem Körper wieder auf dem alten Druck $p_0$ absinkt. Die
	   Druckdifferenz zwischen Vorder- und Rückseite des Körpers gibt den Druckwiderstand. Es
	   gilt dann:
	   - Strömung ungestört: $p_0 + \frac{1}{2}\rho \v v_k^2$
	   - Druck vor dem Körper: $p_0 + \Delta p$
	   - Druck hinter dem Körper: $p_0 + \frac{1}{2}\rho \overline{\v v^2}$
	   - $\implies F_W \approx A \Delta p = A \frac{1}{2} \rho \v v_K^2 = A \frac{1}{2} \rho \overline{\v v^2}$
	Strömungswiderstand = Staudruck $\times$ Konturfläche!! \\
	Aber: Der Strömungswiderstand hängt auch von der Form des Körpers ab. $\implies$ Einführung
	des "$c_W$ -Wertes" für quantitative Beschreibung:
	\[F_W = v_W \frac{1}{2}\rho v^2 A\]
