#+AUTHOR: Robin Heinemann
#+TITLE: Experimentalphysik (H.-C. Schulz-Coulon)
#+INCLUDE: "../header.org" :minlevel 1

#+begin_export latex
\catcode`(=12
\catcode`)=12
#+end_export
\begin{tikzpicture}[every node/.style={draw,outer sep=0pt,thick}]
\tikzstyle{spring}=[thick,decorate,decoration={zigzag,pre length=0.3cm,post length=0.3cm,segment length=6}]
\tikzstyle{damper}=[thick,decoration={markings,
mark connection node=dmp,
mark=at position 0.5 with
{
\node (dmp) [thick,inner sep=0pt,transform shape,rotate=-90,minimum width=15pt,minimum height=3pt,draw=none] {};
\draw [thick] ($(dmp.north east)+(2pt,0)$) -- (dmp.south east) -- (dmp.south west) -- ($(dmp.north west)+(2pt,0)$);
\draw [thick] ($(dmp.north)+(0,-5pt)$) -- ($(dmp.north)+(0,5pt)$);
}
}, decorate]
\tikzstyle{ground}=[fill,pattern=north east lines,draw=none,minimum width=0.75cm,minimum height=0.3cm]


\node (M) [minimum width=3.5cm,minimum height=2cm] {mass, $m$};

\node (ground1) at (M.south) [ground,yshift=-1.5cm,xshift=-1.25cm,anchor=north] {};
\draw (ground1.north west) -- (ground1.north east);
\draw [spring] (ground1.north) -- ($(M.south east)!(ground1.north)!(M.south west)$);

\node (ground2) at (M.south) [ground,yshift=-1.5cm,anchor=north] {};
\draw (ground2.north west) -- (ground2.north east);
\draw [damper] (ground2.north) -- ($(M.south east)!(ground2.north)!(M.south west)$);

\node (ground3) at (M.south) [ground,yshift=-1.5cm,xshift=1.25cm,anchor=north] {};
\draw (ground3.north west) -- (ground3.north east);
\draw [spring] (ground3.north) -- ($(M.south east)!(ground3.north)!(M.south west)$);

\draw [-latex,ultra thick] (M.north) ++(0,0.2cm) -- +(0,1cm);

\begin{scope}[xshift=7cm]
\node (M) [minimum width=1cm, minimum height=2.5cm] {$m$};

\node (ground) [ground,anchor=north,yshift=-0.25cm,minimum width=1.5cm] at (M.south) {};
\draw (ground.north east) -- (ground.north west);
\draw [thick] (M.south west) ++ (0.2cm,-0.125cm) circle (0.125cm)  (M.south east) ++ (-0.2cm,-0.125cm) circle (0.125cm);

\node (wall) [ground, rotate=-90, minimum width=3cm,yshift=-3cm] {};
\draw (wall.north east) -- (wall.north west);

\draw [spring] (wall.170) -- ($(M.north west)!(wall.170)!(M.south west)$);
\draw [damper] (wall.10) -- ($(M.north west)!(wall.10)!(M.south west)$);

\draw [-latex,ultra thick] (M.east) ++ (0.2cm,0) -- +(1cm,0);
\end{scope}
\end{tikzpicture}
#+begin_export latex
\catcode`(=12
\catcode`)=12
#+end_export

#+INCLUDE: "introduction.org" :minlevel 1
#+INCLUDE: "mechanics.org" :minlevel 1
#+INCLUDE: "forcelaws.org" :minlevel 1
#+INCLUDE: "work_energy_power.org" :minlevel 1
#+INCLUDE: "conservation_laws.org" :minlevel 1
#+INCLUDE: "system_mass_points.org" :minlevel 1
#+INCLUDE: "collisions.org" :minlevel 1
#+INCLUDE: "ridid_body.org" :minlevel 1
#+INCLUDE: "deformation.org" :minlevel 1
#+INCLUDE: "thermodynamics.org" :minlevel 1
* Transportprozesse
  Nichtgleichgewichtszustände $\implies$ Transport
  - Wärme (Wärmeleitung, Konvektion)
  - Materie (Diffusion, Strömungen)
  - Ladung (Strom)
  Fluß einer physikalischen Größe in Richtung Gleichgewicht
  \begin{align*}
  \intertext{Energiefluß:}
  J_{\frac{E}{a}} &= \dd{E}{t}a \quad j_E = \frac{\d E}{A\d t} \\
  \intertext{Massenfluß:}
  J_m &= \dd{m}{t} \quad j_M = \frac{\d m}{A \d t} \\
  \intertext{Ladungsfluß:}
  J_a &= \dd{Q}{t} \quad j_a = \frac{\d Q}{A\d t}
  \end{align*}
  Allgemein gilt die Kontinuitätsgleichung (1-dim.):
  \[\dd{\rho}{t} + \dd{j}{z} = 0\]
  - $\rho$: Dichte
  - $j$: Stromdichte
  "Beweis:"
  \[\dd{j}{z} = \dd{}{z} \frac{\d m}{A\d t} = \frac{\d}{\d t} \frac{\d m}{\d V} = \dot{\rho}\]
  3-dim:
  \begin{align*}
  \frac{\partial \rho}{\partial t} + \div \dot{\v j} &= 0 \\
  \div \v j &= \frac{\partial}{\partial x} j_x + \frac{\partial}{\partial y} j_y + \frac{\partial}{\partial z} j_z
  \end{align*}
  Außerdem
  \[\v j = \rho \v v\]
  "Beweis:"
  \[j = \frac{\d m}{A \d t} = \underbrace{\frac{\d m}{A\d z}}_{\rho} \underbrace{\dd{z}{t}}_{v}\]
** Wärmetransport
   Beobachtung:
   \[\frac{\Delta T}{\Delta x} = ~\text{const}\]
   Ansatz:
   \[J_{\frac{E}{a}} = -\lambda A \frac{\Delta T}{\Delta x}\]
   #+ATTR_LATEX: :options [Fourisches Gesetz der Wärmeleitung]
   #+begin_thm latex
   1-dim.
   \[j_Q = -\lambda \frac{\d T}{\d x}\]
   3-dim.
   \[\v j_Q = -\lambda \grad T\]
   - $\v j_Q$: Wärmestromdichte
   - $\lambda$: Wärmeleitzahl
   #+end_thm
   #+ATTR_LATEX: :options [Analogie zum Ohmschen Gesetz]
   #+begin_remark latex
   \begin{align*}
   J_Q &= \dd{Q}{t} = \lambda A \frac{\Delta T}{\Delta x} = \Delta T R \\
   R &= \frac{\Delta x}{\lambda A} \implies \Delta T = R J_Q
   \intertext{Elektrizitätslehre:}
   J_Q &\estimates I, \Delta T \estimates U, R = \frac{d}{\sigma A}, U = R I
   \end{align*}
   #+end_remark
   Besseres Verständnis über Diffusion $\ldots$.
** Diffusion
   Materietransport aufgrund eines Konzentrationsgefälles. Hier: Eindimensionale, vereinfachte Betrachtung.

   Bos mit zwei Molekülsorten $A$ und $B$. \\
   Start $t = 0$: Alle Moleküle der Sorte $B$ in $V_1$. \\
   $t\gg 0$: Gleichgewicht. \\

   Betrachte Umgebung um Ebene $E$: \\
   "Nettofluß" = Fluß nach rechts - Fluß nach links = $j_1 - j_2$
   \begin{align*}
   j_1 &= \frac{1}{6} n_1 v \\
   j_2 &= \frac{1}{6} n_2 v \\
   j &= \frac{1}{6} (n_1 - n_2) v
   \end{align*}
   Aber: Allgemein gilt $n = n(x)$. \\
   Frage: Was muss man für
   \[n_{1,2} = n(x_E \pm \frac{1}{2}\Delta x)\]
   einsetzen? \\
   Antwort:
   \[\frac{1}{2}\Delta x = \lambda\]
   wobei $\lambda$ die mittlere freie Weglänge der Molekülsorte $B$ ist, das heißt
   man wählt die Teilchendichten dort, wo die Moleküle nach dem letzten Stoß starten.
   \begin{align*}
   j &= \frac{1}{6}(n(x_E - \frac{1}{2}\Delta x) + n(x_E + \frac{1}{2}\Delta x))v \\
   &= -\frac{1}{6} \dd{n}{x} \Delta x \\
   &= -\frac{\lambda v}{3} \dd{n}{x} = - \frac{\lambda^2}{3\tau}\dd{n}{x} = -D \dd{n}{x} \\
   D &= \frac{\lambda v}{3} = \frac{\lambda^2}{2\tau}
   \end{align*}
   - $\lambda$: mittlere freie Weglänge
   - $\tau$: mittlere Zeit zwischen zwei Stößen
   - $v = \frac{\lambda}{\tau}$: mittlere Geschwindigkeit
   Also:
   #+ATTR_LATEX: :options [1. Ficksches Gesetz]
   #+begin_thm latex
   \begin{align*}
   j_D &= -D \dd{n}{x} \tag{1-dim} \\
   j_D &= -D \grad n \tag{3-dim}
   \end{align*}
   #+end_thm
   Vergleich:
   | Diffusion         | Konzentrationsgradient |
   | Wärmeleitung      | Temperatutrgradient    |
   | laminare Strömung | Druckgradient          |

   Laminare Strömung:
   - Volumenstrom: $\dot{V} = - \frac{\pi \Delta p}{8\eta L} R^4$
   - Stromdichte: $j = \frac{\dot{V}}{A} = \frac{\dot{L}}{\pi R^2} = - \frac{R^2}{8\eta} \frac{\Delta p}{\Delta x}, L = \Delta x$
   - $\implies j = -\xi \dd{p}{x}, \xi = \frac{R^2}{8\eta}$
** Wärmestrahlung
   Wärmetransport im Allgemeinen sehr kompex. Zusätzlich zur Wärmeleitung: Konvektion und Wärmestrahlung.
   Erfahrung: \\
   Auch ohne direkten Kontakt findet Wärmeaustausch von Körpen über thermische Strahlung statt,
   elektormagnetische Strahlung siehe später. \\
   Interessant: \\
   Emissions- und Absoptionsvermögen von Körpern. \\
   Charakterisierungsgrößen:
   | Emission                                                                                 | Absoption                                                                                                                                                                                  |
   |------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
   | $\phi = \dd{Q}{t}$ Strahlungsleistung, $[\phi] = \si{\joule\per\second} = \si{\watt}$    | $I = \frac{\phi}{F}$ Bestrahlungsstärke, Intensität                                                                                                                                        |
   | $E = \frac{\Phi}{F}$ Emissionsvermögen, Intensität, $[E] = \si{\watt\per\meter\squared}$ | $A = \frac{\text{absobierte Strahlungsleistung}}{\text{auffallende Strahlungsleistung}}$ Absoptionsvermögen, $[A] = \si{L}$                                                                |
   | $F_\lambda = \dd{E}{\lambda}$ spektrales Emissionsvermögen                               | $A_\lambda = \frac{\text{absorbierte Strahlungsleistung im Bereich} [\lambda,\lambda + \d \lambda]}{\text{einfallende Strahlungsleistung im Bereich} [\lambda, \lambda + \d \lambda]}$ |
   Es gilt:
   \[E = \int_{0}^{\infty}E_\lambda \d \lambda, A, A_\lambda \leq 1 \wedge R = 1 - A:~\text{Reflexionsvermögen}\]
   #+ATTR_LATEX: :options [Jaresmittelwert der Sonneneinstrahlung der Erde]
   #+begin_ex latex
   Solarkonstante: (merken!)
   \[I_{solar} = \SI{1.37}{\kilo\watt\per\meter\squared} \approx \SI{1}{\kilo\watt\per\meter\squared}\]
   #+end_ex
   Emmsions und Absoptionsvermögen hängen sicherlich von der Art und Beschaffenheit des abstrahlenden/absobierenden Körpers ab. \\
   Experiment: Leslie Würfel. \\
   Messung:
   - $A: T_s > T_b$
   - $B: T_s = T_b$
   Sei
   \begin{align*}
   T_s &= T_0 + \Delta T_s \\
   T_b &= T_0 + \Delta t_b
   \end{align*}
   - $A: \Delta T_s > \Delta T_b$
   - $B: \Delta t_s = \Delta T_b$
   Außerdem:
   \[\Delta T \sim \Delta U \sim \Delta Q \sim EA\]
   Damit ergibt sich aus $B$:
   \[E_s A_b = E_b A_s \implies \frac{E_b}{A_b} = \frac{E_s}{A_s}\]
   Das Verhältnis von Emmisions- und Absoptionsvermögen eines Körpers ist unabhänig von der
   Beschaffenheit seiner Oberfläche. Übliche Referenz: Nicht-reflektierender Körper, auch "schwarzer-Körper" oder "schwarzer" Strahler.
   das heißt
   \[A_\lambda^s = 1\]
   für alle Wellenlängen gleich! \\
   Wichtig: Auch für $A_\lambda = 1$ seindet ein Körper Wärmestrahlung aus, seinen eigene!, das heißt ein schwarzer Körper kann "weiß" sein.

   Technische Realisierung eines schwarzen Strahlers: Hohlraumstrahler. (Da kein Material mit $A_\lambda = 1$ existiert) \\
   Hohlraum mit stark absobierenden Wänden. Reflexionsvermögen der Öffnung verschwindet quasi! $\implies$
   #+ATTR_LATEX: :options [Kirchhoffsches Strahlungsgesetz]
   #+begin_thm latex
   Für alle Körper im thermischen Gleichgewicht gilt:
   \[\frac{E_\lambda (T)}{A_\lambda (T)} = E_\lambda^s (T), A_\lambda^S(T) = 1\]
   das heißt das Verhältnis von spektralem Emissoins- und Absoptionsvermögen ist unabhängig von der
   Oberflächenbeschaffenheit eines Strahlers und gleich dem Emissionsvermögen eines schwarzen Strahlers. (bei gegebener Temperatur)
   Es folgt: Ein schwarzer Strahler hat maximales Emissionsvermögen.
   #+end_thm
   $\implies$ Emissoinsvermögen eines schwarzen Strahlers ist universell! \\
   Experiment: Schwarzer Strahler. \\
   Beobachtung:
   1. Bei höheren Temperaturen wir mehr Energie abgestrahlt
   2. Warme Körper strahlen "unsichtbar" (IR-Strahlung), wärmere "rot", heiße "weiß-blau"
   $\implies$ Mit steigener Temperatur strahlen Körper elektromagnetische Strahlung mit höheren Frequenzen ab $\implies$
   \begin{align*}
   E^{\frac{q}{r}}(T) &= \sigma \qquad E(T) = \eps \sigma T^4 \tag{Stefan-Boltz-mannsches Strahlungsgesetz} \\
   \intertext{Planksches Strahlungsgesetz:}
   E^{\frac{q}{r}}_\lambda(T) &= \frac{2\pi hc^2}{\lambda^5} \frac{1}{e^{\frac{hc}{\lambda kT}} - 1} \\
   E^{SK}_V(T) &= \frac{2\pi hv^3}{c^2} \frac{1}{e^{\frac{hc}{\lambda kT}} - 1}
   \end{align*}
   - $\sigma = \SI{5.7e-8}{\watt\per\meter\squared\per\kelvin\tothe{4}}$: Stafan-Boltzmann-Konstante
   - $\lambda$: Wellenlänge
   - $v$: Frequenz
   - $h$: Plancksches Wirkungsquantum
