* Verschiedene Kräfte und Kraftgesetze
** Gravitation (TODO Skizze)
   Experimenteller Nachweis im Labor mit Torsionsdrehungen (erstmals Cavendish)
*** Anziehungskraft zweier Massen
	$m_1,m_2$ Massen, Newtonsches Gravitationsgesetz:
	\[\v{F_G} = -G\frac{m_1 m_2}{r^2}\v{e_r}\]
	mit $G=\SI{6.67e-11}{\meter\cubed\per\kilo\gram\per\second\squared}$
*** Erdbeschleunigung
	\[F_G = G\frac{m M_E}{(r_E + h)^2} \approx G\frac{m M_E}{r^2} = m g \implies g\approx \SI{9.81}{\meter\per\second\squared}\]
	(mittleres $g$) \\
**** Abweichungen
	 - komplizierte Massenverteilung, Strukturen
	 - Abflachung der Erde
**** Messung von $g$
	 - Gravimeter (Federgravimeter, Pendelgravimeter), relative Messung
	 - Absolutgravimeter (freier Fall, supraleitende Gravimeter)
**** Träge und schwere Masse
	 \[F= m_T a \rightarrow ~\text{träge Masse}\]
	 \[F= m_S G\frac{M_E}{r_E^2} \rightarrow ~\text{schwere Masse}\]
**** Äquivalenzprinzip
	 $m_S \sim m_T$ beziehungsweise $m_S = m_T$
** Federkraft
   Hook'sches Gesetz
   \[F_x = F_x(\Delta x) = -k_F \Delta x\]
   Beliebige Auslenkungsfunktion ($F_x(\Delta x = x - x_0)$)
   \[F_x(x) = F_x(x_0) + \dd{F_x(x)}{x}(x-x_0) + \frac{1}{2}\frac{\d^2 f_x(x)}{\d x^2}(x - x_0) + \ldots\]
   \rightarrow unabhängig von konkreter Zusammenhang $f_x(x)$ gilt kleine Änderungen
** Maxwell'sches Rad
*** Ruhezustand
	Waage misst Gesamtmasse $M$ austarierter
*** Frage
	Was passiert, wenn sich das Rad bewegt??
*** Messung:
	1. Rad fixiert \rightarrow $m = 0$
	2. Rad läuft \rightarrow $\Delta m  = -0.7 g < 0$
*** Auswertung
	Anwendung 3. Newtonsches Gesetz:
	$\v{F_1} + \v{F_2} = m\v a$ beziehungsweise $F_2 = - F_1 + m\v a$
	1. $\v a = 0: \abs{\v{F_2}} = \abs{\v{F_1}} \rightarrow \abs{\v{F_2}} = 0, 0 m = 0$ (Waage)
	2. $\v a > 0: \abs{\v{F_2}} < \abs{\v{F_1}}$ \rightarrow Waage mit $\abs{\v{F_2}} < m g~\Delta{m} < 0$
** Rotierende Kette
   Winkelelement $\Delta \alpha$. Radialkraft $\v{F_r}$ ist resultierende Kraft der vom abgeschnittenen Teil der Kette wirkende Kräfte $\v{F_1} + \v{F_2}$ \\
   ($\v{F_G}$ vernachlässigbar klein bei hoher Umdrehung und somit großen $\abs{F_1},\abs{F_2}$) \\
   Es gilt:
   \[\v a_zp = -\frac{v^2}{R}\v e_r\quad \v v = R\omega \v e_t\]
   \[\v{F_r} = \Delta m \v a_zp = -\Delta m \frac{v^2}{R}\v e_r\]
   \[\v{F_r} = \v{F_1} + \v{F_2}\]
   \[F_r \approx \Delta \alpha F = F\frac{\Delta L}{R}\]
   \[F = F_r \frac{R}{\Delta L} = \Delta m \frac{v^2}{R}\frac{R}{\Delta L} = \frac{m}{2\pi R}v^2\]
   Die Kraft $F = \frac{m}{2\pi R}v^2$ spannt die Kette.
** Normalkraft
   1. (Skizze) Normalkraft $\v{F}_N$ = Kraft senkrecht zur Kontaktfläche. Wird kompensiert durch $\v{F}_N'$ = Kraft mit der die Unterlage auf Körper wirkt (Źwangskräfte)
** Schiefe Ebene
   - Gewichtskraft: $\v{F}_G = m\v g$
   - Normalkraft: $\v{F}_N = m g\cos{\alpha} \v{e}_y$
   - Hangabtriebskraft: $\v{F}_H = m g\sin{\alpha} \v{e}_x$
   Bewegungsgleichung
   \[F_H = m\ddot{x} \rightarrow x_x = g\sin{\alpha} =\text{const.}\]
** Reibungskräfte
   - im täglichen Leben über all präsent
   - spielt eine wichtige Rolle Technik
   \rightarrow Tribologie = Reibungslehre
   - Reibung hängt stark von der Oberfläche ab
*** Experiment: Bewegung einer Masse
	 - Gewicht ruhte: $\v{F}_Z = - \v{F}_R \to a = 0, v = 0$
	 - Gewicht setzt sich in Bewegung: $\abs{\v{F}_Z} > \abs{\v{F}_R} \to a > 0,v$ steigt an
	 - Gewicht gleitet: $\v{F}_Z = - \v{R}_R \to a = 0, v =~\text{const.}~\neq 0$ mit $\v v =~\text{const}~$
	 Reibungskraft nimmt ab, sobald das Gewicht bewegt wird.
	 - Haftreibung $F_H$ \\
	   Schwellenwert für Zugkraft um Körper zu bewegen
	 - Gleitreibung $F_G$ \\
	   Reibungskraft bei bewegtem Körper

\begin{tikzpicture}

% horizontal axis
\draw[->] (0,0) -- (6,0) node[anchor=north] {$F_Z$};

% vertical axis
\draw[->] (0,0) -- (0,4) node[anchor=east] {$F_R$};

% Us
\draw[thick] (0,0) -- (2,2) -- (2,1) -- (6,1);
\draw (1,0.25) node {$F_R = F_Z$}; %label

\draw[thick,dashed] (0,2) -- (2,2);
\draw (0.85,2.25) node {$F_H$}; %label

\draw[thick,dashed] (0,1) -- (2,1);
\draw (0.85,1.25) node {$F_G$}; %label

\draw (4,1.25) node {$F_R =~\text{const}$};
\draw (4, 0.75) node {Beschleunigung};

\end{tikzpicture}

*** Experiment: Tribologische Messung
	Messung der Zugkraft bei der sich der Holzblock nach kleiner Störung in Richtung Rolle bewegt: $F_R = F_Z$
**** Beobachtung
	 - $F_R$ hängt nicht von der Oberfläche ab.
	 - $F_R$ hängt von dem Gewicht des Blocks ab
	 - $F_R$ ist Materialabhängig

** Tribologische Reibungslehre
   \[F_G = \mu_G F_N \text{ ($\mu_G=$ Gleitreibungskraft)}\]
   \[F_H = \mu_H F_H \text{ ($\mu_H=$ Haftreibungskraft)}\]
   \[\mu_H > \mu_G\]
** Mikroskopisches Modell
   Verantwortlich sind elektrische Kräfte zwischen Atomen und Molekülen der beieinander liegenden Oberflächen: Van-der-Waals-Kräfte
   - Stärke ergibt sich aus effektivem Kontakt.
   Relative mikroskopische Reibungsfläche: $\sum \frac{a_i}{A} \sim \frac{F_N}{A} \leftarrow~\text{Druck}$
   - $a_1$ = effektive Kontaktfläche eines Einzelatoms
   Also: \[F_R \sim \sum \frac{a_i}{A} \sim F_N\]
   - Haftreibung: Verzahnung der Oberflächen mit minimalen Abstand
   - Gleitreibung: Minimaler Abstand wird auf Grund der Bewegung nicht erreicht
** Schiefe Ebene: Messung der Reibungskraft (Skizze)
   Kräftegleichgewicht: $F_H = F_R$
   \[F_H = m g \sin{\alpha}, F_N = m g \cos{\alpha}\]
   Grenzwinkel: $F_R = m g \sin{\alpha} = \mu_R m g \cos{\alpha} \implies \mu_R = \tan{\alpha}$
   \[\alpha = \SI{15}{\degree} \rightarrow \tan{\alpha} = 0.27,\mu_G = 0.27\]
** Zentripetalkraft
   \[\v a_{Zp} = \v \omega \times(\v\omega\times\v r)\quad \v{F}_{Zp} = m\v\omega\times(\v\omega\times\v r)\]
   \[a_{Zp} = \omega^2 r = \frac{v^2}{r}\quad F_{Zp} = m\omega^2 r = m \frac{v^2}{r}\]
*** Beispiel 1 Rotierendes Pendel
	\[\v{F}_{Zp} := \v{F}_G + \v{F}_Z\]
	\[F_G = m g = F_Z \cos{\theta}\]
	\[F_{Zp} = F_Z \sin{\theta}\]
	\[F_{Zp} = mg \frac{\sin{\theta}}{\cos{\theta}} = m g \tan{\theta},\quad a_{Zp} = g\tan{\theta}\]
	\[a_{Zp} = \omega^2 r \implies \omega = \sqrt{\frac{g}{\tan{\theta}}}\]
	- $\theta$ steigt mit $\omega$ an
	- $\theta(\omega)$ ist unabhängig von Masse
*** Beispiel 2 Geostationärer Satellit
	Zentripetal = Gravitationskraft \\
	\[m\omega^2 R = G\frac{m M_E}{R^2}\]
	Geostationär: $\omega = \frac{2\pi}{\SI{24}{\hour}} = \frac{2\pi}{24\cdot\SI{3600}{\second}} = \SI{7.27e-5}{\per\second}$
	\[R^3 = \frac{G M_E}{\omega^2} \rightarrow R = \SI{42312}{\kilo\meter}\]
	Abstand von der Erd-Oberfläche: \[\tilde{R} = R - R_E = \SI{35930}{\kilo\meter}\]
	- $G = \SI{6.67e-11}{\meter\cubed\per\kilo\gram\second\squared}$
	- $M_E = \SI{6e24}{\kilo\gram}$
	- $R_E = \SI{6373}{\kilo\meter}$
