* Mechanik des starren Körper
  #+ATTR_LATEX: :options [Starrer Körper]
  #+begin_defn latex
  System von Massenpunkten mit festen, nicht veränderlichen Abständen. \\
  Idealisierung!
  #+end_defn
  Es gilt:
  \begin{align*}
  \intertext{Volumen:}
  V = \lim_{\Delta V_i \to 0} \sum \Delta V_i = \int \d v
  \intertext{Masse:}
  M = \lim_{\Delta m_i \to 0} \sum \Delta m_i = \int \d m = \int \rho(\v r) \d V
  \intertext{Schwerpunkt:}
  \v r_s = \frac{1}{M}\int \v r \d m = \frac{1}{M} \int \v r \rho(\v r) \d V
  M = \int \rho \d V = \int \rho \d^3 r
  \end{align*}
  #+ATTR_LATEX: :options [Quader]
  #+begin_ex latex
  \begin{align*}
  \v r_s &= \frac{1}{M} \int \v r \rho(\v r) \d V \\
  &= \frac{1}{M} \int_{0}^{a}\int_{0}^{b}\int_{0}^{c}\cvec{x;y;z} \rho \d x \d y \d z \\
  \intertext{Integration für jede einzelne Ortskomponente:}
  x_s = \frac{1}{m} \int_{0}^{a}\int_{0}^{b}\int_{0}^{c} x \rho \d x \d y \d z = \frac{1}{M} \rho b c \int_{0}^{b} x\d x = \frac{1}{M}\rho a b c \frac{1}{2}a = \frac{1}{2}a \\
  y_s = \ldots = \frac{1}{2}b \\
  z_s = \ldots = \frac{1}{2}c \\
  \v r_s = \frac{1}{2} \cvec{a;b;v}
  \end{align*}
  #+end_ex
** Bewegung des starren Körpers
   Es gilt:
   \begin{align*}
   \v r_{si} = \v r_i - \v r_s \rightarrow \dd{\v r_{si}}{t} = \v v_{si} = \v v_i - \v v_s \\
   \intertext{Mit $\abs{\v r_{si}} =$ const beziehungsweise $\v r_{si}^2 = $ const (starrer Körper)}
   \dd{}{t}(\v r_{si}^2) = 2\v r_{si} \v v_{si} = 0 \rightarrow \v v_{si} \perp \v r_{si}
   \intertext{da $\v v_{si} \perp \v r_{si}$ gilt: Betrachte Bewegung in der von $\v v_{si},\v r_{si}$ aufgespannten Ebene $\rightarrow$ Kreisbewegung!, Das heißt:}
   \v v_{si} = \v \omega \times \v r_{si} \\
   \intertext{wobei im Allgemeinen $\v \omega$ zeitabhängig sein kann.}
   \intertext{Mit $\v v_{si} = \v v_i - \v v_s$ folgt:}
   \v v_i = \v v_s + (\v \omega \times \v r_{si})
   \end{align*}
   Achtung: $\v \omega = \v \omega(t)$ muss nicht raumfest sein.

   Die Bewegung eines starren Körpers lässt sich in eine Translationsbewegung und eine Rotation um den Schwerpunkt zerlegen
   - 3 Translationsfreiheitsgrade
   - 3 Rotationsfreiheitsgrade
** Drehmoment und Kräftepaare
   Frage: Wie versetzt man einen Körper in Rotation? \\
   #+ATTR_LATEX: :options [Balkenwaage]
   #+begin_ex latex
   Beobachtung: Kraft mit Angriffspunkt im Abstand $l$, bewirkt Drehbewegung \\
   Es gilt das Hebelgesetz:
   \[F_1 l_1 = F_2 l_2\]
   Hebelarm: Abstand zwischen Drehachse und Angriffspunkt der Kräfte $\v F_1, \v F_2$
   #+end_ex
   Beobachtung: \\
   Kraft $\v F_\parallel$ parallel zum Hebelarm bewirkt keine Drehung, nur Kraft $\v F_\perp$ senkrecht zur Verbindungslinie zwischen Angriffspunkt und Drehachse führt zur Rotation. \\
   Richtung von $\v F_\perp$ bestimmt Drehsinn

   #+ATTR_LATEX: :options [Drehmoment]
   #+begin_defn latex
   \[\v M := \v r \times \v F\]
   Gibt Drehsinn und Stärke der Kraftwirkung an.
   \[M = r F \sin(\angle (\v r, \v F))\]
   #+end_defn
*** Drehmoment und Schwerpunkt
	Betrachte starren Körper aus zwei Massenpunkten plus masselose Verbindung
	\begin{align*}
	\v M_1 &= \v r_1 \times \v F_1 \\
	\v M_2 &= \v r_2 \times \v F_2 \\
	\v M_1 &= r_1 m_1 g \sin{\alpha_1} \v l_z \\
	\v M_2 &= - r_2 m_2 g \sin{\alpha_2} \v l_z \\
	&= -r_2 m_2 g \sin{\alpha_1} \v l_z \\
	\v M_{tot} &= \v M_1 + \v M_2 = (r_1 m_1 - r_2 m_2) g \sin{\alpha_1} \v l_z \\
	\intertext{vektoriell:}
	\v M_{tot} &= \v M_1 + \v M_2 = \v r_1 \times m_2 \v g + \v r_2 \times m_2 \v g = (\v r_1 m_1 + \v r_2 m_2) \times \v g \\
	\intertext{Beliebiger Körper:}
	\v M_{tot} &= \sum \v M_i = \sum m_i \v r_i \times \v g \\
	(\sum m_i \v r_i) \times \v g = m_{ges} \v r_s \times \v g = \v r_s \times \v F \\
	\end{align*}
	Das Gewicht eines starren Körpers greift immer im Schwerpunkt an.
	Bei Aufhängung eines Körpers im Schwerpunkt ist das resultierende Drehmoment auf Grund der Schwerkraft Null. Grund: Im Schwerpunkt gilt: $\v r_s = 0, \v M_{tot} = \v r_s \times \v F_s = 0$
*** Kräftepaare
	Frage: Wirkung einer Kraft $\v F_1$ auf einen starren Körper. \\
	Lösungsansatz: \\
	Einführung der sich gegenseitig aufgebenden Kräfte $\v F_2$ und $\v F_3$ im Schwerpunkt $S$. Ändert nichts! \\
	Zerlegung der Bewegung: \\
	Translation durch Kraft $\v F_2$ mit Angriffspunkt $S$. \\
	Rotation durch Kräftepaar $(\v F_1, \v F_3)$ mit $F_1 = F_3, \v M = \v r \times \v F_1$

	Die Wirkung aller Kräfte auf einen starren Körper lässt sich durch
	\begin{align*}
	\v F &= \sum \v F_i \tag{Gesamtkraft (Gesamtkraft)} \\
	\v M &= \sum F_{si} \times \v F_i = \sum M_i \tag{Gesamtdrehmoment (Rotation)}
	\end{align*}
	beschreiben. Dabei greift $\v F$ im Schwerpunkt an

	Wirkung von Kräftepaaren: Reine Rotation. Es gilt:

	\[\v M = \v r_1 \times \v F - \v r_2 \times \v F = (\v r_1 - \v r_2)\times \v F = \v r_{12} \times \v F\]


# ** TODO Monday
** Trägheitsmoment
   \[I = \int r^2_\perp \d m = \Theta\]
   \[E_{rot} = \frac{1}{2} I \omega^2\]

** steinersche Satz
   Nochmal Stab:

   \begin{align*}
   I &= \int_0^L x^2 \rho A \d x \\
   &= \rho A \int_0^L x^2 \d x \\
   &= \frac{1}{3}\rho A L^2 \\
   \intertext{mit $m = \rho A L$}
   &= \frac{1}{3} m L^3
   \end{align*}


   Allgemein:
   \begin{align*}
   I &= \int r_\perp^2 \d m \\
   &= \int (r_{s,\perp} + R_\perp)^2 \d m \\
   &= \int \v r_{s,\perp}^2 \d m + \int \v R_{perp}^2 \d m + 2\int r_{s,\perp} R_{perp} \d m
   &= \underbrace{\v r_{s,\perp}^2 \int  \d m}_{ = r_{s,\perp}^2 m} + I_s +  2r_{s,\perp} \underbrace{\int R_{perp} \d m}_{ = 0}
   \end{align*}

   #+ATTR_LATEX: :options [Steinersche Satz]
   #+begin_defn latex
   \[I = I_s + r_{\perp,s}^2 m\]
   #+end_defn
   #+ATTR_LATEX: :options [Dünner Stab]
   #+begin_ex latex
   \begin{align*}
   I_A &= \frac{1}{12} m L^2 \\
   I_B  &= \frac{1}{3} m L^2 \\
   I_B &= I_A + (\frac{L}{2})^2 m = \frac{1}{3} m L^2 \\
   \end{align*}
   #+end_ex

   Trägheitsmomente sind additiv

   \[I = \int_v r_{\perp}^2 \d m = \int_{v_1} r_{\perp}^2 \d m + \int_{v_2} r_{\perp}^2 \d m\]

   | Translation                                 | Rotation                                          |
   |---------------------------------------------+---------------------------------------------------|
   | $\v r$                                      | $\v \phi$                                         |
   | $\v v = \dot{\v r}$                         | $\v \omega = \dot{\v \phi}$                       |
   | $\v a = \ddot{\v r}$                        | $\v \alpha = \ddot{\v \phi} = \dot{\v \omega}$    |
   | $\displaystyle E_{kin} = \frac{1}{2} m v^2$ | $\displaystyle E_{rot} = \frac{1}{2} I \omega^2$ |
   | $F = m\v a$                                 | $\v M = I \v \alpha$                              |

   Bei nicht ortsfester Rotationsachse:
   \[E_{rot} = \frac{1}{2} \v \omega^{T} \Theta \v \omega\]
   \[\v M = \Theta \v \alpha\]
   $\v \Theta$ ist ein Tensor

   \begin{align*}
   \v v_i &= \v \omega \times \v r_{\perp, i}, \v v_i = \omega r_{\perp,i} \\
   \v M &= \v r_{\perp,i} \times \v F_i \\
   M_i &= r_{\perp, i} F_{\perp, i} =  r_{\perp, i} m_i \dd{r_i}{t} \\
   &= r_{\perp,i}^2 m_i \dd{\omega}{t} \\
   M_{tot} &= \sum M_i \\
   M_{tot} &= \underbrace{\dd{\omega}{t}}_{\alpha} \underbrace{\sum r_{\perp,i}^2 mi}_{I} \\
   \intertext{Bewegungsgleichung für die Rotation um eine Raumfeste Achse}
   M = I \dot{\omega} = I \alpha
   \end{align*}

   #+begin_ex latex
   \begin{align*}
   M = I \alpha \\
   \v M = \v r \times \v F_G \\
   I = 2m R^2 \\
   \alpha = \frac{M}{I} = \dot{\omega} \\
   \omega = \alpha t + \omega_0 = \alpha t \\
   \phi = \frac{1}{2} \alpha t^2 + \omega_0 t + \phi 0 = \frac{1}{2} \alpha t^2 \\
   2\pi = \frac{1}{2} \alpha T^2 \\
   T^2 = \frac{4 \phi}{\alpha} = 4 \pi \frac{I}{M} \\
   \intertext{wir wollen berechnen}
   T_0^2 = 4\pi \frac{I_0}{M} = (\SI{1.72})^2 \si{\second\squared} \\
   T_1^2 = 4\pi \frac{I_0 + 2 m R^2}{M} = (\SI{5.9})^2 \si{\second\squared} \\
   T_2^2 = 4\pi \frac{I_0 + 2 m \frac{R^2}{4}}{M} = (\SI{3.3})^2 \si{\second\squared} \\
   T_1^2 - T_0^2 = \SI{32}{\second\squared} \\
   T_2^2 - T_0^2 = \SI{8}{\second\squared} \\
   \end{align*}
   #+end_ex
** Drehimpuls
   - Translation: $\v F = m \v a, \v F = \dot{\v p}$
   - Rotation: $\v M = I \v \alpha, \v M = \dot{\v L}$ \rightarrow Drehimpuls
   - Impuls: $p = mv$
   - Drehimpuls: (Guess) $L = I \omega = m r^2 \frac{v}{r} = r m v = r p$

   #+ATTR_LATEX: :options [Drehimpuls]
   #+begin_defn latex
   \[\v L = \v r \times \v p\]
   #+end_defn
   Wichtig: Allen bewegten Masenpunkten kann man bezüglich eines Referenzpunktes $0$ einen Drehimpuls zuordnen; der hängt vom Bezugspunkt ab.

   \[\dot{\v L} = \dd{}{t} (\v r \times \v p) = \underbrace{\dot{\v r} \times \v p}_{0} + \v r \times \dot{\v p} = \v r \times \v F = \v M\]

   Grundgleichung der Dynamik für Rotationsbewegungen:
   \[\v M = \dd{\v L}{t} = \dot{\v L}\]

   Drehimpulserhaltung:
   \[\v M = 0 \rightarrow \v L = ~\text{const}\]

   Drehimpuls für System von Massenpunkten
   \begin{align*}
   \v p_s = \sum \v p_i, \dot{\v p_s} = \sum \v F_i \\
   \v L = \sum \v L_i = \sum m_i (\v r_i \times \v v_i) \\
   \v L = \int \d \v L = \int (\v r \times \v r) \d m
   \dot{\v L} = \dd{}{t} \sum \v r_i \times \v p_i = \underbrace{\sum \dot{\v r_i} \times \v p_i}_{0} + \sum \v r_i \times \dot{\v p_i} = \sum \v M_i = \v M
   \end{align*}

   Für System von Massenpunkten:
   \begin{align*}
   \v M &= \sum \v r_i \times \v F_i = \dot{\v L} \\
   \v L &= 0 ~\text{für}~ \v M = 0
   \end{align*}

   Allgemeiner Zusammenhang:
   \begin{align*}
   \intertext{mit $\hat I$ als Tensor:}
   \v L &= \hat I \v \omega \\
   \v L &= \int \d \v L \\
   \d \v L &= \v r \times \d \v p = \v r \times \v v\d m \\
   &= \d m (\v r \times \v v) = \v r \times (\v \omega \times \v r)
   \intertext{mit $\v a \times (\v b \times \v c) = \v b (\v a \v c) - \v c (\v a \v b)$}
   &= \d m(r^2 \v \omega - \v r (\v \omega \v r)) \\
   \int \d \v L &= \v \omega \int r^2 \d m - \int \v r (\v \omega \v r) \d m
   \end{align*}
