* Mechanik des starren Körper
  #+ATTR_LATEX: :options [Starrer Körper]
  #+begin_defn latex
  System von Massenpunkten mit festen, nicht veränderlichen Abständen. \\
  Idealisierung!
  #+end_defn
  Es gilt:
  \begin{align*}
  \intertext{Volumen:}
  V = \lim_{\Delta V_i \to 0} \sum \Delta V_i = \int \d v
  \intertext{Masse:}
  M = \lim_{\Delta m_i \to 0} \sum \Delta m_i = \int \d m = \int \rho(\v r) \d V
  \intertext{Schwerpunkt:}
  \v r_s = \frac{1}{M}\int \v r \d m = \frac{1}{M} \int \v r \rho(\v r) \d V
  M = \int \rho \d V = \int \rho \d^3 r
  \end{align*}
  #+ATTR_LATEX: :options [Quader]
  #+begin_ex latex
  \begin{align*}
  \v r_s &= \frac{1}{M} \int \v r \rho(\v r) \d V \\
  &= \frac{1}{M} \int_{0}^{a}\int_{0}^{b}\int_{0}^{c}\cvec{x;y;z} \rho \d x \d y \d z \\
  \intertext{Integration für jede einzelne Ortskomponente:}
  x_s = \frac{1}{m} \int_{0}^{a}\int_{0}^{b}\int_{0}^{c} x \rho \d x \d y \d z = \frac{1}{M} \rho b c \int_{0}^{b} x\d x = \frac{1}{M}\rho a b c \frac{1}{2}a = \frac{1}{2}a \\
  y_s = \ldots = \frac{1}{2}b \\
  z_s = \ldots = \frac{1}{2}c \\
  \v r_s = \frac{1}{2} \cvec{a;b;v}
  \end{align*}
  #+end_ex
** Bewegung des starren Körpers
   Es gilt:
   \begin{align*}
   \v r_{si} = \v r_i - \v r_s \rightarrow \dd{\v r_{si}}{t} = \v v_{si} = \v v_i - \v v_s \\
   \intertext{Mit $\abs{\v r_{si}} =$ const beziehungsweise $\v r_{si}^2 = $ const (starrer Körper)}
   \dd{}{t}(\v r_{si}^2) = 2\v r_{si} \v v_{si} = 0 \rightarrow \v v_{si} \perp \v r_{si}
   \intertext{da $\v v_{si} \perp \v r_{si}$ gilt: Betrachte Bewegung in der von $\v v_{si},\v r_{si}$ aufgespannten Ebene $\rightarrow$ Kreisbewegung!, Das heißt:}
   \v v_{si} = \v \omega \times \v r_{si} \\
   \intertext{wobei im Allgemeinen $\v \omega$ zeitabhängig sein kann.}
   \intertext{Mit $\v v_{si} = \v v_i - \v v_s$ folgt:}
   \v v_i = \v v_s + (\v \omega \times \v r_{si})
   \end{align*}
   Achtung: $\v \omega = \v \omega(t)$ muss nicht raumfest sein.

   Die Bewegung eines starren Körpers lässt sich in eine Translationsbewegung und eine Rotation um den Schwerpunkt zerlegen
   - 3 Translationsfreiheitsgrade
   - 3 Rotationsfreiheitsgrade
** Drehmoment und Kräftepaare
   Frage: Wie versetzt man einen Körper in Rotation? \\
   #+ATTR_LATEX: :options [Balkenwaage]
   #+begin_ex latex
   Beobachtung: Kraft mit Angriffspunkt im Abstand $l$, bewirkt Drehbewegung \\
   Es gilt das Hebelgesetz:
   \[F_1 l_1 = F_2 l_2\]
   Hebelarm: Abstand zwischen Drehachse und Angriffspunkt der Kräfte $\v F_1, \v F_2$
   #+end_ex
   Beobachtung: \\
   Kraft $\v F_\parallel$ parallel zum Hebelarm bewirkt keine Drehung, nur Kraft $\v F_\perp$ senkrecht zur Verbindungslinie zwischen Angriffspunkt und Drehachse führt zur Rotation. \\
   Richtung von $\v F_\perp$ bestimmt Drehsinn

   #+ATTR_LATEX: :options [Drehmoment]
   #+begin_defn latex
   \[\v M := \v r \times \v F\]
   Gibt Drehsinn und Stärke der Kraftwirkung an.
   \[M = r F \sin(\angle (\v r, \v F))\]
   #+end_defn
*** Drehmoment und Schwerpunkt
	Betrachte starren Körper aus zwei Massenpunkten plus masselose Verbindung
	\begin{align*}
	\v M_1 &= \v r_1 \times \v F_1 \\
	\v M_2 &= \v r_2 \times \v F_2 \\
	\v M_1 &= r_1 m_1 g \sin{\alpha_1} \v l_z \\
	\v M_2 &= - r_2 m_2 g \sin{\alpha_2} \v l_z \\
	&= -r_2 m_2 g \sin{\alpha_1} \v l_z \\
	\v M_{tot} &= \v M_1 + \v M_2 = (r_1 m_1 - r_2 m_2) g \sin{\alpha_1} \v l_z \\
	\intertext{vektoriell:}
	\v M_{tot} &= \v M_1 + \v M_2 = \v r_1 \times m_2 \v g + \v r_2 \times m_2 \v g = (\v r_1 m_1 + \v r_2 m_2) \times \v g \\
	\intertext{Beliebiger Körper:}
	\v M_{tot} &= \sum \v M_i = \sum m_i \v r_i \times \v g \\
	(\sum m_i \v r_i) \times \v g = m_{ges} \v r_s \times \v g = \v r_s \times \v F \\
	\end{align*}
	Das Gewicht eines starren Körpers greift immer im Schwerpunkt an.
	Bei Aufhängung eines Körpers im Schwerpunkt ist das resultierende Drehmoment auf Grund der Schwerkraft Null. Grund: Im Schwerpunkt gilt: $\v r_s = 0, \v M_{tot} = \v r_s \times \v F_s = 0$
*** Kräftepaare
	Frage: Wirkung einer Kraft $\v F_1$ auf einen starren Körper. \\
	Lösungsansatz: \\
	Einführung der sich gegenseitig aufgebenden Kräfte $\v F_2$ und $\v F_3$ im Schwerpunkt $S$. Ändert nichts! \\
	Zerlegung der Bewegung: \\
	Translation durch Kraft $\v F_2$ mit Angriffspunkt $S$. \\
	Rotation durch Kräftepaar $(\v F_1, \v F_3)$ mit $F_1 = F_3, \v M = \v r \times \v F_1$

	Die Wirkung aller Kräfte auf einen starren Körper lässt sich durch
	\begin{align*}
	\v F &= \sum \v F_i \tag{Gesamtkraft (Gesamtkraft)} \\
	\v M &= \sum F_{si} \times \v F_i = \sum M_i \tag{Gesamtdrehmoment (Rotation)}
	\end{align*}
	beschreiben. Dabei greift $\v F$ im Schwerpunkt an

	Wirkung von Kräftepaaren: Reine Rotation. Es gilt:
	\[\v M = \v r_1 \times \v F - \v r_2 \times \v F = (\v r_1 - \v r_2)\times \v F = \v r_{12} \times \v F\]
	Merke:
	Das Drehmoment eines Kräftepaares ist unabhängig vom Bezugspunkt $0$ \\
	Zwei Kräftepaare sind äquivalent, wenn sie das gleiche Drehmoment besitzen. Äquivalente Kräftepaare können einander ersetzen.
** Statisches Gleichgewicht
   Statik:
   \[\v F = \sum \v F_i = 0, \v M = \sum \v M_i = 0\]
   das heißt keine Translation, keine Rotation
   #+begin_ex latex
   \mbox{}
   1. Gleichgewicht eines starren Körpers in Schwerefeld \\
	 Frage: Wo muss $\v F$ angreifen um für statisches Gleichgewicht zu sorgen? \\
	 Kräfte:
	 \begin{align*}
	 \sum \v F_i + \v F = 0 \\
	 \v F = - \sum m_i \v g = - m_{ges} \v g \\
	 \end{align*}
	 Drehmomente:
	 \begin{align*}
	 \sum \v M_i + \v R \times \v F = 0 \\
	 \sum \v r_i \times \v F_i + \v R \times \v F = \sum m_i (\v r_i \times \v g) + \v R \times \v F \\
	 = (\sum m_i \v r_i) \times \v g - m_{ges} \v R \times \v G \\
	 = m_{ges} (\v R \times \v g) = m_{ges} (\v r_s \times \v g)
	 \end{align*}
	 Lösung A: $\v R = \v r_s$, das heißt Unterstützung im Schwerpunkt mit $\v F = - m{ges} \v g$ \\
	 Lösung B: $(\v R - \v f_s) \times \v g = 0$, das heißt $(\v R - \v r_s) \parallel \v g$, also Unterstützung oberhalb oder unterhalb des Schwerpunkt
	 3 Möglichkeiten:
	  - $\v R$ über Schwerpunkt: stabiles Gleichgewicht
	  - $\v R$ unter SP: labiles Gleichgewicht
	  - $\v R$ in PS: indifferentes Gleichgewicht
   2. Schiefer Turm \\
	  Drehmoment:
	  \[F_g r = F_z r \rightarrow F_g = F_z\]
	  Kräftegleichgewicht:
	  \[F_g + F_z + F_s = 0 \rightarrow F_s = -2F_g\]
   3. Stehende Leiter \\
	  Kräftegleichgewicht:
	  \[\v F_N = - \v F_G, \v F_N' = -\v F_R\]
	  Drehmomente: \\
	  Bezugspunkt = unteres Leiter-Ende (günstige Wahl!) \\
	  \[F_W h = F_g (\frac{1}{2} a)\]
	  (vergleiche Übungsaufgabe)
   #+end_ex
** Rotation und Trägheitsmoment
   Bewegungsenergie eines starren Körpers setzt sich zusammen aus:
   - kinetischer Energie der Schwerpunktsbewegung
   - kinetische Energie aufgrund von Rotation
   Experiment: Rollende Objekte $\rightarrow Form des Körpers wichtig!$ \\
   Mathematisch:
   \begin{align*}
   E_{kin} &= \sum \frac{1}{2} m_i \v v_i^2 \tag{mit $\v v_i = \v v_s + \v v_{si}$} \\
   E_{kin} &= \frac{1}{2} \sum m_i (\v v_s^2 + 2\v v_s \v v_{si} + \v v_{si} + \v v_{si}^2) \\
   &= \frac{1}{2} \sum m_i \v v_s^2 + \v v_s \sum m_i \v v_{si} + \frac{1}{2} \sum m_i \v v_{si}^2 \\
   \end{align*}
   Die kinetische Energie zerlegt sich in die kinetische Energie des Schwerpunktes und Rotationsenergie, aus der kinetischen Energie der Bewegung relativ zum Schwerpunkt

   Jetzt: Betrachte Rotation um raumfeste Achse: (Spezialfall: Achse durch Schwerpunkt) \\
   Kinetische Energie des Massenstücks $\d m$:
   \begin{align*}
   \d E_{kin} &= \frac{1}{2} \d m \v v_i^2 = \frac{1}{2} \d m (\omega r_{\perp})^2 \\
   &= \frac{1}{2} \d m \omega^2 r_\perp^2 \\
   E_{rot} &= \int \d E_{kin} = \frac{1}{2} \int \omega^2 r_{\perp}^2 \d m = \frac{1}{2} \omega^2 \underbrace{\int r_\perp^2 \d m}_{\text{Trägheitsmoment}}
   \end{align*}


   #+ATTR_LATEX: :options [Trägheitsmoment]
   #+begin_defn latex
   Trägheitsmoment bezüglich einer raumfesten Achse
   \[I = \int r_{\perp}^2 \d m = \Theta^2 \d m = \Theta\]
   Diskret:
   \[\Theta = \sum r_{\perp,i}^2 m_i\]
   Dabei ist $r_\perp$ der Abstand zwischen dem Massenstück $\d m$  und der Drehachse.
   #+end_defn
   #+ATTR_LATEX: :options [Rotationsenergie]
   #+begin_defn latex
   Rotationsenergie eines starren Rotators (Rotation um raumfeste Achse)
   \[E_{rot} = \frac{1}{2} I \omega^2\]
   #+end_defn

** Berechnung von Trägheitsmoment
   Volumenintegral:
   \[I = \int r_\perp^2 \d m = \int r_{\perp}^2 \rho(\v r) \d V\]
   #+begin_ex latex
   1. Stab (dünn)
	  \begin{align*}
	  I &= \int_{-\frac{L}{2}}^{\frac{L}{2}} x^2 \rho A \d x = \rho A \int_{-\frac{L}{2}}^{\frac{L}{2}} x^2 \d x \\
	  &= \frac{1}{3} \rho A ((\frac{L}{2})^3 - (- \frac{L}{2})^3) \\
	  &= \frac{1}{3} \rho A \frac{L^3}{4} = \frac{1}{12} \rho AL L^2 \\
	  &= \frac{1}{12} m L^2
	  \end{align*}
   2. Scheibe, Zylinder
	  \begin{align*}
	  \intertext{Zylinderkoordinaten:}
	  x &= r \cos{\phi}, y = r\sin{\phi}, z = z \\
	  \d V &= r\d \phi \d r \d z \\
	  I &= \int_V \v r_\perp^2 \d m = \int_v r_\perp^2 \rho \d V \\
	  \intertext{Zylinderkoordinaten, also $r_\perp = r$}
	  &= \rho \int_v r^2 r \d r \d \phi \d z \\
	  &= \rho \int_{0}^{R} \int_{0}^{2\pi}\int_{0}^{h} r^2 r \d r \d \phi \d z \\
	  &= 2\pi \rho h \int_{0}^{R} r^3 \d r = 2 \pi \rho h \frac{1}{4} R^4 = \frac{1}{2} (\pi R^2 h) \rho R^2 = \frac{1}{2} m R^2 \\
	  \end{align*}
   3. Dünner Hohlzylinder
	  \begin{align*}
	  I &= \rho \int_{R}^{R + d} \int_{0}^{2\pi} \int_{0}^{h} r^2 r \d r \d \phi \d z \\
	  &= 2\pi \rho h \int_{R}^{R + d} r^3 \d r = 2\pi \rho h \frac{1}{4} \Big[ r^4 \Big]_R^{R + d} \\
	  &= 2\pi \rho h \frac{1}{4} ((R + d)^4 - R^4) \\
	  &= 2\pi \rho h \frac{1}{4} (R^4 + 4 R^3 d + \ldots - R^4) \\
	  &\approx 2\pi \rho h R^3 d = (2 \pi Rdh \rho)R^2 = mR^2 \\
	  \end{align*}
   4. Kugel
	  \[I = \int r_{\perp}^2 \d m = \frac{2}{5} m R^2\]
	  (ohne Beweis,  zur Übung...)
   #+end_ex
** Steinersche Satz
   Nochmal Stab:

   \begin{align*}
   I &= \int_0^L x^2 \rho A \d x \\
   &= \rho A \int_0^L x^2 \d x \\
   &= \frac{1}{3}\rho A L^2 \\
   \intertext{mit $m = \rho A L$}
   &= \frac{1}{3} m L^3
   \end{align*}


   Allgemein:
   \begin{align*}
   I &= \int r_\perp^2 \d m \\
   &= \int (r_{s,\perp} + R_\perp)^2 \d m \\
   &= \int \v r_{s,\perp}^2 \d m + \int \v R_{perp}^2 \d m + 2\int r_{s,\perp} R_{perp} \d m
   &= \underbrace{\v r_{s,\perp}^2 \int  \d m}_{ = r_{s,\perp}^2 m} + I_s +  2r_{s,\perp} \underbrace{\int R_{perp} \d m}_{ = 0}
   \end{align*}

   #+ATTR_LATEX: :options [Steinersche Satz]
   #+begin_defn latex
   \[I = I_s + r_{\perp,s}^2 m\]
   #+end_defn
   #+ATTR_LATEX: :options [Dünner Stab]
   #+begin_ex latex
   \begin{align*}
   I_A &= \frac{1}{12} m L^2 \\
   I_B  &= \frac{1}{3} m L^2 \\
   I_B &= I_A + (\frac{L}{2})^2 m = \frac{1}{3} m L^2 \\
   \end{align*}
   #+end_ex

   Trägheitsmomente sind additiv

   \[I = \int_v r_{\perp}^2 \d m = \int_{v_1} r_{\perp}^2 \d m + \int_{v_2} r_{\perp}^2 \d m\]

   | Translation                                 | Rotation                                          |
   |---------------------------------------------+---------------------------------------------------|
   | $\v r$                                      | $\v \phi$                                         |
   | $\v v = \dot{\v r}$                         | $\v \omega = \dot{\v \phi}$                       |
   | $\v a = \ddot{\v r}$                        | $\v \alpha = \ddot{\v \phi} = \dot{\v \omega}$    |
   | $\displaystyle E_{kin} = \frac{1}{2} m v^2$ | $\displaystyle E_{rot} = \frac{1}{2} I \omega^2$ |
   | $F = m\v a$                                 | $\v M = I \v \alpha$                              |

   Bei nicht ortsfester Rotationsachse:
   \[E_{rot} = \frac{1}{2} \v \omega^{T} \Theta \v \omega\]
   \[\v M = \Theta \v \alpha\]
   $\v \Theta$ ist ein Tensor

   \begin{align*}
   \v v_i &= \v \omega \times \v r_{\perp, i}, \v v_i = \omega r_{\perp,i} \\
   \v M &= \v r_{\perp,i} \times \v F_i \\
   M_i &= r_{\perp, i} F_{\perp, i} =  r_{\perp, i} m_i \dd{r_i}{t} \\
   &= r_{\perp,i}^2 m_i \dd{\omega}{t} \\
   M_{tot} &= \sum M_i \\
   M_{tot} &= \underbrace{\dd{\omega}{t}}_{\alpha} \underbrace{\sum r_{\perp,i}^2 mi}_{I} \\
   \intertext{Bewegungsgleichung für die Rotation um eine Raumfeste Achse}
   M = I \dot{\omega} = I \alpha
   \end{align*}

   #+begin_ex latex
   \begin{align*}
   M = I \alpha \\
   \v M = \v r \times \v F_G \\
   I = 2m R^2 \\
   \alpha = \frac{M}{I} = \dot{\omega} \\
   \omega = \alpha t + \omega_0 = \alpha t \\
   \phi = \frac{1}{2} \alpha t^2 + \omega_0 t + \phi 0 = \frac{1}{2} \alpha t^2 \\
   2\pi = \frac{1}{2} \alpha T^2 \\
   T^2 = \frac{4 \phi}{\alpha} = 4 \pi \frac{I}{M} \\
   \intertext{wir wollen berechnen}
   T_0^2 = 4\pi \frac{I_0}{M} = (\SI{1.72})^2 \si{\second\squared} \\
   T_1^2 = 4\pi \frac{I_0 + 2 m R^2}{M} = (\SI{5.9})^2 \si{\second\squared} \\
   T_2^2 = 4\pi \frac{I_0 + 2 m \frac{R^2}{4}}{M} = (\SI{3.3})^2 \si{\second\squared} \\
   T_1^2 - T_0^2 = \SI{32}{\second\squared} \\
   T_2^2 - T_0^2 = \SI{8}{\second\squared} \\
   \end{align*}
   #+end_ex
** Drehimpuls
   - Translation: $\v F = m \v a, \v F = \dot{\v p}$
   - Rotation: $\v M = I \v \alpha, \v M = \dot{\v L}$ \rightarrow Drehimpuls
   - Impuls: $p = mv$
   - Drehimpuls: (Guess) $L = I \omega = m r^2 \frac{v}{r} = r m v = r p$

   #+ATTR_LATEX: :options [Drehimpuls]
   #+begin_defn latex
   \[\v L = \v r \times \v p\]
   #+end_defn
   Wichtig: Allen bewegten Massenpunkten kann man bezüglich eines Referenzpunkts $0$ einen Drehimpuls zuordnen; der hängt vom Bezugspunkt ab.

   \[\dot{\v L} = \dd{}{t} (\v r \times \v p) = \underbrace{\dot{\v r} \times \v p}_{0} + \v r \times \dot{\v p} = \v r \times \v F = \v M\]

   Grundgleichung der Dynamik für Rotationsbewegungen:
   \[\v M = \dd{\v L}{t} = \dot{\v L}\]

   Drehimpulserhaltung:
   \[\v M = 0 \rightarrow \v L = ~\text{const}\]

   Drehimpuls für System von Massenpunkten
   \begin{align*}
   \v p_s = \sum \v p_i, \dot{\v p_s} = \sum \v F_i \\
   \v L = \sum \v L_i = \sum m_i (\v r_i \times \v v_i) \\
   \v L = \int \d \v L = \int (\v r \times \v r) \d m
   \dot{\v L} = \dd{}{t} \sum \v r_i \times \v p_i = \underbrace{\sum \dot{\v r_i} \times \v p_i}_{0} + \sum \v r_i \times \dot{\v p_i} = \sum \v M_i = \v M
   \end{align*}

   Für System von Massenpunkten:
   \begin{align*}
   \v M &= \sum \v r_i \times \v F_i = \dot{\v L} \\
   \v L &= 0 ~\text{für}~ \v M = 0
   \end{align*}

   Allgemeiner Zusammenhang:
   \begin{align*}
   \intertext{mit $\hat I$ als Tensor:}
   \v L &= \hat I \v \omega \\
   \v L &= \int \d \v L \\
   \d \v L &= \v r \times \d \v p = \v r \times \v v\d m \\
   &= \d m (\v r \times \v v) = \v r \times (\v \omega \times \v r)
   \intertext{mit $\v a \times (\v b \times \v c) = \v b (\v a \v c) - \v c (\v a \v b)$}
   &= \d m(r^2 \v \omega - \v r (\v \omega \v r)) \\
   \int \d \v L &= \v \omega \int r^2 \d m - \int \v r (\v \omega \v r) \d m
   \end{align*}

   #+ATTR_LATEX: :options [Schief gestellte Hantel]
   #+begin_ex latex
   Drehimpuls:
   \[\v L = \v r_1 \times \v p_1 + \v r_2 \times \v p_2\]
   Drehimpulsvektor steht senkrecht auf Verbindungslinie zu $m_1$ und $m_2$.
   Aber: Winkelgeschwindigkeit $\v \omega$ zeigt in Richtung der Drehachse.
   #+end_ex
   #+ATTR_LATEX: :options [Rotierende Scheibe mit Unwucht]
   #+begin_ex latex
   Für Rad mit Masse $M$ gilt: (ohne Unwucht)
   \[\v L_1 = \int \d \v L~\text{parallel zu}~ \v \omega\]
   aus Symmetriegründen, $\v L = I \v \omega$
   Für das Rad plus Unwucht gilt:
   \[\v L = \v L_1 + \v L_2, \v L_2 = \v r \times \underarrow[\v p]{Drehimpuls der Unwucht}\]
   das heißt: $\v L$ nicht parallel zu $\v \omega$, daraus folgt: Drehimpuls hat Komponente senkrecht
   zur Winkelgeschwindigkeit $\v \omega$, diese rotiert mit $\v \omega$
   \[\v M = \dot{\v L}\]
   das heißt auf Achse wirkt Drehmoment.
   #+end_ex
** Trägheitstensor, freie Rotation und Kreisel
   Drehimpuls eines starren Körpers:
   \[\v L = \v \omega \int r^2 \d m - \int \v r (\v \omega \v r) \d m\]
   (Bezugspunkt wichtig!)
   \begin{align*}
   L_x &= \omega_x \int r^2 \d m - \int x (\omega_x + \omega_y y + \omega_z z) \d m \\
   &= \omega_x \int (r^2 - x^2) \d m - \omega_y \int xy \d m - \omega_z \int xz \d m \\
   &= I_{xx} \omega_x + I_{xy} \omega_y + I_{xz} \omega_z \\
   L_y &= I_{yx} \omega_x + I_{yy} \omega_y + I_{yz} \omega_z \\
   L_z &= I_{zx} \omega_x + I_{zy} \omega_y + I_{zz} \omega_z \\
   \v L &= \underbrace{\begin{pmatrix}
   I_{xx} & I_{xy} & I_{xz} \\
   I_{yx} & I_{yy} & I_{yz} \\
   I_{zx} & I_{zy} & I_{zz}
   \end{pmatrix}}_{\text{Trägheitstensor}}
   \begin{pmatrix}
   \omega_x \\
   \omega_y \\
   \omega_z
   \end{pmatrix}
   \end{align*}
   #+ATTR_LATEX: :options [Trägheitstensor]
   #+begin_defn latex
   \begin{align*}
   \v L &= \hat I \v omega, \overarrow[\hat I]{Matrix} = I_{ij} \\
   I_{xx} = \int (r^2 - x^2) \d m \quad I_{xy} = I_{yx} = -\int xy \d m \\
   I_{yy} = \int (r^2 - y^2) \d m \quad I_{yz} = I_{zy} = -\int yz \d m \\
   I_{zz} = \int (r^2 - z^2) \d m \quad I_{xz} = I_{zx} = -\int xz \d m
   \end{align*}
   Rotationsenergie:
   \[E_{rot} = \frac{1}{2} \v \omega^{T} \hat I \v \omega\]
   #+end_defn
   Trägheitstensor $\hat I$ hängt von der Wahl des Koordinatensystems ab! \\
   Geeignete Koordinatentransformation \rightarrow Diagonalisieren von $\hat I$. (Hauptachsentransformation)

   Nach Hauptachsentransformation:
   \[\hat I = \begin{pmatrix} I_a & 0 & 0 \\ 0 & I_b & 0 \\ 0 & 0 & I_c \end{pmatrix}\]
   mit $I_a > I_b > I_c$. \\
   Es folgt: Bei Rotation eines Körpers um eine der drei Hauptachsen sind Drehimpuls und Winkelgeschwindigkeit parallel.

*** Kreisel
	Ein Kreisel ist ein rotierender starrer Körper, der höchstens an einem Punkt aufgehängt ist. (Kompass, Satellit, Geschoss) \\
	Beschreibung der Kreiselbewegung mit 3 Achsen:
	- Figurenachse
	- Momentane Drehachse, Richtung von $\v \omega$
	- Drehimpulsachse
