* Was ist Informatik?
  "Kunst" Aufgaben mit Computerprogrammen zu lösen.
** Teilgebiete
*** theoretische Informatik (*ITH*)
	- Berechenbarkeit: Welche Probleme kann man mit Informatik lösen und welche prinzipiell nicht?
	- Komplexität: Welche Probleme kann man effizient lösen?
	- Korrektheit: Wie beweist man, dass das Ergebnis richtig ist? \\
	  Echtzeit: Dass das richtige Ergebnis rechtzeitig vorliegt.
	- verteilte Systeme: Wie sichert man, dass verteilte Systeme korrekt kommunizieren?
*** technische Informatik (*ITE*)
	- Auf welcher Hardware kann man Programme ausführen, wie baut man dies Hardware?
	- CPU, GPU, RAM, HD, Display, Printer, Networks
*** praktische Informatik
	- Wie entwickelt man Software?
	- Programmiersprachen und Compiler: Wie kommuniziert der Programmierer mit der Hardware?\hfill *IPI*, *IPK*
	- Algorithmen und Datenstrukturen: Wie baut man komplexe Programme aus einfachen Grundbausteinen?\hfill *IAL*
	- Softwaretechnik: Wie organisiert man sehr große Projekte?\hfill *ISW*
	- Kernanwendung der Informatik: Betriebssysteme, Netzwerke, Parallelisierung\hfill *IBN*
	  - Datenbanksysteme\hfill *IDB1*
	  - Graphik, Graphische Benutzerschnittstellen\hfill *ICG1*
	  - Bild- und Datenanalyse
	  - maschinelles Lernen
	  - künstliche Intelligenz
*** angewandte Informatik
	- Wie löst man Probleme aus einem anderem Gebiet mit Programmen?
	- Informationstechnik
	  - Buchhandlung, e-Kommerz, Logistik
	- Web Programmierung
	- scientific computing für Physik, Biologie
	- Medizininformatik
	  - bildgebende Verfahren
	  - digitale Patientenakte
	- Computer Linguistik
	  - Sprachverstehen, automatische Übersetzung
	- Unterhaltung: Spiele, special effects im Film
