#+AUTHOR: Robin Heinemann
#+TITLE: Einführung in die Anwendungsorientierte Informatik (Köthe)
#+OPTIONS: H:6
#+LATEX_CLASS: koma-article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage{siunitx}%
#+LATEX_HEADER: \usepackage{fontspec}%
#+LATEX_HEADER: \sisetup{load-configurations = abbrevations}%
#+LATEX_HEADER: \newcommand{\estimates}{\overset{\scriptscriptstyle\wedge}{=}}%
#+LATEX_HEADER: \usepackage{mathtools}%
#+LATEX_HEADER: \DeclarePairedDelimiter\abs{\lvert}{\rvert}%
#+LATEX_HEADER: \DeclarePairedDelimiter\norm{\lVert}{\rVert}%
#+LATEX_HEADER: \DeclareMathOperator{\Exists}{\exists}%
#+LATEX_HEADER: \DeclareMathOperator{\Forall}{\forall}%
#+LATEX_HEADER: \def\colvec#1{\left(\vcenter{\halign{\hfil$##$\hfil\cr \colvecA#1;;}}\right)}
#+LATEX_HEADER: \def\colvecA#1;{\if;#1;\else #1\cr \expandafter \colvecA \fi}
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage{makecell}
# #+LATEX_HEADER: \usemintedstyle{tango}
#+LATEX_HEADER: \usemintedstyle{perldoc}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{arrows,automata}
#+LATEX_HEADER: \usepackage{tikz-qtree}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlistdepth{20}
#+LATEX_HEADER: \renewlist{itemize}{itemize}{20}
#+LATEX_HEADER: \setlist[itemize]{label=$\cdot$}

# #+BEGIN_SRC cpp
# for(int i = 0; i < 5) {
#    std::cout << i << std::endl;
# }
# #+END_SRC

* Klausur 10.02.2016

* Was ist Informatik?
  "Kunst" Aufgaben mit Computerprogrammen zu lösen.
** Teilgebiete
*** theoretische Informatik (*ITH*)
    - Berechenbarkeit: Welche Probleme kann man mit Informatik lösen und welche prinzipiell nicht?
    - Komplexität: Welche Probleme kann man effizient lösen?
    - Korrektheit: Wie beweist man, dass das Ergebnis richtig ist? \\
      Echtzeit: Dass das richtige Ergebnis rechtzeitig vorliegt.
    - verteilte Systeme: Wie sichert man, dass verteilte Systeme korrekt kommunizieren?
*** technische Informatik (*ITE*)
	- Auf welcher Hardware kann man Programme ausführen, wie baut man dies Hardware?
	- CPU, GPU, RAM, HD, Display, Printer, Networks
*** praktische Informatik
	- Wie entwickelt man Software?
	- Programmiersprachen und Compiler: Wie kommuniziert der Programmierer mit der Hardware?\hfill *IPI*, *IPK*
	- Algorithmen und Datenstrukturen: Wie baut man komplexe Programme aus einfachen Grundbausteinen?\hfill *IAL*
	- Softwaretechnik: Wie organisiert man sehr große Projekte?\hfill *ISW*
	- Kernanwendung der Informatik: Betriebsysteme, Netzwerke, Parallelisierung\hfill *IBN*
	  - Datenbanksysteme\hfill *IDB1*
	  - Graphik, Graphische Benutzerschnittstellen\hfill *ICG1*
	  - Bild- und Datenanalyse
	  - maschinelles Lernen
	  - künstliche Intelligenz
*** angewante Informatik
	- Wie löst man Probleme aus einem anderem Gebiet mit Programmen?
	- Informationstechnik
	  - Buchhandlung, e-commerce, Logistik
	- Web programming
	- scientific computing für Physik, Biologie
	- Medizininformatik
	  - bildgebende Verfahren
	  - digitale Patientenakte
	- computer linguistik
	  - Sprachverstehen, automatische Übersetzung
	- Unterhaltung: Spiele, special effect im Film
* Wie unterscheidet sich Informatik von anderen Disziplinen?
** Mathematik
   Am Beispiel der Definition $a \leq b: \exists c \geq 0: a + c = b$
   Informatik: Lösungsverfahren: $a - b \leq 0$, das kann man leicht ausrechen, wenn man subtrahieren und mit $0$ vergleichen kann.
   Quadratwurzel: $y = \sqrt{x} \Leftrightarrow y \geq 0 \wedge y^2 = x (\Rightarrow x > 0)$
   Informatik: Algorithmus aus der Antike: $y = \frac{x}{y}$
   iteratives Verfahren: Initial Guess $y^{(0)} = 1$
   schrittweise Verbesserung $y^{(t+1)} = \frac{y^{(t)} + \frac{x}{y^{(t)}}}{2}$
* Informatik
  Lösugswege, genauer Algorithmen
** Algorithmus
   *schematische* Vorgehensweise mit der jedes Problem einer bestimmten *Klasse* mit *endliche* vielen *elementaren* Schritten / Operationen gelöst werden kann
   - schematisch: man kann den Algorithmus ausführen, ohne ihn zu verstehen ($\Rightarrow$ Computer)
   - alle Probleme einer Klasse: zum Beispiel: die Wurzel aus jeder beliebigen nicht-negativen Zahl, und nicht nur $\sqrt{11}$
   - endliche viele Schritte: man kommt nach endlicher Zeit zur Lösung
   - elementare Schrite / Operationen: führen die Lösung auf Operationen oder Teilprobleme zurück, die wir schon gelöst haben
** Daten
   Daten sind Symbole,
   - die Entitäten und Eigenschaften der realen Welt im Computer representieren.
   - die interne Zwischenergebnisse eines Algorithmus aufbewahren
   $\Rightarrow$ Algorithmen transformieren nach bestimmten Regeln die Eingangsdaten (gegebene Symbole) in Ausgangsdaten (Symbole für das Ergebniss).
   Die Bedeutung / Interpretation der Symbole ist dem Algorithmus egal $\estimates$ "schematisch"
*** Beispiele für Symbole
	- Zahlen
	- Buchstaben
	- Icons
	- Verkehrszeichen
    aber: heutige Computer verstehen nur Binärzahlen $\Rightarrow$ alles andere muss man übersetzen
	Eingansdaten: "Ereignisse":
	- Symbol von Festplatte lesen oder per Netzwerk empfangen
	- Benutzerinteraktion (Taste, Maus, ...)
	- Sensor übermittelt Meßergebnis, Stoppuhr läuft ab
    Ausgangsdaten: "Aktionen":
	- Symbole auf Festplatte schreiben, per Netzwerk senden
	- Benutzeranzeige (Display, Drucker, Ton)
	- Stoppuhr starten
	- Roboteraktion ausführen (zum Beispiel Bremsassistent)
	Interne Daten:
	- Symbole im Hauptspeicher oder auf Festplatte
	- Stoppuhr starten / Timeout
** Einfachster Computer
   endliche Automaten (endliche Zustandsautomaten)
   - befinden sich zu jedem Zeitpunkt in einem bestimmten Zustand aus einer vordefinierten endlichen Zustandsmenge
   - äußere Ereignisse können Zustandsänderungen bewirken und Aktionen auslösen
*** TODO Graphische Darstellung
	graphische Darstellung: Zustände = Kreise, Zustandsübergänge: Pfeile
*** TODO Darstellung durch Übergangstabellen
	Zeilen: Zustände, Spalten: Ereignisse, Felder: Aktion und Folgezustände
    | Zustände \ Ereignisse | Knopf drücken                                     | Timeout                                                   | Timeout(Variante)                       |
    |-----------------------+---------------------------------------------------+-----------------------------------------------------------+-----------------------------------------|
    | aus                   | \Rightarrow{halb} \\ {4 LEDs an}                 | %                                                         | (\Rightarrow{aus},{nichts})             |
    | halb                  | (\Rightarrow{voll},{8 LEDs an})                   | %                                                         | (\Rightarrow{aus},{nichts})             |
    | voll                  | (\Rightarrow{blinken an},{Timer starten})         | %                                                         | (\Rightarrow{aus},{nichts})             |
    | blinken an            | (\Rightarrow{aus},{Alle LEDs aus, Timer stoppen}) | (\Rightarrow{blinken aus},{alle LEDs aus, Timer starten}) | (\Rightarrow{blinken aus},{8 LEDs aus}) |
    | blinken aus           | (\Rightarrow{aus},{Alle LEDs aus, Timer stoppen}) | (\Rightarrow{blinken an},{alle LEDs an, Timer starten})   | (\Rightarrow{blinken an},{8 LEDs an})   |

	Variante: Timer läuft immer (Signal alle 0.3s) \Rightarrow Timout ignorieren im Zustand "aus", "halb", "voll"
*** Beispiel 2:
	\begin{align}
	&1~0~1~1~0~1~0 &= 2 + 8 + 16 + 74 &= 90_{\text{dez}} \\
	+&0~1~1~1~0~0~1 &= 1 + 8 + 16 + 32 &= 57_{\text{dez}} \\
	\hline
	1~&0~0~1~0~0~1~1 &= 1 + 2 + 16 + 128 &= 147_{\text{dez}}\checkmark
	\end{align}
**** Implementation mit Endlichen Automaten
	 Prinzipen:
	 - wir lesen die Eingangsdaten von rechts nach links
	 - Beide Zahlen gleich lang (sonst mit 0en auffüllen)
	 - Ergebnis wird von rechts nach link ausgegeben
**** TODO Skizze der Automaten
     | Zustand   | Ereignis    | Ausgeben |
     |-----------+-------------+----------|
     | start     | (0,1)       | "1"      |
     | start     | (1,0)       | "1"      |
     | start     | (0,0)       | "0"      |
     | start     | (1,1)       | "0"      |
     | carry = 1 | (1,1)       | "1"      |
     | carry = 1 | (0,1)       | "0"      |
     | carry = 1 | (1.0)       | "0"      |
     | carry = 1 | $\emptyset$ | "1"      |
	 *Wichtig:* In jedem Zustand muss für *alle möglichen* Ereignisse eine Aktion und Folgezustand definiert werden.
	 Vergisst man ein Ereignis zeigt der Automat undefiniertes Verhalten, also ein "Bug"
	 Falls keine sinvolle Reaktion möglich ist: neuer Zustand: "Fehler" \Rightarrow Übergang nach "Fehler", Aktion: ausgeben einer Fehlermeldung
***** TODO Skizze Fehlermeldung
	  Ein endlicher Automat hat nur ein Speicherelement, das den aktuelen Zustand angibt. Folge:
	  - Automat kann sich nicht merken, wie er in den aktuellen Zustand gekommen ist ("kein Gedächnis")
	  - Automat kann nicht beliebig weit zählen, sondern nur bis zu einer vorgegebenen Grenze
\begin{center}
\begin{tikzpicture}[->,>=stealth',shorten >=1pt,auto,node distance=2.8cm, semithick]
\node[initial,state] (0) {"0"};
\node[state] (1) [right of=0] {"1"};
\node[state] (2) [right of=1]{"2"};
\node[state] (3) [right of=2]{"3"};
\node[accepting,state] [below of=1] (end) {"stop"};
\path (0) edge [loop above] node {"0"} (0)
(0) edge node {"x"} (1)
(0) edge node {$\emptyset$} (end)
(1) edge [loop above] node {"0"} (1)
(1) edge node {"x"} (2)
(1) edge node {$\emptyset$} (end)
(2) edge [loop above] node {"0"} (2)
(2) edge node {"x"} (3)
(2) edge node {$\emptyset$} (end)
(3) edge [loop above] node {"$0\vee x$"} (3)
(3) edge node {"x"} (3)
(3) edge node {$\emptyset$} (end);
\end{tikzpicture}
\end{center}
      Insgesamt: Man kann mit endlichen Automaten nur relativ einfache Algorithmen implementieren. (nur reguläre Sprachen)
	  Spendiert man zusätzlichen Specher, geht mehr:
	  - Automat mit Stak-Speicher (Stapel oder Keller) \Rightarrow Kellerautomat (Kontextfreie Sprachen)
	  - Automat mit zwei Stacks oder äquivalent Turing-Maschine kann alles auführen, was man intuitiv für berechenbar hält
      Markov Modelle: endliche Automaten mit probabilistischen Übergangen.
	  Bisher: Algorithmen für einen bestimmten Zweck (Problemklasse)
	  Frage: Gibt es einen universellen Algorithms für alle berechenbare Probleme?
	  Betrache formale Algorithmusbeschribung als Teil der Eingabe des universellen Algorithmus.
* Substitutionsmodell (funktionale Programmierung)
  - einfaches Modell für arithmetische Berechnung "Taschenrechner"
  - Eingaben und Ausgaben sind Zahlen (ganze oder reelle Zahlen). Zahlenkonstanten heißten "Literale"
  - elementare Funktionen: haben eine oder mehere Zahlen als Argumente (Parameter) und liefern eine Zahl als Ergebnis (wie Mathematik):
	- add(1,2) \rightarrow 3, mul(2,3) \rightarrow 6, analog sub(), div(), mod()
  - Funktionsaufrufe können verschachtelt werden, das heißt Argumente kann Ergebnis einer anderen Funktion sein
	- mul(add(1,2),sub(5,3)) \rightarrow 6
** Substitutionsmodell
   Man kann einen Funktionsaufruf, deessen Argument vekannt ist (das heißt Zahlen sind) durch den Wert des Ergebnisses ersetzen ("substituieren"). Geschachtelte Ausdrücke lassen sich so von innen nach außen auswerten.
   \[mul(add(1,2),sub(5,3))\]
   \[mul(3,sub(5,3))\]
   \[mul(3,2)\]
   \[6\]
   - Die arithmetischen Operationene add(), sub(), mul(), div(), mod() werden normalerweise von der Hardware implementiert.
   - Die meisten Programmiersprachen bieten außerdem algebraische Funktionen wie: sqrt(), sin(), cos(), log()
	 - sind meist nicht in Hardware, aber vorgefertigte Algorithmen, werden mit Programmiersprachen geliefert, "Standardbibilothek"
   - in C++: mathematisches Modul des Standardbibilothek: "cmath"
   - Für Arithmetik gebräuchlicher ist "Infix-Notation" mit Operator-Symbolen "+", "-", "*", "/", "%"
   - mul(add(1,2),sub(5,3)) \Leftrightarrow ((1+2)*(5-3))
	 - oft besser, unter anderem weil man Klammer weglassen darf
	   1. "Punkt vor Strichrechnung" 3+4*5 \Leftrightarrow 3+(4*5), mul, div, mod binden stärker als add,sub
	   2. Operatoren gleicher Präzedenz werden von links nach rechts ausgeführt (links-assoziativ) \\
		  1+2+3-4+5 \Leftrightarrow ((((1+2)+3)-4)+5)
	   3. äußere Klammer kann man weglassen (1+2)\Leftrightarrow 1+2
   - Computer wandeln Infix zuerst in Prefix Notation um
	 1. weggelassene Klammer weider einfüger
	 2. Operatorensymbol durch Funktionsnamen ersetzen und an Prefix-Position verschieben
		\[1 + 2 + 3 * 4 / (1 + 5) - 2\]
		\[(((1 + 2) + ((3 * 4) / (1 + 5))) - 2)\]
		\[sub(add(add(1,2),div(mul(3,4),add(1,5))), 2)\]
		\[sub(add(3,div(12,6)), 2)\]
		\[sub(add(3,2), 2)\]
		\[sub(5, 2)\]
		\[2\]
** Bäume
   - bestehen aus Knoten unmd Kanten (Kreise und Pfeile)
   - Kanten verbinden Knoten mit ihren Kind-knoten
   - jeder Koten (außer der Wurzel) hat genau ein Elternteil ("parent node")
   - Knoten ohne Kinder heißen Blätter ("leaves / leaf node")
   - Teilbaum
	 - wähle beliebigen Knoten
	 - entferne temporärdessen Elternkante, dadurch wird der Knoten temporär zu einer Wurzel, dieser Knoten mit allen Nachkommen bildet wieder einen Baum (Tailbaum des Orginalbaumes)
   - trivialer Teilbaum hat nur einen Knoten
   - Tiefe: Abstand eines Knotens von der Wurzel (Anzahl der Kanten zwischen Knoten und Wurzel)
	 - Tiefe des Baums: maximale Tiefe eines Knoten
*** Beispiel
	\[1 + 2 + 3 * 4 / (1 + 5) - 2\]
	\[sub(add(add(1,2),div(mul(3,4),add(1,5))), 2)\]
	\begin{center}
	\Tree [ .sub [ .add [ .add 1 2 ] [ .div [ .mul 3 4 ] [ .add 1 5 ] ] ] 2 ]
	\end{center}
** Rekursion
   Rekursiv $\estimates$ Algorithmus für Teilproblem von vorn.
** Prefixnotation aus dem Baum rekonstruieren
   1. <<algstart1>> Wenn die Wurzel ein Blatt ist: Drucke die Zahl
   2. sonst:
	  - Drucke Funktionsnamen
	  - Drucke "("
	  - Wiederhole den Algorithmus ab [[algstart1]] für das linke Kind (Teilbaum mit Wurzel = linkes Kind)
	  - Drucke ","
	  - Wiederhole den Algorithmus ab [[algstart1]] für das rechte Kind (Teilbaum mit Wurzel = rechtes Kind)
	  - Drucke ")"
	\Rightarrow \[sub(add(add(1,2),div(mul(3,4),add(1,5))), 2)\]
** Prefixnotation aus dem Baum rekonstruieren
   1. <<algstart2>> Wenn die Wurzel ein Blatt ist: Drucke die Zahl
   2. sonst:
	  - Drucke Funktionsnamen
	  - Drucke "("
	  - Wiederhole den Algorithmus ab [[algstart2]] für das linke Kind (Teilbaum mit Wurzel = linkes Kind)
	  - Drucke Operatorsymbol
	  - Wiederhole den Algorithmus ab [[algstart2]] für das rechte Kind (Teilbaum mit Wurzel = rechtes Kind)
	  - Drucke ")"
	\Rightarrow \[sub(add(add(1,2),div(mul(3,4),add(1,5))), 2)\]
   \Rightarrow *inorder*
** Berechnen des Werts mit Substitutionsmethode
   1. <<algstart3>> Wenn Wurzel dein Blatt gib Zahl zurück
   2. sonst:
	  - Wiederhole den Algorithmus ab [[algstart3]] für das linkes Kind (Teilbaum mit Wurzel = rechtes Kind), speichere Ergebnis als "lhs"
	  - Wiederhole den Algorithmus ab [[algstart3]] für das rechte Kind (Teilbaum mit Wurzel = rechtes Kind), speichere Ergebnis als "rhs"
	  - berechne funktionsname(lhs,rhs) und gebe das Ergebnis zurück
   \Rightarrow *postorder*
* Maschienensprachen
  - optimiert für die Hardware
  - Gegensatz: höhere Programmiersprachen (c++)
	- optimiert für Programmierer
  - Compiler oder Interpreter übersetzen Hoch- in Maschienensprache
** Umwandlung in Maschienensprache
  1. Eingaben und (Zwischen) Ergebnisse werden in Speicherzellen abgespeichert \Rightarrow jeder Knoten im Baum bekommt eine Speicherzelle
  2. Speicherzellen für Eingaben initialisieren
	 - Notation: SpZ \leftarrow Wert
  3. Rechenoperationen in Reihenfolge des Substitutionsmodell ausführen und in der jeweiligen Speicherzelle speichern
	 - Notation: SpZ-Ergebniss \leftarrow fname SpZArg1 SpZArg2
  4. alles in Zahlencode umwandeln
	 - Funktionsnamen:
	   | Opcode | Wert |
	   |--------+------|
	   | init   | 1    |
	   | add    | 2    |
	   | sub    | 3    |
	   | mul    | 4    |
	   | div    | 5    |
* Funktionale Programmierung
  - bei Maschienensprache wreden Zweischeergebnisse in Speicherzellen abgelegt
  - das ist auch in der funktionalen Programmierung eine gute Idee
  - Speicherzellen werden duch Namen (vom Programmierer vergeben) unterschieden
** Beispiel
   Lösen einer quadratischen Gleichung:
   \[ax^2 + bx + c = 0\]
   \[x^2 - 2px + q = 0, p = -\frac{b}{2a},q=\frac{c}{d}\]
   \[x_2 = p + \sqrt{p^2 - q},x_2 = p - \sqrt{p^2 - q}\]
   ohne Zwischenergebnisse:
   \[x_1 \leftarrow add(div(div(b,a),-2),sqrt(sub(mul(div(b,a),-2),div(div(b,a)-1)),div(c,a)))\]
   mit Zwischenergebniss und Infix Notation
   \[p\leftarrow b / c / -2~\text{oder}~p\leftarrow -0.5 * b / a\]
   \[a\leftarrow c / a\]
   \[d\leftarrow sqrt(p*p - q)\]
   \[x_1\leftarrow p + d\]
   \[x_2\leftarrow p - d\]
** Vorteile von Zwischenergebnissen
   1. lesabrer
   2. redundante Berechnung vermieden. Beachte: In der funktionalen Programmierung können die Speicherzellen nach der initialisierung nicht mehr verändert werden
   3. Speicherzellen und Namen sind nützlich um Argumente an Fuktionen zu übergeben \Rightarrow Definition eigener Funktionen
	  #+BEGIN_SRC cpp
	  function sq(x) {
		 return x * x
	  }
	  #+END_SRC
	  \Rightarrow $d \leftarrow sqrt(sq(p) - q)$
	  Speicherzelle mit Namen "x" für das Argument von $sq$
** Funktionale Programmierung in c++
   - in c++ hat jede Speicherzelle einen Typ (legt Größe und Bedeutung der Speicherzelle fest)
	 - wichtige Typen
	   | int         | ganze Zahlen  |
	   | double      | reelle Zahlen |
	   | std::string | Text          |
	   int: $12,-3$ \\
	   double: $-1.02,1.2e-4 = 1.2*10^{-4}$ \\
	   std::string: "text"
   - Initialisierung wird geschrieben als "typename spzname = Wert;"
	 #+BEGIN_SRC cpp
	 double a = ...;
	 double b = ...;
	 double c = ...;
	 double p = -0.5 b / a;
	 double q = c / a;
	 double d = std::sqrt(p*p - q);
	 double x1 = p + d;
	 double x2 = p - d;
	 std::cout << "x1: " << x1 << ", x2: " << x2 << std::endl;
	 #+END_SRC
   - eigene Funktionen in C++
	 #+BEGIN_SRC cpp
	 // Kommentar (auch /* */)
	 type_ergebnis fname(type_arg1 name1, ...) { // Signatur / Funkitonskopf / Deklaration
		 return ergebnis;                        /* Funktionskörper / Definition / Implementation */
	 }
	 #+END_SRC
	 - ganze Zahl quadrieren:
	   #+BEGIN_SRC cpp
	   int sq(int x) {
		   return x*x;
	   }
	   #+END_SRC
	 - reelle zahl quadrieren:
	   #+BEGIN_SRC cpp
	   double sq(double x) {
		   return x*x;
	   }
	   #+END_SRC
	 - beide Varianten dürfen in c++ gleichzeitig definiert sein \Rightarrow "function overloading" \Rightarrow c++ wählt automatisch die richtig Variable anhand des Argumenttypes ("overload resolution")
	   #+BEGIN_SRC cpp
	   int x = 2;
	   double y = 1.1
	   int x2 = sq(x) // int Variante
	   double y2 = sq(y) // double Variante
	   #+END_SRC
	 - jedes c++-Programm muss genau eine Funktion names "main" haben. Dort beginnt die Programmausführung.
	   #+BEGIN_SRC cpp
	   int main() {
		   Code;
		   return 0;
	   }
	   #+END_SRC
	   - return aus der "main" Funktion ist optional
	 - Regel von c++ für erlaubte Name
	   - erstes Zeichen: Klein- oder Großbuchstaben des englischen Alphabets, oder "_"
	   - optional: weitere Zeichen oder, "_" oder Ziffer 0-9
	 - vordefinierte Funktionen:
	   - eingebaute $\estimates$ immer vorhanden
		 - Infix-Operatoren $+,-,*,/,\%$
		 - Prefix-Operatoren $operator+,operator-,\ldots$
	   - Funktion der Standardbibilothek $\estimates$ müssen "angefordert" werden
		 - Namen beginnen mit "std::", "std::sin,..."
		 - sind in Module geordnet, zum Beispiel
		   - cmath \Rightarrow algebraische Funktion
		   - complex \Rightarrow komplexe Zahlen
		   - string \Rightarrow Zeichenkettenverarbeitung
		 - um ein Modul zu benutzen muss man zuerst (am Anfang des Programms) sein Inhaltsverzeichnis importieren (Header includieren) \rightarrow #include <name>
		   #+BEGIN_SRC cpp
		   #include <iostream>
		   #include <string>
		   int main() {
			   std::cout << "Hello, world!" << std::endl;
			   std::string out = "mein erstes Programm\n";
			   std::cout << out;
			   return 0;
		   }
		   #+END_SRC
	 - overloading der arithmetischen Operationene
	   - overloading genau wie bei $sq$
		 - 3 * 4 \Rightarrow int Variante
		 - 3.0 * 4.0 \Rightarrow double Variante
		 - 3 * 4.0 \Rightarrow automatische Umwandliung in höheren Typ, hier "double" \Rightarrow wird als 3.0 * 4.0 ausgeführt
	 - \Rightarrow Devision unterscheidet sich
	   - Integer-Division: 12 / 5 = 2 (wird abgerundet)
	   - Double-Division: 12.0 / 5.0 = 2.4
	   - -12 / 5 = 2 (\Rightarrow truncated Division)
	   - 12.0 / 5.0 = 2.4
	   - Gegensatz (zum Beispiel in Python)
		 - floor division \Rightarrow wird immer abgerundet \Rightarrow -12 / 4 = -2
